executor/executor_test.go
plan/newplanbuilder.go

e.g. select *, 1+a, sum(a) from src group by 1.

process wildcard correctly.

---

store/tikv/lock.go
store/tikv/lock_test.go
store/tikv/region_cache_test.go
store/tikv/snapshot_test.go
store/tikv/ticlient_test.go
store/tikv/txn.go
store/tikv/txn_committer_test.go

store/tikv: cleanup tests, reduce tests time.

---

executor/builder.go
executor/executor_test.go
executor/new_builder.go
executor/new_executor.go
plan/column_pruning.go
plan/new_plans.go
plan/newplanbuilder.go
plan/predicate_push_down.go
plan/stringer.go

@shenli @coocood @zimulala  PTAL

support union and distinct in new plan.

---

store/tikv/client.go
store/tikv/client_test.go

store/tikv: conn should be closed if error occurs.

---

store/tikv/client_test.go

store/tikv: fix CI failure.

---

ast/functions.go
evaluator/builtin.go
evaluator/builtin_other.go
executor/executor_test.go
executor/new_builder.go
expression/expression.go
plan/expression_rewriter.go
plan/new_plan_test.go
plan/newplanbuilder.go

e.g. select * from src where (a, b) = (1, 1)

support row expression.

---

ddl/column.go
ddl/column_test.go
ddl/ddl_db_test.go
ddl/index.go
executor/compiler.go
executor/executor_test.go
executor/executor_write.go
inspectkv/inspectkv.go
inspectkv/inspectkv_test.go
plan/new_plan_test.go
plan/newplanbuilder.go
plan/resolver.go
sessionctx/variable/session.go
store/localstore/local_client.go
store/localstore/local_region.go
store/localstore/xapi_test.go
store/tikv/mock-tikv/cop_handler.go
table/table.go
table/tables/bounded_tables.go
table/tables/memory_tables.go
table/tables/tables.go
table/tables/tables_test.go
tablecodec/tablecodec.go
tablecodec/tablecodec_test.go
util/codec/codec.go
util/codec/codec_test.go
util/codec/decimal.go

Store row data in single kv pair

---

table/tables/tables.go

The test cover this issue need some work, will be added in next PR.

table/table: set default value when write only column is null

---

table/tables/tables.go

It shadows the outside err.
@coocood @zimulala

tables: Fix shadowed err

---

docs/QUICKSTART.md
kv/error.go

*: Remove hbase related doc and comment

---

table/table.go
table/tables/bounded_tables.go
table/tables/memory_tables.go
table/tables/tables.go

`WritableCols` will be used in ddl_test and in executor for update multiple table.

table: export `WritableCols`

---

executor/new_builder.go
plan/column_pruning.go
plan/expression_rewriter.go
plan/new_plan_test.go
plan/new_plans.go
plan/newplanbuilder.go
plan/optimizer.go
plan/plan.go
plan/planbuilder.go
plan/plans.go
plan/predicate_push_down.go

Finally, the plan will be specified to LogicalPlan and physical plan. This patch implements logic plan first.
@shenli @coocood @zimulala  PTAL

implement logical plan.

---

README.md

Fix: https://github.com/pingcap/tidb/issues/1382

*: Fix license link

---

README.md

readme: Tiny clean up

---

perfschema/perfschema.go
perfschema/perfschema_test.go
perfschema/statement.go
perfschema/statement_test.go
tidb-server/main.go

Add a switch for perfschema

---

table/tables/tables.go
terror/terror.go
terror/terror_test.go

terror: Improve terror performance.

---

ddl/bg_worker_test.go

Or the job may not have done, test may fail.

ddl: increase ddl test sleep time.

---

parser/parser.y
parser/parser_test.go
parser/scanner.l

Add missing syntax rule.
@coocood @zimulala

*: Support grant all privileges syntax

---

ast/ddl.go
parser/parser.y
parser/parser_test.go
parser/scanner.l

Parsed but ignored. Just prevent error.
@coocood @zimulala

*: Support STATS_PERSISTENT option in CreateTableStmt

---

ast/misc.go
executor/executor_simple.go
parser/parser.y
parser/parser_test.go
perfschema/statement.go
plan/planbuilder.go

"set @@session.sql_mode=1, names utf8, charset utf8;" is a valid sql statement.
Fix: https://github.com/pingcap/tidb/issues/1421
@coocood @zimulala

*: Remove SetCharsetStmt, use SetStmt instead

---

executor/new_executor.go

Fix go vet error mentioned in issue: https://github.com/pingcap/tidb/issues/1421
@coocood @zimulala PTAL
@ziyouchutuwenwu Have tested this branch on his machine.

Make go vet happy

---

store/tikv/kv.go

store/tikv: remove radundant Mutex.

---

store/localstore/local_aggregate.go

Address comment. See: https://github.com/pingcap/tidb/pull/1409/files#r70207782
@BusyJay @coocood

localstore: Check argument length for sum function.

---

bootstrap.go

Make mycli happy. Fix: https://github.com/pingcap/tidb/issues/1436
@zimulala @coocood

*: add empty help_topic table

---

plan/resolver.go

I would prefer to change RecordSet interface to return
slice of values, rather than slice of pointers.
But change an interface involve too many changes.

*: tiny clean up

---

executor/aggregate_xapi.go
executor/aggregate_xapi_test.go
store/localstore/local_aggregate.go
store/localstore/local_client.go

@coocood @zimulala PTAL
@BusyJay

*: Support avg for localstore xapi

---

executor/new_executor_xapi.go
plan/column_pruning.go
plan/expression_rewriter.go

@coocood @zimulala @shenli 
just make code more clear.

refine code

---

store/tikv/mock-tikv/cluster.go
store/tikv/mock-tikv/pd.go
store/tikv/pd_codec.go
store/tikv/region_cache.go
store/tikv/region_cache_test.go

store/tikv: update pd.GetRegion().

---

interpreter/main.go
tidb-server/main.go

@coocood @hanfei19910905  PTAL

*: Add switch for newplanner

---

executor/builder.go
executor/new_builder.go
executor/new_executor.go
plan/column_pruning.go
plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/logical_plans.go
plan/new_plan_test.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/predicate_push_down.go

@coocood @shenli @zimulala PTAL

support semi-join for exists.

---

executor/executor_simple.go
session.go
tidb.go

@ngaut @coocood 
Rollback Statement, Session Close, Retry

*: Add reason log for rollback txn

---

executor/executor_test.go
executor/new_executor_xapi.go

@coocood @shenli @zimulala PTAL

fix a bug that select null from a index table.

---

executor/builder.go
executor/executor.go
plan/logical_plan_builder.go
plan/physical_plan_builder.go
plan/plan.go
plan/planbuilder.go
plan/plans.go
plan/predicate_push_down.go
session_test.go

support select lock for new plan.
@coocood @shenli @zimulala PTAL

support select lock.

---

plan/new_plan_test.go
plan/predicate_push_down.go

fix bug about aggr ppd.

---

executor/adapter.go

@coocood @shenli @zimulala PTAL

fix bug of interpreter.

---

ast/misc.go
executor/executor_simple.go
parser/parser.y
parser/parser_test.go
parser/scanner.l
plan/planbuilder.go

Parse and ingore it.
See: http://dev.mysql.com/doc/refman/5.7/en/binlog.html
@coocood @zimulala @tiancaiamao PTAL

*: Support binlog stmt

---

executor/aggregate_xapi.go
executor/new_builder.go
executor/new_executor.go
executor/new_executor_xapi.go
expression/aggregation.go
plan/logical_plan_builder.go
store/localstore/local_region.go
store/tikv/mock-tikv/aggregate.go
store/tikv/mock-tikv/cop_handler.go

Support aggregate push down in new executor

---

store/tikv/coprocessor.go

tikv: Enable xapi for avg/max/min

---

executor/new_executor_xapi.go

Implement NewXExecutor interface for NewXSelectIndexExec.
@coocood @hanfei19910905 PTAL

executor: Support aggregate push down in new index scan executor

---

ast/functions.go
ast/functions_test.go
evaluator/evaluator_test.go
executor/aggregate_xapi.go
executor/executor.go
expression/aggregation.go

*: aggregate related code cleanup

---

.travis.yml

@coocood @zimulala @tiancaiamao

travis: Add go1.7rc3

---

ast/functions.go
ast/functions_test.go
evaluator/evaluator.go
executor/aggregate_xapi.go
expression/aggregation.go
util/types/helper.go

Use datum instead of interface for aggregate calculation.
@coocood @zimulala @BusyJay PTAL

*: Change ctx.Value from interface{} to Datum

---

util/types/helper.go

The test case is in mysql-test.
@coocood @zimulala PTAL

types: Fix bug for CalculateSum

---

mysql/mydecimal.go
mysql/mydecimal_test.go
mysql/util.go

This PR only includes necessary method to make `FromString` method work. Which is used to write unit test.
More methods and test cases will be added in the following PR.
ported from 
https://github.com/mysql/mysql-server/blob/5.7/strings/decimal.c

mysql: add MyDecimal data type.

---

_vendor/Godeps/Godeps.json
_vendor/vendor/github.com/cloudfoundry-incubator/candiedyaml/README.md

resolve merge conflict in Godeps.json

*: fix _vendor/Godeps/Godeps.json

---

evaluator/builtin.go
evaluator/builtin_string.go
evaluator/builtin_string_test.go
evaluator/builtin_test.go
parser/parser.y
parser/parser_test.go
parser/scanner.l
plan/typeinferer.go
plan/typeinferer_test.go

add builtin function hex

---

.gitignore
Dockerfile
Makefile
docs/QUICKSTART.md

Make: Change make server to make, Change make to make dev

---

Makefile

@BusyJay @coocood @siddontang @qiuyesuifeng PTAL

Makefile: Add default task

---

Makefile
ddl/column_test.go
executor/new_executor_xapi.go
privilege/privileges/privileges_test.go
store/tikv/coprocessor.go
store/tikv/txn_committer.go

*: Pass make race

---

.travis.yml

travis： Change CI build cmd

---

plan/match_property.go
plan/new_plan_test.go
plan/physical_plan_builder.go

@hanfei19910905 @coocood @shenli PTAL

plan: Fix convert to physical plan, when there are multiple index ranges

---

parser/scanner.l
parser/yy_parser.go

the old lexer and the new lexer can both use those code

parser: move lexer's int/float/hex method to function

---

executor/new_executor_xapi.go

@hanfei19910905 @coocood @zimulala PTAL
It is a serious bug. I have tested it on TiKV. Test cases will be added in the future PR.

executor: Fix limit bugs in new xapi executor

---

executor/executor_test.go
store/tikv/isolation_test.go
store/tikv/kv.go
store/tikv/lock.go
store/tikv/lock_test.go
store/tikv/oracle/oracle.go
store/tikv/oracle/oracles/local.go
store/tikv/oracle/oracles/local_test.go
store/tikv/oracle/oracles/pd.go
store/tikv/scan_mock_test.go
store/tikv/split_test.go
store/tikv/store_test.go
store/tikv/ticlient_test.go
store/tikv/txn_committer_test.go

store/tikv: mantain lastTS in pd oracle.

---

evaluator/builtin.go
expression/expression.go
plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/new_plan_test.go

add constant folding

---

executor/executor_test.go
executor/new_builder.go
executor/new_executor_xapi.go
plan/match_property.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/statistics/statistics.go
tablecodec/tablecodec.go

when the sql stmt only requires index columns, we can only read index one time.
@coocood @shenli @zimulala @tiancaiamao @XuHuaiyu PTAL

support single index read.

---

expression/expression.go
plan/expression_rewriter.go

Now it can be faster than old plan for simple query.
@coocood @shenli @zimulala @XuHuaiyu @tiancaiamao PTAL

add arguments buffer to avoid making new slice frequently.

---

tidb-server/main.go

@ngaut @coocood @tiancaiamao @zimulala PTAL

tidb-server: Change some int flag to bool

---

plan/physical_plan_builder.go

@hanfei19910905 @coocood @shenli PTAL

plan: Fix cost bug when the range high value is equal to the max value

---

plan/logical_plan_builder.go
plan/optimizer.go
session_test.go

for query, select (1), (1+1);
each column name should be 1, and (1+1) 
@coocood @shenli @zimulala @tiancaiamao @XuHuaiyu

correct column names.

---

plan/optimizer.go

let update/delete do old logicOptimize

---

_vendor/Godeps/Godeps.json
_vendor/vendor/github.com/pingcap/pd/pd-client/rpc_worker.go

@coocood @huachaohuang @qiuyesuifeng PTAL

vendor: Update pd vendor

---

bootstrap.go

modify comment systemt to system

modify comment systemt to system

---

tidb-server/main.go
util/printer/printer.go

@coocood @siddontang @qiuyesuifeng PTAL
#1559

*: Add --log-file flag to set log file path

---

Makefile

as @coocood suggested, we'd better not install a binary on user's GOPATH

*: change Makefile goyacc to go build

---

_vendor/Godeps/Godeps.json
_vendor/vendor/github.com/ngaut/log/log.go

vendor: Update log repo

---

parser/lexer.go
parser/scanner_test.go

refact a function `scanString`, make the code clean, and more efficient

refact scan string

---

parser/lexer.go
parser/scanner_test.go

fix \`numeric\` recognised as numericType in new lexer

parser: fix a lex bug

---

.gitignore
Makefile

fix last PR...if parser/scanner.go exists, build would fail...

*: remove scanner.go from gitignore

---

xapi/xapi.go

@coocood @tiancaiamao @zimulala PTAL

*: Use gogo Marshal/Unmarshal

---

store/tikv/gc_worker.go

Quit the loop when get quit singnal

---

store/tikv/client.go

store/tikv: make i/o timeout longer.

---

plan/physical_plan_builder.go
tidb-server/main.go

@shenli @coocood @zimulala @tiancaiamao @XuHuaiyu PTAL

add flag for setting join concurrency.

---

.travis.yml
Makefile
plan/logical_plan_builder.go
util/types/datum.go

remove travis 1.5.3,
makes check run faster.
gofmt writes file.

*: cleanup Makefile

---

store/tikv/lock_test.go
store/tikv/snapshot.go

store/tikv: fix 'BatchGet' send empty key issue, complement tests.

---

executor/executor_test.go
store/tikv/coprocessor.go

Those functions returns Decimal result and new Decimal has not been supported yet.

store/tikv: turn-off 'Sum' and 'Avg'.

---

executor/executor_xapi.go
store/localstore/local_aggregate.go
store/tikv/coprocessor.go
store/tikv/mock-tikv/aggregate.go

Also fix a bug about evaluating `first` aggregation function, that `first` should be the first not null value rather than first value.

store/tikv: turn on Decimal, Avg, Sum switch and fix `First` function

---

executor/show.go
executor/show_test.go

*: Fix bug in show index for PkIsHandle

---

evaluator/builtin.go
evaluator/builtin_math.go
evaluator/builtin_math_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go

*: Support ceil() and ceiling()

---

evaluator/builtin_other.go
evaluator/evaluator.go
evaluator/evaluator_binop.go
evaluator/evaluator_test.go
util/types/datum.go
util/types/datum_test.go
xapi/xeval/eval.go

*: do not coerce int and uint to uint

---

evaluator/builtin.go
evaluator/builtin_string.go
evaluator/builtin_string_test.go
executor/executor_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go
plan/typeinferer_test.go

More details refer to http://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_unhex
@zimulala @shenli @coocood @XuHuaiyu @tiancaiamao PTAL

support unhex.

---

benchkv/main.go

@ngaut @siddontang @tiancaiamao @coocood  PTAL

benchkv: Make value size configurable

---

benchkv/main.go

benchkv: just register metrics handler

---

store/tikv/coprocessor.go
store/tikv/coprocessor_test.go

store/tikv: speed up buildTask().

---

executor/show.go
executor/show_test.go

*: fix show create table bug

---

ddl/column_change_test.go
ddl/column_test.go
util/sqlexec/restricted_sql_executor.go

Slightly improves go report card score.

fix typo and ineffassign

---

plan/plan_test.go
plan/predicate_push_down.go

fix bug in constant propagation

---

parser/misc.go
parser/parser.y
parser/parser_test.go

Parsed but do nothing. Just make workbench happy.
@tiancaiamao @coocood @zimulala PTAL

parser: Support show function status grammar

---

executor/aggregate_test.go
executor/executor.go
executor/executor_test.go
expression/aggregation.go
plan/column_pruning.go

I will split #1686 into multiple small prs. This pr only implents stream agg executor.
@zimulala @coocood @shenli @tiancaiamao @XuHuaiyu  PTAL

add stream agg executor.

---

store/tikv/backoff.go
store/tikv/coprocessor.go
store/tikv/kv.go
store/tikv/store_test.go

@zimulala @coocood @shenli 
Ref: https://github.com/pingcap/tikv/pull/1054

store/tikv: backoff and retry for 'ServerIsBusy'.

---

Makefile

Makefile: Move benchkv from default to dev

---

meta/meta.go
meta/meta_test.go
structure/hash.go
structure/list.go
structure/string.go
structure/structure.go
structure/structure_test.go

Snapshot meta will be used to load history schema, so we can
support history read with changed schema version.

meta, structure: support snapshot meta.

---

store/tikv/oracle/oracle.go
store/tikv/oracle/oracles/local.go
store/tikv/oracle/oracles/pd.go

PTAL @shenli @zimulala @coocood @tiancaiamao

oracle: export some timestamp calculation functions.

---

store/tikv/coprocessor.go

coprosssor: do not share backoffer by tasks.

---

store/tikv/coprocessor.go
store/tikv/kv.go
store/tikv/metrics.go

store/tikv: add metrics for RegionError.

---

executor/aggregate_test.go

Add a test to avoid calling addAggregation multiple times.

---

executor/executor_distsql.go

The logic has been moved to plan.

executor: remove aggregate and limit push down functions.

---

store/tikv/store_test.go

store/tikv: fix a data race.

---

server/conn.go

fixes https://github.com/pingcap/tidb/issues/1810

server: fix connection string collation

---

executor/executor_test.go
plan/physical_plan_builder.go

If a function exists in order by lists, it shouldn't push down anything. But we pushed a single limit into table scan , which may cause a bug about correctness. This PR fixes it.
@coocood @shenli @zimulala @tiancaiamao @XuHuaiyu

plan: fix a topn bug

---

plan/physical_plan_builder.go
plan/plan.go

@shenli @coocood Please take a look. Thanks

plan: make some editorial changes to the comments

---

README.md

[doc]: add Chinese doc reference

---

store/tikv/coprocessor.go
store/tikv/txn_committer.go

Add and update some logs for error handling.
@zimulala @coocood @tiancaiamao PTAL

store/tikv: add/update some logs.

---

util/printer/printer.go

printer: Remove 'the'

---

ddl/ddl_db_test.go
ddl/ddl_worker.go
ddl/index.go
model/ddl.go

ddl: Cancel DDL job when the key is exist

---

_vendor/src/github.com/pingcap/pd/pd-client/client.go
_vendor/src/github.com/pingcap/pd/pd-client/metrics.go
glide.lock
glide.yaml

vendor: update pd-client

---

infoschema/builder.go
infoschema/infoschema_test.go

infoschema: checks if DBInfo read from Meta is nil.

---

parser/misc.go
parser/parser.y
parser/parser_test.go

Fix: https://github.com/pingcap/tidb/issues/1849
@zimulala @coocood @tiancaiamao PTAL

parser: Support show index in tbl

---

ddl/ddl_worker.go
ddl/ddl_worker_test.go

ddl: Add a time limit to check owner

---

ddl/ddl_worker.go

ddl: Fix metrics bug

---

executor/executor_test.go
plan/optimizer.go
tidb-server/main.go

As the title, cartesian product is condisered very dangerous. We forbid it defaultly.
PTAL
@shenli @coocood @zimulala @tiancaiamao

*: add a flag to restrict cartesian product.

---

ddl/column_test.go
ddl/ddl_test.go
ddl/ddl_worker_test.go
ddl/schema_test.go
ddl/table_test.go

In order to read and maintain test easily.

ddl: Remove useless code and adjust test position

---

executor/explain_test.go
expression/aggregation.go
plan/physical_plans.go
plan/planbuilder.go

The explain result becomes more precise.
@coocood @shenli @zimulala @tiancaiamao @XuHuaiyu PTAL

*: support explain aggregation query.

---

store/tikv/gc_worker.go

So we can control when to trigger GC during performance test.

store/tikv: export DoGC method of GCWorker for testing purpose.

---

executor/show.go
executor/show_test.go

Fixes issue https://github.com/pingcap/tidb/issues/1904

executor: show original identifier instead of lower case.

---

ast/dml.go
executor/show.go
executor/show_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/resolver.go

@coocood @zimulala @hanfei1991  PTAL
See: http://dev.mysql.com/doc/refman/5.7/en/processlist-table.html

*: Support Show processlist

---

domain/domain.go
domain/domain_test.go
executor/executor_test.go
executor/executor_write_test.go

A store should has only one domain, and it is already created when create a session.
we should not manually create domain.

executor: avoid create new domain in test.

---

ast/dml.go
executor/show.go
executor/show_test.go
parser/parser.y
plan/resolver.go

We could run mydumper on TiDB now.
Fix: https://github.com/pingcap/tidb/issues/1851
See: http://dev.mysql.com/doc/refman/5.7/en/show-create-database.html

Support show create db

---

sessionctx/binloginfo/binloginfo_test.go

The commit binlog is written in background goroutine, we need to wait for some time to get it.
Sleeping 1ms may not long enough, so the test case occasionally fails.

sessionctx/binloginfo: fix test.

---

executor/show.go
executor/show_test.go

Fix https://github.com/pingcap/tidb/issues/1918
@coocood @tiancaiamao @zimulala PTAL

*: Fix bug in show create table

---

executor/executor_test.go
plan/physical_plan_builder.go
plan/plan_test.go
plan/statistics/statistics.go
plan/statistics/statistics_test.go

When we calculate record counts for table scan, we didn't consider equal conditions.

plan: fix cost calculate bug.

---

executor/executor_test.go
plan/typeinferer.go
util/types/convert_test.go
util/types/datum.go

Fixes a bug when pattern in items input is string but pattern column is of integer type.

plan: add cast function for PatternInExpr.

---

plan/physical_plan_builder.go
plan/plan_test.go
plan/planbuilder.go

If an index is not public, we should not use it.

plan: only use public index.

---

ddl/column.go
ddl/ddl.go
ddl/ddl_db_test.go
ddl/ddl_worker.go
ddl/foreign_key.go
ddl/index.go
ddl/table.go
ddl/table_test.go

update error codes and add tests
improve the test coverage from 79% to 81%

ddl: Update error information and add tests

---

store/tikv/gc_worker.go

Internal SQL query should use RestrictedSQLExecutor.

store/tikv: use RestrictedSQLExecutor to execute sql in GC worker.

---

Makefile

Revert "makefile: Add the argument of "-check.v" in test"

---

bootstrap_test.go
ddl/bg_worker.go
ddl/ddl.go
ddl/ddl_worker.go
domain/domain.go
executor/compiler.go
executor/executor_distsql.go
executor/executor_simple.go
model/ddl.go
server/conn.go
server/server.go
session.go
session_test.go
store/localstore/txn.go
store/tikv/txn.go
tidb_test.go
util/testkit/testkit.go

Add logging for set system variable.
Add connection ID in log.
Adjust some log level.
Improve readability.

*: improve log

---

_vendor/src/github.com/pingcap/check/run.go
glide.lock
glide.yaml

*: Update glide

---

table/tables/index.go
table/tables/index_test.go
table/tables/tables.go

table/tables: fix panic

---

mysql/charset.go
plan/physical_plan_builder.go
plan/plan_test.go
plan/range.go
plan/refiner.go
plan/typeinferer.go
session_test.go

Also add cast string for like and regexp expression.

plan: handle type convertion when building index range.

---

store/tikv/client.go
store/tikv/metrics.go
store/tikv/txn_committer.go

Count the size of data that a transaction writes.

store/tikv: add txn size metrics.

---

executor/adapter.go
executor/builder.go
executor/executor.go
executor/executor_ddl.go
executor/executor_distsql.go
executor/executor_simple.go
executor/executor_write.go
executor/explain.go
executor/grant.go
executor/prepared.go
executor/prepared_test.go
executor/show.go
executor/union_scan.go
plan/plan.go
plan/planbuilder.go
session.go

remove useless code.
@zimulala @shenli @coocood @tiancaiamao @XuHuaiYu PTAL

*: clean code.

---

ddl/schema.go

ddl: minor clean up

---

ddl/ddl_test.go
ddl/reorg.go

pass race and rename reorgContext to mockContext.

ddl: Pass race

---

session.go

*: clean up log

---

plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/optimizer.go
plan/plan_test.go
plan/validator.go

clean useless code. The validating has been done in rewriter function.
@shenli @coocood @zimulala @XuHuaiyu @tiancaiamao @winoros  PTAL

plan: remove old validator logic

---

sessionctx/variable/session.go
sessionctx/variable/session_test.go

*: Fix set tidb session variable bug

---

executor/executor.go

We don't need it any more.
@shenli @coocood @zimulala @XuHuaiyu PTAL

executor: remove filter exec.

---

store/tikv/mock-tikv/cop_handler.go

mock-tikv: return correct Locked error.

---

ddl/ddl_db_test.go

ddl: Tiny clean up

---

ddl/ddl_db_test.go

The time spent before and after is "106s vs. 71s"

ddl: Speed up test

---

ddl/foreign_key_test.go

ddl: Fix the data race in foreign_key_test.go

---

executor/aggregate_test.go

make test result stable.
@shenli @zimulala @coocood @tiancaiamao PTAL

executor: fix ci.

---

domain/domain.go
domain/domain_test.go
session_test.go

Using MockReloadFailed  leads to data race. Now fix it.

domain: Fix data race

---

executor/executor_test.go
plan/physical_plan_builder.go

fix #2077 
@winoros @shenli @coocood @zimulala @XuHuaiyu PTAL

plan: correct enforcer's correlated attribute.

---

ddl/ddl_db_test.go

ddl: Update lease

---

domain/domain.go

Update log level to reduce unnecessary logs when using info.

domain: Update log level

---

ddl/ddl.go
ddl/ddl_db_test.go

ddl: Support creating anonymous index

---

executor/builder.go
plan/column_pruning.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/logical_plans.go
plan/physical_plan_builder.go
plan/physical_plan_test.go
plan/physical_plans.go
plan/predicate_push_down.go
plan/resolve_indices.go
plan/stringer.go

Then we can apply all optimization without considering apply specially.
@coocood @shenli @winoros @zimulala @shenli PTAL

plan: set apply's innerplan be the second child of it.

---

plan/expression_rewriter.go
plan/logical_plan_test.go

I forgot to handle an error which may lead to panic.
fix #2001 
@shenli @coocood @zimulala @XuHuaiyu @winoros PTAL

plan: handle the missing err to avoid panic.

---

README.md

Add tidb user google group link

---

ast/dml.go
executor/executor_test.go
executor/show.go
executor/show_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/planbuilder.go
plan/resolver.go

#2015 
This commits support `show events` statement.
PTAL @shenli @coocood @tiancaiamao @hanfei1991 @zimulala @winoros

parser: support show events

---

store/tikv/2pc.go

4k is better for importing data.
@ngaut @zhangjinpeng1987

tikv: change batch size from 32k to 4k

---

store/tikv/store_test.go

Fix #2061 
It works fine on current master. /cc @zimulala

store/tikv: enable test.

---

plan/logical_plan_builder.go
plan/logical_plan_test.go

fix #1997 
When we can't resolve a column in having clause, it may be a correlated column.
@winoros @shenli @coocood @zimulala @XuHuaiyu PTAL

plan: fix a resolve bug.

---

infoschema/tables.go
session_test.go

See: http://dev.mysql.com/doc/refman/5.7/en/columns-table.html

*: Fix a typo in information_schema.columns table column name

---

sessionctx/binloginfo/binloginfo_test.go

close DDL before set PumpClient to nil.

sessionctx/binloginfo: fix race.

---

ddl/column.go
ddl/ddl_test.go
ddl/reorg.go
util/mock/context.go

Remove mockContext in the package of ddl

*: Remove mockContext in the package of ddl

---

executor/executor.go

executor: Fix data race

---

mysql/const.go
mysql/util.go

mysql: Tiny clean up

---

executor/explain_test.go
plan/aggregation_push_down.go
plan/physical_plan_test.go

When we push aggregation across join, we should update the gbyCols.
@coocood @shenli @zimulala @winoros PTAL

plan: update gby cols for pushed agg.

---

circle.yml

ci: Add circleci

---

plan/typeinferer.go
plan/typeinferer_test.go

See: http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_date-format
@tiancaiamao @zimulala PTAL

plan: Fix date_format type infer

---

executor/executor.go
executor/executor_simple.go
executor/executor_simple_test.go

Fix #2153 and it helps to solve issue #2073

executor: Support the statement of 'set password = ... ' 

---

ast/misc.go
ast/misc_test.go
executor/executor_simple.go
executor/executor_simple_test.go
parser/parser.y
parser/parser_test.go
plan/planbuilder.go

Resolving issue #2073 needs to support the statement of "alter user user() ..."

*: Support the statement of "alter user"

---

ddl/column_change_test.go

line 162 and line 156 encounter data race.
read at store/localstore/txn.go:96  
write at store/localstore/txn.go:59

ddl: Pass data race

---

README.md

*: Add circle ci status icon

---

store/tikv/coprocessor.go

support case when.
@XuHuaiyu @shenli @coocood @zimulala PTAL

store/tikv: switch case when on.

---

plan/typeinferer.go
plan/typeinferer_test.go

typeinferer: Fix schema() function type infer bug

---

util/charset/charset.go
util/charset/charset_test.go

a problem encountered by issue #2183 
@shenli @coocood @zimulala @XuHuaiyu PTAL

util/charset: Let charset name be insensitive.

---

ddl/ddl.go
ddl/ddl_db_test.go

Unsupport dropping the column that is pk handle.

ddl: Unsupport dropping the column that is pk handle

---

util/types/convert.go
util/types/convert_test.go

Return overflow when exp is too large, Avoid allocating too much memory.

util/types: fix floatStrToIntStr, handle large exponent corner case.

---

executor/executor.go
executor/executor_test.go
executor/run.sh
plan/match_property.go
plan/physical_plan_builder.go
plan/physical_plan_test.go
session_test.go

An enhancement and a bug fix
1. make union execution parallel
2. order can't push across union / unionall but limit can.
@shenli @coocood @zimulala @tiancaiamao @XuHuaiyu @winoros @lamxTyler PTAL

*: make union execution parallel and fix a union plan bug.

---

executor/executor_simple.go
executor/executor_simple_test.go
plan/planbuilder.go

I will remove the evaluator.Eval step by step.
@shenli @coocood @zimulala @winoros @lamxTyler PTAL

*: rewrite the logic of do statement.

---

ddl/ddl.go
ddl/ddl_db_test.go

ddl: Fix issue #2176

---

executor/prepared.go
plan/expression_rewriter.go
plan/planbuilder.go
plan/plans.go

I will remove the evaluator.Eval step by step.
@shenli @coocood @zimulala @winoros @lamxTyler PTAL

*: rewrite the logic of execute.

---

store/tikv/backoff.go
store/tikv/region_request.go

Print only last 3 errors when fail after retried many times.
cc @siddontang @shenli

store/tikv: trim error message.

---

store/tikv/metrics.go
store/tikv/rawkv.go

Add rawkv metrics to measure time cost and key-value size.

store/tikv: add rawkv metrics.

---

plan/validator.go
plan/validator_test.go

Default value can be null when the column's option is auto-increment.

plan: Default value can be null when the option is auto-increment

---

util/segmentmap/segmentmap.go
util/segmentmap/segmentmap_test.go

The test coverage increases from 0% to 90.5%.
Handle issue #1613

util/segmentmap: Improve the test coverage

---

domain/domain.go

domain: Fix typo

---

plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/physical_plan_builder.go
plan/plan.go
plan/refiner.go

Variables are declared or assigned when it's used.
Rename `Ts` to `Tbl` like `Idx`.

plan: Clean up

---

session.go

Clean `GetTxn` and `finishTxn` in session.

*: Clean "GetTxn" and "finishTxn"

---

executor/builder.go
executor/compiler.go
executor/executor.go
executor/executor_simple.go
executor/executor_test.go
executor/grant.go
executor/prepared.go
executor/union_scan.go
kv/kv.go
session.go
session_test.go
sessionctx/binloginfo/binloginfo.go
sessionctx/forupdate/for_update_ctx.go
sessionctx/variable/session.go
table/tables/tables_test.go
tidb.go

Revert "tidb, variable: refactor retry, add TransactionContext"

---

ast/functions.go
evaluator/builtin.go
evaluator/builtin_time.go
evaluator/builtin_time_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go

See https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_timediff

builtin function timediff

---

ddl/ddl.go
executor/executor.go
plan/expression_rewriter.go

*: remove evaluate.Eval from ddl

---

evaluator/builtin_string_test.go

change test to give up eval interface.
@shenli @zimulala @coocood @tiancaiamao PTAL

evaluator: change string test.

---

executor/show_test.go
parser/parser.y
parser/parser_test.go

Fixes issue https://github.com/pingcap/tidb/issues/2303

parser: support show keys from table from database syntax.

---

store/tikv/2pc.go
store/tikv/backoff.go
store/tikv/region_request.go
store/tikv/scan.go
store/tikv/snapshot.go

Use *DEBUG* level for retryable / recoverable errors.

store/tikv: adjust log levels.

---

ast/functions.go
evaluator/builtin.go
evaluator/builtin_string.go
evaluator/builtin_string_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go
plan/typeinferer_test.go

`char_length` and its synonym `character_length`

add func char_length

---

util/types/time.go

fix isZero(), log timestamp error for CI

util/types: log timestamp error

---

executor/builder.go
expression/constant_fold.go
expression/constant_propagation.go
expression/expression.go
expression/scalar_function.go
expression/util.go
plan/aggregation_push_down.go
plan/column_pruning.go
plan/expr_to_pb.go
plan/expression_rewriter.go
plan/join_reorder.go
plan/logical_plan_builder.go
plan/range.go
plan/refiner.go
plan/resolve_indices.go
plan/stringer.go

prepare to refactor function model.

*: add GetArgs interface

---

expression/builtin.go

prepare to refactor function model.
@shenli @zimulala @coocood @tiancaiamao PTAL

*: add builtin func interface.

---

executor/executor.go
executor/executor_test.go

fix a bug when do join.
@shenli @coocood @tiancaiamao PTAL

executor: consider uint = int in join condition.

---

expression/aggregation.go
expression/util.go
util/types/helper.go

refactor step by step.
@shenli @coocood @zimulala @tiancaiamao @ngaut PTAL

expression: move types.helper to expression pkg.

---

store/tikv/coprocessor.go

After this PR https://github.com/pingcap/tikv/pull/1459, we could pushdown if expression.
@disksing @coocood PTAL

tikv: Enable if expr pushdown

---

expression/builtin_info.go

refactor step by step.
@shenli @coocood @tiancaiamao @zimulala PTAL

expression: implement functionClass and builtinFunction for info funcs.

---

expression/builtin.go
expression/builtin_control.go

expression: implement functionClass and builtinFunction for some funcs.

---

ddl/ddl_api.go
session_test.go
util/types/etc.go

Hi @coocood,
In according to #2380 I create this PR.
Regards,
Yu

ddl: bug in columnDefToCol, Length shouldn't be set for unspecified fields. (#2381)

---

expression/builtin_string.go

add function class step by step.

expression: add functionClass and builtinFunc for str funcs.

---

domain/domain.go
domain/metrics.go
metrics.go
session.go

add some simple schema lease related metrics

tidb, domain: schema lease metrics

---

ast/functions.go
expression/builtin.go
plan/logical_plan_test.go

*: support substr.

---

tidb-server/main.go

PTAL @andelf @shenli 
cc pingcap/pd#472
cc pingcap/tikv#1499

tidb-server: change flag v to V

---

store/tikv/lock_resolver.go

Log more details when error is unexpected.
@coocood @shenli

store/tikv: log more info for unexpected errors.

---

ast/flag.go
ast/functions.go
expression/aggregation.go

clean ast code and move aggContext outof ast package.

*: clean code in ast package.

---

plan/logical_plan_builder.go
plan/statistics/statistics_test.go

@shenli @coocood @zimulala @XuHuaiyu @lamxTyler PTAL

plan: remove useless log

---

store/tikv/2pc_test.go

10ms may not be enough for slow machine.
@zimulala @tiancaiamao

store/tikv: make test stable.

---

ast/flag.go
executor/prepared.go

remove useless code.
@shenli @coocood @zimulala @shenli PTAL

ast: clean some code.

---

executor/adapter.go
executor/compiler.go
executor/metrics.go
executor/metrics_test.go
executor/prepared.go
server/server_test.go

Make the statement label contains more information.

executor: refine statement count metrics

---

executor/executor_simple.go

Removes unnecessary new transaction when execute BEGIN statement.

executor: optimize begin

---

bootstrap_test.go
ddl/ddl_db_test.go
executor/executor_test.go
perfschema/perfschema_test.go
plan/resolver_test.go
plan/typeinferer_test.go
privilege/privileges/cache_test.go
privilege/privileges/privileges_test.go
server/tidb_test.go
session.go
session_test.go
sessionctx/binloginfo/binloginfo_test.go
store/tikv/gc_worker_test.go
store/tikv/store_test.go
store/tikv/ticlient_test.go
table/tables/tables_test.go
tidb-server/main.go
tidb_test.go

Revert "*: run a bootstrap session before store is ready"

---

expression/builtin_control_test.go
expression/builtin_info_test.go
expression/builtin_math_test.go

change expression test to fit new interface.

expression: change test.

---

ast/functions.go
expression/builtin.go
expression/builtin_math.go
expression/builtin_math_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go
plan/typeinferer_test.go

*: added builtin function sqrt

---

ddl/reorg.go
ddl/schema.go
ddl/table.go

Fix error format and clean up error trace.

ddl: Fix error format and clean up error trace.

---

executor/aggregate_test.go
plan/logical_plan_builder.go
plan/physical_plan_test.go

change `select distinct a from t` to `select a from t group by a`;

plan: change distinct to aggregation.

---

parser/parser_test.go

Move some tests from DML test to DDL test.

parser: Tiny clean up

---

domain/metrics.go
metrics.go

regist session retry metrics and fix two metrics names

tidb,session: fix session retry metrics

---

executor/builder.go
executor/executor.go
plan/match_property.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/plans.go
plan/stringer.go

clean code about distinct
@shenli @coocood PTAL

plan, executor: clean code

---

store/tikv/backoff.go
store/tikv/coprocessor.go
store/tikv/snapshot.go

Aims to decrease time wait for lock. 
/cc @coocood @shenli

store/tikv: tuning backoff base.

---

executor/metrics.go

An expensive query may run for a long time, we need to see the log before query is finished.

executor: log expensive query.

---

bootstrap_test.go
ddl/ddl_db_test.go
executor/executor_test.go
perfschema/perfschema_test.go
plan/resolver_test.go
plan/typeinferer_test.go
privilege/privileges/cache_test.go
privilege/privileges/privileges_test.go
server/tidb_test.go
session.go
session_test.go
sessionctx/binloginfo/binloginfo_test.go
store/tikv/gc_worker_test.go
store/tikv/store_test.go
store/tikv/ticlient_test.go
table/tables/tables_test.go
tidb-server/main.go
tidb_test.go

cherry-pick this branch to rc1.1
PTAL @shenli @iamxy

*: run a bootstrap session before store is ready (fix race) (#2491)

---

executor/executor_distsql.go

log the count of double read's handle.

executor: add log.

---

plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/logical_plans.go
plan/optimizer.go
plan/physical_plan_builder.go
plan/physical_plan_test.go
plan/physical_plans.go
plan/plan.go

clean code
@shenli @coocood @winoros @zimulala PTAL

plan: remove IsCorrelated and SetCorrelated.

---

executor/executor_test.go
plan/logical_plan_builder.go

We shouldn't omit the agg operator without gby cols.

plan: fix a bug of exists sub query

---

expression/builtin_compare.go
expression/builtin_test.go

expression: refactor functions.

---

expression/builtin_control.go
expression/builtin_control_test.go
expression/builtin_info.go

expression: refactor function.

---

expression/builtin_op.go

if the first item of CNF is true, the whole expression should be true.

expression: make and/ or expression faster.

---

expression/builtin.go
expression/builtin_time.go
expression/builtin_time_test.go

@shenli @coocood @tiancaiamao @zimulala PTAL

expression: refactor time function.

---

plan/aggregation_pruning.go
plan/aggregation_push_down.go
plan/build_key_info.go
plan/column_pruning.go
plan/decorrelate.go
plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/optimizer.go
plan/physical_plan_test.go
plan/planbuilder.go
plan/predicate_push_down.go

Not all queries need to use all the optmizer rules. This pr will make optimizer query-awared.
@shenli @coocood @zimulala @tiancaiamao @winoros @lamxTyler PTAL

plan: add opt flag.

---

plan/optimizer.go

only plans that have apply will add cache.

plan: only plans that have apply will add cache.

---

executor/executor.go
executor/executor_agg.go
executor/executor_join.go
executor/executor_set.go
executor/executor_write.go
executor/prepared.go
expression/aggregation.go
expression/builtin.go
expression/builtin_op.go
expression/column.go
expression/constant_fold.go
expression/constant_test.go
expression/expression.go
expression/scalar_function.go
plan/expression_rewriter.go

*: remove ctx from function args.

---

plan/logical_plan_test.go
plan/physical_plan_test.go

plan: move some test.

---

executor/aggregate_test.go
infoschema/infoschema_test.go
infoschema/tables.go

Fix https://github.com/pingcap/tidb/issues/2580
See https://dev.mysql.com/doc/refman/5.7/en/table-constraints-table.html

*: Support information_schema.table_constraints

---

store/tikv/gc_worker.go

store/tikv: fix gc lifetime metrics.

---

expression/column.go
expression/expression.go
expression/schema.go
plan/aggregation_push_down.go
plan/column_pruning.go
plan/join_reorder.go
plan/logical_plan_builder.go
plan/logical_plans.go
plan/physical_plan_builder.go
plan/physical_plans.go

plan: add Contains function on Schema

---

privilege/privileges/cache.go
privilege/privileges/cache_test.go

reuse pattern match code in stringutil
@hanfei1991 @coocood @zimulala

privilege/privileges: use stringutil for like pattern match

---

ddl/column.go
ddl/ddl_api.go
ddl/ddl_db_test.go
tidb.go

*: Add default value checking when `create table` 

---

executor/simple.go
privilege/privileges/cache.go
util/sqlexec/restricted_sql_executor.go

This tiny change also fix a bug that privilege background session never commit.
PTAL @zimulala @coocood

util/sqlexec: introduce a SQLExecutor interface and use it

---

ddl/ddl_api.go
ddl/ddl_db_test.go
parser/parser.y
parser/parser_test.go

*: Support the statement of `drop default`

---

ddl/ddl_api.go
plan/typeinferer.go
plan/typeinferer_test.go
util/types/etc.go

refine the type inferer of greatest() and least().
PTAL @coocood @hanfei1991 @zimulala @tiancaiamao

plan/typeinferer: refine type inferer of builtin func greatest/least

---

executor/prepared.go
session.go
session_test.go

Prepared statement should return result fields.

tidb: return fields for prepared statements.

---

parser/parser.y
parser/parser_test.go

parser: Support the field of `column` optional

---

executor/write.go
executor/write_test.go

executor: fix a bug about table name comparison

---

.travis.yml
Makefile

travis: Use go 1.8

---

executor/join.go
executor/join_test.go

executor: fix bug about left outer join.

---

executor/builder.go
executor/join.go
executor/join_test.go
plan/physical_plan_builder.go

fix bug about left outer join.

*: fix bug about scalar subquery.

---

store/tikv/oracle/oracles/pd.go

optimize GetTimestamp function

tikv/oracle: remove updated channel and mutext for last TS.

---

plan/planbuilder.go
plan/planbuilder_test.go

Fix database list empty problem.
I will refactor buildShowSchema related code latter.

Make tidb comptible compatible with navicat

---

executor/executor_test.go
util/types/datum.go

util/types: fix bug when truncating string values.

---

session.go
tidb-server/main.go
tidb.go

Some of our long-running tests want to increase the number of retries.
cc @coocood @shenli

server, session: add commitRetryLimit config.

---

ddl/ddl_api.go

ddl: Remove useless argument

---

parser/parser.y
parser/parser_test.go

Handle ON UPDATE CURRENT_TIMESTAMP(6), which specify fraction part.
```
CREATE TABLE IF NOT EXISTS `general_log` (
`event_time` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
`user_host` mediumtext NOT NULL,
`thread_id` bigint(21) unsigned NOT NULL,
`server_id` int(10) unsigned NOT NULL,
`command_type` varchar(64) NOT NULL,
`argument` mediumblob NOT NULL
) ENGINE=CSV DEFAULT CHARSET=utf8 COMMENT='General log'
```

parser: parse ON UPDATE CURRENT_TIMESTAMP(6)

---

parser/parser.y
parser/parser_test.go

mysql> alter table t modify a timestamp ON UPDATE now;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'now' at line 1

parser: Compatible with "on update timestamp now"

---

ddl/table.go

ddl: Fix the bug of %!(MISSING) in error message

---

Makefile

disable cgo for release build

---

executor/aggregate_test.go
infoschema/infoschema_test.go
infoschema/tables.go

Some admin tool will complain about this.

*: Add a empty table for triggers

---

expression/evaluator_test.go
expression/expression.go

expression: make values function underministic.

---

session.go
session_test.go
tidb.go

Fixes https://github.com/pingcap/tidb/issues/2759

session: reset StmtCtx in retry

---

session.go

ActivePendingTxn is an interface of Context, not Session

 clean up comment

---

store/tikv/region_request.go

Use _Warn_ for some region errors, help to diagnose issues online.

store/tikv: adjust log level for some region errors.

---

expression/builtin_encryption.go
expression/builtin_encryption_test.go

expression: Use Datum.ToBytes() in AESEncrypt/Decrypt

---

_vendor/src/github.com/pingcap/tipb/go-binlog/binlog.pb.go
_vendor/src/github.com/pingcap/tipb/go-binlog/cistern.pb.go
_vendor/src/github.com/pingcap/tipb/go-binlog/pump.pb.go
_vendor/src/github.com/pingcap/tipb/go-tipb/select.pb.go
_vendor/src/google.golang.org/grpc/backoff.go
_vendor/src/google.golang.org/grpc/balancer.go
_vendor/src/google.golang.org/grpc/call.go
_vendor/src/google.golang.org/grpc/clientconn.go
_vendor/src/google.golang.org/grpc/credentials/credentials.go
_vendor/src/google.golang.org/grpc/credentials/credentials_util_go17.go
_vendor/src/google.golang.org/grpc/credentials/credentials_util_pre_go17.go
_vendor/src/google.golang.org/grpc/interceptor.go
_vendor/src/google.golang.org/grpc/metadata/metadata.go
_vendor/src/google.golang.org/grpc/rpc_util.go
_vendor/src/google.golang.org/grpc/server.go
_vendor/src/google.golang.org/grpc/stream.go
_vendor/src/google.golang.org/grpc/transport/control.go
_vendor/src/google.golang.org/grpc/transport/go16.go
_vendor/src/google.golang.org/grpc/transport/go17.go
_vendor/src/google.golang.org/grpc/transport/handler_server.go
_vendor/src/google.golang.org/grpc/transport/http2_client.go
_vendor/src/google.golang.org/grpc/transport/http2_server.go
_vendor/src/google.golang.org/grpc/transport/http_util.go
_vendor/src/google.golang.org/grpc/transport/pre_go16.go
_vendor/src/google.golang.org/grpc/transport/transport.go
glide.lock
glide.yaml
sessionctx/binloginfo/binloginfo_test.go

* update grpc version to 1.0.4
* update tipb
@disksing @coocood @shenli PTAL

vendor: update grpc to v1.0.4

---

executor/metrics.go

For expensive query, not only log it, but also add it to metrics.
PTAL @coocood @shenli

executor: add expensive query metrics

---

plan/logical_plan_test.go

plan: fix column prunning test.

---

executor/distsql_test.go
store/tikv/kv.go

Fix a data race in test code of last PR.

executor,store/tikv: fix data race

---

executor/analyze_test.go
plan/analyze_test.go
plan/logical_plan_builder.go
plan/optimizer.go
tidb-server/main.go

after supporting stats_meta #2766 
we can remove the stats switch safely.
@shenli @coocood @zimulala @lamxTyler PTAL

*: remove stats switch.

---

expression/builtin_math.go
expression/builtin_math_test.go
plan/typeinferer.go
plan/typeinferer_test.go

builtin: add pi built-in function

---

server/region_handler_test.go
server/server_test.go
server/tidb_test.go

Hi,all
This PR is to fix bug for `function not defined` error during `make race`. @ @ @ @coocood @zimulala PTAL

regions:fix bug for function not defined in make race

---

util/types/datum.go

* fix a typo in line 61
from "// f hold"
to     "// x hold"

* fix a typo in line 61

---

expression/builtin_miscellaneous.go
expression/builtin_miscellaneous_test.go
plan/typeinferer.go
plan/typeinferer_test.go

Add implementation for built-in function: is_ipv6

builtin: add is_ipv6 built-in function

---

sessionctx/varsutil/varsutil.go
sessionctx/varsutil/varsutil_test.go

Extract a function to check if the option is on.

varsutil: tiny cleanup

---

expression/builtin_math.go
expression/builtin_miscellaneous.go

expression: tiny cleanup

---

bootstrap.go
bootstrap_test.go
executor/aggregate_test.go
executor/grant.go
mysql/const.go
privilege/privileges/cache_test.go
session.go

Revert "*: upgrade mysql.user table schema"

---

parser/lexer.go
parser/lexer_test.go
parser/parser.y

Parse special MySQL comment `/*+ xxx */` will get token `hintBegin xxx hintEnd`.
It could be used for optimizer hit later.
@coocood  @hanfei1991

parser: parse special comment /*+ */ for optimizer hint

---

executor/explain_test.go
executor/merge_join_test.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/plan.go

Revert "Maxiaoyu/fix sort"

---

executor/aggregate_test.go
expression/aggregation.go

expression: fix bug about function equal logic.

---

util/types/convert_test.go
util/types/datum.go

Fix issue #2955 
@coocood @tiancaiamao PTAL

types: Add missing TypeNewDate in ConvertTo

---

executor/explain_test.go
plan/physical_plan_builder.go

Let the pushed limit show its id.

plan: optimize explain result

---

executor/builder.go
executor/executor.go
plan/aggregation_push_down.go
plan/build_key_info.go
plan/column_pruning.go
plan/decorrelate.go
plan/expression_rewriter.go
plan/initialize.go
plan/join_reorder.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/logical_plans.go
plan/optimizer.go
plan/physical_plan_builder.go
plan/physical_plan_test.go
plan/physical_plans.go
plan/plan.go
plan/planbuilder.go
plan/predicate_push_down.go
plan/resolve_indices.go
plan/stringer.go

plan, executor: add logical prefix for agg, join and apply.

---

plan/task_profile.go

If table plan is nil, it doesn't need to add `netWorkFactor` to `cst`.

plan: Update the function of `finishTask`

---

expression/builtin.go
expression/builtin_miscellaneous.go

expression/builtin: fix inet6_ntoa

---

executor/distsql.go
executor/executor.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/plans.go
plan/range.go
plan/refiner.go
plan/statistics_helper.go
util/types/range.go

Those types will be used in statistics later.

plan, util: move IndexRange and TableRange to types package.

---

plan/logical_plan_test.go
plan/topn_push_down.go

When Limit has Offset, the pushed down limit's count should be count + offset.

plan: fix bug of topn push down

---

ast/functions.go
expression/builtin.go
expression/builtin_other.go
expression/builtin_string.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go
plan/typeinferer_test.go

Hi, I've added three more builtin definitions, one of which is wanted by #2981 .

*: add three more builtin definitions

---

expression/builtin_time.go
expression/builtin_time_test.go
plan/typeinferer.go
plan/typeinferer_test.go

Signed-off-by: Xuanwo <xuanwo.cn@gmail.com>

built-in: add time-to-sec built-in function

---

plan/logical_plan_test.go
plan/logical_plans.go
plan/new_physical_plan_builder.go
plan/predicate_push_down.go
plan/task_profile.go

When decide the push down condition in phase of ppd,  then the mained selection must not be pushed down. BuildIndex/TableScan may return a selection plan.

plan: simplify the selection converting phase.

---

ast/functions.go
expression/builtin.go
parser/parser.y
parser/parser_test.go
plan/typeinferer.go
plan/typeinferer_test.go

Hi, I just resolved the conflict on 'in' caused by position function, PTAL.

*: resolve conflict on 'in' and add builtin position

---

executor/analyze.go

after all tasks have done, we write them to TiKV.
@shenli @coocood @lamxTyler PTAL

executor: fix race.

---

executor/builder.go
executor/distsql.go

Index scan concurrency is not initialized, so the effective concurrency was 1.
For table lookup task, the concurrency should use table scan concurrency instead.

executor: initialize index scan concurrency.

---

expression/builtin_miscellaneous.go
expression/builtin_other.go

After fixing:
mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.00 sec)
mysql> select sleep(1.5);
+------------+
| sleep(1.5) |
+------------+
|          0 |
+------------+
1 row in set (1.50 sec)
fix #2737

expression: fix bug in sleep function.

---

circle.yml

related:
https://github.com/pingcap/pd/pull/624

circleci: fix bad gopath under forked project

---

executor/builder.go
executor/executor.go
executor/join.go
executor/join_test.go
executor/merge_join.go
executor/union_scan.go
expression/constant_propagation.go
expression/expression.go
plan/physical_plan_builder.go
plan/physical_plans.go

let eval bool process multiple expressions. make code cleaner.

*: refine EvalBool function.

---

executor/aggregate_test.go
executor/executor_test.go
store/tikv/mock-tikv/cop_handler.go
store/tikv/mock-tikv/cop_handler_dag.go
store/tikv/mock-tikv/rpc.go

executor, store: let old plan use old store.

---

_vendor/src/github.com/gorilla/context/doc.go
_vendor/src/github.com/pingcap/tipb/go-tipb/executor.pb.go
_vendor/src/github.com/pingcap/tipb/go-tipb/expression.pb.go
_vendor/src/github.com/pingcap/tipb/go-tipb/schema.pb.go
_vendor/src/github.com/pingcap/tipb/go-tipb/select.pb.go
glide.lock
glide.yaml
plan/plan_to_pb.go
store/tikv/mock-tikv/cop_handler_dag.go
store/tikv/mock-tikv/executor.go

1. change some *int64 type to uint64.
2. add output columns.
@shenli @zimulala @coocood PTAL

*: update vendor for dag req.

---

executor/builder.go
plan/initialize.go
plan/physical_plans.go
plan/stringer.go
plan/task_profile.go

move flattenPlan to plan package.
@shenli @coocood @winoros @zimulala  PTAL

plan, executor: refine code.

---

store/tikv/2pc_test.go
store/tikv/coprocessor.go
store/tikv/kv.go
store/tikv/lock_resolver.go
store/tikv/split_test.go
store/tikv/store_test.go

left tikv and mock-tikv's cop client behave differently.

store, tikv: let client of mock-tikv support dag req.

---

ast/ast.go
ast/base.go
ast/ddl.go
ast/dml.go
ast/expressions.go
ast/functions.go
ast/misc.go

This PR aims to address comments warning produced by `goword`. There are some comments in form of `foo ...` means I do not know how to write comments for it. Please check it out and give me some advice.

fixed comments warning in ast

---

infoschema/infoschema.go

remove useless code

---

cmd/benchdb/main.go
cmd/benchkv/main.go
cmd/benchraw/main.go

BTW，there are no warnings in meta, domain.

cmd: fix comments warning in cmd

---

ddl/ddl.go
ddl/ddl_api.go
ddl/ddl_db_test.go

ddl: Return an error when add or drop primary key

---

expression/builtin_miscellaneous.go
expression/evaluator_test.go

Fix: https://github.com/pingcap/tidb/issues/3205

expression: Make UUID() a dynamic function

---

executor/executor_test.go
expression/expr_to_pb.go
plan/dag_plan_test.go
store/tikv/mock-tikv/executor.go

There are two bugs in new plan:
1. Distinct agg shouldn't be pushed.
2. Avg function should push both partial results to bytes slice in TiKV.
@shenli @zimulala @coocood PTAL

*: fix aggregation bug in new plan.

---

executor/adapter.go
executor/builder.go
executor/executor_test.go
executor/new_distsql.go
executor/union_scan.go
executor/union_scan_test.go

1. Let PointGet be able to process new executors.
2. fix bugs of dirty tables.
@shenli @coocood @zimulala @winoros @lamxTyler PTAL

executor: fix some bugs about new plan.

---

executor/analyze_test.go
executor/distsql_test.go
executor/executor_test.go
executor/explain_test.go
executor/join_test.go
executor/merge_join_test.go
executor/metrics_test.go
executor/union_scan_test.go
plan/analyze_test.go
plan/dag_plan_test.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/new_physical_plan_builder.go
plan/optimizer.go
plan/plan.go
plan/predicate_push_down.go
plan/resolve_indices.go
plan/stringer.go

@shenli @zimulala @winoros @lamxTyler @XuHuaiyu  PTAL

plan, executor: open the new plan switch for all test.

---

ddl/ddl.go
ddl/ddl_worker_test.go

PTAL @shenli @hanfei1991 @tiancaiamao @XuHuaiyu

ddl: Remove the function of Start

---

ddl/ddl_worker_test.go

store: Make test stable

---

store/tikv/kv.go

Hi,
This PR tries to clean up a little bit for the constructor of mock tikv store.
PTAL @tiancaiamao @zimulala @AndreMouche @disksing

store/tikv: clean up duplicate codes

---

store/tikv/client.go
store/tikv/metrics.go

It will help to identify bugs when the conn pool is full.

store/tikv: add conn pool metrics.

---

util/types/field_type.go
util/types/field_type_test.go

fix #3315 
PTAL @shenli @hanfei1991

util: correct type infer of Bit literal value

---

expression/builtin_miscellaneous.go
expression/builtin_miscellaneous_test.go
expression/typeinferer.go
expression/typeinferer_test.go

closes https://github.com/pingcap/tidb/issues/3305

Implementation of INET6_NTOA

---

ddl/syncer.go

schemaVersionSyncer is short of comment.
@zimulala PTAL

Add some comment for schemaVersionSyncer

---

executor/distsql.go

terminate the index read as soon as possible.

executor: stop fetch handles after closing.

---

store/tikv/2pc.go

When there are too much doActionOnBatches goroutine, it's expensive if they call `runtime.morestack`.
So I reserve a bigger stack for those goroutines.
@disksing @siddontang

store/tikv: avoid too much runtime.morestack by 2PC commit

---

context/context.go
plan/plan.go
store/tikv/2pc.go
util/types/json/serdes.go

Fix some typos, according to https://goreportcard.com/report/github.com/pingcap/tidb

*: fix typos

---

checklist.md

Add a newline to each paragraph to make them more readable.

tidb: format checklist.md

---

store/tikv/client.go

Hi,
This PR adds grpc window size configuration. It's the second part of PR #3377 
PTAL @coocood @tiancaiamao @disksing @siddontang

store/tikv: add grpc window size config

---

executor/executor_test.go
executor/set.go
sessionctx/variable/session.go
sessionctx/varsutil/varsutil.go

Fixes https://github.com/pingcap/tidb/issues/2485

executor: validate snapshot TS

---

_vendor/src/github.com/Sirupsen/logrus/LICENSE
_vendor/src/github.com/Sirupsen/logrus/alt_exit.go
_vendor/src/github.com/Sirupsen/logrus/doc.go
_vendor/src/github.com/Sirupsen/logrus/entry.go
_vendor/src/github.com/Sirupsen/logrus/exported.go
_vendor/src/github.com/Sirupsen/logrus/formatter.go
_vendor/src/github.com/Sirupsen/logrus/hooks.go
_vendor/src/github.com/Sirupsen/logrus/json_formatter.go
_vendor/src/github.com/Sirupsen/logrus/logger.go
_vendor/src/github.com/Sirupsen/logrus/logrus.go
_vendor/src/github.com/Sirupsen/logrus/terminal_appengine.go
_vendor/src/github.com/Sirupsen/logrus/terminal_bsd.go
_vendor/src/github.com/Sirupsen/logrus/terminal_linux.go
_vendor/src/github.com/Sirupsen/logrus/terminal_notwindows.go
_vendor/src/github.com/Sirupsen/logrus/terminal_solaris.go
_vendor/src/github.com/Sirupsen/logrus/terminal_windows.go
_vendor/src/github.com/Sirupsen/logrus/text_formatter.go
_vendor/src/github.com/Sirupsen/logrus/writer.go
_vendor/src/github.com/pingcap/pd/pd-client/client.go
glide.lock
glide.yaml

vendor: update pd version

---

ddl/owner_manager.go

ddl: Update owner_manager TTL

---

executor/executor_test.go

executor: set statsLease to 0

---

_vendor/src/github.com/pingcap/pd/pd-client/client.go
glide.lock
glide.yaml

PTAL @disksing @shenli @zimulala @coocood

vendor: update pd to fix a pd-client race

---

store/tikv/client.go

Hi,
This PR removes lock in connArray for grpc client.
PTAL @siddontang @tiancaiamao @coocood @disksing

store/tikv: remove lock in connArray

---

store/tikv/region_cache.go
store/tikv/region_cache_test.go
store/tikv/region_request.go

Hi,
This PR revises the log of removing regions from region cache.
PTAL @tiancaiamao @siddontang @disksing

store/tikv: revise region cache log

---

store/tikv/mock-tikv/cop_handler.go
store/tikv/mock-tikv/cop_handler_dag.go
store/tikv/mock-tikv/executor.go
store/tikv/mock-tikv/topn.go

`topn` and its family is quite confusing at first time. Rename them to `topN`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/3502)

refactor variable name

---

session.go

It's not easy to construct the testcase for this change, I'll refactor mockTikv and add it later.
PTAL @shenli @disksing

tidb: reset transaction when session retry statement in history meets error

---

CONTRIBUTORS

Sorry for the careless. This should be correct order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/3500)

fix order in contributors

---

ddl/ddl_db_test.go
ddl/index.go
table/tables/tables.go

Similar to #3510
Conflicts:
table/tables/tables.go

*: Fix add index after add column with default value (#3510)

---

ddl/table.go
inspectkv/inspectkv_test.go
meta/meta.go
meta/meta_test.go

*: Fix rename table auto id conflict problem (#3493)

---

expression/builtin_miscellaneous.go
expression/builtin_miscellaneous_test.go
expression/typeinferer.go
expression/typeinferer_test.go

builtin: IsIPv4Compat function
nearly the same code with #3193

builtin: IsIPv4Compat function

---

parser/parser.y
parser/parser_test.go

Refer [URL](https://dev.mysql.com/doc/refman/5.7/en/rename-table.html)

parser: Support alter table rename table without to

---

ddl/owner_manager.go
ddl/syncer.go

ddl: Break campaignLoop when closing DDL

---

parser/parser.y

parser: add TablesTerminalSym nonterminal symbol desc

---

CONTRIBUTORS
ddl/generated_column.go
sessionctx/varsutil/varsutil.go
store/tikv/client.go
store/tikv/lock_test.go
store/tikv/tikvrpc/tikvrpc.go
util/testleak/leaktest.go

*: Fix typo

---

store/tikv/lock_resolver.go

For binlog service. Toke down by #3172 unexpectedly.

store/tikv: export LockResolver.

---

store/tikv/mock-tikv/executor.go

Optimize this [PR](https://github.com/pingcap/tidb/pull/3483/files).
PTAL @hanfei1991 @winoros

store/tikv/mock-tikv: Remove useless encode

---

plan/logical_plan_test.go
statistics/histogram.go
statistics/table.go

This will make the params passed to #3161 's method `Selectivity` clean.
PTAL @shenli @hanfei1991

statistics: add variable member for table.

---

store/tikv/2pc.go

Hi,
This PR disable `skip_contraint_check` in prewrite. The exception case is similar to https://github.com/pingcap/tidb/pull/3561. It seems that we can not retry `prewrite` with `skip_contraint_check=true` . And If we do not do this, the following case may happened:
1.  In transaction 1, we send `prewrite(a,start_ts,skip_contraint_check = true)`  to tikv, and tikv process the request and marked with `lock(a,start_ts)`, and then the request timeout.
2.   In transaction 2,  `tikv` find a lock of `a(start_ts)`, it send a `rollback(a,start_ts)` to primary key `a`.`tikv` receive a `rollback(a,start_ts)` on the primary, it marked with `write(a,rollback,start_ts,start_ts)`
3.  In transaction 1, `tikv` get a timeout error from  request`prewrite`, it retry …

tikv/2pc:disable skip_contraint_check

---

executor/executor_test.go
executor/write.go
plan/logical_plan_builder.go
plan/plan.go
plan/resolve_indices.go

port something from master to RC3.

plan, executor: fix multi-update. (#3531)

---

store/tikv/2pc.go

Hi,
This PR is for RC3, It disabled skip_contraint_check in prewrite. The related PR is https://github.com/pingcap/tidb/pull/3600
@zhangjinpeng1987 @shenli @disksing PTAL

tikv/2pc: disable skip_contraint_check in 2pc

---

ddl/ddl_db_test.go
ddl/index.go

ddl: Fix add index with PK

---

expression/helper.go
expression/helper_test.go
util/types/convert_test.go
util/types/datum.go

cherry-pick https://github.com/pingcap/tidb/pull/3544 and https://github.com/pingcap/tidb/pull/3587 from master.
@shenli @zimulala

expression,util/types: cherry-pick timestamp related bug fix

---

expression/builtin_miscellaneous.go

Don't repeat yourself
Use a common IPv6 Prefix check function for IPv6Compat and IPv6Mapped

Use one function to handle IPv4Mapped and IPv4Compat

---

ddl/ddl_db_test.go
ddl/index.go

ddl: Fix add index with PK (#3622)

---

ddl/ddl.go
ddl/ddl_worker.go
ddl/owner_manager.go
ddl/syncer.go
executor/ddl_test.go
executor/executor_test.go
parser/parser.y
parser/parser_test.go
plan/logical_plan_test.go
plan/optimizer.go
plan/resolver.go
sessionctx/varsutil/varsutil.go

PRs:
#3534 
#3525 
#3553 
#3552 
#3527

*: Cherry pick some PRs

---

ast/dml.go
executor/show.go
executor/show_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/planbuilder.go
plan/resolver.go
statistics/handle.go
statistics/table.go

The syntax is `show stats_meta` or `show stats_meta where ...`. For example:
```
MySQL [test]> show stats_meta where table_name = 't';
+---------+------------+---------------------+--------------+-----------+
| Db_name | Table_name | Update_time         | Modify_count | Row_count |
+---------+------------+---------------------+--------------+-----------+
| test    | t          | 2017-07-05 17:13:53 |            0 |         0 |
+---------+------------+---------------------+--------------+-----------+
```
PTAL @hanfei1991  @zimulala  @winoros

*: support show stats

---

executor/show_test.go
plan/resolver.go

Fix https://github.com/pingcap/tidb/issues/3641

plan: check database when parsing `show tables` and `show table status`

---

executor/write.go
executor/write_test.go

fix https://github.com/pingcap/tidb/issues/3639

executor: support SQL mode NO_AUTO_VALUE_ON_ZERO

---

executor/executor_test.go
expression/builtin_string.go
expression/builtin_string_test.go

Refactor builtin string function `ORD`
I implemented the function `ORD` and added some test cases in executor

refactor builtin string function ord

---

statistics/builder.go
statistics/histogram.go
statistics/statistics_test.go

PTAL @hanfei1991  @zimulala  @winoros

statistics: fix bug when calculating lowerbound of the first bucket

---

server/conn.go
server/server.go
server/tidb_test.go

https://github.com/pingcap/tidb/issues/3680

tidb-server: fix incorrect error message when auth failed

---

executor/executor_test.go
expression/builtin.go

fix #3704 
PTAL @hanfei1991 @zz-jason

executor, expression: fix cast(-1 as unsigned)(#3704)

---

util/parser/expression_test.go

Improve the test coverage from 0% to 100%.

util/parse: Improve the test coverage

---

plan/optimizer.go
plan/physical_plan_builder.go
plan/plan.go
plan/stats.go

This is the a pre-step of stats propagation, just call it and increase the coverage of test to 79.7%

plan: call the prepareStats but not use it yet.

---

expression/builtin_control_test.go

to https://github.com/pingcap/tidb/issues/3729

expression: add unit test for function CASE

---

expression/builtin_info_test.go

to https://github.com/pingcap/tidb/issues/3729

expression: add unit test for builtin_info.go

---

domain/schema_validator.go
domain/schema_validator_test.go

PTAL @shenli @hanfei1991 @tiancaiamao

domain: Fix a lock bug (#3750)

---

parser/lexer.go
parser/yy_parser.go
plan/logical_plan_builder.go
session.go
session_test.go

Fix #3739, the wrong comment in selection field.
Due to #2017, I fix the result set fields instead of fix it in parser.
PTAL @tiancaiamao @zimulala

parser, session: fix wrong comment in selection field

---

executor/executor_test.go

executor: add sort for union test

---

executor/executor_test.go
executor/join_test.go
plan/expression_rewriter.go

This bug-fix will be merged to release rc3.

plan, executor_test: fix bug for user variable. (#3776)

---

expression/builtin_compare_test.go
expression/builtin_test.go
util/types/field_type.go

as title described
PTAL @hanfei1991 @zz-jason

expression: unit test coverage from builtin_compare.go from 53.2% to 85.8%

---

store/tikv/backoff.go

store/tikv: increase max backoff.

---

executor/join_test.go
util/codec/codec.go

executor, codec: fix bug when join 2 decimal keys.

---

ddl/column.go
ddl/foreign_key.go
ddl/index.go
ddl/table.go

The test will be added in the next PR.
PTAL @shenli @hicqu @hanfei1991 @tiancaiamao

ddl: Fix a version bug

---

domain/domain.go
server/server_test.go

Cherry pick from master to rc3.
PTAL @shenli @jackysp @hanfei1991

domain: handle load privilege loop watch channel closed

---

ddl/column.go
ddl/foreign_key.go
ddl/index.go
ddl/table.go
privilege/privileges/privileges_test.go

PTAL @hicqu @winoros @hanfei1991 @shenli

ddl: Fix a version bug (#3800)

---

Jenkinsfile

PTAL @shenli @zimulala @hanfei1991

Jenkinsfile: use tidb-test `rc3` branch to test tidb `rc3` branch

---

tidb-server/main.go

PTAL @hicqu @zimulala @winoros

tidb-server: fix typo. (#3632)

---

plan/eliminate_projection.go
plan/logical_plan_builder.go
plan/physical_plan_test.go

fix https://github.com/pingcap/tidb/issues/3810

plan: set column's FromID to the projection's ID

---

ddl/ddl_db_test.go
ddl/index.go

PTAL @shenli @hicqu @hanfei1991

ddl: Fix the wrong offset when using PK as an index

---

executor/executor_test.go
expression/builtin_math.go
expression/builtin_math_test.go
plan/typeinfer_test.go

The functionality of `ceil` is similar to the `floor`. Please take a look. @XuHuaiyu Thanks

expression, executor, plan: rewrite builtin function ceil

---

server/server_test.go
sessionctx/varsutil/varsutil_test.go

Cherry-pick from master.
See: https://github.com/pingcap/tidb/pull/3821

*: Make travis happy (#3821)

---

ddl/ddl_db_test.go
ddl/index.go

ddl: Fix the wrong offset when using PK as an index

ddl: cherry-pick 3820

---

statistics/histogram.go
statistics/table.go

PTAL @hanfei1991  @winoros  @zhexuany

statistics: make the naming more coherent

---

expression/expression_test.go

#3729 
PTAL @hanfei1991 @zz-jason

expression: improve unit test coverage of expression.go to 82.5%

---

expression/scalar_function_test.go

#3729 
PTAL @zz-jason @hanfei1991

expression: improve unit test coverage of scalar_function.go to 90.2%

---

distsql/distsql.go
distsql/distsql_test.go
model/model_test.go

Add unit tests for model and distsql (exclude distsql/xeval). 
PTAL @XuHuaiyu

model, distsql: add unit tests (exclude distsql/xeval)

---

plan/planbuilder.go

plan: fix typo

---

executor/executor_test.go
expression/builtin_op.go
expression/builtin_op_test.go
plan/typeinfer_test.go

*: rewrite logicOr using new expression evaluation architecture

---

executor/executor_test.go
expression/builtin.go
expression/builtin_op.go
expression/builtin_op_test.go
plan/typeinfer_test.go

*: rewrite rightShift using new expression evaluation architecture

---

executor/join_test.go
executor/sort.go

I forgot to set sort's Idx.
@winoros @lamxTyler PTAL

executor: fix bug when sort meets apply.

---

executor/executor_test.go
expression/builtin_op_test.go
expression/typeinferer.go

PTAL @shenli @zz-jason @hanfei1991

expression, executor: 1. revert typeinfer of cast and binary ops 2. add TestUnaryNot

---

plan/cbo_test.go
statistics/selectivity.go

statistics: return 1 when statistics is not ready and row count of table is 0

---

executor/join_test.go
plan/new_physical_plan_builder.go
plan/optimizer.go
plan/physical_plans.go

We should reset the schema in physical optimization.
@zz-jason @winoros @lamxTyler @zimulala  PTAL

plan: fix the order of schema columns

---

executor/new_distsql.go
util/testkit/testkit.go

We should make it stable when close multiple times.

*: fix close problem for index look up executor.

---

plan/explain.go
plan/explain_test.go

plan: avoid panic in explain

---

server/conn.go
server/server.go

cherry pick from master.
@shenli @zimulala

server: make show processlist doesn't include killed session (#3978)

---

executor/executor_test.go
util/types/time.go

fix https://github.com/pingcap/tidb/issues/3986

types: handle zero value in RoundFrac

---

config/config.go
server/server.go
server/tidb_test.go
tidb-server/main.go

Add a tcp keep alive start up option.

server: add a tcp keep alive start up option

---

executor/join_test.go
executor/new_join.go
store/tikv/coprocessor.go

This may cause panic and make result wrong.
PTAL @hanfei1991 @lamxTyler @shenli

executor: fix bug when do outer index join

---

executor/union_scan_test.go
plan/resolve_indices.go

fix a resolve bug cause by union scan.
@winoros @lamxTyler PTAL

*: fix union scan's bug.

---

executor/executor_test.go

Union executor will read multiple data source parallelly.
Line 622 is unstable and duplicate with line 633.

executor: Make union test stable

---

plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/logical_plan_test.go

we should handle the bug when building union. fix #4010

plan: fix a panic when executing union.

---

plan/dag_plan_test.go
plan/explain_test.go
plan/task.go

If two big tables join, we should choose hash join.
@winoros @lamxTyler PTAL

plan: make hashjoin's cost more reasonable.

---

expression/builtin_string.go
expression/integration_test.go

fix https://github.com/pingcap/tidb/issues/4019

expression: function SUBSTR/LEFT/RIGHT should manipulate code points instead of bytes(#4019)

---

executor/builder.go
plan/task.go
session.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/varsutil/varsutil.go

*: add variable to control batch size of index join

---

plan/validator.go
plan/validator_test.go
util/types/errors.go

Fix issue #3844 
PTAL @winkyao @zimulala

plan: check type set with comma in elements (#3844)

---

Jenkinsfile

jenkins: update Jenkinsfile in rc3 branch

---

Jenkinsfile

jenkins: update Jenkinsfile of rc4 branch 

---

executor/executor_test.go
plan/new_physical_plan_builder.go

plan: fix bug when access cond is not scalar function (#4044)

---

plan/cbo_test.go
plan/new_physical_plan_builder.go
plan/task.go

Currently, we will construct wrong plan due to the wrong process for sort property columns of Reader plans.
PTAL @shenli @hanfei1991 @lamxTyler

plan: fix bug about processing property of reader plan.

---

plan/cbo_test.go
plan/new_physical_plan_builder.go
plan/task.go

a cherry-pick pr.
PTAL @shenli @hanfei1991

plan: fix bug about processing property of reader plan. (#4065)

---

plan/dag_plan_test.go
plan/task.go

plan: make sort's cost right

---

executor/join_test.go
plan/dag_plan_test.go
plan/new_physical_plan_builder.go

plan: push property across semijoin.

---

executor/executor_test.go
executor/new_distsql.go

executor: fix double desc read.

---

executor/executor_test.go
executor/join_test.go
executor/new_distsql.go
plan/dag_plan_test.go
plan/new_physical_plan_builder.go

merge two fix to rc4

---

executor/write_test.go
plan/column_pruning.go

This is a cherry-pick.
PTAL @shenli @hanfei1991 @lamxTyler

plan: fix a bug when prune extra handle column (#4079)

---

plan/expression_rewriter.go
plan/logical_plan_test.go
plan/planbuilder.go

insert into t set b = a is not allowed, it should be written as insert into t set b = values(a).

plan: fix bug in insert statement.

---

statistics/update.go
statistics/update_test.go

This is a cherry pick.
PTAL @hanfei1991 @winoros @zz-jason

statistics: fix bug when update stats delta (#4098)

---

store/tikv/coprocessor.go

Push if null down to coprecessor.

coprocessor: open ifnull pushdown.

---

store/tikv/coprocessor.go

This is a cherry pick pr.
PTAL @hanfei1991 @shenli @XuHuaiyu

coprocessor: open ifnull pushdown. (#4126)

---

expression/builtin_op.go
expression/distsql_builtin_test.go
expression/integration_test.go
plan/typeinfer_test.go

to https://github.com/pingcap/tidb/issues/4080
@XuHuaiyu @zz-jason

expression: rewrite builtin function: ISNULL

---

store/tikv/coprocessor.go

There are some functions which are implemented in TiKV but we didn't open the swith. We should open them step by step.

store/tikv: support minus and mul push down.

---

expression/builtin_encryption.go
expression/builtin_info.go
expression/builtin_info_test.go
expression/builtin_miscellaneous.go
expression/builtin_string.go
expression/builtin_time.go

to https://github.com/pingcap/tidb/issues/4080

expression: throw unsupported error during type infer stage

---

infoschema/infoschema.go
mysql/const.go
plan/validator.go
plan/validator_test.go

add multi-column index key part limit

---

Makefile
util/printer/printer.go

@tiancaiamao @choleraehyq PTAL
➜  tidb git:(shenli/branch) ✗ ./bin/tidb-server -V                
Git Commit Hash: d5b860b126d97c8d6e3b623ccab7f0d8d1f9f7d7
Git Commit Branch: shenli/branch
UTC Build Time:  2017-08-14 06:04:17
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------+
| Git Commit Hash: d5b860b126d97c8d6e3b623ccab7f0d8d1f9f7d7
Git Branch: shenli/branch
UTC Build Time: 2017-08-14 06:04:17 | …

*: Add git branch name in tidb_version and starting log

---

ddl/ddl.go

ddl: Update the max interval of checking job

---

store/tikv/gc_worker_test.go

store/tikv: Make the GC test stable

---

expression/builtin_miscellaneous.go
expression/integration_test.go
plan/typeinfer_test.go

For #4080 
PTAL @XuHuaiyu @zz-jason

expression: rewrite builtin function: ANY_VALUE

---

store/tikv/gc_worker_test.go

store/tikv: make gc worker test more stable

---

executor/builder.go
executor/distsql.go
executor/new_distsql.go
executor/union_scan.go
plan/logical_plan_builder.go
plan/physical_plan_builder.go
tablecodec/tablecodec.go

*: tiny clean.

---

_vendor/src/github.com/go-sql-driver/mysql/buffer.go
_vendor/src/github.com/go-sql-driver/mysql/collations.go
_vendor/src/github.com/go-sql-driver/mysql/connection.go
_vendor/src/github.com/go-sql-driver/mysql/connection_go18.go
_vendor/src/github.com/go-sql-driver/mysql/const.go
_vendor/src/github.com/go-sql-driver/mysql/driver.go
_vendor/src/github.com/go-sql-driver/mysql/dsn.go
_vendor/src/github.com/go-sql-driver/mysql/errors.go
_vendor/src/github.com/go-sql-driver/mysql/infile.go
_vendor/src/github.com/go-sql-driver/mysql/packets.go
_vendor/src/github.com/go-sql-driver/mysql/rows.go
_vendor/src/github.com/go-sql-driver/mysql/statement.go
_vendor/src/github.com/go-sql-driver/mysql/transaction.go
_vendor/src/github.com/go-sql-driver/mysql/utils.go
_vendor/src/github.com/go-sql-driver/mysql/utils_go17.go
_vendor/src/github.com/go-sql-driver/mysql/utils_go18.go
_vendor/src/github.com/go-sql-driver/mysql/utils_legacy.go
glide.lock
glide.yaml

Cherry picked from https://github.com/pingcap/tidb/pull/4207, to support assembling DSN from structures.
@tiancaiamao @zimulala PTAL

*: update dependency `go-sql-driver`

---

expression/distsql_builtin.go

we have implemented all signatures of the function that can be pushed down

expression: clean code.

---

mysql/const.go

mysql: Remove the init function

---

_vendor/src/github.com/pingcap/pd/pd-client/client.go
glide.lock
glide.yaml

ref https://github.com/pingcap/pd/pull/711

vendor: update pd.

---

server/server.go

log is about listening addr, even though during the unix socket case.

server: minor log info corrections

---

expression/builtin.go
expression/builtin_arithmetic.go
expression/builtin_cast.go
expression/builtin_compare.go
expression/builtin_control.go
expression/builtin_math.go
expression/builtin_op.go
expression/builtin_other.go

This is a preparement for pushing signatures down. Every signature set its pbCode before construction.

expression: set pb code for signatures.

---

expression/builtin_cast.go
plan/cbo_test.go

Then we can choose timestamp index.

expression, plan: refine timestamp index selection

---

executor/join_test.go
plan/logical_plan_builder.go

If there's cast function in equal conditions, push it to other condition first.
It will be solved in predicate push down phase.
PTAL @hanfei1991 @lamxTyler

plan: fix bugs when do natural join or join with using.

---

executor/join_test.go
plan/logical_plan_builder.go

This is a cherry pick pr.
PTAL @hanfei1991 @shenli @lamxTyler

plan: fix bugs when do natural join or join with using. (#4382)

---

expression/distsql_builtin.go
expression/expr_to_pb.go

expression: tiny fix.

---

util/codec/codec.go

codec: use reference instead of value copy of "[]types.Datum"

---

executor/executor_test.go
plan/logical_plan_builder.go
plan/task.go

This is a cherry-pick pr.
PTAL @shenli @hanfei1991 @lamxTyler

plan: fix bug when push topn down. (#4413)

---

executor/show.go
executor/show_test.go

Fix https://github.com/pingcap/tidb/issues/4426
Fix https://github.com/pingcap/tidb/issues/4425
@winkyao PTAL

executor: Fix DEFAULT output in SHOW CREATE TABLE

---

expression/builtin_compare.go
expression/builtin_string.go
expression/integration_test.go
store/tikv/mock-tikv/mvcc.go

Fixed word misspelled

---

statistics/update.go
util/filesort/filesort.go

should use time.Since instead of time.Now().Sub

should use time.Since instead of time.Now().Sub

---

executor/join.go
infoschema/tables.go
plan/physical_plan_builder.go
util/ranger/new_refiner.go

Optimize merging array elements

Optimize merging array elements

---

distsql/xeval/eval_compare_ops.go
expression/builtin_time.go

should use strings.Contains() instead of strings.Index()

should use strings.Contains() instead of strings.Index()

---

server/server_test.go
server/tidb_test.go

server: fix compile failure when running race tests

---

expression/builtin_other.go
expression/builtin_other_test.go
expression/integration_test.go
plan/typeinfer_test.go

to #4080
PTAL @zz-jason @breeswish @jackysp

expression, plan: rewrite builtin funcs setvar, getvar

---

util/systimemon/systime_mon_test.go

Variable `jumpForward` has race condition.

util/systimemon: fix test race

---

_vendor/src/github.com/BurntSushi/toml/COPYING
_vendor/src/github.com/BurntSushi/toml/decode.go
_vendor/src/github.com/BurntSushi/toml/decode_meta.go
_vendor/src/github.com/BurntSushi/toml/doc.go
_vendor/src/github.com/BurntSushi/toml/encode.go
_vendor/src/github.com/BurntSushi/toml/encoding_types.go
_vendor/src/github.com/BurntSushi/toml/encoding_types_1.1.go
_vendor/src/github.com/BurntSushi/toml/lex.go
_vendor/src/github.com/BurntSushi/toml/parse.go
_vendor/src/github.com/BurntSushi/toml/type_check.go
_vendor/src/github.com/BurntSushi/toml/type_fields.go
glide.lock
glide.yaml

prepare for https://github.com/pingcap/tidb/pull/4509

vendor: add BurntSushi/toml

---

executor/analyze.go
store/tikv/coprocessor.go
util/types/datum.go
util/types/datum_test.go

distsql,store/tikv: fix analyze table OOM (#4399)

---

executor/aggregate_test.go
perfschema/const.go
perfschema/init.go

perf_schema: add required tables of mysqlx

---

new_session_test.go
session_test.go

1. move InTrans test
2. move Prepare Retry test
3. move Auth Test
4. Remove Substring_index test, which is in expression's test.

session_test: move some tests.

---

executor/show.go
executor/show_test.go

executor: Fix show create table with fk (#4537)

---

executor/show.go
mysql/charset.go
mysql/const.go
server/driver_tidb.go
server/tidb_test.go

[cherry-pick to pre-ga]executor,mysql: fix #4540, Navicat for MySQL compability of show create table(#4544)

---

plan/cbo_test.go
plan/dag_plan_test.go
plan/explain_test.go
plan/resolver_test.go
plan/typeinfer_test.go
plan/validator_test.go
statistics/selectivity_test.go
util/testleak/leaktest.go

Domain have many background goroutines bind to it.
If we forget to close it:
1. make leak may fail
2. make race may fail, because the background goroutines may still visiting store after store is closed.

plan,statistics: don't forget to close domain in testing

---

ddl/ddl_db_test.go
domain/domain_test.go

Hopes it would be more stable.

ddl,domain: make test leak more stable

---

ddl/ddl_db_test.go

1. Remove the useless bootstrap in tests.
2. Split the TestIndex to locate the specific function rows if the test is failed.

ddl: Clean up tests

---

mysql/const.go

Make it consistent with TiKV and PD.

Update version to 0.9.0 on pre-ga

---

domain/domain.go

domain: fix goroutine leak in auto analyze worker

---

expression/builtin_compare.go
expression/builtin_control.go
util/types/eval_type.go
util/types/field_type.go
util/types/field_type_test.go

expression, types: remove the usage of "TypeClass" in "builtin_compare.go"

---

ddl/ddl_db_test.go

change ddl_db_test's store to mocktikv

ddl_test: use mock tikv store

---

mysql/errcode.go
mysql/errname.go
store/tikv/backoff.go
store/tikv/error.go
terror/terror.go

```
MySQL [mysql]> select * from tidb;
ERROR 9001 (HY000): PD server timeout[try again later]
MySQL [mysql]> select * from tidb;
ERROR 9002 (HY000): TiKV server timeout[try again later]
```

store/tikv: simplify error messages that return to mysql client.

---

domain/domain.go
store/tikv/kv.go

domain: add prometheus interceptor to etcd client's grpc dial option

---

new_session_test.go
session.go
session_test.go
tidb_test.go

move a test of issue #1435 . @zimulala PTAL
I change the way of test, every txn is called by sync. I think it's simpler.

session_test: move tests.

---

new_session_test.go
session_test.go

session_test: move test for last insert id.

---

expression/builtin_arithmetic_test.go
expression/builtin_compare_test.go
expression/builtin_control_test.go
expression/builtin_encryption_test.go
expression/builtin_info_test.go
expression/builtin_json_test.go
expression/builtin_math_test.go
expression/builtin_miscellaneous_test.go
expression/builtin_op_test.go
expression/builtin_other_test.go
expression/builtin_string_test.go
expression/builtin_test.go
expression/builtin_time_test.go
expression/evaluator_test.go
expression/util.go

expression: rewrite unit test for Minus and Plus

---

_vendor/src/github.com/pingcap/pd/pd-client/client.go
glide.lock
glide.yaml

ref https://github.com/pingcap/pd/pull/777

store/tikv: upgrade pd-client.

---

CONTRIBUTING.md

1. Fix a header level mistake.
2. Capitalize the first character.

Improve CONTRIBUTING.md documentation.

---

expression/aggregation/avg.go
expression/builtin_math.go
expression/builtin_time.go
expression/constant_propagation.go
expression/distsql_builtin.go
expression/expr_to_pb.go

expression: enforce error check

---

Dockerfile

See https://github.com/pingcap/tidb/pull/4527 Bumping golang version to 1.9.

*: Dockfile upgrade to golang:1.9

---

store/localstore/local_aggregate.go

Fix `make check` error.
> store/localstore/local_aggregate.go:70: declaration of "err" shadows declaration at store/localstore/local_aggregate.go:51

localstore: Fix make check shadow

---

session.go

Tiny change, as the title says.

tidb: keep a record of user information in logCrucialStmt

---

statistics/metrics.go
statistics/update.go

stats: add metrics for auto analyze (#4793)

---

expression/builtin_other.go
expression/integration_test.go

[cherry pick] expression: correct the signature building of Values

---

_vendor/src/github.com/pingcap/mysqlx-driver/buffer.go
_vendor/src/github.com/pingcap/mysqlx-driver/capability.go
_vendor/src/github.com/pingcap/mysqlx-driver/connection.go
_vendor/src/github.com/pingcap/mysqlx-driver/const.go
_vendor/src/github.com/pingcap/mysqlx-driver/convert.go
_vendor/src/github.com/pingcap/mysqlx-driver/datatypes.go
_vendor/src/github.com/pingcap/mysqlx-driver/driver.go
_vendor/src/github.com/pingcap/mysqlx-driver/errors.go
_vendor/src/github.com/pingcap/mysqlx-driver/mysql41.go
_vendor/src/github.com/pingcap/mysqlx-driver/protocol.go
_vendor/src/github.com/pingcap/mysqlx-driver/result.go
_vendor/src/github.com/pingcap/mysqlx-driver/rows.go
_vendor/src/github.com/pingcap/mysqlx-driver/utils.go
_vendor/src/github.com/pingcap/mysqlx-driver/xconfig.go
glide.lock
glide.yaml

Update mysqlx driver:
1. implement Exec() method
2. replace old log and errors packages with Sirupsen/logrus and juju/errors
3. add a makefile for static check
4. fix some bugs
PTAL @shenli @coocood @wentaoxu

vendor: update mysqlx driver for X protocol

---

executor/write.go
executor/write_test.go

This is a cherry-pick pr.
PTAL @hanfei1991 @shenli @coocood

executor: fix bug when auto_increment meets unsigned. (#4824)

---

executor/write_test.go
plan/logical_plan_builder.go

[cherry pick]executor, plan: add cast for the expr of assignments of updateList

---

expression/column.go
expression/integration_test.go

The problem is commented in the code.
PTAL @shenli @zz-jason @coocood

expression: fix a bug occured in select sum(float col)*0.1

---

expression/column.go
expression/integration_test.go

[cherry pick]  expression: fix a bug occured in select sum(float col)*0.1

---

store/tikv/gc_worker.go
store/tikv/kv.go

gc_woker: start safePointChecker before run worker. 

---

plan/stats.go

Add length check to prevent index out of range

---

store/tikv/coprocessor.go

store/tikv: fix a check visibility bug. 

---

Jenkinsfile

after this pr, branch **release-1.0** of **tidb** will use test case in branch **1.0.0** of **tidb-test**

jenkins: use tidb-test:1.0.0 in tidb:release-1.0

---

executor/show_test.go
plan/planbuilder.go

PTAL @shenli @zz-jason @coocood

[cherry pick]executor, plan: correct the schema type of ShowStmt

---

parser/parser.y
parser/parser_test.go

parser: add numeric type signed opt support

---

expression/builtin_other.go
expression/integration_test.go

expression: fix values null value issue

---

ast/misc.go
ddl/ddl.go
ddl/ddl_db_test.go
ddl/ddl_worker.go
ddl/ddl_worker_test.go
ddl/index.go
ddl/reorg.go
executor/builder.go
executor/executor.go
executor/executor_test.go
inspectkv/inspectkv.go
inspectkv/inspectkv_test.go
model/ddl.go
model/model_test.go
parser/misc.go
parser/parser.y
parser/parser_test.go
plan/planbuilder.go
plan/plans.go

*: Support the operation of `cancel DDL jobs` (#4753)

---

executor/merge_join_test.go
plan/column_pruning.go
plan/dag_plan_test.go
plan/eliminate_projection.go

cherry pick #4882 #4828 
PTAL @shenli @winoros

cherry pick #4882 #4828

---

executor/adapter.go
tidb-server/main.go

Cherry pick to release 1.0
Need to merge this on first https://github.com/pingcap/tidb/pull/4934

executor: log success/fail for slow-query

---

Makefile
mysql/const.go

The release version would be like `v1.0.0-69-gd122f582` if it's not exact tag, if the commit is on exact tag, it would be the tag name.

Makefile: use git describe to assign TiDBReleaseVersion.

---

statistics/histogram.go
statistics/statistics_test.go

PTAL @coocood  @hanfei1991  @winoros

stats: fix estimation in index point query

---

ddl/column.go
ddl/ddl.go
ddl/ddl_test.go
ddl/index.go
ddl/schema.go
ddl/table.go
ddl/util/event.go
executor/simple.go
statistics/ddl.go
statistics/handle.go

change ddl_test's storage to mock-tikv

ddl, statistics: resolve the package dependency.

---

domain/domain_test.go
infoschema/infoschema_test.go
meta/meta_test.go
structure/structure_test.go
util/admin/admin_test.go
util/prefix_helper_test.go

*: change some tests' storages to mock-tikv

---

config/config.go
config/config.toml.example

config: redundant names

---

plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/physical_plan_test.go

Cherry-pick.
PTAL @zz-jason @hanfei1991 @shenli

plan: selection to dual directly if condition is always false. (#4980)

---

ddl/column.go
ddl/ddl_db_test.go
ddl/index.go
ddl/reorg.go
domain/schema_validator.go

* ddl: add log details and tests

ddl: Add log details and tests (#5021)

---

_vendor/src/github.com/pingcap/pd/pd-client/client.go
glide.lock
glide.yaml

vendor: update pd-client which add opentracing

---

_vendor/src/github.com/pingcap/pd/pd-client/client.go
glide.lock
glide.yaml

Fix a nil pointer dereference in pd client.
https://github.com/pingcap/pd/pull/838

vendor: update pd client

---

store/tikv/2pc.go
store/tikv/2pc_test.go
store/tikv/region_request.go

store/tikv: set undetermined error if not recover from an rpc error.

---

executor/index_join.go

executor: let batch size of index join increase slowly.

---

ddl/reorg.go

ddl: Update reorg wait time (#4808)

---

plan/explain.go
plan/logical_plans.go
plan/plan.go
plan/predicate_push_down.go

remove addChild and addParent from interface Plan

plan: tiny clean.

---

executor/adapter.go
table/tables/tables.go

Add transaction TS to log in debug level.

executor: Add debug logs

---

expression/typeinfer_test.go

as the title says
PTAL @hanfei1991 @zz-jason

plan, expression: move typeinfer_test.go from plan to expression

---

executor/write.go
expression/integration_test.go
types/datum.go
types/json/json.go
types/json/json_test.go
types/row.go

for #5064 #5084 
Add 'deepcopy' maybe not suitable, PTAL.

types: add deepcopy for update operation

---

plan/column_pruning.go
plan/plan.go
plan/stats.go
plan/task.go

modify variables
@hanfei1991 PTAL

plan: do some preallocate of slice.

---

executor/join_result_generators.go

Remove ineffectual assignment to joinedRow.

Remove ineffectual assignment to joinedRow

---

bootstrap.go
session.go

Remove unused return

---

store/tikv/coprocessor.go

Cherry pick.
PTAL @hanfei1991 @zimulala

coprocessor: enable push float down to tikv. (#4967)

---

executor/executor_test.go
plan/topn_push_down.go

plan, executor: deep clone TopN when push it down through Join (#5158)

---

executor/builder.go
executor/distsql.go
executor/union_scan.go
model/model.go
plan/column_pruning.go
plan/initialize.go
plan/logical_plan_builder.go
plan/logical_plans.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/planbuilder.go

plan, executor: remove NeedHandle field

---

executor/write.go
executor/write_test.go

…amp 5172 (#5176)
PTAL @shenli

executor: Cherry pick pull request #5176

---

store/tikv/region_cache.go
store/tikv/region_cache_test.go

store/tikv: fix region cache data race.

---

executor/write.go
table/tables/tables.go

executor: simplify logic

---

mysql/errcode.go
mysql/errname.go
mysql/state.go
plan/build_key_info.go
plan/dag_plan_test.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/logical_plans.go
plan/physical_plan_builder.go
plan/plan.go
plan/planbuilder.go
plan/property_cols_prune.go

throw out error if index hint not exist

---

table/tables/tables.go

table: tiny clean up and add logs

---

store/tikv/region_cache.go

store/tikv: fix data race caused by race fixing.

---

plan/column_pruning.go

analyze will no longer call column prunning.

plan: clean code.

---

plan/dag_plan_test.go
plan/logical_plan_builder.go
plan/physical_plan_builder.go

Hints for join will fail when construct semi join plan.
PTAL @hanfei1991 @zz-jason @lamxTyler

plan: fix the join plan's hints.

---

ddl/ddl.go

Small error message spelling mistake.

ddl: fix spelling

---

plan/gen_physical_plans.go
plan/physical_plan_builder.go

plan: pick `generatePhysicalPlans` to one file.

---

executor/simple.go

executor: notify TiDB update privilege after alter/drop user (#5226)

---

config/config.go
config/config.toml.example
server/conn.go

In case we need to use the old row executor.

config: add an option to disable chunk

---

domain/domain.go
domain/domain_test.go
tidb.go

domain: refactor NewDomain

---

util/kvencoder/kv_encoder.go
util/kvencoder/kv_encoder_test.go

@coocood @shenli @winkyao  PTAL

util : fix problem of kvencoder accessing database without creating in advance 

---

Makefile
store/tikv/2pc_fail_test.go
store/tikv/2pc_test.go
store/tikv/sql_fail_test.go
store/tikv/store_fail_test.go
store/tikv/store_test.go

use `make gofail` to run tests with gofail.

*: fix gofail test.

---

plan/task.go

Cherry pick to release 1.0
PTAL @shenli @coocood @hanfei1991

plan: the schema topN that is pushed down isn't set correctly. (#5305)

---

new_session_test.go
sessionctx/varsutil/varsutil.go

*: session variable value should not be modified when get global variable

---

ast/ast.go
distsql/distsql.go
executor/adapter.go
executor/distsql.go
executor/executor.go
executor/sort.go
new_session_test.go
server/conn.go
server/driver.go
server/driver_tidb.go
statistics/boostrap.go
statistics/sample_test.go
statistics/statistics_test.go
store/tikv/mocktikv/analyze.go
tidb.go

@coocood @zz-jason @XuHuaiyu PTAL

*: add a "context.Context" parameter for "NextChunk"

---

executor/builder.go
executor/write.go

executor: support Chunk for InsertExec

---

server/region_handler.go
server/region_handler_test.go
store/tikv/pd_codec.go

store/tikv:fix bug in GetRegionByID

---

executor/builder.go
executor/set.go

executor: support Chunk for SetExecutor

---

x-server/server.go

Add ignored import for mysqlx to avoid glide-update to prune them. PTAL @coocood @hicqu

xprotocol: import for mysqlx

---

executor/builder.go
executor/executor.go

executor: support Chunk for SelectLockExec

---

executor/simple.go
sessionctx/variable/session.go
statistics/update_test.go

*: clear delta info when roll back transaction (#5390)

---

executor/show.go
executor/show_test.go

executor: fix issue 5384 (#5414)

---

plan/initialize.go
plan/logical_plans.go
plan/physical_plan_builder.go
plan/physical_plans.go
plan/plan.go
plan/predicate_push_down.go
plan/stats.go
plan/task.go
plan/topn_push_down.go

put base plan inside logical base plan and physical base plan

plan: put base plan inside logical base plan and physical base plan.

---

plan/logical_plan_test.go

extract test for subquery decorrelation.

plan: adjust logical plan test

---

plan/explain.go
plan/planbuilder.go
plan/plans.go

change the way of setting parent in explain.

plan: second step of removing parents

---

executor/join_test.go
executor/new_index_lookup_join.go

In row.GetDatum: `d.SetBytes(r.GetBytes(colIdx))`
In row.GetBytes: `return col.data[start:end]`
In datum.SetBytes: `d.b = b`
No new space allocated so the Next()'s return value may share the same space. Causing wrong result. In added test, current master will return 
```
+------+
| a    |
+------+
| 3    |
| 3    |
| 3    |
+------+
```
PTAL @hanfei1991 @shenli @coocood

executor: fix a bug of NewIndexLookUpJoin's Next().

---

plan/aggregation_push_down.go
plan/decorrelate.go
plan/eliminate_projection.go
plan/expression_rewriter.go
plan/join_reorder.go
plan/logical_plan_builder.go
plan/plan.go
plan/planbuilder.go
plan/predicate_push_down.go
plan/topn_push_down.go
plan/util.go

plan: remove parents totally

---

executor/builder.go
executor/revoke.go

executor: support Chunk for RevokeExec

---

executor/builder.go
executor/prepared.go

executor: support Chunk for DeallocateExec

---

executor/builder.go
executor/simple.go

executor: support Chunk for SimpleExec

---

executor/analyze.go
executor/builder.go

executor: support Chunk for AnalyzeExec

---

executor/builder.go
executor/grant.go

executor: support Chunk for GrantExec

---

executor/builder.go
executor/write.go

 executor: support Chunk for LoadData

---

plan/column_pruning.go
plan/gen_physical_plans.go
plan/logical_plan_builder.go
plan/predicate_push_down.go
plan/topn_push_down.go

I uniform the schema of ua and its children to avoid extra cost.
and physical union all cannot pass order prop.

plan: refine UnionAll building

---

session.go
session_test.go

load timezone from tikv when start a tidb-server (#5393)

---

ddl/ddl_db_test.go

Update the cancel DDL job test.
It's hard to cherry pick, so I update it directly.

ddl: Update the cancel DDL job test

---

executor/show.go
executor/show_test.go

executor: wrong format of show create table (#5463)

---

tidb-server/main.go

tidb: fix some case TiDB does not graceful shutdown expectly.

---

ast/ddl.go
parser/misc.go
parser/parser.y
parser/parser_test.go

Parse but ignore it.
Fix https://github.com/pingcap/tidb/issues/5525

parser: Support PACK_KEYS option in CreateTable statement

---

expression/aggregation/concat.go

expression: refine the type infer of group_concat

---

Makefile
util/printer/printer.go

Go version could be helpful when investigating some problems.

*: Add go version in tidb version info

---

executor/merge_join.go

- reduce `runtime.growslice` and `runtime.convT2I`
- remove the transformation between chunk rows and datum rows

executor: refactor the way to compare rows in MergeJoinExec

---

plan/gen_physical_plans.go
plan/physical_plan_test.go
plan/physical_plans.go
plan/task.go

KeepOrder is not needed and batch size is not one anymore.

plan: update index lookup join cost

---

executor/aggregate_test.go
expression/aggregation/concat.go

aggregation: "group_concat" should not modify the argument during execution

---

plan/aggregation_push_down.go
plan/build_key_info.go
plan/column_pruning.go
plan/decorrelate.go
plan/eliminate_projection.go
plan/expression_rewriter.go
plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/max_min_eliminate.go
plan/optimizer.go
plan/planbuilder.go
plan/predicate_push_down.go
plan/topn_push_down.go

Assign value may cause data race.
PTAL @hanfei1991 @zz-jason @lamxTyler

plan: no need to pass the ctx to logicalOptRule

---

README.md

Update the version label to 1.1 alpha

---

Makefile
cmd/importer/README.md
cmd/importer/config.go
cmd/importer/config.toml
cmd/importer/data.go
cmd/importer/db.go
cmd/importer/job.go
cmd/importer/main.go
cmd/importer/parser.go
cmd/importer/rand.go

Move importer tool to tidb so that we can use tidb's package directly without vendor. We need to improve importer to generate data that is closer to real world.

cmd: add importer tool.

---

executor/builder.go
executor/join_test.go
plan/column_pruning.go
plan/eliminate_projection.go
plan/logical_plan_builder.go

The code of #5383 in executor package is hard to pick up. So rewrite this part.
PTAL @XuHuaiyu @zz-jason @hanfei1991

release-1.0: only set DefaultValues in agg push down.

---

executor/builder.go
executor/executor.go

`MaxOneRow.NextChunk` does not really work before this commit.
PTAL @zz-jason @coocood

executor: fix MaxOneRow.NextChunk

---

executor/executor.go

executor: refine plan.EvalSubquery to support NextChunk

---

util/logutil/log.go
util/logutil/log_test.go

@shenli @tiancaiamao @coocood PTAL

log_util:let slow query entry keep order

---

plan/logical_plan_builder.go

Not really a big PR, but makes the context more clear. 😃

plan: fix typo in comments.

---

plan/logical_plan_builder.go

plan: reduce memory allocation in buildDataSource

---

model/ddl.go

Make the value clearer and reduce the possibility of errors when adding or modifying values.

model: remove iota

---

cmd/importer/config.go
cmd/importer/config.toml
cmd/importer/main.go

sepcify the config file and we can point out the stats file path. Prepare to generate data with stats.

cmd/importer: specify the config file

---

meta/autoid/autoid.go
meta/meta.go
metrics/meta.go
metrics/metrics.go

Add metrics for auto id allocation and meta operation.

meta: Add metrics for meta package

---

ddl/ddl.go
ddl/index.go
ddl/syncer.go
metrics/ddl.go

Move code and fix an issue reported by `goword`.
@zimulala @winkyao @coocood PTAL

ddl, metrics: Move DDL metrics from ddl package to metrics package

---

sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go
sessionctx/variable/varsutil_test.go
util/printer/printer.go

And log the config at server start.

variable,printer: add a session variable to show configuration.

---

statistics/update.go
statistics/update_test.go

For small table, we need not auto analyze.

stats: set a min count for auto analyze

---

metrics/stats.go
statistics/update.go

Add metrics for stats inaccuracy rate.

stats: add metrics for stats

---

Makefile
util/printer/printer.go

add build platform for tidb_version
PTAL @shenli @coocood

util: add GoVersion info for tidb_version

---

cmd/benchdb/main.go
store/tikv/gc_worker.go
store/tikv/gc_worker_test.go

cherry pick from master.
do GC parallel.

store/tikv: do gc parallel

---

domain/domain.go
metrics/domain.go

Move the `metrics.go` file and add a LoadPrivilegeCounter metric.

domain,metrics: move domain metrics, add privilege load counter

---

session.go
statistics/update_test.go

stats: fix panic when updating stats table

---

executor/executor_test.go
parser/parser.y
parser/parser_test.go

This is the valid grammar that can be parsed by MySQL: http://sqlfiddle.com/#!9/9eecb/14389. Therefore, I add lines of code and some tests in this PR. 😄

parser: parse "select 1 order by 1" statement

---

ddl/column.go
ddl/ddl_db_change_test.go

Merge adding column fix https://github.com/pingcap/tidb/pull/5878 with dropping column fix together.

(Cherry pick) ddl : fix panic in adding and dropping columns

---

executor/executor.go

This PR aims to add more comments in baseExecutor.

executor:add more comments for baseExecutor

---

sessionctx/variable/sysvar.go

variable: set `have_profiling` to `NO`

---

ast/ddl.go
executor/show_test.go
parser/parser.y
parser/parser_test.go

Syntax support for it will make TiDB working on more benchmark tools.

parser: support reference as a column option

---

config/config.go
config/config.toml.example
config/config_test.go
util/logutil/log.go

1. Fix typos.
2. Add upper limit and some default info.
3. Make template values consistent with default.
@coocood @tiancaiamao PTAL

config: update config template

---

ast/ast.go
executor/adapter.go
server/conn.go
server/driver.go
server/driver_tidb.go
statistics/statistics_test.go
store/mockstore/mocktikv/analyze.go
tidb.go

As the title says.
PTAL
@zz-jason @coocood

*: remove SupportChunk() from interface ResultSet and RecordSet

---

README.md

readme: add TiDB adopters

---

docs/tidb_http_api.md
server/http_handler.go
server/http_handler_test.go
server/http_status.go

Make sure the rowBin with slashes can be handled.
e.g.
rowBin=`CAIIyAEIBAIGYWJjCAYGAQCBCAgJ7/yY8LKF1M8Z`
Fix #5982

server, docs: change rowBin to request.

---

statistics/builder.go
statistics/statistics_test.go

stats: fix building too many buckets

---

executor/join.go
executor/join_result_generators.go
executor/merge_join_test.go

PTAL
@zz-jason  @coocood 
To #5985

executor: remove Next function for HashJoinExec

---

executor/merge_join.go

PTAL @zz-jason @coocood 
To #5985

executor: remove Next function for MergeJoinExec

---

plan/logical_plan_builder.go
plan/logical_plans.go
plan/planbuilder.go
statistics/table.go

- add some comments
- only add metrics when statistics is outdated
- fix typo, change `avalableIndices` to `availableIndices`

plan: tiny code refine for building DataSource

---

executor/executor_pkg_test.go
executor/show.go
executor/show_test.go
server/tidb_test.go
session_test.go
util/arena/arena.go

PTAL @zz-jason @coocood
To [#5985](https://github.com/pingcap/tidb/issues/5985)

executor: remove Next function for ShowExec

---

executor/index_lookup_join.go

PTAL @coocood @zz-jason 
To #5985

executor: remove Next function for IndexLookUpJoin

---

statistics/histogram.go
statistics/update_test.go

stats: remove invalid range when split

---

executor/join_test.go
plan/logical_plans.go

Join's equal condition may become single side condition after substitution.
See added unit for more details.
PTAL @lamxTyler @zz-jason

plan: fix a bug when do column substitution for join.

---

expression/aggregation/explain.go
expression/column.go
expression/constant.go
expression/explain.go
expression/scalar_function.go
parser/parser_test.go
plan/explain.go
plan/preprocess.go
types/mydecimal_test.go

1. func isConstraintKeyTp check `the first column of constraint is auto_increment`, code can be more clearly.
2. func XXXTableStmt check `Table == nil`, It looks like it's not necessary.
3. func checkAlterTableGrammar only check first new column, It is better to check multi new columns, though this feature is not supported at present.
4. fix typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/5343)

*: remove useless code 

---

executor/aggregate_test.go
types/datum.go

types: support converting json to float64

---

domain/schema_validator_test.go

I suspect the test environment is affect by the machine load, then `time.Now()` may drift from the time it's actually called.
So I extend lease to 10ms
@winkyao @zimulala

domain: make schema validator test more stable

---

util/ranger/ranger_test.go

fix https://github.com/pingcap/tidb/issues/6129

util/ranger: Improve the aesthetics of code review

---

executor/distsql.go

This commit pushes some flags to the coprocessor,
for further supporting handling warnings in the coprocessor.
PTAL @coocood @zz-jason @AndreMouche

executor: push some flags down to coprocessor

---

kv/txn.go

Reduce twice judgments when the transaction is running normally and make `RunInNewTxn` more readable.

kv: tiny clean up

---

ddl/ddl_worker_test.go

The `testCreateIndex` will use the system schema version to check the job's `SchemaVersion`. After finishing the normal index(idx_normal) there are still two cancelled jobs in the `DDLJobList`. And They can update the system schema version. So when `testCreateIndex` checks the job's `SchemaVersion`, the system schema may be updated by other canceled jobs. 
The `TestCleanJobs` will be removed after we initially support the parallel DDL. So now I remove the unstable check to fix it.

ddl: remove the unstable check

---

expression/constant.go

If DeferredExpr is nil. We can just return itself.
PTAL @zz-jason @XuHuaiyu @coocood

expression: optimize the `Clone` of Constant.

---

table/tables/tables.go

table/tables: add logs when column offsets are wrong

---

executor/show.go
executor/show_test.go
model/model.go

support table partition in show create table statement.

executor: support table partition in show create table stmt

---

ddl/ddl_db_change_test.go
ddl/ddl_db_test.go
executor/write.go
table/tables/tables.go

Rewrite some parts of the original pull request. @zimulala @coocood PTAL

(cherry pick) *: fix writing null value into not null column in write-only state.

---

expression/aggregation/agg_to_pb_test.go
expression/expr_to_pb_test.go
util/mock/client.go

1. remove mockKvClient, use `mock.Client` instead
2. update `mock.Client`

expression: remove mockKvClient

---

sessionctx/variable/session.go
sessionctx/variable/varsutil_test.go

Make it organized and easy to write verify test.

variable: group same kind of variables into structs.
