.github/ISSUE_TEMPLATE/bug-report.md

restore `What did you see instead` in bug report
restore `What did you see instead` in bug report
Tests 
- No code
- No Release note

.github: restore `What did you see instead` in bug report

---

config/config.go
config/config.toml.example

Issue Number: close #17371 
We need to change deafult `oom-action` to `"log"` in GA version since it is experimental, does not have full metrics and is not fully tested.
Tests 
- No code

config: Change default oom-action to "log"

---

executor/analyze_test.go

Issue Number: close #16369
Problem Summary: failpoint cause data race in analyze test. which makes other tests failed.
What's Changed: make the failpoint test unparalleled.
Tests 
- Unit test
Side effects
- fix failpoint race for analyze test

executor: fix failpoint race for analyze test

---

server/http_status.go

Usage
```
➜  tidb git:(pd-hotfix-stale) ✗ curl http://127.0.0.1:10080/runtime/gc
"Manual GC successfully in 3.2281ms"
```

Add HTTP API for manual GC

---

planner/core/util.go
server/http_status.go

How it Works:
- PR to update `pingcap/tidb-ansible`:
Tests 
- Unit test
- No code
Side effects

Fix panic and add manual free os memory

---

executor/adapter.go
executor/executor.go
util/disk/tracker.go
util/memory/tracker.go
util/memory/tracker_test.go

How it Works:
- PR to update `pingcap/tidb-ansible`:
Tests 
- Unit test
- No code
Side effects

Util: Fix global tracker mutex contention (#16298)

---

executor/executor.go
sessionctx/context.go

Cherry-pick #15685 to release 4.0, the automated-tests will fail without this
How it Works:
Tests 
- Unit test
Side effects
- Add connection id for lock keys committer

add connection id for lock keys committer(#15685)

---

go.mod
go.sum

Fixes the failed test in https://github.com/pingcap/tidb/pull/17397
https://github.com/ngaut/unistore/pull/392
Tests 
- Unit test
- no release note

update unistore to fix unstable test

---

util/chunk/chunk.go

This problem is already resolved by https://github.com/pingcap/tidb/pull/14278
`No release note`.
-

util/chunk: Remove outdated comment about Time

---

executor/batch_point_get.go
executor/builder.go
executor/executor.go
executor/insert_test.go
executor/point_get.go
executor/point_get_test.go

support batch get on cluster index
and add test-case to cover unique-key point/batch get
Proposal: https://github.com/pingcap/tidb/blob/master/docs/design/2020-05-08-cluster-index.md
What's Changed, How it Works:
support batch get on cluster index
and add test-case to cover unique-key point/batch get
- n/a
Tests 
- Unit test
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/17858)

executor: support batch-get cluster index & add test case

---

go.mod
go.sum

update `go.mod` to latest parser, branch `release-4.0`
- None

parser: update go.mod to latest parser

---

executor/point_get_test.go
planner/core/find_best_task.go

Issue Number: close https://github.com/pingcap/tidb/issues/18077
see more in issue
What's Changed, How it Works:
we also need check index column cover when IsIntHandlePath = false and IsCommonHandle = true
- n/a
Tests 
- Unit test
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/18078)

executor/planner: fix wrong point-get plan on cluster table

---

go.mod
go.sum

update br dependency to latest, current version has some statistics bug. the fix is in https://github.com/pingcap/br/pull/374
update br with go mod
How it Works:
- Unit test
Side effects

br: update dependency to latest 4.0

---

cmd/ddltest/column_test.go
cmd/ddltest/ddl_test.go
cmd/ddltest/index_test.go
ddl/column_change_test.go
ddl/column_test.go
ddl/db_partition_test.go
ddl/db_test.go
ddl/index_change_test.go
ddl/reorg.go
ddl/testutil/testutil.go
executor/admin.go
executor/ddl_test.go
executor/executor.go
infoschema/perfschema/tables.go
infoschema/tables.go
planner/core/exhaust_physical_plans.go
planner/core/find_best_task.go
planner/core/plan_to_pb.go
planner/core/planbuilder.go
table/table.go
table/tables/tables.go
table/tables/tables_test.go
util/admin/admin.go
util/rowDecoder/decoder.go

This PR is preparation to support `admin check table` on the clustered indexes.
- Refactor table.IterRecord to apply kv.Handle.
- Refactor `tipb.TableScan` constructor.
- Rename tiny things and add some comments.
How it Works:
Tests 
- Unit test
Side effects

*: refactor table.IterRecord and extract some methods

---

store/mockstore/unistore/mock.go

use Blob is slower on tpcC workload
- Set ValueThreshold to 0 to disable blob.
Tests 
- Only config change.

unistore: do not write blob file

---

domain/domain.go

cherry-pick #18074 to release-4.0
Tests 
- Unit test
Side effects
- Add context cancel for domain close

server: add context cancel for domain close (#18074)

---

ddl/db_test.go

Close https://github.com/pingcap/tidb/issues/18134
How it Works:
Tests 
- No code
Side effects
- No
- No.

ddl: make TestCreateTable pass normally

---

store/tikv/coprocessor.go

How it Works:
- PR to update `pingcap/tidb-ansible`:
Tests 
- Unit test
- No code
Side effects
-

store: remove the nil assignment

---

executor/index_lookup_merge_join.go

Issue Number: close #18196
Problem Summary: as the title says.
How it Works: add a variable to control it.
Tests 
- Unit test
Side effects
- fix data race for chunk resource channel in index merge join

executor: fix data race for chunk resource channel in index merge join

---

docs/design/2020-05-08-cluster-index.md

Problem Summary: fix typo in cluster-index proposal.
Tests 
Side effects

docs: fix typo in cluster-index proposal

---

store/mockstore/unistore/rpc.go

The Leak tests are not stable, like [this](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/41800/nodes/85/steps/285/log/?start=0).
The root cause is `RPCClient` doesn't check the server states and directly route request into a closed unistore.
The returned error will make some goroutines get stuck in `Backoff`.
Tests 
- Manual test: run leak test locally

mockstore: return error when store is closed

---

server/conn_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/18398
stable test in CI
What's Changed,How it Works:
using genport instead of const
- n/a
Tests 
- No code
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/18414)

test: make TestDispatchClientProtocol41 stable

---

domain/domain.go
domain/domain_test.go
domain/schema_checker.go
domain/schema_checker_test.go
domain/schema_validator.go
domain/schema_validator_test.go
executor/ddl.go
kv/kv.go
session/session.go
store/tikv/2pc.go
store/tikv/txn.go

Proposal: #17932 
1. Record information about  `action type` when applying schema diff, these information will be used by schema amender to check if a transaction is amendable, and try to do transaction amend based on it.
How it Works:
Tests 
- Unit test
Side effects
-

ddl: collect actionTypes for schema change

---

executor/infoschema_reader.go

fix #15527
```sql
[2020-07-13T06:10:50.139Z] ----------------------------------------------------------------------
[2020-07-13T06:10:50.139Z] FAIL: tables_test.go:901: testTableSuite.TestStmtSummaryTable
[2020-07-13T06:10:50.139Z] 
[2020-07-13T06:10:50.139Z] tables_test.go:906:
[2020-07-13T06:10:50.139Z]     tk.MustQuery("select column_comment from information_schema.columns " +
[2020-07-13T06:10:50.139Z]         "where table_name='STATEMENTS_SUMMARY' and column_name='STMT_TYPE'",
[2020-07-13T06:10:50.139Z]     ).Check(testkit.Rows("Statement type"))
[2020-07-13T06:10:50.139Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:62:
[2020-07-13T06:10:50.139Z] …
```

executor: fix bug of read information_schema.columns

---

executor/executor_test.go

Problem Summary: fix the failed test from #18277, because the error maybe come from `tikv` or `executor` module.
How it Works:
- update test of PR/18277

fix Test failed case from PR/18277

---

config/config.go
config/config.toml.example

Change the default value of OOMAction to OOMActionCancel.
How it Works:
- PR to update `pingcap/docs`/`pingcap/docs-cn`: https://github.com/pingcap/docs-cn/pull/3961
Tests 
existing test 
Side effects
N/A
- Change the default value of OOMAction to OOMActionCancel.

config: set the default value of OOMAction to OOMActionCancel

---

session/txn.go

`TxnState.GetMemBuffer` may be invoked concurrently. Because I am going to replace the memdb, just use a `Mutex` to fix this problem in this PR.

session: add a mutex in TxnState.initStmtBuf

---

kv/sandbox.go
kv/sandbox_test.go

Problem Summary: fix typo in kv.
Tests
- No code
No release note

kv: fix typos

---

metrics/grafana/tidb.json

Issue Number: close https://github.com/pingcap/tidb/issues/18154
Add the script.
How it Works:
Tests 
Side effects

metrics/grafana: add disconnection metrics script

---

ddl/db_test.go

Signed-off-by: Wang Ruichao <wangruichao2014@xiaochuankeji.cn>
fix error bug
TestCase: TestAddIndexWithDupIndex
Tests 
- Unit test
No release note; sorry for the bug I made...
-

ddl: fix test `TestAddIndexWithDupIndex`

---

store/mockstore/unistore/cophandler/cop_handler.go

close https://github.com/pingcap/tidb/issues/18575
Run `tidb-server` with `unistore`, you will see many error logs such as below:
```sql
[2020/07/16 16:05:16.969 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/16 16:05:16.972 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/16 16:05:19.969 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
```
Add empty executor runtime information for `unistore` cop handler.
Tests 
```shell
bin/tidb-server …
```

mockstore: add empty executor runtime information for unistore cop handler

---

executor/index_lookup_merge_join.go
executor/index_lookup_merge_join_test.go

Issue Number: close #18631
Problem Summary: keep descent order in index merge join is not correct.
What's Changed: sort it first and reserve before build range.
Tests 
- Unit test
Side effects
- fix wrong result for keep desc order in index merge join

executor: fix wrong result for keep desc order in index merge join

---

docs/design/2020-05-08-standardize-error-codes-and-messages.md

Fix standardize-error-codes-and-messages.md: it has wrong field description.
Correct the example of how to writing the error result.
How it Works:
Tests 
- No code
Side effects
-

docs: update 2020-05-08-standardize-error-codes-and-messages.md

---

.github/workflows/assign_question_bug.yml

How it Works:
Auto Assign issues to `In Progress: Handled to SIGs` column in `Question and Bug Reports` kanban if they're labeled to sig.
Tests 
- No code

.github: Auto Assign Question and Bug Reports

---

store/tikv/lock_resolver.go

We see the metric resolve lock is abnormal, but we do not know which lock key cause the conflict.
Read write does not conflict, so it does not matter.
Write write conflict should have been log here https://github.com/pingcap/tidb/blob/d1b728b278ef4fa8ca3bfe9ff898b81155dcd1d1/store/tikv/prewrite.go#L162
Before this change, the resolve lock rollback only record the resolveLite case.
How it Works:
Print log.
Tests 
- No code

store/tikv: print log when resolve lock rollback keys

---

go.mod
go.sum

Signed-off-by: AilinKid <314806019@qq.com>
Issue Number: close [#18873](https://github.com/pingcap/tidb/issues/18873)
update parser with https://github.com/pingcap/parser/pull/952
Tests 
as mentioned in https://github.com/pingcap/parser/pull/952
- parser: update parser to fix CI

parser: update parser to fix CI

---

executor/write_test.go
store/tikv/2pc_test.go
store/tikv/txn.go

Force disable local latches.
Tests 
- Unit test
-  Disable local latches.

tikv: force disable local latches

---

bindinfo/cache.go
bindinfo/handle.go
ddl/db_change_test.go
ddl/db_partition_test.go
ddl/foreign_key_test.go
distsql/request_builder.go
domain/topn_slow_query.go
executor/explain_test.go
session/pessimistic_test.go

Problem Summary: fix a lot of typos.
Tests
- Unit test
No release note

*: fix a lot of typos

---

executor/prepared_test.go

Issue Number: close #18833 
What's Changed: remove test leak for `TestPlanCacheClusterIndex`.
Tests 
- Unit test
- node.

executor: fix unstable leak test on TestPlanCacheClusterIndex

---

metrics/grafana/tidb.json

It is better to use heatmaps for some transaction pannels.
It is better to use heatmaps for some transaction pannels.
How it Works:
Tests 
- No code

metrics: use heatmap for some transaction pannels

---

metrics/tikvclient.go

TiDB supports larger transactions in 4.0. The metrics should enlarge its upper limit.
Enlarge upper limit.
How it Works:
Tests 

metrics: enlarge txn upper limit

---

ddl/db_change_test.go
ddl/ddl_test.go
ddl/index.go

Problem Summary: Tiny cleanup and fix typo
How it Works:
- Remove useless code in `makeupDecodeColMap `.
- Rename `SetInterceptoror` to `SetInterceptor`.
Tests 
- No code
Side effects
-

ddl: tiny cleanup and fix typo

---

.github/labeler.yml
.github/workflows/assign_project.yml

Signed-off-by: shirly <AndreMouche@126.com>
This PR update the labels for sigs
auto label sig's label when PR created
no
no
No release note

.github: update the label for sigs

---

executor/clustered_index_test.go
executor/mem_reader.go

Issue Number: close #19092 
The minimal reproducible case:
```sql
set @@tidb_enable_clustered_index=1;
drop table if exists t;
create table t (a int, pk char(10), c int, primary key(pk), key(a));
insert into t values (1, '111', 3);
begin;
update t set a = a + 1, pk = '222' where a = 1;
select pk, c from t where a = 2;
commit;
select pk, c from t where a = 2;
```
In `memIndexLookUpReader`, the `handleColIDs` field of row decoder should be initialized with primary key IDs. 
What's Changed: Omitted.
How it Works: Omitted.
N/A
Tests 
- Unit test
Side effects
N/A

executor: fix common handle index lookup in union scan

---

cmd/explaintest/r/explain_easy.result
executor/infoschema_reader.go
infoschema/tables.go

Issue Number: close #19201, BTW close #17288 
Tests 
- Unit test
Side effects
- display attribute `visible` in information_schema.tidb_indexes

executor, infoschema: display attribute `visible` in information_schema.tidb_indexes

---

server/http_handler_test.go
server/http_status.go
server/server.go

Issue Number: ref https://github.com/pingcap/tidb/issues/19075
How it Works:
listen port 0, just as https://github.com/pingcap/tidb/issues/19075#issuecomment-675334610 said
- no Need to cherry-pick to the release branch
Tests 
- only test
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/19266)

server: make http test listen on port 0

---

store/tikv/scan_test.go

Issue Number: close #19076 
Try to stabilize the scan test, this is possibly a debug try, may not solve it.
How it Works:
Tests 
- Unit test
Side effects

test: try to stablize scan test

---

.github/labeler.yml

Signed-off-by: shirly <AndreMouche@126.com>
Update the label for sig/execution from sig/executor
No release note

.github:update label for sig/execution

---

executor/join_test.go

Issue Number: a following PR for #11896 
Re-enable a test now that it passes again.
How it Works:
Tests 
- Unit test
- No code

executor: uncomment the join test for issue #11896

---

go.mod
go.sum

Issue Number: close #19076 
Update the dependency of `unistore`.
Tests 
- Unit test
Side effects

test: update unistore dependency

---

go.mod
go.sum

`terror.Log` can print stack trace for better debugging terror logs like https://asktug.com/t/topic/36843
How it Works:
Tests 

terror: add stack trace in terror log

---

config/config.go
config/config_test.go

Signed-off-by: Wang Ruichao <wangruichao2014@xiaochuankeji.cn>
Issue Number: close #18838 
How it Works:
Tests 
- Unit test
- No code
Side effects
Nope

config: refine config validation error message

---

executor/seqtest/seq_executor_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/18781 
As the title says
How it Works:
N/A
Tests 
Side effects
N/A

executor: make TestIssue18744 stable using failpoint

---

session/pessimistic_test.go

Issue Number: Try to close #19636 
Increase the default `managedLockTTL` for these tests and restore after finish.
How it Works:
Tests 
- Unit test
Side effects
- Try to stabilize some tests.

test: try to stable some tests

---

executor/index_lookup_join.go
expression/integration_test.go
types/datum.go

Issue Number: close #19654 
Didn't process converting enum/set to enum/set properly.
Precess them specially.
Tests 
- Unit test
- fix bug of converting enum and set

types: fix bug of converting enum and set

---

distsql/select_result.go
util/execdetails/execdetails.go
util/execdetails/execdetails_test.go

Issue Number: close #19788  
After #19207, explain analyze result for TiFlash is disordered, which make it very difficult to read.
How it Works:
Extract plan id from execution summaries for tiflash cop response
Tests 
- Unit test

executor: Extract plan id from execution summaries for TiFlash cop response

---

metrics/grafana/tidb_runtime.json

Some counter will be restted after restart, the delta may be negative.
Filter negative values

grafana: handle negative delta in runtime dashboard

---

store/mockstore/unistore/cophandler/analyze.go

splitted PR for https://github.com/pingcap/tidb/pull/18717
current unistore's analyze only support analyze one range in one analyze requests.
but https://github.com/pingcap/tidb/pull/18717 will send multi ranges in one analyze requests.
What's Changed, How it Works:
tiny change to support multi ranges in one analyze request in unistore
- n/a
Tests 
- Integration test(in following PRs)
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/19838)

unistore: support analyze multi-ranges

---

executor/inspection_profile.go

Add metric definition in metric profile to help the user understand the metric meaning.
eg:
Tests 
- Manual test
Side effects
- No
- Add metric definition in metric profile.

executor: add metric definition in metric profile

---

store/tikv/region_request.go

Issue Number: close #20029
What's Changed: you can check the comments in file change to know what happens.
Tests 
- Unit test
- fix unexpected retry region request when context cancel.

tikv: fix unexpected retry region request when context cancel

---

ddl/db_test.go
executor/batch_point_get.go
executor/builder.go
executor/point_get.go
kv/kv.go
session/pessimistic_test.go
session/schema_amender.go
session/schema_amender_test.go
session/session.go
store/tikv/2pc.go
store/tikv/2pc_test.go
store/tikv/region_cache.go
store/tikv/txn.go
table/tables/index.go

Cherry-pick #18447 to release 4.0 branch
How it Works:
Tests 
- Unit test
Side effects
- Part of pessimistic transaction amend new feature.
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)
- 300
* @SunRunAway

txn: support pessimistic transaction amend for specific ddls(#18447)

---

go.mod
go.sum

Issue Number: close #19868 
There may be some data race adding pessimistic locks and wake up waiters in unistore.
How it Works:
Tests 
- Unit test
Side effects
- Update the `unistore` version.

store: update unistore version

---

metrics/grafana/tidb.json
metrics/metrics.go
metrics/tikvclient.go
store/tikv/2pc.go

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
This PR adds metrics that counts async commit transactions.
This PR adds metrics that counts async commit transactions.
Tests 
- Unit test

2pc: Add counter metrics for async commit transactions

---

config/config.go
config/config.toml.example
config/config_test.go

Disable feedback by default temporarily.
Tests 
- Manual test

config: disable query feedback by default.

---

executor/insert_test.go
kv/kv.go
kv/memdb.go
kv/memdb_arena.go
kv/union_store.go
store/tikv/2pc.go
table/tables/index.go
table/tables/tables.go

Fix unreadable error message after #18372 merged
Use correct codec function to decode handle and index values.

*: fix message for duplicate entry error

---

ddl/placement_rule_test.go

Problem Summary: Refer to https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/53121/pipeline. I though the order is fixed after I moved to the new api, but not. So let us add the order-irelevant check logic back.
Tests
- Unit test

ddl: fix placement test

---

ddl/db_integration_test.go
ddl/error.go
ddl/index.go

Issue Number: close #20319 
What's Changed: error message for error expression index
How it Works: checking whether the column to be indexed is an expression, if yes then return the intended error
Tests 
- Unit test
Side effects

ddl: refine error message for expression index

---

config/config.go
config/config.toml.example
go.mod
go.sum
store/tikv/client.go

Issue Number: close #20429 
Add gRPC compression configs for TiDB.
How it Works:
Tests 
- Unit test
Check compression type work with TiKV
Side effects
- Add gRPC compression type config for TiDB.

tikvclient: add gzip compression type support for tidb grpc channel

---

store/tikv/client.go
store/tikv/region_request.go

Add region ID and type for `SendRequest` for tracing
How it Works:
Tests 

tikv: add region ID and type for tracing

---

store/tikv/2pc.go

A failpoint could lead to returning before `defer` statement.
Move a `defer` statement
Tests 
- No code

store/tikv: Move defer ttlManager.close

---

executor/explainfor_test.go
executor/parallel_apply_test.go

Fix the integration test problem introduced by #20422.
Move TestApplyWithOtherFeatures to a serial test suite.
N/A
Tests 
- Unit test
Side effects
N/A

tests: move TestApplyWithOtherFeatures to a serial test suite

---

executor/write_test.go

After https://github.com/pingcap/tidb/pull/20279.
This PR only add test for insert/update/delete list [columns] partition.
Tests 
- No code
Side effects
- No
- No.

executor: add test for insert/update/delete list [columns] partition

---

ddl/ddl_api.go

Issue Number: close https://github.com/pingcap/tidb/issues/17270
Improve error messages
Tests 
- No code

ddl: provide more details about primary key error

---

executor/analyze_test.go

Issue Number: #20574 
There is no particularly good solution, and it affects CI, so skip it now.
Side effects
- 

test: skip TestDefaultValForAnalyze

---

bindinfo/bind_test.go
bindinfo/handle.go
executor/compiler.go
planner/core/hints.go
planner/core/preprocess.go
planner/core/preprocess_test.go
planner/core/testdata/plan_suite_out.json
planner/optimize.go
session/session_test.go
util/hint/hint_processor.go
util/stmtsummary/statement_summary.go
util/stmtsummary/statement_summary_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/15827
Not a problem, this is an enhancement of SQL bind to support Delete / Update.
- parser PR: https://github.com/pingcap/parser/pull/1067, merged;
- adjust SQL bind / SPM code to take Delete / Update into consideration as well;
Tests 
- Unit test: to be added
Side effects
N/A
- Support SQL bind for Update / Delete.

*: support SQL bind for Update / Delete / Insert / Replace

---

planner/core/rule_column_pruning.go
session/session_test.go

Fix #19336 on the release-4.0 branch.
Fix the check function and the possible compile error for select .. lock in share.
How it Works:
Tests 
- Unit test
Side effects

plan: fix lock in share mode compile error

---

expression/integration_test.go
planner/core/exhaust_physical_plans.go

PR21201 is not correct.
-
Tests 
- Unit test
Side effects

planner: make index-hash-join and index-merge-join consider the collation in the right way

---

expression/aggregation/base_func.go

Some parts of PR #19857 cause the MySQL test fails.
Revert some parts of PR #19857.
Tests 
Side effects

expression: revert some changes to fix mysql_test

---

sessionctx/variable/session.go

`stmtFuture` is useless after refactor.
How it Works:
Delete it.
Tests 
- Unit test

variable: cleanup code

---

util/testleak/leaktest.go

Cherry pick part of https://github.com/pingcap/tidb/pull/19526  and  https://github.com/pingcap/tidb/pull/18286 to make leak test stable
util/testleak
How it Works:
Tests 
- Unit test

test: stabilize leak test #19526

---

go.mod
go.sum

update the tools dependence
need cherry pick to 4.0
Tests 
- Unit test

*: update the tools dependence

---

executor/aggregate_test.go

Issue Number: close #21263 
Problem Summary: decrease precision in this test to avoid float precision problem
decrease precision in this test to avoid float precision problem
Tests 
- Unit test
- executor: fix test problems in TestIssue20658

executor: fix test problems in TestIssue20658

---

go.mod
go.sum

This is for below issues:
* https://github.com/pingcap/sysutil/pull/24
* https://github.com/pingcap/sysutil/pull/25
* https://github.com/pingcap/sysutil/pull/22
Tests 
- No code
Side effects
- N/A
- N/A

*: update go.mod for sysutil

---

executor/aggregate_test.go

Issue Number: close #21263 
Problem Summary: decrease precision in this test to avoid float precision problem
decrease precision in this test to avoid float precision problem
Tests 
- Unit test
- executor: fix test problems in TestIssue20658

executor: fix test problems in TestIssue20658 

---

ddl/ddl_worker.go

Issue Number: close #21384 
N/A
Tests 
- No code
Side effects

ddl: change a log's level from error to warn 

---

ddl/db_test.go
ddl/ddl_api.go
ddl/error.go

Issue Number: close #11425 
return an error if the alter table option is invalid
Tests 
- Unit test
Side effects

ddl: return an error if the alter table option is invalid

---

ddl/db_integration_test.go
ddl/index.go

Issue Number: close #20320 
Special handle for the hidden column.
Tests 
- Unit test
Side effects

ddl: refine the error message for the expression index on primary key

---

ddl/db_test.go
ddl/ddl_api.go

Issue Number: close #14116 
If the candidate's name is too long, truncate the original name to 30. This is compatible with MySQL.
Tests 
- Unit test
Side effects

ddl: get a correct name for long anonymous index

---

ddl/placement_sql_test.go

Remove the debug code and add the forgotten`begin` sql.
Tests 
- Unit test

ddl: revise TestTxnScopeConstraint

---

executor/set_test.go

Issue Number: 
close https://github.com/pingcap/tidb/issues/21030
close https://github.com/pingcap/tidb/issues/21154
close https://github.com/pingcap/tidb/issues/21264
`TestSetVar` will set many global variables.
Tests 
- No code
- no

executor: stabilize TestInsertIntoGivenPartitionSet

---

ddl/db_test.go
ddl/ddl_api.go
ddl/ddl_worker.go
ddl/ddl_worker_test.go
ddl/index.go
ddl/placement_sql_test.go
ddl/rollingback.go
ddl/sequence.go
server/conn.go
server/conn_stmt.go
server/conn_test.go
server/driver_tidb.go
server/http_handler.go
server/server.go
server/server_test.go
server/tidb_test.go
server/util.go
server/util_test.go
session/pessimistic_test.go
session/schema_amender.go
session/session.go
session/session_test.go

Issue Number: part of https://github.com/pingcap/tidb/issues/20859
`gocritic` warns of over 1000+ issues. This PR fixes a chunk of some of the easiest issues in the packages ddl, server, session.
I thought it was important to fix the obvious issues first, and isolate to the DDL team. But this is only a small slice of the total issues :(
How it Works:
Tests 
- No functionality changes
Side effects
- Minimal

ddl, server, session: make gocritic happy

---

config/config.go
config/config.toml.example
go.sum
store/tikv/coprocessor.go
store/tikv/coprocessor_cache.go
store/tikv/coprocessor_cache_test.go

Allow changing maxRanges config for Coprocessor cache.
Add a new config.
How it Works:
- PR to update `pingcap/docs`/`pingcap/docs-cn`: We can keep this config hidden since in near future this config will be dropped.
Tests 
- Unit test
- Manual test
- Support changing Coprocessor cache max ranges admission policy in config files.

coprocessor: Support changing maxRanges

---

ddl/column_type_change_test.go
executor/executor_test.go
types/convert.go
types/datum.go

Issue Number: close #12178  
How it Works: use convertToDecimal instead of convertToFloat64
- Need to cherry-pick to the release branch 4.0
Tests 
Side effects
- N/A

expression, json: fix converting from string to decimal

---

session/pessimistic_test.go

Try to stablize test case `TestOptimisticConflicts`. Testing failed like [link](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/66257/pipeline).
Increase the pessimistic lock `managedLockTTL` so that resolve lock timeout will occur before lock expire.
How it Works:
Tests 
- Unit test
Side effects
-  No release note.

test: stablize test case

---

executor/sort_test.go
util/chunk/disk.go

How it Works:
Tests 
Side effects

executor: add error trace to investigate unstable test Issue16696

---

table/tables/tables_test.go

```
[2020-12-14T06:38:19.913Z] WARNING: DATA RACE
[2020-12-14T06:38:19.913Z] Write at 0x00c005417650 by goroutine 112:
[2020-12-14T06:38:19.913Z]   github.com/pingcap/tidb/store/tikv.(*tikvTxn).close()
[2020-12-14T06:38:19.913Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/tikv/txn.go:311 +0x41
[2020-12-14T06:38:19.913Z]   github.com/pingcap/tidb/store/tikv.(*tikvTxn).Commit()
[2020-12-14T06:38:19.913Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/tikv/txn.go:283 +0x7e1
[2020-12-14T06:38:19.913Z]   github.com/pingcap/tidb/session.(*TxnState).Commit()
[2020-12-14T06:38:19.913Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/txn.go:2 …
```

table/tables: fix a DATA RACE in a unit test case

---

executor/executor_test.go
expression/expression.go

Issue Number: close #12201 
What's Changed: add handling for hybrid data types when evaluate bool
Tests 
Side effects

expression: handle hybrid field types for where clause

---

session/pessimistic_test.go
store/mockstore/mocktikv/mvcc_leveldb.go
store/tikv/2pc.go
store/tikv/2pc_test.go
store/tikv/lock_resolver.go
store/tikv/lock_test.go
store/tikv/txn.go

Cherry-pick #21689  to release-3.0 branch.
How it Works:
Tests 
- Unit test
Side effects
- Fix the resolved txn status cache for pessimistic transactions.

txn: fix the resolved txn status cache for pessimistic txn(#21689)

---

store/mockstore/unistore/cophandler/mpp.go

MPP mock test may hit data race issue
How it Works:
add lock to avoid data race issue
Tests 
Side effects

test: fix potential data race in mpp mock test

---

config/config.go
config/config.toml.example
config/config_util.go
domain/domain.go
executor/simple.go
executor/simple_test.go
infoschema/tables.go
tests/globalkilltest/config.toml
tests/globalkilltest/global_kill_test.go
util/processinfo_test.go

- Add a switch to disable global kill by default. It'll be set to true by default when been tested fully.
- Recover the configuration item CompatibleKillQuery.
How it Works:
Tests 
- No code
Side effects
N/A
- Add a configuration item enable-global-kill with default value false.

*: add enable-global-kill with default value FALSE

---

tests/globalkilltest/run-tests.sh

Add start cluster in globalkilltest and make it happy in CI
How it Works:
- None
Tests 
- No code, just modify test script
Side effects
- None
-

*: Add start cluster in  run-tests.sh in globalkilltest

---

ddl/ddl_api.go
ddl/ddl_worker.go
ddl/partition.go
ddl/placement/const.go
infoschema/infoschema.go
infoschema/infoschema_test.go

Cherry-pick #21910 
Tests 
- Unit test
Same to #21910.

ddl: inherit placement rules from the parent (#21910)

---

util/memory/meminfo.go

Add a cache for memory info when the cluster is deployed in container
How it Works:
Tests 
- Unit test
- No code
Side effects
- Add a cache for memory info when the cluster is deployed in container.

util: add cache for mem info in container

---

go.mod
go.sum

We fixed several bugs for parser in 4.0, TiDB should update parser dependency to make them take effect.
Update go.mod and go.sum
N/A
Tests 
- No code
Side effects
N/A
- update parser dependency

mod: update parser to latest 4.0 version

---

ddl/partition.go

Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Issue Number: close #22325
Problem Summary: Error handling code for truncating partition looks suspicious. This PR try fixing it with checking error with correct variable.
Error handling code for truncating partition looks suspicious. This PR try fixing it with checking error with correct variable.
How it Works:
Error handling code for truncating partition looks suspicious. This PR try fixing it with checking error with correct variable.
Side effects

ddl: fix a typo when truncating table partition

---

executor/executor_test.go
session/session_test.go

The detail design of staleness transaction, please see: https://github.com/pingcap/tidb/issues/19817
This is test improving for staleness transaction, here is the [test design](https://docs.google.com/document/d/1OvjNQ4kx5wUeSmvMYCvnlK5FNZK_HC3R2s65dyjPiIE/edit)
Add testcases for staleness transaction including constraint checking and compatibility with history read
Tests 
- Unit test

session: add testcases for staleness transaction

---

README.md

add more info and update links
Some links in the README file are not correct. 
The README file
The README file

README: add more info and update links

---

session/session.go
session/session_test.go

For https://github.com/pingcap/tidb-test/issues/1152
Prohibit multiple statements in restricted SQL.
How it Works:
Avoid injected SQL bypass the privilege check through `ExecRestrictedSQL()`
This is on 3.0, need to cherry-pick 2.1
Tests 
- Unit test
-  Prohibit multiple statements in restricted SQL

*: prohibit multiple statements in restricted SQL

---

executor/load_data.go
executor/write_test.go

Reverts pingcap/tidb#22481 since it introduces a new bug(https://github.com/pingcap/tidb/issues/22578).

Revert "executor: fix load data in file get wrong result #20854 (#21895)"

---

store/tikv/pd_codec.go
store/tikv/ticlient_test.go
store/tikv/util/codec/bytes.go

Remove store/tikv's dependency on util/codec.
Part of #22513 
store/tikv: remove import tidb/util/codec from store/tikv
Tests 
- Unit test

store/tikv: remove util/codec dependency

---

README.md

README: change mailing list from google group to lists.tidb.io

---

kv/kv.go

Signed-off-by: mwish <anmmscs_maple@qq.com>
Just a typo.
None
None
Tests 
- No code
Side effects
None

kv/typo: fix the description for `GetMemCache`

---

session/session.go
session/session_test.go
util/sqlexec/utils.go
util/sqlexec/utils_test.go

Problem Summary: cherry-pick #22499 
Tests 
- Unit test

*: Introduce new escaping API

---

executor/executor_test.go
expression/builtin_compare.go

Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>
Issue Number: close #22817
How it Works: as the title says.
Tests 
- Unit test
- do not ajust int when it is null and compared year

expression: do not adjust int when it is null and compared year

---

store/tikv/backoff.go
store/tikv/batch_request_sender.go
store/tikv/client_helper.go
store/tikv/coprocessor.go
store/tikv/region_request.go

Move the position of some components to make it easier for later migration.
Part of https://github.com/pingcap/tidb/issues/22513
Tests 
- Unit test

store/tikv: move some code

---

executor/aggregate.go

Issue Number: close #22881  
How it Works:
Tests 
Side effects

executor: fix regression by Tracker.Consume in aggregate.

---

executor/analyze.go
executor/brie.go
executor/ddl.go
executor/grant.go
executor/infoschema_reader.go
executor/inspection_profile.go
executor/inspection_result.go
executor/inspection_summary.go
executor/metrics_reader.go
executor/opt_rule_blacklist.go
executor/prepared.go
executor/reload_expr_pushdown_blacklist.go
executor/revoke.go
executor/show.go
executor/simple.go
executor/trace.go
executor/utils.go
telemetry/data_cluster_hardware.go
telemetry/data_cluster_info.go
util/mock/context.go
util/sqlexec/restricted_sql_executor.go

Problem Summary: cherry pick #22644
Tests 
- Unit test
- No code

*: adapt new api for the executor package (#22644)

---

infoschema/infoschema_test.go

Issue Number: fix #22979  
What's Changed: added err check
Tests 
- Unit test

infoschema: fix err check

---

domain/db_test.go
domain/domain_test.go
domain/global_vars_cache_test.go
domain/infosync/info_test.go

Issue Number: fix #22979  
What's Changed: added err check
Tests 
- Unit test

domain: fix err check

---

config/config_test.go

Issue Number: #22979  
What's Changed: added err check
Tests 
- Unit test
- config: fix error check

config: fix err check

---

go.mod
go.sum

Update PD client to take some fixes and optimizations: tikv/pd#3413, tikv/pd#3430, tikv/pd#3432
Update PD client and related dependencies in `go.mod`.
Tests 
- Unit test

*: update PD client

---

ddl/delete_range.go

cherry-pick #22729 to release-2.1
- migrate part of ddl package code from Execute/ExecRestricted to safe API (2) (#22729)

ddl: migrate part of ddl package code from Execute/ExecRestricted to safe API (2) (#22729)

---

docs/design/2018-10-08-online-DDL.md

Issue Number: N/A
Problem Summary: A link in docs/design/2018-10-08-online-DDL.md is broken.
What's Changed: Fix the link.
How it Works: N/A
N/A
Tests 
- No code
Side effects
N/A

docs/design: fix broken link in 2018-10-08-online-DDL.md

---

go.mod
go.sum
store/tikv/batch_coprocessor.go
store/tikv/coprocessor.go

Problem Summary: Update to a KvProto that contains ScanDetailV2.
This PR partially cherry picks #20966 . Only kvproto change is included.
What's Changed: Update kvproto
Tests 
- Unit test

misc: Update kvproto

---

sessionctx/variable/tidb_vars.go
statistics/integration_test.go

Problem Summary: hide the variable before it's GA
Tests 
- Unit test
- `No release note`

statistics: hide the `tidb_analyze_version` before it's GA

---

server/sql_info_fetcher.go
store/tikv/gcworker/gc_worker.go
util/admin/admin.go

Manually back port some of the changes https://github.com/pingcap/tidb/pull/22621
Escape SQL
How it Works:
Tests 
- No code

server,store,util: escape internal SQL statement

---

distsql/select_result.go

Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>
How it Works:
Tests 
- Unit test
- fix incorrect value for copr cache in telemetry.

telemetry: fix incorrect value for copr cache

---

kv/union_store.go

Signed-off-by: AndreMouche
This PR removes some unused types from kv package
Part of https://github.com/pingcap/tidb/issues/22513
Tests 
- Unit test

kv/union_store:remove some unused type

---

executor/aggfuncs/builder.go
expression/integration_test.go

Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>
Issue Number: close #23662
How it Works:
Tests 
- Unit test
- fix approx_percent panic on bit column

expression: fix approx_percent panic on bit column

---

config/config.toml.example

Issue Number: close #23739 
index-usage-sync-lease is hidden in 5.0, remove it from config.toml.example

config: remove index-usage-sync-lease from config.toml.example

---

expression/integration_test.go
table/tables/tables.go

Issue Number: close #23805 
Didn't skip the column which doesn't need restored data.
Skip the column which doesn't need restored data.
Tests 
- Unit test
Side effects
-
- fix a bug in TryGetHandleRestoredDataWrapper which may cause panic

table: fix a bug in TryGetHandleRestoredDataWrapper which may cause panic

---

statistics/handle/gc.go
statistics/handle/handle.go
statistics/handle/handle_test.go

Problem Summary: statistics: fix a statistics GC problem that can cause duplicated fm-sketch records
statistics: fix a statistics GC problem that can cause duplicated fm-sketch records
Tests 
- Unit test
- statistics: fix a statistics GC problem that can cause duplicated fm-sketch records

statistics: fix a statistics GC problem that can cause duplicated fm-sketch records

---

README.md

Easier to read the README.md
There was an extra space in a sentence of the README.md
An extra space was removed.
How it Works:
Text only, no change in implementation
N/A

*: Remove an extra space in README.md

---

planner/core/cbo_test.go
planner/core/testdata/analyze_suite_in.json
planner/core/testdata/analyze_suite_out.json

Signed-off-by: Piotr Rzysko <piotr.rzysko@gmail.com>
Issue Number: close #15549
What's Changed: Splitted test data from test cases in  `planner/core/cbo_test.go`.
Tests 
- Unit test

planner: split test data from test cases in cbo_test.go

---

executor/executor_test.go
executor/index_lookup_join.go
go.sum

Issue Number: close #23609  
Ignore error from convertTimezone
How it Works:
- Need to cherry-pick to the release branch 5.0
Tests 
- Unit test
Side effects

executor: bypass encoding invalid datetime for index join

---

statistics/handle/handle_test.go

Not a problem, add more unit tests for extended stats feature.
No code change.
N/A
Tests 
- Unit test
- No code
Side effects
N/A
- N/A

statistics: add more tests for extended stats

---

store/mockstore/mocktikv/executor_test.go
store/mockstore/mocktikv/mock_tikv_test.go
store/mockstore/mocktikv/utils.go

We can make some test utilities public so it can be used by other package.
Part of https://github.com/pingcap/tidb/issues/22513
Tests 
- Unit test

mocktikv: extract test utils

---

store/mockstore/mocktikv/analyze.go
store/mockstore/mocktikv/cop_handler_dag.go
store/mockstore/mocktikv/rpc.go
store/mockstore/mocktikv/session.go

Add some exported functions so it will be more clear when we move it to another directory.
Part of https://github.com/pingcap/tidb/issues/22513
Tests 
- Unit test

mocktikv: add exported functions to session

---

executor/aggregate.go
executor/executor.go
executor/executor_test.go
executor/projection.go

Issue Number: close #24210 
the original issue has the summary: https://github.com/pingcap/tidb/issues/24210
How it Works:
- Need to cherry-pick to the release branch, 5.0 and 4.0
Tests 
- Unit test
Side effects
- N/A

executor: fix projection executor panic and add failpoint test

---

statistics/cmsketch.go
statistics/handle/handle.go
statistics/handle/handle_test.go
statistics/histogram.go

Issue Number: close #24349 
Please check the issue for details
How it Works:
Tests 
- Unit test
Side effects

statistics: fix three bugs about MergePartTopN2GlobalTopN

---

sessionctx/variable/noop.go

Signed-off-by: Ryan Leung <rleungx@gmail.com>
Problem Summary: We have defined the variable`CharacterSetSystem`. But it is unused right now.
What's Changed: Use it.
Tests 
- Unit test (all existed tests can pass)

variable: use the defined variable

---

planner/core/integration_test.go
planner/core/logical_plan_builder.go

cherry-pick #23404 to release-4.0
---
Issue Number: close #23273 
Tests 
- Unit test
- no release note.

planner: fix only_full_group_by check not enough (#23404)

---

expression/builtin_time.go
expression/builtin_time_test.go

Fix the misspelling of the word `arithmetical`.
Change `arithmitical` to `arithmetical`.
Tests 
- Unit test
- `No release note`.

expression: fix the spelling of word arithmetical

---

expression/expression.go

Issue Number: close https://github.com/pingcap/tics/issues/1943 
Problem Summary: push down left/right without cosidering collation, char_length aims to verification.
How it Works:
Tests 
Side effects
- push down left/right/char_length to tiflash

expression: push down left/right/char_length

---

expression/expression.go

partially pingcap/tics#1860
How it Works:
Tests 
- Unit test
- No code
Side effects
-

expression: support push down replace to TiFlash

---

expression/expr_to_pb_test.go
expression/expression.go

Related to: https://github.com/pingcap/tics/issues/1936
- Enable `CastStringAsReal` push down for TiFlash
Tests 
- Unit test
Side effects

expression: Support cast string as real push down

---

expression/expr_to_pb_test.go
expression/expression.go

How it Works:
Tests 
- Unit test
- No code
Side effects

expression: push Concat and UnixTimestamp to TiFlash

---

distsql/select_result.go
planner/core/task.go
util/execdetails/execdetails.go

How it Works:
Tests 
- Unit test
- No code
Side effects

planner: support explain analyze for mpp task with union

---

planner/core/exhaust_physical_plans.go

How it Works:
Tests 
- Unit test
- No code
Side effects
-

choose build side based on row count for left/right join

---

go.mod
go.sum
store/tikv/region_request_test.go

Update dep `unistore` and `kvproto` to newest release-5.0.
https://github.com/pingcap/br/pull/1150 deps on a newer version of kvproto, and we need to update the unistore version because some interface has changed.
How it Works:
Tests 
- Unit test
- No code
Side effects
- No Release Note

*: update unistore

---

executor/partition_table_test.go

Problem Summary: executor: fix the unstable test TestDML
TestDML does some DML operations randomly on partition tables. 
Since these partition tables have PKs, errors may occur when some duplicated rows are inserted into them.
These PKs would not affect the test, so I remove them to make this test stable.
Tests 
- Unit test 
- executor: fix the unstable test TestDML

executor: fix the unstable test TestDML

---

expression/integration_test.go
go.mod
go.sum

see https://github.com/pingcap/tidb/pull/24522
The test is added in the parser repo
- update parser to fix lexer bug

parser: update parser to fix lexer bug

---

cmd/explaintest/r/cte.result
cmd/explaintest/t/cte.test

Add tests for CTE
This PR is based on https://github.com/pingcap/tidb/pull/24809 now
Tests 
- Unit test
Side effects

cmd: add tests for CTE

---

ddl/column_type_change_test.go

Signed-off-by: AilinKid <314806019@qq.com>
Problem Summary: fix typo
fix a typo link in the error
Tests 
- No code
- test: fix a name typo error in test file

test: fix a name typo error in test file

---

expression/integration_test.go
planner/core/logical_plan_builder.go
planner/core/preprocess.go

Issue Number: close https://github.com/pingcap/tidb/issues/24116
Tests 
- Unit test
- add the DML support in CTE

planner: add dml support in CTE

---

session/session.go

Problem Summary: CI unstable fix.
Tests 
- Unit test

*: concurrent session access leads to race

---

store/tikv/lock_resolver.go

Fix a typo in the comment.
Actually nothing.

tikv: fix a typo

---

executor/builder.go
executor/executor_test.go

add tablesample compatibility for temporary table
If perform tablesample query in temporary table, we will get a error
- N/A
Tests 
- Unit test
Side effects
- N/A

executor: add tablesample compatibility for temporary table

---

config/config.toml.example

Issue Number: close https://github.com/pingcap/tidb/issues/25313
This adds a configuration file example to make it easier to understand SEM is available. It does not change any functionality, but makes it a bit easier to use.
Non functional change.
Tests 
- No code
Side effects
- None

config: add example config line for sem

---

go.mod
go.sum
session/session_test.go

- Update BR to latest version.
- Enable BR test.
Tests 
- Unit test

*: update br and kvproto

---

expression/builtin_compare.go

Signed-off-by: glorv <glorvs@163.com>
How it Works:
Tests 
- Unit test
- No code
Side effects

expression: cast string to decimal when compare string and decimal

---

expression/expr_to_pb_test.go
expression/expression.go

Problem Summary: cherry-pick #25084
How it Works:
Tests 
- Unit test
- No code
Side effects
- Support push down function replace to TiFlash.

expression: [cherry-pick-5.0] Support push function replace down to TiFlash

---

store/copr/mpp.go

How it Works:
Tests 
- Unit test
- No code
Side effects

copr: add log to record task id when mpp task fail

---

ddl/db_change_test.go

remove useless println in the test.
remove useless println in the test.
Tests 
- Unit test
- test: remove useless code

test: remove useless code

---

distsql/distsql.go

No
Just a typo
fix a typo
How it Works:
:)
None
Tests 
- No code
Side effects
No

distsql/*: typo fix for `dispatches`

---

executor/tiflash_test.go

Problem Summary: executor: skip all test cases related to TiFlash+Partition since they are too slow
executor: skip all test cases related to TiFlash+Partition since they are too slow
I will port these test cases into the `tidb-test` repo later.
Tests 
- Unit test

executor: skip all test cases related to TiFlash+Partition since they are too slow

---

expression/builtin_compare.go

This reverts commit ef25da39785b8c8fcdf7a6cb071f738f22573702.
How it Works:
Tests 
- Unit test
- No code
Side effects
-

Revert "done (#25382)"

---

planner/core/rule_partition_processor.go
util/math/math.go

This is a minor change.
In a57dc3ab654327ddfc23fae1ae36ccad24758beb we introduce this export but it is redundant. We should avoid adding such public methods which cause further confusion.

util/math: reduce redundant wrapper

---

go.mod
kv/checker_test.go
kv/error_test.go
kv/fault_injection_test.go
kv/key_test.go
kv/main_test.go
kv/mock_test.go
kv/txn_test.go
kv/utils_test.go

Issue Number:
- closes #26100
- closes #26107 
How it Works:
Line by line migrate matchers. Also replace manually leak scripts with [go.uber.org/goleak](https://github.com/uber-go/goleak) as in https://github.com/tikv/client-go/pull/172

kv: migrate test-infra to testify

---

statistics/handle/handle.go
statistics/handle/handle_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/24722
Lock leak if error happens when reloading stats
Put `releaseStatsReader` into defer func.
N/A
Tests 
- Unit test
Side effects
N/A
- Avoid lock leak if error happens when reloading stats

statistics: avoid lock leak if error happens when reloading stats

---

util/main_test.go
util/misc_test.go
util/prefix_helper_test.go
util/processinfo_test.go

Issue Number
* close #26157
Done as the title.

util: migrate test-infra to testify

---

util/mock/main_test.go
util/mock/mock_test.go

Issue Number: close #26153 
What's Changed: Migrate test-infra to testify for `util/mock` pkg.

util/mock: migrate test-infra to testify

---

executor/stale_txn_test.go
go.mod
store/copr/batch_coprocessor.go
store/copr/coprocessor_test.go
util/memory/tracker.go

Issue Number: close #26167 
How it Works:
Tests 
- N/A
Side effects
- N/A
Documentation
- N/A

format: fix check

---

session/pessimistic_test.go

Try to add some more combinations of transaction amend tests.
Tests 
- Unit test
Side effects
* No release note.

test: try to add some combinations for amend test

---

util/expensivequery/expensivequerey_test.go

util/expensivequery: migrate test-infra to testify

---

go.mod
go.sum

Issue Number: close https://github.com/tikv/tikv/issues/10570
Upgrade client-go to include the fix https://github.com/tikv/client-go/pull/233
- `No release note`

tikv: upgrade client-go to fix the bug that transaction may read stale data

---

server/tidb_test.go
util/topsql/reporter/mock/server.go
util/topsql/reporter/reporter_test.go
util/topsql/topsql_test.go

Signed-off-by: crazycs <crazycs520@gmail.com>
close #26321
Tests 
Side effects
- N/A

*: make test TestCollectInternal stable

---

util/format/format_test.go
util/format/main_test.go

Issue Number: close #26179 
What's Changed: Migrate test-infra to testify for util/format pkg.

util/format: migrate test-infra to testify

---

types/json/binary_functions_test.go
types/json/binary_test.go
types/json/main_test.go
types/json/path_expr_test.go

types/json: migrate test-infra to testify

---

util/sem/main_test.go
util/sem/sem_test.go

Issue Number: close #26416 
Problem Summary: ref to #26022

util/sem: migrate test-infra to testify

---

util/tracing/main_test.go
util/tracing/util_test.go

Issue Number: close #26429 
migrate tracing test to testify

util/tracing: migrate tracing test to testify

---

util/dbterror/main_test.go
util/dbterror/terror_test.go

Issue Number: close #26174 
Migrate test-infra to testify for util/dbterror pkg.

util/dbterror: migrate test-infra to testify

---

table/tables/tables_test.go

Issue Number: close #25691 
Problem Summary: planner: fix the unstable unit test TestTableFromMeta
`TestTableFromMeta` modifies some read-only meta table info, which is incorrect and might be conflicted with the background auto-analyze.
This PR makes it clone meta table info before modifying it.
Tests 
- `No release note`

planner: fix the unstable unit test TestTableFromMeta

---

executor/analyze_test.go
statistics/handle/handle_test.go
statistics/handle/update.go
statistics/handle/update_test.go

Issue Number: close #25013 
Problem Summary: planner: fix the unstable unit test `TestAnalyzeIncremental`
Tests 
- `No release note`

planner: fix the unstable unit test `TestAnalyzeIncremental`

---

executor/tiflash_test.go
store/copr/batch_coprocessor.go
store/copr/mpp.go
store/mockstore/unistore/rpc.go

cherry-pick #26462 to release-5.0
How it Works:
Tests 
Side effects
Documentation
- store/copr: support retry for mpp query

store/copr: support retry for mpp query (#26462)

---

util/texttree/main_test.go
util/texttree/texttree_test.go

util/texttree: migrate test-infra to testify

---

docs/design/2021-06-27-restructure-tests.md

Issue Number: follow-ups to #26023 

docs: correct typo of author link

---

planner/core/integration_test.go
planner/core/property_cols_prune.go

How it Works:
Tests 
Side effects
Documentation
-

planner: create new column slice in PreparePossibleProperties (#24342)

---

util/slice/main_test.go
util/slice/slice_test.go

Signed-off-by: Keming <kemingy94@gmail.com>
Issue Number: close #26418

util/slice: migrate test-infra to testify

---

expression/builtin_other.go
expression/builtin_other_vec_generated.go
expression/generator/other_vec.go
expression/integration_test.go
expression/scalar_function.go
planner/core/integration_test.go

How it Works:
Tests 
Side effects
Documentation
- 
Signed-off-by: ti-srebot <ti-srebot@pingcap.com>

expression: fix the `in` function get the wrong result if args is time type (#21293) (#21406)

---

.github/pull_request_template.md

Using release note plugin checker instead of CI
How it Works:
Tests 
Side effects
Documentation
-

*: Using release note plugin checker instead of CI

---

.github/pull_request_template.md

How it Works:
Tests 
Side effects
Documentation
```release-note
If you don't think this PR needs a release note then fill it with None.
```

*: Refine release note

---

sessionctx/variable/sysvar_test.go
sessionctx/variable/varsutil.go
sessionctx/variable/varsutil_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/25893
This removes the flaky part of a test since it is modified by other parts of the server concurrently. Additional tests are added to improve coverage from 47.2% to 51.1%.
Improves tests only
Tests 
Side effects
Documentation
```release-note
None
```

variable: improve code coverage, fix unstable test

---

types/parser_driver/main_test.go
types/parser_driver/value_expr_test.go

types/driver: migrate test-infra to testify

---

executor/adapter.go
executor/bind.go
executor/compiler.go
executor/prepared.go
executor/trace.go

Fix audit log for https://docs.google.com/spreadsheets/d/1E59z7busbRwjb2D20QLbmAGhLT75vec44HTB5vi2WrI/edit#gid=0
How it Works:
Tests 
Side effects
Documentation
```release-note
```

executor: fix some audit log error

---

plugin/conn_ip_example/conn_ip_example_test.go
plugin/conn_ip_example/main_test.go

Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>
Issue Number: close #26745 
```release-note
None
```

plugin/conn_ip_example_test.go: migrate test-infra to testify

---

executor/analyze_test.go

Issue Number: close #25187 
Problem Summary: planner: fix the unstable test case TestAnalyzeIncremental
`stats-ver2` doesn't support `incremental analyze`.
Tests 
```release-note
planner: fix the unstable test case TestAnalyzeIncremental
```

planner: fix the unstable test case TestAnalyzeIncremental

---

executor/adapter.go
executor/trace.go

How it Works:
Tests 
Side effects
Documentation
```release-note
Fix shutdown and trace statement audit log
```

executor: fix shutdown and trace statement audit log

---

executor/analyze.go
executor/analyze_test.go
executor/executor_test.go
statistics/histogram.go

cherry-pick #21262 to release-4.0
---
Issue Number: close #20874  
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

statistics: fix the panic when analyze with collation enabled

---

expression/integration_test.go
planner/core/rule_decorrelate.go

Issue Number: close https://github.com/pingcap/tidb/issues/26958 
How it Works:
Tests 
Side effects
Documentation
```release-note
```

planner: add missing distinct flag for Apply convert to join

---

go.mod
go.sum
sessionctx/variable/session.go

Issue Number: close https://github.com/pingcap/tidb/issues/26538
Problem Summary: For details, see https://github.com/pingcap/tidb/issues/26538#issuecomment-893316891
NA
Tests 
Side effects
Documentation
```release-note
None
```

parser: disable text position recording

---

br/pkg/lightning/backend/tidb/tidb.go
br/pkg/lightning/backend/tidb/tidb_test.go
br/pkg/lightning/common/util.go

Close https://github.com/pingcap/br/issues/1366.
Please take a look at:
* https://github.com/pingcap/br/issues/1366
* https://github.com/pingcap/br/pull/1370
Tests 
```release-note
None.
```

Lightning: support batch import downgrading 

---

config/config.go

Issue Number: close #27038 
Miss the prefix `experimental.`
Add prefix `experimental.`
Tests 
Side effects
Documentation
```release-note
'None'
```

config: fix config experimental.allow-expression-index

---

planner/core/integration_partition_test.go
planner/core/testdata/integration_partition_suite_in.json
planner/core/testdata/integration_partition_suite_out.json

Problem Summary: planner: add more test cases for list column partition
No logical change, just add more test cases for list column partition.
Tests 
```release-note
None
```

planner: add more test cases for list column partition

---

br/pkg/task/restore.go

Issue Number: close https://github.com/pingcap/br/issues/1415
Problem Summary: Parameters error
Fill in the correct parameters in restore.go
Tests 
```release-note
None
```

br-restore: Update restore.go

---

util/math/main_test.go
util/math/math_test.go

Issue Number: close #26978 
```release-note
None
```

util/math: migrate test-infra to testify

---

bindinfo/bind_test.go
cmd/explaintest/r/access_path_selection.result
cmd/explaintest/r/explain_easy.result
cmd/explaintest/r/explain_easy_stats.result
cmd/explaintest/r/select.result
cmd/explaintest/r/topn_push_down.result
executor/set_test.go
executor/testdata/agg_suite_out.json
expression/integration_test.go
planner/core/exhaust_physical_plans.go
planner/core/find_best_task.go
planner/core/integration_test.go
planner/core/rule_result_reorder_test.go
planner/core/testdata/analyze_suite_out.json
planner/core/testdata/integration_serial_suite_out.json
planner/core/testdata/integration_suite_out.json
planner/core/testdata/ordered_result_mode_suite_out.json
planner/core/testdata/plan_suite_out.json
session/session.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go

Cherry-pick #18996 and #26550
How it Works:
Tests 
Side effects
Documentation
```release-note
```

hotfix: cherry-pick two commits

---

executor/executor_test.go

Issue Number: close #27435
Tests 
```release-note
None
```

*: fix unstable test testSerialSuite.TestTemporaryTableNoNetwork

---

Makefile.common

How it Works:
Tests 
Side effects
Documentation
```release-note
```

Makefile: modify the binary version to 4.0.15

---

executor/executor_test.go

- close https://github.com/pingcap/tidb/issues/27476
- close https://github.com/pingcap/tidb/issues/27474
- close https://github.com/pingcap/tidb/issues/27485
```release-note
None
```

*: fix the date race in `TestCharsetFeature`

---

docs/MAINTAINERS.md

co: https://github.com/pingcap/community/pull/526
```release-note
None
```

docs: Delete MAINTAINERS.md

---

go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/27320 
How it Works:
Tests 
Side effects
Documentation
```release-note
'None' 
```

*: update parser to fix IT

---

ddl/db_test.go

Issue Number: close #25943 
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

ddl: add test case of local temporary table

---

Makefile

phony target is series of rules/shell commands, it is not real target.
make always show a up to date if any folder and file has the same name with build target.
define phony target
How it Works:
phony target is not real target, but it is series of rules which make to follow.
Tests 
Side effects
Documentation
```release-note
```

br: declare phony target

---

store/mockstore/unistore/rpc.go

unistore: remove an unused interface

---

br/tests/README.md

Problem Summary: Maintain the README.md for br
Justly change the README.me
Tests 
```release-note
None
```

br: maintain the README.md

---

Makefile.common
go.mod
go.sum

Signed-off-by: ailinkid <314806019@qq.com>
makefile: add customized release version support 
makefile: add customized release version support 
Tests 
```release-note
None
```

makefile: add customized release version support 

---

expression/aggregation/base_func.go
planner/core/logical_plan_builder.go

cherry-pick #27176 to release-5.0-20210902
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

planner: Fix the problem that `PlanBuilder.buildWindowFunctions` may change sub operator's schema.

---

telemetry/data_feature_usage_test.go
telemetry/data_window_test.go
telemetry/telemetry_serial_test.go
telemetry/telemetry_test.go

telemetry: clean up test code

---

store/tikv/txn.go

Issue Number: close #27400 on release 5.1
Cherry pick modification in client-go#274 to release-5.1
Tests 
Side effects
NA
Documentation
NA
```release-note
Fix a bug that retryable deadlocks are incorrectly recorded into `INFORMATION_SCHEMA.DEADLOCKS` table.
```

txn: Cherry pick client-go#274 to release-5.1

---

executor/join.go

Issue Number: close #27876 
close https://github.com/pingcap/tidb/issues/27878
spill and copying row container might contend, bring copying ahead
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

test: fix race of hash join

---

store/helper/helper_test.go
store/helper/main_test.go

Issue Number: close #27656  
migrate test-infra to testify for store/helper 
```release-note
None
```

store/helper: Migrate test-infra to testify 

---

config/config_test.go

TestConfig will create config.toml, which is untracked by git
How it Works:
remove it after test using defer
Tests 
Side effects
Documentation
```release-note
None
```

test: remove created config file after test

---

store/mockstore/unistore/cophandler/closure_exec.go

The code removed is not used, so removed for clearity.
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

mockstore: remove unused code

---

types/errors_test.go

Signed-off-by: Hanlin Shi <shihanlin9@gmail.com>
Issue Number: close #28001 
```release-note
NONE
```

types: migrate test-infra to testify for errors_test.go

---

types/core_time_test.go

Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>
Issue Number: close #27998
```release-note
None
```

types: migrate test-infra to testify for core_time_test.go

---

executor/executor_test.go

close https://github.com/pingcap/tidb/issues/28099
this test will fail if update parser, comment it temporarily.
Tests 
Side effects
Documentation
```release-note
None
```

charset: comment a test to prevent it block ci

---

br/pkg/kv/checksum_test.go
br/pkg/kv/kv_test.go
br/pkg/kv/main_test.go
br/pkg/kv/session_test.go

Issue Number: close #28169 
Problem Summary: migrate test-infra to testify for br/pkg/kv
What's Changed: migrate test-infra to testify for br/pkg/kv
```release-note
None
```

br/pkg/kv: migrate test-infra to testify

---

br/pkg/summary/collector_test.go
br/pkg/summary/main_test.go

Issue Number: close #28180 
Problem Summary: migrate test-infra to testify for br/pkg/summary
What's Changed: migrate test-infra to testify for br/pkg/summary
```release-note
None
```

br/pkg/summary: migrate test-infra to testify

---

statistics/scalar_test.go

Signed-off-by: Xiaoyong Zhao <xiaoyong99z@163.com>
Issue Number: close #28119
```release-note
None
```

statistics/scalar_test: migrate test-infra to testify

---

br/pkg/metautil/main_test.go
br/pkg/metautil/metafile_test.go

Signed-off-by: xiaoyong-z <a997647204@gmail.com>
Issue Number: close #28173 
```release-note
'None'
```

br/pkg/metautil: migrate test-infra to testify

---

br/pkg/conn/conn.go
br/pkg/conn/conn_test.go
br/pkg/conn/main_test.go

Issue Number: close #28167
```release-note
None
```

br/pkg/conn: migrate test-infra to testify

---

types/field_type_test.go

Issue Number: close #28004
```release-note
None
```

issue-28004: migrate test-infra to testify for types/field_type_test.go

---

br/pkg/lightning/restore/check_info.go
br/pkg/lightning/restore/restore.go
br/pkg/lightning/restore/restore_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/28276
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

lightning: fix tidb-backend estimate data source

---

store/store.go

Issue Number: close #28318
introduced in #27993
`Register` function is not thread safe.
https://github.com/pingcap/tidb/blob/e60f20b9f4ee502bec4cebd84de18a25fefeebb4/store/store.go#L31-L40
Run those  parallel test functions will suffer fatal error for concurrent map writes on occasionally.
https://github.com/pingcap/tidb/blob/e60f20b9f4ee502bec4cebd84de18a25fefeebb4/store/store_test.go#L765-L770
https://github.com/pingcap/tidb/blob/e60f20b9f4ee502bec4cebd84de18a25fefeebb4/store/store_test.go#L780-L785
How it Works:
Add mutex Lock for map variable in package write and read.
```release-note
None
```

store: thread safe for Register kv.Driver

---

br/pkg/lightning/backend/tidb/tidb.go
br/pkg/logutil/logging_test.go
br/pkg/logutil/rate.go
br/pkg/restore/systable_restore.go

Fix typo
Tests 
```release-note
None
```

br: Fix typo in br

---

store/copr/batch_coprocessor.go

Signed-off-by: ti-srebot <ti-srebot@pingcap.com>
How it Works:
Tests 
Side effects
Documentation
```release-note
```

copr: cherry pick #28110 to release-5.0-20210923

---

ddl/column_type_change_test.go

Issue Number: close #28350 
How it Works:
Make sure the `insert` logic only runs 3 times.
Tests 
Side effects
Documentation
```release-note
None.
```

ddl: make TestChangingColOriginDefaultValue stable

---

store/tikv/client/client.go

Cherry pick https://github.com/pingcap/tidb/pull/27678
Hotfix on v5.1.1
How it Works:
Tests 
Side effects
Documentation
```release-note
Fix a batch client bug that recycle idle connection may block sending requests in some rare cases.
```

store/tikv/client: remove the lock for idle connection recycle #27678

---

executor/explainfor_test.go

close https://github.com/pingcap/tidb/issues/28348
Tests 
```release-note
None
```

test: make test TestExplainFor stable

---

executor/prepared_test.go

Problem Summary: planner: add more unit tests for prepare plan cache
No logical change, just add more unit test cases.
Tests 
```release-note
None
```

planner: add more unit tests for prepare plan cache

---

go.mod
go.sum
store/copr/coprocessor.go

update client-go and fix metrics
```release-note
None
```

*: update client-go and fix metrics

---

ddl/attributes_sql_test.go
ddl/schema.go

Issue Number: close https://github.com/pingcap/tidb/issues/29466
Problem Summary: attributes cannot be deleted when dropping the database.
Handle the delete attributes logic in `onDropSchema`
Tests 
```release-note
Fix the issue that attributes cannot be deleted when dropping the database.
```

ddl: fix cannot delete attributes when database is dropped

---

ddl/column_test.go

Signed-off-by: ailinkid <314806019@qq.com>
some test name are modified for special test case convenience since `goCheck` framework has the prefix match 
change the test with the common prefix name to some distinguished ones.
Tests 
```release-note
None
```

ddl_test: amend the test name to the distinguished one

---

cmd/explaintest/r/new_character_set_builtin.result
cmd/explaintest/t/new_character_set_builtin.test
expression/builtin_encryption.go
expression/builtin_encryption_test.go
expression/builtin_encryption_vec.go

Issue Number: close #29356
close #29355
support GBK for builtin function SHA1/SHA2
Tests 
```release-note
None
```

expression: support GBK for builtin function SHA1/SHA2

---

table/tables/cache_test.go

Issue Number: close #29632 
Make CI stable
Tests 
Side effects
Documentation
```release-note
None
```

table/tables: make CI stable for table/tables package

---

go.mod
go.sum

Issue Number: https://github.com/pingcap/tidb/issues/29787
See more details at https://github.com/tikv/client-go/pull/375.
Tests 
```release-note
None
```

go.mod: upgrade the client-go to use a more readble key log format

---

br/pkg/lightning/lightning.go

fix DATA RACE in the TestRunServer
```
WARNING: DATA RACE
Read at 0x00c0005d9090 by goroutine 76:
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handlePostTask()
/home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:467 +0x19c
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handleTask()
/home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:403 +0x59c
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).handleTask-fm()
/home/jenkins/agent/workspace/atom-ut/tidb/br/pkg/lightning/lightning.go:384 +0x68
net/http.HandlerFunc.ServeHTTP()
/usr/local/go/src/net/http/server.go:2069 +0x51
net/http.StripPrefix.func1()
/usr/local/go/src/net/http/server.go:2112 +0x535 …
```

br: fix DATA RACE in the TestRunServer

---

statistics/fmsketch_test.go
statistics/main_test.go
statistics/statistics_serial_test.go
statistics/statistics_test.go

Issue Number: close #29845 
fix unstable tests by Independently using middleware.
Tests 
```release-note
None
```

statistics: fix unstable test

---

server/statistics_handler_serial_test.go

Problem Summary: fix unstable test TestDumpStatsAPI
https://ci.pingcap.net/job/atom-ut/1297/testReport/github/com_pingcap_tidb_server/TestDumpStatsAPI/
Tests 
Side effects
Documentation
```release-note
None
```

server: fix unstable test TestDumpStatsAPI

---

ddl/db_integration_test.go
ddl/ddl_api.go

Issue Number: close #29785
Tests 
Side effects
Documentation
```release-note
None
```

ddl: check EnableChangeMultiSchema sysvar when deal with multi columns

---

parser/types/etc.go
parser/types/etc_test.go

add a method in parser, to get MySQL Type By string representation.
Tests 
Side effects
Documentation
```release-note
None
```

parser: add Str2Type method.

---

cmd/explaintest/r/index_merge.result
cmd/explaintest/t/index_merge.test
executor/builder.go
executor/mem_reader.go
executor/union_scan.go
planner/core/stats.go

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Tests 
Side effects
Documentation
```release-note
None
```

index_merge: enable index_merge used in transaction

---

domain/globalconfigsync/globalconfig_test.go

Issue Number: close #29890 
Tests 
Side effects
Documentation
```release-note
None
```

*: fix unstable test TestStoreGlobalConfig

---

executor/main_test.go
executor/prepared_serial_test.go
util/testutil/testutil.go

use testkit/testdata instead of util/testutil
Tests 
Side effects
Documentation
```release-note
None
```

*: use testkit/testdata instead of util/testutil

---

executor/analyze.go
executor/analyze_test.go

Issue Number: close #25782
fix data race with RandSeed
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix data race with RandSeed

---

br/pkg/lightning/backend/backend_test.go

Issue Number: close  #29983
migrate test-infra to testify for lightning/backend/backend_test.go
Tests 
Side effects
Documentation
```release-note
None
```

br : migrate test-infra to testify for lightning/backend/backend_test

---

executor/index_lookup_join.go

https://github.com/pingcap/tidb/pull/30214 introduces an useless log
Tests 
Side effects
N/A
Documentation
N/A
```release-note
None
```

executor: remove useless log

---

docs/design/2021-09-29-secure-bootstrap.md

Add a period to the document
Problem Summary: A typo issue for doc.
Add a period to the document
Tests 
Side effects
Documentation
```release-note
None
```

docs: Update 2021-09-29-secure-bootstrap.md

---

br/pkg/backup/client.go
go.mod
go.sum
store/copr/coprocessor.go

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
Issue Number: close #30313
update client-go to use resolveForRead
update client-go.
Tests 
Unistore doesn't support read-through-lock and the code change is small, so I don't write a test.
Side effects
Documentation
```release-note
None
```

*: update client-go to use resolveForRead

---

metrics/grafana/tidb.json

Issue Number: close #30307
Before:
After:
I guess this is a regression when we move client-go out from tidb repo.
Tests 
tiup playground
import the json file to the grafana and check it works
Side effects
Documentation
```release-note
None
```

metrics/grafana: fix display for 'Start TSO Wait Duration' panel

---

cmd/ddltest/ddl_serial_test.go
cmd/ddltest/main_test.go

Issue Number: close #30332
fix goroutine leak in ddl intergration test
Tests 
Side effects
Documentation
```release-note
None
```

*: fix goroutine leak in ddl intergration test

---

executor/admin_serial_test.go
executor/admin_test.go
table/tables/mutation_checker.go
util/logutil/consistency/reporter.go

Signed-off-by: ekexium <ekexium@gmail.com>
No related issue since it's intended to fix a few broken tests or bugs caused by a merge conflict in a development branch.
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix admin test

---

cmd/ddltest/main_test.go

Issue Number: close #30332
Add mysql client goroutine to ignore list
Tests 
Side effects
Documentation
```release-note
None
```

*: skip mysql client goroutine leak detection in integration ddl

---

store/mockstore/unistore/tikv/region.go

Issue Number: close 
mockstore: improve log to avoid nil pointer
Tests 
Side effects
Documentation
```release-note
None
```

mockstore: improve log to avoid panic for nil pointer

---

expression/integration_test.go
parser/parser.y
parser/parser_test.go

Issue Number: close #30519
Tests 
Side effects
Documentation
```release-note
raise `interval` symbol precedence.
```

parser, expression: follow mysql, increase interval precedence

---

expression/integration_serial_test.go
expression/integration_test.go

Issue Number: close #29139
expression: migrate test-infra to testify for integration_test.go
Tests 
Side effects
Documentation
```release-note
None
```

expression: migrate test-infra to testify for integration_test.go

---

go.mod
go.sum

Signed-off-by: crazycs <chen.two.cs@gmail.com>
close #27795
update `sysutil` in `go.mod` to fix panic when search log.
related PR: https://github.com/pingcap/sysutil/pull/33
Tests 
- N/A
Side effects
- N/A
Documentation
- N/A
```release-note
None
```

*: update sysutil in go.mod to fix panic when search log

---

executor/index_lookup_hash_join.go
executor/index_lookup_join.go

Issue Number: close #30669 
As the issue be fixed shows. 
Tests 
N/A
Side effects
N/A
Documentation
N/A
```release-note
None
```

executor: fix data race on IndexHashJoin.cancelFunc

---

statistics/handle/handle.go

remove reassignment of `Handle.pool` in `NewHandle`.
Tests 
Side effects
Documentation
```release-note
None
```

statistics: remove reassignment of Handle.pool in NewHandle

---

metrics/grafana/tidb.json

hit and miss are always the same.
Fix it.
Tests 
Side effects
Documentation
```release-note
None
```

metrics: fix copr-cache metrics

---

br/pkg/lightning/common/storage_unix.go
br/pkg/lightning/common/storage_windows.go
br/pkg/lightning/config/config.go
br/pkg/lightning/restore/check_info.go
br/pkg/lightning/restore/check_info_test.go
br/pkg/lightning/restore/check_template.go
br/pkg/lightning/restore/meta_manager.go
br/pkg/lightning/restore/restore.go
br/pkg/storage/gcs.go
br/pkg/storage/gcs_test.go
br/tests/lightning_distributed_import/config.toml
br/tests/lightning_duplicate_detection/config1.toml
br/tests/lightning_duplicate_detection/config2.toml
br/tests/lightning_incremental/config.toml
br/tests/lightning_local_backend/run.sh
br/tests/lightning_tidb_rowid/data/rowid.pre_rebase-schema.sql
br/tests/lightning_tidb_rowid/run.sh

Cherry-pick following three pr into release-5.3 to fix the issues in DBaaS platform:
- #30393. Fix the bug that lightning only read the first 1000 files in GCS.
- #30439. Make the precheck error message clearer.
- #30887. Add a switch to enable `incremental import` feature so lightning will check whether target tables contain data by default.
Tests 
Side effects
Documentation
```release-note
None
```

lighting: hotfix lightning for DBaaS

---

store/mockstore/unistore/tikv/mvcc.go
store/mockstore/unistore/tikv/mvcc_test.go
store/mockstore/unistore/tikv/server.go

Signed-off-by: you06 <you1474600@gmail.com>
Issue Number: ref #30942
Handle and support RC isolation level in mockstore.
Tests 
Side effects
Documentation
```release-note
None
```

mockstore: support rc read

---

planner/core/prepare_test.go

add more test cases for admin flush plan_cache
add more test cases for admin flush plan_cache
Tests 
Side effects
Documentation
```release-note
None
```

planner: add more test cases for admin flush plan_cache

---

expression/expr_to_pb_test.go
expression/expression.go
tools/check/ut.go

Tests 
Side effects
Documentation
```release-note
Add strcmp support for TiFlash
```

expression: enable strcmp for tiflash

---

executor/select_into.go
executor/select_into_test.go

Issue Number: close #31131
After write chunk to file, update affected rows.
Tests 
```release-note
Support "Affected Rows" for `SELECT ... OUTFILE` grammer.
```

executor: let select into outfile has affected rows return

---

executor/split.go
executor/split_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/31137
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix split table error message reversed step and minRegionStep

---

statistics/handle/update_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/31220
It's basically a dead feature. Skip TestLogDetailedInfo test.  
Tests 
Side effects
Documentation
```release-note
None
```

statistics: skip TestLogDetailedInfo test

---

ddl/util/syncer_test.go
domain/schema_validator_test.go
executor/explainfor_test.go
executor/insert_test.go
meta/meta_test.go
owner/fail_test.go
session/tidb_test.go
store/driver/sql_fail_test.go
util/memory/tracker_test.go

Issue Number: ref #29517
migrate sync.WaitGroup to util.WaitGroupWrapper
Tests 
Side effects
Documentation
```release-note
None
```

*: migrate sync.WaitGroup to util.WaitGroupWrapper

---

planner/core/plan_stats_test.go

Issue Number: ref #26857
Tests 
Side effects
Documentation
```release-note
None
```

planner: migrate test-infra to testify for plan_stats_test

---

util/topsql/topsql_test.go

Issue Number: close #31243
Tests 
Side effects
Documentation
```release-note
None
```

topsql: fix data race in the topsql_test

---

br/pkg/restore/client_test.go
br/pkg/restore/main_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/31356
Problem Summary:  https://github.com/pingcap/tidb/pull/31248/files roll back the fix of mockCluster conflict. This PR tries to fix it again...
Tests 
```release-note
None
```

br: fix unstable unit test

---

cmd/explaintest/main.go
config/config.go
config/config_test.go
ddl/column_test.go
ddl/db_integration_test.go
ddl/integration_test.go
executor/executor_test.go
executor/infoschema_reader_test.go
executor/point_get_test.go
executor/seqtest/seq_executor_test.go
executor/tiflash_test.go
expression/builtin_string_test.go
parser/charset/charset.go
parser/charset/charset_test.go
parser/parser_test.go
session/session.go
util/collate/charset.go
util/collate/collate.go
util/collate/collate_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/31236
Tests 
```release-note
None
```

config: remove new charset config

---

cmd/explaintest/r/new_character_set_builtin.result
cmd/explaintest/t/new_character_set_builtin.test
expression/builtin_convert_charset.go

Issue Number: close #31331
Tests 
Side effects
Documentation
```release-note
fix elt with gbk charset
```

expression: fix elt with gbk charset

---

br/pkg/lightning/restore/checksum_test.go
distsql/distsql.go
executor/executor_test.go
executor/simple.go
infoschema/tables_test.go
kv/kv.go
store/copr/batch_coprocessor.go
store/copr/batch_request_sender.go
store/copr/coprocessor.go
store/copr/mpp.go
util/mock/client.go

Issue Number: close #31038 
forbid collecting info if enable-collect-execution-info disabled
Tests 
```release-note
None
```

store: forbid collecting info if enable-collect-execution-info disabled

---

docs/tidb_http_api.md

Issue Number: close #31389
Make the document more developer-friendly!
Tests 
Side effects
Documentation
```release-note
None
```

docs: update tidb_http_api.md add MVCC operation type description

---

util/cpuprofile/cpuprofile_test.go

Signed-off-by: mornyx <mornyx.z@gmail.com>
Issue Number: close #31412
```release-note
None
```

topsql: fix data race in cpuprofile test

---

table/tables/cache.go

Issue Number: close #31474
When the current time is close to the cache table's read lock lease's expire time, a renew lease operation is sent.
However, the current code doesn't avoid the repeated message, it means before the previous renew lease operation finished, 
a new one will be create... so renew lease become a heavy operation...
Avoid repeated renew lease operation.
Don't send the second one before the previous one finish.
Tests 
After the change, the QPS is stable:
```
sysbench 1.0.18 (using system LuaJIT 2.1.0-beta3)
Running the test with following options:
Number of threads: 128
Report intermediate results every 10 second(s)
Initializing random number generator from current time
Initializing worker threads...
Threads started!
[ 10s ] thds: 128 tps: 96691.54 qps: …
```

table/tables: avoid repeated renew lease operation for cached table

---

planner/core/memtable_predicate_extractor_test.go

Issue Number: close #28403
Tests 
Side effects
Documentation
```release-note
None
```

planner: migrate test-infra to testify for memtable_predicate_extractor_test.go

---

cmd/explaintest/r/explain_easy.result
cmd/explaintest/t/explain_easy.test
executor/builder.go
executor/infoschema_reader.go
infoschema/tables_test.go
planner/core/logical_plan_builder.go
planner/core/memtable_predicate_extractor.go
planner/core/memtable_predicate_extractor_test.go
privilege/privileges/privileges_test.go

Issue Number: ref #31481
Tests 
Side effects
Documentation
```release-note
None
```

*: fix case-sensitivity issue with EQ/IN when query information_schema.columns 

---

br/pkg/utils/retry.go
br/pkg/utils/retry_test.go

Issue Number: close #31376
Reference: retry check implementation in tidb-tools: https://github.com/pingcap/tidb-tools/blob/b1def7746ec382a71a70b8958b1053202092f95c/pkg/dbutil/retry.go#L43
Tests 
Side effects
Documentation
```release-note
None
```

lightning: add more retryable error type

---

server/conn.go
server/conn_stmt.go
server/conn_stmt_test.go
server/util.go

Cherry-pick https://github.com/pingcap/tidb/pull/30723 to release-5.3-20211223.

server: support decoding prepared string args to character_set_client(#30723)

---

cmd/explaintest/r/collation_check_use_collation_disabled.result
cmd/explaintest/r/collation_check_use_collation_enabled.result
cmd/explaintest/run-tests.sh
cmd/explaintest/t/collation_check_use_collation.test
expression/builtin_cast.go
planner/core/expression_rewriter.go

Issue Number: close #31551
Tests 
Side effects
Documentation
```release-note
None
```

expression: fix BuildCastCollationFunction

---

planner/optimize.go

Tests 
Side effects
Documentation
```release-note
None
```

planner: add connID when GetPreparedStmt

---

ddl/placement_policy_test.go
ddl/placement_sql_test.go

Issue Number: Close #31455
This PR added some tests, the bug is already fixed by #31093
Tests 
Side effects
Documentation
```release-note
None
```

*: Add some tests for CreateTable/SchemaWithInfo for placement

---

br/pkg/lightning/config/config.go
br/pkg/lightning/config/config_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/31656
Problem Summary: fix the issue that use the non-exists sorted-dir is valid.
Tests 
Side effects
Documentation
```release-note
None
```

lightning: fix storage not exists error

---

tidb-server/main.go

Issue Number: close #31672
```
$ ./bin/tidb-server -config <(echo -en '[log]\nformat="json"\n')
{"level":"INFO","time":"2022/01/13 13:46:57.969 +01:00","caller":"cpuprofile.go:111","message":"parallel cpu profiler started"}
```
Previously this would not have been in JSON format
Tests 
Side effects
Documentation
```release-note
None
```

main: Fix logging setup

---

util/topsql/stmtstats/aggregator.go
util/topsql/stmtstats/aggregator_test.go

Signed-off-by: mornyx <mornyx.z@gmail.com>
Issue Number: ref #31704
```release-note
None
```

topsql: do not aggregate when topsql is not enabled

---

metrics/grafana/performance_overview.json

Issue Number: close #31676
Tests 
import the dashboard to existing grafana and enjoy the strait-forward metrics
Side effects
Documentation
```release-note
add a performance overview dashboard, to show the core performance metrics on the typical critical path in one dashboard and make the metric analysis on TiDB much easier
```

metrics: Add a new performance overview dashboard

---

session/session.go

Issue Number: close #30880
Manually cherry pick https://github.com/pingcap/tidb/pull/31723 to the release-5.4 branch
Tests 
Side effects
Documentation
```release-note
None
```

*: don't use chunk rpc protocol for internal session

---

executor/admin_test.go

Issue Number: ref #26833
There's some mistake in the comments and a sentence is incomplete. Fix it.
Tests 
```release-note
None
```

test: Fix an incomplete comment

---

util/topsql/reporter/datamodel.go
util/topsql/reporter/datamodel_test.go

Issue Number: ref #31192, ref #28720
Tests 
Side effects
Documentation
```release-note
None
```

util/topsql: remove unused functions

---

domain/db_test.go
domain/domain_test.go
domain/main_test.go
executor/executor_pkg_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: remove the t.Run

---

br/pkg/lightning/metric/metric_test.go
br/pkg/lightning/tikv/tikv_test.go
br/pkg/lightning/verification/checksum_test.go
br/pkg/lightning/worker/worker_test.go

Issue Number: close #28239, close #28243, close #28242, close #28244
```release-note
None
```

br/pkg/lightning: migrate test-infra to testify

---

executor/analyze_test.go

Issue Number: close #31907
Tests 
Side effects
Documentation
```release-note
None
```

*: fix data race in the TestAnalyzeIncremental

---

br/pkg/lightning/config/bytesize_test.go
br/pkg/lightning/config/config_test.go
br/pkg/lightning/config/configlist_test.go

Issue Number: close #28237
```release-note
None
```

br/pkg/lightning/config: migrate test-infra to testify

---

util/topsql/collector/cpu.go

fix typo
Tests 
Side effects
Documentation
```release-note
None
```

topsql: fix typo

---

metrics/grafana/tidb.json

Signed-off-by: ekexium <ekexium@gmail.com>
Issue Number: ref #26833
Add grafana panels for assertion ~and mutation checker~ under the "Transaction" row.
Tests 
Side effects
Documentation
```release-note
None
```

metrics: add grafana panels for assertion

---

cmd/explaintest/r/collation_misc_disabled.result
cmd/explaintest/r/collation_misc_enabled.result
cmd/explaintest/r/new_character_set.result
cmd/explaintest/t/collation_misc.test
cmd/explaintest/t/new_character_set.test
ddl/db_integration_test.go
ddl/db_test.go
executor/partition_table_test.go
executor/set_test.go

Issue Number: ref #31625
Tests 
Side effects
Documentation
```release-note
None
```

*: refine some tests related to the collation

---

dumpling/export/dump_test.go

Issue Number: close #32008
Tests 
Side effects
Documentation
```release-note
None
```

 dumpling: fix unstable test TestDumpBlock

---

ddl/attributes_sql_test.go

Tests 
Side effects
Documentation
```release-note
None
```

ddl: improve test for attributes_sql_test.go

---

br/pkg/lightning/restore/check_info_test.go
br/pkg/lightning/restore/checksum.go
br/pkg/lightning/restore/checksum_test.go
br/pkg/lightning/restore/chunk_restore_test.go
br/pkg/lightning/restore/meta_manager_test.go
br/pkg/lightning/restore/restore_schema_test.go
br/pkg/lightning/restore/restore_test.go
br/pkg/lightning/restore/table_restore_test.go
br/pkg/lightning/restore/tidb_test.go

Issue Number: ref #28241
(it does not close the issue because it is incomplete. there are still some issue in `restore_schema_test.go`)
Problem Summary: Migrate test to testify
Tests 
```release-note
None
```

br/lightning: migrate test to testify for restore

---

br/pkg/lightning/checkpoints/checkpoints_file_test.go
br/pkg/lightning/checkpoints/checkpoints_test.go
br/pkg/lightning/common/security_test.go
br/pkg/lightning/common/storage_test.go
br/pkg/lightning/mydump/csv_parser_test.go
br/pkg/lightning/mydump/loader_test.go
br/pkg/lightning/mydump/parquet_parser_test.go
br/pkg/lightning/mydump/reader_test.go
br/pkg/lightning/mydump/region_test.go
executor/memtable_reader_test.go
server/tidb_serial_test.go
server/tidb_test.go
store/mockstore/unistore/cophandler/cop_handler_test.go
store/mockstore/unistore/tikv/mvcc_test.go
util/disk/tempDir_test.go

Issue Number: close #32070
Tests 
Side effects
Documentation
```release-note
None
```

*: replace os.MkdirTemp with t.TempDir

---

planner/core/errors_test.go

Issue Number: close #28407
Tests 
Side effects
Documentation
```release-note
None
```

planner: migrate test-infra to testify for planner/core/errors_test

---

ddl/placement_sql_test.go

Issue Number: close #29107
Migrate ddl/placement_sql_test to use testify 
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Use testify in ddl/placement_sql_test

---

executor/trace_test.go

Issue Number: close #28622
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate `trace_test.go` to testify

---

Makefile

Issue Number: close #32113
Clean up an unused command
Tests 
Side effects
Documentation
```release-note
None
```

Makefile: cleanup a unused makefile target 'devgotest'

---

executor/window_test.go

Issue Number: close #28626
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for window_test.go

---

domain/domain.go

Issue Number: close #32042
Tests 
Side effects
Documentation
```release-note
None
```

domain: fix panic when Domain.Close()

---

session/bootstrap_test.go

Issue Number: ref #31966
Close the domain to avoid the leak.
Tests 
Side effects
Documentation
```release-note
None
```

session: dom.Close() in boostrap_test

---

statistics/handle/ddl_test.go
statistics/handle/dump_test.go
statistics/handle/gc_test.go
statistics/handle/handle_test.go
statistics/handle/update_test.go
testkit/testkit.go

Issue Number: close #28127 close #28126 close #27141 close #30006
```release-note
None
```

statistics/handle: migrate test-infra to testify

---

planner/core/logical_plans_test.go

Issue Number: close #28410
Tests 
Side effects
Documentation
```release-note
None
```

planner/core: migrate `logical_plans_test.go` to testify

---

store/store_test.go

Issue Number: close #32182
```release-note
None
```

stroe: clean up pingcap/check dep

---

util/ranger/ranger_test.go

Issue Number: close #32180
```release-note
None
```

util/range: replace in-place create store helper function with testkit

---

executor/join_pkg_test.go
executor/pkg_test.go

Issue Number: close #28601
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for pkg_test

---

planner/core/main_test.go
planner/core/rule_inject_extra_projection_test.go
planner/core/rule_join_reorder_dp_test.go
planner/core/rule_result_reorder_test.go
testkit/testdata/testdata.go

Issue Number: close #28396 close #28397 close #28398
```release-note
None
```

planner/core: migrate test-infra to testify for rule_ tests

---

store/mockstore/unistore/tikv/errors.go
store/mockstore/unistore/tikv/mvcc.go
store/mockstore/unistore/tikv/mvcc_test.go
store/mockstore/unistore/tikv/server.go

Issue Number: ref #26833 
This is part of #31547 , which includes changes to unistore. This PR is split out to make it easier to update client-go.
Tests 
Side effects
Documentation
```release-note
None
```

unistore: Update unistore for assertion

---

session/pessimistic_test.go

Signed-off-by: zyguan <zhongyangguan@gmail.com>
Issue Number: close https://github.com/pingcap/tidb/issues/30677
Some tests within `testPessimisticSuite` are unstable because sometimes locks are gone unexpectedly. After some investigations we found that the lock ttl is set to 300ms by default, thus the problem may caused by the jitter of the environment (many slowlog items are seen).
Related CI links:
- https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/63945/pipeline/
- https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/63783/pipeline/
Increase default lock ttl used in `testPessimisticSuite`. The previous 300ms TTL is introduced by https://github.com/pingcap/tidb/pull/11037 for …

session: increase default lock ttl to stabilize pessimistic test suite

---

cmd/explaintest/r/new_character_set_builtin.result
cmd/explaintest/r/select.result
cmd/explaintest/t/new_character_set_builtin.test
expression/builtin_convert_charset.go

Issue Number: close #30444
Tests 
Side effects
Documentation
```release-note
None
```

expression: refine invalid char error msg for string conversion

---

ddl/db_integration_test.go
ddl/db_partition_test.go
ddl/serial_test.go

Issue Number: close #28634
Tests 
Side effects
Documentation
```release-note
None
```

ddl: migrate test-infra to testify for db_integration_test 

---

bindinfo/handle.go

Issue Number: ref #32224
Tests 
Side effects
Documentation
```release-note
None
```

bindinfo: fix inconsistent comments

---

session/session.go
statistics/handle/handle.go
util/sqlexec/restricted_sql_executor.go

Issue Number: close #32233 
Tests 
Side effects
Documentation
```release-note
None
```

*: refactor sqlexec to support using current session

---

go.mod
go.sum

Tests 
Side effects
Documentation
```release-note
None
```

*: Remove replace client go for ft-data-inconsistency 

---

Makefile
tools/check/ut.go

Issue Number: close #32243
1. clean up the generate test.bin files after test
2. close the temporary coverage profile file after handling its data, to avoid the "too many open files" error
Tests 
Side effects
Documentation
```release-note
None
```

Makefile: tiny polish the `make ut` command

---

br/pkg/gluetidb/glue.go
br/pkg/logutil/logging.go
br/pkg/restore/client.go
br/pkg/stream/stream_mgr.go
br/pkg/task/stream.go
executor/brie.go

Signed-off-by: Yu Juncen <yu745514916@live.com>
Issue Number: ref #32167
Problem Summary: See the issue.
Tests 
```release-note
None
```

br-stream: backup record key only

---

executor/explain_test.go

Issue Number: close #28578
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for explain_test

---

planner/core/main_test.go
planner/core/point_get_plan_test.go

Issue Number: close #28393
Tests 
Side effects
Documentation
```release-note
None
```

planner: migrate test-infra to testify for point_get_plan_test

---

ddl/placement/bundle_test.go
ddl/placement/common_test.go
ddl/placement/constraint_test.go
ddl/placement/constraints_test.go
ddl/placement/meta_bundle_test.go
ddl/placement/rule_test.go

Issue Number: close #27671
```release-note
None
```

ddl/placement: migrate test-infra to testify

---

ddl/db_integration_test.go
executor/join_test.go
executor/show_test.go
executor/stale_txn_test.go
expression/integration_serial_test.go
statistics/selectivity_test.go
util/chunk/row_container_test.go

Issue Number: close #28618
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for stale_txn_test

---

sessionctx/variable/session.go
sessionctx/variable/session_test.go

Signed-off-by: lemonhx <lemonhx@lemonhx.tech>
Issue Number: close #32222
Tests 
Side effects
Documentation
```release-note
None
```

sessionctx: fix issue #32222

---

executor/infoschema_reader.go
infoschema/cluster_tables_test.go
util/stmtsummary/reader.go
util/stmtsummary/statement_summary_test.go

Issue Number: close #32156 
Tests 
```release-note
None
```

 statement table: fixed issue #32156 time_zone not sync in stmt table

---

executor/insert_test.go
testkit/testkit.go

Issue Number: close #28588
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for insert_test

---

executor/show_placement_labels_test.go

Issue Number: close #28609 
```release-note
None
```

executor: migrate test-infra to testify for show_placement_labels_test.go

---

executor/sample_test.go

Issue Number: close #28606
```release-note
None
```

executor: migrate test-infra to testify for sample_test.go

---

executor/explain_test.go
store/mockstore/unistore/cophandler/closure_exec.go
store/mockstore/unistore/cophandler/cop_handler.go
store/mockstore/unistore/cophandler/cop_handler_test.go
store/mockstore/unistore/cophandler/mpp.go
store/mockstore/unistore/cophandler/mpp_exec.go
store/mockstore/unistore/tikv/dbreader/db_reader.go

Issue Number: close #26878 
How it Works:
Tests 
Side effects
Documentation
```release-note
None
```

copr: replace unistore closure executors with existing mpp executors

---

executor/show_placement_test.go

Issue Number: close #28610
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for show_placement_test

---

executor/analyze_test.go
planner/core/integration_partition_test.go
planner/core/plan_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: remove skip test

---

br/pkg/restore/client.go
br/pkg/restore/import.go
br/pkg/task/stream.go
go.mod
go.sum

add restore ts to filter kv event for br-stream restore.
1. update kvproto
2. add restore ts in `ApplyRequest`
Tests 
Manual test:
1. use `tiup bench tpcc prepare --warehouses 1 --db tpcc --threads 8 -P 4000` to build base dataset.
2. start full backup and log backup
3. insert 5 rows in `tpcc.orders` and record coarse current ts (431203771482112000)
4. start full restore and log restore with --restore-ts(431203771482112000) in another cluster.
5. check data consistent.
Side effects
Documentation
```release-note
None
```

br-stream: add restore_ts for apply

---

store/mockstore/unistore/cophandler/mpp_exec.go

Issue Number: close #32408
Tests 
Side effects
Documentation
```release-note
None
```

executor, unistore: simply add a wait group to avoid data race

---

executor/ddl_test.go

Issue Number: close #28572
Tests 
Side effects
Documentation
```release-note
None
```

executor: migrate test-infra to testify for ddl_test

---

util/cpuprofile/cpuprofile.go
util/cpuprofile/cpuprofile_test.go

Issue Number: close #32080
close #32304
```release-note
None
```

cpuprofile: fix unstable test

---

executor/joiner_test.go

Issue Number: close #28594 
```release-note
None
```

executor: migrate test-infra to testify for joiner_test.go

---

tools/check/ut.go

Issue Number: close #32442
When some test case fail, the process should exit with non-zero code.
Tests 
Side effects
Documentation
```release-note
None
```

tools/check: exit non-zero when the unit test fail

---

statistics/handle/handle.go
statistics/handle/update.go

Issue Number: close #32426 
Data race imported by https://github.com/pingcap/tidb/pull/32229
Tests 
Side effects
Documentation
```release-note
None
```

statistics: fix data race

---

ddl/sequence_test.go

Issue Number: close #29112
Tests 
Side effects
Documentation
```release-note
None
```

ddl: migrate test-infra to testify for sequence_test

---

executor/metrics_reader_test.go

Issue Number: close #28598 
```release-note
None
```

executor: migrate test-infra to testify for metrics_reader_test.go

---

planner/core/main_test.go
planner/core/physical_plan_test.go

Issue Number: close #28409 close #32108
```release-note
None
```

planner/core: migrate test-infra to testify for physical_plan_test.go

---

ddl/ddl_worker.go
ddl/table.go

Tests 
Side effects
Documentation
```release-note
None
```

ddl: onDropTableOrView remove useless parameter

---

ddl/ddl.go
ddl/ddl_worker.go

Issue Number: close #32541
Move ddlSeqNumMu and ddlSeqNum to ddlCtx
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix data race for ddl seq

---

planner/core/cbo_test.go
planner/core/main_test.go

Issue Number: close #28388
```release-note
None
```

planner/core: migrate test-infra to testify for cbo_test.go

---

br/tests/lightning_new_collation/data/nc.t-schema.sql
br/tests/lightning_new_collation/data/nc.t.0.sql
br/tests/lightning_new_collation/data/nc.t.1.sql
br/tests/lightning_new_collation/run.sh

Test `lighting_new_collation` test failed in ci:
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10247/pipeline/
Fix the `lighting_new_collation` test.
Tests 
Side effects
Documentation
```release-note
None
```

lightning: fix lighting_new_collation test

---

statistics/handle/handle_hist_test.go

Issue Number: close #32580 
Tests 
Side effects
Documentation
```release-note
None
```

handle_test: fix unstable test in the TestConcurrentLoadHistTimeout 

---

table/tables/tables_test.go

Issue Number: close #32412
The test case exit before the goroutine exit, so there are leaked goroutine in the test code.
```
[2022-02-24T12:38:39.775Z] goleak: Errors on successful test run: found unexpected goroutines:
[2022-02-24T12:38:39.775Z] [Goroutine 350 in state select, with [github.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop](http://github.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop) on top of the stack:
[2022-02-24T12:38:39.775Z] goroutine 350 [select]:
[2022-02-24T12:38:39.775Z] [github.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop](http://github.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop)(0xc000b6ff00, 0xdf8475800) …
```

table/tables: make test case TestConstraintCheckForUniqueIndex stable

---

ddl/column_change_test.go
ddl/column_test.go
ddl/ddl_test.go
ddl/ddl_worker_test.go
ddl/foreign_key_test.go
ddl/index_change_test.go
ddl/integration_test.go
ddl/main_test.go
ddl/placement_policy_ddl_test.go
ddl/reorg_test.go
ddl/restart_test.go
ddl/stat_test.go

Issue Number: close #32673
```release-note
None
```

ddl: cleanup redundant globally settings for tests

---

config/config.go
executor/aggregate_test.go
executor/executor_test.go
executor/main_test.go
executor/set_test.go

Issue Number: close #28608 
```release-note
None
```

executor: migrate test-infra to testify for set_test.go

---

ddl/placement_policy_test.go

Issue Number: ref #27180
Tests 
Side effects
Documentation
```release-note
None
```

ddl: migrate test-infra to testify for placement_policy_test

---

executor/inspection_result_test.go
executor/memtable_reader_test.go
testkit/testkit.go

Issue Number: close #28590 
```release-note
None
```

executor: migrate test-infra to testify for inspection_result_test.go

---

ddl/db_integration_test.go
ddl/primary_key_handle_test.go
testkit/testutil/require.go
util/testutil/testutil.go

Issue Number: close #32843 
```release-note
None
```

ddl: migrate test-infra to testify for primary_key_handle_test.go

---

metrics/grafana/tidb.json

Issue Number: close #32832
Add TopSQL metrics in grafana.
Tests 
```release-note
None
```

metrics: add topsql grafana pannel

---

Makefile
telemetry/data_slow_query.go

Signed-off-by: huangxr <huangxr.me@gmail.com>
Issue Number: close #32844
Tests 
Side effects
Documentation
```release-note
None
```

Makefile, telemetry: fix typo

---

executor/load_data.go
executor/write_test.go

Signed-off-by: ti-srebot <ti-srebot@pingcap.com>
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix load data panic if the data is broken at escape character(cherry pick #30868 to release-5.4-20220308)

---

br/pkg/metautil/metafile.go
br/pkg/restore/client.go
br/pkg/restore/import.go
br/pkg/stream/client.go
br/pkg/stream/integration_test.go
br/pkg/stream/models.go
br/pkg/stream/prefix_scanner.go
br/pkg/task/stream.go

Issue Number: close #32253 
Added progress bar for log restoring.
This work is based on #32168
Tests 
```release-note
None
```

br/restore: Added progress bar for restore

---

expression/builtin_time_test.go
types/convert.go
types/convert_test.go

Issue Number: close #31680 
Tests 
Side effects
Documentation
```release-note
fix Timediff builtin func
```

expression, types: fix StrToDuration result

---

ddl/db_partition_test.go
ddl/ddl_test.go
ddl/ddl_worker_test.go
ddl/foreign_key_test.go
ddl/partition_test.go
ddl/schema_test.go
ddl/table_test.go
ddl/util_test.go

Issue Number: ref #27180
```release-note
None
```

ddl: remove temporary testing methods

---

unstable.txt

Signed-off-by: dianqihanwangzi <dianqihanwangzi@gmail.com>
Issue Number: ref #32303 
Side effects
Documentation
```release-note
None
```

*: update unstable unit test case list

---

ddl/column_modify_test.go
ddl/db_legacy_test.go

Issue Number: close #32963 
```release-note
None
```

ddl: migrate test-infra to testify for ddl.testDBSuite3

---

telemetry/data_feature_usage.go
telemetry/data_feature_usage_test.go

Signed-off-by: ekexium <ekexium@gmail.com>
Issue Number: ref #26833
Add the usage info of the mutation checker and assertion.
Tests 
Side effects
Documentation
```release-note
None
```

telemetry: add mutation checker and assertion usage info to TxnUsage

---

telemetry/data_feature_usage.go
telemetry/data_feature_usage_test.go

Issue Number: close #32807 
Add telemetry for new feature indroduced in https://github.com/pingcap/tidb/pull/32806.
Tests 
Side effects
Documentation
```release-note
None
```

telemetry: add telemetry for tso optimization

---

session/bootstrap.go

Issue Number: close https://github.com/pingcap/tidb/issues/33163
correctly increment the bootstrap version
correctly increment the bootstrap version
Tests 
Side effects
Documentation
```release-note
None
```

bootstrap: correctly increment the bootstrap version

---

executor/hot_regions_history_table_test.go

Issue Number: close #33327
Tests 
Side effects
Documentation
```release-note
None
```

executor: improve the way of getting table_id in the TestTiDBHotRegionsHistory

---

.github/workflows/br_compatible_test.yml
.github/workflows/compile_br.yaml
.github/workflows/dumpling_integration_test.yml

Issue Number: close #32874
Tests 
Side effects
Documentation
```release-note
None
```

*: update go1.18 for github action job

---

executor/executor_legacy_test.go
executor/executor_test.go
testkit/testkit.go

Issue Number: ref #28577 
```release-note
None
```

executor: migrate test-infra to testify for executor_test.go testSuiteP1

---

config/config.go
config/config_test.go

Issue Number: close #33337
Problem Summary: config: be compatible with deprecated stmt-summary config items
config: be compatible with deprecated stmt-summary config items
Tests 
Side effects
Documentation
```release-note
None
```

config: be compatible with deprecated stmt-summary config items

---

util/dbutil/common_test.go
util/dbutil/index_test.go
util/dbutil/retry_test.go
util/dbutil/table_test.go
util/dbutil/variable_test.go
util/filter/schema_test.go
util/table-filter/column_filter_test.go
util/table-filter/table_filter_test.go
util/table-router/router_test.go

Issue Number: close #33454 #33456 #33458 #33459
Tests 
Side effects
Documentation
```release-note
None
```

util: migrate test-infra to testify for dbutil,filter,table-filter

---

util/etcd/etcd_test.go

Issue Number: close #33455
Tests 
Side effects
Documentation
```release-note
None
```

util: migrate test-infra to testify for etcd

---

util/schemacmp/lattice_test.go
util/schemacmp/type_test.go

Issue Number: close #33457
Tests 
Side effects
Documentation
```release-note
None
```

util: migrate test-infra to testify for util/schemacmp pkg

---

go.mod
go.sum
store/copr/store.go
store/mockstore/redirector.go
store/mockstore/unistore/rpc.go

close pingcap/tidb#33537
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
Issue Number: close #33537
Make TiDB be compatible with latest client-go.
Update client-go.
Tests 
Side effects
Documentation
```release-note
None
```

*: update client-go

---

br/pkg/restore/client.go
br/pkg/restore/import.go
br/pkg/task/stream.go
br/pkg/task/stream_test.go
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/33400
- Support checkSum in file level when stream restore DML kv-events.
- 
Tests 
Side effects
Documentation
```release-note
None
```

br: support checkSum during restore dml kv-events.

---

util/dbutil/common.go
util/dbutil/common_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/32999
the code is changed and caused a bug
Tests 
Side effects
Documentation
```release-note
None
```

util: fix GetTimeZoneOffset error when migrating repo

---

tools/check/ut.go

Issue Number: close #32690  #32392
The 'segmentation fault' panic is weird, there is no more information, just this error message:
```
[2022-03-29T10:34:30.137Z] [FAIL]  planner/core TestIssue16837
[2022-03-29T10:34:30.137Z] err=signal: segmentation fault (core dumped)
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/43086/artifacts/
I try to debug the panic stack but there is nothing interesting.
```
(gdb) bt
#0  runtime.lock2 (l=0x5e937f8 <runtime.sched+24>) at /usr/local/go/src/runtime/lock_futex.go:53
#1  0x000000000129dfa5 in runtime.lockWithRank (l=<optimized out>, rank=<optimized out>) at /usr/local/go/src/runtime/lockrank_off.go:22
#2  runtime.lock (l=<optimized out>) at /usr/local/go/src/runtime/lock_futex.go:47 …
```

tools/check: make ut retry on special 'segmentation fault' error

---

ddl/db_partition_test.go
ddl/ddl_api.go

Issue Number: close #32748
Unnecessary check for equal values compared folded values, which is wrong for _bin collations.
Removed the check, since the following check is now collation aware.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: increasing value of partition by range columns fix (#32748)

---

go.mod
go.sum

Issue Number: close #33649 #33667
it has been fixed in https://github.com/dgraph-io/ristretto/pull/133
Tests 
Side effects
Documentation
```release-note
None
```

gomod: update ristretto and sarama to fix data race

---

util/column-mapping/README.md
util/column-mapping/column.go
util/column-mapping/column_test.go
util/ddl-checker/ddl_syncer.go
util/ddl-checker/executable_checker.go
util/ddl-checker/executable_checker_test.go

Issue Number: close #32999
Tests 
Side effects
Documentation
```release-note
None
```

util: migrate column-mapping and ddl-checker from tidb-tools to tidb

---

util/ddl-checker/executable_checker_test.go

Issue Number: close #33701
Tests 
Side effects
Documentation
```release-note
None
```

util: refactor TestExecute to fix data race

---

executor/copr_cache_test.go
executor/executor_legacy_test.go

Issue Number: close #33442 
```release-note
None
```

executor: migrate test-infra to testify for executor_test.go testCoprCache

---

executor/executor_failpoint_test.go
executor/executor_legacy_test.go
executor/recover_table_test.go
testkit/testkit.go

Issue Number: close #33435 
```release-note
None
```

executor: migrate test-infra to testify for testRecoverTable

---

ddl/db_integration_test.go

Issue Number: close #33807
Tests 
Side effects
Documentation
```release-note
None
```

*: fix unstable case `TestIssue29282`

---

executor/stale_txn_test.go
session/session.go

Issue Number: close #33814
Tests 
Side effects
Documentation
```release-note
None
```

*: forbid using cache when stale read in binary proto

---

executor/cluster_table_test.go
executor/executor_legacy_test.go

Issue Number: close #33436
```release-note
None
```

executor: migrate test-infra to testify for testClusterTableSuite

---

util/importer/config.go
util/importer/data.go
util/importer/db.go
util/importer/importer.go
util/importer/job.go
util/importer/parser.go
util/importer/rand.go
util/watcher/event.go
util/watcher/watcher.go
util/watcher/watcher_test.go

Issue Number: close #32999
Tests 
Side effects
Documentation
```release-note
None
```

util: migrate importer and watcher from tidb-tools to tidb

---

executor/slow_query.go
infoschema/cluster_tables_test.go

Issue Number: close #33974
Tests 
```release-note
None
```

executor: fix issue of query instance from CLUSTER_SLOW_QUERY return '' result

---

br/pkg/restore/import_retry.go
br/pkg/stream/client.go
br/pkg/stream/models.go
br/pkg/stream/stream_status.go
br/pkg/task/stream.go
go.mod
go.sum

Issue Number: ref https://github.com/pingcap/tidb/issues/30544
This PR:
1. Make `stream status` shows information about last errors.
2. Clean the error when executing `stream resume`.
Tests 
Side effects
Documentation
```release-note
None
```

br/stream: make status shows the log

---

config/config_test.go
dumpling/export/sql_test.go
parser/consistent_test.go
parser/reserved_words_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: remove useless code

---

ddl/cancel_test.go
ddl/ddl.go
ddl/ddl_worker.go
ddl/rollingback.go
parser/model/ddl.go
util/admin/admin.go
util/admin/admin_test.go

Tests 
Side effects
Documentation
```release-note
None
```

parser: turn some functions into member functions of model.Job

---

br/tests/br_gcs/run.sh

Issue Number: close #33811 
#33568 didn't fix tikv integration tests. This PR tries to fix it.
Tests 
Side effects
Documentation
```release-note
None
```

br_gcs: fix tikv integration test

---

br/cmd/br/restore.go
br/cmd/br/stream.go
br/pkg/restore/client.go
br/pkg/stream/meta_kv_test.go
br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/task/stream.go
meta/meta.go
meta/meta_test.go

- rename the command `br stream` to `br log`.
- support restoring sequenceID/auto_incrementID/auto_randomID.
- report other TiDBs after update global schema version.
- 
Tests 
Side effects
Documentation
```release-note
None
```

br: support autoIncrementID, autoRandomID and sequenceID in PiTR

---

ddl/column_modify_test.go
ddl/db_integration_test.go
ddl/table_test.go
executor/executor_failpoint_test.go
executor/executor_issue_test.go
executor/infoschema_cluster_table_test.go

Issue Number: ref #33008
refine some tests for concurrent DDL
Tests 
Side effects
Documentation
```release-note
None
```

*: refine some tests for concurrent DDL

---

session/session_legacy_test.go
session/statistics_test.go
session/tidb_library_test.go

Issue Number: close #34292 
```release-note
None
```

session: migrate test-infra to testify for testStatisticsSuite

---

ddl/db_rename_test.go
ddl/ddl_api.go
ddl/ddl_test.go
ddl/foreign_key_test.go
ddl/placement_policy.go
ddl/placement_policy_ddl_test.go
ddl/reorg_test.go
ddl/stat_test.go
ddl/table_lock.go
ddl/table_test.go
ddl/util_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/34284
move some tests  to `ddl_test` package, export some function
Tests 
Side effects
Documentation
```release-note
None
```

ddl: move some tests to package `ddl_test`

---

server/util.go

Tests 
Side effects
Documentation
```release-note
None
```

server: debug inconsistency

---

executor/projection.go
owner/manager.go
testkit/asynctestkit.go
util/misc.go
util/misc_test.go

Issue Number: close #34356
before improvement:
```
[2022/05/03 00:23:20.820 +08:00] [ERROR] [main.go:22] ["recover panic"] [buffer="goroutine 1 [running]:\nmain.GetStack(...)\n\t/Users/hawkingrei/tmp/gomain/main.go:13\nmain.main.func1()\n\t/Users/hawkingrei/tmp/gomain/main.go:21 +0x59\npanic({0x117e360, 0x11f0890})\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207\nmain.main()\n\t/Users/hawkingrei/tmp/gomain/main.go:25 +0x49\n"] [stack="main.main.func1\n\t/Users/hawkingrei/tmp/gomain/main.go:22\nruntime.gopanic\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838\nmain.main\n\t/Users/hawkingrei/tmp/gomain/main.go:25\nruntime.main\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go: …
```

util: improve stack message in the panic log

---

executor/admin_test.go
go.mod
go.sum
server/conn.go
util/logutil/log.go

Issue Number: close #34359
```release-note
None
```

log: avoid panic on unknown log format

---

go.mod
go.sum

Issue Number: close #32747
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade testify and remove replace options

---

planner/core/enforce_mpp_test.go
planner/core/plan_cost_test.go
planner/core/task.go
planner/core/testdata/enforce_mpp_suite_out.json

Issue Number: ref #33945
Problem Summary: planner: add enforce-mpp test cases for the new cost implementation
add enforce-mpp test cases for the new cost implementation
Tests 
Side effects
Documentation
```release-note
None
```

planner: add enforce-mpp test cases for the new cost implementation

---

bindinfo/handle.go
br/pkg/lightning/restore/restore.go
br/pkg/lightning/restore/tidb.go
distsql/select_result.go
domain/sysvar_cache.go
planner/funcdep/fast_int_set_test.go
statistics/handle/statscache.go
table/temptable/interceptor.go

Issue Number: close #34454
```maps.Copy``` is a convenience function that allows us to map copy.
```
// Copy copies all key/value pairs in src adding them to dst.
// When a key in src is already present in dst,
// the value in dst will be overwritten by the value associated
// with the key in src.
func Copy[M ~map[K]V, K comparable, V any](dst, src M) {
for k, v := range src {
dst[k] = v
}
}
```
Tests 
```release-note
None
```

*: improve map copy

---

Dockerfile

Issue Number: close #34482
Tests 
```
docker build -t tidb .
```
```release-note
None
```

*: use go1.18 in the dockerfile

---

br/cmd/br/stream.go
br/pkg/backup/client.go
br/pkg/backup/client_test.go
br/pkg/backup/schema.go
br/pkg/backup/schema_test.go
br/pkg/gluetidb/glue.go
br/pkg/metautil/metafile.go
br/pkg/restore/client.go
br/pkg/restore/db_test.go
br/pkg/restore/import_retry.go
br/pkg/restore/rawkv_client.go
br/pkg/restore/rawkv_client_test.go
br/pkg/restore/util.go
br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/task/backup.go
br/pkg/task/backup_raw.go
br/pkg/task/restore.go
br/pkg/task/stream.go
br/pkg/task/stream_test.go
br/pkg/utils/schema.go
parser/model/model.go

- It can directly restore log from start-ts to restore-ts without full-snapshot.
- It can restore log from last-restore-ts to new-restore-ts after last restore operation.
Tests 
Side effects
Documentation
```release-note
None
```

br: restore log from start-ts to restore-ts

---

cmd/ddltest/ddl_test.go
executor/analyze.go
executor/distsql.go
executor/executor.go
executor/index_lookup_join.go
executor/index_lookup_merge_join.go
server/conn.go
statistics/handle/handle_hist.go

Issue Number: close https://github.com/pingcap/tidb/issues/34356
before improvement:
```
[2022/05/03 00:23:20.820 +08:00] [ERROR] [main.go:22] ["recover panic"] [buffer="goroutine 1 [running]:\nmain.GetStack(...)\n\t/Users/hawkingrei/tmp/gomain/main.go:13\nmain.main.func1()\n\t/Users/hawkingrei/tmp/gomain/main.go:21 +0x59\npanic({0x117e360, 0x11f0890})\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207\nmain.main()\n\t/Users/hawkingrei/tmp/gomain/main.go:25 +0x49\n"] [stack="main.main.func1\n\t/Users/hawkingrei/tmp/gomain/main.go:22\nruntime.gopanic\n\t/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838\nmain.main\n\t/Users/hawkingrei/tmp/gomain/main.go:25\nruntime.main\n\t/usr/local/Cellar/ …
```

*: improve stack message in the panic log

---

executor/set_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/34052
add unit test for assert tidb_stats_cache_mem_quota
Tests 
```release-note
None
```

config: add unit test for assert tidb_stats_cache_mem_quota

---

expression/expr_to_pb_test.go
expression/expression.go

Signed-off-by: yibin <huyibin@pingcap.com>
Issue Number: close #34625 
Tests 
Side effects
Documentation
```release-note
None
```

expression: Support to_seconds function push down for tiflash

---

executor/hot_regions_history_table_test.go
executor/infoschema_cluster_table_test.go

Issue Number: ref #26854
```release-note
None
```

executor: remove testify suite

---

domain/domain.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go

Issue Number: close https://github.com/pingcap/tidb/issues/34773
Tests 
I manually tested origin variable function which is worked as expected.
```release-note
None
```

variable: fix 34773 race error

---

expression/aggregation/window_func.go
planner/core/testdata/window_push_down_suite_out.json

Issue Number: close https://github.com/pingcap/tidb/issues/34794
```release-note
None
```

expression: correct window function push down list.

---

executor/compact_table_test.go

Signed-off-by: Wish <breezewish@outlook.com>
Issue Number: close #34795
Problem Summary: Fix the data race introduced by test mocker.
Protect the modification field via a mutex.
Tests 
Side effects
Documentation
```release-note
None
```

test: fix data race in the test mocker

---

executor/set_test.go
planner/core/integration_test.go
planner/core/testdata/integration_suite_out.json
sessionctx/variable/sysvar.go

Issue Number: ref #33945
Problem Summary: disable the new cost implementation by default 
The release-6.1 is a long-term version, so for safety, we decide to disable the new cost implementation in this version and enable it in release-6.2.
Tests 
Side effects
Documentation
```release-note
None
```

planner: disable the new cost implementation by default 

---

README.md

Issue Number: close #34824
Update descriptions and content organization in readme
Tests 
Side effects
Documentation
```release-note
None
```

readme: update readme descriptions

---

ddl/db_change_failpoints_test.go
ddl/db_change_test.go
ddl/db_integration_test.go

Issue Number: ref #28633
```release-note
None
```

ddl: remove testify suite 

---

config/config.toml.example

Issue Number: close #34914
Tests 
Side effects
Documentation
```release-note
None
```

config: remove enable-chunk-rpc in example config

---

domain/infosync/info.go
sessionctx/variable/variable.go

Signed-off-by: TonsnakeLin <lpbgytong@163.com>
`refresh SysvarCache when tidb_gc_max_wait_time updated`
Issue Number: close #34966 
Tests 
Side effects
Documentation
```release-note
None
```

variable: refresh sysvar cache for tidb_gc_max_wait_time

---

ddl/backfilling.go
ddl/cancel_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/34909
- mock slow in backfill
- make `tidb_ddl_reorg_batch_size` works
Tests 
```release-note
None
```

test: mock slow when backfilling data

---

infoschema/tables.go
parser/types/field_type.go

Signed-off-by: fanrenhoo <fanrenhoo@sina.com>
Issue Number: close #34745
Problem Summary: Add some annotation for columnInfo of INFORMATION_SCHEMA db
Tests 
No
Side effects
No
Documentation
No
```release-note
Add some annotation for columnInfo of INFORMATION_SCHEMA db
```

infoschema: add some annotation for columnInfo #34745

---

plugin/audit.go
plugin/const_test.go
plugin/plugin_test.go

Issue Number: ref #34963
This PR provides some methods to cast `plugin.GeneralEvent` to string value or string to `plugin.GeneralEvent` .
Tests
```release-note
None
```

*: Add `GeneralEventFromString` to `plugin.GeneralEvent`

---

config/config_test.go

Tests 
```release-note
None
```

config: improve test code

---

util/security.go

Issue Number: close #35012
as title
Tests 
Side effects
Documentation
```release-note
None
```

util: use tls1.0 as min tls version

---

ddl/ddl.go
executor/executor_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/35020
we should commit the txn even if it is a read txn because if the `gc` checker uses the same session, it will have a txn start with the same ts and cannot see the newest change.
Tests 
```release-note
None
```

test: fix `integration-ddl-test`

---

go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/34956
Tests 
Side effects
Documentation
```release-note
None
```

br: update package tikv client-go

---

ddl/db_test.go
ddl/label/rule.go
distsql/select_result.go
domain/schema_validator.go
planner/core/exhaust_physical_plans.go
planner/core/memtable_predicate_extractor.go
planner/core/stats.go
planner/funcdep/fast_int_set_test.go
session/schema_amender_test.go
store/mockstore/unistore/tikv/util.go
testkit/testutil/handle.go
util/execdetails/execdetails.go

Issue Number: ref #34250
- use pdqsort to improve sort performance
- remove less function in sort to remove BCE so that it can improve performance too.
Tests 
```release-note
None
```

*: use pdqsort to sort and remove BCE

---

executor/show.go
executor/show_test.go
planner/core/planbuilder.go
planner/core/show_predicate_extractor.go
planner/core/stringer_test.go

Issue Number: close #35047 
add a filter `plannercore.ShowCollationExtractor` in the ShowExec. It will bring the like expression to the place where to get meta and filter them for getting the right result.
Tests 
```text
mysql root@127.0.0.1:(none)> show collation like 'UTF8MB4_BI%';
+-------------+---------+----+---------+----------+---------+
| Collation   | Charset | Id | Default | Compiled | Sortlen |
+-------------+---------+----+---------+----------+---------+
| utf8mb4_bin | utf8mb4 | 46 | Yes     | Yes      | 1       |
+-------------+---------+----+---------+----------+---------+
1 row in set
Time: 0.012s
```
Side effects
Documentation …

executor: fix show collation like case sensitive issue

---

planner/core/find_best_task.go

Issue Number: ref #33945
Problem Summary: use compareTaskCost to compare costs between different plans
just refactor, no logical changes.
Tests 
Side effects
Documentation
```release-note
None
```

planner: use compareTaskCost to compare costs between different plans in `DataSource.findBestTask`

---

executor/simple_test.go

Tests 
```release-note
None
```

executor: clean test code 

---

br/pkg/task/stream.go

cherry-pick pr #35237 manually
Tests 
Side effects
Documentation
```release-note
None
```

br: add summary to stream restore

---

privilege/privileges/BUILD.bazel

Issue Number: ref #35247
Tests 
```release-note
None
```

privileges: enable flaky test

---

br/pkg/stream/client.go
br/pkg/stream/stream_misc_test.go
br/pkg/stream/stream_status.go

Signed-off-by: Yu Juncen <yujuncen@pingcap.com>
Issue Number: close https://github.com/pingcap/tidb/issues/35164
cherry-pick https://github.com/pingcap/tidb/pull/35169
Tests 
Side effects
Documentation
```release-note
None
```

br: adapt new checkpoint model

---

br/pkg/restore/import.go
br/pkg/restore/split.go
br/pkg/restore/split_client.go
br/pkg/restore/split_test.go
br/pkg/restore/util_test.go
br/pkg/task/restore.go
br/tests/br_full/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/35211
cherry-pick https://github.com/pingcap/tidb/pull/35339
Tests 
Side effects
Documentation
```release-note
None
```

br: return given error and wait retry when failed to ScanRegions

---

br/pkg/restore/import_retry.go
br/pkg/restore/import_retry_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/35204
Cherry-pick https://github.com/pingcap/tidb/pull/35218
Tests 
Side effects
Documentation
```release-note
None
```

log_backup: fix the retry over wrapped errors (#35218)

---

executor/ddl_test.go
executor/write_test.go
testkit/testkit.go

Issue Number: ref https://github.com/pingcap/tidb/issues/31716
Tests 
```release-note
None
```

executor: close RecordSet in the ddl_test and write_test

---

ddl/ddl.go
ddl/ddl_test.go
ddl/ddl_worker.go

Issue Number: ref https://github.com/pingcap/tidb/issues/32031
Tests 
```release-note
None
```

ddl: refactor unlock seq and make ddl worker closeable

---

executor/main_test.go
go.mod
go.sum

Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Issue Number: close #34906
See https://github.com/tikv/client-go/pull/503
Tests 
Side effects
Documentation
```release-note
Prevent sending requests to unhealthy TiKV nodes to improve availability.
```

*: update client-go to improve availability on tikv failure

---

DEPS.bzl
build/BUILD.bazel
build/linter/exportloopref/BUILD.bazel
build/linter/exportloopref/analyzer.go
build/nogo_config.json
go.mod
go.sum
sessionctx/sessionstates/BUILD.bazel

Issue Number: ref #35345
Tests 
```release-note
None
```

*: enable exportloopref 

---

br/pkg/restore/client.go
br/pkg/restore/import.go
br/pkg/restore/import_retry.go
br/pkg/restore/import_retry_test.go
br/pkg/restore/split.go
br/pkg/restore/split_client.go
br/pkg/restore/split_test.go
br/pkg/restore/util_test.go
br/pkg/stream/client.go
br/pkg/stream/stream_misc_test.go
br/pkg/stream/stream_status.go
br/pkg/task/restore.go
br/pkg/task/stream.go
br/tests/br_full/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/29501
- [br: add summary to stream restore](https://github.com/pingcap/tidb/pull/35655/commits/fb6d0183a0faed433a39ea1b5d4b19145b98c9d5)
- [adapt new checkpoint model](https://github.com/pingcap/tidb/pull/35655/commits/1c48f92843b67fc5bf41832d1adefd22820c58cb)
- [br: return given error and wait retry when failed to ScanRegions](https://github.com/pingcap/tidb/pull/35655/commits/bd306c6041ddd2acef057cc658004fa95fa9af25)
- [log_backup: fix the retry over wrapped errors](https://github.com/pingcap/tidb/pull/35655/commits/b50d96f160a4610a02449717f8e2efe1407a7ba3)
- [log-backup: adjust restore concurrency](https://github.com/pingcap/tidb/pull/35655/commits/730e6aa000c0266be17313afce627042f0b8b579)
- [increase the retry …

log-backup: support pitr feature for PoC test 

---

br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/stream/rewrite_meta_rawkv_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/35757
Fix the bug, which uses the local variable.
Tests 
Side effects
Documentation
```release-note
None
```

log-backup: fix rewrite partition table

---

DEPS.bzl
build/BUILD.bazel
build/linter/asciicheck/BUILD.bazel
build/linter/asciicheck/analysis.go
build/linter/predeclared/BUILD.bazel
build/linter/predeclared/analysis.go
build/nogo_config.json
go.mod
go.sum
store/driver/error/error.go
store/driver/error/error_test.go

Issue Number: ref #35345
Tests 
Side effects
Documentation
```release-note
None
```

*: support predeclared and asciicheck

---

ddl/ddl_api.go

Issue Number: close #35945
fixes typo in comment
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix typo in comment

---

infoschema/builder.go
infoschema/infoschema.go

Signed-off-by: elijah <f1renze.142857@gmail.com>
Issue Number: close #36062
- use pdqsort to replace sorter interface
Tests 
Side effects
Documentation
```release-note
None
```

infoschema: use pdqsort to replace sorter interface

---

br/README.md

Issue Number: close #35997 
Updated broken in README.md
Tests 
Side effects
Documentation
```release-note
None
```

br: updated broken link

---

sessiontxn/isolation/main_test.go

Issue Number: close #36071
Tests 
```release-note
None
```

*: fix unstable test in `sessiontxn`

---

Makefile
dumpling/install.sh
dumpling/tests/run.sh
dumpling/tests/s3/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/36080
Fix s3 integration tests by using mc to download SQL files instead of reading it directly from the disk.
Tests 
- None
Side effects
- None
Documentation
- None
```release-note
None
```

dumpling: fix dumpling s3 integration tests

---

planner/core/plan_cost.go

pick https://github.com/pingcap/tidb/pull/35378
```release-note
None
```

planner: introduce new cost formula for Selection/TableScan/IndexScan

---

planner/core/plan_cost.go

pick #35408
```release-note
None
```

planner: introduce new cost formula for IndexLookup (#35408)

---

planner/core/common_plans.go
planner/core/plan_cost.go
planner/core/plan_cost_test.go
types/explain_format.go

pick https://github.com/pingcap/tidb/pull/34566
```release-note
None
```

planner: support 'explain analyze format=true_card_cost'  (#34566)

---

planner/core/plan_cost.go
planner/core/task.go

pick https://github.com/pingcap/tidb/pull/35436
```release-note
None
```

planner: introduce new cost formula for MPPAggs (#35436)

---

planner/core/plan_cost.go
planner/core/task.go
planner/implementation/join.go

pick https://github.com/pingcap/tidb/pull/35643
```release-note
None
```

planner: introduce new cost formula for MPPJoins (#35643)

---

planner/core/plan_cost.go
planner/core/task.go

pick https://github.com/pingcap/tidb/pull/35671
```release-note
None
```

planner: new cost formula for IndexJoin (#35671)

---

br/pkg/task/backup_ebs.go
br/pkg/task/common.go
br/pkg/task/restore_ebs_meta.go

Issue Number: ref #35306
Tests 
Side effects
Documentation
```release-note
None
```

ebs-based-br: change to skip-aws to ease local test

---

WORKSPACE

[here](https://github.com/golang/go/issues?q=milestone%3AGo1.18.4+label%3ACherryPickApproved) is the golang 1.18.4 release note
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.18.4

---

br/pkg/restore/client.go
br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/stream/rewrite_meta_rawkv_test.go

Issue Number: close #36251 
need to update job's raw_args
update decode way to job's raw_args when restore ddl job.
Tests 
Side effects
Documentation
```release-note
None
```

br restore point: update job's raw_args

---

build/nogo_config.json
lock/lock.go

Tests 
Side effects
Documentation
```release-note
None
```

*: enable revive for more components

---

ddl/ddl.go

Issue Number: ref #32031
Tests 
Side effects
Documentation
```release-note
None
```

ddl: set reorgCnt by judging the GOMAXPROCS

---

br/pkg/lightning/backend/local/localhelper.go

Issue Number: close https://github.com/pingcap/tidb/issues/36401
See https://github.com/pingcap/tidb/issues/36401.
This is a retriable error, we shouldn't print many warn logs that will confuse the user.
Tests 
```release-note
None
```

lightning: suppress warn log for scatter-region

---

telemetry/data_feature_usage.go
telemetry/data_feature_usage_test.go

Problem Summary: telemetry: add telemetry for cost_model_ver2
telemetry: add telemetry for cost_model_ver2
Tests 
Side effects
Documentation
```release-note
None
```

telemetry: add telemetry for cost_model_ver2

---

ddl/ddl.go

Issue Number: close #36429
Tests 
Side effects
Documentation
```release-note
None
```

ddl: skip to close nil sessPool 

---

ddl/ddl.go
ddl/job_table_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/36439
Tests 
```release-note
None
```

ddl: only set concurrent variable if no error

---

planner/core/rule_join_reorder_test.go
planner/core/testdata/join_reorder_suite_in.json
planner/core/testdata/join_reorder_suite_out.json

Issue Number: ref https://github.com/pingcap/tidb/issues/29932
add more test cases for leading outer join
add more test cases for leading outer join
Tests 
Side effects
Documentation
```release-note
None
```

planner: add more test cases for leading outer join

---

br/pkg/conn/conn.go
br/pkg/lightning/backend/local/local.go
br/pkg/lightning/backend/local/local_test.go
br/pkg/lightning/restore/check_info.go
br/pkg/version/version.go
domain/infosync/info.go
util/engine/engine.go

Issue Number: close https://github.com/pingcap/tidb/issues/36449
Tests 
```release-note
None
```

server: skip check tiflash version

---

ddl/ddl_api.go

Issue Number: close #36494
Tests 
Side effects
Documentation
```release-note
None
```

ddl: optimize map allocation

---

executor/infoschema_reader.go
table/tables/tables_test.go

This reverts commit 2c4a60da
Issue Number:  ref https://github.com/pingcap/tidb/issues/36496
Tests 
```release-note
None
```

executor: Revert "executor: fix tidb can not show view data_type (#22363)"

---

build/linter/revive/analyzer.go
build/nogo_config.json
planner/cascades/enforcer_rules.go
planner/cascades/implementation_rules.go
planner/cascades/optimize.go
planner/cascades/transformation_rules.go
planner/core/common_plans.go
planner/core/expression_rewriter.go
planner/core/find_best_task.go
planner/core/memtable_predicate_extractor.go
planner/core/plan.go
planner/core/plan_stats.go
planner/core/planbuilder.go
planner/core/preprocess.go
planner/core/property_cols_prune.go
planner/core/rule_aggregation_push_down.go
planner/core/rule_build_key_info.go
planner/core/rule_result_reorder.go
planner/core/stats.go
planner/core/task.go
planner/implementation/base.go
planner/implementation/datasource.go
planner/implementation/join.go
planner/implementation/simple_plans.go
planner/implementation/sort.go
planner/property/physical_property.go

Tests 
Side effects
Documentation
```release-note
None
```

*: fix revive in the planner

---

ddl/ddl_worker.go
session/bootstrap.go
sessionctx/variable/tidb_vars.go

Issue Number: close https://github.com/pingcap/tidb/issues/36601
Tests 
```release-note
None
```

upgrade: add a variable to make insert ddl job force to queue

---

util/admin/admin.go

Tests 
```release-note
None
```

admin: rename the same name field in the log

---

br/cmd/br/restore.go
br/pkg/aws/ebs.go
br/pkg/config/ebs.go
br/pkg/errors/errors.go
br/pkg/restore/data.go
br/pkg/summary/collector.go
br/pkg/task/backup_ebs.go
br/pkg/task/restore_data.go
br/pkg/task/restore_ebs_meta.go
go.mod
go.sum

Issue Number: close #36215
Tests 
https://github.com/fengou1/blr/tree/main/scripts/idc
Side effects
Documentation
```release-note
None
```

br: recover all tikv data into a consistency state

---

executor/aggregate_test.go

Tests 
Side effects
Documentation
```release-note
None
```

executor: close recordset in the aggregate_test

---

bindinfo/handle_test.go
ddl/column_test.go
executor/stale_txn_test.go
expression/integration_serial_test.go
infoschema/infoschema_test.go
planner/core/integration_test.go
session/bootstrap_upgrade_test.go
sessiontxn/isolation/optimistic_test.go
sessiontxn/isolation/readcommitted_test.go
sessiontxn/isolation/repeatable_read_test.go
sessiontxn/isolation/serializable_test.go
sessiontxn/staleread/processor_test.go
sessiontxn/staleread/provider_test.go
sessiontxn/txn_manager_test.go
statistics/trace_test.go
table/tables/partition_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: clean code

---

infoschema/tables.go

Issue Number: close #36688
Tests 
Side effects
Documentation
```release-note
None
```

infoschema: fix typo in variables_info

---

.bazelrc
WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade golang 1.18.5

---

Makefile

if we fail to build before changing. we will continue to build for finding more failing. but it means that it will take more time to build bad code.
Tests 
Side effects
Documentation
```release-note
None
```

*: remove keeping flag for build

---

.bazelrc

Tests 
```release-note
None
```

*: remove remote cache uri

---

sessionctx/variable/sysvar_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/36795
One of the main features of the [instance scope proposal](https://github.com/pingcap/tidb/blob/master/docs/design/2021-12-08-instance-scope.md) includes uniformity between config names and sysvars. This test ensures that this is the case.
Tests only
Tests 
This shows the test working when I manually add a new option which is invalid. Currently there is no problem:
```
--- FAIL: TestInstanceConfigHasMatchingSysvar (0.00s)
Error Trace:	/Users/mtocker/go/src/github.com/morgo/tidb/sessionctx/variable/sysvar_test.go:907
Error:      	Expected value not to be nil.
Test:       	TestInstanceConfigHasMatchingSysvar
Messages:   	config option: instance.new_option_here requires a matching sysvar of the same name
FAIL …
```

sessionctx/variable: Add tests for instance scoped config uniformity

---

executor/executor.go
planner/core/cache.go
planner/core/plan_cache.go
planner/core/planbuilder.go
planner/optimize.go
server/conn.go
server/conn_stmt.go
session/session.go
sessionctx/stmtctx/stmtctx.go
sessionctx/variable/session.go
sessionctx/variable/session_test.go
sessionctx/variable/sysvar.go

Reverts pingcap/tidb#36770
Issue Number: close None·
it fails to pass the unit test.
Tests 
```release-note
None
```

Revert "planner: refactor the IsolationReadEngines variable for plan cache"

---

Makefile
build/jenkins_unit_test.sh

Issue Number: close #36872
Tests 
Side effects
Documentation
```release-note
None
```

*: remove redundant steps

---

br/pkg/lightning/restore/get_pre_info.go
br/pkg/lightning/restore/get_pre_info_test.go

Issue Number: close #36905 
Tests 
- Write a simple program to check CheckTargetClusterSize for a test TiDB cluster and see whether the check can proceed on.
Side effects
Documentation
```release-note
None
```

lightning: fix nil config for new target info getter

---

Makefile
tools/check/check-file-perm.sh

Problem Summary: CI pipeline removed `.git` dir, thus `git` command won't work as expected.
Tests 
Side effects
Documentation
```release-note
None
```

*: do not rely on git to check file perm

---

executor/prepared.go
session/session.go
sessionctx/variable/session.go
sessionctx/variable/session_test.go

Issue Number: close #36598
Problem Summary: planner: introduce Session.CacheGeneralStmt for general plan cache
planner: introduce Session.CacheGeneralStmt for general plan cache
Tests 
Side effects
Documentation
```release-note
None
```

planner: introduce Session.CacheGeneralStmt for general plan cache

---

distsql/request_builder.go
distsql/request_builder_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/36983
revert #37019
Tests 
```release-note
None
```

distsql: revert 37019

---

distsql/request_builder.go
distsql/request_builder_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/36983
we first create #37048 due to we thought it caused analye test failed, however we found that the analye test failed due to #36509 ,thus we should revert #37048 and make #37019 back
revert #37048
Tests 
```release-note
None
```

distsql: revert 37048

---

parser/ast/ddl.go
parser/ast/ddl_test.go
parser/misc.go
parser/parser.y

Issue Number: close #36953
Tests 
```release-note
support TOKUDB_ZSTD compression method
```

parser: support TOKUDB_ZSTD

---

Makefile

Tests 
run in CI
```release-note
None
```

makefile: skip realtikvtest in the ut

---

tools/check/go.mod
tools/check/go.sum
tools/check/ut.go
tools/check/xprog.go

Tests 
```release-note
None
```

*: remove useless gomod

---

build/nogo_config.json
ddl/backfilling.go
ddl/column.go
ddl/index.go

Problem Summary: delete unnecessary params for create backfillWorker
Tests 
Side effects
Documentation
```release-note
None
```

ddl: refine param for backfillWorker

---

executor/seqtest/BUILD.bazel
util/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

util: set 50 shard_count

---

executor/show.go
executor/showtest/show_test.go
session/session.go

Issue Number: close #37045 close #35916
Tests 
```release-note
None
```

executor: enable TiDBEnableWindowFunction in SystemVar

---

executor/stale_txn_test.go

Tests 
```release-note
None
```

executor: close recordset

---

executor/trace_test.go
parser/parser.y

Signed-off-by: Jack Yu <jackysp@gmail.com>
Issue Number: close #37152
Support trace analyze.
Tests 
```
mysql> create table t (i int);
mysql> trace format='row' analyze table t;
+--------------------------------------------+-----------------+-------------+
| operation                                  | startTS         | duration    |
+--------------------------------------------+-----------------+-------------+
| trace                                      | 19:01:06.060895 | 16.500667ms |
|   └─session.ExecuteStmt                    | 19:01:06.060942 | 16.446167ms |
|     ├─executor.Compile                     | 19:01:06.060964 | 962.667µs   |
|     └─session.runStmt                      | 19:01:06.062067 | 15.291917ms |
| …
```

parser: support trace analyze table statement

---

tools/check/ut.go

Issue Number: close #37166
Tests 
```
make ut
```
```release-note
None
```

tools: skip tools/check when to use ut

---

.bazelrc
Makefile

Tests 
Side effects
Documentation
```release-note
None
```

bazel: enable color for all

---

executor/prepared.go
planner/core/plan_cache_test.go
planner/core/plan_cache_utils.go
server/conn.go
server/conn_stmt.go
session/session.go
testkit/testkit.go

Problem Summary: introduce the Parameterizer interface for general plan cache
Introduce the Parameterizer interface for general plan cache.
Tests 
Side effects
Documentation
```release-note
None
```

planner: introduce the Parameterizer interface for general plan cache

---

br/cmd/br/backup.go
br/pkg/aws/ebs.go
br/pkg/task/backup_ebs.go
br/pkg/task/common.go
br/pkg/task/restore_ebs_meta.go

Issue Number: close #37278
- add concurrency for aws operation
- delete snapshot if backup failed
- restore schedule ASAP
Tests 
Side effects
Documentation
```release-note
None
```

ebs br: add concurrency for aws operation & restore schedule ASAP

---

bindinfo/BUILD.bazel
types/json/BUILD.bazel

update bazel config
Tests 
Run in CI
```release-note
None
```

*: update bazel config

---

br/pkg/pdutil/pd.go
br/pkg/task/restore_data.go

Issue Number: close #37396
Tests 
Side effects
Documentation
```release-note
None
```

br: pause all schedule during ebs restore phase 2

---

ddl/db_partition_test.go
distsql/request_builder.go
executor/adapter.go
executor/builder.go
executor/distsql.go
executor/partition_table_test.go
executor/table_reader.go
kv/kv.go
planner/cascades/testdata/integration_suite_in.json
planner/cascades/testdata/integration_suite_out.json
planner/core/find_best_task.go
planner/core/partition_pruner_test.go
planner/core/physical_plans.go
planner/core/task.go
planner/core/testdata/partition_pruner_out.json
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
store/copr/coprocessor.go
testkit/result.go

close #34847
Issue Number: ref #36108 
testing ci
Tests 
Side effects
Documentation
```release-note
None
```

*: push part of order prop to partitiontable and make auto-analyze configurable

---

br/pkg/lightning/backend/local/localhelper_test.go
br/pkg/restore/client.go

Issue Number: 
close #37446
close #37445
Tests 
```release-note
None
```

br: fix data race

---

session/session_test.go

Issue Number: close #37463
Tests 
Side effects
Documentation
```release-note
None
```

session: fix data race in the TestInitMetaTable

---

go.mod

Issue Number: ref #36879
Tests 
```release-note
None
```

*: force to use go1.19

---

errors.toml
parser/terror/terror.go
privilege/privileges/errors.go
privilege/privileges/privileges.go
session/session.go

Issue Number: close #37493
Tests 
Side effects
Documentation
```release-note
None
```

*: fix a bug found by jdbc_test

---

ddl/ddl_api.go

Issue Number: ref #24698
```
[2022/09/01 21:14:54.597 +08:00] [INFO] [conn.go:1105] ["command dispatched failed"] [conn=2199023255957] [connInfo="id:2199023255957, addr:127.0.0.1:60382 status:10, collation:utf8mb4_0900_ai_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="drop table t"] [txn_mode=PESSIMISTIC] [timestamp=435693314269773824] [err="[schema:1051]Unknown table 'test.t'\ngithub.com/pingcap/errors.AddStack\n\t/Users/tangenta/gopath/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/Users/tangenta/gopath/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tidb/ddl.(*ddl).dropTable …
```

ddl: reduce the log for drop non-existent table

---

Makefile
br/cmd/br/restore.go
br/pkg/task/restore_data.go
go.sum

Tests 
Side effects
Documentation
```release-note
None
```

br: fix comments & compile

---

executor/distsql.go
executor/executor.go
executor/index_lookup_hash_join.go
executor/index_lookup_merge_join.go
executor/join.go
executor/shuffle.go
sessiontxn/BUILD.bazel
util/channel/channel.go

Tests 
Side effects
Documentation
```release-note
None
```

util: use channel.Clear to empty channel

---

ddl/ddl_api.go

Issue Number: close https://github.com/pingcap/tidb/issues/37669
Tests 
Side effects
Documentation
```release-note
None
```

ddl: expose BuildTableInfoWithStmt for DM

---

br/pkg/storage/s3.go
br/pkg/storage/storage.go

Issue Number: close #37710 
Tests 
Side effects
Documentation
```release-note
None
```

br: add retryer option for new storage

---

.bazelrc

Merkle tree calculations will be memoized to improve the remote cache hit checking speed
Tests 
Side effects
Documentation
```release-note
None
```

bazel: enable experimental_remote_merkle_tree_cache

---

tests/realtikvtest/brietest/BUILD.bazel

enable race test for brietest.
It only takes 2m 45s for it to complete task.
Tests 
Side effects
Documentation
```release-note
None
```

tests: add race for brietest

---

ddl/ddl_api.go

Issue Number: close #37686
The type number is exposed to users, which is hard to understand. 
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix exposion of magic number

---

br/pkg/task/backup_ebs.go

Tests 
Side effects
Documentation
```release-note
None
```

ebs-br: fix concurrent add region issue

---

br/pkg/aws/BUILD.bazel
br/pkg/aws/ebs.go

Tests 
Side effects
Documentation
```release-note
None
```

ebs-br: fix concurrency access issue

---

br/pkg/backup/client.go
br/pkg/task/backup_ebs.go

1. after stop scheduler , update min-resolved-ts2. 
2. log backup start ts, let  resolved-ts lag has visibility from log at least
Tests 
Side effects
Documentation
```release-note
None
```

br: update min-resolved-ts after stop scheduler

---

br/pkg/task/backup_ebs.go
br/pkg/task/backup_ebs_test.go

Tests 
Side effects
Documentation
```release-note
None
```

ebs-br: add ut for check region hole

---

tests/realtikvtest/pessimistictest/BUILD.bazel

enlarge test timeout for real tikv test
Timeout from 5min to 15min
Tests 
Side effects
Documentation
```release-note
None
```

tests: enlarge test timeout for real tikv test

---

ddl/db_change_test.go

Issue Number: close #37864 
The original test already has a comment to describe when and why it will timeout. If the first sql executes much faster than the second one, the session count will never reach 2 (but keep 0, which represents the first SQL has finished).
I use a channel to represent finished state and waitgroup to replace the original session count atomic variables. Though, I could simply add another atomic variable (`finished`) to solve the problem, I thought comparing with loop, a channel or waitgroup looks better :thinking: 
```release-note
None.
```
.

ddl,test: fix unstable test `TestParallelDDLBeforeRunDDLJob`

---

br/cmd/br/backup.go
br/cmd/br/restore.go
br/pkg/config/ebs.go
br/pkg/task/backup.go
br/pkg/task/backup_ebs.go
br/pkg/task/common.go
br/pkg/task/restore.go
br/pkg/task/restore_data.go
br/pkg/task/restore_ebs_meta.go
br/pkg/task/restore_test.go
br/tests/_utils/check_not_contains
br/tests/br_ebs/backupmeta
br/tests/br_ebs/run.sh

- unify `backup ebs` into `backup full`
- unify `restore ebs/data` into `restore full`
Tests 
Side effects
Documentation
```release-note
None
```

ebs-br: unify command into existing command

---

br/pkg/summary/collector.go
br/pkg/task/backup.go
br/pkg/task/restore.go

Tests 
Side effects
Documentation
```release-note
None
```

ebs-br: fix error check on parsing args and check in summary

---

planner/core/task.go

Issue Number: close #37913
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix for single DQA mode issue

---

ddl/concurrentddltest/switch_test.go

Tests 
```release-note
None
```

test: remove partition in `TestConcurrentDDLSwitch`

---

distsql/BUILD.bazel
tests/realtikvtest/sessiontest/BUILD.bazel

Tests 
run in CI
```release-note
None
```

*: enable race for sessiontest

---

ddl/ddl_api.go
ddl/foreign_key.go
ddl/foreign_key_test.go
ddl/schema.go

Issue Number: close #38005
Problem Summary: drop database should check foreign key constraint
Tests 
Side effects
Documentation
```release-note
None
```

*: drop database should check foreign key constraint

---

roadmap.md

Remove the dates from roadmap.
Tests 
Side effects
Documentation
```release-note
None
```

docs: remove dates from roadmap

---

ddl/foreign_key.go

Issue Number: close #38051
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix issue of foreign key check block ddl

---

roadmap.md

Tests 
Side effects
Documentation
```release-note
None
```

*: simplify roadmap description

---

Dockerfile

Tests 
```release-note
None
```

*: update docker builder

---

Makefile

Tests 
Side effects
Documentation
```release-note
None
```

makefile: add bazel linter

---

ddl/concurrentddltest/BUILD.bazel
testkit/mocksessionmanager.go

Issue Number: close #38063
Tests 
Side effects
Documentation
```release-note
None
```

*: fix race and enable race for concurrent ddl test

---

Dockerfile

Tests 
```release-note
None
```

*: update dockerfile

---

util/wait_group_wrapper.go
util/wait_group_wrapper_test.go

Issue Number: not needed.
Update license comment for `wait_group_wrapper.go` and `wait_group_wrapper_test.go`
Tests 
- Not needed
Side effects
- Not needed
Documentation
- Not needed
```release-note
None
```

util: a tiny update of license comment

---

br/pkg/storage/s3.go

Issue Number: ref https://github.com/pingcap/tidb/issues/38089
Add a disable s3 100 continue hotfix.
Tests 
Side effects
Documentation
```release-note
None
```

external storage: disable s3 100 continue

---

util/codec/codec.go

just a clean code 
Tests 
```release-note
None
```

*: use unsafe.slice

---

Makefile

Tests 
Side effects
Documentation
```release-note
None
```

makefile: add parser_yacc check when to linter

---

ddl/db_test.go
ddl/ddl_worker.go
ddl/foreign_key.go
ddl/foreign_key_test.go
errors.toml
planner/core/preprocess.go
util/dbterror/ddl_terror.go

Issue Number: close #38168
Problem Summary:  Add more check when add foreign key ddl job.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix issue when add foreign key ddl job

---

roadmap.md

Problem Summary: remove inappropriate description
Tests 
Side effects
Documentation
```release-note
None
```

docs: update roadmap description

---

ddl/job_table_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/38177
Tests 
```release-note
None
```

test: add information if test failed

---

executor/aggfuncs/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

executor: enable race for executor/aggfuncs

---

expression/collation.go

Issue Number: close #38282
Tests 
Side effects
Documentation
```release-note
None
```

expression: fix data race in the collationInfo

---

go.mod
go.sum

Signed-off-by: Jack Yu <jackysp@gmail.com>
Issue Number: close #36861
Tests 
Side effects
Documentation
```release-note
None
```

*: disable PermitWithoutStream to avoid too many pings

---

domain/domain.go

Issue Number: close #38329
Tests 
Side effects
Documentation
```release-note
None
```

domain: fix data race in the Domain.bindHandle

---

util/gctuner/BUILD.bazel
util/gctuner/memory_limit_tuner.go
util/gctuner/memory_limit_tuner_test.go

Tests 
Side effects
Documentation
```release-note
None
```

util: fix data race for memory limit tuner test

---

.bazelrc
Makefile.common

Tests 
Side effects
Documentation
```release-note
None
```

bazel: only enable zgc on CI

---

parser/ast/dml.go

Tests 
Side effects
Documentation
```release-note
None
```

*: fix restore error typo

---

util/gctuner/memory_limit_tuner.go

it needs to remove this limit.
Tests 
Side effects
Documentation
```release-note
None
```

gctuner: remove limit  for global memory limit

---

planner/core/plan_cost_ver2.go

Problem Summary: planner: update the cost model ver2
1. use the correct concurrency in HashJoin and UnionAll;
2. use the correct task-type in TableReader;
3. update the hash-build and hash-probe cost formulas;
Tests 
Side effects
Documentation
```release-note
None
```

planner: update the cost model ver2

---

ddl/ddl_tiflash_api.go

Signed-off-by: hehechen <chentongli@pingcap.com>
Issue Number: close #38676
`progress` updating is too slow for tables that are already available.
Tests 
Create 50k tables with TiFlash replica, check the updates of `progress`.
Side effects
Documentation
```release-note
None
```

DDL: fix update progress of available table

---

planner/core/plan_cost_ver2.go

Problem Summary: planner: update some cost formulas of model ver2
1. update the cost formula of Sort/TopN from `rows*log(rows)*cols*cpu_factor` to `rows*cols*cpu_factor + rows*log(rows)*cpu_factor`;
2. consider `BCastJoin` and `ShuffleJoin` in `Exchange` and `HashJoin`; 
Tests 
Side effects
Documentation
```release-note
None
```

planner: update some cost formulas of model ver2

---

session/session.go
statistics/feedback.go

Issue Number: close #34155
Problem Summary: planner: disable query-feedback thoroughly
planner: disable query-feedback thoroughly
Tests 
Side effects
Documentation
```release-note
None
```

planner: disable query-feedback thoroughly

---

.bazelrc
build/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

nogo: enable filepermission during building and lint

---

executor/fktest/foreign_key_test.go
executor/foreign_key.go

Issue Number: close #38831
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix issue of insert ignore with foreign key check

---

planner/core/integration_test.go
planner/core/plan_cost_ver2.go
planner/core/plan_cost_ver2_test.go
planner/core/testdata/integration_suite_out.json

Problem Summary: planner: udpate cost model ver2 and some related UT
Tests 
Side effects
Documentation
```release-note
None
```

planner: udpate cost model ver2 and some related UT

---

metrics/grafana/performance_overview.json

Issue Number: close #38871
It would be more accurate to calculate the active connections and DB time with the following promeQL: sum(tidb_server_tokens{k8s_cluster="$k8s_cluster",tidb_cluster="$tidb_cluster"})
- change the PromeQL of active connection and DB time to: sum(tidb_server_tokens{k8s_cluster="$k8s_cluster",tidb_cluster="$tidb_cluster"})
- add metric: miss plan cache
- add PD server handle time
Tests 
Side effects
Documentation
```release-note
None
```

metrics: update active connection promeQL and add metric: miss plan cache

---

server/conn.go

Problem Summary: `checkAuthPlugin` may return nil pass if it does not need to switch auth. Hard to do unit testing, since we need to mock the full packet IO...
Tests 
Same as #38830
Side effects
Documentation
```release-note
None
```

*: fix check auth support

---

util/memoryusagealarm/memoryusagealarm.go

Issue Number: close https://github.com/pingcap/tidb/issues/38902
Tests 
Side effects
Documentation
```release-note
None
```

util: fix the compatibility problem for oom-alarm

---

telemetry/BUILD.bazel
telemetry/data_feature_usage.go
telemetry/data_feature_usage_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/38907
Tests 
Side effects
Documentation
```release-note
None
```

telemetry: add telemetry for global memory control

---

ddl/concurrentddltest/switch_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/37891
Tests 
```release-note
None
```

test: fix unstable test

---

telemetry/data_feature_usage.go
telemetry/data_feature_usage_test.go

Add telemetry for https://github.com/pingcap/tidb/issues/38442
Tests 
Side effects
Documentation
```release-note
None
```

telemetry: add telemetry for the new autoid implementation

---

br/pkg/restore/BUILD.bazel
br/pkg/restore/client.go
br/pkg/restore/log_client_test.go
br/pkg/restore/stream_metas.go
br/pkg/restore/stream_metas_test.go
br/pkg/storage/gcs.go
br/pkg/task/stream.go

Issue Number: ref #38229 #38939
Fix the bug that failed to truncate the log data on gcs or azure blob
Fix the bug that delete the files that should not be deleted
Tests 
Side effects
Documentation
```release-note
None.
```

hotfix: cherry pick pull 38232 38870 to release-6.3-20221108-v6.3.0

---

tests/realtikvtest/statisticstest/main_test.go

Issue Number: close #39004
add ```google.golang.org/grpc.(*ccBalancerWrapper).watcher``` into goleak's config.
Tests 
Side effects
Documentation
```release-note
None
```

statisticstest: fix goleak on the statisticstest

---

domain/domain.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
statistics/handle/update.go

Tests 
Side effects
Documentation
```release-note
None
```

*: add system variable tidb_check_auto_analyze_status

---

DEPS.bzl
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/39062
Tests 
```release-note
None
```

*: upgrade pingcap/log

---

infoschema/tables.go
infoschema/tables_test.go

Issue Number: close #39059 
Tests 
Side effects
Documentation
```release-note
None
```

infoschema: fix FormatTiDBVersion panic

---

statistics/handle/update.go
statistics/handle/update_test.go

Tests 
Side effects
Documentation
```release-note
None
```

statistics: remove 1min no write check for unanalyzed table in auto analyze

---

executor/executor_test.go
executor/plan_replayer.go

Tests 
```release-note
None
```

executor: cherry-pick 45588a1

---

executor/slow_query.go
infoschema/cluster_tables_test.go

cherry-pick #33975 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
git pr https://github.com/pingcap/tidb/pull/34000
```
Issue Number: close #33974
Tests 
```release-note
None
```

executor: fix issue of query instance from CLUSTER_SLOW_QUERY return '' result (#33975) 

---

ddl/backfilling.go
ddl/index.go
ddl/index_merge_tmp_test.go
ddl/ingest/engine_mgr.go
ddl/ingest/mem_root.go
ddl/ingest/message.go
ddl/reorg.go
table/tables/index.go
tests/realtikvtest/addindextest/integration_test.go

Issue Number: cherry-pick #39239 and #39190 to release 6.4.0-hotfix
Tests 
Side effects
Documentation
```release-note
None
```

ddl: add index using ingest 640 hotfix

---

ddl/db_partition_test.go
distsql/request_builder.go
executor/adapter.go
executor/builder.go
executor/distsql.go
executor/partition_table_test.go
executor/table_reader.go
kv/kv.go
planner/cascades/testdata/integration_suite_in.json
planner/cascades/testdata/integration_suite_out.json
planner/core/find_best_task.go
planner/core/integration_partition_test.go
planner/core/partition_pruner_test.go
planner/core/physical_plans.go
planner/core/task.go
planner/core/testdata/partition_pruner_out.json
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
store/copr/coprocessor.go
testkit/result.go

Issue Number: close #38902
Tests 
Side effects
Documentation
```release-note
None
```

*: push order to partition table and configure concurrency for auto analyze

---

dumpling/export/status_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/39255
increased error tolerance
Tests 
Side effects
Documentation
```release-note
None
```

dumpling: fix TestSpeedRecorder flaky test

---

bindinfo/handle.go

Tests 
Side effects
Documentation
```release-note
None
```

bindinfo: fix the timer leak bug.

---

br/pkg/restore/client_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/39412
Fit unit test.
Tests 
Side effects
Documentation
```release-note
None
```

br: fix unit test - TestApplyKVFilesWithBatchMethod3

---

br/pkg/lightning/backend/local/BUILD.bazel
br/pkg/utils/BUILD.bazel
ddl/concurrentddltest/BUILD.bazel
executor/fktest/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

bazel: update shard_count

---

server/http_status.go

Issue Number: close https://github.com/pingcap/tidb/issues/39214
A silly mistake in the previous fix.... the port is missing!
Tests 
Side effects
Documentation
```release-note
None
```

server: fix port of autoid_service

---

br/tests/br_foreign_key/run.sh

cherry-pick https://github.com/pingcap/tidb/pull/39607
Tests 
Side effects
Documentation
```release-note
None
```

br: fix br foreign key test (#39607)

---

store/tikv/client/client.go
store/tikv/client/client_test.go

Issue Number: ref #33773
Cherry-pick fix https://github.com/tikv/client-go/issues/464 to release-5.1
Tests 
Side effects
Documentation
```release-note
Fix the data race issue of the connection array.
```

kvclient: fix the connection array race

---

executor/builder.go

Issue Number: close #39724
Problem Summary: planner: check error when building INLJ executor
planner: check error when building INLJ executor
Tests 
Side effects
Documentation
```release-note
None
```

planner: check error when building INLJ executor

---

domain/historical_stats.go
domain/plan_replayer.go
domain/plan_replayer_dump.go
metrics/grafana/tidb.json
metrics/metrics.go
metrics/stats.go
statistics/handle/dump.go

add metrics for plan replayer and historical stats
Tests 
```release-note
None
```

metrics: add metrics for plan replayer and historical stats

---

ddl/cluster_test.go

Issue Number: close #40287 
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix flaky test TestGlobalVariablesOnFlashback

---

br/pkg/gluetidb/glue.go

Issue Number: close #40281
Tests 
Pass the test as described in the issue
Side effects
Documentation
```release-note
None
```

br: fix bootstrap domain

---

Makefile

Issue Number: close #40293
Tests 
Side effects
Documentation
```release-note
None
```

makefile: enable deadlock in the with-real-tikv

---

statistics/selectivity.go
statistics/table.go
statistics/testdata/integration_suite_out.json

cherry-pick #40338 to [release-6.5-20230104-v6.5.0](https://github.com/pingcap/tidb/tree/release-6.5-20230104-v6.5.0)
Tests 
Side effects
Documentation
```release-note
None
```

statistics: use histogram buckets bounds to enhance string match functions estimation

---

expression/expr_to_pb_test.go
expression/expression.go
planner/core/integration_test.go

Issue Number: close #40396
Tests 
Side effects
Documentation
```release-note
None
```

expression: cherry-pick `regexp_replace` function pushdown

---

session/nontransactional.go

Signed-off-by: you06 <you1474600@gmail.com>
Non-transactional may generate sharding query like:
```
SELECT `_tidb_rowid` FROM `xx`.`yy` WHERE TRUE ORDER BY IF(ISNULL(`_tidb_rowid`),0,1),`_tidb_rowid`
```
In case `_tidb_rowid` is not indexed, the query will be executed by a sort executor, which consumes large memory.
This PR avoids using the sort executor for such case and sorts the `_tidb_rowid` by quick sort, in my test, 1,000,000,000 rand int64 numbers(worst case) take 5m56s to sort with 8G memory usage, this definitely outperforms the sort executor.
Tests 
Side effects
Documentation …

nt-txn: reduce memory usage by avoiding sort executor |tidb-test=release-6.5

---

expression/expression.go

Tests 
Side effects
Documentation
```release-note
None
```

expression: least string | tidb-test=pr/2061

---

executor/insert.go
executor/insert_common.go
executor/replace.go
sessionctx/variable/tidb_vars.go

Signed-off-by: gengliqi <gengliqiii@gmail.com>
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix insert into select bugs | tidb-test=release-6.5

---

server/conn.go
sessionctx/variable/BUILD.bazel
sessionctx/variable/session.go

Tests 
Side effects
Documentation
```release-note
None
```

*: change result query | tidb-test=release-6.5 

---

executor/insert_common.go
table/table.go
table/tables/tables.go
util/chunk/row.go

Signed-off-by: gengliqi <gengliqiii@gmail.com>
Tests 
Side effects
Documentation
```release-note
None
```

executor: reduce make slice for insert select statement

---

planner/core/optimizer.go
planner/core/plan_cache.go

Problem Summary: planner: refactor to put all plan-cacheability-check functions together
No logical change, just refactor that put all plan-cacheability-check functions together.
Tests 
Side effects
Documentation
```release-note
None
```

planner: refactor to put all plan-cacheability-check functions together

---

tests/realtikvtest/flashbacktest/BUILD.bazel

enable race and flaky for flashback test
Tests 
Side effects
Documentation
```release-note
None
```

tests: enable race and flaky for flashback test

---

store/gcworker/gc_worker.go

cherry-pick https://github.com/pingcap/tidb/pull/40760
Issue Number: ref pingcap/tidb#40759
Tests 
Side effects
Documentation
```release-note
None
```

log-backup: do not resolve locks frequently when log-backup task did not exist (#40760)
