pingcap/tidb

- executor/analyze_test.go
- statistics/table.go
Issue Number: close #35056 
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix panic when mergeGlobalStats for newly-added index or column

- statistics/handle/update.go
Issue Number: ref https://github.com/pingcap/tidb/issues/35094
fmsketch in not used in `dumpStatsUpdateToKV`, thus we can remove this param.
Tests 
```release-note
None
```
> statistics: remove unused fmsketch param

- executor/executor_txn_test.go
- executor/simple.go
- sessionctx/variable/session.go
Issue Number: close #35063
Tests 
```release-note
None
```
> executor: fix compatibility issue of release savepoint

- go.mod
- go.sum
- statistics/cmsketch.go
Issue Number: ref #34250
remove the ```sortutil``` by using the ```exp/slices``` library.
Tests 
```release-note
None
```
> *: remove sortutil

- server/server.go
- session/session.go
Try do skip the transaction start_ts used by analyze calculating the GC safepoint, so the GC process would not be blocked.
Tests 
- Slow donw the `analyzeExec`
- Print the calculated safepoint
- Check if the safepoint is moving forward as expected.
Side effects
Documentation
```release-note
None
```
> txn: skip the transaction start_ts used by analyze calculating the gc safepoint

- ddl/column_type_change_test.go
- ddl/db_cache_test.go
- ddl/db_integration_test.go
- ddl/db_partition_test.go
- ddl/db_table_test.go
- ddl/ddl_error_test.go
- ddl/ddl_worker_test.go
- ddl/failtest/fail_db_test.go
- ddl/placement_policy_test.go
- ddl/placement_sql_test.go
- ddl/sequence_test.go
- privilege/privileges/BUILD.bazel
- testkit/testkit.go
In history, We have met many [problems](https://github.com/pingcap/tidb/pull/34837/files) caused by forgetting to close RecordSet. so we refactor the test case by closing the record set to make the test stable.
Tests 
```release-note
None
```
> *: close RecordSet

- executor/grant.go
- executor/grant_test.go
Issue Number: close #35310
When `sql_mode` doesn't contain `NO_AUTO_CREATE_USER` and the grant statement doesn't contain a password, TiDB will panic because of a previous PR that supports auth-plugin.
Check nil.
Tests 
```release-note
None
```
> executor: fix panic when granting privilege to a non-exists user

- ddl/ddl.go
- ddl/ddl_api.go
- ddl/multi_schema_change.go
- docs/design/2022-03-10-backup-with-batch-create-table.md
- parser/model/ddl.go
- sessionctx/stmtctx/stmtctx.go
Issue Number: ref https://github.com/pingcap/tidb/issues/14766
- Refactor `callHookOnChanged` so that the hook is not called every time.
- Add unique check for changing schema object, including add/drop/alter/modify columns and indexes.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: add front-end checks for multi-schema change

- planner/core/plan_cost.go
Problem Summary: introduce new cost formula for IndexLookup
Introduce new cost formula for IndexLookup: accumulate the real double-read cost:
1. `doubleReadCost = numDoubleReadTasks * SeekFactor`;
2. `numDoubleReadTasks` is based on a magic number `distRatio=40`, `doubleReadRows / IndexBatchSize * distRatio`.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce new cost formula for IndexLookup

- ddl/table.go
Issue Number: close #35406
Tests 
Since it is not possible to have both `shard_row_id_bits` and clustered pk in master, I remove the check:
```diff
--- a/ddl/ddl_api.go
+++ b/ddl/ddl_api.go
@@ -2833,9 +2833,9 @@ func handleTableOptions(options []*ast.TableOption, tbInfo *model.TableInfo) err
case ast.TableOptionCompression:
tbInfo.Compression = op.StrValue
case ast.TableOptionShardRowID:
-                       if op.UintValue > 0 && tbInfo.HasClusteredIndex() {
-                               return dbterror.ErrUnsupportedShardRowIDBits
-                       }
+                       //if op.UintValue > 0 && tbInfo.HasClusteredIndex() {
+                       //      return dbterror.ErrUnsupportedShardRowIDBits
+                       //}
tbInfo.ShardRowIDBits = …
```
> ddl: skip shard_row_id_bits check if it is zero

- cmd/explaintest/r/explain_cte.result
- cmd/explaintest/t/explain_cte.test
- expression/column.go
- planner/core/logical_plan_builder.go
cherry-pick https://github.com/pingcap/tidb/pull/35415 to release-6.1-20220619
Thank you for contributing to TiDB!
PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed
-->
Issue Number: close #35404
After #33158, the predicate pushdown for CTE has been supported. While some cases will have some problems when it comes to projection elimination using column's hashcode mapping.
In building dataSource,  we clone CTE schema with some newly assigned uniqueID when referring to a CTE. In PR #33158, code as following
```
for i, col := range lp.schema.Columns {
lp.cte.ColumnMap[string(col.HashCode(nil))] = prevSchema.Columns[i]
}
```
here will generate hashcode in columns of the schema of CTE when building CTE itself.
Later when building the main select …
> planner: fix cte-schema-clone will clone the old hashcode of its column if any (#35415)

- ddl/ddl_api.go
- parser/model/model.go
Issue Number: close #35511
Set the visibility of function getPrimaryKey() public 
Tests 
```release-note
None
```
> ddl: expose getPrimaryKey() as a public method of model.TableInfo

- br/pkg/restore/client.go
- br/pkg/task/restore.go
- br/pkg/task/stream.go
Issue Number: close https://github.com/pingcap/tidb/issues/35410
about br restore point
- on stage of full-restore, the concurrency number should be 128(default).
- on stage of log-restore, the concurrency number should be 16(default).
Tests 
Side effects
Documentation
```release-note
None
```
> log-backup: adjust restore concurrency

- br/pkg/restore/split.go
Issue Number: close https://github.com/pingcap/tidb/issues/35657
Increase the retry backoff when scan regions. 
Old backoff is 500ms * 30 times, the new is 1s * 60 times.
Tests 
Side effects
Documentation
```release-note
None
```
> br: increase the retry backoff when scan regions

- store/copr/coprocessor.go
Issue Number: close #35673
~~If the storage engine doesn't support paging, they may send the whole region data.
Then we can still use the old way to handle the response.~~
~~TiFlash doesn't support coprocessor paging, disable it on tiflash.
Most of the query should go to `sendBatchCop()` code path.~~
Tests 
Side effects
Documentation
```release-note
None
```
> store/copr: fix tiflash integration test by disable paging on tiflash

- br/pkg/restore/import_retry.go
- br/pkg/restore/import_retry_test.go
this PR is cherry-picked from https://github.com/pingcap/tidb/pull/35716
Issue Number: close #35657
Currently, we use a context with 10s timeout for scanning regions. This is not enough for PiTR restore condition.
Removed the deadline, at the same time, we fixed a problem that may cause the start key and end key added to the logger multi times.
Tests 
Side effects
Documentation
```release-note
None
```
> br: remove the timeout for scan region

- expression/expression.go
- expression/expression_test.go
- planner/core/integration_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/25813
`evaluateExprWithNull` will pass the expression's RetType to `NewFunctionInternal`, which may change it unexpectedly.
pass its clone instead of itself.
Tests 
```release-note
Fixed a bug that may cause comparisons between json and string report.
```
> expression: use cloned RetType at `evaluateExprWithNull` when it may be changed.

- store/helper/helper.go
Issue Number: close https://github.com/pingcap/tidb/issues/35708.
`requestPD` should try the PD hosts one by one until the request is successful.
Tests 
Side effects
Documentation
```release-note
Fix an issue that TiDB cannot access `TIKV_REGION_STATUS` when one of the PD is down.
```
> helper: request another PD if one of them is unavailable

- br/pkg/glue/console_glue.go
- br/pkg/task/stream.go
Signed-off-by: Yu Juncen <yujuncen@pingcap.com>
Issue Number: close #(TBD)
Log truncate is too slow and there isn't time cost information.
This PR added time cost for `log truncate`, and using a 128 threads concurrency for deleting the files in S3. (Will this be too frequently?)
Tests 
```release-note
Now, `br log truncate` command would display the time cost of each steps.
```
> log_backup: make deleting file concurrently, show the time cost of truncating

- ddl/ddl.go
- ddl/ddl_api.go
- executor/ddl.go
Issue Number: ref #35665 
move some logic from DDL executor into DDL interface.
I'll open more PR for other DDL method. The goal is that DDL interface should accept ast.XXXStmt as parameters and handle all logic by the information of the statement, so the definition of DDL interface will have a more clear boundary.
Tests 
- pass exising tests
Side effects
Documentation
```release-note
None
```
> ddl: DROP TABLE/VIEW/SEQUENCE now use XXXStmt as parameter

- tools/check/ut.go
Issue Number: close #35799
Although `make ut` is not the default CI unit test script, I'd still love to use it locally.
And the shallow merge CI pipeline still run it.
Skip the 'tests' directory... they are integration test and can't run with 'go test ...'
Tests 
`make ut` to see the tests pass after this change.
Side effects
Documentation
```release-note
None
```
> tools/check: skip 'tests' directory in 'make ut'

- store/copr/coprocessor.go
- tests/realtikvtest/sessiontest/session_test.go
Issue Number: close #35829
When `@@tidb_enable_collect_execution_info` is off,  the `resp.detail` is nil
And when cop cache code use it in `resp.detail.TimeDetail.ProcessTime`, tidb get a nil point panic.
Tests 
Run the test case with real tikv
Side effects
Documentation
```release-note
Fix a nil point panic when @@tidb_enable_collect_execution_info is off and cop cache feature is on. This combination is not the default setting, so most of the time a user would not meet it.
```
> executor: fix a nil point when @@tidb_enable_collect_execution_info is off and cop cache is on

- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/delete_range.go
- ddl/multi_schema_change.go
- ddl/sanity_check.go
- parser/model/ddl.go
Issue Number: ref https://github.com/pingcap/tidb/issues/14766
- Makes `ToProxyJob` return a value instead of a pointer.
- Clone the job in the failpoint `mockParallelSameDDLJobTwice` to prevent sharing the same instance(which will fail in concurrent DDL implementation).
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: make ToProxyJob return value to avoid heap allocation

- ddl/ddl_api_test.go
- ddl/ddl_test.go
- ddl/reorg_test.go
- ddl/schema_test.go
- meta/meta.go
Tests 
```release-note
None
```
> ddl: move ddl test

- br/pkg/errors/errors.go
- br/pkg/restore/db.go
- br/pkg/restore/db_test.go
- br/pkg/task/stream.go
- br/pkg/utils/schema.go
- errors.toml
Issue Number: close #35294
When execute br restore point repeatedly, it may cause unexpected error because of use's data existed in restored cluster.
Add validation when execute pitr, to make sure that restored cluster is an empty cluster. But when users only execute log restore, we won't add that limitation.
Tests 
1. Create database `d1` in restored cluster, and create table `user` in database `test`. Then execute pitr.
2. Drop database `d1` in restored cluster, then execute pitr.
3. Drop database `test` and recreate database `test` to make the cluster recover to original state. Then execute pitr.
Side effects
Documentation …
> br: add requirements checking when execute pitr

- Makefile
- dumpling/cmd/dumpling/main.go
- dumpling/export/consistency.go
- dumpling/export/dump.go
- dumpling/export/sql.go
- dumpling/export/writer.go
- tidb-binlog/driver/reader/offset.go
- tidb-binlog/driver/reader/reader.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: improve bazel build

- executor/infoschema_reader.go
- infoschema/perfschema/const.go
- infoschema/perfschema/tables.go
- infoschema/perfschema/tables_test.go
- infoschema/tables.go
Issue Number: close #35894
Problem Summary: add `session_variables` table to `performance_schema`. Keep it same as `information_schema.session_variables`
Tests 
Side effects
Documentation
```release-note
For compatible with MySQL 5.7.22+ and MySQL 8.x, add `session_variables` table to `performance_schema`
```
> perfschema: add `session_variables` table to `performance_schema`

- parser/auth/caching_sha2.go
- parser/auth/caching_sha2_test.go
Issue Number: close #35998 
the `Sum` method in `Hash` interface will copy the hash object 
https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/crypto/sha256/sha256.go;l=207
it will make lots of hash object in the iteration loop  `for i = 0; i < iterations; i++`
```
goos: darwin
goarch: amd64
pkg: github.com/pingcap/tidb/parser/auth
cpu: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
BenchmarkShaPassword
BenchmarkShaPassword-8   	     699	   1697389 ns/op	    9738 B/op	       6 allocs/op
BenchmarkShaPassword-8   	     382	   3101911 ns/op	  320674 B/op	   10022 allocs/op
```
Tests 
Side effects
Documentation …
> parser/auth: Optimize caching sha2 speed

- .github/workflows/license-checker.yml
fix check license error on github action. use v0.3.0 instead of main
Issue Number: close https://github.com/pingcap/tidb/issues/36039
Problem Summary: fix check license error on github action.
Tests 
- [-] No code
Side effects
Documentation
```release-note
None
```
> ci: fix check-license github action

- distsql/distsql.go
- distsql/distsql_test.go
- distsql/select_result.go
- util/execdetails/execdetails.go
- util/execdetails/execdetails_test.go
Issue Number: ref #35889
Add two new information into runtime stats:
1. the distsql scan concurrency
2. the avg time for cop tasks
This new information is needed to support the visual plan feature.
And some code is also refactored to be cleaner.
Tests 
Side effects
Documentation
```release-note
None
```
> distsql, execdetails: add information into runtime stats

- ddl/ddl_api.go
- ddl/multi_schema_change_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/14766
This PR supports adding primary key or indexes along with columns:
```sql
alter table t add column (b int default 2, index i(a), primary key (a));
```
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: support adding constraint with column in one spec

- planner/core/exhaust_physical_plans.go
- planner/core/testdata/window_push_down_suite_in.json
- planner/core/testdata/window_push_down_suite_out.json
Issue Number: close https://github.com/pingcap/tidb/issues/35990
miss exchange between hash-partition window and single-partition window
check the single-partition property when build mpp windows.
Tests 
```release-note
None
```
> planner: add missing exchange between hash-partition window and single-partition window

- planner/core/common_plans.go
- planner/core/encode.go
- planner/core/flat_plan.go
- planner/core/flat_plan_test.go
- planner/core/main_test.go
- planner/core/physical_plans.go
- planner/core/testdata/flat_plan_suite_in.json
- planner/core/testdata/flat_plan_suite_out.json
Issue Number: ref https://github.com/pingcap/tidb/issues/35888 ref https://github.com/pingcap/tidb/issues/35889
- Introduce the flat plan.
- Use the flat plan to implement `EXPLAIN` logic.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce flat plan

- br/pkg/storage/s3.go
Issue Number: close #36055
backup to s3 backend without region param failed.
bind the region param get from s3 to backend object.
Tests 
1. execute br before fix this bug
2. execute br after fixed this bug
Side effects
Documentation
```release-note
None
```
> br: modify to send s3 region param to tikv

- executor/set_test.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
pick https://github.com/pingcap/tidb/pull/35241
```release-note
None
```
> planner: introduce some new variables for the cost model version2

- dumpling/export/config.go
Issue Number: close #36112
Tests 
- `bin/dumpling -h ::1 -p123456 -P3306 -B test -o dump-test`
Side effects
Documentation
```release-note
use net.JoinHostPort to generate host-port part of URI
```
> db(dumpling): use net.JoinHostPort to generate host-port part of URI

- planner/core/plan_cost.go
pick https://github.com/pingcap/tidb/pull/35718
```release-note
None
```
> planner: fix the wrong cost formula of MPPExchanger on cost model ver2

- br/pkg/restore/client.go
- br/pkg/restore/client_test.go
- br/pkg/stream/rewrite_meta_rawkv.go
- br/pkg/stream/rewrite_meta_rawkv_test.go
- br/pkg/task/stream.go
Issue Number: close https://github.com/pingcap/tidb/issues/35372
Problem Summary: drop table meta only, not delete record and index belonged to table.
deal with the mddl job, and insert rows into table mysql.gc_delete_range.
Tests 
Side effects
Documentation
```release-note
None
```
> br: deal with mddljob when pitr restores (#35976)

- br/pkg/restore/client.go
- br/pkg/restore/stream_metas.go
- br/pkg/restore/stream_metas_test.go
- br/pkg/stream/stream_mgr.go
- br/pkg/task/stream.go
Issue Number: close https://github.com/pingcap/tidb/issues/36138
- Calculate the min-begin-ts(shift-ts) according to the start-ts in kv-pair at write-cf
- get the kv-count and total-size when restore log
Tests 
- backup
- create a log backup task with command `br log start`
- begin transaction and insert 5 records
- wait 30 minutes
- create a full backup(ts=434516875680940033)
- insert 5 record at the uncommitted transaction
- commit the transaction 
- restore
- PiTR from snapshot-ts to target restore-ts with the comand `br restore point`
- the result
- restore successfully and the down-stream cluster has 10 record
- the log like blow, it has calculate the `shift-start-ts`
[2022/07/11 23:13:45.818 +08:00] [INFO] [client.go:301] ["set restore range ts"] …
> log-backup: support calculating dynamic shift-start-ts when restoring kv-files belonging to default-cf

- br/pkg/stream/stream_status.go
Issue Number: fixed #36092
Before, if there isn't any checkpoint in the global scope, `br log status` would display no checkpoints.
This PR would make us display checkpoint no matter there are some checkpoints.
Tests 
```release-note
Fixed a bug that caused `br log status` returns no checkpoint.
```
> log-backup: fix checkpoint display

- ddl/ddl_test.go
- ddl/restart_test.go
rewrite the `restart_test`, use `ddl.stop` and `ddl.start` to restart ddl
Tests 
```release-note
None
```
> test: refactor restart test

- .bazelrc
- distsql/BUILD.bazel
- domain/db_test.go
- domain/infosync/BUILD.bazel
- domain/main_test.go
Issue Number: close #36153
Tests 
Side effects
Documentation
```release-note
None
```
> domain: fix unstable test TestAbnormalSessionPool

- planner/core/find_best_task.go
- planner/core/integration_test.go
- planner/core/testdata/integration_suite_out.json
Issue Number: close #36194
We didn't handle the expected row count for pushed-down selection in mpp task.
Handle the row count for pushed-down selection for mpp task the same as other tasks:
https://github.com/pingcap/tidb/blob/bc1b152f0f958d02ceacc981a99457d678b3f667/planner/core/find_best_task.go#L1945
Tests 
Side effects
Documentation
```release-note
None
```
> planner: handle the expected row count for pushed-down selection in mpp

- br/pkg/task/stream.go
- br/pkg/task/stream_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/29501
- If V3 global-checkpoint advance, the maximum value in storeMap.resolvedTSMap as global-checkpoint-ts.
- If v2 global-checkpoint advance, it need the minimal value in storeMap.resolvedTSMap as global-checkpoint-ts.Because each of store maintains own checkpoint-ts only.
Tests 
Side effects
Documentation
```release-note
None
```
> log-backup: get can restored global-checkpoint-ts when support v3 checkpoint advance

- sessionctx/sessionstates/BUILD.bazel
- sessionctx/sessionstates/session_token_test.go
Issue Number: close #36203
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: fix data race in the TestLoadAndReadConcurrently

- sessiontxn/isolation/readcommitted_test.go
Issue Number: close #36212
Even `session.ResultSetToStringSlice(ctx, tk.Session(), rs)` return error, the `rs` should be closed.
Otherwise the will be resource (goroutine) leak.
Tests 
go test -v -run TestPessimisticRCTxnContextProviderRCCheckForPrepareExecute
```
--- PASS: TestPessimisticRCTxnContextProviderRCCheckForPrepareExecute (0.11s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 321 in state select, with github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh on top of the stack:
goroutine 321 [select]:
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh(0xc00561dc70?, 0x43dfd78?, 0xc0053a0180?, 0x14?)
/home/genius/project/src/github.com/pingcap/tidb/store/copr/coprocessor.go:542 +0xad …
```
> sessiontxn/isolation: fix goleak for TestPessimisticRCTxnContextProviderRCCheckForPrepareExecute

- planner/core/physical_plans.go
- planner/core/plan_cost.go
- planner/core/plan_cost_test.go
- planner/core/task.go
Issue Number: close #36243
Problem Summary: costs of Selection operators from DataSources are not accumulated
costs of Selection operators from DataSources are not accumulated
Tests 
Side effects
Documentation
```release-note
None
```
> planner: costs of Selection operators from DataSources are not accumulated

- br/tests/br_tikv_outage/run.sh
- br/tests/br_tikv_outage2/run.sh
After https://github.com/pingcap/tidb/pull/36114/files merged. The failpoint path has changed from `br/pkg/conn/` to `br/pkg/utils/`. so we have to change it.
Use the correct failpoint inject path.
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix broken integration test

- .bazelrc
we have timeout control for every single test file, no need this anymore
Tests 
```release-note
None
```
> bazel: remove timeout

- ddl/column.go
- ddl/multi_schema_change_test.go
- parser/model/model.go
Issue Number: ref https://github.com/pingcap/tidb/issues/14766
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: handle rolling back modify columns correctly

- planner/core/exhaust_physical_plans.go
- planner/core/integration_test.go
- planner/core/testdata/enforce_mpp_suite_out.json
- planner/core/testdata/integration_suite_in.json
- planner/core/testdata/integration_suite_out.json
This is a refined version of PR #34193. Credit to @fzhedu.
Issue Number: close #34192
Before this patch, the planner only push down Selection to TiFlash when it is required by its parent operator. If the Selection is the top operator of the plan tree, the planner will failed to push down the Selection even if it is able to. This patch improves the plan by pushing down Selection whenever possible.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: push down top selection to TiFlash

- executor/show.go
Issue Number: close #36348 
Problem Summary: fix error that check whether partitionInfo.Columns is `nil` while it is `[]`.
change the condition
Tests 
Side effects
Documentation
```release-note
None
```
> log-backup: fix error that check whether partitionInfo.Columns is `nil` while it is `[]`

- executor/builder.go
- executor/compact_table_test.go
- parser/ast/misc.go
- parser/ast/misc_test.go
- parser/parser.y
Signed-off-by: Wish <breezewish@outlook.com>
Issue Number: ref #34749
This is an extension to the current syntax:
```sql
alter table T compact tiflash replica; 
```
that we additionally allow compaction without explicitly specifying the replica kind:
```sql
alter table T compact;
```
Tests 
Side effects
Documentation
```release-note
None
```
> compact: Add syntax for COMPACT command without specifying the replica

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #36395
The error generated by `GetExecDetailsV2` is never used. So, we just choose not to generate the error to avoid the cost.
See https://github.com/tikv/client-go/pull/553
Tests 
```release-note
None
```
> *: update client-go to avoid useless error format

- dumpling/export/consistency.go
Issue Number: ref https://github.com/pingcap/tidb/issues/36547
In DM's integration tests, after fallback to LOCK TABLES, the error message becomes
```
"Message": "mydumper/dumpling runs with error, with output (may empty): ",
"RawCause": "Error 1044: Access denied for user 'dm_full'@'%' to database 'full_mode'",
```
We don't know what happened
add the SQL to error
Tests 
Side effects
Documentation
```release-note
None
```
> dumpling: display the SQL which causes error

- executor/adapter.go
- planner/core/binary_plan_test.go
Issue Number: close #36617
Do not add the `tidb_decode_binary_plan('` and `')` if it's an empty binary plan.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: avoid log empty binary plan into slow log

- Makefile
- build/nogo_config.json
- distsql/distsql.go
- distsql/request_builder.go
- distsql/select_result.go
```goword``` is replaced by ```misspell``` in the ```golangci-linter```.
```megacheck``` is replaced by ```staticcheck,``` ```gosimple``` and ```unused``` in the ```golangci-linter```.
Tests 
```release-note
None
```
> makefile: remove useless linter and enable revive for distsql

- executor/infoschema_reader_test.go
- executor/show.go
- planner/core/expression_rewriter.go
- planner/core/planbuilder.go
- sessionctx/stmtctx/stmtctx.go
Issue Number: close #36426, #36496
This PR prevents running the executor when executing `SHOW COLUMNS` or reading `INFORMATION_SCHEMA.COLUMNS`.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: prevent sending cop request for show columns

- br/pkg/backup/BUILD.bazel
- ddl/BUILD.bazel
- ddl/column.go
- ddl/db_partition_test.go
- ddl/ddl.go
- ddl/ddl_api.go
- ddl/index.go
- ddl/partition.go
- parser/model/model.go
- parser/mysql/const.go
- planner/core/BUILD.bazel
- planner/core/plan_stats.go
- planner/core/preprocess.go
- planner/core/rule_partition_processor.go
- sessionctx/stmtctx/stmtctx.go
- sessionctx/variable/BUILD.bazel
- types/field_type.go
Previously, the package `planner/core` depends on the package `ddl`. It is a bit confusing.
1. Unify the functions of `model.TableInfo` or `model.IndexInfo`.
2. Decouple planner/core from ddl package.
Tests 
Side effects
Documentation
```release-note
None
```
> *: decouple planner/core from ddl package

- br/pkg/stream/stream_mgr.go
- br/pkg/task/stream.go
log-backup: fixed bugs about log truncate left some files and log truncate update log-min-date
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>
Issue Number: close #36376, #36533, #36535
- PiTR updates the safepoint after the user selects Y
- PiTR deletes the log file first and then deletes the meta file.
Tests 
Side effects
Documentation
For issue-36535:
- Run `./bin/br log metadata -s s3://xxx`
- Run `./bin/br log truncate -s s3://xxx  --until '2022-07-26 20:20:00+0800'` and enter 'N'
- Run `./bin/br log metadata -s s3://xxx` again
output: log-min-date unchange.
For issue-36533:
- Run `./bin/br log truncate -s s3://xxx  --until '2022-07-26 20:20:00+0800'`
output: No files remain.
For issue-36376:
- Run `./bin/br log truncate -s s3://xxx  --until '2022-07-26 …
> log-backup: fixed bugs about log truncate left some files and log truncate update log-min-date

- sessionctx/variable/tidb_vars.go
- util/paging/paging.go
Issue Number: close #35273
There is no single `min/max_paging_size` that suite for all circumstance.
QA require no performance degression on TPCH...
Without tuning the paging size, that's impossible.
But if we set the default value for TPCH performance testing, it's not fit for clould env to avoid OOM.
So the release decision for 6.2 is:
- Disable paging for non-cloud, let user to do the choice
- Enable paging on tidb cloud, better setting for avoiding OOM issues
Tests 
Side effects
Documentation
- [] Affects user behaviors
```release-note
None
```
> sessionctx/variable: set @@tidb_enable_paging default value to false on 6.2

- planner/core/plan_cost.go
- planner/core/plan_cost_test.go
pick https://github.com/pingcap/tidb/pull/36690 
```release-note
None
```
> planner: prefer to use TiKV to process small table scans and consider IndexJoin batch size in cost model ver2

- br/tests/br_split_region_fail/run.sh
Issue Number: ref #36651
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix merge conflict

- session/tidb.go
Issue Number: close #36791
Problem Summary: As title, refer the issue. After investigation,  rwmutex did not bring notable performance gain. Also no one will ever pass a nil store, verified by running all tests, so  `if len(dm.domains) == 1 && store == nil {` removed.
```
xhe@M1PRO testkit % cat 1
creating domains:
// mutex
BenchmarkDomain-8 5 241125350 ns/op
// rwmutex
BenchmarkDomain-8 5 229305383 ns/op
one domain, creating sessions:
// mutex
BenchmarkDomain-8 128607 9408 ns/op
BenchmarkDomain-8 125948 9338 ns/op
// rwmutex
BenchmarkDomain-8 132254 9853 ns/op
BenchmarkDomain-8 107743 9331 ns/op
```
Tests 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/re …
> session: fix multiple domain creation racing in domap

- planner/core/common_plans.go
- planner/core/plan_test.go
Issue Number: close #35090
Problem Summary: the chunk only have 5 columns, but the analyze results need 9 columns 
using analyze fieldNames
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix explain analyze format="brief" fails

- planner/core/cache.go
- planner/core/common_plans.go
- planner/core/plan_cache.go
Problem Summary: clean useless Plan Cache code of binary protocol parameters
Following https://github.com/pingcap/tidb/pull/36781, clean useless Plan Cache code of binary protocol parameters.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: clean useless Plan Cache code of binary protocol parameters

- DEPS.bzl
- br/pkg/storage/BUILD.bazel
- br/pkg/storage/parse_test.go
- br/pkg/storage/s3.go
- go.mod
- go.sum
- store/mockstore/unistore/tikv/server.go
Issue Number: close #36891 
* Added two query parameters for S3 URL in external storage: `role-arn` and `external-id`
* When creating an S3 client, if `role-arn` is set, assume the given role to access the S3 objects.
Tests 
- write a main program to construct a Lightning prechecker using a config
- set a role in AWS IAM with proper trust entity
- In the config, set the `data-source-url` to an S3 URL with 'role-arn' and 'external-id' set.  For example: `s3://my-testing-data/my-dir/?role-arn=arn:aws:iam::88888888:role%2Ftest-role&external-id=abcd1234`
- run the program, the check should not be blocked on 'Access Denied' error
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-no …
> br,lightning: S3 URL support assuming role

- .cilinter.yaml
```unused``` have been used in the ```staticcheck``` of nogo.
```typecheck``` have been checked when to build.
Tests 
```release-note
None
```
> *: remove useless linter

- br/pkg/stream/util_test.go
Signed-off-by: Gaoming Zhang <zhanggaoming028@gmail.com>
Issue Number: close #36802
Remove the timezone dependency of TestDateFormat.
Tests 
Test Env:
```
$ ls -l /etc/localtime
lrwxrwxrwx 1 root root 33 5月  12 09:33 /etc/localtime -> /usr/share/zoneinfo/Asia/Shanghai
```
Run `export TZ=Europe/Amsterdam && go test -v -run TestDateFormat`
output: 
```
=== RUN   TestDateFormat
--- PASS: TestDateFormat (0.00s)
PASS
ok  	github.com/pingcap/tidb/br/pkg/stream	0.067s
```
Side effects
Documentation
```release-note
None
```
> br: Fix bug in TestDateFormat

- executor/adapter.go
- executor/write.go
- sessionctx/variable/session.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Signed-off-by: zyguan <zhongyangguan@gmail.com>
Issue Number: ref #36438
Problem Summary: as described in https://github.com/pingcap/tidb/issues/36438#issuecomment-1209536885.
Revert #36498 to avoid accumulating LOCK records on unique keys.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: revert #36498 to avoid perf regression

- executor/aggregate.go
Issue Number: ref https://github.com/pingcap/tidb/issues/35635
Now AggExec will expand the map first and then track the memory usage. May cause a lot of memory to be allocated at once before the SQL OOM action is taken. 
We can move the tracking before the expand to avoid it.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: check memory limit before allocate large memory in HashAgg

- util/BUILD.bazel
- util/security_test.go
Issue Number: ref #36866
Tests 
Side effects
Documentation
```release-note
None
```
> util: fix unstable test TestCheckCN

- executor/adapter.go
- executor/executor_test.go
- executor/prepared.go
- executor/prepared_test.go
- planner/core/cache.go
- planner/core/common_plans.go
- planner/core/plan_cache.go
- planner/core/prepare_test.go
- server/conn_stmt.go
- server/driver_tidb.go
- session/session.go
Problem Summary: planner: remove keyword `prepared` in plan cache backend
No logical change, just refactor, remove keyword `prepared` in plan cache backend
Tests 
Side effects
Documentation
```release-note
None
```
> planner: remove keyword `prepared` in plan cache backend

- planner/core/integration_test.go
Issue Number: close #36867
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix unstable test TestPushDownSelectionForMPP

- server/optimize_trace.go
- server/plan_replayer.go
Tests 
```release-note
None
```
> server: revise scheme code

- executor/join_test.go
- planner/core/exhaust_physical_plans.go
Issue Number: close #37009
Tests 
```release-note
None
```
> planner: fix data race in the TestInlineProjection4HashJoinIssue15316

- br/pkg/restore/import.go
- br/pkg/restore/util.go
- br/pkg/restore/util_test.go
Issue Number: close #37063 
fix wrong of rewrite table id 767 when do restore point
The original logic is firstly try to rewrite the key in the way of rawKey, and then try the way of encodeKey if error.
But for the rewrite the encodeKey with table id 767 can success to be rewrited in the way of rawKey.
don't try both, just separate treatment.
Tests 
```release-note
None
```
> log-backup: fix wrong of rewrite table id 767 when do restore point

- executor/builder.go
- executor/point_get.go
- executor/slow_query_sql_test.go
Issue Number: close #37066
The display of index names for `PointGet` and `BatchPointGet` is inconsistent in `EXPLAIN` and the statements summary/slow log. In the statements summary and slow log, the index names are missing.
Append the index names when building `PointGet` and `BatchPointGet`, like we do when building `IndexReader`, `IndexLookUpReader` and `IndexMergeReader`.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix missing index names in stmt summary/slow log for `[Batch]PointGet`

- build/nogo_config.json
- planner/core/plan.go
Tests 
Run in CI
```release-note
None
```
> planner: enable more linter for planner/core/plan.go

- statistics/table.go
Issue Number: close #37080
Please see the issue.
Make the order of iterating the map in (t *Table) GetColRowCount() is stable.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: stablize `(*Table).GetColRowCount()`

- bindinfo/optimize_test.go
- planner/optimize.go
Issue Number: close #37059 
The test counts the times the `optimize` function is called. However, it's not expected. We only want ot validate the `optimize` time for a specified SQL (`select * from t` in the test).
I added a condition in the failpoint to compare the input node with the failpoint value, to make it only increate the counter for the specific sql.
Tests 
```release-note
None
```
> test,planner: only increase `optimizeCnt` for specified sql in test

- planner/core/plan_cost.go
Issue Number: close https://github.com/pingcap/tidb/issues/37096
Before:
```sh
BenchmarkTableScan-4   	    2829	    383439 ns/op
```
After:
```sh
BenchmarkTableScan-4   	    3663	    277817 ns/op
```
Tests 
```release-note
None
```
> planner: fix trace cost detail performance regression 

- build/nogo_config.json
- types/json/binary_functions.go
- types/json/binary_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/37133
because of the `**` in json path, the result of `json_extract` may contain duplicate result, we should remove it
Tests 
```release-note
None
```
> expression: remove duplicate element in `json_extract` function result

- executor/set_test.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: ref #36598 
Transform variable scope of TiDBPrepPlanCacheSize from `ScopeGlobal` to `ScopeGlobal | ScopeSession`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: modify sysvar TiDBPrepPlanCacheSize scope

- executor/prepared.go
- executor/seqtest/prepared_test.go
- executor/simple.go
- parser/ast/misc.go
- planner/core/plan_cache.go
- planner/core/plan_cache_utils.go
- planner/core/prepare_test.go
- planner/optimize.go
- server/driver_tidb.go
- session/session.go
- sessionctx/context.go
- sessionctx/variable/session.go
- sessionctx/variable/session_test.go
- util/mock/context.go
Problem Summary: planner: introduce the general plan cache
Introduce the general plan cache and refactor the interface to get plan cache from `session.PreparedPlanCache()` to `session.GetPlanCache(generalPlanCache bool)` where the argument `generalPlanCache` indicates whether to return the general plan cache or the prepared plan cache.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce the general plan cache

- executor/adapter.go
Issue Number: ref #36049
`colNames2ResultFields` was always called in `runPessimisticSelectForUpdate`. But the `Fields` method of `chunkRowRecordSet` is not always used. We can set `fields` to `nil` first in `runPessimisticSelectForUpdate` and generate it lazily when `Fields` is really called.
Tests 
- [] No code
Side effects
```release-note
None
```
> executor: generate fields in chunkRowRecordSet lazily

- distsql/distsql_test.go
- distsql/request_builder.go
- distsql/request_builder_test.go
- executor/analyze_col.go
- executor/analyze_idx.go
Issue Number: ref #36983
The default SI isolation level with max ts will meet txn conflict with high possibility if there exists writes. Thus we use tidb_enable_analyze_snapshot to control the isolevel.
let analyze isolevel controlled by tidb_enable_analyze_snapshot 
Tests 
```release-note
None
```
> executor: let analyze isolevel controlled by tidb_enable_analyze_snapshot 

- ddl/db_partition_test.go
- ddl/ddl_api.go
- errors.toml
- util/dbterror/ddl_terror.go
Issue Number: close #37201
Tests 
Side effects
Documentation
```release-note
When exchange partition with temporary table, an error will be returned.
```
> ddl: forbid exchange partition with temporary table

- dumpling/export/dump.go
- dumpling/export/dump_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/37241
Tests 
Side effects
Documentation
```release-note
None
```
> dumpling: fix wrong behaviour of StrictCollationCompatible

- .github/workflows/license-checker.yml
- executor/ddl.go
- parser/ast/ddl.go
- parser/misc.go
- parser/parser.y
- parser/parser_test.go
Issue Number: close #37229
Tests 
Side effects
Documentation
```release-note
Support `flashback cluster` stmt
```
> parser: let parser support `flashback cluster`

- .bazelrc
Problem Summary: Enable CI to output more compat logs, i.e. without lots of `coverage.dat` or `attempt_1.log` or the result of each test package(nobody really cares). Only the count of succeeded/failed tests are shown as a summary.
What is changed:
1. Use `--test_summary=testcase`
2. group bazel config by command type
3. Use `--test_env=TZ=Asia/Shanghai --test_output=errors` in non-ci environment but not `--experimental_ui_max_stdouterr_bytes=104857600`
Tests 
Side effects
Documentation
```release-note
None
```
> *: more concise bazel log

- expression/builtin_cast.go
- expression/builtin_cast_test.go
- expression/builtin_cast_vec.go
- types/json/binary.go
- types/json/binary_functions.go
- types/json/binary_test.go
- types/json/constants.go
Issue Number: close #31918 , close #9996
The cast and comparison is incompatible with MySQL. It's because we didn't consider the "opaque json" values. With considering the opaque json, and add it to the comparison order (actually, it has been in the list for a while :laughing: ).
This PR added a "Opaque JSON` values to store the binary strings. When this kind of json value is marshaled to the string, it's converted to `base64:typeXX:<base64 encoded string>`. It records both the mysql type (in `typeXX`), and the underlying binary data.
Considered three kinds of binary strings: `(.*)BLOB`, `BINARY`, `VARBINARY`. The `BLOB` and `VARBINARY` will not have extra zeros. However, the `BINARY` kind in opaque json will always have the …
> expression: add json opaque value

- session/session.go
Issue Number: ref https://github.com/pingcap/tidb/pull/37065
remove useless part for the preparedStmtExec
remove useless part for the preparedStmtExec
Tests 
Side effects
Documentation
```release-note
None
```
> planner: remove useless part for the preparedStmtExec

- sessionctx/variable/sysvar.go
- sessionctx/variable/sysvar_test.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #31585
This PR generally follows the [suggestion](https://github.com/pingcap/tidb/issues/31585#issuecomment-1010515766) from @morgo in #31585.
Tests 
As shown in #31585:
```
mysql> SET TIMESTAMP=3147483698;
ERROR 1231 (42000): Variable 'timestamp' can't be set to the value of '3147483698'
-- Retain previously set  timestamp
```
Side effects
Documentation
```release-note
Fix the issue that when setting a timestamp that is larger than `MAXINT32`, TiDB doesn't report an error like MySQL.
```
> sessionctx/variable: fix range check for @@timestamp

- kv/key.go
- kv/key_test.go
- store/copr/key_ranges.go
- util/logutil/hex.go
Issue Number: close #37286
make `kv.KeyRange` the same with `coprocessor.KeyRange` so we avoid converting and thus reduce object allocation.
The same workload, get the pprof
Before:
After:
Tests 
TPCH 50
Execute Query 16
```
explain analyze select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp, part where p_partkey = ps_partkey and p_brand <> 'Brand#34' and p_type not like 'LARGE BRUSHED%' and p_size in (48, 19, 12, 4, 41, 7, 21, 39) and ps_suppkey not
in ( select s_suppkey from supplier where s_comment like '%Customer%Complaints%' ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size;
```
Get the profile flamegraph.
Side effects
Documentation …
> kv,store/copr: make kv.KeyRange the same with coprocessor.KeyRange, so we can use unsafe optimization

- executor/executor_pkg_test.go
- util/memory/tracker.go
- util/memory/tracker_test.go
Issue Number: close #37058
1. The order of `FallbackOldAndSetNewAction` is wrong. It should set the current action to the new one, and set the original one as its fallback (as how it's used, and described in the comments). However, it acts in the opposite way now :facepalm: , and cause the unstable test.
2. The bytes limit of the third test is too low, which may cause two partitions. I increased the bytes limit, and it will only spill one partition now.
I rearrange the arguments order of the `FallbackOldAndSetNewAction`
Tests
I manually, repeatedly run this test multiple times (in parallel, 32 jobs) for several minutes, and it seems that it's stable now :heart: .
```release-note
Fix the issue that the action order of 
```
> *: fix the order of `FallbackOldAndSetNewAction`

- session/tidb.go
- session/tidb_test.go
Issue Number: close #37319
Problem Summary: Enterprise plugin will pass nil store.
Tests 
Side effects
Documentation
```release-note
Fix panic of enterprise plugin on 6.1
```
> session: handle nil store for plugins

- types/json/binary_functions.go
- types/json/binary_functions_test.go
Issue Number: close #37315
The comparison between json opaque is not implemented. They are currently comparing the `.GetString` of them, which will cause panic!
Implement the json opaque through comparing the `.GetOpaque().Buf`.
Tests 
```release-note
Fix the issue that comparison between json opaque will cause panic
```
> expression: implement comparison between json opaque

- executor/temporary_table_test.go
- infoschema/builder.go
- infoschema/infoschema_test.go
Issue Number: close #37306
This bug is introduced by #37225.  When the information schema applying diff, it will create a builder and then call `InitWithOldInfoSchema` to copy old schema to the new one. However, the previous PR forgot to copy `temporaryTableIDs` in it.
copy `temporaryTableIDs` in `InitWithOldInfoSchema`
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix global temp table will read tikv after schema change

- executor/aggregate.go
Issue Number: close #37299
The parameter for `UpdatePartialResult` is []chunk.Row, but there is only one row here.
`[]chunkRow{row}`  cause unnecessary object allocation.
Before:
After:
The `runtime.newobject` disappear after the change.
Tests 
Run tpch16 and capture the flamegraph
Side effects
Documentation
```release-note
None
```
> executor: reduce a place of object allocation for HashAggExec

- expression/builtin_json.go
- expression/typeinfer_test.go
- parser/mysql/const.go
Issue Number: close https://github.com/pingcap/tidb/issues/37339
Tests 
```release-note
None
```
> expression: set json to right type

- ddl/ddl_tiflash_test.go
- domain/infosync/tiflash_manager.go
Issue Number: close #37370
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix data race in `TestTiFlashGroupIndexWhenStartup`

- executor/aggfuncs/func_json_arrayagg.go
- executor/aggfuncs/func_json_objectagg.go
- executor/aggfuncs/func_json_objectagg_test.go
- expression/aggregation/base_func.go
Issue Number: close #25053 
The behavior of `json_objectagg` and `json_arrayagg` are different with MySQL, about the binary opaque value.
Add a condition for the binary values, and convert them to the JSON Opaque. It needs to notice that:
1. The value cannot be directly casted into JSON. The cast json behavior will try to cast a string to json, which is not expected.
2. The key could contain control character (e.g. `\t`, `\n`). The MySQL also has the same behavior, though JSON path cannot contain control character.
Tests 
```
drop table if exists test;
create table test (col_2 int, col_3 varbinary(163));
insert into test values (1,'o');
select json_objectagg( col_2, col_3 ) from test;
drop table if exists test;
create table …
```
> executor: add conversion to opaque value for json_objectagg and json_arrayagg

- ddl/db_integration_test.go
- infoschema/infoschema.go
- infoschema/infoschema_test.go
- session/session.go
- sessiontxn/failpoint.go
- sessiontxn/isolation/optimistic_test.go
- sessiontxn/isolation/readcommitted_test.go
- sessiontxn/isolation/repeatable_read_test.go
- sessiontxn/isolation/serializable_test.go
- sessiontxn/txn_manager_test.go
- table/temptable/ddl_test.go
- table/temptable/infoschema.go
TemporaryTableAttachedInfoSchema will save MDL table's tableInfo later, rename it now.
Tests 
Side effects
Documentation
```release-note
None
```
> *: rename TemporaryTableAttachedInfoSchema

- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/restore/tiflashrec/BUILD.bazel
- build/linter/noloopclosure/BUILD.bazel
Issue Number: close #37377
Tests 
Side effects
Documentation
```release-note
None
```
> bazel: update config

- bindinfo/bind_test.go
- bindinfo/capture_test.go
- executor/prepared_test.go
- planner/core/exhaust_physical_plans.go
- planner/core/integration_test.go
- planner/core/physical_plan_test.go
- planner/core/plan_cost_test.go
- planner/core/plan_test.go
- planner/core/testdata/analyze_suite_out.json
- planner/core/testdata/enforce_mpp_suite_out.json
- planner/core/testdata/integration_suite_out.json
- planner/core/testdata/plan_normalized_suite_out.json
- planner/core/testdata/plan_suite_in.json
- planner/core/testdata/plan_suite_out.json
For simple query like `select * from table where id > 1`, MPP mode should also have higher priority over cop mode because in cop mode, the data access is based on region, if the table have thousands of regions, TiFlash will receiver thousands of cop requests, and in MPP mode, the data access is based on TiFlash node, that is one TiFlash node only receiver one MPP request. Obviously, the latter one is more friendly to TiFlash. This patch solves above issue.
Before this patch:
```sql
explain select * from employee where deptid>1;
TableReader 3333.33 root  data:Selection
└─Selection 3333.33 cop[tiflash]  gt(test.employee.deptid, 1)
└─TableFullScan 10000.00 cop[tiflash] table:employee keep order:false, stats:pseudo
```
After this patch:
```sql
explain select * from employee where deptid>1; …
```
> planner: allow requesting MPP task for simple selection or projection operator

- store/copr/coprocessor.go
Issue Number: ref #36108 ref #37421
After #36108 or #37421, global kill request doesn't build any cop task so global kill doesn't take effect. We adjust the logic of building cop tasks so that global kill request can build the cop task, which will be sent to another TiDB for executing kill command.
Tests 
Side effects
Documentation
```release-note
None
```
> store/copr: fix building cop task for global kill

- ddl/db_partition_test.go
- distsql/request_builder.go
- executor/adapter.go
- executor/builder.go
- executor/distsql.go
- executor/partition_table_test.go
- executor/table_reader.go
- kv/kv.go
- planner/cascades/testdata/integration_suite_in.json
- planner/cascades/testdata/integration_suite_out.json
- planner/core/find_best_task.go
- planner/core/partition_pruner_test.go
- planner/core/physical_plans.go
- planner/core/task.go
- planner/core/testdata/partition_pruner_out.json
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
- store/copr/coprocessor.go
- testkit/result.go
Issue Number: ref #37483 
and cherry-pick #37477 
Tests 
Side effects
Documentation
```release-note
None
```
> *: make auto-analyze concurrency configurable & push part of order prop to partition table

- expression/builtin_compare.go
- expression/builtin_compare_test.go
- expression/distsql_builtin.go
- expression/distsql_builtin_test.go
- expression/integration_test.go
Issue Number: close #37403 
If one of the compare args is json value, the other should be casted to json.
Tests 
```
select cast('{ }' as json) < 1;
```
```release-note
Fix the issue that the comparison between json and other value is not compatible with MySQL
```
> expression: use a relax json comparison cast rule

- executor/compiler.go
- server/server_test.go
Signed-off-by: zyguan <zhongyangguan@gmail.com>
Issue Number: close #37503
Problem Summary: as described in #37503
`CountStmtNode` with `preparedObj.PreparedAst.Stmt` if the `stmtNode` is an `*ExecuteStmt`.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: distinguish query types of prepared stmt

- ddl/BUILD.bazel
- ddl/cluster.go
- ddl/ddl.go
- ddl/ddl_api.go
- ddl/ddl_tiflash_test.go
- ddl/ddl_worker.go
- ddl/schematracker/checker.go
- ddl/schematracker/dm_tracker.go
- domain/infosync/BUILD.bazel
- domain/infosync/info.go
- domain/infosync/schedule_manager.go
- executor/BUILD.bazel
- executor/ddl.go
- executor/recover_test.go
- meta/meta.go
- parser/ast/ddl.go
- parser/misc.go
- parser/model/ddl.go
- parser/parser.y
- parser/parser_test.go
Issue Number: ref #37197
Tests 
Side effects
Documentation
```release-note
merge PRs from feature/flashback-cluster to master
```
> *: merge feature/flashback-cluster to master

- session/tidb_test.go
- session/txn.go
- tablecodec/tablecodec.go
close pingcap/tidb#36235
Tests 
Side effects
Documentation
```release-note
None
```
> executor: do not acqurie pessimistic lock for non-unique index keys (#36229)

- owner/manager_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/37557
In `CampaignOwner`, we do `NewSession` get an error because of `context canceled`.
In `CampaignOwner` we use `go m.campaignLoop(session)`, so I think we need to use `go` to call `CampaignOwner`.
Tests 
Side effects
Documentation
```release-note
None
```
> owner: fix the unstable test of `TestCluster`

- parser/parser.y
- parser/parser_test.go
Issue Number: close #37495 
Problem Summary: flashback cluster shouldn't support expr in timestamp
Tests 
Side effects
Documentation
```release-note
flashback cluster shouldn't support expr in timestamp
```
> parser: let flashback cluster don't support expr

- Makefile
- go.mod
- server/conn.go
- server/conn_stmt.go
- server/conn_test.go
- sessionctx/variable/session.go
Tests 
Manual test log:
```
[2022/09/02 15:55:55.565 +08:00] [WARN] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="INSERT INTO t VALUES( ?, ? )"] [stmtID=1] [hasError=false] []
[2022/09/02 15:55:55.565 +08:00] [WARN] [conn_stmt.go:68] ["[DEBUG] [STMT_PREPARE]"] [conn=3] [connInfo="id:3, addr:127.0.0.1:54080 status:10, collation:utf8mb4_general_ci, user:root"] [status="inTxn:0, autocommit:1"] [sql="INSERT INTO t VALUES( ?)"] [stmtID=0] [hasError=true] [error="[planner:1136]Column count doesn't match value count at row 1"]
[2022/09/02 15:55:55.565 +08:00] [INFO] [conn.go:877] ["command dispatched failed"] [conn=3] …
```
> server: add debug log

- executor/infoschema_reader.go
- executor/show.go
- infoschema/tables.go
- privilege/privileges/privileges_test.go
Issue Number: close #37586
Two views may leak variables information in SEM
When fetching the data, check the privilege.
Tests 
Side effects
Documentation
```release-note
Fix a bug about variables information leak.
```
> infoschema: check hidden sysvars for SEM

- planner/core/cbo_test.go
- planner/core/logical_plan_builder.go
- planner/core/optimizer.go
- planner/core/rule_eliminate_projection.go
- sessionctx/stmtctx/stmtctx.go
close pingcap/tidb#37568
Tests 
Side effects
Documentation
```release-note
fix update plan's projection elimination will cause column resolution error
```
> cherry-pick: fix update plan's projection elimination will cause column resolution error. (#37582)

- planner/core/initialize.go
As `PhysicalIndexMergeJoin` and `PhysicalIndexHashJoin` Init having no `newBasePhysicalPlan`, the self pointer is wrongly point to the `IndexJoin` as its child, which may caused optimize trace panic.
Tests 
optimize trace tpch q3 and success.
```release-note
None
```
> planner: fix idxHJ/idxMJ with wrong self pointer

- br/pkg/lightning/restore/opts/precheck_opts.go
- build/nogo_config.json
Issue Number: close #37614 
Enabled the no-go checks for restore/opts package, to improve the code quality.
Also fixed the issues found by the new no-go check.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: enable nogo checks for restore-opts

- br/pkg/pdutil/pd.go
- br/pkg/restore/split.go
- br/pkg/restore/split_client.go
Issue Number: close #37549 
In huge clusters, we may fail to send `ScatterRegions` request with high concurrency config due to the timeout. Then we would retry it, however according to the PD team, scatter a region multiple times would make region unbalanced.
Added the timeout of requesting PD to 60s.
Tests 
```release-note
Fixed a bug caused when restoring with high `concurrency` the regions aren't balanced.
```
> br: increased PD time out

- server/http_handler_test.go
Issue Number: ref #35983 
The origin test `TestAllHistory` has defect because when the `RawArgs` is non-empty, the job from HTTP API `/ddl/history` is unequal to the job from kv-get `GetAllHistoryDDLJobs`:
GetAllHistoryDDLJobs:
```
[{"L":"idx1","O":"idx1"},false,1,[]]
```
HTTP API `/ddl/history`:
```
[
{
"L": "idx1",
"O": "idx1"
},
false,
1,
[]
]
```
Tests 
Side effects
Documentation
```release-note
None
```
> test: correct TestAllHistory

- distsql/select_result.go
- store/copr/coprocessor.go
Issue Number: close #37715
The old way to calculate the copr cache hit rate is not accurate.
Move the metrics to where it should be!
Tests 
Manually construct some tests and see how it works in grafana.
Side effects
Documentation
```release-note
None
```
> distsql,store: fix copr-cache hit/miss metrics

- ddl/db_partition_test.go
- executor/partition_table_test.go
Issue Number: close #37719 #37717
Make the test stable
Tests 
- [] Unit test
Side effects
Documentation
```release-note
None
```
> ddl,executor: fix two unstable partitino table unit test cases

- br/pkg/lightning/restore/get_pre_info.go
- br/pkg/lightning/restore/get_pre_info_test.go
- br/pkg/lightning/restore/mock/mock.go
Issue Number: close #37726 
When fetched the datum values slice, create a new slice with a copy of these datums, and append the new slice into the result.
Tests 
Side effects
Documentation
```release-note
None
```
> import: copy datum values when read first N rows

- expression/builtin_json.go
- expression/builtin_json_test.go
- expression/builtin_json_vec.go
- expression/distsql_builtin_test.go
The `json_storagesize` usually returns the size of json string, which is not expected. It should return the binary size consumed by this json (which is usually bigger than the size of json string, for `object` and `array`).
Issue Number: close #37307 
Returns the size of binary `JSONBinary`.
Tests 
```release-note
Fix the issue that `json_storage_size` returns incorrect size.
```
> expression: set correct json storage size

- session/bench_test.go
Issue Number: close #37708 
For now using dynamic prune mode should have global stats, otherwise it will fallback to partition union plan, thus we analyze table in this case in order to generate global stats.
```sh
before fix
BenchmarkRangeColumnPartitionPruning-4   	     380	   2906818 ns/op
after fix
BenchmarkRangeColumnPartitionPruning-4   	    1765	    675119 ns/op
```
Tests 
```release-note
None
```
> session: fix regression of BenchmarkRangeColumnPartitionPruning

- planner/core/exhaust_physical_plans.go
- planner/core/find_best_task.go
- planner/core/integration_test.go
- planner/core/logical_plans.go
- planner/core/physical_plans.go
- planner/core/plan_cache.go
- planner/core/stats.go
- sessionctx/stmtctx/stmtctx.go
- statistics/selectivity.go
- util/ranger/detacher.go
- util/ranger/points.go
- util/ranger/ranger.go
- util/ranger/ranger_test.go
- util/ranger/types.go
- util/ranger/types_test.go
Issue Number: ref #37176
Restrict column range mem usage. If the optimizer estimates that complete column ranges would exceed `tidb_opt_range_max_size`, it chooses full range. Part 2 of #37160.
Tests 
Side effects
Documentation
```release-note
None
```
> *: restrict column range mem usage

- executor/write_test.go
- planner/core/integration_test.go
- planner/core/logical_plan_builder.go
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add warning if fallback to static plan from dynamic

- executor/set_test.go
- sessionctx/variable/BUILD.bazel
- sessionctx/variable/tidb_vars.go
Issue Number: ref #37176
1. Put `TiDBOptRangeMaxSize` to the right place. It was with vars having only global scope. Now we put it with vars having both global and session scope.
2. Since range mem control mechanism is not GA for v6.3, we change the default value of `TiDBOptRangeMaxSize`, which indicates no range mem limit.
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx/variable: put TiDBOptRangeMaxSize to right place and set default value to 0

- types/datum.go
- types/datum_test.go
Issue Number: close #37852 
The json `null` is regarded the same with NULL, and then TiDB refuses to update it :thinking:. It expected that they are not equal in any senerio (not only for `update`, but also in `select j = NULL from t;`, and other cases).
Add a special condition to return 1 for comparing json and NULL.
Tests 
```release-note
Fix the issue that the user cannot update from json 'null' to NULL
```
> datum: json is not equal with NULL

- types/binary_literal.go
Issue Number: close #33494
For binary type error `ErrTruncatedWrongVal`, it is easy to locate. So it is not necessary to generate a stack for it.
Tests 
Side effects
Documentation
```release-note
None
```
> types: prevent generate error stack for BinaryLiteral.ToInt()

- Makefile
- domain/schema_validator.go
- domain/schema_validator_test.go
- session/session_fail_test.go
When a transaction executes a DDL, relatedPhysicalTableIDs is nil.
When a transaction only contains DML, relatedPhysicalTableIDs is [].
Tests 
```release-note
None
```
> ddl, transaction: DDL won't affect transactions

- planner/core/plan_cache_lru.go
- planner/core/plan_cache_lru_test.go
Forget consider the cache size when trigger memoryControl
Issue Number: close #37914 
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix nil pointer in plan cache LRU

- ddl/callback_test.go
- ddl/cancel_test.go
- ddl/column_change_test.go
1. Some variables in the test is used concurrently. I used an atomic variable to read/write them to fix the data race
2. The callback struct is also concurrently modified. I add a clone method to copy it explicitly. 
I have also considered other solutions, for example using non-pointer receiver to implement the callback, so it can be copied automatically when passing into the functions. However, as this struct contains a `*BaseCallback`, it could cause more problem when misused.
Issue Number: close #37757
> test,ddl: fix data race in `TestCancel`

- executor/show.go
- executor/showtest/show_test.go
Issue Number: close #37966
Problem Summary: `SHOW CREATE USER` fails to correctly show if a user is locked or not.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: show locked status of accounts

- store/copr/batch_coprocessor.go
Issue Number: close #37989
After changing last to lastAny, Any doesn't init to time. So it may panic if casting it to time. 
Tests 
``` SQL
mysql> CREATE table t(c int);
Query OK, 0 rows affected (0.11 sec)
mysql> insert into t values(1),(2),(3);
Query OK, 3 rows affected (0.02 sec)
Records: 3  Duplicates: 0  Warnings: 0
mysql> alter table t set tiflash replica 1;
Query OK, 0 rows affected (0.15 sec)
mysql> SELECT c from t ORDER BY c;
+------+
| c    |
+------+
|    1 |
|    2 |
|    3 |
+------+
3 rows in set (0.00 sec)
```
Side effects
Documentation …
> store: handle nil execption

- ddl/ingest/env.go
- ddl/ingest/rlimit_linux.go
- ddl/ingest/rlimit_windows.go
Tests 
```release-note
None
```
> *: windows compile support

- roadmap.md
Signed-off-by: Ran <huangran.alex@gmail.com>
Add a disclaimer notice.
Tests 
Side effects
Documentation
```release-note
None
```
> docs: add disclaimer for roadmap

- types/json_binary.go
- types/json_binary_test.go
Issue Number: close #38092 
The hash value of json is conflict unexpected for some values.
I add some logic to make sure the `HashValue` function is (potentially) a bidirectional mapping between the json value and hash value.
Tests
```release-note
Fix the issue that the hash of some json values are conflict unexpectedly.
```
> json, executor: fix json hash value conflict

- planner/core/exhaust_physical_plans.go
- util/ranger/detacher.go
Issue Number: ref #37176
1. `relatedExprs` in `(*indexJoinBuildHelper).analyzeLookUpFilters` is just the same as `access` so we can remove `relatedExprs`.
2. Make `(*indexJoinBuildHelper).findUsefulEqAndInFilters` clearer.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: small refactor for index join inner range building

- ddl/foreign_key_test.go
- executor/show.go
- executor/showtest/show_test.go
Issue Number: close #38118
Problem Summary: show create table with foreign key need display database name.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix show create table with foreign key

- planner/core/planbuilder.go
Issue Number: close #38043
The number of arguments exceeds the number of parameters.
Tests 
```release-note
None
```
> planner: fix the strange error message of ErrDBaccessDenied

- executor/tiflashtest/BUILD.bazel
- executor/tiflashtest/tiflash_test.go
- go.mod
- go.sum
- store/copr/batch_coprocessor.go
- store/mockstore/unistore/rpc.go
- store/mockstore/unistore/tikv/server.go
Signed-off-by: xufei <xufeixw@mail.ustc.edu.cn>
Issue Number: close #38113
The whole story is like this:
1. At the very beginning, TiDB can only access TiFlash in cop mode, in cop mode, each cop request only access data in one region. If the region has multiple TiFlash replicas, then each time the region is accessed, it will choose the next replica to serve, so the load is balanced between TiFlash nodes.
2. After introducing MPP and BatchCop, TiDB can access TiFlash in BatchCop/MPP mode, compared to cop mode, BatchCop/MPP mode does not access data by region, instead, it access data by TiFlash node. That is to say, each BatchCop/MPP request will read a batch of regions in on TiFlash node. BatchCop/MPP can reduce the rpc calls greatly but it also meet some problems, …
> copr: enable region load balance for MPP

- br/pkg/lightning/config/BUILD.bazel
- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/config/global.go
Issue Number: close #38151 
When constructing a new Lightning config, clone the default filter before assigning.  To avoid the elements of default filter being changed.  
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: clone default filter for new configs

- executor/table_reader.go
- tidb-server/BUILD.bazel
Issue Number: close #38178
Tests 
enable race for tidb-server binary and run it with mysql-test.
```release-note
None
```
> *: fix data race and enable race for tidb-server

- executor/show.go
- executor/showtest/show_test.go
- parser/ast/dml.go
- planner/core/logical_plans.go
- planner/core/planbuilder.go
- planner/core/preprocess.go
issue pingcap/tidb#33407
Issue Number: close #33407
The supported Show stmts are go through to find out what stmts should be influenced by SelectLimit value on return result set row numbers.  The Limit executor is added into plan tree for show stmts to archieve the requirement.
Tests 
```release-note
None
```
> Compatibility: SQL_SELECT_LIMIT worked in show statement;

- types/json_path_expr.go
Issue Number: ref https://github.com/pingcap/tidb/issues/38230
there is some evidence that shows the data in json path cache is broken, we'd better make a copy when retrieving it
Tests 
```release-note
None
```
> expression: make a copy when retrieving json path expression from cache

- .bazelrc
Tests 
Side effects
Documentation
```release-note
None
```
> bazel: enable experimental_guard_against_concurrent_changes

- planner/core/integration_test.go
- planner/core/planbuilder.go
Issue Number: close #38295
This is a pointer leak bug that causes the field type of a column changed after a "SELECT" statement is executed.
```
SELECT t0.c1, t0.c2 FROM t0 GROUP BY MOD(t0.c0, DEFAULT(t0.c2));
```
When TiDB evaluates the "DEFAULT" expression, the table in infoschema is used:
```
tbl, er.err = er.b.is.TableByName(dbName, name.OrigTblName)
...
col := table.FindCol(tbl.Cols(), colName)
```
Furthermore, the reference to this column's field type is passed to the `Constant` struct:
https://github.com/pingcap/tidb/blob/20e749ecbeafb1a8967cda3bddf4052005f6f630/planner/core/planbuilder.go#L3439
And it is changed in the type propagation during rewrite:
```
types.(*FieldType).SetDecimalUnderLimit (field_type.go:167) github.com/pingcap/tidb/parser/types …
```
> planner: `getDefaultValue` should clone field type

- parser/ast/ddl.go
- parser/parser_test.go
Issue Number: close #38368
Restore table option `INSERT_METHOD` should always be without quotes.
Use `WriteKeyWord()` instead of `WriteString()`, both upper case and lower case can works well.
Tests 
Side effects
Documentation
```release-note
None
```
> fix(parser): restore table option INSERT_METHOD should use WriteKeyWord

- executor/builder.go
- planner/core/planbuilder.go
Issue Number: close #37323 
Maybe the better error message should be "index `primary` is not defined in table `%v` when primary key is a single integer column and clustered" ?
Tests 
Side effects
Documentation
```release-note
None
```
> executor: better error message for `ADMIN CHECK INDEX`

- Makefile
- go.mod
- store/tikv/region_cache.go
- store/tikv/region_cache_test.go
Issue Number: close #37141
Our region cache B-Tree uses the start key of the region as the entry key. So, `insertRegionToCache` only replaces the region with the same start key:
https://github.com/tikv/client-go/blob/516cfcdecce865d90ec05dd1cc1de060c35438dc/internal/locate/region_cache.go#L1287
Considering there's a table with lots of regions, the user removes all data from the table. So, PD will finally merge all regions into one. In our region cache implementation, only the first region (containing the table head) is updated, while all other regions still exist in the cache.
When we locate a key near the end of the table, `DescendLessOrEqual` will iterate over all regions that are left in the cache. This will waste a lot of CPU and make region search really slow, and it …
> store/tikv: clear intersecting regions in the cache when inserting a region

- planner/core/common_plans.go
- planner/core/plan_cost_ver2.go
- planner/core/plan_cost_ver2_test.go
- planner/core/planbuilder.go
Issue Number: ref #36243
Problem Summary: planner: show operator cost formulas under 'explain format=true_card_cost' 
Show operator cost formulas under 'explain format=true_card_cost', which can help understand how the optimizer calculates the plan costs.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: show operator cost formulas under 'explain format=true_card_cost' 

- Makefile.common
The repository cache
Bazel tries to avoid fetching the same file several times, even if the same file is needed in different workspaces, or if the definition of an external repository changed but it still needs the same file to download. To do so, bazel caches all files downloaded in the repository cache which, by default, is located at ~/.cache/bazel/_bazel_$USER/cache/repos/v1/. The location can be changed by the --repository_cache option. The cache is shared between all workspaces and installed versions of bazel. An entry is taken from the cache if Bazel knows for sure that it has a copy of the correct file, that is, if the download request has a SHA256 sum of the file specified and a file with that hash is in the cache. So specifying a hash …
> bazel: enable repository_cache

- go.mod
- go.sum
Issue Number: close #37141
Our region cache B-Tree uses the start key of the region as the entry key. So, insertRegionToCache only replaces the region with the same start key:
https://github.com/tikv/client-go/blob/516cfcdecce865d90ec05dd1cc1de060c35438dc/internal/locate/region_cache.go#L1287
Considering there's a table with lots of regions, the user removes all data from the table. So, PD will finally merge all regions into one. In our region cache implementation, only the first region (containing the table head) is updated, while all other regions still exist in the cache.
When we locate a key near the end of the table, DescendLessOrEqual will iterate over all regions that are left in the cache. This will waste a lot of CPU and make region search really slow, and it is …
> *: update client-go (tidb-6.1)

- br/pkg/streamhelper/basic_lib_for_test.go
Signed-off-by: hillium <yujuncen@pingcap.com>
Issue Number: (hopefully) close #37482
The `lastFlushedEpoch` might get shared between cores but not guarded with atomic.
Make it an atomic variable.
Tests 
```release-note
None
```
> tests: use atomic values for flushed epoch in `streamhelper_test`

- store/mockstore/unistore/cophandler/cop_handler.go
like other code, it should be `-1` if no primary key is used
Tests 
```release-note
None
```
> mockkv: make pk id = -1 if no primary key column is used

- ddl/backfilling.go
- ddl/column.go
- ddl/db_partition_test.go
- ddl/ddl_api.go
- ddl/failtest/fail_db_test.go
- expression/expression.go
- planner/core/plan_test.go
- planner/core/rule_predicate_push_down.go
- store/mockstore/unistore/cophandler/cop_handler.go
Tests 
Side effects
Documentation
```release-note
None
```
> Merge master into feature branch

- br/tests/br_incremental_ddl/run.sh
The [change](https://github.com/pingcap/tidb/pull/32169/files) of concurrent ddl didn't pick to release-6.1. so the incrmental backup will invoke `UseOneShotSession` once and the test `br_incremental_ddl` is different from master.
fix the broken test by update the check logic.
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix the broken incremental backup  integration test

- ddl/ddl.go
- ddl/ddl_api.go
- ddl/ddl_worker.go
- ddl/rollingback.go
- ddl/schema.go
- ddl/schematracker/checker.go
- ddl/schematracker/dm_tracker.go
- ddl/table.go
- executor/ddl.go
- executor/recover_test.go
- infoschema/builder.go
- parser/ast/ddl.go
- parser/ast/ddl_test.go
- parser/model/ddl.go
- parser/parser.y
- parser/parser_test.go
- planner/core/planbuilder.go
- planner/core/preprocess.go
Issue Number: close #20463
1.Add RecoverSchemaInfo struct contains SchemaInfo and TableInfo.
2.Add recoverSchema code logical like the recovertable .
Tests 
```
mysql> drop database m;
Query OK, 0 rows affected (0.43 sec)
mysql> create database m;
Query OK, 0 rows affected (0.20 sec)
mysql> use m;
mysql> CREATE TABLE t(id int PRIMARY KEY AUTO_INCREMENT, c int);
Query OK, 0 rows affected (0.19 sec)
mysql> INSERT INTO t(c) VALUES (1);
Query OK, 1 row affected (0.03 sec)
mysql> INSERT INTO t(c) VALUES (2);
Query OK, 1 row affected (0.01 sec)
mysql> drop database m;
Query OK, 0 rows affected (0.42 sec)
mysql> flashback database m;
Query OK, 0 rows affected (0.97 sec)
mysql> use m ;
mysql> select * from t;
+----+------+
| id | c    | …
```
> ddl: Support flashback schema

- expression/util.go
- planner/cascades/transformation_rules.go
- planner/core/integration_test.go
- planner/core/rule_predicate_push_down.go
close pingcap/tidb#35623
Issue Number: ref #35623 
cherry-pick https://github.com/pingcap/tidb/pull/37992
Problem Summary: Some conditions can not be substituted. Do not push down them.
Do not push down some conditions which can not be substituted.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: don't push down some conditions to projections (#37992)

- executor/infoschema_reader.go
Issue Number: close #37499
Tests 
tiup create a cluster, execute sqls below
```
create table t(a int);
mysql> select * from INFORMATION_SCHEMA.TIKV_REGION_STATUS where table_id in (2,68,70) limit 5;
+-----------+--------------------------------------+--------------------------------------+----------+---------+---------------+----------+----------+------------+----------------+---------------+---------------+------------+------------------+------------------+-------------------------+---------------------------+
| REGION_ID | START_KEY                            | END_KEY                              | TABLE_ID | DB_NAME | TABLE_NAME    | IS_INDEX | INDEX_ID | INDEX_NAME | EPOCH_CONF_VER | EPOCH_VERSION | WRITTEN_BYTES | READ_BYTES | APPROXIMATE_SIZE | APPROXIMATE_KEYS | …
```
> executor: fix getting the more result when `select * from TIKV_REGION_STATUS where table_id=xx`

- executor/infoschema_reader.go
Issue Number: close #38407
We forget to check the permission while reading information_schema.
Tests 
- `tiup playground --db 1 --kv 1 --tiflash 0 --db.binpath ./bin/tidb-server`
- executes the commands in the issue
Side effects
Documentation
```release-note
Fix a permission issue in information_schema.TIKV_REGION_STATUS
```
> inforschema: check the user permission before loading TIKV_REGION_STATUS

- executor/adapter.go
- executor/fktest/foreign_key_test.go
- executor/foreign_key.go
Issue Number: close #38631
Problem Summary: fix issue of foreign key cascade delete very slow.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix issue of foreign key cascade delete very slow

- planner/core/common_plans.go
- planner/core/plan_cost_ver2.go
- planner/core/plan_cost_ver2_test.go
Problem Summary: planner: update seek-factor in cost model ver2
1. output cost factor weights under `true-card-cost` mode for cost calibration;
2. since the number of requests is tough to estimate, for simplicity and robustness, only let operators that need double-read like IndexLookup and IndexJoin consider this cost.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: update seek-factor in cost model ver2

- executor/adapter.go
- server/conn_test.go
When user issue an long run DDL statement, it should not be checked in maxExecutionTime for slow query checking mechanism.
Issue Number: close #38580
Just Skip none query type statements max execution time checking and kill them.
Tests 
```release-note
None
```
> *: skip log timeout on maxExecutiontime as slow query for DDL statement.

- executor/fktest/foreign_key_test.go
- executor/show.go
- executor/showtest/show_test.go
…reign key
Issue Number: close #38717
Already discussed with the PM @easonn7
The old version foreign key will display a comment:
```sql
mysql>show create table t1\G
***************************[ 1. row ]***************************
Table        | t1
Create Table | CREATE TABLE `t1` (
`id` int(11) NOT NULL,
`leader` int(11) DEFAULT NULL,
PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
KEY `leader` (`leader`),
CONSTRAINT `fk` FOREIGN KEY (`leader`) REFERENCES `test`.`t1` (`id`) ON DELETE CASCADE ON UPDATE SET NULL /*T![FOREIGN KEY] INVALID */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```
The new version foreign key doesn't have comment:
```sql
mysql>show create table t1\G
***************************[ 1. row …
```
> executor: show create table should distinguish between old and new foreign key

- br/pkg/restore/log_client_test.go
Issue Number: close N/A
This PR added test case for stream-iters, and refactored the test implementation.
Now, we write test case with type `func(*testing.T, metaMaker), which can hold two types of metadata.`
Tests 
```release-note
None
```
> tests: added v1 test for iterators

- .bazelrc
- Makefile
```
Does not download any remote build outputs to the local machine. 
```
Tests 
Side effects
Documentation
```release-note
None
```
> bazel: use --remote_download_minimal in ci

- sessionctx/variable/sysvar.go
- sessionctx/variable/sysvar_test.go
Issue Number: close #38867
Just as issue said, add global scope for the var.
Tests 
Side effects
Documentation
```release-note
None
```
> variable: add global scope for tidb_opt_agg_push_down

- Makefile
- sessionctx/variable/sysvar.go
…it is disabled
if ServerMemoryLimit is 0, we need to read machine memory.
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: fix tidb_gogc_tuner_threshold 

- executor/executor.go
- executor/executor_test.go
- server/conn.go
- session/bootstrap.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
- tidb-server/main.go
- util/memory/tracker.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: disable global memory control by default

- executor/adapter.go
- executor/builder.go
- metrics/telemetry.go
- session/session.go
- telemetry/data_feature_usage.go
- telemetry/data_feature_usage_test.go
Issue Number: close #38896
Tests 
Side effects
Documentation
```release-note
None
```
> telemetry: telemetry supports count `flashback cluster`

- executor/executor.go
- executor/executor_test.go
- session/bootstrap.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
- tidb-server/main.go
- util/memory/tracker.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: enable global memory control by default

- planner/core/enforce_mpp_test.go
- planner/core/integration_test.go
- planner/core/physical_plan_test.go
- planner/core/plan_cost_ver2.go
- planner/core/testdata/enforce_mpp_suite_out.json
- planner/core/testdata/integration_suite_in.json
- planner/core/testdata/integration_suite_out.json
Problem Summary: planner: update some UTs to cost model2
Tests 
Side effects
Documentation
```release-note
None
```
> planner: update some UTs to cost model2

- session/txnmanager.go
Issue Number: close #38951
To reduce space allocation, we used to reserve `OptimisticTxnContextProvider` to txnManager that cause the old and new `OptimisticTxnContextProvider` be the same. After `ResetForNewTxn` , the old provider's state will be corrputed. 
It is triggered when new MDL codes merged, see: https://github.com/pingcap/tidb/pull/38926#issuecomment-1305198324
Reserve two `OptimisticTxnContextProvider` and make the old and the new one not the same.
```release-note
None
```
> *: fix panic when reusing `OptimisticTxnContextProvider`

- go.mod
- go.sum
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
Issue Number: close #37141
Our region cache B-Tree uses the start key of the region as the entry key. So, insertRegionToCache only replaces the region with the same start key:
https://github.com/tikv/client-go/blob/516cfcdecce865d90ec05dd1cc1de060c35438dc/internal/locate/region_cache.go#L1287
Considering there's a table with lots of regions, the user removes all data from the table. So, PD will finally merge all regions into one. In our region cache implementation, only the first region (containing the table head) is updated, while all other regions still exist in the cache.
When we locate a key near the end of the table, DescendLessOrEqual will iterate over all regions that are left in the cache. This will waste a lot of CPU …
> *: update client-go for v5.3.4

- sessionctx/variable/BUILD.bazel
- sessionctx/variable/sysvar.go
- sessionctx/variable/variable_test.go
Issue Number: close #38973
We have limit between tidb_server_memory_limit_gc_trigger and tidb_gogc_tuner_threshold.
But we init the one of them and the other is not inited. it will have problem.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix variable problem during initialization

- server/rpc_server.go
Issue Number: close #38983
`keepalive.EnforcementPolicy.MinTime` is the minimum amount of time a client should wait before sending a keepalive ping. Currently, it is unset and the default value is 5 minutes, which is too long, since TopSQL gRPC client sends pings to the server every 10 seconds. As a result, "too many pings" is reported too frequently.
This PR changes this argument to 5 seconds.
Tests 
Side effects
Documentation
```release-note
None
```
> server: set the keepalive MinTime for gRPC server

- executor/analyzetest/analyze_test.go
Issue Number: close #38882, close #38883
Timeout of SyncWaitStatsLoad, fixed by increasing the default wait.
Tests 
Manually tested by running each test case 100 times concurrently (before fix ~5-15% failure, after 0 out of 100 failures)
Side effects
Documentation
```release-note
None
```
> executor/analyzetest: Stabilise analyze table tests due to SyncWaitStatsLoad timeout

- br/pkg/utils/db.go
Issue Number: close #39012
TiDB is stuck in accessing self instance. Because the bootstrap has not completed, the status port is not available. However, the bootstrap process uses `show config`, which needs to access the status port.
Filter the TiKV nodes for `CheckLogBackupEnabled`.
Tests 
Run `make integration_test` in binlog repo.
Side effects
Documentation
```release-note
None
```
> br: refine IsLogBackupEnabled

- util/security.go
Tests 
use dumpling to connection TiDB cloud serverless
Side effects
Documentation
```release-note
Fix a bug that can not connect server if server returns intermediate certs 
```
> util: support intermediate certs when use TLS

- types/core_time.go
- types/core_time_test.go
Issue Number: close #39037
Our request of accessing time zone bounds in the go time pkg has been implemented, and simplifies our time zone check code.
Tests 
Side effects
Documentation
```release-note
None
```
> types: Make use of the new time.ZoneBounds function in go-1.19

- executor/executor.go
Issue Number: close #38980
For the add index jobs from TiDB v4.0, it is possible to have `job.ReorgMeta` to be `nil`.
Check if `job.ReorgMeta` is nil before using it.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix admin show job panic when upgrade from v4.0 to v6.4

- ddl/syncer/syncer.go
cluster_info may return invalid TiDB info, in OwnerCheckAllVersions, it doesn't need to check the invalid TiDB info.
If two instances have the same address and port, we know that the one started earlier is invalid.
``` SQL
mysql> select * from information_schema.cluster_info;
+------+---------------------+---------------------+-------------+------------------------------------------+---------------------------+---------------+-----------+
| TYPE | INSTANCE            | STATUS_ADDRESS      | VERSION     | GIT_HASH                                 | START_TIME                | UPTIME        | SERVER_ID |
+------+---------------------+---------------------+-------------+------------------------------------------+--------------------------- …
```
> ddl: refine logic of OwnerCheckAllVersions

- extension/event_listener_test.go
- planner/core/planbuilder.go
Issue Number: close #38493
The `StatementContext.Tables` records the all tables/databases we are accessing in the statement. But some times it have some empty value (db == "" and table == "").
The reason is that the tables are from `planBuilder.visitInfos` , but it not only contains database/tables, it also contains some dynamic privilege visitInfos, so we should filter those visitInfos out.
filter out the visitInfos with dynamic privilege out.
Tests 
Side effects
Documentation
```release-note
None
```
> stmtctx: remove the empty values in `StatementContext.Tables`

- ddl/ddl_api.go
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: delete `pkIsHandle` log in drop index

- ddl/cluster_test.go
- domain/domain.go
- executor/BUILD.bazel
- executor/analyze.go
- executor/builder.go
- executor/infoschema_cluster_table_test.go
- executor/lock_stats.go
- executor/show.go
- executor/show_stats.go
- executor/show_stats_test.go
- parser/ast/dml.go
- parser/ast/stats.go
- parser/misc.go
- parser/parser.y
- parser/parser_test.go
- planner/core/common_plans.go
- planner/core/planbuilder.go
- session/bootstrap.go
- statistics/handle/handle.go
- statistics/handle/handle_test.go
- statistics/handle/update.go
- statistics/handle/update_test.go
Sometime peformance drop due to the explain change that caused by statistic info change after data changes in table.
So we want to introduce table statistic lock/unlock function to avoid unexpected peformance drop by statistic changes.
The main idea is adding new table mysql.stats_table_locked to record which table is locked, and when doing manual/auto table analyze, check whether table is locked, if locked, skip analyse. And I also filter the locked table in session stat collector operations, that session stat collector  won't collect the statistic data of locked table.
Add SQL syntax 'lock/unlock stats xxx(table name)'  to add/remove table name to/from mysql.stats_table_locked.
- Add new table mysql.stats_table_locked
- Add lock/unlock function …
> *: add statistic lock/unlock function

- executor/simple.go
- executor/simpletest/simple_test.go
- parser/ast/misc_test.go
- parser/ast/stats.go
- parser/parser.y
- parser/parser_test.go
- parser/yy_parser.go
Issue Number: close #37872 
`DROP STATS` doesn't allow dropping stats of multiple tables now.
This PR modifies the parser and executors to allow dropping multiple tables without partitions. 
The grammar should be discussed, as the `DROP STATS t1, t2 GLOBAL` and `DROP STATS t PARTITION xxx` is not consistent now. I'm not sure whether it's expected, or I shouldn't allow dropping multiple tables with `GLOBAL` at the end?
Tests 
```release-note
Allow dropping stats of multiple tables
```
> parser: allow drop stats of multiple tables

- executor/fktest/foreign_key_test.go
- executor/show.go
- executor/showtest/show_test.go
- util/gctuner/tuner_test.go
Problem Summary: The issue was introduce by https://github.com/pingcap/tidb/pull/38719, caused by the comment `/*T![FOREIGN KEY] INVALID */` can't be parsed by TiDB, so this PR use `/* [FOREIGN KEY] INVALID */` a normal comment instead.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix issue of show create table with foreign key comment

- util/gctuner/tuner.go
- util/gctuner/tuner_test.go
Issue Number: close #39110
Tests 
Side effects
Documentation
```release-note
None
```
> gogctuner: support Max/Min GOGC

- ddl/index.go
- executor/admin.go
- executor/builder.go
- planner/core/plan_to_pb.go
- session/schema_amender.go
- table/tables/mutation_checker_test.go
- table/tables/tables.go
- `SetPBColumnsDefaultValue` will be used by the ddl package. It is moved out of `planner/core` in this PR.
- `TryGetHandleRestoredDataWrapper` accepts a `model.TableInfo` instead of `tables.Table`.
Tests 
Side effects
Documentation
```release-note
None
```
> *: refactor some functions for better reusability

- executor/infoschema_reader_test.go
- parser/types/field_type.go
Issue Number: close #25472
fix bit, year column metadata is not compatible with mysql 
Tests 
Side effects
Documentation
```release-note
None
```
> infoschema: fix bit, year column metadata is not compatible with mysql

- DEPS.bzl
- go.mod
- go.sum
- util/logutil/log.go
- util/logutil/log_test.go
Issue Number: close #38941
Problem Summary: Check the issue. Use one logger.
Tests 
Check the issue.
Side effects
Documentation
```release-note
Fix broken log rotation of grpc
```
> util: use one logger

- executor/fktest/foreign_key_test.go
- executor/foreign_key.go
Issue Number: close #39200
Problem Summary: fix issue of insert into parent table failed cause by foreign key check.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix issue of insert into parent table failed cause by foreign key check

- br/pkg/restore/stream_metas_test.go
- br/pkg/storage/gcs.go
- br/pkg/storage/gcs_test.go
- br/pkg/storage/s3.go
- br/pkg/storage/storage.go
Issue Number: close #39204 
* Expose the constructor for S3 / GCS external storage implementations.
* Expose the GCS external storage implementation public.
* Expose some fields for these implementations.
Tests 
Write an external program to construct an S3 / GCS storage implementation, and use the newly exposed fields to achieve some S3 / GCS operations.  
Side effects
Documentation
```release-note
None
```
> lightning: make some s3/gcs external storage fields public

- br/pkg/lightning/lightning.go
Issue Number: ref #38455 , but it's about showing lightning speed
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: expose metrics when as a library

- sessionctx/variable/tidb_vars.go
Issue Number: close #35240
Problem Summary: planner: enable cost model2 by default
planner: enable cost model2 by default
Tests 
Side effects
Documentation
```release-note
None
```
> planner: enable cost model2 by default

- ddl/multi_schema_change_test.go
Issue Number: close #39224
It is possible that the last DDL job does not exit in time.
Skip non-multi-schema change jobs.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: stabilize multi-schema change tests

- statistics/handle/ddl.go
cherry-pick https://github.com/pingcap/tidb/pull/35424
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: fix panic when using wrong globalStats.Indices key

- br/pkg/restore/client.go
- br/pkg/restore/client_test.go
- br/pkg/task/restore.go
- br/pkg/task/stream.go
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>
Issue Number: ref #36910
When the switch of the leader occurs in the PD, it affect the BR restore and PiTR restore.
replace `GetTS` with `GetTSWithRetry`
Tests 
Side effects
Documentation
- run restore with injected error
- restore succeeded
```release-note
Fix a bug that caused: When the switch of the leader occurs in the PD, it affect the BR restore and PiTR restore.
```
> br: replace GetTS with GetTSWithRetry

- br/pkg/gluetidb/glue.go
- br/pkg/restore/BUILD.bazel
- br/pkg/restore/client.go
- br/pkg/restore/client_test.go
- br/pkg/task/backup.go
- br/pkg/task/common.go
- br/pkg/task/restore.go
- br/pkg/task/restore_test.go
- br/pkg/utils/db.go
Issue Number: close #39150
The `collate.newCollationEnabled` variable is set to 1 when the collate package is initialized. When using this package, this value is not modified according to the config of the TiDB cluster (i.e., `new_collations_enabled_on_first_bootstrap`).
As a result, the user sets `new_collations_enabled_on_first_bootstrap` to `false` in the TiDB cluster, and it is still treated as `true` when br is executed.
Modify `collate.newCollationEnabled` according to the config of the cluster.
Tests 
Side effects
Documentation
- create a cluster with tidb config `new_collations_enabled_on_first_bootstrap: false`.
- create a table with collation 'utf8mb4_0900_ai_ci': `create table books (id bigint auto_increment,name varchar(64), primary key (id)) CHARSET utf8mb4 …
> br: modify collate.newCollationEnabled according to the config of the cluster

- docs/design/2020-01-24-collations.md
Fix typo and fix dead link.
Tests 
Side effects
Documentation
```release-note
None
```
> docs: fix typo and dead link

- executor/analyze_col_v2.go
- executor/batch_point_get.go
- executor/executor.go
- executor/point_get.go
- executor/table_reader.go
- table/BUILD.bazel
- table/column.go
Move `FillVirtualColumnValue` from `executor` to `table` for better reusability.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: move `FillVirtualColumnValue` to the `table` package

- parser/ast/ddl.go
- parser/ast/ddl_test.go
- parser/misc.go
- parser/parser.y
- parser/parser_test.go
Issue Number: close #39340
Use `alter table remove ttl` instead of `alter table no_ttl`. And remove the support of arbitrary expression, but only support valueExpr from Literal.
It changed three things:
1. Change the name of `AlterTablePartitionOpt` to `AlterTableSingleSpecOpt` and add a `"REMOVE" "TTL"` branch to it. We cannot add `"REMOVE" "TTL"` to other rules or `AlterTableSpec` because `yacc` has to know whether to reduce the `AlterTableSpec` and moving forward to `AlterTablePartitionOpt`, or try to `"REMOVE" "TTL"`
2. Change the value of "TTL" config to `valueExpr`. Maybe we could modify it to `DefaultValueExpr` or other wider range grammar later, but supporing number / string literal is enough for today.
Tests …
> parser: use alter table remove ttl spec

- expression/builtin_time_vec.go
- expression/integration_test.go
Issue Number: close #39146
fix that str_to_date returns different result on no zero date sql mode
Tests 
Side effects
Documentation
```release-note
fix that str_to_date returns different result on no zero date sql mode.
```
> expression: fix that str_to_date returns different result on no zero date sql mode.

- executor/analyze.go
- executor/analyze_col_v2.go
- executor/analyze_global_stats.go
Issue Number: 
add debug log for analyze
```sql
mysql> CREATE TABLE t (a int, b int, index idx(b))
-> PARTITION BY RANGE ( a ) (
->   PARTITION p0 VALUES LESS THAN (6),
->   PARTITION p1 VALUES LESS THAN (11)
-> );
mysql> set @@tidb_build_stats_concurrency=1;
Query OK, 0 rows affected (0.00 sec)
mysql> analyze table t;
Query OK, 0 rows affected, 2 warnings (0.10 sec)
```
```txt
[2022/11/24 13:37:26.118 +08:00] [INFO] [analyze_col_v2.go:213] ["merge subCollector in concurrency in AnalyzeColumnsExecV2"] [tableID=87] [partitionID=88] [isPartitionTable=true] [oldRootCount=0] [newRootCount=1] [subCount=1] [subCollectorIndex=0]
[2022/11/24 13:37:26.118 +08:00] [INFO] [analyze_col_v2.go:205] ["merge …
```
> executor: add debug log for analyze

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref #33649
after #33649 is fixed, ristretto is released which contains our bugfix and it fixes some bug in arm64. it is useful for us.
Tests 
Side effects
Documentation
```release-note
None
```
> *: upgrade dgraph-io/ristretto

- ddl/index_cop.go
- ddl/index_cop_test.go
Issue Number: close #39308
The issue could be reproduced easily when the data set is large enough.
```diff
diff --git a/ddl/index.go b/ddl/index.go
index c3c3ffd37c..f5ed601d2b 100644
--- a/ddl/index.go
+++ b/ddl/index.go
@@ -1548,6 +1548,13 @@ func (w *addIndexWorker) BackfillDataInTxn(handleRange reorgBackfillTask) (taskC
} else { // The lightning environment is ready.
vars := w.sessCtx.GetSessionVars()
sCtx, writeBufs := vars.StmtCtx, vars.GetWriteStmtBufs()
+                               logutil.BgLogger().Info("write", zap.String("handle", idxRecord.handle.String()),
+                                       zap.String("idxVal", idxRecord.vals[0].GetString()),
+                                       zap.String("addr", fmt.Sprintf("%p", idxRecords)),
+ …
```
> ddl: don't reuse the chunk until underlying memory is not referenced

- DEPS.bzl
- br/pkg/streamhelper/basic_lib_for_test.go
- ddl/ddl.go
- domain/globalconfigsync/globalconfig_test.go
- executor/set_test.go
- go.mod
- go.sum
- kv/option.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
- sessionctx/variable/variable.go
- store/driver/txn/txn_driver.go
Issue Number: ref https://github.com/pingcap/tidb/issues/38587
```release-note
None
```
> variable: add `txn_source` into kv.context

- statistics/handle/update.go
- statistics/handle/update_test.go
Same as #39179
When we decide whether a table needs to be auto analzyzed, if the table has never been analyzed and there is no write to the table in the last minute, we trigger auto analyze for the table. The condition of no write in the last minute may prevent the table from auto analyze and the optimizer may choose wrong plans using pseudo stats. Hence the pr removes the condition. The condition of no write in the last minute was first introduced for the following case. When loading data, auto analyze v1 is triggered and preempts CPU and other resources with loading data. However, after auto analyze v2 is introduced, the resource consumption of analyze is reduced so it would not be a problem to trigger auto analyze when loading data.
Tests 
Side …
> statistics: remove 1min no write check for unanalyzed table in auto analyze

- executor/executor_issue_test.go
- types/time.go
Issue Number: close #35678
Tests 
Side effects
Documentation
```release-note
None
```
> types: handle io.EOF error when to parse datatime

- Makefile
- ddl/ddl.go
- ddl/index.go
- ddl/reorg.go
- meta/autoid/autoid_service.go
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: improve log messages

- tests/realtikvtest/statisticstest/BUILD.bazel
- tests/realtikvtest/statisticstest/main_test.go
Issue Number: close #39502
In fact, the old limit is useless. they are defined in the ```RunTestMain```.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix goleak in the statisticstest

- executor/distsql_test.go
Issue Number: close #39516 
Tests 
Side effects
Documentation
```release-note
None
```
> distsql_test: fix TestPartitionTableIndexLookUpReader

- ttl/cache/BUILD.bazel
- ttl/cache/main_test.go
- ttl/cache/table.go
- ttl/cache/table_test.go
- ttl/session/BUILD.bazel
- ttl/session/main_test.go
- ttl/session/session.go
- ttl/session/session_test.go
- ttl/sqlbuilder/BUILD.bazel
- ttl/sqlbuilder/main_test.go
- ttl/sqlbuilder/sql.go
- ttl/sqlbuilder/sql_test.go
Issue Number: close #39490
Split the util functions inside ttl into multiple standalone packages.
Just move the files, and change some headers. Nothing new.
Tests
> ttl: refractor ttl pkg into multiple sub packages

- executor/index_merge_reader.go
Issue Number: close #39514
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix data race on the IndexMergeReaderExecutor

- bindinfo/bind_test.go
- executor/bind.go
- executor/builder.go
- planner/core/planbuilder.go
Issue Number: ref #39199 
plan digest field should not be empty when create binding from existing plan
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fill plan digest when create binding from existing plan 

- ddl/concurrentddltest/BUILD.bazel
- executor/projection.go
- executor/seqtest/main_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: simple code for readProjection

- build/linter/allrevive/analyzer.go
- tools/check/revive.toml
it is found by https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check/detail/ghpr_check/6720/pipeline.
the revive which run by cli is old. so that we disable it to fix. It has been enabled in the bazel nogo.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix revive false positive with generics

- session/bootstrap_test.go
Issue Number: close  https://github.com/pingcap/tidb/issues/39682
mustExec only open the executor, but not close it. We need close the recordSet by manual.
Tests 
Side effects
Documentation
```release-note
None
```
> session: fix data race in TestBootstrap

- br/pkg/restore/client.go
- br/pkg/restore/client_test.go
- br/tests/br_full_cluster_restore/run.sh
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>
Issue Number: close #39692
Fix integration test cases with `--with-sys-table`.
Tests 
Side effects
Documentation
case 1:
- br backup full
- In restore cluster, execute `alter table mysql.user add column xx int;`
- br restore full
- success
case 2:
- In backup cluster, execute `alter table mysql.user add column xx int;`
- br backup full
- br restore full
- failed, `Error: missing column in cluster data, table: user, col: xx int(11): [BR:Restore:ErrRestoreIncompatibleSys]incompatible system table`
```release-note
None
```
> br: fix integration test cases with `--with-sys-table`

- ddl/index_cop.go
- table/tables/tables.go
- tests/realtikvtest/addindextest/integration_test.go
Issue Number: close #39723
I made the wrong assumption on the arguments of `TryGetHandleRestoredDataWrapper`. 
Actually, the `row []types.Datum` must have the length of all columns in a table.
- Refactor `TryGetHandleRestoredDataWrapper` and correct the usage.
- Add a recover function to prevent TiDB exiting directly on error.
- Add two integration tests.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix panic when add index on prefixed pk tables

- planner/core/binary_plan_test.go
Issue Number: close #39746
we should init logger first. next to init domain.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix data race in the TestLongBinaryPlan

- ddl/db_partition_test.go
Issue Number: close #39764
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: Stabilise TestAlterModifyColumnOnPartitionedTableFail, due to #38669

- ddl/concurrentddltest/BUILD.bazel
- executor/BUILD.bazel
- session/BUILD.bazel
- testkit/BUILD.bazel
- testkit/testkit.go
In Bazel, we will parallelly run multi test cases in different threads. if every golang in the thread use unlimited GOMAXPROCS, the test cases will be slow.
Tests 
Side effects
Documentation
```release-note
None
```
> testkit: set GOMAXPROCS in test

- ddl/index.go
- ddl/index_merge_tmp.go
- ddl/index_merge_tmp_test.go
- table/tables/index.go
Cherry-pick #39796.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: mark the writes from delete-only and drop them on merge (#39796)

- util/printer.go
- util/util.go
utils/utils: ioutil obsolete method upgrade & case pruning
Tests 
Side effects
Documentation
```release-note
None
```
> fix: update ioutil func&pruning case

- ddl/ttl.go
- domain/BUILD.bazel
- domain/domain.go
- ttl/cache/BUILD.bazel
- ttl/cache/infoschema.go
- ttl/cache/infoschema_test.go
- ttl/cache/table.go
- ttl/cache/ttlstatus.go
- ttl/session/session.go
- ttl/ttlworker/BUILD.bazel
- ttl/ttlworker/config.go
- ttl/ttlworker/del_test.go
- ttl/ttlworker/job.go
- ttl/ttlworker/job_manager.go
- ttl/ttlworker/job_manager_test.go
- ttl/ttlworker/job_test.go
- ttl/ttlworker/scan.go
- ttl/ttlworker/scan_test.go
- ttl/ttlworker/session.go
- ttl/ttlworker/session_test.go
- ttl/ttlworker/worker.go
Issue Number: close #39471
Implement a ttl job schedule framework. It reads information from the info schema and the `mysql.tidb_ttl_table_status`, gets the job to run and schedule them to a scan worker.
The implementation of variable settings, `scanWorker` and `delWorker` are left for future development.
For most parts, the job manager is split from the original demo: https://github.com/pingcap/tidb/pull/39320/files. It implements the following feature:
1. The most fundamental one. Let the job run on the worker. 
2. Support graceful shutdown with the context from domain.
3. Allow collecting the errors from the tasks, and storing them into the table when the job is finished.
4. Allow cancelling the running jobs.
This pr left a lot of TODO for system variables. They are …
> ttl: implement ttl job schedule framework

- br/pkg/storage/memstore_test.go
- executor/set_test.go
- parser/consistent_test.go
- parser/format/format_test.go
- parser/reserved_words_test.go
- planner/core/binary_plan_test.go
- server/plan_replayer.go
- server/plan_replayer_test.go
- statistics/handle/dump.go
- util/cpuprofile/cpuprofile_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> fix: update ioutil.readall

- executor/BUILD.bazel
- executor/ddl_test.go
- executor/show.go
- executor/showtest/show_test.go
Issue Number: close #39852
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: ouput TTL comment format when show create table

- ttl/ttlworker/job_manager.go
Issue Number: close #39890
Reschedule scan tasks after polling result from scan workers.
Reschedule scan tasks after polling result from scan workers, so it won't need to wait until the next schedule tick.
Tests
> ttl: reschedule scan tasks after update task state

- metrics/grafana/tidb.json
- ttl/cache/split_test.go
- ttl/cache/table.go
- ttl/sqlbuilder/sql.go
- ttl/sqlbuilder/sql_test.go
Issue Number: close #39895
TTL support more tables that can be split to scan. In this PR, if a table's primary key's first column is int or binary, it can be split.
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: TTL support split scan ranges for some primary key with more than one columns

- executor/slow_query_sql_test.go
- planner/core/binary_plan_test.go
Issue Number: close #39892
Please see the issue.
Please see the issue.
Tests 
Side effects
Documentation
```release-note
None
```
> executor, planner: `InitLogger` before `CreateMockStore` in tests to avoid data race

- ttl/session/session.go
- ttl/session/session_test.go
Issue Number: close #39917
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: fix ttl txn will not return error when rolling back

- executor/showtest/show_test.go
- expression/builtin.go
- expression/builtin_json.go
- expression/builtin_json_test.go
- expression/builtin_json_vec.go
- expression/integration_test.go
- types/json_binary.go
- types/json_binary_functions.go
Issue Number: ref https://github.com/pingcap/tidb/issues/39866
Tests 
```release-note
None
```
> expression: support `member of` function

- ttl/ttlworker/job.go
- ttl/ttlworker/job_manager.go
- ttl/ttlworker/job_test.go
Issue Number: close #39930
1. Some levels of the log decreased to `Info`, but not `Debug`.
2. Add more logs when the job is created and appended to the `runningJobs`.
3. Remove redundant removing of job (without log and cancel) in the `localJobs`.
4. Add more fields to the log, so that we'll know what's exactly happending in that situation.
Tests
> ttl: add log in the whole lifecycle of a job

- ttl/ttlworker/job_manager.go
Issue Number: close #39955
Initialize the `notifyStateCh` while initializing the job manager. It'll make the recycle of scan worker much faster.
Using a channel with bound 1 is good enough, as the scan worker will actually be blocked by `PollTaskResult`. If the manager didn't call `PollTaskResult`, it will not be scheduled anything.
> ttl: initialize notifyStateCh in ttl job manager

- ttl/ttlworker/session.go
Issue Number: close #39957
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: enable 1pc for ttl delete

- .bazelrc
- ddl/sequence_test.go
- executor/admin_test.go
- executor/autoidtest/autoid_test.go
- executor/executor_test.go
- executor/grant_test.go
- executor/seqtest/seq_executor_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> executor: close recordset again

- br/pkg/lightning/backend/kv/sql2kv.go
- ddl/ddl_api.go
- ddl/generated_column.go
- ddl/index.go
- ddl/partition.go
- expression/BUILD.bazel
- expression/builtin_cast.go
- expression/errors.go
- expression/expression.go
- expression/multi_valued_index_test.go
- expression/simple_rewriter.go
- parser/model/model.go
- parser/parser_test.go
- parser/types/field_type.go
- planner/core/expression_rewriter.go
- planner/core/planbuilder.go
- types/field_type_builder.go
Issue Number: close https://github.com/pingcap/tidb/issues/40045
Tests 
```release-note
None
```
> expression: introduce `cast(... as ... array)` in expression index

- executor/oomtest/oom_test.go
Issue Number: close #40054
it simply fixes it. but we should refactor it and add whitelists to filter useless logs.
Tests 
Side effects
Documentation
```release-note
None
```
> oomtest: add whitelist for oom test to fix flaky test

- ddl/backfilling.go
- ddl/export_test.go
- ddl/index_cop.go
- ddl/index_cop_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/40074
The cop-request senders use the same start TS to read table record. If the total read time exceed the GC life time, the error "GC life time is shorter than transaction duration" is reported.
This PR changes it to use a latest TS to read table record.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: use latest ts to read record for adding index

- ddl/index.go
- errors.toml
- expression/expression.go
- expression/multi_valued_index_test.go
- util/dbterror/ddl_terror.go
Issue Number: close https://github.com/pingcap/tidb/issues/40086
Tests 
```release-note
None
```
> ddl: check the limitation when creating multi-valued index 

- sessionctx/sessionstates/session_states_test.go
- util/sem/sem.go
- util/sem/sem_test.go
Issue Number: close #38238
When SEM is ON, we want to modify `tidb_allow_remove_auto_inc` without  the `RESTRICTED_VARIABLES_ADMIN` privilege.
Make `tidb_allow_remove_auto_inc` visible and modifiable when SEM is ON.
Tests 
> Setting `[security].enable-sem = true` in `config.toml` to enable SEM, and modify `tidb_allow_remove_auto_inc` successfully.
Side effects
Documentation
```release-note
None
```
> sysvar: allow modifying 'tidb_allow_remove_auto_inc' when SEM is ON

- ddl/db_partition_test.go
- ddl/fktest/foreign_key_test.go
- ddl/foreign_key.go
- errors.toml
- infoschema/error.go
Problem Summary: This PR do following things:
- Add test for the foreign key with temporary table.
- Add test for the foreign key with cache table.
- Add test for the foreign key with partition table.  As [MySQL doc](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html) said, foreign key is not support in partition table, TiDB ditto.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix issue of partition table with foreign key and add more test case

- parser/parser_test.go
- parser/types/field_type.go
Issue Number: close https://github.com/pingcap/tidb/issues/40130
Tests 
```release-note
None
```
> parser: fix cast function restore

- store/copr/coprocessor.go
Issue Number: close #40162
Don't reset concurrency of analyze req to 2.
Tests 
Before the PR:
After the PR:
Side effects
Documentation
```release-note
None
```
> store/copr: don't reset concurrency of analyze req to 2

- cmd/explaintest/r/explain_complex.result
- cmd/explaintest/t/explain_complex.test
Problem Summary: planner: fix an unstable explain test case 
planner: fix an unstable explain test case 
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix an unstable explain test case 

- executor/adapter.go
- executor/compiler.go
- executor/point_get_test.go
- planner/core/plan_cache_utils.go
- session/session.go
- sessiontxn/interface.go
- sessiontxn/isolation/optimistic.go
Issue Number: close #40194
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix PointGet will return an stale value when `tidb_enable_plan_replayer_capture` is set

- expression/builtin_compare.go
- expression/builtin_other.go
- planner/core/expression_rewriter.go
- planner/core/find_best_task.go
- planner/core/integration_test.go
- planner/core/optimizer.go
- planner/core/plan_cache.go
- sessionctx/stmtctx/stmtctx.go
- util/ranger/detacher.go
Problem Summary: planner: record reasons when skipping Plan Cache
No logical change, just refactoring.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: record reasons when skipping Plan Cache

- roadmap.md
**DO NOT MERGE** until v6.5 is released. 
n/a
Tests 
Side effects
Documentation
```release-note
None
```
> docs: update tidb roadmap based on v6.5

- expression/builtin_compare.go
- expression/util.go
- planner/core/expression_rewriter.go
- planner/core/plan_cache.go
- sessionctx/stmtctx/stmtctx.go
Problem Summary: planner: remove the unnecessary skip-plan-cache flag in StmtCtx
planner: remove the unnecessary skip-plan-cache flag in StmtCtx
Tests 
Side effects
Documentation
```release-note
None
```
> planner: remove the unnecessary skip-plan-cache flag in StmtCtx

- ttl/ttlworker/BUILD.bazel
- ttl/ttlworker/job.go
- ttl/ttlworker/job_integration_test.go
- ttl/ttlworker/job_test.go
Issue Number: close #40231 
The TTL always fails to update job status. It's actually not a big problem as ttl didn't depend on the status to schedule.
This problem is caused by a custom-defined type argument (even if the underlying type is a string) cannot be handled by the `escapeSQL`. The funny thing is that the initial 'waiting' is inlined in the SQL, so the job status could be 'waiting' :smiley: .
Convert the argument to string
Tests 
```release-note
Fix the issue that ttl job status will never be changed.
```
> ttl: fix change status sql argument

- executor/admin.go
- executor/builder.go
- expression/multi_valued_index_test.go
- planner/core/logical_plan_builder.go
- planner/core/plan_to_pb.go
- planner/core/plan_to_pb_test.go
- table/tables/index.go
- table/tables/mutation_checker.go
- table/tables/tables.go
- types/convert.go
- types/datum.go
- types/json_binary.go
- util/misc.go
- util/misc_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/40207
Tests 
```release-note
None
```
> executor: write multi-valued index

- expression/expr_to_pb_test.go
- expression/expression.go
- planner/core/integration_test.go
Issue Number: close [#5112](https://github.com/pingcap/tiflash/issues/5112)
Tests 
Side effects
Documentation
```release-note
expression: implement unhex function pushdown to tiflash
```
> expression: implement `unhex` function pushdown to tiflash

- expression/builtin_cast.go
Issue Number: close https://github.com/pingcap/tidb/issues/40276
Tests 
```release-note
None
```
> test: fix data race in cast as array

- domain/domain.go
- session/session.go
- session/session_test/session_test.go
- sessionctx/variable/mock_globalaccessor.go
- sessionctx/variable/mock_globalaccessor_test.go
- sessionctx/variable/variable.go
- sessionctx/variable/varsutil.go
Issue Number: close #40240
In https://github.com/pingcap/tidb/pull/39584, we invoke `SetGlobal` of variable A in the `Validation` of variable B. This brought a circular dependency in `rebuildSysVarCache`. We must modify something to break this circular.
Modify the declaration of `SetGlobalSysVarOnly`, add a parameter to break the circular.
Tests 
> (cd executor ; go test -v -run 'TestValidateSetVar|TestIssue28073') | grep '^[^[]'
Side effects
Documentation
```release-note
None
```
> sysvar: fix circular dependency in rebuildSysVarCache leading to deadlock

- server/server.go
- tidb-server/main.go
Issue Number: close #40038
When tidb-server recives SIGTERM, it doesn't exit until auto analyze is finished.
When tidb-server is gracefully shutting down, kill sys processes(including auto analyze). In this way, it can exit quickly.
Tests 
Set up a cluster and import tpcc data. When finding one tidb-server starts to auto analyze a large table(such as `order_line` or `stock`), kill the tidb-server. Before the PR, the tidb-server would not exit until auto analyze is finished. After the PR, auto analyze would be killed and the tidb-server can exit quickly.
Side effects
Documentation
```release-note …
```
> server, tidb-server: kill auto analyze when gracefully shutting down

- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
Issue Number: close #40225
Problem Summary: planner: better coordination between the ignore_plan_cache() binding and plan-cache
planner: better coordination between the ignore_plan_cache() binding and plan-cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: better coordination between the ignore_plan_cache() binding and plan-cache

- executor/partition_table_test.go
- planner/core/task.go
Issue Number: close #40273 
Open the partial order property push down for LIST partition
Tests 
Side effects
Documentation
```release-note
None
```
> planner: open the partial order prop push down for LIST PARTITION

- executor/partition_table_test.go
- planner/core/task.go
cherry-pick #40290 
-----------------------
close pingcap/tidb#40273
Tests 
Side effects
Documentation
```release-note
None
```
> planner: open the partial order prop push down for LIST PARTITION (#40290)

- planner/core/expression_rewriter.go
- planner/core/plan_cache_test.go
Issue Number: close #40224
Problem Summary: planner: skip plan-cache for prepared queries with `INT in (Decimals...)`
skip plan-cache for prepared queries with `INT in (Decimals...)`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: skip plan-cache for prepared queries with `INT in (Decimals...)`

- domain/historical_stats.go
- executor/analyze.go
- executor/analyze_global_stats.go
- executor/analyze_worker.go
- executor/historical_stats_test.go
- statistics/handle/dump.go
- statistics/handle/handle.go
- statistics/handle/handle_test.go
support historical stats dump partition table
Tests 
```release-note
None
```
> statistics: support historical stats dump partition table

- expression/BUILD.bazel
Unit tests in the expression always are timeout so we need to enlarge timeout for test.
Tests 
Side effects
Documentation
```release-note
None
```
> expression: enlarge timeout for test

- Makefile
- domain/BUILD.bazel
- domain/sysvar_cache.go
- executor/autoidtest/BUILD.bazel
- go.mod
- go.sum
- server/BUILD.bazel
- server/server.go
- server/tidb_library_test.go
- session/BUILD.bazel
- session/session.go
- util/syncutil/BUILD.bazel
- util/syncutil/mutex_deadlock.go
- util/syncutil/mutex_sync.go
Issue Number: close #40293
Tests 
We can find this log in the CI. It has been fixed in the https://github.com/pingcap/tidb/issues/40240
```
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 273418 lock 0xc005e863b0
domain/sysvar_cache.go:121 domain.(*Domain).rebuildSysVarCache ??? <<<<<
domain/sysvar_cache.go:51 domain.(*Domain).rebuildSysVarCacheIfNeeded ???
domain/sysvar_cache.go:75 domain.(*Domain).GetGlobalVar ???
domain/domain.go:1541 domain.(*Domain).globalBindHandleWorkerLoop.func1 ???
Have been trying to lock it again for more than 20s
goroutine 261135 lock 0xc005e863b0
domain/sysvar_cache.go:121 domain.(*Domain).rebuildSysVarCache ??? <<<<<
domain/domain.go:2199 …
```
> util: use go-deadlock to find deadlock

- ttl/ttlworker/job_manager.go
- ttl/ttlworker/job_manager_integration_test.go
- ttl/ttlworker/job_manager_test.go
Issue Number: close #40335
Don't try to schedule anything if the `EnableTTLJob` is false.
Tests 
```release-note
Fix the issue that the ttl job keeps scheduling even when `tidb_ttl_job_enable` is set to 'OFF'
```
> ttl: don't schedule ttl job when EnableTTLJob is off

- executor/analyzetest/analyze_test.go
- planner/core/collect_column_stats_usage_test.go
- planner/core/integration_partition_test.go
- planner/core/logical_plan_builder.go
- statistics/handle/handle.go
Issue Number: close #40368
fix panic during starting tidb-server if creating global binding for partition table
Tests 
```sql
create table t1(a int, b int, key (a)) partition by range (a) (partition p0 values less than (10), partition p1 values less than (20));
create global binding for select * from t1 using select * from t1 use index (a);
show global bindings;
```
restart the tidb-server and make sure it restart successfully
```release-note
None
```
> planner: fix panic during starting tidb-server if creating global binding for partition table

- executor/analyzetest/analyze_test.go
- planner/core/collect_column_stats_usage_test.go
- planner/core/integration_partition_test.go
- planner/core/logical_plan_builder.go
- statistics/handle/handle.go
cherry pick 4a8006c 
Tests 
Side effects
Documentation
```release-note
None
```
> planner: cherry pick 4a8006c 

- planner/core/integration_test.go
- planner/core/logical_plan_builder.go
- planner/core/plan_cost_ver2_test.go
Issue Number: close #40285
Add a nil check.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add nil check when handling empty charset in `setUnionFlen`

- executor/set_test.go
- planner/core/plan_cacheable_checker.go
- planner/core/prepare_test.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: ref #33031
Enable plan cache when tidb_partition_prune_mode = dynamic
Adding a new system variable (both global and session) tidb_enable_plan_cache_with_dynamic_prune_mode = <on|off>
to allow testing even when https://github.com/pingcap/tidb/issues/33031 is not fixed.
Tests 
Side effects
Documentation
```release-note
None
```
> *: Adding tidb_enable_plan_cache_with_dynamic_prune_mode

- parser/ast/dml.go
- server/driver_tidb.go
- server/driver_tidb_test.go
- session/nontransactional.go
- session/nontransactional_test.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Signed-off-by: you06 <you1474600@gmail.com>
This PR generally made three changes:
- Add global/variable `tidb_etl_concurrency` and `tidb_etl_batch_size`.
- Rewrite `insert into ... select ...` stmts into nt-txn forms.
- Accelerate insert speed by concurrent execution of nt-txn jobs. 
The rewrite is only enabled for valid stmts when `tidb_etl_concurrency > 0`.
Tests 
Side effects
Documentation
```release-note
None
```
> nt-txn: support complex aliased join and concurrency runner |tidb-test=release-6.5

- br/pkg/restore/BUILD.bazel
- br/pkg/restore/systable_restore.go
- br/pkg/restore/systable_restore_test.go
- br/pkg/task/restore.go
- br/pkg/task/restore_data.go
Issue Number: close https://github.com/pingcap/tidb/issues/40418
1. For ebs volume-snapshot restore, we need to reset some accounts otherwise db_initializer will fail due to accounts existing.
1. add a new config `reset-sys-users`. in case we need to reset more users in future.
2. remove cloud_admin by default
3. reset the root password and let cloud_admin control it.
Tests 
Side effects
Documentation
```release-note
None
```
> br: reset cloud_admin and root after ebs restoration (#39986)

- br/pkg/restore/client.go
- br/pkg/restore/tiflashrec/tiflash_recorder.go
- br/pkg/restore/tiflashrec/tiflash_recorder_test.go
- br/pkg/task/restore_data.go
Issue Number: close https://github.com/pingcap/tidb/issues/40208
Problem Summary: resettle tiflash replica after ebs restoration. This PR associate with https://github.com/pingcap/tidb-operator/pull/4812.
Tests 
Side effects
Documentation
```release-note
None
```
> br: support reset_tiflash after ebs restoration (#40124)

- planner/core/encode.go
- planner/core/plan_test.go
Issue Number: ref #35687
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix the children of `ShuffleReceiver` not displayed in execution plan in stmt summary and slow query

- bindinfo/BUILD.bazel
- bindinfo/session_handle_test.go
- parser/ast/misc.go
- planner/optimize.go
set var hint is invalid when create binding
Issue Number: close #40570
1. After finding the binding sql, you also need to update the value of the session var
2. Only session vars with ```IsHintUpdatable:true``` set can be updated
3. When obtaining session var, you cannot directly read attributes, you need to use the function ```GetSessionFromHook```
Tests 
Side effects
Documentation
```release-note
None
```
> hint: fix the problem that set var hint is invalid when create binding

- planner/core/plan_cost_ver2.go
- planner/core/plan_cost_ver2_test.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #40556
Problem Summary: planner: introduce a new variable to adjust the penalty double read cost of IndexJoin
IndexJoin can cause plenty of extra double-read tasks, which consume lots of resources and take a long time.
Since the number of double-read tasks is hard to be estimated accurately, we introduce a new variable to let us have the ability to adjust this part of the cost manually.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce a new variable to adjust the penalty double read cost of IndexJoin

- executor/analyze.go
- executor/analyze_test.go
- executor/set_test.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
- statistics/handle/handle.go
- statistics/handle/handle_test.go
- statistics/handle/update.go
- util/sqlexec/restricted_sql_executor.go
Cherry pick #36588 and #35232 to release-6.1
Introduce `tidb_enable_analyze_snapshot` and its defalut value is false. When `tidb_enable_analyze_snapshot` is false, analyze use MaxUint64 ts so it reads the latest data, and it directly update count when saving stats to storage. The PR can solve #36552 and #29862.
Tests 
Side effects
Documentation
```release-note
None
```
> *: analyze use MaxUint64 ts to read data and directly update count

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #40461
Region cache may have memory leak if a lot of data is deleted and the adjacent regions are not touched at all. See #40461 for detail.
Add a background goroutine to clean stale region cache.
Tests 
Side effects
```release-note
Clear stale region info actively in the background to reduce memory footprint and avoid memory leak.
```
> *: update client-go

- executor/executor_test.go
- planner/core/encode.go
Issue Number: close #40206
A `TestKit` contains one `Session`, so we can't concurrently use a `TestKit` to execute SQLs.
- Use another `TestKit` to concurrently run SQLs in `TestAdmin`
- Add a nil check in `NormalizeFlatPlan`
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix concurrent use of `testkit` in tests and add nil check

- resourcemanager/BUILD.bazel
- resourcemanager/rm.go
- testkit/BUILD.bazel
- testkit/mockstore.go
Tests 
Side effects
Documentation
```release-note
None
```
> testkit: reset the resource manager after test finishes

- executor/main_test.go
- go.mod
- go.sum
To fix:
- https://github.com/pingcap/tidb/issues/37141
- https://github.com/pingcap/tidb/issues/40461
Update client-go to include https://github.com/tikv/client-go/commit/b16bdd64ac090dc500cd6e72eb9f3a6d88b8088c and https://github.com/tikv/client-go/commit/b670f6c3eb65996991ca7029151b0fd306dfc6fb
Tests 
Side effects
```release-note
Clear stale region cache actively in the background.
```
> *: update client-go to latest tidb-5.4 (cherry-pick)

- planner/core/find_best_task.go
- planner/core/indexmerge_path.go
- planner/core/indexmerge_path_test.go
- planner/core/optimizer.go
- planner/core/physical_plans.go
- planner/core/plan_cache.go
- planner/core/task.go
- planner/util/path.go
Problem Summary: planner: disable plan-cache for plans with IndexMerge accessing Multi-Valued Index
planner: disable plan-cache for plans with IndexMerge accessing Multi-Valued Index
Tests 
Side effects
Documentation
```release-note
None
```
> planner: disable plan-cache for plans with IndexMerge accessing Multi-Valued Index

- ddl/fktest/foreign_key_test.go
- executor/fktest/foreign_key_test.go
Issue Number: close #40649
Tests 
Side effects
Documentation
```release-note
None
```
> test: add more foreign key test

- ddl/resource_group_test.go
- executor/builder.go
- executor/infoschema_reader.go
- executor/show.go
- executor/simple.go
- executor/simple_test.go
- infoschema/infoschema_test.go
- infoschema/tables.go
- parser/ast/dml.go
- parser/parser.y
- planner/core/logical_plans.go
- planner/core/planbuilder.go
- privilege/privileges/privileges_test.go
- session/session.go
Issue Number: Close #39781
1.  A new mem table information_schema.resource_groups
2. Support to `show create resource group` command
3. Fix problem of binding user to non existent resource group
Tests 
```release-note
None
```
> *: add a new I_S table and support show create for resource groups

- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/36598
Reverts pingcap/tidb#40651
This PR can cause some CI failures, so revert it temporarily, and I'll submit another PR after.
```release-note
None
```
> Revert "planner: show un-cacheable reasons for execute statements"

- resourcemanager/pooltask/task_manager.go
- util/gpool/spmc/spmcpool_test.go
Issue Number: close #40700
Tests 
Side effects
Documentation
```release-note
None
```
> resourcemanager: avoid to get nil after task finished when to stop task

- DEPS.bzl
- errno/errcode.go
- errno/errname.go
- expression/builtin_op.go
- expression/builtin_op_test.go
- expression/errors.go
- go.mod
- go.sum
Issue Number: close #40683
Implement a new json unary not. Currently it's implemented through casting to double and run unary not on the double. However, the compatible implementation should be comparing the json with zero json.
Related TiKV implementation: https://github.com/tikv/tikv/pull/14070
Tests 
```release-note
Fix the issue that unary not json is not compatible with MySQL
```
> json, expression: add json unary not implementation

- store/gcworker/gc_worker.go
cherry-pick https://github.com/pingcap/tidb/pull/40760
Issue Number: ref pingcap/tidb#40759
Tests 
Side effects
Documentation
```release-note
None
```
> br: do not resolve locks frequently when log-backup task do not exist

- planner/core/find_best_task.go
- planner/core/indexmerge_path_test.go
- planner/core/point_get_plan.go
Problem Summary: planner: forbid the optimizer to generate point-plan upon MVIndexes
planner: forbid the optimizer to generate point-plan upon MVIndexes
Tests 
Side effects
Documentation
```release-note
None
```
> planner: forbid the optimizer to generate point-plan upon MVIndexes

- planner/core/indexmerge_path.go
planner: refactor some code related to IndexMerge and MVIndex
Tests 
Side effects
Documentation
```release-note
None
```
> planner: refactor some code related to IndexMerge and MVIndex

- ttl/ttlworker/job_manager_integration_test.go
Issue Number: close #40811
The test `TriggerScanTask` uses the default ttl job manager in dom. However, the original manager in dom may have started, and call the `resizeWorkersWithSysVar` concurrently, which is not supported. Calling `resizeWorkersWithSysVar` is necessary to make sure the message is not lost in this test.
Construct a new manager, and start manually after resizing the workers.
Tests
> ttl: use a standalone manager in TriggerScanTask test

- resourcemanager/pooltask/BUILD.bazel
- resourcemanager/pooltask/task_manager.go
- resourcemanager/pooltask/task_manager_iterator.go
- resourcemanager/pooltask/task_manager_scheduler.go
- resourcemanager/rm.go
- resourcemanager/schedule.go
- resourcemanager/scheduler/cpu_scheduler.go
- resourcemanager/scheduler/scheduler.go
- resourcemanager/util/util.go
- util/gpool/spmc/spmcpool.go
- util/gpool/spmc/spmcpool_test.go
- util/gpool/spmc/worker.go
Issue Number: close #40719
Now, we can control the concurrency of the pool. But we need to wait for the subtask to finish when we need to downclock the pool, then we can exit the worker in the pool. if we want to overclock the pool, we need to create a subtask for adding concurrency to the task. so we have the ability to control the subtask to make itself exiting or creating.
Tests 
```release-note
None
```
> resourcemanager: scheduler subtask in the pool's task

- planner/core/indexmerge_path_test.go
- planner/core/planbuilder.go
Problem Summary: planner: show warnings when analyzing multi-valued indexes
planner: show warnings when analyzing multi-valued indexes
Tests 
Side effects
Documentation
```release-note
None
```
> planner: show warnings when analyzing multi-valued indexes

- metrics/grafana/tidb_runtime.json
Signed-off-by: TonsnakeLin <lpbgytong@163.com>
Issue Number: close #40835
We have added many detail metrics for TiDB, TiKV and some related modules to diagnose slow queries and long tail statements, but we lack the metric of go runtime such as goroutine schedule latency.
This PR adds goroutine schedule latency to  grafana panel which helps to diagnose long tail statements.
Tests 
Side effects
Documentation
```release-note
None
```
> metrics: add goroutine schedule latency to grafana panel 

- planner/core/indexmerge_path_test.go
Problem Summary: planner: add more test cases for MVIndex
planner: add more test cases for MVIndex
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for MVIndex

- ddl/cluster.go
Issue Number: close #40861 
Problem Summary: The attribute related info is stored in PD which doesn't have MVCC.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: unsupport flashback cluster cross `alter table attributes`

- domain/domain.go
- util/gctuner/tuner.go
Signed-off-by: TonsnakeLin <lpbgytong@163.com>
Issue Number: close #40849
See the issue #40849.
tidb-server doesn't call `runtime.ReadMemStats` when GOGC tuner is disabled.
Tests 
Side effects
Documentation
```release-note
None
```
> Variables: enhance tidb_enable_gc_tuner

- executor/builder.go
- executor/partition_table_test.go
Issue Number: close #40803
Tests 
Side effects
Documentation
```release-note
None
```
> executor: backport of #40674

- metrics/grafana/tidb.json
- metrics/metrics.go
- metrics/ttl.go
- ttl/metrics/metrics.go
- ttl/ttlworker/BUILD.bazel
- ttl/ttlworker/job_manager.go
- ttl/ttlworker/job_manager_integration_test.go
- ttl/ttlworker/job_manager_test.go
- ttl/ttlworker/task_manager.go
- ttl/ttlworker/task_manager_integration_test.go
- ttl/ttlworker/task_manager_test.go
Issue Number: close #40810
Add a metric to track the owned task with different task status.
Tests
> ttl: add metrics for task manager

- br/pkg/utils/json.go
- br/pkg/utils/json_test.go
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>
Issue Number: close #40878
The goroutinue will panic when executing `br debug encode`.
New `backuppb.Schema` to avoid nil pointer dereference
Tests 
Side effects
Documentation
- br backup full
- br debug decode
- br debug encode
- success
```release-note
Fixed a bug that caused: execute br debug encode panic.
```
> br: fix br debug encode panic

- planner/core/indexmerge_path.go
- planner/core/indexmerge_path_test.go
- planner/core/testdata/index_merge_suite_in.json
- planner/core/testdata/index_merge_suite_out.json
Problem Summary: planner: forbid using IndexFullScan on multi-valued indexes
Using IndexFullScan on multi-valued indexes may not see all rows.
```
create table t(j json, index kj((cast(j as signed array))));
insert into t values ('[]');
```
For example, the row above is invisible to `IndexFullScan(kj)` since the `j` in this row has no element and then `kj` has no record of this row.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: forbid using IndexFullScan on multi-valued indexes

- ttl/cache/task.go
- ttl/ttlworker/task_manager_integration_test.go
- ttl/ttlworker/task_manager_test.go
Issue Number: close #40918
Don't fetch ttl scan tasks, if the task has finished. 
Tests 
```release-note
Fix the issue that a ttl scan task will be restarted by other nodes.
```
> ttl: don't fetch ttl scan task after it finished

- executor/index_merge_reader.go
- executor/index_merge_reader_test.go
Issue Number: close #40877
Let both `pickAndExecTask` and `handlePickAndExecTaskPanic` take the address of `task` as its argument, so once `*task` is assigned in `pickAndExecTask`,  `handlePickAndExecTaskPanic` will get a non nil value.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: Fix tidb crash on index merge reader

- Makefile
- ddl/BUILD.bazel
- ddl/sanity_check.go
- kv/BUILD.bazel
- kv/txn.go
- resourcemanager/util/BUILD.bazel
- resourcemanager/util/shard_pool_map.go
- resourcemanager/util/shard_pool_map_test.go
- server/BUILD.bazel
- server/mock_conn.go
- session/BUILD.bazel
- session/bootstrap.go
- session/session.go
- testkit/BUILD.bazel
- testkit/testkit.go
- tools/check/ut.go
- util/intest/BUILD.bazel
- util/intest/common.go
- util/intest/intest.go
Issue Number: close #40929
- add ```intest``` build tags when running test.
- add ```intest``` into bazel and ut tools for helping the developers to config.
Tests 
Side effects
Documentation
```release-note
None
```
> util: add InTest to check whether to be in test

- executor/index_merge_reader.go
- executor/index_merge_reader_test.go
close pingcap/tidb#40877
Tests 
Side effects
Documentation
```release-note
None
```
> executor: Fix tidb crash on index merge reader (#40904)

- ddl/indexmergetest/BUILD.bazel
- ddl/indexmergetest/merge_test.go
Issue Number: close #40939
We should not run `testkit.MustExec()` concurently.
Tests 
Side effects
Documentation
```release-note
None
```
> test: stabilize TestAddIndexMergeConflictWithPessimistic

- util/chunk/alloc.go
Issue Number: close https://github.com/pingcap/tidb/issues/40987
Unlink the reference to the chunk for freeColumns.allocColumns and freeColumns.freeColumns. 
Tests 
Side effects
Documentation
```release-note
Fix the potential memory leak when enable tidb_enable_reuse_chunk.
```
> util: fix memory leak in chunk allocator

- domain/domain.go
Issue Number: close #40944
Fix the data race to read and initialize the TTL job manager.
Use the atomic pointer to store the TTL job manager.
Tests
> ttl: fix data race in TTL manager and test

- meta/meta.go
- session/bootstrap_test.go
- session/session.go
- session/session_test.go
Issue Number: close #40980
Tests 
Side effects
Documentation
```release-note
None
```
> session: use `mDDLTableVersion` key to control backfill tables

- planner/core/indexmerge_path.go
- planner/core/indexmerge_path_test.go
Problem Summary: planner: planner: not allow the optimizer to use `json_contains(j, '[]')` as access conditions on MVIndex
On the current MVIndex Implementation, if the optimizer meets `json_contains(j, '[]')`, it'll generate a TableDual plan since the JSON array is empty, and then it'll return an empty result.
But actually, `json_contains(j, '[]')` is always `true`, so all rows should be returned instead of an empty result.
```
mysql> select json_contains('[1]', '[]');
+----------------------------+
| json_contains('[1]', '[]') |
+----------------------------+
|                          1 |
+----------------------------+
1 row in set (0.01 sec)
```
To solve this issue, we don't allow the optimizer to use `json_contains` with an empty array as an argument as an …
> planner: not allow the optimizer to use `json_contains(j, '[]')` as access conditions on MVIndex

- ddl/ingest/disk_root.go
Issue Number: close #40970
Add mutex to prevent concurrent access to disk root.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl/ingest: add mutex to disk root

- ttl/cache/task.go
- ttl/ttlworker/job_manager_integration_test.go
- ttl/ttlworker/task_manager.go
- ttl/ttlworker/task_manager_integration_test.go
Issue Number: close #41019
Add a retry limit to the schedule logic.
Tests
> ttl: avoid endless loop in TTL task schedule

- resourcemanager/pooltask/BUILD.bazel
- resourcemanager/pooltask/task.go
- util/gpool/spmc/BUILD.bazel
- util/gpool/spmc/option.go
- util/gpool/spmc/spmcpool.go
- util/gpool/spmc/spmcpool_test.go
Issue Number: close #41015
Tests 
Side effects
Documentation
```release-note
None
```
> resourcemanager: fix TaskController.Stop() can't make producer exit in spmcpool 

- executor/seqtest/seq_executor_test.go
- statistics/handle/handle_test.go
- statistics/handle/update_test.go
- statistics/integration_test.go
- statistics/table.go
When deciding whether to trigger auto analyze or whether stats is outdated, we use `modify_count / histogram_count`. However, when calculating stats healthy, we use `modify_count / realtime_count`. The PR changes the stats healthy formula from `(1 - modify_count / realtime_count) * 100` to `(1 - modify_count / histogram_count) * 100`. In this way, stats healthy is aligned with the threshold of auto analyze and outdated stats.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: use histogram count rather than realtime count to calculate stats healthy

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/localhelper.go
- br/tests/lightning_local_backend/data/cpeng.a-schema.sql
- br/tests/lightning_local_backend/data/cpeng.a.1.sql
- br/tests/lightning_local_backend/data/cpeng.a.2.sql
- br/tests/lightning_local_backend/data/cpeng.a.3.sql
- br/tests/lightning_local_backend/run.sh
- kv/key.go
manually cherry-pick #40959 
Issue Number: close #40934
Avoid to let CommonHandle++ and decode it because the result may not be a valid value. The string datum encoding will not be ended with 0xff and we may increase 0xfe to 0xff.
https://github.com/pingcap/tidb/blob/151cd7ed605c934aa8fed6907762130147caed4d/util/codec/bytes.go#L35-L49
Tests 
Run the changed tests and failpoints will trigger this panic. And after the fix it is avoided.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x34e93e5]
goroutine 436 [running]:
github.com/pingcap/tidb/br/pkg/lightning/backend/local.nextKey({0xc000874f18, 0x0?, 0x119?})
/home/lance/Projects/tidb/br/pkg/lightning/backend/local/local.go:2069 +0x85 …
```
> lightning: fix panic when nextKey twice (#40959)

- br/pkg/restore/data.go
- br/pkg/utils/backoff.go
close pingcap/tidb#41058
Issue Number: close #41058 
when backup cluster is empty and there is only one region, BR assigned a leader and then do prepare a flashback immediately.
prepare flashback failed when a region was created without a leader.
region heartbeat sent may have some delay (10s), during the prepare flashback, the leader may not be sent heartbeat yet.
add retry for prepare flashback for specific errors.
Tests 
step as issue description #41058 
Side effects
Documentation
```release-note
None
```
> br: add retry for prepare flashback for backup cluster is empty and there are only one region (#41059)

- DEPS.bzl
- ddl/attributes_sql_test.go
- ddl/ddl.go
- ddl/ddl_api.go
- ddl/main_test.go
- ddl/resource_group.go
- ddl/resource_group_test.go
- ddl/schematracker/checker.go
- ddl/schematracker/dm_tracker.go
- domain/db_test.go
- domain/domain.go
- domain/infosync/BUILD.bazel
- domain/infosync/info.go
- domain/infosync/info_test.go
- domain/infosync/resource_group_manager.go
- executor/ddl.go
- executor/infoschema_reader.go
- go.mod
- go.sum
- meta/meta.go
- meta/meta_test.go
- server/stat_test.go
- store/mockstore/unistore/pd.go
Issue Number: ref #38825.
- Update client-go to make sure https://github.com/tikv/client-go/pull/691 take effect.
- Use the latest independent resource group manager client.
Tests 
Before:
After:
```release-note
None
```
> *: use the latest independent resource group manager client

- store/copr/batch_coprocessor.go
Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #41102
Problem Summary:Add log when build cop task takes too long, just like https://github.com/pingcap/tidb/blob/master/store/copr/batch_coprocessor.go#L814
We have following logs:
```
[2023/02/07 11:20:38.812 +08:00] [DEBUG] [batch_coprocessor.go:1304] ["detailed info buildBatchCopTasksConsistentHash"] [taskMap="{\"10.71.221.179:39809\":\"addr: 10.71.221.179:39809; regionInfos: [{{107 2 50} id:107 start_key:\\\"t\\\\200\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000U_r\\\" end_key:\\\"t\\\\200\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000V\\\" region_epoch:\\u003cconf_ver:2 version:50 \\u003e peers:\\u003cid:108 store_id:1 \\u003e peers:\\u003cid:116 store_id:104 role:Learner \\u003e …
```
> store/copr: add log for buildBatchCopTasksConsistentHash

- ddl/reorg.go
- parser/model/ddl.go
Issue Number: close #40751
Problem Summary: See #40751.
Lock the job's mutex before setting warnings. 
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix data race on job.SetWarnings

- Makefile
- sessiontxn/BUILD.bazel
Tests 
Side effects
Documentation
```release-note
None
```
> *: remove limit

- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/lightning.go
- br/pkg/lightning/restore/table_restore.go
- br/tests/br_views_and_sequences/run.sh
- br/tests/lightning_checkpoint_chunks/run.sh
Issue Number: close #41235
exit the function after check goroutine if finished by wg.Done()
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix panic when user cancel

- planner/core/optimizer.go
Signed-off-by: Zhigao Tong <tongzhigao@pingcap.com>
Issue Number: ref #40123
- In most x86-64 platforms, `Thread(s) per core` is 2
- ARM cpus don't implement Hyper-threading. `Thread(s) per core` is 1
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix calculating TiFlash stream count

- ddl/index.go
- ddl/serial_test.go
- errno/errname.go
- errors.toml
- parser/mysql/errname.go
Prefix indexes are specified in characters while this error message returns a limit in bytes. By adding the byte length in the message this is makes it easier to understand. Note that a limit of 3072 bytes means a limit of 768 characters for UTF-8 (768×4=3072).
This would deviate a little bit from the message in MySQL.
Before:
```
sql> CREATE TABLE t1(id int primary key, c1 text, key(c1(1000)));
ERROR: 1071 (42000): Specified key was too long; max key length is 3072 bytes
```
After:
```
sql> CREATE TABLE t1(id int primary key, c1 text, key(c1(1000)));
ERROR: 1071 (42000): Specified key was too long (4000 bytes); max key length is 3072 bytes
```
Issue Number: close #41272 
Tests 
Side effects
Documentation …
> ddl: Improve ErrTooLongKey message

- executor/hash_table.go
Issue Number: close https://github.com/pingcap/tidb/issues/41263
Fix the regression caused by https://github.com/pingcap/tidb/pull/41081
Tests 
```
Before PR 41081:
BenchmarkHashJoinExec
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0_1],_disk:false)
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0_1],_disk:false)-32         	       2	 638092875 ns/op
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0],_disk:false)
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0],_disk:false)-32           	      16	  64674572 ns/op
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5) …
```
> executor: fix unreasonable CPU time in HashJoin probe phash

- domain/plan_replayer.go
- executor/builder.go
- executor/executor_test.go
- executor/plan_replayer.go
- parser/ast/misc.go
- parser/parser.y
- parser/parser_test.go
- planner/core/common_plans.go
- planner/core/planbuilder.go
- privilege/privileges/privileges.go
- util/misc.go
Issue Number: close https://github.com/pingcap/tidb/issues/41262
1. support `plan replayer capture remove "sql_digest" "plan_digest" ` to remove task
2. let plan replayer related table can be visited under sem mode
Tests 
```release-note
None
```
> executor: support plan replayer capture remove task

- br/pkg/backup/client.go
Signed-off-by: Leavrth <jianjun.liao@outlook.com>
Issue Number: ref #40404 #40898 
1. We need to use `autoIDAccess.SequenceValue().Get()` instead of `autoIDAccess.SequenceCycle().Get()`.
refer to 
https://github.com/pingcap/tidb/blob/48bc046fe1a92c5861ae11584f5a131debc471ff/meta/autoid/autoid.go#L1162-L1175
2. fix condition when fetch replica label
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix backup ci

- tablecodec/BUILD.bazel
- tablecodec/tablecodec.go
- tablecodec/tablecodec_test.go
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
Issue Number: close #41300
The original decode process checks if the key is API v2 first, which will always fail while the user is using API V1. This will cause the code will read the stack every time it decodes the key, which is CPU/MEM expensive.
This pull request checks if the key is API V1 first, if it's not, then try API v2 decoding.
Tests 
Side effects
Documentation
```release-note
*: reduce the allocation of error constructing in `DecodeTableID`
```
> *: reduce the allocation of error constructing in `DecodeTableID`

- util/codec/codec.go
This fixes a dropped `err` in the `util/codec` package.
```release-note
None
```
> util: fix dropped error

- executor/simple.go
- metrics/grafana/tidb.json
- metrics/session.go
- session/session.go
- session/tidb.go
- store/driver/txn/txn_driver.go
Issue Number: ref #41203 
```
Separate the internal and external transaction types in metrics, this is the tidb related part.
```
Usually, to diagnose user issues the user transaction metrics are considered, they are displayed together with the internal ones and sometimes it's misleading and confusing.
After executing a few user transactions by hand.
Before
After
Tests 
Side effects
Documentation
```release-note
None
```
> metric: seperate the internal and external transaction metrics

- domain/BUILD.bazel
- domain/domain.go
Issue Number: close #41288
Tests 
Side effects
Documentation
```release-note
None
```
> domain: fix data race in the ttlJobManager

- util/stmtsummary/v2/stmtsummary.go
- util/stmtsummary/v2/stmtsummary_test.go
Signed-off-by: mornyx <mornyx.z@gmail.com>
Issue Number: close #41275 
Fix data race in `stmtsummary_test.go`.
Tests
Side effects
Documentation
```release-note
None
```
> stmtsummary: fix data race in test

- ddl/ddl_tiflash_api.go
- ddl/tiflashtest/BUILD.bazel
Issue Number: close #39949
In the test, the server cannot start up because the port is occupied. Although the port is random. so we need to quickly return when to fail to get tiflash sync.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: return panic when to get tiflash sync progress failed in test

- executor/infoschema_reader.go
- executor/infoschema_reader_test.go
Issue Number: close #40931 
Code not updated for multi-columns RANGE COLUMNS partitioning
Added all columns to the output.
Tests 
Side effects
Documentation
```release-note
None
```
> infoschema: fix is.partitions.partition_expression for range columns

- executor/index_advise_test.go
- planner/core/exhaust_physical_plans.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: ref #40505 
introduce variable tidb_enable_inl_join_inner_multi_pattern
Tests 
```release-note
None
```
> sysvar: introduce variable tidb_enable_inl_join_inner_multi_pattern

- executor/hash_table.go
Fix the logic error in https://github.com/pingcap/tidb/pull/41265
Tests 
Can kill the SQL in 1min
```
mysql> desc analyze  select * from sbtest2, sbtest3, sbtest4,sbtest5;
ERROR 1105 (HY000): probeWorker[4] meets error: Out Of Memory Quota![conn_id=897098134172205459]
```
Side effects
Documentation
```release-note
None
```
> executore: fix logic error in HashJoin probe

- br/pkg/restore/import.go
Signed-off-by: hillium <yujuncen@pingcap.com>
Issue Number: close #41328
There are too many tiny files while doing log restore, however the import API is stateless, hence we must create one TLS connection for each download, which has poor performance. 
This PR added cache for log restore. It have reused the cache functionality of full restore.
Tests 
```release-note
Now, PITR uses less CPU.
```
> log-backup: added cache for sst_importer client

- server/conn_stmt.go
- server/conn_test.go
Issue Number: close #41156 
The `text` of the execute stmt constructed in the `ExecuteCommand` is not initialized. This PR initializes it to the prepared statement text. This behavior is consistent with the MySQL.
Initialize the `text` for `ExecuteCommand`.
Tests 
```release-note
Fix the issue that `execute` statement is not shown in the info of `show processlist`.
```
> server, execute: set text for execute command

- br/pkg/restore/batcher_test.go
Issue Number: close #41210 
When `Batcher.Len` reaches the threshold, it will call `asyncSend`, then call `Send` in `sendWorker`, and then call `RestoreBatch` to append `*ranges.RewriteRules` to `sender.rewriteRules`, the whole process may not be completed within 10ms, forming a flaky test(`require.True(t, sender.HasRewriteRuleOfKey("a"))` should be true, but false), so we need to increase the sleep time in the `waitForSend` function.
Note: `waitForSend` is only used for test.
Tests 
Side effects
Documentation
```release-note
None
```
> br: increase the sleep time in the `waitForSend` function

- util/cgroup/cgroup_cpu.go
- util/cgroup/cgroup_cpu_test.go
Issue Number: close #39786
If you are in the linux 3.x, Your cgroup path is different from the latest version.
the path of CPU cgroup is ```cpu,cpuacct```. But the old is ```cpuacct,cpu```. it just is a small problem. But it has a more serious problem. the path in old version is nonexistent like 
```cpuacct.usage_sys``` and ```cpuacct.usage_user``` which is created at the Linux 4.x.
Tests 
Side effects
Documentation
```release-note
None
```
> cgroup: improve test to find cgroup compatibility issues 

- planner/core/BUILD.bazel
- planner/core/binary_plan_test.go
Issue Number: close #40004  close #41297
Try to fix the above two unstable test cases.
1. `TestTooLongBinaryPlan`: I'm unable to reproduce this fail. But I suspect this is because this case is affected by other cases. So I disable and then enable stmt summary in this case to trigger clear the stmt summary in memory, hoping this can fix the problem.
2. `TestLongBinaryPlan`: I added a rather strict check when I wrote this test case. It looks like this is too strict and even small changes might break this case. So I removed some non-necessary checks.
3. I also reset the global variables in the test cases of this file to reduce the possibility of test cases affecting each other.
4. As @hawkingrei advised, update timeout of planner/core to "short".
Tests 
Side effects …
> planner: stabilize tests in `binary_plan_test.go`

- domain/domain.go
- tidb-server/main.go
Issue Number: close #41318
When shutting down, stop `autoAnalyzeWorker` from launching new auto analyze job.
Tests 
```
set @@global.tidb_enable_auto_analyze = 0; 
create table t1(a int, b int);
create table t2(a int, b int);
-- insert data into t1 and t2 to let them be ready for triggering auto analyze
set @@global.tidb_enable_auto_analyze = 1; 
```
Assume auto analyze of `t1` is triggered. Then Ctrl+C to shut down the tidb server. Auto analyze of `t1` is killed. Before the PR, auto analyze of `t2` may be triggered(I add `time.Sleep` in `cleanup` to make that reproducible). After the PR, auto analyze of `t2` would not be triggered. 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/r …
> domain, tidb-server: stop launching new auto analyze job when shutting down

- planner/core/indexmerge_path.go
- planner/core/integration_test.go
Issue Number: close #41273 close #41293
This bug is introduced by #30341.
This case is related to the `SET` type mainly. We don't support pushing down the `SET` type now. `util/ranger` also can't correctly handle expressions on `SET` column. So it requires these expressions be blocked in advance. After #30341, such expressions can reach `util/ranger` without the `CanExprsPushDown` check.
Add a `CanExprsPushDown` check before using an expression to build an IndexMerge partial path.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add missing `CanExprsPushDown` checks when generating IndexMerge path for `or`

- Makefile
Tests 
Side effects
Documentation
```release-note
None
```
> *: improve makefile

- br/pkg/glue/glue.go
- br/pkg/gluetidb/BUILD.bazel
- br/pkg/gluetidb/glue.go
- br/pkg/gluetidb/glue_test.go
- ddl/ddl_api.go
Issue Number: close #41333 
when restoring to a brand-new cluster, reused table id was disabled, which caused restore to consume more resources.
Tests 
Side effects
Documentation
```release-note
None
```
> br: reused table id is disabled when restore a brand-new cluster

- planner/core/plan_cache_test.go
Problem Summary: planner: add more test cases for non-prepared plan cache
planner: add more test cases for non-prepared plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for non-prepared plan cache

- br/pkg/lightning/backend/local/BUILD.bazel
- ddl/metadatalocktest/BUILD.bazel
- parser/types/BUILD.bazel
- util/ranger/BUILD.bazel
Tests 
Side effects
Documentation
```release-note
None
```
> *: bazel upgrade shard_count

- executor/adapter.go
- executor/builder.go
- executor/index_lookup_merge_join_test.go
- executor/issuetest/executor_issue_test.go
- session/session.go
Signed-off-by: you06 <you1474600@gmail.com>
Issue Number: close #41412
The build function may be called concurrently when building executors on probe side, use an atomic variable to avoid data race
```bssh
» go test -race ./executor/issuetest -run TestIssueRaceWhenBuildingExecutorConcurrently --tags=intest
ok      github.com/pingcap/tidb/executor/issuetest      15.110s
```
Tests 
Side effects
Documentation
```release-note
Fix the data race of store batch coprocessor telemetry stats.
```
> executor: fix race when collecting telemetry info of batch copr

- ddl/ddl.go
- ddl/ddl_test.go
- ddl/ddl_worker_test.go
- ddl/job_table.go
Issue Number: close https://github.com/pingcap/tidb/issues/41418
`newReorgCtx` and `setReorgCtxForBackfill` are no problem when used with dist-reorg, because `newReorgCtx` must be called before `setReorgCtxForBackfill` when using the same jobID.
However, the code has been changed to prevent other ways of using it in the future and to test for stability, so change the code
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: make `reorgCtx` safer to use

- planner/cascades/BUILD.bazel
- planner/funcdep/BUILD.bazel
- store/BUILD.bazel
- types/BUILD.bazel
Tests 
Side effects
Documentation
```release-note
None
```
> *: improve bazel config

- parser/ast/dml.go
- parser/misc.go
- parser/parser.y
- parser/parser_test.go
add parser support for `NULL DEFINED BY`
```
LOAD DATA ... [LINES ...] [NULL DEFINED BY <string> [OPTIONALLY ENCLOSED]] [IGNORE ...]
```
add parser support for `FORMAT`
```
LOAD DATA ... INFILE 'string' FORMAT 'string' ...
```
Tests 
Side effects
Documentation
```release-note
None
```
> parser: add NULL DEFINED BY and FORMAT to LOAD DATA

- br/pkg/storage/BUILD.bazel
- br/pkg/storage/s3_test.go
- build/nogo_config.json
Issue Number: close #41449
1. open bazel parallel test for storage_test
2. modify unit test to remove sequential dependency of test cases.
Tests 
Side effects
Documentation
```release-note
None
```
> br: open parallel test for storage_test

- br/pkg/lightning/backend/local/local.go
```
[2023/02/15 15:12:47.757 +08:00] [INFO] [local.go:1110] ["write to tikv partial finish"] [count=920276] [size=0]
```
size is always 0
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix total_bytes is always 0 in log

- util/cgroup/cgroup_cpu_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/39786
Refine the handling of errNoCPUControllerDetected: ignore errNoCPUControllerDetected on old kernel but still panic on new kernel. Thanks a lot for the advice from @nolouch.
Tests 
Side effects
Documentation
```release-note
None
```
> cgroup: refine the handling of errNoCPUControllerDetected

- br/pkg/storage/BUILD.bazel
- sessionctx/BUILD.bazel
It is a test case in the ```sesessionctx``` package. it is unsuitable to set timeout moderate.
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: set timeout short

- ddl/backfilling.go
- tests/realtikvtest/addindextest/integration_test.go
Issue Number: close #41459
The condition `remains == 0` does not indicate the whole task is finished after #40411.
Correct the remain check code.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: correct the remain ranges check for adding index

- br/pkg/lightning/backend/local/localhelper_test.go
- br/pkg/restore/split/split.go
- br/pkg/restore/util_test.go
Issue Number: close #41479
```
--- PASS: TestBatchSplitRegionByRangesScanFailed (256.34s)
```
Tests 
```
--- PASS: TestBatchSplitRegionByRangesScanFailed (6.01s)
```
Side effects
Documentation
```release-note
None
```
> test: change retry limit for ScanRegionAttemptTimes

- DEPS.bzl
- config/config.go
- go.mod
- go.sum
- server/conn.go
- server/server.go
- server/tidb_test.go
- tidb-server/main.go
Issue Number: close #41409 
Add `-proxy-protocol-fallbackable` option to let TiDB can handle raw connection connect to TiDB and the IP address is in allowed IP list.
update `go-proxyprotocol` package to enable fallbackable support.
Tests 
Side effects
Documentation
```release-note
Add `-proxy-protocol-fallbackable` options to let TiDB can handle raw connection which client IP is in PROXY protocol allowed IP list.
```
> server: support PROXY protocol fallback-able options

- meta/autoid/autoid_service.go
Issue Number: close https://github.com/pingcap/tidb/issues/40322
`AUTO_ID_CACHE = 1` use a different implementation, this metric in the new code path is missing
Tests 
Run the sysbench and check the dashboard:
Side effects
Documentation
```release-note
None
```
> meta/autoid: fix AutoID allocation metrics for AUTO_ID_CACHE=1

- tidb-server/main.go
- util/stmtsummary/v2/logger.go
- util/stmtsummary/v2/stmtsummary.go
- util/stmtsummary/v2/stmtsummary_test.go
- util/stmtsummary/v2/tests/main_test.go
- util/stmtsummary/v2/tests/table_test.go
Issue Number: close #41485
Flush the current window when gracefully shutdown.
Tests 
Side effects
Documentation
```release-note
None
```
> stmtv2: flush the last window before shutdown

- domain/BUILD.bazel
- domain/domain.go
- util/gctuner/BUILD.bazel
- util/gctuner/memory_limit_tuner.go
Issue Number: close #41524
Tests 
Side effects
Documentation
```release-note
None
```
> gctuner: fix goleak in the memoryLimitTuner.tuning

- distsql/request_builder.go
- executor/distsqltest/BUILD.bazel
- executor/distsqltest/distsql_test.go
- executor/distsqltest/main_test.go
- planner/core/partition_pruner_test.go
- store/copr/coprocessor.go
Issue Number: ref #41480
The [distsql concurrency of limit statement is set to 1](https://github.com/pingcap/tidb/blob/f9e1845849bf2b1f9f2e35cd0f5a5c8e397f2405/distsql/request_builder.go#L159-L161) before, but with partitioned table, it may affect performance, see the case in #41480.
```sql
MySQL [test]> CREATE TABLE t(id int PRIMARY KEY, val int)
-> PARTITION BY RANGE (id)
-> (PARTITION p1 VALUES LESS THAN (100),
->  PARTITION p2 VALUES LESS THAN (200),
->  PARTITION p3 VALUES LESS THAN (300),
->  PARTITION p4 VALUES LESS THAN (400),
->  PARTITION p5 VALUES LESS THAN (500),
->  PARTITION p6 VALUES LESS THAN (600),
->  PARTITION p7 VALUES LESS THAN (700),
->  PARTITION p8 VALUES LESS THAN (800),
->  PARTITION p9 VALUES LESS THAN (900),
->  PARTITION p10 VALUES LESS THAN …
```
> store/copr: set concurrency to partition number for limit statements

- ddl/index_merge_tmp.go
- executor/insert.go
- server/http_handler.go
- session/txn.go
- table/tables/index.go
- table/tables/mutation_checker.go
- tablecodec/tablecodec.go
- tablecodec/tablecodec_test.go
Issue Number: close #41515
- Add the unique check for temp index in `keyNeedToLock()`
- Refine some of the function parameters
Tests 
Side effects
Documentation
```release-note
None
```
> *: lock the temp index key properly in DML

- ddl/backfilling.go
- ddl/column.go
- ddl/dist_backfilling.go
- ddl/index.go
- ddl/partition.go
Issue Number: ref #41534
Problem Summary: Previously, TiDB use `id == 0` to decide whether to allocate a new backfill context ID for distributed execution. However, it is possible to pass a `0` ID even if the distributed execution is disabled.
Use a separate parameter to decide whether exec in distributed mode.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: use a param to decide whether exec in distributed mode

- config/config.go
- config/config.toml.example
- config/config_test.go
- executor/compiler.go
- metrics/executor.go
- metrics/server.go
- metrics/session.go
- metrics/telemetry.go
- server/conn.go
- server/server_test.go
- server/tidb_serial_test.go
- server/tidb_test.go
- session/session.go
Issue Number: close #37892
Problem Summary: add  some metric by database 
This pr is based on a modification of https://github.com/pingcap/tidb/pull/38261
（We need to add a switch to control whether the db label is added to the metric or not.）
Reasons for not adding table labels: https://prometheus.io/docs/practices/naming/#labels
Add additional information about database name to the current metric 
tidb_server_handle_query_duration_seconds
tidb_executor_statement_total
tidb_server_execute_error_total
**Added a switch to control whether to add database labels**
```
[status]
record-db-label = true // default false
```
Tests 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.ht …
> metric: add some metric by database

- executor/cluster_table_test.go
- executor/slow_query_test.go
- infoschema/tables_test.go
Issue Number: close #41308
Tests 
Side effects
Documentation
```release-note
None
```
> infoschema: fix unstable test TestTableIfHasColumn

- executor/aggregate.go
- executor/cte.go
- executor/distsql.go
- executor/executor.go
- executor/index_lookup_hash_join.go
- executor/index_merge_reader.go
- executor/join.go
- executor/projection.go
- executor/table_reader.go
- util/memory/tracker.go
Issue Number: close #41476 
Detach memTracker from the parent executor in Open.
Apply will open and close the child executor over and over again, if the memory tracker is not detached, there will be too many small Tracker objects held by the parent, and thus cause high memory pressure.
Tests 
steps: https://github.com/pingcap/tidb/issues/41476#issuecomment-1434308990
before this commit:
after this commit:
Side effects
Documentation
```release-note
None
```
> executor: detach memTracker when open executor

- ddl/column.go
- ddl/column_type_change_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/41281
For operations that modify columns, double and float data should be truncated when the length is the same and the number of decimal places is reduced. But the old logic doesn't do it.
When the length is the same and the number of decimal places is reduced, we need reorg the data.
Tests 
Side effects
Documentation
```release-note
Fixed double and float data not being truncated for column modification operations when the length is the same and the number of decimal places is reduced.
```
> ddl: fix double/float data not being truncated for column modification operations when the number of decimal places is reduced.

- WORKSPACE
- parser/terror/terror_test.go
- server/tidb_serial_test.go
- util/misc.go
Issue Number: ref #40969
Tests 
Side effects
Documentation
```release-note
None
```
> *: upgrade go 1.20.1

- ddl/backfilling.go
- ddl/ddl_test.go
- ddl/dist_backfilling.go
- ddl/dist_owner.go
- ddl/index.go
- ddl/job_table.go
- ddl/job_table_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/41576
- Move some dist-reorg code from backfilling.go to dist_* files (The code hasn't changed at all)
- Add the function of generating prefix key and key, unified generating backfill job key.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: move some dist-reorg code to dist_* files and add the generate prefix key function 

- distsql/request_builder.go
Issue Number: close #41591 
https://github.com/pingcap/tidb/pull/41120 fix the problem partly.
This PR refines the code of check logic.
Tests 
Before:
``` sql
+----------------------------------+----------+---------+-----------+--------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
> distsql: refine code for setting LimitSize of kvRequest

- br/pkg/lightning/mydump/csv_parser.go
- executor/builder.go
- executor/load_data.go
- executor/loadremotetest/one_csv_test.go
- executor/loadremotetest/util_test.go
- executor/select_into.go
- executor/writetest/write_test.go
- parser/ast/dml.go
- parser/parser.y
- planner/core/common_plans.go
- planner/core/planbuilder.go
as title
This PR also fix that ASCII 00 can set as FIELDS ENCLOSED BY or FIELDS ESCAPED BY
Tests 
Side effects
Documentation
```release-note
None
```
> executor: implement NULL DEFINED BY for LOAD DATA

- server/BUILD.bazel
- server/http_handler.go
- server/http_handler_serial_test.go
- server/http_status.go
Issue Number: close #41597
Expose a http api to trigger TTL job manually to make it easier for some integration tests. You can do it like this:
```
curl -X POST http://127.0.0.1:10081/test/ttl/trigger/test/t1
```
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: Add a http api to trigger TTL job manually for test

- ddl/delete_range.go
- ddl/index.go
- ddl/sanity_check.go
- executor/builder.go
- executor/distsql.go
- executor/partition_table_test.go
- planner/core/logical_plan_builder.go
- planner/core/planbuilder.go
- planner/core/rule_partition_processor.go
Issue Number: close https://github.com/pingcap/tidb/issues/40497
Issue Number: close https://github.com/pingcap/tidb/issues/21732
Issue Number: close https://github.com/pingcap/tidb/issues/40149
Note: PR https://github.com/pingcap/tidb/pull/22478?w=1 doest not solve #40149 actually, so I list it here.
- filter out the selected partitions in IndexLookUpExecutor when global index query specifies partitions. 
- only dynamic mode and global stats is ready, we can use the global index. Otherwise ignore it, as PartitionUnionAll logical plan not suitable for global index.
- when drop global index's regions(drop table/index), we should specify the correct key prefix, like t{tableID}_i{indexID}.
Tests 
Side effects
Documentation …
> executor: enhance global index

- executor/builder.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #41581 
The point get read result is unexpected if RC is used with DML statements.
Update the `forUpdateTS` when building `insert/delete/update/select for update` executors, to ensure the `pointGetExecutor` may use the correct timestamp to read.
Tests 
Side effects
Documentation
```release-note
Fix the incorrect result when RC is used with update.
```
> txn: fix the point get data read for RC

- expression/builtin_compare.go
- planner/core/plan_cache_test.go
Issue Number: close #41626
Problem Summary: planner: skip plan cache if the query has filters like `year <cmp> const`
planner: skip plan cache if the query has filters like `year <cmp> const`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: skip plan cache if the query has filters like `year <cmp> const`

- executor/builder.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
close pingcap/tidb#41581
Issue Number: close #41581 
Tests 
Side effects
Documentation
```release-note
None
```
> hotfix: pick f6edebc054371e4bce9b672d420bfeaa60d52049 to branch

- statistics/handle/update.go
- statistics/handle/updatetest/update_test.go
Issue Number: close #41638
Tests 
Test #41638 manually.
Side effects
Documentation
```release-note
None
```
> statistics/handle: fix trigger auto analyze for partition table after adding index

- DEPS.bzl
- executor/point_get_test.go
- go.mod
- go.sum
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #41527 
Under RC, point-get with lock on a non-existent key will not actually lock it. Aggressive locking didn't handle this case well and caused the committer to prewrite this non-existent key, thus generating "pessimistic lock not found" error.
Tests 
Side effects
Documentation
```release-note
None
```
> txn: fix point-lock non-existent key with aggressive locking under rc

- executor/index_merge_reader.go
- executor/index_merge_reader_test.go
Issue Number: close #41605
Problem Summary: As issue said, for partialIndexWorker and partialTableWorker of IndexMerge, we may failed to call `SelectResult.Close` when got panic(oom) in `IndexMerge.fetchHandles()`. Therefore goroutines in coprocessor that tries to send copResp will stuck, because receiver already panic and `copIterator.finishCh` is never closed.
Tests 
Side effects
Documentation
```release-note
exeuctor: fix coprocessor goroutine leak for IndexMerge
```
> exeuctor: fix coprocessor goroutine leak for IndexMerge

- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- planner/optimize.go
Problem Summary: planner: add diagnosis information for non-prep plan cache
planner: add diagnosis information for non-prep plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add diagnosis information for non-prep plan cache

- executor/distsql.go
- executor/distsql_test.go
- store/copr/coprocessor.go
Issue Number: close #41582
Cherry pick part of #40711
- Now scan details are set in TiKV correctly, this PR handle it.
- Record the next wait time so that we get more latency info from the critical path.
Tests 
Side effects
Documentation
```release-note
None
```
> store/copr: handle scan details & record next wait details

- br/pkg/storage/s3.go
- br/pkg/storage/storage.go
Issue Number: close #41650
1. When creating s3 storage, replace `context.Background()` with `ctx` passed in from the outside.
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix s3 timeout

- br/pkg/lightning/restore/precheck_impl.go
- br/pkg/lightning/restore/precheck_impl_test.go
- br/pkg/task/stream.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/cdc.go
- br/pkg/utils/cdc_test.go
- br/pkg/utils/tools_check.go
Issue Number: close #41504 
BR restore should be failed when the cluster has cdc changefeed running
Currently lightning has the step to check whether the cdc changefeed is running. Move the step to public pkg so that BR restore can directly use it.
Tests 
Side effects
Documentation
```release-note
None
```
> BR: move check_cdc to public pkg

- ddl/backfilling.go
- ddl/index.go
- tests/realtikvtest/addindextest/integration_test.go
Issue Number: close #41630
There are two problems in current implementation:
- In `getBatchTasks()`, the `endInclude` field of `reorgBackfillTask` is assigned according to whether the range is the last one. It means the end key of key ranges that passed to `handleRangeTasks()` is processed. We should set the start key of next round to `endKey.Next()` instead of `endKey`.
- For partial import, the key duplicated error is not correctly handled and returned. It unexpectedly  fallbacks to the old way to add the index.
See "Problem Summary" part.
Tests 
Side effects
Documentation
```release-note
None …
```
> ddl: fix unexpected duplicated error when adding unique index

- executor/compiler.go
- server/server_test.go
Issue Number: close #41688 
Problem Summary:  meet panic when status.record-db-label enable
add nil check
Tests 
Side effects
Documentation
```release-note
None
```
> metric: fix panic when status.record-db-label enable

- executor/aggregate_test.go
- executor/join_test.go
- executor/seqtest/seq_executor_test.go
- executor/simple.go
- server/server.go
- tests/globalkilltest/global_kill_test.go
- util/expensivequery/expensivequery.go
- util/memory/action.go
- util/memory/tracker.go
- util/servermemorylimit/servermemorylimit.go
- util/util.go
- util/util_test.go
Issue Number: close #41699 
Tests 
Side effects
Documentation
```release-note
Log messages were updated to always use the same key name for connection ID's
```
> *: Standardize use of conn_id=, connID= and conn= in messages

- executor/explainfor_test.go
- planner/core/plan_cache.go
- planner/core/prepare_test.go
Problem Summary: planner: check rebuilt ranges more strictly for plan cache
planner: check rebuilt ranges more strictly for plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: check rebuilt ranges more strictly for plan cache

- cmd/explaintest/r/index_merge.result
- executor/distsqltest/BUILD.bazel
- planner/core/exhaust_physical_plans.go
- planner/core/find_best_task.go
- planner/core/integration_test.go
- planner/core/physical_plan_test.go
- planner/core/plan_cost_ver1.go
- planner/core/plan_cost_ver2.go
- planner/core/plan_cost_ver2_test.go
- planner/core/task.go
- planner/core/testdata/integration_suite_out.json
- planner/core/testdata/plan_suite_in.json
- planner/core/testdata/plan_suite_out.json
- planner/property/physical_property.go
- planner/property/task_type.go
Manual cherry-pick of #41054
Issue Number: ref https://github.com/pingcap/tidb/issues/41028
Tests 
Side effects
Documentation
```release-note
None
```
> planner: support push part of limit prop to IndexMerge (#41054)

- parser/model/BUILD.bazel
- parser/model/ddl.go
- parser/model/model.go
- parser/model/reorg.go
This PR moves the reorg and backfill related types and functions to a new file to prevent `model/ddl.go` being too large.
Tests 
Side effects
Documentation
```release-note
None
```
> parser/model: move reorg related types to a new file

- executor/index_merge_reader.go
- executor/index_merge_reader_test.go
Issue Number: close #41605
Problem Summary: Manually cherrypick of https://github.com/pingcap/tidb/pull/41610
Tests 
Side effects
Documentation
```release-note
exeuctor: fix coprocessor goroutine leak for IndexMerge
```
> exeuctor: fix coprocessor goroutine leak for IndexMerge | tidb-test=a7d6b8869742f76a93eb3c69804fabab8d6a42e8

- executor/grant.go
- executor/revoke.go
- executor/revoke_test.go
Issue Number: close #41773 
Problem Summary: Should skip `USAGE`, which is `0`. It does not have coressponding column on priv table.
Tests 
Side effects
Documentation
```release-note
Fix error on 'REVOKE USAGE ...'
```
> executor: fix revoke USAGE

- executor/adapter.go
- server/conn.go
- server/conn_stmt.go
- session/txnmanager.go
- sessiontxn/interface.go
- sessiontxn/isolation/base.go
- sessiontxn/isolation/optimistic_test.go
- sessiontxn/isolation/readcommitted.go
- sessiontxn/isolation/readcommitted_test.go
- sessiontxn/isolation/repeatable_read.go
- sessiontxn/isolation/repeatable_read_test.go
- sessiontxn/isolation/serializable.go
- sessiontxn/isolation/serializable_test.go
- sessiontxn/staleread/provider.go
Issue Number: close #41724 
This PR moves invokations of aggressive locking starting/retrying/exiting to single functions (`handlePessimisticDML` and `handlePessimisticSelectForUpdate`). These two functions will enter aggressive locking if needed, and exit aggressive locking when it returns. Previously we exits aggressive locking in `StmtCommit` and `StmtRollback`. However in issue #41724 we founds that sometimes TiDB doesn't evaluate the condition to call `StmtCommit`/`StmtRollback` correctly, causing the aggressive locking state leak to the next statement. This PR avoids this leaking by exiting aggressive locking within the function that starts the aggressive locking.
Tests 
Side effects
Documentation …
> adapter, txn: Move aggressive locking controlling logic to handlePessimisticXXX functions to avoid some potential misuses

- ddl/index.go
Issue Number: close #41776
Problem Summary: See #41776.
For the ingest mode, we use lightning local backend's local check and remote check to implement the duplicate key detection. This PR removes the unnecessary check.
> add non-unique index: 22.16 sec, 20.05 sec, 21.10 sec
> add unqiue index: 1 min 12.86 sec, 1 min 10.17 sec, 1 min 16.17 sec
After this PR:
add unqiue index: 22.98 sec, 21.55 sec, 23.23 sec
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: remove unnecessary unique check for ingest mode

- types/convert.go
- types/convert_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/41736
see https://github.com/pingcap/tidb/issues/41736#issuecomment-1449271739
Tests 
```release-note
Fix a compare incorrect issue cause by fault convert 
```
> types: clip to zero when convert negative decimal to uint

- executor/slow_query_sql_test.go
- util/stmtsummary/v2/tests/table_test.go
Problem Summary: planner: add more test cases for non-prep plan cache 
planner: add more test cases for non-prep plan cache 
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for non-prep plan cache 

- planner/core/exhaust_physical_plans.go
- planner/core/logical_plan_builder.go
- planner/core/rule_join_reorder.go
- planner/core/rule_join_reorder_dp_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/36600
resolve the compatibility problems for the join hint
1. Record the hint information before the join reorder. Use map[plan-ID] = hintInfo to record the hint information for sub-plan.
2. After the join reorder, restore the hint information from the map.
Tests 
The switch is off, so we hope the original test can be passed. And in the next PR, we will enable the switch and try to add and modify more test cases.
Side effects
Documentation
```release-note
None
```
> planner: resolve the compatibility problems for the join hint

- planner/core/plan_cache_test.go
Issue Number: ref #40219 
Tests 
Side effects
Documentation
```release-note
None
```
```
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version() …
```
> planner: supply test for subquery in prepared plan cache

- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
Issue Number: close #41829
Problem Summary: planner: skip plan cache if plans have `MemTableScan` operator
planner: skip plan cache if a plan accesses memory tables
Tests 
Side effects
Documentation
```release-note
None
```
> planner: skip plan cache if plans have `MemTableScan` operator

- br/pkg/streamhelper/advancer_daemon.go
- br/pkg/streamhelper/daemon/interface.go
- br/pkg/streamhelper/daemon/owner_daemon.go
- br/pkg/streamhelper/daemon/owner_daemon_test.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/db.go
- br/tests/br_restore_log_task_enable/run.sh
Issue Number: close https://github.com/pingcap/tidb/issues/41806
close https://github.com/pingcap/tidb/issues/41642
If the gc-worker owner and the pitr owner is not the same node, the gc-worker owner cannot check the log-backup task existed.
Tests 
- Create a TiDB cluster with the 3 tidb-server, 3 pd-server and 3 tikv-server.
- Create a log-backup task, Search the log in all of tidb-server, the log like this
```
2023-03-01 16:38:04 (UTC+08:00)TiDB 10.2.5.20:4100[db.go:206] ["inc log backup task"] [count=1]
2023-03-01 16:38:07 (UTC+08:00)TiDB 10.2.5.31:4100[db.go:206] ["inc log backup task"] [count=1]
2023-03-01 16:38:10 (UTC+08:00)TiDB 10.2.5.32:4100[db.go:206] ["inc log backup task"] [count=1]
```
- restart all of tidb-server, and search the log
```
2023-03-01 17:11:27 …
```
> log-backup: fix the issue that gc-worker owner cannot check log-backup task existed.

- expression/builtin_time.go
- expression/integration_test/integration_test.go
Issue Number: close #40015
Tests 
Side effects
Documentation
```release-note
None
```
> expression: fix error handling of `DateAddString` vectorized function

- ddl/job_table.go
Issue Number: close #41579
using `=` is better than ```like``` here.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: use `=` to replace with `like` when querying complete task_key

- executor/explainfor_test.go
- planner/core/indexmerge_path.go
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
Issue Number: close #41828
Problem Summary: planner: fix the issue that cached IndexMerge plans can return wrong results in some cases
Fix the issue that cached IndexMerge plans can return wrong results in some cases
Two enhancements here:
1. keep all conditions with parameters as a part of table filters for cached IndexMerge for safety.
2. don't put IndexMerge plans with full-scans into the plan-cache for safety.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that cached IndexMerge plans can return wrong results in some cases

- ddl/indexmergetest/merge_test.go
- table/tables/index.go
Issue Number: close #41880
Previously, for untouched temp index key, TiDB writes it to the memory buffer and never commits it to TiKV(by checking if the last byte is the uncommited flag). 
https://github.com/pingcap/tidb/pull/40749 introduced a new temp index value encoding: for each insertion, TiDB appends the new temp index value to the end based on the old value. As a result, the "uncommitted flag" is not the last byte anymore and the key-value will be incorrectly committed to TiKV. The encoding becomes invalid.
Check the untouched values before writting to the temp index. Because the untouched values is only used for speeding up the index reading, and the temp index is never visible to the users, we can skip writting a untouched value to the temp index. 
Tests 
Side …
> ddl: never write untouched index values to temp index

- cmd/explaintest/r/explain_easy.result
- planner/core/expression_rewriter.go
- planner/core/expression_rewriter_test.go
- planner/core/testdata/plan_suite_unexported_out.json
- util/ranger/ranger_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/41734
Problem Summary:  see https://github.com/pingcap/tidb/issues/41734#issuecomment-1449475900
Tests 
Side effects
Documentation
```release-note
None
```
> planner: optimize `ifnull(not-null-column, ...)` to a cast instead of eliminating it. tidb-test=pr/2098

- WORKSPACE
Rules_cc always fail to download.
add a mirror in the IDC.
Tests 
Side effects
Documentation
```release-note
None
```
> *: add mirror for bazel's rules

- ddl/db_partition_test.go
- parser/ast/functions.go
Issue Number: close #41800 
Internally the expression was regenerated with a comma instead of 'FROM':
`extract(YEAR, '1998-01-01')` which should be `extract(YEAR FROM '1998-01-01')`
Tests 
Side effects
Documentation
```release-note
None
```
> parser: Add special formatter for extract(unit FROM date)

- domain/extract.go
- domain/plan_replayer_dump.go
- server/extract.go
- server/extract_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/41130
1. revise extract plan package format
2. support extract plan server handler default param
Tests 
```release-note
None
```
> domain: revise extract plan package format

- go.mod
- session/bootstrap.go
- session/bootstrap_test.go
- session/session.go
Issue Number: ref #35624
We need to add more tests to cover the scenarios of configuration `initialize-sql-file`
Tests 
Side effects
Documentation
```release-note
None
```
> bootstrap: add more tests for initialize-sql-file

- keyspace/BUILD.bazel
- keyspace/keyspace.go
- sessionctx/variable/BUILD.bazel
- sessionctx/variable/sysvar.go
- tidb-server/main.go
- util/logutil/log.go
- util/logutil/log_test.go
- util/logutil/main_test.go
Issue Number: close #41843 
add keyspace into log
Tests 
1. start tidb with keyspace
2. execute some sql
3. view tidb logs
start tidb with keyspace
start tidb without keyspace
Side effects
```release-note
add keyspace into log
```
> util: add keyspace into log

- executor/BUILD.bazel
- executor/adapter.go
- util/stmtsummary/statement_summary.go
- util/stmtsummary/v2/reader.go
- util/stmtsummary/v2/record.go
- util/stmtsummary/v2/record_test.go
Issue Number: close #41881
StmtsummaryV2 with keyspace
Tests 
1. start tidb with config
```
keyspace-name = "keyspace_a"
[instance]
tidb_stmt_summary_enable_persistent = true
tidb_stmt_summary_file_max_size = 25
tidb_stmt_summary_file_max_backups = 3
```
2. execute `set @@global.tidb_stmt_summary_refresh_interval=30;`
3. view log file, keyspace found in log file
//==============
1. start tidb with config
```
[instance]
tidb_stmt_summary_enable_persistent = true
tidb_stmt_summary_file_max_size = 25
tidb_stmt_summary_file_max_backups = 3
```
2. execute `set @@global.tidb_stmt_summary_refresh_interval=30;`
3. view log file, keyspace didn't found in log file
Side effects
No …
> stmtsummary: stmtsummary with keyspace

- store/copr/coprocessor.go
Issue Number: close #41562
Add index has 5% regression in the latest tidb, and it's probably caused by batched copr.
Disable batch for internal requests.
Tests 
I ran it 4 times with this PR and the time used are: 5453s, 5470s, 5459s, 5462s. Compare with the duration before, confirm that the regression is fixed.
Side effects
Documentation
```release-note
None
```
> store/copr: disable store batch copr for internal requests

- planner/core/plan_cache_test.go
- planner/optimize.go
Issue Number: ref #36598 
For compatibility purpose, we will not allow existing explain format use non-prep plan cache, the explain result keep consistant with the previous. Later, we will add a new explain format to reveal cache hit situation.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: existing explain format can not use non-prepared plan cache

- br/pkg/storage/gcs.go
- br/pkg/storage/gcs_test.go
- executor/loadremotetest/error_test.go
- executor/loadremotetest/util_test.go
Issue Number: close #41899 
gcs reader seekend should has an positive offset
get the total size of the object then file open.
return the `totalSize+offset` instead of `offset`.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: gcs reader seekend should has an positive offset

- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/lightning/backend/local/compress.go
- br/pkg/lightning/backend/local/compress_test.go
- br/pkg/lightning/backend/local/local.go
- build/nogo_config.json
Issue Number: close https://github.com/pingcap/tidb/issues/41970
The default gzip library has poor performance.  See the issue for more details.
Replace gzip compressor implementation with [klauspost/compress/gzip](https://github.com/klauspost/compress). Test the same 562GiB data in the issue, with compression enabled, the time cost reduced to 50m7s, which is a big improvement.
Also in unit test, we can see that our custom `GzipCompressor` is better than the default `grpc.GzipCompressor`.
```bash
> go test -bench "^Benchmar.*(Compressor|Decompressor)$" -run "^$"
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/br/pkg/lightning/backend/local
cpu: AMD Ryzen 7 3700X 8-Core Processor             
BenchmarkGzipCompressor-16                  2149            698146 ns/op …
```
> lightning: replace grpc gzip compressor with klauspost/compress/gzip

- br/pkg/restore/import_retry.go
- br/pkg/restore/import_retry_test.go
- br/pkg/utils/backoff.go
Issue Number: close https://github.com/pingcap/tidb/issues/41983
- If the config `tikv.import.memory-use-ratio` is too low, `tikv-server` would report the error "memory is limited" to `BR` when PITR restore, and the PITR restore failed finally because the retry times exceeds the threshold.
Tests 
Side effects
Documentation
```release-note
Fix the issue that failed to restore log with the error "memory is limited".
```
> br: continuing retry when pitr met the error about memory is limited

- statistics/handle/bootstrap.go
- statistics/handle/handletest/handle_test.go
Issue Number: close #41938
Use a newly-created `StatementContext` with `UTC` `TimeZone` when calling `(*Datum).ConvertTo` for upper/lower bounds in `initStatsBuckets4Chunk`.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics/handle: use StatementContext with TimeZone in initStatsBuckets4Chunk

- sessionctx/variable/sysvar_test.go
- sessionctx/variable/tidb_vars.go
- tidb-server/main.go
Issue Number: ref #41962
Tests 
- before this change, when set `tidb_resource_control = on` and restart tidb instance, the resource controller in kv-client is not initialized and kv request are not limit by ru. The resource control metrics has no data.
- After this change, the resource control behaved as expected.
Side effects
Documentation
```release-note
None
```
> sysvar: set the default value of resource control switch to false

- ddl/ddl.go
- ddl/metadatalocktest/mdl_test.go
Issue Number: close #41796
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix enable metadata lock

- util/execdetails/BUILD.bazel
- util/execdetails/execdetails.go
Issue Number: close #39076
Problem Summary:  fix potential risks of fatal error concurrent map read and map write
Tests 
Side effects
Documentation
```release-note
None
```
> util/execdetails: fix potential risks of fatal error concurrent map read and map write

- br/pkg/lightning/backend/backend.go
- br/pkg/lightning/backend/backend_test.go
- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/localhelper.go
- br/pkg/lightning/checkpoints/checkpoints.go
- br/pkg/lightning/common/BUILD.bazel
- br/pkg/lightning/common/common.go
- br/pkg/lightning/importer/import.go
- br/pkg/lightning/importer/meta_manager.go
- br/pkg/lightning/importer/table_import.go
- br/pkg/lightning/importer/table_import_test.go
- br/pkg/lightning/mydump/loader.go
- ddl/ingest/config.go
- ddl/ingest/engine.go
- move some code which can be reused to other package to avoid import cycle
- eliminate some func param which can be saved in the object
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: refactor to better reuse in load data

- executor/show.go
- parser/model/BUILD.bazel
- parser/model/model.go
- parser/model/model_test.go
- ttl/ttlworker/BUILD.bazel
- ttl/ttlworker/job_manager.go
Issue Number: close #41865
If the value of `TTL_JOB_INTERVAL` is not set, use `1h` instead. 
Actually the `TTL_JOB_INTERVAL` will be set to `1h` during the DDL. However, if the user created the table at 6.5 and upgrade the cluster to 6.6, the attribute is empty.
I'm not sure whether this is the best (and most suggested) way to fix this problem. If you have more suggestion, feel free to point out.
Tests 
```release-note
Fix the issue that an TTL table upgraded from old version could have 0 job interval and the TTl job will keep running.
```
> ttl: fix upgrade from 6.5 to 6.6 configuration default value

- session/bootstrap.go
- session/bootstrap_test.go
Issue Number: close #42078 
Tests 
Side effects
Documentation
```release-note
None
```
> session: set tidb_stats_load_pseudo_timeout to ON when upgrade to v6.5

- statistics/integration_test.go
- statistics/interact_with_storage.go
Issue Number: close #42073
Refine the condition whether to load column stats. Fix the behavior which doesn't follow column stats lazy load.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: fix wrong column stats loading after analyze twice

- session/session.go
Issue Number: close #42100
When the failpoint "assertTSONotRequest" is enabled, TiDB executes a DDL internal SQL, which is executed periodically. As a result, the failpoint unexpectedly affects the DDL.
https://github.com/pingcap/tidb/blob/5a4c14cfd54a2b18075bd48978ae481b88fd1771/executor/stale_txn_test.go#L1251-L1254
Make the failpoint only affect external SQL.
Tests 
Side effects
Documentation
```release-note
None
```
> session: fix unstable test TestStaleReadNoExtraTSORequest

- statistics/integration_test.go
- statistics/interact_with_storage.go
Issue Number: close #42052
When loading index stats from storage, we don't need to load index fmsketch unless `loadAll` is true. We only use index fmsketch when merging partition stats to global stats, where `loadAll` is true.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: fix unnecessary index fmsketch loading

- ddl/BUILD.bazel
- ddl/export_test.go
- ddl/index.go
- ddl/index_cop.go
- ddl/index_cop_test.go
Issue Number: close #42079
The function `extractDatumByOffset` takes too much memory.
This PR moves the encoding work from the readers to writers. Once the chunk is read, the writers encode index KV and write them to the local engine without using any intermediate data structure.
As a result, the memory allocation in `extractDatumByOffset` could be eliminated.
After this PR:
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: move adding index encoding work from readers to writers

- resourcemanager/pool/spool/BUILD.bazel
- resourcemanager/pool/spool/spool.go
Issue Number: close #42130
when we are in exit mode, Some tasks still want to start a new goroutine and call ```waitgroup.Add```. but at the same time, we are calling the ```waitgroup.Wait```.
the data race will happen.
Adding the logic of checking the exit mode when to check the running exit and wait to make all tasks called ```waitgroup.Add```.
Tests 
Side effects
Documentation
```release-note
None
```
> spool: fix data race when to exit

- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/job_table.go
Issue Number: ref #39824
waiting is useless now. It is always `false`. 
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: remove a useless variable

- ddl/placement/common.go
- infoschema/tables.go
Issue Number: close #42064
https://github.com/pingcap/tiflash/issues/7007
When the label of TiFlash contains `engine_role`:`write`, it means that this TiFlash is a `tiflash_write` node. So `tiflash_write` should be displayed in `information_schema.cluster_info`.
Check the label and display `tiflash_write`.
Tests 
Side effects
Documentation
```release-note
None
```
> *: display tiflash_write in cluster_info

- resourcemanager/pool/spool/spool_test.go
Issue Number: close #42163
Some tasks are still increasing after ```Tune```, so we need to wait for all tasks to be completed.
Tests 
Side effects
Documentation
```release-note
None
```
> spool: fix unstable test TestPoolTuneScaleUpAndDown

- executor/adapter.go
- executor/fktest/BUILD.bazel
- executor/fktest/foreign_key_test.go
- executor/metrics/metrics.go
- infoschema/tables_test.go
- kv/interface_mock_test.go
- kv/kv.go
- metrics/grafana/tidb.json
- metrics/metrics.go
- metrics/session.go
- metrics/telemetry.go
- session/bootstrap.go
- session/txn.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
- sessiontxn/isolation/base.go
- sessiontxn/isolation/readcommitted.go
- sessiontxn/isolation/repeatable_read.go
- sessiontxn/isolation/repeatable_read_test.go
- sessiontxn/txn_context_test.go
- store/driver/txn/txn_driver.go
- telemetry/data.go
- telemetry/data_feature_usage.go
- telemetry/data_feature_usage_test.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: ref #42107 , close #42147 
This PR does the following changes:
1. Rename the term *Aggressive Locking* to *Fair Locking* for all places, including the system variable, telemetry item and metrics.
2. Enable `tidb_pessimistic_txn_fair_locking` by default for new clusters, but clusters upgraded from older version will still have this option disabled.
3. Adapt some tests that doesn't work well with `tidb_pessimistic_txn_fair_locking` globally enabled.
The term *Aggressive Locking* is also used in client-go which is not updated for now, thus the old term still occurs in code that references to client-go. We will also rename it in client-go later.
Tests 
Side effects
Documentation …
> txn, session: Rename Aggressive Locking to Fair Locking and enable by default for new clusters

- ddl/ddl_api.go
- ddl/resourcegroup/errors.go
- ddl/resourcegroup/group.go
- ddl/resourcegrouptest/resource_group_test.go
- executor/ddl.go
- session/BUILD.bazel
- session/bootstrap.go
- session/session.go
- sessionctx/variable/session.go
- telemetry/data_feature_usage_test.go
Issue Number: close #40875
Initialize the default resource group to resource manager, and let it readable and changeable  but not droppable. 
Tests 
Simulate the upgrade from 6.6 to nightly to verify default resource group will be created.
Side effects
Documentation
```release-note
None
```
> *: visible default resource group

- br/pkg/lightning/importer/import.go
- br/pkg/lightning/importer/meta_manager.go
- br/pkg/lightning/importer/meta_manager_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/42214
Problem Summary: Sorry, I only tested on the third-party platform and did not conduct integrated testing.
Tests 
Side effects
Documentation
```release-note
None
```
> Lightning: fix integration test

- server/conn_stmt.go
- server/conn_stmt_test.go
- server/driver.go
- server/driver_tidb.go
Issue Number: close #40094 
TiDB cannot handle concurrently running statements. This PR stores and restores the params.
Store and restore the prepared params in session
Tests
The following JDBC codes run without panic:
```java
import java.sql.*;
public class Example {
public static void main(String[] args) throws SQLException, InterruptedException {
Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:4000/test?useCursorFetch=true&useServerPrepStmts=true&useSSL=false", "root", "");
conn.setAutoCommit(false); // must set
conn.prepareStatement("drop table if exists t").execute();
conn.prepareStatement("create table t (id int auto_increment primary key, id_2 int)").execute();
conn.prepareStatement("insert into t values (1,1)").execute(); …
```
> session, com_stmt: store and restore the params for cursor fetch

- server/conn.go
- tidb-server/main.go
Issue Number: close #32110 
ref #32111 
Set default drainClientWait as 15s
The default keeps waiting maybe too rigorous, It is easy having little slow txns which we may not want to wait for them, also the idle connections may block the shutdown two.
generally, 15s is enough for an ongoing txn to finish, better provider a dynamic way to set this value. 
Tests 
Side effects
Documentation
```release-note
None
```
> server: Set default drainClientWait as 15s

- br/pkg/utils/retry.go
- br/tests/br_full/run.sh
Issue Number: close #41756
Some S3-compatible external storage does not return an error response with a human-readable `<Message>` tag. BR relied on its content and thus failed to recognize a RequestTimeout error is in fact retryable.
Added the error code into the list of phrases to check.
Tests 
Side effects
Documentation
```release-note
BR can now properly retry on RequestTimeout transient errors when backing up to Baidu Object Storage (BOS).
```
> br: add <Code>RequestTimeout</Code> to list of retryable errors

- br/pkg/task/backup.go
- br/pkg/utils/safe_point.go
Issue Number: close #41835 
the checkpoint mode lead to failure when br use noop storage
turn off the checkpoint mode when use noop storage
Tests 
Side effects
Documentation
```release-note
None
```
> br: turn off the checkpoint mode when use noop storage

- br/pkg/restore/client.go
- br/pkg/restore/ingestrec/ingest_recorder.go
- br/pkg/restore/ingestrec/ingest_recorder_test.go
Issue Number: ref #41668 
when rewrite rule not found for ingest recorder, should skip instead of return error
skip instead of error
Tests 
Side effects
Documentation
```release-note
None
```
> pitr: skip when rewrite rule not found for ingest recorder

- ddl/reorg_partition_test.go
Issue Number: ref #38535
Add more tests for `REORGANIZE PARTITION` on Range/Range Columns/List/List Columns partitions.
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```
> ddl: add more functional tests for `REORGANIZE PARTITION`

- executor/stale_txn_test.go
- session/session.go
Issue Number: close #41622 close #42003
Build plan need to use the same InfoSchema, but `vars.InTxn()` is false in #41622.
Relax the condition can fix issue/41622
Alternative: change all `sctx.GetInfoSchema()` to `sessiontxn.GetTxnManager(sctx).GetTxnInfoSchema()`
It involves a lot of changes and seems more fragile comparing to this single line of change.
Tests 
Test with the reproduce provided by @crazycs520 in the issue.
Side effects
Documentation
```release-note
None
```
> session: use TxnCtx.InfoSchema, no matter vars.InTxn() or not

- executor/insert_common.go
- executor/insert_test.go
- executor/write.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #42121 
Problem Summary: When doing insert-ingore or replace without changes, tidb doesn't lock conflict keys properly.
Lock keys even when insert-ingnore meets duplicated rows or replace without changes.
Tests 
Side effects
**The change may introduce more lock records, which may further lead performance regression like https://github.com/pingcap/tidb/issues/25659 .**
Documentation
```release-note
None
```
> executor: lock duplicated keys on insert-ignore & replace-nothing

- ddl/ddl_api.go
- executor/compact_table.go
- infoschema/tables.go
Issue Number: close #42245
Fix TiFlash serverType check in disaggregated mode.
Tests 
`alter table t1 set tiflash replica 1;`
Before modified:
After modified:
Side effects
Documentation
```release-note
None
```
> *: Fix TiFlash serverType check  in disaggregated mode

- br/pkg/restore/split/BUILD.bazel
- br/pkg/restore/split/split.go
- br/pkg/restore/split/split_test.go
- br/pkg/utils/backoff.go
Issue Number: close https://github.com/pingcap/tidb/issues/42001
The operation of scanning regions from PD exceeds the retry time. The old backoff is 128s， the new one is 5min
Tests 
Side effects
Documentation
```release-note
Fix the issue, expand the backoff to scan regions from PD
```
> br: wait more time to wait spitting the region

- planner/core/exhaust_physical_plans.go
Issue Number: ref #31316  #41996
Slices are passed to `slices.Equal` without sorting caused by carelessness.
This won't cause any real problems. It just makes #41996 not as effective as expected.
Pass the ordered slice to `slices.Equal`.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix appropriate index stats may be missed when estimating NDV for inner side of index join

- br/pkg/restore/systable_restore.go
- br/tests/br_full_cluster_restore/full_data.sql
- br/tests/br_full_cluster_restore/run.sh
Issue Number: ref #42266
Because we decided not to support backup&restore resource control related data in v7.0, this PR try to remove the resource group meta in user_attributes.
Tests 
Side effects
Documentation
```release-note
None
```
> br: filter resource group in br full restore

- planner/core/plan_to_pb.go
Issue Number: close https://github.com/pingcap/tidb/issues/42303
Test with the case in https://github.com/pingcap/tiflash/issues/7079, the result is correct now.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: set correct key type of equal condition in pb for null-aware semi join

- distsql/distsql.go
- sessionctx/variable/BUILD.bazel
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/sysvar_test.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #42308
Add 3 session variable to set TiFlash's spill threshold by sql statement
Tests 
Side effects
Documentation
```release-note
None
```
> session,executor: add variables to support set tiflash spill threshold by sql statement

- ddl/backfilling.go
- ddl/column.go
- ddl/ddl.go
- ddl/index.go
- ddl/reorg.go
`reorgCtx.doneKey` is not used, let's remove it.
- Remove `reorgCtx.doneKey`.
- Extract the ingest reorg worker into a separate function.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: remove unused SetNextKey()

- executor/asyncloaddata/show_test.go
- executor/importer/import.go
- executor/importer/import_test.go
- executor/load_data.go
- executor/loadremotetest/multi_file_test.go
- parser/ast/dml_test.go
- server/server_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> executor: add default value for LOAD DATA batch size

- planner/core/expression_rewriter.go
- planner/core/hints.go
- planner/core/logical_plan_builder.go
- planner/core/planbuilder.go
- sessionctx/variable/session.go
Issue Number: close #42342
Tests 
Side effects
Documentation
```release-note
None
```
> session: data race at the PlannerSelectBlockAsName

- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
- util/ranger/detacher.go
Issue Number: close #42150
When rebuild range for `IndexFullScan`, if there is no filter on columns, the type slice may out of bound. There should be early stop logic facing this situation.
Return full range when build index full scan without filter cols
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix plan cache rebuild range error

- ddl/resource_group.go
- ddl/resourcegrouptest/BUILD.bazel
- ddl/resourcegrouptest/resource_group_test.go
- domain/infosync/info.go
- domain/infosync/resource_group_manager.go
- store/mockstore/unistore/pd.go
Issue Number: close https://github.com/pingcap/tidb/issues/42324
Bootstrap a TiDB with a keyspace-name, then bootstrap a TiDB without a keyspace-name
skip the `default` group exists error.
Tests 
```release-note
None
```
> ddl: skip exist error when create the default resource group

- br/pkg/restore/client.go
Issue Number: close #42157
As the issue has described, after encountered an error, we still try to fire new requests to the thread pool.
This PR would give up issuing new requests to the thread pool when there are failed tasks.
Tests 
This PR is really hard to test: perhaps we need to figure out a effective way to mock the `restore.Client`.
If you want to verify these changes, you may need to make a environment where download fail very slow. In our case, that is all S3 requests from TiKV has been rejected by a firewall just DROP TCP packets(also not send some RST packet). 
```release-note
Fixed a problem that made BR looks like be stuck when there are some network issues.
```
> br/restore: fail fast when meeting some error during restoration

- ddl/ddl_api.go
- executor/compact_table.go
- executor/infoschema_reader.go
- infoschema/tables.go
Issue Number: ref #42245
In https://github.com/pingcap/tidb/pull/41998, I modified `serverType` in `GetStoreServerInfo`, but there are several problems such as #42245. So I think it's better to only modify `serverType` in `dataForTiDBClusterInfo`.
Tests 
select * from information_schema.cluster_info;
alter table test.t1 set tiflash replica 1;
select count(*) from TIFLASH_TABLES;
select count(*) from TIFLASH_SEGMENTS;
alter table test.t1 compact tiflash replica ;
Side effects
Documentation
```release-note
None
```
> *:  Fix TiFlash serverType check in disaggregated mode

- ddl/db_change_test.go
- ddl/db_integration_test.go
- ddl/ddl_api.go
- ddl/index.go
- ddl/schematracker/dm_tracker.go
- executor/autoidtest/autoid_test.go
- planner/core/BUILD.bazel
- planner/core/integration_partition_test.go
- planner/core/preprocess.go
- planner/core/preprocess_test.go
Issue Number: close #40580
Remove the constraint for auto id column.
Tests 
Side effects
Documentation
```release-note
Remove the constraint that auto column must be defined as a key
```
> *: remove the constraint that auto column must be defined as a key | tidb-test=pr/2104

- br/pkg/lightning/importer/get_pre_info.go
- br/pkg/lightning/importer/precheck_impl.go
- br/pkg/lightning/importer/table_import_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/42354
Tests 
https://github.com/okJiang/tidb/actions/runs/4445667488/jobs/7805054954
Side effects
Documentation
```release-note
None
```
> Lightning: don't use pd port in tidb backend

- cmd/explaintest/r/tpch.result
- planner/core/exhaust_physical_plans.go
- statistics/integration_test.go
Issue Number: close #42351
#41996 itself provides a correct lower bound for the estimation.
But this change exposed the underestimation of the join size of (mi join it join ci) of JOB Q19D, and resulted in a plan change and therefore a performance regression.
We revert for now to avoid blocking the release and see how to improve it afterward.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: revert #41996 due to an execution plan regression in JOB workload

- DEPS.bzl
- go.mod
- go.sum
- store/copr/coprocessor.go
- store/copr/region_cache.go
Issue Number: close #42322
Currently, store batched coprocessor is not compatible with load-based replica read.
This PR makes them compatible.
Tests 
Side effects
Documentation
```release-note
None
```
> store/copr: batch replica read

- table/tables/BUILD.bazel
- table/tables/export_test.go
- table/tables/partition.go
- table/tables/partition_test.go
- table/tables/tables.go
Issue Number: ref #38535
Tests 
Side effects
Documentation
```release-note
None
```
> partition: Add extensive reorganize partition test

- executor/asyncloaddata/operate_test.go
Issue Number: close #42402
For default batch_size, the sleep time which failpoint injected is not enough
Tests 
Side effects
Documentation
```release-note
None
```
> test: fix flaky test due to forget to change batch size

- planner/core/BUILD.bazel
- planner/core/casetest/main_test.go
- planner/core/casetest/predicate_simplification_test.go
- planner/core/casetest/testdata/plan_suite_in.json
- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/casetest/testdata/predicate_simplification_in.json
- planner/core/casetest/testdata/predicate_simplification_out.json
- planner/core/logical_plan_builder.go
- planner/core/optimizer.go
- planner/core/plan.go
- planner/core/rule_predicate_simplification.go
Issue Number: ref #39676
TiDB optimizer has limited predicate simplifications and does not support many cases. One example is filtering redundant conditions across <> and In for same column. For example, a <> 1 and a in (1,2,3) can be simplified to a in (2,3). Also, a <> 5 and a in (1,2,3) can be simplified to a in (1,2,3) 
We added a new place holder logical rewrite optimization for predicate simplification. The general solution is 
1- Process all predicates as a set of ranges for all columns 
2- build equivalence classes for columns based col = col 
3- Merge all ranges of each equivalence class 
4- Build range predicates for each column in each equivalence class
This solution is on the optimizer roadmap and similar to what Teradata did …
> Optimizer: Fix Merge In and Not Equal ranges #39676

- expression/builtin_math_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/42420
math.Tan(math.Pi / 4)  equals 0.9999999999999998, not 1
Tests 
Side effects
Documentation
```release-note
None
```
> test:  fix ut TestTan due to math.Tan(math.Pi / 4) equals 0.9999999999999998, not 1

- planner/core/BUILD.bazel
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
Problem Summary: planner: add more test cases for non-prep plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for non-prep plan cache

- planner/core/prepare_test.go
- util/ranger/ranger.go
Issue Number: close #42439
Problem Summary: planner: fix incompatible behaviors between prep and non-prep statements when converting date/time values
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix incompatible behaviors between prep and non-prep statements when converting date/time values

- metrics/grafana/tidb.json
- metrics/metrics.go
- metrics/ttl.go
- ttl/metrics/metrics.go
- ttl/ttlworker/BUILD.bazel
- ttl/ttlworker/job_manager.go
- ttl/ttlworker/job_manager_integration_test.go
- ttl/ttlworker/job_manager_test.go
Issue Number: close #42466
Add two more charts for TTL in grafana:
- `Table Count By TTL Schedule Delay` shows table count in different deletion delays. A table's schedule delay is computed as `Max(0, now - lastJobTime - jobInterval)`
- `Table Count By TTL Schedule Delay` shows deleted/inserted rows for TTL table in days.
Tests 
Side effects
Documentation
```release-note
add more metrics for TTL in grafana
```
> ttl: add more metrics for TTL in grafana

- parser/model/ddl.go
- parser/model/ddl_test.go
Issue Number: close #42442
See the comments in https://github.com/pingcap/tidb/issues/42442:
> The root cause is that we didn't mark "reorganize partition" as ["need backfill"](https://github.com/pingcap/tidb/blob/42957c57e0cbf062ff7c5465e0e4a277ff788a6f/parser/model/ddl.go/#L759) so it is scheduled as the 'general job', and the 'general job' is scheduled in serial(always block each others).
This PR simply fixes this.
Tests 
Like #42442, concurrently run `CREATE TABLE` and `REORGANIZE PARTITION` in 2 sessions: 
```
session1(first)> alter table t1 reorganize partition p0, p1, p2, p3, p4 into( partition pnew values less than (10000000));
session2(second)> create table t01(a int, b int);
```
We can verify that `create table` will not be blocked anymore.
Side effects
- None …
> parser, ddl: correct the job type of 'REORGANIZE PARTITION'

- ddl/partition.go
- ddl/partition_test.go
- ddl/rollingback.go
Issue Number: close #42448
The reorganize partition job did not handle the cancel operation. After `admin cancel ddl jobs ...` command, DDL job will be set to cancelled directly without rolling back.
Do rolling back when job is cancelled by user.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix corrupted table meta after rollback a reorganize partition job

- executor/batch_point_get.go
- executor/point_get.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #28011
Problem Summary: as described in https://github.com/pingcap/tidb/issues/28011 , kv pairs converted from locks is visible to union-scan, which leads to duplicated rows (one from snapshot and the other from mem-index-reader).
Since https://github.com/tikv/tikv/issues/13694 has introduced a better solution to the problem of accumulated locks, thus we can simply revert #25730 .
[Here](https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7213372357103198046?from=1679493001&to=1679495159) is the benchmark result. It shows that there is a slight regression in point-get workload.
Tests 
Side effects
Documentation …
> executor: revert #25730 to fix #28011

- ddl/resourcegrouptest/resource_group_test.go
- domain/infosync/info.go
- domain/infosync/resource_group_manager.go
- executor/calibrate_resource.go
- executor/calibrate_resource_test.go
- meta/meta.go
- meta/meta_test.go
- session/bootstrap.go
- store/mockstore/unistore/pd.go
Issue Number: close #42403
In the old implementation, we init the default resource group via a ddl job after tidb is bootstraped. This has a compatible issue because there are some instances that is not upgraded, thus these instances can not recognise this ddl and upgrade can be stuck.
This change resolve this issue by init the `default` resource group when first init the resource group manager, after this change the default resource group is not persistented to the storage by default, but this is ok as tidb will create one in memory when the default is not exist. The pd side change is: https://github.com/tikv/pd/pull/6206. With these two changes, we can ensure the default resource group is always inited and there is no compatible issues.
Tests 
- After this change, I …
> resource_control: init default resource group without ddl

- ttl/metrics/metrics.go
Issue Number: close #42515
Tests 
Manually test steps:
1. start up a ttl server using this PR:
2. `curl http://127.0.0.1:10080/metrics | grep tidb_server_ttl_phase_time` , the metrics output:
```
tidb_server_ttl_phase_time{phase="begin_txn",type="delete_worker"} 0
tidb_server_ttl_phase_time{phase="begin_txn",type="scan_worker"} 0
tidb_server_ttl_phase_time{phase="check_ttl",type="delete_worker"} 0
tidb_server_ttl_phase_time{phase="check_ttl",type="scan_worker"} 0
tidb_server_ttl_phase_time{phase="commit_txn",type="delete_worker"} 0
tidb_server_ttl_phase_time{phase="commit_txn",type="scan_worker"} 0
tidb_server_ttl_phase_time{phase="dispatch",type="delete_worker"} 0
tidb_server_ttl_phase_time{phase="dispatch",type="scan_worker"} 0 …
```
> ttl: fix TTL cannot export metrics `tidb_server_ttl_phase_time`

- table/tables/tables.go
- tests/realtikvtest/sessiontest/session_fail_test.go
Issue Number: close #42426
Wrong assertion is set for `DELETE FROM sbtest1 WHERE id=502571;`
Tests 
Side effects
Documentation
```release-note
None
```
> table/tables: fix assertion protocol for partition reorganize

- ddl/partition.go
- statistics/handle/ddl.go
- statistics/handle/ddl_test.go
Issue Number: close #42180
The wrong partitions was sent to HandleDDL, for updating the statistics, resulting in error in HandleDDL background thread.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: Add the correct partitions to avoid error in updateGlobalStats

- executor/seqtest/prepared_test.go
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- planner/core/plan_cacheable_checker_test.go
- sessiontxn/txn_rc_tso_optimize_test.go
Problem Summary: planner: plan cache to support short insert statements
Can get some performance benefits:
```
23564             52102 ns/op
```
After
```
25329             48071 ns/op
```
Tests 
Side effects
Documentation
```release-note
None
```
> planner: plan cache to support short insert statements

- Makefile.common
- executor/adapter.go
- parser/digester.go
- parser/digester_test.go
- parser/lexer.go
- session/session.go
- util/sqlexec/restricted_sql_executor.go
Issue Number: close #42169
Plan hint will be redacted when enabling the log redaction in slow log files.
Add the hint as an item to the slow log files.
An example looks like this:
```
...
select /*+ use_index(t, primary) */ * from t use index (`primary`) where i = sleep(?);
```
Tests 
Side effects
Documentation
```release-note
None
```
> *: add plan hint to slow log files when redaction is enabled

- expression/function_traits.go
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- planner/core/plan_cacheable_checker_test.go
Problem Summary: planner: non-prep plan cache supports regular builtin-functions
planner: non-prep plan cache supports regular builtin-functions
Tests 
Side effects
Documentation
```release-note
None
```
> planner: non-prep plan cache supports regular builtin-functions

- Makefile.common
- distsql/select_result.go
Issue Number: close #42507
Tests 
Side effects
Documentation
```release-note
None
```
> distsql: misuse IsTelemetryEnabled in the selectResult.fetchResp

- metrics/metrics.go
- resourcemanager/pool/workerpool/BUILD.bazel
- resourcemanager/pool/workerpool/main_test.go
- resourcemanager/pool/workerpool/workerpool.go
- resourcemanager/pool/workerpool/workpool_test.go
Issue Number: close #42511
This PR supports a worker pool that can change workers dynamically by the resource manager.
Tests 
Side effects
Documentation
```release-note
None
```
> resourcemanager: support worker pool

- ddl/db_partition_test.go
- table/tables/index.go
Issue Number: close #42312
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix update global index return duplicate key error

- ddl/index_modify_test.go
Issue Number: close #42417
The subtask execution order is not guaranteed in distributed reorg. We need to disable it first before the test.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix unstable test TestAddIndexUniqueFailOnDuplicate

- metrics/grafana/tidb.json
Issue Number: ref #41203
Changes the panel to display user request related metrics by default, use the updated information from https://github.com/tikv/client-go/pull/723.
For example, the kv requests panel would no longer display internal request information by default.
- The kv request 99 by type panel
Before:
after:
The RPC layer latency panel
before:
after:
Tests 
Side effects
Documentation
```release-note
None
```
> metric: display the user metrics by default in transaction and kv panels

- DEPS.bzl
- go.mod
- go.sum
- store/driver/txn/txn_driver.go
Issue Number: close #42615
Requires https://github.com/tikv/client-go/pull/750
The `LockKeys` functions in txn_driver.go can be called concurrently in some case. However we added some fair locking related logic here, which is not protected by the mutex that's locked in `LockKeys` of client-go: if locking more than one key, exit fair locking mode. 
Tests 
Side effects
Documentation
```release-note
None
```
Release note not needed since the bug is just introduced in 7.0
> txn: Fix data race of checking and exiting fair locking concurrently in LockKeys (#42635)

- store/gcworker/gc_worker.go
Issue Number: Ref #42410
Mock store may not support engine type query which leads to decode error.
Ignore the error and treat it as raft-kv version 1.
Tests 
```release-note
None
```
> gc_worker: remove hex decode for the result of acquring engine type

- executor/batch_point_get.go
- executor/point_get.go
- go.mod
- go.sum
- session/txn.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: ref #28011
Problem Summary: as described in https://github.com/pingcap/tidb/issues/28011 , kv pairs converted from locks is visible to union-scan, which leads to duplicated rows (one from snapshot and the other from mem-index-reader).
Instead of writing membuf directly, cache locked key-value pairs that might be converted to PUT separately, and merge them on commit.
Tests 
Side effects
Documentation
```release-note
None
```
> executor,session: reimplement lock->put by `SetLockedKeyValue`

- dumpling/export/sql_type.go
- dumpling/tests/rows/run.sh
Issue Number: close https://github.com/pingcap/tidb/issues/42620
Add unsigned type in integer.
Tests 
Side effects
- None
Documentation
- None
```release-note
dumpling: fix the problem that unsigned integer field can't be used for splitting chunks
```
> dumpling: fix unsigned integer field split problem

- expression/builtin_other_test.go
- expression/constant.go
- expression/util.go
- planner/core/expression_rewriter.go
- planner/core/plan_cache_param.go
- planner/core/plan_cache_test.go
- server/conn_stmt.go
- types/etc.go
- types/field_type.go
Problem Summary: planner: initialize charset, collation and repertoire correctly for parameter values
1. Initialize charset and collation when inferring types of parameters;
2. Initialize repertoire when creating constants from parameters;
Tests 
Side effects
Documentation
```release-note
None
```
> planner: initialize charset, collation and repertoire correctly for parameter values | tidb-test=pr/2108

- disttask/framework/dispatcher/dispatcher_test.go
- disttask/framework/proto/task.go
- disttask/framework/storage/table_test.go
- disttask/framework/storage/task_table.go
- session/bootstrap.go
- session/bootstrap_test.go
Issue Number: close #42610
A new column `task_key` added to system table `mysql.tidb_global_task`. The `task_key` is defined as unique and defined by user. User can use this field to avoid submitting the duplicated tasks in recover logic.
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: Add `task_key` column to `mysql.tidb_global_task`

- util/cgroup/cgroup.go
- util/cgroup/cgroup_mock_test.go
Issue Number: close #42659
the root cause of this problem is that some container name contain the special symbol. it will lead to get the wrong cgroup path.
Tests 
Side effects
Documentation
```release-note
None
```
> cgroup: fix the path problem due to special containor name

- ddl/backfilling.go
Issue Number: close #42653
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: make waitGroup.Done() the last function to be called

- ddl/BUILD.bazel
- ddl/backfilling.go
- ddl/backfilling_scheduler.go
- ddl/dist_backfilling.go
- ddl/export_test.go
- ddl/index.go
- ddl/index_cop.go
- ddl/index_cop_test.go
- ddl/index_merge_tmp.go
- ddl/ingest/backend.go
- ddl/ingest/engine.go
- ddl/ingest/engine_mgr.go
- ddl/ingest/mem_root.go
- ddl/reorg.go
- resourcemanager/pool/workerpool/workerpool.go
This is a refactoring PR, let's skip the issue check.
This PR extracts `backfillScheduler` to an interface:
```go
// backfillScheduler is used to manage the lifetime of backfill workers.
type backfillScheduler interface {
setupWorkers() error
close(force bool)
sendTask(task *reorgBackfillTask) error
drainTasks()
receiveResult() (*backfillResult, bool)
setMaxWorkerSize(maxSize int)
currentWorkerSize() int
adjustWorkerSize() error
}
```
There are two implementations: 
- `txnBackfillScheduler`: the transaction way to backfill data.
- `ingestBackfillScheduler`: the ingest way to backfill data.
Tests 
Side effects
Documentation …
> ddl: reimplement the backfill scheduler

- infoschema/infoschema.go
- table/temptable/BUILD.bazel
- table/temptable/infoschema.go
- table/temptable/intergration_test.go
Issue Number: close #42563
It will also close #42307 because it will no longer modify the information schema in session.
Tests 
Side effects
Documentation
```release-note
fix select temporary table with view will panic problem
```
> infoschema: fix select temporary table with view will panic problem

- parser/terror/terror_test.go
Issue Number: close  https://github.com/pingcap/tidb/issues/42557
FAIL TestTraceAndLocation when run with go test. 
```
if strings.Contains(line, goroot) || strings.Contains(line, "GOROOT") || strings.Contains(line, "runtime.goexit") {
sysStack++
}
```
when you run test case in the bazel. the stack looks like this:
``` go 
testing.tRunner
GOROOT/src/testing/testing.go:1576
runtime.goexit
src/runtime/asm_arm64.s:1172
```
the sysStack
```
GOROOT/src/testing/testing.go:1576
runtime.goexit
```
but run with go test.  the stack looks like this:
```
testing.tRunner
/Users/pingcap/.gvm/gos/go1.20.1/src/testing/testing.go:1576
runtime.goexit
/Users/pingcap/.gvm/gos/go1.20.1/src/runtime/asm_arm64.s:1172
```
the sysStack
``` …
```
> test: fix ut TestTraceAndLocation when run with go test

- metrics/grafana/tidb.json
Issue Number: close #42562
Duplicated id 234 of "Ignore Event Per Minute" and "Stats Cache LRU Cost" panels caused them to be displayed abnormally, sometimes disappeared and sometimes there with expressions confused with each other. The fix is to assign them different ids.
The "Ignore Event Per Minute" and "Stats Cache LRU Cost" panels should be displayed normally with the fix.
Tests 
The "Ignore Event Per Minute" and "Stats Cache LRU Cost" panels should be displayed normally with the fix.
Side effects
None
Documentation
None
```release-note
Fix the issue that "Ignore Event Per Minute" and "Stats …
```
> metrics: fix duplicated "id": 234 in tidb.json

- util/sqlexec/utils.go
- util/sqlexec/utils_test.go
Support use customized type whose underlying type is intXXX, uintXXX, floatXX, bool, string in `ExecuteSQL`. Typically this can make ease of using customized enum type when `ExecuteSQL`.
Tests 
benchmark
at 2137ff3974d9bcf3a90683f72f682d7423cdb3c0
```
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/util/sqlexec
BenchmarkEscapeString
BenchmarkEscapeString-8       	 4011201	       292.8 ns/op
BenchmarkUnderlyingString
BenchmarkUnderlyingString-8   	 3403500	       351.3 ns/op
BenchmarkEscapeInt
BenchmarkEscapeInt-8          	 6085053	       196.5 ns/op
BenchmarkUnderlyingInt
BenchmarkUnderlyingInt-8      	 4736172	       253.8 ns/op
```
at master
```
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/util/sqlexec
BenchmarkEscapeString …
```
> util/sqlexec: EscapeSQL support resolve some underlying type

- executor/importer/BUILD.bazel
- executor/importer/import.go
- executor/importer/import_test.go
- executor/load_data.go
- executor/loadremotetest/multi_file_test.go
Tests 
a simple test shows concurrent writing improves the performance indeed. tiup playground, 1G data, 4 indexes
- LOAD DATA thread = 1: **9min 28s**
- lightning default thread = #CPU core: **6min 0s**
- LOAD DATA thread = #CPU core: **4min 52s**
however, during the lightning test my OS is very slow, I will deploy a cluster to test it later.
Side effects
Documentation
```release-note
None
```
> loaddata: support concurrent writing to TiKV

- executor/adapter.go
- executor/insert_common.go
- executor/update_test.go
- executor/write.go
- parser/model/model.go
- sessionctx/variable/session.go
Issue Number: close #36438
Problem Summary: Only row keys will be locked after updates (without changing handle), which leads to https://github.com/pingcap/tidb/issues/36438. We tried to solve the issue by https://github.com/pingcap/tidb/pull/36498, however it has been reverted because of the issue of accumulated locks. Since the optimizition described in https://github.com/tikv/tikv/issues/13694 is done, we can now solve the issue again.
Also collect untouched unique keys and lock them.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: lock untouched unique keys on update

- br/pkg/lightning/config/config.go
- br/pkg/lightning/mydump/BUILD.bazel
- br/pkg/lightning/mydump/charset_convertor.go
- executor/loadremotetest/one_csv_test.go
close #42704
Tests 
Side effects
Documentation
```release-note
None
```
> loaddata, lightning: support ascii, latin1, utf8 charset of source file

- executor/analyze_col_v2.go
- executor/analyze_fast.go
- executor/builder.go
- executor/show_stats.go
- planner/core/casetest/integration_test.go
- planner/core/logical_plan_builder.go
- planner/core/logical_plans.go
- planner/core/stats.go
- planner/core/tiflash_selection_late_materialization.go
- statistics/handle/bootstrap.go
- statistics/handle/ddl_test.go
- statistics/handle/dump.go
- statistics/handle/dump_test.go
- statistics/handle/handle.go
- statistics/handle/handletest/handle_test.go
- statistics/handle/internal/testutil.go
- statistics/handle/update.go
- statistics/handle/updatetest/update_test.go
- statistics/histogram.go
- statistics/histogram_test.go
- statistics/index.go
- statistics/interact_with_storage.go
- statistics/selectivity.go
- statistics/selectivity_test.go
- statistics/statistics_test.go
- statistics/table.go
Issue Number: ref #42160
Rename `Table.Count` to `Table.RealtimeCount`. We hope to distinguish between `RealtimeCount` and `AnalyzeCount`(which will be introduced by the following PRs).
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: rename Table.Count to Table.RealtimeCount

- parser/lexer.go
- parser/misc.go
Issue Number: close #42763
With the help of AI, we become stronger.
Subtitle: ChatGPT teach me how to write better code.
It's amazing!
ChatGPT is right in this case, except for two tiny mistakes:
1. He advise to change this:
```
for i := 0; i < len(lit); i++ {
if lit[i] >= 'a' && lit[i] <= 'z' {
data[i] = lit[i] + 'A' - 'a'
} else {
data[i] = lit[i]
}
}
```
to
```
for i, c := range lit {
if c >= 'a' && c <= 'z' {
data[i] = c + 'A' - 'a'
} else {
data[i] = c
}
}
```
The for-range loop reduce the temporary object declaration avoid repeated lit[i], making better chance for the compiler to generate more optimized code.
**However, the semantic for this code changes.** 
When for-range over a string, `c` is a rune, while in the original code it's iterating the string as bytes. …
> parser: a tiny function optimization follow the advise by ChatGPT

- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/dispatcher/dispatcher_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/42791
```
[2023/04/04 13:40:01.880 +08:00] [INFO] [dispatcher.go:381] ["process normal flow"] ["task ID"=2] [state=pending] [concurrency=0] [subtasks=10]
[2023/04/04 13:40:02.060 +08:00] [INFO] [dispatcher.go:217] ["check task, subtasks aren't finished"] ["task ID"=1] [cnt=10]
[2023/04/04 13:40:02.185 +08:00] [INFO] [dispatcher.go:217] ["check task, subtasks aren't finished"] ["task ID"=1] [cnt=10]
[2023/04/04 13:40:02.252 +08:00] [INFO] [dispatcher.go:217] ["check task, subtasks aren't finished"] ["task ID"=1] [cnt=10]
[2023/04/04 13:40:02.319 +08:00] [INFO] [dispatcher.go:217] ["check task, subtasks aren't finished"] ["task ID"=1] [cnt=10]
[2023/04/04 13:40:02.482 +08:00] [INFO] [dispatcher.go:186] ["dispatch …
```
> disttask: make TestParallelErrFlow more stable

- expression/builtin_miscellaneous.go
Issue Number: close #35155
The error is not always terror  `errors.Cause(err).(*terror.Error)`.
The expected error in the test is `mysql.ErrLockWaitTimeout`, but sometimes the error got is 
`errors.New("pessimistic lock retry limit reached")` which is not a terror.
So the assumption cause panic.
```
--- FAIL: TestGetLock (1.88s)
panic: interface conversion: error is *errors.fundamental, not *errors.Error [recovered]
panic: interface conversion: error is *errors.fundamental, not *errors.Error [recovered]
panic: interface conversion: error is *errors.fundamental, not *errors.Error
goroutine 100 [running]:
testing.tRunner.func1.2({0x48b9d40, 0xc006f54f90})
/home/genius/project/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1() …
```
> expression: make expression TestGetLock test more stable

- ddl/ingest/config.go
Issue Number: ref #35983
Config should reflect the real behaviour, so other logic like "shouldCheckWriteStall" can work
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: set lightning cron config to real behaviour

- parser/ast/dml.go
- parser/format/format.go
- planner/core/plan_cache_param.go
- planner/core/plan_cache_param_test.go
Problem Summary: planner: keep original select fields names for non-prep plan cache
```
Before:
BenchmarkParameterizeSelect-8             325916              3584 ns/op
BenchmarkParameterizeInsert-8             403291              2792 ns/op
After:
BenchmarkParameterizeSelect-8             363246              3140 ns/op
BenchmarkParameterizeInsert-8             489097              2378 ns/op
```
Tests 
Side effects
Documentation
```release-note
None
```
> planner: keep original select fields names for non-prep plan cache

- executor/explain_test.go
- planner/core/plan_cache_param.go
- planner/core/plan_cache_param_test.go
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- planner/core/plan_cacheable_checker_test.go
Problem Summary: planner: non-prep plan cache to support limit clauses
planner: non-prep plan cache to support limit clauses
Tests 
Side effects
Documentation
```release-note
None
```
> planner: non-prep plan cache to support limit clauses

- util/rowcodec/common.go
- util/rowcodec/encoder.go
- util/rowcodec/row.go
- util/rowcodec/rowcodec_test.go
Issue Number: ref #42747
Problem Summary: see #42747 
Add checksum-related utilities in tidb.
- add `Encoder.WithChecksum` to enable/disable checksum.
- add `Encoder.Checksum()` to calculate the checksum of input datums.
- add `Encoder.EncodeWithExtraChecksum()` to append extra checksum to the row value. (the extra checksum is calculated by `Encoder.Checksum()`)
- let row codec export `GetChecksum/GetExtraChecksum` to access the checksum info encoded in the row value.
Tests 
Side effects
Documentation
```release-note
None
```
> util: extend row format with checksum

- store/driver/tikv_driver.go
Issue Number: ref #42778 
- since this pr is more like a extra fix of #42778, so will not add release-note
Tests 
- create store without real-tikv, check it can fail with err
Side effects
Documentation
```release-note
None
```
> store: fix panic when failed to create pdclient

- expression/function_traits.go
- parser/parser.y
- planner/core/metrics/metrics.go
- planner/core/plan_cache_param_test.go
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
Problem Summary: planner: add more metrics for non-prep plan cache
1. add a new metric to measure which can help measure the extra overhead of non-prep plan cache;
2. set the original text even if Field.As is not nil;
3. uncache some special TiDB functions;
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add more metrics for non-prep plan cache

- util/gpool/spmc/spmcpool_test.go
Issue Number: close #42721
**There is a dead loop in the code**, so if there is only 1 cpu, it depends on the preempt scheduling to break the loop.
And even the loop break, which goroutine to run next is choosed by (maybe random) chance.
Here is a simpler reproduce:
```
func TestXXX(t *testing.T) {
for i:=0; i<500; i++ {
exitCh := make(chan struct{})
sema := make(chan struct{}, 10)
go func() {
for i:=0; i<10000; i++{
sema <- struct{}{}
}
close(exitCh)
}()
f := func() {
for {
select {
case <-sema:
return
default:
select {
case <-exitCh:
return
default:
}
}
}
}
f()
}
}
```
```
genius@genius-System-Product-Name:~/project/src/sss$ go test  -cpu 16 -run TestXXX
PASS
ok      sss     0.042s
genius@genius-System-Product-Name:~/project/src/sss$ go test  -cpu 8 -run TestXXX
PASS
ok …
```
> util/gpool/spmc: make test case TestBenchPool stable

- ddl/internal/session/BUILD.bazel
- ddl/internal/session/session_pool.go
- ddl/internal/session/session_pool_test.go
- testkit/BUILD.bazel
- testkit/mocksessionmanager.go
Issue Number: close #42895
The session used by the internal transaction of DDL is not added to the session manager (`StoreInternalSession`), which causes the min start TS reporter to be unaware of the DDL transaction when updating the metadata on etcd, so that GC safepoint will move forward, which will further lead to the failure of the DDL transaction.
This problem will be more obvious when the DDL transaction takes a long time to execute, especially when creating index in ingest mode. If the import process takes more than 10 minutes, it will almost certainly trigger this error.
Add the DDL session to the session manager.
Tests 
```
[2023/04/10 16:53:58.872 +08:00] [INFO] [local.go:1394] ["put job back to jobCh to retry later"] …
```
> ddl: include ddl sessions in session manager's internal list

- ddl/stat_test.go
- executor/executor.go
Issue Number: close #42268
Cherry-pick https://github.com/pingcap/tidb/pull/42904 manually for 6.5 branch
Tests 
Side effects
Documentation
```release-note
Fix a bug that table name in 'admin show ddl jobs' is missing for ongoing drop table operation
```
> *: fix bug that table name in 'admin show ddl jobs' is missing for ongoing drop table operation #42904

- ddl/stat_test.go
- executor/executor.go
Issue Number: close #42268
During drop table, the table is removed from the infoschema
So `getTableName` found nothing.
This cause the missing of the table name in 'admin show ddl jobs' result.
On the master branch, we can get the table name by `job.TableName`.
For older tidb, there is no `TableName` field, we need some other way to fix it.
Tests 
Side effects
Documentation
```release-note
Fix a bug that table name in 'admin show ddl jobs' is missing for ongoing drop table operation
```
> *: fix bug that table name in 'admin show ddl jobs' is missing for ongoing drop table operation

- statistics/column.go
- statistics/handle/bootstrap.go
- statistics/handle/handle.go
- statistics/handle/handle_hist.go
- statistics/handle/update.go
- statistics/handle/updatetest/update_test.go
- statistics/histogram.go
- statistics/index.go
- statistics/interact_with_storage.go
- statistics/table.go
Issue Number: ref #42160
1. Introduce `IsAnalyzed` and `StatsCollected` to improve encapsulation.
2. Make `TableAnalyzed` more precise.
3. Make `(StatsLoadedStatus).IsLoadNeeded` more precise.
4. Make `(*Table).GetColRowCount` neat.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: refine index/column stats methods

- bindinfo/handle.go
Issue Number: close #42333
Read access:
https://github.com/pingcap/tidb/blob/a0e6ccb4e5a7ab62f253e6143700350aa27d1997/bindinfo/handle.go#L931-L938
Write access:
https://github.com/pingcap/tidb/blob/a0e6ccb4e5a7ab62f253e6143700350aa27d1997/bindinfo/handle.go#L216-L227
We should lock for both **read** and **write** access of the field that being protected.
Omitted.
Tests 
Side effects
Documentation
```release-note
None
```
> bindinfo: lock before reading session ctx from BindHandle

- sessiontxn/isolation/base.go
Issue Number: close #42092
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix data race in the baseTxnContextProvider.ActivateTxn

- table/table.go
- table/tables/cache.go
Issue Number: close #42925
Before this change, `UpdateLockForRead` work in a blocking way:
Read operation from all the sessions wait on this operation to continue.
It's unnecessary, and when there are many tidb instances, update lock meta information conflicts a lot, result int long waiting.
In fact, it's safe to change `UpdateLockForRead` to non-waiting, the read will just skip the cache for this time.
The session does not need to block on it.
Tests 
Side effects
Documentation
```release-note
None
```
> table: fix transaction conflict on cached table's read lock updating caused long block

- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
Issue Number: close #42975
Problem Summary: planner: skip caching too large plan for plan cache
Add 2 more strategies to prevent OOM caused by plan cache:
1. if the `in-list` is too long like `where a in (1, 2, ..., 10000)`, skip caching this plan;
2. if the final plan memory usage is large than `2MB`, skip caching this plan;
Tests 
Side effects
Documentation
```release-note
None
```
> planner: skip caching too large plan for plan cache

- statistics/handle/BUILD.bazel
- statistics/handle/dump.go
- statistics/handle/dump_test.go
Issue Number: close #42931
When v4.0.x and earlier versions dump stats json, stats json doesn't contain `StatsVer`. Before the PR, when we find stats json does not contain `StatsVer`, we just simply set its `StatsVer` to 1. Another fact is that we use `StatsVer != 0` to decide whether stats are collected(i.e., analyze has been executed). Setting `StatsVer` to 1 for stats json from old versions makes us unable to distinguish whether stats are collected or not. Hence, after the PR, when we find stats json does not contain `StatsVer`, we check `NDV > 0 || NullCount > 0` to decide whether stats are collected. If stats are collected, we set its `StatsVer` to 1, otherwise we set its `StatsVer` to 0.
Tests 
Side effects
Documentation …
> staistics: fix load stats from old version json | tidb-test=pr/2114

- parser/format/format.go
- planner/core/plan_cache_param.go
Problem Summary: planner: optimize the parameterization performance for non-prep plan cache
4X faster and 6X less memory allocation after this optimization:
```
Before
BenchmarkParameterizeInsert-8             420446              2722 ns/op            1144 B/op         61 allocs/op
After
BenchmarkParameterizeInsert-8            1760029               678.6 ns/op           176 B/op          4 allocs/op
```
Tests 
Side effects
Documentation
```release-note
None
```
> planner: optimize the parameterization(parser.Restore) performance for non-prep plan cache

- br/pkg/lightning/backend/local/local_freebsd.go
Issue Number: close #43014 
Basically `Rlim_t` was renamed to `RlimT` `local_unix.go` and `local_unix_generic.go` but not in `local_freebsd.go`.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: Fix build failure on FreeBSD

- server/conn_stmt.go
close https://github.com/pingcap-inc/security-sevices/issues/12
See https://github.com/pingcap-inc/security-sevices/issues/12 for more details.
Tests 
See https://github.com/pingcap-inc/security-sevices/issues/12 for the test steps.
Side effects
Documentation
```release-note
None
```
> server: normalize SQL of execute command in logs when redaction enabled

- ddl/ddl.go
Issue Number: close #42987
The job is modified in another goroutine at line 1055, and it is read at line 1060.
https://github.com/pingcap/tidb/blob/c1ce67d7eaa32c79ad2e7564fc2ef0261f03f902/ddl/ddl.go#L1054-L1067
We should wait for `limitJobCh`'s modification before reading the job.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: sync the job access in failpoint mockParallelSameDDLJobTwice

- planner/core/BUILD.bazel
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: ref #42975
Problem Summary: planner: introduce a new variable to control the maximum size of plans that can be cached
planner: introduce a new variable to control the maximum size of plans that can be cached
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce a new variable to control the maximum size of plans that can be cached

- sessionctx/sessionstates/session_states.go
- sessionctx/sessionstates/session_states_test.go
- sessionctx/variable/session.go
Issue Number: close #42884
#41722 introduced `set resource group` but session states don't encode it.
Encode resource group into session states.
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: support encoding resource group name into session states

- server/conn.go
Issue Number: close #39664
The error is throw from the `Preprocess()` in the `prefetchPointPlanKeys`.
`prefetchPointPlanKeys` is quite tricky, it does not reuse the common code path for the sake of performance.
**Premature optimization is the root of all evil**.
This tricky optimization helped us improve the performance by 100 times and won the deal, and now it's time to pay the (technical) debt.
Tests 
Side effects
Documentation
```release-note
None
```
> server: ignore Preprocess error for the `prefetchPointPlanKeys` optimization

- executor/builder.go
- executor/index_merge_reader.go
- executor/index_merge_reader_test.go
- planner/core/casetest/physical_plan_test.go
- planner/core/casetest/testdata/plan_suite_in.json
- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/explain.go
- planner/core/find_best_task.go
- planner/core/physical_plans.go
- planner/core/task.go
Issue Number: ref https://github.com/pingcap/tidb/issues/41028
Tests 
Side effects
Documentation
```release-note
None
```
> executor, planner: support indexMerge limit embeded with non partition table

- planner/core/casetest/integration_test.go
- planner/core/casetest/testdata/integration_suite_out.json
- planner/core/stats.go
- statistics/column.go
- statistics/handle/bootstrap.go
- statistics/handle/dump.go
- statistics/handle/dump_test.go
- statistics/handle/handle.go
- statistics/handle/handle_hist.go
- statistics/handle/handletest/handle_test.go
- statistics/handle/internal/testutil.go
- statistics/integration_test.go
- statistics/interact_with_storage.go
Issue Number: ref #42160
Remove `statistics.Column.Count`. 
Before the PR, in order to maintain `statistics.Column.Count`, we need to read `mysql.stats_top_n` and `mysql.stats_buckets` for each column when init stats, which is time-consuming. On the other hand, the usage of `statistics.Column.Count` is limited. We modify `(*DataSource).getColumnNDV` to get rid of `statistics.Column.Count`.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: remove statistics.Column.Count

- util/globalconn/BUILD.bazel
- util/globalconn/globalconn.go
- util/globalconn/pool.go
- util/globalconn/pool_test.go
Issue Number: ref #8854
Problem Summary: Support CTRL-C or kill to kill a connection/query by implementing global connection IDs.
(This PR is split from #25385  to reduce PR size)
- Implement a simple ID pool (`AutoIncPool`) for 64 bits connection IDs.
- Implement a lock-free ring buffer for 32bits local connection ID allocation.
Tests 
```bash
❯ go test -v -count 100 -run TestLockFreePoolConcurrencySafety github.com/pingcap/tidb/util/globalconn
ok  	github.com/pingcap/tidb/util/globalconn	122.269s
❯ go test -race -count 10 github.com/pingcap/tidb/util/globalconn
ok  	github.com/pingcap/tidb/util/globalconn	507.211s
```
```
go test -benchmem -run=^$ -tags intest,deadlock -bench ^BenchmarkPoolConcurrency$ github.com/pingcap/tidb/util/globalconn
goos: linux
goarch: amd64
pkg: …
```
> util: ID pools for global kill 32bit

- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/region_job.go
- br/pkg/lightning/backend/local/region_job_test.go
Issue Number: close #43055
Tests 
without this fix, the newly added UT fails (I added a panic when error is not nil)
```
panic: write to tikv with no leader returned, region '1', leader: 0
```
Side effects
Documentation
```release-note
None
```
> lightning: always retry from needRescan when NotLeader

- types/datum.go
- util/ranger/ranger_test.go
- util/ranger/types.go
Issue Number: ref  #43045
Tests 
Tested as in the issue.
Side effects
Documentation
```release-note
None
```
> planner: escape the string when display `Range` to make it more clear | tidb-test=pr/2116

- expression/builtin_encryption_vec.go
- expression/integration_test/integration_test.go
Issue Number: close #43063
Tests 
Side effects
Documentation
```release-note
fix index out of range for `AES_DECRYPT`
```
> expression: fix index out of range for `AES_DECRYPT`

- executor/oomtest/oom_test.go
Issue Number: close #43119
Tests 
Side effects
Documentation
```release-note
None
```
> oomtest: fix data race at the oomCapture

- planner/core/plan_cache_lru.go
Problem Summary: planner: make `LRUPlanCache.Close` reenterable
make `LRUPlanCache.Close` reenterable, otherwise the relevant metrics can be negative unexpectedly.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: make `LRUPlanCache.Close` reenterable

- cmd/pluginpkg/pluginpkg.go
Some plugin names like `tidb-audit-log` would be invalid due to the limitation that the plugin name contains '-'.
Remove this limitation.
Tests 
- prepare a plugin named `tidb-audit-log`, then use `pluginpkg` to package it.
Side effects
Documentation
```release-note
None
```
> pluginpkg: remove the limitation of the plugin name

- planner/core/fragment.go
Issue Number: close #43137
Tests 
Side effects
Documentation
```release-note
None
```
> mpp: set recoveryTTL of tiflash_compute node as zero

- executor/set_test.go
- session/bootstrap.go
- session/session.go
- sessionctx/variable/session.go
- sessionctx/variable/session_test.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Problem Summary: planner: introduce a new variable `tidb_session_plan_cache_size`
planner: introduce a new variable `tidb_session_plan_cache_size`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce a new variable `tidb_session_plan_cache_size`

- util/rowcodec/BUILD.bazel
- util/rowcodec/bench_test.go
- util/rowcodec/common.go
- util/rowcodec/encoder.go
- util/rowcodec/row.go
- util/rowcodec/rowcodec_test.go
Issue Number: ref #42747
We have implemented row level checksum utilities in #42859. However, it doesn't match the requirements for e2e checksum verification, because downstream consumers cannot calculate the checksum as tidb does. So, we reimplement checksum algorithm in this PR.
Tests 
Side effects
The overhead of checksum calculation shall be fine.
```
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/util/rowcodec
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkChecksum
BenchmarkChecksum-16                    16851555                68.72 ns/op            0 B/op          0 allocs/op
BenchmarkEncode
BenchmarkEncode-16                      15039044                82.57 ns/op            0 B/op          0 allocs/op
```
Documentation
Please refer to [Release …
> util: reimplement row level checksum utilities

- errno/errname.go
- plugin/helper.go
After https://github.com/pingcap/tidb/pull/43125, the plugin name can contain `-`. But we still check the plugin name when loading it.
Remove the checking.
Tests 
- load a plugin named `tidb-audit-log-1`, where the name is `tidb-audit-log` and version is `1`
Side effects
Documentation
```release-note
None
```
> plugin: remove the limitation of decoding a plugin name

- planner/core/plan_cache_param.go
- planner/core/plan_cache_param_test.go
Problem Summary: planner: optimize the performance of `GetParamSQLFromAST` for non-prep plan cache
planner: optimize the performance of `GetParamSQLFromAST` for non-prep plan cache
1.5X faster and 2X less allocs:
```
Before:
BenchmarkGetParamSQL-8            758413              1486 ns/op            2809 B/op         13 allocs/op
After:
BenchmarkGetParamSQL-8           1282550               927.4 ns/op           248 B/op          5 allocs/op
```
Tests 
Side effects
Documentation
```release-note
None
```
> planner: optimize the performance of `GetParamSQLFromAST` for non-prep plan cache

- br/pkg/restore/split.go
- br/pkg/restore/split_test.go
Issue Number: close #42924
When restoring tables, for optimization, we are not going to split between tables:
(Referencing #27240)
```
before：
--|-------t1 data-------|-----|---t2 data-------|
after: 
----------t1 data-------|---------t2 data-------|
Legends:
'|' the split point
'-' the key space
```
This works fine as long as we are restoring tables sequentially and restoring tables after we finish splitting. However, for now, in some scenarios:
1. t2 starts its restoration, importing file to the very left region.
2. t1 starts its restoration too, and split region from left to right -- the table may be huge and take a long time to split the regions.
3. Newly split regions will be born from the very right region of `t1`, i.e. the very left region of `t2`. Which means... …
> restore: split between tables

- planner/core/casetest/physical_plan_test.go
- planner/core/casetest/testdata/plan_suite_in.json
- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/exhaust_physical_plans.go
Issue Number: close #43062  
https://github.com/pingcap/tiflash/issues/7280
Tests 
Side effects
Documentation
```release-note
Improve semi join and anti semi join performance of MPPTasks when left table has smaller size than right table.
```
> plan: Choose left table as build table for semi join when left one is smaller for MPPTask

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- executor/importer/table_import.go
Issue Number: close https://github.com/pingcap/tidb/issues/42456
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix generating region job is serialized

- executor/builder.go
- executor/distsql.go
- executor/distsql_test.go
- executor/index_merge_reader.go
- executor/table_reader.go
- store/copr/coprocessor.go
Issue Number: close #43144
cherry-pick of #43146
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix Request range exceeds bound error for partition table (#43146)

- planner/core/plan_cache.go
- planner/core/plan_cache_param.go
- planner/core/plan_cache_test.go
- planner/core/plan_cache_utils.go
Problem Summary: planner: performance optimization for plan-cache
planner: performance optimization for plan-cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: performance optimization for plan-cache

- br/pkg/backup/push.go
- br/pkg/utils/misc.go
Issue Number: close #42973
The current implementation cannot detect whether a store is down. So it keeps retry sending request to an offline store.
This PR checks the `LastHeartbeatTS` of the store and give up to request the store once the gap is greater than 20s (also defined in the PD package.)
Tests 
Backup over a cluster with one node down, finished in reasonable time.
```release-note
Fixed a bug that caused backup get very slow when there are down TiKV nodes in the cluster.
```
> backup: check the store state by last heartbeat

- ddl/BUILD.bazel
- ddl/ddl_api.go
- executor/adapter.go
- executor/analyze_utils.go
- executor/analyzetest/BUILD.bazel
- executor/analyzetest/analyze_test.go
- executor/compiler.go
- executor/executor_test.go
- executor/fktest/BUILD.bazel
- executor/fktest/foreign_key_test.go
- executor/index_merge_reader_test.go
- executor/issuetest/executor_issue_test.go
- executor/jointest/BUILD.bazel
- executor/jointest/join_test.go
- executor/partition_table_test.go
- executor/tiflashtest/BUILD.bazel
- executor/tiflashtest/tiflash_test.go
- executor/unstabletest/unstable_test.go
- infoschema/cluster_tables_test.go
- server/conn.go
- session/sessiontest/session_test.go
- util/memory/action.go
- util/memory/tracker.go
Issue Number: close #42044
As described in the issue description.
Tests 
Side effects
Documentation
```release-note
Refine the error message when a query is killed because of exceeding the memory limit. When a query is killed because of exceeding `tidb_mem_quota_query`, error message `Your query has been cancelled due to exceeding the allowed memory limit for a single SQL query. Please try narrowing your query scope or increase the tidb_mem_quota_query limit and try again.` will be returend. When a query is killed because of the instance memory exceeds `tidb_server_memory_limit`, error message …
```
> *: format the error message when query/instance exceeds memory quota

- planner/core/casetest/integration_test.go
- planner/core/casetest/testdata/integration_suite_in.json
- planner/core/casetest/testdata/integration_suite_out.json
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #43169
- Add a new system variable `tidb_opt_fix_control`
- Add the corresponding field of type `map[uint64]string` to `SessionVars` 
Tests 
Side effects
Documentation
```release-note
None
```
> planner, sessionctx: add `tidb_opt_fix_control` variable

- br/pkg/lightning/mydump/BUILD.bazel
- br/pkg/lightning/mydump/region.go
- br/pkg/lightning/mydump/region_test.go
Issue Number: close #43195
use error group and sync.Map to refine the logic
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix MakeTableRegions may panic when context is canceled

- ttl/sqlbuilder/sql.go
- ttl/sqlbuilder/sql_test.go
- ttl/ttlworker/scan_test.go
Issue Number: close #43206
Tests 
Side effects
Documentation
```release-note
ttl: use `SQL_NO_CACHE` to skip tikv block cache for TTL scan queries
```
> ttl: use `SQL_NO_CACHE` to skip tikv block cache for TTL scan queries

- planner/core/plan_cache_param.go
- planner/core/plan_cache_param_test.go
Problem Summary: planner: fix unsafe sync.Pool used in non-prep plan cache
planner: fix unsafe sync.Pool used in non-prep plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix unsafe sync.Pool used in non-prep plan cache

- executor/stale_txn_test.go
- sessiontxn/staleread/processor.go
Issue Number: close #43044
Recalculate the snapshot ts for staleread when it's provided by as of statement.
Tests 
Side effects
Documentation
```release-note
Fix the bug that prepared staleread cannot read following changes.
```
> planner: recalculate as-of ts of staleread when plan is cached

- distsql/select_result.go
- executor/distsql.go
- executor/index_merge_reader.go
- executor/index_merge_reader_test.go
- executor/partition_table_test.go
- executor/table_reader.go
- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/handle_cols.go
- planner/core/task.go
Issue Number: close #43158, close #43160, ref #41028
Tests 
```
use real tikv env to run executor_test.TestOrderByWithLimit and passed.
```
Side effects
Documentation
```release-note
None
```
> planner, executor: indexMerge support partition table with limit embedded

- Makefile
EE team set too many concurrencies for tidb UT. so that many UT are very easy to become the unstable test for high CPU usage.
Tests 
Side effects
Documentation
```release-note
None
```
> *: reset jobs number

- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Problem Summary: planner: disable non-prep plan cache for DML statements for now
planner: disable non-prep plan cache for DML statements for now
Tests 
Side effects
Documentation
```release-note
None
```
> planner: disable non-prep plan cache for DML statements for now

- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Problem Summary: planner: disable non-prep plan cache for DML statements for now
planner: disable non-prep plan cache for DML statements for now
Tests 
Side effects
Documentation
```release-note
None
```
> planner: disable non-prep plan cache for DML statements for now (#43258)

- domain/infosync/BUILD.bazel
- domain/infosync/info_test.go
- domain/infosync/tiflash_manager.go
Issue Number: close #43070 
`json.Marshal(ruleOps)` call `func (r *TiFlashRule) MarshalJSON() ([]byte, error)` so do not  marshal `action`
Tests 
Side effects
Documentation
```release-note
None
```
> domin: fix do not marshal `RuleOp` correctly

- session/session.go
- session/sessiontest/session_test.go
Issue Number: close #43283
Problem Summary: As issue said, add log to make life easier when debug internal sql error.
Tests 
Side effects
Documentation
```release-note
None
```
> session: add more log for internal sql when parse failed

- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/region_job.go
- br/pkg/lightning/common/retry.go
- br/pkg/lightning/common/retry_test.go
- br/pkg/lightning/importer/import.go
Issue Number: close #43291
- log region/peer/store info on write tikv error
- log error when failed to import table
- retry on unknown rpc error
Tests 
- return context.Canceled or other non-retryable error, see the log print accordingly.
- return non-retryable error during write, see if it contains region/peer/store info:
```
[2023/04/21 18:05:33.809 +08:00] [ERROR] [import.go:1631] ["failed to import table"] [table=`xxx`.`xxx`] [error="peer 173, store 1, region 172, epoch conf_ver:1 version:82 : rpc error: code = Unimplemented desc = fake error"] [errorVerbose="rpc error: code = Unimplemented desc = fake error\npeer 173, store 1, region 172, epoch conf_ver:1 version:82 \ngithub.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).writeToTiKV.func2\n\t/Users/jujiaji …
```
> lightning: retry on unknown RPC error, log more info to help debug

- br/pkg/backup/client.go
- br/pkg/backup/push.go
- br/pkg/backup/schema.go
- br/pkg/checkpoint/backup.go
- br/pkg/checkpoint/log_restore.go
- br/pkg/checkpoint/restore.go
- br/pkg/restore/client.go
- br/pkg/restore/pipeline_items.go
- br/pkg/task/stream.go
Issue Number: close #43298
Make the plugin can be loaded again. The load fail for plugin may be cause by the bug of the golang. When we have some generic definition like:
```
type BackupRunner = CheckpointRunner[BackupKeyType, BackupValueType]
```
The plugin cannot be loaded by tidb even they have all same dependencies and built together.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix plugin build

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #43205
go-proxyprotocol will return `ErrHeaderReadTimeout` error at parse header step with error returned `conn.Read` call. That will hide the original error object.
update `go-proxyprotocol` package to new version will return the original error when enable fallback mode.
Tests 
Side effects
Documentation
```release-note
None
```
> *: Update go-proxyprotocol version to fix some corner case

- ddl/db_partition_test.go
- executor/builder.go
- executor/distsql.go
- executor/partition_table_test.go
- expression/constant.go
- planner/core/find_best_task.go
Issue Number: close #41991
Issue Number: close #42065
- fix global index scan when specify partition
- fix global index join
- fix drop/truncate partition reorg for global index
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix global index scan, index join, and query filtering reorg partition for global index

- ddl/db_partition_test.go
- planner/core/integration_test.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: close https://github.com/pingcap/tidb/issues/43281
See https://github.com/pingcap/tidb/issues/43281
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix wrong output for two deprecated system variables

- ddl/ingest/engine.go
- ddl/rollingback.go
Issue Number: close #43323
```
[2023/04/23 15:41:46.619 +08:00] [WARN] [backfilling.go:496] ["[ddl] backfill worker failed"] ["job ID"=95] ["result next key"=] [error="[ddl:8214]Cancelled DDL job"]
[2023/04/23 15:41:46.863 +08:00] [WARN] [backfilling.go:450] ["[ddl] backfill worker handle tasks failed"] ["total added count"=18078289] ["start key"=74800000000000005a5f728000000000000001] ["task failed error"="[ddl:8214]Cancelled DDL job"]
[2023/04/23 15:41:46.863 +08:00] [WARN] [index.go:1015] ["[ddl] run add index job failed, convert job to rollback"] [job="ID:95, Type:add index, State:cancelling, SchemaState:write reorganization, SchemaID:88, TableID:90, RowCount:13332166, ArgLen:6, start time: 2023-04-23 15:41:25.554 +0800 CST, Err:<nil>, ErrCount:0, …
```
> ddl: return early when encounter error in `BackendCtx.Unregister()`

- expression/constant.go
- planner/core/plan_cache_test.go
Issue Number: close #43311
Problem Summary: planner: use the correct fraction for decimal values in plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: use the correct fraction for decimal values in plan cache

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
This is an manually cherry-pick of #43079
Issue Number: close #43055
Tests 
without this fix, the newly added UT fails (I added a panic when error is not nil)
```
panic: write to tikv with no leader returned, region '1', leader: 0
```
Side effects
Documentation
```release-note
None
```
> lightning: always retry from rescan when NotLeader

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
Issue Number: close #43363 
The "needRescan" stage should let the worker exit the `executeJob`, to rescan the region of the job. But we forget to check it.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix wrongly retry writing when partial write + "needRescan"

- planner/core/casetest/testdata/plan_suite_in.json
- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/logical_plan_builder.go
Fix inline cte + recursive cte + with clause could not found table name
Issue Number: close #43318
The with clause is removed incorrectly when plan builder build ```recursive cte```.
Due to the original AST is modified. When the plan builder builds again (such as inline cte), there will be a problem that the table name cannot be found.
Tests 
Side effects
Documentation
```release-note
None
```
v6.5 and later
> planbuilder: Keep with clause when build recursive cte

- store/copr/coprocessor.go
Issue Number: close #43365
Fix missing `Request.TxnScope` so [the global stale-read optimization](https://github.com/tikv/client-go/pull/765) will take effect.
Seems there is no place to add a test for handling request inside coprocessor, the code change is really simple and safe.
Tests 
Side effects
Documentation
```release-note
store/copr: fix missing `Request.TxnScope` so the global stale-read optimization will take effect.
```
> store/copr: fix missting Request.TxnScope

- build/nogo_config.json
- owner/mock.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: enable revive for owner

- executor/executor_test.go
- expression/builtin_cast_vec.go
Issue Number: close #40582 
close #41729
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix warning message when to meet strconv.ErrRange

- planner/core/plan_cache_test.go
- sessionctx/variable/sysvar.go
Issue Number: close #43320
Problem Summary: planner: keep `tidb_prepared_plan_cache_size` compatible
planner: keep `tidb_prepared_plan_cache_size` compatible
Tests 
Side effects
Documentation
```release-note
None
```
> planner: keep `tidb_prepared_plan_cache_size` compatible

- executor/calibrate_resource.go
- executor/calibrate_resource_test.go
Issue Number: ref #43212
When the value is 0, the corresponding metrics does not return. If `RU` metrics is empty but `CPU` metrics is not (for example, when doing backup or restore), this logic will now cause `RU` and CPU` to be misaligned
Exactly match ru, tidb, and tikv metrics according to metrics timestamps
Tests 
Side effects
Documentation
```release-note
None
```
> resource_control: make metrics time point match in dynamic calibrate

- Makefile.common
Issue Number: close #43413 
Replace `-a` with `-d` which is more portable:
```
...
-a file
True if file exists.
...
-d file
True if file exists and is a directory.
...
```
Tests 
Side effects
Documentation
```release-note
None
```
> *: Fix portability issue in Makefile.common

- planner/core/plan_cache_test.go
- planner/core/rule_predicate_simplification.go
Issue Number: close #43405
Problem Summary: planner: label predicate_simplification as over-optimized for plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: label predicate_simplification as over-optimized for plan cache

- executor/importer/import.go
- executor/importer/import_test.go
- executor/loadremotetest/multi_file_test.go
- server/server_test.go
- tests/realtikvtest/loaddatatest/detach_test.go
- tests/realtikvtest/loaddatatest/load_data_test.go
- tests/realtikvtest/loaddatatest/show_test.go
- previously we use `ignoreInTest` to determine how many threads to use, it's not explicit to write case. now change them to explicit use `with thread=1` if needed.
Tests 
Side effects
Documentation
```release-note
None
```
> loaddata: make some test use 1 thread explicitly

- sessionctx/variable/sysvar.go
- tidb-server/main.go
Issue Number: ref #7968
In #42560 the mysql component of the version that TiDB reports was updated. However the version that is in the `version_comment` wasn't updated.
Tests 
Side effects
Documentation
```release-note
None
```
No release note as the release note for #42560 covers this already.
With this PR:
```
$ mysql -u root -P 4000 -h 127.0.0.1
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 403
Server version: 8.0.11-TiDB-v7.2.0-alpha-42-g7c5e7ea851-dirty TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible
Copyright (c) 2000, 2023, …
```
> *: Update version in version_comment

- config/config.go
- config/config.toml.example
- config/config_test.go
- domain/domain.go
- statistics/handle/handle.go
- tidb-server/main.go
Issue Number: close #43385 ref #42160
Introduce the configuration `force-init-stats`, which indicates whether to wait for init stats to finish before providing service during startup. 
Tests 
Add `time.Sleep(30 * time.Second)` at the beginning of init stats to simulate slow init stats. Start the tidb node with setting `force-init-stats` to true. The connection from mysql client is accepted after init stats is finished(after roughly 30 sec).
Side effects
Documentation
```release-note
None
```
> *: provide a option to wait for init stats to finish before providing service during startup

- planner/core/casetest/physical_plan_test.go
- planner/core/casetest/testdata/integration_suite_out.json
- planner/core/casetest/testdata/plan_suite_in.json
- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/exhaust_physical_plans.go
Issue Number: close #43347 
Add support only for normal ones: non-cross, non-nullAware joins.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: Support normal left/right outer MPPTask join with other condition to use either side as build side

- ddl/fktest/foreign_key_test.go
- ddl/table.go
- ddl/table_test.go
- parser/model/ddl.go
Issue Number: close #43338
We split the renaming table job into two steps:
1. rename table and update the schema version.
2. update the job state to JobStateDone.
This is the requirement from TiCDC because
- it uses the job state to check whether the DDL is finished.
- there is a gap between schema reloading and job state updating:
when the job state is updated to JobStateDone, before the new schema reloaded,
there may be DMLs that use the old schema.
- TiCDC cannot handle the DMLs that use the old schema, because
the commit TS of the DMLs are greater than the job state updating TS.
Tests 
Side effects
Documentation …
> ddl: wait schema change before rename table job is done

- .pre-commit-config.yaml
- Makefile
create a task to do ```go mod tidy```.
Tests 
Side effects
Documentation
```release-note
None
```
> *: update pre-commit

- executor/executor_test.go
- extension/event_listener_test.go
- parser/digester.go
- parser/digester_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/43409
Tests 
Side effects
Documentation
```release-note
Merge multiple placeholder lists into one to make SQL normalization more aggressive, in order to avoid meaningless distinctions that eliminate other meaningful SQLs.
```
> parser: make normalization more aggressive

- DEPS.bzl
- go.mod
- go.sum
- store/mockstore/unistore/tikv/kverrors/errors.go
- store/mockstore/unistore/tikv/mvcc.go
- store/mockstore/unistore/tikv/mvcc/mvcc.go
- store/mockstore/unistore/tikv/mvcc_test.go
- store/mockstore/unistore/tikv/server.go
- store/mockstore/unistore/tikv/write.go
Issue Number: ref https://github.com/pingcap/tidb/issues/42937
ref https://github.com/pingcap/tidb/issues/43243
Follows some latest behavior changes to TiKV:
* Supports `CheckTxnStatus` verifying primary
* However the change to TiKV has not been merged yet (https://github.com/tikv/tikv/pull/14637)
* `Commit` rollbacks pessimistic locks
And fixes some existing incorrect behaviors:
* `ScanLock` return complete lock info
* ~~`Commit` do not omit Lock records~~ Removing this change from this PR due to too many problems in the current implementation of unistore.
Tests 
Side effects
Documentation …
> unistore: Adjust some behaviors to be consistent with TiKV

- executor/revoke_test.go
- session/bootstrap.go
Issue Number: close #41048
After this PR: for `mysql.db`, `mysql.tables_priv` and `mysql.columns_priv` table, we have a slight different schema definition with MySQL: columns `DB`/`Table_name`/`Column_name` are defined with case-insensitive collation(in MySQL, they are case-sensitive).
The reason behind this is that when writing those records, MySQL always converts those names into lower case while TiDB does not do so in early implementations, which makes some 'GRANT'/'REVOKE' operations case-sensitive.
In order to fix this, we decide to explicitly set case-insensitive collation for the related columns here, to make sure:
* The 'GRANT'/'REVOKE' could be case-insensitive for new clusters(compatible with MySQL).
* Keep all behaviors unchanged for upgraded cluster.
Tests …
> session: change some privilege columns to case-insensitive

- DEPS.bzl
- go.mod
- go.sum
- metrics/grafana/tidb.json
Issue Number: close #43325
With tikv/client-go#776, we can display the following metrics:
Before 15:15, the stale-read hit ratio is high, and after 15:15, there are over 80% stale-read misses. From the metrics, we can clearly find the traffic used by stale-read.
Tests 
Side effects
Documentation
```release-note
Add traffic metrics for stale-read.
```
> grafana: add traffic metrics for staleread traffic

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/common/retry.go
- br/pkg/lightning/common/retry_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/43055
add retry for "write to tikv with no leader returned"
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```
> lightning: add retry for "write to tikv with no leader returned"

- planner/core/casetest/physical_plan_test.go
- planner/core/issuetest/BUILD.bazel
- planner/core/issuetest/planner_issue_test.go
- planner/core/task.go
Issue Number: close https://github.com/pingcap/tidb/issues/43178
Wrong slice-bound check, so the out-of-bound panic raised.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: wrong slice length check for index merge's order prop push down

- executor/infoschema_reader.go
- executor/infoschema_reader_test.go
Issue Number: close #43379
The change is actually quite simple(see the code).
the bug was introduced by me([#37419](https://github.com/pingcap/tidb/pull/37419)), and the root cause is that I didn't realize that filtering logic was pushed into `hugeMemTableRetriever`.
Tests 
Side effects
- None
Documentation
- None
```release-note
Fix the issue that `ORDINAL_POSITION` from `information_schema.columns` is incorrect when filtering.
```
> executor: fix the wrong `ORDINAL_POSTITION` in columns view

- build/nogo_config.json
Tests 
Side effects
Documentation
```release-note
None
```
> *: all linter ignore parser's generate code

- meta/autoid/autoid.go
Issue Number: close #42643 
ref https://github.com/pingcap/tidb/pull/9575, ref #33908
When the pd server change, the corresponding etcd address should be auto-refresh on the client side.
> While it is easy to just add back the option AutoSyncInterval: 30 * time.Second in, I think a bigger issue is why do we need to have 4 different etcd clients rather than sharing the same one with all the correct config 🤷
Because 1. tidb repo is too big, and it's not designed to be used as a lib. (this applies to all tidb/util/xxx), so the etcd client utility in the tidb repo is not a good place to be shared by other repos (tools / binlog ...)
2. For autoid service, it's a indenpendent component, the code is put to the tidb repo though. So this case is similiar to tools etc.
It should …
> meta/autoid: enable etcd client auto sync for autoid service

- br/pkg/restore/split.go
- br/pkg/restore/split_test.go
Reverts pingcap/tidb#42972
Issue Number: Ref https://github.com/pingcap/tidb/issues/42924, Ref https://github.com/tikv/tikv/issues/14641
```release-note
None
```
> restore: Revert "split between tables"

- executor/showtest/show_test.go
- expression/builtin.go
- expression/builtin_miscellaneous.go
- expression/integration_serial_test/BUILD.bazel
- expression/integration_serial_test/integration_serial_test.go
- parser/ast/functions.go
- parser/model/model.go
- planner/core/point_get_plan.go
- util/rowcodec/decoder.go
- util/rowcodec/row.go
Issue Number: ref #42747
Problem Summary: as decribed in #42747, we need to implement a builtin function `tidb_row_checksum` to export row checksums to users.
This is a quick & dirty implementation of `tidb_row_checksum`, which can only be used as a select field in a fast point plan. `tidb_row_checksum()` will be rewritten as a dummy column when `buildSchemaFromFields` in `TryFastPlan` and `ChunkDecoder` will fill this dummy column with row checksum info.
Tests 
Side effects
Documentation
```release-note
None
```
> *: add tidb_row_checksum() as a builtin function

- autoid_service/autoid_test.go
Issue Number: close #43518
Tests 
Side effects
Documentation
```release-note
None
```
> autoid_service: make test TestGRPC stable when port 10080 conflicts

- br/pkg/lightning/backend/local/engine.go
- ddl/index.go
- ddl/ingest/backend.go
- ddl/ingest/disk_root.go
- ddl/ingest/engine.go
- ddl/ingest/engine_mgr.go
- ddl/ingest/mock.go
Issue Number: close #43523
We should not call `FlushEngine()` concurrently.
Aquire the lock before `FlushEngine()`.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: flush data in local engine serially

- expression/scalar_function.go
- expression/scalar_function_test.go
- sessionctx/stmtctx/stmtctx.go
Issue Number: close https://github.com/pingcap/tidb/issues/43572
In TiDB Expression tree, sometimes we may need judge whether two expression tree are semantic equal,
this PR adds the simple check logic ported from SparkSQL.
Tests 
Side effects
Documentation
```release-note
None
```
> expression: add simple expression semantic equal check logic

- ddl/backfilling_scheduler.go
- ddl/index.go
- ddl/ingest/BUILD.bazel
- ddl/ingest/backend.go
- ddl/ingest/checkpoint.go
- ddl/ingest/checkpoint_test.go
- ddl/ingest/engine_mgr.go
- ddl/ingest/integration_test.go
- ddl/ingest/mock.go
- ddl/job_table.go
- ddl/scheduler.go
Issue Number: close #43586
Previously, the checkpoint manager is created or closed in each partition. It doesn't have a way to "remember" the row count in previous partition. As a result, the row count reported by the `Status()` function from checkpoint manager is always the last partition.
Create or close the checkpoint manager for each table instead of each partition.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: correct ingest row count for partition tables

- br/pkg/restore/client.go
- domain/domain.go
Issue Number: close #43402 
after log restore, there are many warning logs, see the issue.
Add a diffKey whose `regenerateSchemaMap` is true to trigger full load schemas.
Tests 
If modify the `64 + ...` to `6` to trigger `loadSchemaDiff`, the log would print that as follows:
```
[2023/05/08 15:46:48.758 +08:00] [ERROR] [domain.go:249] ["failed to load schema diff"] [error="Meets a schema diff with RegenerateSchemaMap flag"] [errorVerbose="Meets a schema diff with RegenerateSchemaMap flag\ngithub.com/pingcap/tidb/domain.(*Domain).tryLoadSchemaDiffs\n\t/root/tidb/domain/domain.go:421\ngithub.com/pingcap/tidb/domain.(*Domain).loadInfoSchema\n\t/root/tidb/domain/domain.go:236\ngithub.com/pingcap/tidb/domain.(*Domain).Reload\n\t/root/tidb/domain/domain.go:556\ngithub.com/pingca …
```
> br: avoid too many warning logs after update schema version

- planner/core/partition_pruner_test.go
- planner/core/rule_partition_processor.go
- table/tables/partition.go
- testkit/result.go
Built on top of:
https://github.com/jiyfhust/tidb/tree/fix_prune_multicolumn_datetime
Issue Number: close #43459 
Issue is that the type of the Column List values is just from internal parsing, not from target / table.column type, so some conversions fails.
Tests 
Side effects
Documentation
```release-note
None
```
> *: Fix issue in multi column range partition pruning

- ddl/index.go
- ddl/ingest/integration_test.go
Issue Number: ref #43523
Before this PR, if there is an error during creating index in ingest mode, TiDB will fallback to txn-merge mode automatically. However, this may not be expected by the users because the txn-merge mode is too slow in the scenario of large dataset.
This PR deletes the code of falling back and divides into the following cases:
- When `BackendCtx.Register()` reports an error, roll it back directly.
- When `runReorgJob()` reports an error, try it again until the error limit is reached.
- When `FinishImport()` reports an error, try it again until the error limit is reached.
Tests 
Side effects
Documentation …
> ddl: retry or rollback on error in ingest mode

- DEPS.bzl
- br/pkg/utils/key.go
- build/BUILD.bazel
- build/linter/mirror/BUILD.bazel
- build/linter/mirror/analyzer.go
- build/nogo_config.json
- go.mod
- go.sum
- parser/auth/caching_sha2.go
- session/txninfo/txn_info.go
- tools/check/xprog.go
- types/json_binary.go
- types/json_binary_functions.go
```mirror``` suggests use of alternative functions/methods in order to gain performance boosts by avoiding unnecessary []byte/string convertion calls. See [MIRROR_FUNCS.md](https://github.com/butuzov/mirror/blob/main/MIRROR_FUNCS.md) list of mirror functions you can use in go's stdlib.
Tests 
Side effects
Documentation
```release-note
None
```
> *: enable mirror linter

- br/pkg/checkpoint/BUILD.bazel
- br/pkg/checkpoint/checkpoint.go
- br/pkg/checkpoint/checkpoint_test.go
- br/pkg/checkpoint/restore.go
- br/pkg/gluetidb/glue_test.go
- br/pkg/logutil/logging.go
- br/pkg/restore/BUILD.bazel
- br/pkg/restore/batcher.go
- br/pkg/restore/client.go
- br/pkg/restore/logutil.go
- br/pkg/restore/pipeline_items.go
- br/pkg/restore/split_test.go
- br/pkg/task/restore.go
Issue Number: close #43632 
checkpoint for snapshot restore should be more accurate.
records the ranges once the range has been import done.
Besides, the changed checkpoint data for snapshot restore now is :
```
<table-id, start-key>
```
instead of the original one :
```
<table-id, (start-key, end-key)>
```
Tests 
Side effects
Documentation
```release-note
None
```
> br: push down checkpoint record

- Makefile
```
make bench-daily TO=/tmp/2023-05-09.json
```
`tidb/executor/splittest` is moved to `tidb/executor/test/splittest`, so that command fails.
Tests 
Side effects
Documentation
```release-note
None
```
> Makefile: fix the 'make bench-daily' target
