infoschema/cluster_tables_test.go

Issue Number: ref #39199
Supply test cases:
- set binding status with null sql digest
Tests 
Side effects
Documentation
```release-note
None
```

planner: supply test cases for binding from history 

---

go.mod
go.sum

Issue Number: ref #40461
To include https://github.com/tikv/client-go/pull/678, as complement of #40642.
Tests 
Side effects
Documentation
```release-note
None
```

*: update client-go to latest tidb-5.4

---

DEPS.bzl
go.mod
go.sum

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade mgechev/revive

---

br/pkg/restore/data.go
br/pkg/task/restore_data.go

cherry pick pr 40504
Issue Number: close #40391 #41005
refactoring code to remove totalFlashbackRegions since task completion region already contains all regions
Tests 
1. follow the doc https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/backup-to-aws-s3-by-snapshot to do the backup
2. follow the doc https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/restore-from-aws-s3-by-snapshot to do the restore
3. restore success
Side effects
Documentation
```release-note
None
```

br: remove totalFlashbackRegions since task completion region already contains all regions

---

distsql/distsql.go
executor/builder.go
executor/mpp_gather.go
executor/tiflashtest/tiflash_test.go
kv/mpp.go
store/copr/mpp.go

Tests 
Side effects
Documentation
```release-note
None
```

*: cherry-pick 40901

---

Makefile

Tests 
Side effects
Documentation
```release-note
None
```

*: add buildtag for ddltest

---

DEPS.bzl
go.mod
go.sum
kv/interface_mock_test.go
kv/kv.go
session/txn.go
sessionctx/BUILD.bazel
sessiontxn/BUILD.bazel
store/driver/txn/txn_driver.go

Issue Number: close #40355 #40461
And also fix a minor slow log data missing.
Update client-go to include https://github.com/tikv/client-go/pull/641, https://github.com/tikv/client-go/pull/655, https://github.com/tikv/client-go/pull/664 and https://github.com/tikv/client-go/pull/678
Tests 
Side effects
Documentation
```release-note
Clear stale region cache periodically to avoid memory leak and performance degradation
```

*: update client-go to latest tidb-6.5 branch

---

executor/index_merge_reader.go
executor/index_merge_reader_test.go

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #41047
Problem Summary: Check description in https://github.com/pingcap/tidb/pull/41036
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix IndexMerge handle panic logic

---

Makefile.common

after upgrade a dependency in https://github.com/pingcap/tidb/pull/41111, macOS must turn on cgo to build
Tests 
```
manually make build_dumpling on macOS
```
Side effects
Documentation
```release-note
None
```

makefile: update dumpling build options

---

ddl/backfilling.go

Issue Number: close #40879
For mock context, prevent initializing it in the worker concurrently.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: initialize the mock session in advanced

---

util/gpool/spmc/spmcpool.go

Issue Number: close https://github.com/pingcap/tidb/issues/41205
Tests 
Side effects
Documentation
```release-note
None
```

util/gpool/spmc: add a sleep to a simple `for`

---

.bazelrc
Makefile

Tests 
Side effects
Documentation
```release-note
None
```

bazel: set --test_keep_going false

---

ddl/backfilling.go
ddl/constant.go
ddl/ddl.go
ddl/ddl_worker_test.go
ddl/dist_backfilling.go
ddl/dist_owner.go
ddl/index.go
ddl/job_table.go
ddl/job_table_test.go
meta/meta.go
parser/model/ddl.go
resourcemanager/schedule.go
session/bootstrap_test.go
session/session.go
session/session_test.go
telemetry/BUILD.bazel
telemetry/data_feature_usage_test.go

Issue Number: close #41002
Tests 
Side effects
Documentation
```release-note
None
```

ddl: improve backfill more general

---

ttl/cache/BUILD.bazel
ttl/client/BUILD.bazel
ttl/metrics/BUILD.bazel
ttl/session/BUILD.bazel
ttl/sqlbuilder/BUILD.bazel
ttl/ttlworker/BUILD.bazel

Issue Number: close #41276
Tests 
Side effects
Documentation
```release-note
None
```

ttl: optimize bazel for TTL codes

---

infoschema/cluster_tables_test.go

Issue Number: close #41307 
Tests 
Side effects
Documentation
```release-note
None
```

infoschema: fix unstable test TestSelectClusterTable

---

util/stmtsummary/v2/tests/table_test.go

Issue Number: close #41315 
Tests 
Side effects
Documentation
```release-note
None
```

stmtsummary: fix panic in stmts test

---

config/main_test.go
telemetry/cte_test/cte_test.go

Issue Number: close #41274 
close #41337
Tests 
Side effects
Documentation
```release-note
None
```

*: fix goleak in the test

---

DEPS.bzl
go.mod
go.sum

Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>
Issue Number: ref #38825 
should be merged after https://github.com/tikv/pd/pull/5981
update pd client 
+ https://github.com/tikv/pd/pull/5981
Tests 
```release-note
None
```

go.mod: update pd client in 6.6

---

keyspace/BUILD.bazel
keyspace/keyspace.go
keyspace/keyspace_test.go
tidb-server/BUILD.bazel
tidb-server/main.go

Issue Number: ref https://github.com/pingcap/tidb/issues/41354
Tests 
Side effects
Documentation
```release-note
None
```

keyspace: add keyspace util func and ut

---

planner/core/plan_cache.go
planner/core/plan_cacheable_checker.go

Problem Summary: planner: small refactor about plan cache checker
planner: small refactor about plan cache checker
Tests 
Side effects
Documentation
```release-note
None
```

planner: small refactor about plan cache checker

---

util/etcd/etcd_test.go

Issue Number: close #37652 
Tests 
Side effects
Documentation
```release-note
None
```

etcd_test: remove unnecessary sleep, make ci more stable

---

keyspace/BUILD.bazel
keyspace/keyspace_test.go

Signed-off-by: ystaticy <y_static_y@sina.com>
Issue Number: close https://github.com/pingcap/tidb/issues/41376
Fix keyspace ut.
Tests 
Side effects
Documentation
```release-note
None
```

keyspace: fix keyspace ut

---

ddl/index_cop.go

Issue Number: close #41400
Set the request source for coprocessor requests that are used in adding index.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: set request source for cop requests that are used in adding index

---

telemetry/data_feature_usage_test.go
telemetry/ttl.go
ttl/ttlworker/job.go
ttl/ttlworker/job_manager.go
ttl/ttlworker/job_manager_integration_test.go
ttl/ttlworker/job_manager_test.go

Issue Number: close #41419
Tests 
Side effects
Documentation
```release-note
`mysql.tidb_ttl_job_history` will show running TTL jobs
```

ttl: add running jobs to `mysql.tidb_ttl_job_history`

---

store/copr/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

*: update bazel config for copr

---

ddl/backfilling.go
ddl/ddl_worker.go
ddl/job_table.go
ddl/syncer/syncer.go
tests/realtikvtest/addindextest/integration_test.go

Issue Number: ref #41452
- Timed out because of the unreasonable huge unit test
- Dead loop because of the incorrect usage of `context.Background()`
Refine the code to fix for the above problems.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: improve the stability of real tikv test of adding index

---

Makefile

Tests 
Side effects
Documentation
```release-note
None
```

*: build test only when to test

---

executor/load_data.go
server/server_test.go

Issue Number: close #41410 
Tests 
Side effects
Documentation
```release-note
LOAD DATA INFILE now handles the situation where the column names of the table don't match the named columns in the statement
```

executor: Check for column mismatch

---

infoschema/cluster_tables_test.go

Issue Number: close #41518
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix broken test TestBindingFromHistoryWithTiFlashBindable

---

session/BUILD.bazel
session/bootstraptest/BUILD.bazel
session/bootstraptest/bootstrap_upgrade_test.go
session/bootstraptest/main_test.go
session/index_usage_sync_lease_test.go
session/testutil.go

Issue Number: ref #41377
split some test cases into new folders. it can add concurrency for the test cases.
because bezel's max concurrency is 50 in a folder.
Tests 
Side effects
Documentation
```release-note
None
```

session: fine-grained cache for session's bootstrap test

---

Makefile

Tests 
Side effects
Documentation
```release-note
None
```

makefile: fix bazel_test

---

ddl/db_partition_test.go
ddl/partition.go
store/driver/txn/txn_driver.go

Issue Number: close #40145, close #40148, close #41447
Tests 
Side effects
Documentation
```release-note
None
```

partition: check global index when execute create table

---

util/gctuner/BUILD.bazel
util/gctuner/finalizer_test.go

Issue Number: close #41563
Tests 
Side effects
Documentation
```release-note
None
```

gctuenr: fix unstable test TestFinalizer

---

executor/show_stats.go
executor/show_stats_test.go
planner/core/planbuilder.go
planner/core/show_predicate_extractor.go

Issue Number: close #41544
Tests 
Side effects
Documentation
```release-note
None
```

executor: make `show stats_healthy` case-insensitive

---

roadmap.md

Issue Number: close #41330 
Problem Summary: update roadmap
Tests 
Side effects
Documentation
```release-note
None
```

docs: update roadmap for v6.6

---

planner/core/plan_cache_test.go
planner/core/plan_cacheable_checker.go

Problem Summary: planner: add more test cases for non-prep plan cache
Tests 
Side effects
Documentation
```release-note
None
```

planner: add more test cases for non-prep plan cache

---

DEPS.bzl
go.mod
go.sum

Tests 
Side effects
Documentation
```release-note
None
```

linter: upgrade go-tools

---

cmd/explaintest/r/index_merge.result
planner/core/exhaust_physical_plans.go
planner/core/find_best_task.go
planner/core/integration_test.go
planner/core/physical_plan_test.go
planner/core/plan_cost_ver1.go
planner/core/plan_cost_ver2.go
planner/core/task.go
planner/core/testdata/integration_suite_out.json
planner/core/testdata/plan_suite_in.json
planner/core/testdata/plan_suite_out.json
planner/property/physical_property.go
planner/property/task_type.go

Issue Number: cherry pick #41054 
Tests 
Side effects
Documentation
```release-note
None
```

planner: support push part of limit prop to IndexMerge (#41054) | tidb-test=a7d6b8869742f76a93eb3c69804fabab8d6a42e8

---

executor/historical_stats_test.go
sessionctx/variable/sysvar.go

add test for tidb_historical_stats_duration
Tests 
Side effects
Documentation
```release-note
None
```

sysvar: add test for tidb_historical_stats_duration

---

executor/builder.go
executor/mpp_gather.go
executor/table_reader.go
executor/tiflashtest/tiflash_test.go
planner/core/find_best_task.go
planner/core/task.go

Signed-off-by: guo-shaoge <shaoge1994@163.com>
Issue Number: close #41360
Problem Summary: As issue said.
Tests 
Side effects
Documentation
```release-note
None
```

planner: enable tiflash path for generated col in disaggregated tiflash mode

---

infoschema/cluster_tables_test.go

Issue Number: close #41425
Fix unstable test by `time.Sleep()`
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix unstable test TestCreateBindingRepeatedly

---

expression/function_traits.go
planner/core/plan_cache_test.go
planner/core/plan_cacheable_checker.go
planner/core/plan_cacheable_checker_test.go

Problem Summary: planner: add more test cases for non-prep cache
planner: add more test cases for non-prep cache
Tests 
Side effects
Documentation
```release-note
None
```

planner: add more test cases for non-prep cache

---

server/http_handler.go
server/http_handler_serial_test.go

Issue Number: close #41704
Tests 
Side effects
Documentation
```release-note
None
```

ttl: fix the error message for TTL job trigger api in http

---

ddl/index.go

Refine the error handle for `runReorgJob`.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: refine the error handling for runReorgJob

---

.github/dependabot.yml

Tests 
Side effects
Documentation
```release-note
None
```

*: update dependabot to support parser

---

DEPS.bzl
go.mod
go.sum

Issue Number: ref #41720
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade client-go

---

executor/index_merge_reader.go
executor/index_merge_reader_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/41545
Problem Summary: Manually cherry pick of https://github.com/pingcap/tidb/pull/41633
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix goroutine leak in IndexMerge.Close  | tidb-test=a7d6b8869742f76a93eb3c69804fabab8d6a42e8

---

ttl/ttlworker/config.go
ttl/ttlworker/task_manager.go

Issue Number: close #41760
Add a failpoint to shrink the expire interval of ttl task heartbeat.

ttl: add failpoint for task heartbeat expire interval

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #41758, close #41772
Tests 
Side effects
Documentation
```release-note
None
```

client-go: update client-go

---

executor/builder.go
tests/realtikvtest/pessimistictest/pessimistic_test.go

close pingcap/tidb#41581
Tests 
Side effects
Documentation
```release-note
None
```

hotfix: pick f6edebc054371e4bce9b672d420bfeaa60d52049 to release-6.1-20230301-v6.1.2 | tidb-test=1ea2292cb6b66e9497652a0845b7b0118afe3294

---

executor/asyncloaddata/BUILD.bazel
executor/asyncloaddata/util.go
executor/asyncloaddata/util_test.go
kv/option.go

Add a table and helper function so that LOAD DATA worker can use them to run asynchronously
Tests 
Side effects
Documentation
```release-note
None
```

asyncloaddata: add table and helper functions 

---

domain/infosync/info.go
domain/infosync/label_manager.go
domain/infosync/placement_manager.go
go.mod
go.sum

Hotfix (#33909)
Tests 
Side effects
Documentation
```release-note
None
```

*: Auto refresh PD addrs for PDPlacementManager, PDLabelManager (#33909)

---

executor/delete.go
executor/index_merge_reader.go
kv/key.go

Tests 
Side effects
Documentation
```release-note
None
```

key: remove unnecesssary convert

---

br/pkg/lightning/restore/get_pre_info.go
br/pkg/lightning/restore/precheck_impl.go
br/pkg/lightning/restore/table_restore_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/41895
reduce the number of calling `GetAllTableStructures`, it is enough just one
Tests 
Side effects
Documentation
```release-note
None
```

Lightning: reduce the complexity of precheck

---

ddl/table.go

Issue Number: ref https://github.com/pingcap/tidb/issues/41951
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix create view when met err

---

br/tests/lightning_reload_cert/run.sh

Issue Number: close #41960 
Fixed the integration test failure introduced by https://github.com/pingcap/tidb/pull/40793
Tests 
Side effects
Documentation
```release-note
None
```

lightning: fix integration test

---

roadmap.md

Issue Number: close #41894 
Tests 
Side effects
Documentation
```release-note
None
```

docs: add new roadmap

---

br/pkg/lightning/backend/kv/kv2sql.go
br/pkg/lightning/backend/kv/sql2kv.go
ddl/index.go
ddl/mv_index_test.go
tests/realtikvtest/addindextest/integration_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/41907
Tests 
```release-note
None
```

ddl: fix check unique multi-valued index

---

domain/domain.go
domain/extract.go
domain/extract_test.go
domain/plan_replayer_test.go
server/extract.go
server/http_handler.go
util/replayer/replayer.go

Issue Number: ref https://github.com/pingcap/tidb/issues/41130
* support more params for extract plan task
* make dumpFileGC support gc file results for extrack task handler
Tests 
```release-note
None
```

domain: support more params for extract plan task

---

br/pkg/lightning/backend/kv/sql2kv.go
br/pkg/lightning/importer/table_import.go
br/pkg/lightning/mydump/parser.go
br/pkg/lightning/mydump/region.go
br/pkg/lightning/mydump/region_test.go

Tests 
Side effects
Documentation
```release-note
None
```

lightning: some refactor about id allocation

---

executor/resource_tag_test.go
server/tidb_test.go
store/mockstore/unistore/rpc.go

Issue Number: close #42008
Tests 
Side effects
Documentation
```release-note
None
```

*: fix data race at the UnistoreRPCClientSendHook

---

session/bootstrap.go
session/bootstrap_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/36600
set the tidb_opt_advanced_join_hint to off when upgrade
set the tidb_opt_advanced_join_hint to off when upgrade
Tests 
Side effects
Documentation
```release-note
None
```

planner: set the tidb_opt_advanced_join_hint to off when upgrade

---

roadmap.md

Tests 
Side effects
Documentation
```release-note
None
```

docs: remove 1-year description from roadmap

---

DEPS.bzl
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/42048
fix some problems in client and catch up some updates.  
Tests 
```release-note
None
```

mod: update the pd client

---

WORKSPACE
executor/fktest/BUILD.bazel
executor/fktest/main_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/42047
https://github.com/golang/go/issues/57523
It is solved. It is very importance to improve our performance.
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go 1.20.2

---

metrics/grafana/tidb_runtime.json

Issue Number: ref #42057
Tests 
before
after 
Side effects
Documentation
```release-note
None
```

metrics: fix bad estimate-inuse

---

DEPS.bzl
go.mod
go.sum
store/driver/txn/txn_driver.go
store/mockstore/unistore/tikv/mvcc.go
tests/realtikvtest/pessimistictest/pessimistic_test.go

Issue Number: close #42068 
This PR updates client-go to latest master (which contains the changes that implements #42068), updated implementation of unistore to follow https://github.com/tikv/tikv/issues/14293, and added some related tests.
Requires https://github.com/tikv/tikv/pull/14330 , https://github.com/tikv/client-go/pull/727
Tests 
Side effects
Documentation
```release-note
None
```

txn: Make lockOnlyIfExist and WakeUpModeForceLocking able to work together

---

br/pkg/restore/main_test.go

Issue Number: close #42124
Tests 
Side effects
Documentation
```release-note
None
```

*: fix goleak goleveldb/leveldb.(*DB).mpoolDrain

---

WORKSPACE

Issue Number: close #42058
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go 1.19.7

---

config/main_test.go
telemetry/cte_test/cte_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/42117
Tests 
Side effects
Documentation
```release-note
None
```

*: fix syscall.Syscall goleak

---

util/gctuner/finalizer_test.go

Issue Number: close #38466
Tests 
Side effects
Documentation
```release-note
None
```

gctuner: fix unstable test TestFinalizer

---

ddl/resourcegrouptest/BUILD.bazel
ddl/resourcegrouptest/resource_group_test.go

Issue Number: close #42119
Tests 
Side effects
Documentation
```release-note
None
```

ddl/test: fix DATA RACE in TestResourceGroupBasic

---

distsql/select_result.go
statistics/handle/handletest/BUILD.bazel

Issue Number: close #42122
Tests 
Side effects
Documentation
```release-note
None
```

statistics: fix DATA RACE in the TestInitStatsVer2

---

domain/extract_test.go

Issue Number: close #42128
Do not assign `nil` to global pointer when it may still be in use.
Tests 
Side effects
Documentation
```release-note
None
```

domain: fix data race in test with stmtsummary

---

roadmap.md

minor change on security feature
Issue Number: close #42178 
Tests 
Side effects
Documentation
```release-note
None
```

*: Update roadmap.md

---

planner/core/common_plans.go
planner/core/prepare_test.go

Issue Number: close #38335
planner: skip plan cache if the plan contains Shuffle operators
Tests 
Side effects
Documentation
```release-note
None
```

planner: skip plan cache if the plan contains Shuffle operators

---

distsql/distsql.go
distsql/request_builder.go
executor/admin.go
executor/builder.go
executor/distsql.go
executor/index_merge_reader.go
executor/table_reader.go
kv/kv.go
server/conn_stmt_test.go
sessiontxn/isolation/readcommitted.go
store/copr/coprocessor.go

Disable the `RCReadCheckTS` usage for prepared statement cursor read mode.
Issue Number: close #42184 
Tests 
Side effects
Documentation
```release-note
Disable the rc read check ts for prepared statement cursor read mode.
```

txn: disable rc read check ts for cursor read mode

---

ddl/backfilling.go
ddl/ddl.go
ddl/dist_backfilling.go
ddl/dist_owner.go
ddl/index.go
ddl/job_table.go
ddl/job_table_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/42176, close https://github.com/pingcap/tidb/issues/42199, close https://github.com/pingcap/tidb/issues/42175
- https://github.com/pingcap/tidb/issues/42175: add `ddl_physical_tid` info for SQL.
- https://github.com/pingcap/tidb/issues/42176: cherry pick `remain` to dist-reorg logical.
- https://github.com/pingcap/tidb/issues/42199: backfill job use a new `reorgCtx`.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix dist-reorg bugs

---

executor/load_data.go
server/tidb_serial_test.go

Issue Number: close #42233
seecode comment
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix broken happens-before during refactor LOAD DATA

---

config/config.go
config/config.toml.example
config/config_test.go
executor/tiflashtest/tiflash_test.go

Issue Number: close #42190
Problem Summary: As issue said.
Tests 
Side effects
Documentation
```release-note
None
```

config: set use-autoscaler default as false

---

executor/stale_txn_test.go
session/session.go

Tests 
Side effects
Documentation
```release-note
None
```

session: use TxnCtx.InfoSchema, no matter vars.InTxn() or not #42027

---

session/bootstrap.go
session/bootstrap_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/42271
Tests 
Side effects
Documentation
```release-note
None
```

session: set tidb_enable_null_aware_anti_join to ON when upgrading to v7.0

---

roadmap.md

Issue Number: close #42231
Tests 
Side effects
Documentation
```release-note
None
```

*: Minor changes for better clarity in roadmap file

---

executor/fktest/foreign_key_test.go
executor/seqtest/seq_executor_test.go
kv/BUILD.bazel
kv/kv.go
server/server_test.go
session/session.go
store/driver/txn/txn_driver.go
tidb-server/main.go

Issue Number: close https://github.com/pingcap/tidb/issues/42335
Tests 
Side effects
Documentation
```release-note
None
```

*: fix data race at the TxnTotalSizeLimit

---

executor/asyncloaddata/util.go
executor/asyncloaddata/util_test.go
executor/infoschema_cluster_table_test.go
executor/load_data.go
session/bootstrap.go

Tests 
Side effects
Documentation
```release-note
None
```

bootstrap: move LOAD DATA system table into bootstrap

---

ddl/job_table_test.go

Tests 
```release-note
None
```

*: update comment

---

planner/core/casetest/testdata/plan_normalized_suite_in.json
planner/core/casetest/testdata/plan_normalized_suite_out.json
planner/core/casetest/tiflash_selection_late_materialization_test.go
planner/core/tiflash_selection_late_materialization.go

Issue Number: close #40601
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix do not remove empty selection just blow TableReader

---

errno/errname.go
errors.toml
executor/load_data.go
executor/loadremotetest/error_test.go

Issue Number: ref #40499 
Tests 
Side effects
Documentation
```release-note
None
```

load data: add root cause to an error message

---

executor/hash_table.go

We add a checkpoint for memory tracking during the probe phase of hashjoin. It may impact the performance.
We enlarge the checkpoint mask for reducing the impact.
Tests 
Side effects
Documentation
```release-note
None
```

executor: increase signalCheckpointForJoinMask to reduce the impact on performance

---

session/session.go

Issue Number: close #42347
Tests 
Side effects
Documentation
```release-note
None
```

session: fix data race at the TxnCtx

---

server/tidb_test.go

Issue Number: close #41685
We will enable the data race check in the future. so we need to fix all data race.
Tests 
Side effects
Documentation
```release-note
None
```

*: fix data race in the mockProxyProtocolProxy

---

DEPS.bzl
go.mod
go.sum

Tests 
Side effects
Documentation
```release-note
None
```

linter: upgrade linter

---

executor/adapter.go
server/tidb_test.go

Issue Number: close #42269
Tests 
Side effects
Documentation
```release-note
None
```

server: fix unstable test-case TestInternalSessionTxnStartTS

---

dumpling/export/ir_impl.go
dumpling/tests/basic/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/42391
1. Init SQLRowIter when we start a new table data.
2. Add integration test for `--output-file-template`.
Tests 
Side effects
- None
Documentation
- None
```release-note
fix dumpling panic bug when --output-file-template is incorrect
```

dumpling: fix dumpling panic bug when --output-file-template is incorrect

---

executor/executor.go
executor/executor_test.go
executor/issuetest/executor_issue_test.go

Issue Number: close #42298
Tests 
Side effects
Documentation
```release-note
fix a bug for ADMIN SHOW DDL JOB QUERIES
```

executor: fix a bug for ADMIN SHOW DDL JOB QUERIES

---

planner/core/plan_to_pb.go

Issue Number: close #42386
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix do not set lateMaterializationFilterCondition to pb when DynamicPartitionPrune is enable

---

ddl/backfilling.go
ddl/column.go
ddl/dist_backfilling.go
ddl/index.go
ddl/index_merge_tmp.go
ddl/partition.go

This reverts commit 4e2e11bab7c1c7c65d16aab9c0f83546d26e60d7.
Issue Number: close #42436
Tests 
Side effects
Documentation
```release-note
None
```

Revert "ddl: refactor add index worker for ingest mode (#42115)"

---

br/pkg/version/build/info.go

Issue Number: close https://github.com/pingcap/tidb/issues/42460
Fix br-integration-test
Tests 
Side effects
Documentation
```release-note
None
```

br: fix ci

---

ddl/BUILD.bazel
ddl/backfilling.go
ddl/backfilling_scheduler.go

This is a refactor PR, let's skip the issue check.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: move the backfill scheduler to a separate file

---

br/pkg/lightning/common/util.go
br/pkg/lightning/config/config.go
br/pkg/lightning/config/config_test.go
br/pkg/lightning/importer/import.go
br/pkg/lightning/importer/table_import.go

Issue Number: close https://github.com/pingcap/tidb/issues/42457
Tests 
Side effects
Documentation
```release-note
None
```

lightning: always disable add-index-by-sql by default

---

br/pkg/lightning/importer/import.go

Issue Number: ref https://github.com/pingcap/tidb/issues/41536
log backup task conflict with restore/lightning.
register task key with ttl to pd, and keepalive it during running.
Tests 
Side effects
Documentation
```release-note
None
```

lightning: register import task to pd

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #42492
ref https://github.com/tikv/pd/pull/6216
Tests 
1.  mysql> alter resource group rg1 RU_PER_SEC=10000 BURSTABLE;
2. run sysbench and kill it.
3. wait 1 minute and alter resource group rg1 RU_PER_SEC=1000;
4. run sysbench again.
Side effects
Documentation
```release-note
None
```

mod: update pd client

---

executor/importer/import.go
executor/loadremotetest/one_csv_test.go

Issue Number: close #42446
Tests 
Side effects
Documentation
```release-note
None
```

executor: LOAD DATA use VisibleCols to skip hidden columns

---

.bazelrc
Makefile.common

try to fix jvm coredump by https://github.com/bazelbuild/bazel/issues/11401
Tests 
Side effects
Documentation
```release-note
None
```

bazel: add sandbox_tmpfs_path and set memory 4g

---

distsql/select_result.go

Issue Number: close https://github.com/pingcap/tidb/issues/42507
Tests 
Side effects
Documentation
```release-note
None
```

distsql: misuse IsTelemetryEnabled in the selectResult.fetchResp

---

infoschema/infoschema_test.go
infoschema/tables.go

Issue Number: close #42440 
Correct the table's definition.
Tests 
Side effects
Documentation
```release-note
None
```

infoschema: fix ddl_jobs table `query` column's type

---

executor/batch_point_get.go
executor/point_get.go
tests/realtikvtest/pessimistictest/pessimistic_test.go

This reverts commit 3a5f434aad408299d58ab34bbb73af2ac0b3a5bf.
Issue Number: ref #28011 
Problem Summary: #42409 is little risky, thus we need to provide a safer solution.
revert #28011 .
Tests 
Side effects
Documentation
```release-note
None
```

executor: revert #25730 to fix #28011

---

executor/index_merge_reader.go

Issue Number: close #41949 
Tests 
Side effects
Documentation
```release-note
None
```

executor: Lower the log level from info to debug for index merge reader

---

ddl/resourcegrouptest/resource_group_test.go
domain/infosync/resource_group_manager.go
executor/infoschema_reader.go
infoschema/tables.go
store/mockstore/unistore/pd.go

Issue Number: close https://github.com/pingcap/tidb/issues/42595
ref https://github.com/pingcap/tidb/issues/42595
Tests 
Documentation
```release-note
None
```

infoschema: make the  resource group display more intuitive

---

executor/asyncloaddata/operate_test.go
executor/asyncloaddata/show_test.go
executor/show.go

Issue Number: close #42593 
Tests 
Side effects
Documentation
```release-note
None
```

loaddata: fix result_code is 0 when task is not finished

---

resourcemanager/pool/workerpool/workerpool.go

Issue Number: ref #42511
The resource control component is immature, it is better to support setting the worker size manually.
Tests 
Side effects
Documentation
```release-note
None
```

workerpool: add skip register option

---

parser/docs/quickstart.md

Issue Number: ref #42230 
Tests 
Side effects
Documentation
```release-note
None
```

parser: Update quickstart.md to mention parser.result is reused

---

metrics/grafana/performance_overview.json

Issue Number: close #42654 
Tests 
Side effects
Documentation
```release-note
None
```

metrics: enhancements and bug fixes in tiflash panel

---

metrics/grafana/performance_overview.json

Issue Number: close #42657
Tests 
Side effects
Documentation
```release-note
None
```

metrics: fix 3 miss labels in tiflash panels

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #42652
ref https://github.com/tikv/pd/pull/6237
Tests 
> alter resource group rg2 RU_PER_SEC=200 BURSTABLE;
alter user 'user2' resource group rg2;
sysbench --mysql-host=127.0.0.1 --mysql-user=user2 --mysql-port=4000 --mysql-db=sbtest --percentile=99 --report-interval=1 --tables=4 --table_size=1000000 oltp_read_only --range_selects --threads=4 --time=1800 run
Side effects
Documentation
```release-note
None
```

mod: update pd client to fix burst too many token request

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #42652
ref https://github.com/tikv/pd/pull/6240
Tests 
> alter resource group rg2 RU_PER_SEC=200 BURSTABLE;
alter user 'user2' resource group rg2;
sysbench --mysql-host=127.0.0.1 --mysql-user=user2 --mysql-port=4000 --mysql-db=sbtest --percentile=99 --report-interval=1 --tables=4 --table_size=1000000 oltp_read_only --range_selects --threads=4 --time=1800 run
Side effects
Documentation
```release-note
None
```

mod: update pd client to fix burst too many token request(#42660)

---

go.mod
go.sum

Issue Number: ref #28011, https://github.com/tikv/client-go/pull/752
See https://github.com/tikv/client-go/pull/752 & https://github.com/tikv/client-go/pull/753.
Tests 
Side effects
Documentation
```release-note
None
```

txn: bump client-go to allow lock->put on untouched kv

---

br/pkg/lightning/backend/local/BUILD.bazel
br/pkg/lightning/backend/local/local.go
br/pkg/lightning/backend/local/local_test.go

Issue Number: close #42301
Tests 
Side effects
Documentation
```release-note
None
```

test: use concurrent-safe structure to fix a flaky test

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #42691 
Problem Summary: Fix the compatibility issue that the new PD client cannot access the old PD server.
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade pd client for release 7.0 branch

---

br/pkg/restore/ingestrec/ingest_recorder.go

Issue Number: close #42707
the rowcount of the ddl history job would be inaccurate in v7.1
remove rowcount check for ingest recorder
Tests 
Side effects
Documentation
```release-note
None
```

pitr: remove row count check for ingest recorder

---

disttask/framework/dispatcher/BUILD.bazel
ttl/ttlworker/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

bazel: update config

---

resourcemanager/pool/spool/spool_test.go

Issue Number: close #42163
Tests 
Side effects
Documentation
```release-note
None
```

*: fix unstable test TestPoolTuneScaleUpAndDown

---

util/gctuner/memory_limit_tuner_test.go

Issue Number: close #38465
Tests 
Side effects
Documentation
```release-note
None
```

gctuner: fix unstable test in the TestGlobalMemoryTuner

---

executor/asyncloaddata/BUILD.bazel
executor/asyncloaddata/show_test.go
executor/load_data.go

Issue Number: close #42722 
as title
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix flaky LOAD DATA test by adding a channel to synchronize

---

disttask/framework/dispatcher/dispatcher.go
disttask/framework/dispatcher/dispatcher_test.go
disttask/framework/dispatcher/main_test.go
domain/domain.go

Issue Number: close https://github.com/pingcap/tidb/issues/42791
- Change the total retry time from 600ms to 2s.
-  Update logs.
- Add `MockDisableDistTask` to stop the dispatcher in the domain.
- Besides, clean up the cache in the test.
```
dispatcher_test.go:212: 
Error Trace:	disttask/framework/dispatcher/dispatcher_test.go:21
disttask/framework/dispatcher/dispatcher_test.go:248
Error:      	Not equal: 
expected: 0
actual  : 1
Test:       	TestParallelNormalFlow
```
Tests 
Side effects
Documentation
```release-note
None
```

distask: make the test stable

---

WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

bazel: upgrade rules_go and rules_gazelle

---

build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

*: enable revive for ddl/internal

---

ddl/BUILD.bazel
ddl/cluster.go
ddl/column.go
ddl/ddl.go
ddl/ddl_test.go
ddl/ddl_worker.go
ddl/dist_backfilling.go
ddl/dist_owner.go
ddl/index.go
ddl/internal/session/BUILD.bazel
ddl/internal/session/session.go
ddl/internal/session/session_pool.go
ddl/job_table.go
ddl/job_table_test.go
ddl/partition.go
ddl/reorg.go

This is the code refactoring, let's skip the issue check.
- Extract the `session` to an internal package for better modularity.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: extract session to a separate internal package

---

ddl/column.go
ddl/ddl.go
ddl/ddl_test.go
ddl/ddl_worker_test.go
ddl/job_table.go
ddl/partition.go
ddl/reorg.go

Small cleanup
Tests 
Side effects
Documentation
```release-note
None
```

ddl: clean up reorgCtx

---

WORKSPACE

Issue Number: close #42824
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go 1.19.8

---

br/pkg/lightning/backend/local/BUILD.bazel
br/pkg/lightning/backend/local/engine_test.go
br/pkg/lightning/backend/local/local.go
br/pkg/lightning/backend/local/local_test.go
br/pkg/lightning/backend/local/localhelper_test.go
ddl/ingest/config.go

Issue Number: ref https://github.com/pingcap/tidb/issues/40163
Manually cherry-pick #40228 and #42855
Tests 
Side effects
Documentation
```release-note
None
```

lightning: check peers write stall when switch-mode is disabled (#40228)

---

domain/domain.go
session/session.go

Issue Number: close #42767
Tests 
Side effects
Documentation
```release-note
None
```

session, domain: fix "tidb_global_task doesn't exist" error during bootstrap

---

domain/domain.go
server/server.go
session/session.go
testkit/mocksessionmanager.go

Issue Number: close #42890
Tests 
Side effects
Documentation
```release-note
None
```

domain, session: print more MDL log and make MDL more stable

---

executor/BUILD.bazel
executor/admintest/BUILD.bazel
executor/admintest/admin_test.go
executor/admintest/main_test.go
executor/unstabletest/BUILD.bazel
executor/unstabletest/memory_test.go

Tests 
Side effects
Documentation
```release-note
None
```

admintest: move admin test into new package

---

ddl/ddl_api.go
ddl/partition.go
ddl/table.go

Issue Number: close #42940
This is a cherry-pick for #42957
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Fix issue with truncate table and partitions and tiflash

---

ddl/BUILD.bazel
ddl/ddl.go
ddl/disttask_flow.go
ddl/disttask_flow_test.go
ddl/index.go
ddl/scheduler.go
tests/realtikvtest/addindextest/add_index_test.go

Issue Number: close #42974
Tests 
Side effects
Documentation
```release-note
None
```

ddl, test: integrate add index with the distribute framework

---

util/gctuner/tuner_test.go

Issue Number: close #41280
Tests 
Side effects
Documentation
```release-note
None
```

gcunter: stable TestTuner

---

util/gctuner/memory_limit_tuner_test.go

Issue Number: close #43036
Tests 
Side effects
Documentation
```release-note
None
```

*: stable TestGlobalMemoryTuner

---

store/gcworker/main_test.go

Issue Number: close #43052
Tests 
Side effects
Documentation
```release-note
None
```

gcworker: fix goleak net/http.(*persistConn).writeLoop

---

statistics/handle/handle.go
statistics/table.go

Tests 
Side effects
Documentation
```release-note
None
```

statistics: remove useless parameter

---

ddl/syncer/syncer.go

Issue Number: close https://github.com/pingcap/tidb/issues/43092
Abstract out a watcher in syncer.go. 
Tests 
Side effects
Documentation
```release-note
None
```

ddl: abstract out a watcher

---

util/memory/tracker.go

This is a cherry-pick for #43089 
Issue Number: 
close #42662 
https://github.com/pingcap/tidb/pull/42803 introduces a useless debug log, it's removed in this commit
Tests 
Side effects
Documentation
```release-note
None
```

util: remove useless debug log (#43089)

---

planner/core/integration_test.go
util/ranger/points.go

Issue Number: close #43116
Tests 
Side effects
Documentation
```release-note
None
```

util/ranger: fix collator missing of FullNotNullRange

---

util/memory/tracker.go

Issue Number: 
close #42662 
https://github.com/pingcap/tidb/pull/42803 introduces a useless debug log, it's removed in this commit
Tests 
Side effects
Documentation
```release-note
None
```

util: remove useless debug log

---

server/server_test.go

Issue Number: close #43138
Skip the test
Tests 
Side effects
Documentation
```release-note
None
```

server: skip unstable test TestDBStmtCount

---

planner/core/plan_stats.go

Issue Number: close #43142
- Check if the table is a temporary table, and skip the stats warning during collecting.
Tests 
Side effects
Documentation
```release-note
None
```

planner: skip stats warnings for temporary table during optimize

---

tests/realtikvtest/loaddatatest/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

test: set loaddatatest moderate

---

br/pkg/stream/rewrite_meta_rawkv_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/43170
Problem Summary: fix unstable test
Tests 
Side effects
Documentation
```release-note
None
```

br: fix unstable test

---

ddl/backfilling_scheduler.go
ddl/index.go
ddl/index_cop.go
ddl/ingest/BUILD.bazel
ddl/ingest/integration_test.go

Issue Number: ref #39468
After the code refactoring in #42668, the issue #39468 occurs again.
Recycle add index cop chunks correctly to prevent leakage.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: recycle add index cop chunks correctly

---

ddl/backfilling.go
ddl/backfilling_scheduler.go
ddl/ingest/BUILD.bazel
ddl/ingest/backend.go
ddl/ingest/backend_mgr.go
ddl/ingest/checkpoint.go
ddl/ingest/checkpoint_test.go
ddl/ingest/disk_root.go
ddl/ingest/engine.go
ddl/ingest/env.go
ddl/ingest/mock.go

Issue Number: close #43102
- Update the adding index status with memory counter in checkpoint manager.
- Refine some interfaces.
- Refine log.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: update the row count in time during adding index

---

DEPS.bzl
go.mod
go.sum

Added support for go 1.20 and get more metrics from Golang's runtime.
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade prometheus/client_golang

---

domain/infosync/info.go
domain/infosync/info_test.go
domain/infosync/tiflash_manager.go

Issue Number: close #43070 
create a table with 1000 partitions
```sql
create table t (idx int, b int) 
PARTITION BY RANGE (idx) (
PARTITION p0 VALUES LESS THAN (10),
PARTITION p1 VALUES LESS THAN (20),
PARTITION p2 VALUES LESS THAN (30),
......
PARTITION p998 VALUES LESS THAN (9990),
PARTITION p999 VALUES LESS THAN (10000)
);
```
before
```sql
mysql> truncate table t;
Query OK, 0 rows affected (1.22 sec)
mysql> alter table t set tiflash replica 1;
Query OK, 0 rows affected (2.06 sec)
mysql> truncate table t;
Query OK, 0 rows affected (5.67 sec)
mysql> truncate table t;
Query OK, 0 rows affected (7.69 sec)
mysql> alter table t set tiflash replica 0;
Query OK, 0 rows affected (5.80 sec)
mysql> truncate table t;
Query OK, 0 rows affected (1.26 sec)
```
after
```sql
mysql> …
```

domin: set placement rule of partition table in batch

---

br/pkg/lightning/backend/local/region_job.go

Issue Number: close #43197
- change log level of this log to debug
- 
Tests 
Side effects
Documentation
```release-note
None
```

lighting: change log level to debug for "keys within region is empty, skip doIngest"

---

docs/design/2023-03-14-multi-valued-index.md

Issue Number: close https://github.com/pingcap/tidb/issues/42208
Tests 
```release-note
None
```

doc: add multi-valued index design doc

---

executor/seqtest/seq_executor_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/43272
Tests 
Side effects
Documentation
```release-note
None
```

*: fix unstable test TestIndexMergeReaderClose

---

WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade rules_go 0.39.1

---

session/bench_test.go

Issue Number: close #42729
Tests 
Side effects
Documentation
```release-note
None
```

test: fix the plan for IndexLookUp test not include IndexLookUp

---

session/session.go

Problem Summary: Mannually cherry pick of https://github.com/pingcap/tidb/pull/43282
Tests 
Side effects
Documentation
```release-note
None
```

session: add more log for internal sql when parse failed

---

domain/infosync/info.go
infoschema/tables.go
server/http_status.go
server/plan_replayer.go

Issue Number: close #43260 
Tests 
Side effects
Documentation
```release-note
None
```

server: fix join address on ipv6

---

ddl/ingest/backend_mgr.go
ddl/ingest/disk_root.go

Add some logs before the import in ingest mode.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: add logs before import in ingest mode

---

build/nogo_config.json
domain/BUILD.bazel
domain/domain.go

Tests 
Side effects
Documentation
```release-note
None
```

*: enable SA1019 for more package

---

store/gcworker/BUILD.bazel
store/gcworker/main_test.go

Issue Number: close #43387
Tests 
Side effects
Documentation
```release-note
None
```

*: fix goleak internal/poll.runtime_pollWait

---

executor/oomtest/oom_test.go

Issue Number: close #43396
Tests 
Side effects
Documentation
```release-note
None
```

oomtest: fix data race in the oomtest

---

dumpling/export/BUILD.bazel
tools/tazel/util.go

Tests 
Side effects
Documentation
```release-note
None
```

tazel: enable for dumpling

---

build/nogo_config.json
session/bootstrap.go
session/session.go
session/tidb.go
session/txn.go
session/txninfo/summary.go

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable revive for session 

---

distsql/select_result.go
executor/builder.go
executor/distsql.go
executor/index_merge_reader.go
executor/table_reader.go
planner/core/task.go

Issue Number: close #43241
```
use ExtraPhysTblID instead of `pids` param in `sortedSelecResults`
```
Tests 
```
code refine, the test already coverd.
```
Side effects
Documentation
```release-note
None
```

planner, executor: remove pid param for `sortedSelectResults`

---

planner/core/tiflash_selection_late_materialization.go

Issue Number: close #43421
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix late materialization log may panic (#43349)

---

planner/core/tiflash_selection_late_materialization.go

Issue Number: close #43421
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix late materialization log may panic

---

session/BUILD.bazel
session/bootstrap.go
session/bootstraptest/BUILD.bazel
session/bootstraptest/bootstrap_upgrade_test.go
session/mock_bootstrap.go

Issue Number: close https://github.com/pingcap/tidb/issues/43418
Tests 
Side effects
Documentation
```release-note
None
```

session: add mock upgrading code for testing

---

br/metrics/grafana/lightning.json
br/pkg/lightning/backend/local/localhelper.go
br/pkg/lightning/backend/local/region_job.go
br/pkg/lightning/metric/metric.go
br/pkg/lightning/metric/metric_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/43357
Fix granafa target json file.
Tests 
before:
after:
Side effects
- None
Documentation
- None
```release-note
fix the problem that some lightning panels don't have data
```

lightning: fix some grafana panel json

---

kv/error.go
store/driver/txn/driver_test.go

Issue Number: close #43485 
Inherit redact positions from original error types.
Tests 
Side effects
Documentation
```release-note
None
```

log: let Write Conflict error message respect redact setting

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #43499
Update client-go to include https://github.com/tikv/client-go/pull/788
Tests 
```release-note
None
```

resource_control: Fix missing resource group name for kv_get requests

---

ddl/schematracker/checker.go

Issue Number: close #43516
Tests 
Side effects
Documentation
```release-note
None
```

schemachecker: fix data race at the checker

---

WORKSPACE

Issue Number: close https://github.com/pingcap/tidb/issues/43515
includes security fixes for html/template and fixs some bugs for the compiler. 
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.20.4 

---

br/pkg/conn/conn.go
br/pkg/restore/client.go
br/pkg/restore/client_test.go
br/pkg/restore/import.go
br/pkg/task/restore.go

make log more clear
1. add warn log when set tiflash replica to nil during restore
2. make retryable error to warn log level.
Tests 
Side effects
Documentation
```release-note
None
```

br: make logs more clear.

---

ddl/index.go
ddl/scheduler.go
disttask/framework/dispatcher/BUILD.bazel
disttask/framework/dispatcher/dispatcher.go
disttask/framework/dispatcher/dispatcher_test.go
disttask/framework/proto/task.go
disttask/framework/storage/table_test.go
disttask/framework/storage/task_table.go

Issue Number: close #43497
Tests 
Side effects
Documentation
```release-note
None
```

disttask: support cancel for disttask

---

executor/BUILD.bazel
executor/indexmergereadtest/BUILD.bazel
executor/indexmergereadtest/index_merge_reader_test.go
executor/indexmergereadtest/main_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/43118
- Executor has too mush test cases. we need to move them into the new package to speed up CI.
- enable race to avoid data race.
Tests 
Side effects
Documentation
```release-note
None
```

*: enable race for index_merge_read_test and increase shard for it

---

br/pkg/backup/client.go
br/pkg/backup/schema.go
br/pkg/checkpoint/BUILD.bazel
br/pkg/checkpoint/backup.go
br/pkg/checkpoint/checkpoint.go
br/pkg/checkpoint/checkpoint_test.go
br/pkg/checkpoint/log_restore.go
br/pkg/checkpoint/restore.go
br/pkg/metautil/metafile.go
br/pkg/restore/batcher.go
br/pkg/restore/client.go
br/pkg/restore/client_test.go
br/pkg/restore/pipeline_items.go
br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/stream/rewrite_meta_rawkv_test.go
br/pkg/summary/collector.go
br/pkg/task/backup.go
br/pkg/task/restore.go
br/pkg/task/stream.go

Issue Number: close #43270 
make some enhancements for checkpoint for backup/restore
see in the issue #43270 .
Tests 
Side effects
Documentation
```release-note
None
```

br: enhancement for checkpoint

---

ddl/db_partition_test.go

Issue Number: close #40733
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix data race at the test

---

.gitignore

https://docs.docker.com/desktop/dev-environments/
Tests 
Side effects
Documentation
```release-note
None
```

gitignore: ignore compose-dev.yaml

---

br/pkg/lightning/backend/local/localhelper.go
br/pkg/lightning/backend/local/localhelper_test.go

Tests 
Side effects
Documentation
```release-note
None
```

lightning: add unit tests for #43608 

---

autoid_service/autoid.go
bindinfo/bind_cache.go
bindinfo/handle.go
bindinfo/session_handle.go
bindinfo/stat.go
build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

*: enable revive for autoid_service and bindinfo

---

session/bootstraptest/bootstrap_upgrade_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/43703
Tests 
Side effects
Documentation
```release-note
None
```

session: fix TestUpgradeWithPauseDDL data race

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #43673
Retry leader read when meets flashback-in-progress error, because leader is ready in this case.
Tests 
Side effects
Documentation
```release-note
None
```

client-go: handle flashback error when replica read is used

---

DEPS.bzl
go.mod
go.sum
store/driver/tikv_driver.go

Issue Number: close #43386
Tests 
```release-note
None
```

client-go: fetch the store min resolved_ts by pd api firstly

---

executor/cte.go
executor/cte_test.go
util/cteutil/storage.go

Problem Summary: Manually cp of https://github.com/pingcap/tidb/pull/43758
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix cte may hang because register OOMAction repeatedly

---

session/bootstraptest/main_test.go
structure/main_test.go

Issue Number: close #43053
Tests 
Side effects
Documentation
```release-note
None
```

*: ignore some ttlworker in the goleak

---

ddl/ingest/BUILD.bazel
ddl/ingest/backend_mgr.go
ddl/ingest/checkpoint.go
ddl/ingest/engine_mgr.go
ddl/ingest/main_test.go
ddl/ingest/mock.go
tests/realtikvtest/addindextest/integration_test.go

Issue Number: close #43764
- Add a simple adding index test for `tidb_enable_dist_task`.
- Add goleak check for ingest package.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: enable goleak for ingest package

---

resourcemanager/pool/spool/spool.go

Issue Number: close #43826
Tests 
Side effects
Documentation
```release-note
None
```

spool: add stack information in the panic log

---

executor/cluster_table_test.go
executor/test/showtest/show_test.go
expression/builtin.go
expression/builtin_info.go
parser/ast/functions.go

Issue Number: close https://github.com/pingcap/tidb/issues/43193
Add encode SQL digest function.
Tests 
Side effects
Documentation
```release-note
None
```

*: add encode SQL digest function

---

ddl/rollingback_test.go

Issue Number: close #43889
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix data race at the TestCancelAddIndexJobError

---

br/pkg/lightning/backend/local/localhelper.go
br/pkg/lightning/backend/local/localhelper_test.go

cherry-pick 1 commit from https://github.com/pingcap/tidb/pull/43807

unify retry for waitForScatterRegions

---

executor/test/tiflashtest/tiflash_test.go
planner/core/optimizer.go
store/copr/batch_coprocessor.go

Issue Number: close #43757
Tests 
Side effects
Documentation
```release-note
None
```

*: refine some err msg in disaggregated tiflash mode

---

br/pkg/lightning/backend/local/BUILD.bazel
br/pkg/lightning/backend/local/tikv_mode.go
br/pkg/lightning/importer/BUILD.bazel
br/pkg/lightning/importer/import.go
br/tests/lightning_csv/run.sh

Issue Number: ref #42930
- move switch tikv mode into `local` pkg
Tests 
Side effects
Documentation
```release-note
None
```

lightning: refactor switch mode for reuse

---

BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

gazelle: ignore vendor

---

ddl/syncer/state_syncer_test.go

Issue Number: close #43943
Tests 
Side effects
Documentation
```release-note
None
```

*: fix panic in the TestStateSyncerSimple

---

tests/realtikvtest/loaddatatest/detach_test.go
tests/realtikvtest/loaddatatest/load_data_test.go
tests/realtikvtest/loaddatatest/one_parquet_test.go
tests/realtikvtest/loaddatatest/operate_test.go
tests/realtikvtest/loaddatatest/precheck_test.go
tests/realtikvtest/loaddatatest/show_test.go

- load data physical mode will be reverted in 7.1 so we skip those tests temporary, will add it back when we put it in another statement.
Tests 
Side effects
Documentation
```release-note
None
```

load data: skip physical mode test

---

DEPS.bzl
go.mod
go.sum

revive is a linter. We need to update it daily.
Tests 
Side effects
Documentation
```release-note
None
```

lint: update revive

---

statistics/handle/handletest/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

handletest: enable race

---

timer/api/BUILD.bazel
timer/api/client.go
timer/api/client_test.go
timer/api/error.go
timer/api/hook.go
timer/api/main_test.go
timer/api/mem_store.go
timer/api/store.go
timer/api/store_test.go
timer/api/timer.go
timer/api/timer_test.go

Issue Number: close #43938
- Add a new interface `TimerStoreCore`, the implementation can be different underlayer stores.
- Add a struct `TimerStore` which wraps `TimerStoreCore` to provide some extra methods
- Add a memory implement for `TimerStoreCore`
Tests 
Side effects
Documentation
```release-note
None
```

timer: Add `TimerStore` add a memory implement

---

build/nogo_config.json
planner/core/stats.go

Signed-off-by: SeigeC 486315944@qq.com
Issue Number: close #44058
Tests 
Side effects
Documentation
```release-note
None
```

linter: enable revive for planner/core/status.go

---

server/server.go
sessionctx/variable/session.go

Issue Number: ref #43720 
Add authentication method (e.g. `mysql_native_password`, `caching_sha2_password`, ...) and connection attributes to ConnectionInfo.
```
(dlv) p connInfo
*github.com/pingcap/tidb/sessionctx/variable.ConnectionInfo {
ConnectionID: 2199023255955,
ConnectionType: "TCP",
Host: "2001:****",
ClientIP: "2001:****",
ClientPort: "52418",
ServerID: 1,
ServerIP: "2001:****",
ServerPort: 4000,
Duration: 0,
User: "root",
ServerOSLoginUser: "Daniël van Eeden",
OSVersion: "Linux 6.2.14-300.fc38.x86_64.x86_64",
ClientVersion: "",
ServerVersion: "None",
SSLVersion: "",
PID: 677464,
DB: "",
AuthMethod: "mysql_native_password",
Attributes: map[string]string [
"_os": "FreeBSD13.1", 
"_platform": "amd64", 
"_client_version": "8.0.32", 
"_client_name": "libmysql", …
```

server: Add connection attributes and auth method to conninfo

---

DEPS.bzl
go.mod
go.sum

Signed-off-by: husharp <jinhao.hu@pingcap.com>
Issue Number: close #44103 wait for https://github.com/tikv/client-go/pull/814
Tests 
```release-note
None
```

client-go: when meet GetStoreMinResolvedTS error just write in debug log

---

br/pkg/task/BUILD.bazel
br/pkg/task/backup.go
br/pkg/task/backup_test.go

Issue Number: close #44130 
when use backup checkpoint , config changes are not allowed
only some configurations are not allowed to changed in the next execution.
Tests 
Side effects
Documentation
```release-note
None
```

br: allow to change some configurations for checkpoint for backup

---

expression/grouping_sets.go
expression/grouping_sets_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/44112
add grouping sets utility function for later usage.
Tests 
Side effects
Documentation
```release-note
expression: add rollup grouping sets util
```

expression: add rollup grouping sets util

---

ddl/partition.go
ddl/placement_policy_test.go
infoschema/builder.go

Issue Number: close #44031 close #44116
cherry pick of #44043 and #44129
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix placement issues

---

planner/core/integration_test.go

Issue Number: close #44166
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix unstable test TestAggPushToCopForCachedTable

---

executor/insert_common.go
executor/test/loadremotetest/error_test.go
executor/test/loadremotetest/multi_file_test.go
executor/test/loadremotetest/one_csv_test.go
tests/realtikvtest/loaddatatest/load_data_test.go

Issue Number: close #43555
Tests 
Side effects
Documentation
```release-note
None
```

loaddata: fix inconsistent MySQL error

---

expression/integration_test/integration_test.go

Issue Number: close #44226 
Tests 
Side effects
Documentation
```release-note
None
```

test: fix TestIfFunctionWithNull

---

DEPS.bzl
go.mod
go.sum
store/copr/coprocessor.go

Issue Number: close #43659
Disable stale read after meeting lock.
Tests 
Test sysbench read only without point select(all queries are based on coprocessor).
Side effects
Documentation
```release-note
None
```

store/copr: disable stale read when meeting lock for cop

---

server/conn_stmt.go
server/conn_stmt_test.go

Issue Number: close #44254 
Detach the `memTracker`  if the `resultSet` and `err` are both not empty. Consider the four situations:
1. `resultSet == nil && err == nil`. It will be detached in the defer of `handleNoDelay` directly.
2. `resultSet != nil && err == nil`. It will be detached when the `resultSet` is closed.
3. `resultSet == nil && err != nil`. **This PR fixes this situations** It will be detached right before returning the error.
2. `resultSet != nil && err != nil`. **This PR fixes this situations** It will be detached when the `resultSet` is closed.
Tests 
```release-note
Fix the issue that the `memTracker` is not cleared when facing an error while executing statement with cursor fetch.
```

server: fix memtracker leak with cursor

---

ddl/job_table.go
ddl/reorg.go

Issue Number: close https://github.com/pingcap/tidb/issues/44265
This is a cherry-pick PR for #44271.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix ingest checkpoint not resumed for empty partitions (#44271)

---

ddl/job_table.go
ddl/reorg.go

Issue Number: close #44265
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix ingest checkpoint not resumed for empty partitions

---

cmd/explaintest/r/cte.result
cmd/explaintest/r/explain_cte.result
executor/explain_test.go
executor/oomtest/BUILD.bazel
planner/core/expression_rewriter.go
planner/core/integration_test.go
planner/core/issuetest/BUILD.bazel
planner/core/issuetest/planner_issue_test.go
planner/core/planbuilder.go
planner/core/rule_predicate_push_down.go
planner/core/stats.go
planner/core/testdata/flat_plan_suite_out.json
planner/core/testdata/plan_suite_out.json

Issue Number: ref #44054, ref #43759
Tests 
Side effects
Documentation
```release-note
None
```

planner: cherry pick two CTE related commit | tidb-test=pr/2145

---

build/nogo_config.json
planner/core/logical_plans.go
planner/core/plan_cost_ver2.go

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable revive for part of planner 

---

ddl/ingest/env.go
executor/importer/table_import.go
util/rlimit_other.go

Issue Number: close #44319 
Tests 
Side effects
Documentation
```release-note
None
```

*: refine log for `GenRLimit`

---

metrics/grafana/tidb_resource_control.json

Issue Number: ref #38825
Tests 
Side effects
Documentation
```release-note
None
```

metrics: add metrics for avaiable RU

---

build/nogo_config.json
statistics/handle/dump.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/lru_cache.go
statistics/handle/statscache.go
statistics/handle/update.go

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable fieldalignment for statistics/handle

---

session/txnmanager.go
sessiontxn/interface.go

Issue Number: close #44361
Tests 
Side effects
Documentation
```release-note
None
```

txn: delete useless `SetTxnInfoSchema` in `TxnManager`

---

br/pkg/aws/BUILD.bazel
br/pkg/aws/ebs.go

Issue Number: close #44325
See the issue.
This PR added some utilities for retrying when the snapshot count reaches the quota.
Tests 
(TBD)
Side effects
Documentation
```release-note
None
```

ebs_backup: added retry for exceeding of quota

---

README.md

Add Playground link to the 'What is TiDB' section
Tests 
Side effects
Documentation
```release-note
None
```

*: Add TiDB Playground portal in README.md

---

br/pkg/aws/ebs.go

Issue Number: close #43934 
This pr refactored to 
1. carry all tags of ebs volume to the snapshots as they are
2. carry tags for snapshots to restored volume whose keys of tags are prefixed with "snapshot/"
Tests 
Verify the logic by EBS snapshot backup and restore, take one volume as example,
original tags
snapshot for the volume
tags for restored volume
Side effects
Documentation
```release-note
None
```

br: ebs tags refactoring

---

go.mod
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/historical_stats_handler.go
statistics/handle/update.go

Tests 
Side effects
Documentation
```release-note
None
```

statistic: use atomic.Pointer to avoid type conversions

---

ddl/pausetest/pause_test.go

Issue Number: close #44417 
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix data race in pause ddl test 

---

Dockerfile
Dockerfile.enterprise

Tests 
Side effects
Documentation
```release-note
None
```

dockerfile: upgrade golang

---

br/pkg/lightning/backend/backend.go
ddl/ddl.go
ddl/ddl_worker.go
ddl/ingest/engine.go
executor/analyze_global_stats.go

Issue Number: ref #44371
Tests 
Side effects
Documentation
```release-note
None
```

*: change some error logs to warn logs

---

executor/index_merge_reader.go
executor/partition_table_test.go
kv/BUILD.bazel
kv/key.go
kv/key_test.go
planner/core/casetest/testdata/integration_partition_suite_out.json
planner/core/find_best_task.go
planner/core/task.go

Issue Number: close #44312
Problem Summary: After exchange partition, a partition table may have same `_tidb_rowid` in different partition tables. So the handleMap should supports partitionHandle.
Tests 
Side effects
Documentation
```release-note
None
```

*: let handleMap supports partitionHandle

---

planner/core/plan_cache_utils.go
tablecodec/tablecodec.go
ttl/cache/split_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: remove useless

---

distsql/distsql.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go

Issue Number: close #44468
Tests 
Side effects
Documentation
```release-note
None
```

session,executor: add variables to support set if enable tiflash pipeline model by sql statement

---

Dockerfile
Dockerfile.enterprise
WORKSPACE
build/image/base
tests/globalkilltest/Dockerfile

Issue Number: ref #44476
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.20.5

---

disttask/framework/dispatcher/dispatcher.go

Issue Number: close #44483 
Tests 
Side effects
Documentation
```release-note
None
```

disttask: Refine dispatcher

---

domain/domain.go

Tests 
Side effects
Documentation
```release-note
None
```

domain: avoid using unsafe

---

README.md

Issue Number: close https://github.com/pingcap/tidb/issues/44538
Tests 
Side effects
Documentation
```release-note
None
```

docs: update build badge on docs

---

ddl/ddl.go

Issue Number: close #44534 
Tests 
Side effects
Documentation
```release-note
None
```

ddl, test: fix data race in owner change test

---

executor/adapter.go
executor/adapter_test.go
util/stmtsummary/statement_summary.go
util/stmtsummary/v2/record.go

Issue Number: close #44542
Tests 
Side effects
Documentation
```release-note
None
```

executor: avoid using fmt.Sprint to truncate the string

---

timer/api/BUILD.bazel
timer/api/mem_store.go
timer/runtime/BUILD.bazel

Issue Number: close #44576
Tests 
Side effects
Documentation
```release-note
None
```

timer: fix data race in timer store

---

DEPS.bzl
go.mod
go.sum

Issue Number: Ref #44431, close #44471
Related PR: https://github.com/tikv/client-go/pull/833
Tests 
Side effects
Documentation
```release-note
None
```

client-go: update tikv client-go for batch_client auto re-connect idle connection when wait connection ready

---

domain/infosync/BUILD.bazel
domain/infosync/resource_group_manager.go
store/mockstore/unistore/pd.go

Issue Number: close #44596
Problem Summary: Update mock API to fix tikv client-go ci.
```sql
go mod edit -replace=github.com/tikv/client-go/v2=../client-go
go mod tidy
make server
```
```shell
domain/infosync/resource_group_manager.go:50:9: cannot use mockMgr (variable of type *mockResourceGroupManager) as pd.ResourceManagerClient value in return statement: *mockResourceGroupManager does not implement pd.ResourceManagerClient (missing method LoadResourceGroups)
domain/infosync/resource_group_manager.go:53:34: cannot use (*mockResourceGroupManager)(nil) (value of type *mockResourceGroupManager) as pd.ResourceManagerClient value in variable declaration: *mockResourceGroupManager does not implement pd.ResourceManagerClient (missing method LoadResourceGroups) …
```

*: fix for tikv client-go

---

OWNERS

See https://github.com/pingcap/community/pull/762
Tests 
Side effects
Documentation
```release-note
None
```

OWNERS: add elsa0520 to reviewers

---

executor/BUILD.bazel
executor/show_stats_test.go
statistics/handle/handle.go
statistics/handle/update.go

Issue Number: close #44532
It appears that there is a problem with the test code where there may be a data race occurring in the TTL section. Therefore, the disable TTL feature is necessary for this test.
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix data race at the TestShowStatsExtended

---

server/statistics_handler.go

Issue Number: close #44648
Please see the issue.
As the title says
Tests 
Since it's not easy to mock such a scenario in UT. I choose to test it manually.
Tested as specified in the issue.
Side effects
Documentation
```release-note
None
```

server: try to use latest infoschema if failed to get snapshot infoschema in historical stats HTTP API

---

ddl/ingest/disk_root.go

Issue Number: close #44584
The performance regression is introduced by #44307, which added a lock for the writers before getting the `EngineFileSize`.
Under sysbench 70 millions rows, the performance of adding index:
Before #44307:
```
mysql> alter table sbtest1 add index idx(c, pad);
Query OK, 0 rows affected (2 min 34.06 sec)
```
After #44307:
```
mysql> alter table sbtest1 add index idx(c, pad);
Query OK, 0 rows affected (3 min 51.65 sec)
```
The root cause is that reorg workers invoke `CheckDiskQuota()` every time a batch of index records is written. This could happen concurrently so the performance is not affected before #44584.
This PR prevents updating the disk usage too frequently.
Tests 
```
mysql> alter table sbtest1 add index idx(c, pad);
Query OK, 0 rows …
```

ddl/ingest: prevent update disk usage too frequently

---

disttask/framework/scheduler/manager.go
disttask/importinto/dispatcher.go
tests/realtikvtest/importintotest/import_into_test.go

- revert add index via SQL
Tests 
Side effects
Documentation
```release-note
None
```

import into: revert add index via SQL

---

build/nogo_config.json
planner/core/common_plans.go
planner/core/plan_cache_lru.go
planner/core/preprocess.go
planner/core/task.go

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable revive for part planner/core

---

WORKSPACE

Issue Number: close #44476
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.19.10

---

br/pkg/storage/azblob_test.go

Issue Number: close #44652 
we have no azurite in the test environment, so just skip the test.
Tests 
Side effects
Documentation
```release-note
None
```

test: close azblob test

---

timer/store_intergartion_test.go

Issue Number: close #44708
Tests 
Side effects
Documentation
```release-note
None
```

timer: fix unstable test `TestEtcdNotifier`

---

executor/BUILD.bazel
executor/infoschema_reader.go
executor/infoschema_reader_test.go
executor/test/analyzetest/analyze_test.go
infoschema/tables.go
planner/core/planbuilder.go

Issue Number: ref #44033
we first remove this function. and It will be added next sprint.
Tests 
Side effects
Documentation
```release-note
None
```

executor: remove remain time for show analyze

---

expression/builtin_regexp.go
expression/builtin_regexp_test.go

Issue Number: close #44684 
Tests 
Side effects
Documentation
```release-note
None
```

expression: change escape character from '$' to '\' for `regexp_replace`

---

timer/api/mem_store.go

Issue Number: close #44720
Tests 
Side effects
Documentation
```release-note
None
```

timer: use read/write lock for timer's memory store

---

disttask/importinto/dispatcher.go
executor/import_into.go
executor/importer/precheck.go
tests/realtikvtest/importintotest/precheck_test.go

Issue Number: close #44729
- add precheck when total file size is 0, either when no matched file or when file is empty
- enhance how we check task finish
- current framework takes task as finished when `no err and no subtask` when switch to next step.
Tests 
- without this precheck, and with the enhancement, create a task with no matched file, the task can be finished.
Side effects
Documentation
```release-note
None
```

import into: add precheck when total file size is 0 & enhance how we check task finish

---

br/pkg/storage/azblob.go

Issue Number: ref #44199 
the feature server-side encryption won't be GA, so hide the parameter.
Tests 
Side effects
Documentation
```release-note
None
```

br: hide_encryption_scope

---

.bazelrc

Problem Summary: In #37247, bazel logs of passed tests are suppresed by `test_output=errors` and `test_summary=testcase`. However, there are lots of sharding tests. It is now hard to find and solve failed tests. Try `test_summary=detailed` to print the summary of non-passed testcases.
PASSED cases are still supressed.
Tests 
Side effects
Documentation
```release-note
None
```

*: output non-passed test cases

---

parser/mysql/const.go

Reverts pingcap/tidb#42560
As requested by @songrijie
The plan is to re-apply the original PR once the character set improvements are done.
```release-note
None
```

Revert "parser: Update ServerVersion to 8.0.11"

---

Makefile
tools/check/check-bazel-prepare-rbe.sh

Issue Number: ref #44765
Tests 
Side effects
Documentation
```release-note
None
```

makefile: support rbe for bazel prepare in ci

---

executor/distsql.go
executor/index_merge_reader.go

Issue Number: close #44773
Problem Summary: Eliminate some implicit assumptions between plan and execute in `hasExtralPidCol` function, reducing the risk of problems later.
Tests 
Side effects
Documentation
```release-note
None
```

executor: improve code for `hasExtralPidCol` function

---

br/pkg/lightning/web/res_vfsdata.go
build/linter/gosec/analysis.go
build/linter/util/util.go
domain/plan_replayer.go
executor/analyze_test.go
parser/goyacc/format_yacc.go
parser/goyacc/main.go
session/bootstrap.go
util/security.go
util/tiflashcompute/topo_fetcher.go
util/watcher/watcher.go
util/watcher/watcher_test.go

remove refs to deprecated io/ioutil
Tests 
Side effects
Documentation
```release-note
None
```

*: remove refs to deprecated io/ioutil

---

executor/BUILD.bazel
executor/infoschema_reader.go
executor/infoschema_reader_test.go
executor/test/analyzetest/analyze_test.go
infoschema/tables.go
planner/core/planbuilder.go

Reverts pingcap/tidb#44717
Issue Number: ref https://github.com/pingcap/tidb/issues/44033
re-support remain time for show analyze
Tests 
Side effects
Documentation
```release-note
None
```

executor: support remain time for show analyze

---

executor/builder.go
executor/internal/mpp/local_mpp_coordinator.go
executor/prepared_test.go
executor/test/showtest/show_test.go
executor/test/tiflashtest/tiflash_test.go
expression/integration_test/integration_test.go
kv/mpp.go
planner/core/casetest/cbotest/testdata/analyze_suite_out.json
planner/core/casetest/enforce_mpp_test.go
planner/core/casetest/integration_test.go
planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
planner/core/casetest/testdata/enforce_mpp_suite_out.json
planner/core/casetest/testdata/integration_suite_in.json
planner/core/casetest/testdata/integration_suite_out.json
planner/core/casetest/testdata/window_push_down_suite_out.json
planner/core/casetest/tiflash_selection_late_materialization_test.go
planner/core/find_best_task.go
planner/core/fragment.go
planner/core/integration_test.go
planner/core/plan_test.go
planner/core/testdata/runtime_filter_generator_suite_out.json
server/conn_test.go
sessionctx/sessionstates/session_states_test.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
store/batch_coprocessor_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/37459
Tests 
Side effects
Documentation
```release-note
None
```

planner: complete fall through into MPP task if up-layer can generate a cop tiflash 

---

expression/builtin_cast.go
expression/builtin_cast_test.go
expression/typeinfer_test.go

Issue Number: close #44786 
Tests 
Side effects
Documentation
```release-note
None
```

expression: fix cast negint to string

---

DEPS.bzl
go.mod
go.sum

Issue Number: ref #44032 
Tests 
Side effects
Documentation
```release-note
None
```

*: update kvproto and tipb go mod 

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #44818, close #44800
Update client-go to apply https://github.com/tikv/client-go/pull/848 to fix a data race in ResourceControlInterceptor.
Tests 
Side effects
Documentation
```release-note
None
```

test: fix data race by updating client-go

---

br/web/README.md
br/web/package-lock.json

Close: https://github.com/pingcap/tidb/security/dependabot/53
Close: https://github.com/pingcap/tidb/security/dependabot/28
Update the README to reflect changes after BR was merged into pingcap/tidb
Related:
- #40333 
- #42228
Tests 
Side effects
Documentation
```release-note
Security updates for the TiDB Lightning web interface were applied
```

br: Update web deps and README

---

ttl/ttlworker/job_manager.go
ttl/ttlworker/job_manager_integration_test.go
ttl/ttlworker/job_manager_test.go

Issue Number: close #44767
Tests 
Side effects
Documentation
```release-note
ttl: fix ttl job start time will be override after failover
```

ttl: fix ttl job start time will be override after failover

---

.github/licenserc.yml
WORKSPACE
WORKSPACE.patchgo
tools/patch-go/Dockerfile
tools/patch-go/build.sh

Issue Number: ref #41574
Tests 
Side effects
Documentation
```release-note
None
```

patchgo: add build script for it

---

util/topsql/reporter/mock/server.go

Issue Number: ref #44736 
Tests 
Side effects
Documentation
```release-note
None
```

topsql: use atomic.Pointer to replace with atomic.Value

---

.bazelrc

Tests 
Side effects
Documentation
```release-note
None
```

*: expand the experimental_ui_max_stdouterr_bytes

---

WORKSPACE
WORKSPACE.patchgo
util/signal/BUILD.bazel

Issue Number: close #44909
Tests 
Side effects
Documentation
```release-note
None
```

bazel: upgrade gazelle

---

WORKSPACE
WORKSPACE.patchgo

Issue Number: close #44909
Tests 
Side effects
Documentation
```release-note
None
```

bazel: upgrade rules_go

---

executor/test/oomtest/oom_test.go

Issue Number: close #44912
It is recommended to first clear out the old filters and then register the new ones.
Tests 
Side effects
Documentation
```release-note
None
```

*: deflake the TestMemTracker4InsertAndReplaceExec

---

build/nogo_config.json
planner/core/expression_rewriter.go
planner/core/indexmerge_path.go
planner/core/plan_cache_utils.go
planner/core/plan_cacheable_checker.go
planner/core/resolve_indices.go
planner/core/rule_decorrelate.go
planner/core/rule_join_reorder.go

Issue Number: close https://github.com/pingcap/tidb/issues/44113
close https://github.com/pingcap/tidb/issues/44085
ref https://github.com/pingcap/tidb/issues/40786
Tests 
Side effects
Documentation
```release-note
None
```

planner: enable revive for all planner

---

WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

*: add mirror for rbe

---

executor/foreign_key.go
executor/test/fktest/BUILD.bazel
executor/test/fktest/foreign_key_test.go

Issue Number: close #44848
Problem Summary: fix issue of update with same foreign key value returns error
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix issue of update with same foreign key value returns error

---

disttask/framework/BUILD.bazel
disttask/framework/dispatcher/BUILD.bazel
disttask/framework/dispatcher/dispatcher.go
disttask/framework/dispatcher/dispatcher_test.go
disttask/framework/framework_rollback_test.go
disttask/framework/framework_test.go
util/disttask/idservice.go

Issue Number: ref #44399 
Add rollback test that ensure all scheduler called `Rollback` function.
1. add `framework_rollback_test.go`, register a scheduler that count the called time of `Rollback`.
2. fix a bug that mimic distributed test didn't use mock serverInfos to dispatch rollback subtask by changing the interface `GetAllSchedulerIDs`.
Note: We choose to add failpoints to test the rollback case. In future, if we have injected enough failpoints, we will summarize all of them, and transfer some of them into hook to make the code cleaner.
Tests 
Side effects
Documentation
```release-note
None …
```

disttask/test: add rollback test

---

executor/test/jointest/hashjoin/BUILD.bazel
executor/test/jointest/hashjoin/hash_join_test.go
executor/test/jointest/hashjoin/main_test.go
executor/test/jointest/join_test.go

Tests 
Side effects
Documentation
```release-note
None
```

executor: split test and create hash_join_test to improve ci

---

executor/infoschema_reader.go
executor/infoschema_reader_test.go
infoschema/tables.go

Issue Number: close https://github.com/pingcap/tidb/issues/44933
Tests 
Side effects
Documentation
```release-note
None
```

executor: unite the type of the progress in the analyze status

---

parser/README.md

Issue Number: close https://github.com/pingcap/tidb/issues/44931
```release-note
None
```

README: Add sqlc to the list of parser users

---

DEPS.bzl
go.mod
go.sum

Issue Number: ref #44032 
Tests 
Side effects
Documentation
```release-note
None
```

*: udpate kvproto version so that tiflash side related changes can submit

---

config/config_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/44906
Tests 
Side effects
Documentation
```release-note
None
```

config: avoid file conflicts between tests

---

executor/test/oomtest/oom_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/44949
Tests 
Side effects
Documentation
```release-note
None
```

oomtest: fix data race in the oomCapture

---

br/pkg/lightning/config/config.go
executor/importer/table_import.go

Issue Number: close https://github.com/pingcap/tidb/issues/44926
reduce diskquota check interval, from 1m -> 10s
Tests 
Side effects
Documentation
```release-note
None
```

lightning, importinto: reduce disk quota interval

---

DEPS.bzl
go.mod
go.sum

Issue Number: Ref #43481
Problem Summary: update tikv/client-go in go.mod
Related fix:
- https://github.com/tikv/client-go/pull/846
- https://github.com/tikv/client-go/pull/851
Tests 
Side effects
Documentation
```release-note
None
```

*: update tikv/client-go

---

domain/plan_replayer.go

Issue Number: close #45019 
Tests 
Side effects
Documentation
```release-note
Logging related to the plan replayer has been updated to not show expected failures
```

domain: Make dumpFileGcChecker logging less noisy

---

disttask/importinto/scheduler.go

Reverts pingcap/tidb#45049
Issue Number: ref #45048
- revert pingcap/tidb#45049, due to ci issue, some test has failed but ci still merge it
Tests 
Side effects
Documentation
```release-note
None
```

revert import into: fix some subtask keeps running on cancel when triggered disk quota

---

planner/core/rule_max_min_eliminate.go

Tests 
Side effects
Documentation
```release-note
None
```

planner: fix a typo error

---

tests/realtikvtest/testkit.go

Issue Number: close #45091
Tests 
Side effects
Documentation
```release-note
None
```

importintotest: fix goleak on opencensus 

---

br/pkg/task/backup_ebs.go

Issue Number: close #44806 
Metadata file for EBS backup could miss being written to S3 due to BR pod is killed prematurely. As a consequence, later deleting of delete CR will leave orphan snapshots.
Save the metadata file for EBS backup once CreateSnapshots requests are issued to AWS instead of waiting for snapshots creation is done.
Tests 
Side effects
Documentation
```release-note
None
```

br: save meta file for ebs backup earlier

---

go.mod
go.sum

Issue Number: close #43243 close #44822
Bump client-go to fix #43243 & #44822 in release-6.1.
Tests 
Side effects
Documentation
```release-note
None
```

*: bump tikv client-go

---

br/pkg/lightning/backend/local/local_windows.go
util/rlimit_windows.go
util/signal/signal_windows.go

Issue Number: close #45089 
Tests 
Side effects
Documentation
```release-note
None
```

util: Fix building on Windows

---

.github/workflows/integration-test-compile-br.yml

- Combine `compile` and `compile-windows`
- Simplify matrix
- Use `setup-go@v3`
- Use `go.mod` instead of specific version
- Allow workflow dispatch
- Update if condition
Tests 
Side effects
Documentation
```release-note
None
```

ci: Rework integration-test-compile-br

---

tests/graceshutdown/graceshutdown_test.go

Issue Number: close #45108
#44953 changed to wait for connections in transaction only for graceful shutdown..
This PR fix the e2e test case [`graceshutdown`](https://github.com/pingcap/tidb/tree/master/tests/graceshutdown) by executing query in transaction.
Tests 
Side effects
Documentation
```release-note
None
```

tests: fix e2e test `graceshutdown`

---

build/nogo_config.json
statistics/builder.go
statistics/cmsketch.go
statistics/debugtrace.go
statistics/estimate.go
statistics/feedback.go
statistics/handle/bootstrap.go
statistics/handle/dump.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/update.go
statistics/table.go

Tests 
Side effects
Documentation
```release-note
None
```

statistics: enable revive

---

owner/manager.go
owner/mock.go

Issue Number: close #45106
Tests 
Side effects
Documentation
```release-note
None
```

*: fix data race at the mockOwnerOpValue

---

planner/core/plan.go

Fix a typo.
Tests 
Side effects
Documentation
```release-note
None
```

planner: fix typo in comment

---

executor/internal/mpp/local_mpp_coordinator.go
executor/internal/util/partition_table.go
expression/builtin_grouping.go
expression/expr_to_pb.go
expression/expr_to_pb_test.go
planner/core/logical_plans_test.go
planner/core/physical_plans.go
planner/core/plan_to_pb.go

Issue Number: close https://github.com/pingcap/tidb/issues/45179
Tests 
Side effects
Documentation
```release-note
planner: physical expand support being converted to tipb.Expand2
```

planner: physical expand support being converted to tipb.Expand2

---

WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade rules_go

---

executor/builder.go
executor/cte.go
executor/cte_test.go

This is an manually cherry-pick of https://github.com/pingcap/tidb/pull/44643
Tests 
Side effects
Documentation
```release-note
None
```

executor: add CTEProducer that shared by all CTEExec

---

README.md

Issue Number: ref  None
1. Align the first div to center and make the TiDB logo clickable
2. Add two website links
a. Visit the Official Website -> https://www.pingcap.com/
b. Try it Online -> https://play.tidbcloud.com/
3. Add social media quick links
a. TiDB Developer twitter account
b. Forum
c. Slack
d. Stack Overflow
```release-note
None
```

README: add badges and links

---

server/tidb_test.go

Issue Number: close #45216
Tests 
Side effects
Documentation
```release-note
None
```

*: avoid use same port

---

session/sessiontest/session_test.go
session/sessiontest/vars/BUILD.bazel
session/sessiontest/vars/vars_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/44940
Tests 
Side effects
Documentation
```release-note
None
```

session: update sessiontest for improve ci

---

executor/internal/mpp/local_mpp_coordinator.go
executor/mpp_gather.go
kv/mpp.go
planner/core/fragment.go
store/copr/mpp.go
store/mockstore/unistore/cophandler/mpp.go

Issue Number: close #45225
Set `mpp_gather_id` for all mpp task meta.
Tests 
Side effects
Documentation
```release-note
None
```

executor: set `mpp_gather_id` for all mpp task meta

---

statistics/handle/bootstrap.go
statistics/handle/cache/internal/inner.go
statistics/handle/cache/internal/lru/lru_cache.go
statistics/handle/cache/internal/mapcache/map_cache.go
statistics/handle/cache/statscache.go
statistics/handle/cache/statscacheinner.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/update.go

Problem Summary: planner: simplify `StatsCacheWrapper`
planner: simplify `StatsCacheWrapper`
Tests 
Side effects
Documentation
```release-note
None
```

planner: simplify StatsCacheWrapper

---

statistics/handle/cache/BUILD.bazel
statistics/handle/cache/statscache.go
statistics/handle/handle.go

Problem Summary: planner: simplify `StatsCachePointer`
planner: simplify `StatsCachePointer`
Tests 
Side effects
Documentation
```release-note
None
```

planner: simplify `StatsCachePointer`

---

timer/BUILD.bazel
timer/api/BUILD.bazel
timer/api/client.go
timer/api/client_test.go
timer/api/error.go
timer/api/hook.go
timer/api/store.go
timer/api/store_test.go
timer/api/timer.go
timer/runtime/BUILD.bazel
timer/runtime/cache.go
timer/runtime/cache_test.go
timer/runtime/runtime.go
timer/runtime/runtime_test.go
timer/runtime/worker.go
timer/runtime/worker_test.go
timer/store_intergartion_test.go
timer/tablestore/sql.go
timer/tablestore/sql_test.go
timer/tablestore/store.go

Issue Number: close #45009
A new field `ManualRequest` is added to `TimerRecord` , it is defined as below
```
// ManualRequest is the request info to trigger timer manually
type ManualRequest struct {
// ManualRequestID is the id of manual request
ManualRequestID string
// ManualRequestTime is the request time
ManualRequestTime time.Time
// ManualTimeout is the timeout for the request, if the timer is not triggered after timeout, processed will be set to true
// with empty event id.
ManualTimeout time.Duration
// ManualProcessed indicates the request is processed (triggered or timeout)
ManualProcessed bool
// ManualEventID means the triggered event id for the current request
ManualEventID string
}
```
We can invoke `client.ManualTriggerEvent` to trigger a timer event manually, after it …

timer: support manual trigger for timer framework

---

executor/test/indexmergereadtest/BUILD.bazel
executor/test/indexmergereadtest/index_merge_reader_test.go

Tests 
Side effects
Documentation
```release-note
None
```

executor: improve performance for test

---

tools/tazel/util.go
util/chunk/BUILD.bazel
util/stmtsummary/BUILD.bazel
util/stmtsummary/v2/BUILD.bazel
util/stmtsummary/v2/tests/BUILD.bazel

ref #41377
Tests 
Side effects
Documentation
```release-note
None
```

kazel: enable shard_count for util/chunk

---

build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

forcetypeassert: ignore testmain.go

---

statistics/handle/bootstrap.go
statistics/handle/cache/internal/inner.go
statistics/handle/cache/internal/lru/lru_cache.go
statistics/handle/cache/internal/lru/lru_cache_test.go
statistics/handle/cache/internal/mapcache/map_cache.go
statistics/handle/cache/statscacheinner.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/historical_stats_handler.go
statistics/handle/update.go

Issue Number: close #45303
Tests 
Side effects
Documentation
```release-note
None
```

statcache: remove GetByQuery and PutByQuery

---

WORKSPACE
WORKSPACE.patchgo

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade rules_go 0.41

---

WORKSPACE

Issue Number: ref #45316
Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.20.6

---

executor/infoschema_reader.go

Issue Number: close #45320 
https://github.com/pingcap/tiflash/issues/7795
```shell
$ mysql --comments --host 127.0.0.1 --port 4000 -u root
mysql> use test
mysql> create table t1 (i int); # have privilege
Query OK, 0 rows affected (0.08 sec)
mysql> create table t2 (i int); # do not have privilege
Query OK, 0 rows affected (0.08 sec)
mysql> create table t3 (i int); # do not have tiflash replica
Query OK, 0 rows affected (0.08 sec)
mysql> alter table t1 set tiflash replica 1;
Query OK, 0 rows affected (0.08 sec)
mysql> alter table t2 set tiflash replica 1;
Query OK, 0 rows affected (0.08 sec)
mysql> select TABLE_NAME, AVAILABLE from information_schema.tiflash_replica where TABLE_SCHEMA='test';
+------------+-----------+
| TABLE_NAME | AVAILABLE | …
```

executor: fix privilege issue on table `information_schema.tiflash_replica`

---

ddl/tests/resourcegroup/resource_group_test.go
executor/infoschema_reader.go
parser/ast/ddl.go
parser/misc.go
parser/model/model.go
parser/parser.y
parser/parser_test.go

Issue Number: ref #44517
Problem Summary: ref #45189
`task_names` is inaccurate, let's change it to `task_types`.
N/A
Tests 
Side effects
Documentation
```release-note
None
```

parser: change token `TASK_NAMES` to `TASK_TYPES`

---

WORKSPACE

Issue Number: close #45316
Tests 
Side effects
Documentation
```release-note
None
```

*: use go 1.19.11

---

ddl/backfilling_scheduler.go
ddl/index.go
ddl/index_cop.go
ddl/ingest/backend.go
ddl/ingest/backend_mgr.go
ddl/ingest/config.go
ddl/ingest/disk_root.go
ddl/ingest/engine.go
ddl/ingest/engine_mgr.go
ddl/ingest/env.go
ddl/ingest/message.go
ddl/scheduler.go
util/logutil/log.go

Issue Number: ref #45057
https://github.com/pingcap/tidb/pull/45058 did not update the log message in `ddl/ingest/message.go`.
N/A
Tests 
Side effects
Documentation
```release-note
None
```

ddl: move ddl-ingest log category into a real field

---

DEPS.bzl
go.mod
go.sum

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade dependency

---

build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

executor: enable revive for executor/concurrent_map.go

---

build/nogo_config.json
executor/adapter.go
executor/admin.go
executor/admin_plugins.go
executor/admin_telemetry.go

Enable revive checking for all files "executor/a*".
for example, ```adapter.go```, ```admin.go```.
Tests 
Side effects
Documentation
```release-note
None
```

executor: enable revive for executor/a*

---

build/linter/toomanytests/analyze.go
build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable toomanytests for more package

---

br/pkg/lightning/backend/tidb/BUILD.bazel
br/pkg/lightning/backend/tidb/tidb.go
br/pkg/lightning/backend/tidb/tidb_test.go
br/pkg/lightning/errormanager/errormanager.go
br/pkg/lightning/importer/import.go
br/tests/_utils/generate_certs
br/tests/_utils/run_lightning
br/tests/_utils/run_lightning_ctl
br/tests/lightning_config_max_error/run.sh
br/tests/lightning_config_max_error/tidb-limit-record.toml
br/tests/lightning_tidb_duplicate_data/replace.toml

use affected rows to check if batch insert meets duplications
Tests 
Side effects
Documentation
```release-note
None
```

lightning: tidb backend will check conflict threshold

---

build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

lint: enable toomanytest for more package

---

planner/core/logical_plan_builder.go
planner/core/plan_cache_test.go

Issue Number: ref #45253
Problem Summary: planner: add more test cases for plan-cache
planner: add more test cases for plan-cache
Tests 
Side effects
Documentation
```release-note
None
```

planner: add more test cases for plan-cache

---

timer/tablestore/BUILD.bazel
timer/tablestore/sql_test.go
timer/tablestore/store.go

Issue Number: close #45527
Tests 
Side effects
Documentation
```release-note
None
```

timer: Add more tests for 'takeSession' and 'runInTxn' in timer table store

---

metrics/grafana/tidb.json

Issue Number: close #45287
The panel preview:
Tests 
Side effects
Documentation
```release-note
None
```

metrics: add grafana panel for follower read

---

statistics/handle/bootstrap.go
statistics/handle/cache/statscacheinner.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/update.go

Issue Number: ref https://github.com/pingcap/tidb/issues/45367
Tests 
Side effects
Documentation
```release-note
None
```

statistics: not always COW to update stats cache

---

build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable toomanytests for planner casetest 

---

executor/test/tiflashtest/BUILD.bazel
executor/test/tiflashtest/tiflash_test.go

Tests 
Side effects
Documentation
```release-note
None
```

tiflashtest: remove skiprace

---

planner/core/casetest/enforcempp/enforce_mpp_test.go
planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json
planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
planner/core/logical_plan_builder.go
planner/core/logical_plans.go
planner/core/rule_column_pruning.go

Issue Number: close https://github.com/pingcap/tidb/issues/45593
Details ref about the issue discription
Tests 
Side effects
Documentation
```release-note
planner: fix order-by item should be resolved to grouping item under rollup
```

planner: fix order-by item should be resolved to grouping item under rollup

---

planner/core/preprocess.go

Issue Number: close https://github.com/pingcap/tidb/issues/45596
Tests 
Side effects
Documentation
```release-note
None
```

planner/core: remove redundant checks for the DB name

---

.codecov.yml

Tests 
Side effects
Documentation
```release-note
None
```

*: update .codecov to skip the testutil

---

metrics/grafana/tidb_resource_control.json

Issue Number: ref #44517 
The metrics at tikv side is added in https://github.com/tikv/tikv/pull/15195
Screen snapshot:
Tests 
Side effects
Documentation
```release-note
None
```

resource_control: add grafana panel for background task control

---

build/nogo_config.json

Tests 
Side effects
Documentation
```release-note
None
```

linter: enable toomanytests for domain

---

build/nogo_config.json
executor/internal/calibrateresource/calibrate_resource.go
executor/internal/mpp/local_mpp_coordinator.go
executor/internal/pdhelper/pd.go
executor/internal/querywatch/query_watch.go

Issue Number: ref https://github.com/pingcap/tidb/issues/40786
Tests 
Side effects
Documentation
```release-note
None
```

*: enable the fieldalignment for part package

---

cmd/explaintest/BUILD.bazel
cmd/explaintest/main.go

Issue Number: close #45681
Tests 
Side effects
Documentation
```release-note
None
```

explaintest: improve retry for open db

---

ddl/db_partition_test.go
ddl/partition.go

Issue Number: close #45694
Tests 
Side effects
Documentation
```release-note
None
```

ddl: Fix NULL values in List partitioning.

---

planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json
planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
planner/core/logical_plan_builder.go

Issue Number: close https://github.com/pingcap/tidb/issues/45661
Tests 
Side effects
Documentation
```release-note
Fix grouping function validation
```

planner: defer grouping function validation to expression rewriting logic

---

statistics/cmsketch.go

Tests 
Side effects
Documentation
```release-note
None
```

statistics: remove useless code in the MergePartTopN2GlobalTopN

---

WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

*: upgrade java_tools v12.6

---

ddl/db_integration_test.go
ddl/index_modify_test.go
privilege/privileges/privileges_test.go

Tests 
Side effects
Documentation
```release-note
None
```

tests: remove some TODO comments

---

server/server_test.go
server/tidb_test.go
table/tables/tables.go

cherry pick #43858
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix load data assertion failure (#43858) | tidb-test=pr/2145

---

ddl/BUILD.bazel
ddl/backfilling.go
ddl/ddl_test.go
ddl/export_test.go
ddl/mock.go
ddl/tests/serial/BUILD.bazel
ddl/tests/serial/main_test.go
ddl/tests/serial/serial_test.go

Tests 
Side effects
Documentation
```release-note
None
```

ddl: split series test into new package

---

statistics/column.go
statistics/handle/handletest/handle_test.go
statistics/histogram.go
statistics/index.go
statistics/table.go

Issue Number: close https://github.com/pingcap/tidb/issues/45367
Tests 
Side effects
Documentation
```release-note
None
```

statistics: refactor TableCacheItem

---

ddl/table.go

cherry-pick https://github.com/pingcap/tidb/pull/41950
Issue Number: close https://github.com/pingcap/tidb/issues/41951
Tests 
Side effects
Documentation
```release-note
None
```

ddl: fix create view when met err (#41950)

---

bindinfo/capture_test.go

Issue Number: close #40297
Tests 
Side effects
Documentation
```release-note
None
```

*: fix TestCaptureWildcardFilter

---

executor/partition_table_test.go

Issue Number: close #45870 
Reduce the data size and loop size.
Tests 
Side effects
Documentation
```release-note
None
```

executor: speed up TestOrderByAndLimit

---

statistics/column.go
statistics/handle/cache/internal/lfu/BUILD.bazel
statistics/handle/cache/internal/lfu/key_set.go
statistics/handle/cache/internal/lfu/key_set_shard.go
statistics/handle/cache/internal/lfu/lfu_cache.go
statistics/handle/cache/internal/lfu/lfu_cache_test.go
statistics/handle/dump.go
statistics/handle/update.go
statistics/handle/updatetest/update_test.go
statistics/histogram.go
statistics/index.go
statistics/integration_test.go
statistics/table.go

Issue Number: close https://github.com/pingcap/tidb/issues/45367
Tests 
Side effects
Documentation
```release-note
None
```

statscache: support multi-level evict

---

executor/index_lookup_join.go
executor/index_lookup_join_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/45716
Tests 
Issue 45716 test passed.
Side effects
Documentation
```release-note
None
```

executor: fix hang when index join newInnerworker panic

---

br/pkg/lightning/backend/external/BUILD.bazel
br/pkg/lightning/backend/external/byte_reader_test.go
br/pkg/lightning/backend/external/file.go
br/pkg/lightning/backend/external/file_test.go

Fix a bug that use `AppendUint64(b[:], ...)`
Tests 
Side effects
Documentation
```release-note
None
```

lightning/external: add UT and fix a bug

---

ddl/tests/adminpause/BUILD.bazel
ddl/tests/adminpause/ddl_data_generation.go
ddl/tests/adminpause/pause_cancel_test.go
ddl/tests/adminpause/pause_resume_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/45906
Tests 
Side effects
Documentation
```release-note
None
```

*: batch write for admin pause 

---

ddl/tests/adminpause/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

test: set timeout moderate for adminpause

---

br/pkg/gluetidb/glue_test.go
br/pkg/task/show/cmd_test.go
ddl/column_change_test.go
ddl/constraint_test.go
ddl/multi_schema_change_test.go
ddl/tests/fk/foreign_key_test.go
executor/simple_test.go
executor/test/autoidtest/autoid_test.go
executor/test/passwordtest/password_management_test.go
planner/core/integration_test.go
planner/core/plan_stats_test.go
planner/core/rule_join_reorder_test.go
ttl/ttlworker/job_manager_integration_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: replace CreateMockStoreAndDomain with CreateMockStore

---

Makefile

Tests 
Side effects
Documentation
```release-note
None
```

*: simple bazel prepare

---

Makefile

Issue Number: ref https://github.com/pingcap/tidb/issues/45987
- Added help text support for the makefile
- Added help text for `bazel_prepare` target
Tests 
Side effects
Documentation
```release-note
None
```

makefile: add help texts

---

Makefile

Issue Number: ref https://github.com/pingcap/tidb/issues/45987
Follow up https://github.com/pingcap/tidb/pull/45988
Set the default target correctly.
Tests 
Side effects
Documentation
```release-note
None
```

makefile: set default target

---

planner/core/planbuilder.go
planner/core/planbuilder_test.go
statistics/histogram.go

Issue Number: close https://github.com/pingcap/tidb/issues/46002
- Added unit tests for `handleAnalyzeOptions`
Tests 
Side effects
Documentation
```release-note
None
```

planner: add tests for `handleAnalyzeOptions`

---

WORKSPACE

Issue Number: close #46026
Tests 
Side effects
Documentation
```release-note
None
```

*: set go1.19.12

---

WORKSPACE

Issue Number: close #46026
Tests 
Side effects
Documentation
```release-note
None
```

*: set go1.20.7

---

planner/core/plan_cache.go
planner/core/plan_cache_utils.go
planner/core/point_get_plan.go
session/test/vars/BUILD.bazel
session/test/vars/vars_test.go
sessionctx/stmtctx/BUILD.bazel
sessionctx/stmtctx/stmtctx.go
sessionctx/stmtctx/stmtctx_test.go

Issue Number: close #45812
Tests 
Side effects
Documentation
```release-note
None
```

planner: store the hints of session variable

---

executor/test/analyzetest/analyze_test.go
planner/core/planbuilder.go
planner/core/planbuilder_test.go

- refactored `getFullAnalyzeColumnsInfo`
- Added tests for `handleAnalyzeOptionsV2`
Tests 
Side effects
Documentation
```release-note
None
```

planner: refactor `getFullAnalyzeColumnsInfo`

---

util/collate/BUILD.bazel
util/collate/collate.go
util/execdetails/BUILD.bazel
util/execdetails/execdetails.go
util/extsort/BUILD.bazel
util/extsort/disk_sorter.go
util/extsort/disk_sorter_test.go
util/extsort/external_sorter_test.go
util/memory/BUILD.bazel
util/memory/tracker.go
util/memoryusagealarm/BUILD.bazel
util/memoryusagealarm/memoryusagealarm.go
util/profile/BUILD.bazel
util/profile/flamegraph.go
util/ranger/BUILD.bazel
util/ranger/ranger.go
util/rowDecoder/BUILD.bazel
util/rowDecoder/decoder.go
util/schemacmp/BUILD.bazel
util/schemacmp/table.go
util/stmtsummary/BUILD.bazel
util/stmtsummary/statement_summary.go
util/stmtsummary/v2/BUILD.bazel
util/stmtsummary/v2/column.go
util/stmtsummary/v2/reader.go
util/stringutil/BUILD.bazel
util/stringutil/string_util.go

Tests 
Side effects
Documentation
```release-note
None
```

util: use std/slices to replace exp/slices

---

expression/builtin_miscellaneous_vec.go
server/conn.go
server/conn_test.go

Issue Number: close #45813
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix select sleep killed return expected error

---

ttl/client/command.go
ttl/ttlworker/job_manager_integration_test.go

Issue Number: close #46024
Tests 
Side effects
Documentation
```release-note
None
```

*: fix ttl unstable test `TestTTLDeleteWithTimeZoneChange`

---

types/BUILD.bazel
types/json_binary.go
types/json_binary_functions.go

Issue Number: close #45933
Tests 
Side effects
Documentation
```release-note
None
```

*: use std/slices to replace exp/slices

---

planner/core/explain.go

Issue Number: close #46151
Tests 
Side effects
Documentation
```release-note
None
```

planner: avoid create new stats cache

---

planner/optimize.go

Issue Number: close #46124 
Problem Summary: make test TestRuntimeHintsInEvolveTasks stable.
Tests 
Side effects
Documentation
```release-note
None
```

tests: make test TestRuntimeHintsInEvolveTasks stable

---

planner/core/plan_cache_param.go
planner/core/plan_cache_param_test.go
planner/optimize.go

Tests 
Side effects
Documentation
```release-note
None
```

*: remove useless param

---

executor/analyze.go
executor/infoschema_cluster_table_test.go
planner/core/common_plans.go
planner/core/planbuilder.go
planner/core/planbuilder_test.go
statistics/analyze.go
statistics/table.go

- Added tests for `getFullAnalyzeColumnsInfo`
- Added more comments
- Fixed some typos
- Moveded `filterSkipColumnTypes` out from `buildAnalyzeFullSamplingTask`
Tests 
Side effects
Documentation
```release-note
None
```

planner: add tests for `getFullAnalyzeColumnsInfo`

---

br/pkg/lightning/importer/import.go
br/pkg/restore/client.go
br/pkg/task/backup.go
br/pkg/utils/db.go
br/tests/br_check_new_collocation_enable/run.sh
br/tests/br_s3/run.sh

Issue Number: close #46136
Tests 
Side effects
Documentation
```release-note
None
```

br: update new_collation related logs

---

store/mockstore/mockcopr/aggregate.go
store/mockstore/mockcopr/executor.go

Issue Number: ref #35276
I find this code is unused ... do some cleanup.
Tests 
Side effects
Documentation
```release-note
None
```

store/mockstore/mockcopr: cleanup unused code

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #46198
The fix is included in https://github.com/tikv/client-go/pull/949 .
Tests 
Side effects
Documentation
```release-note
None
```

*: bump client-go to fix #46198

---

executor/BUILD.bazel
executor/analyze_utils.go
executor/analyze_utils_test.go

Issue Number: close #45690 
Without this commit:
```
sql> ANALYZE TABLE x WITH 1024 buckets, 1024 topn,1 SAMPLERATE;
ERROR: 1105 (HY000): Your query has been cancelled due to exceeding the allowed memory limit for the tidb-server instance and this query is currently using the most memory. Please try narrowing your query scope or increase the tidb_server_memory_limit and try again.[conn=2097154]%!(EXTRA *errors.fundamental=analyze panic due to memory quota exceeds, please try with smaller samplerate(refer to 110000/count))
```
(note the `%!(EXTRA *errors.fundamental` in there)
With this commit:
```
sql> ANALYZE TABLE x WITH 1024 buckets, 1024 topn,1 SAMPLERATE;
ERROR: 1105 (HY000): Your query has been cancelled due to exceeding the allowed memory limit for the tidb-server …
```

memory: Fix formatting of memory usage error for analyze table

---

domain/domain.go
domain/runaway.go

Issue Number: close #46200
Tests 
Side effects
Documentation
```release-note
None
```

domain: initResourceGroupsController after fetching ServerID

---

privilege/conn/conn.go
privilege/privileges/ldap/const.go
privilege/privileges/ldap/ldap_common.go
privilege/privileges/ldap/ldap_common_test.go
privilege/privileges/ldap/sasl.go
privilege/privileges/ldap/simple.go

Tests 
Side effects
Documentation
```release-note
None
```

*: modify headers of some source files in `privilege`

---

ddl/constraint.go
ddl/constraint_test.go
table/constraint.go

Issue Number: source code not modified, issue not needed
Modify the header to make it compliant
Tests 
Side effects
Documentation
```release-note
None
```

*: modify header of some source file

---

executor/main_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/46158
Tests 
Side effects
Documentation
```release-note
None
```

executor: enable LFU stats cache for test

---

statistics/cmsketch.go
statistics/cmsketch_bench_test.go
statistics/cmsketch_test.go
statistics/handle/handle.go

Tests 
Side effects
Documentation
```release-note
None
```

*: simple code

---

session/bootstrap.go
session/bootstraptest/bootstrap_upgrade_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/46228, close https://github.com/pingcap/tidb/issues/46227
* remove pause all jobs when upgrading
* update `TestUpgradeWithPauseDDL` and add a comment.
Tests 
Pass the issue's test.
Side effects
Documentation
```release-note
None
```

session: remove pause all jobs when upgrading

---

parser/misc.go
parser/parser_test.go

Issue Number: close #35031
Tests 
Side effects
Documentation
```release-note
None
```

parser: fix parser identifier with dot

---

server/testdata/optimizer_suite_out.json
statistics/column.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/update.go
statistics/histogram.go
statistics/index.go
statistics/interact_with_storage.go
statistics/testdata/trace_suite_out.json

Issue Number: ref https://github.com/pingcap/tidb/issues/46056
Remove the error rate struct, it was for the feedback feature which already has been deprecated.
Tests 
Side effects
Documentation
```release-note
None
```

* : remove error rate

---

DEPS.bzl
br/pkg/lightning/backend/local/local_test.go
go.mod
go.sum
util/extsort/disk_sorter.go

Issue Number: close #46344
The pebble dependency in tidb repo is older than the one in tiflow, which in turn is using tidb repository as a dependency. This makes it hard to update the tidb dependency in tiflow.
Fixed by updating the pebble dependency in tidb, to match the one in tiflow.
Tests 
Side effects
Documentation
```release-note
None
```

*: Updated pebble, to be same version as tiflow.

---

ddl/constraint.go

Issue Number: close #46022
Tests 
Side effects
Documentation
```release-note
None
```

ddl: small fix of `verifyRemainRecordsForCheckConstraint` func

---

statistics/BUILD.bazel
statistics/cmsketch.go
statistics/cmsketch_util.go
statistics/histogram.go
statistics/merge_worker.go

Issue Number: ref #46158
Tests 
Side effects
Documentation
```release-note
None
```

statistics: use DatumMapCache to remove duplicate code

---

executor/test/tiflashtest/tiflash_test.go

The original TestMPPExecution contains ineffective failpoint enable that points to an incorrect location.
Tests 
Side effects
Documentation
```release-note
None
```

*: fix ineffective failpoint enable in TestMPPExecution

---

DEPS.bzl
autoid_service/BUILD.bazel
autoid_service/autoid.go
autoid_service/autoid_test.go
bazel-tidb-master-yjy-autoid-check-ks
go.mod
go.sum
meta/autoid/autoid.go
meta/autoid/autoid_service.go

Issue Number: ref https://github.com/pingcap/tidb/issues/46421
For example:
If at TS1:
the TiDB-01 instance of keyspace A is auto id service leader of keyspace A.
TiDB-02 is auto id client of keyspace A .
But at TS2:
TiDB-01 restart and set to keyspace B, become auto id service leader of keyspace B.
TiDB-01 need reject auto id request from other keyspace.
Add keyspace check when auto id service handle the AutoIDRequest.
Tests 
At TS1:
Start TiDB-01 instance of keyspace-name=ks1, is auto id service leader of keyspace-name=ks1.
Start TiDB-02 is auto id client of keyspace-name=ks1 .
execute SQL at TiDB-02:
```
use test;
create table t(id int primary key auto_increment) auto_id_cache=1;
insert into t() values();
```
Log of TiDB-02:
```
["connect to leader"] [keyspaceName=ks1] …
```

autoid_service: check request keyspace

---

statistics/column.go
statistics/handle/cache/internal/lfu/lfu_cache.go
statistics/handle/cache/internal/lfu/lfu_cache_test.go
statistics/histogram.go
statistics/index.go
statistics/table.go

Issue Number: ref #46158
Tests 
Side effects
Documentation
```release-note
None
```

statistics: implement copy for index and column

---

util/misc_test.go

Issue Number: close #46420
Tests 
Side effects
Documentation
```release-note
None
```

test: fix test TestChannelMap

---

ddl/ddl_api.go
ddl/tests/partition/db_partition_test.go

Issue Number: close #46165
Tests 
Side effects
Documentation
```release-note
None
```

partition: fix ExchangePartition bug when partition table with global index

---

executor/test/tiflashtest/tiflash_test.go

Issue Number: close #46484 
Tests 
Side effects
Documentation
```release-note
None
```

executor: Remove mpp task number check to pass tests in ci

---

server/handler/upgrade_handler.go
session/BUILD.bazel
session/bootstrap.go
session/sync_upgrade.go

Issue Number: close https://github.com/pingcap/tidb/issues/46493
* Move the upgrade code from bootstrap.go to sync_upgrade.go
* Add a timeout argument to `SyncUpgradeState`
Tests 
Side effects
Documentation
```release-note
None
```

session, server: do a simple refactoring of the code for the upgrade

---

autoid_service/autoid.go

Issue Number: ref #46444
Add some debug log for rebase operation, so it's easier for us to know what happen when we see 'duplicate entry' error 
Tests 
No logic change, just log.
Side effects
Documentation
```release-note
None
```

autoid_service: add some debug log for rebase related operation

---

README.md

Add a new community channel - Discord
Tests 
Side effects
Documentation
```release-note
None
```

README: Add Discord channel

---

executor/test/issuetest/executor_issue_test.go

Tests 
Side effects
Documentation
```release-note
None
```

executor: merge test into UnionTest

---

statistics/handle/cache/internal/lfu/lfu_cache.go

Issue Number: close #46554
Tests 
Side effects
Documentation
```release-note
None
```

statistics: improve default NumCounters in the LFU stats cache

---

planner/core/tests/prepare/issue/BUILD.bazel
planner/core/tests/prepare/issue/issue_test.go

Tests 
Side effects
Documentation
```release-note
None
```

planner: merge test for prepare cache

---

metrics/BUILD.bazel
metrics/metrics_internal_test.go
metrics/stats.go
statistics/handle/cache/internal/metrics/metrics.go

Issue Number: close #46577
Tests 
Side effects
Documentation
```release-note
None
```

statistics: fix the metrics for stats cache

---

ddl/tests/adminpause/pause_resume_test.go

Tests 
Side effects
Documentation
```release-note
None
```

adminpause: improve test proformance

---

disttask/framework/dispatcher/BUILD.bazel

Issue Number: close #46573 
Tests 
Side effects
Documentation
```release-note
None
```

*: disable race for framework tests

---

metrics/stats.go
statistics/handle/cache/internal/metrics/metrics.go

Issue Number: close #46577
Tests 
Side effects
Documentation
```release-note
None
```

statistics: fix the cost metrics for stats cache

---

br/pkg/lightning/backend/external/engine.go
br/pkg/lightning/backend/local/duplicate.go
br/pkg/lightning/backend/local/engine.go
br/pkg/lightning/backend/local/local.go
br/pkg/lightning/backend/local/local_test.go
br/pkg/lightning/backend/local/localhelper.go
br/pkg/lightning/backend/local/localhelper_test.go
br/pkg/lightning/backend/local/region_job.go
br/pkg/lightning/backend/local/region_job_test.go
br/pkg/lightning/common/engine.go

- Add method `KVStatistics()`, `ImportedStatistics()` and `SplitRanges()` for `common.Engine`.
- Tiny code refactoring.
Tests 
Side effects
Documentation
```release-note
None
```

lightning: extract split range for local/external engine

---

ddl/tests/adminpause/pause_cancel_test.go
ddl/tests/adminpause/pause_resume_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: faster adminpause test

---

ddl/tests/adminpause/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

adminpause: set moderate timeout

---

executor/show_stats_test.go
types/datum.go
types/datum_test.go

Issue Number: close #46579
Problem Summary: planner: optimize the performance of `PlanCacheParamList.String()`
planner: optimize the performance of `PlanCacheParamList.String()`
```
Before
BenchmarkDatumsToString-8                 676939              1605 ns/op             952 B/op         37 allocs/op
BenchmarkDatumsToStringStr-8              315628              3564 ns/op            1184 B/op          4 allocs/op
BenchmarkDatumsToStringLongStr-8           17454             68606 ns/op           21794 B/op          4 allocs/op
After
BenchmarkDatumsToString-8                1000000              1044 ns/op             792 B/op         34 allocs/op
BenchmarkDatumsToStringStr-8            10546382               113.5 ns/op           584 B/op          2 allocs/op …
```

planner: optimize the performance of `PlanCacheParamList.String()`

---

statistics/handle/cache/internal/lfu/BUILD.bazel
statistics/handle/cache/internal/lfu/lfu_cache.go
statistics/handle/cache/internal/lfu/lfu_cache_test.go

Issue Number: close #46585
Tests 
Side effects
Documentation
```release-note
None
```

statistics: improve the memory usage for stats cache

---

domain/BUILD.bazel
domain/domain.go
infoschema/metrics/metrics.go
metrics/domain.go
metrics/grafana/tidb.json

Issue Number: ref #46524
Problem Summary: refine metrics of infoschema
- Remove duplicate metrics panel `Load Schema Duration`
- `Load Schema OPS` add information about load snapshot schema, it's important to diagnose problem for stale read request.
- Add `Schema Cache OPS` metric panel.
This PR: 
Tests 
Side effects
Documentation
```release-note
None
```

metrics: refine metrics of infoschema

---

distsql/distsql.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/sysvar_test.go
sessionctx/variable/tidb_vars.go

Issue Number: close #46536
Add two variables to control TiFlash query level memory quota and auto spill
Tests 
Side effects
Documentation
```release-note
None
```

session: add tiflash auto spill support

---

planner/core/planbuilder.go
statistics/BUILD.bazel
statistics/integration_test.go

This PR is to solve generating global index analyze task correctly.
Issue Number: close #46366
Tests 
Side effects
Documentation
```release-note
None
```

statistics: fix global index statistics

---

WORKSPACE

Issue Number: close #46668
Tests 
Side effects
Documentation
```release-note
None
```

bazel: add mirror for rules_java

---

infoschema/BUILD.bazel
infoschema/perfschema/const.go
infoschema/perfschema/tables.go
infoschema/tables.go
server/BUILD.bazel
server/server.go
server/server_test.go
testkit/BUILD.bazel
testkit/mocksessionmanager.go
util/BUILD.bazel
util/processinfo.go

Issue Number: ref #44341
Similar to https://github.com/pingcap/tidb/pull/44340
Tests 
Side effects
Documentation
```release-note
Add `performance_schema.session_account_connect_attrs` table
```

server,infoschema,util: Implement session_account_connect_attrs P_S table

---

statistics/handle/cache/statscacheinner.go

Issue Number: close https://github.com/pingcap/tidb/issues/46577
Tests 
Side effects
Documentation
```release-note
None
```

statistics: add update metrics for stats cache

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #46664
update https://github.com/tikv/client-go/pull/921
Tests 
```release-note
safeTS obtain min-resolved-ts by store list 
```

client-go: safeTS obtain min-resolved-ts by store list

---

ddl/backfilling_operator.go
ddl/export_test.go
ddl/index.go
ddl/index_cop.go
ddl/stage_read_index.go
tests/realtikvtest/addindextest/BUILD.bazel
tests/realtikvtest/addindextest/operator_test.go

Issue Number: ref #46258, close #46508
This PR adds failpoint tests for add-index operator.
Tests 
Side effects
Documentation
```release-note
None
```

ddl: add failpoint tests for add-index operator

---

WORKSPACE

Tests 
Side effects
Documentation
```release-note
None
```

*: use self mirror for rules_proto

---

executor/analyze.go
executor/show_stats.go
statistics/handle/lock_stats_handler.go
statistics/handle/lockstats/lock_stats.go
statistics/handle/lockstats/query_lock.go
statistics/handle/lockstats/query_lock_test.go
statistics/handle/lockstats/unlock_stats.go
statistics/handle/update.go

Issue Number: ref https://github.com/pingcap/tidb/issues/46351
Only return locked tables to reduce memory usage.
Tests 
Side effects
Documentation
```release-note
None
```

statistics: improve query locked table API memory usage

---

DEPS.bzl
go.mod
go.sum

Issue Number: ref #46664
cherry-pick #46661
Tests 
```release-note
None
```

client-go: safeTS obtain min-resolved-ts by store list(hotfix)

---

metrics/grafana/tidb.json

Issue Number: close #46719
Add active connections to Connection pannel.
Tests 
1. start a cluster with TiUP
2. copy tidb.json to {deploy_dir}/grafana-3000/bin
3. reload Grafana
4. run some benchmarks
5. check the metrics on Grafana
Side effects
Documentation
```release-note
None
```

metrics: add active connections to Connection panel

---

statistics/handle/cache/internal/lfu/lfu_cache.go
statistics/handle/cache/internal/lfu/lfu_cache_test.go

Issue Number: close #46585
Tests 
Side effects
Documentation
```release-note
None
```

statstics: fix update the value of LFU's MaxCost

---

errors.toml
expression/builtin_encryption.go
expression/builtin_miscellaneous.go
expression/builtin_test.go
expression/distsql_builtin.go
expression/errors.go
expression/integration_test/integration_test.go
expression/scalar_function.go
planner/core/preprocess.go
util/dbterror/ddl_terror.go

Issue Number: close #46744
Tests 
Side effects
Documentation
```release-note
None
```

expression, planner: check function exists with schema name

---

session/session.go

Issue Number: close #46637
Tests 
1. start a cluster and change the log level of TiDB to debug
2. run multi-statement test
3. check the logs, e.g.
```
[2023/09/04 19:52:34.165 +08:00] [DEBUG] [session.go:1681] [parse] [conn=2097154] [session_alias=] [sql="select 1; select 1;"]
```
Side effects
Documentation
```release-note
None
```

session: add debug log for parsing

---

executor/prepared_test.go
util/hint/hint_processor.go

Issue Number: close #46817
Fix it.
Tests 
Side effects
Documentation
```release-note
None
```

hint: fix panic when query block not found in prepare statement

---

planner/core/casetest/enforcempp/enforce_mpp_test.go

Issue Number: close #46415
Tests 
Side effects
Documentation
```release-note
None
```

enforcempp: fix flaky test TestEnforceMPP

---

executor/batch_point_get_test.go
executor/builder.go

Issue Number: close #46779 
Tests 
Side effects
Documentation
```release-note
None
```

executor: fix batchPoint for partition table with duplicate rows

---

build/BUILD.bazel

Tests 
Side effects
Documentation
```release-note
None
```

linter: revert the delete configure

---

executor/index_lookup_join_test.go
executor/test/analyzetest/analyze_test.go

Tests 
Side effects
Documentation
```release-note
None
```

executor: merge some tests into one

---

disttask/framework/dispatcher/dispatcher_test.go

Issue Number: close #46884 
When check subtask cnt, maybe subtasks are not dispatched. So we need to wait the subtask dispatched.
Tests 
Side effects
Documentation
```release-note
None
```

disttask: fix dispatcher checksubtask flaky test

---

ddl/multi_schema_change_test.go

Issue Number: close #43231
It is possible that the last DDL job does not exit in time.
Only check multi-schema-change jobs in `OnJobUpdated()`.
Tests 
Side effects
Documentation
```release-note
None
```

test: stabilize TestMultiSchemaChangeAlterIndex

---

statistics/analyze_jobs.go

used RWMutex in AnalyzeProgress.
Tests 
Side effects
Documentation
```release-note
None
```

statistics: use RWMutex in AnalyzeProgress

---

executor/test/analyzetest/BUILD.bazel
executor/test/analyzetest/analyze_bench_test.go

Issue Number: close #46914
Tests 
Side effects
Documentation
```release-note
None
```

*: add bench for analyze

---

executor/test/indexmergereadtest/index_merge_reader_test.go

Issue Number: close #46841
Tests 
Side effects
Documentation
```release-note
None
```

executor: speed up `TestOrderByWithLimit`

---

executor/analyze.go
planner/core/BUILD.bazel
planner/core/logical_plan_builder.go
statistics/handle/bootstrap.go
statistics/handle/cache/bench_test.go
statistics/handle/cache/internal/inner.go
statistics/handle/cache/internal/lfu/lfu_cache.go
statistics/handle/cache/internal/lfu/lfu_cache_test.go
statistics/handle/cache/internal/mapcache/map_cache.go
statistics/handle/cache/statscache.go
statistics/handle/cache/statscacheinner.go
statistics/handle/handle.go
statistics/handle/handle_hist.go
statistics/handle/handletest/BUILD.bazel
statistics/handle/handletest/handle_test.go
statistics/handle/historical_stats_handler.go
statistics/handle/updatetest/BUILD.bazel
statistics/handle/updatetest/update_test.go

Tests 
Side effects
Documentation
```release-note
None
```

*: unite stats cache's GET

---

statistics/cmsketch.go

Issue Number: close #46967
Tests 
Side effects
Documentation
```release-note
None
```

statistics: prealloc right size for NewTopN

---

util/gctuner/tuner_test.go

Issue Number: close #46828
Tests 
Side effects
Documentation
```release-note
None
```

gctuner: wait to condition to fix flaky test

---

distsql/request_builder.go
executor/analyze_col_v2.go
executor/builder.go

- Added some comments
- Fixed some typos
Tests 
Side effects
Documentation
```release-note
None
```

executor: add some comments and fix typos

---

parser/model/model.go

Tests 
Run `TestOrderByWithLimit`, no warn log like `unable to get collation name from collation ID, return default charset and collation instead` any more.
Side effects
Documentation
```release-note
None
```

model: set collation and charset for `ExtraPhysTblIDCol` and `ExtraPartitionIDCol`

---

statistics/sample.go

Tests 
Side effects
Documentation
```release-note
None
```

statistics: use slices.SortStableFunc to simple SortSampleItems

---

statistics/fmsketch.go

Issue Number: close https://github.com/pingcap/tidb/issues/47016
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: use MurmurPool to reuse the memory

---

Makefile
util/hack/hack.go

Issue Number: ref #47066
Tests 
>   
Side effects
Documentation
```release-note
None
```

hack: remove deprecate SliceHeader

---

planner/core/integration_test.go
planner/core/rule_inject_extra_projection.go

Issue Number: close #46580
Problem Summary: planner: fix Uncertain Results caused by MERGE_JOIN
Similar to https://github.com/pingcap/tidb/pull/8073, see it for more explanation.
Tests 
>   
Side effects
Documentation
```release-note
None
```

planner: fix Uncertain Results caused by MERGE_JOIN

---

OWNERS_ALIASES
distsql/OWNERS
executor/OWNERS
expression/OWNERS

Issue Number: ref #47088, #47089, #47090
- add aliases in `/OWNERS_ALIASES` file.
- add `OWNERS` files in `distsql`, `executor` and `expression` folders.
Tests 
>   
Side effects
Documentation
```release-note
None
```

distsql,executor,expression: add code `OWNERS` files

---

DEPS.bzl
br/pkg/lightning/backend/local/BUILD.bazel
br/pkg/lightning/backend/local/compress.go
go.mod
go.sum
statistics/handle/BUILD.bazel
statistics/handle/dump.go
util/compress/BUILD.bazel
util/compress/gzip.go

Issue Number: close #47104
Tests 
in the same cluster:
before:
after:
>   
Side effects
Documentation
```release-note
None
```

statistics: faster gzip

---

statistics/handle/globalstats/global_stats.go
statistics/handle/handle.go

Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: simple globalstats

---

executor/test/executor/executor_test.go
tests/integrationtest/r/executor/executor.result
tests/integrationtest/t/executor/executor.test

Issue Number: ref #47076
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor, tests: move some test cases from `executor_test.go` to `integrationtest`

---

SECURITY.md

Problem Summary: Modify the email address for the security group in SECURITY.md.
Tests 
>   
Side effects
Documentation
```release-note
None
```

README: Change Security Group Email

---

docs/design/2022-10-13-mysql-compatible-auto-increment.md

Issue Number: ref #38442
Add the design document for https://github.com/pingcap/tidb/issues/38442
Tests 
Side effects
Documentation
```release-note
None
```

docs/design: add MySQL compatible auto_increment design doc

---

sessionctx/variable/sysvar.go
sessionctx/variable/sysvar_test.go
sessionctx/variable/tidb_vars.go
util/gctuner/tuner.go

Issue Number: close #47166
Tests 
>   
Side effects
Documentation
```release-note
None
```

variable: control max/min gogc for gogctuner

---

ddl/column.go
ddl/ddl_api.go
expression/expression.go
parser/model/model.go
planner/core/find_best_task.go
planner/core/planbuilder.go
server/err/BUILD.bazel
statistics/handle/globalstats/global_stats.go
table/tables/tables.go
testkit/testsetup/BUILD.bazel

just clean code.
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: make IsVirtualGeneratedColumn more readable

---

DEPS.bzl
go.mod
go.sum

Issue Number: ref https://github.com/pingcap/tidb/issues/46664, cherry-pick https://github.com/pingcap/tidb/pull/46661.
Tests 
```release-note
None
```

client-go: safeTS obtain min-resolved-ts by store list (hotfix)

---

disttask/framework/storage/task_table.go

Issue Number: ref #46258 close #47178
Insert subtasks in one sql.
Tests 
```
newSubtasks := []*proto.Subtask{}
for i := 0; i < 10000; i++ {
newSubtasks = append(newSubtasks, &proto.Subtask{
Step:        proto.StepInit,
Type:        proto.TaskTypeExample,
SchedulerID: "instance1",
Meta:        []byte(""),  // with big enough bytes
})
}
retryable, err := sm.UpdateGlobalTaskAndAddSubTasks(task, newSubtasks, prevState)
require.NoError(t, err)
require.Equal(t, true, retryable)
cnt, err := sm.GetSubtaskInStatesCnt(task.ID, proto.TaskStatePending)
require.Equal(t, int64(10000), cnt)
``` 
pass this test
>   
Side effects
Documentation …

disttask: batch insert subtasks

---

br/pkg/lightning/backend/local/local.go
disttask/importinto/encode_and_sort_operator.go
tests/realtikvtest/importintotest4/global_sort_test.go

Issue Number: close #47226
use  ImportedStatistics, instead of KVStatistics
Tests 
>   
Side effects
Documentation
```release-note
None
```

importinto: fix import-rows always 0

---

statistics/handle/globalstats/global_stats.go

Issue Number: ref #47219
Fm sketch is so big that we can release it early as soon as possible. any other can reuse this struct again.
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: first calculate NDV to better reuse memory

---

DEPS.bzl
go.mod
go.sum
infoschema/metric_table_def.go
metrics/grafana/tidb_resource_control.json

Issue Number: close https://github.com/pingcap/tidb/issues/47231
Tests 
```release-note
None
```

*: upgrade client-go and update metircs about resource control

---

statistics/handle/BUILD.bazel
statistics/handle/handle.go
statistics/handle/update.go
statistics/handle/update_list_test.go
statistics/handle/usage/BUILD.bazel
statistics/handle/usage/stats_usage.go
statistics/handle/usage/table_delta.go

Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: move StatsUsage and TableDelta into new package

---

executor/OWNERS

Issue Number: ref #47089
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: revert OWNERS file

---

executor/analyze.go

Issue Number: close #47339
Tests 
>   
Side effects
Documentation
```release-note
None
```

executer: collect and write analyze at the same time

---

tests/integrationtest/t/planner/core/integration.test

Issue Number: close #47411
The test result is unstable. This PR adds the annotation `--sorted_result` to the line.
Tests 
>

tests: add sorted result for a test

---

statistics/handle/extstats/extended_stats.go
statistics/handle/gc.go
statistics/handle/handle.go
statistics/handle/history/BUILD.bazel
statistics/handle/history/history_stats.go
statistics/handle/storage/gc.go
statistics/handle/storage/save.go

Problem Summary: planner: move code about `recordHistoricalStatsMeta`
planner: move code about `recordHistoricalStatsMeta`
Tests 
>   
Side effects
Documentation
```release-note
None
```

planner: move code about `recordHistoricalStatsMeta`

---

executor/test/analyzetest/analyze_test.go
statistics/handle/globalstats/global_stats.go
statistics/handle/handletest/analyze/analyze_test.go

Issue Number: close #47384
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: correctly handle the ErrPartitionStatsMissing

---

tests/realtikvtest/importintotest/detach_test.go
tests/realtikvtest/importintotest/import_into_test.go
tests/realtikvtest/importintotest/job_test.go
tests/realtikvtest/importintotest/one_parquet_test.go
tests/realtikvtest/importintotest/util_test.go
tests/realtikvtest/importintotest4/global_sort_test.go

Issue Number: close #47416
ci might be slow sometimes, 10 second might not be enough, so set max wait to 30
Tests 
>   
Side effects
Documentation
```release-note
None
```

importinto: fix flaky test

---

expression/builtin_time.go

Issue Number: close #47308 
Change the log level to debug to reduce log numbers.
Tests 
Side effects
Documentation
```release-note
None
```

util: change log level to debug calculating stale read ts

---

OWNERS_ALIASES

From `benjamin2037` to `Benjamin2037`
Issue Number: ref #47088
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: fix member spell in OWNERS_ALIASES

---

statistics/handle/gc.go
statistics/handle/handle.go
statistics/handle/storage/BUILD.bazel
statistics/handle/storage/gc.go
statistics/handle/storage/read.go
statistics/handle/storage/update.go
statistics/handle/update.go
statistics/handle/usage/BUILD.bazel
statistics/handle/usage/predicate_column.go
statistics/handle/util/util.go

Problem Summary: planner: move code about `stats gc` and `stats predicate col`
No logical change, just refactor
Tests 
>   
Side effects
Documentation
```release-note
None
```

planner: move code about `stats gc` and `stats predicate col`

---

br/pkg/storage/helper.go
br/pkg/stream/rewrite_meta_rawkv.go
ddl/ddl_worker.go
ddl/delete_range.go
ddl/index.go
ddl/ingest/integration_test.go
ddl/multi_schema_change.go
ddl/sanity_check.go
disttask/framework/storage/task_table.go
parser/model/ddl.go
tests/realtikvtest/addindextest/BUILD.bazel
tests/realtikvtest/addindextest/global_sort_test.go

Issue Number: ref #41602
#47135 have little functional tests.
- Add more functional tests for multi-schema change.
- Fix a small bug that `task_key` is the same among different sub-jobs.
Tests 
>   
Side effects
Documentation
```release-note
None
```

ddl: add more tests for multi-schema change

---

statistics/handle/handle.go
statistics/handle/storage/read.go

Issue Number: ref https://github.com/pingcap/tidb/issues/46905
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: use StatsMetaCountAndModifyCount to remove duplicate code

---

timer/README.md

Issue Number: close #46857
The readme for timer framework
Tests 
Side effects
Documentation
```release-note
None
```

timer: README file for timer framework

---

metrics/grafana/tidb.json

Issue Number: close #47389
Fix it.
Tests 
* start a cluster
* running a benchmark
* check the metrics, should be like
>   
Side effects
Documentation
```release-note
None
```

metrics: do not stack connections

---

session/session.go
statistics/handle/autoanalyze/BUILD.bazel
statistics/handle/autoanalyze/autoanalyze.go
statistics/handle/ddl.go
statistics/handle/handle.go
statistics/handle/history/BUILD.bazel
statistics/handle/history/history_stats.go
statistics/handle/update.go
statistics/handle/usage/index_usage.go
statistics/handle/usage/predicate_column.go
statistics/handle/util/BUILD.bazel
statistics/handle/util/interfaces.go

Problem Summary: planner: move more methods from `statsHandler` to its subpackages
planner: move more methods from `statsHandler` to its subpackages
**No logical change, just refactor and code movement.**
Tests 
>   
Side effects
Documentation
```release-note
None
```

planner: move more methods from `statsHandler` to its subpackages

---

types/context/BUILD.bazel
types/context/context.go
util/intest/BUILD.bazel
util/intest/assert.go
util/intest/assert_test.go
util/intest/common.go

Issue Number: close #47551
See description in issue
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: Add `Assert` to do assertions in test

---

DEPS.bzl
go.mod
go.sum
store/copr/coprocessor.go

Issue Number: ref #47559 
Simple refactor and update the client-go dependency.
Tests 
Side effects
Documentation
```release-note
None
```

store: update client go

---

testkit/testenv/testenv.go

Tests 
>   
Side effects
Documentation
```release-note
None
```

*: set MAX GOMAXPROCS in test as 16

---

WORKSPACE

Issue Number: ref #47441
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: upgrade go1.21.3

---

OWNERS_ALIASES

[SKIP-CI]
Issue Number: ref #47301
Tests 
>   
Side effects
Documentation
```release-note
None
```

ci: fix error ids in OWNERS_ALIASES file

---

executor/analyze_col_v2.go

Issue Number: close #47613
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: fix data race at the getIntFromSessionVars

---

DEPS.bzl
go.mod
go.sum
pkg/parser/go.mod
pkg/parser/go.sum

Tests 
>   
Side effects
Documentation
```release-note
None
```

*: upgrade klauspost/compress

---

DEPS.bzl
go.mod
go.sum

Tests 
>   
Side effects
Documentation
```release-note
None
```

client-go: add retry limit for excluded backoff type to avoid infinite retry

---

Makefile

Issue Number: close #47663
Update the makefile script.
Tests 
```
make bench-daily TO=/tmp/2023-10-16.json
```
>   
Side effects
Documentation
```release-note
None
```

Makefile: fix 'make bench-daily' after reorganize of the package directory

---

pkg/ddl/ddl_worker.go
pkg/ddl/index.go
pkg/ddl/multi_schema_change.go
pkg/executor/executor.go
pkg/parser/model/ddl.go
pkg/parser/model/reorg.go

The result of `ADMIN SHOW DDL JOBS` does not indicate whether global sort is used.
Add `/* cloud */` to `JOB_TYPE` field if global sort is used.
Tests 
Multi-schema change job:
```
|    113 | test    | t          | alter table multi-schema change           | none         |         2 |      105 |         0 | 2023-10-17 13:22:31 | 2023-10-17 13:22:31 | 2023-10-17 13:22:37 | synced |
|    113 | test    | t          | add index /* subjob */ /* ingest cloud */ | public       |         2 |      105 |         1 | 2023-10-17 13:22:31 | 2023-10-17 13:22:31 | 2023-10-17 13:22:37 | done   |
```
Plain job:
```
|    109 | test    | t          | add index /* ingest cloud */              | public       |         2 |      105 |         1 | 2023-10-17 13:10:15 | …
```

ddl: refine job_type of admin show ddl jobs

---

DEPS.bzl
go.mod
go.sum

Issue Number: close #47753 
related pr: https://github.com/tikv/client-go/pull/1026
Problem Summary: fix issue of tikv rpc request source tag unset
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: fix issue of tikv rpc request source tag unset

---

pkg/executor/update_test.go
pkg/sessionctx/stmtctx/stmtctx.go
pkg/types/datum.go

Issue Number: close #47816
Tests 
>   
Side effects
Documentation
```release-note
fix update unsigned column with overflow string issue
```

types: fix update unsigned column with overflow string issue

---

OWNERS_ALIASES
pkg/domain/OWNERS

Issue Number: close #47798
Tests 
>   
Side effects
Documentation
```release-note
None
```

pkg/domain: add `OWNERS` file

---

pkg/executor/builder.go
pkg/executor/executor_pkg_test.go

Issue Number: close #47788
Tests 
>   
Side effects
Documentation
```release-note
fix an issue that index_lookup_hash_join incorrectly estimate memory usage.
```

executor: fix an issue that index_lookup_hash_join incorrectly estimate memory usage.

---

pkg/statistics/BUILD.bazel
pkg/statistics/cmsketch.go
pkg/statistics/histogram.go
pkg/statistics/histogram_test.go

Issue Number: close #47887
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: fix difference between BinarySearchRemoveVal and RemoveVals

---

OWNERS_ALIASES
pkg/disttask/OWNERS

Issue Number: close #47845
Tests 
>   
Side effects
Documentation
```release-note
None
```

pkg/disttask: add `OWNERS` file

---

errors.toml
pkg/errno/errname.go
pkg/types/errors.go

Issue Number: close #47943
Tests 
>   
Side effects
Documentation
```release-note
None
```

errno: fix typo for overflow message

---

pkg/session/bootstrap.go
pkg/session/bootstrap_test.go
pkg/session/bootstraptest/bootstrap_upgrade_test.go

Issue Number: close #48029
Tests 
>   
Side effects
Documentation
```release-note
None
```

bootstrap: modify `variable_value` column to `varchar(16383)`

---

Makefile
tests/realtikvtest/addindextest1/BUILD.bazel
tests/realtikvtest/addindextest1/dummy_test.go
tests/realtikvtest/addindextest1/main_test.go
tests/realtikvtest/addindextest2/BUILD.bazel
tests/realtikvtest/addindextest2/dummy_test.go
tests/realtikvtest/addindextest2/main_test.go
tests/realtikvtest/addindextest3/BUILD.bazel
tests/realtikvtest/addindextest3/dummy_test.go
tests/realtikvtest/addindextest3/main_test.go
tests/realtikvtest/addindextest4/BUILD.bazel
tests/realtikvtest/addindextest4/dummy_test.go
tests/realtikvtest/addindextest4/main_test.go

Issue Number: close #48094
currently, test in real-tikv-test is run in serial, if there're too many test in one directory, test will run slow and delay pr merge, or even timeout
so we add 4 addindextestX into real tikv test, we will split the test later, to avoid test timeout as we will add more test later.
Tests 
>   
Side effects
Documentation
```release-note
None
```

ddl: split add index real tikv tests

---

br/pkg/restore/ingestrec/BUILD.bazel
br/pkg/restore/ingestrec/ingest_recorder_test.go
go.mod
pkg/disttask/framework/scheduler/BUILD.bazel
pkg/disttask/framework/scheduler/scheduler_test.go
pkg/expression/BUILD.bazel
pkg/expression/builtin_compare.go
pkg/ttl/sqlbuilder/BUILD.bazel
pkg/ttl/sqlbuilder/sql.go

Tests 
>   
Side effects
Documentation
```release-note
None
```

*: remove pkg/errors

---

pkg/statistics/histogram.go

Add better comments for the out-of-range algorithm
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: add better comments for the out of range algorithm

---

pkg/statistics/handle/storage/stats_read_writer.go
pkg/statistics/handle/util/interfaces.go

Updated the wrong comments.
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: fix the wrong comments

---

pkg/sessionctx/variable/tidb_vars.go

Issue Number: ref #43333
fix typo
Tests 
> - [x] fix typo in comment.
>   
Side effects
Documentation
```release-note
None
```

planner, sessionctx: fix typo

---

br/OWNERS

Issue Number: ref #45183
Tests 
>   
Side effects
Documentation
```release-note
None
```

br: fix filter spells in `OWNERS` file

---

pkg/domain/domain.go

Issue Number: close #48124 
Back pick the https://github.com/pingcap/tidb/pull/48017 to the master branch.
Tests 
Side effects
Documentation
```release-note
None
```

domain: use the KV timeout read feature to mitigate the slow meta region issue

---

pkg/executor/BUILD.bazel
pkg/executor/analyze.go
pkg/executor/analyze_col.go
pkg/executor/analyze_col_v2.go
pkg/executor/analyze_utils.go
pkg/executor/builder.go
pkg/util/BUILD.bazel
pkg/util/topsql/BUILD.bazel
pkg/util/topsql/reporter/BUILD.bazel
pkg/util/topsql/stmtstats/BUILD.bazel
pkg/util/wait_group_wrapper.go
tools/tazel/util.go

reuse goroutine when to analyze. there are goroutines to do analyze and merge global stats.
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: reuse goroutine in the analyze 

---

br/pkg/lightning/common/util_test.go

Issue Number: close #48272
Tests 
>   
Side effects
Documentation
```release-note
None
```

test: fix leak DNS goroutine in test

---

pkg/executor/compiler.go
pkg/planner/core/plan_cache.go
pkg/planner/optimize.go
pkg/sessiontxn/interface.go

- Added some comments for the compiling process.
- Renamed 'OptimizeWithPlanAndThenWarmUp' to 'AdviseOptimizeWithPlanAndThenWarmUp'. I think it will help to differentiate between planner optimizing and txn optimizing.
- Rename `IsPointPlanShortPathOK` to `IsPointGetPlanShortPathOK`. I think it is more clear.
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: better comments

---

pkg/executor/analyze.go
pkg/executor/test/analyzetest/BUILD.bazel
pkg/executor/test/analyzetest/analyze_test.go

Issue Number: close #48327
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: add recover handler for handleResultsError

---

pkg/server/internal/packetio.go
pkg/server/metrics/metrics.go

Issue Number: close #48200
Rename to In/Out.
Tests 
2. patch this PR
3. check TiDB -> Server -> Client Data Traffic
>   
Side effects
Documentation
```release-note
None
```

metrics: rename label name of packet IO

---

pkg/util/cgroup/cgroup_cpu_linux.go

Issue Number: close #48342
Tests 
below value is calculated using result of MemTotal
before
[2023/11/07 13:23:21.976 +08:00] [INFO] [merge.go:39] ["start to merge overlapping files"] [file-count=1000] [file-groups=17] [concurrency=16] [memory-limit=**14.79GiB**]
after
[2023/11/07 14:06:00.211 +08:00] [INFO] [merge.go:39] ["start to merge overlapping files"] [file-count=1000] [file-groups=17] [concurrency=16] [memory-limit=**963.8MiB**]
>   
Side effects
Documentation
```release-note
None
```

util/cgroup: fix InContainer for cgroup v2

---

pkg/executor/executor.go
pkg/executor/test/analyzetest/memorycontrol/BUILD.bazel
pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go

Issue Number: close #48357
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: fix panic when to enable tidb_mem_quota_analyze 

---

WORKSPACE

Issue Number: ref #48383
Tests 
>   
Side effects
Documentation
```release-note
None
```

*: upgrade 1.20.11

---

pkg/executor/cte_test.go
pkg/executor/executor_pkg_test.go
pkg/executor/sortexec/sort_test.go

Issue Number: close #48401
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: fix `TestSortSpillDisk` in ut

---

pkg/expression/expr_to_pb_test.go
pkg/expression/expression.go

Issue Number: close #48350
Tests 
>   
Side effects
Documentation
```release-note
None
```

expression: Add json_array push down support for tiflash

---

pkg/planner/core/indexmerge_path_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/47759
Tests 
>   
Side effects
Documentation
```release-note
None
```

planner: add rand test for cnf/dnf index merge case

---

pkg/statistics/handle/autoanalyze/BUILD.bazel
pkg/statistics/handle/autoanalyze/autoanalyze.go
pkg/statistics/handle/autoanalyze/autoanalyze_test.go
pkg/statistics/handle/lockstats/lock_stats.go
pkg/statistics/handle/lockstats/unlock_stats.go
pkg/statistics/handle/util/BUILD.bazel
pkg/statistics/handle/util/interfaces.go

- Added more comments to the auto-analyze process.
- Format the code and make sure it is not too long.
- Extracted the `getAllTidsAndPids` to improve readability.
- Removed the useless argument.
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: Refactor code to improve readability

---

br/pkg/lightning/backend/external/BUILD.bazel
br/pkg/lightning/backend/external/engine.go
pkg/util/BUILD.bazel
pkg/util/wait_group_wrapper.go
pkg/util/wait_group_wrapper_test.go

Issue Number: close #48480
Tests 
>   
Side effects
Documentation
```release-note
None
```

util: add recover wrapper with error group

---

executor/recover_test.go
sessiontxn/staleread/util.go

close pingcap/tidb#48372
Tests 
>   
Side effects
Documentation
```release-note
None
```

pkg: support the TSO format for asof expression (#48371)

---

pkg/metrics/grafana/tidb.json

Issue Number: close #48291
Tests 
2. import tidb.json
3. check tidb->Server->TiDB server status on Grafana
>   
Side effects
Documentation
```release-note
None
```

metrics: add server status count

---

WORKSPACE

Tests 
>   
Side effects
Documentation
```release-note
None
```

*: upgrade bazel_gazelle

---

pkg/domain/BUILD.bazel
pkg/domain/domain.go
pkg/statistics/BUILD.bazel
pkg/statistics/builder.go
pkg/statistics/handle/BUILD.bazel
pkg/statistics/handle/autoanalyze/BUILD.bazel
pkg/statistics/handle/autoanalyze/autoanalyze.go
pkg/statistics/handle/cache/BUILD.bazel
pkg/statistics/handle/cache/statscache.go
pkg/statistics/handle/globalstats/BUILD.bazel
pkg/statistics/handle/globalstats/global_stats_async.go
pkg/statistics/handle/handle.go
pkg/statistics/handle/lockstats/BUILD.bazel
pkg/statistics/handle/lockstats/lock_stats.go
pkg/statistics/handle/lockstats/unlock_stats.go
pkg/statistics/handle/logutil/BUILD.bazel
pkg/statistics/handle/logutil/logutil.go
pkg/statistics/handle/storage/BUILD.bazel
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/storage/save.go
pkg/statistics/handle/util/BUILD.bazel
pkg/statistics/handle/util/interfaces.go

just a clean code.
Tests 
>   
Side effects
Documentation
```release-note
None
```

handle: use logutil to unify the log category

---

br/pkg/aws/ebs.go
br/pkg/task/restore_ebs_meta.go

Issue Number: close #48505 
This PR will control the batch size of snapshots for AWS snapshot FSR enablement.
Tests 
>   
Side effects
Documentation
```release-note
None
```

ebs br: control the snapshots batch size for fsr enable/disable

---

br/pkg/utils/backoff.go
br/pkg/utils/retry.go
br/tests/br_full/run.sh

Issue Number: close #48528 
the error need to be marked as the retryable error
add the error message into the retryable error list
Tests 
>   
Side effects
Documentation
```release-note
None
```

br: add more retryable error for br_import

---

pkg/planner/core/optimizer.go
pkg/planner/core/stats.go

Because we only use `DoOptimizeAndLogicAsRet` internally, so better to rename it and give it a better comment. Then we can minimize unnecessary confusion.
- Fixed the code length issues.
- Rename the `DoOptimizeAndLogicAsRet` to `doOptimize`.
Tests 
>   
Side effects
Documentation
```release-note
None
```

planner: Improve the DoOptimize function names to minimize unnecessary confusion

---

DEPS.bzl
go.mod
go.sum
pkg/domain/infosync/resource_manager_client.go
pkg/executor/internal/calibrateresource/BUILD.bazel
pkg/executor/internal/calibrateresource/calibrate_resource_test.go

Issue Number: ref #35319.
Problem Summary: upgrade and adapt to the new PD client.
Tests 
```release-note
None
```

*: upgrade and adapt to the new PD client

---

.codecov.yml

Problem Summary: fix issues introduced by #48581
Tests 
>   
Side effects
Documentation
```release-note
None
```
[SKIP-CI]

CI: fix empty values for `information` fileds

---

pkg/executor/union_scan_test.go

Issue Number: ref #48622
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: fix typo of some tests

---

executor/mem_reader.go

Hotfix for 7.4, original PR https://github.com/pingcap/tidb/pull/45786
Tests 
>   
Side effects
Documentation
```release-note
None
```

executor: union scan refactor for index read scenario #45786

---

pkg/executor/infoschema_reader.go

Issue Number: close #48602
Tests 
before 
after
>   
Side effects
Documentation
```release-note
None
```

executor: avoid displaying progress when to merge global stats

---

DEPS.bzl
go.mod
go.sum
pkg/domain/infosync/resource_manager_client.go
pkg/domain/runaway.go
pkg/executor/internal/calibrateresource/BUILD.bazel
pkg/executor/internal/calibrateresource/calibrate_resource_test.go
pkg/store/mockstore/unistore/pd.go

Issue Number: close https://github.com/pingcap/tidb/issues/48598
Tests 
```release-note
None
```

*: update pd client and client-go

---

pkg/session/bootstraptest/bootstrap_upgrade_test.go
pkg/session/mock_bootstrap.go

Issue Number: close https://github.com/pingcap/tidb/issues/48554
`with-mock-upgrade` doesn't work.
Use `*bool` instead of `bool`.
Tests 
Do issue case and pass.
>   
Side effects
Documentation
```release-note
None
```

session: fix mock upgrade mode in test

---

br/pkg/storage/local.go
br/pkg/storage/local_test.go

Issue Number: close #48452
Tests 
>   
Side effects
Documentation
```release-note
None
```

br: fix incorrect uri for the file storage

---

pkg/statistics/histogram.go

Issue Number: ref #48713
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: add logs to facilitate debugging

---

pkg/statistics/BUILD.bazel
pkg/statistics/builder_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/48699
Fix #48699
Tests 
>   
Side effects
Documentation
```release-note
None
```

statistics: Add benchmark for BuildHistAndTopN

---

.github/pull_request_template.md

Fixed some grammar issues in the pull request template.
Tests 
>   
Side effects
Documentation
```release-note
None
```

github: fix some grammar issues in the pull request template

---

Makefile
pkg/statistics/BUILD.bazel
pkg/statistics/bench_daily_test.go
pkg/statistics/builder_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/48699
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: add daily bench and improve bench

---

pkg/session/bootstrap_test.go

Issue Number: close #46834
Tests 
> 
Side effects
Documentation
```release-note
None
```

bootstrap: split index merge bootstrap case

---

.codecov.yml
Makefile

Issue Number: close #48868
Tests 
```
$ head -n 10 tests/realtikvtest/addindextest3/addindextest3_test/coverage.dat 
mode: set
github.com/pingcap/tidb/pkg/statistics/index.go:45.33,46.16 1 1
github.com/pingcap/tidb/pkg/statistics/index.go:49.2,55.25 3 1
github.com/pingcap/tidb/pkg/statistics/index.go:58.2,58.21 1 1
github.com/pingcap/tidb/pkg/statistics/index.go:61.2,61.25 1 1
github.com/pingcap/tidb/pkg/statistics/index.go:64.2,64.21 1 1
github.com/pingcap/tidb/pkg/statistics/index.go:67.2,69.11 3 1
github.com/pingcap/tidb/pkg/statistics/index.go:46.16,48.3 1 0
github.com/pingcap/tidb/pkg/statistics/index.go:55.25,57.3 1 0
github.com/pingcap/tidb/pkg/statistics/index.go:58.21,60.3 1 0
```
> 
Side effects …

bazel: add instrumentation_filter to collect all coverage

---

pkg/disttask/framework/BUILD.bazel
pkg/disttask/framework/dispatcher/dispatcher.go
pkg/disttask/framework/framework_test.go

Issue Number: close #48890
Tests 
> 
Side effects
Documentation
```release-note
None
```

disttask: fix keep reporting error when cancel pending task

---

pkg/bindinfo/tests/BUILD.bazel
pkg/bindinfo/tests/bind_test.go
pkg/parser/parser.y

Issue Number: close #48876
Problem Summary: planner: simplify the syntax of creating bindings
planner: simplify the syntax of creating bindings
See https://github.com/pingcap/tidb/issues/48876
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: simplify the syntax of creating bindings

---

pkg/config/config.go
pkg/statistics/handle/bootstrap.go

- I have updated the outdated comments. Because the lite load now loads the index and column histograms as well.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: update outdated comments

---

pkg/expression/expr_to_pb_test.go
pkg/expression/expression.go

Issue Number: close #48994
Tests 
> 
Side effects
Documentation
```release-note
Add `json_depth` push down support for tiflash.
```

expression: Add `json_depth` push down support for tiflash

---

pkg/statistics/handle/globalstats/global_stats.go

Issue Number: close #49041 
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: fix invaild asnyc_merge_global_stats

---

pkg/bindinfo/capture.go
pkg/bindinfo/handle.go

Issue Number: close #49088
Problem Summary: planner: fix DATA RACE caused by TestCaptureWildcardFilter
fix DATA RACE caused by TestCaptureWildcardFilter
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix DATA RACE caused by TestCaptureWildcardFilter

---

pkg/server/BUILD.bazel
pkg/server/extract.go
pkg/server/handler/extractorhandler/BUILD.bazel
pkg/server/handler/extractorhandler/extract_test.go
pkg/server/handler/extractorhandler/extractor.go
pkg/server/handler/extractorhandler/main_test.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

server: fix spell

---

server/BUILD.bazel
server/conn.go
server/conn_test.go
server/http_status.go
server/server.go
tidb-server/main.go

This reverts commit b504f0b37d19bd689db359c2076bedb31d6576aa.
Issue Number: close #49098
See #49098 for more details.
See #49098 for more details.
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```

server: revert "#48905" for release-6.5

---

tests/realtikvtest/addindextest/BUILD.bazel
tests/realtikvtest/addindextest/add_index_test.go
tests/realtikvtest/addindextest/concurrent_ddl_test.go
tests/realtikvtest/addindextest/failpoints_test.go
tests/realtikvtest/addindextest/multi_schema_change_test.go
tests/realtikvtest/addindextest/pitr_test.go
tests/realtikvtest/addindextestutil/BUILD.bazel
tests/realtikvtest/addindextestutil/common.go
tests/realtikvtest/addindextestutil/compatibility.go
tests/realtikvtest/addindextestutil/workload.go

Issue Number: close #49121
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl/test: split realtikv addindex testutil

---

pkg/util/sqlkiller/BUILD.bazel
pkg/util/sqlkiller/sqlkiller.go

Add a failpoint for random panic test
Tests 
> 
Side effects
Documentation
```release-note
None
```

util: add a failpoint for random panic test

---

.github/licenserc.yml

Issue Number: close #49156
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: exclude `**/.git/**` in licenserc.yml

---

pkg/statistics/histogram.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: remove useless code

---

pkg/plugin/plugin.go

Issue Number: ref #49273
Tests 
> 
Side effects
Documentation
```release-note
None
```

plugin: add lost rewatch sleep in plugin loop

---

.gitignore
Makefile
pkg/domain/plan_replayer_handle_test.go
pkg/executor/test/executor/executor_test.go
pkg/server/handler/optimizor/BUILD.bazel
pkg/server/handler/optimizor/plan_replayer_test.go

Issue Number: close #49070
After `make test` or `make ut`, some unnecessary files can be shown as untracked files for git. We should prevent accidental commit for them.
After this change, files pointed out in #49070 won't be shown in untracked files and you can remove them by executing `make clean`.
There are 3 types of files which are reported in the issue.
Since test coverage files should be committed, ignoring this folder makes sense.
Although 3 folders are reported (`pkg/executor/test/executor/replayer/`, `pkg/server/handler/optimizor/replayer/`, `tests/integrationtest/replayer/`), `replayer` folder can be made in more places. (e.g. `./pkg/server/replayer`, `./pkg/domain/replayer`, ) . I added file names instead of listing folder names.
The file names and the folder …

*: add unnecessary untracked files to .gitignore and clean up them

---

pkg/disttask/framework/storage/table_test.go
pkg/disttask/framework/storage/task_table.go
pkg/disttask/framework/storage/util.go

This is a manually cherry-pick of part of the code in https://github.com/pingcap/tidb/pull/49020
Issue Number: close #49263
see issue
Tests 
> 
Side effects
Documentation
```release-note
None
```

disttask: query subtask fields with explicit order

---

.github/licenserc.yml
MODULE.bazel
MODULE.bazel.lock
tools/check/check-bazel-prepare-rbe.sh
tools/check/check-bazel-prepare.sh

bazel 7 have enable the bzlmod. and it will create some file so I upload it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

bazel: support module

---

br/pkg/lightning/common/BUILD.bazel
br/pkg/lightning/common/common_test.go
br/pkg/lightning/importer/table_import.go
pkg/ddl/column.go
pkg/ddl/ddl.go
pkg/ddl/options.go
pkg/disttask/importinto/subtask_executor.go
pkg/domain/BUILD.bazel
pkg/domain/domain.go
pkg/meta/autoid/BUILD.bazel
pkg/meta/autoid/autoid.go
pkg/meta/autoid/autoid_service.go
pkg/meta/autoid/autoid_test.go

hotfix on 7.5 branch 
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: fix grpc client leak bug for AUTO_ID_CACHE=1 tables (#48870)

---

pkg/statistics/handle/autoanalyze/BUILD.bazel
pkg/statistics/handle/autoanalyze/autoanalyze_test.go

added a test to cover index auto-analyze behavior
Covered three behaviors:
1. Before a table has been analyzed, it should be analyzed regardless of the ratio.
2. If the ratio is 0, do not analyze tables that have already been analyzed.
3. Even if the ratio is 0, analyze newly added indexes.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: add a test to cover index auto-analyze behavior

---

pkg/util/gctuner/memory_limit_tuner.go
pkg/util/gctuner/memory_limit_tuner_test.go

Problem Summary: Check `MemoryLimitGCTotal` instead of `r.NumGC` to avoid go runtime gc affecting test results.
Tests 
> 
Side effects
Documentation
```release-note
None
```

gctuner: make TestIssue48741 more stable

---

pkg/expression/expr_to_pb_test.go
pkg/expression/expression.go

Issue Number: close #49345
Tests 
> 
Side effects
Documentation
```release-note
Add json_valid and json_keys push down support for tiflash.
```

expression: Add `json_valid` and `json_keys` push down support for tiflash

---

pkg/statistics/handle/ddl/BUILD.bazel
pkg/statistics/handle/ddl/ddl_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/48126
- Added a case for truncating hash partition.
- Added a case for increasing the hash partition number.
- Added a case for decreasing the hash partition number.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: add more test cases for handling DDL event

---

pkg/bindinfo/BUILD.bazel
pkg/bindinfo/bind_record.go
pkg/bindinfo/universal_binding_test.go
pkg/planner/core/logical_plan_builder.go
pkg/planner/core/planbuilder.go
pkg/planner/core/rule_join_reorder.go

Problem Summary: planner: match hints from universal bindings correctly
planner: match hints from universal bindings correctly
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: match hints from universal bindings correctly

---

.dockerignore
Dockerfile
Dockerfile.enterprise

Use the official golang mirror as the builder image, supporting building on Linux arm64.
Issue Number: close https://github.com/pingcap/tidb/issues/49071,https://github.com/pingcap/tidb/issues/49560
Tests 
> 
Side effects
Documentation
```release-note
None
```

dockerfile: optimize dockerfile

---

pkg/planner/core/hints.go

just clean code
Tests 
> 
Side effects
Documentation
```release-note
None
```

binding: use matchTiKVOrTiFlash to remove duplicate code

---

DEPS.bzl
expression/builtin_convert_charset.go
expression/integration_test.go
go.mod
go.sum

This is a manually cherry-pick of #49527
Issue Number: close #49526
Ignore the `TypeNull` in `HandleBinaryLiteral`, as the `castStringToString` will actually do nothing for NULL (except changing the type).
Tests 
> 
Side effects
Documentation
```release-note
None
```

expression: ignore NULL in handle binary literal (#49527)

---

br/cmd/br/fips.go
br/cmd/tidb-lightning-ctl/fips.go
br/cmd/tidb-lightning/fips.go
tidb-server/fips.go

Now we maintain special branch https://github.com/pingcap/tidb/tree/feature/release-6.5-fips instead of release with the master
The version already padding the branch name, so we can remove this, otherwise we get 'release-6.5-fips-fips'
Tests 
```
./bin/tidb-server -V
Release Version: v6.5.6-3-gd2ed500f62
Edition: Community
Git Commit Hash: d2ed500f62d442f92879b3366b1de9faf8b59eb9
Git Branch: fip-6.5
UTC Build Time: 2023-12-21 06:22:37
GoVersion: go1.21.0
TiKV Min Version: 6.2.0-alpha
```
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb …

br,tidb,lightning: remove 'fips' suffix on version

---

pkg/expression/builtin_ilike_vec.go

Issue Number: close #49677
Tests 
> 
Side effects
Documentation
```release-note
fix datarace for `ilike` function in same cases
```

expression: fix datarace for `builtinIlikeSig`

---

pkg/executor/analyze_col.go

Issue Number: close #49704
We've found that the current implementation of the AnalyzeColumnsExec includes unnecessary BCE (Bounds Check Elimination). so this pr is to remove them.
Tests 
before
```
pkg/executor/analyze_col.go:245:21: Found IsInBounds
pkg/executor/analyze_col.go:251:31: Found IsInBounds
pkg/executor/analyze_col.go:252:25: Found IsInBounds
pkg/executor/analyze_col.go:253:25: Found IsInBounds
pkg/executor/analyze_col.go:259:28: Found IsInBounds
pkg/executor/analyze_col.go:326:16: Found IsSliceInBounds
```
after
```
pkg/executor/analyze_col.go:245:21: Found IsInBounds
pkg/executor/analyze_col.go:251:31: Found IsInBounds
pkg/executor/analyze_col.go:252:36: Found IsInBounds
pkg/executor/analyze_col.go:327:16: Found IsSliceInBounds
```
> - [ ] I checked and no …

executor: remove bce in the AnalyzeColumnsExec

---

Makefile

Problem Summary: fix https://cd.pingcap.net/blue/organizations/jenkins/build-common/detail/build-common/277921/pipeline/
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: rm -f to silent error

---

pkg/infoschema/perfschema/tables.go
pkg/server/conn_stmt_params_test.go
pkg/store/copr/batch_coprocessor.go

Tests 
> 
Side effects
Documentation
```release-note
server: refactor server pkg's warning and note generation
```

server: refactor server pkg's warning and note generation

---

pkg/session/BUILD.bazel
pkg/session/bootstrap_test.go

Issue Number: close #47045
Problem Summary: planner: disable race check in session package to speed up bootstrap test
planner: disable race check in session package to speed up bootstrap test
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: disable race check in session package to speed up bootstrap test

---

pkg/statistics/handle/autoanalyze/autoanalyze.go
pkg/statistics/handle/autoanalyze/autoanalyze_test.go

Issue Number: close #49724
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: fix bad sql with many interrupted analyze jobs

---

pkg/statistics/histogram.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: add comments to reuse the memory

---

pkg/executor/infoschema_cluster_table_test.go

Issue Number: close #49772
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix unstable `TestTiDBClusterInfo` test

---

br/cmd/br/BUILD.bazel
br/cmd/br/cmd.go
br/cmd/tidb-lightning/BUILD.bazel
br/cmd/tidb-lightning/main.go

Issue Number: ref #47442
as title
Tests 
> very easy
Side effects
Documentation
```release-note
None
```

br, lightning: call memory hook init in main()

---

pkg/table/column.go

Tests 
> 
Side effects
Documentation
```release-note
table: refactor table pkg's warning and note generation
```

table: refactor table pkg's warning and note generation

---

br/pkg/lightning/backend/local/local.go
br/pkg/lightning/backend/local/localhelper.go
br/pkg/lightning/backend/local/localhelper_test.go
br/pkg/mock/BUILD.bazel
br/pkg/mock/mock_cluster.go
br/pkg/pdutil/pd.go
br/pkg/restore/BUILD.bazel
br/pkg/restore/client.go
br/pkg/restore/client_test.go
br/pkg/restore/split/BUILD.bazel
br/pkg/restore/split/client.go
br/pkg/restore/split_test.go
br/pkg/restore/util.go
br/pkg/task/restore.go
br/pkg/task/restore_data.go
br/pkg/task/restore_raw.go
br/pkg/task/restore_test.go
br/pkg/task/restore_txn.go
br/pkg/task/stream.go
br/tests/lightning_local_backend/config.toml

Issue Number: ref #49865
as title. Also this PR fixes a lightning integration test
Tests 
> 
Side effects
Documentation
```release-note
None
```

br, lightning: split client use pd HTTP client

---

DEPS.bzl
go.mod
go.sum

Tests 
> 
Side effects
Documentation
```release-note
None
```

*: fix appdash version

---

pkg/planner/core/plan_cacheable_checker.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: use switch to simple code

---

pkg/executor/set.go

Issue Number: close #49978
Tests 
downgrade version from master to 7.5, run `set tidb_service_scope='background';` should work
> 
Side effects
Documentation
```release-note
None
```

disttask: use explicit column list when set tidb_service_scope

---

pkg/bindinfo/binding_match.go
pkg/planner/optimize.go

Problem Summary: planner: move more binding code to binding package
JUST CODE MOVEMENT, NO LOGICAL CHANGE.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: move more binding code to binding package

---

pkg/bindinfo/binding_match.go
pkg/bindinfo/universal_binding_test.go
pkg/infoschema/test/clustertablestest/cluster_tables_test.go

Problem Summary: planner: remove universal binding and skip related test cases temporarily
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: remove universal binding and skip related test cases temporarily

---

pkg/disttask/framework/storage/table_test.go

Issue Number: close #49984
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix flaky case

---

pkg/statistics/handle/globalstats/global_stats_async.go

Issue Number: close #50030
Tests 
before:
```
pkg/statistics/handle/globalstats/global_stats_async.go:518:20: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:525:35: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:526:21: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:526:39: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:528:20: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:528:53: Found IsInBounds
```
after:
```
pkg/statistics/handle/globalstats/global_stats_async.go:518:34: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:527:24: Found IsInBounds
pkg/statistics/handle/globalstats/global_stats_async.go:529:38: Found …
```

statistics: BCE for the async global stats

---

DEPS.bzl
go.mod
go.sum

Tests 
> 
Side effects
Documentation
```release-note
None
```

dep: upgrade PD client

---

pkg/ddl/backfilling_scheduler.go
pkg/expression/errors.go
pkg/sessionctx/stmtctx/stmtctx.go
tests/integrationtest/r/generated_columns.result
tests/integrationtest/t/generated_columns.test

Issue Number: close #50053
fix reorg cannot handle divide 0 error
Tests 
> 
Side effects
Documentation
```release-note
fix reorg cannot handle divide 0 error
```

ddl: fix reorg cannot handle divide 0 error

---

DEPS.bzl
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/49311
Tests 
> 
```release-note
None
```

mod: upgrade pd client to latest release-7.5

---

pkg/disttask/framework/scheduler/scheduler_test.go
pkg/disttask/framework/storage/BUILD.bazel
pkg/disttask/framework/storage/table_test.go
pkg/disttask/framework/storage/task_state_test.go

Issue Number: ref #48795 
Tests 
> 
Side effects
Documentation
```release-note
None
```

disttask: add more tests for task_state

---

pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
pkg/statistics/handle/autoanalyze/priorityqueue/job.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go

Part of https://github.com/pingcap/tidb/pull/49418
This PR added a basic priority queue based on the weight of the table.
Also added some tests to it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: add basic analysis job queue

---

pkg/bindinfo/binding_match.go

Problem Summary: planner: fix incorrect object pool usage in binding package
planner: fix incorrect object pool usage in binding package
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix incorrect object pool usage in binding package

---

br/pkg/lightning/config/config.go
br/pkg/lightning/config/config_test.go

Issue Number: close #50136
as issue
Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning config: tolerate tidb backend parallel-import

---

DEPS.bzl
go.mod
go.sum

Issue Number: ref https://github.com/tikv/pd/issues/7676
Tests 
> 
Side effects
Documentation
```release-note
None
```

gomod: update pd client

---

docs/design/2023-09-12-grouping-sets.md

Issue Number: close https://github.com/pingcap/tidb/issues/42631
Tests 
Side effects
Documentation
```release-note
doc: add grouping sets doc
```

doc: add grouping sets doc

---

pkg/expression/builtin_compare.go
pkg/planner/core/partition_pruning_test.go
pkg/planner/core/rule_partition_processor.go
pkg/types/compare.go
tests/integrationtest/r/planner/core/partition_pruner.result
tests/integrationtest/t/planner/core/partition_pruner.test

Issue Number: close #50082
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix range partition prune with an unsigned column

---

pkg/executor/recover_test.go
pkg/store/driver/main_test.go

Issue Number: close #50153
Problem Summary: Do not use image in `TestFlashbackSchema`, there may be some old ddl jobs causing get a wrong error in the tests.
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix unstable test `TestFlashbackSchema`

---

pkg/table/tables/index.go

Issue Number: close https://github.com/pingcap/tidb/issues/50214
Remove some useless codes.
Tests 
In the 16GB scenario, about 1G memory is reduced, and memory usage is stable.
**Before this PR**
**After this PR**
> 
Side effects
Documentation
```release-note
None
```

table: reduce unnecessary memory usage

---

pkg/owner/manager.go

Issue Number: close https://github.com/pingcap/tidb/issues/50152
Tests 
There's a test in the original code.
> 
Side effects
Documentation
```release-note
None
```

owner: add error check

---

pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
pkg/statistics/handle/autoanalyze/priorityqueue/interval.go
pkg/statistics/handle/autoanalyze/priorityqueue/interval_test.go
pkg/statistics/handle/autoanalyze/priorityqueue/main_test.go

Issue Number: ref https://github.com/pingcap/tidb/pull/49018
Added some functions to get the analysis intervals.
Tests 
> 
Side effects
Documentation
```release-note
None
```

feat: add interval util functions for priority queue

---

pkg/disttask/framework/taskexecutor/manager_test.go

Issue Number: close #50297
use mu to protect context
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix race in TestManagerHandleTasks

---

WORKSPACE
build/image/base
tests/globalkilltest/Dockerfile

Tests 
> 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.21.6

---

pkg/ddl/table_test.go

Issue Number: close #44948 
Similar to #43825. It is possible that the last DDL job does not exit in time.
```
[2024/01/11 06:36:15.397 +00:00] [INFO] [callback.go:122] ["on job updated"] [job="ID:110, Type:rename table, State:running, SchemaState:public, SchemaID:104, TableID:108, RowCount:0, ArgLen:1, start time: 2024-01-11 06:36:15.382 +0000 UTC, Err:<nil>, ErrCount:0, SnapshotVersion:0, LocalMode: false"]
[2024/01/11 06:36:15.398 +00:00] [WARN] [session.go:2209] ["compile SQL failed"] [error="[schema:1146]Table 'db1.t' doesn't exist"] [errorVerbose="[schema:1146]Table 'db1.t' doesn't exist\ngithub.com/pingcap/errors.AddStack\n\texternal/com_github_pingcap_errors/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\texternal/com_github_pingcap_errors/n …
```

test: stabilize TestRenameTableIntermediateState

---

WORKSPACE

Tests 
> 
Side effects
Documentation
```release-note
None
```

*: upgrade rules for golang

---

pkg/planner/core/plan_cache_test.go
pkg/planner/core/plan_cache_utils.go

Issue Number: ref #49736
Problem Summary: planner: enhance fix control 49736
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: enhance fix control 49736

---

pkg/util/security_test.go

Issue Number: ref #36036
Add a tiny unit test to verify tls1.0/1.1 is not supported.
Tests 
> 
Side effects
Documentation
```release-note
None
```

util: add a unit test to test min tls version

---

br/pkg/restore/data.go

Issue Number: close #50315, close #50312
See #50312 
```commit-message
Removed the wait apply phase of restoring.
```
Tests 
(Will run regression test.)
> 
```release-note
None
```

restore_data: remove wait apply phase

---

pkg/bindinfo/bind_cache.go
pkg/bindinfo/bind_cache_test.go
pkg/bindinfo/bind_record.go
pkg/bindinfo/global_handle.go
pkg/bindinfo/session_handle.go
pkg/domain/plan_replayer.go
pkg/domain/plan_replayer_dump.go
pkg/executor/adapter.go
pkg/planner/optimize.go
pkg/server/testdata/optimizer_suite_out.json

Problem Summary: planner: clean BindRecord in the binding package
NO LOGICAL CHANGE, JUST REFACTOR
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: clean BindRecord in the binding package

---

pkg/expression/expr_to_pb_test.go
pkg/expression/infer_pushdown.go

Issue Number: close #50485
allow pushdown `power` to TiFlash/TiKV
Tests 
> 
Side effects
Documentation
```release-note
None
```

expression: allow pushdown `power` to TiFlash/TiKV

---

pkg/planner/core/BUILD.bazel
pkg/planner/core/indexmerge_path.go
tests/integrationtest/r/planner/core/casetest/index/index.result
tests/integrationtest/t/planner/core/casetest/index/index.test

Issue Number: close https://github.com/pingcap/tidb/issues/50496
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix index merge intersection case will have redundant partial path

---

pkg/executor/builder.go
pkg/executor/test/tiflashtest/BUILD.bazel
pkg/executor/test/tiflashtest/tiflash_test.go
pkg/planner/core/rule_eliminate_projection.go

Issue Number: ref #50358
Described in #50358
Quick fix for the issue in executor. Had tried to fix it in planner phase, but failed with so many test failures: https://github.com/pingcap/tidb/pull/50410
May try to fix it in planner phase later.
Tests 
Try to run cross join queries with high concurrency, and check no empty result sets are found
> 
Side effects
Documentation
```release-note
None
```

executor: check schema when build table reader executor

---

pkg/executor/importer/table_import.go

Issue Number: close #50586
some already changed in https://github.com/pingcap/tidb/pull/49516, will pick it to 7.5 too
Tests 
test import into a table `create table t(a int auto_increment primary key nonclustered) auto_id_cache=1;`, should success and fast
> 
Side effects
Documentation
```release-note
None
```

importinto: fix multiple pd addr

---

pkg/bindinfo/bind_cache.go
pkg/bindinfo/global_handle.go
pkg/bindinfo/session_handle.go

Issue Number: close #48875
Tests 
> 
Side effects
Documentation
```release-note
None
```

bindinfo: simple code

---

pkg/planner/core/planbuilder.go
pkg/planner/core/planbuilder_test.go
pkg/statistics/handle/handletest/analyze/analyze_test.go

Issue Number: close #50597
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: increase the upper limit for analyze

---

DEPS.bzl
go.mod
go.sum
pkg/meta/autoid/autoid_service.go

Issue Number: close #50519
Cherry-pick https://github.com/pingcap/tidb/pull/50522 for a hotfix 
Tests 
> 
Side effects
Documentation
```release-note
None
```

meta/autoid: make autoid client ResetConn operation concurrency-safe (#50522)

---

pkg/telemetry/data_cluster_info.go

Issue Number: close #50426 
Problem Summary: data column type changed, so the code panic.
Tests 
> 
Side effects
Documentation
```release-note
None
```

telemetry: fix panic on newer version

---

pkg/parser/reserved_words_test.go

Tested against MySQL 8.2.0
Issue Number: close #48856
Tests 
> 
Side effects
Documentation
```release-note
None
```

parser: Update TestCompareReservedWordsWithMySQL

---

pkg/executor/sortexec/sortexec_pkg_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/50679
Tests 
> 
Side effects
Documentation
```release-note
None
```

exeuctor: fix data race for test TestInterruptedDuringSort

---

pkg/ttl/ttlworker/job_manager_integration_test.go

Issue Number: close #50686
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: fix unstable test `TestManagerJobAdapterCanSubmitJob`
