- ddl/BUILD.bazel
- ddl/db_test.go
- ddl/ddl.go
- ddl/pause_test.go
- errno/errcode.go
- errno/errname.go
- errors.toml
- executor/builder.go
- executor/executor.go
- parser/model/ddl.go
- util/dbterror/ddl_terror.go
Add Pause/Resume admin command in parser and planner
What problem does this PR solve?
Issue Number: close https://github.com/pingcap/tidb/issues/18015 https://github.com/pingcap/tidb/issues/40041
Related issue number: https://github.com/pingcap/tidb/issues/39751 https://github.com/pingcap/tidb/pull/43061
Related PR: https://github.com/pingcap/tidb/pull/43081
Problem Summary: Add pause/resume on ddl jobs
What is changed and how it works?
`Add admin pause ddl jobs 3,5`;
a. the job should be in Running or Queueing state
b. change the state to be Pausing on command issued, in another PR
c. background work will pause the job once scheduled, in another PR
`Add admin resume ddl jobs 3,5`;
a. the job should be paused
b. change the state to be Queueing on command issued, in another PR
c. …
> ddl, executor: executor change for pause/resume on ddl jobs

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/importer/import.go
- br/pkg/lightning/importer/meta_manager.go
- br/pkg/pdutil/pd.go
Issue Number: ref #43657
- add implicit config `tikv-importer.force-pause-scheduler-by-remove`, default is true, i.e. pause scheduler by removing scheduler on default
- 
Tests 
run with default
```log
➜  lightning grep 'removing PD leader' tidb-lightning.log
[2023/05/09 20:02:19.006 +08:00] [INFO] [import.go:1496] ["removing PD leader&region schedulers"]
➜  lightning grep 'pause scheduler by key range' tidb-lightning.log
➜  lightning
```
set it to false and run again
```log
➜  lightning grep 'removing PD leader' tidb-lightning.log
➜  lightning grep 'pause scheduler by key range' tidb-lightning.log
[2023/05/09 20:04:12.568 +08:00] [INFO] [local.go:1298] ["pause scheduler by key range"]
[2023/05/09 20:04:13.662 +08:00] [INFO] [local.go:1298] ["pause scheduler by key range"] …
```
> lightning: pause scheduler by removing scheduler on default

- domain/BUILD.bazel
- domain/domain.go
- domain/plan_replayer.go
- domain/plan_replayer_test.go
- util/replayer/BUILD.bazel
- util/replayer/replayer.go
Issue Number: close #43663 
- For plan replayer capture file without historical stats enabled, name it "capture_normal_replayer_XXX.zip".
- As title says, increase  GC duration for plan relayer capture file to 7 days
Tests 
Side effects
Documentation
```release-note
None
```
> domain, util/replayer: increase GC duration for plan replayer capture file to 7 days

- ddl/backfilling.go
- ddl/column.go
- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/index.go
- ddl/job_table.go
- ddl/partition.go
- ddl/reorg.go
- ddl/rollingback.go
- ddl/scheduler.go
- server/http_handler_serial_test.go
What problem does this PR solve?
Issue Number: close https://github.com/pingcap/tidb/issues/18015 https://github.com/pingcap/tidb/issues/40041
Related issue number: https://github.com/pingcap/tidb/issues/39751 https://github.com/pingcap/tidb/pull/43061
Problem Summary:  support `admin pause ddl jobs 3,5;` and `admin resume ddl jobs 3,5;`
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: background reorganization change for `admin pause/resume ...`

- domain/BUILD.bazel
- domain/plan_replayer.go
- executor/adapter.go
- planner/core/plan_cache.go
- server/BUILD.bazel
- server/optimize_trace_test.go
- server/testdata/optimizer_suite_in.json
- server/testdata/optimizer_suite_out.json
Issue Number: close #43620
Trying to parse a normalized SQL in `HandleTask()`
- Fix the incorrect method to get the original prepared ast when handling the EXECUTE stmt.
- Add a debug trace point to record the parameters for both binary/non-binary EXECUTE stmt.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix incorrect handling of EXECUTE stmt in plan replayer capture

- sessionctx/variable/tidb_vars.go
Issue Number: ref #43667
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: change default value of tidb_enable_non_prepared_plan_cache to false

- executor/test/analyzetest/analyze_test.go
- planner/core/planbuilder.go
Issue Number: close #43705
When we decide which columns must be analyzed, we skip the columns existing in multi-value indexes because we don't collect stats for multi-value indexes for now.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: skip json column which exists in mv index when collecting stats

- sessionctx/variable/session.go
- sessionctx/variable/session_test.go
- sessiontxn/isolation/BUILD.bazel
- sessiontxn/isolation/base.go
- sessiontxn/isolation/readcommitted_test.go
Issue Number: close #43294 
Tests 
Side effects
Documentation
```release-note
None
```
> txn: introduce the statement buffer of pessimistic lock cache

- br/metrics/grafana/lightning.json
Issue Number: ref https://github.com/pingcap/tidb/issues/43357
1. Update gauge to bargauge to make sure the show is correct for parallel importing.
before:
after:
2. add instance label for some lightning panels.
Tests 
Deploy a tidb cluster using new grafana template and it works.
Side effects
- None
Documentation
- None
```release-note
None
```
> lightning: update lightning metrics to bargauge

- DEPS.bzl
- br/pkg/aws/ebs.go
- br/pkg/task/backup_ebs.go
- br/pkg/task/restore_ebs_meta.go
- go.mod
- go.sum
Issue Number: close #43433 
Use AWS SDK API CreateSnapshots to create snapshots for multiple volumes to make crash consistent.
Tests 
1. Established a real tidb cluster on tidb cloud
2. Run `bin/br backup full --type=aws-ebs --volume-file=../../built/clustermeta.txt --pd=localhost:2379 --send-credentials-to-tikv=false --storage=s3://xxxxx --s3.region=ap-northeast-1 --s3.provider=aws` command and verify snapshots are created for and only for specified EBS volumes, and tags for volumes are copied
3. Verify above logic work also for tidb cloud
Side effects
Documentation
```release-note
None
```
> br: use AWS CreateSnapshots API to automic create snapshots for multiple volumes

- ddl/BUILD.bazel
- ddl/backfilling_scheduler.go
- ddl/export_test.go
- ddl/index_cop.go
Issue Number: close #40074
Previously, we use `store.CurrentVersion` to get the latest start TS to read table records. This is problematic because it does not take the GC life time into account.
Get an internal session and begin transaction explicitly. Thus, we can utilize the mechanism introduced in #42897 to block the progress of GC safe point before the reading is complete.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: use session begin timestamp to read record for adding index

- parser/ast/ddl.go
- parser/parser.y
- parser/parser_test.go
Issue Number: close #22535
After the change, the error code and message is the same with MySQL.
Before:
```
mysql>  create table t1 (a int, b int as (a + 1) default 10);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 52 near ")"Invalid column definition
```
After: 
```
mysql> create table t1 (a int, b int as (a + 1) default 10);
ERROR 1221 (HY000): Incorrect usage of DEFAULT and generated column
```
Tests 
```
mysql> create table t1 (a int, b int as (a + 1) default 10);
ERROR 1221 (HY000): Incorrect usage of DEFAULT and generated column
mysql> create table t1 (a int, b int as (a + 1) on update now());
ERROR 1221 (HY000): Incorrect usage of ON UPDATE and generated …
```
> parser: polish the error message for generated column with default value

- br/pkg/lightning/lightning.go
- br/pkg/lightning/lightning_serial_test.go
Issue Number: close #43684
fix missing configurable keyspace name
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix missing configurable keyspace name

- br/pkg/lightning/backend/kv/base.go
- br/pkg/lightning/backend/kv/sql2kv.go
- executor/importer/kv_encode.go
Issue Number: close #43728
we ignore warnings when encoding rows now, but warnings uses the same memory as parser, since the input
`row []types.Datum` share the same underlying buf, and when doing CastValue, we're using `hack.String`/`hack.Slice`.
when generating error such as `mysql.ErrDataOutOfRange`, the data will be part of the error, causing the buf
unable to release. So we truncate the warnings.
Tests 
- one csv file test, about 1g, each row is about 20k. add a sleep after encode this file, then get a memory profile
before
after
Side effects
Documentation
```release-note
None
```
> lightning: fix oom when mem/cpu ratio is low

- ddl/resourcegrouptest/BUILD.bazel
- ddl/resourcegrouptest/resource_group_test.go
- planner/optimize.go
- session/session.go
Issue Number: close #43736, Ref #38825
Tests 
```release-note
None
```
> bind: fix global binding hint for resource groups

- Makefile
cherry-pick of #43681
Issue Number: close #43683 ref #42188 
Tests 
It works after `make enterprise-server`
```
./bin/tidb-server -V
Release Version: v7.2.0-alpha-125-g5c31e1694-dirty
Edition: Enterprise
Git Commit Hash: 5c31e169446f34e398dc63f34f4208d67b4186c6
Git Branch: master
UTC Build Time: 2023-05-10 07:05:02
GoVersion: go1.20.2
TiKV Min Version: 6.2.0-alpha
```
Side effects
Documentation
```release-note
None
```
> *: set `TIDB_EDITION` when build enterprise tidb (#43681)

- planner/core/issuetest/BUILD.bazel
- planner/core/issuetest/planner_issue_test.go
- planner/core/rule_predicate_push_down.go
Issue Number: close #43645
The predicate push-down might change the correlated status of the CTE. Our current implementation will cause the wrong result.
We disable that case's pushing down first.
I will support it later.
Tests 
Side effects
Documentation
```release-note
Fix the issue that pushing the correlated filter into CTE might cause the wrong result.
```
> planner: fix correctness of the correlated predicate push down for cte | tidb-test=pr/2128

- br/pkg/restore/client.go
- br/pkg/restore/client_test.go
Issue Number: close #43739 
no block between `PUT` and `DELETE` files restore.
add the block
Tests 
Side effects
Documentation
```release-note
None
```
> br: add waitgroup for delete type files

- .github/dependabot.yml
- DEPS.bzl
- go.mod
- go.sum
Tests 
Side effects
Documentation
```release-note
None
```
> *: update dependabot

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/config/BUILD.bazel
- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/importer/import.go
- br/tests/lightning_csv/config-pause-global.toml
- br/tests/lightning_csv/run.sh
- executor/importer/table_import.go
Issue Number: close #43657
- add option `pause-pd-scheduler-scope` to control the scope when pause scheduler, default=table
Tests 
- manually change CanPauseSchedulerByKeyRange to return false and set pause-pd-scheduler-scope=table, it should fail
Side effects
Documentation
```release-note
add option `pause-pd-scheduler-scope` to control the scope when pause scheduler
```
> lightning: add option to control pause scheduler scope

- executor/builder.go
- executor/test/partitiontest/BUILD.bazel
- executor/test/partitiontest/partition_test.go
Issue Number: close #43686
When doing pruning for inner join lookup it propagated errors of not found partition instead of ignoring it (since there are no matching values).
Tests 
Side effects
Documentation
```release-note
None
```
> executor: ignore non-found partitions in inner joins

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
Issue Number: close #43768
please see the linked issue
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix data lost when partial write and server is busy

- br/pkg/conn/conn.go
- ddl/ddl_tiflash_api.go
- infoschema/cluster.go
- privilege/privileges/ldap/ldap_common.go
- store/copr/coprocessor.go
- util/processinfo.go
Issue Number: close #43286
Tests 
```
mysql> select * from information_schema.cluster_processlist;
+----------------------------------------------+---------------------+------+----------------------------------------------+------+---------+------+------------+------------------------------------------------------+------------------------------------------------------------------+------+------+----------------------------------------+----------------+
| INSTANCE                                     | ID                  | USER | HOST                                         | DB   | COMMAND | TIME | STATE      | INFO                                                 | DIGEST                                                           | MEM  | DISK | TxnStart …
```
> *: fix ipv6 host address

- br/tests/_utils/check_contains
- br/tests/_utils/check_not_contains
- br/tests/lightning_csv/run.sh
- br/tests/lightning_error_summary/run.sh
- br/tests/lightning_fail_fast/run.sh
Issue Number: ref #43820
```
-e      Exit immediately if a pipeline (which may consist of a single simple command), a list, or a compound command (see SHELL GRAMMAR above), exits with a non-zero status.  The shell
does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test following the if or elif reserved words, part
of any command executed in a && or || list except the command following the final && or ||, any command in a pipeline but the last, or if the command's return value is being
inverted with !.
```
> **The shell does not exit if ...... the command's return value is being inverted with !**
that means check `not contains` by `! grep` directly will not work
Tests 
Side effects
Documentation …
> lightning: fix grep check in integration test

- ddl/table_test.go
Issue Number: close #43825
It is possible that the last DDL job does not exit in time.
Only check rename-table jobs in `OnJobUpdated()`.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: stabilize TestRenameTableIntermediateState

- executor/builder.go
- executor/partition_table_test.go
This is a manual cherry-pick of #43763
Issue Number: close #43686
When doing pruning for inner join lookup it propagated errors of not found partition instead of ignoring it (since there are no matching values).
Tests 
Side effects
Documentation
```release-note
None
```
> executor: ignore non-found partitions in inner joins (#43763)

- ddl/backfilling_scheduler.go
The backfill total counter has been updated in 
https://github.com/pingcap/tidb/blob/0f7bb0a1122eea2ca0fbcf9c41b5591aeba9582f/ddl/index.go#L1649
Let's remove the incorrect counting here.
After this PR:
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: remove redundant backfill metric counting

- cmd/explaintest/r/cte.result
- cmd/explaintest/t/cte.test
- planner/core/integration_test.go
- planner/core/logical_plan_builder.go
- planner/core/rule_predicate_push_down.go
cherry-pick #43759 and #38214
Tests 
Side effects
Documentation
```release-note
None
```
> planner: cherry-pick two commits for CTE with APPLY

- br/pkg/task/backup.go
- br/pkg/task/backup_ebs.go
- br/pkg/task/common.go
Issue Number: ref https://github.com/pingcap/tidb/issues/43559
After https://github.com/pingcap/tidb/pull/43562, we get the ability of pausing GC and schedulers in an external pod. But the backup command still tries to pause them, which is not really effective and will bring the ABA problem. (Say, some of BRs think the state of "no scheduler exists" is the original state of the cluster.)
This PR added a new hidden flag `--operator-paused-gc-and-scheduler`. Once it set, the client will no longer try to pause scheduler (Should / Is it possible to further check whether they are really paused?) and start backup directly after the pending split done.
Tests 
Run command:
```bash
br_ebs_backup_mocking_wait_snapshot_duration=800s ~/br-operator backup full --type aws-ebs …
```
> br/backup_ebs: added flag `operator-paused-gc-and-scheduler`.

- planner/core/integration_partition_test.go
- planner/core/rule_partition_processor.go
Issue Number: close #42323
Tests 
Side effects
Documentation
```release-note
None
```
> partition: fix select statement error on table which partitioned by column with floor func

- planner/BUILD.bazel
- planner/core/plan_cache.go
- planner/core/plan_cache_param.go
- planner/core/plan_cache_test.go
- planner/optimize.go
Issue Number: close #43667
Problem Summary: planner: fix Jepsen fail caused by non-prep plan cache
planner: fix Jepsen fail caused by non-prep plan cache
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix Jepsen fail caused by non-prep plan cache

- expression/constant_propagation.go
- planner/core/plan_cache_test.go
Issue Number: close #43852
Problem Summary: planner: skip plan-cache if some predicates are converted to True/False when constant propagation
planner: skip plan-cache if some predicates are converted to True/False when constant propagation
Tests 
Side effects
Documentation
```release-note
None
```
> planner: skip plan-cache if some predicates are converted to True/False when constant propagation

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/restore/split_test.go
Issue Number: close #43682 
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: new regionJob from needRescan has zero retry counter

- sessionctx/variable/tidb_vars.go
Problem Summary: planner: enable non-prep plan cache by default on Master
planner: enable non-prep plan cache by default on Master
Tests 
Side effects
Documentation
```release-note
None
```
> planner: enable non-prep plan cache by default on Master

- ddl/ddl.go
- server/conn.go
- server/server.go
- sessionctx/variable/session.go
Issue Number: close https://github.com/pingcap/tidb/issues/43854
1. This [issue](https://github.com/pingcap/tidb/pull/35803) support canceling DDL statements with KILL（related PR:https://github.com/pingcap/tidb/pull/35923）.
---**The original PR that supported this didn't seem to say cancel DDL on "kill TiDB"**
2. But after these PRs, when we do `kill TiDB`, this TiDB's DDLs **may be** canceled(In some cases it can't be cancelled).
--- **Cancel DDL is not fully supported in the case of "kill TiDB".**
3. This [issue](https://github.com/pingcap/tidb/issues/39751) need do "Pause user DDL when upgrading TiDB", but these DDLs may be canceled by `kill TiDB`. So we consider `kill TiDB` can not cancel DDL.
4. We'll deal with this in detail when we distinguish between asynchronous …
> *: Make DDL unaffected by killing TiDB instance

- privilege/privileges/ldap/ldap_common.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #43822
1. TiDB uses variable `root_pw`, which is different from `root_pwd`.
2. TiDB doesn't support the server which doesn't allow anonymous bind.
1. Rename the variables to `root_pwd`.
2. Initialize the connection with binding to the `root_dn` and `root_pwd`.
The only concern is that the the ACL configuration for anonymous user and `root` could be different.
Tests 
I manually tested this patch with okta ldap service, which doesn't support anonymous binding.
Copied from https://github.com/pingcap/tidb/issues/43822, I also attached the "Alternatives" here:
I have checked the behavior on two different implementations:
1. Percona server, as shown in its code, will also use root_dn and root_pwd to initialize the connection.
2. MySQL server doesn't detect …
> ldap: modify variable name and initialize connection with root_dn and root_pwd

- build/nogo_config.json
- timer/api/BUILD.bazel
- timer/api/client.go
- timer/api/client_test.go
- timer/api/hook.go
- timer/api/schedule_policy_test.go
- timer/api/store.go
- timer/api/store_test.go
- timer/api/timer.go
Issue Number: close #43836
- Add a new package `timer` for timer framework
- Add some new interfaces for user
- Introduce the model `TimerRecord` to present the meta of the timer
- Introduce `TimerClient` to provide some operations of timer for user
- Introduce `Hook` for the users to custom actions when timer event is triggered
Tests 
Side effects
Documentation
```release-note
None
```
> timer: add user interfaces for timer framework

- br/pkg/lightning/BUILD.bazel
- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/lightning/backend/local/duplicate.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/localhelper.go
- br/pkg/lightning/backend/local/localhelper_test.go
- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/lightning.go
- br/pkg/restore/split/split.go
- br/pkg/restore/split/split_test.go
- br/pkg/restore/split_test.go
- br/pkg/restore/util_test.go
- br/pkg/utils/backoff.go
- executor/importer/table_import.go
- tests/realtikvtest/loaddatatest/load_data_test.go
Issue Number: close #43510
- This PR introduce two config, `tikv-importer.region-split-batch-size` and `tikv-importer.region-split-concurrency`.
- `tikv-importer.region-split-batch-size` controls the maximum region number in one round of region split+scatter. The default value is 4096
- `tikv-importer.region-split-concurrency` controls the number of workers that handle the region split/scatter job., The default value is number of CPU cores.
- This PR intrudoce a hidden config `region-check-backoff-limit`. The default value is 1800 and its max backoff interval is 2s, so lightning will wait about 3600s.
- This PR changed some retry strategy. When some of retry jobs made progress, we won't increase the retry counter so won't exit retry due to reach retry counter limit.
Tests …
> lightning: improve region actions for huge region number

- ddl/job_table.go
- owner/BUILD.bazel
- owner/manager.go
Issue Number: close https://github.com/pingcap/tidb/issues/43850
There a already expired additional owner,  resulting in no normal DDL owner in the cluster..
```
ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 lease timetolive 2231882562b6cb5f
{"level":"warn","ts":"2023-05-17T00:40:56.476894+0800","caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCDCTL_API=3"}
lease 2231882562b6cb5f already expired
```
* Set the value to etcd with lease.
* Clean up the log(get global state and global state change) when the TiDB is notOwner.
Tests 
1. Using tiup start 2 TiDBs(master brach) cluster.
2. Kill a TiDB and start(before start do `update mysql.tidb set VARIABLE_VALUE = 143 WHERE VARIABLE_NAME="tidb_server_version";`) it with …
> ddl, owner: set owner op with lease

- extension/event_listener_test.go
- server/conn.go
- server/extension.go
Issue Number: close #43918
Tests 
Side effects
Documentation
```release-note
extension: fix panic when use db command return error
```
> extension: fix panic when use db command return error

- ddl/index_change_test.go
Issue Number: close #43942
The issue is not significant, but I don't want it to appear on the data race report.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix DATA RACE in the TestIndexChange

- ddl/BUILD.bazel
- ddl/db_test.go
- ddl/index.go
- ddl/index_cop.go
- ddl/ingest/BUILD.bazel
- ddl/ingest/integration_test.go
- ddl/mv_index_test.go
- ddl/rollingback.go
- util/dbterror/ddl_terror.go
Issue Number: close #43814
- Enumerate the retryable errors during adding index, and retry the execution only if necessary.
- Unwrap the error "Cannot decode index value" to improve the MySQL compatibility.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: list the retryable errors for ingest mode | tidb-test=pr/2129

- expression/builtin_cast.go
- expression/integration_test/integration_test.go
- planner/core/rule_aggregation_push_down.go
Issue Number: close https://github.com/pingcap/tidb/issues/43805
Tests 
Side effects
Documentation
```release-note
None
```
> planner, expression: fix wrong fieldtype after aggregationPushDownSolver

- br/pkg/backup/client.go
- br/pkg/checkpoint/backup.go
- br/pkg/checkpoint/checkpoint.go
- br/pkg/checkpoint/checkpoint_test.go
- br/pkg/checkpoint/log_restore.go
- br/pkg/checkpoint/restore.go
- br/pkg/restore/client.go
- br/pkg/task/backup.go
- br/pkg/task/restore.go
- br/pkg/task/stream.go
Issue Number: close #43811 
The checkpoint log has much space used for log restore
Use a new checkpoint file format with smaller space used
Tests 
10.5 MB -> 2.6 MB
Before
```
[INFO] [checkpoint.go:836] ["start to remove checkpoint data"] ["checkpoint task"=/checkpoints/restore-7233306295998094311/441278585472024577.441280055261265922] [remove-count=6] [remove-size=11038833]
```
After
```
[INFO] [checkpoint.go:843] ["start to remove checkpoint data"] ["checkpoint task"=/checkpoints/restore-7233304143091542806/441278585472024577.441280055261265922] [remove-count=6] [remove-size=2753259]
```
Side effects
Documentation …
> br: a new checkpoint file format with smaller space used

- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/job_table.go
- ddl/multi_schema_change_test.go
- ddl/pause_test.go
- ddl/rollingback.go
- errno/errname.go
- errors.toml
- parser/model/ddl.go
- session/bootstrap.go
- session/bootstraptest/BUILD.bazel
- session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close #43897
1. TiDB will try to pause jobs again if restarted during upgrade, need to omit ErrPausedDDLJob
2. Once there is error during Pause/Resume a bunch of jobs, it will fail immediately and return. Which should be continue to next job
3. There are some corner cases that jobs could not be paused during upgrade, which should not become runnable
1. Would not run the jobs that could not be paused during TiDB Upgrade
2. Omit the error of `pause` during TiDB Upgrade in DDL Worker
3. Continue to pause/resume next job even error happened
4. Return `ErrPausedDDLJob` if already `paused`
5. Process the errors returned by  PauseAllJobsBySystem and ResumeAllJobsBySystem during upgrade
Tests 
Side effects
Documentation …
> ddl: better approach to pause or resume ddl jobs during upgrade

- errno/errcode.go
- errno/errname.go
- errors.toml
- executor/executor.go
- executor/simple.go
- expression/builtin_miscellaneous_vec.go
- parser/mysql/errcode.go
- parser/mysql/errname.go
- server/server.go
- testkit/mocksessionmanager.go
- util/dbterror/exeerrors/errors.go
- util/expensivequery/expensivequery.go
- util/processinfo.go
Issue Number: close #43031 
- The query gets killed if it hits the max execution time
- Where we return an error to the client we don't know why the query was killed, so we return a generic error
This PR changes this so that `Killed` gets set to 2 instead of  1 if the query was killed because of the max execution time and then later uses this to send the right error to the client.
1. Why is `Killed` a `uint32` instead of a bool?
2. Is using a `Killed` value other than 0 or 1 safe? Or should we change checks from `==1` to `>0` etc?
3. Is there a better way to communicate the reason something was killed to the goroutine/process that sends the error to the client?
Tests 
Side effects
Documentation …
> executor,util: Correct error for MAX_EXECUTION_TIME | tidb-test=pr/2115

- parser/mysql/const.go
- session/session.go
- session/sessiontest/session_test.go
Issue Number: close #43392
Problem Summary: As issue said, `NO_BACKSLASH_ESCAPES` may cause internal sql parse failed.
Delete `NO_BACKSLASH_ESCAPES` for internal sql mode.
Tests 
Side effects
Documentation
```release-note
None
```
> session: del NO_BACKSLASH_ESCAPES sql mode for internal sql

- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/job_table.go
- ddl/multi_schema_change_test.go
- ddl/pause_test.go
- ddl/rollingback.go
- errno/errname.go
- errors.toml
- parser/model/ddl.go
- session/bootstrap.go
- session/bootstraptest/BUILD.bazel
- session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close #43897
1. TiDB will try to pause jobs again if restarted during upgrade, need to omit ErrPausedDDLJob
2. Once there is error during Pause/Resume a bunch of jobs, it will fail immediately and return. Which should be continue to next job
3. There are some corner cases that jobs could not be paused during upgrade, which should not become runnable
1. Would not run the jobs that could not be paused during TiDB Upgrade
2. Omit the error of `pause` during TiDB Upgrade in DDL Worker
3. Continue to pause/resume next job even error happened
4. Return `ErrPausedDDLJob` if already `paused`
5. Process the errors returned by  PauseAllJobsBySystem and ResumeAllJobsBySystem during upgrade
Tests 
Side effects
Documentation …
> ddl: better approach to integrate with upgrade and to pause or resume ddl job (#43907)

- ddl/syncer/syncer.go
Issue Number: close #44014
Using lease when writing MDL to ETCD may lead to lost MDL info.
Tests 
Side effects
Documentation
```release-note
fix a bug that using lease when writing MDL to ETCD which may lead to DDL blocked
```
> ddl: don't use lease when writing MDL to ETCD

- ddl/ddl_worker.go
- ddl/job_table.go
- session/bootstrap.go
Issue Number: close https://github.com/pingcap/tidb/issues/44017
Tests 
Side effects
Documentation
```release-note
None
```
> *: unify logs when the cluster is upgrading state

- ddl/db_test.go
- ddl/ddl.go
- ddl/pause_test.go
Issue Number: close #44002 
Once try times are exhausted, it should return en error, but now it just return nil as error.
Return error if try too much times during `admin pause/resume/cancel ddl jobs`.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: better error handling during PauseJobs/ResumeJobs/CancelJobs

- br/pkg/aws/ebs.go
- br/pkg/task/backup_ebs.go
- br/pkg/task/restore.go
- br/pkg/task/restore_ebs_meta.go
Issue Number: close #43963 
Currently, ebs snapshot restore command can only ebs volumes to the same az as the original.
1. A new flag `target-az` is introduced to let the user specify a target Availability Zone for restoring EBS volumes.
2. The CreateVolumes method in `br/pkg/aws/ebs.go` is modified to accept a new parameter targetAZ and set the availability zone of the new volume using the targetAZ flag value.
3. The RestoreConfig struct is updated to store the TargetAZ flag value.
4. The ParseFromFlags function is updated to parse the `target-az` flag value.
5. The restore feature including cross-AZ restore capability by using the `target-az` flag is manually tested.
Tests 
EBS snapshot backup a tidb cluster in AZ az1
EBS snapshot restore with the new flag to restore …
> br : a new flag to enable ebs br cross az restore

- ddl/index.go
- ddl/ingest/checkpoint.go
- ddl/job_table.go
- ddl/reorg.go
Issue Number: close #43997
The basic idea of checkpoint is to recover the progress:
```
| add index for partition 1
|  [ local checkpoint ]
| add index for partition 2
|  [ local checkpoint ]
|  [ global checkpoint ]
| ...
| add index for partition k
|  [ local checkpoint ]
| add index for partition k+1
v  (TiDB 1) crash
| (TiDB 2) get DDL owner
| add index for partition 2
| ...
```
Note that we can only begin with partition 2 because the local checkpoint is lost when TiDB 1 crashes.
In order to represent which partition we should begin with, reorg meta is used. The reorg meta contains a tuple: (partition ID or physical table ID, start key, end key). Every time TiDB restarts in the middle state of adding an index, it tries to reset the reorg meta to the state exactly …
> ddl: recover to the correct partition from checkpoint

- br/pkg/checkpoint/checkpoint_test.go
- br/pkg/checkpoint/log_restore.go
- br/pkg/restore/BUILD.bazel
- br/pkg/restore/client.go
- br/pkg/restore/ingestrec/ingest_recorder.go
- br/pkg/restore/ingestrec/ingest_recorder_test.go
- br/pkg/task/stream.go
Issue Number: close #43893 
br checkpoint for log restore is not compatible with repairing ingest index
add the fixed sqls into the checkpoint mode.
Tests 
the first execution
```
GO_FAILPOINTS="github.com/pingcap/tidb/br/pkg/restore/failed-before-create-ingest-index=1*return(false)->return(true)" ./br restore point -s ...
Restore Meta Files <-----------------------------------------------------------------------------------------> 100.00%
Restore KV Files <-------------------------------------------------------------------------------------------> 100.00%
repair ingest index zips2 for table test.pairs7  ... DONE
repair ingest index i2 for table test.pairs7   ABORTED
[2023/05/17 10:06:54.373 +08:00] [INFO] [collector.go:77] ["restore log failed summary"] [error="failed to …
```
> br: add checkpoint for repairing ingest index

- planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- planner/core/find_best_task.go
- planner/core/plan_cost_ver2_test.go
Issue Number: close #44025
Problem Summary: planner: fix incorrect cost when the plan has `IndexLookup->Limit/Agg/TopN`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix incorrect cost when the plan has `IndexLookup->Limit/Agg/TopN`

- build/BUILD.bazel
- build/linter/etcdconfig/BUILD.bazel
- build/linter/etcdconfig/analyzer.go
- build/nogo_config.json
- dumpling/export/util.go
- util/etcd/etcd.go
Issue Number: close #42643
Tests 
```
compilepkg: nogo: errors found by nogo during build-time code analysis:
util/etcd/etcd.go:81:27: missing field AutoSyncInterval (etcdconfig)
```
Side effects
Documentation
```release-note
None
```
> linter: check AutoSyncInterval for etcd config

- ddl/db_test.go
- ddl/ddl_worker.go
Cherry-pick #43867.
```release-note
None
```
> ddl: roll back txn before handling ErrEntryTooLarge (#43867)

- br/pkg/lightning/mydump/BUILD.bazel
- br/pkg/lightning/mydump/parser.go
- build/BUILD.bazel
- build/nogo_config.json
- expression/BUILD.bazel
- expression/builtin_encryption_vec.go
- expression/expression.go
- util/checksum/BUILD.bazel
- util/checksum/checksum.go
- util/zeropool/BUILD.bazel
- util/zeropool/pool.go
- util/zeropool/pool_test.go
Issue Number: close #44042
ref https://github.com/prometheus/prometheus/pull/12189
```
$ go test -run=X -bench=.  -benchmem 
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/util/zeropool
BenchmarkZeropoolPool-8                 68883153                17.39 ns/op            0 B/op          0 allocs/op
BenchmarkSyncPoolValue-8                46020945                26.25 ns/op           24 B/op          1 allocs/op
BenchmarkSyncPoolNewPointer-8           46381591                25.57 ns/op           24 B/op          1 allocs/op
```
```
│     old      │                  new                  │
│  allocs/op   │  allocs/op    vs base                 │
RowBasedFilterAndVectorizedFilter/Vec-int/-8                    4.000 ± ∞ ¹    2.000 ± ∞ ¹        ~ (p=1.000 n=1) ² …
```
> zeropool:  better Pool to improve performance

- ddl/ddl_worker.go
- ddl/job_table.go
- session/bootstrap.go
Issue Number: close https://github.com/pingcap/tidb/issues/44120
* After https://github.com/pingcap/tidb/pull/43907 updating([line](https://github.com/pingcap/tidb/pull/43907/files#diff-dfc42c5764e7e4ff9122a1db728ff1cb0dee56e72dbccefdb211018ccd444c73R980)), the log of `[ddl] run DDL job` in ddl package the level is change from `info` to `debug`. But I think this is bad for ddl related debugging.
* The log of [line189](https://github.com/pingcap/tidb/compare/master...zimulala:zimuxia/log?expand=1#diff-91c692cc214077acc788fcaf2f92fb40d0a6c4aef3e34e3b6ed532677dac9f13R189)  always print when the jobID is small(every time do a filter). 
* Add version144 is set in v7.1.0-rc which version we doesn't support upgrade state. And version145 it is set in master. This change related …
> ddl: update `run DDL job` log back to info level and SupportUpgradeStateVer 

- errno/errname.go
- errors.toml
- executor/simple.go
- executor/test/passwordtest/password_management_test.go
- executor/test/simpletest/BUILD.bazel
- executor/test/simpletest/simple_test.go
- parser/mysql/errname.go
- util/password-validation/password_validation.go
Issue Number: close #44098
Password validation should only take effect for users that authenticate with a password, like `mysql_native_password`, `caching_sha2_password` and `tidb_sm3_password`
Disable password validation for users without clear text password
Tests 
Side effects
Documentation
```release-note
Fix a bug that validates passwords for users with `tidb_auth_token`
```
> executor: disable password validation for `tidb_auth_token` users | tidb-test=pr/2136

- ddl/partition.go
- ddl/placement_policy_test.go
- infoschema/builder.go
Issue Number: close #44116
When dropping/truncating a partition, this PR will:
- reset the table's placement group with the new meta. After that, the dropped partition id not in the table's placement group.
- create a new placement group by dropped partition  id with the old rules to wait for GC to delete it.
Tests 
Side effects
Documentation
```release-note
ddl: fix the placement behavior when drop/truncate partitions
```
> ddl: fix the placement behavior when drop/truncate partitions

- ddl/cancel_test.go
- ddl/ddl.go
Issue Number: close #44143
It doesn't Unmarshal the rawArg to Arg if the job is rollbacking.
Don't update the RawArg since it doesn't change during cancel/pause/resume.
Tests 
Side effects
Documentation
```release-note
fix cancel the rollbacking back may lead to meta data broken
```
> ddl: fix cancel the rollbacking back may lead to meta data broken

- ddl/index.go
- ddl/ingest/BUILD.bazel
- ddl/ingest/backend.go
- ddl/ingest/engine_mgr.go
- tests/realtikvtest/addindextest/integration_test.go
Issue Number: close #44137, close #44044
See https://github.com/pingcap/tidb/issues/44137#issuecomment-1560583438.
If there is no writers in engine, it means the local backend is closed. 
- Reopen the local backend before retrying adding index.
- Skip deleting SST files that belong to a running DDL job.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl/ingest: create new local backend if necessary

- config/config.go
- config/config.toml.example
- config/config_test.go
- executor/test/analyzetest/analyze_test.go
- planner/core/plan_stats_test.go
- statistics/handle/handle_hist_test.go
- statistics/handle/handletest/handle_test.go
- statistics/handle/updatetest/update_test.go
- statistics/integration_test.go
Issue Number: ref #42160
Turn on `lite-init-stats` and `force-init-stats` by default.
Tests 
Side effects
Documentation
```release-note
None
```
> config: turn on lite-init-stats and force-init-stats by default

- executor/builder.go
- executor/partition_table_test.go
- planner/core/find_best_task.go
- tests/realtikvtest/brietest/brie_test.go
- tests/realtikvtest/sessiontest/session_fail_test.go
Issue Number: close #44123 
Problem Summary: The root case is we asked one more column which is `model.ExtraPhysTblID` in indexReq. When `resp.EncodeType = EncodeType_TypeDefault`, it can't handle it correctly.
Tests 
Side effects
Documentation
```release-note
None
```
> executor, planner: fix indexLookUp with static pruning

- statistics/handle/handle.go
- statistics/handle/lru_cache.go
- statistics/handle/statscache.go
Issue Number: ref #34052
Show stats mem usage even if stats mem quota is not set.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: show stats mem usage even if stats mem quota is not set

- br/pkg/task/backup_ebs.go
Issue Number: close #44182 
When `operator-paused-gc-and-scheduler=true` is set for ebs snapshot full backup, PD and GC restore function is not set but is invoked erroneously, and it caused a panic as below.  We need to avoid invoke the restore function when `SkipPauseGCAndScheduler` is turned on.
`I0525 09:38:32.981380       9 backup.go:292]
I0525 09:38:32.981426       9 backup.go:299] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a33831]
goroutine 1 [running]:
[github.com/pingcap/tidb/br/pkg/task.RunBackupEBS](http://github.com/pingcap/tidb/br/pkg/task.RunBackupEBS)({0x6212770, 0xc000101900}, {0x62295a8?, 0x9067330?}, 0xc0001aee00) …
> br: ignore restore pd and gc if SkipPauseGCAndScheduler is on

- ddl/BUILD.bazel
- ddl/ddl.go
- ddl/job_table.go
- ddl/job_table_test.go
- ddl/mock.go
- session/bootstrap.go
Issue Number: close https://github.com/pingcap/tidb/issues/44159
When we into the upgrading state we can do the `CannotPauseDDLJob` jobs.
Tests 
As  https://github.com/pingcap/tidb/issues/44159
deploy a cluster add do large ddl in queueing
upgrade the cluster
**Before this PR**, can't upgrade successfully
**After this PR**, can upgrade successfully
Side effects
Documentation
```release-note
None
```
> *: Fix a bug when have a lot of jobs in upgrading state(#44162)

- ddl/BUILD.bazel
- ddl/job_table.go
- ddl/job_table_test.go
- ddl/mock.go
- session/bootstrap.go
Issue Number: close https://github.com/pingcap/tidb/issues/44159
When we into the upgrading state we can do the `CannotPauseDDLJob` jobs.
Tests 
As  https://github.com/pingcap/tidb/issues/44159
deploy a cluster add do large ddl in queueing
upgrade the cluster
**Before this PR**, can't upgrade successfully
**After this PR**, can upgrade successfully
Side effects
Documentation
```release-note
None
```
> *: Fix a bug when have a lot of jobs in upgrading state 

- executor/BUILD.bazel
- executor/builder.go
- executor/infoschema_reader.go
- executor/infoschema_reader_test.go
- executor/internal/util/BUILD.bazel
- executor/internal/util/util.go
- executor/show.go
- executor/show_stats.go
- executor/test/analyzetest/analyze_test.go
- executor/utils.go
- parser/model/model.go
- planner/core/planbuilder.go
Issue Number: close #44033
Tests 
Side effects
Documentation
```release-note
None
```
> executor: add remain time for showAnalyzeStatus

- build/BUILD.bazel
- build/linter/deferrecover/BUILD.bazel
- build/linter/deferrecover/analyzer.go
- build/linter/etcdconfig/analyzer.go
- build/linter/recover/BUILD.bazel
- build/linter/recover/analyzer.go
- build/linter/util/util.go
- build/nogo_config.json
- ddl/ddl.go
- domain/domain.go
- domain/plan_replayer.go
- resourcemanager/pool/workerpool/workerpool.go
- util/topsql/collector/cpu.go
Issue Number: close #44191
Tests 
```
compilepkg: nogo: errors found by nogo during build-time code analysis:
util/topsql/collector/cpu.go:107:3: Recover() should be directly called by defer (recover)
```
Side effects
Documentation
```release-note
None
```
> linter: Recover() must be directly called by defer

- session/bootstrap.go
- statistics/handle/gc.go
Issue Number: close #44169
1. Add index `idx_create_time(create_time)` for both `mysql.stats_meta_history` and `mysql.stats_history`. With the index, SELECT and DELETE statements of stats history GC would be more efficient.
2. Reserve some bootstrap version slots(147-166) for patches for v7.1.x. Just the same thing as #40182 did.
Tests 
Create a table. Do insert and analyze several times.
```
set @@global.tidb_historical_stats_duration=1s;
```
Observe GCStats SQLs on dashboard.
Side effects
Documentation
```release-note
None
```
> statistics: add idx_create_time for stats_meta_history and stats_history

- ddl/index.go
- ddl/ingest/BUILD.bazel
- ddl/ingest/integration_test.go
- ddl/ingest/mock.go
- ddl/rollingback.go
Issue Number: close https://github.com/pingcap/tidb/issues/44205
Previously, we unregister the add index job in the step of rolling back. However, for indexes in the "NONE" state, there is no rollback step.
Unregister backend after job cancelled.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl/ingest: unregister backend after job cancelled

- ddl/multi_schema_change_test.go
- executor/executor.go
- parser/model/ddl.go
Issue Number: ref #14766
Before this PR: 
```
|     92 | test    | t                    | alter table multi-schema change     | none         |         2 |       88 |         0 | 2023-05-25 15:24:06 | 2023-05-25 15:24:06 | 2023-05-25 15:24:16 | synced |
|     92 | test    | t                    | add index /* subjob */ /* ingest */ | public       |         2 |       88 |         3 | NULL                | NULL                | NULL                | done   |
|     92 | test    | t                    | add index /* subjob */ /* ingest */ | public       |         2 |       88 |         3 | NULL                | NULL                | NULL                | done   |
|     92 | test    | t                    | add index /* subjob */ /* ingest */ | public       |         2 | …
```
> *: show start time of multi-schema change sub-jobs

- br/pkg/task/stream.go
Issue Number: close #44160 
when users start another restore task but don't clean the cluster, the error information make them confused.
add more information in the error when user starts another restore task and doesn't clean the cluster
Tests 
before:
```
Detail BR log in /tmp/br.log.2023-05-25T11.34.52+0800 
Error: databases ddl_test existed in restored cluster, please drop them before execute PiTR: [BR:Restore:ErrDatabasesAlreadyExisted]databases already existed in restored cluster
```
after
```
Detail BR log in /tmp/br.log.2023-05-25T11.37.13+0800 
Error: The current restore task is regarded as a new task, last task info: [start-ts=441462819686449156] [restored-ts=441485796493230080] [skip-snapshot-restore=true]. If you ensure that no changes have been made to the …
```
> br: add more information in the error when user starts another restore task but doesn't clean the cluster

- executor/infoschema_reader.go
- table/tables/tables_test.go
Issue Number: close #43264
Tests 
Side effects
Documentation
```release-note
None
```
> table,executor: fix bug that information_schema.columns shows wrong type var_string instead of varchar for view

- executor/analyze.go
- executor/analyze_worker.go
- executor/infoschema_reader.go
- executor/infoschema_reader_test.go
- server/http_handler_serial_test.go
- statistics/handle/gc.go
- statistics/handle/handle.go
- statistics/handle/historical_stats_handler.go
- statistics/handle/statscache.go
- statistics/handle/update.go
#43297 added `time.Sleep(5 * time.Second)` in test. The root cause is that the table row count cache is not updated in time.
- Move stats row count cache from executor to statistics.
- Invalidate the cache every time the row count of `mysql.stat_meta` is changed.
- Remove the sleep code in `TestGetSchemaStorage`.
Tests 
Side effects
Documentation
```release-note
None
```
> *: move row count cache from package executor to statistics

- planner/core/casetest/integration_test.go
- planner/core/logical_plan_builder.go
- sessionctx/variable/session.go
Issue Number: close #44262
Problem Summary: planner: allow to use dynamic mode to access partitioning tables without global-stats
Tests 
Side effects
Documentation
```release-note
None
```
> planner: allow to use dynamic mode to access partitioning tables without global-stats

- executor/calibrate_resource.go
- executor/ddl.go
- executor/stale_txn_test.go
- expression/helper.go
- planner/core/planbuilder.go
- sessionctx/context.go
- sessionctx/stmtctx/stmtctx.go
- sessiontxn/staleread/BUILD.bazel
- sessiontxn/staleread/processor.go
- sessiontxn/staleread/util.go
Issue Number: close #44215
When calculate as-of expr, calculate `now` expression by cached PD ts, the stale read ts will be more accurate, and there will also be less stale read fallback.
Tests 
I also test with 100ms staleness read:
- resolved-ts.advance-ts-interval: 100ms
nightly:
this PR:
- resolved-ts.advance-ts-interval: 50ms
nightly:
this PR:
Side effects
Documentation
```release-note
Use more accurate stale read ts.
```
> sessiontxn/staleread: more accurate stale ts

- ddl/ddl.go
- ddl/job_table.go
- ddl/pausetest/BUILD.bazel
- ddl/pausetest/pause_test.go
- ddl/reorg.go
- ddl/rollingback.go
Issue Number: close #44217
Problem Summary: fail to resume the paused ddl job
1. Fix bug in notify the reorganization worker after 'admin resume'
2. Better logging to reduce noise
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: Fix the way to notify the reorganization worker after 'admin resume'

- executor/builder.go
- executor/partition_table_test.go
Issue Number: close #44266
Problem Summary: The `indexScan.Table` only contained an index related column `b` which was not enough for `buildIndexReq`. When we `ordered by b, a` with index idx(b), and `a` was a primary key, we could also push the keep order into TiKV parts.
So we need use `indexScan.Schema()` in `buildIndexReq` function.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: found column by idxScan.schema instead of idxScan.Table

- disttask/framework/storage/BUILD.bazel
- disttask/framework/storage/task_table.go
Issue Number: close #44286
rs.Close() may not call if there is any error in DrainRecordSet.
Tests 
Start the tiup cluster, kill and restart PD during the test. Add some logs to check if the session is committed. 
Side effects
Documentation
```release-note
None
```
> disttask: fix a bug that session may not commit before putting into the session pool

- ddl/ddl_worker.go
- ddl/syncer/syncer.go
Cherry-pick #44295  and #44021
1. It may clean the DML info at ETCD while leaving the MDL info at mysql.tidb_mdl_info.
2. Using lease when writing MDL to ETCD may lead to lost MDL info.
Tests 
Run the schrDDL test on a cluster. Kill and restart PD, then check if DDL is blocked.
Side effects
Documentation
```release-note
None
```
> ddl: fix DDL is blocked when pd down during the DDL execution | tidb-test=pr/2145

- domain/infosync/info.go
- domain/infosync/info_test.go
- domain/infosync/tiflash_manager.go
After https://github.com/pingcap/tidb/pull/43087 we use `PostAccelerateScheduleBatch` instead of `PostAccelerateSchedule`. So `PostAccelerateSchedule` is useless.
Tests 
Side effects
Documentation
```release-note
None
```
> domain/infosync: remove `PostAccelerateSchedule` related code

- executor/show.go
Issue Number: close #44327
Problem Summary: planner: fix the unstable test `TestHypoIndexDDL`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix the unstable test `TestHypoIndexDDL`

- executor/executor.go
- executor/test/analyzetest/analyze_test.go
- executor/test/issuetest/executor_issue_test.go
- util/memory/action.go
- util/memory/memstats.go
- util/memory/tracker.go
- util/servermemorylimit/servermemorylimit.go
Issue Number: close #44320 & #40946
For now, `prepare stmt from "analyze table t"; execute stmt; ` is not recognized as an analyze statement and is not managed by global memory quota instead of query memory quota.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: make prepare analyze killed globally instead of query quota

- infoschema/tables.go
- infoschema/test/clustertablestest/tables_test.go
- session/txninfo/txn_info.go
Issue Number: close https://github.com/pingcap/tidb/issues/43104
See the issue for details.
Add lock wait time.
Tests 
Side effects
Documentation
```release-note
None
```
> *: add wait lock time in tidb_trx

- executor/analyzetest/analyze_test.go
- executor/executor.go
- executor/issuetest/executor_issue_test.go
- util/memory/action.go
- util/memory/memstats.go
- util/memory/tracker.go
- util/servermemorylimit/servermemorylimit.go
Issue Number: ref #44320 
For now, prepare stmt from "analyze table t"; execute stmt;  is not recognized as an analyze statement and is not managed by global memory quota instead of query memory quota.
Cherry-pick of https://github.com/pingcap/tidb/pull/44352 
Tests 
Side effects
Documentation
```release-note
None
```
> executor: make prepare analyze killed globally instead of query quota | tidb-test=pr/2145

- planner/core/integration_test.go
- planner/core/stats.go
- planner/core/testdata/integration_suite_out.json
- statistics/column.go
- statistics/handle/bootstrap.go
- statistics/handle/dump.go
- statistics/handle/dump_test.go
- statistics/handle/handle.go
- statistics/handle/handle_hist.go
- statistics/handle/handle_test.go
- statistics/handle/update.go
- statistics/handle/update_test.go
- statistics/histogram.go
- statistics/index.go
- statistics/table.go
This is a manual cherry-pick of #42910 and #43033
Issue Number: ref #42160 close #44404
#42910
1. Introduce IsAnalyzed and StatsCollected to improve encapsulation.
2. Make TableAnalyzed more precise.
3. Make (StatsLoadedStatus).IsLoadNeeded more precise.
4. Make (*Table).GetColRowCount neat.
#43033
Remove statistics.Column.Count.
Before the PR, in order to maintain statistics.Column.Count, we need to read mysql.stats_top_n and mysql.stats_buckets for each column when init stats, which is time-consuming. On the other hand, the usage of statistics.Column.Count is limited. We modify (*DataSource).getColumnNDV to get rid of statistics.Column.Count.
Tests 
Side effects
Documentation …
> statistics: refine index/column stats methods and remove statistics.Column.Count 

- executor/builder.go
- executor/test/partitiontest/partition_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/43686
https://github.com/pingcap/tidb/pull/43763 This PR has missed a case where the index join has a table range scan as its probe side, the pk resolution should also consider the locate partition error.
Tests 
Side effects
Documentation
```release-note
partition: fix index join probe side will locate partition error when it's a table range scan
```
> partition: fix index join probe side will locate partition error when it's a table range scan

- planner/core/rule_join_reorder.go
- planner/core/rule_join_reorder_greedy.go
- planner/core/rule_join_reorder_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/44314
As mentioned in the last comment on the issue
Reason: outer join's other condition influence is quite different from inner join's other condition, the latter one functions as a simple filter, just integrated with inner join. The former functions as a simple filter but also decides whether the outer join is matched or not, consequently deciding whether appending an additional null (which means this row itself is not pruned in the final result)
So when enumerating join order when encountering inner join combined with outer join, those original other conditions bonded with an outer join, just let it be; those additional remained other conditions shouldn't be put down into it, adding additional selection above …
> planner: fix join reorder will append remained other condition to an outer join

- br/pkg/lightning/backend/local/duplicate.go
- ddl/ingest/backend.go
- tests/realtikvtest/addindextest/BUILD.bazel
- tests/realtikvtest/addindextest/integration_test.go
Issue Number: close #44439
https://github.com/pingcap/tidb/pull/36108 refactors and adds duplicate task building support for partitions. However, one of the field has been missed.
As a result, it takes index keys as row keys, and "invalid key" error is reported:
https://github.com/pingcap/tidb/blob/21934de769686ffcf2397e35eb4f426072756bc2/br/pkg/lightning/backend/local/duplicate.go#LL819C14-L819C14
Add back the missing field `indexInfo`.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning/backend/local: fix `buildIndexDupTasks`

- br/pkg/gluetidb/glue.go
- br/pkg/streamhelper/daemon/owner_daemon_test.go
- ddl/ddl.go
- ddl/util/BUILD.bazel
- ddl/util/mock.go
- domain/domain.go
- owner/BUILD.bazel
- owner/mock.go
Issue Number: ref #41495
At present, it is not easy to mock the distributed environment in unit tests. The correctness of this feature depends heavily on the integration test in real clusters. As a result, a bugfix with little changes require a whole real cluster to verify, which is quite inefficient.
This PR is the first step to mock distributed environment in unit tests. First of all, we mock the leader campaign in the owner manager used for tests.
Tests 
Side effects
Documentation
```release-note
None
```
> *: support mock campaign leader in owner manager

- build/BUILD.bazel
- build/nogo_config.json
- executor/adapter.go
- expression/builtin_string.go
- expression/builtin_string_vec.go
- expression/builtin_time.go
- infoschema/metrics_schema.go
- parser/ast/expressions.go
- parser/format/format.go
- store/copr/coprocessor.go
- util/dbutil/common.go
- util/plancodec/codec.go
- util/sqlexec/utils.go
- util/stringutil/string_util.go
- util/util.go
Tests 
Side effects
Documentation
```release-note
None
```
> linter: enable qf1004

- planner/core/resolve_indices.go
- planner/core/runtime_filter_generator.go
The column of table scan needs to be resolved, otherwise its index is wrong. If the index is wrong, the target column of the runtime filter will also be wrong, and finally the runtime filter will be hung on the wrong target column. Lead to wrong results.
Issue Number: close #44450
Tests 
Side effects
Documentation
```release-note
None
```
> planner, runtimefilter: resolve column index for table scan

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/region_job.go
- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/tests/lightning_write_batch/run.sh
- executor/importer/table_import.go
Issue Number: ref #43853
- deprecate `send-kv-pairs`, user can still set it, but it will take no effect
Tests 
Side effects
Documentation
```release-note
deprecate `send-kv-pairs`, user can still set it, but it will take no effect
```
> lightning: deprecate send-kv-pairs

- DEPS.bzl
- executor/test/showtest/show_test.go
- expression/builtin.go
- expression/builtin_grouping.go
- expression/builtin_grouping_test.go
- go.mod
- go.sum
- parser/ast/functions.go
Issue Number: close https://github.com/pingcap/tidb/issues/44437
related tiflash issue : https://github.com/pingcap/tiflash/issues/7590
related tipb pr: https://github.com/pingcap/tipb/pull/308
add one more dimension for grouping marks maintenance.
ideas come from MySQL's support for grouping(a,b,c,...) with maximum of 64 parameters.
```
mysql> select grouping(a,b), grouping(a), grouping(b) from t group by a, b with rollup;
+---------------+-------------+-------------+
| grouping(a,b) | grouping(a) | grouping(b) |
+---------------+-------------+-------------+
|             0 |           0 |           0 |
|             1 |           0 |           1 |
|             0 |           0 |           0 |
|             1 |           0 |           1 |
|             3 |           1 | …
```
> expression: refactor grouping function computation and update related tipb

- session/session.go
Issue Number: close https://github.com/pingcap/tidb/issues/43829
```
processInfo := s.ShowProcess()
txnInfo.ConnectionID = processInfo.ID   // panic is this line.
```
* Check if the `processInfo` is nil.
* Delete the duplicate logic of getting `processInfoID`.
Tests 
Hard to test. In UT we use the `MockSessionManager`, so can't to test it.
Side effects
Documentation
```release-note
None
```
> session, ddl: fix the nil point in `TxnInfo`

- statistics/handle/update.go
Issue Number: close #44502
We don't need to `h.mu.Lock` when creating `NewSessionStatsCollector` or `NewSessionIndexUsageCollector`.
Tests 
Use `time.Sleep` to simulate slow internal sql in `dumpTableStatCountToKV`. When `dumpTableStatCountToKV` is holding `h.mu`, MySQL client can still establish connection with TiDB server. 
Side effects
Documentation
```release-note
None
```
> statistics: remove h.mu.Lock when creating NewSessionStatsCollector

- executor/adapter.go
- executor/cte_test.go
- executor/executor_test.go
- session/session.go
Issue Number: close #44477
Close record set for select stmt and insert/update stmt is in different code path.
Miss calling `resetCTEStorage` for insert/update stmt, whose recordSet is nil.
1. call `resetCTEStorage()` in handleNoDelay(), this will cover insert/update.. DML stmt.
2. call `resetCTEStorage() in `(a *ExecStmt) CloseRecordSet`, this will cover select stmt. Also for prepare/execute/plan cache/select for update.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix cte miss cleaning spilled-disk file

- br/pkg/lightning/backend/kv/sql2kv.go
- br/pkg/lightning/importer/dup_detect.go
- util/extsort/BUILD.bazel
- util/extsort/disk_sorter.go
- util/extsort/disk_sorter_test.go
- util/extsort/external_sorter.go
- util/extsort/external_sorter_test.go
* Refactor `DiskSorter` to improve performance.
* Remove the dependency on `pebble.DB`.
In the test, it takes 18 minutes to sort 400G data on a 32vCPU, 64G RAM machine.
Tests 
Side effects
Documentation
```release-note
None
```
> util/extsort: parallelize DiskSorter.Sort

- br/pkg/gluetidb/glue.go
Issue Number: close #44496, close #44490
https://github.com/pingcap/tidb/pull/44338 add a goroutine to detect exit signal for `UpdateTableStatsLoop`. It breaks the test `TestIsOnline` because it runs `UpdateTableStatsLoop` twice. #44338 removes the loop from glue, resulting in failures of BR's integration tests.
Check if the domain exists and run `UpdateTableStatsLoop` only if necessary.
Tests 
Side effects
Documentation
```release-note
None
```
> br: run `UpdateTableStatsLoop` when domain is not bootstrapped

- infoschema/test/clustertablestest/cluster_tables_test.go
Issue Number: ref #39199
Problem Summary: planner: add more test cases for quick binding
planner: add more test cases for quick binding
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for quick binding

- executor/test/writetest/write_test.go
- executor/write.go
Issue Number: close #44565
Problem Summary: We didn't set `handleChanged` properly when a on-update-now column gets updated automatically and it's also a pk column, which leads to #44565 .
Set `handleChanged` properly in that case.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: set handle changed when col gets auto-updated

- errno/errcode.go
- errno/errname.go
- errors.toml
- expression/column.go
- expression/constant.go
- expression/expression.go
- expression/grouping_sets.go
- expression/grouping_sets_test.go
- expression/scalar_function.go
- expression/util_test.go
- planner/core/casetest/enforce_mpp_test.go
- planner/core/casetest/testdata/enforce_mpp_suite_in.json
- planner/core/casetest/testdata/enforce_mpp_suite_out.json
- planner/core/errors.go
- planner/core/exhaust_physical_plans.go
- planner/core/explain.go
- planner/core/expression_rewriter.go
- planner/core/logical_plan_builder.go
- planner/core/logical_plans.go
- planner/core/logical_plans_test.go
- planner/core/physical_plans.go
- planner/core/resolve_indices.go
- planner/core/task.go
Issue Number: close https://github.com/pingcap/tidb/issues/44487
https://github.com/pingcap/tidb/pull/44216  logical expand support
https://github.com/pingcap/tidb/pull/44436  grouping function refactor
Now, after the above two PR is merged, now we can support transforming a ast rollup syntax to a Expand logical plan.
There is something important that needs to be done before we step into the next physical plan generation --- that's rewriting.
* grouping function needs to be rewritten. what the user typed in the SQL layer is the raw definition of the grouping function which receives multi-raw columns ref as its parameters with a maximum number of up to 64. While in its runtime, what she only considered is the gid(uint64) column, getting the gid uint64 value from every row …
> planner: support grouping function/col/expression rewriting and physical plan exhaustion for rollup expand OP

- ddl/db_change_test.go
- executor/builder.go
- executor/insert_common.go
- parser/ast/dml.go
- parser/parser.y
- planner/core/common_plans.go
- planner/core/planbuilder.go
- planner/core/resolve_indices.go
- util/parser/ast.go
Issue Number: close #44464
Problem Summary: https://github.com/mysql/mysql-server/blob/ea7087d885006918ad54458e7aad215b1650312c/sql/sql_insert.h#L241-L250
Mysql treated `INSERT .. SET x=y` and `INSERT .. (x) VALUES (y)` identically. Why do we bother two implementations for them?
1. Replace `Setlist []assignment` to `Setlist bool` in ast. And remove them in plan and executor.
2. It is unified into `insert.Columns` and `insert.Lists`.
Tests 
Side effects
Documentation
```release-note
None
```
> *: simplify insert into set

- disttask/framework/storage/task_table.go
- planner/core/expression_rewriter.go
- sessionctx/variable/BUILD.bazel
- sessionctx/variable/sysvar.go
- sessionctx/variable/sysvar_test.go
- sessionctx/variable/variable.go
- sessionctx/variable/variable_test.go
Issue Number: close #44574
Problem Summary: For mysql, the return type of `last_insert_id` is `LONGLONG` with `UNSIGNED`, `BINARY` and `NUM` three flags. Also the return type of bool session value is `LONGLONG` with `BINARY` and `NUM` flasgs. Just change the behavior closer to MySQL.
```
mysql> select @@last_insert_id;
Field   1:  `@@last_insert_id`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     21
Max_length: 1
Decimals:   0
Flags:      UNSIGNED BINARY NUM
+------------------+
| @@last_insert_id |
+------------------+
|                0 |
+------------------+
1 row in set (0.01 sec)
mysql> select @@super_read_only;
Field   1:  `@@super_read_only`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type: …
```
> sessionctx: make session_vars' type closer to MySQL

- ddl/table.go
- infoschema/BUILD.bazel
- infoschema/builder.go
- infoschema/infoschema_test.go
Issue Number: close #43714
Reproducible step:
```sql
create table test.t1 (id int primary key,a text);
insert test.t1 values(1,'334'),(4,'3443435'),(5,'fdf43t536653');
rename table test.t1 to mysql.t1;
SELECT * FROM information_schema.TABLES WHERE (TABLE_SCHEMA = 'mysql') AND (TABLE_NAME = 't1');
```
#43341 changes the behavior of `RENAME TABLE`: it takes two schema versions to complete. However, `applyDiff()` doesn't handle two `SchemaDiff`s properly. The same table is created twice in `infoschema`, causing the phantom described in #43714.
During applying schema diff, we check if the table already exists before creating a new table. Thus, we can skip the second creation.
Other alternative fixes include
- Drop the table first and then create a new table(like what `CREATE …
> infoschema: update raw args to make it drop correct table in `RENAME TABLE`

- server/conn_stmt_test.go
- session/session.go
Issue Number: close https://github.com/pingcap/tidb/issues/44612
Tests 
Side effects
Documentation
```release-note
None
```
> session: fix the memory tracker leak in prepare binary protocol

- store/copr/batch_coprocessor.go
Issue Number: close #44622
sort `keyRanges` when retry batch cop
Tests 
Side effects
Documentation
```release-note
None
```
> store: key ranges should be sorted in batch cop retry

- DEPS.bzl
- tools/check/check-bazel-prepare.sh
Issue Number: close #44661
This PR adds some more simple commands to check-bazel-prepare.sh to output the expected changes to be made after CI check bazel failed.
Not sure if the checksum diff makes any sense. I kept them anyway. Btw the previous `diff` command exits immediately if there are any diff (since there's a `set -e` before). I added `|| true` to avoid this behavior, though it doesn't make anything different for now.
Tests 
Side effects
Documentation
```release-note
None
```
> *: Show required changes by git diff when CI check bazel files failed

- disttask/framework/framework_test.go
- testkit/mockstore.go
Since `NewDistExecutionTestContext` takes the argument `testing.TB`, we can assert the error is not null instead of returning it to the caller.
- Refine the function signature of `DistExecutionTestContext`.
Tests 
Side effects
Documentation
```release-note
None
```
> test: refine func signature of distributed execution test context

- Makefile
- on timeout, bazel won't print log sometimes, so we use --test_output=all to print log always
Tests 
Side effects
Documentation
```release-note
None
```
> makefile: always print log for importintotest

- executor/importer/BUILD.bazel
- executor/importer/job.go
- executor/importer/job_test.go
Issue Number: ref #42930
- check `isNull` before get it, else we might got data of prev row
Tests 
Side effects
Documentation
```release-note
None
```
> show import: fix show import might read data from prev line

- expression/expression.go
- planner/core/memtable_predicate_extractor.go
- planner/core/memtable_predicate_extractor_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/39605, cherry-pick from https://github.com/pingcap/tidb/pull/40262
Predicates are not pushed down to memory tables in the prepared mode because the author avoids doing that intentionally. I'm not sure why but it should work.
Get the value from constant when it uses prepared mode. Note that it still skips evaluating when DeferredExpr is not nil.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: support pushing down predicates to memory tables in prepared mode (#40262) | tidb-test=pr/2145

- ddl/scheduler.go
- disttask/example/proto.go
- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/framework_test.go
- disttask/framework/handle/handle.go
- disttask/framework/proto/task.go
- disttask/framework/scheduler/interface_mock.go
- disttask/framework/scheduler/scheduler.go
- disttask/importinto/BUILD.bazel
- disttask/importinto/dispatcher.go
- disttask/importinto/job.go
- disttask/importinto/proto.go
- disttask/importinto/scheduler.go
- disttask/importinto/subtask_executor.go
- disttask/importinto/wrapper.go
- executor/import_into.go
- executor/import_into_test.go
- executor/importer/import.go
- executor/importer/import_test.go
- executor/importer/job.go
- executor/importer/table_import.go
- tests/realtikvtest/importintotest/BUILD.bazel
- tests/realtikvtest/importintotest/import_into_test.go
- tests/realtikvtest/importintotest/job_test.go
- tests/realtikvtest/importintotest/util_test.go
- unify and fix log, avoid exposing meta info in log
- redact meta after task end(success or err)
- cancel job on kill event
- change default `thread` param to `0.5*cpuCount`
- add some missed ut
Tests 
- add some wait before start sorting, start import, kill it in another terminal, the job should be cancelled, check task status too, should be reverted
Side effects
Documentation
```release-note
None
```
> import into: redact task meta after import & cancel on kill

- metrics/grafana/tidb_resource_control.json
- metrics/server.go
- metrics/session.go
- server/conn.go
- session/session.go
Issue Number: Ref #43691 
Add max query duration per resource group metrics
Tests 
Side effects
Documentation
```release-note
None
```
> metrics: add max query duration per resource group metrics

- server/driver_tidb.go
- sessionctx/sessionstates/BUILD.bazel
- sessionctx/sessionstates/session_states.go
- sessionctx/sessionstates/session_states_test.go
- sessionctx/variable/session.go
Issue Number: close #44738
Hypo indexes and hypo tiflash replicas are added in #43607 and #44575 but are not encoded into session states, so they won't be migrated when the session is migrated.
Encode `HypoIndexes` and `HypoTiFlashReplicas` into `SessionStates`.
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: encode hypo indexes and tiflash replicas into session states

- disttask/importinto/scheduler.go
- executor/importer/import.go
- executor/importer/import_test.go
- change max pool size to num-cpu, so import be able to use all cpu resource, previously it's 10 independently on TiDB cpu count
Tests 
- after change cfg, import is 8(8c on local mac)
Side effects
Documentation
```release-note
None
```
> import into: change max pool size to num-cpu

- br/pkg/checksum/executor.go
- disttask/importinto/dispatcher.go
- disttask/importinto/subtask_executor.go
- executor/importer/table_import.go
- tests/realtikvtest/importintotest/import_into_test.go
Issue Number: close #44755
- exit importMode after import step, coprocessor is extremely slow if in importMode
- change default `regionSplitSize` to 192MiB which is the value we set when importing 50T data.
- change the value of `regionSplitSize` to be the same as lightning when doing `unsafeImport`
Tests 
Side effects
Documentation
```release-note
None
```
> import into: exit ImportMode after import step

- parser/parser.y
- parser/parser_test.go
Issue Number: close #44751
In MySQL, `:=` can replace `=` in most of the assignments
https://dev.mysql.com/doc/refman/8.0/en/assignment-operators.html
Tests 
Side effects
Documentation
```release-note
None
```
> parser: support `:=` in assignment on `UPDATE`

- executor/builder.go
- executor/cte.go
- executor/cte_test.go
Issue Number: close #44649
Problem Summary: As issue comment said: https://github.com/pingcap/tidb/issues/44649#issuecomment-1589210758
Before: For different CTE references(a.k.a. `CTEExec`) that use one CTE definition. They will only have one PhysicalPlan of the CTE defition. But we will build CTE definition multiple time for each CTE references.
After: Add `CTEProducer` struct, it corresponsds to CTE defition and will only build once. These different `CTEExec` will read from the same `CTEProducer`.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: add CTEProducer that shared by all CTEExec

- domain/domain.go
- tidb-server/main.go
Issue Number: close #44776
The change move the ResourceControlInterceptor from main into domain to avoid data race. In the previous implementation, `SetResourceControlInterceptor` is run after dom is inited, so it's possible that session variable(`tidb_enable_resource_control`) initialization runs at the same time with `SetResourceControlInterceptor`.
Tests 
Side effects
Documentation
```release-note
None
```
> test: fix data race in resouce control interceptor initialization

- ddl/cancel_test.go
- ddl/db_partition_test.go
- ddl/ddl_api.go
- ddl/ddl_worker.go
- ddl/partition.go
- ddl/partition_test.go
- ddl/rollingback.go
- parser/model/ddl.go
- parser/model/model.go
- table/tables/partition.go
Issue Number: close #42435
add DeleteOnly and DeleteReorg for truncate partition ddl, so that global index can be handled correctly.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix truncate partition for global index

- br/pkg/backup/client.go
- ddl/db_integration_test.go
- executor/show.go
Issue Number: close #44716, ref #38442
https://github.com/pingcap/tidb/pull/39041 use separate allocator for row id and auto id.
That is some kind of  compatibility-break, although it handle the backword-compatibility carefully in the tidb side, I still miss something in the br component.
When br backup a table with auto increment column, it get the row id allocator from the meta key. It should have used the auto increment id allocator after https://github.com/pingcap/tidb/pull/39041
The auto increment meta key of a table with AUTO_ID_CACHE=1 option is a separated one, rather than the row ID meta key.
Tests 
The steps descripted in https://github.com/pingcap/tidb/issues/44716
I do think some integration test is necessory for this commit.
Side effects
Documentation
Please …
> *: fix 'duplicate entry' error when using br to restore AUTO_ID_CACHE=1 tables

- config/config.go
- config/config.toml.example
- domain/domain.go
Issue Number: close #44567
Add config `in-mem-slow-query-topn-num` and `in-mem-slow-query-recent-num`.
Tests 
Start a tidb to check whether `in-mem-slow-query-topn-num` and `in-mem-slow-query-recent-num` are configurable.
Side effects
Documentation
```release-note
None
```
> config: add in-mem-slow-query-topn-num and in-mem-slow-query-recent-num

- br/tests/lightning_duplicate_detection_new/run.sh
manually cherry-pick #44812
---
in https://github.com/pingcap/tidb/pull/44702 we disable the code part of pre-deduplication, but forget to disable the test part 😢 
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: disable pre-deduplication test after we disable the code part (#44812)

- util/execdetails/execdetails.go
- util/execdetails/execdetails_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/44753
MergePercentile will set `p2.dt = nil`, so the next time using the copStats will get an empty result.
It will getting different results(or panic) when calling `CopRuntimeStats.String()`
Tests 
Side effects
Documentation
```release-note
None
```
> util: fix index out of range error when using the copStat twice

- ddl/constraint_test.go
- ddl/ddl_api.go
Issue Number: close #44689 
As issue describe, when use `check(true)` in column check constraint, we receive unexpected error. The reason is when validate the column if exists, we don't consider this situation.
Involve this situation.
Tests 
Side effects
Documentation
```release-note
None
```
> sql: fix error when use true in check constraint expression

- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- planner/core/plan_cacheable_checker_test.go
- sessionctx/variable/session.go
Issue Number: close #44823
Problem Summary: planner: plan cache supports queries with more than 200 parameters 
planner: plan cache supports queries with more than 200 parameters 
Tests 
Side effects
Documentation
```release-note
None
```
> planner: plan cache supports queries with more than 200 parameters 

- expression/builtin_miscellaneous.go
- expression/integration_test/integration_test.go
- session/advisory_locks.go
- session/session.go
- sessionctx/context.go
- util/mock/context.go
Issue Number: close #44493 
TiDB, Session 1
```
sql> select is_used_lock('foo');
+---------------------+
| is_used_lock('foo') |
+---------------------+
|                NULL |
+---------------------+
1 row in set (0.0037 sec)
sql> select get_lock('foo', 10);
+---------------------+
| get_lock('foo', 10) |
+---------------------+
|                   1 |
+---------------------+
1 row in set (0.0032 sec)
sql> select is_used_lock('foo');
+---------------------+
| is_used_lock('foo') |
+---------------------+
|       2199023255557 |
+---------------------+
1 row in set (0.0005 sec)
sql> select connection_id();
+-----------------+
| connection_id() |
+-----------------+
|   2199023255557 |
+-----------------+
1 row in set (0.0004 sec)
```
TiDB, Session 2
```
sql> select …
```
> session,expression: Support IS_USED_LOCK function

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
Issue Number: close #44733
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: fix "context cancel" overwrites the real error

- br/tests/lightning_duplicate_detection_new/run.sh
in https://github.com/pingcap/tidb/pull/44702 we disable the code part of pre-deduplication, but forget to disable the test part 😢 
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: disable pre-deduplication test after we disable the code part

- br/pkg/lightning/backend/local/checksum.go
- br/pkg/lightning/backend/local/checksum_test.go
Issue Number: close #44857
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: unwrap the error before call PD function

- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/engine_test.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
Issue Number: close #44867
- make pebble db a atomic reference to avoid lock when check disk quota
Tests 
Side effects
Documentation
```release-note
fix check disk quota routine block when some engine is importing
```
> lightning: fix check disk quota routine block when some engine is importing

- DEPS.bzl
- Makefile
Tests 
Side effects
Documentation
```release-note
None
```
> *: Prune go_repository from bazel deps

- executor/adapter.go
- executor/metrics/metrics.go
- metrics/grafana/tidb.json
- metrics/metrics.go
- metrics/server.go
Issue Number: close https://github.com/pingcap/tidb/issues/44896
Add MVCC version ratio to slow log metrics.
Tests 
1. create a new cluster
2. run the benchmark test: sysbench oltp_read_write
3. check slow query panel on grafana
Side effects
Documentation
```release-note
None
```
> *: add  MVCC version ratio to slow log metrics

- executor/partition_table_test.go
- executor/test/writetest/write_test.go
- planner/core/indexmerge_path.go
Issue Number: ref #43013 
Tests 
Side effects
Documentation
```release-note
None
```
> planner: ignore index_merge when partial path has global index

- planner/core/find_best_task.go
- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
- planner/core/plan_cache_utils.go
- sessionctx/variable/session.go
Issue Number: close #44830
Problem Summary: planner: plan cache supports Batch/PointGet converted from (primary keys) in ((...), ...)
Tests 
Side effects
Documentation
```release-note
None
```
> planner: plan cache supports Batch/PointGet converted from (primary keys) in ((...), ...)

- planner/core/find_best_task.go
- planner/core/physical_plans.go
- planner/core/task.go
- tests/realtikvtest/txntest/txn_test.go
Issue Number: close #44615
Problem Summary: When a schema has two `ExtraPhysTblID` rows, the first one will return 0 in TiKV side which caused `SelectLock` failed. And in some reasons, the `SelectLock` will ignore this problem, see https://github.com/pingcap/tidb/blob/bd278a05dae96861c94cc9dc69203c26b77fe15b/executor/executor.go#L1281-L1288
So we should avoid it in planner part.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: avoid have two `ExtraPhysTblID` row in same schema

- ddl/tests/resourcegroup/resource_group_test.go
- testkit/result.go
- testkit/testkit.go
Issue Number: close #44883
introduce EventuallyMustQueryAndCheck into `TestKit` to assert query eventually
Tests 
Side effects
Documentation
```release-note
None
```
> tests: fix unstable test in resource group

- ddl/tests/resourcegroup/resource_group_test.go
- executor/infoschema_reader.go
Issue Number: ref #43691
Earlier, I shortened `watch=XXX duration=YY` to `watch=XXX[YY]` in order to reduce the length of the query_limt field, but this may be confused.
The output is now consistent with the SQL syntax.
Tests 
Side effects
Documentation
```release-note
None
```
> I_S: unify the output of query_limit in `resource_groups`

- ddl/ddl_api.go
- parser/ast/ddl.go
- parser/parser.y
- planner/core/plan_test.go
- session/session.go
- sessionctx/sessionstates/session_states_test.go
Issue Number: close #43817
Problem Summary: planner: update the syntax of `drop hypo index`
`drop index {index-name} on {table-name}` --> `drop hypo index {index-name} on {table-name}`
Add the keyword `hypo` into this syntax to make it clearer and safer.
And also, let the optimizer not output `crucial operation log records` for operations on hypo-indexes.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: update the syntax of `drop hypo index`

- server/conn.go
- server/conn_test.go
- server/server.go
- tidb-server/main.go
- util/signal/signal_posix.go
Issue Number: close #44951
Problem Summary: After https://github.com/pingcap/tidb/pull/32111, user need to wait for all connections to be disconnected, or execute a new sql before tidb-server exit. It's not an expected behaviour.
Tests 
Side effects
Documentation
```release-note
Exit tidb-server directly when all connections not in txn
```
> server: exit tidb-server directly when all connections not in txn

- executor/builder.go
- executor/internal/mpp/local_mpp_coordinator.go
- executor/mem_reader.go
- executor/mpp_gather.go
- executor/test/tiflashtest/BUILD.bazel
- executor/test/tiflashtest/tiflash_test.go
- executor/union_scan.go
- kv/mpp.go
- planner/core/fragment.go
Issue Number: close #44705
UnionScan doesn't support MPPGather, so when you force use tiflash in dirty transaction, will give err msg like "union scan integrated with MPPGather is not supported now"
1. support scan mem buf for MPPGather, basically just use `memTableReader` is ok.
Tests 
Side effects
Documentation
```release-note
None
```
> *: support MPPGather for UnionScan

- disttask/framework/storage/task_table.go
- domain/domain.go
Issue Number: close #44983
The distributed task framework should not use `*pools.ResourcePool` directly, otherwise we may encounter issues like #42895.
Use wrapped `*sessionPool` instead.
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: use the correct session pool for dist tasks

- planner/core/find_best_task.go
- tests/realtikvtest/txntest/txn_test.go
Issue Number: close #44984
Problem Summary: If we add `model.ExtraPhysTblID` in DataSource via `SelectLock`, we will not add it again in `AddExtraPhysTblIDColumn`, which will be missing this column in indexScan.Schema()
Tests 
Side effects
Documentation
```release-note
None
```
> planner: add `model.ExtraPhysTblID` into indexScan.Schema()

- executor/BUILD.bazel
- executor/change.go
- executor/show.go
Issue Number: ref https://github.com/pingcap/tidb/issues/42643
In the past code we directly use tidb's global config path to create etcd registry. After this PR we use binlog client's etcd registry to do the following staff. Binlog client will update etcd urls in time.
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```
> binlog: fix show pump/drainer status

- ddl/ddl.go
- ddl/tests/adminpause/pause_cancel_test.go
- ddl/tests/adminpause/pause_resume_test.go
Issue Number: close #45010
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: better approach of logging

- br/pkg/restore/client.go
Issue Number: close #45013 
when do snapshot restore, br should cleanup the table's `TiflashReplica.AvaliableParitionIDs`.
cleanup the table's `TiflashReplica.AvaliableParitionIDs` when create the table.
Tests 
Side effects
Documentation
```release-note
None
```
> br: cleanup `AvaliablePartitionIDs` for tiflash when restore

- ttl/ttlworker/task_manager.go
- ttl/ttlworker/task_manager_integration_test.go
- ttl/ttlworker/task_manager_test.go
Issue Number: close #45022
Tests 
Side effects
Documentation
```release-note
ttl: fix a bug that a TTL task will not be taken by other tidb after failover sometimes
```
> ttl: fix a bug that a TTL task will not be taken by other tidb after failover sometimes

- executor/simple_test.go
- parser/parser.y
- parser/parser_test.go
Issue Number: ref #43180
Make parser support default(without quota, compare to `default`) as resource group name. The use experience should be a litter better because many user don't notice that default is a reserved keywork and need quoted when used as a identifier.
Before:
```
mysql> set resource group default;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 26 near "default"
mysql> set resource group `default`;
Query OK, 0 rows affected (0.01 sec)
```
After:
```
mysql> set resource group default;
Query OK, 0 rows affected (0.01 sec)
mysql> set resource group `default`;
Query OK, 0 rows affected (0.01 sec)
```
Tests 
Side effects
Documentation
Please refer to …
> resource_control: support unquoted default group name

- disttask/importinto/scheduler.go
Issue Number: close #45048
- use parent ctx, not `background`
Tests 
- add a block(a `select` with `ctx.Done` and `time.After`) at end of `ProcessChunk`, add a block in `FlushAllEngines` too, change disk quota = 1. then start import, when it block, cancel the job
- check we can receive context.Cancelled when calling `FlushAllEngines` in disk quota routine
Side effects
Documentation
```release-note
None
```
> import into: fix some subtask keeps running on cancel when triggered disk quota

- table/tables/partition.go
- table/tables/partition_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/44966
If the value is  unsigned type and exceeds max(int64) when locating partition is out of partition range, an error message will be displayed with incorrect values. This issue exist in the scenarios of range and list partition.
Tests 
Side effects
Documentation
```release-note
None
```
> table/tables: fix locate partition error info for unsigned | tidb-test=pr/2162

- executor/builder.go
- executor/cte.go
- expression/column.go
- expression/column_test.go
- planner/core/integration_test.go
Issue Number: close #45033
Problem Summary: Introduced by this pr: https://github.com/pingcap/tidb/pull/44782 . #44782 add `CorrelatedColumn.HashCode`, which will update `Column.hashcode`.
1. In `rule_decorrelate`, extract Column of CorrelatedColumn directly, check https://github.com/pingcap/tidb/blob/master/planner/core/rule_decorrelate.go#L215C44-L215C44 and https://github.com/pingcap/tidb/blob/master/expression/column.go#L177. The hashcode of Column has changed(it's the hash code of CorrelatedColumn instead the original Column)
2. In `rule_eliminate_projection`, planner will try to [replace](https://github.com/pingcap/tidb/blob/master/planner/core/rule_eliminate_projection.go#L99) CondExpr in HashJoin by the output of Projection, here we use hashcode to decide whether to repace or not. …
> *: remove CorrelatedCol.HashCode to avoid potential bug

- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Tests 
Side effects
Documentation
```release-note
None
```
> sessionctx: not use meaningless constants

- sessionctx/variable/sysvar.go
The `DefTiDBEnableExternalTSRead` is unused and the original default value `false` is hard-coded. Let's replace it into `DefTiDBEnableExternalTSRead`
> sessionctx:  use the defined default variables for "tidb_enable_external_ts_read"

- expression/constant_propagation.go
- planner/core/plan_cache_test.go
Issue Number: close #45086
Problem Summary: planner: check whether values are const in constant propagation
planner: check whether values are const in constant propagation
Tests 
Side effects
Documentation
```release-note
None
```
> planner: check whether values are const in constant propagation

- executor/cluster_table_test.go
- extension/event_listener_test.go
- infoschema/test/clustertablestest/tables_test.go
- parser/digester.go
- sessionctx/variable/session_test.go
- util/stmtsummary/v2/tests/table_test.go
Issue Number: close #45104
Ignore the ending semicolon of the SQL when generating the digest.
Tests 
Side effects
Documentation
```release-note
When generating SQL digests, the semicolon at the end of the SQL statement will not affect the generated digest. In other words, whether there is a semicolon or not, the same digest will be generated for an SQL statement.
```
> *: ignore the semicolon at the end of the SQL when generating the SQL digest

- expression/schema.go
- planner/core/integration_test.go
- planner/core/issuetest/BUILD.bazel
- planner/core/issuetest/planner_issue_test.go
- planner/core/logical_plans.go
Issue Number: close #45036
Fix the wrong logic to get extraHandleId. And this part needs further refactoring.
Tests 
Side effects
Documentation
```release-note
None
```
> planner, expression: fix TableFullScan caused by extraHandleId not correctly found

- DEPS.bzl
- go.mod
- go.sum
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #45134
This PR update client-go dependency to include https://github.com/tikv/client-go/pull/866 to fix the issue that BatchResolveLock may leave some primary pessimistic lock uncleared in some rare cases.
The issue is introduced while fixing https://github.com/pingcap/tidb/issues/43243 . For branches that no release with #43243's fix was published, the release note is not needed.
Tests 
Side effects
Documentation
```release-note
Fix the issue that in some rare cases, some primary pessimistic locks may be left uncleared after GC.
```
> txn: Update client-go to fix the issue that GC BatchResolveLcok may miss primary pessimistic locks

- util/chunk/BUILD.bazel
- util/chunk/disk.go
- util/chunk/disk_test.go
- util/chunk/row_container_reader.go
- util/chunk/row_container_test.go
Issue Number: close #45125
The existing reading method of `RowContainer` (`GetChunk(...)`) is not fast enough for dumping a lot of rows from disk (for the `cursorFetch` use case). 
The existing `Iterator4RowContainer` is even slower, as it allocates a new chunk for each row :facepalm:.
This PR is extracted from https://github.com/pingcap/tidb/pull/44730 (with a some refractor).
This PR pipelines the IO and CPU calculation, to make full use of the IO bandwidth. It should also help other features using `rowContainer`, as `GetChunk` is now much faster.
The performance of existing benchmark `BenchmarkListInDisk_GetChunk` increases from `2877471ns/op` to `462864ns/op`
Tests
> util/chunk: optimize `(*ListInDisk).GetChunk` and add a fast row container reader

- server/internal/parse/parse.go
- server/internal/parse/parse_test.go
Issue Number: close #45144 
Add support for time_zone information in the parameters.
Tests 
```release-note
Add support for timezone information in the executing parameter.
```
> server: support timestamp with timezone info in parameter

- br/pkg/lightning/backend/tidb/tidb.go
- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/errormanager/errormanager.go
- br/pkg/lightning/errormanager/errormanager_test.go
- br/pkg/lightning/importer/chunk_process.go
- br/tests/lightning_config_max_error/run.sh
- br/tests/lightning_duplicate_detection_new/run.sh
- After the release, we turn on the pre-deduplication and tests.
- rename the table to `duplicate_records`
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: enable pre-deduplication and rename the recording table 

- executor/test/indexmergereadtest/BUILD.bazel
- executor/test/indexmergereadtest/index_merge_reader_test.go
- session/session.go
- util/processinfo.go
- util/util.go
Issue Number: close https://github.com/pingcap/tidb/issues/45126
Clone some fields from stmtContext to ProcessInfo.
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix data race in ProcessInfo

- executor/analyze.go
- executor/analyze_global_stats.go
Issue Number: ref #43260
Tests 
Side effects
Documentation
```release-note
None
```
> statistic: improve ipv6 for analyze job meta

- parser/mysql/errname.go
- server/conn.go
- server/conn_stmt.go
- server/conn_stmt_test.go
- server/driver.go
- server/driver_tidb.go
- sessionctx/sessionstates/session_states_test.go
- util/memory/action.go
- util/memory/tracker.go
This PR is same with https://github.com/pingcap/tidb/pull/44730. Some bugs of Github makes me fail to update https://github.com/pingcap/tidb/pull/44730, so I have to create a new one :face_exhaling: .
Issue Number: close #43233
1. Use the `rowContainer` to store the rows after execution.
2. Reset the memory/disk tracker when the statement is closed.
TODO:
Tests 
I used the following codes to do some basic tests. The preloaded data is 5M rows `sysbench ./oltp_insert.lua` :
```java
public static void tidbBigSelectTest() throws SQLException, InterruptedException {
// the following are test codes for MySQL
ConnectionImpl conn = (ConnectionImpl) DriverManager.getConnection("jdbc:mysql://127.0.0.1:4000/test?useCursorFetch=true&defaultFetchSize=1000", "root", "");
conn.prepareStatement("set …
```
> server: implement spill disk for cursorFetch result

- executor/mem_reader.go
- executor/union_scan_test.go
Issue Number: close #41827
Problem Summary: `tablecodec.DecodeIndexHandle` will create a `IntHandle` when handle only contained a column which type is year. We could check `IsCommonHanle` when create handle in `IndexMerge` and `IndexLookUp` to avoid this problem.
Tests 
Side effects
Documentation
```release-note
None
```
> executor: void create IntHandle when table is commonHandle

- br/pkg/lightning/config/config.go
Issue Number: ref #44711
- set default value of checksum-via-sql to false, checksum via sql requires SUPER priv, but on cloud we don't have it, and add an explicit config `checksum-via-sql` requires updating some other service code, so make it default to false in this hotfix
Tests 
on default config, 
Side effects
Documentation
```release-note
None
```
> lightning: set default value of checksum-via-sql to false

- br/pkg/lightning/backend/local/engine.go
Issue Number: close #44584 
```
WARNING: DATA RACE
Write at 0x00c006882480 by goroutine 304253:
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Writer).appendRowsSorted()
br/pkg/lightning/backend/local/engine.go:1028 +0xa5
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Writer).AppendRows()
br/pkg/lightning/backend/local/engine.go:1124 +0x3e9
github.com/pingcap/tidb/executor/importer.(*chunkProcessor).deliverLoop.func1()
executor/importer/chunk_process.go:253 +0x1cd
github.com/pingcap/tidb/executor/importer.(*chunkProcessor).deliverLoop()
executor/importer/chunk_process.go:266 +0x578
github.com/pingcap/tidb/executor/importer.(*chunkProcessor).process.func2()
executor/importer/chunk_process.go:131 +0x4c
golang.org/x/sync/errgroup.(*Group).Go.func1() …
```
> import/add-index: fix race and performance regression

- docs/design/2023-06-30-configurable-kv-timeout.md
Issue Number: ref #44771 
Add the detailed design document for the configurable kv timeout proposal.
Tests 
Side effects
Documentation
```release-note
None
```
> doc: rfc for configurable kv timeout

- ddl/ddl_api.go
- ddl/modify_column_test.go
Issue Number: close #45136 
Problem Summary: Let the behaviour same as MySQL.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: disable modify column combine auto_increment with default value

- Makefile
- Makefile.common
- WORKSPACE
- WORKSPACE.patchgo
Tests 
Side effects
Documentation
```release-note
None
```
> *: embed failpoint into bazel

- statistics/handle/bootstrap.go
- statistics/handle/cache/internal/inner.go
- statistics/handle/cache/statscache.go
- statistics/handle/cache/statscacheinner.go
- statistics/handle/handle.go
Problem Summary: planner: simplify `StatsCacheWrapper`
planner: simplify `StatsCacheWrapper`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: simplify `StatsCacheWrapper`

- planner/core/handle_cols.go
- planner/core/logical_plan_builder.go
- planner/core/logical_plans.go
- planner/core/rule_column_pruning.go
Issue Number: close https://github.com/pingcap/tidb/issues/44579
step1: when column pruner #1 steps into datasource, it will keep column ‘a’ and clear handleCols in the case below
step2: ppd logical optimization will clear invalid condition count(a) = null, which is always false
step3: as is known to all, the last column pruner finds there is nothing required by datasource parent, it will clear all the schema columns existed now, and try to add a handle col (which cleared in step 1), therefore it adds a _tidb_rowid instead for a clustered table.
Tests 
```
tiup playground v7.2.0 --tiflash=1 --db.binpath="/Users/arenatlx/go/src/github.com/pingcap/tidb/bin/tidb-server"
create table if not exists test.t1(a int(11) DEFAULT NULL, id int(11) NOT NULL, PRIMARY KEY (`id`) …
```
> planner: fix column pruner will clear handleCols and lead filling _tidb_rowid when datasource's schema length is 0 for a pkIsHandled table

- util/cgroup/cgroup.go
- util/cgroup/cgroup_cpu.go
- util/cgroup/cgroup_mock_test.go
Issue Number: close #44790
Fixed the issue that getCgroupCPU() v1 logic doesn't work with CPU controller that appears like 'cpuacct,cpu' in /proc/self/cgroup and /proc/self/mountinfo. Added controllerMatch() to split the controllers and do the matching one by one instead of simply comparing them as a whole.
Tests 
- Unit test: the modified cgroup_mock_test
Side effects
None
Documentation
None
```release-note
Fix the issue that getCgroupCPU() v1 logic doesn't work with CPU controller that appears like 'cpuacct,cpu' in /proc/self/cgroup and /proc/self/mountinfo.
```
> cgroup: fixed cpu,cpuacct controller order incompatibility.

- dumpling/export/ir_impl.go
- dumpling/tests/basic/run.sh
Issue Number: close #45200 
- revert some code in https://github.com/pingcap/tidb/pull/41588, we still init `SQLRowIter` lazily, and check it on close
Tests 
Side effects
Documentation
```release-note
None
```
> dumpling: fix panic when query result is empty

- dumpling/export/dump.go
- dumpling/tests/no_table_and_db_name/run.sh
Issue Number: close #45239 
Tests 
Side effects
Documentation
```release-note
None
```
> dumpling: skip query tables when use `--sql`

- server/conn_stmt_test.go
- server/mock_conn.go
Add more tests to cover the following situations:
1. Execute returns error in the early check
2. Execute / Fetch can return the expected data
3. Execute multiple times will not return an error, and the original cursor will be closed automatically
4. Reset will close the opened cursor automatically
5. Command send long data works well
6. Reset will removes the stored "long data"
> server: add more integration/unit tests for cursor fetch

- statistics/handle/cache/internal/inner.go
- statistics/handle/cache/internal/lru/lru_cache.go
- statistics/handle/cache/internal/lru/lru_cache_test.go
- statistics/handle/cache/internal/mapcache/map_cache.go
- statistics/handle/cache/statscacheinner.go
- statistics/handle/handle.go
- statistics/handle/handle_hist.go
- statistics/handle/update.go
Problem Summary: planner: simplify `StatsCacheInner`
planner: simplify `StatsCacheInner`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: simplify `StatsCacheInner`

- infoschema/tables.go
- infoschema/test/clustertablestest/tables_test.go
Issue Number: ref #16302 
Before (`7.3.0-alpha`):
```
mysql> TABLE information_schema.CLUSTER_INFO;
+------+-----------------+-----------------+-------------+------------------------------------------+---------------------+---------------+-----------+
| TYPE | INSTANCE        | STATUS_ADDRESS  | VERSION     | GIT_HASH                                 | START_TIME          | UPTIME        | SERVER_ID |
+------+-----------------+-----------------+-------------+------------------------------------------+---------------------+---------------+-----------+
| tidb | 127.0.0.1:4000  | 127.0.0.1:10080 | 7.3.0-alpha | 8c71149116f9439713604d3bf737156a2735b963 | 2023-07-06 15:14:07 | 12.962112656s |   1561139 |
| pd   | 127.0.0.1:2379  | 127.0.0.1:2379  | 7.2.0       | …
```
> infoschema: Don't truncate versions

- ddl/ddl_api.go
- ddl/placement/bundle.go
- ddl/placement/bundle_test.go
- ddl/placement/errors.go
- ddl/placement/rule.go
- ddl/placement_policy_test.go
- docs/design/2020-06-24-placement-rules-in-sql.md
- domain/infosync/BUILD.bazel
- domain/infosync/placement_manager.go
- parser/ast/ddl.go
- parser/misc.go
- parser/model/model.go
- parser/parser.y
- parser/parser_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/38605
pick: https://github.com/pingcap/tidb/pull/40613
**Is your feature request related to a problem? Please describe:**
users hoped that the scale of high availability is controllable, not for the entire database.  they want to distribute data across regions with specified tables. Such as:
**Describe the feature you'd like:**
Supports SQL Placement Policy Like :
```
ALTER PLACEMENT POLICY myplacementpolicy FOLLOWERS=5 SURVIVAL_PREFERENCES=["region", "zone", "host"]; 
```
Tests 
Documentation
```release-note
placement: supports survival …
```
> placement: supports survival preferences (#40613) (#44701)

- statistics/handle/bootstrap.go
- statistics/handle/cache/statscacheinner.go
- statistics/handle/handletest/statstest/BUILD.bazel
- statistics/handle/handletest/statstest/stats_test.go
Problem Summary: planner: remove unnecessary method `StatsCache.FreshMemUsage `
Tests 
Side effects
Documentation
```release-note
None
```
> planner: remove unnecessary method `StatsCache.FreshMemUsage `

- planner/core/physical_plans.go
- planner/core/planbuilder_test.go
Issue Number: close #45299
Fix `PhysicalTableReader::Clone`, so `PhysicalTableReader::TablePlans` are still extracted from `PhysicalTableReader::tablePlan`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix bug in `PhysicalTableReader::Clone()`

- ddl/ddl_api.go
- ddl/ddl_worker.go
- ddl/partition.go
- ddl/split_region.go
- ddl/table.go
Issue Number: close #44785
Before this PR, TiDB splits and scatters region after the DDL is complete. This may cause the issue that client waits a long time but the ddl info records only a few time.
As recommended in https://github.com/pingcap/tidb/issues/44785#issuecomment-1596835129, I moved `preSplitAndScatter` to DDL worker side.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: move preSplitAndScatter to ddl worker

- executor/index_merge_reader.go
Issue Number: close #45279 
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix query hang in IndexMerge Executor when it's killed

- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/lightning/backend/local/checksum.go
- br/pkg/lightning/backend/local/checksum_test.go
manually cherry-pick (#44478) (#44856) 
Issue Number: close #45301
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: retry for leader change error when GetTS (#44478) (#44856) 

- session/resourcegrouptest/resource_group_test.go
- session/session.go
Issue Number: close #45178
After setting resource group name from hint, check the group name's existence and directly fallback to the original group name if the hint name is invalid.
Tests 
Side effects
Documentation
```release-note
None
```
> session: add check resource group hint existence

- ttl/ttlworker/job_manager.go
- ttl/ttlworker/job_manager_integration_test.go
- ttl/ttlworker/job_manager_test.go
Issue Number: close #45285
There are two scenes for a tidb instance to lock and execute a job:
1. A table is time to execute, a new job should be created.
2. A exist job's heartbeat is timeout, the tidb should take over it.
In the previous implement this two scenes and processed in one method and not separated. However, in the future we want to move the trigger codes to timer so it's better to separate the above code from two scenes apart.
Refactor method `lockNewJob` to `lockJob` and it can pass the extra argument `isCreate`, if `isCreate` is true, it only creates a new job and if `isCreate` is false, it only takes over the timeout job.
Tests 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release …
> ttl: refactor TTL to seperate creating new job and take timeout job codes

- executor/index_merge_reader.go
close pingcap/tidb#45279
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix query hang in IndexMerge Executor when it's killed (#45284)

- br/pkg/lightning/backend/kv/BUILD.bazel
- br/pkg/lightning/backend/kv/base.go
- br/pkg/lightning/backend/kv/base_test.go
Issue Number: close #44321 
When the source file has ill-formated row, the row is very large so it can't be logged. We can't locate the bad row;
```
2023-06-01 10:55:27.887067902 +0800 CST m=+35.508861459 write error: write length 20297970322 exceeds maximum file size 536870912
```
When we encounter ill-formatted row, we take out the ill-formatted row and only log the first 1024 characters of the row, so that it would not report error that write length exceeds maximum file size.
Before fixing the issue, the log looks like this when encountering ill-formatted row:
```
[2023/07/06 22:23:38.812 +08:00] [INFO] [base_test.go:40] ["logger is initialized"]
2023-07-06 22:23:39.344279 +0800 CST m=+0.575101501 write error: write length 1050272 exceeds maximum file size 1048576 …
```
> lightning: fix lightning failed to log encoding error

- expression/builtin_string.go
- planner/core/plan_cache_test.go
Issue Number: close #45253
Problem Summary: planner: fix incorrect `flen` for the `to_base64` function
planner: fix incorrect `flen` for the `to_base64` function
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix incorrect `flen` for the `to_base64` function

- br/pkg/lightning/config/config.go
- br/tests/lightning_add_index/config1.toml
Issue Number: close #45368 
set default value of checksum-via-sql to false
Tests 
Side effects
Documentation
```release-note
None
```
> lightning:set default value of checksum-via-sql to false

- store/copr/coprocessor.go
- store/copr/coprocessor_cache.go
Issue Number: close #45398
https://pkg.go.dev/github.com/dgraph-io/ristretto?utm_source=godoc#Config
we know from the document of ristretto. ristretto's metric is disabled at default. so we are never able to read value from it.
Tests 
Side effects
Documentation
```release-note
coprocessor: fix the evict metrics for copr cache
```
> coprocessor: fix the evict metrics for copr cache

- expression/builtin_string.go
- planner/core/plan_cache_test.go
Issue Number: close #45378
Problem Summary: planner: consider Unspecified length when setting length for unhex
planner: consider Unspecified length when setting length for unhex
Tests 
Side effects
Documentation
```release-note
None
```
> planner: consider Unspecified length when setting length for unhex

- ttl/ttlworker/timer_test.go
Issue Number: close #45445
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: fix unstable test 'TestTTLTimerHookOnEvent'

- statistics/handle/cache/internal/BUILD.bazel
- statistics/handle/cache/internal/bench_test.go
- statistics/handle/cache/internal/lfu/BUILD.bazel
- statistics/handle/cache/internal/lfu/key_set.go
- statistics/handle/cache/internal/lfu/key_set_shard.go
- statistics/handle/cache/internal/lfu/lfu_cache.go
- statistics/handle/cache/internal/lfu/lfu_cache_test.go
- statistics/handle/cache/internal/lru/BUILD.bazel
Issue Number: ref #45367
```
BenchmarkCachePut
BenchmarkCachePut/LRU
BenchmarkCachePut/LRU-8         	   35224	     65941 ns/op
BenchmarkCachePut/LFU
BenchmarkCachePut/LFU-8         	  143685	     10771 ns/op
BenchmarkCachePutGet/LRU
BenchmarkCachePutGet/LRU-8         	   30358	     40205 ns/op
BenchmarkCachePutGet/LFU
BenchmarkCachePutGet/LFU-8         	   85431	     14172 ns/op
```
Tests 
add benchmark
Side effects
Documentation
```release-note
None
```
> statcache: faster LFU

- ddl/index.go
- ddl/ingest/disk_root.go
- errno/errcode.go
- errno/errname.go
- errors.toml
- tests/realtikvtest/addindextest/integration_test.go
- util/dbterror/ddl_terror.go
Issue Number: close #45456
#43210 added the `PrecheckUsage()` function which depends on the existence of temp dir. However, the automatically creation of temp dir happens after `PrecheckUsage()`. It cause the unexpected behavior.
Create temp dir automatically for adding index.
Tests 
Terminal 1:
```
mysql> alter table t1 add index idx(k);
Query OK, 0 rows affected (2.59 sec)
```
Terminal 2:
```
➜  tidb ls
import-4000
➜  tidb ls
import-4000  tmp_ddl-4000
```
Side effects
Documentation
```release-note
None
```
> ddl: create temp dir automatically for adding index

- session/session.go
- ttl/ttlworker/task_manager.go
- ttl/ttlworker/task_manager_integration_test.go
Issue Number: close #45510
Fix two memory leaks in TTL implement:
1. task context created by `context.WithCancel` should be cancelled finally when task finished.
2. `SessionStatsCollector.Delete` should be called when detaching it from a session because of `NewSessionStatsCollector` will append the created collector to a global list
Tests 
Side effects
Documentation
```release-note
ttl: fix some memory leaks in TTL
```
> ttl: fix some memory leak in TTL

- executor/partition_table_test.go
Issue Number: close #45496
```
The test easy failed when `limit = 1`.
Like `select /*+ LIMIT_TO_COP() */ * from tlist use index(idx_b) where b > 1126 and b < greatest(1127+1, 1127) order by b limit 1`.
It will change to `b = 1127`. Sometimes we have more than 1 line equal to 1127, so the result is unstable.
```
Tests 
```
Modify y=1 to run the test without error.
```
Side effects
Documentation
```release-note
None
```
> executor: make `TestOrderByAndLimit` stable

- br/pkg/lightning/log/BUILD.bazel
- br/pkg/lightning/log/log.go
- br/pkg/lightning/log/log_test.go
- util/logutil/log.go
Issue Number: close #45497
- add parameter `enable-diagnose-logs` to output logs of all packages and enable grpc log when enabled, default is false
Tests 
- enable the parameter, we can see logs: `coprocessor.go` of tidb, and `client_batch.go` of client-go
```log
[2023/07/21 14:48:09.126 +08:00] [INFO] [grpclogger.go:92] ["[core][Channel #1] Channel created"] [system=grpc] [grpc_log=true]
[2023/07/21 14:48:09.126 +08:00] [INFO] [grpclogger.go:92] ["[core][Channel #1] original dial target is: \"127.0.0.1:2379\""] [system=grpc] [grpc_log=true]
[2023/07/21 14:16:56.613 +08:00] [INFO] [coprocessor.go:1290] ["[TIME_COP_PROCESS] resp_time:380.626041ms txnStartTS:443002375548698627 region_id:128 store_addr:192.168.192.77:20160 kv_process_ms:194 kv_w
ait_ms:5 kv_read_ms:0 …
```
> lightning: add parameter to output logs of all packages and enable grpc log

- planner/core/casetest/rule/BUILD.bazel
- planner/core/casetest/rule/rule_join_reorder_test.go
- planner/core/casetest/rule/testdata/join_reorder_suite_in.json
- planner/core/casetest/rule/testdata/join_reorder_suite_out.json
- planner/core/exhaust_physical_plans.go
- planner/core/logical_plan_builder.go
- planner/core/logical_plans.go
- planner/core/planbuilder.go
Issue Number: ref #45520
Problem Summary: planner: support `no_hash_join` hint on optimizer
planner: support `no_hash_join` hint on optimizer
Tests 
Side effects
Documentation
```release-note
None
```
> planner: support `no_hash_join` hint on optimizer

- store/helper/helper.go
Issue Number: close #45531
Tests 
```
mysql> select tidb_table_id from information_schema.tables where table_schema='test' and table_name='t1';
+---------------+
| tidb_table_id |
+---------------+
|            96 |
+---------------+
1 row in set (0.01 sec)
mysql> select region_id, is_index, start_key from information_schema.tikv_region_status where table_id = 96;
+-----------+----------+--------------------------------------------------------+
| region_id | is_index | start_key                                              |
+-----------+----------+--------------------------------------------------------+
|       154 |        0 | 7480000000000000FF605F720173000000FF0000000000000000FB |
|       160 |        0 | 7480000000000000FF605F720176000000FF0000000000000000FB |
| …
```
> store: Don't set limit for GetRegionsInfoByRange function

- server/http_handler.go
- server/http_handler_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/45561
Fix data race between getting labels and setting labels in config
Tests 
Side effects
Documentation
```release-note
None
```
> *: Fix data race between getting labels and setting labels in config

- DEPS.bzl
- go.mod
- go.sum
- metrics/grafana/tidb.json
Issue Number: close #45339
cherry-pick: https://github.com/pingcap/tidb/pull/45505
Tests 
Side effects
Documentation
```release-note
None
```
> *: update tikv/client-go and fix stale read metrics in grafana

- planner/core/casetest/rule/BUILD.bazel
- planner/core/casetest/rule/rule_join_reorder_test.go
- planner/core/casetest/rule/testdata/join_reorder_suite_in.json
- planner/core/casetest/rule/testdata/join_reorder_suite_out.json
- planner/core/exhaust_physical_plans.go
- planner/core/logical_plan_builder.go
- planner/core/logical_plans.go
- planner/core/planbuilder.go
Issue Number: ref #45520
Problem Summary: planner: support `no_merge_join` hint on optimizer
planner: support `no_merge_join` hint on optimizer
Tests 
Side effects
Documentation
```release-note
None
```
> planner: support `no_merge_join` hint on optimizer

- br/pkg/lightning/config/config.go
- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/importer/check_info.go
- br/pkg/lightning/importer/check_info_test.go
- br/pkg/lightning/importer/import.go
- br/tests/lightning_incremental/config.toml
Issue Number: close #45501 
The actual meaning of `tikv-importer.incremental-import` is to use the physical import mode for parallel import, which requires the target table to be empty. However, the current name may mislead users into thinking it is for incremental import, leading to misuse.
When the user misuses it and sets the `duplicate-resolution` to `remove`, conflicts between data in the source file and the existing data in the target table can lead to the mistaken deletion of the conflicting records in the target table.
1. Starting from version 7.3, the parameter name has been changed from `tikv-importer.incremental-import` to `tikv-importer.parallel-import`.
2. If users pass the parameter name as `tikv-importer.incremental-import`, it will be converted to …
> Lightning: Update Parameter Name from `tikv-importer.incremental-import` to `tikv-importer.parallel-import`

- build/BUILD.bazel
- planner/core/main_test.go
- planner/core/rule_join_reorder.go
- planner/core/rule_join_reorder_test.go
- planner/core/testdata/join_reorder_suite_in.json
- planner/core/testdata/join_reorder_suite_out.json
Issue Number: close #45564 , ref #44409
In #44409 , we only cleaned the other conditions, but the one side filters will also need to be checked.
Tests 
Side effects
Documentation
```release-note
Fix the case that the join predicates might be put in the wrong place.
```
> planner: clean the one side filters for outer join reorder which is not done in #44409

- planner/core/exhaust_physical_plans.go
- planner/core/planbuilder.go
Issue Number: ref #45520
Problem Summary: planner: refine `tryToGetIndexJoin`
planner: refine `tryToGetIndexJoin`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: refine `tryToGetIndexJoin`

- disttask/framework/framework_rollback_test.go
- disttask/framework/framework_test.go
- disttask/framework/scheduler/register.go
- disttask/framework/scheduler/scheduler.go
- disttask/framework/scheduler/scheduler_test.go
- disttask/importinto/scheduler.go
Issue Number: ref #41495
- remove the option of running subtasks concurrently
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: remove the option of running subtasks concurrently

- ddl/db_change_test.go
- ddl/index.go
Issue Number: close https://github.com/pingcap/tidb/issues/45575
cherry-pick #45582 and fixed "alter index" issue)
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix parallel execution "alter index" (cherry-pick #45582 and fixed "alter index" issue)

- br/pkg/lightning/backend/tidb/tidb_test.go
- br/pkg/lightning/errormanager/errormanager.go
- br/pkg/lightning/errormanager/errormanager_test.go
- br/tests/lightning_config_max_error/run.sh
- br/tests/lightning_duplicate_detection_new/run.sh
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: rename conflict table to conflict_records

- executor/importer/BUILD.bazel
- executor/importer/chunk_process.go
- executor/importer/import.go
- executor/importer/import_test.go
- executor/importer/table_import.go
- executor/importer/table_import_test.go
- tests/realtikvtest/importintotest/import_into_test.go
- tests/realtikvtest/importintotest/job_test.go
Issue Number: close #44975, ref #45005
- change default engine size to 500g, it's adjusted by total data size to avoid generate engine that is too small
- add logs about read/encode/deliver duration
Tests 
for a 1T data set, before this change, we split into 11 subtasks, takes more than 241m
after, 2 subtasks, takes about 164m
Side effects
Documentation
```release-note
None
```
> import into: enlarge subtask size to reduce range overlap

- metrics/BUILD.bazel
- metrics/metrics.go
- metrics/timer.go
- metrics/ttl.go
- timer/metrics/BUILD.bazel
- timer/metrics/metrics.go
- timer/runtime/BUILD.bazel
- timer/runtime/runtime.go
- timer/runtime/runtime_test.go
- timer/runtime/worker.go
- timer/runtime/worker_test.go
- ttl/ttlworker/BUILD.bazel
- ttl/ttlworker/timer_sync.go
- ttl/ttlworker/timer_sync_test.go
- util/mock/BUILD.bazel
- util/mock/metrics.go
Issue Number: close #45610
Tests 
Side effects
Documentation
```release-note
None
```
> timer,ttl: add some metrics for timer framework and TTL timer syncing

- br/cmd/br/debug.go
Issue Number: close #44690
in debug mode to validate backupmeta, br forgets to set partition info before get rewrite rules.
set partition info
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix forget to set partition info when debug validate backupmeta

- extension/event_listener_test.go
Issue Number: ref #38788
Tests 
Side effects
Documentation
```release-note
None
```
> extension: fix some wrong code for extension test

- tests/realtikvtest/importintotest/job_test.go
Issue Number: close #45655
If we meet
```
job_test.go:295: 
Error Trace:	tests/realtikvtest/importintotest/job_test.go:295
Error:      	Condition never satisfied
Test:       	TestLoadRemote/TestShowDetachedJob
```
we don't continue the test, because the slow closure may race with following test logic on `s.tk`
Tests 
Side effects
Documentation
```release-note
None
```
> importintotest: fail fast to avoid data race

- ddl/job_table.go
Issue Number: ref https://github.com/pingcap/tidb/issues/39751
* Rename `needCheckClusterState` to `checkAndUpdateClusterState`
* Using `checkAndUpdateClusterState` instead of `doCheckClusterState`, then remove `doCheckClusterState`.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: simply refactor the code called "needCheckClusterState"

- timer/metrics/metrics.go
- timer/runtime/BUILD.bazel
- timer/runtime/runtime.go
- timer/runtime/runtime_test.go
Issue Number: close #45610
Tests 
Side effects
Documentation
```release-note
None
```
> timer: refactor timer runtime metrics to make it more flexible to use

- metrics/grafana/tidb.json
Issue Number: ref #39848
Added a new chart to show the count of the events in TTL runtime.
Tests 
Side effects
Documentation
```release-note
Added a new chart to show the count of the events in TTL runtime.
```
> ttl: add grafana chart for TTL events

- br/pkg/utils/BUILD.bazel
- br/pkg/utils/backoff_test.go
Issue Number: close #45684
Tests 
Side effects
Documentation
```release-note
None
```
> br: improve TestNewImportSSTBackofferWithSucess

- server/conn.go
Issue Number: close #45675
Problem Summary: Failed to release 32bits connection ID
There are two calls to release for every connection ID. So the pool is unexpected full.
```
(dlv) bt
0  0x00000000041129aa in github.com/pingcap/tidb/util/globalconn.(*LockFreeCircularPool).Put
at ./util/globalconn/pool.go:219
1  0x0000000004111d31 in github.com/pingcap/tidb/util/globalconn.(*GlobalAllocator).Release
at ./util/globalconn/globalconn.go:307
2  0x0000000004c36e18 in github.com/pingcap/tidb/domain.(*Domain).ReleaseConnID
at ./domain/domain.go:2859
3  0x0000000004c36e18 in github.com/pingcap/tidb/server.closeConn
at ./server/conn.go:340
4  0x0000000004c36d69 in github.com/pingcap/tidb/server.(*clientConn).Close
at ./server/conn.go:335
5  0x0000000004c3d58f in …
```
> server: make call to `ReleaseConnID` idempotent.

- ddl/db_partition_test.go
- ddl/ddl_api.go
- ddl/partition.go
- planner/core/casetest/partition/partition_pruner_test.go
- planner/core/partition_pruner_test.go
- session/sessiontest/session_test.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #45700
Tests 
Side effects
Documentation
```release-note
None
```
> *: Remove tidb_enable_default_list_partition variable

- statistics/cmsketch.go
Issue Number: close #45706
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: kill in time when to mergeGlobalTopN with partition

- planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json
- planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
- planner/core/logical_plan_builder.go
- planner/core/rule_predicate_push_down.go
Issue Number: close https://github.com/pingcap/tidb/issues/45647
Tests 
Side effects
Documentation
```release-note
planner: fix having clause item that ref-ed to grouping set expression shouldn't pushed down through Expand OP
```
> planner: fix having clause item that ref-ed to grouping set expression shouldn't be pushed down through Expand OP

- executor/test/writetest/write_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> test: remove dup comments

- sessionctx/variable/session.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #45618
Tests 
Side effects
Documentation
```release-note
TiFlash enables pipeline mode by default.
```
> sessionctx: set tiflash pipeline model to true by default

- br/pkg/conn/conn.go
- br/pkg/conn/util/util.go
- br/pkg/restore/BUILD.bazel
- br/pkg/restore/data.go
- br/pkg/utils/storewatch/BUILD.bazel
- br/pkg/utils/storewatch/watching.go
- br/pkg/utils/storewatch/watching_test.go
Issue Number: close #45206
When TiKV restarts, the leaders will be dropped here.
We need to reregister the leaders.
Tests 
```release-note
Fixed a bug that may cause snapshot restore stuck while there are TiKV restarts.
```
> snap_restore: resend `recover_region` while there are TiKV restarts

- executor/executor.go
- util/chunk/row_container.go
- util/chunk/row_container_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/45161
close https://github.com/pingcap/tidb/issues/26806
Tmp-storage-quota can't take affect.
Use global disk tracker to track the disk usage.
Tests 
Pass the test case in issue45161 and issue26806.
Side effects
Documentation
```release-note
None
```
> executor, util: make tmp-storage-quota take affect

- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/engine_test.go
- br/pkg/lightning/backend/local/iterator.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/region_job.go
part of #45356
before this PR, region job holds an `Engine` structure which is the concept of local backend. In this PR an interface `ingestData` replaces `Engine` so we can introduce a new implementation. Compared with `Engine` which stores data in the disk, we can use a pure memory sorted slice of KV pairs to accomplish region job.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: extract region job's accessing data to an interface

- statistics/merge_worker.go
Issue Number: close https://github.com/pingcap/tidb/issues/45706
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: kill in time when to run topnStatsMergeWorker and improve memory

- build/nogo_config.json
- statistics/analyze.go
- statistics/analyze_jobs.go
- statistics/builder.go
- statistics/cmsketch.go
- statistics/column.go
- statistics/debugtrace.go
- statistics/feedback.go
- statistics/fmsketch.go
- statistics/histogram.go
- statistics/index.go
- statistics/merge_worker.go
- statistics/row_sampler.go
- statistics/sample.go
- statistics/selectivity.go
- statistics/table.go
```
/Users/weizhenwang/devel/opensource/tidb/statistics/analyze.go:70:21: struct with 80 pointer bytes could be 40
/Users/weizhenwang/devel/opensource/tidb/statistics/analyze_jobs.go:23:17: struct with 160 pointer bytes could be 152
/Users/weizhenwang/devel/opensource/tidb/statistics/analyze_jobs.go:35:22: struct with 40 pointer bytes could be 24
/Users/weizhenwang/devel/opensource/tidb/statistics/builder.go:31:20: struct with 56 pointer bytes could be 16
/Users/weizhenwang/devel/opensource/tidb/statistics/cmsketch.go:55:15: struct with 32 pointer bytes could be 8
/Users/weizhenwang/devel/opensource/tidb/statistics/cmsketch.go:82:17: struct with 16 pointer bytes could be 8
/Users/weizhenwang/devel/opensource/tidb/statistics/column.go:37:13: struct …
```
> statistics: enable fieldalignment 

- Makefile
Tests 
Side effects
Documentation
```release-note
None
```
See also: #44889
> *: Update bazel to prune

- server/BUILD.bazel
- server/conn_test.go
- store/copr/coprocessor.go
Issue Number: close #45773 
Tests 
Side effects
Documentation
```release-note
None
```
> store,server: Reduce TiFlashFallBack test time

- executor/batch_point_get.go
- executor/builder.go
- planner/core/casetest/partition/testdata/integration_partition_suite_in.json
- planner/core/casetest/partition/testdata/integration_partition_suite_out.json
- planner/core/find_best_task.go
- planner/core/point_get_plan.go
Issue Number: close #45720
Problem Summary: I didn't check specific table partitions in `batch_point_get` before, support it and add tests to cover it.
Tests 
Side effects
Documentation
```release-note
None
```
> planner, executor: fix batch_point_get with specific table partitions

- br/pkg/lightning/common/BUILD.bazel
- br/pkg/lightning/common/security.go
- br/pkg/lightning/common/security_test.go
- br/tests/lightning_partitioned-table/run.sh
Issue Number: close https://github.com/pingcap/tidb/issues/45747
TrimPrefix before WithHost
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```
> lightning: fix lightning TLS.WithHost to access the correct host

- statistics/handle/handletest/statstest/BUILD.bazel
- statistics/handle/handletest/statstest/stats_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> statstest: make test faster

- Dockerfile
- Dockerfile.enterprise
- WORKSPACE
- build/image/base
Tests 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.20.7

- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/byte_reader.go
- br/pkg/lightning/backend/external/byte_reader_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/45719
Problem Summary: N/A
Add the byte reader implementation.
Tests 
Side effects
Documentation
```release-note
None
```
> br/lightning: add byte reader implementation

- infoschema/BUILD.bazel
- infoschema/infoschema.go
- infoschema/infoschema_test.go
- infoschema/metrics_schema.go
Issue Number: close https://github.com/pingcap/tidb/issues/45744
At present, it is the `MaxColumnID` of the table in the `information_schema` database, which affects `modify column`, `add column`(this action has no problem in behavior, but can cause problems with column ids that are not unique)
. 
The table under `metrics_schema` has a similar problem, and the table under `performance_schema` does not.
* Set tables' `MaxColumnID` in the `information_schema` and `metrics_schema` databases.
* Set tables' `MaxIndexD`, although this field is not currently used.
Tests 
Side effects
Documentation …
> infoschema: fix the value of `MaxColumnID` in memDB

- br/pkg/mock/storage/storage.go
- br/pkg/storage/azblob.go
- br/pkg/storage/compress.go
- br/pkg/storage/gcs.go
- br/pkg/storage/hdfs.go
- br/pkg/storage/local.go
- br/pkg/storage/local_test.go
- br/pkg/storage/memstore.go
- br/pkg/storage/memstore_test.go
- br/pkg/storage/noop.go
- br/pkg/storage/s3.go
- br/pkg/storage/storage.go
- br/pkg/storage/writer_test.go
- br/pkg/task/stream_test.go
- dumpling/export/writer_util.go
This PR supports concurrent write on S3, which is faster than before.
Tests 
Side effects
Documentation
```release-note
None
```
> *: support concurrent write for S3 writer

- planner/core/issuetest/BUILD.bazel
- planner/core/issuetest/planner_issue_test.go
- planner/core/resolve_indices.go
Issue Number: close #45758 , close #45805 
In https://github.com/pingcap/tidb/pull/45158, we use `ResolveIndices` for the inline projection's column matching.
It's possible that the join/limit's child(ren)'s output columns are `[col0, col0, col1]`.
And if we call ResolveIndices, the two `col0` from join/limit will resolve their indexes to the first col0. But actually, the first col0 should resolve to the first col0 of its child(ren). The second should resolve to the second of its child(ren).
This pr aims to solve this issue.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: refactor Join and Limit's ResolveIndices

- statistics/handle/handletest/statslock/stats_lcok_test.go
Issue Number: close #45843
Tests 
Side effects
Documentation
```release-note
None
```
> *: fix TestStatsLockAndUnlockTables

- br/pkg/task/stream.go
Issue Number: close #45853 
the error should be checked when failed to initialize the dml iterator in pitr
check the unchecked error of initialization of dml iterator in pitr
Tests 
Side effects
Documentation
```release-note
None
```
> br: check the unchecked error of initialization of dml iterator in pitr

- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/dispatcher/dispatcher_manager.go
- disttask/framework/dispatcher/dispatcher_test.go
- disttask/framework/framework_rollback_test.go
- disttask/framework/framework_test.go
Issue Number: ref #41495 
scheduleTask is in a mess.
Refine scheduleTask to follow the state machine.
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: refine scheduleTask

- Makefile
Issue Number: ref #25754
I find some benchmark tests missing data in http://www.zenlife.tk:18081/
For example this one
So I try to figure out why... and find that if `-tags intest` is not set, `testkit.NewTestKit(b, store)` make the program exit directly, so the benchmark tests do not get the data.
Tests 
Side effects
Documentation
```release-note
None
```
> Makefile: add '-tags intest' for running bench-daily

- meta/meta.go
- session/bootstrap_test.go
Issue Number: close #45570
We checked DDLTableVersion == 2 in 6.5, but it may be set to a higher value in a higher version TiDB.
check DDLTableVersion >= 2, which is the same as the fixed in the higher version.
Tests 
Start a master cluster, then use this PR to start a TiDB server. It can start normally.
Side effects
Documentation
```release-note
support rollback from higher version to 6.5
```
> *: support rollback from higher version to 6.5

- ttl/client/command.go
Issue Number: close #45868
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: make ttl manually trigger stable

- executor/batch_point_get.go
- executor/builder.go
- planner/core/casetest/partition/integration_partition_test.go
- planner/core/casetest/partition/testdata/integration_partition_suite_in.json
- planner/core/casetest/partition/testdata/integration_partition_suite_out.json
- planner/core/casetest/partition/testdata/partition_pruner_out.json
- planner/core/find_best_task.go
- planner/core/point_get_plan.go
Issue Number: close #45889
Problem Summary: Revert https://github.com/pingcap/tidb/pull/45748 and #45646. `Batch_point_get` for partition table in dynamic mode has many potential problems (see it in https://github.com/pingcap/tidb/issues/45532), let's ban it now.
Tests 
Side effects
Documentation
```release-note
None
```
> partition: Revert support batch_point_get for partition table in dynamic mode

- parser/lexer.go
- parser/parser_test.go
Issue Number: close #45898
Problem Summary: parser: reset `lexer.identifierDot` correctly when reusing parsers
parser: reset `lexer.identifierDot` correctly when reusing parsers
Tests 
Side effects
Documentation
```release-note
None
```
> parser: reset `lexer.identifierDot` correctly when reusing parsers

- executor/partitiontest/BUILD.bazel
- executor/partitiontest/partition_test.go
- planner/core/task.go
…t + static prune
Issue Number: close #45757
Tests 
Side effects
Documentation
```release-note
None
```
> executor, planner: add extraProj for indexLookUp with order by + limit + static prune

- parser/parser.y
- parser/parser_test.go
Issue Number: close #45838
In https://github.com/pingcap/tidb/blob/v7.3.0-alpha/parser/parser.y#L9933, it takes `SelectStmtWithClause` as a `SelectStmt`, but it can also be a `SetOprStmt`.
Judge the type and consider `SetOprStmt`.
Tests 
Side effects
Documentation
```release-note
None
```
> parser: fix panic in parsing CTE within a subquery

- Makefile
- cmd/explaintest/run-tests.sh
Issue Number: ref #44301
Tests 
Side effects
Documentation
```release-note
None
```
> Makefile: add coverage report for `explaintest`

- br/tests/_utils/run_br
- br/tests/_utils/run_lightning
- br/tests/_utils/run_lightning_ctl
- br/tests/run.sh
- br/tests/run_group.sh
update integration test coverage for br/lightining.
Tests 
Side effects
Documentation
```release-note
None
```
> br: update code coverage for integration test

- statistics/cmsketch.go
- statistics/cmsketch_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/45899
- Add normal tests for MergePartTopN2GlobalTopN
- Update outdated comment.
- Add benchmark tests
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: Add tests for MergePartTopN2GlobalTopN

- docs/design/2023-06-16-runaway-queries-management.md
Issue Number: Ref #43691 
Tests 
Side effects
Documentation
```release-note
None
```
> resource_control: publish runaway management rfc

- statistics/cmsketch.go
- statistics/histogram.go
Issue Number: close #45727
Tests 
add some gobench for it.
Before:
| Benchmark                                  | Iterations | Time per Operation | Memory Allocated | Allocations per Operation |
|--------------------------------------------|------------|-------------------|------------------|---------------------------|
| BenchmarkMergePartTopN2GlobalTopNWithHists100-8    | 85184      | 13737 ns/op       | 4408 B/op        | 53 allocs/op             |
| BenchmarkMergePartTopN2GlobalTopNWithHists1000-8   | 8985       | 136583 ns/op      | 40696 B/op       | 503 allocs/op            |
| BenchmarkMergePartTopN2GlobalTopNWithHists10000-8  | 702        | 1637701 ns/op     | 405880 B/op      | 5003 allocs/op           |
| BenchmarkMergePartTopN2GlobalTopNWithHists100000-8 | 48 …
> statistics: reduce memory usage when to MergePartTopN2GlobalTopN

- executor/analyze.go
- executor/analyze_test.go
- executor/builder.go
- executor/infoschema_reader_test.go
- executor/test/analyzetest/analyze_test.go
- planner/core/indexmerge_path_test.go
- planner/core/integration_test.go
- statistics/analyze_jobs.go
- statistics/handle/handletest/analyze/analyze_test.go
- statistics/integration_test.go
Issue Number: close #45936
Problem Summary: planner: log the reason why the sample-rate is chosen when analyzing table
planner: log the reason why the sample-rate is chosen when analyzing table
Tests 
Side effects
Documentation
```release-note
None
```
> planner: log the reason why the sample-rate is chosen when analyzing table

- planner/core/planbuilder.go
- statistics/handle/handletest/analyze/analyze_test.go
Issue Number: ref #45919
Problem Summary: planner: increase the maximum number limit of TopN when analyzing tables
planner: increase the maximum number limit of TopN when analyzing tables
Tests 
Side effects
Documentation
```release-note
None
```
> planner: increase the maximum number limit of TopN when analyzing tables

- executor/infoschema_reader_test.go
- executor/merge_join_test.go
- executor/test/analyzetest/analyze_test.go
- planner/core/prepare_test.go
Issue Number: ref #45985
Tests 
Side effects
Documentation
```release-note
None
```
> *: remove skip

- ddl/ddl_api.go
- executor/BUILD.bazel
- executor/builder.go
- executor/cte_test.go
- executor/merge_join_test.go
- executor/metrics_reader.go
- executor/show.go
- executor/slow_query.go
- executor/table_reader.go
- executor/test/analyzetest/analyze_test.go
- executor/trace.go
- planner/core/util.go
- sessionctx/variable/BUILD.bazel
- sessionctx/variable/session.go
- sessionctx/variable/varsutil.go
- statistics/table.go
- telemetry/BUILD.bazel
- telemetry/data_cluster_hardware.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: replace exp/slices with std

- build/nogo_config.json
Tests 
Side effects
Documentation
```release-note
None
```
> br:  enable toomanytests

- br/pkg/lightning/BUILD.bazel
- br/pkg/lightning/backend/kv/BUILD.bazel
- br/pkg/lightning/backend/kv/sql2kv.go
- br/pkg/lightning/duplicate/BUILD.bazel
- br/pkg/lightning/duplicate/detector_test.go
- br/pkg/lightning/importer/dup_detect.go
- br/pkg/lightning/importer/precheck_impl.go
- br/pkg/lightning/lightning.go
- br/pkg/restore/db.go
- br/pkg/task/BUILD.bazel
- br/pkg/task/stream.go
- br/pkg/trace/BUILD.bazel
- br/pkg/trace/tracing.go
- executor/infoschema_reader_test.go
- executor/merge_join_test.go
- executor/test/analyzetest/analyze_test.go
- planner/core/prepare_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> br: replace exp/slices with std

- br/pkg/lightning/backend/local/engine.go
- dumpling/export/BUILD.bazel
- dumpling/export/dump.go
- dumpling/export/util.go
- expression/BUILD.bazel
- expression/builtin.go
- expression/builtin_info.go
- expression/builtin_info_vec.go
- expression/column.go
- expression/explain.go
- planner/core/BUILD.bazel
- planner/core/exhaust_physical_plans.go
- planner/core/find_best_task.go
- planner/core/fragment.go
- planner/core/hashcode.go
- planner/core/memtable_predicate_extractor.go
- planner/core/memtable_predicate_extractor_test.go
- planner/core/plan_cache_utils.go
- planner/core/rule_join_reorder.go
- planner/core/rule_partition_processor.go
- planner/core/rule_predicate_simplification.go
- planner/core/stats.go
- planner/core/tiflash_selection_late_materialization.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: use std slices to replace exp/slices

- statistics/BUILD.bazel
- statistics/cmsketch.go
- statistics/cmsketch_test.go
- statistics/feedback.go
- statistics/handle/BUILD.bazel
- statistics/handle/handle.go
- statistics/handle/update.go
- statistics/index.go
- statistics/selectivity_test.go
using builtin slices lib instead of exp slices 
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: using standard lib slices instead of exp slices

- statistics/cmsketch_bench_test.go
- statistics/handle/handle.go
- statistics/merge_worker.go
Issue Number: close https://github.com/pingcap/tidb/issues/45727
Tests 
```
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/statistics
cpu: AMD Ryzen 7 7735HS with Radeon Graphics
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size100-16         	   16852	     82494 ns/op	   19801 B/op	     248 allocs/op
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size1000-16        	    2394	    528919 ns/op	  164952 B/op	    2048 allocs/op
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size10000-16       	      46	  27104549 ns/op	16254536 B/op	  200239 allocs/op
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size100000-16      	       1	3820741278 ns/op	1564350080 B/op	19552007 allocs/op
```
after
```
goos: linux
goarch: amd64
pkg: …
```
> statistics: improve memory for mergeGlobalStatsTopNByConcurrency

- executor/executor_test.go
- expression/builtin_compare.go
Issue Number: close #38361
Problem Summary: When compare datetime/timestamp column with numeric constant, try convert numeric constant to timestamp datetime, do nothing if conversion failed.
Tests 
Side effects
Documentation
```release-note
None
```
> expression: Fix different behaviors with MySQL when comparing datetime column with numeric constant | tidb-test=pr/2196

- executor/simple.go
Issue Number: close #46034 
Problem Summary: Coroutine leak after kill remote connection.
Close `resp` of coprocessor request. Otherwise the coprocessor will be blocked on the `respChan`.
Tests 
Run the same test in issue, the coroutine count was stable, and no OOM occurred.
Side effects
Documentation
```release-note
None
```
> executor: Fix coroutine leak after kill remote connection

- statistics/handle/cache/internal/lfu/lfu_cache.go
- statistics/handle/cache/internal/metrics/metrics.go
Issue Number: close #46074
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: add reject metrics for LFU cache

- build/nogo_config.json
- expression/aggregation/agg_to_pb.go
- expression/aggregation/avg.go
- expression/aggregation/base_func.go
- expression/aggregation/bit_and.go
- expression/aggregation/bit_or.go
- expression/aggregation/bit_xor.go
- expression/aggregation/concat.go
- expression/aggregation/count.go
- expression/aggregation/descriptor.go
- expression/aggregation/first_row.go
- expression/aggregation/max_min.go
- expression/aggregation/sum.go
Tests 
Side effects
Documentation
```release-note
None
```
> expression: enable revive for part

- disttask/framework/framework_rollback_test.go
- disttask/framework/framework_test.go
Issue Number: close #46014 
Subtask in tests are not reentrant.
Use map instead of atomic.Int64
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: fix owner change flaky test

- planner/core/issuetest/planner_issue_test.go
- planner/core/resolve_indices.go
This is a manual cherry-pick of #45831
Issue Number: close #45758 , close #45805 
In https://github.com/pingcap/tidb/pull/45158, we use `ResolveIndices` for the inline projection's column matching.
It's possible that the join/limit's child(ren)'s output columns are `[col0, col0, col1]`.
And if we call ResolveIndices, the two `col0` from join/limit will resolve their indexes to the first col0. But actually, the first col0 should resolve to the first col0 of its child(ren). The second should resolve to the second of its child(ren).
This pr aims to solve this issue.
Tests 
Side effects
Documentation …
> planner: refactor Join and Limit's ResolveIndices (#45831)

- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/byte_reader.go
- br/pkg/lightning/backend/external/byte_reader_test.go
- br/pkg/lightning/backend/external/file.go
- br/pkg/lightning/backend/external/file_test.go
- br/pkg/lightning/backend/external/iter.go
- br/pkg/lightning/backend/external/iter_test.go
- br/pkg/lightning/backend/external/kv_reader.go
Add two merge iterators, which are implemented on min-heap.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning/external: port merge iterators 

- br/pkg/lightning/importer/precheck_impl.go
- br/pkg/storage/BUILD.bazel
- br/pkg/storage/azblob.go
- br/pkg/storage/storage.go
- br/pkg/storage/storage_test.go
- br/pkg/task/stream.go
Issue Number: close #46011 
br use the default http client to connect the external storage, which doesn't have enough reuse-connection-pool for each host(the default value is 2). This leads to slow batch files processing and TCP connections exceeding the system configuration limit.
set the `MaxIdleConnsPerHost` as the same as `MaxIdleConns`.
Tests 
before configuration
after configuration
Side effects
Documentation
```release-note
None
```
> br: configure the httpclient for external storage

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #44822
Tests 
Side effects
Documentation
```release-note
None
```
> *: bump client-go to fix #44822

- planner/core/casetest/enforcempp/enforce_mpp_test.go
- planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json
- planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
- planner/core/stats.go
Issue Number: close https://github.com/pingcap/tidb/issues/40146
After the logical plan tree is built, the access paths have been filled;
while in the pre-action of the physical optimization phase, the heuristic rule in datasource.DeriveStats will prune out the hint preferred tiflash read table path, causing `can't find proper physical plan` error
Tests 
Side effects
Documentation
```release-note
planner: fix index heuristic rule will prune out hint preferred tiflash path
```
> planner: fix index heuristic rule will prune out hint preferred tiflash path

- expression/builtin_compare.go
- planner/core/expression_rewriter_test.go
This is an manually cherry-pick of https://github.com/pingcap/tidb/pull/45945
Issue Number: close #38361
Problem Summary: When compare datetime/timestamp column with numeric constant, try convert numeric constant to timestamp datetime, do nothing if conversion failed.
Tests 
Side effects
Documentation
```release-note
None
```
> expression: Fix different behaviors with MySQL when comparing datetime column with numeric constant | tidb-test=pr/2200 (#45945)

- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/dispatcher/dispatcher_manager.go
- disttask/framework/dispatcher/dispatcher_test.go
- disttask/framework/scheduler/manager.go
- domain/domain.go
Issue Number: close #46122
the log of the dispatcher in disttask does not contain any server information
add server info(host+port) for dispatcher log
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: add server info for dispatcher log

- ddl/split_region.go
- session/session.go
Issue Number: close https://github.com/pingcap/tidb/issues/46135
https://github.com/pingcap/tidb/blob/95b4dcce80d3ad4af89bc9813911af94be7f7a82/ddl/split_region.go#L44-L46
https://github.com/pingcap/tidb/blob/95b4dcce80d3ad4af89bc9813911af94be7f7a82/ddl/split_region.go#L121-L123
https://github.com/tikv/pd/blob/346e7716e2598dfba2db6afa73c3731e15449f49/client/client.go#L1403-L1409
```
req := &pdpb.ScatterRegionRequest{
Header:         c.requestHeader(),
Group:          options.group,
RegionsId:      regionsID,
RetryLimit:     options.retryLimit,
SkipStoreLimit: options.skipStoreLimit,
}
```
As you can see from the above code, the tableID passed to `SplitRegions` is the ID of the partitioned table. And we use tableID as `Group` pass to PD. So different partition ID uses …
> ddl, session: using table ID instead of partition ID when calling `SplitRegions`

- br/pkg/task/restore.go
Issue Number: close #45793
When the upstream set the column count limit to any value larger than the default one, the downstream would be not able to restore the data for DDL check error.
use the max value as the default value for br.
Tests 
Side effects
Documentation
```release-note
None
```
> br: adjust default tidb global config for br

- ddl/ddl_worker.go
- ddl/partition.go
- infoschema/builder.go
Issue Number: ref #46125 close #45791
Tests 
Manual test:
Build this PR and use it for starting a cluster `tiup playground --db.binpath ./bin/tidb-server`
and then run tiflash test `sh run-test.sh fullstack-test2/ddl/alter_exchange_partition.test` which no longer fails
Also check the tidb.log that there are no failures loading new schema diffs, so no full schema reloads are needed.
Side effects
Documentation
```release-note
None
```
(Unless 7.4 get released without this fix).
> ddl: Exchange part schema load fix

- br/pkg/task/backup_ebs.go
Issue Number: close #46073 
To make sure TiKV gc and schedule status check can exit in 10 mins.
Tests 
Repro the tikv shutdown at backup execution time, and make sure ebs br backup will fail with timeout.
Side effects
Documentation
```release-note
None
```
> br: avoid possible infinite loop checking tikv gc and scheduling status

- expression/builtin_string.go
- expression/builtin_string_test.go
Issue Number: close #45725 
Tests 
Side effects
Documentation
```release-note
MySQL Compatibility of `WEIGHT_STRING()` was improved by matching the collation.
```
TiDB with this PR:
```
sql> SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;
Query OK, 0 rows affected (0.0011 sec)
sql> SELECT WEIGHT_STRING('aéè€☺');
Field 1
Name:      `WEIGHT_STRING('aéè€☺')`
Org_name:  ``
Catalog:   `def`
Database:  ``
Table:     ``
Org_table: ``
Type:      Bytes
DbType:    VAR_STRING
Collation: binary (63)
Length:    0
Decimals:  31
Flags:     NOT_NULL BINARY 
+------------------------+
| WEIGHT_STRING('aéè€☺') | …
```
> expression: WEIGHT_STRING() collation

- expression/builtin_grouping.go
This typo has been introduced via https://github.com/pingcap/tidb/pull/42464
Problem Summary: Fix typo ref #42464
expression: Replace `initialzied` with `initialized`
Tests 
Side effects
Documentation
```release-note
None
```
> expression: Replace `initialzied` with `initialized`

- br/pkg/restore/data.go
- br/pkg/task/restore_data.go
- br/pkg/utils/backoff.go
- br/pkg/utils/retry.go
Issue Number: close #46181
Now, when TiKV reboots, it is possible to abort the whole restore procedure.
This PR has also introduced a new interface for retrying, `WithRetryV2`, which supports returned value and move the closure to be retried last of the arguments. (So the code will probably be more readable, comparing `WithRetry(ctx, backoffer, func() { /* multi lines */ })` and `WithRetry(ctx, func() { /* multi lines */ }, backoffer)`.
This PR added retry to the `RecoverData` call.
Tests 
```release-note
Make snapshot restoration more robust.
```
> snap_restore: added retry for recovery

- planner/core/debugtrace.go
- server/server_test.go
- server/testdata/optimizer_suite_out.json
Issue Number: close https://github.com/pingcap/tidb/issues/46229
Used fixed TblInfoID in `stabilizeGetStatsTblInfo`.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: use fixed TblInfoID in `stabilizeGetStatsTblInfo`

- br/pkg/backup/client.go
Issue Number: ref #46093
In the previous cherry-pick https://github.com/pingcap/tidb/pull/46217
I didn't notice the subtle difference between master and v6.5 branch.
https://github.com/pingcap/tidb/commit/91f675247d5a763aeac7e2f8232b8fd8986a5917#diff-e611f02c279107dbfa433418c809e99569c0b24c2ea92cc7aef9f7f41fbcc3b9L581 
old version use 
```
idAlloc.NextGlobalAutoID()
```
and master use
```
rowID + 1
```
The semantic is the same, but the tiny code struct change make the previous cherry-pick introduce a bug and break CI.
Tests 
Side effects
Documentation
```release-note
None
```
> pkg/backup: fix test case br_autoid for the previous cherry-pick

- planner/util/BUILD.bazel
- planner/util/path.go
- statistics/debugtrace.go
- statistics/histogram.go
- testkit/BUILD.bazel
- testkit/result.go
- testkit/testutil/BUILD.bazel
- testkit/testutil/handle.go
- timer/api/BUILD.bazel
- timer/api/mem_store.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: use std/slices to replace exp/slices

- ddl/backfilling_scheduler.go
- executor/executor.go
- resourcemanager/pool/workerpool/BUILD.bazel
- resourcemanager/pool/workerpool/workerpool.go
- resourcemanager/pool/workerpool/workpool_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> workerpool: generic result type for worker pool

- executor/index_merge_reader.go
- executor/test/executor/executor_test.go
- executor/test/indexmergereadtest/BUILD.bazel
- executor/test/indexmergereadtest/index_merge_reader_test.go
Issue Number: close #46005
Tests 
Side effects
Documentation
```release-note
None
```
> executor: fix retChk = nil in index_merge_reader

- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
Issue Number: close #46159
Problem Summary: planner: output a warning if plan rebuilding fails when reusing a cached plan
Tests 
Side effects
Documentation
```release-note
None
```
> planner: output a warning if plan rebuilding fails when reusing a cached plan

- go.mod
- statistics/BUILD.bazel
- statistics/cmsketch_bench_test.go
- statistics/handle/BUILD.bazel
- statistics/handle/handle.go
Issue Number: close #46267
Tests 
```
before
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/statistics
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size100
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size100-8              38046         31401 ns/op
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size1000
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size1000-8              6194        180800 ns/op
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size10000
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size10000-8              100      11043109 ns/op
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size100000
BenchmarkMergeGlobalStatsTopNByConcurrencyWithHists/Size100000-8 …
```
> statistics: use goroutine pool to improve performance

- executor/index_lookup_join_test.go
- planner/core/casetest/hint/hint_test.go
- planner/core/logical_plan_builder.go
Issue Number: close #46160
Problem Summary: planner: fix the issue that TIDB_INLJ hint cannot take effect when left joining two sub-queries
planner: fix the issue that TIDB_INLJ hint cannot take effect when left joining two sub-queries
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that TIDB_INLJ hint cannot take effect when left joining two sub-queries

- Makefile
- tests/realtikvtest/importintotest2/BUILD.bazel
- tests/realtikvtest/importintotest2/dummy_test.go
- tests/realtikvtest/importintotest2/main_test.go
- tests/realtikvtest/importintotest3/BUILD.bazel
- tests/realtikvtest/importintotest3/dummy_test.go
- tests/realtikvtest/importintotest3/main_test.go
- tests/realtikvtest/importintotest4/BUILD.bazel
- tests/realtikvtest/importintotest4/dummy_test.go
- tests/realtikvtest/importintotest4/main_test.go
Issue Number: ref #42930
currently, test in real-tikv-test is run in serial, if there're too many test in one directory, test will run slow and delay pr merge, or even timeout
so we add 3 importintotestX into real tikv test, we will split the test later, to avoid test timeout as we will add more test later.
Tests 
Side effects
Documentation
```release-note
None
```
> import into: split real-tikv test

- executor/analyze.go
- Split the `Next` function into small functions
- Used minimal channel size: `concurrency = min(len(tasks), concurrency)`
- Called `e.Ctx().GetSessionVars()` only once
- Used `strings.Join` to generate the warning message
Tests 
Side effects
Documentation
```release-note
None
```
> planner: refactor `Next` function of `AnalyzeExec`

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/localhelper.go
- br/pkg/lightning/backend/local/localhelper_test.go
When lightning runs in physical import mode, it runs this sql query
SELECT REGION_ID, APPROXIMATE_SIZE FROM information_schema.TIKV_REGION_STATUS WHERE TABLE_ID = ?
This call is made by each lightning process in parallel import mode and by multiple worker threads in a lightning process. It can potentially overload the PD if number of regions are too many. However, it appears that this call may be unnecessary since its purpose is to display a warning message and increment a counter in the SplitAndScatterRegionByRanges() function. Considering that lightning physical import always operates on a new table, splitting the new region should not pose any harm.
Issue Number: close #45507
Remove the getRegions call from lightning
Tests 
1. Run lightning in parallel import mode
2. …
> pkg/lightning : remove get_regions call in physical backend

- br/pkg/restore/client.go
- br/tests/br_tiflash/run.sh
- br/tests/run.sh
Issue Number: close https://github.com/pingcap/tidb/issues/46302
1. restore wait tiflash ready need handle partition tables
2. tiflash refresh ticker need 2 seconds to trigger. so make the test sleep 3 seconds.
Tests 
Side effects
Documentation
```release-note
None
```
> br: wait tiflash replicas ready && fix unstable test

- executor/sample.go
- planner/core/casetest/cbotest/cbo_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: use std/slices to replace exp/slices 

- session/session.go
Issue Number: close #46349
Tests 
With this PR:
Side effects
Documentation
```release-note
None
```
> session: set request source to type of the prepared stmt for execute stmt

- disttask/framework/BUILD.bazel
- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/framework_test.go
- disttask/framework/storage/table_test.go
- disttask/framework/storage/task_table.go
Issue Number: close #46261 ref #46258 
see #46261
1. When state transform fails, framework still adds subtasks.
2. can't transform state from cancelling to reverted.(If there are no subtasks for task submitted, this state transform is legal.)
1. When state transform fails, check the affected row cnt to skip adding subtask. This error should not be retryable.
2. When there are no subtasks submitted and the task is canceled, the state transform will be canceling--->reverting--->reverted. Remove the old fast path: canceling--->reverted.
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: fix wrongly add subtask when state transform fail

- statistics/handle/cache/internal/lfu/BUILD.bazel
- statistics/handle/cache/internal/lfu/lfu_cache.go
- statistics/handle/cache/internal/lfu/lfu_cache_test.go
- statistics/handle/cache/internal/testutil/testutil.go
Issue Number: ref #46158
- copy cache item when to evict
- clean code by merging some logic.
I have created a flowchart to facilitate everyone's understanding.
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: improve code to avoid data race

- metrics/grafana/tidb.json
Issue Number: close #45953
Problem Summary: Change PD tso rpc duration to higher percentile.
Tests 
1. create a new cluster
2. check the grafana
Side effects
Documentation
```release-note
None
```
> metrics: change PD tso rpc duration to higher percentile

- sessionctx/binloginfo/binloginfo.go
Issue Number: close #28659
Catch both send and receive large binlog error.
Tests 
Side effects
Documentation
```release-note
None
```
> binlog: fix the wrong fatal error when binlog is too large

- planner/core/logical_plan_builder.go
- planner/core/planbuilder.go
Issue Number: close #46311
Use empty slices to init `PlannerSelectBlockAsName` to avoid panic when dereferencing.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix potential panic when generating hints in statement summary

- parser/mysql/const.go
This reverts commit a55d19635632e181e0db24aebb2ee092f90a154b.
Issue Number: ref #7968
#42560 was reverted in #44744 as we decided to wait until #45650 was merged, and that's now the case.
Tests 
Side effects
Documentation
```release-note
The MySQL version number reported by TiDB was updated to 8.0.11
```
> parser: Update ServerVersion to 8.0.11

- planner/cardinality/BUILD.bazel
- planner/cardinality/histogram.go
- planner/cardinality/pseudo.go
- planner/cardinality/row_count_column.go
- planner/cardinality/row_count_index.go
- planner/cardinality/selectivity.go
- planner/cardinality/selectivity_test.go
- planner/cardinality/testdata/cardinality_suite_out.json
- planner/cardinality/trace.go
- planner/core/find_best_task.go
- planner/core/logical_plans.go
- planner/core/stats.go
- server/testdata/optimizer_suite_out.json
- statistics/BUILD.bazel
- statistics/column.go
- statistics/debugtrace.go
- statistics/handle/handletest/BUILD.bazel
- statistics/handle/handletest/handle_test.go
- statistics/histogram.go
- statistics/index.go
- statistics/statistics_test.go
- statistics/table.go
Issue Number: ref #46358
Problem Summary: Move the Selectivity function from the stats package into cardinality package
**No logical change, just some code movement.**
Follow with https://github.com/pingcap/tidb/pull/46359
Move the Selectivity function from the stats package.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: Move the Selectivity function from the stats package into cardinality package

- session/bootstrap_test.go
Issue Number: close #46385
This issue arose after #45465,  and #28555 caused it.
After #45465, `runawayWatchSyncLoop` will do `ExecRestrictedSQL` which will get the domain from the session, so `domainMap` will get or create it. #28555 deletes the store before closing the domain, which causes runawayWatchSyncLoop create a new Domain. So the domain created in `TestBootstrapWithError` can not become DDL owner and finish `bootstrap`.
We don't need to delete the store from `domainMap` because we will do it in `Domain.Close`. 
Tests 
Side effects
Documentation
```release-note
None
```
> test: remove useless code

- planner/core/casetest/testdata/plan_suite_out.json
- planner/core/issuetest/BUILD.bazel
- planner/core/issuetest/planner_issue_test.go
- planner/core/logical_plan_builder.go
- planner/core/planbuilder.go
- planner/core/resolve_indices.go
- planner/core/rule_eliminate_projection.go
- planner/core/stats.go
Issue Number: close https://github.com/pingcap/tidb/issues/45758 , close https://github.com/pingcap/tidb/issues/45805, close https://github.com/pingcap/tidb/issues/45804, close https://github.com/pingcap/tidb/pull/46311
Problem Summary: cherry pick [#45831](https://github.com/pingcap/tidb/pull/45831), [#45824](https://github.com/pingcap/tidb/pull/45824) and https://github.com/pingcap/tidb/pull/46312 for hot-fix branch
Tests 
Side effects
Documentation
```release-note
None
```
> planner: cherry-pick #45824, #45831 and #46312 | tidb-test=pr/2207

- docs/tidb_http_api.md
- server/handler/BUILD.bazel
- server/handler/tests/http_handler_test.go
- server/handler/upgrade_handler.go
- server/http_status.go
Issue Number: close https://github.com/pingcap/tidb/issues/46424
* Update `/upgrade?op={op}` to `/upgrade/{op}` and add related doc
* Fix a minor doc issue
After this PR:
Tests 
Side effects
Documentation
```release-note
None
```
> *: update the HTTP API about "upgrade" and fix a minor doc issue

- planner/cardinality/BUILD.bazel
- planner/cardinality/cross_estimation.go
- planner/cardinality/join.go
- planner/cardinality/ndv.go
- planner/core/exhaust_physical_plans.go
- planner/core/logical_plans.go
- planner/core/plan.go
- planner/core/plan_cost_ver1.go
- planner/core/stats.go
- planner/core/task.go
- planner/property/stats_info.go
Issue Number: ref #46358
Problem Summary: Move the Selectivity function from the stats package into cardinality package
**No logical change, just some code movement.**
Follow with https://github.com/pingcap/tidb/pull/46359
Move the Selectivity function from the stats package.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: Move some NDV and join estimation functions from the physical-optimization package into cardinality package

- autoid_service/autoid.go
- keyspace/keyspace.go
- meta/autoid/autoid.go
- meta/autoid/autoid_service.go
Fix the prefix of auto id service etcd path.
Issue Number: ref https://github.com/pingcap/tidb/issues/46457
Tests 
If set keyspace-name:
If not set keyspace-name:
```release-note
autoid_service: fix etcd path prefix in keyspace scenario
```
> autoid_service: fix etcd path prefix in keyspace scenario

- domain/domain.go
- infoschema/cache.go
- infoschema/test/cachetest/cache_test.go
correct the wrong timestamp in schema cache to make it useful
Issue Number: close #46325 
try to update the timestamp of the existing schema cache when the timestamp is fetched
Tests 
Side effects
Documentation
```release-note
None
```
> schema cache: fix wrong timestamp in schema cache

- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/rollingback.go
- parser/model/ddl.go
- parser/model/ddl_test.go
- util/logutil/log.go
- util/logutil/log_test.go
- util/logutil/main_test.go
Issue Number: close #46441, ref #46071
After this PR, we can trace the ddl worker logs by `conn` or `session_alias` field to figure out where this ddl job come from, for example:
```
TiDB root@127.0.0.1:test> set @@session.tidb_session_alias="alias123";
Query OK, 0 rows affected
Time: 0.002s
TiDB root@127.0.0.1:test> create table t1(a int);
Query OK, 0 rows affected
Time: 0.040s
```
log:
```
[2023/08/28 14:47:58.899 +08:00] [INFO] [ddl_worker.go:615] ["finish DDL job"] [worker="worker 1, tp general"] [category=ddl] [jobID=217] [conn=2097154] [session_alias=alias123] [job="ID:217, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:216, RowCount:0, ArgLen:0, start time: 2023-08-28 14:47:58.883 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
```
Tests 
Side …
> ddl: add `conn` and `session_alias` entry in ddl worker log

- br/pkg/lightning/importer/chunk_process.go
- br/pkg/lightning/importer/get_pre_info.go
- br/pkg/lightning/mydump/loader.go
- br/pkg/lightning/mydump/parser.go
- br/pkg/lightning/mydump/reader.go
- br/pkg/storage/BUILD.bazel
- br/pkg/storage/compress.go
- br/pkg/storage/compress_test.go
- br/pkg/storage/writer.go
- br/pkg/storage/writer_test.go
- dumpling/export/writer_util.go
- executor/importer/chunk_process.go
- executor/importer/import.go
- executor/importer/table_import.go
- executor/load_data.go
Issue Number: ref #42930
add DecompressConfig to external storage to make code to have chance to avoid async decode(default behavior of https://github.com/klauspost/compress) of ZStd, async decode cause data race when decoding of lightning/import into, as it read reader fields too.
Tests 
Side effects
Documentation
```release-note
None
```
> br/lightning: add DecompressConfig to external storage

- ddl/mock.go
- server/handler/upgrade_handler.go
- session/bootstrap.go
- session/bootstraptest/BUILD.bazel
- session/bootstraptest/bootstrap_upgrade_test.go
- session/mock_bootstrap.go
- session/session.go
Issue Number: close https://github.com/pingcap/tidb/issues/46275
* `version < v7.1.0`, we don't support upgrading TiDB without manually Canceling DDL
* `v7.4.0 > version >= v7.1.0`, we support upgrading TiDB without manually Canceling DDL, but we don't support `/upgrade/start` and `upgrade/finish` APIs.
* `version >= v7.4.0`, we support `/upgrade/start` and `upgrade/finish` APIs.
* For compatibility:
* When upgrading from the version in the `v7.4.0 > version >= v7.1.0` range, we do not need to execute `/upgrade/start` before upgrading.
* When upgrading from the `version >= v7.4.0` version, we need to execute `/upgrade/start` before upgrading.
* ddl/mock.go : We move `clusterState` out of `MockStateSyncer`. Because we want to make it unaffected by ddl close.
* Update …
> *: compatible upgrade with previous versions

- planner/cardinality/BUILD.bazel
- planner/cardinality/cross_estimation.go
- planner/core/find_best_task.go
Issue Number: ref #46358
Problem Summary: Move the Selectivity function from the stats package into cardinality package
**No logical change, just some code movement.**
Follow with https://github.com/pingcap/tidb/pull/46359
Move the Selectivity function from the stats package.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: move some estimation functions from the physical-optimization package into cardinality package

- ddl/ddl.go
- ddl/disttask_flow.go
- ddl/disttask_flow_test.go
- tests/realtikvtest/addindextest/add_index_test.go
Issue Number: ref #46258 
Make the code cleaner.
Add realtikv test for non-partition table.
Tests 
Side effects
Documentation
```release-note
None
```
> disttask, ddl: refine disttask_flow

- executor/benchmark_test.go
- executor/hash_table.go
- executor/sort.go
- util/chunk/row_container.go
Issue Number: close #46482
`SortExec` allocates one `chunk` for each row. It will waste a lot of resource of GC and costs a lot of CPU. Some tiny modification can give big performance boost.
For a non-partitioned table: Use the chunk provided from the caller of `Next` directly.
For a partitioned table: allocate a chunk with 1 capacity for each partition and use it to store the row. Reset it after the row is copied to the `req` chunk.
This PR will not use more memory, because these rows definitely need to take some space to store.
It also does some refractor:
1. Rename the `GetSortedRowAndAppendToChunk` to `GetSortedRowAndAppendToChunkIfInDisk`.
2. Add a new function called `GetSortedRowAndAlwaysAppendToChunk`
Tests
```
BenchmarkSortExec …
```
> executor: pre-alloc chunks to optimize `SortExec` in 

- autoid_service/autoid.go
Issue Number: close #46444 
If the autoid service node is not leader, it should not save the cached id back to tikv.
Tests 
- See the [steps in the comments of #46444](https://github.com/pingcap/tidb/issues/46444#issuecomment-1697132996)
Side effects
Documentation
```release-note
Fix potential 'duplicated entry' error when tidb exit for AUTO_ID_CACHE=1 tables.
The bug could happen when a tidb is the autoid_service leader previously, and exit as non-leader, it stores staled next autoid value to tikv in a force rebase way. If the value is loaded again, the autoid decreases and could cause …
```
> autoid_service: fix potential 'duplicated entry' error when tidb exit for AUTO_ID_CACHE=1 tables

- planner/core/plan_cache.go
- sessionctx/variable/tidb_vars.go
Issue Number: close #36598
Problem Summary: planner: disable non-prep plan cache by default
Non-Prep plan cache causes some extra memory usage, to make the default behavior more stable, disable this feature by default and let users turn on this feature manually if they need.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: disable non-prep plan cache by default

- autoid_service/autoid.go
Issue Number: close #46444
Hotfix for v6.5.3, cherry-pick https://github.com/pingcap/tidb/pull/46445 and https://github.com/pingcap/tidb/pull/46526
Tests 
Side effects
Documentation
```release-note
None
```
> autoid_service: fix potential 'duplicated entry' error when tidb exit for AUTO_ID_CACHE=1 tables #46445

- ddl/tests/adminpause/BUILD.bazel
- ddl/tests/adminpause/pause_cancel_test.go
- ddl/tests/adminpause/pause_resume_test.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: faster adminpause test

- autoid_service/autoid.go
Issue Number: close #46545
After https://github.com/pingcap/tidb/pull/39041 the row id and auto increment id use different key.
Here IncrementID should be used.
Tests 
Follow the step in issue https://github.com/pingcap/tidb/issues/46545
It's not easy to integration test for this, since the bug need a tidb restart to trigger.
After the autoid service initialized, the cached value is used and the code logic does not go the buggy line.
https://github.com/pingcap/tidb/pull/46550/files#diff-617839a099f419c84781f44a2286d763780a446a701eac0a440c7c579378706cR457-R462
Side effects
Documentation …
> autoid_service: fix the result of NextGlobalAutoID() for AUTO_ID_CACHE=1

- br/tests/br_300_small_tables/run.sh
Issue Number: close https://github.com/pingcap/tidb/issues/46561
Problem Summary: Sometimes, when the backupsize is exactly an integer, it can cause the test script to receive a null value and unexpectedly exit.
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix unstable test br_300_small_tables

- planner/core/integration_test.go
- planner/core/plan_cost_ver2.go
- planner/core/plan_cost_ver2_test.go
Issue Number: close #43285
Problem Summary: planner: adjust N used in TopN cost formula based on the total number of rows
planner: adjust N used in TopN cost formula based on the total number of rows
Tests 
Side effects
Documentation
```release-note
None
```
> planner: adjust N used in TopN cost formula based on the total number of rows

- planner/core/casetest/integration_test.go
- planner/core/find_best_task.go
- planner/util/fixcontrol/get.go
Issue Number: close #45132
Problem Summary: planner: introduce a new empirical rule into the Skyline pruning
Add a new empirical rule to the Skyline pruning: If x's range row count is significantly lower than y's, for example, 1000 times, we think x is better than y and prune y from the candidate.
Use fixcontrol to control this behavior.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: introduce a new empirical rule into the Skyline pruning

- domain/BUILD.bazel
- domain/domain.go
- infoschema/cache.go
- infoschema/cache_test.go
- meta/meta.go
- structure/string.go
- structure/type.go
Issue Number: ref #43481
Problem Summary: cherry-pick:
- https://github.com/pingcap/tidb/pull/42083
- https://github.com/pingcap/tidb/pull/42745/files
- https://github.com/pingcap/tidb/pull/46326
Tests 
Side effects
Documentation
```release-note
None
```
> schema cache: record the ddl timestamp and associate schema cache with the timestamp for stale read (#42083)

- session/session.go
- sessionctx/sessionstates/BUILD.bazel
- sessionctx/sessionstates/session_states_test.go
- sessionctx/sessionstates/session_token_test.go
Issue Number: close #46216
If the user has `RESTRICTED_VARIABLES_ADMIN` when SEM is enabled, the invisible session variables should also be migrated.
1. Compare the restricted session variable values with the global or default one
2. If they are different and the user has `RESTRICTED_VARIABLES_ADMIN`, migrate the variable
3. If they are different but the use doesn't have `RESTRICTED_VARIABLES_ADMIN`, report an error
Other:
- Remove the check of `sv.HasInstanceScope()` just in case some variables may have both instance and session scopes.
Tests 
Side effects
Documentation
```release-note
None
```
> session, sessionctx: show restricted session variables in `show session_states`

- DEPS.bzl
- go.mod
- go.sum
- session/session.go
- session/test/session_test.go
- store/copr/coprocessor.go
Issue Number: close #46514
Update client-go which will attach the request source with retry info for KV requests. This PR set the required options for coprocessor to enable the extra retry info.
Tests 
Side effects
Documentation
```release-note
None
```
> client-go: attach request source with retry info for coprocessor

- ddl/ddl_tiflash_api.go
- ddl/tests/tiflash/BUILD.bazel
- ddl/tests/tiflash/ddl_tiflash_test.go
- domain/infosync/tiflash_manager.go
Issue Number: close #45859
In `pollAvailableTableProgress`, iterator of `UpdatingProgressTables` may not be advanced under several errors.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: Advance iterator when skip handling TiFlash tables

- ddl/constant.go
- disttask/framework/proto/task.go
- disttask/framework/storage/task_table.go
- session/bootstrap.go
- session/bootstrap_test.go
- session/bootstraptest/BUILD.bazel
- session/bootstraptest/bootstrap_upgrade_test.go
We need a field to record the subtask execution statistic(for example, affected row count). Basically, there are three options:
1. Add a field `row_count INTEGER` to `tidb_background_subtask`.
2. Serialize the `row_count` in `meta BLOB` of `tidb_background_subtask`.
3. Add a field `summary JSON` to `tidb_background_subtask`.
For option 1,  it is not extensive to collect more execution statistic. For option 2, it is not convenient to collect the information without deserializing the whole `meta` blob value.
Option 3 is a better choice since we make json functions GA in TiDB v6.5.0.
Example usage:
```sql
mysql> show create table tidb_background_subtask;
+-------------------------+----------------------------------------------------------------------- …
```
> bootstrap: add summary field for system table `tidb_background_subtask`

- executor/importer/BUILD.bazel
- executor/importer/import.go
- executor/load_data.go
- server/server_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46081
manually cherry-pick https://github.com/pingcap/tidb/pull/46082
Tests 
Side effects
Documentation
```release-note
None
```
> executor: optimize load data assignment expression

- Makefile
- disttask/framework/BUILD.bazel
- disttask/framework/dispatcher/BUILD.bazel
- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/dispatcher/dispatcher_test.go
- disttask/framework/framework_ha_test.go
- disttask/framework/framework_test.go
- disttask/framework/mock/scheduler_mock.go
- disttask/framework/scheduler/BUILD.bazel
- disttask/framework/scheduler/interface.go
- disttask/framework/scheduler/manager.go
- disttask/framework/scheduler/manager_test.go
- disttask/framework/scheduler/scheduler.go
- disttask/framework/scheduler/scheduler_test.go
- disttask/framework/storage/table_test.go
- disttask/framework/storage/task_table.go
- disttask/importinto/dispatcher_test.go
- domain/infosync/mock_info.go
Problem Summary: This PR adds a simple mechanism to cancel existed subtask.
Dispatcher: 
1. fetches `liveNodes` from etcd every `DefaultLiveNodesCheckTick` ticks  in `handleRunning`.
2. lazily fetched `taskNodes` in `handleRunning` as a local cache.
3. If some of `taskNodes` are absent from `liveNodes`, it is marked as failure. And random nodes `liveNodes` will replace them. It is done by `UpdateFailedSchedulerIDs`. The local cache is also updated.
Scheduler:
1. starts a background task every `Run(..)` for checking if the scheduler has been canceled by dispatcher. If so, call `runtimeCancel`.
Tests 
-  3 subtasks
- 4 nodes. 3 nodes are hung up, then the task is forwarded to the rest nodes and executed successfully.
- 30 nodes. 3 nodes are hung up, then the task is …
> disktask: replace failure nodes with alive ones 

- planner/core/BUILD.bazel
- planner/core/logical_plans_test.go
- planner/core/rule_generate_column_substitute.go
- planner/core/rule_generate_column_substitute_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/42788
currently Expression.Hashcode() functionality is only used in some limited comparison cases, so lazy computation is necessary.
Say memory formular for every DNF item is m(?)
```
OR                 root node                 hashcode mem consumption: 
(a  OR)                                       m(a) + m(child) = m(a) + m(b) + m(c) + ... m(y) + m(z)
(b  OR)
(c  OR)
(d  OR)
(e  OR)
(f  OR)                         m(f) + m(child) = m(f) + m(x) + m(y) + m(y)  
(x  OR)                      m(x) + m(child) = m(x) + m(y) + m(y)  
(y   z)                    m(y);  m(z);      
total: m(a)+m(b)*2+m(c)*3+ ....+m(x)*(n-1)+m(y)*n+m(z)*n, assume the tree depth is n.
```
from the case above, when computing the hashcode …
> planner: don't recompute the hashcode when generated column substitution doesn't happen

- WORKSPACE
Issue Number: close #46660
Tests 
Side effects
Documentation
```release-note
None
```
> bazel: rules_proto use mirror to download

- WORKSPACE
- executor/aggfuncs/func_max_min.go
- executor/aggfuncs/func_max_min_test.go
- expression/builtin_compare.go
- expression/builtin_compare_vec_generated.go
- expression/builtin_other_vec_generated.go
- expression/generator/compare_vec.go
- expression/generator/other_vec.go
- store/mockstore/unistore/cophandler/topn.go
- types/compare.go
- types/datum.go
- util/chunk/compare.go
- util/ranger/points.go
Tests 
Side effects
Documentation
```release-note
None
```
> *: use cmp.Compare to replace types.Compare

- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/storage/task_table.go
Problem Summary: When dispatcher fails, the new dispatcher will pick up the running task while not invoking `onNextStage`. In this case, we need to fallback to task table for `taskNodes`.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix taskNodes temporarily

- br/pkg/lightning/backend/external/split_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46678
`splitKeys` can be empty.
Tests 
manually specify the seed
```
func TestGeneralProperties(t *testing.T) {
seed := time.Now().Unix()
rand.Seed(uint64(1693902578))
t.Logf("seed: %d", seed)
```
Side effects
Documentation
```release-note
None
```
> test: fix an unit test that is too strict

- expression/integration_test/integration_test.go
- types/datum.go
Issue Number: close https://github.com/pingcap/tidb/issues/45410
Tests 
Side effects
Documentation
```release-note
None
```
> expression: fix wrong result for unsigned non-const int cmp const duration

- session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46388
The job may be `pausing`, we only check it uses `paused`.
* Using `pausing`  or `paused` to check whether the job is pausing.
* Extract the function of `checkDDLJobState` from the same two pieces of judgment code.
Tests 
Side effects
Documentation
```release-note
None
```
> session: make TestUpgradeWithPauseDDL stable

- util/cgroup/cgroup_cpu_test.go
- util/cpu/BUILD.bazel
- util/cpu/cpu_test.go
Problem Summary: The `TestCPUValue` test case always fails when execute in local machine without `InContainer() == true`.
Tests 
Side effects
Documentation
```release-note
None
```
> tests: check `InContainer()` for `TestCPUValue` and `TestGetCgroupCPU()` test cases

- br/pkg/lightning/importer/check_info_test.go
- br/pkg/lightning/importer/import.go
- br/pkg/lightning/importer/import_test.go
- br/pkg/lightning/importer/precheck.go
- br/pkg/lightning/importer/precheck_impl.go
- br/pkg/lightning/importer/precheck_impl_test.go
- br/pkg/lightning/importer/precheck_test.go
- br/pkg/lightning/importer/table_import_test.go
- br/pkg/lightning/log/log.go
- br/pkg/pdutil/pd.go
- br/tests/_utils/run_services
- br/tests/lightning_pd_leader_switch/config.toml
- br/tests/lightning_pd_leader_switch/data/cpeng-schema-create.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.a-schema.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.a.1.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.a.2.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.a.3.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.b-schema.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.b.1.sql
- br/tests/lightning_pd_leader_switch/data/cpeng.b.2.sql
- br/tests/lightning_pd_leader_switch/run.sh
- br/tests/run_group.sh
Issue Number: close #46688 close #43436
PD nodes may change, so lightning should always try to use latest informtion rather than the addresses in task configuration.
Tests 
Side effects
Documentation
```release-note
None
```
> lightning: always get latest PD leader when access PD after initialized

- planner/core/prepare_test.go
- util/ranger/ranger.go
This is an manual cherry-pick of #42443
Issue Number: close #42439
Problem Summary: planner: fix incompatible behaviors between prep and non-prep statements when converting date/time values
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix incompatible behaviors between prep and non-prep stateme… | tidb-test=pr/2145

- executor/test/showtest/show_test.go
- parser/types/BUILD.bazel
- parser/types/field_type.go
- parser/types/field_type_test.go
Issue Number: close #46650 
Tests 
Side effects
Documentation
```release-note
Display width deprecation now excludes `tinyint(1)` and types with `ZEROFILL`. This improves compatibility with MySQL Connectors.
```
> parser,config: Correct handling of display width deprecation except for zerofill and tinyint(1)

- executor/BUILD.bazel
- executor/builder.go
- executor/infoschema_reader.go
- executor/infoschema_reader_internal_test.go
- infoschema/tables.go
- infoschema/test/clustertablestest/tables_test.go
- This adds the [`information_schema.CHECK_CONSTRAINTS`  table](https://dev.mysql.com/doc/mysql-infoschema-excerpt/8.1/en/information-schema-check-constraints-table.html) similar to what MySQL 8.0 does.
Note that other databases implement this as well:
```
postgres=# \d information_schema.CHECK_CONSTRAINTS
View "information_schema.check_constraints"
Column       |               Type                | Collation | Nullable | Default 
--------------------+-----------------------------------+-----------+----------+---------
constraint_catalog | information_schema.sql_identifier |           |          | 
constraint_schema  | information_schema.sql_identifier |           |          | 
constraint_name    | information_schema.sql_identifier |           |          | 
check_clause       | …
```
> infoschema,executor: Add CHECK_CONSTRAINTS I_S table

- planner/core/casetest/physicalplantest/physical_plan_test.go
- planner/core/casetest/physicalplantest/testdata/plan_suite_in.json
- planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- planner/core/find_best_task.go
- planner/core/task.go
Issue Number: close https://github.com/pingcap/tidb/issues/46313
Tests 
Side effects
Documentation
```release-note
planner: sink limit down to index merge table side under union and intersection case
```
> planner: sink limit down to index merge table side under union and intersection case

- br/pkg/lightning/backend/local/localhelper_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46783
```
WARNING: DATA RACE
Read at 0x00c000ac1f58 by goroutine 144:
slices.insertionSortCmpFunc[go.shape.*uint8]()
GOROOT/src/slices/zsortanyfunc.go:12 +0xc4
slices.pdqsortCmpFunc[go.shape.*uint8]()
GOROOT/src/slices/zsortanyfunc.go:73 +0x6c8
slices.SortFunc[go.shape.[]*github.com/pingcap/tidb/store/pdtypes.Region,go.shape.*uint8]()
GOROOT/src/slices/sort.go:28 +0xc6
github.com/pingcap/tidb/store/pdtypes.(*RegionTree).ScanRange()
store/pdtypes/region_tree.go:55 +0x7b
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*testSplitClient).ScanRegions()
br/pkg/lightning/backend/local/localhelper_test.go:257 +0x1cf
github.com/pingcap/tidb/br/pkg/restore/split.PaginateScanRegion.func1() …
```
> test: add lock to avoid data race

- ddl/syncer/syncer.go
Issue Number: close #46751
If etcd is not clean successfully, and the tidb is down.
The owner can see an older version with the down tidb-id in ownerCheckAllVersions.
Check if the tidb-id exists in the cluster.
Tests 
Insert code Sleep before owner cleaning etcd mdl info, and kill the tidb when sleeping.
Side effects
Documentation
```release-note
fix a big that DDL may get block if tidb server is killed/restarts
```
> ddl: relax the check in ownerCheckAllVersions

- .codecov.yml
Reverts pingcap/tidb#46180
changes:
- disable report git commit status.
- disable report github checks.
- only keep comments.
- recover `carryforward` for flags.
> CI: disable codecov's reports in commit status and github cheks

- br/pkg/lightning/backend/local/local.go
Issue Number: close #46682
try to solve a flaky test. We shall see if it won't appear in future
Tests 
Side effects
Documentation
```release-note
None
```
> test: close duplicateDB when meet error halfway

- util/memory/meminfo.go
Issue number: close #46761
When VirtualMemory() returns an error, the actual value of `v` is nil, so returning v.Total when err != nil was causing segfaults
Simply return 0 when there is an error instead of trying to dereference nil
Tests 
```release-note
util: memory: fix a bad error handling case which could cause a segmentation fault in case of error
```
> util: memory: fix segfaults in meminfo when VirtualMemory errors

- planner/core/task.go
Issue Number: close #46809
Using nested loop is inefficient when column count is high.
This is a refactoring of `PhysicalTopN#containVirtualColumn`.
At the beginning, we establish a `map` from column Id to `*expression.Column`.
In the main loop, we just check whether the underlying column Id is in the map.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: speed up PhysicalTopN#containVirtualColumn

- Makefile
avoid probably failure in the bazel_check 
Tests 
Side effects
Documentation
```release-note
None
```
> makefile: remove bazel_check before ut

- statistics/BUILD.bazel
- statistics/histogram_bench_test.go
Issue Number: close #46805
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: add historgram bench for MergePartitionHist2GlobalHist

- executor/aggfuncs/func_json_objectagg.go
Issue Number: close #46806
`jsonObjectAgg#MergePartialResult` should return memory delta to the caller.
Currently 0 is always returned.
`memDelta` is returned from `jsonObjectAgg#MergePartialResult`.
Tests 
Side effects
Documentation
```release-note
None
```
> memory: return memory delta from jsonObjectAgg#MergePartialResult

- ddl/tests/adminpause/pause_cancel_test.go
- util/sem/main_test.go
Issue Number: close #46844
Tests 
Side effects
Documentation
```release-note
None
```
> sem: fix goleak

- server/server.go
close pingcap/tidb#31063
cherry-pick from #31081
Issue Number: close #31063
Tests 
Side effects
Documentation
```release-note
None
```
> server: filter the EOF error for normal closed at handshake  (#31081)

- planner/core/casetest/integration_test.go
Issue Number: close #46663
Problem Summary: planner: fix the unstable test `TestFixControl45132`
planner: fix the unstable test `TestFixControl45132`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix the unstable test `TestFixControl45132`

- br/pkg/lightning/backend/external/split_test.go
Issue Number: close #46869
as title
Tests 
Side effects
Documentation
```release-note
None
```
> test: fix rand.Read will generate same key

- ddl/db_partition_test.go
- ddl/ddl.go
- ddl/ddl_api.go
- ddl/ddl_worker.go
- ddl/failtest/fail_db_test.go
- ddl/metadatalocktest/BUILD.bazel
- ddl/metadatalocktest/mdl_test.go
- ddl/partition.go
- ddl/placement_policy_test.go
- ddl/rollingback.go
- executor/insert_common.go
- executor/write.go
- infoschema/builder.go
- parser/model/model.go
- planner/core/integration_partition_test.go
- testkit/testkit.go
- types/parser_driver/value_expr.go
This is an manual cherry-pick of #46533 and https://github.com/pingcap/tidb/pull/45980
Issue Number: close #46492
The main issue was that the values are store in single quoted strings, and when adding them to the parser as parameters, they are quoted again, which issues (ignored) internal warnings, and no matching rows will be found.
Also the check did not handle NULL, so I added proper null-safe comparison.
Tests 
Side effects
Documentation
```release-note
None
```
> *: Exchange partition, fix LIST COLUMNs validation as well as NULL validation (#46533)

- .gitignore
- expression/integration_serial_test/BUILD.bazel
- expression/integration_serial_test/integration_serial_test.go
- expression/integration_test/integration_test.go
- tests/integrationtest/r/expression/issues.result
- tests/integrationtest/t/expression/issues.test
Issue Number: ref #46679
Problem Summary: mysql-tester already supported `sorted_result`, so move more test cases. Total test cases 9.
Tests 
Side effects
Documentation
```release-note
None
```
> expression, tests: move integration tests in `expression` pkg to `tests/integration`

- session/test/variable/variable_test.go
- sessionctx/variable/sysvar.go
Issue Number: ref #46071
after discussing, we need always truncate value when setting `tidb_session_alias` even if the value is not valid.
Tests 
Side effects
Documentation
```release-note
None
```
> variable: always truncate `tidb_session_alias` when it is not a valid value

- bindinfo/tests/BUILD.bazel
- bindinfo/tests/bind_test.go
- planner/core/planbuilder.go
- planner/core/preprocess.go
Issue Number: ref #44298
Problem Summary: planner: fix the issue that binding for `in (?)` cannot work for `in (?,?,?)`
Following https://github.com/pingcap/tidb/pull/44601, fix some compatibility issues.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that binding for `in (?)` cannot work for `in (?,?,?)`

- br/pkg/streamhelper/advancer.go
- br/pkg/streamhelper/advancer_test.go
Issue Number:  ref https://github.com/pingcap/tidb/issues/40759
After PR #45904 merged. advancer resolve lock state set is too frequently. This PR try to correct it.
Tests 
Side effects
Documentation
```release-note
None
```
> br: fix the issue that state not set correctly after resolve locks

- executor/test/partitiontest/partition_test.go
- planner/core/rule_join_elimination.go
- planner/core/testdata/plan_suite_unexported_in.json
- planner/core/testdata/plan_suite_unexported_out.json
- tests/integrationtest/r/explain_easy.result
Issue Number: close #46248 
Previously we check all the referenced columns come from outer table or not, if yes, then we proceed to check whether we can eliminate outer join or not. However, when there is no column referenced from outer table and inner table, e.g. SELECT 1 FROM R LOJ S ON x=y, there is no column matching with outer table columns, we decided that we can't eliminate outer join, which is incorrect.
This patch fixes above issue by checking as long as there is no column referenced from inner table, we should continue to next step to see whether we can remove outer join or not, instead of bailing out quickly.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: remove outer join on unique keys when there is no column referenced

- planner/core/expression_rewriter.go
- planner/core/expression_rewriter_test.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
Issue Number: close https://github.com/pingcap/tidb/issues/46666
Support the behavior:
> Any statement containing a string literal of the form _utf8mb4'some text' without a COLLATE clause.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: support `default_collation_for_utf8mb4` for _utf8mb4'text'

- ddl/index.go
- ddl/ingest/backend_mgr.go
- ddl/ingest/mock.go
- ddl/stage_scheduler.go
- tests/realtikvtest/addindextest/integration_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46656
Tests 
- [] No code
Side effects
Documentation
```release-note
None
```
> rc: resource name support import into

- executor/index_merge_reader.go
- executor/test/indexmergereadtest/index_merge_reader_test.go
Tests 
Side effects
Documentation
```release-note
planner: remove useless todo comment and fix some typos for index merge
```
> planner: remove useless todo comment and fix some typos for index merge

- OWNERS_ALIASES
- autoid_service/OWNERS
Signed-off-by: wuhuizuo <wuhuizuo@126.com>
Issue Number: ref #46911
Tests 
Side effects
Documentation
```release-note
None
```
> autoid_service: setup OWNERS file for reviewing assigning

- parser/mysql/charset.go
- server/conn.go
- tests/integrationtest/r/collation_misc_disabled.result
- tests/integrationtest/r/collation_misc_enabled.result
- tests/integrationtest/t/collation_misc.test
- types/etc.go
- types/etc_test.go
- util/collate/collate.go
Issue Number: close #46690
This PR fixed three problems:
1. Add `utf8mb4_0900_bin` to the collation to id map in the `parser/mysql`. Without this field, it'll be converted to `utf8mb4_bin` (the default collation) when it's serialized into protobuf.
2. Fix the `IsBinCollation` for `utf8mb4_0900_bin`.
3. Make sure the `utf8mb4_0900_bin` doesn't need restore.
The composition of these three bugs make the behavior really weird.
1. When writing the index, because `IsBinCollation` is false while `NeedRestoreData` is true, it will write the original data into the index value.
2. When decoding the restore data (in unistore or tikv), the collation is `utf8mb4_bin` (because of the first problem), so it tries to decode an integer from the `RestoreData`, and it'll definitely fail. See …
> types, collation: utf8mb4_0900_bin shouldn't have RestoreData

- tests/realtikvtest/testkit.go
Issue Number: close #46432
Fix the flaky goroutine leak test by ignoring the backoff function.
Tests 
Side effects
Documentation
```release-note
None
```
> test: fix flaky goleak test by ignoring the backoff function

- br/pkg/lightning/log/log.go
I forget to revert `tidbLogCfg.Level = "debug"` in https://github.com/pingcap/tidb/pull/46726
Tests 
Side effects
Documentation
```release-note
None
```
> log: revert mistakenly change library logger level to debug

- bindinfo/handle.go
- session/bootstrap.go
- session/bootstrap_test.go
Issue Number: close #44298
Problem Summary: planner: update binding's original_sql when upgrading
Following https://github.com/pingcap/tidb/pull/46896, update binding's original_sql when upgrading to make it compatible.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: update binding's original_sql when upgrading

- ddl/partition.go
- ddl/schema_test.go
- ddl/tests/partition/db_partition_test.go
Issue Number: close #46881
AutoIDs was not copied over to the new table id.
Notice, that there may still be issues with concurrent use of nonclustered ids and auto_increment ids during Delete Reorganization phase, but that would need a solution for #46904 to be fixed.
Copy the AutoID from the old table id to the new table id.
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: Fix AutoID for Add/Remove partitioning

- statistics/histogram.go
- util/chunk/chunk.go
- util/chunk/row.go
Issue Number: close https://github.com/pingcap/tidb/issues/46804
Tests 
before: 
```
$  go test -run=^$ -bench=BenchmarkMergePartitionHist2GlobalHist -benchmem github.com/pingcap/tidb/statistics  
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/statistics
BenchmarkMergePartitionHist2GlobalHist/Size1000-8                     14          75695795 ns/op        45846930 B/op     782037 allocs/op
BenchmarkMergePartitionHist2GlobalHist/Size10000-8                     1        1669962708 ns/op        601507720 B/op  10201122 allocs/op
BenchmarkMergePartitionHist2GlobalHist/Size100000-8                    1        24380916125 ns/op       5989421424 B/op 101480169 allocs/op
PASS
ok      github.com/pingcap/tidb/statistics      30.015s
```
after:
```
$ go test -run=^$ …
```
> statistics: add pool in the buildBucket4Merging to reuse datum

- disttask/framework/dispatcher/dispatcher_manager.go
- disttask/framework/framework_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46928
Problem Summary: It is difficult to predict mock duration
remove unstable part
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix flaky test TestGC

- domain/domain.go
Issue Number: close #46948
In the previous code, the ttlJobManager is created and started in a background goroutine:
https://github.com/pingcap/tidb/blob/a7e3176f30e0dff6d993eda0ddd1b64776ad98f6/domain/domain.go#L2917-L2929
It has a probability that if a test runs very fast and `domain.Close` will be called before `do.ttlJobManager.Store(ttlJobManager) `. The ttlJobManager will not stop anymore.
In this PR, we just move ttlJobManager's create and start out of the goroutine.
Tests 
Side effects
Documentation
```release-note
None
```
> ttl: fix potential go leak for ttl in test

- statistics/handle/handle.go
- statistics/handle/update.go
Problem Summary: planner: refactor to make `colStatsUsageMap` thread-safe
No logical change, just refactor, create a separate structure for `colStatsUsage`, and hide the lock in it to make it thread-safe.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: refactor to make `colStatsUsageMap` thread-safe

- statistics/handle/handle.go
- statistics/handle/update.go
- statistics/handle/update_list_test.go
Problem Summary: planner: refactor to make tableStatsDelta thread-safe
No logical change, just refactor
Tests 
Side effects
Documentation
```release-note
None
```
> planner: refactor to make `tableStatsDelta` thread-safe

- table/tables/test/partition/partition_test.go
Issue Number: close #46815
Two ways to reproduce the error:
1. run many times, let the competitive occur:
```
$ go test --tags=intest --run="TestExchangePartitionStates" 
```
2.  make the competitive easier to occur: 
```
$ git diff
diff --git a/table/tables/test/partition/partition_test.go b/table/tables/test/partition/partition_test.go
index 2f218db..702a0d1 100644
--- a/table/tables/test/partition/partition_test.go
+++ b/table/tables/test/partition/partition_test.go
@@ -749,7 +749,7 @@ func TestExchangePartitionStates(t *testing.T) {
logutil.BgLogger().Info("Got state", zap.String("State", s))
break
}
-                       gotime.Sleep(50 * gotime.Millisecond)
+                       gotime.Sleep(1 * gotime.Millisecond)
}
}
waitFor("t", "write only", 4)
$ go test …
```
> partition: fix unstable test TestExchangePartitionStates

- statistics/cmsketch.go
Tests 
Side effects
Documentation
```release-note
None
```
> statistics: use slices.BinarySearchFunc to simple TopN.FindTopN

- executor/analyze.go
- executor/test/analyzetest/analyze_test.go
- statistics/handle/handle.go
Issue Number: ref #46992
Please see the issue.
Add some logs that will only be printed in this flaky test case.
Tests 
Side effects
Documentation
```release-note
None
```
> executor, statistics: add logs in failpoint to debug flaky test

- ddl/index.go
- ddl/tests/partition/db_partition_test.go
Issue Number: close #46907
Tests 
Side effects
Documentation
```release-note
None
```
> ddl: fix drop multiple partitions with global index

- statistics/handle/ddl.go
- statistics/handle/gc.go
- statistics/handle/handle.go
Problem Summary: planner: use the session pool to execute SQLs in `statshandler`
Tests 
Side effects
Documentation
```release-note
None
```
> planner: use the session pool to execute SQLs in `statshandler`

- br/pkg/storage/gcs.go
- br/pkg/storage/storage.go
Issue Number: close #47022 
the custom http client for gcs should has the credential, but currently we don't provide it.
don't use the custom http client for gcs
Tests 
>   
Side effects
Documentation
```release-note
None
```
> br: not use the custom http client for gcs

- ddl/ddl.go
- ddl/ddl_worker.go
- ddl/job_table.go
- session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close #46920
1. Check once for every DDL job.
2. Check if waitSchemaChange is returned correctly.
Tests 
Pass the test described in the issue
Side effects
Documentation
```release-note
fix a bug that MDL may progress unexpectedly or block forever
```
> ddl: fix a bug that MDL may progress unexpectedly or block forever

- executor/lockstats/BUILD.bazel
- executor/lockstats/lock_stats_executor.go
- executor/lockstats/lock_stats_executor_test.go
- executor/lockstats/unlock_stats_executor.go
- statistics/handle/handletest/lockstats/BUILD.bazel
- statistics/handle/handletest/lockstats/lock_partition_stats_test.go
- statistics/handle/handletest/lockstats/lock_table_stats_test.go
- statistics/handle/lock_stats_handler.go
- statistics/handle/lockstats/BUILD.bazel
- statistics/handle/lockstats/lock_stats.go
- statistics/handle/lockstats/lock_stats_test.go
- statistics/handle/lockstats/unlock_stats.go
- statistics/handle/lockstats/unlock_stats_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/46351
See https://github.com/pingcap/tidb/pull/46768#discussion_r1327064524
- Changed the `tids` to `tidAndNames` to make the relationship more explicit.
- Printed all table names.
- Stabilized the warning message.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: add better API and better logs for lock stats

- executor/analyze_global_stats.go
- statistics/handle/ddl.go
- statistics/handle/globalstats/global_stats.go
- statistics/handle/handle.go
- Added more comments.
- Change `isIndex` to bool
Tests 
> - Only update comment
Side effects
Documentation
```release-note
None
```
> statistics: add comments and change `isIndex` to bool

- executor/BUILD.bazel
- executor/analyze_global_stats.go
- statistics/fmsketch.go
- statistics/handle/ddl.go
- statistics/handle/globalstats/global_stats.go
- statistics/table.go
Issue Number: close #47071
Tests 
before:
after:
>   
Side effects
Documentation
```release-note
None
```
> statstics: reuse fmsketch

- expression/integration_test/BUILD.bazel
- expression/integration_test/integration_test.go
- planner/core/rule_aggregation_push_down.go
Issue Number: close https://github.com/pingcap/tidb/issues/41986
Tests 
Side effects
Documentation
```release-note
planner: fix group_concat function couldn't resolve the index of its order-by item
```
> planner: fix group_concat function couldn't resolve the index of its order-by item

- metrics/grafana/tidb.json
Issue Number: close #47113
tidb cluster label should be `tidb_cluster`, not `cluster_id`
Tests 
>   
Side effects
Documentation
```release-note
None
```
> metric: fix label name

- executor/internal/mpp/local_mpp_coordinator.go
- kv/mpp.go
- store/copr/batch_coprocessor.go
- store/copr/mpp.go
Issue Number: close #47093
This is part of tiflash resource control.
Add resource group name to cop/batchCop/MPP req when dispatching to tiflash.
Tests 
1. setup tidb cluster with one or more tiflash instances
2. run following sqls:
```
create resource group rg1 ru_per_sec = 1000 burstable = false;
create resource group rg2 ru_per_sec = 1000 burstable = false;
create resource group rg3 ru_per_sec = 1000 burstable = false;
set tidb_allow_mpp=0;
set @@tidb_allow_tiflash_cop = 1;
set @@tidb_allow_batch_cop = 0;
explain analyze select /*+ resource_group(rg1) */ * from t1;
set tidb_allow_mpp=0;
set @@tidb_allow_tiflash_cop = 1;
set @@tidb_allow_batch_cop = 2;
explain analyze select /*+ resource_group(rg2) */ * from t1;
```
3. check tiflash log, we can see resource group is …
> *: add resource group name when dispatch req to tiflash

- statistics/handle/gc.go
- statistics/handle/handletest/lockstats/BUILD.bazel
- statistics/handle/handletest/lockstats/lock_partition_stats_test.go
- statistics/handle/handletest/lockstats/lock_table_stats_test.go
- statistics/handle/lockstats/unlock_stats.go
- statistics/handle/lockstats/unlock_stats_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/46351
- We can clean up lock info when the table or partition is deleted now.
- Added more tests for the partitioned table.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: clean up lock info when the table is deleted

- ddl/db_rename_test.go
- ddl/ddl_worker.go
- ddl/tests/fk/foreign_key_test.go
Issue Number: close #47064
it seems lead to ApplyDiff twice for the first table of rename table list.
https://github.com/pingcap/tidb/blob/4bd39b5fd712f06b1c4594418a88ee1740f6f1aa/ddl/ddl_worker.go#L1381C2-L1381C2
Tests 
>   
Side effects
Documentation
```release-note
None
```
> ddl: fix duplicate inforSchema information of rename tables

- statistics/handle/globalstats/global_stats.go
just remove useless code
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: remove useless copy in the MergePartitionStats2GlobalStats

- README.md
Add activity trends widget to README
No
Only updated README.md
Tests 
>   
Side effects
Documentation
```release-note
None
```
> README: add repo activity trends widget

- bindinfo/BUILD.bazel
- bindinfo/session_handle_test.go
- bindinfo/tests/BUILD.bazel
- bindinfo/tests/bind_test.go
- tests/integrationtest/r/bindinfo/bind.result
- tests/integrationtest/r/bindinfo/session_handle.result
- tests/integrationtest/t/bindinfo/bind.test
- tests/integrationtest/t/bindinfo/session_handle.test
Issue Number: close #47124
Problem Summary: Move 12 test cases.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> bindinfo, tests: move IT test cases in bindinfo to `tests/integrationtest`

- executor/bind.go
- planner/core/plan_test.go
- sessionctx/variable/setvar_test.go
- util/hint/hint_processor.go
Issue Number: close #46958, close #46888
The explain stmt will enter the Optimize twice. Make the func `AddSetVarHintRestore` add the already changed value into the restore map.
Tests 
Side effects
Documentation
```release-note
None
```
> planner: EXPLAIN will make SET_VAR not SQL level

- br/pkg/lightning/backend/external/engine.go
- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/common/ingest_data.go
When scan region, one IngestData may be assigned to multiple regionJob if the key ranges of IngestData belongs multiple regions. And we will call `Finish()` for each of regionJob. But we have put `m.memBuf.Destroy()` in `Finish()` so the data slice will be sent back to buffer pool and be reused while other regiobJob still reads it.
Add `IncRef()` as a reference count, but not easy to use.
Tests 
>   
test it in a large cluster test
Side effects
Documentation
```release-note
None
```
> lightning: fix forgetting multiple regionJob use same IngestData

- ddl/backfilling_read_index.go
- tests/realtikvtest/addindextest/add_index_test.go
Issue Number: close #47164
`BackendCtx.Register` reocrd the concurrency. If it exceeds 16, an error will be reported.
Reset this counter every time a subtask is finished.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> ddl: fix unexpected concurrency exceed quota during adding index

- planner/core/find_best_task.go
- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
- planner/core/plan_cache_utils.go
- sessionctx/variable/session.go
Issue Number: close #44830
Problem Summary: planner: plan cache supports Batch/PointGet converted from (primary keys) in ((...), ...)
Tests 
Side effects
Documentation
```release-note
None
```
> planner: plan cache supports Batch/PointGet converted from (primary keys) in ((...), ...) 

- executor/BUILD.bazel
- executor/analyze_global_stats.go
- statistics/handle/ddl.go
- statistics/handle/globalstats/global_stats.go
- statistics/handle/handle.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: remove useless partition stats cache

- br/pkg/lightning/backend/local/localhelper.go
Issue Number: ref #46203
Lightning try to scatter all the regions and at the end it backoff and retry it again. It causes few issues
1. If we are hiting a store limit, than further scatter regions cause unnecessarily load on PD. 
2. Regions can be skewed as stores are allocated based on number of scatter operation scheduled. It doesn't take into number of scatter operations cancelled because of store limit.
I am proposing the change similar to tikv go client which doesn't retry and back off after scattering all the regions. 
https://github.com/tikv/client-go/blob/a0ac170698524cbf20a869cb3471e969608d599a/tikv/split_region.go#L198
Tests 
I tested the similar logic in 6.5 and 6.6 by using the below steps
1. Set store limit to 16
2. Parallel import and verify that regions are …
> pkg/lightning: retry individual scatter region

- ddl/backfilling_operators.go
Issue Number: ref #45719 
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask/ddl: change memory quota for writer

- executor/internal/mpp/local_mpp_coordinator.go
- store/copr/mpp.go
Issue Number: close #47274
Tests 
1. tiup start cluster
2. connect to tidb and run a query and cancel it
3. check tiflash log, we can see resource group name in cancel request.
>   
Side effects
Documentation
```release-note
None
```
> *: add resource group name for cancel/establish req for tiflash

- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/dispatcher/dispatcher_manager.go
- disttask/framework/proto/task.go
- disttask/framework/scheduler/manager.go
- disttask/framework/scheduler/scheduler.go
remove scheduler/dispatcher id from logs, the server log itself will identify where we're in
avoid stack overriding in scheduler.OnErr using errors.Trace
some comments
Tests 
run import into task, check logs
```
[2023/09/25 19:48:00.041 +08:00] [INFO] [dispatcher.go:481] [onNextStage] [task-id=90001] [task-type=ImportInto] [current-step=3] [next-step=4]
....
[2023/09/25 19:47:59.141 +08:00] [INFO] [scheduler.go:131] ["scheduler run a step"] [task-id=90001] [step=3] [concurrency=4]
```
>   
Side effects
Documentation …
> disttask: remove scheduler/dispatcher id from logs and refinement

- executor/analyze_col_v2.go
- statistics/fmsketch.go
- statistics/row_sampler.go
Issue Number: close #47071
Tests 
>   
Side effects
Documentation
```release-note
None
```
> executor: reuse fm sketch when to analyze

- statistics/handle/globalstats/global_stats.go
Issue Number: ref https://github.com/pingcap/tidb/issues/47219
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: remove useless cache in the MergePartitionStats2GlobalStats

- config/config.go
- tidb-server/main.go
Issue Number: close #47204
In the initial version, the initialization process would include glog. Now, with this update, we have made a few changes. After the main function starts, the ```initflag``` function will be cleared first, and then the program will continue to execute.
Tests 
```
tidb-server --help
-log-file string
log file path
-log-slow-query string
slow query file path
```
>   
Side effects
Documentation
```release-note
None
```
> cli: avoid glog flags inject into tidb cli

- session/bootstrap.go
Issue Number: ref #47311 close #47299
Forget to call upgradeToVer176
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask: fix upgrade

- OWNERS_ALIASES
- br/OWNERS
Fixes #47130
Issue Number: close #47130
Tests 
>   
Side effects
Documentation
```release-note
None
```
/type enhancement
/component br
> br: add `OWNERS` file

- executor/infoschema_reader.go
- statistics/handle/autoanalyze/BUILD.bazel
- statistics/handle/autoanalyze/autoanalyze.go
- statistics/handle/bootstrap.go
- statistics/handle/cache/BUILD.bazel
- statistics/handle/cache/statscacheinner.go
- statistics/handle/ddl.go
- statistics/handle/extstats/BUILD.bazel
- statistics/handle/extstats/extended_stats.go
- statistics/handle/gc.go
- statistics/handle/handle.go
- statistics/handle/history/BUILD.bazel
- statistics/handle/history/history_stats.go
- statistics/handle/storage/read.go
- statistics/handle/storage/save.go
- statistics/handle/update.go
- statistics/handle/usage/index_usage.go
- statistics/handle/util/util.go
Problem Summary: planner: unify ways to execute SQLs in stats_handle package
planner: unify ways to execute SQLs in stats_handle package
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: unify ways to execute SQLs in stats_handle package

- executor/BUILD.bazel
- executor/analyze_global_stats.go
- statistics/handle/ddl.go
- statistics/handle/globalstats/global_stats.go
- statistics/handle/handle.go
Issue Number: close #47247
we need to handGlobalStats with index and without index. so we need to add cache here. to avoid load data twice.
Tests 
the benchmark result is from benchbot. 
this pr: 416.19412s
the old: 479.01944s
>   
Side effects
Documentation
```release-note
None
```
> statistics: add cache for handleGlobalStats's load data

- br/pkg/lightning/importer/precheck_impl_test.go
- br/pkg/task/stream.go
- br/pkg/utils/cdc.go
- br/pkg/utils/cdc_test.go
- executor/importer/precheck_test.go
Issue Number: close https://github.com/pingcap/tiflow/issues/9807
1. cdc will generate `__backup__` changefeed key after upgrade from v6.1. and the check cannot handle it right now.
1. make `check-requirements` can skip the cdc change feed check.
2. fix the issue that br can handle migration key in etcd after cdc upgrade from v6.1.
Tests 
>   
Side effects
Documentation
```release-note
fix the issue that br can handle migration key in etcd after cdc upgrade from v6.1.
```
> br: check the correct changefeed info when restore/import data

- server/internal/packetio.go
- server/internal/packetio_test.go
This was `flate.HuffmanOnly` (-2) to 6 to match what MySQL does.
Note that `compress/flate` doesn't define a const for level 6.
Issue Number: close #47278 
Related: https://github.com/pingcap/tidb/pull/36780
Tests 
>   
Side effects
Documentation
```release-note
The compression level for zlib level was updated to match the compression level of MySQL
```
> server: Change zlib compression level

- ddl/ddl.go
- sessionctx/variable/BUILD.bazel
- sessionctx/variable/sysvar.go
Issue Number: close #47224
Remove the redundant logs.
These logs are added for debugging UTs and understanding the logic of "Enable MDL". They are quite meaningless, so should be removed from the released codes. I forgot to remove them in https://github.com/pingcap/tidb/pull/45980.
It only affects 6.5.
Tests 
>
> ddl, sysvar: remove `Switch EnableMDL` logs

- disttask/framework/dispatcher/dispatcher_manager.go
short circuit when no work to do to avoid log too much
Tests 
- change interval manaully to 5 seconds, checks logs.
>   
Side effects
Documentation
```release-note
None
```
> disttask: fix too much log on cleanup

- statistics/cmsketch.go
- util/chunk/compare.go
Issue Number: ref #47219
Golang's binarysearch does not check boundary conditions first, so we check boundary conditions first to quickly terminate the binary search.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: quickly exit FindTopN and LocateBucket

- statistics/builder.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: reuse datum when to  buildHist

- statistics/cmsketch.go
- statistics/handle/globalstats/global_stats.go
- statistics/table.go
Issue Number: ref #47219
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: reduce the copy when to merge global status

- planner/core/plan_cache.go
- planner/core/plan_cache_test.go
- planner/core/plan_cacheable_checker.go
- planner/core/plan_cacheable_checker_test.go
- planner/optimize.go
Issue Number: close #47133
Problem Summary: planner: fix wrong output alias names when using non-prep cache with point plans
planner: fix wrong output alias names when using non-prep cache with point plans
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: fix wrong output alias names when using non-prep cache with point plans

- executor/executor.go
- server/conn.go
- util/misc.go
Issue Number: close #47398
Use `FormatSQL` to replace `QueryStrForLog`.
Tests 
* start a cluster.
* `set global tidb_query_log_max_len = 5`
* make a dispatched error with long statement.
* check the logs.
```
mysql> select * from abfdasf;
ERROR 1146 (42S02): Table 'test.abfdasf' doesn't exist
[2023/10/04 17:03:33.495 -07:00] [INFO] [conn.go:1098] ["command dispatched failed"] [conn=2097154] [session_alias=] [connInfo="id:2097154, addr:[::1]:52348 status:10, collation:utf8mb4_0900_ai_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql=selec(len:21)] [txn_mode=PESSIMISTIC] [timestamp=0] [err="[schema:1146]Table 'test.abfdasf' doesn't exist"]
```
>   
Side effects
Documentation
Please refer to [Release …
> *: make tidb_query_log_max_len could affect more logs

- executor/test/splittest/split_table_test.go
- planner/core/planbuilder.go
Issue Number: close #47350
"Key 'primary' doesn't exist in table 'test'" should be reported like int type clustered index.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: disallow split clustered index with SPLIT TABLE .. INDEX

- OWNERS_ALIASES
Issue Number: ref #47088
Add members to `sig-approvers-distsql`:
- cfzjywxk
- benjamin2037
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: add members to owner alias `sig-approvers-distsql`

- types/json_binary.go
- util/codec/codec_test.go
Issue Number: close #46233 close #45686
`x == int64(float64(x))` is not a safe way to judge whether an integer can be converted to float64. I judged whether this integer has too long fraction part to tell whether it's safe to be converted to float64.
I changed the condition to convert to float64 for integers in json.
Tests 
>   
```release-note
Fix the issue that the hash join result of large integers and float is incorrect.
```
> types, json: use a more accurate way to judge whether int64/uint64 can be converted to float64

- ddl/ddl_worker.go
Issue Number: close #47455
Tests 
run SQL below,
```
create table t ( obj json, arr json, nil json, t json, f json, i json, ui json, f64 json, str json, nul json );
insert into t values ('{\"obj\": 100}', '[-1, 0, 1]', 'null', 'true', 'false', '20200826173501', '20201123', '20200826173501.123456', '\"2020-08-26 17:35:01.123456\"', null);
alter table t modify obj datetime;
```
`alter table` return error directly, no more sleep.
>   
Side effects
Documentation
```release-note
None
```
> ddl: no more sleep when meets nonRetryable error

- executor/analyze.go
Issue Number: close #47464
There is a concurrent mode in handleResultsError, but if the number of tasks is small, there is actually no need to open too many goroutines
Tests 
>   
Side effects
Documentation
```release-note
None
```
> executor: AnalyzePartitionConcurrency is not more than number of task

- ddl/placement/constraints.go
- ddl/placement/rule.go
- ddl/placement/rule_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46304
Currently, all `FOLLOWER_CONSTRAINTS` will set the role in the rule to be `voter`. It can cover major scenarios and reduce the user's burden. but in some scenarios cannot cover, like:
there are three az, zone1, zone2, zone3. the user wants the replicas in zone 1 and zone 2 can be the leader, and normal situations, the leader should be placed in zone 1, if zone 1 is gone, the leader is better in zone 2. and zone3 reject be the leader,  zone 3 can be seen as a backup zone, it's not used to serve.
maybe we can enhance the `FOLLOWER_CONSTRAINTS`, like
```
Dictionary:  e.g. {"+region=us-east": 2, "+region=us-west,#evict-leader": 1}
```
`#evict-leader` explains voters should be followers, and reject becoming …
> placement: supports follower role with evict-leader hint

- br/pkg/restore/ingestrec/ingest_recorder.go
- br/pkg/stream/rewrite_meta_rawkv.go
Issue Number: close #47451 
currently the `addindex` ddl job's `Args[0]` might be `[]int64` instead of `int64`.
retry to parse by `[]int64` when failed to parse by `int64`.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> br: modify how to parse the add index job args

- expression/builtin_time.go
Issue Number: ref #47308 
Change log level to debug for
```
[2023/09/22 22:58:36.055 +00:00] [WARN] [builtin_time.go:6639] [calAppropriateTime] [minTime=2023/09/22 22:57:36.055 +00:00] [maxTime=2023/09/22 22:58:36.055 +00:00] [minSafeTime=2023/09/22 22:57:35.289 +00:00]
```
Tests 
Side effects
Documentation
```release-note
None
```
> util: change log level to debug calculating stale read ts

- br/pkg/restore/client.go
- executor/load_stats.go
- executor/plan_replayer.go
- planner/core/casetest/cbotest/cbo_test.go
- statistics/handle/BUILD.bazel
- statistics/handle/dump.go
- statistics/handle/dump_test.go
Issue Number: close #47183
Problem Summary: planner: speed up the process of loading partition table stats
planner: speed up the process of loading partition table stats
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: speed up the process of loading partition table stats

- ddl/backfilling_dist_scheduler.go
- disttask/framework/handle/handle.go
- disttask/framework/scheduler/manager.go
- `WaitGlobalTask` may exit before cleaning up the global task, which can cause unexpected behavior.
- The error returned by `scheduler.Init()` should persist to subtask table instead of constantly retrying.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask: persist business error to subtask table

- ddl/multi_schema_change.go
- ddl/multi_schema_change_test.go
Issue Number: ref #41602
#47135 changes the order of adding indexes, which is unexpected.
```
mysql> alter table t add index i(a), add primary key (a);
Query OK, 0 rows affected (4.82 sec)
mysql> show create table t;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                      |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> ddl: preserve index order for multi-schema change

- session/bootstraptest/bootstrap_upgrade_test.go
- session/mock_bootstrap.go
- tidb-server/main.go
Issue Number: close https://github.com/pingcap/tidb/issues/47493
After https://github.com/pingcap/tidb/pull/47205, we ran the TiDB binary with `--with-mock-upgrade true` failed.
Add `with-mock-upgrade` to FlagSet in initFlag.
Tests 
After this PR, we do `./tidb-server --with-mock-upgrade true` successfully.
>   
Side effects
Documentation
```release-note
None
```
> session, tidb-server: fix `with-mock-upgrade` doesn't work

- ddl/column.go
- ddl/ddl_api.go
Issue Number: ref https://github.com/pingcap/tidb/issues/46258 https://github.com/pingcap/tiflow/issues/9850
export method for dm to judge ddl type
Tests 
>   
Side effects
Documentation
```release-note
None
```
> ddl: export method for needChangeColumns

- planner/core/plan_test.go
- planner/optimize.go
Issue Number: close https://github.com/pingcap/tidb/issues/45957
Fixed the explain panic issue when using the VALUES statement.
Tests 
>   
Side effects
Documentation
```release-note
Fixed the Explain panic problem when using the VALUES statement
```
> planner: fix explain panic when using VALUES statement

- executor/analyze_col_v2.go
Start the merge operation early to reduce memory consumption.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> analyze: merge task and send task concurrently

- disttask/framework/dispatcher/dispatcher.go
- disttask/framework/dispatcher/dispatcher_manager.go
- disttask/importinto/job.go
- disttask/importinto/subtask_executor.go
Issue Number: close #47520
fix panic on refresh task fails or returns nil which makes dispatcher.Task nil
move delRunningTask of manager into defer
Tests 
return `nil, nil`, `nil, err`, `task, nil` on GetGlobalTaskByID, check dispatcher.Task is always not nil, and updated correctly.
>   
Side effects
Documentation
```release-note
None
```
> distask: fix panic on refresh task fails or returns nil

- executor/plan_replayer.go
Issue Number: close #46474 
If the zip file dumped by `plan replayer dump` is unzipped and zipped again, a normal compression software will always add entries for directories, such as `stats/`... They are just directories and cannot be read, so we should skip them to avoid returning error.
Tests 
> The basic function of `plan replayer` has been covered by existing tests. It's hard to add tests for this PR as it needs cooperation with other compression software. I've considered to add an existing `zip` file as test data, but we cannot promise that a dumped file can be decoded by any version of TiDB right? so it'll need to be updated in the future 🤔 .
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-note …
> executor, planner: fix plan_replayer zip format

- DEPS.bzl
- go.mod
- go.sum
Signed-off-by: husharp <jinhao.hu@pingcap.com>
Issue Number: close #47468
The core question is getting safe ts in client-go
- we introduce `PD API` to not execute `go func which for KV request`, resulting in not updating `safeTSMap`. 		 
- `updateMinSafeTS` relies on  `safeTSMap` which makes sense(because actually, we can call `updateMinSafeTS` to `kvReuqestUpdater`[to indicate func base]).
- And we need to update `minsafeTS` to make sure when API fails we can fall back to the original way which is by kv request.
- But the core problem is:  **`updateMinSafeTS` will return `maxUnit64` when the first kv request returns 0 and then although `PD API` returns correctly[maybe kv is not initialized], TS can not change `maxUnit64`.**
- to resolve this question, we need to regard …
> gomod: fix MinSafeTS might be set to MaxUint64 permanently

- br/pkg/lightning/backend/backend.go
- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/engine.go
- br/pkg/lightning/backend/external/engine_test.go
- br/pkg/lightning/backend/external/split.go
- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/common/engine.go
- br/pkg/lightning/common/ingest_data.go
- disttask/importinto/planner.go
- disttask/importinto/proto.go
- disttask/importinto/scheduler.go
- When the external engine contains less than 1000 files, we can open multiple iterators to concurrently read the data in given key ranges.
- When the region size is larger than 2*96MB, generate region jobs per 96MB KV pairs so the large region still have enough concurrency
Tests 
>   
Side effects
Documentation
```release-note
None
```
> external engine: support concurrent read and split into smaller data

- executor/analyze.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> executor: reduce the length of channel to avoid OOM

- testkit/BUILD.bazel
- testkit/testkit.go
- testkit/testkit_test.go
Issue Number: close #47365 
Run multiple statements in testkit will cause resource leak. The record set is not closed properly and the memtracker on the statement context is not detached.
Drain out and close the record set before run the next statement. This PR doesn't return the resultset of the following statements. It kept the original behavior.
Tests 
>   
```release-note
None
```
> testkit: fix memtracker leak in testkit

- disttask/importinto/BUILD.bazel
- disttask/importinto/dispatcher.go
- disttask/importinto/dispatcher_test.go
Issue Number: close #47546
Tests 
add some wait when write&ingest tikv, run global sort integration test, see we switched tikv mode
```
[2023/10/11 15:57:13.589 +08:00] [INFO] [tikv_mode.go:60] ["switch tikv mode"] [task-id=1] [mode=Import]
```
>   
Side effects
Documentation
```release-note
None
```
> importinto: switch tikv mode on write&ingest step

- sessionctx/variable/tidb_vars.go
Issue Number: close #47549
Tests 
>   
Side effects
Documentation
```release-note
*: set default tidb_analyze_partition_concurrency as 2
```
> *: set default tidb_analyze_partition_concurrency as 2

- br/pkg/lightning/backend/local/checksum.go
Issue Number: close #47566
// When there are many pending compaction bytes, TiKV might not respond within 1m,
// and report "rpcError:wait recvLoop timeout,timeout:1m0s", and retry might
// time out again.
// so we enlarge it to 30 * 20 = 10 minutes.
for import into, user can workaround by set session var `tidb_backoff_weight`, but have to waste a round of import
Tests 
run import into integration test, check that the weight is current value
> - only enlarge default timeout setting.
>   
Side effects
Documentation
```release-note
None
```
> lightning/import: enlarge default checksum timeout

- OWNERS_ALIASES
- br/cmd/tidb-lightning-ctl/OWNERS
- br/cmd/tidb-lightning/OWNERS
- br/pkg/lightning/OWNERS
Issue Number: close #47301
- Add alias `sig-approvers-lightning` in `/OWNERS_ALIASES` file.
- Add `OWNERS` file to folders:
- `br/pkg/lightning`
- `br/cmd/tidb-lightning`
- `br/cmd/tidb-lightning-ctl`
Tests 
>   
Side effects
Documentation
```release-note
None
```
> lightning: add `OWNERS` in folders owned by lightning

- statistics/handle/storage/BUILD.bazel
- statistics/handle/storage/read.go
Issue Number: close #47570
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: check Killed in the TableStatsFromStorage

- domain/domain_sysvars.go
- statistics/handle/bootstrap.go
- statistics/handle/cache/BUILD.bazel
- statistics/handle/cache/bench_test.go
- statistics/handle/cache/statscache.go
- statistics/handle/cache/statscacheinner.go
- statistics/handle/handle.go
- statistics/handle/handle_hist.go
- statistics/handle/handletest/handle_test.go
- statistics/handle/handletest/statstest/stats_test.go
- statistics/handle/history/history_stats.go
- statistics/handle/storage/gc.go
- statistics/handle/storage/read.go
- statistics/handle/storage/update.go
- statistics/handle/util/interfaces.go
Problem Summary: planner: capsulate stats cache behind an interface
planner: capsulate stats cache behind an interface
No logical change, just code movement and refactor.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: capsulate stats cache behind an interface

- statistics/cmsketch.go
- statistics/handle/storage/read.go
the first one is in the DecodeTopN. DecodeTopN called TopNFromProto. it will copy again.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: avoid copy twice when to decode the topn

- metrics/grafana/tidb.json
Issue Number: close https://github.com/pingcap/tidb/issues/47585
panel id is same
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask: fix grafana panel id duplicate

- executor/analyze_col_v2.go
- executor/analyze_utils.go
- executor/set_test.go
- sessionctx/variable/sysvar.go
- sessionctx/variable/tidb_vars.go
…idb_build_stats_concurrency as 2
Issue Number: close #47583
Tests 
>   
Side effects
Documentation
```release-note
None
```
> variable: add variable to control the concurrency of buildSampling 

- ddl/placement/bundle.go
- ddl/placement/common.go
- ddl/placement_policy.go
- ddl/placement_policy_test.go
- executor/show_placement.go
- executor/simple.go
- parser/ast/misc.go
- parser/parser.y
- parser/parser_test.go
- planner/core/planbuilder.go
Issue Number: close https://github.com/pingcap/tidb/issues/29677 ref https://github.com/pingcap/tidb/issues/45384
unify the entry of placement rule to tidb. supports setting global/meta range placement policy by tidb. Example:
```
// policy about 5 replicas
create placement policy `mypolicy` FOLLOWERS=4;
// set global range to 5 replicas
ALTER RANGE global PLACEMENT POLICY mypolicy
// set meta range to 5 replicas
ALTER RANGE meta PLACEMENT POLICY mypolicy
// remove and reset to default
ALTER RANGE global PLACEMENT POLICY default
```
Tests 
Documentation
```release-note
*: supports setting …
```
> *: supports setting global/meta range placement policy

- executor/sort.go
- util/chunk/row_container.go
- util/chunk/row_container_test.go
Issue Number: close #47538
- Add base struct `baseSpillDiskAction` for `SpillDiskAction` and `SortAndSpillDiskAction`, so `SortAndSpillDiskAction` don't have to hold a useless `RowContainer`
- Add a new interface SpillHelper and use a common function (a *baseSpillDiskAction) action(t *memory.Tracker, spillHelper SpillHelper) to unify the code of (a *SpillDiskAction) Action(t *memory.Tracker) and (a *SortAndSpillDiskAction) Action(t *memory.Tracker)
- Add recover function in `c *SortedRowContainer) Sort()` to avoid panic
Tests 
>   
Side effects
Documentation …
> executor: Fix crash during sort spill

- planner/core/optimizer.go
- planner/core/plan_stats.go
- planner/core/rule_aggregation_elimination.go
- planner/core/rule_aggregation_push_down.go
- planner/core/rule_aggregation_skew_rewrite.go
- planner/core/rule_build_key_info.go
- planner/core/rule_column_pruning.go
- planner/core/rule_constant_propagation.go
- planner/core/rule_decorrelate.go
- planner/core/rule_derive_topn_from_window.go
- planner/core/rule_eliminate_projection.go
- planner/core/rule_generate_column_substitute.go
- planner/core/rule_join_elimination.go
- planner/core/rule_join_reorder.go
- planner/core/rule_max_min_eliminate.go
- planner/core/rule_partition_processor.go
- planner/core/rule_predicate_push_down.go
- planner/core/rule_predicate_simplification.go
- planner/core/rule_push_down_sequence.go
- planner/core/rule_resolve_grouping_expand.go
- planner/core/rule_result_reorder.go
- planner/core/rule_semi_join_rewrite.go
- planner/core/rule_topn_push_down.go
This PR mainly add the interaction rule framework in new rule engine. It doesn't be enabled by default.
The interaction rule will be trigger when it satisfies following conditions:
1. The related rule has been trigger and changed the plan
2. The interaction rule is enabled
The `optimizer` interface of logical rule has been changed. This PR add a new bool return value which used to flag whether plan changed or not during this logical rule.
If the logical rule changed the plan, it will return true. 
In this PR, I just add a new framework and not enable the interaction progress. So all of rules plan changed flag is false.
Issue Number: close #43360
Tests 
> The basic function of all logical rule has been covered by existing tests. Because this is an architectural adjustment, …
> planner: Refactor framework of rule engine.(Support interaction rule of new rule engine )

- pkg/statistics/histogram.go
Tests 
before:
```
$ go test -run=^$ -bench=BenchmarkMergePartTopN2GlobalTopNWithHists -benchmem github.com/pingcap/tidb/statistics/handle/globalstats
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/statistics/handle/globalstats
BenchmarkMergePartTopN2GlobalTopNWithHists/Size100-8               79554             13026 ns/op             120 B/op          2 allocs/op
BenchmarkMergePartTopN2GlobalTopNWithHists/Size1000-8               9308            129048 ns/op             120 B/op          2 allocs/op
BenchmarkMergePartTopN2GlobalTopNWithHists/Size10000-8               710           1495563 ns/op             120 B/op          2 allocs/op
BenchmarkMergePartTopN2GlobalTopNWithHists/Size100000-8               60          18915999 ns/op …
```
> statistics: add branch check for BinarySearchRemoveVal

- pkg/executor/analyze.go
- pkg/executor/analyze_worker.go
- pkg/statistics/analyze.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> executor: reuse the memory from analyze result

- br/pkg/backup/schema.go
- br/pkg/restore/client.go
Issue Number: ref #47596 
the tidb session is not thread safe
add lock
Tests 
>   
Side effects
Documentation
```release-note
None
```
> br: lock the call of update stats meta

- Makefile.common
Issue Number: close #47646
fix enterprise build does not display `Enterprise Extension Commit Hash` issue.
Tests 
1. make enterprise-server
2. ./bin/tidb-server -V displays:
```
./bin/tidb-server -V
Release Version: v7.5.0-alpha-117-g308974cf57
Edition: Enterprise
Git Commit Hash: 308974cf5722d2f24669a3e3b10e90272572f08f
Git Branch: enterprise-fix-print
UTC Build Time: 2023-10-16 05:01:12
GoVersion: go1.21.0
Enterprise Extension Commit Hash: eac31cedd37f7143483f4b387c38fc2e8638b379
```
>   
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write …
> extension: fix enterprise git commit hash display in `tidb-server -V`

- Makefile
- Makefile.common
Issue Number: close #47646
1. fix `make enterprise-server` failed
2. detect `pkg/extension/enterprise/.git` to check whether we can get enterprise git hash because `.git/modules/extension/enterprise` always exits even folder`pkg/extension/enterprise` not exist
Tests 
>   
Side effects
Documentation
```release-note
None
```
> extension: fix make enterprise-server failed

- pkg/statistics/handle/history/history_stats.go
Issue Number: close #47649
Set the json block of RecordHistoricalStatsToStorage to be smaller. Previously, the json block was 6MB, and with the other columns added, it would exceed the limit.
Tests 
we update tidb at 15:30, we cannot see fail after 
>   
Side effects
Documentation
```release-note
None
```
> statistics: fix entry too large when to save historical stats

- pkg/disttask/framework/scheduler/scheduler.go
When subtask == nil but task is running, sleep for a while.
Very likely to happen when some tidb node is the tail, and some tidb node already processed all subtasks.
Tests 
The cop request qps is really high.
>   
Side effects
Documentation
```release-note
None
```
> disttask: add sleep when subtask == nil

- pkg/executor/BUILD.bazel
- pkg/executor/analyze.go
- pkg/executor/analyze_global_stats.go
- pkg/executor/analyze_worker.go
- pkg/statistics/handle/BUILD.bazel
- pkg/statistics/handle/ddl.go
- pkg/statistics/handle/dump.go
- pkg/statistics/handle/dump_test.go
- pkg/statistics/handle/globalstats/BUILD.bazel
- pkg/statistics/handle/globalstats/global_stats.go
- pkg/statistics/handle/handle.go
- pkg/statistics/handle/util/util.go
Issue Number: ref https://github.com/pingcap/tidb/issues/46905
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: move some functions into global stats

- build/BUILD.bazel
- build/linter/constructor/BUILD.bazel
- build/linter/constructor/analyzer.go
- build/linter/constructor/analyzer_test.go
- build/linter/constructor/testdata/src/github.com/pingcap/tidb/util/linter/constructor/BUILD.bazel
- build/linter/constructor/testdata/src/github.com/pingcap/tidb/util/linter/constructor/constructorflag.go
- build/linter/constructor/testdata/src/t/BUILD.bazel
- build/linter/constructor/testdata/src/t/construct.go
- build/nogo_config.json
- pkg/sessionctx/stmtctx/BUILD.bazel
- pkg/sessionctx/stmtctx/stmtctx.go
- pkg/util/linter/constructor/BUILD.bazel
- pkg/util/linter/constructor/constructorflag.go
Issue Number: close #47660
Add a linter to ensure the `stmtCtx` is constructed correctly, at least the `AppendWarning` of `TypeCtx` is set.
A simple linter, as documented in the comment, it will detect the following cases:
1. Create struct directly, like `SomeStruct{}` or `&SomeStruct{}`.
2. Create struct with `new`: `new(SomeStruct)`
3. Struct literal in slice or other struct: `[]SomeStruct{{}}, []*SomeStruct{{}}`
4. Define variables through `var`: `var a SomeStruct`.
5. Implicit zero value in other struct literal: `type OtherStruct struct{SomeStruct}; other := OtherStruct{}`
After this PR is merged, the `StmtCtx` can only be constructed through:
```go
stmtctx.NewStmtCtx()
stmtctx.NewStmtCtxWithTimeZone()
```
Or `Reset` an existing `StmtCtx`.
Though we still exposed the …
> linter: setup a linter to validate constructor

- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/cache/BUILD.bazel
- pkg/statistics/handle/cache/statscache.go
- pkg/statistics/handle/handle.go
- pkg/statistics/handle/storage/BUILD.bazel
- pkg/statistics/handle/storage/gc.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/util/interfaces.go
Problem Summary: planner: move more methods from StatsHandle to its sub-packages
planner: move more methods from StatsHandle to its sub-packages
No logical change, just refactor.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: move more methods from StatsHandle to its sub-packages

- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #47685
Now, the default tidb_build_stats_concurrency is 4. it is too large for 8c machine. It will create 4*2 workers to do analysis. but only 2 workers to write data and release memory.
so we change the default tidb_build_stats_concurrency and is the same as the number of write worker.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> variable: set default tidb_build_stats_concurrency 2

- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/writer.go
- pkg/disttask/importinto/encode_and_sort_operator.go
Issue Number: ref #47572
add more logs to external backend, disable parallel sort to speed up encode&sort
Tests 
with a case of 150g, import takes 58m after vs 70m before, mainly speed up encode&sort step. and CPU curve became more smooth.
after
before
flush log looks like this:
```
[2023/10/16 16:27:57.768 +00:00] [INFO] [writer.go:445] ["flush kv"] [bytes=268339017] [kv-cnt=18160] [stat-size=42504] [sort-time=250.47596ms] [write-time=1.781394854s] [sort-speed(kv/s)=72.5kB] [write-speed(bytes/s)=143.7MiB] [writerID=data/56625710-9837-4c0e-a3f1-b35490f9a008]
[2023/10/16 16:27:57.963 +00:00] [INFO] [writer.go:445] ["flush kv"] [bytes=268339452] [kv-cnt=18160] [stat-size=42504] [sort-time=53.950553ms] [write-time=1.635531465s] [sort-speed(kv/s)=336.6kB] …
```
> importinto: add more logs to external backend, disable parallel sort

- server/conn_stmt_test.go
- session/session.go
close pingcap/tidb#44612
Tests 
>   
Side effects
Documentation
```release-note
None
```
> session: fix the memory tracker leak in prepare binary protocol (#44618)

- pkg/store/gcworker/gc_worker_test.go
Issue Number: ref #47023
#47023 mentions that the test TestLeaderTick is unstable, however I failed to reproduce it locally, and nothing helpful was found in the log of that failure. This PR tries to print the detail of the error when it fails on the same place again.
Tests 
```release-note
None
```
> gc_worker_test: Print error to the failure message when mustGetNone encounters unexpected error

- tests/globalkilltest/Makefile
- tests/graceshutdown/Makefile
Issue Number: close https://github.com/pingcap/tidb/issues/47705
Relate to https://github.com/pingcap/tidb/pull/47123, we need to update build cmds to modify tidb-server src path.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> makefile: update build cmd in graceshutdown & globalkilltest  makefile

- pkg/statistics/handle/autoanalyze/autoanalyze.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: add log to show reason for partition table's auto analyze

- sessionctx/sessionstates/BUILD.bazel
- sessionctx/sessionstates/session_states_test.go
- sessionctx/variable/sysvar.go
Issue Number: close #47665
The configuration for TiDB Cloud dedicated cluster is:
```
require_secure_transport: OFF
ssl_ca : /var/lib/tidb-server-tls/ca.crt
ssl_cert : /var/lib/tidb-server-tls/tls.crt
ssl_key: /var/lib/tidb-server-tls/tls.key
```
We just provide the `ca.crt` file for the the users to connect the TiDB cluster. When `require_secure_transport = OFF`, there is no problem.
**But if the user set the value of require_secure_transport to 'ON', the users can not connect to the cluster anymore!**
This is because the new configuration require the mysql client to pass all `ca.crt` `tls.crt` `tls.key` correctly, while the user only have  the `ca.crt` file.
To prevent the user from losing access of the cluster, we can forbid changing `require_secure_transport` system …
> session/variable: forbid changing @@global.require_secure_transport to 'on' with SEM enabled #47677

- pkg/domain/schema_validator.go
- pkg/metrics/domain.go
- pkg/metrics/grafana/tidb.json
- pkg/metrics/metrics.go
Issue Number: close #47729
Add a metric for lease expired time.
Tests 
tiup playground
explore & edit & export ...
import again & verify the changes ...
>   
Side effects
Documentation
```release-note
None
```
> domain/metrics: add a metric for lease expired time

- pkg/parser/ast/expressions.go
- pkg/planner/core/plan_test.go
- pkg/planner/core/point_get_plan.go
Issue Number: close https://github.com/pingcap/tidb/issues/47445
- do not convert update to point get if the expr has sub-query
- covered the case expr
- covered the parentheses case expr
- covered the parentheses sub-query expr
- covered the sub-query expr (do we really need this? I copied the code from the old code)
Tests 
>   
Side effects
Documentation
```release-note
Fixed TiDB incorrectly converts update statement to point get plan issue
```
> planner: do not convert update to point get if the expr has sub-query

- pkg/ddl/placement_policy_test.go
- pkg/executor/test/admintest/admin_test.go
- pkg/planner/core/plan_test.go
- pkg/statistics/handle/handletest/lockstats/lock_partition_stats_test.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: simple code

- DEPS.bzl
- go.mod
- go.sum
- tests/realtikvtest/sessiontest/session_fail_test.go
cherry-pick #47716
Issue Number: close #47691
related PR: https://github.com/tikv/client-go/pull/1021
Problem Summary: update tikv/client-go to fix batch-client send loop panic issue
Tests 
Side effects
Documentation
- N/A
```release-note
None
```
> *: update tikv/client-go to fix batch-client send loop panic issue (#47716)

- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
Issue Number: close #47593 
forget to add dist_framework_meta when upgrading from version < v7.4 to v7.4 or higher.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask: fix upgrade missing create framework_meta 

- pkg/domain/infosync/info.go
- pkg/executor/infoschema_cluster_table_test.go
- pkg/executor/infoschema_reader_test.go
- pkg/infoschema/tables.go
Issue Number: ref #44827 
Add TiProxy to table `information_schema.cluster_info`.
- Read TiProxy server info from `/topology/tiproxy/xxx/info`. The path for TiDB server info is `/tidb/server/info` but it's duplicated with `/topology/tidb/xxx/info`. I'll just use `/topology/tiproxy/xxx/info` for TiProxy.
- Add TiProxy to table `information_schema.cluster_info`.
Tests 
Before starting TiProxy:
```
mysql> select * from information_schema.cluster_info;
+------+-----------------+-----------------+---------+------------------------------------------+---------------------------+--------------+-----------+
| TYPE | INSTANCE        | STATUS_ADDRESS  | VERSION | GIT_HASH                                 | START_TIME                | UPTIME       | SERVER_ID | …
```
> executor, infoschema: add tiproxy into table `cluster_info`

- pkg/statistics/handle/globalstats/BUILD.bazel
- pkg/statistics/handle/globalstats/global_stats_async.go
- pkg/statistics/handle/globalstats/globalstats_test.go
Issue Number: close #47771
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statstics: correctly handle error when merging global stats

- br/pkg/lightning/backend/local/local.go
Issue Number: close #47781
log error of worker waitgroup if it's not context cancelled
Tests 
temporary change code, send a dummy job in `generateAndSendJob` then wait 5 second, and let `executeJob` always return `the remaining storage capacity of TiKV` error, see we can see the eaten log
```log
[2023/10/19 16:01:56.812 +08:00] [ERROR] [local.go:1677] ["worker meets error"] [error="the remaining storage capacity of TiKV(%!s(MISSING)) is less than 10%; please increase the storage capacity of TiKV
and try again"] [errorVerbose="the remaining storage capacity of TiKV(%!s(MISSING)) is less than 10%; please increase the storage capacity of TiKV and try again\ngithub.com/pingcap/tidb/br/pkg/lightning/b
ackend/local.(*Backend).executeJob\n\t/Users/jujiajia/code/pingcap/tidb/br/pk …
```
> local backend: fix log been eaten when failed on execute region job

- pkg/executor/BUILD.bazel
- pkg/executor/executor_failpoint_test.go
- pkg/store/helper/helper.go
- pkg/store/mockstore/unistore/rpc.go
Issue Number: close #47807
Before:
Related TIDB Log:
```log
tidb.log
9758:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9760:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9762:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9764:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
10034:[2023/10/19 18:11:28.173 +08:00] …
```
> *: handle region error for GetMvccByEncodedKey API

- pkg/statistics/handle/storage/json.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/util/util.go
Issue Number: close #47779
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: check Killed in the GenJSONTableFromStats

- DEPS.bzl
- executor/executor_failpoint_test.go
- go.mod
- go.sum
- store/helper/helper.go
- store/mockstore/unistore/rpc.go
Issue Number: close #47807
Problem Summary: pick #47811
Before:
Related TIDB Log:
```log
tidb.log
9758:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9760:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9762:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9764:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
10034:[2023/10/19 …
```
> *: handle region error for GetMvccByEncodedKey API(#47811)

- pkg/executor/insert_test.go
- pkg/types/convert.go
- pkg/types/convert_test.go
Issue Number: close #47787
Tests 
>   
Side effects
Documentation
```release-note
fix the behavior when inserting a big scientific notation number to keep it same with mysql
```
> types: fix the behavior when inserting a big scientific notation number to keep it same with mysql

- pkg/session/bootstrap.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
- pkg/statistics/handle/globalstats/BUILD.bazel
- pkg/statistics/handle/globalstats/global_stats.go
- pkg/statistics/handle/globalstats/globalstats_test.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/util/interfaces.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: add variable to control async merge global stats

- br/pkg/utils/retry.go
- br/tests/br_full/run.sh
This is an cherry-pick of #47584
Issue Number: ref #47656
Add new appear error in allow list.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> br: retry import sst files on invalidPart error (#47584)

- pkg/ddl/ddl.go
- pkg/ddl/reorg.go
Issue Number: close https://github.com/pingcap/tidb/issues/46306
Ref: https://github.com/pingcap/tidb/pull/45679. Before this PR(#45679 ), we used [startKey, endKey] with endInclude as the table range. After this PR we used [startKey, endKey.next).
We do "add index" on a branch without #45679, then get startKey and endKey with the range [startKey, endKey]. 
Then we do upgrade, we will continue to "add index" in the branch with #45679. And we use [startKey, endKey).
If the old version upgrades to the new version, we add Next to the endKey.
Tests 
deploy v7.1.1+ cluster
`set @@global.tidb_ddl_enable_fast_reorg = 0;`
Create a table and import 3.5 million rows.
Do `alter table t add index idx(a, b);`, and when it backfills 700,000+ indexes, kill the cluster.
Then upgrade this …
> pkg/ddl: fix an issue where endkey usage issues caused index loss

- br/pkg/lightning/backend/kv/session.go
- br/pkg/lightning/backend/tidb/tidb.go
- pkg/ddl/backfilling_scheduler.go
- pkg/executor/executor.go
- pkg/expression/builtin_cast.go
- pkg/planner/core/planbuilder.go
- pkg/sessionctx/stmtctx/stmtctx.go
- pkg/sessionctx/stmtctx/stmtctx_test.go
- pkg/table/column.go
- pkg/types/binary_literal_test.go
- pkg/types/context.go
- pkg/types/context/context.go
- pkg/types/context/context_test.go
- pkg/types/convert.go
- pkg/types/convert_test.go
- pkg/types/datum.go
- pkg/types/datum_test.go
- pkg/util/codec/codec_test.go
- pkg/util/rowcodec/common.go
Issue Number: close #47829
- Replace `FlagClipNegativeToZero` with `FlagAllowNegativeToUnsigned` which has a opposite semantics to make the `StrictFlags` (all-zero value) more strict.
- Introduce `DefaultStmtFlags` with `FlagAllowNegativeToUnsigned` set to 1 to keep it same behavior with old implement.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> types: more strict for `types.StrictFlags`

- pkg/ddl/delete_range.go
Issue Number: close #47825 
delete range drop indices not entirely
drop all the indices if they are global.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> ddl: fix delete range drop indices not entirely

- pkg/statistics/handle/history/history_stats.go
- pkg/statistics/handle/storage/gc.go
- pkg/statistics/handle/storage/json.go
- pkg/statistics/handle/storage/save.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/storage/update.go
- pkg/statistics/handle/util/util.go
Problem Summary: planner: unify the way to handle txn in `statshandle`
planner: unify the way to handle txn in `statshandle`
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: unify the way to handle txn in `statshandle`

- go.mod
- pkg/ddl/placement/bundle.go
- pkg/ddl/placement/bundle_test.go
- pkg/ddl/placement/rule.go
- pkg/ddl/placement/rule_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/47741
Minimal reproduce step 
```
mysql> CREATE PLACEMENT POLICY ssd FOLLOWER_CONSTRAINTS="{+disk=ssd: 1}";
ERROR 1105 (HY000): label constraints with invalid REPLICAS: count of replicas in dict constrains is 1, but got 2: invalid FollowerConstraints
```
skip the checks.
Tests 
```release-note
None
```
> placement: fix the issue cannot create dict follower constraints

- tests/globalkilltest/Dockerfile
- tests/globalkilltest/Makefile
Issue Number: close #47895 
Problem Summary: Global kill e2e test failed
Fix path of LDFLAGS related to path changed by https://github.com/pingcap/tidb/pull/47123.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> tests: fix path of LDFLAGS for global kill e2e test

- pkg/executor/cte.go
- pkg/executor/hash_table.go
- pkg/executor/index_lookup_hash_join.go
- pkg/executor/join.go
- pkg/executor/joiner.go
Issue Number: close https://github.com/pingcap/tidb/issues/47424
The sql will be very slow if there are a lot of matched row for each row from build side in (left) (anti) semi join.
Recognize this case then optimize it.
Tests 
>   
Before
```
mysql> select count(*) from customer a where exists (select 1 from customer b where a.C_NATIONKEY=b.C_NATIONKEY);
+----------+
| count(*) |
+----------+
|   150000 |
+----------+
1 row in set (36.32 sec)
```
After
```
mysql> select count(*) from customer a where exists (select 1 from customer b where a.C_NATIONKEY=b.C_NATIONKEY);
+----------+
| count(*) |
+----------+
|   150000 |
+----------+
1 row in set (0.16 sec)
```
Side effects
Documentation
Please refer to [Release Notes …
> executor: optimize (left outer) (anti) semi join which has no other condition

- pkg/ddl/index.go
Issue Number: close #47902 
reorgCtx for reorgJob is cleaned up since worker is closed when calling isReorgPaused.
Use isReorgRunnable to ignore the check.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> ddl: fix panic in pause

- pkg/ddl/ddl.go
- pkg/ddl/ddl_api.go
- pkg/ddl/reorg.go
- pkg/parser/model/reorg.go
Issue Number: close https://github.com/pingcap/tidb/issues/47912, close https://github.com/pingcap/tidb/issues/47910
After https://github.com/pingcap/tidb/pull/3993, we using `job.Version` like 
```
if job.Version <= currentVersion {
err = w.delRangeManager.addDelRangeJob(ctx, job)
} else {
err = dbterror.ErrInvalidDDLJobVersion.GenWithStackByArgs(job.Version, currentVersion)
}
```
So, when we add the `currentVersion` value(https://github.com/pingcap/tidb/pull/47818) and have two versions TiDB has an issue.
Use `ReorgMeta`'s version instead of `Job`'s.
Tests 
* Case 1
deploy v7.1.0 cluster with 2 tidb.
Then upgrade this cluster to master one by one.
**Result**: After this PR, upgrade successfully.
* Case 2(Manual test in https://github.com/pingcap/tidb/pull/47884 )
deploy …
> ddl, parser: fix the DDL job version using issue

- Makefile
Use the `MAKE` variable to call make. This ensures the make we call is the correct one. This is mostly important on systems where `make` isn't GNU make and where make is called via `gmake ...`
https://www.gnu.org/software/make/manual/make.html#MAKE-Variable
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: Makefile: correct calling of make

- pkg/sessionctx/variable/setvar_affect.go
Issue Number: ref #45892 
Problem Summary: fix typo
Tests 
>   
Side effects
Documentation
```release-note
None
```
> sessionctx: fix var typo

- DEPS.bzl
- go.mod
- go.sum
- pkg/executor/chunk_size_control_test.go
- pkg/executor/distsql_test.go
- pkg/store/gcworker/gc_worker_test.go
- pkg/store/mockstore/unistore/tikv/mock_region.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #35418
update client-go to fix #35418
Tests 
> - tests added in client-go side  
Side effects
Documentation
```release-note
None
```
> executor: update client-go to fix #35418

- br/pkg/pdutil/pd.go
- br/pkg/pdutil/pd_serial_test.go
Issue Number: close #47930
http.Client.Do will read the body of request, so the request should not be reused.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> lightning: every HTTP retry should use its own request

- pkg/executor/insert_test.go
- pkg/expression/builtin_cast.go
- pkg/expression/builtin_cast_vec.go
- pkg/types/datum.go
Issue Number: close #47945
Tests 
>   
Side effects
Documentation
```release-note
fix issue that we can insert negative value to unsinged float column sometimes
```
> types: fix issue that we can insert negative value to unsinged float column sometimes

- DEPS.bzl
- pkg/statistics/builder.go
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
Issue Number: close https://github.com/pingcap/tidb/issues/35948
The issue arises when a value appears twice in the topN list, triggering a panic.  The solution involves breaking out of the loop as soon as we find the duplicate value. This bug seems to occur only when the column is of JSON type. Since we haven't been able to reproduce the issue, we've added a warning log to print all topN values, helping us identify the duplicated value.
Tests 
>   
Side effects
Documentation
```release-note …
```
> statistic: fix panic when building topN

- pkg/executor/brie_test.go
- pkg/expression/integration_test/integration_test.go
- pkg/expression/typeinfer_test.go
- pkg/planner/cardinality/selectivity_test.go
- pkg/planner/cardinality/trace_test.go
- pkg/planner/cascades/optimize_test.go
- pkg/planner/cascades/stringer_test.go
- pkg/planner/cascades/transformation_rules_test.go
- pkg/planner/core/logical_plans_test.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/rule_generate_column_substitute_test.go
- pkg/planner/memo/group_test.go
- pkg/util/ranger/bench_test.go
- pkg/util/ranger/ranger_test.go
Issue Number: close #47974 
Problem Summary: The BuildLogicalPlanForTest function returns p.OutputNames()  is never used. we can delete it. 
Remove the second return value of BuildLogicalPlanForTest function. Now it doesn't return types.NameSlice. And modifie the code that references the function。
Tests 
>   
Side effects
Documentation
```release-note
None
```
> enhancement: Modify the BuildLogicalPlanForTest function

- br/pkg/lightning/mydump/loader.go
- pkg/disttask/framework/dispatcher/dispatcher_manager.go
- pkg/disttask/importinto/dispatcher_testkit_test.go
Issue Number: close #47776, #47941
Tests 
>   
Side effects
Documentation
```release-note
None
```
> importinto: fix data race in test

- pkg/executor/analyze.go
- pkg/executor/analyze_col_v2.go
Tests 
before 
after 
>   
Side effects
Documentation
```release-note
None
```
> executor: improve channel length for analyze

- pkg/executor/executor.go
- pkg/sessionctx/variable/session.go
Issue Number: close https://github.com/pingcap/tidb/issues/47979
Tests 
```
tidb> set @@tidb_mem_quota_query=1;
Query OK, 0 rows affected, 1 warning (0.000 sec)
tidb> select sum(a) from t group by a;
ERROR 8175 (HY000): Your query has been cancelled due to exceeding the allowed memory limit for a single SQL query. Please try narrowing your query scope or increase the tidb_mem_quota_query limit and try again.[conn=2097156]
```
>   
Side effects
Documentation
```release-note
None
```
> executor: fix wrong ConnID for query out of memory quota

- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
close pingcap/tidb#39778
Issue Number: close #39778
Updated the bootstrap code to write the `mDDLTableVersion` value into the `mysql.tidb` table.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> session: display mDDLTableVersion in mysql.tidb table

- pkg/types/convert.go
- tests/integrationtest/r/expression/json.result
- tests/integrationtest/t/expression/json.test
Issue Number: close #47864 
Previously, the behavior of casting json string to integers is not consistent with casting normal string to integers. Now they have the same behavior and is compatible with MySQL.
I follow the nearly the same behavior as `builtinCastStringAsIntSig`, but doesn't append any warnings.
Tests 
>   
```release-note
Fix the issue that json string representing a negative value cannot be converted to unsigned integer.
```
> types: fix the behavior of casting json string to integers

- pkg/planner/core/plan_cache_test.go
- pkg/planner/core/plan_cacheable_checker.go
- pkg/planner/util/fixcontrol/get.go
Issue Number: ref #45798
Problem Summary: planner: introduce a new fix-control flag to control whether to cache plans that access generated columns
planner: introduce a new fix-control flag to control whether to cache plans that access generated columns
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: introduce a new fix-control flag to control whether to cache plans that access generated columns

- pkg/statistics/cmsketch.go
- pkg/statistics/handle/globalstats/topn.go
- pkg/statistics/handle/globalstats/topn_bench_test.go
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
- Added some better benchmark tests for merging topN.
- Used 500 topN 
- Skip some values for some partitions 	
- Optimized CheckEmptyTopNs to remove usless count
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: better benchmark tests for merge topN

- pkg/executor/test/tiflashtest/BUILD.bazel
- pkg/executor/test/tiflashtest/tiflash_test.go
- pkg/planner/core/rule_generate_column_substitute.go
Issue Number: close https://github.com/pingcap/tidb/issues/47766
Tests 
>   
Side effects
Documentation
```release-note
planner: fix mpp task spreading blocked by virtual column substitution
```
> planner: fix mpp task spreading blocked by virtual column substitution

- br/pkg/aws/ebs.go
- br/pkg/config/ebs.go
- br/pkg/task/common.go
- br/pkg/task/restore.go
- br/pkg/task/restore_data.go
- br/pkg/task/restore_ebs_meta.go
Issue Number:
close #47271
close #47273 
This PR addresses 2 issues
1. EBS snapshot restore can do FSR based warmup to tikv data volumes. A new parameter of`use-fsr` is introduced to  `br` command. Set it to `true` to use FSR to warmup tikv data volumes.
2. Get rid of unnecessary removal of some users from mysql.user table at the end of restore
Tests 
Run real EBS restore job and check the BR pod log to verify.
>   
Side effects
Documentation
```release-note
None
```
> ebs br: provide fsr warmup to tikv data volumes

- .gitignore
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: Ignore *.log.json files, like tidb-audit.log.json

- pkg/ddl/job_table.go
- pkg/owner/manager.go
- pkg/owner/manager_test.go
- pkg/session/sync_upgrade.go
Issue Number: close https://github.com/pingcap/tidb/issues/47903
` [INFO] [job_table.go:343] ["[ddl] the owner sets owner operator value"] [ownerOp="get upgrading state"]`
The `ownerOp` info doesn't quite match.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: update owner op message

- pkg/executor/ddl.go
- pkg/executor/recover_test.go
- pkg/parser/ast/ddl.go
- pkg/parser/parser_test.go
Issue Number: close #46296
The "RECOVER TABLE BY JOB 0":
1. parser will return no error, jobID set to 0 is allowed
2.  when jobID is 0, function executeRecoverTable treat is as "Recover table tableName"，then call getRecoverTableByTableName, How ever Table is nil.
https://github.com/pingcap/tidb/blob/8d0fdef09869a43ff8d2f14749f7afc38bf56514/executor/ddl.go#L396-L400
```
sql1： RECOVER TABLE BY JOB 0
sql2： RECOVER TABLE tableName
```
The both case paser will set JobID to 0, so can't distinguish them by JobID. 
Change it by Table info, if it is not nil, it is sql2, else sql1.
case Table is nil and JobID is 0 is impossible.
Tests 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-n …
> ddl: fix recover table by JobID bug when JobID is set to 0 tidb-server panic

- pkg/executor/benchmark_test.go
- pkg/executor/hash_table.go
Issue Number: close https://github.com/pingcap/tidb/issues/48082
Reuse chunk for GetMatchedRowsAndPtrs.
Add a new benchmark case.
Tests 
BenchmarkHashJoinExec
```
Old:
go test -benchmem -run=^$ -bench ^BenchmarkHashJoinExec$ github.com/pingcap/tidb/pkg/executor
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/pkg/executor
cpu: 13th Gen Intel(R) Core(TM) i9-13900KF
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0_1],_disk:false)-32                   2         625585277 ns/op        2428636920 B/op   512892 allocs/op
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0],_disk:false)-32                    19          64306968 ns/op        278193261 B/op    112877 allocs/op …
```
> executor: reuse chunk for GetMatchedRowsAndPtrs calls

- pkg/planner/core/casetest/BUILD.bazel
- pkg/planner/core/casetest/plan_test.go
- pkg/planner/core/casetest/testdata/plan_normalized_suite_out.json
- pkg/planner/core/explain.go
Issue Number: close #47634  
After pr:[#38259](https://github.com/pingcap/tidb/pull/38259) queries with the same plan have different plan_digest in information_schema.statement_summary
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: Fix the issue that may generate many plandigests when the inner table is clustered

- pkg/planner/core/integration_test.go
- pkg/planner/core/rule_result_reorder.go
Issue Number: close #45044
Problem Summary: planner: check nil pointer in rule_result_reorder to avoid panic
planner: check nil pointer in rule_result_reorder to avoid panic
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: check nil pointer in rule_result_reorder to avoid panic

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #48107
related pr: https://github.com/tikv/client-go/pull/1046
Problem Summary: update tikv/client-go to fix performance regression
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: update tikv/client-go to fix performance regression

- br/pkg/lightning/backend/external/iter.go
- br/pkg/lightning/backend/external/iter_test.go
Issue Number: close #47923
If a hotspot is detected, the reader would change to concurrent mode and read 32M data by default.
If the hotspot shifts to other files, the previous reader will drop the unread byte to release memory. If dropping too many bytes, the whole performance would be very bad.
Set the period of checking merge iter hotspot according to the key size.
For example, if the average key size is 0.1K (by sampling), then we can check the hotspot every
(32M / 0.1K) = 320000 KVs.
Tests 
before:
after:
>   
Side effects
Documentation …
> external: set the period of checking merge iter hotspot according to the key size

- domain/domain.go
Use kv timeout feature for schema reload.
When the leader peer of meta region is slow, use kv timeout could help alleviated by enabling the KV read timeout, avoid errors like "schema lease expire". For example when injecting slowness into the meta region TiKV node,
Tests 
Side effects
Documentation
```release-note
None
```
> domain: use with kv timeout feature schema load kv timeout

- errors.toml
- pkg/ddl/ddl_api.go
- pkg/ddl/ddl_test.go
- pkg/util/dbterror/ddl_terror.go
- tests/integrationtest/r/ddl/db_integration.result
- tests/integrationtest/r/ddl/multi_schema_change.result
Issue Number: close #48040 
Ensure correct error codes and error text for duplicate constraint names.
Tests 
>   
Side effects
Documentation
```release-note
Duplicate check constraints now use the correct error code and text
```
> ddl: Ensure correct errors for duplicate constraint names | tidb-test=pr/2231

- pkg/executor/builder.go
- pkg/executor/test/admintest/admin_test.go
- tests/integrationtest/r/expression/charset_and_collation.result
- tests/integrationtest/t/expression/charset_and_collation.test
Issue Number: close #47687
Problem Summary: In TiKV env, tableFullScan can't process schema have same columns which make it paniced.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> admin: fix `admin recover index` with CommonHandle table in TiKV env | tidb-test=pr/2231 

- executor/benchmark_test.go
- executor/hash_table.go
cherry-pick of #48090
Issue Number: close https://github.com/pingcap/tidb/issues/48082
Reuse chunk for GetMatchedRowsAndPtrs.
Add a new benchmark case.
Tests 
BenchmarkHashJoinExec
```
Old:
go test -benchmem -run=^$ -bench ^BenchmarkHashJoinExec$ github.com/pingcap/tidb/pkg/executor
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/pkg/executor
cpu: 13th Gen Intel(R) Core(TM) i9-13900KF
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0_1],_disk:false)-32                   2         625585277 ns/op        2428636920 B/op   512892 allocs/op
BenchmarkHashJoinExec/(rows:100000,_cols:[bigint(20)_var_string(5)],_concurency:4,_joinKeyIdx:_[0],_disk:false)-32                    19          64306968 ns/op        278193261 B/op …
```
> executor: reuse chunk for GetMatchedRowsAndPtrs calls (#48090)

- pkg/ddl/constraint_test.go
Issue Number: close #48123
There seems a race between:
https://github.com/pingcap/tidb/blob/3894bc5232183d8107482cae4f6c121a71478cb8/pkg/ddl/constraint_test.go#L239C43-L239C43
and
https://github.com/pingcap/tidb/blob/3894bc5232183d8107482cae4f6c121a71478cb8/pkg/ddl/constraint_test.go#L247C1-L247C1
The reason is:
1. When model.StatePublic,  L245 "alter table t add constraint c3 check ( a > 10)" return, and go on L246、L247.
2. However，the Hook set local constraint state to model.StateWriteReorganization at L234.
3. if L247 go faster than Hook L239，it will read the the not public state，then error occur.
How to reproduce:
before Hook L239, we add a line "time.Sleep(50 * time.Millisecond)" to make the race more competitive, then run the tests.
Sleep 50ms after add constraints …
> test: fix flaky TestAlterAddConstraintStateChange3

- br/pkg/lightning/common/retry.go
- pkg/ddl/index.go
- pkg/disttask/framework/scheduler/manager.go
- pkg/disttask/framework/scheduler/scheduler.go
Issue Number: ref #46258, close #48064
1. Check error retryable when init scheduler.
2. Add ErrCreatePDClient for ha test met it.
3. Check retryable error for dist task in ddl framework.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask/ddl: refine manager error handling

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #48107 ref #47691
Problem Summary: cherry-pick #48109
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: update tikv/client-go to fix performance regression (#48109)

- cmd/tidb-server/main.go
- pkg/util/memory/meminfo.go
Issue Number: close #47442
Tests 
1、with systemd 
run tidb-server 
```
[Unit]
Description=tidb
[Service]
Type=simple
Restart=always
ExecStart=/usr/bin/tidb
StandardOutput=journal
MemoryMax=500M
[Install]
WantedBy=multi-user.target
```
you will see the log like this.
```
[2023/10/30 11:00:49.325 +00:00] [INFO] [meminfo.go:188] ["use cgroup memory hook"] [cgroupMemorySize=524288000] [physicalMemorySize=32900468736]
```
2、without systemd
you will see.
```
[2023/10/30 10:47:16.154 +00:00] [INFO] [meminfo.go:190] ["use physical memory hook"] [cgroupMemorySize=9223372036854775807] [physicalMemorySize=32900468736]
```
>   
Side effects
Documentation …
> *: support cgroup with systemd

- br/pkg/storage/ks3.go
- br/pkg/storage/s3.go
- br/pkg/storage/s3_test.go
Issue Number: close #48164
Tests 
>   
Side effects
Documentation
```release-note
None
```
> s3: fix s3 concurrent uploader will overwrite error

- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/localhelper_test.go
Issue Number: close #47992
put job generation into the same error group as worker
Tests 
send a dummy job before scan region in generating job, and let worker returns error directly
```
| 300001 | //small-2.csv | `test`.`t`|148 | importing| failed | 16B  | NULL | [0]the remaining storage capacity of TiKV is less than 10%%; please increase the storage capacity of TiKV and try again | 2023-11-01 17:42:42.330981 | 2023-11-01 17:42:44.665693 | 2023-11-01 17:42:50.674848 | root@%  |
```
>   
Side effects
Documentation
```release-note
None
```
> local backend: fix worker err overriden by job generation err

- br/pkg/lightning/common/retry.go
- br/pkg/lightning/common/retry_test.go
- br/pkg/pdutil/pd.go
Issue Number: close #46950, #48075
- enlarge max retry time of pd request
- fix nested retriable net error
Tests 
>   
Side effects
Documentation
```release-note
None
```
> pdutil/backend: enlarge max retry time and fix nested retriable error

- pkg/executor/test/indexmergereadtest/BUILD.bazel
- pkg/executor/test/indexmergereadtest/index_merge_reader_test.go
Issue Number: close #46836
Problem Summary: planner: speed up the slow test TestPartitionTableRandomIndexMerge
planner: speed up the slow test TestPartitionTableRandomIndexMerge
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: speed up the slow test TestPartitionTableRandomIndexMerge

- pkg/ddl/tests/fail/fail_db_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/46840
When we occur `exchangePartitionErr`, we will retry 512 times. 
Set `DDLErrorCountLimit` to 3.
Tests 
**Before this PR**
without race
```
PASS
ok  	github.com/pingcap/tidb/pkg/ddl/tests/fail	2.762s
```
with race
```
PASS
ok  	github.com/pingcap/tidb/pkg/ddl/tests/fail	10.506s
```
**After this PR**
without race
```
PASS
ok  	github.com/pingcap/tidb/pkg/ddl/tests/fail	2.068s
```
with race
```
PASS
ok  	github.com/pingcap/tidb/pkg/ddl/tests/fail	5.072s
```
>   
Side effects
Documentation …
> ddl: make TestHalfwayCancelOperations faster

- pkg/planner/core/find_best_task.go
- pkg/planner/core/integration_test.go
- pkg/planner/util/fixcontrol/get.go
Issue Number: close #46177
Problem Summary: planner: fix the issue that the optimizer terminates the optimization process for `DataSource` too early
fix the issue that the optimizer terminates the optimization process for `DataSource` too early
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that the optimizer terminates the optimization process for `DataSource` too early

- pkg/config/config.toml.example
Issue Number: close #48203
Tests 
>   
Side effects
Documentation
```release-note
None
```
> config: update `packet-Protocol::Handshake` config url

- pkg/domain/domain.go
`["loading schema takes a long time, we do a new reload"] ["take time"=5m26.230125917s]`
The taken time is included `load schema` and `start DDL` in this log. So only add `loading schema` in this log is misleading. An example of this scenario is the following:
Tests 
>   
Side effects
Documentation
```release-note
None
```
> domain: make log information clearer in domain.Init

- pkg/executor/analyze.go
- pkg/executor/analyze_utils.go
- pkg/executor/builder.go
- pkg/executor/test/analyzetest/memorycontrol/BUILD.bazel
- pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go
Issue Number: close #48171
Tests 
>   
Side effects
Documentation
```release-note
None
```
> executor: fix hang for analyze table when exceed tidb_mem_quota_analyze

- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/util.go
planner: fix typo in comment
Tests 
> - [x] Only fix typo in comment.
>   
Side effects
Documentation
```release-note
None
```
> planner: fix typo in comment

- pkg/metrics/grafana/tidb.json
- pkg/metrics/server.go
- pkg/server/server.go
Issue Number: close #48289
Rename it.
Tests 
2. reload the tidb.json
3. set max_execution_time to a lower values, then make it take effect
4. check on grafana
>   
Side effects
Documentation
```release-note
None
```
> metrics: distinguish events of server level and connection level

- br/pkg/pdutil/pd.go
- br/pkg/pdutil/pd_serial_test.go
Issue Number: close #48307
Tests 
>   
Side effects
Documentation
```release-note
None
```
> pdutil: fix retry reusing body reader

- pkg/infoschema/cache.go
- pkg/infoschema/test/cachetest/BUILD.bazel
- pkg/infoschema/test/cachetest/cache_test.go
Issue Number: close #48285
Problem Summary: refine info cache logic to reduce the impact of DDL on information schema cache
Do same test in #48285,  with this PR, the impact of `failed to get schema version` to stale read QPS is much smaller.
```
[2023/11/04 09:44:04.794 +08:00] [WARN] [domain.go:196] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=3234]
[2023/11/04 09:44:18.787 +08:00] [WARN] [domain.go:196] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=3280]
[2023/11/04 09:44:20.885 +08:00] [WARN] [domain.go:196] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=3281]
[2023/11/04 09:44:37.502 +08:00] [WARN] [domain.go:196] …
```
> infoschema: refine info cache logic to reduce the impact of DDL on information schema cache

- domain/domain.go
- store/helper/helper.go
Issue Number: ref #48281
Handle lock error reading mvcc get schema diff key to avoid unexpected schema cache invalidation.
Tests 
Side effects
Documentation
```release-note
Fix unhandled lock error reading schema diff key using mvcc interface.
```
> domain: add resolve lock logic for mvcc get key loading schema diff

- domain/schema_validator.go
- metrics/domain.go
- metrics/grafana/tidb.json
- metrics/metrics.go
close pingcap/tidb#47729
Tests 
>   
Side effects
Documentation
```release-note
None
```
> domain/metrics: add a metric for lease expired time (#47730)

- pkg/disttask/framework/scheduler/manager.go
- pkg/disttask/framework/scheduler/scheduler.go
- tests/realtikvtest/addindextest1/BUILD.bazel
- tests/realtikvtest/addindextest1/disttask_test.go
Issue Number: close #48303
After cancelling the job, I found that the ingest worker did not stop. Instead, it was waiting for the server side(TiKV):
```
11 @ 0x1c2d6ee 0x1c3e185 0x21cf23c 0x225699a 0x2256987 0x2255c1f 0x22548da 0x2255a73 0x3d9bb96 0x3d999f1 0x3d98066 0x3d8942b 0x3d88f47 0x3d8be0e 0x3ac2a96 0x1c625c1
#	0x21cf23b	google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader+0x7b			/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/transport/transport.go:327
#	0x2256999	google.golang.org/grpc/internal/transport.(*Stream).RecvCompress+0xb9			/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/transport/transport.go:342
#	0x2256986	google.golang.org/grpc.(*csAttempt).recvMsg+0xa6					/go/pkg/mod/google.golang.org/grpc@v1.59.0/stream.go:1070
#	0x2255c1e …
```
> disttask: correct the usage of context

- pkg/ddl/BUILD.bazel
- pkg/ddl/backfilling_dispatcher.go
- pkg/ddl/backfilling_dispatcher_test.go
- pkg/ddl/export_test.go
- pkg/executor/executor.go
- tests/realtikvtest/addindextest2/global_sort_test.go
Issue Number: close #48347
- Set lower bound of `regionBatch` to `1`.
- Do not print "cloud" in `ADMIN SHOW DDL JOBS` for the add-index jobs that running with `tidb_enable_dist_task` disabled.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> disttask: fix split region batch panic

- br/pkg/restore/BUILD.bazel
- br/pkg/restore/split.go
- br/pkg/restore/split_test.go
Issue Number: close #47236
`ref #46001`
Due to the store limit, the regions with `CANCEL` or `TIMEOUT` status needs to be scatterred again.
retry to scatter the region if the status is not `RUNNING` or `SUCCESS`.
Tests 
Side effects
Documentation
```release-note
None
```
> br: retry to scatter the regions if status is timeout or cancel

- pkg/executor/recover_test.go
- pkg/sessiontxn/staleread/util.go
Issue Number: close #48372 
This PR provides the support to use TSO for asof expression of `flashback` sql command, stale read and resource calibration.
Tests 
>   
Side effects
Documentation
```release-note
Besides the timestamp format, TiDB users can use the TSO directly for `flashback` sql command, stale read and resource calibration.
```
> pkg: support the TSO format for asof expression

- pkg/ddl/tests/resourcegroup/resource_group_test.go
- pkg/parser/model/model.go
Issue Number: close #48140
Tests 
>   
Side effects
Documentation
```release-note
None
```
> resource_control: fix burst patch

- br/pkg/lightning/backend/local/region_job.go
- br/pkg/lightning/common/retry.go
- br/pkg/lightning/common/retry_test.go
Issue Number: close #48352 close #46321
Tests 
>   
Side effects
Documentation
```release-note
None
```
> lightning: add timeout for "write" RPC

- pkg/ddl/backfilling_dispatcher.go
- pkg/ddl/backfilling_dispatcher_test.go
- pkg/disttask/framework/dispatcher/dispatcher.go
- pkg/disttask/framework/dispatcher/dispatcher_test.go
- pkg/disttask/framework/dispatcher/interface.go
- pkg/disttask/framework/framework_dynamic_dispatch_test.go
- pkg/disttask/framework/framework_err_handling_test.go
- pkg/disttask/framework/framework_ha_test.go
- pkg/disttask/framework/framework_rollback_test.go
- pkg/disttask/framework/framework_test.go
- pkg/disttask/importinto/dispatcher.go
- pkg/disttask/importinto/dispatcher_test.go
- pkg/disttask/importinto/dispatcher_testkit_test.go
Issue Number: close #48368
1. serverNodes used in OnNextStageBatch didn't filter by role.
2. serverNodes may change during planning and dispatching phase, may lead to inconsistency of task nodes.
```
server:= d.GetEligibleInstance()
server:=d.filterByRole(server)
subtasks := d.OnNextStageBatch(server)
d.dispatchSubtasks(subtasks, server)
```
Using the above logic, the planner will use consistent serverNodes in plan and dispatching phase.
Tests 
>   
Side effects
Documentation
```release-note
Enhance planning of dist task
```
> disttask: fix wrong plan when filterByRole

- pkg/sessionctx/variable/sysvar.go
Fix #48177
If those variable set to global, the tidb instance config 'tidb_isolation_read_engines' cann't work.
Issue Number: close #48177
Tests 
>   
Side effects
Documentation
```release-note
None
```
> session_variable: change TiDBIsolationReadEngines and TiDBEnforceMPPExecution from global to session

- pkg/util/sys/linux/BUILD.bazel
- pkg/util/sys/linux/sys_linux.go
Problem Summary: input of `charsToString` is not always `int8`, it is probably `uint8` on some platforms.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: fix platform dependent utils charsToString

- pkg/statistics/handle/ddl/BUILD.bazel
- pkg/statistics/handle/ddl/event.go
Issue Number: ref https://github.com/pingcap/tidb/issues/48126#issuecomment-1794362183
- Added new DDL event for stats handler. You can see https://github.com/pingcap/tidb/issues/48126#issuecomment-1794362183 to check why we need these fields and information.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: add new DDL event for stats handler

- dumpling/export/dump.go
Issue Number: ref https://github.com/pingcap/tidb/issues/48253
force sort for table sample by using COALESCE.
Tests 
Manual using dumpling to dump false data and it works now.
Side effects
- None
Documentation
- None
```release-note
None
```
> dumpling: force sort for table sample | tidb-test=2d8288cf58aec9d381d09da70b18fd27855ed597

- br/pkg/task/BUILD.bazel
- br/pkg/task/backup.go
- br/pkg/task/common.go
- br/pkg/task/common_test.go
- br/pkg/task/restore.go
- pkg/executor/brie.go
Issue Number: close #48000
The current default config parameter is different from the BR CLI's. For example, `SkipStatistics` is always `false` (in BR it is defaultly `true`), `UseCheckpoint` is always `false` too (in BR it is defaultly `true`).
This PR exports the default config via the command line parameter of BR. And we will use it at the BRIE via SQL.
Tests 
>   
```release-note
Now, BRIE via SQL will use the same default config with BR CLI.
```
> executor/brie: use the default value from flags

- pkg/executor/analyze.go
- pkg/executor/test/analyzetest/BUILD.bazel
- pkg/executor/test/analyzetest/analyze_test.go
- pkg/executor/test/analyzetest/panictest/BUILD.bazel
- pkg/executor/test/analyzetest/panictest/main_test.go
- pkg/executor/test/analyzetest/panictest/panic_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/48356
if analyze worker or result handler unexpectedly exit. it is possible to hang in the place of sending task.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> executor: fix hang when the analyze worker unexpectedly exits

- pkg/expression/builtin_compare.go
- pkg/expression/util.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/plan_cache_test.go
Issue Number: close #48165
Problem Summary: planner: fix the issue that plan cache may return wrong result when comparing datetime column with `unix_timestamp`
planner: fix the issue that plan cache may return wrong result when comparing datetime column with `unix_timestamp`
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that plan cache may return wrong result when comparing datetime column with `unix_timestamp`

- pkg/planner/core/find_best_task.go
- tests/integrationtest/r/executor/sample.result
- tests/integrationtest/t/executor/sample.test
Issue Number: close #48253
`TableSampleExecutor` does not process unsigned int handles. They are treated as the signed handles.
Always keep the sort operator when a `TABLESAMPLE` query contains `ORDER BY` clause.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner/core: keep sort operator when ordered by tablesample

- WORKSPACE
Issue Number: close #48383
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.21.4

- pkg/domain/domain.go
Issue Number: close #47809 
Problem Summary: improve information log information
```log
[2023/10/19 20:39:12.623 +08:00] [INFO] [domain.go:262] ["diff load InfoSchema success"] [currentSchemaVersion=50] [neededSchemaVersion=51] ["start time"=39.45µs] [gotSchemaVersion=51] [phyTblIDs="[]"] [actionTypes="[]"] [diffTypes="[\"create schema\"]"]
```
Tests 
>   
Side effects
Documentation
```release-note
None
```
> domain: improve information log information

- pkg/executor/distsql_test.go
- pkg/store/copr/coprocessor.go
Issue Number: close #48212
Goroutine panic because of nil pointer dereference.
When coprocessor cache is hit, check the details before set execution info.
Because some internal tasks may lead to cache hit when `tidb_enable_collect_execution_info` is turned off, so this need to be checked.
Tests 
>   
```bash
tiup playground nightly --kv=3 --mode=tikv-slim
export TIKV_PATH=127.0.0.1:2379
export TIDB_TEST_STORE_NAME=tikv
make integrationtest
```
- Before
It may panic like the log in #48212
- After
No panic
Side effects
Documentation …
> copr: fix copr cache panic when `tidb_enable_collect_execution_info` is off

- pkg/server/conn.go
- pkg/session/session.go
Issue Number: close #48446, ref #48411
This also fix #48411 in another way, and can prevent more bugs.
Close the result set after all rs.Next(), and before cc.writeEOF()
Avoid the case that error happen and can't be sent to the client after writeEOF.
Tests 
The test code in https://github.com/pingcap/tidb/pull/48412 should also apply for this one, as the both can fix #48411, so I don't bother writer another duplicated test.
See https://github.com/pingcap/tidb/issues/48411
>   
Side effects
Documentation
```release-note
None
```
> server,session: make sure ResultSet.Close() errors return to the client

- pkg/executor/historical_stats_test.go
- pkg/session/session.go
- pkg/statistics/handle/storage/gc.go
Issue Number: close #48431
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statistics: avoid oom when to gc large stats_history

- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/bench_test.go
Add a simple unit test framework that wants to check the throughput, CPU profile and heap profile of external reader/writer and their compositions.
Tests 
>   
```
$ go test ./br/pkg/lightning/backend/external -v --tags=intest -test.run TestCompare --testing-storage-uri "s3://nfs/tianyuan-ut?access-key=xxx&secret-access-key=xxx&endpoint=https://xxx&force-path-style=false&region=xxx&provider=ks"
...
bench_test.go:210: base speed for 1200000000 bytes: 14.68 MB/s
...
bench_test.go:215: writer speed for 1200000000 bytes: 54.18 MB/s
```
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide …
> external/test: compare the performance of external writer

- br/pkg/utils/backoff.go
- br/pkg/utils/retry.go
- br/tests/br_full/run.sh
This is an cherry-pick of #48529
Issue Number: close #48528
the error need to be marked as the retryable error
add the error message into the retryable error list
Tests 
>   
Side effects
Documentation
```release-note
None
```
> br: add more retryable error for br_import (#48529)

- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/bench_test.go
generate the speed, CPU/heap profile for reading from external storage. See below.
Tests 
>   
```
$ go test ./br/pkg/lightning/backend/external -v --tags=intest -test.run TestCompareReader --testing-storage-uri "s3://nfs/tianyuan-ut?access-key=xxx&secret-access-key=xxx&endpoint=https://xxx&force-path-style=false&region=xxx&provider=ks"
bench_test.go:413: sequential read speed for 1258291200 bytes: 52.38 MB/s
bench_test.go:420: concurrent read speed for 1258291200 bytes: 730.08 MB/s
bench_test.go:427: merge iter read speed for 1258291200 bytes: 103.47 MB/s
```
The data is evenly distributed in files. We can see that even in this case merge iterator is slower than concurrent reading.
and here's …
> external/test: compare the performance of merge iter

- pkg/sessionctx/stmtctx/stmtctx.go
- pkg/types/context.go
- pkg/util/intest/BUILD.bazel
- pkg/util/intest/assert.go
- pkg/util/intest/assert_test.go
- pkg/util/intest/common.go
Issue Number: close #48578
Make `intest.Assert` to have a brief semantics:
- `intest.Assert` only receives `bool` input to check the condition should be true
- provide `intest.AssertNotNil` to check a pointer should not be nil
- provide `intest.AssertNoError` to check a error should be nil 
Tests 
>   
Side effects
Documentation
```release-note
None
```
> util/intest: provide `intest.AssertNotNil` and `intest.AssertNoError`

- pkg/param/binary_params.go
- pkg/server/conn_stmt_params_test.go
Issue Number: close #48563
The `TIME` parameters will always use `us` precision.
Only use `us` (6) precision when the parameter length is 12.
Tests 
>   
```release-note
Fix the issue that the `TIME` parameters always use the `us` precision.
```
> pkg/param: add correct fsp for duration

- pkg/table/index.go
- pkg/table/tables/index.go
- tests/realtikvtest/addindextest4/ingest_test.go
Issue Number: close #48304
Minimum reproducible step: https://github.com/pingcap/tidb/issues/48304#issuecomment-1810085121.
#48184 made the wrong assumption that multi-valued index must produce more than one result:
https://github.com/pingcap/tidb/blob/911334b6ef7f548da6ef8ef90fc429c4c4c272b6/pkg/table/index.go#L135-L139
However, for empty JSON slice, there is no result.
Pass `isMultiValueIndex` as parameter explicitly.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> table: fix the iterator of multi-valued index

- .codecov.yml
- update ignore paths for coverage.
- make the codecov results just as informations in github statuses on components and flags level, will not failed the statuses.
Total project level was disabled before(ref #46232).
Tests 
>   
Side effects
Documentation
```release-note
None
```
> CI: adjust the codecov statuses to make it not affect the PR or branch commit status

- pkg/extension/README.md
Issue Number: ref #38493
Tests 
>   
Side effects
Documentation
```release-note
None
```
> extension: add `README.md` to extension

- pkg/executor/set.go
- pkg/parser/ast/misc.go
Issue Number: close #48498 
As the issue said
1. Redact uri in log.
2. Redact uri in show processList.
Tests 
>   
1. In tidb log:
3. show processlist;
Side effects
Documentation
```release-note
redact tidb_cloud_storage_uri in log
```
> global sort: fix set tidb_cloud_storage_uri should be redacted

- .codecov.yml
Fix pingcap/tidb#48605
Tests 
```release-note
None
```
> Revert "CI: fix empty values for `information` fileds"

- pkg/ddl/backfilling_scheduler.go
- pkg/expression/builtin_cast.go
- pkg/expression/builtin_cast_test.go
- pkg/expression/builtin_cast_vec.go
- pkg/types/context.go
- pkg/types/convert_test.go
- pkg/types/datum.go
- pkg/types/time.go
- pkg/types/time_test.go
- tests/integrationtest/r/expression/cast.result
- tests/integrationtest/t/expression/cast.test
Issue Number: close #48557
The correct behavior of converting time to year should be mixing the `Now` and duration, and then return the year.
Actually, it has two different behaviors when converting the `TIME` to `YEAR`.
1. In DDL, e.g. modify the column type from `TIME` to `YEAR`, it follows the "concatenation" rule. The `00:19:98` will be converted to `1998`. TiDB follows this behavior in all scenario before this PR. It's more like `TIME -> CHAR() -> YEAR`. This behavior has been covered by existing tests in `ddl/column_type_change` and `ddl/modify_column`.
2. In `SELECT` (cast implicitly or explicitly) and `INSERT` (inserting a `TIME` to a `YEAR` column), it's more like `TIME -> DATETIME -> YEAR`. It will mix the duration with the current time, and return the year. …
> expression, types: fix the logic of converting duration to year

- pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_in.json
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- pkg/planner/core/find_best_task.go
- pkg/planner/core/task.go
Issue Number: close https://github.com/pingcap/tidb/issues/48588
detail ref the comment https://github.com/pingcap/tidb/issues/48588#issuecomment-1809856218 in the issue above
Tests 
>   
Side effects
Documentation
```release-note
planner: fix index merge union case couldn't sink limit into index merge reader
```
> planner: fix index merge union case couldn't sink limit into index merge reader

- pkg/planner/core/hints.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/rule_join_reorder.go
Issue Number: ref #46791
Problem Summary: planner: quick fix the panic issue when restoring hints from a plan
Forget to check whether the pointer is nil before using it:
But this pointer shouldn't be nil anyway, the root cause still needs more investigation, this is just a quick fix for users.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> planner: quick fix the panic issue when restoring hints from a plan

- pkg/executor/BUILD.bazel
- pkg/executor/analyze_global_stats.go
- pkg/statistics/handle/globalstats/global_stats.go
- pkg/statistics/handle/util/interfaces.go
Tests 
>   
Side effects
Documentation
```release-note
None
```
> statstics: remove useless cache

- br/pkg/task/backup.go
- br/pkg/task/backup_test.go
- br/pkg/task/common.go
Issue Number: close https://github.com/pingcap/tidb/issues/48571
checksum and backup stats does have impact on cluster. so public the parameter with `table-concurrency`. which means the concurrency of backup all table metas. including backup tableInfos/stats and checksum.
Public internal parameter to configuration.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> backup: add table-concurrency to control backup tableInfo stats and checksum.

- br/pkg/lightning/mydump/loader_test.go
- cmd/ddltest/ddl_test.go
- cmd/importer/rand.go
- pkg/executor/internal/vecgroupchecker/vec_group_checker_test.go
- pkg/planner/core/tests/prepare/prepare_test.go
- pkg/statistics/handle/updatetest/update_test.go
- pkg/store/driver/tikv_driver.go
- pkg/util/chunk/list_test.go
- pkg/util/chunk/row_in_disk_test.go
- pkg/util/importer/rand.go
- pkg/util/selection/selection_test.go
- tools/check/ut.go
Issue Number: https://github.com/golang/go/issues/54880
```golang
// Seed uses the provided seed value to initialize the default Source to a
// deterministic state. Seed values that have the same remainder when
// divided by 2³¹-1 generate the same pseudo-random sequence.
// Seed, unlike the Rand.Seed method, is safe for concurrent use.
//
// If Seed is not called, the generator is seeded randomly at program startup.
//
// Prior to Go 1.20, the generator was seeded like Seed(1) at program startup.
// To force the old behavior, call Seed(1) at program startup.
// Alternately, set GODEBUG=randautoseed=0 in the environment
// before making any calls to functions in this package.
//
// Deprecated: As of Go 1.20 there is no reason to call Seed with
// a random value. Programs …
```
> pkg: stop using math/rand.Seed

- br/pkg/lightning/importer/precheck_impl.go
- br/pkg/lightning/importer/table_import_test.go
As title.
Issue Number: close https://github.com/pingcap/tidb/issues/48654
- the comments is "source csv files is proper" when lightning imports the parquet data files, which could confuse the DBA.
Tests 
>   
- after fix it 
```
+----+------------------------------------------------------------------------------------------------------------------------------------+-------------+--------+
|  # | CHECK ITEM                                                                                                                         | TYPE        | PASSED |
+----+------------------------------------------------------------------------------------------------------------------------------------+-------------+--------+
|  1 | Source data files size is proper …
```
> lightning: fix typo because lightning supports sql/parquet data files but csv. 

- br/pkg/lightning/backend/external/engine.go
- br/pkg/lightning/backend/local/local.go
Issue Number: close #48538
Tests 
>   
Manually check the memory usage in large cluster testing
Side effects
Documentation
```release-note
None
```
> lightning: release memory pool when external engine close

- pkg/server/conn.go
- pkg/session/session.go
close #48667
Reverts pingcap/tidb#48486
The 7.5 release is frozen, and we don't have enough time to figure out why this PR could introduce a regression.
So revert it.
As for the bug this PR fixes, we have other PR that also could do that, the risk is low.
> Revert "server,session: make sure ResultSet.Close() errors return to the client (#48447)"

- pkg/executor/ddl.go
- pkg/executor/recover_test.go
- pkg/parser/ast/ddl.go
- pkg/parser/lexer.go
- pkg/parser/misc.go
- pkg/parser/parser.y
- pkg/parser/parser_test.go
- pkg/sessiontxn/staleread/util.go
Issue Number: close #48372
This PR provide the `flashback cluster to tso` support.
Tests 
>   
Side effects
Documentation
```release-note
This feature provides the new syntax of `flashback` of `flashback cluster to tso xxx_int`. An example is `flashback cluster to tso 445494955052105728`.
```
> flashback: support to flashback to tso syntax

- pkg/ddl/backfilling_dist_scheduler.go
- pkg/ddl/index.go
- pkg/ddl/ingest/backend_mgr.go
- pkg/ddl/ingest/config.go
- pkg/ddl/ingest/mock.go
- tests/realtikvtest/addindextest4/ingest_test.go
- tests/realtikvtest/testkit.go
Issue Number: close https://github.com/pingcap/tidb/issues/48680
as title
Tests 
>   
Side effects
Documentation
```release-note
None
```
> ddl: use latest PD address to register lightning

- planner/core/physical_plans.go
- planner/core/testdata/enforce_mpp_suite_out.json
Issue Number: close https://github.com/pingcap/tidb/issues/48643
Tests 
>   
Side effects
Documentation
```release-note
planner: fix potential modification of shared immutable aggDesc
```
> planner: fix potential modification of shared immutable aggDesc

- pkg/executor/test/executor/executor_test.go
- tests/integrationtest/r/executor/executor.result
- tests/integrationtest/r/session/variable.result
- tests/integrationtest/t/executor/executor.test
- tests/integrationtest/t/session/variable.test
Problem Summary: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/33657/pipeline/
The result contains `backoff{regionMiss:<num>}` which not processed correctly, so update the regex pattern. And aslo found a duplicate test case, delete it.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> test: fix unstable test `TestIndexMergeRuntimeStats`

- pkg/executor/set_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #48674
Now, the default value of tidb_auto_analyze_partition_batch_size is 1. it is too small. so that it will lead to merge global stats frequantly.
It is for a partition table to only trigger merge global stats once. so we need to increase the ```tidb_auto_analyze_partition_batch_size```. it will look like this.
﻿﻿﻿
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: set default tidb_auto_analyze_partition_batch_size 128

- pkg/ddl/index.go
Issue Number: close https://github.com/pingcap/tidb/issues/48706
Tests 
Ran IT as described in the issue
>   
Side effects
Documentation
```release-note
None
```
> ddl: we shouldn't make a DDL job to a dist task when it's on system DB in upgrading

- br/pkg/lightning/backend/external/engine.go
- br/pkg/lightning/backend/external/engine_test.go
- br/pkg/lightning/backend/external/writer_test.go
- br/pkg/lightning/backend/local/engine.go
- br/pkg/lightning/backend/local/engine_test.go
- br/pkg/lightning/backend/local/iterator.go
- br/pkg/lightning/backend/local/iterator_test.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/region_job.go
- br/pkg/lightning/common/BUILD.bazel
- br/pkg/lightning/common/ingest_data.go
Issue Number: close #48677
iter.Key() and Value() should promise the returned key and value can be retained after Next(), Key(), Value(). The memory can be released by iter.RelaeseBuf()
Tests 
>   
Side effects
Documentation
```release-note
None
```
> lightning: avoid copying bytes if the bytes are already non-shared

- dumpling/export/config.go
- dumpling/export/writer_serial_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/48720
Add CSVDialectBigQuery to support dumpling binary data that encode as base64 format, user can define it in command flag by `--csv-output-dialect bigquery`.
Tests 
>   
Side effects
Documentation
```release-note
None
```
> dumpling: support bigquery dialect

- pkg/ddl/ddl_api.go
- tests/integrationtest/r/util/admin.result
- tests/integrationtest/t/util/admin.test
Issue Number: close #48754
Tests 
>   
Side effects
Documentation
```release-note
None
```
> *: support alter table row_format for the compatibility

- pkg/executor/explain_test.go
- pkg/planner/core/rule_join_reorder.go
Issue Number: close https://github.com/pingcap/tidb/issues/47331
Through my investigation, I identified several key points:
1. The panic occurs during DeriveStats: p.StatsInfo().ColNDVs[selfSchema.Columns[i].UniqueID] = childProfile.RowCount.
2. There's a discrepancy in the number of expressions and schema columns: the plan has 8 expressions but only 7 columns in the schema.
3. The logic plan causing the panic is a projection (ID 25), generated by the joinReOrderSolver.
4. Post-debugging, I noted that the schema undergoes changes after the LogicalProjection.PruneColumns process.
5. On further debugging the PruneColumns function individually, I discovered that the schema of projection#25 is affected even before it's reached in the process.
6. This led me to suspect a …
> planner: fix a panic during column pruning

- pkg/ddl/backfilling_operators.go
Issue Number: ref https://github.com/pingcap/tidb/issues/47757
Tests 
add index, check the log
>   
Side effects
Documentation
```release-note
None
```
> ddl: use memory available as the memory limit for add index

- pkg/ddl/backfilling_operators.go
- pkg/ddl/backfilling_scheduler.go
Issue Number: ref #48724
The timezone is not recovered correctly. 
Tests 
Pass the internal test.
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix add wrong timezone during adding index

- pkg/ddl/tests/serial/serial_test.go
- pkg/infoschema/tables.go
Issue Number: close #42030
Problem Summary: see #42030.
Change the data type length from `30` to `45`.
Tests 
Side effects
Documentation
```release-note
None
```
> infoschema: make information_schema.columns copyable

- br/pkg/lightning/backend/kv/base.go
- pkg/executor/importer/kv_encode.go
- pkg/util/ranger/detacher.go
- pkg/util/ranger/points.go
- pkg/util/ranger/ranger.go
Issue Number: close #48783
After https://github.com/pingcap/tidb/pull/48609 , we have added a ctx parameter to Expression.Eval to use context as an input instead of using the inner one. However, we left some EvalWithInnerCtx invokes when we could not find a context around the invoke. We should replace them with Eval in the later PRs.
In this PR, we replace all the invokes of `EvalWithInnerCtx` with `Eval` to use the context as an input parameter in packages `br` and `util/ranger`
Tests 
>   
Side effects
Documentation
```release-note
None
```
> br, util/ranger: replace `EvalWithInnerCtx` with `Eval` for packages br and util/ranger

- pkg/expression/constant.go
Issue Number: close #48790
See the issue description.
remove call of `EvalWithInnerCtx` in method `Constant.HashCode`
Tests 
> simple modification, just re-run exist tests
Side effects
Documentation
```release-note
None
```
> expression: remove call of `EvalWithInnerCtx` in method `Constant.HashCode`

- pkg/planner/cardinality/trace.go
Issue Number: close #48787
After https://github.com/pingcap/tidb/pull/48609 , we have added a ctx parameter to Expression.Eval to use context as an input instead of using the inner one. However, we left some EvalWithInnerCtx invokes when we could not find a context around the invoke. We should replace them with Eval in the later PRs.
replace `EvalWithInnerCtx` with `Eval` in `exprToString` in planner
Tests 
>   
just run current tests is enough
Side effects
Documentation
```release-note
None
```
> planner: replace `EvalWithInnerCtx` with `Eval` in `exprToString` in planner

- DEPS.bzl
- go.mod
- go.sum
- pkg/ddl/attributes_sql_test.go
- pkg/ddl/label/BUILD.bazel
- pkg/ddl/label/attributes.go
- pkg/ddl/label/attributes_test.go
- pkg/ddl/label/rule.go
- pkg/ddl/label/rule_test.go
- pkg/ddl/main_test.go
- pkg/ddl/partition.go
- pkg/ddl/tests/serial/main_test.go
- pkg/domain/BUILD.bazel
- pkg/domain/db_test.go
- pkg/domain/domain.go
- pkg/domain/infosync/info.go
- pkg/domain/infosync/info_test.go
- pkg/domain/infosync/label_manager.go
- pkg/executor/infoschema_reader.go
- pkg/kv/BUILD.bazel
- pkg/kv/kv.go
- pkg/server/handler/tests/BUILD.bazel
- pkg/server/handler/tests/http_handler_test.go
- pkg/server/stat_test.go
- pkg/store/gcworker/gc_worker.go
Issue Number: ref #35319, https://github.com/tikv/pd/issues/7300
Integrate PD HTTP client into the label manager.
- Replace the etcd client inside `LabelRuleManager` with PD HTTP client.
- Reuse the type definitions within the PD SDK as much as possible.
Tests 
```release-note
None
```
> infosync: integrate PD HTTP client into the label manager

- pkg/server/conn_stmt_test.go
- pkg/util/chunk/row_container_reader.go
Issue Number: close #47029
In the original test, I closed the file used by row containers, and expected it to give an error. However, it seems to be unstable, and cannot be used on Mac OS. I turned to use `failpoint` to give a more stable error.
Actually, I'm not very sure whether this PR will fix the flacky test, because I still don't know the root cause of it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server: use failpoint rather than real error in test `TestCursorFetchErrorInFetch`

- br/pkg/lightning/backend/external/bench_test.go
- br/pkg/lightning/backend/external/byte_reader.go
- br/pkg/lightning/backend/external/kv_reader.go
- br/pkg/lightning/backend/external/stat_reader.go
- br/pkg/storage/BUILD.bazel
- br/pkg/storage/s3.go
- br/pkg/storage/storage.go
- br/pkg/storage/storage_test.go
- pkg/util/prefetch/BUILD.bazel
- pkg/util/prefetch/reader.go
- pkg/util/prefetch/reader_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/48781
offload the network reading from the main goroutine of merge iterator
Still need to improve the performance in future.
Tests 
>   
use this command to run the specific "benchmark" unit test
```
go test ./br/pkg/lightning/backend/external -v --tags=intest -test.run TestCompareReader --testing-storage-uri "xxx"
```
On master with ks3
```
bench_test.go:414: merge iter read speed for 1258291200 bytes: 109.49 MB/s
```
This PR with ks3
```
bench_test.go:412: merge iter read speed for 1258291200 bytes: 121.49 MB/s
```
This PR with memstore
```
bench_test.go:412: merge iter read speed for 1258291200 bytes: 163.92 MB/s
```
And I checked the heap usage, I have set …
> br/storage: enable async prefetch data
