pingcap/tidb

pkg/planner/core/planbuilder.go, tests/integrationtest/r/executor/split_table.result
Issue Number: close #47686
Problem Summary: see #47686.
Refine the error message of splitting clustered index
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: refine error message of split clustered index

br/pkg/lightning/common/BUILD.bazel, br/pkg/lightning/common/common_test.go, br/pkg/lightning/importer/table_import.go, pkg/ddl/column.go, pkg/ddl/ddl.go, pkg/ddl/options.go, pkg/disttask/importinto/subtask_executor.go, pkg/domain/BUILD.bazel, pkg/domain/domain.go, pkg/meta/autoid/BUILD.bazel, pkg/meta/autoid/autoid.go, pkg/meta/autoid/autoid_service.go, pkg/meta/autoid/autoid_test.go
Issue Number: close #48869
Prior to this commit, each auto id allocator has it's own autoid client (a grpc connection inside), so if we have 60K tables there would be 60K tcp connections ...
After the fix, the autoid client is moved to domain so there should be only one autoid client instance. All the autoid allocator share this instance now.
Tests 
See the reproduce steps in the issue.
The test check tcp connection counts, it's harder to do that in unit test
> 
Side effects
Documentation
```release-note
Fix grpc client leak bug for …
```
=> *: fix grpc client leak bug for AUTO_ID_CACHE=1 tables

pkg/executor/analyze_col.go, pkg/executor/analyze_col_v2.go, pkg/statistics/builder.go, pkg/statistics/builder_ext_stats.go, pkg/statistics/builder_test.go, pkg/statistics/main_test.go, pkg/statistics/sample.go, pkg/statistics/sample_test.go, pkg/statistics/statistics_test.go
Tests 
before
```
$ go test -benchmem -run=^$ -bench ^BenchmarkBuildHistAndTopN$ github.com/pingcap/tidb/pkg/statistics
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/statistics
BenchmarkBuildHistAndTopN-8            1        1363438291 ns/op        72031328 B/op    4000055 allocs/op
```
after
```
$ go test -benchmem -run=^$ -bench ^BenchmarkBuildHistAndTopN$ github.com/pingcap/tidb/pkg/statistics
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/statistics
BenchmarkBuildHistAndTopN-8            1        1352474167 ns/op        64027744 B/op    4000054 allocs/op
```
>   
Side effects
Documentation …
=> *: avoid copy in the SortSampleItems

pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/globalstats/BUILD.bazel, pkg/statistics/handle/globalstats/global_stats.go, pkg/statistics/handle/globalstats/globalstats_test.go, pkg/statistics/handle/types/interfaces.go
Issue Number: ref https://github.com/pingcap/tidb/issues/48182#issuecomment-1824091079
Based on [this design doc](https://pingcap.feishu.cn/docx/OLCrdxHj2ojb9KxlUvUch60LnBe#part-PRTmdkF0doiZSxxHHmDckfeJnZf), we will only update the `count` and `modfiy_count` for it. Then it will use the `count` and `modify_count` to determine if we need to trigger an auto-analysis task.
So in this PR, I dropped the update global stats operation.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: do not directly update global stats when dropping a partition

br/pkg/lightning/common/BUILD.bazel, br/pkg/lightning/common/common_test.go, br/pkg/lightning/importer/table_import.go, ddl/column.go, ddl/ddl.go, ddl/options.go, domain/BUILD.bazel, domain/domain.go, executor/importer/table_import.go, infoschema/BUILD.bazel, infoschema/infoschema_test.go, meta/autoid/BUILD.bazel, meta/autoid/autoid.go, meta/autoid/autoid_service.go, meta/autoid/autoid_test.go
Cherry-pick https://github.com/pingcap/tidb/pull/48870 to hotfix for 7.1.2
Issue Number: close #48869
Prior to this commit, each auto id allocator has it's own autoid client (a grpc connection inside), so if we have 60K tables there would be 60K tcp connections ...
After the fix, the autoid client is moved to domain so there should be only one autoid client instance. All the autoid allocator share this instance now.
Tests 
See the reproduce steps in the issue.
The test check tcp connection counts, it's harder to do that in unit test
> 
Side effects
Documentation …
=> *: fix grpc client leak bug for AUTO_ID_CACHE=1 tables #48870

pkg/util/dbutil/BUILD.bazel, pkg/util/dbutil/common.go
Issue Number: close #48911
Remove a simple usage of `stmtctx` in the `dbutil`.
Tests 
> These codes are covered by existing tests.
```release-note
None
```
=> pkg/util/dbutil: remove dependency `stmtctx` from `dbutil`

DEPS.bzl, br/pkg/pdutil/pd.go, go.mod, go.sum, pkg/ddl/placement/BUILD.bazel, pkg/ddl/placement/bundle.go, pkg/ddl/placement/bundle_test.go, pkg/ddl/placement/constraint.go, pkg/ddl/placement/constraint_test.go, pkg/ddl/placement/constraints.go, pkg/ddl/placement/constraints_test.go, pkg/ddl/placement/meta_bundle_test.go, pkg/ddl/placement/rule.go, pkg/ddl/placement/rule_test.go, pkg/domain/infosync/info.go, pkg/domain/infosync/placement_manager.go, pkg/domain/infosync/tiflash_manager.go, pkg/executor/infoschema_reader.go, pkg/store/helper/helper.go
Issue Number: ref #35319, https://github.com/tikv/pd/issues/7300
Integrate PD HTTP client into the placement manager.
- Replace the etcd client inside `PlacementManager` with PD HTTP client.
- Reuse the type definitions within the PD SDK as much as possible.
Tests 
```release-note
None
```
=> infosync: integrate PD HTTP client into the placement manager

br/pkg/aws/ebs.go, br/pkg/task/restore.go, br/pkg/task/restore_ebs_meta.go
Issue Number: close #48899 
This PR adds a new flag "volume-encrypted". The flag sets the encrypted param, when creating the EBS volume. Default is disabled.
The flag will passed as an option to the backup_manager from the restore CRD, which sets it as a flag when invoking restore command.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> BR: Support encryption for restored ebs volumes

pkg/executor/distsql.go, pkg/expression/aggregation/agg_to_pb.go, pkg/expression/aggregation/explain.go, pkg/expression/aggregation/window_func.go, pkg/expression/constant_fold.go, pkg/expression/explain.go, pkg/expression/expr_to_pb.go, pkg/expression/expr_to_pb_test.go, pkg/expression/expression.go, pkg/expression/grouping_sets.go, pkg/expression/util.go, pkg/expression/util_test.go, pkg/planner/cascades/transformation_rules.go, pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/explain.go, pkg/planner/core/find_best_task.go, pkg/planner/core/handle_cols.go, pkg/planner/core/indexmerge_path.go, pkg/planner/core/plan_to_pb.go, pkg/planner/core/rule_predicate_push_down.go, pkg/planner/core/runtime_filter.go, pkg/planner/core/scalar_subq_expression.go, pkg/planner/core/task.go, pkg/planner/core/tiflash_selection_late_materialization.go, pkg/planner/property/BUILD.bazel, pkg/planner/property/physical_property.go
Issue Number: close #48914
To make sure some `Eval` methods can have a outside input of the context, we did below two refactors
1. Replace inner context type from `StatementContext` to `sessionctx.Context` for `PbConverter`
2. Add a new parameter `ctx` for method `Expression.ExplainInfo`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: replace `EvalWithInnerCtx` with `Eval` for `PbConverter` and `ExplainInfo`

pkg/expression/builtin_cast.go, pkg/expression/builtin_convert_charset.go, pkg/expression/builtin_other.go, pkg/expression/builtin_test.go, pkg/expression/builtin_vectorized_test.go, pkg/expression/column.go, pkg/expression/constant.go, pkg/expression/distsql_builtin.go, pkg/expression/expression.go, pkg/expression/scalar_function.go, pkg/expression/util_test.go, pkg/planner/core/scalar_subq_expression.go
Issue Number: close #48916
After some previous works in #47958, the context cache in `ScalarFunction` is not used anymore, we should remove it.
Remove inner context cache in `expression.ScalarFunction`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: remove inner context cache in `expression.ScalarFunction`

br/pkg/lightning/importer/table_import.go, br/tests/lightning_checkpoint_chunks/file.toml, br/tests/lightning_checkpoint_chunks/run.sh
Issue Number: close #48562
update mysql.stats_meta if analyze is off
Tests 
> 
Side effects
Documentation
```release-note
even if lightning didn't run analyze which is specified in task configuration, still enable TiDB server auto analyze feature for the imported table
```
=> lightning: still update stats_meta if analyze is skipped

pkg/statistics/builder_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: add benchmark for BuildHistAndTopN with low NDV

pkg/session/bootstrap.go
Issue Number: close #48953
Problem Summary: planner: fix DATA RACE caused by TestTiDBBindingInListToVer175
planner: fix DATA RACE caused by TestTiDBBindingInListToVer175
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix DATA RACE caused by TestTiDBBindingInListToVer175

pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/ddl_test.go, pkg/statistics/handle/storage/save.go, pkg/statistics/handle/storage/stats_read_writer.go, pkg/statistics/handle/types/interfaces.go
Issue Number: close https://github.com/pingcap/tidb/issues/48182
Based on [this design doc](https://pingcap.feishu.cn/docx/OLCrdxHj2ojb9KxlUvUch60LnBe#part-PRTmdkF0doiZSxxHHmDckfeJnZf), we will only update the count and modfiy_count for it. Then it will use the count and modify_count to determine if we need to trigger an auto-analysis task.
So in this PR, I updated the count and modify count of the global table.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: Update stats meta count and modify count for dropped table partitions

pkg/parser/docs/quickstart.md
#41241 reorganized the file structure. This PR updates parser document accordingly.
See code changes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> docs: update parser quickstart

br/pkg/lightning/log/log.go, build/linter/util/exclude.go, build/linter/util/exclude_test.go, build/nogo_config.json, pkg/disttask/framework/storage/task_table.go, pkg/planner/property/BUILD.bazel, pkg/planner/property/physical_property.go
Issue Number: close #48998
The config use `key` to represent the pattern, but not value. I copied the code from [`nogo_main.go`](https://github.com/bazelbuild/rules_go/blob/master/go/tools/builders/nogo_main.go), but in `nogo_main` it's an array :facepalm: .
Tests 
> 
```release-note
None
```
=>  build/linter/util: exclude files according to the key of `only_files`

pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/handle.go
Issue Number: ref https://github.com/pingcap/tidb/pull/48929#discussion_r1407975768
Printed the DB name in the logs.
Because changing the interface would have a significant invasive impact, the ctx was attached to the DDL handler. Otherwise, not only all the tests but also the handle's flush operation would have to query the schema by themselves.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: log the db name

tools/check/ut.go
Issue Number: ref #31880
Increase the parallelism when building the test binaries, by default it is the number of cores(https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies): 
> 
>-p n
>	the number of programs, such as build commands or
>	test binaries, that can be run in parallel.
>	The default is GOMAXPROCS, normally the number of CPUs available.
> 
I found that when running the 'building binaries stage' of `make ut`, the CPU usage is not high with the default value. So I think it's a better idea to increase the parallelism. In this PR, I doubled it.
The result of `make ut` time in my Macbook M2 Pro:
(Before this PR)
```
bash> make ut
...
building task finish, maxproc=10, count=4822, takes=12m32.547299958s 
...
```
(After this PR)
```
bash> make ut
... …
```
=> tools/check: increase the parallelism for building test binaries

pkg/statistics/handle/autoanalyze/autoanalyze.go
Before proceeding with the implementation of a new auto-analysis queue, we can first consolidate the existing logic into one function. This way, it will be easier to revert to the old method if necessary. We don't have to remove the old logic right away. Instead, we can use a deprecation and opt-in process to gradually introduce this change to users.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: move the previous auto-analyze selection into a func

.dockerignore
Issue Number: close #49037
Tests 
success to run ```make docker```
﻿﻿﻿
> 
Side effects
Documentation
```release-note
None
```
=> *: remove cmd in the dockerignore

pkg/expression/chunk_executor.go, pkg/util/codec/codec.go, tests/integrationtest/r/executor/jointest/hash_join.result, tests/integrationtest/t/executor/jointest/hash_join.test
Issue Number: close #48991 
When the projection disables the ColumnEvaluator, it will eval the ENUM and parse a new ENUM. But the new ENUM value's value index will be set to 0.
But when we construct the hash value for the join key, we use the value index to seek the string value. So a wrong hash key is constructed.
This pull aims to solve the case.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that hash join will construct wrong join key for ENUM type
```
=> executor, codec: hash join build wrong hash key for ENUM/SET value

pkg/session/bootstraptest/main_test.go, pkg/session/clusteredindextest/main_test.go, pkg/session/main_test.go, pkg/session/nontransactionaltest/main_test.go, pkg/session/schematest/main_test.go, pkg/session/temporarytabletest/main_test.go, pkg/session/test/common/main_test.go, pkg/session/test/main_test.go, pkg/session/test/meta/main_test.go, pkg/session/test/privileges/main_test.go, pkg/session/test/txn/main_test.go, pkg/session/test/variable/main_test.go, pkg/session/test/vars/main_test.go, pkg/store/copr/copr_test/main_test.go, tests/realtikvtest/testkit.go
Issue Number: close #49038
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix goleak in the client-go

pkg/sessionctx/variable/noop.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/variable_test.go
Issue Number: close #48910
default_password_lifetime should not be noop.
Move default_password_lifetime from noop to sysvar.
Tests 
> 
```
mysql> select * from information_schema.VARIABLES_INFO where VARIABLE_NAME='default_password_lifetime'\G
*************************** 1. row ***************************
VARIABLE_NAME: default_password_lifetime
VARIABLE_SCOPE: GLOBAL
DEFAULT_VALUE: 0
CURRENT_VALUE: 0
MIN_VALUE: 0
MAX_VALUE: 65535
POSSIBLE_VALUES: NULL
IS_NOOP: NO
1 row in set (0.02 sec)
mysql> set global default_password_lifetime=2;
Query OK, 0 rows affected (0.01 sec)
mysql> select @@global.default_password_lifetime;
+------------------------------------+
| @@global.default_password_lifetime | …
```
=> sessionctx: move default_password_lifetime out of noop

pkg/util/memory/tracker.go
Issue Number: ref https://github.com/pingcap/tidb/issues/44736
Tests 
> Current Tests have already covered, so no need to add more tests.
Side effects
Documentation
```release-note
None
```
=> util/memory: use atomic.Pointer instead of atomic.Value for byteLimits

pkg/statistics/handle/history/history_stats.go
Issue Number: close #49076
if it has any historical stats in the tikv, It is possible to panic
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix panic in the RecordHistoricalStatsToStorage

config/config.go, distsql/select_result.go, executor/adapter.go, sessionctx/variable/sysvar.go, sessionctx/variable/tidb_vars.go, util/execdetails/execdetails.go, util/logutil/log.go
Issue Number: ref #48947
Record the expensive scan queries in the slow log. Adding a new system varible `tidb_expensive_scan_ratio` to config the expensive scan ratio. It works seperately with the slow log theshold.
For example
```
...
...
...
select * from t;
```
When set to `6`, the `select * from t` is regarded as expensive scan.
Here the `Rocksdb_key_skipped_count` is `25` and  `Process_keys` is `4`.
Note it works for `SELECT` statments with coprocessor tasks only in this PR by now, the `point get` and `batch point get` expensive scan could not be recorded yet.
Tests 
Side effects
Documentation …
=> server: log expensive scan query in slow log

pkg/planner/cardinality/testdata/cardinality_suite_out.json, pkg/statistics/builder.go
Issue Number: close https://github.com/pingcap/tidb/issues/49080
as described in the issue. we make 0 topn to return empty topn.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix return 1 topn when to set 0 topn in analyzeOption

pkg/server/conn.go, pkg/server/conn_test.go
Issue Number: ref #48224, #36793 and #32110
Please check https://github.com/pingcap/tidb/issues/36793#issuecomment-1823563911 for more details and context:
> But for further enhancement, we cloud still try to make [closeConn](https://github.com/pingcap/tidb/blob/3f94666b4bafd903886b89206ac603d26d9a9e87/pkg/server/conn.go#L352-L354) thread-safe.
Tests 
> 
Side effects
- None
Documentation
- None
```release-note
None
```
=> server: make `clientConn()` thread-safe

server/conn.go, tidb-server/main.go
This reverts commit 877198dde22010e428be26aa0d7bdc5aab75d629.
Issue Number: ref https://github.com/pingcap/tidb/issues/49098
https://github.com/pingcap/tidb/pull/32111 causes too many problems, so we decided to revert it in v6.5.6 and merge https://github.com/pingcap/tidb/pull/49073 to v6.5.6.
Revert PR.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> Revert "server: Set default drainClientWait as 15s (#42134) (#48944)"

pkg/executor/executor_failpoint_test.go, pkg/executor/shuffle.go
Issue Number: close https://github.com/pingcap/tidb/issues/48230
Tests 
Test issue https://github.com/pingcap/tidb/issues/48230 by manual
> 
Side effects
Documentation
```release-note
Fix tidb crash when shuffleExec quit unexpectedly
```
=> executor: fix tidb crash when shuffleExec quit unexpectedly

pkg/util/cgroup/cgroup_cpu_linux.go, pkg/util/cpu/cpu_test.go
Issue Number: close #49014
Tests 
```
Run TestCPUValue and TestGetCgroupCPU in my own computer successed.
Also 82b39298b046ca8f65fefc3b305fad3eb7f590df commit runs successed in CI env(docker env).
```
> 
Side effects
Documentation
```release-note
None
```
=> cgroup: use a more accurate way to determine `inContainer()`

pkg/domain/extract_test.go, pkg/domain/plan_replayer_test.go, pkg/executor/test/executor/executor_test.go, pkg/server/handler/extractorhandler/BUILD.bazel, pkg/server/handler/extractorhandler/extract_test.go
Issue Number: close #49127
Remove the `extract` and `replayer` folder after running tests related with them.
Tests 
> This PR is modifying tests
Side effects
```release-note
None
```
=> test: remove test files (`extract` and `replayer`) after running tests

pkg/ddl/ingest/backend.go
This PR adds a failpoint to change flush local interval, thus we can change this in test environment.
See code changes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl/ingest: add failpoint to change flush local interval

pkg/statistics/BUILD.bazel, pkg/statistics/histogram.go
Issue Number: close #49168 
it need to clean the old data when to release bucket4Merging
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix old bucket4Merging to merge new data

pkg/bindinfo/handle.go
Issue Number: close #49113
Problem Summary: planner: fix DATA RACE caused by TestDropBindBySQLDigest
planner: fix DATA RACE caused by TestDropBindBySQLDigest
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix DATA RACE caused by TestDropBindBySQLDigest

pkg/executor/builder.go, pkg/executor/set_test.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #48949
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: add tidb_analyze_distsql_scan_concurrency

pkg/server/conn.go, pkg/server/conn_test.go
Issue Number: close #49190
The `conn` shouldn't be registered as a statistics. The `RegisterStatistics` should be called for each **kind** of statistics. Registering every connection on it will cause memory leak.
Create a new struct `compressionStats` to register the status variables.
Tests 
> 
```release-note
None
```
=> server: register compression statistics and fix the memory leak

pkg/executor/cte.go, pkg/executor/cte_test.go, pkg/util/cteutil/BUILD.bazel, pkg/util/cteutil/storage.go
Issue Number: close https://github.com/pingcap/tidb/issues/49096
Tests 
> 
Side effects
Documentation
```release-note
executor: fix deadlock in dml statement with cte when oom panic action was triggered
```
=>  executor: fix deadlock in dml statement with cte when oom panic action was triggered

errors.toml, pkg/errno/errname.go, pkg/executor/test/loadremotetest/error_test.go
Issue Number: close #49196
Tests 
only changes error msg
Side effects
Documentation
```release-note
None
```
=> errmsg: fix example s3 url in error msg

pkg/meta/autoid/autoid_service.go, pkg/metrics/grafana/tidb.json, pkg/metrics/meta.go, pkg/metrics/metrics.go
Issue Number: close #48942
From time.Sleep(200ms) to bo.Backoff() and the duration increase every time.
Tests 
start tidb 4000, 4001, where 4001 is the autoid service leader
Run some workload connect to tidb 4000
kill -9 to kill the tidb 4001 instance
Watch the autoid client connection retry behaviour:
> 
Side effects
Documentation
```release-note
None
```
=> meta/autoid: change to exponental backoff and add a reset count metric

pkg/domain/domain.go, pkg/statistics/builder.go, pkg/statistics/handle/autoanalyze/autoanalyze.go, pkg/statistics/handle/cache/statscache.go, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/globalstats/global_stats_async.go, pkg/statistics/handle/handle.go, pkg/statistics/handle/lockstats/lock_stats.go, pkg/statistics/handle/lockstats/unlock_stats.go, pkg/statistics/handle/logutil/logutil.go, pkg/statistics/handle/storage/read.go, pkg/statistics/handle/storage/save.go, pkg/statistics/histogram.go
Issue Number: close #49216
```statstics.logutil``` is initialized after the global one. so it prints the log at the stdout.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix log for statistics

tests/integrationtest/r/collation_agg_func_disabled.result, tests/integrationtest/r/collation_check_use_collation_disabled.result, tests/integrationtest/r/collation_misc_disabled.result, tests/integrationtest/r/collation_misc_enabled.result, tests/integrationtest/r/executor/executor.result, tests/integrationtest/r/executor/write.result, tests/integrationtest/r/privilege/privileges.result, tests/integrationtest/run-tests.sh, tests/integrationtest/t/collation_agg_func.test, tests/integrationtest/t/collation_check_use_collation.test, tests/integrationtest/t/collation_misc.test, tests/integrationtest/t/ddl/constraint.test, tests/integrationtest/t/ddl/db_partition.test, tests/integrationtest/t/ddl/table_modify.test, tests/integrationtest/t/executor/aggregate.test, tests/integrationtest/t/executor/delete.test, tests/integrationtest/t/executor/executor.test, tests/integrationtest/t/executor/foreign_key.test, tests/integrationtest/t/executor/issues.test, tests/integrationtest/t/executor/update.test, tests/integrationtest/t/executor/write.test, tests/integrationtest/t/expression/builtin.test, tests/integrationtest/t/expression/json.test, tests/integrationtest/t/planner/core/integration_partition.test, tests/integrationtest/t/planner/funcdep/only_full_group_by.test, tests/integrationtest/t/privilege/privileges.test
Problem Summary: enable `check-error` for mysql-tester and fix some mistakes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tests: enable `check-error` for integrationtest

pkg/ddl/constraint.go, pkg/ddl/db_table_test.go, pkg/ddl/table.go, tests/integrationtest/r/ddl/constraint.result, tests/integrationtest/t/ddl/constraint.test
Issue Number: close #48038
Currently, when `tidb_enable_check_constraint` is ON, the uniqueness of constraint names is not enforced by the check constraint when creating a table creation. This PR fixes this problem and enforces check constraints.
Tests 
>   
Side effects
Documentation
```release-note
None
```
=> ddl: constraint name uniquness is enforced for check constraints

pkg/bindinfo/BUILD.bazel, pkg/bindinfo/capture.go, pkg/bindinfo/global_handle.go, pkg/bindinfo/global_handle_test.go, pkg/bindinfo/session_handle.go, pkg/bindinfo/session_handle_test.go, pkg/domain/domain.go, pkg/executor/adapter.go, pkg/executor/bind.go, pkg/executor/show.go, pkg/planner/core/plan_cache.go, pkg/planner/optimize.go, pkg/session/bootstrap.go, pkg/session/session.go
Problem Summary: planner: encapsulate binding operations behind 2 interfaces
planner: encapsulate binding operations behind 2 interfaces
NO LOGICAL CHANGE, JUST REFACTOR
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: encapsulate binding operations behind 2 interfaces

ci.md
Issue Number: close https://github.com/pingcap/tidb/issues/49266
update ci commands doc
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> docs: update ci commands doc

pkg/ddl/partition.go, pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/ddl_test.go, pkg/statistics/handle/ddl/exchange_partition.go, pkg/statistics/handle/util/BUILD.bazel, pkg/statistics/handle/util/ddl_event.go
Issue Number: close https://github.com/pingcap/tidb/issues/47354
Based on [this design doc](https://pingcap.feishu.cn/docx/OLCrdxHj2ojb9KxlUvUch60LnBe#part-PRTmdkF0doiZSxxHHmDckfeJnZf), we will only update the count and modfiy_count for it. Then it will use the count and modify_count to determine if we need to trigger an auto-analysis task.
So in this PR, I updated the global stats with the old partition info and table info.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: handle exchange partition event

pkg/plugin/BUILD.bazel, pkg/plugin/plugin.go, pkg/plugin/plugin_test.go
Issue Number: close #49273
Recreate watch channel when it is closed
Tests 
> 
Side effects
Documentation
```release-note
fix bug that watch loop will refresh frequently when channel closed sometimes
```
=> plugin: fix bug that watch loop will refresh frequently when channel closed

pkg/executor/adapter.go, pkg/server/conn.go, pkg/server/conn_stmt.go, pkg/server/internal/resultset/BUILD.bazel, pkg/server/internal/resultset/resultset.go, pkg/session/session.go
Issue Number: close #48667
In the old interface design, `ResultSet.Close()`  may return error, and we must make sure the error is returned to the client, otherwise we get this issue https://github.com/pingcap/tidb/issues/48446
In the previous https://github.com/pingcap/tidb/pull/48447 I make sure the error is returned, but that cause peformance regression #48667
So the idea is split the work of Close() into two: the part that may return error and the part that may not return error.
```
Finish() error
Close()
```
We call Finish() first and writeEOF(), then call Close().
Tests 
Run sysbench and get the flamegraph:
Now Close() will be after writeChunks() and there is a Finish() call inside writeChunks().
> 
Side effects …
=> server,executor: split ResultSet Close() to Finish() and Close()

br/pkg/lightning/importer/tidb.go, pkg/bindinfo/BUILD.bazel, pkg/bindinfo/global_handle.go, pkg/domain/BUILD.bazel, pkg/domain/sysvar_cache.go, pkg/executor/asyncloaddata/BUILD.bazel, pkg/executor/asyncloaddata/progress.go, pkg/table/temptable/BUILD.bazel, pkg/table/temptable/interceptor.go, pkg/timer/runtime/BUILD.bazel, pkg/timer/runtime/runtime.go
as the title describes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: replace exp/maps with std/maps

pkg/statistics/histogram.go, pkg/statistics/histogram_test.go
Issue Number: close #49023
for better performance, we reuse memory to avoid allocating memory frequently. but bug will happen here. when we remove the empty bucket, use the non-empty bucket to overwrite it. but we cannot use the empty bucket to put into the pool. we wrongly put the non-empty bucket into the pool. it will lead to problems.
Tests 
We have tested with problem data. it will not raise this error.
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix illegal bucket order when to merge global stats

br/pkg/lightning/common/main_test.go, pkg/store/helper/main_test.go
Issue Number: close #43430
Ignore some expected goroutine leak when DNS server is slow, like 
```
[2023/12/11 10:24:20.846 +08:00] [ERROR] [client.go:256] ["[pd] do http request failed"] [name=GetMinResolvedTSByStoresIDs] [url=http://invalid_pd_address/pd/api/v1/min-resolved-ts] [error="Get \"http://invalid_pd_address/pd/api/v1/min-resolved-ts\": dial tcp: lookup invalid_pd_address on [fe80::1%enp34s0]:53: no such host"] [stack="github.com/tikv/pd/client/http.(*client).request\n\t/home/jasonmo/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20231130081618-862eee18738e/http/client.go:256\ngithub.com/tikv/pd/client/http.(*client).requestWithRetry\n\t/home/jasonmo/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20231130081618-862eee18738e/http/client.go:223\ngithub.com/tikv/pd/client …
```
=> test: ignore some expected goroutine leak

tests/globalkilltest/BUILD.bazel, tests/globalkilltest/global_kill_test.go, tests/globalkilltest/util.go
Issue Number: close #49316 
Problem Summary: **test: Global Kill e2e test is flaky**
- Wait services (PD, TiKV & TiDB) to be healthy before executing test cases.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tests: wait services to be healthy before executing test cases in GlobalKill e2e tests

pkg/statistics/handle/storage/BUILD.bazel, pkg/statistics/handle/storage/stats_read_writer.go, pkg/statistics/handle/storage/stats_read_writer_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/49334
1. Set the statsVer correctly.
2. Added a unit test for this behavior.
Tests 
> 
Side effects
Documentation
```release-note
Fix dropped partition stats meta can not record issue
```
=> statistics: fix can not record meta history issue

br/pkg/lightning/backend/external/BUILD.bazel, br/pkg/lightning/backend/external/bench_test.go, br/pkg/storage/BUILD.bazel, br/pkg/storage/gcs.go, br/pkg/storage/gcs_test.go, br/pkg/storage/storage.go
Issue Number: close #49340
Tests 
run TestReadFileConcurrently and check speed can use all network bandwidth
before
```
bench_test.go:575: concurrent read speed for 2.136GiB bytes(20 files): 234.9MiB/s, total-dur=9.309418879s
```
after
```
bench_test.go:568: concurrent read speed for 2.136GiB bytes(20 files): 2.353GiB/s, total-dur=907.624007ms
```
> 
Side effects
Documentation
```release-note
None
```
=> br/storage: disable keep alive for GCS on default to speed up request

pkg/executor/test/executor/executor_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/49323
We shoud call the rs.Close() first, and the run the next sql.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix data race for test TestColumnName

pkg/domain/resourcegroup/BUILD.bazel, pkg/domain/resourcegroup/runaway.go
Issue Number: close #49351
Change map to SyncMap to avoid data race.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> domain: fix data race in runaway DeriveChecker

pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/drop_partition.go
Issue Number: ref https://github.com/pingcap/tidb/issues/48126
1. Moved the code to a separate file to have better readability.
2. Do not use the stats meta from the cache, maybe it is outdated.
3. ~~Added a TODO item. There are some bugs in ResetTableStats2KVForDrop which prevent it from storing history correctly. I will fix it in my next PR, and then I will complete this TODO.~~ After offline discussion with @time-and-fate, it's OK to put them in the different txns.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: do not get stats meta from cache when handling drop partition DDL event

pkg/expression/expression.go, pkg/expression/integration_test/integration_test.go
Issue Number: close #49126
Tests 
```release-note
None
```
=> expression: Granular Control in mysql.expr_pushdown_blacklist Configuration

pkg/statistics/handle/storage/dump_test.go, pkg/statistics/handle/storage/stats_read_writer.go, pkg/statistics/handle/types/interfaces.go
Issue Number: close #49374
Problem Summary: When `runtime.GOMAXPROCS(0)` return 1, the `concurrencyForPartition` will be set to 0.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix `LoadStatsFromJSONNoUpdate` func for `CPUNum = 1`

pkg/planner/core/plan_cache.go, pkg/planner/core/plan_cache_test.go
Issue Number: close #49344
Problem Summary: planner: check whether plan-cache is disabled each time when getting plan from the plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: check whether plan-cache is disabled each time when getting plan from the plan cache

pkg/statistics/fmsketch.go
Issue Number: close #49381
Tests 
before
after:
The new one has better CPU usage.
the left one is the old, the right one is the new.
> 
Side effects
Documentation
```release-note
None
```
=> statsitics: clear the fmsketch's map correctly

br/pkg/lightning/backend/external/bench_test.go
Issue Number: ref #48952 
Add bench for merge step:
1. with ascending order kv
2. with random kv
On gcs with 16c machine.
```
bench_test.go:951: merge speed for 1258292064 bytes in 18.53020444s, speed: 64.76 MB/s
bench_test.go:951: merge speed for 1258292064 bytes in 18.243174291s, speed: 65.78 MB/s
```
The speed is relative slow since we haven't support parallel upload for gcs.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> global sort: bench merge step

br/pkg/lightning/importer/table_import.go
Issue Number: close #49368
Tests 
import parquet file, success(fail before this pr)
> 
Side effects
Documentation
```release-note
None
```
=> lightning: fix parquet import always fail

pkg/planner/core/casetest/enforcempp/enforce_mpp_test.go, pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json, pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json, pkg/planner/core/find_best_task.go, pkg/planner/core/stats.go
Issue Number: close https://github.com/pingcap/tidb/issues/49285
Tests 
> 
Side effects
Documentation
```release-note
planner: fix tiflash path will be identified as table dual
```
=> planner: fix tiflash path will be identified as table dual

br/pkg/lightning/backend/external/bench_test.go, br/pkg/restore/BUILD.bazel, br/pkg/restore/stream_metas_test.go, br/pkg/storage/BUILD.bazel, br/pkg/storage/gcs.go, br/pkg/storage/gcs_test.go, br/pkg/storage/storage.go, br/pkg/storage/storage_test.go, br/pkg/task/BUILD.bazel, br/pkg/task/stream.go, br/pkg/task/stream_test.go, pkg/ddl/backfilling_merge_sort.go, pkg/executor/importer/import.go, tests/realtikvtest/addindextest2/global_sort_test.go
Issue Number: ref #49340
- remove default GCS httpclient and init httpclient on need, as BR might cause some issue when reading many metadata
- `https://www.googleapis.com/auth/cloud-platform` must be add to scope to use `service_account` type of credential-file, else it report:
```
oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_scope\",\"error_description\":\"Invalid OAuth scope or ID token audience provided.\"}"
```
Tests 
run `TestReadFileConcurrently` with a service_account type of credential file
> 
Side effects
Documentation …
=> br/storage: add scope to support service_account type of credential file & remove default GCS httpclient

pkg/ddl/BUILD.bazel, pkg/ddl/index.go, pkg/disttask/framework/proto/task.go, pkg/disttask/framework/storage/BUILD.bazel, pkg/disttask/framework/storage/table_test.go, pkg/disttask/framework/storage/task_table.go, pkg/disttask/framework/testutil/disttest_util.go, tests/realtikvtest/addindextest1/BUILD.bazel, tests/realtikvtest/addindextest1/disttask_test.go
- adjust add index task concurrency to make sure it can be scheduled
- add sanity check that task.Concurrency should < cpu-cpunt when submit task
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> addindex/disttask: adjust add index task concurrency & add check when submit task

pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/ddl_test.go, pkg/statistics/handle/ddl/truncate_partition.go, pkg/statistics/handle/globalstats/global_stats_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/39681
- Relocated truncate partition logic to truncate_partition.go.
- Updated the global stats correctly, updated the count, and modify_count for the global table.
- Added test case for truncating one partition and multiple partitions.
- Fixed the broken old test case for global stats.
Tests 
> 
Side effects
Documentation
```release-note
Fix TiDB global stats meta update issue after truncating tables
```
=> statistics: update the global stats correctly after truncate a partition

pkg/executor/builder.go, pkg/executor/table_reader.go, pkg/planner/core/explain.go, pkg/planner/core/physical_plans.go, pkg/planner/core/plan_to_pb.go, pkg/planner/core/tiflash_selection_late_materialization.go
… condition
Issue Number: close #49241
tidb integration test does not support tiflash now, add test in tiflash https://github.com/pingcap/tiflash/pull/8480
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fill correlated column value in late materialization filter conditions

pkg/expression/builtin.go, pkg/expression/builtin_grouping_test.go, pkg/expression/distsql_builtin.go
Issue Number: ref #47958
After we removed ctx cache inner `ScalarFunction`. The `ctx` parameter in `newBaseBuiltinFuncWithFieldType` is useless, just remove it.
Tests 
> Simple code, no need to test
Side effects
Documentation
```release-note
None
```
=> expression: remove useless ctx input in `newBaseBuiltinFuncWithFieldType`

pkg/planner/core/logical_plan_builder.go, tests/integrationtest/r/planner/core/issuetest/planner_issue.result, tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #48969 
When we build the recursive CTE, we'll first try to build it as a non-recursive one. And going to treat it as a real recursive one when we actually meet the recursive part.
So the non-recursive part is built twice, but we don't pop the rowid information correctly, causing the UPDATE's result wrong.
Tests 
> 
Side effects
Documentation
```release-note
Fix the possible wrong result when the UPDATE/DELETE contains the Recursive CTE.
```
=> planner: the recursive cte will make UPDATE's result wrong

pkg/ddl/table.go, pkg/meta/meta.go, pkg/meta/meta_test.go, pkg/parser/model/model.go
Issue Number: close https://github.com/pingcap/tidb/issues/49370
`ListTables` took a lot of time when the number of tables was relatively large
Because the unmarshal of the `TableInfo` structure takes a large proportion of time, we only needn't all structures of the `TableInfo`. So we use `TableNameInfo` instead of it.
Tests 
Execute `checkTableNotExistsFromStore` function consumption of time.
| Total Table Count 	| Current DB Table Count 	| Master Branch Take Time 	| After this PR Table Time 	|
|-------------------	|------------------------	|-------------------------	|--------------------------	|
| 437k              	| 215k                   	| 23-26s                  	| 12-14s                   	|
Master branch info:
After this PR info(The middle area is particularly …
=> *: speed up `create table` when the number of tables is relatively large

pkg/executor/executor.go, tests/integrationtest/r/executor/issues.result, tests/integrationtest/t/executor/issues.test
Issue Number: close #49369
Fix the compatibility issue.
Tests 
> 
Side effects
Documentation
```release-note
In non-strict SQL mode, treat the overflow error as warning in insert statement.
```
=> executor: set OverflowAsWarning for insert statement in non-strict sql mode

DEPS.bzl, go.mod, go.sum, pkg/planner/cardinality/selectivity.go, pkg/planner/core/common_plans.go, pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/expression_rewriter.go, pkg/planner/core/find_best_task.go, pkg/planner/core/indexmerge_path.go, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/optimizer.go, pkg/planner/core/plan_cache.go, pkg/planner/core/plan_cache_utils.go, pkg/planner/core/planbuilder.go, pkg/planner/core/point_get_plan.go, pkg/planner/core/preprocess.go, pkg/planner/core/rule_join_reorder.go, pkg/planner/core/rule_join_reorder_greedy.go, pkg/planner/core/rule_partition_processor.go, pkg/planner/core/rule_semi_join_rewrite.go, pkg/planner/core/stats.go, pkg/planner/core/task.go, pkg/planner/optimize.go, pkg/sessionctx/stmtctx/stmtctx.go
* if a error is only generated and used like warning and note, don't bind unnecessary stack info with it. Because showExec (show warning logic) only fetch errCode and errMsg to show.
* if a error is generated in deep call chain, by now, always generating it with stack, because you couldn't know whether it will be used like error/warning/note later.
* if a error is treated several ways according sqlMode/var/hint/ticker and some thing, eg: like the code below, the error can be possibly treated like an error, always generating stack info with it.
```go
if err != nil {
// generate ERROR here.
stmtCtx.IsSyncStatsFailed = true
if variable.StatsLoadPseudoTimeout.Load() {
logutil.BgLogger().Warn("SyncWaitStatsLoad …
```
=> planner: refactor planner module's warning and note generation logic (get rid of unnecessary stack info)

pkg/executor/index_lookup_hash_join.go, pkg/executor/test/jointest/join_test.go
Issue Number: close #49453
Problem Summary: `IndexNestedLoopHashJoin.isDryUpTasks` sometimes will return true when ctx be canceled instead of get a task from `e.taskCh`. This can lead to missed panic errors.
This situation is easier to trigger when `GOMAXPROCS = 1`, so change the test case.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix `IndexNestedLoopHashJoin` missed panicErr

pkg/expression/builtin.go, pkg/expression/column.go, pkg/expression/constant.go, pkg/expression/expression.go, pkg/expression/scalar_function.go, pkg/expression/util_test.go, pkg/planner/core/scalar_subq_expression.go
Issue Number: close #49467
Just remove `expression.ReverseExpr` because it is useless now.
Tests 
> simple code, just make sure build pass is enough
Side effects
Documentation
```release-note
None
```
=> expression: remove interface `expression.ReverseExpr`

DEPS.bzl, go.mod, go.sum, pkg/domain/infosync/info.go, pkg/store/helper/helper.go
Issue Number: ref #35319, https://github.com/tikv/pd/issues/7300.
Add caller ID to the PD HTTP client on the hot path.
Tests 
```release-note
None
```
=> infosync, helper: add caller ID to the PD HTTP client on the hot path

br/pkg/backup/BUILD.bazel, br/pkg/backup/client.go, br/pkg/backup/client_test.go, br/pkg/utils/misc.go
Issue Number: close https://github.com/pingcap/tidb/issues/48405
the storeheart could behind more than 100s if user set don't care the store heartbeat duration and set it to 1 minute.
1. change 100s to 300s
2. use more better retry mechanism.
Tests 
>   
Side effects
Documentation
```release-note
None
```
=> backup: more stable check liveness when store heartbeat behind too much

br/pkg/lightning/backend/kv/session.go, pkg/ddl/backfilling_scheduler.go, pkg/errctx/context.go, pkg/errctx/context_test.go, pkg/executor/executor.go, pkg/expression/builtin_arithmetic.go, pkg/expression/builtin_arithmetic_vec.go, pkg/expression/builtin_cast.go, pkg/expression/builtin_cast_test.go, pkg/expression/builtin_cast_vec.go, pkg/expression/typeinfer_test.go, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/stmtctx/stmtctx_test.go, pkg/table/column.go, pkg/util/codec/codec_test.go, tests/integrationtest/r/ddl/integration.result, tests/integrationtest/r/executor/delete.result, tests/integrationtest/r/executor/insert.result, tests/integrationtest/t/ddl/integration.test, tests/integrationtest/t/executor/delete.test, tests/integrationtest/t/executor/insert.test
Issue Number: close #49143, close #49137
The difference between `OverflowAsWarning` and `TruncatedAsWarning` doesn't actually exist. The existing difference are all incompatible with MySQL.
**I suggest to read https://github.com/pingcap/tidb/issues/49141#issuecomment-1838583457. It gives a clearer explanation on why this PR is right.**
This PR removes `OverflowAsWarning` and handle them through `HandleError`. Actually `HandleError` and `HandleTruncate` are the same (and `HandleTruncate` will be removed in this or next week). As we provided `HandleErrorWithAlias`, it's more appropriate for this PR.
Tests 
> 
Side effects
Documentation …
=> stmtctx: remove OverflowAsWarning flag

pkg/disttask/framework/handle/BUILD.bazel, pkg/disttask/framework/handle/handle_test.go, pkg/disttask/framework/storage/table_test.go, pkg/disttask/framework/testutil/table_util.go
Issue Number: close #49463
Unit tests should not rely on the real CPU count in test environment.
Enable mock CPU count failpoint.
Tests 
```
make ut
```
> 
Side effects
Documentation
```release-note
None
```
=> test: fix make ut for package disttask/framework

build/linter/bootstrap/analyzer.go, pkg/session/bootstrap.go
Issue Number: close #49485
We did not assig a explicitly version to `version181`, see: https://github.com/pingcap/tidb/pull/49426/files#diff-2fde3341e0231e7b162880b36f07d23b7949ca512c5536b50706ac5aa9072b25R1045
Seems golang will not increase the last const value when the list not started with iota, see: https://go.dev/play/p/dCORpY3lJP7
```
const (
v1 = 1
v2
)
func main() {
fmt.Println(v1)
fmt.Println(v2)
}
```
result is
```
1
1
```
See PR
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix upgrade error for version 181

pkg/executor/test/executor/BUILD.bazel, pkg/executor/test/executor/executor_test.go, pkg/parser/ast/dml.go, pkg/parser/parser.y, pkg/planner/core/casetest/physicalplantest/BUILD.bazel, pkg/planner/core/casetest/physicalplantest/physical_plan_test.go, pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_in.json, pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json, pkg/planner/core/logical_plan_builder.go, tests/integrationtest/t/executor/executor.test
Issue Number: close https://github.com/pingcap/tidb/issues/49377
Tests 
> 
Side effects
Documentation
```release-note
parser, planner: fix embedded setOprStmt will be seen as SetOprSelectList item and lost its orderBy and Limit
```
=> parser, planner: fix embedded setOprStmt will be seen as SetOprSelectList item and lost its orderBy and Limit

DEPS.bzl, expression/builtin_convert_charset.go, expression/integration_test.go, go.mod, go.sum
This is a manually cherry-pick of #49527
Issue Number: close #49526
Ignore the `TypeNull` in `HandleBinaryLiteral`, as the `castStringToString` will actually do nothing for NULL (except changing the type).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: ignore NULL in handle binary literal

DEPS.bzl, go.mod, go.sum, pkg/expression/builtin_convert_charset.go, tests/integrationtest/r/expression/cast.result, tests/integrationtest/t/expression/cast.test
Issue Number: close #49526
Ignore the `TypeNull` in `HandleBinaryLiteral`, as the `castStringToString` will actually do nothing for NULL (except changing the type).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: ignore `TypeNULL` in `HandleBinaryLiteral`

pkg/expression/chunk_executor.go, tests/integrationtest/r/expression/enum_set.result, tests/integrationtest/t/expression/enum_set.test
Issue Number: close #49487 
The invalid enum/set value can exist during evaluation. So we should not throw error here.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: enum/set could be invalid during evaluation

br/pkg/lightning/backend/external/byte_reader.go, br/pkg/lightning/backend/external/byte_reader_test.go
Issue Number: ref #48952 close #49537
1. enable switch concurrent mode in byte reader test
2. fix a bug when switch mode.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> global sort: enable concurrent read test

pkg/ddl/cluster.go, pkg/ddl/cluster_test.go, pkg/ddl/tests/tiflash/BUILD.bazel, pkg/ddl/tests/tiflash/ddl_tiflash_test.go, pkg/executor/recover_test.go, pkg/executor/stale_txn_test.go, pkg/infoschema/test/clustertablestest/BUILD.bazel, pkg/infoschema/test/clustertablestest/tables_test.go, tests/realtikvtest/flashbacktest/BUILD.bazel, tests/realtikvtest/flashbacktest/flashback_test.go
Issue Number: ref #49493
Problem Summary: Deal with `TestTiDBTrx`, `TestSetTransactionReadOnlyAsOf` and flashback cluster related problems.
Just a workround for flashback cluster related test cases. The root case is https://github.com/pingcap/tidb/issues/49555.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tests: fix some tests failed when `system_time_zone != Asia/Shanghai`

pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/ddl_test.go, pkg/statistics/handle/ddl/reorganize_partition.go
Issue Number: close https://github.com/pingcap/tidb/issues/48226 close https://github.com/pingcap/tidb/issues/48233 close https://github.com/pingcap/tidb/issues/48231
- Reset old partition information.
- Added a test to cover it.
Tests 
> 
Side effects
Documentation
```release-note
Fix TiDB can't delete old partition statistics after partition reorganization issue
```
=> statistics: delete old partitions info after reorganize partitions 

pkg/statistics/handle/autoanalyze/BUILD.bazel, pkg/statistics/handle/autoanalyze/autoanalyze.go, pkg/statistics/handle/autoanalyze/autoanalyze_test.go
Issue Number: close #49552
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: skip auto-analyze when it is executed outside the available time period

br/pkg/lightning/backend/external/BUILD.bazel, br/pkg/lightning/backend/external/bench_test.go, br/pkg/lightning/backend/external/engine.go, br/pkg/lightning/backend/external/merge.go, br/pkg/lightning/backend/external/merge_v2.go, br/pkg/lightning/backend/external/onefile_writer.go, br/pkg/lightning/backend/external/onefile_writer_test.go, br/pkg/lightning/backend/external/reader_test.go, br/pkg/lightning/backend/external/sort_test.go, br/pkg/lightning/backend/external/testutil.go, br/pkg/lightning/backend/external/util.go, br/pkg/lightning/backend/external/writer.go, br/pkg/lightning/backend/external/writer_test.go
Issue Number: ref #48779
Implement new merge step. In new implementation, mergeIter is abandoned.
The new merge step process data from startKey to endKey, using datas and stats.
1. use rangeSplitter to split range groups to read data.
2. read range data then sort them.
3. write all data to only one file.
Currently, the new merge step use only 1 writer.
TODO:
1. We can speed up the process using multiple worker doing the merge process later.
2. Add more bench test after gcs parallel writer stable.
3. integrate with add index and import into.
4. See if the new merge step can handle more files.
Tests 
> 
Side effects
Documentation …
=> global sort: new merge with 1 writer

DEPS.bzl, go.mod, go.sum, pkg/executor/infoschema_cluster_table_test.go, pkg/executor/tikv_regions_peers_table_test.go, pkg/store/driver/tikv_driver.go, pkg/store/helper/helper_test.go
Issue Number: ref #35319, https://github.com/tikv/pd/issues/7300.
Update the PD HTTP client to support source mark via https://github.com/tikv/pd/pull/7565.
Tests 
```release-note
None
```
=> driver: update the PD HTTP client to support source mark

pkg/executor/adapter.go, pkg/executor/admin.go, pkg/executor/batch_point_get.go, pkg/executor/builder.go, pkg/executor/coprocessor.go, pkg/executor/cte.go, pkg/executor/executor.go, pkg/executor/index_lookup_join.go, pkg/executor/index_lookup_merge_join.go, pkg/executor/index_merge_reader.go, pkg/executor/insert.go, pkg/executor/internal/exec/executor.go, pkg/executor/join.go, pkg/executor/merge_join.go, pkg/executor/point_get.go
Issue Number: close #49490
Currently, the `BaseExecutor` and especially `BaseExecutor.Ctx()` is used everywhere. We need to progressively replace `BaseExecutor` with some `NewBaseExecutor` which doesn't have a `.Ctx` inside. To reach this goal, I'll use several functions to replace `Base() *BaseExecutor`.
This is a simple PR. It doesn't harm the logic. It adds the following functions to the `Executor` interface:
```go
NewChunk() *chunk.Chunk
NewChunkWithCapacity(fields []*types.FieldType, capacity int, maxCachesize int) *chunk.Chunk
RuntimeStats() *execdetails.BasicRuntimeStats
HandleSQLKillerSignal() error
RegisterSQLAndPlanInExecForTopSQL()
AllChildren() []Executor
```
Each executor can still use the `sctx` inside itself by calling `.BaseExecutor.Ctx()`, because they …
=> pkg/executor: refine the Executor interface

pkg/ddl/ddl_api.go, pkg/ddl/partition.go, pkg/ddl/schematracker/dm_tracker.go
* if a error is only generated and used like warning and note, don't bind unnecessary stack info with it. Because showExec (show warning logic) only fetch errCode and errMsg to show.
* if a error is generated in deep call chain, by now, always generating it with stack, because you couldn't know whether it will be used like error/warning/note later.
* if a error is treated several ways according sqlMode/var/hint/ticker and some thing, eg: like the code below, the error can be possibly treated like an error, always generating stack info with it.
```go
if err != nil {
// generate ERROR here.
stmtCtx.IsSyncStatsFailed = true
if variable.StatsLoadPseudoTimeout.Load() {
logutil.BgLogger().Warn("SyncWaitStatsLoad …
```
=> ddl: refactor ddl pkg's warning and note generation

.bazelrc, br/pkg/task/show/cmd_test.go, pkg/ddl/column_type_change_test.go, pkg/executor/brie.go, pkg/executor/slow_query.go, pkg/executor/slow_query_sql_test.go, pkg/executor/stale_txn_test.go, pkg/expression/integration_test/integration_test.go, pkg/util/stmtsummary/v2/reader_test.go
Issue Number: close #49493
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tests, executor, br: fix time_zone related bugs in UT

tests/realtikvtest/addindextest1/disttask_test.go
`TestAddIndexDistPauseAndResume` is unstable now and we cannot fix it quickly.
Skip integration test `TestAddIndexDistPauseAndResume`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: skip unstable test `TestAddIndexDistPauseAndResume`

pkg/statistics/analyze.go, pkg/statistics/handle/globalstats/global_stats_async.go, pkg/statistics/handle/storage/json.go, pkg/statistics/histogram.go, pkg/util/chunk/BUILD.bazel, pkg/util/chunk/chunk.go, pkg/util/chunk/pool.go
Issue Number: close #48584
Tests 
analyze a table with 292 columns.
before:
spend 2517.959s
Allocate Speed: 500MB/s
after:
spend 2422.801s
Allocate Speed: ~400MB/s
>   
Side effects
Documentation
```release-note
None
```
=> *: reuse chunk in the histogram

pkg/planner/core/integration_test.go, pkg/planner/core/rule_predicate_push_down.go
Issue Number: close #49616
Problem Summary: planner: fix the issue that the optimizer cannot convert OUTER JOIN to INNER JOIN with nested AND/OR in some cases
planner: fix the issue that the optimizer cannot convert OUTER JOIN to INNER JOIN with nested AND/OR in some cases
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix the issue that the optimizer cannot convert OUTER JOIN to INNER JOIN with nested AND/OR in some cases

pkg/statistics/column.go
Issue Number: close #49631
Add table id in timeout sync load log
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: add some key info in sync load timeout log

server/conn.go, server/conn_test.go, server/server.go, tidb-server/main.go, util/signal/signal_posix.go
This is a manual backport of #44953:
---------------------------------------------------------------------------------------------------------------------
Issue Number: close #44951
Problem Summary: After https://github.com/pingcap/tidb/pull/32111, user need to wait for all connections to be disconnected, or execute a new sql before tidb-server exit. It's not an expected behaviour.
Tests 
Side effects
Documentation
```release-note
Exit tidb-server directly when all connections not in txn
```
=> server: exit tidb-server directly when all connections not in txn (#44953)

br/pkg/lightning/checkpoints/checkpoints.go, br/pkg/lightning/checkpoints/checkpoints_sql_test.go
Issue Number: ref #30699
This PR removes `// nolint:gosec` for `IgnoreErrorCheckpoint()` as a tiny security enhancement of our source code, see https://securego.io/docs/rules/g201-g202.html for more details.
Tests 
> 
Side effects
- None
Documentation
- None
```release-note
None
```
=> br: update IgnoreErrorCheckpoint() for G201/G202 security rules

pkg/domain/BUILD.bazel, pkg/domain/plan_replayer.go, pkg/domain/plan_replayer_handle_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/49619
https://github.com/pingcap/tidb/blob/master/pkg/domain/plan_replayer.go#L169
We use fmt.Sprintf here. But this would generate an invalid SQL if the user's SQL contains a `'`.
So I added a test case to cover it and also fixed it by using the `%?` syntax.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> domain: do not use fmt.Sprint to format SQL

pkg/bindinfo/bind_cache.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> binding: fix linter for prealloc in the GetAllBindings

.gitignore, Makefile
Issue Number: ref #49070
After #30822, `make ut` will build the `.test.bin` files for each of the `_test.go` file and run them in parallel and clean `.test.bin` files. However, when `make ut` failed because of any reason, the cleanup will not happen and leave a large number of `.test.bin` files:
```
➜  tidb git:(bb7133/make_clean) ✗ find . -name '*.test.bin' -print0 | xargs -0 du -hsc
56M	./pkg/statistics/handle/lockstats/lockstats.test.bin
136M	./pkg/statistics/handle/handletest/lockstats/lockstats.test.bin
136M	./pkg/statistics/handle/handletest/handletest.test.bin
...
136M	./pkg/session/resourcegrouptest/resourcegrouptest.test.bin
136M	./pkg/session/temporarytabletest/temporarytabletest.test.bin
25G	total
```
IMO it's better to make `.test.bin` files cleanable by `make …
=> *: delete '.test.bin' files for 'make clean'

pkg/executor/aggfuncs/func_group_concat.go, pkg/executor/analyze.go, pkg/executor/bind.go, pkg/executor/builder.go, pkg/executor/compact_table.go, pkg/executor/ddl.go, pkg/executor/lockstats/lock_stats_executor.go, pkg/executor/lockstats/unlock_stats_executor.go, pkg/executor/memtable_reader.go, pkg/executor/plan_replayer.go, pkg/executor/revoke.go, pkg/executor/set.go, pkg/executor/simple.go, pkg/expression/simple_rewriter.go, pkg/table/tables/partition.go, pkg/util/misc.go
* if a error is only generated and used like warning and note, don't bind unnecessary stack info with it. Because showExec (show warning logic) only fetch errCode and errMsg to show.
* if a error is generated in deep call chain, by now, always generating it with stack, because you couldn't know whether it will be used like error/warning/note later and outer.
* if a error is treated several ways according sqlMode/var/hint/ticker and some thing, eg: like the code below, the error can be possibly treated like an error, we couldn't control generating logic with it. 
* if this error is generated in current level, like the second case below, generating it without stack info, and wrapping stack with it when warn is …
=> executor: refactor executor pkg's warning and note generation

pkg/parser/generate_keyword/genkeyword.go
Issue Number: ref #48801
The code added in #48807 doesn't truncate the file when re-creating it. This might lead to left over bits of previous versions if the new file is shorter.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser: truncate keywords.go when re-creating it

br/pkg/lightning/checkpoints/checkpoints.go, br/pkg/lightning/checkpoints/checkpoints_sql_test.go
Issue Number: ref #30699
caused by https://github.com/pingcap/tidb/pull/49637 CI is running but bot merged
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: fix integration test failed

pkg/metrics/grafana/tidb_resource_control.json
Issue Number: ref #49318
Change the resource group name from "name" to "resource_group" so we can add a global label selector later. Related tikv side change is https://github.com/tikv/tikv/pull/16192.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> metrics: change background resource group label name

cmd/mirror/mirror.go
Issue Number: close #49690
Print the stderr of `ExitErr` in `cmd/mirror` command. It now prints:
```
panic: subprocess exited with stderr: 
go: github.com/twmb/murmur3@v1.1.6: missing go.sum entry for go.mod file; to add it:
go mod download github.com/twmb/murmur3
goroutine 1 [running]:
main.main()
cmd/mirror/mirror.go:486 +0x105
```
If your `go.sum` somehow lost some rows.
Tests 
> Not important change. Only take effect for CI / dev environment.
> 
Side effects
Documentation
```release-note
None
```
=> bazel, mirror: print exit err in mirror/mirror.go

pkg/expression/builtin_regexp.go, pkg/expression/builtin_regexp_test.go, pkg/expression/distsql_builtin.go
Issue Number: close #49684
After #49584 and #49642 the old `regexpBaseFuncSig` is useless. Now, we can remove it and rename `regexpNewBaseFuncSig` to `regexpBaseFuncSig` now.
remove old `regexpBaseFuncSig` and rename `regexpNewBaseFuncSig` to `regexpBaseFuncSig`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: remove old `regexpBaseFuncSig` and rename `regexpNewBaseFuncSig` to `regexpBaseFuncSig`

pkg/util/dbterror/ddl_terror.go
Issue Number: close #49556
Temporary network partitioning may cause pk commit failure.
Add `global:2` to retryable error codes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> util/dbterror: add 'result undetermined' to retryable error codes

pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/ddl_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/49663
- Added a test case to cover this problem.
- Drop the old stats meta after truncating a table.
Tests 
> 
Side effects
Documentation
```release-note
Fix TiDB can not drop old stats meta after truncating a table issue
```
=> statistics: drop old stats meta after truncate a table 

pkg/expression/aggregation/concat.go, pkg/expression/builtin_encryption.go, pkg/expression/builtin_encryption_vec.go, pkg/expression/builtin_info.go, pkg/expression/builtin_json.go, pkg/expression/builtin_json_vec.go, pkg/expression/builtin_miscellaneous.go, pkg/expression/builtin_miscellaneous_vec.go, pkg/expression/builtin_string.go, pkg/expression/builtin_string_vec.go, pkg/expression/errors.go, pkg/expression/expression.go, pkg/expression/scalar_function.go
* if a error is only generated and used like warning and note, don't bind unnecessary stack info with it. Because showExec (show warning logic) only fetch errCode and errMsg to show.
* if a error is generated in deep call chain, by now, always generating it with stack, because you couldn't know whether it will be used like error/warning/note later and outer.
* if a error is treated several ways according sqlMode/var/hint/ticker and some thing, eg: like the code below, the error can be possibly treated like an error, we couldn't control generating logic with it. 
* if this error is generated in current level, like the second case below, generating it without stack info, and wrapping stack with it when warn is …
=> expression: refactor expression pkg's warning and note generation logic

pkg/sessionctx/stmtctx/BUILD.bazel, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/stmtctx/stmtctx_test.go
Issue Number: close #49688
We are going to add more and more complex logic to the initialization of errctx, so we'd better add a cache for it.
Use the `sync.Once` to achieve a lazy initialization.
Tests 
> 
Side effects
Documentation
The existing performance gain is also significant:
Before:
```
BenchmarkErrCtx
BenchmarkErrCtx-8   	552535581	         2.166 ns/op
```
After:
```
BenchmarkErrCtx
BenchmarkErrCtx-8   	1000000000	         0.7046 ns/op
```
```release-note
None
```
=> errctx, stmtctx: add cache to the errctx

pkg/planner/optimize.go, pkg/session/session.go, tests/readonlytest/BUILD.bazel, tests/readonlytest/readonly_test.go
Issue Number: close #49659
Problem Summary: I think the [original code ](https://github.com/pingcap/tidb/pull/31746/files#diff-0a0c95887230cee4dde6537c6be06ea308529b392c4c3303c242509f53bb8f1aR354) is unexpected.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> session: fix wrong test logic of tidb_super_read_only

br/pkg/restore/client.go, br/pkg/restore/client_test.go, br/pkg/stream/BUILD.bazel, br/pkg/stream/rewrite_meta_rawkv.go, br/pkg/stream/rewrite_meta_rawkv_test.go
Issue Number: close #49346
When there is no rewrite rule, need to skip trying to insert SQL to `gc_delete_range`
skip and add unit test
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: skip when rewrite rule not found

pkg/executor/analyze.go, pkg/executor/analyze_col.go, pkg/executor/analyze_col_v2.go
Issue Number: close #49704
Tests 
run ```go build -gcflags="-d=ssa/check_bce" ./pkg/executor/...```
before:
```
pkg/executor/analyze.go:339:10: Found IsInBounds
pkg/executor/analyze_col_v2.go:207:46: Found IsInBounds
pkg/executor/analyze_col_v2.go:207:98: Found IsInBounds
pkg/executor/analyze_col_v2.go:382:41: Found IsInBounds
pkg/executor/analyze_col_v2.go:382:91: Found IsInBounds
```
after:
```
pkg/executor/analyze_col_v2.go:207:88: Found IsInBounds
```
```
go test --tags=intest -run=^$ -bench=BenchmarkAnalyzePartition -benchmem github.com/pingcap/tidb/pkg/executor/test/analyzetest 
```
before
```
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/executor/test/analyzetest
BenchmarkAnalyzePartition-8            1        33893337833 ns/op       16944721856 B/op …
```
=> executor: BCE for the analyze

pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/drop_partition.go, pkg/statistics/handle/ddl/reorganize_partition.go, pkg/statistics/handle/ddl/truncate_partition.go, pkg/statistics/handle/storage/stats_read_writer.go, pkg/statistics/handle/storage/stats_read_writer_test.go, pkg/statistics/handle/types/interfaces.go
- Added better comments to `ResetTableStats2KVForDrop` to get better readability.
- Renamed to `UpdateStatsMetaVersionForGC`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: add better comments to UpdateStatsMetaVersionForGC

pkg/expression/builtin_func_param.go, pkg/expression/builtin_ilike.go, pkg/expression/builtin_ilike_vec.go, pkg/expression/builtin_like.go, pkg/expression/distsql_builtin.go, tests/integrationtest/r/expression/plan_cache.result, tests/integrationtest/t/expression/plan_cache.test
Issue Number: close #49674
Same as #49584 . In this PR we refactor some cache logic for `like` and `ilike` function
relies on #49678, we should fix datarace first
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: refactor like and ilike cache logic

pkg/util/rowcodec/decoder.go, tests/integrationtest/r/expression/multi_valued_index.result, tests/integrationtest/t/expression/multi_valued_index.test
Issue Number: close #49680
For multi-valued index, we should use the `ArrayType` to decode the restore data.
Use the `ArrayType` rather the direct `GetType` to decode the restore data. The `GetType` will give `JSON`, but we expect the internal type (e.g. unsigned integer, string...).
Tests 
> 
```release-note
Fix the issue that the compound index of multi-valued index and any other non-binary string cannot be inserted.
```
=> rowcodec: use array type to decode index value

pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/stmtctx/stmtctx_test.go, pkg/sessionctx/variable/noop.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/variable.go, pkg/sessionctx/variable/varsutil.go
Tests 
> 
Side effects
Documentation
```release-note
sessionctx: refactor sessionctx pkg's warning and note generation
```
=> sessionctx: refactor sessionctx pkg's warning and note generation

br/pkg/lightning/log/BUILD.bazel, br/pkg/lightning/log/log.go, br/pkg/lightning/log/log_test.go
Issue Number: close #49117
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: fix context.Cancelled nested in aws err

br/cmd/br/fips.go, br/cmd/tidb-lightning-ctl/fips.go, br/cmd/tidb-lightning/fips.go, cmd/tidb-server/fips.go
Issue Number: close #49771
Now we maintain special branch https://github.com/pingcap/tidb/tree/feature/release-6.5-fips instead of release with the master
The version already padding the branch name, so we can remove this, otherwise we get 'release-6.5-fips-fips'
Tests 
```
./bin/tidb-server -V
Release Version: v7.6.0-alpha-513-g8215479a68
```
> 
Side effects
Documentation
```release-note
None
```
=> br,tidb,lightning: remove 'fips' suffix on version

pkg/infoschema/test/clustertablestest/BUILD.bazel, pkg/infoschema/test/clustertablestest/cluster_tables_test.go, pkg/planner/core/planbuilder.go
Problem Summary: planner: support creating universal bindings from historical plans
planner: support creating universal bindings from historical plans
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: support creating universal bindings from historical plans

pkg/ddl/BUILD.bazel, pkg/ddl/ddl.go, pkg/ddl/ddl_api.go, pkg/ddl/ddl_api_test.go, pkg/ddl/ddl_running_jobs.go, pkg/ddl/ddl_running_jobs_test.go, pkg/ddl/ddl_worker.go, pkg/ddl/job_table.go, pkg/ddl/mock.go, pkg/parser/model/ddl.go, pkg/parser/model/ddl_test.go
Issue Number: close #49498
We should also consider schema & table name before picking a DDL job to execute.
- Extract `ddl.runningJobs` to a separate file.
- Add `AffectedSchemaNames` and `AffectedTableNames` to `model.Job`.
- Refine job depenency check.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: set jobs dependency by schema and table name

pkg/statistics/histogram.go
Issue Number: close #49750
Tests 
before
```
➜  tidb git:(master) go test -run=^$ -bench=BenchmarkMergePartTopN2GlobalTopNWithHists -benchmem github.com/pingcap/tidb/pkg/statistics/handle/globalstats
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/pkg/statistics/handle/globalstats
cpu: AMD Ryzen 7 7735HS with Radeon Graphics
BenchmarkMergePartTopN2GlobalTopNWithHists/Size100-16         	     200	   5901398 ns/op	  177652 B/op	      30 allocs/op
BenchmarkMergePartTopN2GlobalTopNWithHists/Size1000-16        	      12	  89938452 ns/op	  178092 B/op	      32 allocs/op
BenchmarkMergePartTopN2GlobalTopNWithHists/Size2000-16        	       4	 254384526 ns/op	  178248 B/op	      30 allocs/op
BenchmarkMergePartTopN2GlobalTopNWithHists/Size5000-16        	       1	1078682107 …
```
=> statistics: BCE for the histogram

pkg/ddl/backfilling.go
Issue Number: close https://github.com/pingcap/tidb/issues/49679, close https://github.com/pingcap/tidb/issues/49682
The optimization for the empty table(`startKey == nil && endKey == nil)` doesn't work.
The following case is obvious (because split regions take so long).
#49679 
```
[2023/12/20 11:23:10.873 +08:00] [INFO] [backfilling.go:712] ["start backfill workers to reorg record"] [category=ddl] [type="add index"] [workerCnt=4] [regionCnt=1] [startKey=] [endKey=]
...
[2023/12/20 11:25:14.752 +08:00] [INFO] [backfilling.go:559] ["get backfill range task, get reverse key failed"] [category=ddl] [error="[tikv:9005]Region is unavailable"]
...
...
```
Tests 
Before this PR, took time: 2min+
After this PR, took time: 40s+
> - [ ] I checked and no code files have been …
=> ddl: fix the optimization for the empty table(speed up)

br/pkg/storage/gcs_extra.go
Issue Number: ref #48443
The error is introduced when port https://github.com/liqiuqing/gcsmpu/blob/fffbb8a9ad154cfe8a9621f091973954d0146d7c/upload.go#L466-L479.
When use channel to send task in producer/consumer pattern, we'd better have only one way to nofity consumer exit, which is closing the channel
Tests 
> easy fix
Side effects
Documentation
```release-note
None
```
=> gcs: fix a deadlock in gs parallel writer

pkg/statistics/BUILD.bazel, pkg/statistics/builder.go, pkg/statistics/cmsketch.go, pkg/statistics/cmsketch_test.go
Issue Number: close #49801
Problem Summary: planner: a better way to round scale factor when collecting TopN stats
planner: a better way to round scale factor when collecting TopN stats
See https://github.com/pingcap/tidb/issues/49801 for more details.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: a better way to round scale factor when collecting TopN stats

build/nogo_config.json
Issue Number: close #40786
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: enable SA1019 to remove deprecated function

pkg/statistics/handle/autoanalyze/autoanalyze.go
- Only get the partition's stats meta once.
Before:
After:
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: do not get partition stats again and again

pkg/server/internal/dump/dump.go
Issue Number: close #44970
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> server: improve `dump.Uintxx` implementation

pkg/ddl/foreign_key.go, tests/integrationtest/r/ddl/foreign_key.result, tests/integrationtest/t/ddl/foreign_key.test
Issue Number: close #47702
Issue Number: close #49836
This pull request is for the compatibility with MySQL regarding altering columns with foreign key constraint.
#47702
As @YangKeao said,  the length of integer does nothing on the data. MySQL document also said so.
> For integer data types, M indicates the minimum display width. The maximum display width is 255. Display width is unrelated to the range of values a type can store
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html
You can confirm the behavior on TiDB as well.
```
tidb> CREATE TABLE bigint_test (
->     bigIntColumn1 bigint(10),
->     bigIntColumn2 bigint(1)
-> );
Query OK, 0 rows affected (0.07 sec)
tidb> INSERT INTO bigint_test (bigIntColumn1, bigIntColumn2) VALUES (1234567890, 1234567890); …
```
=> ddl: allow altering integer with foreign key and deny altering decimal with foreign key

pkg/executor/show.go, tests/integrationtest/r/executor/show.result, tests/integrationtest/t/executor/show.test
Issue Number: close #49839
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: display `pre_split_regions` for auto_random tables in `SHOW CREATE`

DEPS.bzl, go.mod, go.sum, pkg/domain/infosync/resource_manager_client.go
Issue Number: ref #49318
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: update pd-client and client-go

DEPS.bzl, go.mod, go.sum
Issue Number: close #49744
Due to https://github.com/tikv/pd/blob/master/client/http/client.go#L164 check, when leaderIdx is 0, will not enter loop
fixed in PD https://github.com/tikv/pd/pull/7622
Tests 
```release-note
None
```
=> gomod: update pd client to fix follower selection

pkg/domain/domain.go, pkg/executor/test/analyzetest/analyze_test.go, pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go, pkg/statistics/handle/autoanalyze/autoanalyze.go, pkg/statistics/handle/autoanalyze/autoanalyze_test.go, pkg/statistics/handle/types/interfaces.go, pkg/statistics/handle/updatetest/update_test.go, pkg/ttl/ttlworker/job_manager_integration_test.go
We don't need to pass the info schema from the domain directly. We can get it when we need if from the session context.
This would help us to simplify our interface design.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: do not use the infoSchema from domain directly

pkg/util/BUILD.bazel, pkg/util/cpuprofile/cpuprofile.go, pkg/util/wait_group_wrapper.go, pkg/util/wait_group_wrapper_test.go
Issue Number: close #49867
InitLogger contains zap.AddStacktrace(zapcore.FatalLevel), so log level below fatal will not contain stack automatically.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> util: fix recover log doesn't contains stack

br/pkg/lightning/backend/local/local.go, br/pkg/lightning/backend/local/local_test.go
Issue Number: close #49743
Tests 
> recover the old logic which is mistakenly delete before: below code is from v7.5
https://github.com/pingcap/tidb/blob/069631e2ecfedc000ffb92c67207bea81380f020/br/pkg/lightning/backend/local/local.go#L1420-L1426
Side effects
Documentation
```release-note
None
```
=> lightning: skip check if PD returns zero StoreInfo

pkg/statistics/histogram.go
Issue Number: close #49876
Tests 
before
```
pkg/statistics/histogram.go:304:49: Found IsInBounds
pkg/statistics/histogram.go:304:59: Found IsSliceInBounds
pkg/statistics/histogram.go:304:59: Found IsInBounds
pkg/statistics/histogram.go:307:49: Found IsInBounds
pkg/statistics/histogram.go:307:59: Found IsSliceInBounds
pkg/statistics/histogram.go:307:59: Found IsInBounds
pkg/statistics/histogram.go:315:46: Found IsInBounds
pkg/statistics/histogram.go:315:56: Found IsSliceInBounds
pkg/statistics/histogram.go:315:56: Found IsInBounds
pkg/statistics/histogram.go:320:45: Found IsInBounds
```
after 
```
pkg/statistics/histogram.go:302:28: Found IsInBounds
pkg/statistics/histogram.go:305:46: Found IsSliceInBounds
pkg/statistics/histogram.go:305:46: Found IsInBounds …
```
=> statistics: BCE for BinarySearchRemoveVal

br/pkg/lightning/backend/external/bench_test.go, br/pkg/lightning/backend/external/iter.go, br/pkg/lightning/backend/external/iter_test.go, br/pkg/lightning/backend/external/merge_v2.go, br/pkg/lightning/backend/external/sort_test.go, br/pkg/lightning/backend/external/split.go, br/pkg/lightning/backend/external/split_test.go, br/pkg/lightning/backend/external/testutil.go, br/pkg/lightning/backend/external/util.go, br/pkg/lightning/backend/external/writer.go, br/pkg/lightning/backend/external/writer_test.go, pkg/ddl/backfilling_dist_scheduler.go, pkg/disttask/importinto/planner.go
Issue Number: close https://github.com/pingcap/tidb/issues/49717
- For `MultipleFilesStat`, it's maintained every 500 files, and `MultipleFilesStat.MaxOverlappingNum` is the number of the key range maximum overlaping of the 500 files. In this PR, `MultipleFilesStat.Filenames` is also sorted by start key of each file, so that we only need to keep number of `MultipleFilesStat.MaxOverlappingNum` files open from left to right, and get the minimum key among the opened files.
- We introduced a `limitSizeMergeIter`, which can have reader openers, their weights, and maximum weight limit as arguments. `limitSizeMergeIter` will automatically open readers in given order and keep readers' weight sum under the limit.
- For `RangeSplitter`, now it takes `[]MultipleFilesStat` as …
=> global sort: add 2-level iterator for merge property and range splitter

br/pkg/pdutil/pd.go, pkg/disttask/framework/proto/task.go, pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/taskexecutor/manager_test.go, pkg/disttask/framework/taskexecutor/slot.go, pkg/disttask/framework/taskexecutor/slot_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/49008
Problem Summary: we need free slots(resource) when higher task comes.
- cancel the lower priority task when higher task comes, higher task is waiting slots
- alloc slot to waiting task after lower task cancelled
- can't alloc lower task when a task is waiting
- higher task will occupy slots that the waiting task reserved, and waiting task reset
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: Refactor taskExecutor slotManager to handle task occupation

pkg/executor/batch_point_get.go, pkg/executor/point_get.go, pkg/executor/point_get_test.go, pkg/planner/core/initialize.go, pkg/planner/core/point_get_plan.go, tests/integrationtest/r/executor/partition/global_index.result
Issue Number: close #47513
Tests 
>   
Side effects
Documentation
```release-note
None
```
=> executor: fix pointGet and batchPointGet for global index

pkg/ddl/util/callback/callback.go
Issue Number: close #49827
OnJobUpdated may be called unexpectedly for the last DDL, we can ignore it by checking if the state is synced.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: fix unstable test

pkg/disttask/framework/scheduler/scheduler.go, pkg/disttask/framework/taskexecutor/manager.go, pkg/domain/domain.go, pkg/session/session.go
Issue Number: close #49753
```
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=loadPrivilegeInLoop]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=topNSlowQueryLoop]
[INFO] [mock.go:105] ["owner manager is canceled"] [category=ddl] [ID=4d0f1deb-2066-4e6f-b6bd-b7cd26a25837] [ownerKey=/tidb/bindinfo/owner]
[INFO] [domain.go:1346] ["closestReplicaReadCheckLoop exited."]
[INFO] [domain.go:1866] ["globalBindHandleWorkerLoop exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=closestReplicaReadCheckLoop]
[INFO] [domain.go:725] ["globalConfigSyncerKeeper exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] …
```
=> disttask: do not retry meta initialization if context done

pkg/statistics/handle/storage/stats_read_writer.go, pkg/statistics/histogram.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: remove useless code

pkg/disttask/framework/mock/task_executor_mock.go, pkg/disttask/framework/scheduler/interface.go, pkg/disttask/framework/storage/table_test.go, pkg/disttask/framework/storage/task_table.go, pkg/disttask/framework/storage/util.go, pkg/disttask/framework/taskexecutor/interface.go, pkg/disttask/framework/taskexecutor/task_executor.go, pkg/disttask/framework/taskexecutor/task_executor_test.go
May have chance that when one task executor want to mark one subtask as running but this subtask is not owned by it.
Use the affected rows to check if the executor owns the subtask, if not owned, task executor should not run it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: check affacted row before start subtask

pkg/types/datum.go, pkg/types/time.go
Tests 
> 
Side effects
Documentation
```release-note
types: fix types's pkg warning and note generation (get rid of stack info)
```
=> types: fix types's pkg warning and note generation (get rid of stack info)

pkg/table/tables/test/partition/BUILD.bazel, pkg/table/tables/test/partition/partition_test.go
Issue Number: close #49777
Same problem with #46815,  the pr #46816 solve it by sleeping 50ms to wait domain load the new schemaVersion.
In most case it works, but it is only an `improvement`, it did not make it stable, the tests can also fails by some times.
This pr solve it by check the new tableInfo, so it should be possible to handle it fundamentally.
This pr check the non-partition table `ExchangePartitionInfo` part, it will be not-null if it is in write-only state.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: fix not-stable test about ExchangePartition when wait for ddl enter next state

pkg/planner/core/rule_partition_processor.go, tests/integrationtest/r/executor/partition/issues.result, tests/integrationtest/t/executor/partition/issues.test
Issue Number: close #49842
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix `between ... and ...` get wrong result for partition table

statistics/handle/update.go, statistics/handle/update_test.go
Issue Number: close #38189 close #36004
cherry pick https://github.com/pingcap/tidb/pull/38301
If the stats meta is not inserted after creating the table, we insert it in `DumpStatsDeltaToKV`(use `INSERT INTO ... ON DUPLICATE KEY UPDATE ...`).
Tests 
Side effects
Documentation
```release-note
None
```
=> ddl, statistics: fix stats meta missing when creating many tables at once 

pkg/parser/ast/dml.go, pkg/parser/parser.y, pkg/parser/parser_test.go
Issue Number: close #49874
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser: fix limit lost in SetOprStmt

br/pkg/restore/client.go, br/pkg/restore/client_test.go, br/pkg/task/restore.go
Issue Number: close #49466
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that unset new collation when --check-requirements=false
```
=> restore: correct new collation when "--check-requirements=false"

pkg/executor/show_stats_test.go, pkg/util/codec/codec.go
Issue Number: close https://github.com/pingcap/tidb/issues/49823
Tests 
> 
Side effects
Documentation
```release-note
planner: fix show stats_bucket couldn't decode index boundary out
```
=> planner: fix show stats_bucket couldn't decode index boundary out

pkg/planner/core/logical_plans_test.go, pkg/planner/core/point_get_plan.go, pkg/util/mock/context.go
Issue Number: ref #41622
close #49751
The result of  `sctx.GetInfoSchema().(infoschema.InfoSchema)` **is not stable** if the caller side is not in a transaction && snapshot_ts is not set, it just get the latest InfoSchema:
https://github.com/pingcap/tidb/blob/c20874ed33df4621f2a8e12baf43a705755e3291/pkg/session/session.go#L4052-L4074
Tests 
> 
Side effects
Documentation
```release-note
planner: use TxnCtx.InfoSchema to prevent schema inconsistency
```
=> planner: use TxnCtx.InfoSchema to prevent schema inconsistency

pkg/bindinfo/bind_cache.go, pkg/bindinfo/bind_cache_test.go, pkg/bindinfo/global_handle.go, pkg/bindinfo/session_handle.go, pkg/bindinfo/tests/bind_test.go
Problem Summary: planner: simplify the structure of value in binding cache
ONLY REFACTOR, NO LOGICAL CHANGE.
Change the structure of values in the binding cache from `[]*BindRecord` to `*BindRecord` since we assume no hash collision there.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: simplify the structure of value in binding cache

pkg/executor/test/analyzetest/analyze_test.go, pkg/planner/core/indexmerge_path.go, pkg/planner/core/logical_plans.go, pkg/planner/core/planbuilder.go, tests/integrationtest/r/planner/core/indexmerge_path.result
Issue Number: ref https://github.com/pingcap/tidb/issues/46539
- Re-enable analyze for mv index. (`pkg/planner/core/planbuilder.go`)
- Change parameters for some functions related to mv index access path. It's a preparation for the following PR that adds support for estimation for mv index access path. (`pkg/planner/core/indexmerge_path.go`, `pkg/planner/core/logical_plans.go`)
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: re-enable analyze for mv index and code prepare for estimation | tidb-test=pr/2272

pkg/planner/core/indexmerge_path.go
Issue Number: close https://github.com/pingcap/tidb/issues/49977
Tests 
> 
Side effects
Documentation
```release-note
eliminate redundant returned error signature when all code branches return nil
```
=> planner: eliminate redundant returned error signature when all code branchs return nil

br/pkg/lightning/backend/backend.go, br/pkg/lightning/backend/local/engine.go, br/pkg/lightning/backend/local/engine_mgr.go, br/pkg/lightning/backend/local/local.go, br/pkg/lightning/backend/local/local_test.go, br/pkg/lightning/config/config.go, br/pkg/lightning/importer/table_import.go, pkg/ddl/ingest/config.go, pkg/executor/importer/table_import.go
Issue Number: close #45037
We have seen that lightning is bounded by EBS IOPS which is 16k and is taking more than 3 hours to transfer 7 TB of data. 
I have made the block size configurable through lightning config. We are setting it 128k internally. 
Tests 
> 
Its running in production with 128k size. However, i haven't tested the master code. I am relying on pingcap CI to test it. 
Side effects
I haven't seen much increase in memory and CPU after increasing the block size. 
Documentation
```release-note
None
```
=> Lightning : make pebbleDB block size configurable

br/pkg/lightning/config/config.go, br/pkg/lightning/config/config_test.go, br/pkg/lightning/importer/import.go, br/tests/lightning_pd_leader_switch/run.sh, pkg/executor/importer/table_import.go
Issue Number: close #49515
Lightning doesn't support multiple PD addresses in config file. It made to lightning to fail if that PD address is down before import is started.
It is a simple fix as PD client already supports multiple PD addresses. We only need to parse it correctly and give to list of PD addresses while creating the PD client. 
Tests 
> 
It is tested in 6.5 and already deployed to production cluster
Side effects
Documentation
```release-note
None
```
=> Lightning: support multiple PD addresses

pkg/planner/core/rule_aggregation_push_down.go, tests/integrationtest/r/expression/issues.result, tests/integrationtest/t/expression/issues.test
Issue Number: close https://github.com/pingcap/tidb/issues/49986
Tests 
> 
Side effects
Documentation
```release-note
planner: fix agg push down rule mistake order by item inside agg function
```
=> planner: fix agg push down rule mistake order by item inside agg function

pkg/executor/internal/mpp/local_mpp_coordinator.go
Issue Number: close #50011
Problem Summary: introduced by https://github.com/pingcap/tidb/pull/49401/files#diff-bb7331df1642b992efeb5699402d591f45fbc8b9baec6c024680156ae3a5656aR522
`EOF` error of grpc stream `Recv()` indicates a stream completes successfully, ref: https://github.com/grpc/grpc-go/blob/master/stream.go#L134
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix unexpected mpp grpc EOF error log

pkg/errctx/context.go, pkg/errctx/context_test.go, pkg/executor/BUILD.bazel, pkg/executor/executor.go, pkg/executor/insert.go, pkg/sessionctx/stmtctx/BUILD.bazel, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/stmtctx/stmtctx_test.go
Issue Number: close #49991
Use `errctx.Context` to handle `ErrAutoincReadFailed` to make error handling decouple with `stmtctx`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: move `StmtCtx.ErrAutoincReadFailedAsWarning` to errctx

pkg/disttask/framework/handle/BUILD.bazel, pkg/disttask/framework/handle/handle_test.go, pkg/disttask/framework/planner/BUILD.bazel, pkg/disttask/framework/planner/planner_test.go, pkg/disttask/framework/scheduler/scheduler_manager_test.go, pkg/disttask/framework/scheduler/scheduler_test.go, pkg/disttask/framework/taskexecutor/BUILD.bazel, pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/taskexecutor/manager_test.go, pkg/disttask/framework/testutil/context.go, pkg/domain/domain.go
Issue Number: close #49990
we init node meta inside domain, as create task requires at least 1 managed node inited after https://github.com/pingcap/tidb/pull/49875 merged
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: init node meta inside domain

pkg/statistics/handle/storage/BUILD.bazel, pkg/statistics/handle/storage/dump_test.go, pkg/statistics/handle/storage/stats_read_writer.go, pkg/statistics/handle/types/interfaces.go, pkg/statistics/handle/util/util.go
Issue Number: ref #49627 
oom when dump/load the statistic if there are many partitions of a table
dump/load statistic data in the partition dimension
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistic: support fine-grained dump/load statistics

br/pkg/errors/errors.go, br/pkg/restore/client.go, br/pkg/restore/import.go, br/pkg/restore/import_retry.go, br/pkg/restore/merge.go, br/pkg/restore/pipeline_items.go, br/pkg/restore/split.go, br/pkg/restore/split/client.go, br/pkg/restore/split_test.go, br/pkg/restore/util.go, br/pkg/rtree/rtree.go, br/pkg/task/restore.go, br/pkg/task/stream.go, br/pkg/utils/backoff.go, errors.toml
Issue Number: ref https://github.com/pingcap/tidb/issues/33937
split too many regions on the same node. will become bottleneck of a large scale cluster restoration.
1. introduce 2-phase split during restore. when enable fine-grained restore. it will pick keys by store count, and doing a two-phase split scatter. which will save time from scatter-heavy workloads.
2. refactor code and unified `utils.retry` for all related backoffer.
Tests 
>   
without this change:
with this change:
Side effects
Documentation
```release-note
restore: improve …
```
=> restore: refactor split code for two phase split.

pkg/parser/parser.y, pkg/parser/parser_test.go, tests/integrationtest/r/parser/integration.result, tests/integrationtest/t/parser/integration.test
Issue Number: close #34325 
Hints are not supported in `REPLACE INTO ...` statement.
I simply modify the parser to support this hints. I also tested that some simple hints (e.g. `SET_VAR`) actually work. 
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that hints are not supported in the `REPLACE INTO` statement.
```
=> parser: support hints in 'REPLACE INTO' statement

pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/taskexecutor/manager_test.go
Issue Number: ref #48795
When taskType not register, logAndPersistErr may panic.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: fix potential panic in task executor

pkg/planner/core/rule_partition_processor.go, tests/integrationtest/r/executor/partition/issues.result, tests/integrationtest/t/executor/partition/issues.test
Issue Number: close #50044
Problem Summary: Caused by #49853, I made a mistake about `mathutil.Abs` and select a wrong partiton for hash partition table.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix select wrong partition for hash partition table

Makefile.common, tests/realtikvtest/brietest/BUILD.bazel
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> makefile: simplify code

pkg/executor/adapter.go, pkg/session/test/variable/variable_test.go, pkg/sessionctx/sessionstates/session_states.go
Issue Number: ref https://github.com/pingcap/tidb/issues/49318
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: remove duplicate prefix for last query info

pkg/bindinfo/bind_cache.go, pkg/bindinfo/bind_record.go, pkg/bindinfo/capture.go, pkg/bindinfo/global_handle.go, pkg/bindinfo/global_handle_test.go, pkg/bindinfo/session_handle.go, pkg/bindinfo/session_handle_test.go, pkg/bindinfo/tests/bind_test.go, pkg/executor/bind.go, pkg/infoschema/test/clustertablestest/cluster_tables_test.go, pkg/infoschema/test/clustertablestest/tables_test.go, tests/integrationtest/r/bindinfo/bind.result
Problem Summary: planner: simplify global and session binding handle
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: simplify global and session binding handle

pkg/bindinfo/universal_binding_test.go, pkg/infoschema/test/clustertablestest/cluster_tables_test.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/tidb_vars.go
…_fuzzing_binding
Issue Number: ref https://github.com/pingcap/tidb/issues/48875
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> bindinfo: rename tidb_opt_enable_universal_binding as tidb_opt_enable_fuzzy_binding

br/pkg/lightning/backend/kv/BUILD.bazel, br/pkg/lightning/backend/kv/session.go, pkg/ddl/BUILD.bazel, pkg/ddl/backfilling_scheduler.go, pkg/errctx/context.go, pkg/executor/BUILD.bazel, pkg/executor/executor.go, pkg/executor/executor_pkg_test.go, pkg/expression/BUILD.bazel, pkg/expression/errors.go, pkg/expression/evaluator_test.go, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/stmtctx/stmtctx_test.go
Issue Number: close #50041
use errctx to handle divide zero error
- Delete `StatementContext.DividedByZeroAsWarning` and use the error group `ErrDivisionByZero` to mark the error handle level.
- Delete `StatementContext.InReorg` because it is useless now.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: use errctx to handle divide zero error

br/pkg/lightning/config/config.go, br/pkg/lightning/importer/import.go, br/pkg/lightning/importer/table_import.go
Issue Number: close #50105
Tests 
import large mount of tables(each table is about several tens of MB), after this pr, we can import from 674 tables/h/instance -> 809. Since TiDB still handle `alter table` in serial internally, the speedup is not that obvious. Note we are importing using 10 lightning, some instance have more improvement
> 
Side effects
Documentation
```release-note
None
```
=> lightning: remove alter table lock

pkg/statistics/handle/autoanalyze/autoanalyze.go, pkg/statistics/handle/handle.go, pkg/statistics/handle/types/interfaces.go
Issue Number: close #50100
when we meet the many pseudo tables to check whether to do auto-analyze. we will create many pseudo statistics.  it will lead to frequent gc.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: avoid allocating the memory when to auto analyze with pseudo table

pkg/parser/ast/misc.go, pkg/parser/keywords.go, pkg/parser/keywords_test.go, pkg/parser/misc.go, pkg/parser/parser.y, pkg/parser/parser_test.go, pkg/planner/core/planbuilder.go
Issue Number: close https://github.com/pingcap/tidb/issues/50066
ref https://github.com/pingcap/tidb/issues/48875
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser: remove universal keyword

br/pkg/lightning/backend/kv/base.go, br/pkg/lightning/backend/kv/session.go, pkg/ddl/backfilling_scheduler.go, pkg/errctx/context.go, pkg/executor/executor.go, pkg/executor/executor_pkg_test.go, pkg/executor/insert_common.go, pkg/executor/load_data.go, pkg/executor/test/writetest/BUILD.bazel, pkg/executor/test/writetest/write_test.go, pkg/executor/write.go, pkg/expression/builtin_miscellaneous.go, pkg/expression/builtin_miscellaneous_vec.go, pkg/expression/builtin_miscellaneous_vec_test.go, pkg/expression/errors.go, pkg/expression/evaluator_test.go, pkg/sessionctx/stmtctx/stmtctx.go, pkg/table/BUILD.bazel, pkg/table/column.go, pkg/table/column_test.go
Issue Number: close #50119
This is one step to move error handling settings from `stmtctx` to `errctx` and this PR:
- remove `stmtctx.BadNullAsWarning`
- use `errctx` to handle bad null errors (with defined as group `errctx.ErrGroupBadNull`).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: remove `stmtctx.BadNullAsWarning` and use `errctx` to handle bad null error

pkg/store/main_test.go
Issue Number: close #50141
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> store: fix goleak for syscall

br/tests/_utils/generate_certs, br/tests/config/rootca.conf
Issue Number: close https://github.com/pingcap/tidb/issues/50150
- v3 CA requires basic constraints ext `CA:TRUE` exists for self-signed root ca, else it reports `x509: invalid signature: parent certificate cannot sign this kind of certificate`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br/lightning: add basicConstraints to test ca

br/pkg/lightning/backend/local/local.go
Issue Number: close #49517
Lightning job is failing intermittently after enable BR on prod clusters because of batch split failure. During the backup process, BR temporarily disables the schedulers for a period of 1-2 minutes. However, the Lightning job, which does not have a backoff mechanism, continues to retry the process for up to 5 times without pausing or spacing out the retries.
i am adding a exponential back off before each retry and now it will retry upto 930 seconds before if fails the job
Tests 
> 
Side effects
NO
Documentation
NO …
=> Lightning: increase backoff if split fails

pkg/executor/internal/mpp/local_mpp_coordinator.go, pkg/store/copr/batch_coprocessor.go, pkg/store/copr/coprocessor.go
Issue Number: ref #49643
Previously the kill signal was checked against `1`, however TiDB uses non-zero values to indicate a kill signal.
Tests 
- Simple enough change.
Side effects
Documentation
```release-note
None
```
=> fix: check kill signal against 0

pkg/ddl/constraint_test.go, pkg/table/tables/tables.go, pkg/table/tables/tables_test.go, pkg/tablecodec/tablecodec.go
Issue Number: close https://github.com/pingcap/tidb/issues/50077
If a large number of tables (such as the 540k table,  2850k partitions in the scenario shown in issue) are used, the OOM situation may occur.
Reduce memory allocation
* Do not create columns(PublicColumns, VisibleColumns, WritableColumns, FullHiddenColsAndVisibleColumns) for tables that are not used by users.
* Do preallocate for `EncodeInt` in `EncodeTableIndexPrefix`.
Tests 
Prior to this PR, OOM appeared every 20-30 minutes. After this PR memory is relatively stable without OOM (test 4h+).
See the memory usage chart, memory reduction of about 2G.
> 
Side effects
Documentation …
=> *: memory is not allocated first if the user does not use some information from the table.

pkg/ddl/ddl.go, pkg/ddl/job_table.go, pkg/owner/manager.go, pkg/owner/mock.go
Issue Number: close #50073
The sequence is as follows:
```
1. tidb-1 owner starts adding index [MarkProcessingJob()]
2. owner switches to tidb-2
3. tidb-2 owner finishes adding index [MarkJobFinished()]
4. owner switches to tidb-1
5. tidb-1 owner reports error: already in used by another DDL job
```
When a DDL owner is retired, we mark the job finished on this instance.
Tests 
The test code is available at https://github.com/tangenta/dbtool/blob/24a7dc9c5a5808b654f11b229fd70e3103939b31/cases/issue_50073.go
```
Determine the owner of tidb...
Get tidb owner: root@tcp(127.0.0.1:4001)/test
Prepare data...
Start add index on owner...
Evict DDL owner...
Evict back DDL owner...
Add another add index should not block...
Query last 10 seconds log...
2024/01/05 …
```
=> ddl, owner: clean processing ddl jobs when owner retired

.gitignore, pkg/session/bootstrap_test.go, pkg/session/mock_bootstrap.go
Issue Number: close #49870
Adding multiple indexes in one SQL statement has been optimized in #47135. The first job argument is also changed from `bool` to `[]bool`, and this change is not downgrade-compatible.
In mock upgrade test, it is possible that a new version TiDB submits a DDL job, and the old version TiDB executes it.
- Remove multi-schema change in mock upgrade test.
- We should ensure that upgrading DDL does not use multi-schema changes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: remove multi-schema change from mock upgrade test

pkg/ddl/index_merge_tmp.go
Issue Number: close #50203
Found it when trying to close #49940 .
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: remove useless field in `temporaryIndexRecord`

pkg/errctx/context.go, pkg/executor/batch_checker.go, pkg/executor/executor.go, pkg/executor/executor_pkg_test.go, pkg/executor/write.go, pkg/sessionctx/stmtctx/stmtctx.go
Issue Number: close #50172
Decouple some error handling with stmtctx
- remove `IgnoreNoPartition` in `StatementContext`
- add err group `ErrGroupNoMatchedPartition` to `errctx` to handle the corresponding errors.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: remove `stmtctx.IgnoreNoPartition` and use `errctx` to handle partition mismatch error

pkg/parser/misc.go, pkg/parser/parser.y, pkg/parser/parser_test.go, pkg/parser/yy_parser.go
Issue Number: close #45873
as-is
```
tidb> create table ``.t(id int);
```
to-be (same as mysql)
```
tidb> create table ``.t(id int);
ERROR 1102 (42000): Incorrect database name ''
```
When schema is empty string in {schema}.{table}, return error ("Incorrect database name ''").
```
tidb> create table test.t(id int);
tidb> create table t(id int);
tidb> create table ``.t(id int);
ERROR 1102 (42000): Incorrect database name ''
```
The validation for case 3 will be done in parser layer.
The reason is that it's impossible to differenciate case 2 and case 3 in preprocessor layer.
Currently, in both case 2 and case 3, schema name is `""` before preprocessor layer and is …
=> parser: raise error for empty db name | tidb-test=pr/2275

pkg/store/mockstore/mockstore.go
Issue Number: ref #42434
I find https://github.com/pingcap/tidb/pull/42521 does not make the unit test faster ...
Here is an internal document with some investigation progress, but the root cause is still unknown. https://pingcap.feishu.cn/wiki/TpqNwM3eiiWJY1kvJjocWztcn7e?from=from_copylink
Before we know why that doesn't work, it's better to revert first.
Tests 
Revert
> 
Side effects
Documentation
```release-note
None
```
=> store/mockstore: revert using store image to accelerate unit test

pkg/expression/bench_test.go, pkg/expression/builtin_cast_vec_test.go, pkg/expression/errors.go
Issue Number: close #50178
In implement of function `handleInvalidTimeError` and `handleAllowedPacketOverflowed` are using `InInsertStmt /InUpdateStmt /InDeleteStmt` to determine how to handle corresponding errors, but seems necessary now:
- When `StrictSQLMode && (sc.InInsertStmt || sc.InUpdateStmt || sc.InDeleteStmt)`: whether to return an error is determined by whether `insert/update/delete ignore` is used, `HandleTruncate` has the right logic to process it. 
- When `!StrictSQLMode && (sc.InInsertStmt || sc.InUpdateStmt || sc.InDeleteStmt)`: we should see truncate error as warning and  `HandleTruncate` will also do it.
- When `!sc.InInsertStmt && !sc.InUpdateStmt && !sc.InDeleteStmt`: the previous code will append warning and `HandleTruncate` will also do it because …
=> expression: refine code in `handleInvalidTimeError` and `handleAllowedPacketOverflowed`

DEPS.bzl, br/pkg/lightning/backend/local/BUILD.bazel, br/pkg/lightning/backend/local/local.go, br/pkg/pdutil/BUILD.bazel, br/pkg/pdutil/pd.go, br/pkg/pdutil/pd_serial_test.go, go.mod, go.sum
Issue Number: ref #35319, close https://github.com/tikv/pd/issues/7673.
Lightning updated the PD HTTP client but did not keep the same retry logic as before.
- Update the PD HTTP client to adopt the latest retry logic.
- Add a backoffer to the Lightning PD HTTP client to keep the same retry interval and frequency as before.
Tests 
```release-note
None
```
=> deps, lightning: update the PD HTTP client to refine the retry logic

WORKSPACE
Issue Number: close #50216
Upgrade `rules_go` can solve some DATA RACE in test.
Tests 
> 
```release-note
None
```
=> *: upgrade to rules_go 0.44.2

pkg/planner/core/casetest/hint/BUILD.bazel, pkg/planner/core/casetest/hint/hint_test.go, pkg/planner/core/casetest/hint/testdata/integration_suite_in.json, pkg/planner/core/casetest/hint/testdata/integration_suite_out.json, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/planbuilder.go, pkg/util/hint/hint.go, pkg/util/hint/hint_processor.go, tests/integrationtest/r/planner/core/casetest/rule/rule_join_reorder.result
Issue Number: close #50067
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix leading hint cannot take effect in UNION ALL statements

pkg/store/mockstore/unistore/tikv/mock_region.go
Issue Number: close #50177
1. We check the `regionCtx` and it is correct. Then unlock the `MockRegionManager`.
2. Another goroutine split the region, update region epoch.
3. Call `newRegions, err := rm.splitKeys(splitKeys)` got one more `newRegions`.
Tests 
As diff show in https://github.com/pingcap/tidb/issues/50177#issuecomment-1882561057, no panic any more.
```diff
diff --git a/pkg/store/mockstore/unistore/tikv/mock_region.go b/pkg/store/mockstore/unistore/tikv/mock_region.go
index be4173dd4e..7dfe674ae5 100644
--- a/pkg/store/mockstore/unistore/tikv/mock_region.go
+++ b/pkg/store/mockstore/unistore/tikv/mock_region.go
@@ -445,6 +445,13 @@ func (rm *MockRegionManager) SplitRegion(req *kvrpcpb.SplitRegionRequest) *kvrpc
}}
}
+       if len(splitKeys) < 3 {
+ …
```
=> store: let `MockRegionManager` check region epoch and split region in same lock

pkg/planner/core/casetest/hint/BUILD.bazel, pkg/planner/core/casetest/hint/hint_test.go, pkg/planner/core/casetest/hint/testdata/integration_suite_in.json, pkg/planner/core/casetest/hint/testdata/integration_suite_out.json, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/planbuilder.go, pkg/util/hint/hint.go, tests/integrationtest/r/planner/core/casetest/rule/rule_join_reorder.result
Reverts pingcap/tidb#50145
Issue Number: close #50067
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> Revert "planner: fix leading hint cannot take effect in UNION ALL statements"

pkg/executor/test/executor/BUILD.bazel, pkg/executor/test/executor/executor_test.go, pkg/planner/core/task.go
Issue Number: close https://github.com/pingcap/tidb/issues/38756
Do not remove the first row func if the group by expr is a constant.
For instance, if you try `SELECT DISTINCT SQRT(1) FROM t`
```sql
mysql> explain SELECT DISTINCT SQRT(1) FROM t;
+---------------------------+----------+-----------+---------------+-------------------------------------------------------+
| id                        | estRows  | task      | access object | operator info                                         |
+---------------------------+----------+-----------+---------------+-------------------------------------------------------+
| HashAgg_8                 | 1.00     | root      |               | group by:Column#5, funcs:firstrow(Column#5)->Column#3 |
| └─TableReader_9           | 1.00 …
```
=> planner: do not remove the first row func if it is a constant | tidb-test=pr/2277

pkg/planner/core/stats.go
Issue Number: close #50184 
Just change the code comments
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: only change the incorrect comments for the heuristic rule of unique index

pkg/errctx/context.go, pkg/executor/executor.go, pkg/executor/executor_pkg_test.go, pkg/executor/insert.go, pkg/executor/insert_common.go, pkg/executor/load_data.go, pkg/executor/test/writetest/write_test.go, pkg/executor/update.go, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/variable/BUILD.bazel, pkg/sessionctx/variable/session.go, pkg/table/column.go
Issue Number: close #50238
1. Remove `stmtctx. DupKeyAsWarning`
2. Use `errctx. ErrGroupDupKey` to handle dup key errors
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: move dup key error handling to `errctx`

Makefile, tools/check/ut.go
Issue Number: ref #45961
1. make it works without `unstable.txt` file
2. Always report coverprofile even ut failed.
Tests 
call `gotest_in_verify_ci` and `gotest_unstable_in_verify_ci` in local computer, it works and get coverage file.
> 
Side effects
Documentation
```release-note
None
```
=> makefile, tools: update `tools/check/ut` to make it work without `unstable.txt`

pkg/executor/test/analyzetest/analyze_test.go, pkg/planner/cardinality/selectivity.go, pkg/planner/core/indexmerge_path.go, pkg/planner/core/planbuilder.go, tests/integrationtest/r/planner/core/indexmerge_path.result, tests/integrationtest/t/planner/core/casetest/index/index.test, tests/integrationtest/t/planner/core/indexmerge_path.test
Issue Number: close #50125
We cannot blindly scan on the multi-valued index, because scanning on it assumes that the array is not empty. I added a lot comments on related codes to describe why it's safe now.
Tests 
> 
```release-note
Fix the issue that multi-valued index can give incorrect result when the array is empty.
```
=> planner: avoid scanning multi-valued index when there is no condition related | tidb-test=pr/2276

pkg/ddl/ddl_worker.go
Issue Number: close #50055, close #47105
Timeline:
1. `TestFrameworkWithQuery` creates multiple domains in order to test the distributed environment.
2. These domains create & initialize their own DDL structures one by one.
3. The first domain(tidb-0) checks that it is DDL owner, and trying to load DDL jobs and run them. [go runtime is lagging for a while]
4. The second domain(tidb-1) starts, `InitOwner()` assign the DDL owner to tidb-1.
5. tidb-1 starts to load DDL jobs. At the same time, the goroutine in step 3 continues to run.
As a result, there are two DDL owners running the same job concurrently.
Before updating the error to job table, TiDB should check whether it is owner itself.
Tests 
> 
Side effects …
=> ddl: check owner status before commit DDL changes

pkg/ddl/constraint_test.go, pkg/ddl/index_change_test.go
Issue Number: close #50079, close #49825
To make the tests easy to reproduce:
```
--- a/pkg/ddl/job_table.go
+++ b/pkg/ddl/job_table.go
@@ -434,6 +434,9 @@ func (d *ddl) delivery2worker(wk *worker, pool *workerPool, job *model.Job) {
d.mu.hook.OnSchemaStateChanged(schemaVer)
d.mu.RUnlock()
}
+                       if job.SchemaState == model.StatePublic && job.State == model.JobStateSynced && job.TableName == "t" && job.Type == model.ActionCreateTable {
+                               time.Sleep(3000 * time.Millisecond)
+                       }
d.mu.RLock()
d.mu.hook.OnJobUpdated(job)
``` 
This pr:
1. Solve the unstable test.
2. Clean some useless code and make some enhencement.
Tests 
> 
Side effects
Documentation …
=> test: fix unstable `TestIndexChange ` and `TestAlterAddConstraintStateChange3`

pkg/session/bootstraptest/BUILD.bazel, pkg/session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50292
The two "add index" jobIDs are not necessarily serial in `OnGetJobBeforeExported` after https://github.com/pingcap/tidb/pull/48728.
Remove the duplicated check.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> session: make TestUpgradeVersionForResumeJob faster

pkg/ddl/BUILD.bazel, pkg/ddl/index_merge_tmp.go, pkg/ddl/ingest/BUILD.bazel, pkg/ddl/ingest/integration_test.go, pkg/ddl/ingest/mock.go
Issue Number: close #49940
```
expected: "[kv:1062]Duplicate entry '1' for key 't.idx'"
actual  : "[kv:1062]Duplicate entry '%-.64s' for key '%-.192s'"
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: refine duplicate entry err msg when merging temp index

pkg/disttask/framework/handle/handle.go, pkg/disttask/framework/handle/handle_test.go
Issue Number: close #50318
Check task with key exits with history table.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: fix submit task with same key

pkg/expression/expression.go, pkg/store/mockstore/mockcopr/executor.go, pkg/store/mockstore/unistore/cophandler/closure_exec.go, pkg/store/mockstore/unistore/cophandler/mpp_exec.go
Issue Number: close #50278
The function `HandleOverflowOnSelection` seems useless. It was introduced in PR #14081 to solve some bugs.
However, in PR #16014, when converting a string to bool, we use `StrToFloat` instead of `StrToInt`. `StrToFloat` does not raise overflow error and all other errors should be swallowed in `StrToFloat` when the statement is `select ..`.
We can remove `HandleOverflowOnSelection` safely now.
Remove `HandleOverflowOnSelection`
Tests 
> regress the old tests
Side effects
Documentation
```release-note
None
```
=> expression: remove useless `HandleOverflowOnSelection`

pkg/ddl/ddl_worker.go
Issue Number: close #50309
Problem Summary: #50251 missed one line.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: unlock schema version mutex properly

pkg/statistics/table.go, tests/integrationtest/r/planner/core/indexmerge_path.result, tests/integrationtest/t/planner/core/indexmerge_path.test
Issue Number: close #50298
Estimation logic for mv index access path will meet panic if it's a new index without stats.
Add a nil check.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix missing nil check for mv index

pkg/planner/core/expression_rewriter.go, pkg/planner/core/planbuilder_test.go
Issue Number: close #50064
This is one step for enhancement #50059 . In this PR we:
1. introduce `exprRewriterPlanCtx` which includes all plan-related fields when building expression.
2. To make it easier for the further step, most methods in `expressionRewriter` do not read plan-related fields from `expressionRewriter.planCtx`. Instead, these methods should add a new argument `planCtx` with type `exprRewriterPlanCtx`, and read these fields from the argument. So we can know clearly which ast node need plan-related context from the code.
Tests 
> This is a streaming replace without any logic change, just regress tests
Side effects
Documentation …
=> planner: add `exprRewriterPlanCtx` and move planner related fields to it when building expression

pkg/executor/historical_stats_test.go, pkg/executor/test/executor/BUILD.bazel, pkg/executor/test/executor/executor_test.go, pkg/planner/core/point_get_plan.go, tests/integrationtest/r/explain_easy_stats.result
Issue Number: close #49920
It's better to resolve order by clause, but it will make some duplicated code.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: bypass order by clause for fast point get plan

pkg/util/security_test.go
Issue Number: close #37819
I suspect the unstable is caused by the environment, maybe there are some other service running using that port.
So I change the port to a random one to avoid conflict.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> pkg/util: use random port to make test TestVerifyCommonNameAndRotate stable

pkg/planner/core/indexmerge_path.go, tests/integrationtest/r/planner/core/casetest/index/index.result, tests/integrationtest/t/planner/core/casetest/index/index.test
Issue Number: close https://github.com/pingcap/tidb/issues/50265
where
member of(ja)
OR
member of(jb)
OR
member of(jc)
OR
json_contains(jd, [1,2,3])
since json_contains is an intersection index merge itself
for normal cases, we can generate an index merge like the below:
```
IndexMerge(UNION)
mv-index-path(ja)
mv-index-path(jb)
mv-index-path(jc)
IndexMerge(jd)
mv-index-path(jd, 1)
mv-index-path(jd, 2)
mv-index-path(jd, 3)
````
currently, embedded index merge is banned, for for IndexMerge(jd), if it only have 1 partial path, we can just simply merge it with outer UNION type index merge.
Tests 
> 
Side effects
Documentation …
=> planner: fix union index merge can merge a embedded intersection index merge with only one partial path | tidb-test=pr/2279

br/pkg/version/build/info.go, br/pkg/version/version.go, br/pkg/version/version_test.go
some realtikv tests need to run backup. which will run br without TiDBReleaseVersion tags makes check version failed.
Usually we have to update the default value up to the major version of tikv.
This PR try to fix it totally.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: use test version for realtikv test

pkg/planner/core/casetest/parallelapply/BUILD.bazel, pkg/planner/core/casetest/parallelapply/main_test.go, pkg/planner/core/casetest/parallelapply/parallel_apply_test.go, pkg/planner/core/optimizer.go
…blem
Issue Number: close #50256
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: return the complete error info when Parallel Apply meets problem

pkg/executor/internal/applycache/apply_cache.go, pkg/executor/internal/applycache/apply_cache_test.go
Issue Number: close #50347
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: avoid concurrently update for `SimpleLRUCache` in `ApplyCache`

pkg/planner/core/indexmerge_path.go, pkg/planner/core/indexmerge_path_test.go, pkg/planner/core/logical_plans.go
Issue Number: close https://github.com/pingcap/tidb/issues/50380
fix the AND mv index filter mutations generating logic.
`SELECT * FROM t WHERE   15975127 member of (domains)   AND 15975128 member of (domains) AND a = 1 AND b = 2`
for mv index mvi(a, domains, b)
the accessFilters should be `[a = 1, ?, b = 1]`, here ? is pos occupation here stands for set `{15975127 member of (domains), 15975128 member of (domains)}`
when building index partial path, we have two mutation here
`a=1 and 15975127 member of (domains) and b=2`
`a=1 and 15975128 member of (domains) and b=2`
the generation mistake detail can ref the issue
Tests 
> 
Side effects
Documentation …
=> planner: fix intersection type mv index's filters mutations composition

br/pkg/lightning/config/config.go, dumpling/export/config.go, pkg/server/server.go, pkg/sessionctx/variable/statusvar.go, pkg/util/misc.go, pkg/util/security.go
Issue Number: ref #36036 
TLS1.0/1.1 has security issues, remove the support of them.
Tests 
Generate the certificates according to this page https://docs.pingcap.com/tidb/stable/generate-self-signed-certificates
Modify pkg/config/config.toml.example
```
ssl-ca = "/home/genius/root.crt"
ssl-cert = "/home/genius/tikv.crt"
ssl-key = "/home/genius/tikv.key"
```
Run tidb-server:
```
./bin/tidb-server -config config.toml.example
```
Verify connection with mysql client:
```
$ mysql --tls-version=TLSv1.0 -v -v -v --ssl-ca='/home/genius/root.crt'  --ssl-cert="/home/genius/tikv.crt" --ssl-key="/home/genius/tikv.key" -uroot -h127.0.0.1  
ERROR 2026 (HY000): SSL connection error: TLS version is invalid
$ mysql --tls-version=TLSv1.1 -v -v -v --ssl-ca='/home/genius/root.crt' …
```
=> *: remove TLS1.0, TLS1.1 support

pkg/domain/domain.go
Issue Number: ref #50332 
Assign high priority for it so that it can be executed more quickly when tikv is busy.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics, domain: assign high priority for stats sync load

pkg/executor/infoschema_reader_test.go, pkg/infoschema/tables.go
Issue Number: close https://github.com/pingcap/tidb/issues/48835
It should be varchar instead of int64.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that users can not select data from the `information_schema.analyze_status` table
```
=> infoschema: set the correct type for REMAINING_SECONDS

br/cmd/br/restore.go, br/tests/br_stats/run.sh
Issue Number: close #50240
1. Fix the prompt message on restore sys tables failure.
2. Fix an integration case
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: fix the --with-sys-table prompt

pkg/disttask/framework/scheduler/scheduler_test.go
Issue Number: close #50409
Don't start scheduler if it start time(counter) > len(concurrencies)
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: fix flaky dispatch loop

pkg/parser/ast/dml.go, pkg/parser/parser.y, pkg/parser/parser_test.go, pkg/planner/core/planbuilder.go
Issue Number: close #50403
Added support for the `SHOW {REPLICA | SLAVE} STATUS` statement for the parser.
Tests 
> 
Side effects
Documentation
```release-note
Added support for the `SHOW {REPLICA | SLAVE} STATUS` statement for the parser.
```
=> parser: add support for the `SHOW {REPLICA | SLAVE} STATUS` stmt.

pkg/planner/cardinality/selectivity.go, tests/integrationtest/r/planner/core/indexmerge_path.result, tests/integrationtest/t/planner/core/indexmerge_path.test
Issue Number: close #50420
Please see the comments in the issue.
Make the scaling realtime row count logic only applies to the mv index partial path.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix panic when table path and mv index path are both used in access path

pkg/executor/internal/exec/executor.go, pkg/util/util.go
Issue Number: ref https://github.com/pingcap/tidb/issues/49882
Add the stack information to help us understand what is going on.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> exectuor: add stack trace for runtime panic

pkg/statistics/handle/usage/collector/BUILD.bazel, pkg/statistics/handle/usage/collector/collector.go, pkg/statistics/handle/usage/collector/collector_test.go
Issue Number: close #50416
A new collector based on channel is implemented. It will be used to implement the index usage collector and replace other usage collectors in the future.
If you wonder how it will be used, see https://github.com/pingcap/tidb/pull/50050 `pkg/statistics/handle/usage/indexusage/collector.go`.
Compared with the existing list implementation, the pros and cons:
Pros:
1. Every session manage the data structure locally. Most of the time they'll not need to be blocked.
2. Sending through channel is easier to maintain and keep safety / correctness.
Cons:
1. The global collector will lose the view of real time stats.
Tests 
>  …
=> statistics/handle/usage: add a collector utility based on channel to collect stats from sessions

pkg/disttask/framework/scheduler/scheduler.go
Issue Number: close #50498
Tests 
mock the same access pattern as in the issue stack, make sure this pr have no race
> 
Side effects
Documentation
```release-note
None
```
=> disttask: fix data race when accessing task concurrently in scheduler

br/pkg/restore/split.go, br/pkg/restore/split_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50471 https://github.com/pingcap/tidb/issues/50477
1. new split approach will choose empty key in some case. this PR tried to fix it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> restore: fix choose the emptry key as split key

pkg/bindinfo/global_handle_test.go, pkg/parser/ast/misc.go, pkg/parser/parser_test.go
Issue Number: close #50507
Problem Summary: parser: restore set_var value to string instead of plain text
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser: restore set_var value to string instead of plain text

br/pkg/storage/gcs.go
Issue Number: close #50533
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> external: remove old compatibility check of BR

pkg/disttask/framework/framework_test.go
Issue Number: close #50524
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: fix flaky case

pkg/sessionctx/variable/sysvar.go
Issue Number: close #50528
When we test analyze in the 100 nodes cluster. we find tidb cannot make use of resource to make analyze faster. but we large the analyze_distsql_scan as 256. it can improve it. but it can be larger than the limitation.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> variable: raise the upper limit of tidb_analyze_distsql_scan_concurrency

pkg/executor/adapter.go
Issue Number: close #50411
Now. when tidb does auto-analyze, tidb_index_serial_scan_concurrency will be forcely set as 1. It is so slow that it will take too long for the index's analyze.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: make auto-analyze's tidb_index_serial_scan_concurrency configurable

pkg/server/conn.go, pkg/util/tracing/util.go
Issue Number: close #50508
Problem Summary: Caused by https://github.com/pingcap/tidb/pull/40825, miss root span for opentracing tools.
Tests 
Start a TiDB cluster as #50508 said, and use JaegerUI to get trace info success.
> 
Side effects
Documentation
```release-note
None
```
=> conn, util: make `opentracing` work again

go.mod, pkg/executor/BUILD.bazel, pkg/executor/concurrent_map_test.go, pkg/executor/executor_pkg_test.go, pkg/executor/hash_table_test.go, pkg/util/hack/hack.go, pkg/util/set/mem_aware_map.go
Issue Number: close #50544 and #50552 
This PR is trivial.
As the [discussion](https://github.com/golang/go/issues/63438) indicates load factor of map in 1.21 would be 6 rather than 6.5 in other version. The whole test of TestaggPartiualResultMap depends on the assumption that load factor of map in golang would be 6.5.
To adopt this breaking behavior, the codebase of tidb should makes changes accordingly.
Tests 
> 
Side effects
Documentation
=> executor: adapt to the go1.21 map loadFactor setting value

br/pkg/aws/ebs.go
Issue Number: close #50559 
1. Add the new tag to snapshots
2. Check fsr enablement periodically instead of sleep for a long time. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ebs br: new snapshot tagging

pkg/executor/internal/mpp/executor_with_retry.go, pkg/executor/internal/mpp/local_mpp_coordinator.go
Issue Number: close #50493
Should `close coordinator` before `unregister` it, otherwise coordinator manager cannot find it to call `ReportStatus()`, which makes `coordinator.Close()` to wait `3 seconds` to finish, check [here](https://github.com/pingcap/tidb/blob/master/pkg/executor/internal/mpp/local_mpp_coordinator.go#L597)
Tests 
Needs real tiflash to cover, and we already have a integration test in tiflash repo.
before: 
after:
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix the issue of coordinator.Close() taking too long

pkg/meta/autoid/autoid_service.go
Issue Number: close #50519
The old logic is not concurrency-safe. Although some of the fields are protected by mutex, the logic is not correct.
Imagine that there are 7K concurrent Alloc() operation, and one of them meet rpc error.
Then one `ResetConn()` is called, which invokes `grpcConn.Close()`.
Note, there are many ongoing calling of `Alloc()` and still using the conn, so close the grpcConn cause this error:
> rpc error: code = Canceled desc = grpc: the client connection is closing
This error in turn cause `ResetConn()` calling. 
Even though `GetClient()` get a new client, the new client might be reset again by the `ResetConn()` mistakenly!
So the client can not recover from the error automatically some times (when the concurrent contention is high enough).
To …
=> meta/autoid: make autoid client ResetConn operation concurrency-safe

pkg/bindinfo/bind_cache.go, pkg/bindinfo/binding.go, pkg/bindinfo/global_handle.go, pkg/bindinfo/session_handle.go, pkg/executor/adapter.go, pkg/executor/show.go, pkg/planner/optimize.go
Problem Summary: planner: clean BindRecord in the binding package
NO LOGICAL CHANGE, JUST REFACTOR
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: clean BindRecord in the binding package

pkg/planner/core/indexmerge_path.go, tests/integrationtest/r/planner/core/casetest/index/index.result, tests/integrationtest/r/planner/core/indexmerge_path.result, tests/integrationtest/t/planner/core/casetest/index/index.test
Issue Number: close https://github.com/pingcap/tidb/issues/50553
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix single mv index merge case couldn't be hinted by use_index_merge

DEPS.bzl, go.mod, go.sum, meta/autoid/autoid_service.go
Issue Number: close #50519
Cherry-pick https://github.com/pingcap/tidb/pull/50522 for a 6.5.6 hotfix 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> meta/autoid: make autoid client ResetConn operation concurrency-safe (#50522)

pkg/planner/core/optimizer.go
Moved the flags adjusting process out as a func. It would help us reduce the noise when we look at the `doOptimize` function.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> optimizer: move adjust optimization flags code out

pkg/executor/infoschema_reader.go
…alCnt
Issue Number: close #50632
sometime , we will see this situation which process is more than 1 and it's processedRows is greater than totalCnt.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: avoid the situation where processedRows is greater than totalCnt

pkg/executor/analyze_col_v2.go, pkg/executor/builder.go
Issue Number: close #50641
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: use analyze scan concurrency to control index analyze

pkg/expression/context.go
Issue Number: close #50635
Always use the location from `StmtCtx.TypeCtx()` instead `SessionVars.Location`
Tests 
> regress the exist tests
Side effects
Documentation
```release-note
None
```
=> expression: expression always read location from `types.Context`

pkg/planner/core/find_best_task.go
Moved the default iteration function out of the main process to reduce the noise when reading code.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move iterate physical plan out

pkg/expression/expression.go, pkg/planner/core/BUILD.bazel, pkg/planner/core/expression_rewriter.go, pkg/planner/core/expression_test.go, pkg/planner/core/optimizer.go, pkg/planner/core/planbuilder_test.go
Issue Number: close #50463
We provide a new function `expression.BuildExprWithAst` to build some simple expressions. Different with the exists `rewriteAstExpr`, it does not construct a plan builder when building expression. So it requires less context information than `rewriteAstExpr`.
`expression.BuildExprWithAst` is only used to build some simple expressions. When a expression contains a subquery, `BuildExprWithAst` will return an error.
In the later PRs, we should introduce `expression.BuildContext` to replace `sessionctx.Context` as the input context of `BuildExprWithAst`. So that we can build an expression outside a session without using mock context.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language …
=> expression: provide `BuildExprWithAst` to build expression without planner context

pkg/bindinfo/binding_match.go, pkg/bindinfo/global_handle_test.go, pkg/bindinfo/tests/BUILD.bazel, pkg/bindinfo/tests/bind_test.go
Issue Number: close #50646
Problem Summary: planner: fix the issue that upper database schema name cannot match global bindings
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix the issue that upper database schema name cannot match global bindings

pkg/privilege/privileges/ldap/BUILD.bazel, pkg/privilege/privileges/ldap/ldap_common.go, pkg/privilege/privileges/ldap/ldap_common_test.go
Issue Number: ref #36036
TLS1.0/1.1 has security issues, remove the support of them.
Tests 
> 
Side effects
Documentation
```release-note
remove TLS1.0, TLS1.1 support
```
=> privilege: add min TLS version for LDAP

pkg/parser/hintparserimpl.go
…Hint
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser: generate no stack warning for ErrWarnOptimizerHintUnsupportedHint

br/pkg/lightning/backend/kv/kv2sql.go, pkg/ddl/bench_test.go, pkg/ddl/index.go, pkg/ddl/index_change_test.go, pkg/executor/admin.go, pkg/executor/batch_checker.go, pkg/executor/distsql.go, pkg/executor/distsql_test.go, pkg/executor/executor.go, pkg/executor/foreign_key.go, pkg/executor/split.go, pkg/executor/split_test.go, pkg/executor/test/admintest/BUILD.bazel, pkg/executor/test/admintest/admin_test.go, pkg/executor/test/executor/executor_test.go, pkg/server/handler/tikv_handler.go, pkg/table/BUILD.bazel, pkg/table/index.go, pkg/table/tables/BUILD.bazel, pkg/table/tables/index.go, pkg/table/tables/index_test.go, pkg/table/tables/tables.go, pkg/util/admin/admin.go
Issue Number: close #50691
see description in issue
Make some methods in `table.Index` to require less context input
Tests 
> Regress the exist tests.
Side effects
Documentation
```release-note
None
```
=> table: simplify the interface `table.Index` to reduce its context requirement

pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/expression_rewriter.go, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/rule_join_reorder.go, pkg/planner/core/rule_join_reorder_greedy.go, pkg/planner/core/rule_partition_processor.go, pkg/planner/core/rule_semi_join_rewrite.go, pkg/sessionctx/stmtctx/stmtctx.go
Issue Number: close #48875
Now, we have some hint warning when hint has problems. but we cannot know all of them quickly. so we add the ```SetHintWarning``` to know them.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> bindinfo: add SetHintWarning to trace the hint warning

br/pkg/lightning/backend/local/BUILD.bazel, br/pkg/lightning/backend/local/local.go, br/pkg/lightning/backend/local/local_test.go
Issue Number: close #50198
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> local backend: fix sst skip ingest when multiIngest=false and exhausted retry count

go.mod, pkg/executor/BUILD.bazel, pkg/executor/concurrent_map_test.go, pkg/executor/executor_pkg_test.go, pkg/executor/hash_table_test.go, pkg/util/hack/hack.go, pkg/util/set/mem_aware_map.go
This is an cherry-pick of https://github.com/pingcap/tidb/pull/50545 to relase-7.5
Issue Number: close https://github.com/pingcap/tidb/issues/50544 and https://github.com/pingcap/tidb/issues/50552
This PR is trivial.
As the https://github.com/golang/go/issues/63438 indicates load factor of map in 1.21 would be 6 rather than 6.5 in other version. The whole test of TestaggPartiualResultMap depends on the assumption that load factor of map in golang would be 6.5.
To adopt this breaking behavior, the codebase of tidb should makes changes accordingly.
Tests 
> 
Side effects
Documentation
=> executor: adapt to the go1.21 map loadFactor setting value (#50545)

pkg/session/session.go, pkg/util/BUILD.bazel, pkg/util/processinfo.go, pkg/util/processinfo_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50607
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> session: fix update process info will data race with expensive-query check

DEPS.bzl, go.mod, go.sum, pkg/planner/core/point_get_plan.go, pkg/table/tables/test/partition/BUILD.bazel, pkg/table/tables/test/partition/partition_test.go, tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result, tests/integrationtest/t/planner/core/casetest/partition/partition_pruner.test
This is an manual cherry-pick of #50603
Issue Number: close #50206
The column index was set to the second column, but in Fast Plan the value pairs is always the first one, so it needed to be adjusted for Key Partitioned tables.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner/core: Key partitioning uses an column index, which did not match value pairs in fast plan

pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/logical_plans.go, pkg/planner/core/rule_topn_push_down.go, pkg/util/hint/hint.go
Issue Number: ref https://github.com/pingcap/tidb/issues/48875
ONLY REFACTOR, NO LOGICAL CHANGE
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: refactor limit hint

br/pkg/restore/client.go, br/tests/br_check_new_collocation_enable/run.sh
Issue Number: close #50741
br integration test bug
fix br integration test: match the correct error string
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: fix br integration test 6.5.8

pkg/expression/expression.go, pkg/planner/core/expression_rewriter.go, pkg/planner/core/expression_test.go, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/optimizer.go, pkg/planner/core/planbuilder.go, pkg/sessiontxn/staleread/util.go
Issue Number: ref #50463
In #50464, we introduced a new function `BuildExprWithAst` to build some simple expressions. This PR is further work to use `buildExprWithAst` to implement evalAstExpr.
`BuildExprWithAst` also not allow `ParamMarkerExpr` to make the context requirement simple.
In some other subquery expressions we used `planCtx.builder.ctx` instead `er.sctx` to make the `er.sctx` simple
Tests 
> regress the exist tests
Side effects
Documentation
```release-note
None
```
=> expression: use `buildExprWithAst` to implement `evalAstExpr`

pkg/executor/executor.go, pkg/executor/test/simpletest/simple_test.go, pkg/planner/core/debugtrace.go, pkg/plugin/conn_ip_example/conn_ip_example.go, pkg/session/session.go, pkg/sessionctx/sessionstates/session_states.go, pkg/sessionctx/sessionstates/session_states_test.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/session_test.go, pkg/sessionctx/variable/sysvar_test.go
Issue Number: close #50715
This problem was introduced by #44953, which calls `InTxn()` in another goroutine but `Status` is not thread-safe.
- Change `Status` from `uint16` to `atomic.Uint32`
- Rename `Status` to `status` to avoid it to be visited outside
- Make `TestTiDBEnableResourceControl` stable because it always fails after this PR
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> sessionctx: fix data race of SessionVars.Status

DEPS.bzl, go.mod, go.sum
Issue Number: ref #50758 
Problem Summary: TiDB may access an unready store.
bump client-go to pick https://github.com/tikv/client-go/pull/1136 .
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: bump client-go to avoid accesses to unready store

pkg/planner/optimize.go, pkg/util/hint/BUILD.bazel, pkg/util/hint/hint.go
Problem Summary: planner: move more hint code to the hint package
ONLY REFACTOR, NO LOGICAL CHANGE
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move more hint code to the hint package

DEPS.bzl, go.mod, go.sum
Issue Number: close #50775
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix go-resty/resty/v2 HTTP request body disclosure

pkg/statistics/handle/cache/BUILD.bazel, pkg/statistics/handle/cache/internal/lfu/lfu_cache.go, pkg/statistics/handle/cache/stats_table_row_cache.go, pkg/statistics/handle/cache/statscache.go, pkg/statistics/handle/cache/statscacheinner.go
Issue Number: ref https://github.com/pingcap/tidb/issues/40791
- Extracted some util functions.
- Moved stats_table_row_cache out of cacher inner.
- Add some comments.
No logic change, just some refactors.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: extract functions and add comments

pkg/ddl/backfilling_dist_executor.go, pkg/disttask/framework/BUILD.bazel, pkg/disttask/framework/framework_ha_test.go, pkg/disttask/framework/framework_test.go, pkg/disttask/framework/mock/task_executor_mock.go, pkg/disttask/framework/taskexecutor/interface.go, pkg/disttask/framework/taskexecutor/main_test.go, pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/taskexecutor/manager_test.go, pkg/disttask/framework/taskexecutor/task_executor.go, pkg/disttask/framework/taskexecutor/task_executor_test.go, pkg/disttask/framework/taskexecutor/task_executor_testkit_test.go, pkg/disttask/framework/testutil/disttest_util.go, pkg/disttask/framework/testutil/executor_util.go, pkg/disttask/importinto/task_executor.go, pkg/disttask/importinto/task_executor_test.go
- decouple some logic(previous handleExecutableTask) which should belongs to task-executor from manager
- separate task-executor context and run-step context, so we can cancel right context as needed(we are relying on manager context previously to do some task state handling)
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: decouple handleExecutableTask from manager & separate executor context

pkg/executor/importer/importer_testkit_test.go, pkg/executor/importer/table_import.go
Issue Number: close #50805
Tests 
check adjust concurrency works
```
[2024/01/30 12:31:29.634 +08:00] [INFO] [table_import.go:933] ["checksum with adjusted distsql scan concurrency"] [concurrency=50]
```
> 
Side effects
Documentation
```release-note
None
```
=> importinto: fix checksum always use default distsql-scan-concurrency

pkg/executor/adapter.go, pkg/executor/analyze_col_v2.go, pkg/executor/builder.go
Issue Number: close #50641
After #50639, we use ```tidb_analyze_distsql_scan_concurrency``` to control all the disql_scan_concurrency. so we can remove the old code.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: remove useless code for tidb_analyze_distsql_scan_concurrency

pkg/store/mockstore/unistore/tikv/mvcc.go, pkg/store/mockstore/unistore/tikv/server.go
Issue Number: ref #50731 
Introduce lock scan phase for pessimistic lock rollback.
Tests 
Side effects
Documentation
```release-note
None
```
=> txn: support pessimistic rollback with scan first in mockstore

pkg/autoid_service/BUILD.bazel, pkg/autoid_service/autoid.go, pkg/autoid_service/autoid_test.go
Issue Number: close #50819
The exposed API should be thread-safe, and `forceRebase`   `allocAutoID`   `alloc4Unsigned`   `alloc4Signed` ... all those internal functions should be called under lock. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> pkg/autoid_service: add lock to make API thread-safe

docs/design/2022-11-23-batch-cop.md
Issue Number: ref #39361 
The design docuement.
Tests 
Documentation
```release-note
None
```
=> doc: add batch coprocessor rfc

pkg/executor/hash_table.go
Issue Number: close https://github.com/pingcap/tidb/issues/50841
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that goroutine leak when hashJoin triggered spill and sql failed
```
=> executor: fix negative consumedbyte for hashRowcontainer

pkg/executor/plan_replayer.go, pkg/parser/digester.go, pkg/parser/digester_test.go, pkg/planner/core/planbuilder.go, pkg/planner/core/preprocess.go, pkg/server/handler/optimizor/BUILD.bazel, pkg/server/handler/optimizor/plan_replayer_test.go, pkg/session/bootstrap.go
Issue Number: close #43192
plan replayer cannot load bindings when the statement contains in (...).
This PR is to change the way of normalizing in-list from (…) to (?).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> plan replayer: fix cannot load bindings when the statement contains in (...)

pkg/domain/infosync/error.go, pkg/errno/BUILD.bazel, pkg/errno/errcode.go, pkg/errno/errname.go, pkg/errno/errname_test.go
Issue Number: close #49546
Two err codes don't have corresponding error messages. They may be the reason of #49546, but actually I'm not 100% sure. A possible routine is that the connection to PD HTTP Server somehow failed, and the user uses `show ...` like `show placement`, then the `ErrHTTPServiceError` will be recorded.
This PR adds a test to make sure every err code has its corresponding message.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> errno: add test to check every errcode has its message

br/pkg/aws/ebs.go
Issue Number: close #50878 
This PR is to address a name duplication issue doing backup from a restored cluster. The tag key of snapshots is renamed from `TiDBCluster-BR` to `TiDBCluster-BR-Snapshot`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ebs br: rename a tag for EBS snapshots

pkg/infoschema/test/clustertablestest/tables_test.go
Issue Number: close #41455 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: add more sleep time for `TestMemoryUsageAndOpsHistory` test

pkg/executor/batch_point_get.go, pkg/executor/distsql.go, pkg/executor/index_merge_reader.go, pkg/executor/internal/exec/BUILD.bazel, pkg/executor/internal/exec/indexusage.go, pkg/executor/internal/exec/indexusage_test.go, pkg/executor/point_get.go, pkg/statistics/handle/usage/indexusage/collector.go
Issue Number: close #50814
Previously, the usage is recorded on each partitions, so that the queries on different partitions will not be deduplicated 🤦  and will be recorded multiple times.
This PR adds one more argument on the `ReportPointGetIndexUsage` and `ReportCopIndexUsage` function to get both the `physicalTableID` and `tableID`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: record the index usage on a the whole table

br/pkg/mock/mock_cluster.go, cmd/tidb-server/main.go, pkg/bindinfo/tests/bind_test.go, pkg/server/handler/extractorhandler/extract_test.go, pkg/server/handler/optimizor/optimize_trace_test.go, pkg/server/handler/optimizor/plan_replayer_test.go, pkg/server/handler/optimizor/statistics_handler_test.go, pkg/server/handler/tests/http_handler_test.go, pkg/server/server.go, pkg/server/tests/commontest/tidb_test.go, pkg/server/tests/servertestkit/testkit.go, pkg/server/tests/tls/tls_test.go
Issue Number: close #50854
Tests 
create many tables, we can read the metrics HTTP API but cannot operator MySQL port.
> 
Side effects
Documentation
```release-note
None
```
=> *: force_init_stats doesn't block http api's startup

pkg/util/rowcodec/rowcodec_test.go
Issue Number: ref #50851
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> codec: fix row codec unit test on timestamp cannot pass caused by local time zone not utc

br/pkg/restore/BUILD.bazel, br/pkg/restore/merge.go, br/pkg/rtree/BUILD.bazel, br/pkg/rtree/merge_fuzz_test.go, br/pkg/rtree/rtree.go, br/pkg/rtree/rtree_test.go
Issue Number: close #50613
Merge file ranges takes too much time when the file ranges's size is much large.
use the O(n) algorithm
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: merge range in lightweight when snapshot restore

pkg/disttask/framework/integrationtests/BUILD.bazel, pkg/disttask/framework/integrationtests/framework_err_handling_test.go, pkg/disttask/framework/integrationtests/framework_ha_test.go, pkg/disttask/framework/integrationtests/framework_pause_and_resume_test.go, pkg/disttask/framework/integrationtests/framework_role_test.go, pkg/disttask/framework/integrationtests/framework_rollback_test.go, pkg/disttask/framework/integrationtests/framework_test.go, pkg/disttask/framework/integrationtests/main_test.go, pkg/disttask/framework/scheduler/scheduler.go, pkg/disttask/framework/scheduler/scheduler_manager.go, pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/taskexecutor/manager_test.go, pkg/disttask/framework/taskexecutor/slot.go, pkg/disttask/framework/taskexecutor/slot_test.go, pkg/disttask/framework/taskexecutor/task_executor.go, pkg/disttask/framework/testutil/context.go, pkg/testkit/testkit.go
- fix routine leak
- refactor failpoints
- refine logs
- random chose nodes for HA cases
- remove duplicate HA cases
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: fix routine leak & refine logs & refactor failpoint

pkg/expression/util.go, pkg/planner/core/casetest/BUILD.bazel, pkg/planner/core/casetest/integration_test.go, pkg/planner/core/rule_aggregation_push_down.go
Issue Number: close #50926
Problem Summary: planner: stop pushing Agg down through Projection if substitution fail
planner: stop pushing Agg down through Projection if substitution fail
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: stop pushing Agg down through Projection if substitution fail

pkg/ddl/ddl_api.go, pkg/ddl/schematracker/info_store.go, pkg/ddl/schematracker/info_store_test.go, pkg/domain/plan_replayer_dump.go, pkg/executor/show.go, pkg/infoschema/infoschema.go, pkg/infoschema/infoschema_test.go, pkg/statistics/handle/autoanalyze/autoanalyze.go
We're going to implement the [InfoSchemaV2](https://github.com/pingcap/tidb/pull/50591), the new implementation need to keep almost the same interface.
So, remove the redundant methods can make the refactor easier.
```
AllSchemaNames() []string
TableIsView(schema, table model.CIStr) bool
TableIsSequence(schema, table model.CIStr) bool
```
Tests 
> 
Just tiny refactor, no functional changes.
Side effects
Documentation
```release-note
None
```
=> infoschema: remove some redundant methods from InfoSchema

pkg/statistics/handle/syncload/stats_syncload.go
Issue Number: close #50957
we need to load the stats cache in the background. but if we meet the timeout, we must wait constantly to retry. it will happen thundering herd. so we need to add the rand sleep to prevent it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: avoid thundering herd problem when timeout the stats sync load

br/pkg/lightning/backend/external/merge.go, br/pkg/lightning/backend/external/merge_v2.go, br/pkg/lightning/backend/external/onefile_writer.go, br/pkg/lightning/backend/external/onefile_writer_test.go, br/pkg/lightning/backend/external/util.go, br/pkg/lightning/backend/external/writer.go, pkg/disttask/importinto/BUILD.bazel, pkg/disttask/importinto/task_executor.go
Issue Number: ref #50832
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> external: onefile writer should have onClose, and add KV count to WriteSummary

pkg/expression/aggregation/aggregation.go, pkg/store/mockstore/mockcopr/cop_handler_dag.go, pkg/store/mockstore/unistore/cophandler/cop_handler.go, pkg/store/mockstore/unistore/cophandler/mpp.go
Issue Number: close https://github.com/pingcap/tidb/issues/50893
for this simple refactor work, the previous unit test is adequate, there is a concrete fix pull request next to fix explicit issues,
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: refactor NewDistAggFunc for mpp agg aware of tipb's aggDesc execution mode

pkg/executor/builder.go, pkg/executor/infoschema_reader.go, pkg/infoschema/cluster.go, pkg/infoschema/tables.go, pkg/infoschema/test/clustertablestest/BUILD.bazel, pkg/infoschema/test/clustertablestest/cluster_tables_test.go
Issue Number: close #50823
1. Create new tables `information_schema.tidb_index_usage` + `cluster_tidb_index_usage`
Tests 
> 
Documentation
```release-note
Add new tables `information_schema.tidb_index_usage` and `information_schema.cluster_tidb_index_usage` to show the index usage statistics information.
```
=> executor,bootstrap: add `tidb_index_usage` table and `cluster_tidb_index_usage` table

pkg/executor/slow_query_test.go, pkg/executor/stmtsummary_test.go, pkg/expression/builtin_cast_test.go, pkg/expression/builtin_time_test.go, pkg/expression/context.go, pkg/expression/helper_test.go, pkg/expression/main_test.go, pkg/store/mockstore/mockcopr/cop_handler_dag.go, pkg/store/mockstore/unistore/cophandler/cop_handler.go, pkg/table/column_test.go, pkg/util/mock/context.go
Issue Number: close #50953
See issue. The failed test is caused by PR: #50530. In this PR, we unified the code to read the timezone info from `stmtctx.TimeZone`. In product environment, `sc.TimeZone` should be the same with `sessionVars.TimeZone`, but in some test cases, not all of them are set to a same value. So the some tests failed.
The reason why verify check success is because the remote machine is using UTC as the system timezone, but in local environment, it is not.
1. Both set timezone to session variable and statement context in some tests.
2. For `createContext` in `expression.main_test.go`, we set the location to `UTC+11` to make the default time zone different with most CI and dev envrioments.
3. Add an assert in `location` method in `expression/context.go` …
=> expression: fix some failed tests in local env

pkg/ddl/BUILD.bazel, pkg/ddl/backfilling_dist_scheduler.go, pkg/ddl/backfilling_dist_scheduler_test.go
Issue Number: ref #48795
Previously, the subtask count is unreasonable:
https://github.com/pingcap/tidb/blob/35a7c9e2f7c5b6413a1dd30b9d4957552a0d95a9/pkg/ddl/backfilling_dist_scheduler.go#L325-L327
It is inaccurate to use 96M to calculate the size of index data in a region. As a result, the number of subtasks will become very large, which is quite inefficient.
Make local sort generate only one subtask for each instance.
Tests 
1.194TiB table, 8 worker count:
Before this PR: 1 hour 1 min 29 sec
After this PR: 26 min 10 sec
> 
Side effects
Documentation …
=> ddl: make local sort generate only one subtask for each instance

br/pkg/restore/client.go, br/pkg/task/common.go, br/pkg/task/common_test.go, br/pkg/task/restore.go
Issue Number: close #50568
BR cannot load statistic data when it doesn't do checksum
add new parameter `load-stats` for load stats
Tests 
> 
Side effects
Documentation
```release-note
add `load-stats` parameter to enable br to skip restore statistic data.
```
=> br: add restore stats config

DEPS.bzl, go.mod, go.sum
Issue Number: close #50731
Introduce pessimistic lock region rollback to speed up expired lock cleaning. The tikv related issue is https://github.com/tikv/tikv/issues/16158.
From the debugging test, 
```
CREATE TABLE t1 (id BIGINT NOT NULL PRIMARY KEY auto_increment, pad1 BLOB, pad2 BLOB, pad3 BLOB, int_col INT NOT NULL DEFAULT 0);
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM dual;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), …
```
=> txn: bump up dependency of client-go to enable pessimistic lock region rollback

pkg/metrics/grafana/tidb_summary.json, pkg/metrics/grafana/tidb_summary.jsonnet
Issue Number: close https://github.com/pingcap/tidb/issues/51001
Add the missing instance label to make Grafana more accurate.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> grafana: add missing instance filter in tidb_summary.json

br/pkg/lightning/backend/external/bench_test.go, br/pkg/lightning/backend/external/byte_reader.go, br/pkg/lightning/backend/external/engine.go, br/pkg/lightning/backend/external/merge_v2.go, br/pkg/lightning/backend/external/misc_bench_test.go, br/pkg/lightning/backend/external/reader.go, br/pkg/lightning/backend/external/reader_test.go, br/pkg/lightning/backend/external/testutil.go
use 2 membuf.Pool that shares one membuf.Limiter.
- smallBlockBufPool: block size 1M, used to store the KV pairs that will be sent to TiKV. KV size larger than 1M can be allocated but will not be tracked by membuf.Limiter.
- largeBlockBufPool: block size 8M, used by concurrent reader
Also, in readAllData spawn constant number of worker, each with a smallBlockBuf and largeBlockBuf. So the memory usage is no longer relevant to number of files to be read.
Tests 
> 
run `TestReadAllData`, before this PR
```
bench_test.go:821: readAllData time cost: 1m41.626412352s, size: 2939207462
```
and peak memory usage is 8.29G
after
```
bench_test.go:829: readAllData time cost: 39.031899936s, size: …
```
=> external: use 2 membuf pools of difference block size

br/pkg/restore/client.go, br/pkg/restore/client_test.go, br/pkg/task/restore.go
Issue Number: close #50767
br restore is very slowly if there are many databases(2000+)
create database by db pool
Tests 
40 minutes -> 5 minutes
> 
Side effects
Documentation
```release-note
None
```
=> br: create database by db pool

br/pkg/pdutil/pd.go
Issue Number: close #50566 
one tikv has no leader and slow down br restore spee
remove `evict-slow-store-scheduler` when restore
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: remove evict slow store scheduler

br/pkg/restore/client.go, br/pkg/task/restore.go
Issue Number: close #50232
Currently BR determines whether the cluster is fresh by checking the sst checkpoint data.
Instead, it would determines by checking the checkpoint meta which generated during checkpoint initialization.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: check the first run by checkpoint meta

br/pkg/streamhelper/BUILD.bazel, br/pkg/streamhelper/advancer.go, br/pkg/streamhelper/advancer_test.go, br/pkg/utils/worker.go
Issue Number: close #50839
This PR will do the nil check over the `checkpoints`.
This PR also will catch the panic generated during the subscription handler.
And some locking are acquired during handling incoming tasks. 
Tests 
> 
```release-note
Fixed a bug that may make TiDB panic when stopping a log backup task.
```
=> br/streamhelper: fix panic while removing task

pkg/executor/internal/exec/indexusage.go, pkg/executor/internal/exec/indexusage_test.go, pkg/planner/cardinality/trace.go, pkg/planner/core/casetest/planstats/plan_stats_test.go, pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/find_best_task.go, pkg/planner/core/stats.go, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/session_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50835
Introduced by https://github.com/pingcap/tidb/pull/50643/files
Make usedStatsInfo thread-safe and also use CAS to init it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor,planner: make used stats info thread safe

pkg/metrics/grafana/tidb.json
Issue Number: close #51051
In the grafana. QPS of the auto analyze is float. It should be int.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> metrics: tidb_statistics_auto_analyze_total should be int

pkg/executor/benchmark_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/45112
code complement for https://github.com/pingcap/tidb/pull/45158
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: adding missing code of similar definition for test

pkg/ddl/tests/metadatalock/BUILD.bazel, pkg/ddl/tests/metadatalock/mdl_test.go, pkg/planner/core/preprocess.go
Issue Number: close #47475
Skip lock if the statement is analyze stmt
Tests 
> 
Side effects
Documentation
```release-note
Analyze doesn't block DDL any more 
```
=> planner: skip MDL when analyzing table

pkg/executor/importer/import.go, pkg/executor/importer/import_test.go, pkg/executor/importer/precheck.go, pkg/executor/importer/precheck_test.go, tests/realtikvtest/importintotest/precheck_test.go
Issue Number: ref #49883
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> importinto: add disable_precheck option & change default threadcnt when import from select

pkg/ddl/generated_column.go, tests/integrationtest/r/ddl/db_integration.result, tests/integrationtest/t/ddl/db_integration.test
Issue Number: close #49909
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl:  forbid create `Generated column` with `Grouping` function

pkg/ddl/db_integration_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/51114
Different UUID values will result in different error code.
```
tidb> create table t1 (c int(10), c1 int default (REPLACE(UPPER(UUID()), '-', '')));
Query OK, 0 rows affected (0.04 sec)
tidb> insert into t1(c) values (1),(2),(3);
ERROR 1690 (22003): BIGINT value is out of range in '451E9'
tidb> insert into t1(c) values (1),(2),(3);
ERROR 1292 (22007): Truncated incorrect DOUBLE value: '463ED8D2CE3911EE988E3C7D0A09BA5A'
```
Tests 
> 
Side effects
Documentation
```release-note
None …
```
=> ddl: update TestDefaultColumnWithReplace error code

pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/51142
We received some unstable test reports regarding certain cases. The instability arose from the fact that the case attempted to verify if the job had failed just by now. However, in some instances, if the test case was running slowly, it wouldn't be considered as just failing now because it is more than one second. To address this, we decided to omit the fail reason check in this PR. Additionally, we changed the timer intervals from 1 second to 10 seconds.
Tests 
> 
Side effects
Documentation …
=> statistics: fix the test case by increase the time interval

pkg/statistics/handle/autoanalyze/autoanalyze.go, pkg/statistics/handle/handle.go, pkg/statistics/handle/types/interfaces.go
Issue Number: close https://github.com/pingcap/tidb/issues/50100
This PR is a follow-up PR of https://github.com/pingcap/tidb/pull/50099
We should also consider the partitions. We don't need to create pseudo stats here to waste time and memory.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: skip create pseudo stats for partitions

br/pkg/streamhelper/advancer.go, br/pkg/streamhelper/regioniter.go, pkg/metrics/log_backup.go
Issue Number: close #51046
It is painful for debugging slow regions in log backup for now. Exactly when there are many TiKV nodes in the cluster: we only have a range but know nothing about which region this key belongs to.
Also we must pick the TiDB log (which isn't always easily accessible.) for such information.
This PR added two new series to the log backup advancer, which presents the current slowest region's leader location and its region id.
Also we will append more detailed hints about the slowest range.
Tests 
A simple log:
>  …
=> log_backup: added more info for slow regions in log backup advancer

br/pkg/storage/local.go, br/pkg/storage/local_test.go
Issue Number: close #49423
see issue
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> storage: local storage tolerates broken symlink when Walk

pkg/ddl/index.go, pkg/ddl/ingest/checkpoint.go, pkg/ddl/ingest/checkpoint_test.go, pkg/ddl/reorg.go
Issue Number: close #50990
For multi-schema change like `add index i1, add index i2`, only one index is imported when `ddl_disk_quota` is reached:
```
/tmp/tidb/tmp_ddl-4000/108$ du -hs ./*
16K     ./35a62bba-3aab-5322-b59b-c5bc8baf9c9d
4.0K    ./35a62bba-3aab-5322-b59b-c5bc8baf9c9d.sst
16K     ./8d2242cb-c9a7-5915-a93a-45927b24759d
4.0G    ./8d2242cb-c9a7-5915-a93a-45927b24759d.sst
/tmp/tidb/tmp_ddl-4000/108$ du -hs ./*
16K     ./35a62bba-3aab-5322-b59b-c5bc8baf9c9d
4.0K    ./35a62bba-3aab-5322-b59b-c5bc8baf9c9d.sst
16K     ./8d2242cb-c9a7-5915-a93a-45927b24759d
16G     ./8d2242cb-c9a7-5915-a93a-45927b24759d.sst
/tmp/tidb/tmp_ddl-4000/108$ du -hs ./*
16K     ./35a62bba-3aab-5322-b59b-c5bc8baf9c9d
4.0K    ./35a62bba-3aab-5322-b59b-c5bc8baf9c9d.sst
16K …
```
=> ddl/ingest: fix local flush logic for multi-schema change

pkg/ddl/tests/resourcegroup/resource_group_test.go, pkg/domain/resourcegroup/runaway.go, pkg/store/copr/coprocessor.go
Issue Number: close #51161
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> resource_control: dont check runaway after resp

pkg/planner/core/physical_plans.go
Issue Number: close #51204
Before, we do not try to extract correlated column in LateMaterializationFilterCondition. So when the correlated columns only in LateMaterializationFilterCondition, exprs failed to fill in correlated column with constant value during Plan2Pb, and it leads to wrong query result.
Now, in ExtractCorrelatedCols method, we will also try to extract correlated column in LateMaterializationFilterCondition.
Also fix other methods.
Currently, integration test do not support TiFlash, so I will add tests in https://github.com/pingcap/tiflash later
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-n …
=> planner: fix ExtractCorrelatedCols method in PhysicalTableScan (cherry-pick #51205)

pkg/sessionctx/variable/sysvar.go
Issue Number: close #48180
recalculate the threshold of gctuner when ServerMemoryLimit is updated. 
Tests 
I have tested in the production cluster. When I set ```ServerMemoryLimit``` , the GOGC will update.
> 
Side effects
Documentation
```release-note
None
```
=> *: recalculate the threshold of gctuner when ServerMemoryLimit is updated

br/pkg/backup/schema_test.go, br/pkg/restore/BUILD.bazel, br/pkg/restore/client.go, br/pkg/restore/db_test.go, br/pkg/restore/systable_restore.go, br/pkg/task/restore_test.go, br/pkg/utils/schema.go, br/tests/_utils/make_tiflash_config, br/tests/br_backup_version/run.sh, pkg/ddl/db_test.go, pkg/ddl/ddl_api.go, pkg/ddl/tiflash_replica_test.go, pkg/executor/importer/importer_testkit_test.go, pkg/executor/infoschema_cluster_table_test.go, pkg/infoschema/test/clustertablestest/BUILD.bazel, pkg/infoschema/test/clustertablestest/cluster_tables_test.go, pkg/parser/mysql/const.go, pkg/server/handler/tests/http_handler_test.go, pkg/session/bootstrap.go, pkg/statistics/handle/storage/dump_test.go, pkg/telemetry/BUILD.bazel, pkg/telemetry/data_feature_usage_test.go, pkg/util/misc.go, pkg/util/sem/sem.go, tests/integrationtest/r/executor/infoschema_reader.result
Issue Number: close #50886
Add a new database `sys`
Add a new view `sys.schema_unused_indexes` to show show the index which hasn't been used since last restart.
Adding a new system database is risky. I've considered the following related codes and have made some change:
1. For BR, it handles the system table specially. I modified these code logic to also handle the new `sys` database as a special system database. The new view `schema_unused_indexes` will be skipped (like `tidb_mdl_view`).
2. For TiFlash, this PR modifies the `ddl` and also adds some tests to make sure the database is not allowed to add TiFlash replica.
For other tools, I didn't notice any special code logic about the system table 🤔 . I'll do some manually/automatic tests for them.
Tests 
> - [ ] I checked …
=> bootstrap, br: add `sys.schema_unused_indexes` view | tidb-test=pr/2287

pkg/planner/core/planbuilder.go, tests/integrationtest/r/planner/core/integration.result, tests/integrationtest/t/planner/core/integration.test
Issue Number: close #51218
Tell whether a table is `SysDB` with `IsSysDB`, but not `== mysql.SystemDB`.
Tests 
> 
```release-note
None
```
=> planner: allow read from TiKV for `sys` schema when `tidb_isolation_read_engines` is set to tiflash

pkg/planner/core/physical_plan_test.go, pkg/planner/core/physical_plans.go
Issue Number: close #51204
Before, we do not try to extract correlated column in LateMaterializationFilterCondition. So when the correlated columns only in LateMaterializationFilterCondition, exprs failed to fill in correlated column with constant value during Plan2Pb, and it leads to wrong query result.
Now, in ExtractCorrelatedCols method, we will also try to extract correlated column in LateMaterializationFilterCondition.
Also fix other methods.
Currently, integration test do not support TiFlash, so I will add tests in https://github.com/pingcap/tiflash
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-s …
=> planner: fix ExtractCorrelatedCols method in PhysicalTableScan 

pkg/statistics/handle/autoanalyze/autoanalyze.go
Issue Number: close https://github.com/pingcap/tidb/issues/51187
Before using GetPartitionStatsForAutoAnalyze API, we need to check if it returns nil stats. We missed it in some places.
1. Checked the if stats is nil.
2. Renamed `partitionStatsTbl` to `partitionStats`.
3. Added more comments.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: check if stats is nil

DEPS.bzl, go.mod, go.sum, pkg/domain/domain_sysvars.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #51194.
Fix the problem that setting `tidb_enable_tso_follower_proxy` with TSO service will cause stuck.
Return the error after setting `tidb_enable_tso_follower_proxy`.
Tests 
With TSO service:
```shell
mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
|                                0 |
+----------------------------------+
1 row in set (0.00 sec)
mysql> set global tidb_enable_tso_follower_proxy = 1;
ERROR 1105 (HY000): [pd] tso follower proxy is only supported in PD service mode
mysql> select @@tidb_enable_tso_follower_proxy;
+----------------------------------+
| @@tidb_enable_tso_follower_proxy |
+----------------------------------+
| …
```
=> variable: fix setting tidb_enable_tso_follower_proxy with TSO service

pkg/executor/aggfuncs/BUILD.bazel, pkg/executor/aggfuncs/aggfuncs.go, pkg/executor/aggfuncs/builder.go, pkg/executor/aggfuncs/func_avg.go, pkg/executor/aggfuncs/func_bitfuncs.go, pkg/executor/aggfuncs/func_count.go, pkg/executor/aggfuncs/func_count_distinct.go, pkg/executor/aggfuncs/func_cume_dist.go, pkg/executor/aggfuncs/func_first_row.go, pkg/executor/aggfuncs/func_group_concat.go, pkg/executor/aggfuncs/func_json_arrayagg.go, pkg/executor/aggfuncs/func_json_objectagg.go, pkg/executor/aggfuncs/func_lead_lag.go, pkg/executor/aggfuncs/func_max_min.go, pkg/executor/aggfuncs/func_ntile.go, pkg/executor/aggfuncs/func_percent_rank.go, pkg/executor/aggfuncs/func_percentile.go, pkg/executor/aggfuncs/func_rank.go, pkg/executor/aggfuncs/func_stddevpop.go, pkg/executor/aggfuncs/func_stddevsamp.go, pkg/executor/aggfuncs/func_sum.go, pkg/executor/aggfuncs/func_value.go, pkg/executor/aggfuncs/func_varpop.go, pkg/executor/aggfuncs/func_varsamp.go, pkg/executor/aggfuncs/row_number.go, pkg/executor/aggregate/agg_hash_base_worker.go, pkg/executor/aggregate/agg_hash_executor.go
Issue Number: close #51223
This PR introduces standalone contexts for aggregation functions in `pkg/executor/aggfuncs`. We introduce below contexts:
- `AggFuncUpdateContext` is used when updating the partial result of agg functions.
- `AggFuncBuildContext` is used when building agg functions.
We also removed the `ctx` field in `baseHashAggWorker` because it seems not used by anynone.
Tests 
> Only type replace, not logic change
Side effects
Documentation
```release-note
None
```
=> executor: introduce `AggFuncUpdateContext` and `AggFuncBuildContext` to evaluate and build aggeration functions

br/pkg/aws/ebs.go
Issue Number: close #50942 
Avoid recursively copy tagging from snapshots when creating volumes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ebs br: handle tag limit exceed issue

br/pkg/lightning/backend/local/local.go, br/pkg/lightning/common/retry.go, br/pkg/lightning/tikv/tikv.go
Issue Number: close #50998 close #43636
be aware of TiKV's new error `DiskSpaceNotEnough`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: don't check TiKV free space after v8.0.0

pkg/statistics/row_sampler.go
Issue Number: close https://github.com/pingcap/tidb/issues/51246
baseCollector.FromProto will copy the bytes in the ```tipb.RowSampleCollector```. it is unnecessary. After FromProto, it will not be used again.
BTW Someone said the protobuf have a problem to make statistics wrong if we remove this copy. so let us check it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: remove unnecessary copy in the baseCollector

pkg/ddl/backfilling_dist_executor.go, pkg/ddl/backfilling_import_cloud.go, pkg/ddl/backfilling_merge_sort.go, pkg/ddl/backfilling_read_index.go, pkg/ddl/index.go, pkg/ddl/ingest/backend.go, pkg/ddl/ingest/backend_mgr.go, pkg/ddl/ingest/config.go, pkg/ddl/ingest/mock.go
Tests 
> pass existing tests
Side effects
Documentation
```release-note
None
```
=> ddl: move backend register from backfillDistExecutor to its StepExecutor

pkg/session/bootstrap.go
Issue Number: close #51220
`create database sys` and internal tables will make smooth upgrade failed, because the old version of TiDB doesn't think `sys` is a system table. This PR will avoid running these DDL for upgrade, so that the users will have to run these DDL manually if they need the view provided by `sys`.
Tests 
> 
Run a TiDB cluster with 2 TiDB: `tiup playground v7.5.0 --db 2 --tiflash 0`
Start the smooth upgrade: ` curl -X POST http://127.0.0.1:10081/upgrade/start`
Kill the first TiDB whose port is 4000: `kill .....`. Record the arguments.
Start the TiDB compiled with this patch: `./bin/tidb-server -P 4000 --store=tikv --host=127.0.0.1 --status=10080 --path=127.0.0.1:2379 …
=> bootstrap: don't create sys schema for upgrade

DEPS.bzl, go.mod, go.sum
Issue Number: ref #50765
The latest version should no longer panic when checking code targeting Go 1.22.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: upgrade staticcheck

br/pkg/conn/conn.go
Issue Number: close #51296
after the address changed from `string` to `[]string`, printf with `%s` generates invalid `[addr]` content
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: fix printf can tolerate type change

pkg/planner/core/indexmerge_path_test.go
Issue Number: ref #45798
Problem Summary: planner: add more test cases for plan cache with generated columns
planner: add more test cases for plan cache with generated columns
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: add more test cases for plan cache with generated columns

br/pkg/streamhelper/BUILD.bazel, br/pkg/streamhelper/advancer.go, br/pkg/streamhelper/advancer_test.go, br/pkg/streamhelper/basic_lib_for_test.go, br/pkg/utils/worker.go
close pingcap/tidb#50839
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br/streamhelper: fix panic while removing task (#50869)

pkg/disttask/framework/taskexecutor/BUILD.bazel, pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/taskexecutor/manager_test.go
Issue Number: ref #49008 
Use handle.RunWithRetry
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: refine manager retry

pkg/session/bootstrap.go
Issue Number: close #51269
Aggregate the unused index across multiple nodes. The original SQL didn't aggregate them 🤦 , so an index will appear multiple times. A silly bug.
Tests 
> 
Create a cluster with two tidb nodes
```
tiup playground --db 2 --db.binpath ./bin/tidb-server
```
Run the following SQLs
```
create table t (id_1 int, id_2 int, unique key idx_1(id_1), unique key idx_2(id_2));
insert into t with recursive seq as (select 1 as id union all select id + 1 from seq where seq.id < 100) select id as id_1, id as id_2 from seq;
analyze table t;
select * from t use index(idx_1) where id_1 > 60;
select * from sys.schema_unused_indexes;
```
It'll give:
```
mysql> select * from sys.schema_unused_indexes; …
```
=> bootstrap: aggregate the unused index across multiple nodes

pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel, pkg/statistics/handle/autoanalyze/refresher/refresher.go, pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
There are two versions here:
1. Version: The last stats update version(count and modify_count).
2. LastUpdateVersion: The last update time of the histogram. We can take it as the last analysis time.
We should use the second one here instead of the first one.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: use correct last update version

pkg/disttask/framework/integrationtests/framework_err_handling_test.go, pkg/disttask/framework/scheduler/scheduler.go, pkg/disttask/framework/taskexecutor/manager.go, pkg/disttask/framework/testutil/scheduler_util.go, tests/realtikvtest/importintotest4/global_sort_test.go
Previously when planErr and not retryable, the state transition is as follow:
1. pending->failed
2. pending->running->failed
We change the state transition to:
1. pending->reverting->reverted
2. pending->running->reverting->reverted
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: refine planErr state transition

pkg/executor/adapter.go
Issue Number: close #50920
As https://github.com/pingcap/tidb/issues/50920#issuecomment-1963492417 described, we now have two choices to fix it:
1. move the time-cost work of `CheckSum` from `Open` to `Next`.
2. make `CheckSum` processInfo updated earlier.
This pr chooses the second one, there seems no bad effects we move `SetProcessInfo` before `openExecutor` is called.
And this can alse fix similar problems like `CheckSum` who's time-cost work is placed in `Open` function.
Tests 
> 
Manual test as follow steps:
1. update code like this:
```
$ git diff
diff --git a/pkg/executor/checksum.go b/pkg/executor/checksum.go
index bca0af9..b3b31e3 100644
--- a/pkg/executor/checksum.go
+++ b/pkg/executor/checksum.go
@@ -17,6 …
```
=> executor: make `checksum` block gc

.github/licenserc.yml
Issue Number: close #51348
Since the files on `pkg/extension/enterprise` are not open source, we don't need to check the license of these files.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> license: ignore checking license on `pkg/extension/enterprise/`

pkg/ddl/ingest/config.go
Issue Number: ref #51272
Tests 
> 
run 3 ADD INDEX tests,
```
CREATE TABLE `sbtest1` (
`id` int(11) NOT NULL,
`k` int(11) NOT NULL DEFAULT '0',
`c` char(120) NOT NULL DEFAULT '',
`pad` char(60) NOT NULL DEFAULT '',
PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
KEY `k_1` (`k`),
KEY `new_16` (`k`,`c`,`pad`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```
1) before this PR 2) with this PR, with default 4 concurrency from tidb_ddl_reorg_worker_cnt 3) with this PR, with 16 concurrency which is the same value as before . Surprisingly the time costs and CPU does not change a lot.
ADD INDEX time cost
```
CREATE_TIME: 2024-02-27 02:29:25
START_TIME: 2024-02-27 02:29:25
END_TIME: 2024-02-27 03:20:53 …
```
=> ddl: let tidb_ddl_reorg_worker_cnt controls fast DDL local backend concurrency

pkg/bindinfo/binding_cache.go, pkg/bindinfo/binding_cache_test.go, pkg/bindinfo/global_handle.go, pkg/bindinfo/session_handle.go
Problem Summary: planner: introduce a interface for binding cache
NO LOGICAL CHANGE, JUST ADD A INTERFACE.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: introduce a interface for binding cache

pkg/planner/core/physical_plan_test.go, pkg/planner/core/tiflash_selection_late_materialization.go
Issue Number: close #51289
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix flaky test TestPhysicalTableScanExtractCorrelatedCols

pkg/util/ranger/detacher.go, pkg/util/ranger/ranger.go, tests/integrationtest/r/planner/core/casetest/partition/integration_partition.result, tests/integrationtest/t/planner/core/casetest/partition/integration_partition.test
Issue Number: close #51316
As said in 3. of #48522, `convertStringFTToBinaryCollate` should be used only for the new `convertToSortKey` case.
But in the code, among the 4 places `convertStringFTToBinaryCollate` is called, 2 of them missed this check, and resulted in values with wrong types in the result `Range`.
Currently `convertToSortKey = false` is only used for partition pruning.
As the title says, add check for `convertToSortKey` when using `convertStringFTToBinaryCollate`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> util/ranger: do not convert to binary collate for string values when `convertToSortKey` is `false`

Makefile, tools/check/go-compile-without-link.sh, tools/check/ut.go
Issue Number: ref #31880 #30822
Maybe we can 'make ut X=build' a little bit faster!
```
go clean -cache
time make ut X='build'
```
After vs Before:
```
real    11m18.792s
user    106m32.408s
sys     8m57.255s
real    10m14.162s
user    98m40.710s
sys     8m16.094s
=====
real    16m2.547s
user    93m58.212s
sys     7m51.199s
real    15m37.476s
user    91m56.299s
sys     8m11.068s
```
Behind the scene, it's a technique called 'staged build'.
If we build all the test binaries **parallelly**, the go compiler will detect that much of the pacakge cache are not available, so it would build package cache several times. For example, building `pkg/executor` and `pkg/session` parallelly, they all depends on a lot of other small packages, since those packages do not exist at the …
=> tools/check: adpot staged build to make ut a little bit faster

pkg/ddl/partition.go, pkg/ddl/tests/partition/BUILD.bazel, pkg/ddl/tests/partition/db_partition_test.go
Issue Number: close #47167
Tests 
>   
Side effects
Documentation
```release-note
None
```
=> partition: fix exchange partition validition check for null value

pkg/ddl/restart_test.go, pkg/ddl/schema_test.go, pkg/ddl/stat.go, pkg/ddl/stat_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/51376
In https://docs.pingcap.com/tidb/stable/sql-statement-show-status#examples the `show status` results only the following fields:
```
mysql> SHOW SESSION STATUS;
+-------------------------------+--------------------------------------+
| Variable_name                 | Value                                |
+-------------------------------+--------------------------------------+
| Ssl_cipher                    |                                      |
| Ssl_cipher_list               |                                      |
| Ssl_server_not_after          |                                      |
| Ssl_server_not_before         |                                      |
| Ssl_verify_mode               | 0 …
```
=> ddl: cleaning up `show status` unused fields

pkg/executor/aggregate/agg_hash_executor.go, pkg/executor/test/aggregate/BUILD.bazel, pkg/executor/test/aggregate/aggregate_test.go, pkg/session/session.go
Issue Number: close #50849
The standard `errors.Join(err1, err2)` turn the error into another kind, losing the error stack information.
Avoid using this API.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> session,executor: get back the error stack information from a regression

pkg/executor/executor.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/variable.go
Issue Number: close #51344
After #45893. The public method `SessionVars.SetStmtVar` is removed left private field `stmtVars` not used by anyone. We can remove it for code clear
Just remove `setStmtVar` because it is useless
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: remove useless `stmtVars` method in `SessionVars`

pkg/executor/parallel_apply_test.go, pkg/planner/core/physical_plans.go
Issue Number: close #51372
1. Parallel apply needs to copy innerPlan of original PhysicalApply
2. The Clone method of `PhysicalIndexLookupReader` didn't copy `CommonHandleCols`, which cause the cloned innerPlan got wrong CommonHandle info, which cause IndexLookup return wrong result
Tests 
> 
Side effects
Documentation
```release-note
fix parallel apply got wrong result
```
=> *: fix parallel apply wrong result

pkg/bindinfo/binding_cache.go, pkg/bindinfo/binding_cache_test.go, pkg/bindinfo/global_handle.go
Problem Summary: planner: introduce a new fuzzy binding cache
Mainly it's refactoring. Introduce a new cache between the BindingHandler and the BindingCache, where we can implement some advanced binding features like 'fuzzy matching', 'auto binding loading if cache miss', etc...
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: introduce a new fuzzy binding cache

br/cmd/br/stream.go
Issue Number: close #50927 
The command was set `hidden`, now it has been set visible.
Tests 
> 
Side effects
Documentation
```release-note
Now the candidate command "log" in br is visible in help.
```
=> br: make log command visible in cli

pkg/parser/mysql/charset.go, pkg/server/handler/tikvhandler/tikv_handler.go
Issue Number: close https://github.com/pingcap/tidb/issues/51408
* Using `WriteError` and `WriteData` instead of `writeError` and `writeData`.
* Remove two useless constants.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser, server: unify writeData and writeError functions

br/pkg/lightning/checkpoints/checkpoints.go, br/tests/lightning_checkpoint/run.sh, br/tests/lightning_checkpoint_chunks/run.sh
Issue Number: close #50711
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: raise field length of checkpoint

pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel, pkg/statistics/handle/autoanalyze/refresher/refresher.go, pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
There are two configurations for the auto-analyze feature that are very easy to misunderstand.
1. `tidb_enable_auto_analyze`: Determines whether TiDB automatically updates table statistics as a background operation.
2. `tidb_auto_analyze_ratio`: This variable is used to set the threshold when TiDB automatically executes [ANALYZE TABLE](https://docs.pingcap.com/tidb/stable/sql-statement-analyze-table) in a background thread to update table statistics. **It is possible for the value to be 0, which means auto analysis based on the change percentage will be turned off. However, new tables and indexes will still be analyzed.**
So in the new implementation, I forgot it.
In this PR, I added a check for auto-analyze …
=> statistics: do not analyze table when auto analyze ratio is 0

pkg/executor/adapter.go, pkg/expression/builtin_info.go, pkg/planner/core/casetest/planstats/plan_stats_test.go, pkg/planner/core/plan_stats.go, pkg/session/test/variable/variable_test.go, pkg/session/test/vars/vars_test.go, pkg/sessionctx/variable/session.go
Please create an issue first to describe the problem.
There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".
For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.
-->
Issue Number: close #50914, close #50872
1. provide a Function `GetMaxExecutionTime` for `SessionVars`.
2. Fix two potential bug, caused by not properly used `MaxExecutionTime`, one about `plan_stats`，the other `expression/build_in`.
3. Fix a bug related with `tidb_stats_load_sync_wait`
4. unify code for `GetMaxExecutionTime`.
Tests 
> 
Side effects
Documentation …
=> variable: unifiy MaxExecuteTime usage and fix some problem

pkg/infoschema/infoschema_test.go
Add cases for modify table.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> infoschema: more tests for applyDiff

pkg/executor/infoschema_reader_test.go, pkg/infoschema/tables.go
Issue Number: close #51409.
Add TSO and scheduling server to table information_schema.cluster_info.
Tests 
After this PR:
```
mysql> select * from information_schema.cluster_info;
+------------+------------------+------------------+-----------------------------------+------------------------------------------+---------------------+---------------+-----------+
| TYPE       | INSTANCE         | STATUS_ADDRESS   | VERSION                           | GIT_HASH                                 | START_TIME          | UPTIME        | SERVER_ID |
+------------+------------------+------------------+-----------------------------------+------------------------------------------+---------------------+---------------+-----------+
| tidb       | 10.2.8.101:36059 | 10.2.8.101:36983 | …
```
=> executor, infoschema: add microservice into table cluster_info

tests/realtikvtest/brietest/backup_restore_test.go
Issue Number: ref #48301 
the unit test has a heavy workload
reduce the number of tables to be created.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: reduce workload in unit test

tests/realtikvtest/testkit.go
Issue Number: close #51212
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: ignore some routines from grpc that's not waited on close

pkg/executor/memtable_reader.go, pkg/executor/memtable_reader_test.go
Issue Number: close #51495
```
mysql> select * from information_schema.cluster_config;
+------------+------------------+-------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TYPE       | INSTANCE         | KEY                                                                                 | VALUE …
```
=> executor: add microservice into table cluster_config

pkg/ddl/backfilling_dist_scheduler.go, pkg/ddl/backfilling_dist_scheduler_test.go, pkg/disttask/framework/integrationtests/bench_test.go, pkg/disttask/framework/integrationtests/framework_pause_and_resume_test.go, pkg/disttask/framework/integrationtests/resource_control_test.go, pkg/disttask/framework/mock/scheduler_mock.go, pkg/disttask/framework/scheduler/BUILD.bazel, pkg/disttask/framework/scheduler/interface.go, pkg/disttask/framework/scheduler/mock/scheduler_mock.go, pkg/disttask/framework/scheduler/scheduler.go, pkg/disttask/framework/scheduler/scheduler_nokit_test.go, pkg/disttask/framework/scheduler/scheduler_test.go, pkg/disttask/framework/testutil/disttest_util.go, pkg/disttask/framework/testutil/scheduler_util.go, pkg/disttask/importinto/proto.go, pkg/disttask/importinto/scheduler.go, pkg/disttask/importinto/scheduler_test.go, pkg/disttask/importinto/scheduler_testkit_test.go
- after #51241, we only refresh task base on scheduler loop, but task-meta might be changed by other scheduler in network-partition cases. to avoid this case, we maintain state/step change in memory, refresh whole task info when we detected state/step is changed by others, either by other scheduler or by explicit state change operation such as cancel or pause.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> disttask: refresh whole task info when state/step changed

pkg/executor/builder.go, pkg/executor/infoschema_reader.go
Issue Number: close https://github.com/pingcap/tidb/issues/51456
related #51260
Add memory tracker for memtableRetriever
Tests 
Test Case:  50k tables,  each table contains 10 columns.
```
tidb> desc analyze select * from INFORMATION_SCHEMA.tables;
+----------------+----------+---------+------+---------------+-------------------------------------+---------------+---------+------+
| id             | estRows  | actRows | task | access object | execution info                      | operator info | memory  | disk |
+----------------+----------+---------+------+---------------+-------------------------------------+---------------+---------+------+
| MemTableScan_4 | 10000.00 | 50816   | root | table:TABLES  | time:115.1ms, loops:51, RU:0.000000 |               | 91.3 MB | N/A …
```
=> executor: add memory tracker for memtableRetriever

br/pkg/lightning/backend/external/merge.go
Issue Number: close #51508
Tests 
> simple
Side effects
Documentation
```release-note
None
```
=> global sort: fix forget to close writer when reader has error

pkg/server/internal/testserverclient/server_client.go, pkg/server/tests/commontest/BUILD.bazel, pkg/server/tests/commontest/tidb_test.go, pkg/session/session.go
Issue Number: close #51387
The session variables are not loaded before parsing the SQL statements, which makes SQLMode incorrect.
Load session variables before parsing the statements.
Tests 
> 
```release-note
Fix the issue that SQLMode doesn't have effect on the first statement in a session.
```
=> session: load variables before parsing SQL

pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel, pkg/statistics/handle/autoanalyze/priorityqueue/job.go, pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go, pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel, pkg/statistics/handle/autoanalyze/refresher/refresher.go, pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
In this PR, we solved two problems:
1. We shouldn't create pseudo stats during auto-analyze check processing. We only need the real row count of tables, so no need for pseudo stats. This would help us to reduce memory consumption and alleviate GC pressure.
2. We should analyze static partitions one by one instead of analyzing the entry global table again and again.
So I made the following changes:
1. I changed the refresher to use `GetPartitionStatsForAutoAnalyze` and `GetTableStatsForAutoAnalyze ` to avoid creating the pseudo stats.
2. I added a new type of job for the static partition. It will execute the analysis jobs in these ways:
a. `analyze table %n.%n partition %n`
b. `analyze table %n.%n partition %n …
=> statistics: Do not create pseudo statistics for the auto-analysis check process

br/cmd/br/main.go, br/pkg/backup/prepare_snap/prepare.go, br/pkg/task/operator/cmd.go, br/pkg/utils/misc.go
Issue Number: close #51370 
It is hard to debug what happens when the init pod get timed out.
This PR will print all gorouintes to `stdout` once the `prepare-for-snapshot-backup` command exits before finishing the full prepare stage.
Tests 
When we are not yet finished:
When we have finished prepare stage:
> 
Side effects
Documentation
```release-note
None
```
=> operator: print callstack when exiting before preparing done

pkg/ttl/ttlworker/BUILD.bazel, pkg/ttl/ttlworker/job_manager.go, pkg/ttl/ttlworker/job_manager_integration_test.go
Issue Number: close #51540
1. Finish the job when the table is no longer a TTL table (or has been dropped).
2. GC will also remove `tidb_ttl_table_status` when the table is no longer a TTL table (or has been dropped).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ttl: remove TTL job when the table has been dropped

pkg/sessionctx/variable/tidb_vars.go, pkg/statistics/handle/autoanalyze/autoanalyze.go, pkg/statistics/handle/autoanalyze/exec/BUILD.bazel, pkg/statistics/handle/autoanalyze/exec/exec.go, pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel, pkg/statistics/handle/autoanalyze/refresher/refresher.go, pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
I have enabled the auto-analysis priority queue by default. Also from this PR, the priority queue starts respecting the auto-analyze time window.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: enable the auto-analysis priority queue

pkg/domain/domain.go
Issue Number: close #51581
If init-stats panics, then the load stats of this instance will all be broken.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> domain: avoid panic in the init stats breaking the loadStatsWorker

pkg/ddl/ddl.go, pkg/ddl/ddl_running_jobs.go, pkg/ddl/ddl_running_jobs_test.go
Issue Number: close #50061
There is a gap between `runningJobs.remove()` and next `runningJobs.add()`. If `getJob()` is invoked during this gap, DDL worker may execute the second `create table` job first.
This PR distinguishes the concept between "processing" jobs and "unfinished" jobs:
- Processing jobs: activatly running by a DDL worker.
- Unfinished jobs: the jobs whose state is NOT `synced`, `done`, or `rollback done`.
For `checkRunnable()`, we should use "unfinished jobs" to determine the dependency.
Tests 
> 
Side effects
Documentation …
=> ddl: fix unstable test TestCreateDropCreateTable

pkg/server/server.go, pkg/server/server_test.go
Issue Number: close #51596
Tests 
> 
Side effects
Documentation
```release-note
Fix that when the server is not started, it should not default to a healthy state
```
=> server: fix incorrect setting of health status

pkg/server/BUILD.bazel, pkg/server/conn.go, pkg/session/BUILD.bazel, pkg/session/nontransactional.go, pkg/session/session.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/util/redact/BUILD.bazel, pkg/util/redact/redact.go, pkg/util/redact/redact_test.go
Issue Number: close #51557
Problem Summary: add `redact.Mode` and `sessVars.EnableRedactNew`. Use them to desensitive logs.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> session: migrate to the new redact function

errors.toml, pkg/ddl/ddl_api.go, pkg/ddl/partition.go, pkg/ddl/tests/partition/db_partition_test.go, pkg/util/dbterror/ddl_terror.go, tests/integrationtest/r/ddl/db_partition.result, tests/integrationtest/r/ddl/partition.result, tests/integrationtest/r/executor/show.result, tests/integrationtest/r/planner/core/integration_partition.result, tests/integrationtest/t/ddl/partition.test, tests/integrationtest/t/planner/core/integration_partition.test
Issue Number: close #36433, close #49251
The string literal in the partition clause is stored as a formated string literal. For example, the `'你好'` will be kept as `'你好'` in the schema, and the collation information is lost. However, when running the `getRangeLocateExprs`, the expression is constructed with the DDL session, which always use `utf8mb4` collation.
When inserting the row, the string (after converted to the collation corresponding to the column) will be compared with the `utf8mb4` literal string, which may cause unexpected behavior. In the issue #36433, the insert value `你好` is converted to binary encoding GBK `\xc4\xe3\xba\xc3`, and compare it with the utf8 string `'你好'` through binary collation directly, then former is smaller than the later one.
MySQL …
=> ddl: fix partition definition for literal with non-utf8 charsets + binary column | tidb-test=pr/2262

pkg/sessionctx/stmtctx/BUILD.bazel, pkg/sessionctx/stmtctx/stmtctx.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/session_test.go, pkg/util/execdetails/execdetails.go, pkg/util/stmtsummary/statement_summary.go, pkg/util/stmtsummary/statement_summary_test.go, pkg/util/stmtsummary/v2/record.go
Issue Number: close #51516
Move some methods only related to `execdetails` from `stmtctx` to `execdetails` pkg.
Tests 
> - Should be covered by existing tests. All codes are just copied around.
> 
```release-note
None
```
=> stmtctx, execdetails: migrate execdetails inside the stmtctx and related methods to execdetails

pkg/disttask/importinto/encode_and_sort_operator.go, pkg/disttask/importinto/encode_and_sort_operator_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> importinto: fix incorrect index kv group count when table have common handle

build/nogo_config.json, dumpling/export/sql_type.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> fix(lint): dumpling/export/sql_type.go

cmd/tidb-server/BUILD.bazel, cmd/tidb-server/main.go, pkg/metrics/alertmanager/tidb.rules.yml, pkg/metrics/grafana/overview.json, pkg/metrics/grafana/tidb.json, pkg/metrics/grafana/tidb_runtime.json, pkg/metrics/grafana/tidb_summary.json, pkg/metrics/metrics.go, pkg/metrics/server.go, pkg/util/cgmon/BUILD.bazel, pkg/util/cgmon/cgmon.go, pkg/util/cgroup/cgroup.go, pkg/util/cgroup/cgroup_cpu.go, pkg/util/cgroup/cgroup_cpu_linux.go, pkg/util/cgroup/cgroup_cpu_unsupport.go, pkg/util/cgroup/cgroup_mock_test.go
There isn't yet a mechanism to monitor the cgroup cpu/memory limit and do corresponding alerting.
Issue Number: close #50467
Cgmon pkg was added to periodically watch the cgroup cpu/memory limit setting changes. GOMAXPROCS will be set to the minor one between cgroup limit and maxprocs. Metrics will be set accordingly and displayed on Grafana. New alerting rules were also added for the cpu/memory usage ratio relative to the limits.
Tests 
Grafana display and alerting trigger
CPU/Memory Quota will be displayed with the usage graphs as another legend like below (playground on Mac m1, no real data):
> 
Side effects
Documentation …
=> util: Cgroup monitoring and alerting

pkg/expression/BUILD.bazel, pkg/expression/builtin.go, pkg/expression/builtin_info.go, pkg/expression/builtin_info_vec.go, pkg/expression/context.go, pkg/expression/context/BUILD.bazel, pkg/expression/context/context.go, pkg/expression/context/optional.go, pkg/expression/context/optional_test.go, pkg/expression/contextimpl/BUILD.bazel, pkg/expression/contextimpl/sessionctx.go, pkg/expression/contextimpl/sessionctx_test.go, pkg/expression/contextopt/BUILD.bazel, pkg/expression/contextopt/current_user.go, pkg/expression/contextopt/optional.go, pkg/expression/contextopt/optional_test.go, pkg/expression/distsql_builtin.go
Issue Number: close #51477
copied from issue:
The `EvalContext` has many fields to provide but not all of them are required in every scene. So it's better to classify these fields into two categories:
1. **Basic properties** such as `type.Context`, `errctx.Context`, `SQLMode`, etc... These properties are used by functions widely. For example, `errctx.Context` used by most functions to handle some errors. The basic properties are also simple, they should be easy to clone and mock. The `EvalContext` MUST provide basic properties. 
2. **Optional properties**, as its name, is "optional". In some scenes such as [TiDB Lightning](https://github.com/pingcap/br/tree/master/pkg/lightning), it only requires some of the properties, so these properties are provided on demand. Optional …
=> expression: introduce optional properties for `EvalContext`

pkg/ddl/db_integration_test.go, pkg/ddl/ddl_api.go, tests/integrationtest/r/ddl/default_as_expression.result, tests/integrationtest/t/ddl/default_as_expression.test
Issue Number: close https://github.com/pingcap/tidb/issues/51554, close https://github.com/pingcap/tidb/issues/51570
* Add expression default values feature relevant tests for "modify column", "set/drop default" and "add index"
* When the default value is an expression, changing it to a constant by "set default" can be problematic 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl, tests: add expression default values feature relevant tests for some DDLs and fix a related bug

pkg/ddl/ddl_api.go, tests/integrationtest/r/ddl/default_as_expression.result, tests/integrationtest/t/ddl/default_as_expression.test
Issue Number: close https://github.com/pingcap/tidb/issues/51587
* fix the problem that table creation with auto_increment and default expressions
* add tests related to auto_increment and generate columns about default value expressions
* rename `ProcessColumnOptions` to `ProcessModifyColumnOptions`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl, test: fix the problem that table creation with auto_increment and default expressions

pkg/bindinfo/binding.go, pkg/bindinfo/global_handle.go, pkg/bindinfo/global_handle_test.go, pkg/bindinfo/session_handle.go, pkg/bindinfo/session_handle_test.go, pkg/metrics/bindinfo.go, pkg/metrics/metrics.go
Problem Summary: planner: remove unused binding metrics
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: remove unused binding metrics

executor/index_merge_reader.go, store/copr/BUILD.bazel, store/copr/batch_coprocessor.go, store/copr/coprocessor_test.go, store/copr/key_ranges.go, store/copr/region_cache.go
This is a cherry-pick of https://github.com/pingcap/tidb/pull/51333
Issue Number: close #51326
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: load region info from pd in batch(#51333)

pkg/executor/explainfor_test.go, pkg/planner/core/plan_cache_test.go, pkg/planner/core/plan_cacheable_checker.go, tests/integrationtest/r/planner/core/indexmerge_path.result
Issue Number: close #45798
Problem Summary: planner: allow the optimizer to cache query plans accessing generated columns by default
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: allow the optimizer to cache query plans accessing generated columns by default

pkg/infoschema/test/clustertablestest/tables_test.go, pkg/planner/core/planbuilder.go, pkg/util/stmtsummary/v2/tests/table_test.go, tests/integrationtest/r/privilege/privileges.result, tests/integrationtest/t/privilege/privileges.test
Issue Number: close #51366
Tests 
> 
Side effects
Documentation
```release-note
add super privilege checks for some admin commands
```
=> *: add super privilege check for some admin commands

executor/index_merge_reader.go, executor/index_merge_reader_test.go, testkit/testkit.go
cherry-pick #45284
close pingcap/tidb#45279
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix query hang in IndexMerge Executor when it's killed (#45284) (#45345)

pkg/executor/importer/import.go, pkg/executor/importer/import_test.go, pkg/executor/test/loadremotetest/multi_file_test.go, pkg/util/stringutil/string_util.go, pkg/util/stringutil/string_util_test.go
Tests 
> 
Side effects
Documentation
```release-note
IMPORT INTO now can use `[]` of glob pattern matching to match multiple files
```
=> import into: enable `[]` glob matching

pkg/expression/builtin_cast.go, pkg/expression/builtin_cast_vec.go, tests/integrationtest/r/expression/json.result, tests/integrationtest/t/expression/json.test
Issue Number: close #51547
If the `flen` of a binary string is unspecified, don't resize the target json opaque.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> json: don't resize slice to get extra zero when the length is unspecified

br/pkg/restore/batcher.go, br/pkg/restore/batcher_test.go, br/pkg/restore/client.go, br/pkg/restore/merge.go, br/pkg/restore/merge_test.go, br/pkg/restore/pipeline_items.go, br/pkg/restore/range.go, br/pkg/restore/range_test.go, br/pkg/restore/split.go, br/pkg/restore/split_test.go, br/pkg/restore/util.go, br/pkg/rtree/rtree.go, br/pkg/task/restore_raw.go, br/pkg/task/restore_txn.go
Issue Number: close https://github.com/pingcap/tidb/issues/51685
1. when handing files of drainRange result. restore will check the match rewrite rules for each file. this time could be saved when flatten the rewrite rules with map. 
1. speed up handling millions of rewrite rules with new split approach by move rewrite ranges forward.
2. reduce the memory allocation of files object copy.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> restore: shift rewrite ranges before split ranges

pkg/ddl/ddl_api.go, tests/integrationtest/r/ddl/default_as_expression.result
Issue Number: close https://github.com/pingcap/tidb/issues/51703
Now we support `REPLACE` as the default value expression, but don't support `REPLACE('xdfj-jfj', '-', ''))`.
So tiny update the error message.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl, tests: make the error message of the default value expression more appropriate.

pkg/executor/temporary_table_test.go
In TemporaryTableNoNetwork unit test, there is a failpoint assuming that temporary table related operations would not cause network visiting. That's true for infoschema v1.
When using infoschema v2, the API like `SchemaTables` need to visit network to list tables, and also API like `TableByID` may miss table cache and requires reloading ... 
So TemporaryTableNoNetwork can not work under infoschema v2, skip those tests.
Tests 
```
index d655384bfb..7e0bef66e7 100644
@@ -1482,7 +1482,7 @@ const (
DefEnableParallelSort …
```
=> executor: skip TemporaryTableNoNetwork unit test under infoschema v2

pkg/util/fastrand/BUILD.bazel, pkg/util/fastrand/random.go, pkg/util/fastrand/runtime.go, pkg/util/fastrand/runtime_1.22.go
Issue Number: ref #50765
Fix: update calls to `runtime.fastrand` to use `cheaprand` for compatibility with Go 1.22
In Golang 1.22, the `runtime.fastrand` method was renamed to `cheaprand`. This commit updates all occurrences of `runtime.fastrand` in the project to use the new `cheaprand` method to maintain compatibility with the latest Golang version and address performance concerns.
Refer: https://gist.github.com/Aoang/3dc06f127f3f54507b7e06b7b6550c28
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> pkg: fix update calls to `runtime.fastrand` to use `cheaprand` for compatibility with Go 1.22

pkg/executor/BUILD.bazel, pkg/executor/adapter.go, pkg/executor/test/admintest/admin_test.go, pkg/parser/digester.go, pkg/parser/go.mod, pkg/parser/go.sum, pkg/server/conn.go, pkg/server/conn_stmt.go, pkg/session/nontransactional.go, pkg/session/session.go, pkg/session/txnmanager.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/util/logutil/consistency/BUILD.bazel, pkg/util/logutil/consistency/reporter.go
Issue Number: close #51717 
1. remove `sessvars.EnableRedactLog` and rename `sessvars.EnableRedactNew` to `sessvars.EnableRedactLog`.
2. replace all `"ON"`, `"OFF"`, `"MARKER"` to `errors.RedactLogXXX`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: remove old enableredactlog

br/pkg/backup/prepare_snap/BUILD.bazel, br/pkg/backup/prepare_snap/prepare.go, br/pkg/backup/prepare_snap/prepare_test.go, br/pkg/backup/prepare_snap/stream.go
Issue Number: close #51448 
Now if we cannot connect to a TiKV, it will block at creating connection.
But, in this scenario, some of TiKVs' admin commands are paused. That will impact the TP workload more.
After this PR, we won't pause the admin commands before connections to all TiKV nodes established.
Tests 
> 
```release-note
None
```
=> prepare_snap: establish connection to all stores before pausing admin

pkg/planner/core/point_get_plan.go, pkg/session/session.go, tests/realtikvtest/pipelineddmltest/BUILD.bazel, tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Produce warnings when we have to fallback to standard mode if `tidb_dml_type=bulk`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> txn: produce warnings when fallback from bulk mode

pkg/util/chunk/BUILD.bazel, pkg/util/chunk/chunk_test.go, pkg/util/chunk/mutrow_test.go, pkg/util/codec/BUILD.bazel, pkg/util/codec/codec_test.go, pkg/util/codec/collation_test.go
Issue Number: close #51743
Replace the `stmtctx` with `*time.Location` or `types.Context`.
Tests 
> Only tests are modified
Side effects
Documentation
```release-note
None
```
=> pkg/util/chunk, pkg/util/codec: remove redundant stmtctx dependency from tests

pkg/executor/builder.go
Issue Number: close #51749
the old control code is not deleted so it read the concurrency from wrong variable.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: set right concurrency when to auto-analyze

pkg/infoschema/test/clustertablestest/cluster_tables_test.go
Issue Number: close #51673 
See #51673 for the root cause.
We solve it by setting the timezone `UTC+8` explicitly in the tests, `UTC+8` aligns with the timezone specified in the slow query log used by this test case.
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```
=> infoschema: fix `TestSlowQueryOOM` in some timezones

pkg/infoschema/test/clustertablestest/cluster_tables_test.go, pkg/planner/core/planbuilder.go, pkg/util/hint/hint_processor.go
Problem Summary: planner: output a warning instead of returning an error when creating fast binding on a incomplete hint
planner: output a warning instead of returning an error when creating fast binding on a incomplete hint
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: output a warning instead of returning an error when creating fast binding on a incomplete hint

pkg/ddl/backfilling_dist_executor.go, pkg/ddl/backfilling_dist_scheduler.go, pkg/disttask/framework/scheduler/scheduler.go
Issue Number: close #51786
https://github.com/pingcap/tidb/blob/f46ccb3ec15689b426e230f28dfda5f3e25644d5/pkg/disttask/framework/scheduler/scheduler.go#L419-L462
There are three kinds of `task` in total. Assuming task1 is `scheduler.task`, task2 is the copied one in `switch2NextStep`, and task3 is in table.
1. `OnNextSubtaskBatch` modified the meta of task2 (useMergeSort = true).
2. `scheduleSubTask` load task1 and update it to the table (useMergeSort = false).
3. `s.task.Store (& task)` resets task1 to task2.
The result is that the useMergeSort of task3 and task1 are inconsistent.
1. Pass the copied task to `scheduleSubTask` to make it consistent.
2. Remove `UseMergeSort` and make `OnNextSubtaskBatch` do not modify task.
Tests 
> - [ ] I checked and no code files have …
=> disttask: make sure task meta consistent between scheduler and table

pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go, pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job_test.go, pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go, pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job_test.go, pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go, pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/51775
We are analyzing the same table multiple times because when an index is analyzed in TiDB, it also analyzes other indexes and columns.
Only one index should be analyzed. Multiple indexes are stored to track the total analyzed indexes, even if only one is triggered.
You can check the tests to see what is the correct behavior.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: only analyze one index at a time

pkg/ddl/index_merge_tmp.go, pkg/ddl/ingest/BUILD.bazel, pkg/ddl/ingest/integration_test.go, pkg/ddl/reorg.go, pkg/tablecodec/tablecodec.go
Issue Number: close #51746
The bug is introduced by #47135: when merging temp index records from multiple indexes, I didn't set `reorgInfo`'s `StartKey` and `EndKey`  correctly. As a result, only one temp index get merged.
This PR initializes `reorgInfo.Start` and `reorgInfo.End` with keys encoded by the first index ID and the last index ID.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: fix add index's merge with multi-schema optimization

br/pkg/restore/client.go, br/pkg/task/restore.go
Issue Number: close #51736
tables id cannot be reused when there are many databases not being created continously
pre-allocate table ids at first
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: pre allocate table id at first

pkg/timer/BUILD.bazel, pkg/timer/api/client_test.go, pkg/timer/api/mem_store.go, pkg/timer/runtime/worker_test.go, pkg/timer/store_intergartion_test.go, pkg/timer/tablestore/BUILD.bazel, pkg/timer/tablestore/sql_test.go, pkg/timer/tablestore/store.go
Issue Number: close #51768
- fix the timer store's watermark drift for DST
- refine the behavior for the timer store with time zone. For time fields in `TimerRecord`, their location should be same with the `TimerRecord.Location` field
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> timer: fix some timezone behavior in timer framework

pkg/bindinfo/binding_cache.go, pkg/bindinfo/tests/timeout/BUILD.bazel, pkg/bindinfo/tests/timeout/timeout_test.go, tests/integrationtest/r/planner/core/integration.result, tests/integrationtest/t/planner/core/integration.test
Problem Summary: planner: output a SQL warning if binding loading is triggered
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: output a SQL warning if binding loading is triggered

pkg/server/tests/commontest/tidb_test.go
Issue Number: close #51790
We should wait to complete the server init and start to get connection info.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> server: fix data race in the TestProxyProtocolWithIpNoFallbackable

pkg/ttl/cache/table.go, pkg/ttl/cache/table_test.go, pkg/ttl/session/BUILD.bazel, pkg/ttl/session/session.go, pkg/ttl/ttlworker/BUILD.bazel, pkg/ttl/ttlworker/job.go, pkg/ttl/ttlworker/job_manager.go, pkg/ttl/ttlworker/job_manager_integration_test.go, pkg/ttl/ttlworker/job_manager_test.go, pkg/ttl/ttlworker/scan.go, pkg/ttl/ttlworker/scan_test.go, pkg/ttl/ttlworker/session.go, pkg/ttl/ttlworker/session_test.go, pkg/ttl/ttlworker/task_manager.go, pkg/ttl/ttlworker/task_manager_integration_test.go, pkg/ttl/ttlworker/timer.go, pkg/ttl/ttlworker/timer_test.go
Issue Number: close #51675
To make sure we have a right behavior with different timezones, this PR has some modifications:
- `EvalExpireTime` uses go time lib to compute the expired time instead of executing SQL to avoid some problems like: https://bugs.mysql.com/bug.php?id=95219
- `EvalExpireTime` must compute the expired time according to the TiDB global time zone.
- Considering some SQLs are using string format to update timestamp columns. We must ensure that the time argument with type `time.Time` has a location that is the same as the session's location. So I added some asserts.
- We force the session's time zone to 'UTC' for TTL meta operations to make sure we can insert a right time even in daylight saving time.
- We should also considerate the timezone for TTL job window. In this …
=> ttl: fix expire time drift for daylighting-save time case

pkg/session/session.go, tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Ensure MDL is ON when starting and committing pipelined txns
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> txn: check MDL when starting and committing pipelined txns

br/pkg/restore/client.go, br/pkg/restore/import.go, br/pkg/restore/split.go, br/pkg/restore/split/split.go, br/pkg/task/restore.go
Issue Number: ref #50701 
Unlimit goroutines may cause OOM if download and ingest not finished in time. even we had a download quota of importer.
introduce backpressure for download worker to notify main goroutine producer. and same to ingest workers.
Tests 
with this pr:
Memory usage is stable at 20G.
without this pr:
Memory usage reached 80G and eventually OOM.
> 
Side effects
Documentation
```release-note
None
```
=> restore: backpressure the importer producer goroutine

pkg/infoschema/builder.go, pkg/infoschema/infoschema.go, pkg/infoschema/infoschema_test.go, pkg/infoschema/infoschema_v2.go, pkg/infoschema/infoschema_v2_test.go, tests/integrationtest/r/infoschema/v2.result, tests/integrationtest/t/infoschema/v2.test
Before this fix, this would fail:
```
create table t1 (id int);
rename table t1 to t2;
show create table t1;   // expect error, but not get error
```
Changes:
- now drop table will add tomb record to infoschemaV2's byName field
-  `schemaVersion` field is moved to `infoschemaMisc` because both v1 and v2 use it 
Tests 
```
index d655384bfb..7e0bef66e7 100644
@@ -1482,7 +1482,7 @@ const (
DefEnableParallelSort                             = false
DefTiDBTxnEntrySizeLimit                          = 0
- …
```
=> infoschema: support rename table for infoschema v2

pkg/executor/compact_table.go
Issue Number: Fix https://github.com/pingcap/tidb/issues/51810
When returning the Start key and End key to TiDB, TiFlash does not encode them in a memory comparable way, so that we cannot simply compare these keys.
Tests 
> 
Side effects
Documentation
```release-note
Fix `ALTER TABLE ... COMPACT` may not work for tables with a VARCHAR primary key
```
=> executor: Fix compact for VARCHAR PK

pkg/planner/core/rule_predicate_push_down.go, tests/integrationtest/r/planner/core/issuetest/planner_issue.result, tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #51560 
The original codes will push the predicates that are not related to that child.
Don't do the recursively. Let the predicate-push-down to do the recursively.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix the issue about simplify outer join to inner join | tidb-test=pr/2313

pkg/config/BUILD.bazel, pkg/config/config.go, pkg/config/config_test.go
Issue Number: close #51399
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> config: return error when `toml.DecodeFile` failed.

pkg/session/session.go, pkg/session/txnmanager.go, tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Tables with foreign keys and reference by foreign keys when `foreign_key_checks=ON`, temp tables and cached tables are unsupported. Should fallback and generate warnings for them.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> txn: check unsupported table types for Pipelined DML

pkg/distsql/select_result.go, pkg/server/BUILD.bazel, pkg/server/conn_test.go, pkg/store/copr/coprocessor.go, pkg/store/mockstore/unistore/rpc.go
Issue Number: close #51660
Problem Summary: fix issue that some query execution stats was omitted when execution was interrupted.
This PR:
Execute query with max_execution_time, and make the query execution was interrupted, cause by maximum statement execution time exceeded. Then the slow query info still have executor stats.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix issue that some query execution stats was omitted when execution was interrupted

pkg/bindinfo/session_handle.go, pkg/sessionctx/sessionstates/BUILD.bazel, pkg/sessionctx/sessionstates/session_states_test.go
Issue Number: close #51859 
After refactor on the session binding, the data structure has changed a lot, and the new TiDB can't recognize the JSON serialized by the old TiDB.
1. Recognize whether the JSON is of old format or new format
2. If it's old format, convert it into the new data structure
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> bindinfo: fix compatibility of encoding SQL bindings between TiDB versions

Makefile, pkg/session/session.go, tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Issue Number: ref #50215
Some tests failed need to be fixed. But CI doesn't test the pipelineddmltest package before, so need to merge https://github.com/PingCAP-QE/ci/pull/2859 after this PR.
Tests 
> 
With this PR:
```bash
» go test ./tests/realtikvtest/pipelineddmltest --tags=intest
ok      github.com/pingcap/tidb/tests/realtikvtest/pipelineddmltest     11.298s
```
Side effects
Documentation
```release-note
None
```
=> txn: fix the warnings in pipelined dml

br/pkg/lightning/backend/external/BUILD.bazel, br/pkg/lightning/backend/external/bench_test.go, br/pkg/lightning/backend/external/merge.go, br/pkg/lightning/backend/external/merge_test.go, br/pkg/lightning/backend/external/onefile_writer_test.go, br/pkg/lightning/backend/external/sort_test.go, br/pkg/lightning/backend/external/writer.go, pkg/ddl/backfilling_merge_sort.go, pkg/disttask/importinto/BUILD.bazel, pkg/disttask/importinto/task_executor.go
try to split files more evenly to improve performance
Tests 
before(import 1.194TiB with force merge step)
```
[step=merge-sort] [mem-limit-percent=0.99] [server-mem-limit=88%] [resource="[CPU=16, Mem=27.83GiB]"] [takeTime=31m43.024898826s] []
```
after(about 2~3 minutes improvement)
```
[step=merge-sort] [mem-limit-percent=0.99] [server-mem-limit=88%] [resource="[CPU=16, Mem=27.83GiB]"] [takeTime=28m39.158921948s]
```
> 
Side effects
Documentation
```release-note
None
```
=> globalsort: split files evenly in MergeOverlappingFiles

DEPS.bzl, go.mod, go.sum, pkg/store/mockstore/unistore/pd.go, pkg/store/mockstore/unistore/pd_test.go
Issue Number: close #51894, close https://github.com/tikv/pd/issues/7849.
Problem Summary: upgrade PD client to fix the bug that may cause the TSO hang during the PD service mode switch.
Tests 
```release-note
None
```
=> go.mod: upgrade PD client to fix the TSO hang bug

br/pkg/restore/import.go
Issue Number: ref #50701 
https://github.com/pingcap/tidb/pull/51777 introduce a problem that raw kv restore will getting into stuck (catched by integration test). because the default `concurrencyPerStore` is 0. 
we don't need to handle backpressure issue when doing a raw restore. so we add a flag to skip.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: fix the stuck issue when use raw kv restore

pkg/statistics/handle/storage/read.go, pkg/statistics/handle/syncload/stats_syncload.go, pkg/statistics/table.go
Issue Number: close #51871 
It's possible that the meta-loaded item is loaded again and again when we really don't need a full load.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner,statistics: check the meta-load case in ColumnIsLoadNeeded

pkg/ttl/cache/table.go, pkg/ttl/cache/table_test.go, pkg/ttl/session/BUILD.bazel, pkg/ttl/session/session.go, pkg/ttl/ttlworker/BUILD.bazel, pkg/ttl/ttlworker/job.go, pkg/ttl/ttlworker/job_manager.go, pkg/ttl/ttlworker/job_manager_integration_test.go, pkg/ttl/ttlworker/job_manager_test.go, pkg/ttl/ttlworker/scan.go, pkg/ttl/ttlworker/scan_test.go, pkg/ttl/ttlworker/session.go, pkg/ttl/ttlworker/session_test.go, pkg/ttl/ttlworker/task_manager.go, pkg/ttl/ttlworker/task_manager_integration_test.go, pkg/ttl/ttlworker/timer.go, pkg/ttl/ttlworker/timer_test.go
Issue Number: close #51675
fix the time zone issue again after we reverted #51701. In this PR, we still use SQL to compute the expired time to make sure it has the same behavior as the expression. However, to make the result right we:
1. Set the session's time zone to UTC to make the time zone stable and has no daylight-saving time.
2. Make a new start time with the same string value but it is in time zone 'UTC'. For example, if the input now is `2020-01-01 08:00:00 +08:00`, the new start time is `2020-01-01 08:00:00 UTC`.
3. Compute the expired time with the new started time, for example, if the expire interval is `1 hour`, the expire time is `2020-01-01 07:00:00 UTC`
4. The interval between the above two times is the expired duration.
5. Compute the real expired time by …
=> ttl: fix time zone issue in TTL

pkg/executor/infoschema_reader.go, pkg/executor/infoschema_reader_test.go
Issue Number: close #51829
Revert the change for V2
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix columns table query unstable

pkg/privilege/privileges/ldap/BUILD.bazel, pkg/privilege/privileges/ldap/ldap_common.go, pkg/privilege/privileges/ldap/ldap_common_test.go
Issue Number: close #51883
This PR is a smaller version of #51912. We'll finally get #51912 merged, but we need a smaller one to focus on the timeout mechanism (which is much simpler than refactor the locks).
If the LDAP connection lost after the first handshake, the LDAP goroutine and function call will hang forever.
I have done two modifications in this PR:
1. Add a timeout for LDAP dialing and requests. Therefore, the lock will be held for at most several seconds.
2. Add an interval to the retry mechanism, to avoid using all quotas provided by the LDAP service.
Tests 
> 
`docker run --network host -it yangkeao/ldap-sasl-example:d2b324 /bin/bash` to get an environment with LDAP server. Then running a TiDB server at port 4000.
Create …
=> ldap: add timeout and retry-backoff for ldap

pkg/expression/aggregation/agg_to_pb.go, pkg/expression/aggregation/agg_to_pb_test.go, pkg/expression/aggregation/window_func.go, pkg/expression/expr_to_pb_test.go, pkg/expression/infer_pushdown.go, pkg/planner/cascades/transformation_rules.go, pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/find_best_task.go, pkg/planner/core/indexmerge_path.go, pkg/planner/core/plan_to_pb.go, pkg/planner/core/rule_predicate_push_down.go, pkg/planner/core/task.go, pkg/planner/core/util.go
Issue Number: close #51890
It's better to keep `EvalContext` exposed fewer fields to make sure it is simple and semantically clear. In this PR, we introduce `expression.PushDownContext` context to provide some push down information.
`PushDownContext` contains `EvalContext` and also provides some other fields like `kv.Client` that is not required by `EvalContext`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: add `PushDownContext` for push down operations

pkg/executor/builder.go, pkg/executor/test/issuetest/BUILD.bazel, pkg/executor/test/issuetest/executor_issue_test.go
Issue Number: close #51874 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: Fix pushdown caused correlated subquery issue

DEPS.bzl, go.mod, go.sum
Issue Number: close #51894, close https://github.com/tikv/pd/issues/7849.
Problem Summary: upgrade PD client to fix another bug that may cause the TSO to hang during the PD service mode switch, see https://github.com/tikv/client-go/pull/1241 and https://github.com/tikv/pd/pull/7951.
Tests 
```release-note
None
```
=> go.mod: upgrade PD client to fix another TSO hang bug

br/pkg/task/restore_data.go
warn if store num not match
Issue Number: close #51957
It is unnecessary to check the store number in data restore phase -- since tidb-operator will help us to check it. 
Now this check breaks a workaround for one store cannot unexpectedly bootstrap after restoring.
This PR removes the check to number of stores.
Tests 
> 
The change is tiny and I manually tested it in a local k8s cluster.
Side effects
Documentation
```release-note
None
```
=> log_backup: remove checking store number

pkg/ddl/index.go, tests/realtikvtest/addindextest/add_index_test.go
Issue Number: close #51162 
Restored data should not truncated in buildHandle.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: fix adding multi-value index

pkg/ddl/db_test.go, pkg/ddl/ddl_worker.go
Issue Number: close #51962
https://github.com/pingcap/tidb/blob/274d5e2e64e303961208d0320da125fc3cb69d44/pkg/ddl/ddl_worker.go#L544-L565
We should not set `job.InvolvingSchemaInfo` to nil even if this txn size is too large, because we need this field to "unblock" other DDLs that change the same schemas/tables.
See 'Files Changed'.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: do not unset involving schema on EntryTooLarge error

pkg/planner/core/casetest/correlated/BUILD.bazel, pkg/planner/core/casetest/correlated/correlated_test.go, pkg/planner/core/casetest/correlated/main_test.go, pkg/planner/core/logical_plan_builder.go
Issue Number: close #51107
the fields in the having clause should be a correlated column unrelated to select fields and group-by fields.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix the incorrect judgment of correlated column in the having clause

pkg/infoschema/infoschema_v2.go
```
tk.MustExec("create table t1 (id int key, name varchar(10), leader int,  index(leader), foreign key (leader) references t1(id) ON DELETE SET NULL);")
tk.MustExec("drop table t1")
tk.MustExec("create table t1 (id varchar(10) key, name varchar(10), leader varchar(10),  index(leader), foreign key (leader) references t1(id) ON DELETE SET NULL);")
```
Expect no error, but get 
```
Messages:       sql:create table t1 (id int key), [], error stack [schema:1146]Table 'test.t1' doesn't exist
github.com/pingcap/errors.AddStack
/home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178
github.com/pingcap/errors.(*Error).GenWithStackByArgs
/home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555 …
```
=> infoschema: fix foreign key tests for infoschema v2

pkg/parser/ast/dml.go, pkg/parser/ast/expressions.go, pkg/planner/core/logical_plan_builder.go
I find some AST code in the planner. It is hard to find the code for reusing code. so I move those code into AST member function.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> parser,planner: move some code into AST member function

br/pkg/lightning/backend/external/reader.go
Issue Number: close #51947
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: fix an incorrect metric

pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel, pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go, pkg/statistics/handle/autoanalyze/priorityqueue/job.go, pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go, pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go, pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go, pkg/statistics/handle/autoanalyze/refresher/refresher.go
Issue Number: close https://github.com/pingcap/tidb/issues/51972
In this scenario, we set the auto-analyze ratio to a very small value of `0.0001`. However, the table is considerably large and has a total of 10000000 rows and 2 rows. As a result, it will get an (almost)zero weight, and we will skip it. Unfortunately, this is not ideal as the entire database only has one table, and this will cause it to be considered as a regression.
Usually, we don't encounter this type of scenario in reality. However, it may be worth considering removing this limitation and placing the negatively weighted job in the queue to prevent this type of problem from occurring.
1. Only warning about this kind of job.
2. Print more precise weight and change percentage.
Tests 
> - [ ] I checked and …
=> statistics: do not skip negative and zero weight tables

pkg/infoschema/infoschema_v2.go
Tests 
```
go test -timeout 10m -run ^TestCacheTableBasicScan$ github.com/pingcap/tidb/pkg/table/tables -race --tags=intest
```
> 
Side effects
Documentation
```release-note
None
```
=> infoschema_v2: get cache with old schema version

br/tests/br_foreign_key/run.sh, pkg/ddl/table.go
Issue Number: close #51838
When restoring some tables, the state can be `StatePublic`, so `createTableWithForeignKeys` should also handle the `StatePublic`.
Also handle the `StatePublic` in `createTableWithForeignKeys`. In `createTable`, the `State` will always be reset to `StateNone` (though sounds weird :facepalm:, but this code has been existing for 8 years).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: allow `StatePublic` in `createTableWithForeignKeys` for BR

pkg/metrics/grafana/tidb_resource_control.json
Issue Number: ref https://github.com/pingcap/tidb/issues/49318
Tests 
> 
```release-note
None
```
=> metrics: Add a RU(max) panel to observe maximum resource consumption

Makefile, pkg/executor/executor.go, pkg/executor/update.go, pkg/session/session.go, tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Issue Number: ref #50215 close #52028
This PR picks #51867 and #51913
Tests 
> 
```bash
» go test ./tests/realtikvtest/pipelineddmltest --tags=intest -race
ok      github.com/pingcap/tidb/tests/realtikvtest/pipelineddmltest     61.492s
```
Side effects
Documentation
```release-note
None
```
=> txn: fix race in p-dml caused by `Transaction.SetOption` running with background flushing(#51913)

pkg/executor/simple.go, pkg/metrics/grafana/tidb_summary.json, pkg/metrics/grafana/tidb_summary.jsonnet, pkg/server/conn.go, pkg/server/conn_test.go, pkg/server/internal/testserverclient/BUILD.bazel, pkg/server/internal/testserverclient/server_client.go, pkg/server/server.go, pkg/server/tests/commontest/BUILD.bazel, pkg/server/tests/commontest/tidb_test.go
Issue Number: close #51889
1. The connection count is not correct, if the session resets the resource group manually.
2. Maintaining a separated map on `server` to count the connection for each resource group seems to be not necessary. We can use the `GaugeVec` itself. The connection count is not used anywhere else.
3. The grafana panel of connection count is confusing. I added a legend and now it looks like:
Maybe someone prefers to sum up them together. Actually I think both are fine, feel free to comment your opinion.
Personally, I don't like the idea to use the uncontrollable string as a label :facepalm:, because the prometheus will have much greater pressure when these labels multiply together.
As for now, it seems not a big issue, but it'll become much worse if …
=> server, metrics: remove the connection count on server, only use the metrics

pkg/ddl/ingest/engine_mgr.go
After #51261, `TikvImporter.RangeConcurrency` will be dynamically set by `tidb_ddl_reorg_worker_cnt`. The upper limit should be a constant.
Limit max concurrency to 16 for add index writers.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: limit max concurrency to 16 for add index writers

pkg/ddl/backfilling_dist_scheduler.go
Issue Number: close #52042
In read index stage, each subtask contains at most 100 regions. It means a subtask contains 96MB * 100 ~= 10GB table data. If the size of index is small, like 20 bytes, each subtask generates a file with a size of a few metabytes.
This PR increases region number per subtask from 100 to 4000.
Tests 
Tested on 40TB cluster, the unnecessary merge sort step is eliminated, and the max backfill rate also increased by 10%(761493 -> 833370).
> 
Side effects
Documentation
```release-note
None
```
=> ddl: increase to 4000 regions per global sort subtask

pkg/infoschema/tables.go
Issue Number: close #52034
check resp is nil
Tests 
> 
```release-note
None
```
=> tabls: fix resp is nil and change resp check

br/pkg/checkpoint/checkpoint.go
Issue Number: 
Problem Summary: overengineering simple counter with `sync.Mutex`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: use atomic for failedFilesCount

br/pkg/streamhelper/config/advancer_conf.go, br/pkg/task/stream.go
Issue Number: ref #50803
This PR set the default value of 'check-point-lag-limit' to 24 hours, and also expose the paramter.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: Change default check point lag limit

br/pkg/backup/prepare_snap/BUILD.bazel, br/pkg/backup/prepare_snap/prepare.go, br/pkg/backup/prepare_snap/prepare_test.go, br/pkg/task/operator/cmd.go
Issue Number: ref #51448
In #51449, we delayed pausing admin commands after all connections are established. But that isn't enough, due to PD schedulers are paused and ID allocation is disabled. 
This PR pauses PD's scheduler after all connections are established.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> operator: pause scheduler after all connections established

pkg/executor/aggregate/agg_hash_executor.go
Issue Number: close #52069
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix the panic that send on closed channel in the TestRandomFail

pkg/planner/core/casetest/BUILD.bazel, pkg/planner/core/casetest/integration_test.go, pkg/planner/core/find_best_task.go
Issue Number: close #49438
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix the issue that MVIndex leads to "can't find plan" error

pkg/statistics/handle/logutil/logutil.go
Issue Number: close https://github.com/pingcap/tidb/issues/52100
It is unnecessary to have two of them since they are mostly identical.
Only print the first log within 5 minutes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: ignore more logs

br/pkg/restore/client.go, br/pkg/task/restore.go
Issue Number: ref #50701 close https://github.com/pingcap/tidb/issues/51621
Currently eg.Go will generate too many goroutines if ingest too slow. then it will block goroutine release. eventually consume too many memory or even OOM.
This PR tried to give a high limitation of total download goroutines. which consider the balance of restore speed and memory usage.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> restore: use a limited workpool

br/pkg/task/restore.go
Issue Number: ref #50701 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: turn on coarse-grained as default for restore

pkg/ddl/index.go, pkg/ddl/ingest/integration_test.go
Issue Number: close #52080
#51747 does not consider partitioned tables.
This PR also fix on partitioned tables.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: fix add multi-indexes merge on partition tables

pkg/expression/constant_fold.go, tests/integrationtest/r/expression/constant_fold.result, tests/integrationtest/t/expression/constant_fold.test
Issue Number: close #51765
The `ifnull` has different behavior in inferring collation for constant folding and normal execution path.
Set the collation according to the first argument in the path of constant folding.
Tests 
> 
```release-note
Fix the issue that the collation of `ifnull` expression is different with MySQL when constant folding applies.
```
=> expression: set a collation according to the arguments for `ifnull` in constant folding

pkg/ddl/BUILD.bazel, pkg/ddl/backfilling_dist_executor.go, pkg/ddl/backfilling_merge_sort.go, pkg/ddl/backfilling_operators.go, pkg/ddl/backfilling_read_index.go, pkg/ddl/backfilling_scheduler.go, pkg/ddl/index.go, tests/realtikvtest/addindextest3/operator_test.go
Issue Number: close #52085
Problem Summary: See #52085.
- Move avarage row size estimation to the beginning of adding index.
- Use `approximate-key-size` * `MB` / `approximate-keys` from region info fetched by PD client to enhance row size estimation.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: enhance row size estimation before adding index

pkg/infoschema/infoschema_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: fix TestBuildSchemaWithGlobalTemporaryTable with infoschema v2

pkg/executor/analyze.go
Issue Number: close https://github.com/pingcap/tidb/issues/51993
See: https://github.com/pingcap/tidb/issues/51993#issuecomment-2014599880
We should check if errExitCh is already closed, then we don't need to block sending the analyzed result.
Tests 
> 
Side effects
Documentation
```release-note
修复自动分析在 OOM 后卡住的问题
Fix Auto-Analysis stuck issue after OOM
```
=> statistics: do not block when sending analyze result

pkg/infoschema/builder.go, pkg/infoschema/infoschema.go, pkg/infoschema/infoschema_v2.go
Tests 
```
index d5e9b34324..73e6f48387 100644
@@ -1483,7 +1483,7 @@ const (
DefTiDBSchemaVersionCacheLimit                    = 16
DefTiDBTxnEntrySizeLimit                          = 0
-       DefTiDBSchemaCacheSize                            = 0
+       DefTiDBSchemaCacheSize                            = 1024
DefTiDBLowResolutionTSOUpdateInterval             = 2000
```
```
make ut X='run pkg/executor/test/ddl TestRenameTable'
```
> 
Side effects
Documentation
Please …
=> infoschema_v2: fix rename table

tools/check/ut.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tools/check: close junit file

pkg/server/http_status.go
Issue Number: close #51914 
Move all status routes to be registered behind `mux.Router` instead of splitting between the router and `http.ServeMux`.
All status routes are registered with `mux.Router` and `mux.Router` itself is registered as an HTTP handler for all routes for `http.ServeMux`. There should be NO behavior changes and existing test cases for affected routes should continue to pass.
Tests 
> 
Side effects
Documentation
```release-note
Clean up status route registration.
```
=> server: register all status routes with mux.Router

planner/core/issuetest/BUILD.bazel, planner/core/issuetest/planner_issue_test.go, planner/core/logical_plans.go, planner/core/rule_predicate_push_down.go
Manual cherry-pick https://github.com/pingcap/tidb/pull/51329
Issue Number: close #50614 
#35669 disables predicates pushdown on `TableDual`.
This usually won't cause problems, but when it comes to cases like #50614, many unnecessary predicates with lots of conditions will cause obvious performance regression.
This PR reverts https://github.com/pingcap/tidb/pull/35669, which is for fixing https://github.com/pingcap/tidb/issues/35527.
#35527 itself has already been fixed by #38802, which prevents predicates from being incorrectly pushed through `Projection`.
As said in #35669, sometimes `TableDual` doesn't have a `schema`. This may or may not be considered as a mistake depending on our definition of the semantic of `TableDual`.
Anyway, `TableDual` without `schema` should …
=> planner: remove the limitation that predicates can't be pushed through `Projection` on `TableDual` (#51329)

br/pkg/backup/client.go
Issue Number: close #50837 
Remove the misleading entry in br log as described in the issue.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: remove misleading log info

pkg/statistics/column.go, pkg/statistics/table.go
Issue Number: ref #51853
there is a global lock, and although there are plenty of write/read paths, by sharding, I can increase the granularity of the locks.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: shard needsStatsMap 

pkg/executor/infoschema_reader.go
Issue Number: close #50810
Tests 
Create a cluster by `tiup playground nightly --db 1 --tiflash 0 --without-monitor` and wait a minutes.
Before this patch sometimes the query result will like 
```
mysql> select * from `TIDB_HOT_REGIONS`;
+---------------------+----------+--------------------+------------------+------------+-----------+------+----------------+--------------+------------+
| TABLE_ID            | INDEX_ID | DB_NAME            | TABLE_NAME       | INDEX_NAME | REGION_ID | TYPE | MAX_HOT_DEGREE | REGION_COUNT | FLOW_BYTES |
+---------------------+----------+--------------------+------------------+------------+-----------+------+----------------+--------------+------------+
| 4611686018427387961 |     NULL | INFORMATION_SCHEMA | INSPECTION_RULES | NULL       | …
```
=> infoschema: don't display tables in MemDB when query `TIDB_HOT_REGIONS`

pkg/server/http_status.go
Reverts pingcap/tidb#51915
it will make all debug path 404
so we revert it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> Revert "server: register all status routes with mux.Router"

pkg/server/handler/tests/BUILD.bazel, pkg/server/handler/tests/http_handler_serial_test.go, pkg/server/http_status.go
Issue Number: close #51914 
Resubmits https://github.com/pingcap/tidb/pull/51915 and fixes issues with missing `/debug/pprof/` routes.
`pprof.Index` handles multiple sub routes by stripping `/debug/pprof/` from the path and looking the remaining path from a map and load the corresponding HTTP handlers. These handlers are not registered directly to the `http.ServeMux` or `mux.Router`. We have to register `pprof.Index` handler to the `mux.Router` as a backup handler for any `/debug/pprof/*` routes that are not explicitly registered, so that all routes can be found.
Move all status routes to be registered behind `mux.Router` instead of splitting between the router and `http.ServeMux`.
All status routes are registered with `mux.Router` and `mux.Router` itself is registered as …
=> server: move all routes to mux router and make sure pprof paths are good

pkg/executor/adapter.go
Issue Number: close https://github.com/pingcap/tidb/issues/52174
For no delayed DML execution (insert/update/delete), the query locks keys after execution, which make the lock duration be excluded in the total execution time. But for select for update statement, it is included.
Add the lock duration to execution info for pessimistic DMLs.
Tests 
2. make an insert statement wait lock for a long time, like https://github.com/pingcap/tidb/issues/52174 shows.
3. decode the insert plan in the slow log file
> 
Side effects
Documentation …
=> executor: add lock time in total time of insert execution info

tests/integrationtest/r/ddl/default_as_expression.result, tests/integrationtest/t/ddl/default_as_expression.test
Issue Number: close https://github.com/pingcap/tidb/issues/52267
```
run test [ddl/default_as_expression] err: sql:alter table t0 modify column c1 datetime DEFAULT (date_format(now(), '%Y-%m-%d'));: failed to run query
\"alter table t0 modify column c1 datetime DEFAULT (date_format(now(), '%Y-%m-%d'));\"
around line 58,
we need(139):
alter table t0 modify column c1 datetime DEFAULT (date_format(now(), '%Y-%m-%d'));
Error 1292 (22007): Incorrect datetime value: '2024-03'
but got(139):
alter table t0 modify column c1 datetime DEFAULT (date_format(now(), '%Y-%m-%d'));
Error 1292 (22007): Incorrect datetime value: '2024-04'
```
Tests 
> 
Side effects
Documentation …
=> tests: fix the error msg in default_as_expession

WORKSPACE
Issue Number: close #52274
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: upgrade 1.21.8

pkg/expression/builtin_info.go
Issue Number: close #51477
After #52015, `TiDBDecodeKeyFunctionKeyType` is not used by anyone because we use a more static way to provide `decodeKeyFromString` function.
Just remove `TiDBDecodeKeyFunctionKeyType`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: remove useless `TiDBDecodeKeyFunctionKeyType`

br/pkg/streamhelper/advancer_test.go
Issue Number: close #52123 #51671
TestClearCache get wrong result
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: fix TestClearCache

pkg/infoschema/infoschema_v2.go
Tests 
```
index d5e9b34324..73e6f48387 100644
@@ -1483,7 +1483,7 @@ const (
DefTiDBSchemaVersionCacheLimit                    = 16
DefTiDBTxnEntrySizeLimit                          = 0
-       DefTiDBSchemaCacheSize                            = 0
+       DefTiDBSchemaCacheSize                            = 1024
DefTiDBLowResolutionTSOUpdateInterval             = 2000
```
```
make ut X='run pkg/ddl/test/fail/ddl_test TestPartitionAddIndexGC'
```
> 
Side effects …
=> infoschema_v2: fix TestPartitionAddIndexGC

pkg/ddl/backfilling_import_cloud.go, pkg/ddl/backfilling_merge_sort.go, pkg/ddl/backfilling_operators.go, pkg/ddl/backfilling_read_index.go, pkg/ddl/backfilling_scheduler.go, pkg/ddl/index.go, pkg/disttask/framework/storage/task_table.go, pkg/disttask/importinto/encode_and_sort_operator.go, pkg/disttask/importinto/encode_and_sort_operator_test.go, pkg/disttask/importinto/task_executor.go, pkg/executor/importer/import.go, pkg/executor/importer/import_test.go, tests/realtikvtest/addindextest3/operator_test.go
DDL and IMPORT INTO use SubtaskBase.Concurrency. The downside is we cann't dynamically adjust the concurrency using tidb_ddl_reorg_worker_cnt for now.
Tests 
> should be covered by existing test
Side effects
Documentation
```release-note
None
```
=> disttask,ddl: use subtask concurrency

pkg/executor/importer/precheck.go, pkg/executor/importer/precheck_test.go, tests/realtikvtest/importintotest4/main_test.go
Issue Number: ref #49008 
- after https://github.com/pingcap/tidb/pull/51924, we can run import with global sort on 8c machine now, so reduce this limit
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> importinto: change min thread to 8 for global sort

pkg/util/cpuprofile/testutil/util.go, pkg/util/topsql/collector/BUILD.bazel, pkg/util/topsql/collector/cpu.go, pkg/util/topsql/topsql.go
Issue Number: close #52215
Use the hex string in goroutine labels. It'll allow us to use the `go tool pprof` and graphviz to handle the protobuf.
Before this PR returned, you can workaround by generating a `dot` file, and use `iconv` to handle the non-utf8 characters manually.
Use the pre-ecoded hex string, rather than bytes.
Tests 
> 
Run any tests (which runs at least some SQLs) and profile it with `-cpuprofile`, and you'll find the protobuf is useable now.
```release-note
None
```
=> topsql, pprof: use hex string but not binary sql/plan digest in goroutine label

pkg/expression/BUILD.bazel, pkg/expression/aggregation/agg_to_pb.go, pkg/expression/aggregation/agg_to_pb_test.go, pkg/expression/expr_to_pb_test.go, pkg/expression/infer_pushdown.go, pkg/planner/core/util.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #52134
The `SessionVars` in `PushDownContext` is too big. If we are going to decide whether we can clone the whole `tableReaderExecutorContext` can be cloned, one big part of it is the `SessionVars` in `PlanContext`, which turns to be stored in `PushDownContext` (and there are other usages, which will be refactored in the future).
1. Add a special warning handler, to append warn according to whether the statement is `explain` (or not).
2. Get the variable `GroupConcatMaxLen` before constructing the context.
Tests 
> No logic change.
```release-note
None
```
=> expression: minimize the `PushDownContext`

pkg/statistics/table.go
Issue Number: ref #29769
If the table's last analyze version is 0. It has not been analyzed yet.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix the possible wrong result for stats_healthy

pkg/session/session.go, tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Produce warning for Pipelined DML when falling back because of tidb_constraint_check_in_place
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> txn: produce warning for Pipelined DML when falling back because of tidb_constraint_check_in_place

DEPS.bzl, go.mod, go.sum
Issue Number: close #39169
Problem Summary: See https://github.com/tikv/client-go/pull/1219
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> client-go: fix data race that may cause tikv/client-go client_batch panic 

pkg/ddl/ddl.go, pkg/ddl/ddl_running_jobs.go, pkg/ddl/ddl_running_jobs_test.go
Issue Number: close #51846
We have a ddl reorg job with job_id=1, cluster with 2 tidb(tidb1, tidb2).
Timeline:
1.  ddl owner run the reorg job with job_id = 1, then ddl start one reorg worker named worker1.
2. the ddl owner(tidb1) retire then set processingJobs to empty.
3. worker1 on tidb1 not finished for 5s.
4. tidb1 become the ddl owner again.
5. the dispatcher start a new ddl worker for the job since processingJobs is empty, then start a new reorg worker named worker2. At this time, 2 reorg job running concurrently.
6. previous worker1 timeout and notify the dispatcher to start a new reorg worker worker1'.
7. worker2 timeout and notify the dispatcher to start a new reorg worker worker2'.
Then step6 & 7 will run multiple times until one worker finished the job.
Once …
=> ddl: fix 2 reorg worker running concurrently after retire owner then to be owner

br/pkg/backup/prepare_snap/env.go, br/pkg/utils/BUILD.bazel, br/pkg/utils/backoff.go, br/pkg/utils/backoff_test.go, br/pkg/utils/retry.go
Issue Number: close #52175
See the issue.
This make an infinity retry for the connecting to store phase.
The retry of waiting apply phase has been kept because it seems waiting apply isn't always lasting for minutes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> operator: make an infinity retry for connecting to store

pkg/distsql/select_result.go, pkg/util/execdetails/execdetails.go, pkg/util/execdetails/execdetails_test.go
Issue Number: ref #28937 
```
explain analyze select * from t1;
+-----------------------+---------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+
| id                    | estRows | actRows | task      | access object | execution info …
```
=> cop: display kv read time details in the execution information

pkg/parser/model/model.go, pkg/statistics/handle/syncload/stats_syncload.go, pkg/statistics/handle/syncload/stats_syncload_test.go, pkg/statistics/handle/types/BUILD.bazel, pkg/statistics/handle/types/interfaces.go
Issue Number: close #52294
the problem has been described in the issue. we refactor the singleflight using the golang official library.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix wrong singleflight implementation for stats' syncload

br/pkg/backup/prepare_snap/BUILD.bazel, br/pkg/backup/prepare_snap/prepare.go, br/pkg/backup/prepare_snap/prepare_test.go, br/pkg/backup/prepare_snap/stream.go
Issue Number: close #52243
When exiting due to error, we are waiting from the client to finish before receiving from the output channel. In this case, the output channel may be full and blocks the exit procedure.
We will poll from both the request exit result and the exit channel.
Tests 
> 
Side effects
Documentation
```release-note
Fixed an issue where init pod may get stuck when encountering connective errors.
```
=> br/operator: fix stuck when terminating

pkg/ddl/column.go, pkg/ddl/partition.go, pkg/ddl/table.go, pkg/statistics/handle/ddl/BUILD.bazel, pkg/statistics/handle/ddl/ddl.go, pkg/statistics/handle/ddl/ddl_test.go, pkg/statistics/handle/util/BUILD.bazel, pkg/statistics/handle/util/ddl_event.go, pkg/statistics/handle/util/ddl_event_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/52040
During the upgrade process, if there are two different TiDB versions running in the same cluster, statistics will be created for system tables. For example, if we upgrade from v7.5.0 to v8.0.0, and the newer version has a table called `mysql.request_unit_by_group` that was not present in the previous version, we will accidentally create statistics for this newly added table. However, we should avoid creating any statistics for system tables.
Ignore all system table DDL events from the DDL handler.
I put in a lot of effort to test this patch during the upgrade process, but it was quite challenging to do so. This issue only arises when two different versions of TiDB are present in the cluster, with the older …
=> statistics: add schema ID to check if it is a system or mem table

lightning/pkg/server/lightning.go, pkg/lightning/common/BUILD.bazel, pkg/lightning/common/util.go, pkg/lightning/common/util_test.go
Issue Number: close #36374
Lightning in server-mode logged the original TOML task config received in `POST /task`. This will leak password of the task into the log. Previously #36375 attempted to workaround by replacing the password part by `******` with regexp, but the regexp is written wrongly. Even if it is regexp is corrected, using regexp to parse TOML is bound to miss some edge cases.
This PR simply removed the log. If the task config can be successfully parsed, it should still be visible in the subsequent `[cfg]` log with proper redaction.
Tests 
> - run in server-mode and send a config
> 
Side effects
Documentation …
=> lightning: Don't log "received task config" in server mode

pkg/executor/join.go, pkg/executor/join_pkg_test.go, pkg/executor/test/jointest/hashjoin/hash_join_test.go, tests/integrationtest/r/planner/core/cbo.result
Issue Number: close #52222
Tests 
run TPCH query 10 base on TPCH-50 dataset
Before this pr
```
|           ├─HashJoin_88(Build)                | 2882295.78  | 2865763  | root      |                                                         | time:4.93s, loops:2802, build_hash_table:{total:160.6µs, fetch:135.6µs, build:25µs}, probe:{concurrency:5, total:50.9s, max:10.2s, probe:27.9s, fetch:23s} …
```
=> executor: fix distorted join probe time

pkg/domain/domain.go, pkg/statistics/handle/syncload/stats_syncload.go, pkg/statistics/handle/types/interfaces.go
this code is only written, not read. so it is useless.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> domon,statistics: remove useless code for sync load

pkg/executor/adapter.go, pkg/executor/compiler.go, pkg/executor/prepared.go, pkg/parser/ast/misc.go, pkg/planner/core/plan_cache.go, pkg/planner/core/plan_cache_utils.go, pkg/server/driver_tidb.go, pkg/session/session.go
Issue Number: ref #51407
Problem Summary: planner: move fields from ast.Prepared to planner.PlanCacheStmt
NO LOGICAL CHANGE, ONLY REFACTOR
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move fields from ast.Prepared to planner.PlanCacheStmt

pkg/statistics/handle/bootstrap.go, pkg/statistics/handle/cache/statscacheinner.go, pkg/statistics/handle/initstats/BUILD.bazel, pkg/statistics/handle/initstats/load_stats.go, pkg/statistics/handle/initstats/load_stats_page.go
Issue Number: close #52339
During the init stats, we will read many stats and write them into the stats cache. but if too many things need to be written, the cache will return fail because the channel in the internal will be full. so we need to do optimization on it.
1、avoid writing a cache when reading a record from the DB. 
we read all the data about the statistics of the table, then write it into DB.
and if fails, we will retry to write.
2、 Open too many concurrencies for the init stats.
We set the upper bound and changed the default value of concurrency.
Tests 
test with 50k tables, it can work.
> 
Side effects
Documentation …
=> statistics: batch write into stats cache when to init stats

Makefile, pkg/testkit/testkit.go
Issue Number: close #52403
The benchmark gets slower with the assertion. If we disable the `intest` tag, the performance will be back but the `TestKit` will fail to initialize. 
This PR only checks the `intest` tag in testkit when the incoming `t` is not `*testing.B`.
Tests 
> 
```
go test -benchmem -run=^$ -bench ^BenchmarkUnionScanRead$ github.com/pingcap/tidb/pkg/executor
```
Run this command without `-tags intest`, it'll execute successfully.
Side effects
Documentation
```release-note
None
```
=> Makefile, testkit: don't add intest tag for daily bench

pkg/domain/ru_stats.go, pkg/domain/ru_stats_test.go
Issue Number: close #52353
Use the time API to calculate the start_time of ru_stats so it can be compatible with DST(daylight saving time).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> domain: make ru_stats duration compatible with DST

pkg/statistics/handle/bootstrap.go, pkg/statistics/handle/handletest/statstest/stats_test.go
Issue Number: close #52419
We put the wrong table id as key to write stats cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: fix puting wrong stats into cache

build/nogo_config.json, planner/core/exhaust_physical_plans.go, planner/core/find_best_task.go, planner/core/logical_plans.go, planner/core/main_test.go, planner/core/plan_stats_test.go, planner/core/stats.go, planner/core/testdata/plan_stats_suite_in.json, planner/core/testdata/plan_stats_suite_out.json, statistics/histogram.go, statistics/index.go, statistics/selectivity.go, statistics/selectivity_test.go, statistics/table.go
Manually cherry-pick #52208
Issue Number: close #52207
Previously, this place incorrectly used the `UniqueID`, which is only valid during this query.
We should use the column ID from the metadata so that we can correctly fetch the column name from `TableInfo`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner, statistics: use the correct column ID when recording stats loading status (#52208)

pkg/planner/core/rule_collect_plan_stats.go, pkg/sessionctx/variable/session.go, pkg/sessionctx/variable/sysvar.go, pkg/statistics/handle/syncload/stats_syncload.go
Issue Number: close #52425
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: upgrade stats timeout checkpoint after it timeouts

pkg/domain/domain.go, pkg/domain/resourcegroup/runaway.go, pkg/domain/runaway.go
…nished
Issue Number: close #52048
Tests 
> 
before
> tiup playground nightly --tag upgrade3 --db 3
> ctrl + C
> tiup playground nightly --tag upgrade3 --db 3
after
> tiup playground v7.1.1 --tag upgrade --db 3
> ctrl + C
> tiup playground nightly --tag upgrade --db 3 --db.binpath=~/github/tidb/bin/tidb-server
> 
Side effects
Documentation
```release-note
None
```
=> domain: avoit to print too many log if the ddl job of runaway table is not finished

pkg/executor/internal/mpp/local_mpp_coordinator.go
Issue Number: close #52406
Problem Summary: check issue for detail description
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix mppIterator memory leak when got error

pkg/expression/builtin_cast.go, pkg/expression/constant_fold.go, pkg/expression/constant_test.go, pkg/expression/context/context.go, pkg/expression/contextimpl/sessionctx.go, pkg/expression/contextimpl/sessionctx_test.go, pkg/expression/expression.go, pkg/planner/core/rule_predicate_push_down.go, pkg/sessionctx/stmtctx/stmtctx.go
Issue Number: ref #52366
Added more methods in `expression.BuildContext`
- `AllocPlanColumnID` to allocate column id for Column expression.
- `SetInUnionCast` / `IsInUnionCast` is used when building expressions in union cast.
- `SetInNullRejectCheck` / `IsInNullRejectCheck` is used for bull reject check when building plan.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: Move more methods from `SessionVars` to `BuildContext`

pkg/ddl/job_table.go, pkg/ddl/reorg.go
Issue Number: close #52411
```
mysql> select count(1) from sbtest1 use index ();
+----------+
| count(1) |
+----------+
|  5000000 |
+----------+
1 row in set (0.58 sec)
mysql> select count(1) from sbtest1 use index (idxc);
+----------+
| count(1) |
+----------+
|  4999999 |
+----------+
1 row in set (0.85 sec)
```
```
[2024/04/09 09:53:12.953 +08:00] [ERROR] [reporter.go:274] ["admin check found data inconsistency"] [conn=3848273922] [session_alias=] [table_name=sbtest2] [index_name=idxc] [row_id=5134965]
```
```
mysql> select tidb_decode_key('7480000000000000e85f7280000000004e5a75');
+-----------------------------------------------------------+
| tidb_decode_key('7480000000000000e85f7280000000004e5a75') |
+-----------------------------------------------------------+
| …
```
=> ddl: fix reorg info end key after resuming from checkpoint

pkg/config/config.go
Issue Number: close #52453
concurrently-init-stats is a new feature, it should be disabled by default when it is published first.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> config: set concurrently-init-stats false by default

pkg/ddl/syncer/BUILD.bazel, pkg/ddl/syncer/syncer.go, pkg/ddl/syncer/syncer_test.go, pkg/ddl/util/util.go
Issue Number: close #47060 and close #52335
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: make sure put key into ETCD monotonously

pkg/executor/distsql.go, pkg/executor/index_merge_reader.go, pkg/executor/internal/builder/builder_utils.go, pkg/executor/table_reader.go, pkg/planner/context/context.go, pkg/planner/core/physical_plan_test.go, pkg/planner/core/plan.go, pkg/planner/core/plan_to_pb.go, pkg/planner/core/point_get_plan.go, pkg/planner/core/runtime_filter.go, pkg/planner/core/util.go, pkg/session/session.go, pkg/sessionctx/context.go, pkg/sessionctx/stmtctx/stmtctx.go, pkg/util/mock/context.go
Issue Number: close #52368
The `PlanCtx` is too big to call `ToPB` method. We can use a much smaller context for `ToPB` method.
Use a smaller struct to represent all information needed by the `ToPB` method call.
Tests 
> 
> Should be covered by existing tests.
Side effects
Documentation
```release-note
None
```
=> executor, planner: add a smaller context for `ToPB` method

br/pkg/conn/BUILD.bazel, br/pkg/conn/conn.go, br/pkg/conn/conn_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/52095 https://github.com/pingcap/tidb/issues/52094
the backoff case will cost too mush time.
use failpoint and return parse error immediately.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> test: fix TestGetMergeRegionSizeAndCount test

br/pkg/stream/rewrite_meta_rawkv_test.go, build/BUILD.bazel, build/linter/misspell/analyzer.go, build/nogo_config.json, pkg/ddl/stat_test.go, pkg/executor/aggfuncs/func_group_concat.go, pkg/executor/test/aggregate/aggregate_test.go, pkg/planner/core/logical_plans_test.go, pkg/planner/core/memtable_predicate_extractor.go, pkg/planner/funcdep/fd_graph_test.go, pkg/server/conn_stmt_test.go, pkg/sessionctx/variable/session.go
Issue Number: close #52450, ref #52449
Enable two linters: `appends` and `unusedwrite`.
Tests 
> Simple syntax change. They should already be covered by existing test.
> 
Side effects
Documentation
```release-note
None
```
=> linter, *: enable linters appends and unusedwrite

pkg/store/copr/coprocessor.go, pkg/store/mockstore/unistore/cophandler/closure_exec.go
Issue Number: close #52460 
If this cop is not a stale read, which means its start_ts is fetched from PD, which means the start_ts cannot conflict with other transactions, add this ts to resolved_locks so that in a pipelined txn the locks belonging to the same txn will not block coprocessor.
For get and batch_get, they already put start_ts in resolved_locks.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> cop: ignore locks with the same start_ts

pkg/statistics/handle/bootstrap.go
Issue Number: close #52466
forcely use index to order when to init stats
Tests 
before:
You will see that sort will be executed in the tidb.
after:
> 
Side effects
Documentation
```release-note
None
```
=> statstics: forcely use index to order when to init stats

pkg/planner/core/find_best_task.go, pkg/planner/core/plan.go, pkg/planner/core/task.go, pkg/planner/core/task_base.go
Issue Number: ref https://github.com/pingcap/tidb/issues/52181
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: refine mppTask as capital one for latter pkg move

pkg/ddl/column.go, pkg/ddl/internal/session/session_pool.go, pkg/expression/context.go, pkg/expression/context/context.go, pkg/expression/contextimpl/sessionctx.go, pkg/expression/contextimpl/sessionctx_test.go, pkg/expression/contextopt/optional_test.go, pkg/expression/contextopt/sessionvars.go, pkg/expression/helper.go, pkg/expression/helper_test.go, pkg/planner/core/memtable_predicate_extractor_test.go, pkg/session/session.go, pkg/table/column.go
Issue Number: ref #52366
Some codes are using `BuildContext.GetSessionVars().Location()` to read the time zone info. Because we are going to remove `GetSessionVars` in the future, it's better to replace it with `BuildContext.Location()`.
We should notice that `SessionVars.Location()` reads the timezone info from another place that is different from `BuildContext.Location()`. When replacing it, we should ensure they are same to avoid to introduce new bugs.
- replaced `BuildContext.GetSessionVars().Location()` with `BuildContext.Location()` .
- To make sure the logic is the same after the PR, we add some asserts to check the timezone info in sessionVars and statement context is the same.
- Modify some tests to make sure the asserts can pass.
Tests 
> - [ ] I checked and no …
=> expression: `BuildContext` read location from `EvalContext` instead of `SessionVars`

pkg/executor/executor.go, pkg/expression/expression.go, pkg/expression/expression_test.go
Issue Number: close #52366
Before this PR, `ColumnInfos2ColumnsAndNames` is not thread-safe because it will modify the inner state of context to force ignore truncate error. It's better to make it thread-safe and remove calls of `GetSessionVars` in it. 
Add `ignoreTruncateExprCtx` to ignore the truncate error and make `ColumnInfos2ColumnsAndNames` thread safe
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: create a new context in `ColumnInfos2ColumnsAndNames` to ignore truncate error

pkg/executor/builder.go, pkg/executor/executor_failpoint_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/51693
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix goroutine leak when builder panic

pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/find_best_task.go, pkg/planner/core/planbuilder.go, pkg/planner/core/task.go, pkg/planner/core/task_base.go
Issue Number: ref https://github.com/pingcap/tidb/issues/52181
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: refine cop task as a capital one for latter pkg move

pkg/infoschema/bench_test.go, pkg/infoschema/infoschema.go, pkg/infoschema/infoschema_test.go, pkg/infoschema/infoschema_v2.go, pkg/sessionctx/variable/tidb_vars.go
1. Previously, when we build is, we iterate all tables and try to use policyRefs on each table.
2. Now, cache all policyRef then don't need to iterate all tables through network each time we build is.
Before:
bench_test with 10000 tables for v2 can't finished within 30min.
After:
1.  bench_test with 10000 tables for v2 cost 38s.
2. bench_test with 10000 tables for v1 cost 30s.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> infoschema_v2: cache policy ref

pkg/lightning/mydump/loader.go, pkg/lightning/mydump/loader_test.go
Issue Number: close #52518
If the Parquet file is empty, directly set the size to be 0.
Tests 
> 
Side effects
Documentation
```release-note
Importing empty tables via Parquet no longer crash.
```
=> lightning: return 0 early on empty parquet files

pkg/ddl/ddl_api.go, pkg/ddl/tests/tiflash/ddl_tiflash_test.go
Issue Number: close #51990
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: make alter database set tiflash replica skip sequence and view

pkg/executor/sortexec/sort.go
Issue Number: close #52281 #52428 #52526
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: fix data race in the sortexec

br/pkg/lightning/mydump/loader.go, br/pkg/lightning/mydump/loader_test.go
This is an manual cherry-pick of #52519
Issue Number: close #52518
If the Parquet file is empty, directly set the size to be 0.
Tests 
> 
Side effects
Documentation
```release-note
Importing empty tables via Parquet no longer crash.
```
=> lightning: return 0 early on empty parquet files (#52519)

pkg/executor/builder.go, pkg/executor/sample.go, pkg/planner/core/find_best_task.go, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/physical_plans.go, tests/integrationtest/r/executor/sample.result, tests/integrationtest/t/executor/sample.test
Issue Number: close #52282
When `tidb_partition_prune_mode` is `static`, TiDB uses a separate operator to union results from different partitions. But `tablesample` always collects samples from all partitions, the result may contains duplicated rows.
Pass `physicalTableID` to `TableSampleExecutor`, now it only collect samples from corresponding partitions.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: make tablesample work under different partition prune modes

pkg/statistics/handle/bootstrap.go, pkg/statistics/handle/cache/statscache.go, pkg/statistics/handle/util/util.go, pkg/statistics/table.go
Issue Number: close #52553
GetFullTableName only is used in the write, but nothing will read it. so we can remove this useless function.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: remove useless GetFullTableName 

pkg/distsql/BUILD.bazel, pkg/distsql/request_builder.go, pkg/executor/BUILD.bazel, pkg/executor/table_reader.go, pkg/infoschema/context/BUILD.bazel, pkg/infoschema/context/infoschema.go, pkg/infoschema/infoschema.go, pkg/infoschema/interface.go
Issue Number: close #52495
We have splited `PlanContext` into some tiny contexts (`BuildPBContext` and `RangerContext`). Now it's time to remove the `pctx` from `tableReaderExecutorContext`.
1. Remove the `pctx` from `tableReaderExecutorContext`.
2. Replace the `any` in `distsql` into `MetaOnlyInfoSchema` (I don't know why it's originally `any`. Maybe it's used to avoid cyclic dependency?)
Tests 
> 
> Already be covered by existing tests.
Side effects
Documentation
```release-note
None
```
=> distsql, executor: remove pctx from trectx

pkg/util/cgroup/cgroup_cpu_linux.go
Issue Number: close #52612
Problem Summary: The CDC cli will print a redundant log and we could remove it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> cgroup: remove redundant log

pkg/server/BUILD.bazel, pkg/server/conn.go, pkg/server/conn_test.go, pkg/server/metrics/metrics.go
Issue Number: close https://github.com/pingcap/tidb/issues/52605
Tests 
```release-note
None
```
=> server: fix the missing type of query total counter for resource groups above 2

pkg/ddl/backfilling_operators.go, pkg/ddl/ingest/BUILD.bazel, pkg/ddl/ingest/checkpoint.go, pkg/ddl/ingest/flush.go, tests/realtikvtest/addindextest3/operator_test.go
Issue Number: close #52640
When temp-dir have no enough space, TiDB should flush index records to TiKV automatically. This has been implemented in the local ingest mode, but not in the distributed local sort mode.
Add flush check for local distributed sort according to the fix in #52178.
Tests 
Before this PR, add index cannot finish.
After this PR,
```
mysql> admin show ddl jobs 1;
+--------+---------+------------+------------------------+--------------+-----------+----------+------------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE               | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT  | CREATE_TIME         | START_TIME          | END_TIME            | STATE  | …
```
=> ddl: flush index records for local distributed sort

pkg/executor/analyze_col.go, pkg/executor/analyze_col_v2.go
Issue Number: close #52601
1、In v7.5, we have optimized the memory usage for analyze. so it is hard to OOM now.
2、If OOM happens， we should tell users about the oom event. we should not change the sample rate of the table. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: remove the retry for analyze

pkg/statistics/scalar.go
Issue Number: close https://github.com/pingcap/tidb/issues/52343
We don't need to re-alloc anything since we only read from the chunk, no modification after reading it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> statistics: reduce small obj alloc for PreCalculateScalar

pkg/util/execdetails/execdetails.go
Issue Number: close https://github.com/pingcap/tidb/issues/52646
Introduced by https://github.com/pingcap/tidb/pull/51726
The remote_regions and min_remote_stream is 0, but the max_remote_stream is the same as max_local_stream
Fix the field name
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that `max_remote_stream` shown in execution info is not correct
```
=> execdetails: Fix max_remote_stream shown in `execution info.tiflash_task`

dumpling/install.sh, dumpling/tests/run.sh
Issue Number: ref https://github.com/pingcap/tidb/issues/52473
* installing third-party tools requires specifying the version to avoid incompatible changes as time goes by.
* fix test utils load path
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: tools in scripts use fixed version to avoid incompatible updates

br/pkg/restore/client_test.go, br/pkg/utils/backoff.go
Issue Number: close #52547
the flaky test `TestGetTSWithRetry` takes too much time.
less retry
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: fix flaky test

pkg/expression/context/context.go, pkg/expression/contextimpl/sessionctx.go, pkg/expression/contextimpl/sessionctx_test.go, pkg/expression/util.go, pkg/planner/core/expression_rewriter.go, pkg/planner/core/logical_plan_builder.go, pkg/table/column.go, pkg/table/tables/tables.go
Issue Number: close #52366
- Add a new method `InInsertOrUpdate` in `BuildContext` to indicate whether we are building an expression in insert or update statement for some special logics in `CastColumnValue`. Because it is coupled with the statement, we marked it as "deprecated and" considering removing it in the future. However, we keep it as it is now to avoid introducing new bugs.
- Remove `GetSessionVars` in `BuildContext`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: Add `InInsertOrUpdate` in `BuildContext` and remove `GetSessionVars`

pkg/ddl/db_test.go, pkg/ddl/job_table.go
Issue Number: close #52589
Didn't handle the schema id for `truncate table`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: fix incorrect `truncate table`'s scheme_ids 

br/tests/README.md, br/tests/download_integration_test_binaries.sh, br/tests/run.sh
Issue Number: close #52690
Update the manual of integration tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: update manual of integration tests

br/pkg/streamhelper/BUILD.bazel, br/pkg/streamhelper/advancer.go, br/pkg/streamhelper/advancer_test.go, br/pkg/streamhelper/flush_subscriber.go
Issue Number: close #52597 
1. When losing the advancer ownership, the channel for subscription may be full. 
2. the consumer has already gone due to the canceled context. Hence making the producer(subscription) goroutine stuck.
3. After the graceful shutdown period, the output channel will be eventually closed and we will get a `send on closed channel` panic.
- When sending to the channel, also select the context.
- Catch all panic and convert them to errors (so we can retry.) 
Tests 
> 
Side effects
Documentation
```release-note
Fixed a bug …
```
=> log_backup: fix panic during advancer owner transfer

pkg/expression/distsql_builtin.go, pkg/expression/expr_to_pb_test.go, pkg/expression/infer_pushdown.go
Issue Number: close #50601
```
-- Create the table
CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
attributes JSON
);
-- Insert some sample data
INSERT INTO products (name, attributes) VALUES
('Product A', '{"color": "Red", "size": "Medium"}'),
('Product B', '{"color": "Blue", "size": "Small"}');
-- Example usage of JSON_REPLACE()
explain analyze
select *
from products
where 
JSON_REPLACE(attributes, '$.color', 'Green') = JSON_OBJECT('color', 'Green', 'size', 'Medium');
+-------------------------+---------+---------+-----------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> expression/infer_pushdown: enable json_replace/json_array_append/json_merge_patch pushdown

lightning/OWNERS
Issue Number: close #52744 
lightning/OWNERS is not correctly updated when moving lightning directory out of br.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: update lightning/OWNERS for moving lightning directory out of br

pkg/util/stmtsummary/v2/tests/BUILD.bazel, pkg/util/stmtsummary/v2/tests/table_test.go
Problem Summary: planner: add more test cases for unqualified plan cache cases in statement_summary
planner: add more test cases for unqualified plan cache cases in statement_summary
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: add more test cases for unqualified plan cache cases in statement_summary

pkg/ddl/db_integration_test.go, pkg/ddl/table.go, pkg/meta/meta.go, pkg/meta/meta_test.go
Issue Number: close #52680 
After https://github.com/pingcap/tidb/pull/39041, `CreateTableAndSetAutoID` do not set the auto id correctly.
We should recover RowID, AutoIncrementID, RandomID..
P.S. drop table do not remove auto id entry in autoid service, this is not a problem.
Tests 
Follow the steps described in the issue.
> 
Side effects
Documentation
```release-note
None
```
=> meta,ddl: fix duplicate entry error when insert after drop and recover table

br/pkg/streamhelper/subscription_test.go
Issue Number: close #52791, close #52792
When dropping a subscription manager, the pending events will be dropped. So the test case will fail.
Wait until it seems there isn't new events.
Tests 
```console
> go test --count=100 -run '^TestSomeOfStoreUnsupported|TestStoreRemoved$' github.com/pingcap/tidb/br/pkg/streamhelper
ok      github.com/pingcap/tidb/br/pkg/streamhelper     40.463s
```
> 
Side effects
Documentation
```release-note
None
```
=> br: fix flaky test `TestStoreRemoved`

pkg/ddl/ddl_running_jobs.go, pkg/ddl/ingest/backend_mgr.go, tests/realtikvtest/addindextest4/ingest_test.go
Issue Number: ref #52596
Tests 
> 
1. global sort + add index, 1 large table + 1 small table
```
mysql> admin show ddl jobs;
+--------+---------+-------------------------+------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------------+
| JOB_ID | DB_NAME | TABLE_NAME              | JOB_TYPE                     | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE         |
+--------+---------+-------------------------+------------------------------+----------------------+-----------+----------+-----------+---------------------+---------- …
```
=> ddl: allow multiple fast reorg running at the same time

pkg/statistics/handle/syncload/stats_syncload.go, pkg/statistics/handle/syncload/stats_syncload_test.go
Issue Number: close #52827
when ```singleflight``` meets timeout, some goroutines will concurrently use reuse session. we should keep everyone using independent sessions.
Tests 
run it in the HA, It can pass test.
> 
Side effects
Documentation
```release-note
None
```
=> *: avoid concurrently using the session in the syncload 

pkg/expression/context/context.go, pkg/expression/contextsession/sessionctx.go, pkg/expression/contextsession/sessionctx_test.go, pkg/table/column.go, tests/integrationtest/r/ddl/column_type_change.result, tests/integrationtest/r/ddl/db_integration.result, tests/integrationtest/r/ddl/default_as_expression.result, tests/integrationtest/r/ddl/modify_column.result, tests/integrationtest/r/ddl/multi_schema_change.result, tests/integrationtest/t/ddl/column_type_change.test
Issue Number: close #52715, close #52509, close #52748
The function `table.castColumnValue` requires an argument `insertOrUpdate` to indicate whether it is called in an insert or update statement. However, I found this may be a mistake.
If we define the semantic of `CastColumnValue` as "cast a value to another to fit the column to meet the column's restriction", it is not reasonable that the select and insert statements have different behaviors. You can see the issue #52509 that there is a problem if we do not handle the datetime conversion error for a select statement.
A similar issue also exists in the alter statement, see #52748. You can see that if we do not handle the datetime error there, the table will store a wrong timestamp value.
I think it's better to remove …
=> expression: remove `InInsertOrUpdate` in `BuildExpression`

pkg/expression/BUILD.bazel, pkg/expression/constant_test.go, pkg/expression/context/context.go, pkg/expression/contextsession/sessionctx.go, pkg/expression/contextsession/sessionctx_test.go, pkg/planner/context/context.go, pkg/planner/contextimpl/BUILD.bazel, pkg/planner/contextimpl/impl.go, pkg/planner/core/rule_predicate_push_down.go, pkg/util/mock/context.go
Issue Number: close #52719
It's better to remove the method `SetInNullRejectCheck` in `BuildContext` because it will modify its internal state and be not thread-safe in the concurrency scene.
We removed `SetInNullRejectCheck` in `BuildContext` but kept `IsInNullRejectCheck` to do a null reject check. So for most implementations of `BuildContext`, `IsInNullRejectCheck` always returns false. If we want to make it return `true`, use `WithNullRejectCheck` to create a new context.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: remove `SetInNullRejectCheck` in `BuildContext`

pkg/expression/bench_test.go, pkg/expression/builtin_cast.go, pkg/expression/builtin_cast_test.go, pkg/expression/context/context.go, pkg/expression/contextsession/sessionctx.go, pkg/expression/contextsession/sessionctx_test.go, pkg/planner/core/expression_rewriter.go
Issue Number: close #52707
It's better to remove `InUnion/SetInUnion`  in `BuildContext` in two reasons:
1. It is an intermediate and set inside by the build function itself only. Removing it can make `BuildContext` more simple.
2. If `BuildContext` is used in concurrency, `InUnion/SetInUnion` may cause a data race.
Remove `InUnion/SetInUnion` in `BuildContext` and move the "in union" state to argument.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: remove `InUnion/SetInUnion` in `BuildContext`

br/pkg/restore/import.go, br/pkg/restore/import_retry_test.go, br/pkg/restore/split/mock_pd_client.go, br/pkg/restore/split/split.go, br/pkg/restore/split/split_test.go, pkg/lightning/backend/local/BUILD.bazel, pkg/lightning/backend/local/duplicate.go, pkg/lightning/backend/local/region_job.go
Issue Number: close #51124 close #50501
the leader of region, scanned from PD, is nil
check regions' leader after scan from PD.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: handle region leader miss

pkg/planner/core/casetest/planstats/main_test.go, pkg/sessionctx/stmtctx/BUILD.bazel, pkg/sessionctx/stmtctx/stmtctx.go, pkg/statistics/handle/syncload/BUILD.bazel, pkg/statistics/handle/syncload/stats_syncload.go, pkg/statistics/handle/syncload/stats_syncload_test.go, pkg/statistics/handle/types/BUILD.bazel, pkg/statistics/handle/types/interfaces.go
Issue Number: close #52797
All items the query needs will be put into the global task channel( the default capacity is 1000). And workers will merge the same task with the singleflight. So performance depends on the number of tasks that can be concurrently executed. 
Under poor performance conditions, he will not be able to handle a sufficient number of tasks, resulting in slow processing. But there are still many same tasks in the channel. So they still need to check whether to sync load. And They will fill up this channel. Query can not insert the sync load task into it and load necessary stats.
So we need to refactor this code. We need first to let the query pass through singleflight to merge identical tasks. Then insert the task into the channel to make the worker …
=> statistics: support global singleflight for sync load

DEPS.bzl, go.mod, go.sum, pkg/executor/test/oomtest/oom_test.go, pkg/server/conn_test.go
Issue Number: close #52464
Problem Summary: `LocateKey` may returns a wrong region
The fix is included in https://github.com/tikv/client-go/pull/1299, thus bump up client-go.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: bump up client-go to fix #52464

pkg/server/conn_stmt_params.go, pkg/server/internal/testserverclient/BUILD.bazel, pkg/server/internal/testserverclient/server_client.go, pkg/server/tests/commontest/BUILD.bazel, pkg/server/tests/commontest/tidb_test.go
Issue Number: close #52711
After sending the param through `SEND_LONG_DATA`, it's still possible that the type is given in the `EXECUTE` statement. But actually I'm not sure whether every client sends the type, so I kept the original behavior if the type is not sent to keep compatibility.
Assert whether the type is sent in `EXECUTE` statement. If it's sent, use the given `type. If it's not sent, still use the `Blob` to keep compatible with the original behavior.
Tests 
> 
I tried to run the program https://gist.github.com/YangKeao/51bbc88600c69691a799227806f32cd5 on TiDB.
Before this PR, the data in table t after running this program is 
```
| utf8     | "你好"      | "你好"                            | 0x22E4BDA0E5A5BD22       |
| utf8 …
```
=> server: handle the case the type of param is set for the param sent by `SEND_LONG_DATA`

pkg/infoschema/bench_test.go, pkg/infoschema/infoschema.go, pkg/infoschema/infoschema_test.go, pkg/infoschema/infoschema_v2.go
Revert https://github.com/pingcap/tidb/pull/52474 manually.
Because of a mistake by me
https://github.com/pingcap/tidb/pull/52156/commits/de93c054ca9daf639ad5f469c2d33a2a2fd14e74
the CI is not really running infoschema v2 https://github.com/pingcap/tidb/issues/52753
Then the following commit introduce regression, a lot of cases failed after that.
```
building task finish, parallelism=32, count=5133, takes=12m36.921561143s
[FAIL]  pkg/ddl TestDropTableWithPlacement
[FAIL]  pkg/ddl TestCreateSchemaWithPlacement
[FAIL]  pkg/expression/integration_test TestCrossDCQuery
[FAIL]  pkg/ddl TestPolicyCacheAndPolicyDependency
[FAIL]  pkg/executor TestShowPlacementForTableAndPartition
[FAIL]  pkg/ddl TestAlterTablePartitionWithPlacementPolicy
[FAIL] …
```
=> pkg/infoschema: revert cache policy ref

br/pkg/streamhelper/advancer.go, br/pkg/streamhelper/advancer_env.go, br/pkg/streamhelper/advancer_test.go, br/pkg/streamhelper/basic_lib_for_test.go, br/pkg/streamhelper/regioniter.go, br/pkg/streamhelper/regioniter_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/52082
1. Advancer didn't handle GC response correct, if set the safepoint smaller(Normally it won't happen, because the ts from advancer always closed to the current time(RPO <= 5min)) than current service safepoint, it still get the response without error. 
2. Set service safepoint to 0 won't delete the value.
1. handle the response with smaller ts request.
2. add new interface to remove service safepoint.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that del task …
```
=> advancer: fix the incorrect gc safepoint behaviours

pkg/executor/benchmark_test.go, pkg/executor/insert_common.go, pkg/executor/union_scan_test.go, pkg/executor/update.go, pkg/executor/write.go
Issue Number: close https://github.com/pingcap/tidb/issues/52783
Add stack when necessary.
master vs. this PR for `completeInsertErr`
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -tags intest,deadlock -bench ^BenchmarkCompleteInsertErr$ github.com/pingcap/tidb/pkg/executor
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/executor
BenchmarkCompleteInsertErr-8   	  383056	      3115 ns/op	     712 B/op	       8 allocs/op
PASS
ok  	github.com/pingcap/tidb/pkg/executor	4.654s
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -tags intest,deadlock -bench ^BenchmarkCompleteInsertErr$ github.com/pingcap/tidb/pkg/executor
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/executor
BenchmarkCompleteInsertErr-8   	 3575682	       332.1 …
```
=> executor: remove unnecessary stack for insert and load data

Makefile, pkg/statistics/handle/ddl/ddl.go, tests/realtikvtest/flashbacktest/flashback_test.go
Issue Number: close #52898
Problem Summary: After https://github.com/pingcap/tidb/pull/52285, flashbacktest alwayws failed with error info like
```
[r="assert failed, schemaID should not be 0, please set it when creating the event"]
[stack="[github.com/pingcap/tidb/pkg/util.Recover](http://github.com/pingcap/tidb/pkg/util.Recover)
/home/genius/project/src/[github.com/pingcap/tidb/pkg/util/misc.go:118](http://github.com/pingcap/tidb/pkg/util/misc.go:118)
runtime.gopanic
/home/genius/project/go/src/runtime/panic.go:914
[github.com/pingcap/tidb/pkg/util/intest.doPanic](http://github.com/pingcap/tidb/pkg/util/intest.doPanic)
/home/genius/project/src/[github.com/pingcap/tidb/pkg/util/intest/assert.go:59](http://github.com/pingcap/tidb/pkg/util/intest/assert.go:59) …
```
=> flashback: fix `realtikvtest/flashbacktest` test cases

pkg/executor/index_lookup_hash_join.go, pkg/executor/test/jointest/hashjoin/BUILD.bazel, pkg/executor/test/jointest/hashjoin/hash_join_test.go
Issue Number: close #52902 
In IndexHashJoin inner work, we use join type to check if redundant matched rows should be appended to JoinResult. However, only semi and leftOuterSemi is recongnized:
https://github.com/pingcap/tidb/blob/8ba1fa452b1ccdbfb85879ea94b9254aabba2916/pkg/executor/index_lookup_hash_join.go#L739-L752
While anti-semi join doesn't care matched rows, left outer anti semi will append joined rows, thus caused the problem.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: Fix index join hash produces redundant rows for left outer anti semi join type

WORKSPACE, build/nogo_config.json
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: upgrade rules_go

pkg/planner/core/task.go
Issue Number: ref #52828 
In #52836, we added missing "hashCols" to the added projection's schema, since they may be needed by potential type cast projection. However, the way we added is somewhat problemtic, we directly added from the hashCols instead of HashJoin's output schema:
https://github.com/pingcap/tidb/blob/c73d6c5a98ad76df5b97b25dc8c90d1df2e8be35/pkg/planner/core/task.go#L447-L453
While from the existing getProj implementation, we need to add from child executor's schema, and cloned it also(not sure if it is needed), since inside the schema.Clone() function column is cloned actually:
https://github.com/pingcap/tidb/blob/c73d6c5a98ad76df5b97b25dc8c90d1df2e8be35/pkg/planner/core/task.go#L272-L282
After fixing this, we can pass all tiflash's randgen mpp tests in …
=> planner: Fix mpp join column prune added projection incorrect construction

pkg/server/internal/dump/dump_test.go
Issue Number: close #52345
Change the TZ used in `TestDumpBinaryTime` from `Local` to `UTC` to fix invalid time when the system TZ is `Egypt`.
Tests 
Side effects
-  None
Documentation
- NA
```release-note
None
```
=> server, test: fix a minor TZ issue in TestDumpBinaryTime

pkg/bindinfo/capture_test.go
Issue Number: close #40297
Problem Summary: planner: fix the unstable test TestCaptureWildcardFilter
the old implementation of Capture is considered as deprecated
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix the unstable test TestCaptureWildcardFilter

br/pkg/backup/prepare_snap/BUILD.bazel, br/pkg/backup/prepare_snap/prepare.go, br/pkg/task/operator/BUILD.bazel, br/pkg/task/operator/cmd.go, tests/realtikvtest/brietest/operator_test.go
Issue Number: close #52846 
When we failed to prepare the connections for wait apply, the channel may never be closed. Hence the pause PD operation (which relies on the finishing of the prepare connections stage) get stuck.
Selected over the context so it can be canceled.
Tests 
> 
> The change is almost trivial.
Side effects
Documentation
```release-note
None
```
=> br/operator: fix adapt env for snapshot backup stuck when encountered error

DEPS.bzl, go.mod, go.sum
Issue Number: close #52193, close #50758
Problem Summary: There are some client-go side issues need to be fixed for release 7.5
Bump up client-go to pick those fixes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: bump up client-go to fix #52193 & #50758

pkg/expression/context/context.go, pkg/expression/contextstatic/BUILD.bazel, pkg/expression/contextstatic/evalctx_test.go, pkg/expression/contextstatic/exprctx.go, pkg/expression/contextstatic/exprctx_test.go, pkg/sessionctx/variable/sysvar.go, pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #52852
Just like #52631, we provide a static implementation for `ExprContext`. You can use `NewStaticExprContext` to create it:
```
ctx := NewStaticExprContext(
WithEvalCtx(evalCtx),
WithCharset("gbk", "gbk_bin"),
// ...
)
```
You can also use `Apply` to create a new context with specified context updated:
```
ctx2 := ctx.Apply(
WithEvalCtx(evalCtx),
WithCharset("gbk", "gbk_bin"),
// ...
) 
``` 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: introduce `StaticExprContext` to build expressions

pkg/executor/internal/exec/BUILD.bazel, pkg/executor/internal/exec/executor.go
We need to make chunk small enough to trigger multiple flushes in tests.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor: add failpoints to control chunk size

pkg/expression/contextsession/sessionctx.go, pkg/expression/contextsession/sessionctx_test.go, pkg/lightning/backend/kv/session.go, pkg/session/BUILD.bazel, pkg/session/bootstrap_test.go, pkg/session/contextimpl.go, pkg/session/session.go, pkg/util/mock/context.go
Issue Number: close #52838
In the previous code, we use `ExprCtxExtendedImpl` to extend `sessionctx.Context` to make sure all the implementations of `ExpressionContext` can also implement `SQLExecutor` or some other interfaces for some scenes need to do some force type casting. However, after several PRs of refactoring, this is not necessary now. So we can change `ExprCtxExtendedImpl` to `SessionExprContext`. It is more simple.
change `ExprCtxExtendedImpl` to `SessionExprContext`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: change `ExprCtxExtendedImpl` to `SessionExprContext`

br/pkg/storage/memstore.go, br/pkg/storage/storage.go, pkg/lightning/backend/external/writer.go, pkg/lightning/backend/external/writer_test.go
Issue Number: close #52884
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> global sort: fix inner retry doesn't reset collector

pkg/ddl/multi_schema_change.go, pkg/infoschema/BUILD.bazel, pkg/infoschema/builder.go, pkg/infoschema/builder_test.go, pkg/parser/model/ddl.go, tests/integrationtest/r/ddl/multi_schema_change.result, tests/integrationtest/t/ddl/multi_schema_change.test
Issue Number: close #47899
Tests 
for the case in the issue
```sql
mysql>  create table t (a int not null auto_increment primary key, b int) auto_id_cache 100;insert into t (b) values (1);
Query OK, 0 rows affected (0.09 sec)
Query OK, 1 row affected (0.01 sec)
mysql> select * from t;
+---+------+
| a | b    |
+---+------+
| 1 |    1 |
+---+------+
1 row in set (0.00 sec)
mysql> alter table t add column c int, auto_increment 200;
Query OK, 0 rows affected (0.31 sec)
mysql> insert into t (b) values (2);
Query OK, 1 row affected (0.01 sec)
mysql> select * from t;
+-----+------+------+
| a   | b    | c    |
+-----+------+------+
|   1 |    1 | NULL |
| 200 |    2 | NULL |
+-----+------+------+
2 rows in set (0.00 sec)
```
> - [ ] I checked and no code files have been …
=> infoschema: load auto id related changes for multi-schema-change diff | tidb-test=pr/2320

DEPS.bzl, go.mod, go.sum
Issue Number: close #53011 ref #50215
The client-go patch let the pipelined DML abort once the max ttl is exceeded, and avoid writing useless locks which slow down GC.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: bump client-go to fix #53011

pkg/planner/core/integration_test.go, pkg/planner/core/rule_join_reorder.go
Issue Number: close #46556
Problem Summary: planner: add projections to keep join keys as `col=col` 
In some cases, after creating  new EQ function, the 2 args might not be column anymore, which breaks the assumption that join eq keys must be `col=col`, to handle this, inject 2 projections.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: add projections to keep join keys as `col=col` 

tests/integrationtest/r/ddl/default_as_expression.result, tests/integrationtest/t/ddl/default_as_expression.test
Issue Number: close https://github.com/pingcap/tidb/issues/53024
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tests/ddl: make default_as_expression test stable

pkg/executor/show.go, pkg/planner/core/base/BUILD.bazel, pkg/planner/core/base/misc_base.go, pkg/planner/core/logical_plans.go, pkg/planner/core/physical_plans.go, pkg/planner/core/show_predicate_extractor.go, pkg/planner/core/stringer.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move ShowPredicateExtractor interface to base package out of core

pkg/infoschema/tables.go
Issue Number: close #52842.
Tests 
> 
Use tiup to deploy a cluster and execute `select * from cluster_info;` with 3 PD.
Side effects
Documentation
```release-note
None
```
=> infoschema: try other PDs if one cannot serve the request

br/pkg/lightning/common/retry.go, br/pkg/lightning/common/retry_test.go, br/pkg/pdutil/pd.go, tests/realtikvtest/brietest/BUILD.bazel, tests/realtikvtest/brietest/pdutil_test.go
Issue Number: close #53029
In a tidb-operator deployed cluster, sometimes coredns responses `No such host` which will abort the creation of `PDController`. We should  retry this sort of error. 
This PR added retry when the `net.Error` is `DNSError`.
Also, this PR increases the retry time limit from 10 times (totally 10s) to 120 times (totally 120s).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br/pdutils: retry when encountered dns error

pkg/expression/util.go, pkg/planner/core/plan_cache.go, pkg/planner/core/plan_cache_utils.go, pkg/sessionctx/stmtctx/stmtctx.go
Problem Summary: planner: small refactor for plan cache
planner: small refactor for plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: small refactor for plan cache

br/pkg/lightning/common/retry.go, br/pkg/lightning/common/retry_test.go, br/pkg/pdutil/pd.go, tests/realtikvtest/brietest/BUILD.bazel, tests/realtikvtest/brietest/pdutil_test.go
Issue Number: close #53029
In a tidb-operator deployed cluster, sometimes coredns responses `No such host` which will abort the creation of `PDController`. We should  retry this sort of error. 
This PR added retry when the `net.Error` is `DNSError`.
Also, this PR increases the retry time limit from 10 times (totally 10s) to 120 times (totally 120s).
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br/pdutils: retry when encountered dns error (#53005)

pkg/executor/set_test.go, pkg/sessionctx/variable/sysvar.go, tests/realtikvtest/addindextest3/functional_test.go
Issue Number: close #52636
update the default value of tidb_analyze_skip_column_types and put all text series types into it.
Tests 
> 
Side effects
Documentation
```release-note
variable: add all text series types into tidb_analyze_skip_column_types
```
=> variable: add all text series types into tidb_analyze_skip_column_types | tidb-test=pr/2319

pkg/executor/builder.go, pkg/executor/index_merge_reader.go, pkg/executor/mem_reader.go, pkg/kv/key.go, pkg/planner/core/find_best_task.go, pkg/planner/core/indexmerge_path.go, tests/integrationtest/r/executor/partition/global_index.result, tests/integrationtest/r/globalindex/mem_index_merge.result, tests/integrationtest/t/globalindex/mem_index_merge.test, tests/realtikvtest/flashbacktest/BUILD.bazel
Issue Number: close #43013
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> *: global index support `index_merge` and `mem_index_merge`

MODULE.bazel.lock, br/pkg/backup/prepare_snap/BUILD.bazel, br/pkg/backup/prepare_snap/env.go, br/pkg/backup/prepare_snap/prepare.go, br/pkg/backup/prepare_snap/prepare_test.go, br/pkg/backup/prepare_snap/stream.go, br/pkg/task/operator/BUILD.bazel, br/pkg/task/operator/cmd.go, br/pkg/task/restore_data.go, br/pkg/utils/BUILD.bazel, br/pkg/utils/backoff.go, br/pkg/utils/backoff_test.go, br/pkg/utils/retry.go, tests/realtikvtest/brietest/operator_test.go
Issue Number: Ref #52846, #51448, #51957, #52175, #52243, #52049
N/A
This PR picks the following PRs:
- #52607
- #51449
- #51823
- #51886
- #52177
- #52264
- #52051
Tests 
> Because they are cherry-picks.
Side effects
Documentation
```release-note
None
```
=> br: pick some EBS backup bug fixes to 7.5

pkg/ddl/backfilling_operators.go, pkg/ddl/backfilling_scheduler.go, pkg/ddl/index_cop.go, pkg/ddl/ingest/backend.go, pkg/ddl/ingest/checkpoint.go, pkg/ddl/ingest/checkpoint_test.go, pkg/ddl/ingest/mock.go, pkg/ddl/internal/session/session.go, pkg/ddl/reorg.go, pkg/ddl/util/BUILD.bazel, pkg/ddl/util/util.go, pkg/ddl/util/util_test.go
Issue Number: close #53009
- use word "flushed"/"imported" to replace "local"/"global" to unify the terminology with lightning engine
- rename some methods
- remove `FlushModeForceLocalAndCheckDiskQuota` because it's not used
- use `ctx` to detect the closing of `CheckpointManager` and let other goroutine communications check the context
- add a tagged logger to `CheckpointManager`
- remove `updating` field because only one goroutine calls `updateCheckpoint`
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl: check local file existence before resume checkpoint

pkg/executor/inspection_result.go, pkg/executor/inspection_summary.go, pkg/executor/metrics_reader.go, pkg/planner/core/explain.go, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/logical_plans.go, pkg/planner/core/memtable_predicate_extractor.go, pkg/planner/core/memtable_predicate_extractor_test.go, pkg/planner/core/physical_plans.go, pkg/planner/core/planbuilder.go, pkg/planner/util/misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move QueryTimeRange structure to util pkg

pkg/table/tables/BUILD.bazel, pkg/table/tables/index_test.go, pkg/tablecodec/tablecodec.go, tests/integrationtest/r/table/index.result, tests/integrationtest/t/table/index.test
Issue Number: close #47115
Problem Summary: decoding an index value with large padding size might panic, because the padding size is:
- encoded via: `types.NewUintDatum(paddingSize) => encodeUint`
- decoded via `decodeRestoredValuesV5 => rd.DecodeToBytesNoHandle => rd.encodeOldDatum(IntFlag) => codec.EncodeVarint(buf, decodeInt(raw))` because the field type is not marked as unsigned in `buildRestoredColumn`.
Set unsigned flag to the field type correctly. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> tablecodec: fix the issue that decoding an index value might panic

pkg/expression/builtin_encryption.go, pkg/expression/builtin_encryption_test.go
Issue Number: close #53018
Problem Summary: md5 hash update
Performance optimization for md5 hash, use hex EncodeToString instead of fmt
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: update md5 hash to use hex

pkg/executor/compiler.go, pkg/executor/test/executor/executor_test.go, pkg/planner/core/common_plans.go, pkg/planner/core/plan_cache.go, pkg/sessiontxn/isolation/optimistic.go
Problem Summary: planner: simplify plan cache for fast point get
planner: simplify plan cache for fast point get
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: simplify plan cache for fast point get

pkg/domain/domain.go, pkg/infoschema/builder.go, pkg/infoschema/cache.go, pkg/infoschema/infoschema_test.go, pkg/infoschema/infoschema_v2.go, pkg/infoschema/test/infoschemav2test/v2_test.go
Issue Number: close #52683
ref #50959 
It's casued by compatibility issue between infoschema v2 and GC worker.
For infoschema v2, it contains a `ts` field, `SchemaTables` and `loadTableInfo` need this `ts` to get the corresponding schema meta snapshot.
We store the schemaTS as the `ts` of an infoschema v2 object in the past.
Whether it's `schemaTS` or `startTS` does not matter, because they both use the same schema version and data.
But when we're using `schemaTS`, it's not up to date.
For example, a DDL happened 30 minutes ago. (so the `ts` of infoschema v2 object is 30 min ago)
GC happened 10 minutes ago.
Now we get the infoschema v2 object, and use it, we would get the "GC life time is shorter than transaction duration" error.
Instead of using `schemaTS` for infoschema …
=> infoschema: keep the timestamp of infoschema v2 updating

pkg/extension/event_listener_test.go, pkg/extension/session.go, pkg/parser/ast/misc.go, pkg/planner/core/BUILD.bazel, pkg/planner/core/logical_plan_builder.go, pkg/planner/core/point_get_plan.go, pkg/planner/core/preprocess.go, pkg/planner/core/util_test.go, pkg/server/extension.go
Issue Number: close #50988
If the statement fails (`err != nil` in `RelatedTables`), traverse the AST to get all table names.
Tests 
> 
Side effects
Documentation
```release-note
fix a bug for audit log that table filters don't work when status_code is 0
```
=> extension: make `RelatedTables` work when the statement fails

pkg/executor/test/issuetest/BUILD.bazel, pkg/executor/test/issuetest/executor_issue_test.go, pkg/types/helper.go, pkg/types/helper_test.go
Issue Number: close #52978
The root cause is tidb's truncate function returns NaN for corner cases. While in topN executor, we compare float64 using go lib function which treats NaN as min:
https://github.com/pingcap/tidb/blob/81da4f8811f2fc150ed176d7ef3bcde3ce112d9f/pkg/util/chunk/compare.go#L113
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> executor,types: Fix truncate function behavior when second param is large negative

pkg/planner/core/plan_cache.go, pkg/planner/core/plan_cache_test.go, pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: simplify plan cache for fast point get
planner: simplify plan cache for fast point get
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: simplify plan cache for fast point get 

br/pkg/aws/BUILD.bazel, br/pkg/aws/ebs.go, br/pkg/aws/ebs_test.go
During EBS snapshot backup, if any snapshots fail, the backup will be stuck indefinitely checking the snapshots that failed. Since we only run a single backup at a time, this also blocks subsequent backups.
Issue Number: close #53037 
Problem Summary: Backup stuck when EBS snapshot failed
Update snapshot backup process to fail if it detects snapshots in failed state. We observe rare snapshot failures due to underlying EBS hardware issues.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> br: Fail backup if any snapshots failed

pkg/ddl/index.go, tests/integrationtest/r/ddl/index_modify.result, tests/integrationtest/t/ddl/index_modify.test
Issue Number: close #52510
when fast reorg and new collation are enabled, index backfilling only considers the need to restore the index columns, but ignores the primary key columns. The result is that the primary key in the index is not restored.
When considering the need to restore an index, check both the index columns and the primary key columns.
Tests 
> 
Side effects
Documentation
```release-note
- Fix the collation of the primary key in secondary indexes is wrong when tidb_ddl_enable_fast_reorg is enabled
```
=> ddl: fix the primary key in index is not in restored format

pkg/infoschema/tables.go
Issue Number: close #52842
Tests 
5 pd and let 2 of them down
```
[root@tiup-0 ~]# mysql -uroot -P4000 -h tidb2-peer
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 1891631112
Server version: 8.0.11-TiDB-v8.1.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MySQL [(none)]> select * from INFORMATION_SCHEMA.CLUSTER_INFO;
+-------+------------------+------------------+---------+------------------------------------------+---------------------+--------------------+-----------+
| TYPE  | INSTANCE         | STATUS_ADDRESS   | VERSION | GIT_HASH …
```
=> infoschema: fix the nil pointer

pkg/planner/core/BUILD.bazel, pkg/planner/core/cost/BUILD.bazel, pkg/planner/core/cost/factors_thresholds.go, pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/find_best_task.go, pkg/planner/core/indexmerge_path.go, pkg/planner/core/logical_plans.go, pkg/planner/core/physical_plans.go, pkg/planner/core/plan_cost_detail.go, pkg/planner/core/plan_cost_ver1.go, pkg/planner/core/stats.go, pkg/planner/core/task.go, pkg/planner/core/task_base.go, pkg/planner/implementation/BUILD.bazel, pkg/planner/implementation/simple_plans.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move cost factors to core/cost pkg

pkg/planner/core/logical_plan_builder.go, tests/integrationtest/r/planner/core/issuetest/planner_issue.result, tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #52687 
When we meet the subqueries, we'll rewrite the structure of the plan tree. We need to find a way to represent the subqueries in the UPDATE's lists
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: resolve panic when the update lists contain complex subquery

pkg/planner/core/plan_cache.go, pkg/planner/core/plan_cache_utils.go, pkg/planner/core/point_get_plan.go
Problem Summary: planner: simplify plan cache for fast point get
No regression:
```
BenchmarkPreparedPointGet-8   	  144712	      7141 ns/op  -- before
BenchmarkPreparedPointGet-8   	  148641	      7149 ns/op -- after
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: merge fast plan cache and normal plan cache

pkg/config/config.go, pkg/config/config_test.go, pkg/domain/domain.go, pkg/planner/core/casetest/planstats/plan_stats_test.go, pkg/session/BUILD.bazel, pkg/session/session.go, pkg/statistics/handle/syncload/stats_syncload.go, pkg/statistics/handle/syncload/stats_syncload_test.go
Issue Number: close #53157
sync load concurrency will be updated automatically according to the count of CPU core.
if sync load concurrency is set to 0.
Tests 
Now, log will print sync load concurrency. It is right.
> 
Side effects
Documentation
```release-note
statistics: support adaptive sync load concurrency
```
=> statistics: support adaptive sync load concurrency

DEPS.bzl, MODULE.bazel.lock, go.mod, go.sum
Issue Number: close #40926
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> copr: update client-go to fix #40926

pkg/lightning/config/config.go, pkg/lightning/config/config_test.go
Issue Number: close #53001
The behaviour should be the same as https://docs.pingcap.com/zh/tidb/stable/tidb-lightning-configuration
Tests 
> 
Side effects
Documentation
```release-note
Fix the behaviour of lightning configuration tidb.tls is not the same as document
```
=> lightning/config: align the behaviour of tidb.tls to doc

pkg/executor/join/join.go, pkg/executor/test/issuetest/BUILD.bazel, pkg/executor/test/issuetest/executor_issue_test.go
Issue Number: close #51998
In TiDB's hash join, there is a short path in probe side:
https://github.com/pingcap/tidb/blob/65817ac7bb7e1be956932331c3bee0bc47623baa/pkg/executor/join/join.go#L275-L277
If the probe side is empty, and current join use inner side to build, then the join can mark to finished without waiting the build side. This short-path can cause random fail for the case that probe side is empty, but build side may meet error during execution. In this case, there is a data race between build side and probe side:
* if probe side is detected to be empty before build side meet error, the hash join will return empty result without throwing error
* if probe side is detected to be empty after build side meet error, then hash join will throw error
This will cause …
=> executor: disable probe short path in hash join

pkg/infoschema/infoschema_v2.go
Issue Number: close #53158 
Retry on this kind of error: 
```
region 40 is in flashback progress, FlashbackStartTS is 449658828228919302
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> infoschema: fix flashback integration test to make it more stable

br/pkg/restore/db_test.go, pkg/ddl/job_table.go, pkg/infoschema/test/clustertablestest/cluster_tables_test.go, pkg/session/bootstrap.go
Issue Number: close #52758 
The regexp in `mdl_view` is not correct:
```
SELECT ',10,` regexp ',1|2,'
```
This SQL will return 1, because it actually matches ',1' or '2,'.
This PR modified the REGEXP from `,1|2,` to `,(1|2),`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> ddl,mdl: fix the issue that the table_ids overlap regex is not correct

pkg/planner/core/hashcode.go, pkg/planner/core/plan.go, pkg/planner/memo/BUILD.bazel, pkg/planner/memo/group.go, pkg/planner/util/BUILD.bazel, pkg/planner/util/func_pointer_misc.go, pkg/planner/util/misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move hash encoding logic and HasMaxOneRow to util 

pkg/expression/builtin_ilike.go, pkg/expression/builtin_ilike_vec.go, pkg/expression/collation.go, pkg/util/collate/collate.go, tests/integrationtest/r/expression/charset_and_collation.result, tests/integrationtest/t/expression/charset_and_collation.test
Issue Number: close #52833 
MySQL will use binary collation when the `max_length` of some arguments' types are too long. It'll mostly happen on `JSON` types.
As TiDB doesn't have a `max_length` attribute for each type and "datum", I specially handled the situation for JSON. Some function will return binary collation when some of the arguments are JSON type.
In MySQL, the state of `BINARY` flag, `BLOB` type and `binary` collation is really a chaos. For this example, you'll find that sometimes the `collation(...)` returns `utf8mb4_bin` while the returned type info (shown through `--column-type-info`) tells you the collation is `utf8mb4_0900_ai_ci`. I'm not sure whether it's a bug for MySQL or not... 
So, I want to fix the behavior with minimum modification: only change the …
=> expression: fix the collation of functions with json arguments

pkg/lightning/common/util.go
colum -> column
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: update util.go

pkg/ddl/ddl_worker.go, pkg/util/dbterror/ddl_terror.go
Issue Number: close https://github.com/pingcap/tidb/issues/52805
```
[2024/04/20 07:11:41.700 +08:00] [ERROR] [local.go:1231] ["scan region failed"] [error="scan regions from start-key:7480000000000000FFF55F698000000000FF0000570130333532FF35373637FF383237FF2D36393932FF3132FF33383733362DFF32FF30393239363931FFFF3835392D30393837FFFF35343532313237FF2DFF373432313939FF3330FF3138332D33FF363238FF33323834FF3839362DFF393439FF3433363535FF3439FF312D38393330FF37FF3633373839382DFFFF3133313031393538FFFF3631302D313337FF37FF333239333633FF3200FE0380000000FF024DDEEB00000000FB, err: rpc error: code = Canceled desc = context canceled: [BR:PD:ErrPDBatchScanRegion]batch scan region"] [region_len=0] [startKey=7480000000000000FFF55F698000000000FF0000570130333532FF35373637FF383237FF2D36393932FF3132 …
```
=> ddl: add context cancel check before commit

pkg/executor/executor.go, pkg/planner/core/stats.go, pkg/statistics/handle/usage/indexusage/collector.go
Issue Number: close #51898
This PR is trying to optimize the performance of `IndexUsage` utilities. Previously it costed around 1% CPU and did a lot of allocation. This PR tries to optimize it and get some tiny performance boost.
1. Add a pool to avoid frequently allocating/de-allocating `indexUsage` and the internal entries.
2. Avoid using `getTblInfoForUsedStatsByPhysicalID`, which is very slow because it iterates over all tables.
Tests 
> 
I used https://gist.github.com/YangKeao/c02ada99d2602d5e7fb5fb94f0581015 to run a stabler `select_random_points` benchmark. It gives QPS 59029 and 58393 for the commit before index usage and with index usage enabled.
After patching the index usage commit with this PR, the average …
=> planner: optimize performance of `IndexUsage` utilities

pkg/expression/builtin.go, pkg/expression/builtin_cast.go, pkg/expression/builtin_cast_test.go, pkg/expression/builtin_convert_charset.go, pkg/expression/distsql_builtin.go, pkg/expression/scalar_function.go, tests/integrationtest/r/expression/charset_and_collation.result, tests/integrationtest/t/expression/charset_and_collation.test
Issue Number: close #50295 
The error `cannotConvertString` should have three different behaviors:
1. Explicit `cast`, and SQL_MODE is strict: it'll return NULL and add a warning.
2. Explicit `cast`, and SQL_MODE is not strict: it'll return truncated string and add a warning.
3. Implicit `cast`: it'll return an error.
TiDB returns error in all cases, so it's not compatible.
Fix the behavior of `from_binary` function. Now it's only fixed on TiDB, and will need some modification on TiKV as well.
Tests 
> 
Side effects
Documentation …
=> expression: fix charset conversion warning and error behavior

pkg/ddl/BUILD.bazel, pkg/ddl/ttl.go, pkg/ttl/cache/BUILD.bazel, pkg/ttl/cache/table.go, pkg/ttl/cache/table_test.go
Issue Number: close #53103
After we introduced `StaticExprContext`, we can build and evaluate an expression more simply without relying on the session. So, we can make it simple to evalute a TTL expire time. 
- introduce a new function `EvalExpireTime` to compute the TTL expire time. It only requires the current time and the expression info as the input argument. So it is more simple, the new function is:
```
func EvalExpireTime(now time.Time, interval string, unit ast.TimeUnitType) (time.Time, error) {
// ...
}
```
- DDL use `EvalExpireTime` to check whether a expire expression is legal.
Tests 
> 
Side effects
Documentation …
=> ttl: use static expression context to calculate the TTL expire time

pkg/expression/builtin_cast.go, tests/integrationtest/r/expression/multi_valued_index.result
Issue Number: close #53219
The error message was misleading. TiDB actually supports casting to `char(16) array`. The user needs to add length after facing this error.
Change the error message to tell the user that the problem is the missed length.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: clarify the `cast(... as char array)` error message | tidb-test=pr/2326

pkg/planner/core/rule_column_pruning.go, tests/integrationtest/r/planner/core/issuetest/planner_issue.result, tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #49109 
Projection is wrongly pruned to a empty one after the second round of column pruning
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix wrong empty projection | tidb-test=pr/2327

pkg/executor/test/issuetest/BUILD.bazel, pkg/executor/test/issuetest/executor_issue_test.go, pkg/expression/builtin_regexp.go
Issue Number: close #53221 
Tidb report error when these functions are executed in row by row mode. But failed to check it in vector mode.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> expression: Report error when empty pattern in regexp related function

pkg/planner/core/casetest/BUILD.bazel, pkg/planner/core/casetest/plan_test.go, pkg/planner/core/expression_rewriter.go, tests/integrationtest/r/select.result
Issue Number: close #52755
Use ```max``` function instead of ```first_row``` function.
if the query is ```t.id = all (select s.id from s)```, it will be rewrote to
```t.id = (select s.id from s having count(distinct s.id) <= 1 and [all checker])``` .
If there is NULL in the ```s.id``` column, s.id should be the value that isn't null in condition t.id == s.id. So use function max to filter NULL.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: fix wrong behavior for = all()

pkg/planner/core/collect_column_stats_usage.go, pkg/planner/core/collect_column_stats_usage_test.go
Issue Number: close #53141
In calculating cost， we need all columns' stats to get row size.
To get right result,so we need to load all stats when to sync load.
But here is a bug. ```ds.Columns``` has been pruned. it doesn't contain all columns.
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: collect all columns meta by sync load

lightning/tests/lightning_duplicate_resolution_merge/run.sh
Issue Number: ref #52306 
Fix unstable test for lightning_duplicate_resolution_merge.
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/691/pipeline/
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> lightning: fix unstable test for conflict detection

pkg/planner/core/core_init.go, pkg/planner/core/exhaust_physical_plans.go, pkg/planner/core/rule_predicate_push_down.go, pkg/planner/core/rule_topn_push_down.go, pkg/planner/util/utilfuncp/BUILD.bazel, pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: encapsulate baseLogicalPlan push down topN logic and move addSection to util

pkg/infoschema/infoschema_v2.go, pkg/infoschema/infoschema_v2_test.go, pkg/server/handler/tests/http_handler_test.go, pkg/server/handler/tikvhandler/tikv_handler.go, pkg/statistics/handle/util/table_info.go, pkg/ttl/cache/infoschema.go, pkg/ttl/ttlworker/job_manager.go
1. Change some calling from `SchemaTables()` to `SchemaTableInfos()`
`SchemaTables()` is heavier than `SchemaTableInfos()` because the former need to load model.TableInfo from meta kv first and then build `table.Table` from `model.TableInfo`
The caller only need the `model.TableInfo`, so change them to `SchemaTableInfos`.
2. Reset Tables field of model.DBInfo when adding it to infoschema v2
I found some leaky memory occupation in infoschema v2:
It turn out to be that the `model.DBInfo` reference the Tables, so the memoy of json data can not be freed.
3. Skip refill cache In `SchemaTables()` 
Fill cache in the list API cause the memory thrash and also CPU thrash.
Especally I find the cost of `Sizeof()` is much higher than estimated. 
When we add …
=> *: some tiny optimizations to reduce infoschema v2 memory

expression/builtin_compare.go, expression/util.go, planner/core/expression_rewriter.go, planner/core/plan_cache_test.go
This is a cherry-pick of #48413
Issue Number: close #48165, close #41918
Problem Summary: planner: fix the issue that plan cache may return wrong result when comparing datetime column with `unix_timestamp`
planner: fix the issue that plan cache may return wrong result when comparing datetime column with `unix_timestamp`
Tests 
>   
Side effects
Documentation
```release-note
None
```
=> planner: fix the issue that plan cache may return wrong result when comparing datetime column with unix_timestamp (#48413) 

pkg/expression/builtin_cast.go, pkg/expression/builtin_cast_test.go, pkg/expression/builtin_cast_vec.go
Reverts pingcap/tidb#53129
Issue Number: close #53248
Tests 
> 
Side effects
Documentation
```release-note
```
=> expression: reverts #53129 | tidb-test=pr/2329

pkg/planner/core/base/task_base.go, pkg/planner/core/core_init.go, pkg/planner/core/find_best_task.go, pkg/planner/core/plan.go, pkg/planner/core/task.go, pkg/planner/core/task_base.go, pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
=> planner: move invalidTask to task base pkg.

pkg/executor/window_test.go, pkg/parser/parser.y, pkg/planner/core/optimizer.go
Issue Number: close https://github.com/pingcap/tidb/issues/52933
From the MySQL plan:
```sql
mysql> explain analyze select var_samp(c1) over (partition by c1) from t1;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| EXPLAIN …
```
=> planner: make `var_samp` can be used as a window function
