- pkg/util/chunk/row_container_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50688
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix data race for test TestInterruptedDuringSpilling

- pkg/planner/core/casetest/index/index_test.go
- pkg/planner/core/point_get_plan.go
- pkg/session/session.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
- pkg/util/admin/admin.go
Issue Number: ref #50653
Introduce variable tidb_opt_use_invisible_indexes whose scope is session only.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: support tidb_opt_use_invisible_indexes

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/rule_aggregation_push_down.go
- pkg/planner/core/rule_join_reorder.go
- pkg/planner/core/rule_partition_processor.go
- pkg/planner/core/stats.go
- pkg/util/hint/hint.go
- pkg/util/hint/hint_query_block.go
Problem Summary: planner: refactor some internal hint structures
ONLY REFACTOR, NO LOGICAL CHANGE
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor some internal hint structures

- pkg/sessionctx/variable/setvar_affect.go
- tests/integrationtest/r/sessionctx/setvar.result
- tests/integrationtest/t/sessionctx/setvar.test
Issue Number: close https://github.com/pingcap/tidb/issues/50653
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: tidb_opt_use_invisible_indexes support set_var 

- pkg/executor/checksum.go
- pkg/executor/importer/BUILD.bazel
- pkg/executor/importer/importer_testkit_test.go
- pkg/executor/importer/table_import.go
Issue Number: close #50651
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: ChecksumTableExec respects SQLKiller

- pkg/statistics/cmsketch.go
Issue Number: close #50766
As the title descripes. we remove the bounds check by using the ```slices```.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Bounds Check Elimination for cm sketch

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/rule_aggregation_push_down.go
- pkg/planner/core/rule_aggregation_skew_rewrite.go
- pkg/util/hint/hint.go
Issue Number: ref https://github.com/pingcap/tidb/issues/48875
remove Agghint in the PlanHints. we need to remove AggHint in the other LogicalPlan.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> hint: refactor PlanHints

- tests/integrationtest/r/planner/core/casetest/index/index.result
- tests/integrationtest/t/planner/core/casetest/index/index.test
Issue Number: close https://github.com/pingcap/tidb/issues/50553
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix index merge test hint usage and use brief format to show explain case

- pkg/executor/sortexec/BUILD.bazel
Issue Number: close #50799
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: remove redundant go_test

- tests/integrationtest/README.md
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: Add `How to debug integration test` in README.md

- tests/integrationtest/README.md
Issue Number: ref https://github.com/pingcap/tidb/pull/50817
Following of https://github.com/pingcap/tidb/pull/50817/files
We can give it a better name.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: better name for the vscode launch.json

- pkg/executor/BUILD.bazel
- pkg/executor/checksum.go
- pkg/executor/checksum_test.go
Issue Number: ref #50832
ADMIN CHECKSUM TABLE in only used by lightning / IMPORT INTO, BR does not use it, so we can change its behaviour
I want to log the results for every kv-groups, to help locate why data is missing. More changes will be made in future PR.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: log each response for checksum

- pkg/sessionctx/variable/BUILD.bazel
- pkg/sessionctx/variable/session.go
- pkg/table/tables/tables.go
Issue Number: close #50842
Delete useless `SessionVars.IDAllocator` to keep code clean
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: delete useless `SessionVars.IDAllocator`

- pkg/planner/core/flat_plan.go
- pkg/planner/core/rule_join_reorder_greedy.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use slices to eliminate branch check

- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/interval.go
- pkg/statistics/handle/autoanalyze/priorityqueue/interval_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- Added a refresher to help us build the queue.
- Added an IsValidToAnalyze function to check if it is valid before we do the job.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add refresher

- pkg/sessionctx/variable/sysvar_test.go
Issue Number: close #50922 
Avoid expect error message for `TestSetTiDBCloudStorageURI` since it may failed for different reasons.
Tests 
Side effects
- None
Documentation
- None
```release-note
None
```
> variable: fix unexpected failure for `TestSetTiDBCloudStorageURI`

- tests/realtikvtest/addindextestutil/workload.go
Issue Number: close #50902
Generally, the error "[global:2]execution result undetermined" will only be reported when TiDB fails to commit the primary key. The reason may be unstable network.
This PR adds "execution result undetermined" to the ignored error list.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: stabilize TestPiTRCreateNonUniqueIndex

- pkg/disttask/framework/integrationtests/BUILD.bazel
- pkg/disttask/framework/integrationtests/framework_err_handling_test.go
- pkg/disttask/framework/integrationtests/framework_ha_test.go
- pkg/disttask/framework/integrationtests/framework_pause_and_resume_test.go
- pkg/disttask/framework/integrationtests/framework_rollback_test.go
- pkg/disttask/framework/integrationtests/framework_test.go
- pkg/disttask/framework/integrationtests/resource_control_test.go
- pkg/disttask/framework/scheduler/balancer.go
- pkg/disttask/framework/scheduler/interface.go
- pkg/disttask/framework/scheduler/main_test.go
- pkg/disttask/framework/scheduler/nodes.go
- pkg/disttask/framework/scheduler/scheduler.go
- pkg/disttask/framework/scheduler/scheduler_manager.go
- pkg/disttask/framework/taskexecutor/BUILD.bazel
- pkg/disttask/framework/taskexecutor/main_test.go
- pkg/disttask/framework/taskexecutor/manager.go
- pkg/disttask/framework/taskexecutor/task_executor.go
- pkg/disttask/framework/taskexecutor/task_executor_test.go
- pkg/disttask/framework/taskexecutor/task_executor_testkit_test.go
- pkg/disttask/framework/testutil/context.go
- pkg/disttask/framework/testutil/disttest_util.go
- pkg/disttask/framework/testutil/scheduler_util.go
- pkg/disttask/framework/testutil/table_util.go
-  add integration test for resource control
- some refactor for existing cases
Tests 
> 
Side effects
Documentation
```release-note
None
```
> disttask: add integration test for resource control

- br/pkg/lightning/backend/external/BUILD.bazel
- br/pkg/lightning/backend/external/bench_test.go
- br/pkg/lightning/backend/external/misc_bench_test.go
I found it's hard to scroll and navigate in `bench_test.go`, so move some functions into `misc_bench_test.go`
Tests 
Side effects
Documentation
```release-note
None
```
> test: move some functions into another file

- pkg/executor/test/jointest/main_test.go
Issue Number: ref #48991 
Add a goleak ignore option.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor/join_test: add goleak ignore option

- pkg/expression/expr_to_pb_test.go
- pkg/expression/infer_pushdown.go
Issue Number: close #50975 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: Support cast decimal as real push down to tiflash

- pkg/metrics/grafana/tidb.json
- pkg/metrics/metrics.go
- pkg/metrics/stats.go
- pkg/statistics/handle/cache/BUILD.bazel
- pkg/statistics/handle/cache/statscache.go
- pkg/statistics/handle/metrics/metrics.go
- pkg/statistics/handle/usage/BUILD.bazel
- pkg/statistics/handle/usage/session_stats_collect.go
Add two new panels for stats delta loading and updating.
Fix the y-axe of the auto analyze and the sync load.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> stats, metrics: add and fix stats related grafana panel

- pkg/executor/test/loaddatatest/load_data_test.go
- pkg/parser/ast/dml.go
- pkg/parser/ast/dml_test.go
- pkg/parser/parser.y
Issue Number: ref #49602
as title.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: add LOW_PRIORITY for LOAD DATA

- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/localhelper.go
- br/pkg/lightning/backend/local/localhelper_test.go
- br/pkg/lightning/importer/import.go
- br/pkg/lightning/importer/precheck.go
- br/pkg/lightning/importer/precheck_impl.go
- pkg/ddl/BUILD.bazel
- pkg/ddl/backfilling_dist_executor.go
- pkg/ddl/index.go
- pkg/ddl/ingest/BUILD.bazel
- pkg/ddl/ingest/backend_mgr.go
- pkg/ddl/ingest/mock.go
- pkg/executor/import_into.go
- pkg/executor/importer/table_import.go
Issue Number: close #51103
Tests 
> chaos test should stop failing
Side effects
Documentation
```release-note
None
```
> ddl, lightning: use TiDB PD client's discovery to create local backend

- pkg/planner/core/rule_semi_join_rewrite.go
- pkg/planner/optimize.go
1. Fixed a flipped comment.
2. Added more comments about semi-join optimization.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix typos and add more comments

- br/CONTRIBUTING.md
- br/README.md
Issue Number: close #51016
the build instruction in br's readme.md is outdated, now update it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: update readme.md in br

- br/pkg/lightning/backend/kv/session.go
- tests/realtikvtest/importintotest/import_into_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50757
Tests 
> 
Side effects
Documentation
```release-note
None
```
> importinto/lightning: fix incorrect datatime value for zero date

- pkg/planner/core/task.go
https://github.com/pingcap/tidb/blob/aa4f4da72789eac1b52a4abda9a80b73ecac6c48/pkg/planner/core/task.go#L2441
We don't use this variable right now. So we can delete it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove useless variable

- br/pkg/conn/conn.go
- br/pkg/lightning/importer/import.go
- br/pkg/pdutil/pd.go
- br/pkg/task/common.go
- br/pkg/task/operator/cmd.go
- br/pkg/task/restore_ebs_meta.go
Issue Number: close #49865
Tests 
> pass existing tests
Side effects
Documentation
```release-note
None
```
> br, lightning: change PD address type to []string in NewPdController

- pkg/ddl/backfilling_dist_scheduler.go
Issue Number: close #50895
Problem Summary: See https://github.com/pingcap/tidb/issues/50895#issuecomment-1958889520
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl, disttask: add scan-region check before dispatch subtasks

- pkg/executor/index_merge_reader.go
- tests/integrationtest/r/executor/index_merge_reader.result
- tests/integrationtest/t/executor/index_merge_reader.test
Issue Number: close #51188
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: avoid prealloc too big slice for indexMerge

- pkg/domain/infosync/info.go
- pkg/executor/infoschema_cluster_table_test.go
- pkg/executor/infoschema_reader_test.go
- pkg/executor/inspection_result_test.go
- pkg/executor/memtable_reader.go
- pkg/executor/memtable_reader_test.go
- pkg/infoschema/tables.go
Issue Number: close #50723
Add ticdc to table information_schema.cluster_info.
Support querying log, configuration, and hardware information of ticdc through sql
- Read ticdc server info from `/topology/ticdc`
- Add ticdc to table information_schema.cluster_info.
Tests 
> 
1. Query instance info of ticdc
2. Query log of ticdc
3. Query config of ticdc
4. Query hardware of ticdc
Side effects
Documentation
```release-note
Add support for querying log, configuration, and hardware information of ticdc through sql.
```
> executor, infoschema: add ticdc into table cluster_info

- pkg/planner/core/indexmerge_path_test.go
Issue Number: ref #45798
Problem Summary: planner: add more test cases for plan cache with generated columns
planner: add more test cases for plan cache with generated columns
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for plan cache with generated columns

- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
This PR is based on https://github.com/pingcap/tidb/pull/51045
This pull request completes adding partitioned tables to the job queue. 
It calculates three metrics: 
1) change percent
2) table size (cols * row_count)
3) detection of any special events (new index)
Because they are partitions, so we calculate the average value as the final value.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: build the table analysis job queue part2

- pkg/infoschema/BUILD.bazel
- pkg/infoschema/infoschema_test.go
make the ut easier to start up for infoschema cache v2
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: run some infoschema ut without domain

- pkg/ddl/backfilling_operators.go
- pkg/ddl/ddl.go
- pkg/ddl/ddl_worker.go
- pkg/ddl/job_table.go
- pkg/ddl/reorg.go
- pkg/ddl/syncer/syncer.go
- pkg/ddl/util/util.go
- pkg/owner/manager.go
Issue Number: close https://github.com/pingcap/tidb/issues/51343
- Remove `isChanClosed` and `IsContextDone`
- Simply refactor and clean up this function `OwnerCheckAllVersions `
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: simple refactoring `OwnerCheckAllVersions`, remove `isChanClosed` and` IsContextDone`

- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/calculator.go
- pkg/statistics/handle/autoanalyze/priorityqueue/calculator_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
Implement the priority calculator based on this formula:
priority_score = $$0.6 \times \log_{10}(1 + \text{Change Ratio}) + 0.1 \times (1 - \log_{10}(1 + \text{Table Size})) + 0.3 \times \log_{10}(1 + \sqrt{\text{Analysis Interval}})$$ + special_event[event]
When a new index is added, we assign it a priority score of 2 as a special event.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add priority calculator

- pkg/bindinfo/binding.go
- pkg/bindinfo/global_handle.go
- pkg/bindinfo/session_handle.go
Problem Summary: planner: simplify the session binding handler code
planner: simplify the session binding handler code
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify the session binding handler code

- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
- pkg/statistics/handle/autoanalyze/BUILD.bazel
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/autoanalyze_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/calculator.go
- pkg/statistics/handle/autoanalyze/priorityqueue/calculator_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/interval.go
- pkg/statistics/handle/autoanalyze/priorityqueue/interval_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/main_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
Added a new global variable to enable the priority queue called `tidb_enable_auto_analyze_priority_queue`.
Also, I did some refactorings to solve the cyclic dependency issues. Just changed the test files to the test package because `testkit` depends on the `handle` package.
I also did some tests locally:
1. enable the feature
```sql
mysql> SET GLOBAL tidb_enable_auto_analyze_priority_queue=ON;
mysql> show variables like 'tidb_enable_auto_analyze_priority_queue';
+-----------------------------------------+-------+
| Variable_name                           | Value |
+-----------------------------------------+-------+
| tidb_enable_auto_analyze_priority_queue | ON    | …
```
> *: add variable for priority queue

- br/pkg/streamhelper/advancer_test.go
- br/pkg/streamhelper/basic_lib_for_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/50743
Fix unstable test of clear cache.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix unstable test TestClearCache

- br/pkg/restore/client.go
- br/pkg/restore/import.go
Issue Number: close #50593 
slow ingest request pile up in the grpc connection, which leads to download requests blocken.
use the dedicated grpc client for ingest
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: use the dedicated grpc client for ingest

- pkg/executor/aggregate/agg_spill.go
Issue Number: close #51474
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: trigger fallback action when agg memory consumption is lower than limit

- br/pkg/storage/azblob.go
- br/pkg/storage/gcs.go
Issue Number: close #51528
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br, pkg/storage: enable objPrefix for gcs and azure

- br/pkg/storage/ks3.go
- br/pkg/storage/s3.go
- br/pkg/storage/s3_test.go
Issue Number: close #51505
Tests 
> 
Side effects
Documentation
```release-note
None
```
> s3: retry 3 times inside one `Read`

- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/types/interfaces.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> * : delete unuse interface and implementation

- pkg/executor/slow_query_test.go
- pkg/executor/stmtsummary_test.go
- pkg/infoschema/infoschema_v2.go
- pkg/sessionctx/variable/tidb_vars.go
Fix some of the test cases.
Tests 
```
index ea94d024fe..d06e00bcaf 100644
@@ -1478,7 +1478,7 @@ const (
DefEnableParallelSort                             = false
DefTiDBTxnEntrySizeLimit                          = 0
-       DefTiDBSchemaCacheSize                            = 1024
+       DefTiDBSchemaCacheSize                            = 0
DefTiDBLowResolutionTSOUpdateInterval             = 2000
)
```
```
make ut 'X=run pkg/executor' 1>a.log 2>b.log
grep FAIL |wc -l
```
Before this commit, there are 68 failed cases, and …
> *: implement FindTableByPartitionID() for infoschema V2

- pkg/privilege/privileges/cache.go
- pkg/session/session.go
- pkg/table/tables/cache.go
Issue Number:  ref #44736
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util: use atomic.Pointer to replace with atomic.Value

- pkg/executor/index_merge_reader.go
- pkg/store/copr/BUILD.bazel
- pkg/store/copr/batch_coprocessor.go
- pkg/store/copr/coprocessor_test.go
- pkg/store/copr/key_ranges.go
- pkg/store/copr/region_cache.go
This is a cherry-pick of https://github.com/pingcap/tidb/pull/51333
Issue Number: close #51326
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: load region info from pd in batch(#51333)

- Makefile
- pkg/metrics/grafana/tidb.json
- tools/dashboard-linter/BUILD.bazel
- tools/dashboard-linter/main.go
Issue Number: close #51556
there is a dashboard linter https://github.com/grafana/dashboard-linter, but it didn't check duplicate ids, so we write one.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix duplicate panel ids in tidb.json & add a duplicate id checker

- pkg/executor/show_placement.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix show placement for v2

- pkg/statistics/handle/autoanalyze/refresher/refresher.go
Do not print this verbose log. Every three seconds is too much.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: turn off verbose logs

- pkg/executor/insert.go
- pkg/executor/insert_common.go
- tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
Issue Number: close #51629
Problem Summary: fix issue of some insert execution stats was omitted.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix issue of some insert execution stats was omitted

- pkg/executor/test/analyzetest/analyze_test.go
Issue Number: close #51649
fix flaky test TestAnalyzeClusteredIndexPrimary by sorting the result.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix flaky test TestAnalyzeClusteredIndexPrimary

- pkg/disttask/framework/integrationtests/framework_pause_and_resume_test.go
Issue Number: close #51684
Tests 
> 
Side effects
Documentation
```release-note
None
```
> disttask: fix flaky pause test

- pkg/infoschema/builder.go
- pkg/infoschema/infoschema_test.go
- pkg/infoschema/infoschema_v2.go
- pkg/infoschema/internal/testkit.go
Issue Number: ref #51680 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschemav2: support createtables & modifyschema

- br/pkg/restore/db_test.go
- pkg/session/bootstrap.go
Issue Number: close https://github.com/pingcap/tidb/issues/51690
- as title
Tests 
- code transfer, no code change
Side effects
Documentation
```release-note
None
```
> bootstrage: reserve bootstrap versions for v7.5.x

- pkg/executor/show_placement_test.go
- pkg/executor/test/showtest/show_test.go
- pkg/parser/model/model.go
Issue Number: close #51699
Tests 
> 
Side effects
Documentation
```release-note
fix SURVIVAL_PREFERENCES is not shown in SHOW CREATE PLACEMENT POLICY
```
> *: fix `SURVIVAL_PREFERENCES` is not shown in `SHOW CREATE PLACEMENT POLICY`

- pkg/ddl/bdr.go
- pkg/ddl/bdr_test.go
- tests/integrationtest/r/ddl/bdr_mode.result
- tests/integrationtest/t/ddl/bdr_mode.test
Issue Number: close https://github.com/pingcap/tidb/issues/51719
- support add implicit nullable column and generated column
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl/bdr: support add implicit nullable column and generated column

- cmd/tidb-server/BUILD.bazel
- cmd/tidb-server/main.go
- pkg/util/redact/BUILD.bazel
- pkg/util/redact/redact.go
- pkg/util/redact/redact_test.go
Issue Number: close #51758
Problem Summary: add `DeRedactXXX`. add `tidb-server ... collect-logs <input> <output>`
Tests 
```
[xhe@tb14p tidb]$ ./bin/tidb-server --redact collect-logs  c
‹, 3, <nil>, 4096, 10
f, 1, <nil>, 4096, 9
x, 1, <nil>, 4096, 8
c, 1, <nil>, 4096, 7
v, 1, <nil>, 4096, 6
›, 3, <nil>, 4096, 3
g, 1, <nil>, 4096, 2
g, 1, <nil>, 4096, 1
g, 1, <nil>, 4096, 0
?gggggggggggg
?gggggggggggg?gggggggggggg
[xhe@tb14p tidb]$ ./bin/tidb-server  collect-logs  c
‹, 3, <nil>, 4096, 10
f, 1, <nil>, 4096, 9
x, 1, <nil>, 4096, 8
c, 1, <nil>, 4096, 7
v, 1, <nil>, 4096, 6
›, 3, <nil>, 4096, 3
g, 1, <nil>, 4096, 2
g, 1, <nil>, 4096, 1
g, 1, <nil>, 4096, 0
fxcvgggggggggggg
fxcvggggggggggggfxcvgggggggggggg
```
> 
Side effects
Documentation …
> cmd: add new subcommand for redacting logs

- pkg/util/cgmon/cgmon.go
Issue Number: close #50467
1、Do not set the value by ```runtime.GOMAXPROCS```
2、print too much log
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix cgroup monitor

- br/pkg/restore/client.go
reseting -> resetting
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix typo in client.go

- pkg/metrics/grafana/tidb.json
- global sort requires large mount of mem/cpu, add this inside `Server` to help diagnose
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: add a panel for GC rate and GOMEMLIMIT

- br/pkg/lightning/backend/external/engine.go
- br/pkg/lightning/backend/external/util.go
- br/pkg/lightning/backend/external/util_test.go
Issue Number: close #51639
Tests 
AWS 40T ingest step becomes faster
> 
Side effects
Documentation
```release-note
None
```
> external: parallel seekPropsOffsets

- pkg/planner/cardinality/cross_estimation.go
- pkg/planner/cardinality/pseudo.go
- pkg/planner/cardinality/row_count_index.go
- pkg/planner/cardinality/selectivity.go
- pkg/statistics/handle/storage/read_test.go
- pkg/statistics/index.go
fixed function signature
according to the golang specification, ctx should be the first argument, so the first and second arguments of this function should be changed.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> fix: modify signature

- tests/integrationtest/r/ddl/default_as_expression.result
- tests/integrationtest/t/ddl/default_as_expression.test
Issue Number: close https://github.com/pingcap/tidb/issues/51686
* Multi-valued index
* Clustered index
* FK
* Expression Index
* Global index
* Temporary table
* Cache table
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: add expression default values feature relevant tests for different types of tables and indexes

- pkg/ttl/cache/table.go
- pkg/ttl/cache/table_test.go
- pkg/ttl/session/BUILD.bazel
- pkg/ttl/session/session.go
- pkg/ttl/ttlworker/BUILD.bazel
- pkg/ttl/ttlworker/job.go
- pkg/ttl/ttlworker/job_manager.go
- pkg/ttl/ttlworker/job_manager_integration_test.go
- pkg/ttl/ttlworker/job_manager_test.go
- pkg/ttl/ttlworker/scan.go
- pkg/ttl/ttlworker/scan_test.go
- pkg/ttl/ttlworker/session.go
- pkg/ttl/ttlworker/session_test.go
- pkg/ttl/ttlworker/task_manager.go
- pkg/ttl/ttlworker/task_manager_integration_test.go
- pkg/ttl/ttlworker/timer.go
- pkg/ttl/ttlworker/timer_test.go
This reverts commit 932ff725ff21931fd14d160b656fb0310c7badf1.
Issue Number: close #51825
see description in issue
revert #51701
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Revert "ttl: fix expire time drift for daylighting-save time case (#51701)

- br/pkg/restore/import_retry_test.go
- br/pkg/restore/split/BUILD.bazel
- br/pkg/restore/split/client.go
- br/pkg/restore/split/split.go
- br/pkg/restore/split/split_test.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/backoff.go
- br/pkg/utils/backoff_test.go
- br/pkg/utils/retry.go
Issue Number: ref #51533
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br/utils: add WithRetryReturnLastErr and backoffer

- pkg/infoschema/infoschema_test.go
- pkg/infoschema/test/infoschemav2test/v2_test.go
- pkg/sessionctx/variable/noop.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Tests 
```
mysql> set global tidb_enable_noop_variables=OFF;
mysql> set global tidb_schema_cache_size=3;
Query OK, 0 rows affected, 1 warning (0.02 sec)
mysql> show warnings;
+---------+------+------------------------------------------------------+
| Level   | Code | Message                                              |
+---------+------+------------------------------------------------------+
| Warning | 8144 | setting tidb_schema_cache_size has no effect in TiDB |
+---------+------+------------------------------------------------------+
1 row in set (0.00 sec)
mysql> select @@tidb_schema_cache_size;
+--------------------------+
| @@tidb_schema_cache_size |
+--------------------------+
| 3 …
```
> infoschema_v2: disable tidb schema cache size

- pkg/executor/adapter.go
Issue Number: close #51815
This PR is part of #51618. I extract them because it's a logic change (but not simple refactor).
I re-ordered the process of initialing plan digest and TopSQL related things (including KvExecCounter).
Tests 
> They should be covered by existing tests.
Side effects
Documentation
```release-note
None
```
> executor: adjust the order of initialize plan, kvExecCounter and TopSQL

- pkg/planner/core/casetest/BUILD.bazel
- pkg/planner/core/casetest/integration_test.go
- pkg/planner/core/optimizer.go
Issue Number: close #51873
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: apply rule_partition_pruning when optimizing CTE under static mode

- pkg/infoschema/test/clustertablestest/tables_test.go
- pkg/planner/core/planbuilder.go
- pkg/util/stmtsummary/v2/tests/table_test.go
- tests/integrationtest/r/privilege/privileges.result
- tests/integrationtest/t/privilege/privileges.test
This reverts commit 897d93db8c9b0959803cc7ebae419bf72da0ded3.
Issue Number: close #51936
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Revert "add super privilege check for some admin commands (#51497)"

- pkg/bindinfo/capture_test.go
- pkg/bindinfo/tests/bind_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix bind test for information schema v2

- pkg/planner/core/preprocess.go
- pkg/planner/core/preprocess_test.go
Issue Number: close #51592 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: Fix validation error for column default value

- pkg/infoschema/test/clustertablestest/cluster_tables_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: rename two unit tests to run it in CI

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref https://github.com/pingcap/tidb/issues/49353
See https://github.com/pingcap/tidb/issues/49353 and https://github.com/tikv/client-go/pull/1239 to 6.5 https://github.com/tikv/client-go/pull/1246).
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update client-go for release-6.5

- go.mod
- go.sum
Issue Number: ref https://github.com/pingcap/tidb/issues/49353
See https://github.com/pingcap/tidb/issues/49353 and https://github.com/tikv/client-go/pull/1239 to 6.1 https://github.com/tikv/client-go/pull/1247).
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update client-go for release-6.1

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref https://github.com/pingcap/tidb/issues/49353
See https://github.com/pingcap/tidb/issues/49353 and https://github.com/tikv/client-go/pull/1239 to 7.1 https://github.com/tikv/client-go/pull/1245).
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update client-go for release-7.1

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref https://github.com/pingcap/tidb/issues/49353
See https://github.com/pingcap/tidb/issues/49353 and https://github.com/tikv/client-go/pull/1239(cherry-pick to 7.5 https://github.com/tikv/client-go/pull/1244).
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update client-go for release-7.5

- br/tidb-lightning.toml
Issue Number: ref #51036 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: revise tidb-lightning.toml for conflict detection

- br/pkg/lightning/importer/chunk_process.go
- br/pkg/lightning/verification/BUILD.bazel
- br/pkg/lightning/verification/checksum.go
- br/pkg/lightning/verification/checksum_test.go
- pkg/disttask/importinto/subtask_executor.go
- pkg/disttask/importinto/task_executor.go
- pkg/executor/importer/BUILD.bazel
- pkg/executor/importer/chunk_process.go
- pkg/executor/importer/chunk_process_testkit_test.go
- pkg/executor/importer/engine_process.go
- pkg/executor/importer/importer_testkit_test.go
- pkg/executor/importer/table_import.go
- pkg/executor/importer/table_import_testkit_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> importinto: add log for chunk checksum & replace codec with keyspace

- pkg/executor/test/jointest/hashjoin/BUILD.bazel
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
- pkg/planner/core/exhaust_physical_plans.go
We shouldn't use atomic variables for the testing. This would also affect the production performance.
Removed the variables and used hints to update the tests.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove unnessary atomic variables

- pkg/infoschema/infoschema_test.go
1. fix TestBasic
2. fix TestInfoTables
3. fix TestBuildBundle
Tests 
> 
Side effects
Documentation
```release-note
None
```
> * : fix some tests for InfoSchema v2

- docs/tidb_http_api.md
Issue Number: close https://github.com/pingcap/tidb/issues/52128
Update the doc.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: update one MVCC API example

- pkg/store/driver/txn/driver_test.go
- pkg/util/dbterror/terror_test.go
Issue Number: ref #51306
Problem Summary: complete tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: additional marker tests for error redaction

- docs/tidb_http_api.md
Issue Number: close https://github.com/pingcap/tidb/issues/52137
Add the hint for it, and fix some markdown lint errors.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: add the hint of usage of the partition tables in mvcc/key API

- pkg/util/topsql/reporter/BUILD.bazel
- pkg/util/topsql/reporter/pubsub.go
- pkg/util/topsql/reporter/pubsub_test.go
Issue Number: close #51301
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/util: fix panic caused by logging grpc err

- pkg/expression/column.go
- pkg/table/tables/tables_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/52181
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix hidden column may do not have a virtual expression

- br/pkg/storage/OWNERS
As the title, add lightning component reviewers as owners of the pkg
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: add OWNERS for storage pkg

- pkg/executor/test/admintest/admin_test.go
- pkg/session/nontransactionaltest/nontransactional_test.go
- pkg/util/util_test.go
Issue Number: ref #51306
Problem Summary: additional unit test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> admintest: additional redaction test

- pkg/infoschema/builder.go
- pkg/infoschema/infoschema.go
- pkg/infoschema/infoschema_v2.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/planbuilder.go
Issue Number: close #52219
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix oom in the infoSchema.TableByName

- tests/realtikvtest/addindextest/add_index_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix TestAddForeignKeyWithAutoCreateIndex for InfoSchema v2

- br/pkg/lightning/config/config_test.go
- br/pkg/lightning/importer/precheck.go
- br/pkg/lightning/importer/restore_schema_test.go
- br/pkg/lightning/lightning.go
- br/pkg/lightning/mydump/loader.go
- br/pkg/lightning/mydump/loader_test.go
- br/pkg/lightning/mydump/region_test.go
Issue Number: ref #52142
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: extract loader config for reuse

- pkg/executor/sortexec/parallel_sort_spill_helper.go
- pkg/executor/sortexec/sort.go
Issue Number: close #52238
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix data race in parallel sort test

- pkg/statistics/handle/bootstrap.go
1. avoid unnecessay table id loading the stats after the for-loop
2. smaller steps to accommodate a table scale of 1000+.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: avoid unnecessay table id loading the stats

- DEPS.bzl
- go.mod
- go.sum
- pkg/util/execdetails/execdetails_test.go
Issue Number: close #52332
Problem Summary: N/A
Related PR: https://github.com/tikv/client-go/pull/1260
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update tikv/client-go to fix panic log

- tools/check/ut.go
Issue Number: ref #52182
Tests 
> 
Side effects
- NA
Documentation
- NA
```release-note
None
```
> tools/ut: skip Lightning tests in `make ut`

- DEPS.bzl
- cmd/tidb-server/main.go
- pkg/server/conn.go
- pkg/session/session.go
- pkg/table/tables/tables_test.go
Issue Number: close #52364 
1. one test
2. And errors of `errStrForLog, handleAssertionFailure` is already redacted, and we should not redact it again
3. Also the wrong subcommand name, an extra `s`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: additional test for redact log and a fix 

- pkg/executor/adapter.go
- pkg/executor/compiler.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_utils.go
- pkg/server/internal/resultset/resultset.go
Issue Number: ref #51407
Problem Summary: planner: simplify plan cache code 
NO LOGICAL CHANGE, JUST REFACTOR
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify plan cache code

- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/cache/statscacheinner.go
- pkg/statistics/handle/initstats/BUILD.bazel
- pkg/statistics/handle/initstats/load_stats.go
- pkg/statistics/handle/initstats/load_stats_page.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: batch write into stats cache when to init stats 

- pkg/executor/mem_reader.go
- pkg/planner/core/find_best_task.go
- tests/integrationtest/r/executor/distsql.result
- tests/integrationtest/r/planner/core/integration_partition.result
- tests/realtikvtest/txntest/txn_test.go
Issue Number: close #52244
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner, executor: make partition table generate `IndexReader` with `UnionScan`

- WORKSPACE
Issue Number: close #52386
upgrade Golang and fix CVE-2023-45288
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.21.9

- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/handletest/statstest/stats_test.go
Issue Number: close pingcap/tidb#52419
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix puting wrong stats into cache (#52421) (#52422)

- DEPS.bzl
- go.mod
- go.sum
- pkg/metrics/grafana/tidb.json
Issue Number: ref #50215
Implement rollback for pipelined dml.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> p-dml: implement rollback for pipelined dml

- pkg/ddl/tests/resourcegroup/resource_group_test.go
- pkg/domain/resourcegroup/runaway.go
- pkg/executor/internal/querywatch/query_watch_test.go
Issue Number: close #52455
Tests 
> 
Side effects
Documentation
```release-note
None
```
> resource_manager: fix test by checking system table status

- pkg/ddl/ddl_worker.go
- pkg/ddl/job_table.go
Issue Number: close #47060 and close #52335
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix unexpected delete ETCD value

- br/pkg/conn/conn.go
Close a connection properly to prevent memory leak
Issue Number: close #52595 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: make sure connection is closed

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #46602
Problem Summary: `GetTiFlashStores` exported by client-go would return unresolved stores, which causes mpp probe keep checking tomebstone stores.
Bump client-go so that `GetTiFlashStores` only returns resolved stores.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update client-go to fix #46602

- pkg/store/copr/coprocessor_test.go
- pkg/store/copr/region_cache.go
Issue Number: close #52762
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix the issue that tiflash cop throw exception `Income key ranges is empty for region: 211`

- docs/tidb_http_api.md
Issue Number: close https://github.com/pingcap/tidb/issues/52756
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: update smooth upgrade mode in tidb_http_api.md

- br/tests/br_pitr_failpoint/run.sh
Issue Number: close #52800
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: Fix br integration test for 7.1.5

- pkg/expression/column.go
colum -> column
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: fix typo in column.go

- pkg/executor/aggregate/agg_hash_executor.go
- pkg/executor/aggregate/agg_stream_executor.go
- pkg/executor/builder.go
- pkg/planner/core/exhaust_physical_plans.go
- tests/integrationtest/r/planner/core/indexjoin.result
- tests/integrationtest/t/planner/core/indexjoin.test
Issue Number: close #37068
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner, executor: support aggregation as inner side of index join

- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/util/BUILD.bazel
- pkg/planner/util/coreusage/null_misc.go
- pkg/planner/util/null_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: extract null check related code to util null_misc

- pkg/ddl/callback.go
- pkg/ddl/ddl.go
- pkg/ddl/ddl_worker.go
- pkg/ddl/syncer/syncer.go
- pkg/domain/domain.go
- pkg/executor/importer/table_import.go
- pkg/infoschema/cache.go
- pkg/meta/meta.go
- pkg/parser/model/ddl.go
- pkg/session/session.go
- pkg/sessionctx/context.go
- pkg/structure/list.go
Tests 
most are comments, other are variable rename
> 
Side effects
Documentation
```release-note
None
```
> ddl: add some comments to help readability

- pkg/planner/core/exhaust_physical_plans.go
- tests/integrationtest/r/planner/core/indexjoin.result
- tests/integrationtest/t/planner/core/indexjoin.test
Issue Number: close #37068
1. Simplify the code logic of build inner side plan task
2. Fix a typo query in test case
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify the logic of index join and fix the typo test case

- pkg/lightning/errormanager/errormanager.go
Issue Number: close #52886 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: fix delete additionally inserted rows for conflict detection 'replace' mode failed

- pkg/sessionctx/variable/sysvar.go
In fact, I found this issue on 7.1, but I saw that the PRs linked at https://github.com/pingcap/tidb/issues/49291 has almost fixed all the pkgs, except for those in the variable. Therefore, I am adding it here.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> variable: avoid generating stack for warning

- pkg/bindinfo/capture_test.go
Issue Number: close #52437
Problem Summary: planner: fix the unstable test TestCaptureFilter
The old implementation of capture can be regarded as deprecated, so skip this test as well.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the unstable test TestCaptureFilter

- pkg/disttask/framework/handle/handle_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> disttask: fix flaky handle test

- pkg/expression/builtin_encryption.go
- pkg/expression/builtin_encryption_vec.go
- pkg/expression/builtin_json.go
- pkg/expression/builtin_json_vec.go
Issue Number: close #52515
Tests 
> 
```
tidb> SELECT JSON_MERGE('{"a": 5}', '{"foo": "bar"}');
+------------------------------------------+
| JSON_MERGE('{"a": 5}', '{"foo": "bar"}') |
+------------------------------------------+
| {"a": 5, "foo": "bar"}                   |
+------------------------------------------+
1 row in set, 1 warning (0.00 sec)
Warning (Code 1681): JSON_MERGE is deprecated and will be removed in a future release.
tidb> SELECT PASSWORD('secret');
+-------------------------------------------+
| PASSWORD('secret')                        |
+-------------------------------------------+
| *14E65567ABDB5135D0CFD9A70B3032C179A49EE7 |
+-------------------------------------------+
1 row in set, 1 …
```
> expression: Fix formatting of deprecation warnings

- pkg/executor/infoschema_reader.go
- pkg/planner/core/base/misc_base.go
- pkg/planner/core/explain.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/memtable_predicate_extractor.go
- pkg/planner/core/memtable_predicate_extractor_test.go
- pkg/planner/core/physical_plans.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move MemtablePredicateExtractor interface to a unified base place.

- pkg/executor/adapter.go
- pkg/executor/compiler.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_test.go
- pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: merge fast plan cache and normal plan cache
planner: merge fast plan cache and normal plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: merge fast plan cache and normal plan cache

- pkg/executor/adapter.go
- pkg/executor/compiler.go
- pkg/planner/core/plan_cache.go
- pkg/sessiontxn/BUILD.bazel
- pkg/sessiontxn/txn_context_test.go
Problem Summary: planner: simplify plan cache for fast point get
planner: simplify plan cache for fast point get
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify plan cache for fast point get 

- WORKSPACE
Issue Number: close #53139
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.21.10

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #40926
Tests 
> 
Side effects
Documentation
```release-note
None
```
> copr: update client-go to fix #40926

- pkg/planner/core/core_init.go
- pkg/planner/core/find_best_task.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move getTaskPlanCost to planner core util

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #53222
Related PR: https://github.com/tikv/client-go/pull/1339
Problem Summary: fix issue of doesn't fast fail request when no available connections 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix issue of doesn't fast fail request when no available connections 

- pkg/expression/builtin_cast.go
- pkg/expression/builtin_cast_test.go
- pkg/expression/builtin_cast_vec.go
Reverts pingcap/tidb#53207
Issue Number: close #53248
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: Reverts pingcap/tidb#53207 (release-8.1) | tidb-test=pr/2330

- pkg/ddl/db_test.go
Issue Number: close #53244
The function `OnJobUpdatedExported` is invoked during `CREATE TABLE` instead of `TRUNCATE TABLE`.
Add a check in `OnJobUpdatedExported`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: stabilize TestTruncateTableAndSchemaDependence

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/collect_column_stats_usage.go
- pkg/planner/core/stats.go
- pkg/statistics/BUILD.bazel
- pkg/statistics/asyncload/BUILD.bazel
- pkg/statistics/asyncload/async_load.go
- pkg/statistics/column.go
- pkg/statistics/handle/storage/BUILD.bazel
- pkg/statistics/handle/storage/read.go
- pkg/statistics/handle/storage/read_test.go
- pkg/statistics/index.go
- pkg/statistics/table.go
we have a function called ```async load```. but we cannot find any code called ```async load```.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: split async load package

- pkg/executor/adapter.go
Issue Number: close #53349
Problem Summary: As title.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: only output log when error is non-nil

- session/session.go
Issue Number: close #46522
Hotfix on 6.5.6
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: reset CTEStorageMap before txn conflict and retry() #49399

- pkg/executor/infoschema_reader.go
- pkg/infoschema/tables.go
- tests/integrationtest/r/explain_easy.result
- tests/integrationtest/r/globalindex/information_schema.result
- tests/integrationtest/t/globalindex/information_schema.test
Issue Number: close #53342
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: add a new column `is_global` into `information_schema.tidb_indexes` table

- pkg/executor/test/tiflashtest/BUILD.bazel
- pkg/executor/test/tiflashtest/tiflash_test.go
- pkg/planner/core/enforce_mpp_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/53565
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: make TestMppAggShouldAlignFinalMode stable

- pkg/executor/sortexec/topn.go
- pkg/executor/sortexec/topn_worker.go
Issue Number: close #53538
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix data race in topn

- pkg/ddl/BUILD.bazel
- pkg/ddl/ddl.go
- pkg/ddl/ddl_worker_test.go
Issue Number: close #39222
- for https://github.com/pingcap/tidb/issues/39222#issuecomment-2135068317, wait each DDL submitted to tidb_ddl_job before run another DDL to make sure DDL submit order
- simplify test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix flaky test TestParallelDDL

- lightning/pkg/importer/get_pre_info.go
- lightning/pkg/importer/get_pre_info_test.go
- pkg/lightning/backend/local/local.go
Change the requirement when using this repo as package in other repo
Tests 
> very easy
Side effects
Documentation
```release-note
None
```
> lightning: release the requirement for NewTargetInfoGetterImpl

- OWNERS_ALIASES
Issue Number: ref #47843
Tests 
> 
Side effects
Documentation
```release-note
None
```
> OWNERS_ALIAS: add approvers to dumpling

- pkg/executor/sortexec/sort.go
Issue Number: close #53866
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: make channel buffer small in sort executor

- pkg/executor/brie.go
Problem Summary: `config.GetGlobalConfig()` will return a pointer and we modified it in `TestBRIEBuilderOPtions`. It will influnced later test cases.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix `TestBRIEBuilderOPtions` change global config

- br/pkg/backup/BUILD.bazel
- br/pkg/backup/client.go
Issue Number: close #54017
the total retry time is only 1.5 seconds.
retry more time to get pd leader
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: retry more time to get pd leader

- pkg/planner/core/plan_cache.go
- pkg/planner/core/tests/prepare/prepare_test.go
- pkg/planner/optimize.go
- pkg/session/session.go
- pkg/sessionctx/context.go
- pkg/util/mock/context.go
Problem Summary: planner: rename session plan cache interface
no logical change, only refactor
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: rename session plan cache interface

- pkg/planner/core/rule_build_key_info.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove unnecessary pointer receiver function

- pkg/parser/types/BUILD.bazel
- pkg/parser/types/field_type.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: use slices.Equal to simple code

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_plans_test.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_join_reorder.go
- pkg/planner/core/rule_max_min_eliminate.go
- pkg/planner/core/rule_semi_join_rewrite.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: make logical join's elements all public for later pkg move

- pkg/sessionctx/variable/sysvar.go
Issue Number: close https://github.com/pingcap/tidb/issues/54096
Tests 
> 
```
mysql> SET @@global.tidb_cloud_storage_uri = 's3://test/test/?provider=test';
ERROR 1105 (HY000): check permission ListObjects failed due to NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers): [BR:ExternalStorage:ErrStorageInvalidPerm
```
Side effects
Documentation
Please …
> global sort: output clear error message

- pkg/parser/charset/encoding.go
minor fix
Tests 
> 
Side effects
Documentation
```release-note
None
```
> chore: update encoding.go

- WORKSPACE
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update rules_go

- OWNERS_ALIASES
Signed-off-by: wuhuizuo <wuhuizuo@126.com>
Issue Number: ref #46911
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update prow OWNERS_ALIASES file

- pkg/planner/core/exhaust_physical_plans.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: eliminate some unnecessary pointer receiver for logical aggregation

- pkg/infoschema/infoschema_v2.go
- pkg/statistics/handle/util/BUILD.bazel
- pkg/statistics/handle/util/table_info.go
support and use table's partition attribute filter
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema, statistics: support and use table's partition attribute filter

- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/plan_cache_test.go
- pkg/types/parser_driver/value_expr.go
Issue Number: close #53872
Problem Summary: planner: fix the issue that cannot find column if using question marker in group-by-clause
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that cannot find column if using question marker in group-by-clause

- pkg/ddl/constraint_test.go
- pkg/executor/show.go
- tests/integrationtest/r/ddl/constraint.result
Issue Number: close #54214
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix show create table output with check constraint

- pkg/domain/domain.go
Issue Number: close https://github.com/pingcap/tidb/issues/54224
Problem Summary: fix misspelling of readMemTicker variable
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: fix misspelling of readMemTicker variable

- pkg/ddl/ddl_api.go
- pkg/infoschema/infoschema_v2.go
- pkg/session/bootstrap.go
Issue Number: ref https://github.com/pingcap/tidb/issues/50959
remove some usages of SchemaTables
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: remove some usages of SchemaTables

- br/pkg/restore/snap_client/systable_restore_test.go
- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
Issue Number: close #54267, ref #53440
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: reserve bootstrap versions for v8.1.x

- pkg/infoschema/infoschema_v2.go
Issue Number: close #54074 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: speed up schemaByID for v2

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/base/plan_base.go
- pkg/planner/core/operator/baseimpl/BUILD.bazel
- pkg/planner/core/operator/baseimpl/plan.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_rebuild_test.go
Problem Summary: planner: add `CloneForPlanCache` method to Plan interface
planner: add `CloneForPlanCache` method to Plan interface
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add `CloneForPlanCache` method to Plan interface

- pkg/expression/builtin_json.go
- tests/integrationtest/r/expression/json.result
- tests/integrationtest/t/expression/json.test
Issue Number: close #54273 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: Return non-retryable error for schema errors

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_sort.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/rule_topn_push_down.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical sort into a separate file for later pkg move

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_lock.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_topn_push_down.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical lock into a separate file for later pkg move

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_union_all.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/rule_topn_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical union all into a separate file for later pkg move

- executor/cte.go
- executor/cte_test.go
- util/cteutil/storage.go
Problem Summary: manually cherry pick https://github.com/pingcap/tidb/pull/54208
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: setup mem tracker for CTE correctly

- util/gctuner/memory_limit_tuner.go
- util/gctuner/memory_limit_tuner_test.go
close pingcap/tidb#48741
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/util: refine tidb_server_memory_limit to make the cpu usage more stable (#48927)

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_partition_union_all.go
- pkg/planner/core/logical_plans.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical partition union all into a separate file for later pkg move.

- pkg/domain/domain.go
Issue Number: close #54046 
Tests 
```
enable fast_create_table, create table concurrently, tidb will not triger full load schema infos
```
> 
Side effects
Documentation
```release-note
None
```
> ddl: enlarge LoadSchemaDiffVersionGapThreshold

- planner/core/plan_stats.go
- sessionctx/variable/session.go
- sessionctx/variable/sysvar.go
- statistics/handle/handle_hist.go
Issue Number: ref #52438
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: upgrade stats timeout checkpoint after it timeouts

- sessionctx/stmtctx/BUILD.bazel
- sessionctx/stmtctx/stmtctx.go
- statistics/handle/handle_hist.go
- statistics/handle/handle_hist_test.go
close pingcap/tidb#52797
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: support global singleflight for sync load (#52796) (#53838)

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/explain.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/hashcode.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_table_dual.go
- pkg/planner/core/rule_build_key_info.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical table dual into a separate file for later pkg move.

- pkg/infoschema/metrics.go
- pkg/infoschema/sieve.go
- pkg/metrics/grafana/tidb.json
- pkg/metrics/infoschema.go
- pkg/metrics/metrics.go
Issue Number: ref https://github.com/pingcap/tidb/issues/50959
Add metrics for infoschema v2 cache size and limit.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: add infoschema v2 cache size and limit

- pkg/ddl/tiflash_replica_test.go
- pkg/testkit/testkit.go
Issue Number: close #53427
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: stabilize TestSkipSchemaChecker

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_window.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical window into a separate file for later pkg move.

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_max_one_row.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/stats.go
- pkg/planner/core/util.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical max one row into a separate file for later pkg move

- pkg/domain/domain_sysvars.go
- pkg/infoschema/infoschema_v2.go
- pkg/infoschema/sieve.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Previously, if we change `tidb_schema_cache_size` to a different number, we still need to execute something(like DDL) to trigger `loadInfoSchema` to make it effective.
This PR makes changes to tidb_schema_cache_size effective immediately.
Tests 
```
mysql> set global tidb_schema_cache_size = 1000;
mysql> set global tidb_schema_cache_size = 10000;
Query OK, 0 rows affected (0.04 sec)
mysql> set global tidb_schema_cache_size = 100000;
Query OK, 0 rows affected (0.04 sec)
```
> 
Side effects
Documentation …
> *: make changes to tidb_schema_cache_size effective immediately

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/explain.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_tikv_single_gather.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_build_key_info.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical tikv single gather into a separate file for later pkg move.

- pkg/executor/executor.go
- pkg/executor/executor_test.go
- pkg/session/test/session_test.go
- pkg/sessionctx/stmtctx/stmtctx.go
- pkg/sessionctx/variable/tidb_vars.go
- pkg/util/context/warn.go
- pkg/util/memory/tracker.go
Issue Number: ref #54047
Problem Summary: `ResetContextOfStmt` involves many memory allocations.
Reduce mem allocs of `ResetContextOfStmt`.
**micro benchmark**
baseline
this PR
**sysbench oltp point select**
https://clinic.pingcap.com.cn/portal/#/orgs/541/clusters/7381420967173394916?from=1718635725&to=1718636325
  | avg lat | p95 lat | throughput | througput diff
-- | -- | -- | -- | --
baseline | 1.51 | 2.97 | 66415.85 | -
this PR | 1.49 | 2.91 | 67188.56 | 1.16%
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: optimize ResetContextOfStmt

- pkg/executor/cte.go
Issue Number: close #54379
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix cte mem tracker failpoint condition

- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/rule_generate_column_substitute.go
- pkg/planner/core/rule_inject_extra_projection.go
Issue Number: ref #54401
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: avoid chained calls to improve debug 

- pkg/testkit/mocksessionmanager.go
Issue Number: close #54395, close #54374
The original implementation of `GetInternalSessionStartTSList` called `Txn(false)`. However, it's not safe to use it if there is something running on the session (which may also use txn internal state).
I changed to call `TxnInfo`, which is safe to be called concurrently, as it'll have an internal lock and copy the data.
Tests 
> It should pass the test without data race.
> 
```release-note
None
```
> testkit: fix data race in `GetInternalSessionStartTSList`

- WORKSPACE
- build/image/base
- build/image/parser_test
- tests/globalkilltest/Dockerfile
Issue Number: close #54398
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade 1.21.12

- pkg/planner/cascades/implementation_rules.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/explain.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_table_scan.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_build_key_info.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical table scan into a separate file for later pkg move

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/hashcode.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_selection.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_build_key_info.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_constant_propagation.go
- pkg/planner/core/rule_derive_topn_from_window.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/rule_outer_to_inner_join.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical selection into a separate file for later pkg move.

- pkg/planner/core/exhaust_physical_plans.go
Issue Number: ref #54401
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: improve code for friendly debug

- docs/design/2024-05-10-extension-authentication-plugin.md
- pkg/extension/README.md
Modify the design doc for auth plugin extension to make it closer to implementation. Also add simple readme doc for how to use the extension auth plugin framework.
Issue Number: close #53181
Need to update the design doc and add readme for the new extension auth plugin framework.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: improve auth plugin design and add readme

- pkg/planner/cascades/implementation_rules.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/explain.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_index_scan.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/property_cols_prune.go
- pkg/planner/core/rule_build_key_info.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical index scan into a separate file for later pkg move

- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_instance.go
- pkg/planner/core/plan_cache_instance_test.go
- pkg/planner/core/plan_cache_lru.go
- pkg/planner/core/plan_cache_lru_test.go
- pkg/planner/core/plan_cache_utils.go
- pkg/sessionctx/context.go
Problem Summary: planner: refactor a few code of plan cache
Add table dirty flags into the plan cache key
No regression
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor a few code of plan cache

- DEPS.bzl
- go.mod
- go.sum
- pkg/executor/internal/calibrateresource/calibrate_resource_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/47421 ref https://github.com/tikv/pd/issues/8349
Tests 
> 
```release-note
None
```
> [cherry-pick] mod: update the pd client

- tests/realtikvtest/statisticstest/BUILD.bazel
- tests/realtikvtest/statisticstest/statistics_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/54022
Added a test case for the issue 54022 to make sure we don't have this bug on master.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add a testcase for issue 54022

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_union_scan.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical union scan into a separate file for later pkg move.

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_show.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical show logic into a separate file for later pkg move.

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_mem_table.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical mem table logic into a separate file for later pkg move

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_show_ddl_jobs.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical show ddl jobs into a separate file for later pkg move.

- pkg/session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close #54452
The test `TestUpgradeWithPauseDDL` is about during the upgrade process, alternately executing a bunch of user DDL and system DDL, and then verifying that the user DDL will be paused and the system DDL can be executed normally.
However, this test is not synchronized. When the last system DDL is executed, the upgrade process just ends, and then the system DDL stays in the running state because the DDL worker is closed. After the upgrade is completed, the DDL owner restarts and resumes the previous user DDL while `getJob()`. Finally, the user DDL is executed first, and the last system DDL is executed last.
Run system DDL synchronously.
Tests 
> 
Side effects
Documentation
Please refer to …
> test: stabilize TestUpgradeWithPauseDDL

- pkg/statistics/builder.go
- pkg/statistics/histogram.go
We need to add more comments to the histogram bucket structure to make it easier to understand.
- Added some comments for the fields from the bucket struct.
- Added some comments for building histogram procedure.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add more comments for the histogram bucket

- pkg/executor/cte.go
Issue Number: close #54379
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix cte mem tracker failpoint condition again

- README.md
Issue Number: N/A
Problem Summary: The X icon can't display well with the outdated link. This PR fixes it and removes several redundant spaces.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> readme: fix the failure of X icon display

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_cte.go
- pkg/planner/core/logical_cte_table.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical cte table into a separate file for later pkg move

- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/planbuilder_test.go
Problem Summary: planner: add more test cases for Plan.Clone
planner: add more test cases for Plan.Clone
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for Plan.Clone

- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_show.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move show contents to logical_show

- pkg/planner/core/collect_column_stats_usage.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_cte.go
- pkg/planner/core/logical_cte_table.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_union_scan.go
- pkg/planner/core/recheck_cte.go
- pkg/planner/core/rule_partition_processor.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: export logical cte and cte_table's elements for later pkg move.

- docs/tidb_http_api.md
My Goland auto fixed it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: fix markdown list number

- br/pkg/task/backup_ebs.go
Issue Number: close #54555
Uses # of volumes to determine ebs backup progress (rather than number of stores). We already use # of volumes to determine [ebs restore progress](https://github.com/pingcap/tidb/blob/master/br/pkg/task/restore_ebs_meta.go#L179).
Tests 
> 
Conduct volume backup of single tikv w/ 3 attached volumes on current version. Ex. logs from backup w/ single tikv, but 3 volumes
```
I0710 14:37:26.544144       9 backup.go:302] [2024/07/10 14:37:26.544 +00:00] [INFO] [progress.go:160] [progress] [step=backup] [progress=100.00%] [count="100 / 100"] [speed="? p/s"] [elapsed=1m38s] [remaining=1m38s]
```
where 100 corresponds to 100% of a single tikv store.
With fix, observe backup log:
```
I0710 …
```
> br: use tikv volume count for ebs backup progress

- pkg/server/main_test.go
Issue Number: close #54642
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server: ignore goleak for ristretto.(*defaultPolicy).processItems

- pkg/planner/cascades/implementation_rules.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_join.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove unnecessary join's receiver func and export some of them for usage.

- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_clone_generator.go
- pkg/planner/property/physical_property.go
- pkg/planner/util/BUILD.bazel
- pkg/planner/util/misc.go
Problem Summary: planner: use code-gen to generate CloneForPlanCache method for some operators
planner: use code-gen to generate CloneForPlanCache method for some operators
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use code-gen to generate CloneForPlanCache method for some operators 

- pkg/planner/core/logical_join.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_selection.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: export some functional-dependency related func utility in logical plans

- pkg/planner/cardinality/pseudo.go
- pkg/planner/cardinality/selectivity.go
- pkg/statistics/table.go
I found some typos when I was reading the code.
Fixed some typos.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix some typos

- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/logical_join.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/rule_join_reorder.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify part of join's member func into logical_join file.

- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_window.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move window frame definition to logical window for logical convergence

- pkg/domain/domain.go
Issue Number: close #54690
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: fix race on cancelFns

- pkg/executor/set_config.go
- pkg/executor/set_test.go
Issue Number: close #52912 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: improve set config error message for ms

- pkg/ddl/schematracker/BUILD.bazel
- pkg/ddl/schematracker/dm_tracker_test.go
- pkg/util/mock/context.go
Issue Number: close #54760
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util, schematracker: mock sctx turn on EnableListTablePartition

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #54375
Tests 
> test added in client-go
> 
Side effects
Documentation
```release-note
None
```
> *: cherry-pick fix of #54375 to release-7.1

- pkg/planner/cascades/implementation_rules.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/logical_apply.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_decorrelate.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical apply into a separate file for later pkg move.

- tests/integrationtest/r/imdbload.result
- tests/integrationtest/r/tpch.result
- tests/integrationtest/t/imdbload.test
- tests/integrationtest/t/tpch.test
Update the stats used by test to ver2 instead of ver1. So we can know real execution plan of current TiDB's default behavior.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: update the stats and cost for tpch and imdb to ver2

- pkg/server/tests/cursor/cursor_test.go
Issue Number: close #54801
I left a comment to add tests for concurrent cursor fetch.
In this PR, I added these tests to enrich the case about running normal statements while there is a cursor in the background at the same time.
Tests 
> 
```release-note
None
```
> tests: add tests for concurrent cursor fetch

- pkg/ddl/ddl_api.go
- tests/integrationtest/r/ddl/partition.result
- tests/integrationtest/t/ddl/partition.test
Issue Number: close #54829
Tests 
> 
Side effects
Documentation
```release-note
Fix create non-strictly increasing range partition success.
```
> ddl, partition: fix create strictly increasing range partition

- pkg/ddl/callback.go
- pkg/ddl/constraint_test.go
- pkg/ddl/db_change_test.go
- pkg/ddl/ddl.go
- pkg/ddl/ddl_test.go
- pkg/ddl/ddl_tiflash_api.go
- pkg/ddl/executor.go
- pkg/ddl/index.go
- pkg/ddl/job_table.go
- pkg/ddl/multi_schema_change.go
- pkg/ddl/multi_schema_change_test.go
- pkg/ddl/reorg_partition_test.go
- pkg/ddl/schematracker/checker.go
- pkg/ddl/tests/fail/fail_db_test.go
- pkg/ddl/tests/indexmerge/merge_test.go
- pkg/ddl/util/callback/BUILD.bazel
- pkg/ddl/util/callback/callback.go
- pkg/ddl/util/callback/callback_test.go
- pkg/domain/domain.go
- pkg/session/tidb.go
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: remove interceptor and replace some hook with failpoint

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/collect_column_stats_usage.go
- pkg/planner/core/core_init.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/operator/logicalop/BUILD.bazel
- pkg/planner/core/operator/logicalop/logical_cte_table.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move logical cte table into logicalop pkg.

- pkg/planner/cascades/BUILD.bazel
- pkg/planner/cascades/implementation_rules.go
- pkg/planner/cascades/transformation_rules.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/logical_aggregation.go
- pkg/planner/core/logical_cte.go
- pkg/planner/core/logical_join.go
- pkg/planner/core/logical_projection.go
- pkg/planner/core/logical_selection.go
- pkg/planner/core/logical_sort.go
- pkg/planner/core/logical_tikv_single_gather.go
- pkg/planner/core/logical_top_n.go
- pkg/planner/core/logical_window.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/rule/util/BUILD.bazel
- pkg/planner/core/rule/util/misc.go
- pkg/planner/core/rule_eliminate_projection.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move projection elimination related ReplaceExpr/Column code to rule util.

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/operator/logicalop/BUILD.bazel
- pkg/planner/core/operator/logicalop/logical_sequence.go
- pkg/planner/core/rule_push_down_sequence.go
- pkg/planner/core/stringer.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move logical sequence into logicalop pkg.

- tests/integrationtest/r/executor/expand.result
- tests/integrationtest/t/executor/expand.test
Issue Number: close https://github.com/pingcap/tidb/issues/42631
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: import more tests about rollup expand

- pkg/ddl/delete_range.go
- pkg/ddl/index.go
- pkg/ddl/index_modify_test.go
- pkg/ddl/sanity_check.go
Issue Number: close #55014
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl, partition: fix del_range for add global index

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #55081
Related PR: https://github.com/tikv/client-go/pull/1409
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update tikv/client-go for fix issue that store's liveness may incorrectly marked as unreachable when the store restarts with label changed

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/exhaust_physical_plans_test.go
- pkg/planner/core/plan_cache_rebuild.go
Problem Summary: planner: simplify the indexJoinBuildHelper structure
ONLY REFACTORYING, NO LOGICAL CHANGE.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify the indexJoinBuildHelper structure

- DEPS.bzl
- go.mod
- go.sum
This is a reopened PR of https://github.com/pingcap/tidb/pull/54943 which cherry-picks https://github.com/pingcap/tidb/pull/53698
Issue Number: close #53540
Update client-go to fix the problem that when query OOM kill happens in a transaction, the next query in the transaction may encounter panic when starting fair locking.
Tests 
> 
Side effects
Documentation
```release-note
Fix the problem that when query OOM kill happens in a transaction, the next query in the transaction may encounter panic when trying to start fair locking
```
> *: Update client-go to fix fair locking panic when executing a query after OOM kill in a transaction

- tests/integrationtest/r/infoschema/infoschema.result
- tests/integrationtest/run-tests.sh
- tests/integrationtest/t/executor/executor.test
- tests/integrationtest/t/executor/foreign_key.test
- tests/integrationtest/t/executor/index_merge_reader.test
- tests/integrationtest/t/executor/issues.test
- tests/integrationtest/t/executor/jointest/join.test
- tests/integrationtest/t/infoschema/infoschema.test
Problem Summary: Update mysql-tester to drop created database automatic after tests finished.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: update mysql-tester

- pkg/domain/BUILD.bazel
- pkg/domain/domain.go
- pkg/planner/core/metrics/metrics.go
- pkg/planner/core/plan_cache_instance.go
- pkg/planner/core/plan_cache_lru.go
- pkg/sessionctx/context.go
Problem Summary: planner: add metrics for instance plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add metrics for instance plan cache

- pkg/ddl/executor_test.go
Issue Number: close #55232
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix flaky TestGenIDAndInsertJobsWithRetry

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/operator/logicalop/BUILD.bazel
- pkg/planner/core/operator/logicalop/logical_union_scan.go
- pkg/planner/core/operator/logicalop/logical_window.go
- pkg/planner/core/rule_partition_processor.go
- pkg/planner/pattern/pattern.go
- pkg/planner/pattern/pattern_test.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move logical union scan into logicalop pkg.

- WORKSPACE
- build/image/base
- build/image/parser_test
- tests/globalkilltest/Dockerfile
Issue Number: close https://github.com/pingcap/tidb/issues/55249
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.21.13

- pkg/planner/core/indexmerge_path.go
- pkg/planner/core/indexmerge_unfinished_path.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove useless pointer receiver implementation.

- pkg/metrics/grafana/tidb_resource_control.json
append write dimension of the RU max metric
before 
after
Issue Number: Ref #54434
Tests 
> 
```release-note
None
```
> metric/resource_control: append write dimension of the RU max metric

- pkg/table/tables/tables.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tables: remove unnecessary function

- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/casetest/instanceplancache/main_test.go
Problem Summary: planner: add more test cases for instance plan cache
planner: add more test cases for instance plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for instance plan cache

- pkg/executor/adapter.go
- pkg/executor/test/executor/executor_test.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
Issue Number: close #54999
```
Support global scope for tidb_low_resolution_tso sys var.
```
Tests 
> 
Side effects
Documentation
```release-note
Support global scope for tidb_low_resolution_tso system variable.
```
> server: support global scope for tidb_low_resolution_tso sys var

- lightning/tests/lightning_distributed_import/run.sh
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: fix flaky integration test

- pkg/planner/core/indexmerge_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix index merge typo

- pkg/infoschema/infoschema_v2.go
Issue Number: close #55425, #52726
apply diff should return the affected table IDs so that schemaValidator can check whether transaction modified data involve schema changes. 
Tests 
Found and covered by our integration, so no need to add a new one.
> 
Side effects
Documentation
```release-note
None
```
> infoschema: let applyDropSchemaV2 return affected table IDs

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/indexmerge_path.go
- pkg/planner/core/logical_datasource.go
- pkg/planner/core/logical_plans_test.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify datasource's pointer receiver member function.

- br/pkg/restore/snap_client/client.go
- br/pkg/restore/snap_client/client_test.go
- br/pkg/restore/snap_client/export_test.go
- br/pkg/restore/snap_client/pipeline_items.go
- br/pkg/task/restore.go
- pkg/util/misc_test.go
- pkg/util/util.go
Issue Number: ref #52877
we can clean some codes
simplify the `CreateTable` stage
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: clean codes -- simplify the `CreateTable` stage

- pkg/ddl/backfilling_operators.go
- pkg/ddl/export_test.go
- pkg/disttask/importinto/proto.go
- pkg/disttask/importinto/subtask_executor.go
- pkg/disttask/importinto/task_executor.go
- pkg/disttask/operator/operator.go
- pkg/disttask/operator/pipeline_test.go
- pkg/disttask/operator/wrapper.go
- pkg/executor/executor.go
- pkg/resourcemanager/pool/workerpool/BUILD.bazel
- pkg/resourcemanager/pool/workerpool/workerpool.go
- pkg/resourcemanager/pool/workerpool/workpool_test.go
- tests/realtikvtest/importintotest/import_into_test.go
- tests/realtikvtest/importintotest/job_test.go
Issue Number: ref #55497
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> workerpool: add TaskMayPanic interface to remind caller handles panic

- pkg/metrics/grafana/performance_overview.json
Issue Number: close #55579
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: fix the wrong read/write metrics for version < 8.1

- pkg/table/tables/bench_test.go
#55246 refactored the interface but doesn't change the benchmark, which leads to a huge regression.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: specify DupKeyCheckLazy in BenchmarkAddRecordInPipelinedDML

- pkg/disttask/framework/scheduler/scheduler_test.go
- pkg/table/tables/cache_test.go
Issue Number: close #55594
Problem Summary: See https://github.com/pingcap/tidb/issues/55594#issuecomment-2306607046
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix unstable TestParallelErrStage

- pkg/disttask/framework/scheduler/scheduler_test.go
Issue Number: close #55658
due to info cache v2, the task/subtask id might bump to 30000+
Tests 
> 
Side effects
Documentation
```release-note
None
```
> disttask: fix flaky test TestParallelCancel

- pkg/parser/charset/BUILD.bazel
- pkg/parser/charset/charset.go
- pkg/parser/go.mod
- pkg/parser/goyacc/BUILD.bazel
- pkg/parser/goyacc/main.go
- pkg/parser/types/BUILD.bazel
- pkg/parser/types/field_type.go
Issue Number: close #55733
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: upgrade golang version to 1.21

- pkg/planner/core/memtable_infoschema_extractor_test.go
Issue Number: close #55750
Split into two test (suites) to avoid slow test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: split test case to avoid slow test

- OWNERS_ALIASES
Tests 
> 
Side effects
Documentation
```release-note
None
```
> owners: update after Rustin170506 changed GitHub ID

- pkg/ddl/partition.go
- pkg/expression/builtin_cast.go
- pkg/expression/builtin_cast_vec.go
- pkg/expression/builtin_compare.go
- pkg/planner/core/rule_partition_processor.go
- pkg/types/convert.go
- pkg/types/datum.go
Issue Number: NA
Fix typo in function name `IntergerSignedLowerBound`.
Tests 
> 
Side effects
- NA
Documentation
- NA
```release-note
None
```
> *: fix typo interger -> integer

- WORKSPACE
- build/nogo_config.json
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade rules_go v0.50

- pkg/executor/infoschema_reader_test.go
Issue Number: close #55752
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestColumnTable

- pkg/ddl/executor_nokit_test.go
Issue Number: close #55753
use `slices.SortFunc` to make the result stable
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: make `TestMergeCreateTableJobs` stable

- pkg/executor/join/hash_join_v2.go
- pkg/executor/test/issuetest/executor_issue_test.go
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
- pkg/executor/test/seqtest/seq_executor_test.go
enable hash join v2 by default for test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: enable hash join v2 for temporary test

- pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/main_test.go
- pkg/statistics/handle/autoanalyze/refresher/worker.go
- pkg/statistics/handle/autoanalyze/refresher/worker_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/55618
This PR split from the https://github.com/pingcap/tidb/pull/55621.
It introduced a new analysis worker to help us maintain the currently running jobs.
If you want to know how to use it, please check https://github.com/pingcap/tidb/pull/55621.
It also added a new API for the analysis job, because we need to add a unique identifier to avoid adding the same table or job again.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add the analysis worker

- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/algorithm.go
- pkg/planner/indexadvisor/indexadvisor.go
- pkg/planner/indexadvisor/indexadvisor_test.go
- pkg/planner/indexadvisor/indexadvisor_tpch_test.go
- pkg/planner/indexadvisor/model.go
- pkg/planner/indexadvisor/utils.go
Problem Summary: planner: move index advisor into the kernel
planner: move index advisor into the kernel
1. move the algorithm code into TiDB.
2. add more test cases
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move index advisor into the kernel

- pkg/domain/domain.go
Problem Summary: planner: hide instance plan cache eviction log if no plan is evicted
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: hide instance plan cache eviction log if no plan is evicted

- pkg/planner/core/main_test.go
- pkg/statistics/handle/autoanalyze/BUILD.bazel
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
- pkg/statistics/handle/autoanalyze/refresher/worker.go
- pkg/statistics/handle/handle.go
- pkg/statistics/handle/types/interfaces.go
Issue Number: close https://github.com/pingcap/tidb/issues/55618
close https://github.com/pingcap/tidb/pull/55621
Started using analysis worker to run analysis jobs. The analysis jobs are always spawned whenever possible.
1. Init the analysis worker when creating the refresher.
2. Only create one single refresher per stats handle.
For unit tests, I inject WaitAutoAnalyzeFinishedForTest to wait for all analysis jobs to finish. This would help us make the tests easier because many tests depend on this API to analyze tables.
Tests 
> 
Side effects
Documentation …
> statistics: use analysis worker to run analysis jobs

- OWNERS_ALIASES
Issue Number: close #46911
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update owner_aliases to add owners for meta pkg

- pkg/domain/infosync/info.go
- pkg/executor/BUILD.bazel
- pkg/executor/show_placement_test.go
Issue Number: close #55945
Added some tests for `show placement` to check its status
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: add tests for status returned by `show placement`

- pkg/ddl/executor.go
Issue Number: close #55953 
Tests 
> 
just return different infos by different api
Side effects
Documentation
```release-note
None
```
> ddl: remove schemaTableInfos call of DropSchema

- pkg/metrics/grafana/tidb_runtime.json
Issue Number: ref https://github.com/pingcap/tidb/issues/55390
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/metrics: introduce a more detailed metrics for Go STW Latency

- DEPS.bzl
- go.mod
- go.sum
- pkg/config/config.toml.example
- pkg/config/config_test.go
…
Issue Number: close #55984
Problem Summary: As title and issue said.
related PR: https://github.com/tikv/client-go/pull/1461
Tests 
> 
Side effects
Documentation
```release-note
None
```
> config: change grpc-keepalive-timeout from uint to float64, for support millisecond timeout

- pkg/metrics/grafana/tidb_runtime.json
This commit introduces a new monitoring panel to track the CPU time proportion for several key operations:
- gc_total: Total CPU time spent on gc mark and gc pause.
- user_total: CPU time spent on executing user Go code.
- scavenge_total: CPU time dedicated to memory scavenging tasks.
- idle_total: CPU time that was idle and not used by Go or Go runtime code.
In addition, more detailed metrics such as gc_mark_assist, gc_mark_dedicated, gc_mark_idle, gc_pause, and scavenge_assist are included in the panel but are hidden by default to avoid clutter. These metrics can be revealed as needed for deeper analysis.
Note: The CPU portion values displayed here are different from the CPU proportions sampled in the Go CPU profile.
More details are shown as …
> pkg/metrics: add a panel for estimated portion of cpu time

- pkg/ddl/BUILD.bazel
- pkg/ddl/add_column.go
- pkg/ddl/cluster.go
- pkg/ddl/create_table.go
- pkg/ddl/ddl.go
- pkg/ddl/modify_column.go
- pkg/ddl/notifier/BUILD.bazel
- pkg/ddl/notifier/schema_change_notifier.go
- pkg/ddl/notifier/schema_change_notifier_test.go
- pkg/ddl/partition.go
- pkg/ddl/table.go
- pkg/ddl/util/BUILD.bazel
- pkg/ddl/util/util_test.go
- pkg/statistics/handle/ddl/BUILD.bazel
- pkg/statistics/handle/ddl/ddl.go
- pkg/statistics/handle/ddl/ddl_test.go
- pkg/statistics/handle/ddl/drop_partition.go
- pkg/statistics/handle/ddl/exchange_partition.go
- pkg/statistics/handle/ddl/reorganize_partition.go
- pkg/statistics/handle/ddl/truncate_partition.go
- pkg/statistics/handle/types/BUILD.bazel
- pkg/statistics/handle/types/interfaces.go
Init a new package named `notifier` to store code more conveniently and neatly.
No logical change, only modify pkg name 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: move `SchemaChangeEvent` related code to a package

- pkg/metrics/grafana/tidb_runtime.json
Before:
After:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/metrics: make the  golang gc mpanel more readable

- pkg/metrics/grafana/tidb_runtime.json
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/metrics: add panels for heap alloc and heap free

- pkg/ddl/ddl_history.go
- pkg/ddl/notifier/BUILD.bazel
- pkg/ddl/notifier/publish.go
- pkg/ddl/notifier/publish_testkit_test.go
- pkg/ddl/notifier/store.go
- pkg/infoschema/cache.go
Issue Number: ref https://github.com/pingcap/tidb/issues/55722
add minimal API that DDL can use it to publish schema change
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl_notifier: add publish related API

- pkg/ddl/executor.go
- pkg/ddl/job_submitter.go
- pkg/ddl/job_submitter_test.go
- pkg/ddl/resource_group.go
- pkg/meta/model/BUILD.bazel
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
Issue Number: ref #53930
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: args v2 for create/alter/drop resource group

- pkg/executor/aggregate/agg_spill.go
- pkg/executor/sortexec/BUILD.bazel
- pkg/executor/sortexec/sort_spill.go
- pkg/executor/sortexec/topn_spill.go
- pkg/executor/sortexec/topn_spill_test.go
- pkg/util/memory/action.go
Issue Number: close #56185
Tests 
> 
Side effects
Documentation
```release-note
fix the issue that fails to trigger the fallback action of topn executor
```
> executor: fix the fail of triggering topn fallback action

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref https://github.com/pingcap/tidb/issues/56231
Tests 
> 
```release-note
None
```
> mod: Update to the latest client-go for release 7.5

- pkg/executor/executor.go
- pkg/planner/core/planbuilder.go
- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/algorithm.go
- pkg/planner/indexadvisor/indexadvisor.go
- pkg/planner/indexadvisor/options.go
- pkg/planner/indexadvisor/options_test.go
Problem Summary: planner: support `recommend index set <opt>=<val>`
planner: support `recommend index set <opt>=<val>`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: support `recommend index set <opt>=<val>`

- pkg/privilege/privileges/ldap/ldap_common_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56309
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestConnectThrough636

- pkg/executor/show_placement_test.go
Issue Number: close #56303
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestShowPlacementPrivilege

- pkg/executor/show_placement_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56313
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestShowPlacement

- pkg/domain/domain.go
Issue Number: ref #54552
move UpdateStatsHealthyMetrics into updateStatsWorker. This way, it will not compete for resources with sync statistic. because we find that sync stats will pause for too much time to sync stats as soon as possible. it will lead to miss some stats to sync.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: move UpdateStatsHealthyMetrics into updateStatsWorker

- pkg/metrics/grafana/tidb.json
- pkg/metrics/metrics.go
- pkg/metrics/server.go
- pkg/server/server.go
Issue Number: ref #56271 
If we get some internal session leak, this new added panel can catch it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server,metrics: add a metrics for internal session count

- pkg/ddl/notifier/BUILD.bazel
- pkg/ddl/notifier/store.go
- pkg/ddl/notifier/subscribe.go
- pkg/ddl/notifier/testkit_test.go
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl_notifier: delete event after all handlers finish processing

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #55287, ref tikv/tikv#17459
Adopt new 8.4 features, include:
- txn status broadcase
- ART, a new memdb implementation
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: bump client-go to adopt txn status broadcast & new memdb(ART)

- pkg/expression/builtin_time.go
- pkg/expression/distsql_builtin.go
- pkg/expression/expr_to_pb_test.go
- pkg/expression/infer_pushdown.go
- pkg/planner/core/exhaust_physical_plans.go
- tests/integrationtest/r/cte.result
Issue Number: close https://github.com/pingcap/tidb/issues/56297
TiKV PR: https://github.com/tikv/tikv/pull/17541
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: pushdown add_date/sub_date expressions to tikv

- pkg/executor/executor.go
- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/indexadvisor_sql_test.go
- pkg/planner/indexadvisor/indexadvisor_test.go
- pkg/planner/indexadvisor/indexadvisor_tpch_test.go
Problem Summary: planner: more test cases for index advisor
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: more test cases for index advisor

- pkg/planner/util/optimizetrace/opt_tracer.go
assigment -> assignment
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: update opt_tracer.go

- pkg/ddl/index.go
- pkg/ddl/notifier/events.go
- pkg/ddl/notifier/events_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/55722
1. Added NewAddIndexEvent and GetAddIndexInfo APIs.
2. Renamed ColumnInfos to Columns because the information is invariable plural.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl_notifier: add NewAddIndexEvent API

- pkg/meta/model/job.go
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
- pkg/meta/model/job_test.go
Issue Number: ref #53930 
job argument fill v2 is same among all jobs, we can abstract it
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: simplify job args fill

- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/casetest/instanceplancache/others_test.go
- pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: add more test cases for plan cache
planner: add more test cases for plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for plan cache

- pkg/statistics/handle/ddl/BUILD.bazel
- pkg/statistics/handle/ddl/ddl.go
- pkg/statistics/handle/ddl/ddl_test.go
- pkg/statistics/handle/ddl/drop_partition.go
- pkg/statistics/handle/ddl/exchange_partition.go
- pkg/statistics/handle/ddl/truncate_partition.go
- pkg/statistics/handle/globalstats/global_stats_async.go
- pkg/statistics/handle/handle.go
- pkg/statistics/handle/storage/read.go
- pkg/statistics/handle/storage/save.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/storage/update.go
- pkg/statistics/handle/usage/session_stats_collect.go
- pkg/statistics/handle/util/util.go
in a short peroid the HandleDDLEvent and new SchemaChangeHandler will both exist, so I extract some function to let them execute the same logic.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> stats: extract some functions for future SchemaChangeHandler use

- go.mod
- pkg/server/tests/servertestkit/BUILD.bazel
- pkg/server/tests/servertestkit/testkit.go
- pkg/util/cgroup/BUILD.bazel
- pkg/util/cgroup/cgroup.go
Using the correct `errors` package.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/server: using the correct errors import package

- br/pkg/checkpoint/BUILD.bazel
- br/pkg/checkpoint/backup.go
- br/pkg/checkpoint/checkpoint.go
- br/pkg/checkpoint/checkpoint_test.go
- br/pkg/checkpoint/log_restore.go
- br/pkg/checkpoint/restore.go
Issue Number: close #56394 
flush checkpoint need retry
add retry logical when flush checkpoint
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: retry to flush checkpoint

- pkg/executor/set.go
- tests/integrationtest/r/new_character_set.result
- tests/integrationtest/t/new_character_set.test
Issue Number: close #56439
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix `set names` with `default_collation_for_utf8mb4` vars

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref #55287
TiDB DML always checks if the key exists before setting values, the latest client-go patch cache the address of last visited key, so it will save some CPU for DML.
Tests 
> 
* master
```sql
mysql> begin optimistic;
Query OK, 0 rows affected (0.00 sec)
mysql> insert into _sbtest1 select * from sbtest1;
Query OK, 10000000 rows affected (24.61 sec)
Records: 10000000  Duplicates: 0  Warnings: 0
```
* This PR
```sql
mysql> begin optimistic;
Query OK, 0 rows affected (0.00 sec)
mysql> insert into _sbtest1 select * from sbtest1;
Query OK, 10000000 rows affected (22.99 sec)
Records: 10000000  Duplicates: 0  Warnings: 0
```
Side effects
Documentation …
> *: bump client-go to adopt cache for art

- pkg/ddl/index.go
- pkg/executor/show.go
- pkg/meta/model/index.go
- pkg/sessionctx/variable/varsutil.go
Issue Number: ref https://github.com/pingcap/tidb/issues/54245
Small code refinement so that optimizer can use it more friendly. `variable.xxx` doesn't seems to be a right place.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Small refine for Vector Search related utils

- pkg/ddl/create_table.go
- pkg/ddl/executor.go
- pkg/ddl/index_modify_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56491
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: support add nonymous vector index when creating table

- pkg/metrics/grafana/generate_json.sh
- pkg/metrics/grafana/tidb_resource_control.json
- pkg/metrics/grafana/tidb_resource_control.jsonnet
Issue Number: close https://github.com/pingcap/tidb/issues/56547
Tests 
> 
```release-note
None
```
> metrics: fix some panels of rc metrics that cannot show in the cluster deployed by the operator 

- pkg/session/bootstrap.go
- pkg/session/session.go
Issue Number: close #56489 
ctx is nil and it panic here:
https://github.com/pingcap/tidb/blob/1eb0c8c1235c21ebc0177db8e3deb4b05ef5bcba/pkg/infoschema/infoschema_v2.go#L625-L627
Tests 
Follow the upgrade steps described in the issue
> 
Side effects
Documentation
```release-note
None
```
> session: fix bootstrap panic when upgrading to master

- pkg/lightning/config/config.go
Issue Number: ref #56606
Tests 
import files from azurite, success
> 
Side effects
Documentation
```release-note
None
```
> lightning: allow use azure as data source

- pkg/ddl/job_worker.go
- pkg/ddl/schema_version.go
- pkg/ddl/table.go
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
Issue Number: ref #53930
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: pass runtime info through jobContext for rename table(s)

- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
Issue Number: close #56574
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: make all DDLs reentrant in upgradeToVer212

- Makefile
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Makefile: add bazel_mirror_upload entry

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #56635
I checked that other `go mod graph` usage is from unit tests. https://github.com/pingcap/tidb/pull/56645#discussion_r1800385072
Close the issue. If it's not resolved, we can reopen it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dep: update dependencies to update go-farm

- pkg/ddl/backfilling_operators.go
Issue Number: ref #56733
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> disttask: print total count in log

- pkg/planner/cascades/memo/group.go
- pkg/planner/cascades/memo/group_and_expr_test.go
- pkg/planner/cascades/memo/group_expr.go
- pkg/planner/cascades/memo/memo.go
- pkg/planner/cascades/rule/BUILD.bazel
- pkg/planner/cascades/rule/binder.go
- pkg/planner/cascades/rule/binder_test.go
- pkg/planner/pattern/pattern.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add stack based pattern binder logic.

- BUILD.bazel
- tools/check/BUILD.bazel
- tools/check/ut.go
Issue Number: ref #55480
1、fix wrong code in ```ut.go```
2、add bazel build config for ```util/check```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tools: fix built for ut tool

- .github/licenserc.yml
When running `make check` locally this might happen:
```
INFO: Running command line: /bin/bash -c 'cd /home/dvaneeden/dev/pingcap/tidb &&  bazel-bin/external/com_github_apache_skywalking_eyes/cmd/license-eye/license-eye_/license-eye -c ./.github/licenserc.yml header check'
INFO Loading configuration from file: ./.github/licenserc.yml 
INFO Totally checked 447922 files, valid: 3189, invalid: 5, ignored: 444728, fixed: 0 
INFO GITHUB_TOKEN is not set, license-eye won't comment on the pull request 
ERROR the following files don't have a valid license header: 
cmd/tidb-server/tidb-slow.log
export-2024-10-24T15:01:58+02:00/metadata
pkg/executor/tidb-slow-2020-02-14T19-04-05.01.log
pkg/extension/_import/generated-enterprise.go
tests/integrationtest/tidb-slow.log 
ERROR one or …
```
> *: Add slowlog, metadata, etc to licenserc to ignore

- pkg/executor/join/hash_join_v2.go
minor refine of hash join v2
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: minor refine of hash join v2

- pkg/metrics/grafana/tidb.json
- pkg/metrics/metrics.go
- pkg/metrics/server.go
- pkg/planner/core/metrics/metrics.go
- pkg/planner/core/plan_cache.go
Problem Summary: planner: add a panel to display the fine-grained operation duration of the Plan Cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add a panel to display the fine-grained operation duration of the Plan Cache

- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_apply.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add generated hash64 and equals implementing for logical apply.

- pkg/ttl/ttlworker/timer_sync.go
- pkg/ttl/ttlworker/timer_sync_test.go
Issue Number: close #57112
fix a panic sometimes when deleting a TTL timer while executing SQL manually.
see PR
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: fix some panic when delete a ttl timer manually

- WORKSPACE
- build/image/base
- build/image/parser_test
Issue Number: close #57196
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.23.3

- Makefile
Issue Number: ref #57191
see https://github.com/pingcap/tidb/issues/57191#issuecomment-2461851284, we can revert this when the issue of `coverage` is fixed
Tests 
> 
Side effects
Documentation
```release-note
None
```
> makefile: replace `bazel coverage` with `bazel test`

- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_limit.go
- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add generation of hash64 and equals for logical limit

- pkg/executor/main_test.go
Issue Number: close #57250
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix goleak client-go/v2/config/retry.(*Config).createBackoffFn.newBackoffFn

- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_projection.go
- pkg/planner/core/operator/logicalop/logical_selection.go
- pkg/planner/core/operator/logicalop/logical_show.go
- pkg/planner/core/operator/logicalop/logical_show_ddl_jobs.go
- pkg/planner/core/operator/logicalop/logical_sort.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: gen hash64 equals for logical projection/selection/show/sort.

- pkg/metrics/grafana/tidb.json
- pkg/planner/core/metrics/metrics.go
- pkg/planner/core/plan_cache.go
Problem Summary: planner: add a new metrics to record the Instance Plan Cache clone duration
planner: add a new metrics to record the Instance Plan Cache clone duration
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add a new metrics to record the Instance Plan Cache clone duration

- pkg/executor/test/issuetest/executor_issue_test.go
- pkg/planner/core/logical_plan_builder.go
Issue Number: close https://github.com/pingcap/tidb/issues/56640
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix the issue when union all cast('xxxx' as char) and a integer

- pkg/executor/explainfor_test.go
- pkg/planner/core/common_plans.go
Issue Number: close #55669
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: print dynamic prune info in explain for connection

- pkg/lightning/mydump/loader.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: log error cause when SampleFileCompressRatio fail

- pkg/session/session.go
Issue Number: close #57482
Add create/drop/set bindings to CRUCIAL OPERATION log.
Tests 
* create a cluster
* run create/drop/set binding statements
* check CRUCIAL OPERATION log, e.g.
```text
[2024/11/19 11:19:54.383 +08:00] [INFO] [session.go:4109] ["CRUCIAL OPERATION"] [conn=2097154] [schemaVersion=55] [cur_db=test] [sql="create global binding using select 1"] [user=root@%]
[2024/11/19 11:21:19.221 +08:00] [INFO] [session.go:4109] ["CRUCIAL OPERATION"] [conn=2097154] [schemaVersion=55] [cur_db=test] [sql="set binding disabled for select 1"] [user=root@%]
[2024/11/19 11:22:18.493 +08:00] [INFO] [session.go:4109] ["CRUCIAL OPERATION"] [conn=2097154] [schemaVersion=55] [cur_db=test] [sql="drop global binding for select 1"] [user=root@%]
```
> - [ ] I checked and no code …
> pkg/session: add binding operations to CRUCIAL OPERATION log

- pkg/util/codec/codec_test.go
- pkg/util/codec/float.go
- tests/integrationtest/r/expression/issues.result
- tests/integrationtest/t/expression/issues.test
This reverts commit 2cb550a55adc1dc942e77b8b4abd76712a134c55.
Issue Number: close https://github.com/pingcap/tidb/issues/57500
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Revert "util: fix codec for negative zero(#57343) (#57453)" | tidb-test=pr/2431

- br/tests/br_table_partition/prepare.sh
- pkg/distsql/request_builder.go
Issue Number: close #57469
Tests 
```
use br to backup and restore partition table with global index successful.
```
> 
Side effects
Documentation
```release-note
None
```
> br: fix br work with global index

- pkg/util/codec/codec_test.go
- pkg/util/codec/float.go
- tests/integrationtest/r/expression/issues.result
- tests/integrationtest/t/expression/issues.test
This reverts commit 9b2656951dac60ea47074050ef51de3043043d56.
Issue Number: ref https://github.com/pingcap/tidb/issues/57500
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Revert "util: fix codec for negative zero (#57343)" | tidb-test=pr/2432

- pkg/disttask/framework/integrationtests/framework_pause_and_resume_test.go
- pkg/disttask/framework/integrationtests/framework_rollback_test.go
- pkg/disttask/framework/integrationtests/framework_scope_test.go
- pkg/disttask/framework/integrationtests/framework_test.go
- pkg/disttask/framework/scheduler/nodes.go
- pkg/disttask/framework/scheduler/scheduler.go
- pkg/disttask/framework/scheduler/scheduler_manager.go
- pkg/disttask/framework/scheduler/scheduler_manager_nokit_test.go
- pkg/disttask/framework/scheduler/scheduler_nokit_test.go
- pkg/disttask/framework/storage/history.go
- pkg/disttask/framework/storage/table_test.go
- tests/realtikvtest/addindextest2/BUILD.bazel
- tests/realtikvtest/addindextest2/global_sort_test.go
- tests/realtikvtest/importintotest/BUILD.bazel
- tests/realtikvtest/importintotest/import_into_test.go
- tests/realtikvtest/importintotest4/BUILD.bazel
- tests/realtikvtest/importintotest4/global_sort_test.go
- use `failpoint.InjectCall` to reduce code pollution
- abstract a `getTaskClone` method
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dxf: refactor failpoints in scheduler

- pkg/planner/core/plan_stats.go
- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/handle_hist.go
- pkg/statistics/handle/handletest/initstats/BUILD.bazel
- pkg/statistics/handle/handletest/initstats/load_stats_test.go
- pkg/statistics/handle/handletest/initstats/main_test.go
- pkg/statistics/handle/storage/read.go
Issue Number: close https://github.com/pingcap/tidb/issues/57544
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix sync load cannot load common column with concurrently init stats

- pkg/executor/infoschema_reader.go
- pkg/planner/core/casetest/instanceplancache/others_test.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_instance.go
- pkg/planner/core/plan_cache_lru.go
- pkg/planner/core/plan_cache_lru_test.go
- pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: hide read-write fields of PlanCacheValue for safety
planner: hide read-write fields of PlanCacheValue for safety
No logical change, just refactoring.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: hide read-write fields of PlanCacheValue for safety

- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add test about logicalProjection and logicalSelection hash64 and equals logic

- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/handletest/initstats/BUILD.bazel
- pkg/statistics/handle/handletest/initstats/load_stats_test.go
- pkg/statistics/handle/handletest/initstats/main_test.go
- tools/tazel/main.go
Issue Number: ref https://github.com/pingcap/tidb/issues/57544
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add more tests for init stats

- pkg/disttask/framework/integrationtests/framework_scope_test.go
introduced in #57566, as the `refreshNodesLoop` runs in another routine, it might run more than the time we expect and block
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dxf: fix flaky scope test

- pkg/ddl/backfilling.go
- pkg/ddl/ddl_test.go
- pkg/ddl/index.go
- pkg/ddl/job_worker.go
- pkg/ddl/job_worker_test.go
- pkg/ddl/reorg.go
- tests/realtikvtest/addindextest1/disttask_test.go
Issue Number: close #57325
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: check context done in isReorgRunnable function

- pkg/executor/importer/BUILD.bazel
- pkg/executor/importer/importer_testkit_test.go
Issue Number: close #57822
Problem Summary: See #57822
Use SQL interface to set global variable.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: stabilize TestGetTargetNodeCpuCnt

- pkg/planner/core/casetest/instanceplancache/concurrency_test.go
Issue Number: close #57514
Problem Summary: planner: fix flaky test TestInstancePlanCacheConcurrencySysbench
planner: fix flaky test TestInstancePlanCacheConcurrencySysbench
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix flaky test TestInstancePlanCacheConcurrencySysbench

- pkg/metrics/grafana/tidb.json
Issue Number: close #57835 
Remove the filled colors in Grafana script.
Tests 
2. deploy this patch
3. check the grafana
> 
Side effects
Documentation
```release-note
None
```
> metrics: remove the filled colors

- pkg/planner/core/find_best_task.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix wrong comment

- pkg/ddl/ddl_api.go
- pkg/ddl/partition.go
- pkg/ddl/tests/partition/BUILD.bazel
- pkg/ddl/tests/partition/db_partition_test.go
Issue Number: close #55721
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: Added check for Global Index

- pkg/executor/reload_expr_pushdown_blacklist.go
- pkg/expression/builtin.go
- pkg/expression/builtin_time.go
- pkg/expression/integration_test/integration_test.go
- pkg/parser/ast/functions.go
- tests/integrationtest/r/executor/show.result
Issue Number: ref https://github.com/pingcap/tidb/issues/57815
- Simple implementation of Oracle function ‘to_date’.
Tests 
> 
```
mysql> select to_date('2024-11-23','yyyy-mm-dd');
+------------------------------------+
| to_date('2024-11-23','yyyy-mm-dd') |
+------------------------------------+
| 2024-11-23 00:00:00                |
+------------------------------------+
mysql> select to_date('2024-11-23','YYyY-Mm-Dd');
+------------------------------------+
| to_date('2024-11-23','YYyY-Mm-Dd') |
+------------------------------------+
| 2024-11-23 00:00:00                |
+------------------------------------+
mysql> select to_date('20241123','yyyymmdd');
+--------------------------------+
| …
```
> oracle-function: implement the function `to_date`

- WORKSPACE
- build/image/base
- build/image/parser_test
- go.mod
Issue Number: close https://github.com/pingcap/tidb/issues/57965
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update go 1.23.4

- pkg/executor/test/issuetest/executor_issue_test.go
Issue Number: close #57970
Introduced by #56607
Sort and compare results to make test stable.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix flaky test TestUnionIssue

- pkg/executor/reload_expr_pushdown_blacklist.go
- pkg/expression/builtin.go
- pkg/expression/builtin_string.go
- pkg/expression/builtin_string_test.go
- pkg/expression/integration_test/BUILD.bazel
- pkg/expression/integration_test/integration_test.go
- pkg/parser/ast/functions.go
- tests/integrationtest/r/executor/show.result
Issue Number: ref https://github.com/pingcap/tidb/issues/57815
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pingkai: add to_num function

- br/pkg/storage/BUILD.bazel
- br/pkg/storage/gcs.go
Issue Number: close https://github.com/pingcap/tidb/issues/56127
Manual cherry-pick of pingcap#50447 and pingcap#57924 to avoid cherry-picking all the commits along the way.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Dumpling: GCS client always retry and also retry for 401 error.

- pkg/planner/core/casetest/cascades/memo_test.go
- pkg/planner/core/casetest/cascades/testdata/cascades_suite_in.json
- pkg/planner/core/casetest/cascades/testdata/cascades_suite_out.json
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add test about memo derive stats.

- br/pkg/task/stream.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/wait.go
- br/tests/br_pitr_long_running_schema_loading/run.sh
- br/tests/run_group.sh
- pkg/domain/domain.go
- pkg/domain/schema_validator.go
close pingcap/tidb#57743
(cherry picked from commit 8fe061897e804a3127974d96faa6a0d57ce4cb1b)
Tests 
> 
Side effects
Documentation
```release-note
None
```
> cherry-pick-7.5: br: fix insert gc failed due to slow schema reload (#57742)

- br/pkg/task/stream.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/wait.go
- br/tests/br_pitr_long_running_schema_loading/run.sh
- br/tests/run_group_br_tests.sh
- pkg/domain/domain.go
- pkg/domain/schema_validator.go
close pingcap/tidb#57743
(cherry picked from commit 8fe061897e804a3127974d96faa6a0d57ce4cb1b)
Tests 
> 
Side effects
Documentation
```release-note
None
```
> cherry-pick-8.1: br: fix insert gc failed due to slow schema reload (#57742)

- pkg/planner/core/collect_column_stats_usage.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix ExtractColumnsAndCorColumnsFromExpressions caller didn't update its may-expanded cache slice.

- pkg/session/session.go
Issue Number: close #58072
Add BRIE statements to CRUCIAL OPERATION logs.
Tests 
2. run backup/restore statements
3. check tidb logs
```text
[2024/12/09 14:04:33.852 +08:00] [INFO] [session.go:4105] ["CRUCIAL OPERATION"] [conn=3584032770] [schemaVersion=106] ["secure text"="BACKUP DATABASE `test_new` TO 'local:///tmp/backup/2024/13/'"] [user=root@%]
[2024/12/09 14:04:43.802 +08:00] [INFO] [session.go:4111] ["CRUCIAL OPERATION"] [conn=3584032770] [schemaVersion=109] [cur_db=] [sql="drop database test_new"] [user=root@%]
[2024/12/09 14:04:48.305 +08:00] [INFO] [session.go:4105] ["CRUCIAL OPERATION"] [conn=3584032770] [schemaVersion=109] ["secure text"="RESTORE DATABASE `test_new` FROM 'local:///tmp/backup/2024/13/'"] [user=root@%]
```
> - [ ] I checked …
> session: add BRIE to CRUCIAL OPERATION logs

- .bazelrc
Issue Number: close https://github.com/pingcap/tidb/issues/58278
Tests 
> 
Side effects
Documentation
```release-note
None
```
> bazel: remove jdk17 to support bazel7

- pkg/expression/scalar_function.go
- pkg/types/datum.go
- pkg/types/datum_test.go
- pkg/util/ranger/types.go
Problem Summary: tiny optimize by avoid sprintf
before:
This PR:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: tiny optimize by avoid sprintf

- pkg/infoschema/sieve.go
- pkg/infoschema/sieve_test.go
Reverts pingcap/tidb#58243
Issue Number: close https://github.com/pingcap/tidb/issues/58287
Found DATA RACE  in CI
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Revert "infoschema: change sieve Get() function Mutex to RWMutex"

- pkg/planner/core/casetest/vectorsearch/testdata/ann_index_suite_out.json
- pkg/planner/core/casetest/vectorsearch/vector_index_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/57871
Reduce the number of rows that we inserted into this test case. Otherwise the `analyze` may read the snapshot value.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: stabilize the vector index test

- pkg/executor/recommend_index.go
- pkg/planner/core/planbuilder.go
- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/indexadvisor_test.go
Problem Summary: planner: output create-index statements for `recommend index run`
planner: output create-index statements for `recommend index run`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: output create-index statements for `recommend index run`

- lightning/pkg/importer/import.go
Issue Number: close #58141
Tests 
test on a 8c node, import 100 DBs of which each have 100 tables with default config
> 
Side effects
Documentation
```release-note
None
```
> lightning: calculate concurrency of schema import from region-concurrency

- br/pkg/lightning/errormanager/errormanager.go
- br/pkg/lightning/errormanager/errormanager_test.go
Issue Number: close #58085
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: fix data error summary table format

- pkg/metrics/grafana/tidb_runtime.json
- pkg/metrics/metrics.go
Issue Number: ref #55390
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: don't use deprecated api

- pkg/expression/constant.go
- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/plan_cache.go
Issue Number: close #58318
Problem Summary: planner: fix possible read-write DATA RACE on Instance Plan Cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix possible read-write DATA RACE on Instance Plan Cache 

- pkg/executor/join/hash_join_spill_helper.go
- pkg/executor/join/hash_join_v2.go
Issue Number: close #58286
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix the data race in hash join tests

- pkg/executor/importer/import.go
- tests/realtikvtest/importintotest2/from_select_test.go
Issue Number: close #58417
- add table_checksum option for import from select
Tests 
> 
Side effects
Documentation
```release-note
None
```
> importer: add table_checksum option for import from select | tidb-test=2076e2fac85c636e0f3e0f287efc82465f62476a 

- pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json
- pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
- pkg/planner/core/casetest/join/BUILD.bazel
- pkg/planner/core/casetest/join/join_test.go
- pkg/planner/core/casetest/join/main_test.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/issuetest/planner_issue_test.go
- tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result
Issue Number: close #58325
Tests 
> 
Side effects
Documentation
```release-note
choose left side as build in semi and anti semi join
支持可以选择 left side，来构建 semi join 和 anti semi join
```
> planner: choose left side as build in semi and anti semi join

- pkg/planner/core/optimizer.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix optimize name for new cascades code branch

- DEPS.bzl
- cmd/tidb-server/BUILD.bazel
- cmd/tidb-server/main.go
- go.mod
- go.sum
Issue Number: close #52318
Tests 
```
export PYROSCOPE_SERVER_ADDRESS=< get from grafana cloud > 
export PYROSCOPE_BASIC_AUTH_USER=< get from grafana cloud > 
export PYROSCOPE_BASIC_AUTH_PASSWORD=< get from grafana cloud > 
bin/tidb-server --config "conf/tidb.toml" -P 4000 --store tikv --path 127.0.0.1:2379 --host 0.0.0.0 --advertise-address 0.0.0.0 -
```
> 
Side effects
Documentation
```release-note
support pyroscope
支持 pyroscope
```
> *: support pyroscope

- .bazelrc
- WORKSPACE
Tests 
> 
Side effects
Documentation
```release-note
None
```
> bazel: upgrade rules_go 0.51.0

- WORKSPACE
- pkg/ddl/partition.go
Issue Number: close https://github.com/pingcap/tidb/issues/58602
Tests 
Side effects
Documentation
```release-note
None
```
> partition: remove duplicate GetRegionByID

- pkg/domain/domain.go
Issue Number: close #58616
Problem Summary: planner: fix DATA RACE on global binding
planner: fix DATA RACE on global binding
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix DATA RACE on global binding

- pkg/planner/cascades/memo/BUILD.bazel
- pkg/planner/cascades/memo/group.go
- pkg/planner/cascades/memo/group_and_expr_test.go
- pkg/planner/cascades/memo/group_expr.go
- pkg/planner/cascades/memo/memo.go
- pkg/planner/cascades/memo/memo_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add memo group merge logic.

- pkg/planner/core/exhaust_physical_plans.go
Issue Number: ref https://github.com/pingcap/tidb/issues/53127
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: support left outer anti semi join for hash join v2

- pkg/expression/builtin_math.go
- pkg/expression/integration_test/integration_test.go
Issue Number: close #57608
Tests 
> 
Side effects
Documentation
```release-note
Fix issue that the incorrect short path in `truncate` function leads to wrong result
```
> expression: fix incorrect short path in `truncate` function

- pkg/metrics/grafana/tidb.json
Issue Number: ref #54436 
introduced in https://github.com/pingcap/tidb/pull/58360
Tests 
before, the legend part has duplicate rows
after
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix 'Execute Duration' panel of DDL not aggregated by instance

- executor/cluster_table_test.go
- executor/slow_query.go
- executor/slow_query_test.go
- infoschema/cluster_tables_test.go
- planner/core/memtable_predicate_extractor.go
- tools/check/check-bazel-prepare.sh
This is an hotfix of #56356
Issue Number: close #56100
Problem Summary: fix issue that query slow_query table return wrong result
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix issue that query slow_query table return wrong result (#56356) | tidb-test=c1ec4c1217f86e83e4c07da09ef909e3af84ee7e

- pkg/statistics/column.go
- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/globalstats/global_stats.go
- pkg/statistics/handle/storage/dump_test.go
- pkg/statistics/handle/storage/read.go
- pkg/statistics/handle/storage/save.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/syncload/stats_syncload.go
- pkg/statistics/handle/types/interfaces.go
- pkg/statistics/histogram.go
- pkg/statistics/index.go
This file will never be read. So I think we can safely remove it to save some memory.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: remove unused Flag field from Column and Index structs

- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
Issue Number: close #58843
Tests 
1. add sleep to owner.Watch to avoid owner retire and build a special 8.1.0 tidb-server
2. tiup playground with the special 8.1.0
3. add some sleep to job scheduler to avoid 8.5.0 schedule job after force owner, build a special 8.5.0 binary with this pr
4. start the special 8.5.0 to upgrade
5. upgrade success
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix args count for modify column

- pkg/sessionctx/variable/sysvar.go
Issue Number: close #58873
CSE mode doesn't support fair locking now.
If keyspace is set, don't set `tidb_pessimistic_txn_fair_locking`.
Tests 
> 
- Check with MySQL client:
```sql
mysql> select @@global.tidb_pessimistic_txn_fair_locking;
+--------------------------------------------+
| @@global.tidb_pessimistic_txn_fair_locking |
+--------------------------------------------+
|                                          0 |
+--------------------------------------------+
1 row in set (0.00 sec)
mysql> set global tidb_pessimistic_txn_fair_locking=1;
Query OK, 0 rows affected, 1 warning (0.01 sec)
mysql> show warnings;
+---------+------+--------------------------------------------------------------------------+
| Level …
```
> variable: disable fair locking when cse mode is enabled

- pkg/planner/cascades/BUILD.bazel
- pkg/planner/cascades/base/cascadesctx/cascades_ctx.go
- pkg/planner/cascades/cascades.go
- pkg/planner/cascades/cascades_test.go
- pkg/planner/cascades/memo/memo.go
- pkg/planner/cascades/task/base.go
- pkg/planner/cascades/task/task_apply_rule.go
- pkg/planner/cascades/task/task_opt_group.go
- pkg/planner/cascades/task/task_opt_group_expression.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/optimizer.go
- tests/integrationtest/r/planner/cascades/integration.result
- tests/integrationtest/t/planner/cascades/integration.test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add cascades wrapper for integrating cascades into current logical optimization phase.

- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
Issue Number: close #58863
Tests 
- add sleep to owner.Watch to avoid owner retire and build a special 8.1.0 tidb-server
- tiup playground with the special 8.1.0
- add some sleep to job scheduler to avoid 8.5.0 schedule job after force owner, build a special 8.5.0 binary with this pr
- start the special 8.5.0, connect to it, and run 
```sql
create table t(a int, b int, c int, d int, index(a), index(b), index(c));
alter table t drop column a;
```
- from the log of special 8.1.0, we can see the range is deleted, while without this PR, it's not
```log
[2025/01/13 14:52:08.172 +08:00] [INFO] [delete_range.go:422] ["insert into delete-range indices"] [category=ddl] [jobID=136] [tableID=104] [indexIDs="[3]"] [comment="drop column: table ID"]
```
> - [ ] I checked and no code …
> ddl: fix drop column args count for v1

- DEPS.bzl
- go.mod
- go.sum
- pkg/ddl/column_change_test.go
- pkg/ddl/column_test.go
- pkg/ddl/db_integration_test.go
- pkg/ddl/index_change_test.go
- pkg/ddl/job_worker_test.go
- pkg/executor/set.go
- pkg/executor/test/executor/executor_test.go
- pkg/executor/test/writetest/BUILD.bazel
- pkg/executor/test/writetest/write_test.go
- pkg/planner/core/planbuilder.go
- pkg/sessionctx/context.go
- pkg/sessiontxn/staleread/processor.go
- pkg/sessiontxn/staleread/util.go
- pkg/store/copr/BUILD.bazel
- pkg/store/copr/batch_coprocessor.go
- pkg/store/copr/batch_request_sender.go
- pkg/store/copr/mpp.go
- pkg/util/mock/BUILD.bazel
- pkg/util/mock/context.go
- pkg/util/mock/fortest.go
Issue Number: ref #57786 
Cherry pick #58054
Tests 
> 
Side effects
Documentation
```release-note
Strengthen timestamp validation checks.
```
> *: Update client-go and verify all read ts

- br/pkg/backup/client.go
Issue Number: close #58666
the backup error from TiKV is thrown.
log warning about the error.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: output backup error from TiKV

- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/logical_operator_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add logical operator clone test

- pkg/disttask/example/BUILD.bazel
- pkg/disttask/example/app_test.go
- pkg/disttask/example/doc.go
- pkg/disttask/example/proto.go
- pkg/disttask/example/scheduler.go
- pkg/disttask/example/task_executor.go
- pkg/disttask/framework/scheduler/interface.go
- add an example application to help other teams which want to integrate their tasks to DXF
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dxf: add an example application

- WORKSPACE
Tests 
> 
Side effects
Documentation
```release-note
None
```
> bazel: upgrade rules_go 0.52.0

- WORKSPACE
- build/image/base
- build/image/parser_test
- dumpling/README.md
- go.mod
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go 1.23.5 

- pkg/resourcegroup/runaway/BUILD.bazel
- pkg/resourcegroup/runaway/checker.go
- pkg/resourcegroup/runaway/checker_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/57875
Tests 
> 
```release-note
None
```
> runaway: fix race problem when using multiple coprocessor workers

- DEPS.bzl
- go.mod
- go.sum
- pkg/executor/stale_txn_test.go
- pkg/metrics/grafana/performance_overview.json
- pkg/session/test/session_test.go
- pkg/session/txn.go
- pkg/store/mockstore/unistore/rpc.go
Issue Number: ref #54047
Problem Summary: there are several optimizations in client-go needed to pick.
bump client-go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: bump client-go to adopt some optimizations

- pkg/disttask/framework/scheduler/scheduler.go
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dxf: add comment to explain current schedule strategy

- pkg/planner/core/physical_plans.go
Issue Number: ref #34669
Tests 
run the ```go build -gcflags="-d=ssa/check_bce" ./pkg/planner/core/...```
before
```
pkg/planner/core/physical_plans.go:1001:31: Found IsInBounds
```
after 
```
None
```
> 
Side effects
Documentation
```release-note
None
```
> planner: Bound Check Elimination in the PhysicalTableScan.Clone

- util/expensivequery/expensivequerey_test.go
- util/expensivequery/memory_usage_alarm.go
cherry pick #58946 to release-6.1-20231229-v6.1.7 branch
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: cherry pick #58946 to release-6.1-20231229-v6.1.7 branch

- pkg/parser/ast/misc.go
- pkg/parser/ast/misc_test.go
Issue Number: close #59128 
redact passwords and secrets for traffic statements
- redact URL secrets for `TRAFFIC CAPTURE`
- redact passwords and secrets for `TRAFFIC REPLAY`
Tests 
> 
1. Run in MySQL client:
```
traffic replay from 's3://bucket/prefix?access-key=abcdefghi&secret-access-key=123&force-path-style=true' user='root' password='123456'
```
2. Check general log: 
```
[2025/01/22 19:30:15.233 +08:00] [INFO] [session.go:4158] [GENERAL_LOG] [conn=2097154] [session_alias=] [user=root@127.0.0.1] [schemaVersion=54] [txnStartTS=0] [forUpdateTS=0] [isReadConsistency=false] [currentDB=test] [isPessimistic=false] [sessionTxnMode=PESSIMISTIC] [sql="TRAFFIC REPLAY FROM …
```
> parser: redact passwords and secrets for traffic statements

- pkg/sessionctx/variable/sysvar.go
Issue Number: close #58874
This is used to test CSE mode. Fair locking is disabled all the time.
Remove the condition of keyspace.
Tests 
> 
This is only for `dedicated` branch, which is used for testing.
Side effects
Documentation
```release-note
None
```
> variable: disable fair locking all the time

- pkg/planner/cascades/rule/apply/decorrelate_apply/xf_decorrelate_apply.go
- pkg/planner/core/generator/shallow_ref/shallow_ref_generator.go
- pkg/planner/core/operator/baseimpl/plan.go
- pkg/planner/core/operator/logicalop/base_logical_plan.go
- pkg/planner/core/operator/logicalop/shallow_ref_generated.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: export the shallow ref function and fix some function name.

- pkg/planner/core/rule_partition_processor.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use slices.Compact to deduplicate

- pkg/planner/core/operator/logicalop/logical_join.go
Issue Number: ref #54401 
When debugging this function, I want to jump into ```ExtractOnCondition```, but have to navigate through other chained method calls like schema(), which really affects efficiency.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: make code more debug friendly

- WORKSPACE
- build/image/base
- build/image/parser_test
- dumpling/README.md
- go.mod
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go.1.23.6

- pkg/executor/BUILD.bazel
- pkg/executor/infoschema_reader_test.go
- pkg/infoschema/tables.go
Issue Number: close #59245
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: fix schema and data mismatch for TIDB_SERVERS_INFO

- pkg/executor/infoschema_reader_test.go
Issue Number: ref #59245
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Add test for columnames to TestForServersInfo

- pkg/planner/core/logical_plan_builder.go
Issue Number: close #59103 
remove unnecessary slicegrow.
Tests 
run BenchmarkExplainStringIndexScan
before
```
BenchmarkExplainStringIndexScan-8        25618       46114 ns/op
```
after 
```
BenchmarkExplainStringIndexScan-8        27816       42325 ns/op
```
> 
Side effects
Documentation
```release-note
None
```
> planner: remove slicegrow in the planner.core/unfoldWildStar

- OWNERS_ALIASES
Issue Number: close #59302 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> OWNERS: update planner owner

- DEPS.bzl
- go.mod
- go.sum
- pkg/store/mockstore/unistore/pd.go
Issue Number: ref #58780
Tests 
> 
```release-note
None
```
> *: bump pd client

- pkg/planner/cascades/old/BUILD.bazel
- pkg/planner/cascades/old/transformation_rules.go
- pkg/planner/core/rule/util/BUILD.bazel
- pkg/planner/core/rule/util/misc.go
- pkg/planner/core/rule_join_elimination.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner : refactor the usage of int set.

- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/types/interfaces.go
Issue Number: none
remove some dead codes
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: remove some dead codes

- pkg/statistics/handle/cache/stats_table_row_cache.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statstics: remove useless code

- lightning/pkg/server/lightning.go
- pkg/lightning/config/BUILD.bazel
- pkg/lightning/config/config.go
- pkg/lightning/config/config_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/59086
- redact external storage url
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: redact external storage url

- pkg/expression/expr_to_pb_test.go
- pkg/expression/infer_pushdown.go
Issue Number: close https://github.com/pingcap/tidb/issues/59057
Tests 
> 
Side effects
Documentation
```release-note
support str_to_date pushdown to tikv
```
> expr: support str_to_date pushdown to tikv

- .bazelrc
Issue Number: close #59373
Tests 
> 
```sh
bazel clean --expunge
rm -rf ~/.cache/bazel*
time make bazel_prepare
```
```
real	9m29.997s
user	0m3.171s
sys	0m0.880s
real	2m5.106s
user	0m3.145s
sys	0m0.788s
```
Side effects
Documentation
```release-note
None
```
> bazel: Added http_timeout_scaling quicker downloads, if cache is not accessible

- pkg/planner/funcdep/BUILD.bazel
- pkg/planner/funcdep/fd_graph.go
- pkg/planner/funcdep/fd_graph_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/59211
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add a util function of finding common equivs between mutli fds.

- pkg/planner/cascades/memo/BUILD.bazel
- pkg/planner/cascades/memo/group_expr.go
- pkg/planner/core/casetest/cascades/memo_test.go
- pkg/planner/core/casetest/cascades/testdata/cascades_suite_out.json
- pkg/planner/core/optimizer.go
- pkg/planner/property/BUILD.bazel
- pkg/planner/property/logical_property.go
- pkg/testkit/testdata/testdata.go
- tests/integrationtest/r/planner/cascades/integration.result
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: maintain functional dependency in the cascades group

- pkg/executor/adapter.go
- pkg/executor/metrics/metrics.go
- pkg/metrics/executor.go
- pkg/metrics/grafana/tidb.json
- pkg/metrics/metrics.go
Issue Number: ref #57543 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor,metrics: Add network transmission metrics

- br/pkg/membuf/BUILD.bazel
- br/pkg/membuf/buffer.go
- br/pkg/membuf/buffer_test.go
- pkg/disttask/framework/storage/task_table.go
- pkg/disttask/importinto/BUILD.bazel
- pkg/disttask/importinto/encode_and_sort_operator.go
- pkg/disttask/importinto/encode_and_sort_operator_test.go
- pkg/disttask/importinto/task_executor.go
Issue Number: close #59508
avoid alignment when the aligned size >= 1.1 * calculated-buf-size
Tests 
below test also merged this PR https://github.com/pingcap/tidb/pull/59516
import table with 500 indices, 25G, it OOM before, works after
```
[2025/02/13 06:55:30.434 +00:00] [INFO] [encode_and_sort_operator.go:170] ["adjust index buf block siz
e"] [type=ImportInto] [task-id=60001] [step=encode&sort] [before=16777216] [after=2134675]
```
before
after. as the buf is too small, we upload more frequently, so the cpu usage is low
after, but with different number of indices
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-not …
> import: fix oom on global sort when the target table has large number of indices

- pkg/disttask/framework/integrationtests/modify_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dxf: add integration test for modify param during subtask running

- DEPS.bzl
- go.mod
- go.sum
- tests/realtikvtest/txntest/BUILD.bazel
- tests/realtikvtest/txntest/txn_test.go
Do not set txn scope in snapshot to fix the problem.
Tests 
> 
Side effects
Documentation
```release-note
Fix TSO retrieval failure during read TS validation when `zone` label is set.
```
> *: (6.5) fix TSO retrieval failure during read TS validation

- pkg/planner/core/generator/shallow_ref/shallow_ref_generator.go
- pkg/planner/core/operator/logicalop/logical_projection.go
- pkg/planner/core/operator/logicalop/shallow_ref_generated.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: gen shallow ref usage of logical projection.

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/planbuilder.go
- pkg/util/stmtsummary/BUILD.bazel
- pkg/util/stmtsummary/statement_summary.go
- pkg/util/stmtsummary/statement_summary_test.go
- pkg/util/stmtsummary/v2/stmtsummary.go
Problem Summary: planner: refactor some code related to binding
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove some useless binding code

- pkg/statistics/analyze.go
Issue Number: close #59595
Tests 
> 
Side effects
Documentation
```release-note
None
```
> stats: Supplement some comments on analyze result struct

- pkg/disttask/framework/storage/table_test.go
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: disable some test | tidb-test=release-8.1.2

- pkg/lightning/common/retry.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: not retry on `Keys must be added in strict ascending order` | tidb-test=release-8.1.2

- DEPS.bzl
- go.mod
- go.sum
- tests/realtikvtest/txntest/BUILD.bazel
- tests/realtikvtest/txntest/txn_test.go
Do not set txn scope in snapshot to fix the problem.
Tests 
> 
Side effects
Documentation
```release-note
Fix TSO retrieval failure during read TS validation when `zone` label is set.
```
> *: (7.5) fix TSO retrieval failure during read TS validation

- pkg/bindinfo/binding.go
- pkg/bindinfo/binding_cache.go
- pkg/bindinfo/binding_cache_test.go
- pkg/bindinfo/global_handle_test.go
- pkg/bindinfo/session_handle_test.go
- pkg/planner/core/planbuilder.go
Problem Summary: planner: refactor some code related to binding
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor some code related to binding

- pkg/executor/join/join_table_meta.go
Refine `newTableMeta` to make it more readable, no logic changes, only code refine.
Tests 
> There is already [newTableMeta tests](https://github.com/pingcap/tidb/blob/9eabc90838aa03b4c28011727b39b34113785d2a/pkg/executor/join/join_table_meta_test.go)
Side effects
Documentation
```release-note
None
```
> executor: minor refine of `newTableMeta`

- br/pkg/storage/azblob.go
Issue Number: Ref #59339
When polling the asynchronous copy progress, if a small file was blocked by some reason, we may send request too frequently. 
This patch added a minimal polling period.
Tests 
The change is small enough and may be covered by other test cases.
> 
Side effects
Documentation
```release-note
None
```
> storage/azblob: Added Minimal Sleep Duration to Avoid Busy Requests

- pkg/disttask/framework/integrationtests/BUILD.bazel
- pkg/disttask/framework/integrationtests/framework_scope_test.go
- pkg/sessionctx/variable/sysvar.go
Issue Number: ref #58944
As described in #58944, we should validate the variable to prevent users setting it to zero.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> sysvar: add validation check for tidb_max_dist_task_nodes

- DEPS.bzl
- go.mod
- go.sum
- tests/realtikvtest/txntest/txn_test.go
Do not set txn scope in snapshot to fix the problem.
Tests 
> 
Side effects
Documentation
```release-note
Fix TSO retrieval failure during read TS validation when `zone` label is set.
```
> *: (8.5) fix TSO retrieval failure during read TS validation

- pkg/disttask/framework/scheduler/scheduler.go
- pkg/disttask/framework/storage/task_state.go
- pkg/disttask/importinto/job.go
- pkg/disttask/importinto/job_testkit_test.go
- pkg/executor/show.go
- tests/realtikvtest/importintotest/import_into_test.go
Tests 
same steps as in https://github.com/pingcap/tidb/pull/59599/, now we can use `cancel import job` to cancel it
here is the result of `show import job`
```sql
mysql> show import jobs;
+--------+----------------------------------------------------------------+--------------+----------+-----------+---------------------+------------------+---------------+-----------------------------------------------------+----------------------------+----------------------------+----------+------------+
| Job_ID | Data_Source                                                    | Target_Table | Table_ID | Phase     | Status              | Source_File_Size | Imported_Rows | Result_Message                                      | Create_Time                | …
```
> import: show/cancel import job integrate `awaiting-resolution` state | tidb-test=release-8.1.2

- build/nogo_config.json
- pkg/workloadlearning/handle.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> workloadlearning: enable linter

- pkg/bindinfo/BUILD.bazel
- pkg/bindinfo/global_handle.go
- pkg/bindinfo/global_handle_test.go
- pkg/session/bootstrap_test.go
Problem Summary: planner: refactor some code related to binding
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor some code related to binding 

- pkg/executor/internal/mpp/executor_with_retry.go
- pkg/executor/internal/mpp/local_mpp_coordinator.go
- pkg/executor/mpp_gather.go
- pkg/executor/mppcoordmanager/mpp_coordinator_manager.go
- pkg/executor/test/tiflashtest/BUILD.bazel
- pkg/executor/test/tiflashtest/tiflash_test.go
Issue Number: close #59703 
Described in issue.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Fix mpp coordinator leak issue

- pkg/ddl/index.go
Issue Number: close #59732
Send sync schema notification to TiFlash when it is a vector index.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix vector indexes do not been dropped on TiFlash side

- pkg/disttask/framework/storage/task_table.go
set it to double of the default, i.e. 2g
Tests 
simulate a step with 100 subtask, each with 5M meta, is report `Your query has been cancelled due to exceeding the allowed memory`, after it works
> 
Side effects
Documentation
```release-note
None
```
> dxf: increase memory quota for session of generating subtasks | tidb-test=release-8.1.2

- pkg/lightning/backend/external/iter.go
- pkg/lightning/backend/external/split_test.go
Issue Number: close #59841
Tests 
> 
Side effects
Documentation
```release-note
None
```
> globalsort: sort the multiStat before merge

- Makefile
- br/pkg/task/common_test.go
- br/pkg/task/config_test.go
- br/pkg/task/encryption.go
- br/pkg/task/encryption_test.go
- br/pkg/task/restore_test.go
Issue Number: close #59925
fix `br/pkg/task` unit tests
fix `br/pkg/task` unit tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix unit test

- pkg/util/workloadrepo/BUILD.bazel
- pkg/util/workloadrepo/worker_test.go
Problem Summary: We have little test on the availability of multiple workers, let us add one.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> workloadrepo: enhanced availability test

- pkg/parser/go.mod
Issue Number: ref #59577
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: upgrade go1.23

- pkg/planner/core/casetest/parallelapply/parallel_apply_test.go
- pkg/planner/core/issuetest/planner_issue_test.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/planbuilder_test.go
Issue Number: close #59863 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: implement Clone for PhysicalIndexJoin

- pkg/planner/core/tests/analyze/BUILD.bazel
- pkg/planner/core/tests/analyze/analyze_test.go
…
Issue Number: close #60037
add test cases for auto analyze's tidb_skip_missing_partition_stats
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add test cases for auto analyze's tidb_skip_missing_partition_stats

- pkg/metrics/grafana/tidb_resource_control.json
- pkg/metrics/grafana/tidb_resource_control.jsonnet
Issue Number: Ref https://github.com/pingcap/tidb/issues/59389
Tests 
```release-note
None
```
> resource control: update grafana for burstable

- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/algorithm.go
- pkg/planner/indexadvisor/indexadvisor.go
- pkg/planner/indexadvisor/indexadvisor_sql_test.go
Problem Summary: planner: output an explanation though warning if index advisor returns an empty result
```
Warning 1105  Considered 3 indexable columns(test.t.a, test.t.b, test.t.c), 3 or more index candidates(test.t(a), test.t(b), test.t(c)), no sufficiently beneficial indexes were found.
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: output an explanation though warning if index advisor returns an empty result

- WORKSPACE
- pkg/lightning/common/BUILD.bazel
- pkg/util/cgroup/BUILD.bazel
- pkg/util/sys/linux/BUILD.bazel
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade rules_go 0.53

- pkg/domain/domain.go
- pkg/session/session.go
- pkg/statistics/handle/syncload/BUILD.bazel
- pkg/statistics/handle/syncload/stats_syncload.go
- pkg/statistics/handle/syncload/stats_syncload_test.go
- pkg/statistics/handle/types/interfaces.go
Issue Number: ref https://github.com/pingcap/tidb/issues/60011
We don't need these contexts any more. See https://github.com/pingcap/tidb/pull/60012#discussion_r1988699795
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: simplify LoadAndUpdateStatsLoop and SubLoadWorker parameters

- statistics/handle/handle.go
- statistics/handle/update_test.go
…essionVar
Issue Number: close #60037
Tests 
> 
Side effects
Documentation
```release-note
sync TiDBSkipMissingPartitionStats value in the auto analyze
auto analyze 中同步TiDBSkipMissingPartitionStats 的值
```
> statistics: sync TiDBSkipMissingPartitionStats value in the auto analyze

- pkg/parser/ast/dml.go
- pkg/parser/parser.y
- pkg/parser/parser_test.go
Issue Number: ref #60148
Problem Summary: planner: support the new syntax "show plan for <SQL>" for SPM
planner: support the new syntax "show plan for <SQL>" for SPM
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: support the new syntax "show plan for <SQL>" for SPM

- OWNERS_ALIASES
Issue Number: ref #46911
Only changes owner list according changes.
Tests 
> 
```release-note
None
```
> *: edit owner list to latest.

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/index_join_path.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: some code-clean about build index join

- DEPS.bzl
- go.mod
- go.sum
- pkg/planner/core/plan_to_pb.go
Issue Number: ref #59880 
https://github.com/pingcap/tipb/pull/355
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update tipb to support columnar index

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #60223 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix jwt-go allows excessive memory allocation during header parsing

- pkg/executor/select.go
- pkg/util/disk/tracker.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util, executor: fix a typo

- pkg/executor/grant.go
- tests/integrationtest/r/executor/grant.result
- tests/integrationtest/t/executor/grant.test
Issue Number: close #29266
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor/grant: fix grant local temporary table success

- pkg/parser/yy_parser.go
- pkg/planner/core/plan_cache_param.go
- pkg/session/session.go
- pkg/session/test/BUILD.bazel
- pkg/session/test/session_test.go
- pkg/util/generatedexpr/BUILD.bazel
- pkg/util/generatedexpr/generated_expr.go
- pkg/util/parser/parser.go
Issue Number: close #60266
reset parser before putting into parser pool 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util: reset parser before putting into parser pool

- statistics/handle/handle.go
- statistics/handle/update_test.go
Issue Number: close #60037
Tests 
> 
Side effects
Documentation
```release-note
sync TiDBSkipMissingPartitionStats value in the auto analyze
auto analyze 中同步TiDBSkipMissingPartitionStats 的值
```
> statistics: sync TiDBSkipMissingPartitionStats value in the auto analyze | tidb-test=920d9bf1b1137cda1272bdd59ae527aee8067944

- pkg/sessionctx/vardef/tidb_vars.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
Issue Number: close https://github.com/pingcap/tidb/issues/36598
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: revert and fix "remove the useless variable tidb_enable_point_get_cache from #36844".

- pkg/statistics/handle/ddl/ddl.go
Issue Number: ref https://github.com/pingcap/tidb/issues/60194, ref https://github.com/pingcap/tidb/issues/59474
Recently, we discovered an issue with DDL event handling. I believe we need to conduct more tests to identify potential bugs, especially since we haven’t resolved [this issue](https://github.com/pingcap/tidb/issues/59474) yet. It would be better to ignore the errors and ensure that the DDL notifier table can be cleaned up; otherwise, we might end up retrying it indefinitely.
Tests 
> 
Side effects
Documentation
```release-note
None …
```
> statistics: log DDL event handling errors and ignore them temporarily

- pkg/executor/show.go
- pkg/parser/mysql/privs.go
- pkg/planner/core/logical_plans_test.go
- pkg/planner/core/planbuilder.go
- pkg/privilege/privileges/cache.go
- pkg/privilege/privileges/privileges_test.go
- tests/integrationtest/r/privilege/privileges.result
- tests/integrationtest/t/privilege/privileges.test
Issue Number: close #29280, close #29281
Tests 
> 
Side effects
Documentation
```release-note
None
```
> privilege: fix `create temporary tables` privileges related bugs

- DEPS.bzl
- go.mod
- go.sum
- pkg/planner/core/find_best_task.go
- pkg/util/execdetails/execdetails.go
- pkg/util/execdetails/execdetails_test.go
Issue Number: close #59880
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update tipb to support more table scan statistics

- pkg/privilege/privileges/privileges_test.go
Issue Number: close #29286
Problem Summary: The problems is fixed by #60313.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> privilege: uncomments two test cases

- WORKSPACE
- build/image/base
- build/image/parser_test
- dumpling/README.md
- go.mod
Issue Number: close #60360
go1.23.8 (released 2025-04-01) includes security fixes to the net/http package, as well as bug fixes to the runtime and the go command. See the [Go 1.23.8 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.8+label%3ACherryPickApproved) on our issue tracker for details.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go 1.23.8

- br/tests/lightning_max_random/run.sh
Issue Number: close #59969
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightening: fix lightening int test 

- br/tests/br_test_utils.sh
Issue Number: close #59969
Remove go leak in test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: remove go leak in test

- pkg/config/config.go
Issue Number: close #60387
When the TiDB-dashboard and the client are deployed on the same host, it's hard to set proxy-protocol.network. Making fallbackable true as default won't break compatibility.
Set the default value of `proxy-protocol.fallbackable` to true
Tests 
> 
```shell
tiup playground v8.5.1 --tiflash=0 --db.binpath=bin/tidb-server
mysql -h127.1 -uroot -P4000 test
mysql> select * from information_schema.cluster_config where `key` like '%fallbackable%';
+------+----------------+-----------------------------+-------+
| TYPE | INSTANCE       | KEY                         | VALUE |
+------+----------------+-----------------------------+-------+
| tidb | 127.0.0.1:4000 | proxy-protocol.fallbackable | true  | …
```
> config: set `proxy-protocol.fallbackable` to true

- pkg/planner/core/casetest/tpch/BUILD.bazel
- pkg/planner/core/casetest/tpch/testdata/tpch_suite_in.json
- pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json
- pkg/planner/core/casetest/tpch/tpch_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add Q18 MPP test for tpch

- build/nogo_config.json
- pkg/planner/core/base/plan_base.go
- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/funcdep/fd_graph.go
Issue Number: ref #60323 
There have been several new features that simplifies go code in later versions (go 1.24), like:
- `range` over a number
- `min`/`max` generics
- `slices.Contains()`
- `slices.Concat()`
- `slices.Clone()`
- `fmt.Appedf()`
- `maps.Copy()`
...
it can all be fixed by running:
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: modernize some package

- pkg/lightning/mydump/csv_parser.go
- pkg/lightning/mydump/csv_parser_test.go
- tests/realtikvtest/importintotest3/base64_encode_test.go
Issue Number: ref #44893
the rule is updated in here https://github.com/pingcap/tidb/issues/44893#issuecomment-2649876645
Tests 
> 
Side effects
Documentation
```release-note
None
```
> csv-parser: take empty string as NULL when base64 encoded | tidb-test=release-8.1.2

- pkg/lightning/backend/external/onefile_writer.go
Issue Number: close #60410
Tests 
change the code to mock a error, debug and see it's correct handled, and right error is logged
> 
Side effects
Documentation
```release-note
None
```
> globalsort: fix wrong err is returned and fix log

- pkg/ddl/cancel_test.go
- pkg/ddl/create_table.go
- pkg/ddl/db_change_test.go
- pkg/ddl/executor.go
- pkg/ddl/index.go
- pkg/ddl/index_modify_test.go
- pkg/ddl/modify_column.go
- pkg/ddl/tests/adminpause/ddl_stmt_cases.go
- pkg/executor/show.go
- pkg/meta/model/index.go
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
- pkg/meta/model/job_test.go
- pkg/parser/ast/ddl.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/indexmerge_path_test.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_to_pb.go
- pkg/types/etc.go
Issue Number: close #59880
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: support columnar inverted index

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/index_join_path.go
- pkg/planner/property/physical_property.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add datasource inner task build by feeling and building for index join prop.

- pkg/planner/core/plan_cost_ver2_test.go
Issue Number: ref #60357
Add testcases for recent optimizer cost factors.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add optimizer cost factor tests

- br/pkg/restore/internal/prealloc_db/db.go
- br/pkg/restore/internal/prealloc_db/db_test.go
- br/pkg/restore/internal/prealloc_table_id/BUILD.bazel
- br/pkg/restore/internal/prealloc_table_id/alloc.go
- br/pkg/restore/internal/prealloc_table_id/alloc_test.go
- br/pkg/restore/snap_client/export_test.go
- pkg/executor/brie.go
- pkg/executor/brie_utils.go
Issue Number: close #60345
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: Pre-alloc all table ids for restore

- pkg/planner/core/planbuilder.go
- tests/integrationtest/r/privilege/privileges.result
- tests/integrationtest/t/privilege/privileges.test
Issue Number: close #60469
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: check drop privilege for `CREATE OR REPLACE VEIW` stmt | tidb-test=pr/2506

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/access_object.go
- pkg/planner/core/casetest/vectorsearch/vector_index_test.go
- pkg/planner/core/columnar_index_utils.go
- pkg/planner/core/explain.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_cost_ver2.go
- pkg/planner/core/plan_to_pb.go
Issue Number: ref #59880
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: generalize vector index to columnar index

- pkg/planner/core/logical_plan_builder.go
- tests/integrationtest/r/privilege/privileges.result
- tests/integrationtest/t/privilege/privileges.test
Issue Number: close #60468
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix privileges for `select for update` stmt

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #60518
Update pd client dependency to https://github.com/tikv/pd/tree/20250411-6.5.10-ONCALL-7716 to fix https://github.com/tikv/pd/issues/7997
Tests 
> 
```release-note
None
```
> *: call scheduleUpdateConnectionCtxs after leader switch | tidb-test=e1d0c1e615f749e7139f5be95bc4a2b8cedb7380

- pkg/executor/join/hash_join_base.go
- pkg/executor/join/hash_join_v2.go
Issue Number: ref #60466
#60467 try to fix #60466 so it will not scan the row table if build side meet error. However, this fix is not clean because in TiDB, build side and probe side start at the same time, if probe side meet error when reading data from it's children executor before build is finished, the build stage is also stopped, at this time, the `canSkipScanRowTable` is not set, so TiDB will try to scan row table and meet panic again.
This pr makes sure only build sucess, TiDB will scan the row table if needed. In theory, TiDB only need to scan row table if and only if both build and probe sucess, but due to current implementation, it is not easy to be aware that probe is sucess or not, so this pr does not check probe results.
Tests 
> - [ ] I checked and no code …
> executor: avoid scan row table if build is not finished in hash join v2

- pkg/domain/domain.go
- pkg/statistics/handle/bootstrap.go
Issue Number: ref https://github.com/pingcap/tidb/issues/59939
Improve logs for init stats submodule.
1. Fixed all grammar issues.
2. Use the stats logger.
3. Add the duration logs for each subprocess.
Tests 
- lite mode: https://github.com/pingcap/tidb/pull/60521#issuecomment-2808477367
- non-lite mode: https://github.com/pingcap/tidb/pull/60521#issuecomment-2808492658
> 
Side effects
Documentation
```release-note
None
```
> statistics: improve logging messages and add duration metrics for stats initialization

- pkg/lightning/backend/external/file.go
- pkg/lightning/backend/external/file_test.go
- pkg/lightning/backend/external/iter_test.go
- pkg/lightning/backend/external/kv_reader.go
- pkg/lightning/backend/external/onefile_writer.go
- pkg/lightning/backend/external/split_test.go
- pkg/lightning/backend/external/util.go
- pkg/lightning/backend/external/util_test.go
- pkg/lightning/backend/external/writer.go
Issue Number: ref #60621
- add util functions to remove duplicates, they will be used in later PRs
- some refactor to KeyValueStore and rangePropertiesCollector
Tests 
> 
Side effects
Documentation
```release-note
None
```
> globalsort: add util functions to remove duplicates and some refactor

- Makefile.common
- pkg/config/store.go
- pkg/lightning/backend/local/job_worker.go
- pkg/lightning/backend/local/job_worker_test.go
- pkg/lightning/backend/local/local.go
- pkg/util/printer/printer.go
after discuss with PM, some naming related to next-gen need to be changed
Tests 
```shell
➜  tidb git:(refine-text) NEXT_GEN=1 make server
➜  tidb git:(refine-text) bin/tidb-server -V
Release Version: v9.0.0-alpha-511-g50e1e544b5
Edition: Community
Git Commit Hash: 50e1e544b5e5afc7cb2616b5ac6a080abf834ba3
Git Branch: refine-text
UTC Build Time: 2025-04-17 10:09:49
GoVersion: go1.23.8
Data Storage: Object Storage              <------- the change
➜  tidb git:(refine-text) make server
➜  tidb git:(refine-text) bin/tidb-server -V
Release Version: v9.0.0-alpha-511-g50e1e544b5
Edition: Community
Git Commit Hash: 50e1e544b5e5afc7cb2616b5ac6a080abf834ba3
Git Branch: refine-text
UTC Build …
```
> *: refine text and naming related to next-gen | tidb-test=ccf9f5de6817ed2e54c18f2c1757056d2c8b4e4c

- pkg/disttask/importinto/clean_s3.go
- pkg/disttask/importinto/planner.go
- pkg/disttask/importinto/task_executor.go
- pkg/executor/import_into.go
- pkg/executor/importer/import.go
- pkg/executor/importer/importer_testkit_test.go
- pkg/executor/importer/table_import.go
- pkg/executor/load_data.go
Issue Number: close https://github.com/pingcap/tidb/issues/60352
Tests 
> 
Side effects
Documentation
```release-note
None
```
> IMPORTINTO: close store inside LoadDataController

- errors.toml
- pkg/planner/core/planbuilder.go
- pkg/util/dbterror/plannererrors/planner_terror.go
Issue Number: close #60669 
Tests 
> 
Side effects
Documentation
```release-note
DROP PROCEDURE now returns similar errors as MySQL
```
> planner: drop procedure

- br/pkg/task/backup.go
Issue Number: close https://github.com/pingcap/tidb/issues/60654
After https://github.com/pingcap/tidb/pull/54151 merged, we need to update the description of backup concurrency to make it more clear.
Only parameter description changed.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> backup: adjust parameter description

- pkg/parser/hintparser.go
- pkg/parser/hintparser.y
Issue Number: closes #59751
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: Fix build issues on 32-bit arm

- pkg/lightning/config/OWNERS
The changes in `pkg/lightning/config` folder must be approved by owner SIG: `sig-critical-approvers-tidb-lightning`
Issue Number: ref #41241
Tests 
> 
Side effects
Documentation
```release-note
None
```
> OWNERS: guard change for pkg/lightning/config

- build/linter/constructor/analyzer.go
- build/linter/printexpression/analyzer.go
Issue Number: close #60773
Tests 
> - [x] no logic changed, existing tests should be enough.
Side effects
Documentation
```release-note
None
```
> build: gopls modernize

- build/nogo_config.json
- pkg/bindinfo/binding_cache.go
- pkg/bindinfo/session_handle_test.go
Issue Number: close #60782
Tests 
Side effects
Documentation
```release-note
None
```
> bindinfo: gopls modernize

- build/nogo_config.json
- pkg/parser/ast/dml.go
- pkg/parser/ast/expressions.go
- pkg/parser/ast/functions.go
- pkg/parser/ast/misc.go
- pkg/parser/auth/caching_sha2.go
- pkg/parser/auth/tidb_sm3.go
- pkg/parser/charset/charset.go
- pkg/parser/charset/encoding_ascii.go
- pkg/parser/charset/encoding_bin.go
- pkg/parser/format/format.go
- pkg/parser/goyacc/format_yacc.go
- pkg/parser/goyacc/main.go
- pkg/parser/lexer.go
- pkg/parser/misc.go
- pkg/parser/mysql/error.go
- pkg/parser/mysql/privs.go
- pkg/parser/parser_test.go
- pkg/parser/test_driver/test_driver.go
- pkg/parser/test_driver/test_driver_datum.go
- pkg/parser/test_driver/test_driver_mydecimal.go
- pkg/parser/yy_parser.go
Issue Number: close #60796
Tests 
Side effects
Documentation
```release-note
None
```
> Parser: gopls modernize

- Dockerfile
- Dockerfile.enterprise
Issue Number: close #60743 
update the latest base image 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dockerfile: upgrade base image version and address

- br/pkg/streamhelper/advancer.go
- br/pkg/streamhelper/flush_subscriber.go
- br/pkg/streamhelper/subscription_test.go
Issue Number: close #60559
code cleanup and fix log spamming when context cancelled and millions of region scanning returns same error.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix advancer log

- pkg/ddl/executor.go
- tests/integrationtest/r/ddl/partition.result
- tests/integrationtest/t/ddl/partition.test
Issue Number: close #60805
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl, partition: fix exchange partition between clustered table with nonclustered table

- pkg/ddl/partition.go
- tests/integrationtest/r/ddl/partition.result
- tests/integrationtest/t/ddl/partition.test
Issue Number: close #60838
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix create partition with binary type + empty string

- build/nogo_config.json
- pkg/owner/manager.go
- pkg/owner/manager_test.go
- pkg/owner/mock.go
Issue Number: close #60859
Tests 
Side effects
Documentation
```release-note
None
```
> owner: gopls modernize

- tests/globalkilltest/global_kill_test.go
- tests/graceshutdown/graceshutdown_test.go
- tests/llmtest/generator/generator.go
- tests/realtikvtest/addindextest/add_index_test.go
- tests/realtikvtest/addindextest1/disttask_test.go
- tests/realtikvtest/addindextest2/alter_job_test.go
- tests/realtikvtest/addindextest2/global_sort_test.go
- tests/realtikvtest/addindextest3/functional_test.go
- tests/realtikvtest/addindextest3/ingest_test.go
- tests/realtikvtest/addindextest3/operator_test.go
- tests/realtikvtest/brietest/brie_test.go
- tests/realtikvtest/flashbacktest/flashback_test.go
- tests/realtikvtest/importintotest/import_into_test.go
- tests/realtikvtest/importintotest2/from_select_test.go
- tests/realtikvtest/importintotest3/from_server_test.go
- tests/realtikvtest/importintotest4/global_sort_test.go
- tests/realtikvtest/importintotest4/split_file_test.go
- tests/realtikvtest/pipelineddmltest/pipelineddml_test.go
- tests/realtikvtest/sessiontest/infoschema_v2_test.go
- tests/realtikvtest/sessiontest/paging_test.go
- tests/realtikvtest/testutils/common.go
- tests/realtikvtest/testutils/compatibility.go
- tests/realtikvtest/testutils/workload.go
- tests/realtikvtest/txntest/stale_read_test.go
- tests/realtikvtest/txntest/txn_state_test.go
Issue Number: close #60763
Tests 
> No logic should be changed, existing tests should be enough.
Side effects
Documentation
```release-note
None
```
> tests: gopls modernize on the tests directory

- pkg/disttask/example/scheduler.go
- pkg/disttask/framework/handle/handle.go
- pkg/disttask/framework/integrationtests/bench_test.go
- pkg/disttask/framework/integrationtests/framework_ha_test.go
- pkg/disttask/framework/integrationtests/framework_scope_test.go
- pkg/disttask/framework/integrationtests/framework_test.go
- pkg/disttask/framework/integrationtests/modify_test.go
- pkg/disttask/framework/integrationtests/resource_control_test.go
- pkg/disttask/framework/proto/subtask_test.go
- pkg/disttask/framework/scheduler/scheduler_manager.go
- pkg/disttask/framework/scheduler/scheduler_test.go
- pkg/disttask/framework/scheduler/slots.go
- pkg/disttask/framework/scheduler/state_transform.go
- pkg/disttask/framework/storage/table_test.go
- pkg/disttask/framework/storage/task_state_test.go
- pkg/disttask/framework/storage/task_table_test.go
- pkg/disttask/framework/taskexecutor/slot.go
- pkg/disttask/framework/taskexecutor/task_executor_test.go
- pkg/disttask/framework/taskexecutor/task_executor_testkit_test.go
- pkg/disttask/framework/testutil/context.go
- pkg/disttask/framework/testutil/scheduler_util.go
- pkg/disttask/importinto/planner.go
- pkg/disttask/importinto/planner_test.go
Issue Number: close #60794
Tests 
Side effects
Documentation
```release-note
None
```
> disttask: gopls modernize

- pkg/ttl/ttlworker/job_manager_integration_test.go
- pkg/ttl/ttlworker/session_integration_test.go
Issue Number: close #60900
fix unstable tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: fix unstanle TTL test `TestGetSessionWithFault`/`TestWithSession`

- build/nogo_config.json
- pkg/autoid_service/autoid_test.go
Issue Number: close #60908
Tests 
Side effects
Documentation
```release-note
None
```
> autoid_service: gopls modernize + nogo config

- pkg/ingestor/OWNERS
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ingestor: add owner file

- pkg/executor/insert.go
- pkg/executor/insert_common.go
- pkg/executor/replace.go
- pkg/table/tables/index.go
- tests/realtikvtest/addindextest3/ingest_test.go
Issue Number: ref #60339
The assertion introduced by #60340 sometimes failed:
https://github.com/pingcap/tidb/blob/c0e3b546708847435adb8f21af2d6c74c9a70786/pkg/table/tables/index.go#L404
It happens when the same index key gets modified for a few times. For example:
```
row: {h1 -> a}
origin index: {a -> h1}
temp index: {a -> [h1d, h1]}
```
`insert(h1 -> a)` can trigger the "assertion failed" error even the row entry is duplicate.
For details, see the test case `TestAddIndexInsertSameOriginIndexValue`.
- Refactor `FetchDuplicatedHandle` to and cover the case `dupHandle.Equal(h)` in `index.create()`.
- I remained the assertion to see if there is any unexpected case in the future.
- Add a test case.
Tests 
> 
Side …
> executor: refactor uk checker function FetchDuplicatedHandle()

- pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_in.json
- pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_in.json
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add brief format show for planner mpp test case result.

- build/nogo_config.json
- pkg/meta/autoid/autoid_test.go
- pkg/meta/autoid/seq_autoid_test.go
- pkg/meta/meta.go
- pkg/meta/meta_test.go
- pkg/meta/model/job.go
- pkg/meta/model/job_args_test.go
- pkg/meta/model/table.go
- pkg/meta/model/table_test.go
Issue Number: close #60916
Tests 
Side effects
Documentation
```release-note
None
```
> meta: gopls modernize

- pkg/util/logutil/log.go
- pkg/util/logutil/log_test.go
- pkg/util/logutil/slow_query_logger.go
Issue Number: close #61007
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util: Fixed the issues when using the same log files for different log types

- pkg/ddl/tests/partition/multi_domain_test.go
Issue Number: close #60134
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: Fixed a race in test code

- WORKSPACE
- build/image/base
- build/image/parser_test
- dumpling/README.md
- go.mod
Issue Number: close #60997
https://groups.google.com/g/golang-announce/c/UZoIkUT367A/m/5WDxKizJAQAJ
go1.23.9 (released 2025-05-06) includes fixes to the runtime and the linker. See the [Go 1.23.9 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.9+label%3ACherryPickApproved) on our issue tracker for details.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.23.9

- pkg/executor/join/hash_join_v1.go
- tests/integrationtest/r/naaj.result
- tests/integrationtest/t/naaj.test
Issue Number: close https://github.com/pingcap/tidb/issues/60866
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix naaj will output more lines with there is a left condition and some rows aren't selected

- .gitignore
Issue Number: close #61053
Tests 
> - [ ] Only ignores compiled tests from git
Side effects
Documentation
```release-note
None
```
> *: Ignore *test.bin files

- br/pkg/version/version.go
- br/pkg/version/version_test.go
Issue Number: close #60990
the version checker actually is invalid, so need to remove it.
remove this check
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: remove version checker

- pkg/planner/core/casetest/partition/BUILD.bazel
- pkg/planner/core/casetest/partition/partition_pruner_test.go
- pkg/planner/core/point_get_plan.go
Issue Number: close #61134
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix PointGet working with list columns partition table with only one partition

- OWNERS
- OWNERS_ALIASES
Reverts pingcap/tidb#61158
Tests
> Revert "OWNERS: Auto Sync OWNERS files from community membership"

- OWNERS_ALIASES
- docs/design/2023-11-29-priority-queue-for-auto-analyze.md
- docs/design/2024-05-23-predicate-columns.md
- docs/design/2024-09-06-maintain-priority-queue-in-memory.md
- pkg/planner/core/planbuilder.go
- pkg/planner/core/planbuilder_test.go
ref https://github.com/pingcap/community/pull/808
Sorry, I’ve changed my ID again. Every time I attend a Rust conference, people keep asking about my name, so I figured it was time to update it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update owners aliases

- pkg/executor/infoschema_reader.go
- pkg/executor/infoschema_reader_test.go
Issue Number: close #60430
Problem Summary: See https://github.com/pingcap/tidb/issues/60430#issuecomment-2785416709
Filter non-public indexes for `I_S.statistics`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: filter non-public indexes for I_S.statistics

- pkg/ddl/ingest/integration_test.go
Issue Number: close #61291
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix unstable test `TestAddGlobalIndexInIngestWithUpdate`

- pkg/planner/core/physical_plan_trace_test.go
Use defined constants instead of hand-written ones.
And fix the used rules. Our rule is starting with `1<<0` instead of `1<<1`. The original tests refer to the wrong rules.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix TestPhysicalOptimizerTrace

- pkg/executor/analyze_idx.go
- pkg/statistics/builder.go
- pkg/statistics/cmsketch.go
- pkg/statistics/cmsketch_test.go
Issue Number: close #61339
The issue is as shown in this flame graph.
You can see that calculating the total for topn takes a lot of time, because it needs to traverse topn each time to compute the total count. This is very time-consuming. Moreover, the result of each calculation is the same, so you can cache this result to avoid performance issues.
create an cache for ```totalCount``` and ```minCount``` in the ```TopN```. Use ```sync.Once``` to avoid the situation where a large number of tasks concurrently perform the same calculation during the first computation.
Tests 
Sorry, I cannot public this benchmark code. because it contains the customer information.
before:
```
BenchmarkABC-8   	     206	   6164857 ns/op
```
after:
```
BenchmarkABC-8   	     362	   3142310 …
```
> statistics: the totalCount/minCount of TopN is calculated only once

- pkg/planner/core/task.go
- pkg/planner/core/task_base.go
Issue Number: close https://github.com/pingcap/tidb/issues/61355
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: correct the copTask's plan should not contain hash join operator when encapsulating task.

- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_txn_executor.go
- pkg/ddl/column.go
- pkg/ddl/index.go
- pkg/ddl/ingest/config.go
- pkg/ddl/job_worker.go
- pkg/ddl/partition.go
Issue Number: ref #61344
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: remove deadcode

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/fragment.go
- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_schema_producer.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/pb_to_plan.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache_rebuild.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_cost_ver2.go
- pkg/planner/core/plan_to_pb.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/resolve_indices.go
- pkg/planner/core/rule_inject_extra_projection.go
- pkg/planner/core/runtime_filter_generator.go
- pkg/planner/core/task.go
- pkg/planner/core/task_base.go
- pkg/planner/core/util.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move physical schema producer to physical op pkg.

- pkg/parser/ast/util.go
- pkg/parser/ast/util_test.go
Issue Number: close #31175
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: fix IsReadOnly function with trace stmt

- pkg/planner/core/rule_predicate_push_down.go
- pkg/types/datum.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> types: refactor Datum.Sort

- pkg/expression/builtin_compare.go
- pkg/expression/builtin_other.go
- pkg/expression/constant_fold.go
- pkg/expression/constant_propagation.go
- pkg/expression/expression.go
- pkg/expression/util.go
- pkg/planner/cardinality/selectivity.go
- pkg/planner/core/constraint/exprs.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/index_join_path.go
- pkg/planner/core/indexmerge_path.go
- pkg/planner/core/indexmerge_unfinished_path.go
- pkg/planner/core/operator/logicalop/expression_util.go
- pkg/planner/core/rule_predicate_simplification.go
- pkg/planner/util/null_misc.go
- pkg/planner/util/path.go
- pkg/util/ranger/detacher.go
Issue Number: ref #36764
We avoid this code style.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner,executor: improve the convenience of functions

- pkg/ddl/backfilling_operators.go
- pkg/disttask/importinto/BUILD.bazel
- pkg/disttask/importinto/encode_and_sort_operator.go
- pkg/disttask/importinto/encode_and_sort_operator_test.go
- pkg/disttask/importinto/task_executor.go
- pkg/lightning/backend/external/BUILD.bazel
- pkg/lightning/backend/external/onefile_writer.go
- pkg/lightning/backend/external/writer.go
- pkg/lightning/backend/external/writer_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/61398
Tests 
> 
Side effects
Documentation
```release-note
None
```
> import: adjust data mem buf block size based on max_entry_size_limit(#60139)

- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_operators.go
- pkg/ddl/backfilling_read_index.go
- pkg/disttask/framework/storage/BUILD.bazel
- pkg/disttask/framework/storage/table_test.go
- pkg/disttask/framework/storage/task_table.go
- pkg/disttask/framework/taskexecutor/execute/BUILD.bazel
- pkg/disttask/framework/taskexecutor/execute/interface.go
- pkg/disttask/framework/taskexecutor/task_executor.go
- tests/realtikvtest/addindextest3/BUILD.bazel
- tests/realtikvtest/addindextest3/operator_test.go
Issue Number: ref #61088
This PR does two things
**Extend `SubtaskSummary`**
Extend `SubtaskSummary` to store more information.
```go
// SubtaskSummary contains the summary of a subtask
// These fields represent the number of data/rows inputed to the subtask.
type SubtaskSummary struct {
RowCnt int64 `json:"rows,omitempty"`
Bytes  int64 `json:"bytes,omitempty"`
}
```
As mentioned in the comment, although we only need rows for now, we will need to store bytes as well for other executor in future.
(In future PR, we will use `Bytes` to calculate progress percentage for each import step).
**Add `Collector` interface**
This PR add new interface `Collector` to collect running time statistics.
```go
type Collector interface {
Add(bytes, rows int64)
}
```
And `RowCntListener` in …
> ddl, disttask: extend `SubtaskSummary` and add `Collector` interface

- br/CONTRIBUTING.md
- lightning/README.md
> 
Side effects
Documentation
```release-note
None
```
> docs: fix go version in doc

- pkg/planner/core/planbuilder.go
Issue Number: close #61756
Tests 
> No logic changed, simply breaking at first found non Multi Valued Index path, so avoid unnecessary looping.
Side effects
Documentation
```release-note
None
```
> Planner: Minor optimization by breaking loop on first false

- pkg/planner/core/memtable_infoschema_extractor.go
- tests/integrationtest/r/executor/infoschema_reader.result
- tests/integrationtest/t/executor/infoschema_reader.test
manual cp https://github.com/pingcap/tidb/pull/60638
Issue Number: close pingcap/tidb#60593
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix schema-table inconsistent issue in `IS.tables` (#60638) | tidb-test=release-8.5.1

- ci.md
- tests/realtikvtest/configs/classic/tikv.toml
- tests/realtikvtest/configs/next-gen/pd.toml
- tests/realtikvtest/configs/next-gen/tikv-worker.toml
- tests/realtikvtest/configs/next-gen/tikv.toml
- tests/realtikvtest/scripts/classic/run-tests-with-gotest.sh
- tests/realtikvtest/scripts/classic/run-tests.sh
- tests/realtikvtest/scripts/next-gen/run-tests-with-gotest.sh
- tests/realtikvtest/scripts/next-gen/run-tests.sh
Issue Number: close #61695
Provide some testing configuration files and scripts, example:
1. `NEXT_GEN=1 make server`
2. run the command to download peer compound binaries under the `bin` folder: `/<ci-git-clone-folder>/scripts/artifacts/download_pingcap_oci_artifact.sh --tikv=dedicated-next-gen --pd=master-next-gen --tikv-worker=dedicated-next-gen`
3. run the test command at cloned path of tidb repo: `tests/realtikvtest/scripts/next-gen/run-tests.sh bazel_***`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: add test script for bootstrap real tikv integration testing

- pkg/planner/util/optimizetrace/logicaltrace/logical_tracer.go
Issue Number: close #61854 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove copy slices before the appendItemPruneTraceStep

- br/pkg/lightning/backend/local/region_job.go
- br/tests/_utils/check_lightning_log_contains
- br/tests/lightning_write_timeout/config.toml
- br/tests/lightning_write_timeout/run.sh
- br/tests/run_group.sh
Issue Number: ref https://github.com/pingcap/tidb/issues/61326
Manual cherry-pick of #61346.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Lightning: Attempt to return writeTooSlow when we experience write timeout.

- pkg/planner/core/constraint/exprs.go
Issue Number: close #61892 
No need to allocate slices every time in DeleteTrueExprs
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: improve performance in the DeleteTrueExprs

- pkg/planner/core/casetest/tpch/tpch_test.go
just for test 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add tpch q1,q2,q3 benchmark

- pkg/executor/builder.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: minor cleanup in builder.go

- pkg/util/plancodec/binary_plan_decode.go
- pkg/util/plancodec/codec.go
- pkg/workloadlearning/BUILD.bazel
- pkg/workloadlearning/cache_test.go
- pkg/workloadlearning/handle.go
- pkg/workloadlearning/handle_test.go
- pkg/workloadlearning/metrics.go
Issue Number: close #58131
Combines the workload analyze function with the statements stats snapshot function.
1. Extract the original workload data from the snapshot of statements stats
2. Extract the memory and time consumed by the table in this query based on the query execution record and type of each operator
- Index (Pan index)
- PointGet (Pan Point get)
- TableReader (Pan)
- IndexMerge(Pan)
4. Calculate the total memory and time of each table: group and accumulate the results of the second step based on the table id
5. Calculate the total memory and time of all tables: total scan time, total mem usage
6. Calculate the table cost ratio of each table based on the table cost formula.
``` table cost = table scan time / total scan time + table mem usage / total mem …
```
> workload-learning: Extract metrics from cluster statements stats

- pkg/planner/core/physical_plans.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove unused field from physicalTableScan.

- pkg/ddl/multi_schema_change_test.go
Issue Number: close #61957
This issue has been fixed by https://github.com/pingcap/tidb/pull/48728.
This PR adds a test to avoid regression.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: add test to prevent multi-schema change subjobs shown in tidb_mdl_view

- pkg/bindinfo/testdata/binding_auto_suite_in.json
- pkg/bindinfo/testdata/binding_auto_suite_out.json
- pkg/planner/core/find_best_task.go
Issue Number: ref #60148 
Only log the fix control 52869 for index merge IF we have multiple ranges such that index merge may be possible.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: log merge fix control for multiple ranges

- pkg/lightning/backend/external/engine.go
- pkg/lightning/backend/local/engine.go
- pkg/lightning/backend/local/local.go
- pkg/lightning/backend/local/localhelper.go
- pkg/lightning/mydump/loader.go
- pkg/statistics/cmsketch.go
- pkg/statistics/handle/cache/stats_table_row_cache.go
- pkg/statistics/handle/globalstats/global_stats.go
- pkg/statistics/handle/lockstats/BUILD.bazel
- pkg/statistics/handle/lockstats/lock_stats.go
- pkg/statistics/handle/usage/indexusage/collector.go
- pkg/statistics/index.go
Issue Number: ref: https://github.com/pingcap/tidb/issues/61967
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics, lightning: remove useless code

- br/pkg/version/version.go
- br/pkg/version/version_test.go
close pingcap/tidb#60990
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: cherry-pick remove version checker (#61024) (#61549)

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/operator/logicalop/logical_plans_misc.go
- tests/integrationtest/r/executor/expand.result
- tests/integrationtest/r/expression/cast.result
- tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result
- tests/integrationtest/r/select.result
Issue Number: ref https://github.com/pingcap/tidb/issues/62006
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: lift can-push-to-cop check of expand/unionall/sort.

- pkg/planner/core/tiflash_predicate_push_down.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: reuse slices when to deal with tiflash predicate push down

- pkg/planner/cascades/old/implementation_rules.go
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/nominal_sort.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/resolve_indices.go
- pkg/planner/core/rule_inject_extra_projection.go
- pkg/planner/core/task.go
- pkg/planner/implementation/sort.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify all nominal related logic into nominal sort op.

- pkg/metrics/grafana/performance_overview.json
Issue Number: close #61441
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: add Backoff time into execution time overview for easier debug

- pkg/planner/core/access_object.go
- pkg/planner/core/base/misc_base.go
- pkg/planner/core/common_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/foreign_key.go
- pkg/planner/core/point_get_plan.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move access object interface to base interface dir.

- pkg/types/core_time.go
as the diff 
combine two same logic to one for month of days
Tests 
> 
Side effects
Documentation
```release-note
None
```
> fix: combine two same logic for month of days

- pkg/executor/builder.go
- pkg/executor/test/executor/executor_test.go
- pkg/planner/cascades/old/implementation_rules.go
- pkg/planner/core/casetest/planstats/BUILD.bazel
- pkg/planner/core/casetest/planstats/plan_stats_test.go
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/fragment.go
- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_union_all.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/physical_plan_test.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_cost_ver1.go
- pkg/planner/core/plan_cost_ver2.go
- pkg/planner/core/rule_inject_extra_projection.go
- pkg/planner/core/stringer.go
- pkg/planner/core/task.go
- pkg/planner/implementation/simple_plans.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move all physical union all related logic into physical op dir.

- pkg/extension/auth_test.go
- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/logical_plans_test.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/point_get_plan.go
- pkg/privilege/privileges/cache.go
- pkg/privilege/privileges/cache_test.go
- pkg/privilege/privileges/privileges_test.go
Issue Number: ref #61706
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: adapt (Batch)PointGet to collect column-level visit info | tidb-test=pr/2548

- pkg/planner/core/base/BUILD.bazel
- pkg/planner/core/base/misc_base.go
- pkg/planner/core/point_get_plan.go
- pkg/planner/core/rule_partition_processor.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move planner used partitionTable interface to base pkg.

- pkg/planner/core/find_best_task.go
- pkg/planner/core/plan_cost_detail_test.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove useless code

- OWNERS_ALIASES
- pkg/metrics/OWNERS
Issue Number: ref #62286 
For a temporary workaround before we complete #62286 , we'd manually check if metrics are properly updated.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Add owners cfg file for pkg/metrics module

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #62376, ref #59845, ref #59990, ref #61745, ref #61454, ref tikv/client-go#1704
Update client-go to adopt patches for v8.5.3
https://github.com/tikv/client-go/compare/dfc6328...827bf09
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: bump client-go for v8.5.3

- WORKSPACE
- build/image/base
- build/image/parser_test
- dumpling/README.md
- go.mod
Issue Number: close #62383
go1.23.11 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, and the runtime. See the [Go 1.23.11 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.11+label%3ACherryPickApproved) on our issue tracker for details.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.23.11

- README.md
Only modify to remove the English Forum entry.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Update README.md

- DEPS.bzl
- go.mod
- go.sum
- pkg/store/copr/region_cache.go
Issue Number: ref #53850
Batch load regions into the region cache when building cop tasks encounters a region miss.
client-go diff: https://github.com/tikv/client-go/compare/d4383a9a6811...0f6490369b85
Tests 
> 
1. Prepare data `sysbench --config-file=config oltp_point_select --tables=1 --table-size=1000000 --auto_inc=false prepare`
2. Split table into 1000 regions by `SPLIT TABLE sbtest1 BETWEEN (0) AND (1000000) REGIONS 1000;`
3. Restart TiDB to clean the region cache.
4. Run a simple query `explain analyze select * from sbtest1 limit 1;`
- v7.5.6: 0.24ms
- this pr: 0.01ms
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/releas …
> copr: batch load regions when region miss

- pkg/planner/core/casetest/cascades/memo_test.go
- pkg/planner/core/casetest/cbotest/BUILD.bazel
- pkg/planner/core/casetest/cbotest/cbo_test.go
- pkg/planner/core/casetest/cbotest/main_test.go
- pkg/planner/core/casetest/cbotest/testdata/analyze_suite_xut.json
- pkg/testkit/mockstore.go
- pkg/testkit/testdata/testdata.go
Issue Number: ref https://github.com/pingcap/tidb/issues/62328
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add unit/integration test case example covering cascades mode

- .github/ISSUE_TEMPLATE/config.yml
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Replace the Forum entry point with Discord and Slack communities.

- pkg/planner/core/memtable_infoschema_extractor.go
- tests/integrationtest/r/infoschema/infoschema.result
- tests/integrationtest/t/infoschema/infoschema.test
Issue Number: close https://github.com/pingcap/tidb/issues/62347
Problem Summary: memory table extractor will not match all regexp.
every schema object need to match all regexp.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: memory table extractor filter targets by all regexp

- pkg/planner/core/casetest/rule/rule_predicate_simplification_test.go
- pkg/planner/core/casetest/rule/testdata/predicate_simplification_in.json
- pkg/planner/core/casetest/rule/testdata/predicate_simplification_out.json
- pkg/planner/core/casetest/rule/testdata/predicate_simplification_xut.json
- pkg/planner/core/rule_predicate_simplification.go
Issue Number: close #62463
ShortCircuitLogicalConstants is placed at the end for better optimization effect
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix Predicate simplification is not the simplest for selection

- pkg/expression/util.go
- pkg/planner/core/issuetest/planner_issue_test.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/operator/logicalop/logical_join.go
- tests/integrationtest/r/planner/core/rule_constant_propagation.result
- tests/integrationtest/t/planner/core/rule_constant_propagation.test
Issue Number: close #51700 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: constant propagation supports more join type in the logical plan builder

- pkg/executor/builder.go
- pkg/planner/cascades/old/implementation_rules.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/access/BUILD.bazel
- pkg/planner/core/access/access_obj.go
- pkg/planner/core/access_object.go
- pkg/planner/core/explain.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/initialize.go
- pkg/planner/core/memtable_predicate_extractor.go
- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/logical_mem_table_predicate_extractor_test.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_mem_table.go
- pkg/planner/core/pb_to_plan.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cacheable_checker.go
- pkg/planner/implementation/datasource.go
- pkg/testkit/testdata/testdata.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move physical memory table into physical op dir

- br/README.md
as diff
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: a dead link and go version in BR

- pkg/ddl/backfilling_dist_scheduler_test.go
- pkg/disttask/importinto/scheduler_testkit_test.go
Issue Number: close #62623
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: use difference port to fix UT

- pkg/planner/core/casetest/enforcempp/enforce_mpp_test.go
- pkg/planner/core/casetest/enforcempp/main_test.go
- pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_xut.json
- pkg/testkit/mockstore.go
Issue Number: ref #62328
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add enforce_mpp_test cases covering cascades mode

- pkg/telemetry/ttl.go
Issue Number: close #62653
Tests 
> Only modify the log level.
Side effects
Documentation
```release-note
None
```
> telemetry: decrease the log level of telemetry failure in `ttl.go`.

- pkg/executor/join/hash_join_v1.go
Issue Number: close #62652
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Change log level to `Warning` in the `Close` of join

- pkg/planner/core/rule_predicate_simplification.go
Issue Number: close https://github.com/pingcap/tidb/issues/62675
We have already conducted the corresponding checks when passing parameters externally.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: no need to check predicate type in the updateInPredicate

- pkg/planner/core/casetest/parallelapply/parallel_apply_test.go
- pkg/planner/core/casetest/partition/integration_partition_test.go
- pkg/planner/core/casetest/partition/main_test.go
- pkg/planner/core/casetest/partition/partition_pruner_test.go
- pkg/planner/core/casetest/partition/testdata/integration_partition_suite_xut.json
- pkg/planner/core/casetest/partition/testdata/partition_pruner_xut.json
Issue Number: ref #62328
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add partition cases covering cascades mode

- pkg/util/cgroup/BUILD.bazel
- pkg/util/cgroup/cgroup.go
- pkg/util/cgroup/cgroup_memory.go
- pkg/util/cgroup/cgroup_memory_unsupport.go
maks macos happy agagin
cc @hawkingrei 
Issue Number: close #62782
Tests 
> 
Side effects
Documentation
```release-note
None
```
> fix: close issue #62782 make mac os start happy again

- pkg/executor/benchmark_test.go
- pkg/executor/builder.go
- pkg/executor/internal/mpp/local_mpp_coordinator.go
- pkg/executor/test/executor/executor_test.go
- pkg/planner/core/explain.go
- pkg/planner/core/flat_plan.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_shuffle.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan.go
- pkg/planner/core/plan_cacheable_checker.go
- pkg/planner/core/resolve_indices.go
- pkg/planner/core/stringer.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move physical shuffle related logic into physical op dir.

- pkg/tici/tici_manager_client.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tici: fix eletion key typo

- pkg/executor/builder.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/explain.go
- pkg/planner/core/generator/plan_cache/BUILD.bazel
- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_lock.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/resolve_indices.go
- pkg/planner/core/stringer.go
- pkg/sessiontxn/isolation/BUILD.bazel
- pkg/sessiontxn/isolation/readcommitted.go
- pkg/sessiontxn/isolation/repeatable_read.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move physical PhysicalLock related logic into physical op dir.

- cmd/explaintest/r/new_character_set.result
- cmd/explaintest/t/new_character_set.test
- server/util.go
close pingcap/tidb#61085
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server: replace instead of truncate encoded result (#61080)

- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/fragment.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_sequence.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/task.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
…p dir.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move physical PhysicalSequence related logic into physical op dir

- pkg/expression/expression.go
- pkg/expression/util.go
- pkg/planner/cardinality/BUILD.bazel
- pkg/planner/cardinality/cross_estimation.go
- pkg/planner/cardinality/selectivity.go
- pkg/planner/core/casetest/cascades/testdata/cascades_suite_out.json
- pkg/planner/core/operator/logicalop/logical_join.go
- pkg/planner/core/operator/physicalop/base_physical_agg.go
- pkg/planner/core/pb_to_plan.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/rule_aggregation_push_down.go
- pkg/planner/core/rule_join_reorder.go
- pkg/planner/util/funcdep_misc.go
Issue Number: ref https://github.com/pingcap/tidb/issues/45839
ExtractColumnsFromExpressions has been able to remove duplicates. In this PR, we enhence this function to make it reusing the memory and avoid allocating the slices.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: simplify the code with the ExtractColumnsFromExpressions

- pkg/executor/benchmark_test.go
- pkg/executor/builder.go
- pkg/executor/test/executor/executor_test.go
- pkg/planner/cascades/old/implementation_rules.go
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/hint_utils.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/base_physical_agg.go
- pkg/planner/core/operator/physicalop/base_physical_plan.go
- pkg/planner/core/operator/physicalop/physical_hash_agg.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/optimizer_test.go
- pkg/planner/core/physical_plan_test.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_cost_ver1.go
- pkg/planner/core/plan_cost_ver2.go
- pkg/planner/core/plan_to_pb.go
- pkg/planner/core/planbuilder_test.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/rule_inject_extra_projection.go
- pkg/planner/core/stringer.go
- pkg/planner/core/task.go
- pkg/planner/core/task_base.go
- pkg/planner/implementation/simple_plans.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move physical hash agg related logic into physical op dir.

- pkg/server/http_status.go
- pkg/server/server.go
Issue Number: close #62902
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server: use Atomic.Pointer in the Server.statusServer

- pkg/ddl/executor.go
- pkg/domain/infosync/info.go
- pkg/executor/ddl.go
- pkg/sessionctx/stmtctx/stmtctx.go
Issue Number: close #62899
introduced in #62607 where we start checking this var to determine whether the session is involved when reporting min start ts
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix data race when accessing IsDDLJobInQueue

- pkg/executor/test/infoschema/BUILD.bazel
- pkg/executor/test/infoschema/infoschema_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: merge tests for TestIndexUsageWithData

- pkg/util/stmtsummary/v2/tests/table_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/49778
There is no code set to nil in the real code.  So let's make the test code match the real code.
​Since `setupStmtSummary()` is called in every test for initialization, whether it is set to nil may not matter.​​
https://github.com/pingcap/tidb/blob/b529ae5267aa96834bcd0bb7753df67803a085d1/cmd/tidb-server/main.go#L1071-L1076
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util/stmtsummary: fix test data race

- pkg/executor/builder.go
- pkg/executor/test/executor/executor_test.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/initialize.go
- pkg/planner/core/operator/physicalop/BUILD.bazel
- pkg/planner/core/operator/physicalop/physical_cte_table.go
- pkg/planner/core/physical_plans.go
Issue Number: close #52714 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: Moved the code for PhysicalCTETable to the physicalop package.

- pkg/ddl/schemaver/syncer.go
Issue Number: ref #63005
Add log for debug
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: add debug log | tidb-test=release-8.5.1

- WORKSPACE
- pkg/planner/core/casetest/tpch/BUILD.bazel
- pkg/planner/core/casetest/tpch/testdata/tpch_suite_in.json
- pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json
- pkg/planner/core/casetest/tpch/testdata/tpch_suite_xut.json
- pkg/planner/core/casetest/tpch/tpch_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add tpch Q14 with tiflash

- pkg/util/memory/arbitrator.go
- pkg/util/memory/arbitrator_test.go
- pkg/util/memory/utils.go
Issue Number: close #63054
Since #60597
- This is an approximate test with periodic retries.
- Replace its implementation with atomic operators to make ci happy.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> memory: fix data race in #63054 

- br/cmd/br/abort.go
- br/cmd/br/backup.go
- br/cmd/br/main.go
- br/cmd/br/restore.go
Issue Number: close #63089
prevent br from becoming ddl owner
prevent br from becoming ddl owner
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: prevent br from becoming ddl owner

- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
Issue Number: close #63139
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor to use reflect.PointerTo

- pkg/expression/fts_helper.go
- pkg/expression/infer_pushdown.go
- pkg/kv/kv.go
- pkg/planner/core/casetest/tici/testdata/tici_index_suite_in.json
- pkg/planner/core/casetest/tici/testdata/tici_index_suite_out.json
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/operator/logicalop/logical_datasource.go
Issue Number: for https://github.com/pingcap/tidb/issues/61185
Add the execution support for `fts_match_prefix`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: support convert fts_match_prefix to tici expr | tidb-test=3b2adda7436d5e712bffaa859f679c5ca370811b

- pkg/executor/table_reader.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_to_pb.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove some duplicated planner functional function.

- pkg/planner/core/operator/physicalop/base_physical_plan.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: clean debug code.

- Makefile
- tests/globalkilltest/BUILD.bazel
- tests/llmtest/BUILD.bazel
- tests/realtikvtest/addindextest/BUILD.bazel
- tests/realtikvtest/addindextest1/BUILD.bazel
- tests/realtikvtest/addindextest2/BUILD.bazel
- tests/realtikvtest/addindextest3/BUILD.bazel
- tests/realtikvtest/addindextest4/BUILD.bazel
- tests/realtikvtest/brietest/BUILD.bazel
- tests/realtikvtest/brietest/pitr_test.go
- tests/realtikvtest/ddltest/BUILD.bazel
- tests/realtikvtest/flashbacktest/BUILD.bazel
- tests/realtikvtest/importintotest3/BUILD.bazel
- tests/realtikvtest/pessimistictest/BUILD.bazel
- tests/realtikvtest/pipelineddmltest/BUILD.bazel
- tests/realtikvtest/sessiontest/BUILD.bazel
- tests/realtikvtest/statisticstest/BUILD.bazel
- tests/realtikvtest/txntest/BUILD.bazel
- tools/tazel/util.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: enable bazel shard for with real tikv

- pkg/parser/ast/BUILD.bazel
- pkg/parser/ast/dml.go
- pkg/parser/ast/model.go
- pkg/parser/types/BUILD.bazel
- pkg/parser/types/field_type.go
- pkg/parser/util/BUILD.bazel
- pkg/parser/util/hash64.go
- pkg/planner/core/generator/hash64_equals/BUILD.bazel
- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/base_logical_plan.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_lock.go
Issue Number: close https://github.com/pingcap/tidb/issues/63229
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix select lock don't have Hash64 and Equals methods itself in next-gen mode.

- pkg/types/vector.go
as diff
Issue Number: ref #62543
Tests 
> 
Side effects
Documentation
```release-note
None
```
> fix: can replace a copy with slices in vector

- pkg/metrics/grafana/tidb.json
- pkg/metrics/nextgengrafana/tidb_with_keyspace_name.json
Issue Number: ref #62870
The right parentheses are missing when copying the expression, fix it.
Tests 
before:
after:
> 
Side effects
Documentation
```release-note
None
```
> metrics: fix incorrect grafana expression

- pkg/planner/core/operator/logicalop/logical_datasource.go
- pkg/planner/core/stats.go
Issue Number: close #59595
Add the explain comment of DataSource.stats and the DataSource.TableStats 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: Add some comments about the ds.rowcount

- pkg/table/tables/tables.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: skip tici index in delete/insert/update stmt | tidb-test=3b2adda7436d5e712bffaa859f679c5ca370811b

- pkg/executor/adapter.go
- pkg/executor/explain.go
- pkg/executor/test/fktest/foreign_key_test.go
Issue Number: close #63276
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix issue explain analyze DML with foreign key cascade may has bug

- lightning/pkg/importer/BUILD.bazel
- lightning/pkg/importer/table_import_test.go
- pkg/autoid_service/BUILD.bazel
- pkg/autoid_service/autoid_test.go
- pkg/disttask/example/app_test.go
- pkg/executor/importer/import_test.go
- pkg/executor/importer/importer_testkit_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix some failed tests in nextgen

- DEPS.bzl
- pkg/metrics/grafana/tidb.json
Issue Number: close #62740
Add the traffic metric which can tell the traffic cost, which help user deciding whether using local read.
This PR only add monitor for op TiDB. When next-gen can record metrics correctly, I'll port it to `nextgengrafana`.
Tests 
> 
Side effects
Documentation
```release-note
Add the traffic metrics of read requests.
```
> grafana: add KV Read Request Traffic metric

- DEPS.bzl
- go.mod
- go.sum
- pkg/sessionctx/vardef/tidb_vars.go
- pkg/store/mockstore/BUILD.bazel
- pkg/store/mockstore/mockstore.go
Remove mustParseDuration and copyImage
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: remove two useless functions

- pkg/planner/core/find_best_task.go
Using switch can make the code more concise
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simple code in the hasOnlyEqualPredicatesInDNF

- pkg/sessionctx/stmtctx/stmtctx.go
Follow https://github.com/pingcap/tidb/pull/63330#discussion_r2325908118
Tests 
> 
Side effects
Documentation
```release-note
None
```
> sessionctx: update comments

- pkg/expression/constant_propagation.go
Issue Number: close #63382
Tests 
A real tiflash is needed to reproduce this bug. So it's not easy to add this case to ci. So I verified manually.
```
setup cluster with 1 tiflash
run following sql:
drop table if exists foo, bar;
create table foo(a int, b int);
insert into foo values(0, NULL);
alter table foo set tiflash replica 1;
create table bar(a double not null, b decimal(65,0)  not null);
insert into bar values(0, 0);
alter table bar set tiflash replica 1;
set tidb_isolation_read_engines='tiflash';
select * from foo where a=all(select a from bar where bar.b=foo.b);
```
before:
after:
> 
Side effects
Documentation …
> planner: fix return type was modified unexpectedly when building cast

- pkg/executor/copr_cache_test.go
- pkg/executor/test/executor/executor_test.go
- pkg/executor/update_test.go
Issue Number: ref #63343
Fix some next-gen tests.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix some next-gen tests

- pkg/executor/test/analyzetest/BUILD.bazel
- pkg/executor/test/analyzetest/analyze_test.go
- pkg/planner/cardinality/BUILD.bazel
- pkg/planner/cardinality/selectivity_test.go
- pkg/statistics/handle/handletest/lockstats/BUILD.bazel
- pkg/statistics/handle/handletest/lockstats/lock_partition_stats_test.go
- pkg/statistics/handle/handletest/lockstats/lock_table_stats_test.go
In the next-gen, we will not support the analyze version1 and v1 has some bugs wit the next-gen. so we skip it first.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: skip analyze v1 test for the next-gen

- cmd/tidb-server/main.go
- cmd/tidb-server/main_test.go
- pkg/config/config.go
- pkg/domain/sysvar_cache.go
- pkg/sessionctx/vardef/tidb_vars.go
- pkg/sessionctx/variable/variable.go
Issue Number: close #63320
Problem Summary: As title.
Tests 
```
cat >> xx.toml << EOF
[instance]
tidb_server_memory_limit = "80%"
EOF
./bin/tidb-server -config xx.toml
select @@global.tidb_server_memory_limit
show 80%
modify config to 70%
./bin/tidb-server -config xx.toml
select @@global.tidb_server_memory_limit
show 70%
./bin/tidb-server
select @@global.tidb_server_memory_limit
show 80%
```
> 
Side effects
Documentation
```release-note
None
```
> config: add new instance variables

- pkg/executor/test/analyzetest/analyze_test.go
Issue Number: ref #63501 
TestIssue20874 is listed as a frequent flaky test. Given this - there is really no value to testing this issue on current master branch with Stats Version 1. At the current release, all customers should be using version 2.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: flaky test cleanup

- pkg/tici/tici.pb.go
- pkg/tici/tici.proto
- pkg/tici/tici_grpc.pb.go
- pkg/tici/tici_manager_client.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tici: Use JSON in creating full-text index | tidb-test=ef726505f262e22c6ec9c8951273bb5ee20abefb

- pkg/planner/cardinality/row_count_index.go
- pkg/planner/cardinality/testdata/cardinality_suite_out.json
Issue Number: ref #59333 
Correct an error in how the min estimate is calculated. It was always intended to collect the "minimum possible estimate". The current estimation actually allows the regular estimate to be less than the min. The regular estimate should be:
- greater than or equal to the min
- less than or equal to the max.
If the estimate is outside of the min or max, then we have lost the concept of min and max.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix min estimate | tidb-test=pr/2603

- pkg/executor/test/indexmergereadtest/index_merge_reader_test.go
Issue Number: ref #63501 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: flaky test cleanup2

- pkg/executor/join/index_lookup_hash_join.go
Issue Number: ref #63501 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix flaky test TestIndexJoin31494

- tests/realtikvtest/txntest/stale_read_test.go
Issue Number: close #63271
The `TestStaleReadAllCombinations/tidb_read_staleness` test case is flaky under high CI load due to tight timing constraints.
**Changes made:**
1. Relax the time constraints
2. Reorder cases, to run `tidb_read_staleness` cases first 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: improve timing robustness in TestStaleReadAllCombinations

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #63653, ref #62704
Update client-go to adopt patches for v8.5.4
https://github.com/tikv/client-go/compare/79074b120a3e...ea4b866b82fa
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: bump client-go for v8.5.4

- pkg/planner/core/casetest/rule/rule_outer2inner_test.go
- tests/integrationtest/r/planner/core/rule_outer2inner.result
- tests/integrationtest/t/planner/core/rule_outer2inner.test
Issue Number: ref #60080
add more test cases for outer2inner.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more tests for outer2inner

- pkg/metrics/nextgengrafana/performance_overview_with_keyspace_name.json
Issue Number: close #63797
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: add tikv performance for keyspace name

- pkg/executor/simple.go
- pkg/executor/test/simpletest/BUILD.bazel
- pkg/executor/test/simpletest/simple_test.go
- pkg/executor/test/tiflashtest/tiflash_test.go
- pkg/statistics/handle/cache/internal/testutil/testutil.go
- pkg/statistics/handle/storage/BUILD.bazel
- pkg/statistics/handle/storage/gc.go
- pkg/statistics/handle/storage/gc_test.go
- pkg/statistics/handle/storage/read.go
- pkg/statistics/handle/syncload/stats_syncload.go
- pkg/statistics/handle/types/interfaces.go
- pkg/statistics/table.go
- tests/integrationtest/r/executor/expand.result
- tests/integrationtest/r/executor/kv.result
- tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result
Issue Number: ref https://github.com/pingcap/tidb/issues/57901, ref https://github.com/pingcap/tidb/issues/57983
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix the behavior of stats' GC process | tidb-test=pr/2617

- br/tests/br_check_dup_table/run.sh
close pingcap/tidb#61592
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: enhance table existence check (#61596) | tidb-test=release-8.5-20250114-v8.5.0

- pkg/executor/BUILD.bazel
- pkg/executor/inspection_result.go
- pkg/executor/inspection_result_internal_test.go
Issue Number: close #63836 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: support B suffix for convertReadableSizeToByteSize

- pkg/executor/inspection_result.go
Issue Number: close #63842 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Ignore PD config items that are expected to be different
