pingcap/tidb

- pkg/distsql/context/BUILD.bazel
- pkg/distsql/context/context.go
- pkg/distsql/context_test.go
- pkg/expression/infer_pushdown.go
- pkg/planner/context/context.go
- pkg/planner/core/util.go
- pkg/session/session.go
- pkg/sessionctx/stmtctx/stmtctx.go
- pkg/util/context/warn.go
- pkg/util/mock/context.go
Issue Number: close #52848 
We have multiple implementation of `WarnHandler`: the most used one is the `StatementContext` itself. However, we already have a `StaticWarnHandler`, which implements nearly all methods needed by the `WarnHandler`. Now, it'd be better to implement the warning related methods in `StatementContext` with `StaticWarnHandler`.
1. Remove the `warnings` and `extraWarnings` in the `StatementContext`.
2. Add two `WarnHandler`s to handle normal warning and extra warning (which is used in slow log).
Tests 
> The change should be covered by existing tests
> 
Side effects
Documentation
```release-note
None
```
> stmtctx, context: remove the redundant implementation of warnings/extraWarnings in statement context

- pkg/infoschema/BUILD.bazel
- pkg/infoschema/builder.go
- pkg/infoschema/infoschema.go
- pkg/infoschema/infoschema_nokit_test.go
- pkg/infoschema/infoschema_v2.go
Issue Number: close #52610
- add a schema id->name map
Tests 
insert P99: 7.8ms -> 4ms; P95: 5.5ms -> 3.8ms
```
mysql> select count(1) from information_schema.schemata;
+----------+
| count(1) |
+----------+
|     7007 |
+----------+
mysql> create table t(id int);
Query OK, 0 rows affected (0.14 sec)
mysql> insert into t values(1);
```
> 
Side effects
Documentation
```release-note
None
```
> infoschema: speedup SchemaByID

- pkg/planner/core/preprocess.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove useless code

- pkg/ddl/db_integration_test.go
- pkg/ddl/index.go
Issue Number: close https://github.com/pingcap/tidb/issues/53281
Both scenarios are explained in the issue.
Introduce code for this issue: https://github.com/pingcap/tidb/pull/50624/files#diff-45ad039a8b87835b475a52615355c444538d3a1f31a84d7b3ac94e15b1ce8721R126-R127
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix a bug about setting MaxIndexLength

- br/pkg/restore/db_test.go
- pkg/ddl/ddl_worker.go
- pkg/ddl/job_table.go
- pkg/domain/domain.go
- pkg/session/bootstrap.go
- pkg/session/session.go
Issue Number: close #53073
tidb-1 keeps printing "someone is not synced", which means it is blocked at `waitSchemaSynced`.
```
[2024/05/13 17:24:32.067 +08:00] [INFO] [syncer.go:352] ["syncer check all versions, someone is not synced"] [category=ddl] [info="instance ip tc-tidb-1.tc-tidb-peer.endless-ha-test-add-index-tps-7576420-1-811.svc, port 4000, id d3ac6d21-0137-4106-b42a-89692b7ba7e1"] ["ddl job id"=791] [ver=1931]
```
tidb-1 is DDL owner. However, tidb-1's schema version is **less** than non-owner TiDB (here are the results from `tiup ctl:v8.0.0 etcd --endpoints={pd_addr}:2379 get --prefix /tidb/ddl`):
```
/tidb/ddl/all_schema_by_job_versions/791/5bd21551-75b9-4a47-86d4-9520ce74cfd3
1931
/tidb/ddl/all_schema_by_job_versions/791/d3ac6d21-0137-4106-b42a-89692b7ba7e1 …
```
> ddl: add owner_id field to tidb_mdl_info to avoid unexpected writes

- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/handletest/statstest/BUILD.bazel
- pkg/statistics/handle/handletest/statstest/stats_test.go
Issue Number: ref #37548
primary key's is_index is false. so it cannot load the topn. it's stats cannon be set as ```AllFull```.
Tests 
according to https://github.com/pingcap/tidb/issues/37548, it's result is right.
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix wrong behavior for primary key' non-lite init stats

- pkg/planner/core/rule_column_pruning.go
Issue Number: close #52768 
The slice passed to the column pruning should be shallow copied.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: column pruning should use a shallow copy slice

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #53316
Related PR: https://github.com/tikv/client-go/pull/1344
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix query panic when query exceeded resource group quota limitation

- pkg/ddl/constant.go
- pkg/ddl/ddl_worker.go
- pkg/ddl/job_table.go
Issue Number: close #53327
In #53234, TiDB fails to execute below upgrade DDL, because it needs to access `owner_id` from `tidb_mdl_info`.
```
ALTER TABLE mysql.tidb_mdl_info ADD COLUMN owner_id VARCHAR(64) NOT NULL DEFAULT '';
```
For the DDLs related to system tables, we skip using `owner_id` field to prevent above DDL failed.
Tests 
1. Prepare a v8.0.0 cluster.
2. Kill v8.0.0 TiDB server.
3. Start latest(compiled from this PR) TiDB server.
4. Execute upgrade process normally. It can also serve users' DDL. 
> 
Side effects
Documentation …
> ddl: do not reference owner_id for specific system DDL

- pkg/executor/batch_point_get.go
- pkg/executor/mem_reader.go
- pkg/executor/point_get.go
- pkg/table/tables/index.go
- pkg/tablecodec/tablecodec.go
- tests/integrationtest/r/globalindex/mem_index_lookup.result
- tests/integrationtest/r/globalindex/mem_index_merge.result
- tests/integrationtest/r/globalindex/mem_index_reader.result
- tests/integrationtest/r/globalindex/point_get.result
- tests/integrationtest/t/globalindex/mem_index_lookup.test
- tests/integrationtest/t/globalindex/mem_index_merge.test
- tests/integrationtest/t/globalindex/mem_index_reader.test
- tests/integrationtest/t/globalindex/point_get.test
Issue Number: close #49995
Problem Summary: Ref PR https://github.com/pingcap/tidb/pull/50013, remove `insert on duplicate` part. /cc @L-maple 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table, executor: let `SplitIndexValue` work with clustered index table.

- docs/design/2024-05-10-extension-authentication-plugin.md
Issue Number: ref #53181
This is the design doc for #53181.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: design for extension auth plugin

- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/preprocess.go
- tests/integrationtest/r/expression/noop_functions.result
- tests/integrationtest/t/expression/noop_functions.test
Issue Number: close #52432 
The `LOCK IN SHARE MODE` clause for `SELECT` statements is currently a noop, controlled by `tidb_enable_noop_functions`: when `tidb_enable_noop_functions=OFF`, using a noop like `LOCK IN SHARE MODE` should cause an error. However, point-get queries use a special "fast path" that accidentally bypasses this noop check, meaning that a query like `select * from t where a=1 lock in share mode;` (where `a` is a key column) will run even when `tidb_enable_noop_functions=OFF`.
* Move the checks for noop functionality in `SELECT` statements (both `LOCK IN SHARE MODE` and `SQL_CALC_FOUND_ROWS`) out of `buildLogicalPlan` and into `Preprocess`, which runs before the `TryFastPlan` fast path for point-get queries.
* Add a new `noop_functions` test case to …
> planner: move checks for noop functions in select statements to preprocess

- session/session.go
Issue Number: close #46522
Hotfix for 6.1.7
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: reset CTEStorageMap before txn conflict and retry() #49399

- pkg/autoid_service/autoid.go
Issue Number: ref #38442
The original design is that we try our best to avoid holes in AUTO_ID_CACHE=1, 
so when autoid leader exit, forceRebase is called to return the non-consumed in memory IDs back.
When there are a lot of tables, this operation could not be finish quickly.
And tidb graceful shutdown can not done within 30s. This cause tidb can not restart quickly to provide service.
We think over it and deside to remove the force rebase on close behavior.
Tests 
> 
No unit test apply here (it requires tidb restart to cover the changes).
Some integration test may notice the change.
Side effects
Documentation
Behavior change, not tidb restart can cause hole in auto id allocating using AUTO_ID_CACHE=1
Please refer to …
> autoid_service: remove the force rebase on close behavior

- pkg/ddl/constant.go
- pkg/ddl/ddl_worker.go
Issue Number: close https://github.com/pingcap/tidb/issues/53327
This PR is a patch for #53332.
Except `mysql.tidb_mdl_info`, there are other system DDLs during upgrade, we should avoid reference `owner_id` for all of them.
```
[2024/05/17 10:47:07.637 +08:00] [INFO] [session.go:3894] ["CRUCIAL OPERATION"] [conn=0] [schemaVersion=39] [cur_db=] [sql="ALTER TABLE mysql.stats_meta_history ADD COLUMN IF NOT EXISTS `source` varchar(40) NOT NULL after `version`;"] [user=]
[2024/05/17 10:47:07.717 +08:00] [INFO] [ddl_worker.go:261] ["add DDL jobs"] [category=ddl] ["batch count"=1] [jobs="ID:80, Type:add column, State:queueing, SchemaState:none, SchemaID:1, TableID:64, RowCount:0, ArgLen:4, start time: 2024-05-17 10:47:07.655 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0, …
```
> ddl: do not reference owner_id for all system DDLs

- pkg/executor/select_into_test.go
- pkg/planner/core/point_get_plan.go
Issue Number: close #42093
Problem Summary: planner: skip fast-point-get for select-into-outfile statements
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: skip fast-point-get for select-into-outfile statements

- pkg/config/BUILD.bazel
- pkg/config/config.go
- pkg/config/config_test.go
Issue Number: close #53312
If a user sets `token-limit` to a big value, TiDB will OOM.
If the token-limit is bigger than 1M, set it to 1M.
It won't report errors so it's compatible with previous versions.
One TiDB instance won't have over 1M concurrent queries because that will mean at least 1M goroutines and file descriptors.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> config: set max token limit to 1M

- pkg/util/security.go
- pkg/util/security_test.go
Issue Number: close #53357
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util/security: support client TLS verifies CommonName of server

- pkg/planner/core/integration_test.go
- pkg/util/ranger/points.go
Issue Number: close #50235
Problem Summary: planner: fix the wrong result caused by `year_col cmp out-of-range-uint`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the wrong result caused by `year_col cmp out-of-range-uint`

- pkg/expression/contextstatic/exprctx.go
- pkg/expression/contextstatic/exprctx_test.go
Issue Number: close #53390
fix default value of `GetDefaultCollationForUTF8MB4` of `StaticExprContext`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: fix default value of `GetDefaultCollationForUTF8MB4` of `StaticExprContext`

- pkg/ddl/export_test.go
- pkg/ddl/internal/session/BUILD.bazel
- pkg/ddl/internal/session/session_pool.go
Issue Number: close #53377
Remove `mock.Context` ref in production code in `ddl/session/session_pool.go`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: remove `mock.Context` ref in `ddl/session/session_pool.go`

- README.md
Issue Number: N/A
Problem Summary: Updates one heading in `README.md` to make the heading and description match. The existing ones don't match. [TiDB Developer Guide](https://docs.pingcap.com/tidb/stable/dev-guide-overview) and [TiDB Cloud Developer Guide](https://docs.pingcap.com/tidbcloud/dev-guide-overview) are for application developers, not for those contributors who would like to contribute to TiDB code. For how to contribute to TiDB, it's described in the [Contributing](https://github.com/pingcap/tidb/blob/master/README.md#contributing) section.
Tests 
> 
Side effects
Documentation …
> docs: update readme to make heading and description match

- pkg/ddl/BUILD.bazel
- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_scheduler.go
- pkg/ddl/backfilling_test.go
- pkg/ddl/column.go
- pkg/ddl/ddl_api.go
- pkg/ddl/reorg.go
- pkg/ddl/schematracker/dm_tracker.go
- pkg/sessionctx/stmtctx/stmtctx.go
Issue Number: ref #53388
see issue
introduce `newReorgExprCtx` to return an `ExprContext` for DDL reorg phase. `newReorgExprCtx` will replace `newReorgSessCtx` when only expr context is required. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: introduce `newReorgExprCtx` to replace `mock.Context` usage

- lightning/tests/lightning_config_max_error/run.sh
- lightning/tests/lightning_duplicate_resolution_error/run.sh
- lightning/tests/lightning_duplicate_resolution_error_pk_multiple_files/run.sh
- lightning/tests/lightning_duplicate_resolution_error_uk_multiple_files/run.sh
- lightning/tests/lightning_duplicate_resolution_error_uk_multiple_files_multicol_index/run.sh
- lightning/tests/lightning_issue_40657/run.sh
- lightning/tidb-lightning.toml
- pkg/lightning/config/config.go
- pkg/lightning/errormanager/errormanager.go
- pkg/lightning/errormanager/errormanager_test.go
- pkg/lightning/errormanager/resolveconflict_test.go
Issue Number: close #52393
Provide view for users regardless of the lightning configuration.
Tests 
> 
Side effects
Documentation
```release-note
For lightning conflict detection "replace" mode, the conflicting data are recorded in the `lightning_task_info.conflict_view` view of the target TiDB cluster.
If the value for column is_precheck_conflict is 0, it stands for conflicting data detected by post-import conflict detection in the physical import mode; If the value for column is_precheck_conflict is 1, it stands for conflicting data detected …
```
> lightning: provide view for users when using conflict detection

- pkg/executor/set_test.go
- pkg/sessionctx/variable/sysvar.go
Issue Number: close #52636
```text``` is not too large to lead to the problem. Some customers use it in the business. so we remove it in the ```tidb_analyze_skip_column_types```.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> variable: remove text as a default type in the tidb_analyze_skip_column_types | tidb-test=pr/2334

- pkg/executor/analyze_col_v2.go
- pkg/executor/analyze_utils.go
- pkg/executor/builder.go
- pkg/sessionctx/variable/sysvar.go
Issue Number: close #53262
When tidb cluster is larger and larger, the concurrency of the analyze scan should be larger to have a better performance. so we should make analyze_distsql_scan_concurrency adaptive.
BTW, Even a fourfold increase in concurrency seems conservative; for some customers, the actual concurrency is a thousand times the default value.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: adaptively control analyze distsql concurrency 

- pkg/expression/context/context.go
Issue Number: close #53375
Some tests are unstable for assertations of location:
```
[2024/05/17 07:32:17.193 +00:00] [INFO] [job_table.go:349] ["the owner sets owner operator value"] [category=ddl] [ownerOp=none]
panic: assert failed, location mismatch, ctxLoc: UTC, varsLoc: UTC, stmtLoc: UTC [recovered]
panic: assert failed, location mismatch, ctxLoc: UTC, varsLoc: UTC, stmtLoc: UTC
```
The assert fails because the underlayer pointers of location are the not the same. However this assert should pass because they are the same location in fact
Compare location name instead of pointer
Tests 
> 
Side effects
Documentation …
> *: fix unstable assert for location

- pkg/expression/aggregation/BUILD.bazel
- pkg/expression/aggregation/aggregation.go
- pkg/expression/aggregation/explain.go
- pkg/planner/core/enforce_mpp_test.go
- pkg/planner/core/exhaust_physical_plans.go
Issue Number: close https://github.com/pingcap/tidb/issues/51362
Tests 
> 
Side effects
Documentation
```release-note
planner: fix mpp final agg couldn't co-exist with non-final mode
```
> planner: fix mpp final agg couldn't co-exist with other non-final mode

- pkg/ddl/partition.go
- pkg/executor/batch_checker.go
- pkg/executor/builder.go
- pkg/executor/write.go
- pkg/planner/core/point_get_plan.go
- pkg/table/table.go
- pkg/table/tables/partition.go
Issue Number: close #53431
Seems we can replace `expression.BuildContext` with `expression.EvalContext` for `PartitionedTable` because we only need to "evaluate" an expression.
- delete some unnecessary codes
- Replace  `expression.BuildContext` with `expression.EvalContext` in some methods in `PartitionedTable`
Tests 
> Just regress exist tests
Side effects
Documentation
```release-note
None
```
> table: simplify the locate partition args for `PartitionedTable`

- pkg/planner/core/plan_cache_test.go
- pkg/util/ranger/ranger.go
- tests/integrationtest/r/planner/core/partition_pruner.result
Issue Number: close #45783
bigint would be returned if overflow error occurs, so `convertPoint` would adjust the `excl` of the boundary accordingly, and impossible ranges would be removed by consequent `validIntervals()`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ranger: handle longlong overflow properly

- pkg/infoschema/infoschema.go
- pkg/planner/core/collect_column_stats_usage.go
- pkg/planner/core/collect_column_stats_usage_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/53403
We shouldn't collect stats usage for system tables. So in this PR, we do a check before we add them to the column map.
Tests 
> 
Side effects
Documentation
```release-note
When collecting usage statistics for tables, do not include system tables
在统计表的使用情况时，不包括系统表的信息。
```
> planner: skip all system tables when collecting prediction columns

- pkg/ddl/syncer/syncer.go
- pkg/ddl/syncer/syncer_nokit_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/53508
the `require.Zero(t, jobNodeVersionCnt())` check might fail if the loop  cancelled before it receive the last DELETE event. it does not affect the correctness, so remove it.
see https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/53489/fast_test_tiprow/1793524686622035968
```
syncer_nokit_test.go:192: 
Error Trace:	pkg/ddl/syncer/syncer_nokit_test.go:192
Error:      	Should be zero, but was 1
Test:       	TestSyncJobSchemaVerLoop
```
Tests 
> 
Side effects
Documentation …
> test: fix flaky test TestSyncJobSchemaVerLoop

- pkg/ddl/backfilling_operators.go
- pkg/disttask/framework/taskexecutor/task_executor.go
- pkg/executor/adapter.go
- pkg/executor/adapter_test.go
- pkg/store/copr/coprocessor.go
- tests/realtikvtest/addindextest3/operator_test.go
Issue Number: close #50089
always return context error when recvFromRespCh return `closed=true`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> copIterator: return context error to avoid return incorrect result on context cancel/timeout

- pkg/expression/expr_to_pb_test.go
- pkg/expression/infer_pushdown.go
Issue Number: close #51877
As described in #51877, such case can't be supported in TiKV side, just disallow it to be pushed down.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: Disallow conv fuction with hybrid type argement to be pushed down to TiKV

- pkg/planner/core/plan_cache_test.go
- pkg/util/ranger/ranger.go
Issue Number: close #46538
ref #50489
float/integers would be returned if overflow error occurs, so convertPoint would adjust the excl of the boundary accordingly, and impossible ranges would be removed by consequent validIntervals().
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ranger: handle float/integers overflow properly

- pkg/executor/test/analyzetest/analyze_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/sysvar_test.go
In TiDB we have a global variable called tidb_persist_analyze_options, the default value is true, and it will help us to store the analyze options in the system table mysql.analyze_options.
We know that the Predicate Columns collection feature relies on this system to store the column selection. So if we set tidb_persist_analyze_options to false, the predicate column feature won't work anymore. Every time you need to explicitly ANALYZE TABLE table_name PREDICATE COLUMNS to make sure TiDB only analyses the predicate columns, otherwise auto-analyze it will keep analysing all columns.
**So tidb_enable_column_tracking only takes effect when tidb_persist_analyze_options is turned on.**
Issue Number: close https://github.com/pingcap/tidb/issues/53478
I added some checks before …
> sysvar: tidb_enable_column_tracking only takes effect when tidb_persist_analyze_options is turned on

- pkg/executor/admin.go
- pkg/executor/builder.go
- pkg/executor/test/admintest/BUILD.bazel
- pkg/executor/test/admintest/admin_test.go
- tests/integrationtest/r/executor/foreign_key.result
- tests/integrationtest/t/executor/foreign_key.test
Issue Number: close #53439
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: global index supports `admin [recover | cleanup] index`

- pkg/planner/core/casetest/physicalplantest/BUILD.bazel
- pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_in.json
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- pkg/planner/core/rule_build_key_info.go
Issue Number: close #46962
Skip the partial agg mode check in the key_build_info when the agg function is empty.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix panic error when subquery + always true predicate in where clause

- pkg/planner/core/find_best_task.go
- pkg/planner/core/indexmerge_path.go
- tests/integrationtest/r/globalindex/multi_valued_index.result
- tests/integrationtest/t/globalindex/multi_valued_index.test
Issue Number: ref #45133
Problem Summary: Add some test cases for the case where the global index is also a multi-valued index. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove some restrictions for global index

- pkg/expression/builtin_cast.go
- pkg/expression/builtin_cast_vec.go
- pkg/types/json_binary.go
- tests/integrationtest/r/expression/json.result
- tests/integrationtest/t/expression/json.test
Issue Number: close #53352
When casting json as datetime/duration, the `fsp` of target type is not obeyed. 
This PR is split from #53363, because #53363 will be held for a while (as long as MySQL didn't confirm the behavior on JSON implicit cast). This one is a pure/simple bug fix, so it can be merged at first.
Follow the configuration of the return type to set the correct `fsp`. This PR didn't remove the original `GetTime` function, but just mark it as deprecated, because there are still many usages inside the `json` itself.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that casting json as time or duration will drop the fractional part.
```
> expression: fix the fsp of casting json as datetime/duration

- pkg/domain/domain.go
- pkg/infoschema/cache.go
- pkg/infoschema/test/cachetest/BUILD.bazel
- pkg/infoschema/test/cachetest/cache_test.go
Issue Number: close #53428
Problem Summary: fix issue of information schema cache miss cause by schema version gap
When DDL has empty schema version, will cause cache miss, then stale-read query need to load snapshot schema from TiKV.
```sql
[2024/05/23 06:15:10.546 +00:00] [INFO] [domain.go:287] ["diff load InfoSchema success"] [currentSchemaVersion=6760] [neededSchemaVersion=6762] ["start time"=2.583049ms] [gotSchemaVersion=6762] [phyTblIDs="[]"] [actionTypes="[]"] [diffTypes="[\"drop table\"]"]
[2024/05/23 06:15:17.869 +00:00] [INFO] [domain.go:287] ["diff load InfoSchema success"] [currentSchemaVersion=6763] [neededSchemaVersion=6765] ["start time"=2.040666ms] [gotSchemaVersion=6765] [phyTblIDs="[10496]"] [actionTypes="[4]"] [diffTypes="[\"drop table\"]"]
[2024/05/23 06:15:18.051 …
```
> infoschema: fix issue of information schema cache miss cause by schema version gap

- pkg/ddl/constraint_test.go
Issue Number: close #48123
see analyze and root cause here https://github.com/pingcap/tidb/issues/48123#issuecomment-2132584670
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix flaky test TestAlterAddConstraintStateChange3

- pkg/metrics/grafana/tidb.json
Issue Number: close #53558
Sync load's QPS in the grafana should be integer.
Tests 
before
after
> 
Side effects
Documentation
```release-note
None
```
> metrics: fix wrong value in the sync load QPS

- DEPS.bzl
- Makefile
- go.mod
- go.sum
change
upgrade
upgrade failpoint to include this https://github.com/pingcap/failpoint/pull/83
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade failpoint version

- pkg/planner/core/planbuilder.go
- pkg/statistics/handle/types/interfaces.go
- pkg/statistics/handle/usage/predicate_column.go
1. I added some comments to the GetPredicateColumns function.
2. Remove an unnecessary check, because the column id is always not null. You can find it in the schema:
```sql
CreateColumnStatsUsageTable = `CREATE TABLE IF NOT EXISTS mysql.column_stats_usage (
table_id BIGINT(64) NOT NULL,
column_id BIGINT(64) NOT NULL,
last_used_at TIMESTAMP,
last_analyzed_at TIMESTAMP,
PRIMARY KEY (table_id, column_id) CLUSTERED
);`
```
3. Added a TODO item to indicate the need to reconsider this design.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-gu …
> statistics: add comments and remove unnessary check

- DEPS.bzl
- distsql/distsql_test.go
- domain/domain.go
- infoschema/cache.go
- infoschema/cache_test.go
- tests/realtikvtest/sessiontest/session_fail_test.go
- util/logutil/BUILD.bazel
Cherry-pick #53445  #47810 
Issue Number: close #53428
Problem Summary: fix issue of information schema cache miss cause by schema version gap
When DDL has empty schema version, will cause cache miss, then stale-read query need to load snapshot schema from TiKV.
```sql
[2024/05/23 06:15:10.546 +00:00] [INFO] [domain.go:287] ["diff load InfoSchema success"] [currentSchemaVersion=6760] [neededSchemaVersion=6762] ["start time"=2.583049ms] [gotSchemaVersion=6762] [phyTblIDs="[]"] [actionTypes="[]"] [diffTypes="[\"drop table\"]"]
[2024/05/23 06:15:17.869 +00:00] [INFO] [domain.go:287] ["diff load InfoSchema success"] [currentSchemaVersion=6763] [neededSchemaVersion=6765] ["start time"=2.040666ms] [gotSchemaVersion=6765] [phyTblIDs="[10496]"] [actionTypes="[4]"] [diffTypes="[\"drop table\"]"] …
```
> infoschema: fix issue of information schema cache miss cause by schema version gap (#53445)

- br/pkg/restore/internal/prealloc_db/BUILD.bazel
- br/pkg/restore/internal/prealloc_db/db_test.go
- pkg/ddl/ddl_api.go
- pkg/ddl/sequence.go
- pkg/ddl/table.go
Issue Number: close https://github.com/pingcap/tidb/issues/53374
- Invoke `callHookOnChanged` after `BatchCreateTableWithInfo`.
- Refactor and extract `createSequenceWithCheck`.
- Support create sequences in `onCreateTables`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: support create sequences with `BatchCreateTableWithInfo`

- pkg/server/BUILD.bazel
- pkg/server/server.go
- pkg/util/BUILD.bazel
- pkg/util/tokenlimiter.go
just remove the code. it will be convenient for developers to use it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util: move server.TokenLimiter into util

- pkg/statistics/handle/bootstrap.go
Issue Number: close #53607
GetMeta's SQL cannot order by ```table id```. so ```initStatsMeta4Chunk``` cannot get max table id.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: make sure that get max table id when to init stats

- pkg/statistics/fmsketch.go
I have made the necessary corrections to the comments for FMSketch. Although we refer to it as FMSketch, it is actually a variant of FMSketch. The concept is quite similar, but the implementation differs significantly. Therefore, we need to update the comment to avoid confusion.
Some more links:
1. https://dsf.berkeley.edu/cs286/papers/synopses-fntdb2012.pdf (chapter 5.4.3)
2. https://users.cs.utah.edu/~lifeifei/cs6931/lecture5 (page 3)
3. https://www.vldb.org/conf/2001/P541.pdf (section 3.2)
Tests 
> 
Side effects
Documentation …
> statistics: refine comments to FMSketch

- pkg/domain/domain.go
- pkg/domain/infosync/info.go
- pkg/server/BUILD.bazel
- pkg/server/stat_test.go
- pkg/statistics/handle/BUILD.bazel
- pkg/statistics/handle/bootstrap.go
Issue Number: close #53592
The `initStatsCtx` is not get from internal session pool, so it's not tracked by min start ts service, thus gc lifetime can overtake it easily.
Insert it into tracked session table and it will block gc.
Tests 
> 
I reproduce the test mentioned in issue, the stats are loaded successfully after 30min.
Side effects
Documentation
```release-note
fix a bug that tidb will report gc lifetime too short when tidb bootstrap with slow loading statistics
```
> domain: make the transaction from `initStatsCtx` blocking gc

- pkg/util/printer/printer.go
Issue Number: close #53618 
Related: 
- https://github.com/pingcap/tidb/pull/13763
- https://github.com/golang/go/issues/67401
Alternative solution (not chosen):
```patch
diff --git a/Makefile.common b/Makefile.common
index b540debd42..bab0acd3c9 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -71,6 +71,7 @@ LDFLAGS += -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBBuildTS=$(shell
LDFLAGS += -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitHash=$(shell git rev-parse HEAD)"
LDFLAGS += -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitBranch=$(shell git rev-parse --abbrev-ref HEAD)"
LDFLAGS += -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBEdition=$(TIDB_EDITION)"
+LDFLAGS += "-checklinkname=0"
EXTENSION_FLAG =
ifeq ($(shell if [ -f …
```
> util: use runtime.Version() to get Go version

- pkg/ddl/column.go
- pkg/executor/BUILD.bazel
- pkg/executor/executor_txn_test.go
- pkg/table/tables/tables.go
Issue Number: close #53133
Previously, when TiDB writes delete records to binlog, column count of schema and data mismatch. This is because only public columns are selected, while data includes all deletable columns.
Make schema use all deletable columns.
Tests 
1. deploy two TiDB clusters, and start pump & drainer.
2. modify upstream TiDB code:
```diff
diff --git a/pkg/config/config.toml.example b/pkg/config/config.toml.example
index c1438a9e85..b73828367d 100644
--- a/pkg/config/config.toml.example
+++ b/pkg/config/config.toml.example
@@ -416,7 +416,7 @@ capacity-mb = 1000.0
-enable = false
+enable = true
write-timeout = "15s"
diff --git a/pkg/ddl/column.go b/pkg/ddl/column.go
index 206b64d513..1727ba4c44 100644
--- a/pkg/ddl/column.go
+++ b/pkg/ddl/column.go
@@ -173,6 …
```
> executor: sync deletable columns to binlog when remove record

- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_scheduler.go
- pkg/ddl/ingest/backend.go
- pkg/ddl/ingest/engine_mgr.go
- pkg/ddl/ingest/mock.go
- tests/realtikvtest/addindextest4/ingest_test.go
Issue Number: close #53641
in the old code, `finishedWritingNeedImport` checks `closedEngine != nil` which stands for "there's a pending engine to be imported". Now it checks `openedEngine == nil` which stands for "all writing of this engine is finished". The difference is if retry happens after importing engine is finished, `closedEngine` is assigned to nil, and old `finishedWritingNeedImport` returns `false` but `importStarted` returns `true`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: change finishedWritingNeedImport to importStarted

- pkg/executor/compiler.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_lru.go
- pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: fix small regression caused by #53094
BenchmarkPreparedPointGet: `7020 ns/op` --> `6528 ns/op`
Skip `GetMatchOpts` and `checkPreparedPriv` for cached point-get plans
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix small regression caused by #53094

- pkg/ddl/backfilling_scheduler.go
Issue Number: ref #53388
This line seems useless now:
https://github.com/pingcap/tidb/blob/afd23434dc558f00514dd7cc0295807002b69e16/pkg/ddl/backfilling_scheduler.go#L280
This line is first introduced in PR #25728, and [this line]( https://github.com/pingcap/tidb/pull/25728/files#diff-1bbc7833321782b3a22a842b6237974b6a60cb07b49b246b85552ab5e915ed6eR624 )  disallows 0 value when altering a column from integer to time.
However, after PR #47794, it seems not necessary because [this change](https://github.com/pingcap/tidb/pull/47794/files#diff-cedde52f04eef8a5117a506a088e41a878c00e147d529fcda309d834c966a010R220) does the same work.
Currently, `InCreateOrAlterStmt` is only read by `ResetContextOfStmt` which will never be called in DDL worker. So we can remove this line safely. …
> ddl: remove useless code in `adjustWorkerSize`

- pkg/ddl/table.go
- pkg/statistics/handle/ddl/ddl_test.go
Issue Number: close #53652
FK table forgets to send CreateTable event 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statstics,ddl: fix FK table forgets to send CreateTable event

- pkg/table/tables/BUILD.bazel
- pkg/table/tables/bench_test.go
- pkg/table/tables/cache.go
- pkg/table/tables/partition.go
- pkg/table/tables/tables.go
- pkg/table/tables/tables_test.go
Issue Number: close #53604 
`getCols` does duplicated calculation, which wastes CPU time.
Memoize this function.
Proportion of time in the microbenchmark of AddRecord (with pipelined DML and ART memdb)
Previous:
This PR:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: memoize TableCommon.getCols

- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/initstats/BUILD.bazel
- pkg/statistics/handle/initstats/load_stats_page.go
Issue Number: close #53564
it sometimes takes too much time for tidb to init stats. we should print the process info to tell the users.
Tests 
if we have several tables, it will print
```
[2024/05/27 18:21:39.093 +08:00] [INFO] [bootstrap.go:734] ["complete to load the histogram"] [category=stats]
[2024/05/27 18:21:39.094 +08:00] [INFO] [bootstrap.go:743] ["complete to load the topn"] [category=stats]
[2024/05/27 18:21:39.097 +08:00] [INFO] [bootstrap.go:755] ["complete to load the bucket"] [category=stats]
[2024/05/27 18:21:39.098 +08:00] [INFO] [domain.go:2318] ["init stats info time"] [lite=false] ["take time"=13.208834ms]
```
But if TiDB has enough tables, it will print.
```
...
[2024/05/27 19:54:10.516 +08:00] [INFO] [load_stats_page.go:83] ["load bucket …
```
> statistics: print the process of init stats

- pkg/planner/core/point_get_plan.go
Issue Number: close #43339. 
close #49803
Problem Summary: planner: fix DATA RACE caused by initializing PointGet stats
planner: fix DATA RACE caused by initializing PointGet stats
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix DATA RACE caused by initializing PointGet stats

- pkg/expression/builtin_math.go
- pkg/planner/core/plan_cache_test.go
Issue Number: close #53505
Problem Summary: expression: fix the wrong behavior of `conv` function
When evaluating `Constant`, should always use `Constant.EvalXXX()` instead of accessing `Constant.Value` directly, otherwise there might be wrong result if it's a parameter (`?`).
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: fix the wrong behavior of `conv` function

- pkg/statistics/handle/usage/BUILD.bazel
- pkg/statistics/handle/usage/predicate_column.go
- pkg/statistics/handle/usage/predicate_column_test.go
We need to clean up the outdated predicate columns that have been dropped from the schema.
Otherwise, we will attempt to analyze non-existent columns.
1. Added a test case to verify current behavior.
2. Added a new function to clean up the non-existent columns before we get the predicate columns.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: clean up dropped predicate columns stats usage

- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_utils.go
Issue Number: close #53687
Problem Summary: planner: bypass plan cache for cached PointGet plan
```
BenchmarkPreparedPointGet: 6450 ns/op --> 6250 ns/op
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: bypass plan cache for cached PointGet plan

- pkg/domain/domain.go
Issue Number: close #53667 
The DDL of 'admin repair table' works like this:
- create a list of tables been repairing
- ddl owner publish the ddl job
- ddl worker receive ddl job, execute onRepairTable function
- repairment done, update the table info, set the DDL state to public
- remove the table from repair table list
After we set the DDL state to public, and just before the table been removed from the list,
If we trigger a full reload of infoschema, we will goto this line:
https://github.com/pingcap/tidb/blob/22c41d0e0c86ddb98dd029d49a2df038d7ac42bf/pkg/domain/domain.go#L437-L440
And tidb will skip loading this table. (but the table is public, the repairment is done in fact)
In the past, the full reload in not triggered so the bug is not exposed.
After we adding …
> domain: fix unstable test TestRepairTable

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #53727
Related PR: https://github.com/tikv/client-go/pull/1358
Problem Summary: As title said.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix issue of concurrent close batch client panic

- pkg/expression/util.go
- tests/integrationtest/r/planner/core/integration.result
- tests/integrationtest/t/planner/core/integration.test
Issue Number: close #53580, close #53582, close #53603, close #53594
The following `ColumnSubstituteImpl` will fail if it returns `nil` for a function argument.
This PR makes the `ColumnSubstituteImpl` fail if the `NewFunction` returns an error. I traced back the change in `ColumnSubstituteImpl` function. Maybe the only reason why `NewFunctionInternal` is used here is that the developers were quite confident that it'll not return an error, and at that time the `ColumnSubstituteImpl` function didn't return the second value to indicate whether it successes or not.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-n …
> expression: fail `ColumnSubstituteImpl` if creating function returns error

- pkg/metrics/grafana/tidb.json
Issue Number: close #53748
Use log2 for y-axis of uptime.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> grafana: use log2 for y-axis of uptime

- lightning/pkg/importer/chunk_process.go
- lightning/pkg/importer/get_pre_info.go
- lightning/pkg/importer/table_import.go
- pkg/executor/load_data.go
- pkg/lightning/mydump/reader.go
Issue Number: ref #53587
Tests 
> 
check it works using a generated large dataset
Side effects
Documentation
```release-note
None
```
> lightning: turn off zstd decoding concurrency

- pkg/meta/meta.go
- pkg/meta/meta_test.go
Issue Number: close #53685 
Add a function named `GetDBMeta` to meta.go. This function will allow the caller to get all raw tableInfos of database.
Tests 
> 
Covered by the existing unit test cases. 
Side effects
Documentation
```release-note
None
```
> meta: Add a GetDBMeta function to meta.

- pkg/store/driver/txn/txn_driver.go
- pkg/store/driver/txn/unionstore_driver.go
Issue Number: close #53714
`GetMemBuffer` takes too much time.
Cache the result of `newMemBuffer`, instead of creating a new one each time when `GetMemBuffer` is called.
Tests 
> - Simple fix
> - Covered by many existing tests
> 
Side effects
Documentation
```release-note
None
```
> txn: save unnecessary calls to newMemBuffer

- pkg/ddl/ingest/backend.go
- tests/realtikvtest/addindextest4/ingest_test.go
Issue Number: close #53679
`ei.closedEngine` should be empty unless all data has been written and all writers have been closed.
Use correct `closedEngine`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix ingest job panic when reset engine failed

- DEPS.bzl
- go.mod
- go.sum
- pkg/lightning/backend/local/BUILD.bazel
- pkg/lightning/backend/local/checksum.go
Issue Number: ref #35319.
Adopt https://github.com/tikv/client-go/pull/1360.
Tests 
```release-note
None
```
> go.mod: update the clients to adopt the latest fix/optimization

- pkg/executor/executor.go
- pkg/planner/core/casetest/BUILD.bazel
- pkg/planner/core/casetest/integration_test.go
- pkg/planner/util/fixcontrol/get.go
Issue Number: ref #43817
Problem Summary: planner: introduce a new fix-control 43817 to control whether to allow the optimizer to evaluate non-correlated sub-queries in advance
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: introduce a new fix-control 43817 to control whether to allow the optimizer to evaluate non-correlated sub-queries in advance

- pkg/executor/test/admintest/admin_test.go
Issue Number: close #53802
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix data race in `TestAdminCheckGlobalIndexDuringDDL`

- pkg/domain/domain.go
Issue Number: ref #53744
Now, handleDDlEvent is put into the goroutine which also handles ```gcstats``` and other works. so it cannot handle ddl event as soon as possible. it will lead to the problem. for example, If we cannot handle the CreateTable event promptly, this table hasn't the stats.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: splite handleDDLEvent into new thread

- pkg/infoschema/tables.go
- pkg/infoschema/test/clustertablestest/tables_test.go
Issue Number: close #53026
Fix the issue the size is not defined for `tidb_trx` table.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue the size is not defined for `tidb_trx` table.
```
> infoschema: fix the issue txn state size is not defined

- WORKSPACE
Issue Number: close #53830
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade go1.21.11

- pkg/infoschema/infoschema_v2.go
- pkg/infoschema/test/infoschemav2test/v2_test.go
In the last step of infoschema.builder `Build()`, it calls `updateInfoSchemaBundles` and this need to call list tables API.
I test with 40w tables and that takes 15s
TiDB takes a long time to start partly due to this issue.
In this commit, I add placement policy to the special attributes and keep such tables in memory.
So we can repliace the list table API with `ListTablesWithSpecialAttribute` which is much faster.
After the change, build bundle for 40w tables takes 14us.
Tests 
> 
Side effects
Documentation …
> infoschema: make build bundle faster for infoschema v2

- pkg/executor/distsql.go
- tests/realtikvtest/sessiontest/paging_test.go
Issue Number: close #53827
Problem Summary: As title said, see more detail in issue #53827.
Set index lookup scan index cop request `min_page_size` to `initBatchSize`.
- prepare
```sql
drop table if exists t;
create table t (id int key auto_increment, b int, c int, index idx (b));
insert into t () values (), (), (), (), (), (), (), ();
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
update t set b = id, c = id;
```
- bench index lookup query with 1 thread by [loadgen](https://github.com/crazycs520/loadgen)
```sh
loadgen bench --sql="select * from t use index(idx);" --thread=1 --host 0.0.0.0 …
```
> executor: fix issue of index lookup query scan index  may sent redundancy RPC when enable paging

- pkg/ddl/job_table.go
Issue Number: close #53808
When TiDB is just elected as the DDL owner and `startDispatchLoop` is not started, there maybe a "context canceled" error when  owner retired for some reasons(like PD connection issue):
```
[2024/06/03 12:42:37.820 +08:00] [INFO] [manager.go:232] ["retire owner"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager 4e189321-5fd4-48fa-ad33-a8a92ed10cef"]
[2024/06/03 12:42:37.820 +08:00] [INFO] [syncer.go:485] ["schema version sync loop interrupted, retrying..."] [category=ddl]
[2024/06/03 12:42:37.820 +08:00] [WARN] [job_table.go:424] ["get global state failed"] [category=ddl] [error="context canceled"]
[2024/06/03 12:42:37.820 +08:00] [FATAL] [job_table.go:366] ["dispatch loop get cluster state failed, it should not happen, please try restart …
```
> ddl: handle cluster state retrieval failure

- pkg/executor/sortexec/parallel_sort_spill_helper.go
Issue Number: close https://github.com/pingcap/tidb/issues/53861
we get a profiler while we benchmark sync load. it takes too much time on the newParallelSortSpillHelper. it is unnecessary.
https://flamegraph.com/share/4dca9137-2419-11ef-ab1b-b6898751f631
Tests 
after optimization
t takes less time on the newParallelSortSpillHelper
https://flamegraph.com/share/822c3df8-247d-11ef-ab1b-b6898751f631
> 
Side effects
Documentation
```release-note
None
```
> executor: reuse memory for parallelSortSpillHelper

- pkg/ddl/backfilling_operators.go
- pkg/ddl/ingest/env.go
- tests/realtikvtest/addindextest3/BUILD.bazel
- tests/realtikvtest/addindextest3/functional_test.go
Issue Number: close #53791
We should always handle `createWorker` error, because if some index workers cannot start, there may be a data inconsistency issue.
Handle create writer error for index ingest operator.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: handle create writer error for index ingest operator

- pkg/planner/core/common_plans.go
- pkg/planner/core/planbuilder.go
Issue Number: close #53896
remove useless strings.ToLower in the (*Explain).RenderResult. although it is very small. it still can be found in the pprof.
https://flamegraph.com/share/ce8f8cd2-2654-11ef-aba3-6a3d1814cbe4
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove useless string.ToLower in the Explain

- pkg/ddl/cancel_test.go
- pkg/ddl/job_table.go
- pkg/ddl/tests/adminpause/BUILD.bazel
- pkg/ddl/tests/adminpause/pause_cancel_test.go
- pkg/ddl/testutil/testutil.go
- pkg/testkit/testfailpoint/failpoint.go
Issue Number: close #36582
ref #53246 
- see https://github.com/pingcap/tidb/issues/36582#issuecomment-2148790415 for the cause of flaky
- when we failed to get job in delivery2Worker, job variable is nil, it cannot be accecssed, it's introduced in this pr https://github.com/pingcap/tidb/pull/53747
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix flaky test TestCancel & fix panic when we failed to get job in delivery2Worker

- pkg/planner/core/casetest/hint/BUILD.bazel
- pkg/planner/core/casetest/hint/hint_test.go
- pkg/planner/core/casetest/hint/testdata/integration_suite_out.json
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- pkg/util/hint/hint_query_block.go
- tests/integrationtest/r/index_merge.result
Issue Number: close #53767
QBHintHandler may produce duplicate hints. When it reaches the match stage, the first one will be marked as a hint, but the second one will be ignored, ultimately resulting in incorrect warning messages.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> hint: avoid duplicate hints in QBHintHandler

- pkg/planner/core/planbuilder.go
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
Issue Number: close #53905
no need to convert the database names to lowercase in the analyze process. it takes some time on it.
https://flamegraph.com/share/28183024-2742-11ef-ab1b-b6898751f631
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: not convert the database names to lowercase duration the auto analyze

- br/pkg/streamhelper/BUILD.bazel
- br/pkg/streamhelper/advancer.go
- br/pkg/streamhelper/advancer_env.go
- br/pkg/streamhelper/advancer_test.go
- br/pkg/streamhelper/basic_lib_for_test.go
Issue Number: close #53561
Now, advancer will sync checkpoint with pd when adding a new task
Tests 
> 
Side effects
Documentation
```release-note
Fix Log Backup unexpected paused when adding a long-run task
```
> br: fix Log Backup unexpected paused when adding a already long-running task

- pkg/sessionctx/variable/sysvar.go
Issue Number: close #53919
Tests 
> 
Side effects
Documentation
```release-note
None
```
> sessionctx: add warning for system variable `tidb_enable_parallel_hashagg_spill`

- DEPS.bzl
- go.mod
- go.sum
- store/copr/batch_coprocessor_test.go
Issue Number: close #46602
Problem Summary: `GetTiFlashStores` exported by client-go would return unresolved stores, which causes mpp probe keep checking tomebstone stores.
Bump client-go so that `GetTiFlashStores` only returns resolved stores.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that tidb keeps sending probe requests to tomebstone tiflash stores.
```
> *: bump client-go to fix #46602

- pkg/infoschema/test/clustertablestest/tables_test.go
Issue Number: close #53901
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestTiDBTrx

- br/pkg/task/backup_ebs.go
Issue Number: close #53784 
If the cluster has 0 tikv replica, we should fail the backup directly.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ebs br: fail backup when no tikv store

- pkg/ddl/job_table.go
- pkg/ddl/job_table_test.go
- pkg/executor/ddl.go
- pkg/planner/core/preprocess.go
- pkg/sessionctx/variable/session.go
Issue Number: ref #53246
- DDL shouldn't lock MDL, there is only 1 DDL which locks MDL now: `create view as select xx`, create table also has for syntax for `as select`, but it's not implemented.
- after https://github.com/pingcap/tidb/pull/53747, general ddl worker will be held until the job enters final state, for a sequence of general DDLs of `1. alter table a add column xxx; 2. create view v as select * from a`, they will block each other if we don't clear the MDL. also see https://github.com/pingcap/tidb/pull/53747#discussion_r1625797789
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.htm …
> ddl: clear MDL related tables for create view

- pkg/ddl/partition.go
- pkg/ddl/reorg_partition_test.go
- pkg/ddl/tests/partition/db_partition_test.go
- pkg/table/tables/tables.go
- tests/integrationtest/r/ddl/db_partition.result
- tests/integrationtest/t/ddl/db_partition.test
When EXCHANGE PARTITION is used, the _tidb_rowid from the exchanged table, may conflict with rows in other partitions, which can collide during REORGANIZE PARTITION or REMOVE PARTITIONING since they keep the _tidb_rowid but will be placed in the same physical partition/table.
Solution:
Generate new _tidb_rowid for each row during the data reorganization phase.
Issue Number: close #53385
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: Regenerating AutoIDs for _tidb_rowid during Reorganize Partition

- pkg/types/datum.go
Issue Number: close #53942
`RuneCountInString` can be unexpectedly time-consuming for certain workloads. Since the number of runes must be smaller than or equal to the length of the string, we can fast check the length first. Only calculate the number of runes when necessary.
Before:
```
go test -run=^$ -bench=BenchmarkInsertIntoSelect -benchmem -benchtime=100x
100	 136332696 ns/op	106229159 B/op	  507278 allocs/op
```
This PR:
```
go test -run=^$ -bench=BenchmarkInsertIntoSelect -benchmem -benchtime=100x
100	 123812334 ns/op	106041608 B/op	  506652 allocs/op
```
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release- …
> datum: check len(s) before calculating and checking runeCount

- pkg/statistics/handle/cache/internal/lfu/BUILD.bazel
- pkg/statistics/handle/cache/internal/lfu/lfu_cache.go
- pkg/statistics/handle/cache/internal/lfu/lfu_cache_test.go
Issue Number: close #53742
ristretto will evict the data when inserting data. If LFU meets high-update scenes, it cannot evict. so we need to write some entry value to trigger the value.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: updating stats cache can trigger evict

- pkg/statistics/handle/globalstats/global_stats.go
- pkg/statistics/handle/util/util.go
Issue Number: close https://github.com/pingcap/tidb/issues/53972
We need to always update these vars for internal sessions. Otherwise, it won't work. And we will use the wrong default value.
See more at the issue.
Tests 
> 
Side effects
Documentation
```release-note
修复 tidb_enable_async_merge_global_stats 和 tidb_analyze_partition_concurrency 在自动分析无法生效的问题
Fix tidb_enable_async_merge_global_stats and tidb_analyze_partition_concurrency not working in auto-analysis
```
> statistics: update some vars for internal sessions correctly

- pkg/executor/internal/exec/executor.go
Issue Number: close #54001
Problem Summary:  avoid use fmt.Sprintf.
Sysbench oltp_point_select:
|         | thread | QPS |
|---------|--------|-----|
| Before  | 200    | 72211  |
| This PR | 200    | 72616 |
QPS improve 0.56%.
Before: 
This PR:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: avoid use fmt.Sprintf

- pkg/executor/union_scan_test.go
- pkg/planner/core/rule_predicate_push_down.go
- tests/integrationtest/r/explain_generate_column_substitute.result
Issue Number: close #53951
Problem Summary: planner: prevent pushing Projection with virtual columns down to UnionScan
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: prevent pushing Projection with virtual columns down to UnionScan

- pkg/infoschema/infoschema.go
Issue Number: close #54021
(*infoSchema).SchemaTables take too many time on growslics
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: avoid growslices in the infoSchema.SchemaTables

- pkg/bindinfo/global_handle_test.go
- pkg/expression/util.go
- pkg/planner/core/casetest/index/BUILD.bazel
- pkg/planner/core/casetest/index/index_test.go
- pkg/planner/core/casetest/index/main_test.go
- pkg/planner/core/casetest/index/testdata/index_range_in.json
- pkg/planner/core/casetest/index/testdata/index_range_out.json
- pkg/planner/core/casetest/partition/testdata/partition_pruner_out.json
- pkg/util/ranger/detacher.go
- pkg/util/ranger/types.go
- tests/integrationtest/r/util/ranger.result
Issue Number: Ref #41598
Index range extraction in the optimizer can handle disjunctions like 
((a = 1 and b = 2 and c > 3) or (a = 4 and b = 5 and c > 6)) and builds the proper index range like "(1 2 3,1 2 +inf], (4 5 6,4 5 +inf]" for this example. The problem is that when we add another conjunct like d > 3 then the optimizer takes another path which find only the point ranges "[1,1], [4,4]" in this example. Finding point ranges is OK for complex CNF where we only pick ranges from only one conjunct, But, in this case, the best conjunct is also better than point ranges. 
We added code that picks the best conjunct ranges if it is more selective than the point ranges. For example, "(1 2 3,1 2 +inf], (4 5 6,4 5 +inf]" is more selective than "[1,1], [4,4]" . We implemented that by checking if …
> Optimizer: Fix range extraction for CNF(conjunctive normal form) | tidb-test=pr/2341

- pkg/planner/core/preprocess.go
- tests/integrationtest/r/ddl/column.result
- tests/integrationtest/t/ddl/column.test
Issue Number: close #53779
See #53779.
Handle `Decimal(0)` properly in preprocessing.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: set proper default flen of decimal(0) columns

- pkg/ddl/backfilling_dist_executor.go
- pkg/ddl/backfilling_dist_scheduler.go
- pkg/ddl/backfilling_import_cloud.go
- pkg/ddl/backfilling_read_index.go
- tests/realtikvtest/addindextest2/global_sort_test.go
Issue Number: ref #53677
This is a follow-up of PR https://github.com/pingcap/tidb/pull/53632 to resolve a TODO. Before this PR, we don't know which index does a ingest subtask belong, so we can't generate the index name of "duplicate entry" error.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: record the used indexID for global-sort reorg

- pkg/planner/core/find_best_task.go
- tests/integrationtest/r/executor/sample.result
- tests/integrationtest/t/executor/sample.test
Issue Number: close #54015
`TABLESAMPLE REGIONS()` should be only valid in table scan.
Skip index scan plan for `TABLESAMPLE`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: skip index scan plan for tablesample

- br/pkg/backup/BUILD.bazel
- br/pkg/backup/client.go
- br/pkg/backup/client_test.go
- br/pkg/backup/store.go
Issue Number: ref https://github.com/pingcap/tidb/issues/52534
close https://github.com/pingcap/tidb/issues/53926
The previous implementation of `storewatch` has the wrong beginning state. we must take the first step before the tick starts. Then the `WithOnNewStoreRegistered` will have the correct `lastStore` states to make computing results correct.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> backup: fix the missing first store state during backup

- pkg/privilege/privileges/privileges.go
- pkg/server/conn.go
- pkg/server/mock_conn.go
- pkg/server/tests/commontest/tidb_test.go
- pkg/server/tests/servertestkit/testkit.go
Issue Number: close #54031
Tests 
1. my os user is `wangchao`
```
$ whoami
wangchao
```
2. create users:
```mysql
> CREATE USER 'u1'@'localhost' IDENTIFIED WITH auth_socket;
Query OK, 0 rows affected
Time: 0.017s
> CREATE USER 'u2'@'localhost' IDENTIFIED WITH auth_socket AS "wangchao";
Query OK, 0 rows affected
Time: 0.012s
> CREATE USER 'wangchao'@'localhost' IDENTIFIED WITH auth_socket;
Query OK, 0 rows affected
Time: 0.025s
TiDB root@127.0.0.1:test> select host,user,authentication_string,plugin from mysql.user;
+-----------+----------+-----------------------+-----------------------+
| host      | user     | authentication_string | plugin                |
+-----------+----------+-----------------------+-----------------------+
| %         | root     | …
```
> privilege: fix `auth_socket` bug, should only allow os user name to login

- pkg/ddl/backfilling_test.go
- pkg/ddl/ddl.go
- pkg/ddl/index.go
- pkg/ddl/ingest/BUILD.bazel
- pkg/ddl/ingest/backend_mgr.go
- pkg/ddl/ingest/env.go
- pkg/ddl/ingest/env_test.go
- pkg/ddl/ingest/integration_test.go
- pkg/ddl/ingest/message.go
- pkg/ddl/ingest/mock.go
- pkg/ddl/job_table.go
- tests/realtikvtest/addindextest/BUILD.bazel
- tests/realtikvtest/addindextest/add_index_test.go
Issue Number: close #54007
Clean ingest temp data dir in background loop
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: clean ingest temp data dir in background loop

- pkg/planner/core/logical_plan_builder.go
Issue Number: ref #38911 
To prune columns, we should use logical outputs instead of physical outputs to record the position information of each table to be deleted.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use logical output cols to record positions of tables to be deleted

- pkg/planner/core/plan_cache_lru.go
- pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: refactor a few code of plan cache
no logical change, only refactor
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor a few code of plan cache

- pkg/bindinfo/session_handle_test.go
- pkg/planner/optimize.go
- pkg/util/hint/hint.go
- pkg/util/hint/hint_processor.go
Issue Number: close #53834
Problem Summary: planner: fix the issue that bindings with query-level hint can not take effect for replace statements
planner: fix the issue that bindings with query-level hint can not take effect for replace statements
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that bindings with query-level hint can not take effect for replace statements

- pkg/statistics/handle/handle_hist.go
- pkg/statistics/handle/storage/read.go
- tests/realtikvtest/statisticstest/BUILD.bazel
- tests/realtikvtest/statisticstest/statistics_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/54022
See more at the issue. 
A quick summary:
If you have `tidb_opt_objective='determine'` enabled, it will trigger some async stats load for some tables. If there tables histogram isn't in the system, it would cause some problems when we try to load it.
Check that the index statistics are really needed before loading them.
If we don't check it here, it will cause some problems if the index statistics don't exist.
**Note:** We still don't know why the histogram record for the index is missing. There are some possible issues:
1. When users create this table, they may not have created this index yet, so we don't create the record for it automatically. (But if this is the case, I don't why do we have the index in …
> statistics: do not load unnecessary index statistics

- br/pkg/restore/import_retry_test.go
- br/pkg/utils/backoff.go
Issue Number: close https://github.com/pingcap/tidb/issues/54053
Backoffer can't recognize multierrs, therefore it would stop retry for recursive retry calling
Enable backoffer to recognize the multierr, and it will only check the last err returned
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix backoffer can't handle multierrs

- pkg/executor/builder.go
- pkg/executor/delete.go
- pkg/executor/distsql.go
- pkg/executor/index_merge_reader.go
- pkg/executor/partition_table_test.go
- pkg/expression/explain.go
- pkg/parser/model/model.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/plan_to_pb.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_partition_processor.go
- pkg/store/mockstore/unistore/cophandler/closure_exec.go
- pkg/store/mockstore/unistore/cophandler/mpp.go
- pkg/store/mockstore/unistore/cophandler/mpp_exec.go
- tests/integrationtest/r/globalindex/aggregate.result
- tests/integrationtest/r/globalindex/expression_index.result
- tests/integrationtest/r/globalindex/index_join.result
- tests/integrationtest/r/globalindex/mem_index_lookup.result
- tests/integrationtest/r/globalindex/mem_index_merge.result
- tests/integrationtest/r/globalindex/mem_index_reader.result
- tests/integrationtest/r/globalindex/misc.result
- tests/integrationtest/t/globalindex/aggregate.test
- tests/integrationtest/t/globalindex/expression_index.test
- tests/integrationtest/t/globalindex/index_join.test
- tests/integrationtest/t/globalindex/mem_index_lookup.test
- tests/integrationtest/t/globalindex/mem_index_merge.test
- tests/integrationtest/t/globalindex/mem_index_reader.test
- tests/integrationtest/t/globalindex/misc.test
Issue Number: close #53929 
The problem is we added `ExtraPhysTblID` to DataSource's schema for get the partition id. But it returns table id instead of partition id when using `indexReader` executor working with global index, because we decode index key to get it. After deep into the code, I found it's hard to fix it elegantly. In logical plan builder phase, we can't determined it will select a global index path or not which means we can't add`ExtraPidColID` column into `DataSource` in this phase.
Then I think maybe we could combine two columns, let it gets return values from different place(Seems `ExtraPhysTblID` is useless for global index, always return table ID for every records). When it is a global index, we could decode pid by index value, otherwise we could …
> *: remove `ExtraPidCol` and replace it with `ExtraPhysTblIDCol`

- pkg/bindinfo/session_handle_test.go
- pkg/session/test/session_test.go
- pkg/util/hint/hint_processor.go
Issue Number: close #53834
Problem Summary: planner: fix the issue that statement-level hints in sub-queries of Insert/Replace can not take effect
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that statement-level hints in sub-queries of Insert/Replace can not take effect

- pkg/executor/delete.go
- pkg/executor/insert_common.go
- pkg/executor/update.go
Issue Number: ref #53973
In certain workloads, frequent `tracker.Consume` impacts latency. 
An example update benchmark with pipelined DML.
Batch some `tracker.Consume` in the write path.
Tests 
> simple refactoring
Side effects
Documentation
```release-note
None
```
> *: batch frequent tracker.Consume in the write path

- pkg/executor/delete.go
Issue Number: close #54080
(*DeleteExec).deleteSingleTableByChunk spend too much time on making slices
https://flamegraph.com/share/e51414c2-2d3a-11ef-aba3-6a3d1814cbe4
Tests 
https://flamegraph.com/share/c1ef40c6-2d78-11ef-aba3-6a3d1814cbe4
I find many ```runtime.memmove``` in the ```executor.(*DeleteExec).deleteOneRow```
. so I think that deleteOneRow has copied the ```slices```. so it cannot affect the result.
> 
Side effects
Documentation
```release-note
None
```
> executor: reuse memory in the deleteSingleTableByChunk

- pkg/store/mockstore/unistore/cophandler/cop_handler.go
Issue Number: close #54097
Tests 
we cannot see any syscall in the cophandler.buildDAG 
> 
Side effects
Documentation
```release-note
None
```
> unistore: use location cache to reduce the syscall

- pkg/sessionctx/variable/sysvar.go
Mark `tidb_enable_auto_analyze_priority_queue` is deprecated. We will always use it in the future because, compared to random selection, it is always better.
Tests 
> 
Side effects
Documentation
```release-note
将 tidb_enable_auto_analyze_priority_queue 标记为废弃。
Mark tidb_enable_auto_analyze_priority_queue as deprecated.
```
> sessionctx: mark tidb_enable_auto_analyze_priority_queue as deprecated

- pkg/domain/infosync/info.go
- pkg/domain/infosync/info_test.go
- pkg/store/gcworker/gc_worker.go
Issue Number: close #54068
Tests 
> 
Side effects
Documentation
```release-note
None
```
> gc: delete TiFlash placement rules in batch

- pkg/expression/scalar_function.go
- pkg/expression/util_test.go
- pkg/parser/types/field_type.go
- pkg/planner/core/issuetest/planner_issue_test.go
Issue Number: close #53726
when planer call ```RemoveUnnecessaryFirstRow```. it will check the expression between ```Agg``` and ```GroupBy```. but it doesn't check the return type. so it get wrong unnecessary ```FirstRow```.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: correct the erroneous scalar function equivalence check

- br/pkg/restore/snap_client/systable_restore_test.go
- pkg/planner/core/planbuilder.go
- pkg/planner/optimize.go
- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/sysvar_test.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: ref #53440
Add new global variable `tidb_resource_control_strict_mode`:
- If set to 'ON', use need to have `RESOURCE_GROUP_ADMIN` or `RESOURCE_GROUP_USER` privilege to execute `SET RESOURCE GROUP` or use hint `RESOURCE_GROUP()` to change current resource group.
- If set to 'OFF', the privilege is bypassed, all user can execute `SET RESOURCE GROUP` or use hint `RESOURCE_GROUP()`  as before.
For new cluster, the default value is 'ON', but for cluster upgraded from old version, the default value is 'OFF'.
Tests 
> 
Side effects
Documentation …
> variable: add system variable 'tidb_resource_control_strict_mode'

- pkg/planner/core/casetest/index/BUILD.bazel
- pkg/planner/core/casetest/index/index_test.go
- pkg/planner/core/casetest/index/testdata/integration_suite_in.json
- pkg/planner/core/casetest/index/testdata/integration_suite_out.json
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/partition_pruning_test.go
(x,y,z) op (a,b,c)
rewritten
(x op a) or (x = a and y op b) or (x = a and y = b and z op c)
The new rewriting method allows buildrange to handle range construction problems more conveniently.
Issue Number: close #41598
The old expression rewrite is rewritten row expression to if(x!=a, x> a, if(xxxx)). The range builder could not easy build and merge this kind of expr range.
The new expression rewritten to (x op a) or (x = a and y op b) or (x = a and y = b and z op c) . It will be rewritten as a DNF which is more conveniently for Range builder.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.ht …
> planner: change the rewrite rule of row expression

- br/pkg/version/version.go
- br/pkg/version/version_test.go
Issue Number: ref #52534
Due to https://github.com/tikv/tikv/issues/17168, the current tikv does not support backup with subranges very well. 
So we need a version checker in case of use store based backup running on old version of tikv.(There is no correctness issue, but the performance may not work as expected.)
Add a version check
Tests 
> 
Side effects
Documentation
```release-note
None
```
> backup: add version checker for store based backup

- pkg/metrics/grafana/tidb.json
- pkg/metrics/grafana/tidb_resource_control.json
- tools/dashboard-linter/main.go
Some panels cannot be displayed on clinic. 
Normally, labels like "tidb_cluster" will be replaced with "cluster_id"(done by clinic). For example,
Expression on `grafana/tidb.json`
```
sum(rate(tidb_ddl_add_index_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])) by (type)
```
will be replaced to another expression on grafana provided by clinic:
```
sum(rate(tidb_ddl_add_index_total{k8s_cluster="$k8s_cluster", cluster_id=~"$tidb_cluster", instance=~"$instance"}[2m])) by (type)
```
However, expressions like `tidb_cluster=\"$tidb_cluster.*\"` is not matched, note that there is a `.*` appended. As a result, they are not replaced and the panel shows nothing.
Unify the usages of `tidb_cluster`.
Tests 
```
histogram_quantile(0.999, …
```
> metrics: fix the issue where some grafana panels cannot be displayed

- pkg/expression/helper.go
- tests/integrationtest/r/executor/write.result
- tests/integrationtest/t/executor/write.test
Issue Number: close https://github.com/pingcap/tidb/issues/53746
When TiDB uses `current_date` as default value, "hour:minuate:second" is not truncated correctly. As a result, the queries with equal condition cannot match.
Truncate time part for `current_date`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: truncate time part for current_date columns

- pkg/ddl/db_change_failpoints_test.go
- pkg/ddl/ddl_api.go
- pkg/executor/ddl.go
Issue Number: close #54134, ref #53246
- fill correct involved schemainfo for 'flashback table' and 'flashback schema'. this issue is not exposed as before this pr, general DDL only have 1 worker, so the second flashback cannot be run, but after https://github.com/pingcap/tidb/pull/54041, general DDL can be run in parallel
Tests 
existing `TestParallelFlashbackTable` should cover the case, so will not add new one. by add some sleep to make sure those 2 sql run in parallel, the case will fail before this pr, but ok after
> 
Side effects
Documentation …
> ddl: fill correct involved schemainfo for 'flashback table' and 'flashback schema'

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #54159 
Tests 
Manually check the tiflash regression tests several times.
> 
Side effects
Documentation
```release-note
None
```
> *: Revert grpc version and client-go version

- pkg/ddl/ddl.go
- pkg/ddl/ddl_api.go
- pkg/ddl/ddl_running_jobs.go
- pkg/ddl/ddl_running_jobs_test.go
- pkg/ddl/foreign_key_test.go
- pkg/ddl/job_table.go
- pkg/ddl/multi_schema_change.go
- pkg/ddl/placement_policy_test.go
- pkg/ddl/placement_sql_test.go
- pkg/ddl/schematracker/checker.go
- pkg/ddl/schematracker/dm_tracker.go
- pkg/ddl/systable/manager_test.go
- pkg/executor/brie_utils.go
- pkg/parser/model/ddl.go
Issue Number: close https://github.com/pingcap/tidb/issues/52795, ref https://github.com/pingcap/tidb/issues/53246
a DDL job will modify and refer to multiple objects (database, table, placement policy, resource group). Treat it like the job will lock these objects, in exclusive or shared lock mode. If the job finished all locking, then it can run now. In other words, the job has no dependency on other running jobs. This PR implements this lock-like behaviour.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: support referring objects in runningJobs

- pkg/executor/sortexec/parallel_sort_worker.go
- pkg/executor/sortexec/sort.go
Issue Number: close #54070
From clinic we can see that tidb memory usage is larger than normal and most of memory are allocated in sort executor. So we suspect that it's too many allocations which caused the performance regression.
To verify our suspicion we check the cpu usage and find that most cpu are consumed by memory allocation in sort executor. Moreover, GC STW Duration is very high. So I think we can ensure that it's too memory allocation who causes the performance regression in benchbot.
In order to eliminate the memory re-allocation when slice expands, we set a large capacity when creating slices. However, It's a waste to reserving so many memory and wasted memory will be very large because tp sqls usually process few rows while sort executos will be created for …
> executor: remove redundant memory pre-allocations in parallel sort executor

- pkg/executor/BUILD.bazel
- pkg/executor/adapter.go
- pkg/executor/staticrecordset/BUILD.bazel
- pkg/executor/staticrecordset/integration_test.go
- pkg/executor/staticrecordset/recordset.go
- pkg/session/session.go
- pkg/util/sqlexec/restricted_sql_executor.go
Issue Number: close #54090
The original `recordSet` and `execStmtResult` are too complicated to implement the lazy cursor fetch feature. We do need a much simpler one: without explicit transaction, without metrics/summaries and only supports read-only statements.
This PR adds a method `Detach` to create a new record set from existing `recordSet` or `execStmtResult`. The new record set can run without depending on the session context.
However, currently the executor still cannot be detached, so this PR specially handled the `TableReaderExecutor` and left a `TODO` here.
Tests 
> 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html …
> executor, session: Add Detach() method to detach the record set

- pkg/executor/distsql.go
- pkg/executor/index_merge_reader.go
- pkg/executor/test/issuetest/executor_issue_test.go
Issue Number: close #54160
Problem Summary: as title said, see more info in issue #54160
Increate index merge read executor initial batch size.
This PR can reduce the CPU consumption and improve QPS of index-merge read queries with more than 1024 rows.
Tests 
1. prepare data:
```sql
drop table if exists t;
create table t (id int key auto_increment, b int, c int, index idx1 (b), index idx2(c));
insert into t () values (), (), (), (), (), (), (), ();
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from …
```
> executor: try to optimize index merge reader query may send too many cop task

- br/pkg/backup/BUILD.bazel
- br/pkg/backup/client.go
- br/pkg/backup/client_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/54139
sometimes cluster might have too many ddl jobs. backup should skip unnecessary scan of ddl jobs during the backup incremental ddls.
Use `GetLastHistoryDDLJobsIterator` instead of `GetAllDDLJobs`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> backup: use history iterator to scan ddl jobs

- pkg/statistics/handle/cache/stats_table_row_cache.go
- tests/integrationtest/r/globalindex/information_schema.result
- tests/integrationtest/t/globalindex/information_schema.test
Issue Number: close #54173
Tests 
> 
Side effects
Documentation
```release-note
None
```
> stats: fix `index_length` in information_schema

- pkg/ddl/backfilling_operators.go
- pkg/ddl/backfilling_read_index.go
- pkg/ddl/backfilling_scheduler.go
- pkg/ddl/ingest/backend.go
- pkg/ddl/ingest/checkpoint.go
- pkg/ddl/ingest/checkpoint_test.go
- pkg/ddl/ingest/engine_mgr.go
- pkg/ddl/ingest/mock.go
- tests/realtikvtest/addindextest1/BUILD.bazel
- tests/realtikvtest/addindextest1/disttask_test.go
- tests/realtikvtest/addindextest3/functional_test.go
Issue Number: close #54184
easier to let `Flush` do error convertion. In the old code we still missed some branches that convert lightning error to ErrKeyExists
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: refine `BackendCtx.Flush` to display Duplicate entry error

- br/pkg/backup/client_test.go
- br/pkg/utils/misc.go
Issue Number: ref https://github.com/pingcap/tidb/issues/52534
A store is `offline` in PD doesn't mean the store cannot serve. some region leader still in that store. so we cannot simple skip `offline` store during backup.
still backup up/offline store. only skip tombstone store.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> backup: use tombstone instead of offline during CheckStoreLiveness

- pkg/planner/core/logical_plan_builder.go
In the deleted codes, you can see that we append `EmptyName` into the names.
But 
The EmptyName will fail when we try to build the position reference information.
So the codes can be deleted.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove dead codes for buildDelete

- pkg/infoschema/tables.go
- pkg/util/stmtsummary/reader.go
- pkg/util/stmtsummary/v2/column.go
- pkg/util/stmtsummary/v2/record.go
- pkg/util/stmtsummary/v2/tests/table_test.go
Problem Summary: planner: rename column `LAST_PLAN_CACHE_UNQUALIFIED_REASON` to `PLAN_CACHE_UNQUALIFIED_LAST_REASON` in statement_summary
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: rename column `LAST_PLAN_CACHE_UNQUALIFIED_REASON` to `PLAN_CACHE_UNQUALIFIED_LAST_REASON` in statement_summary

- pkg/planner/core/plan_cache.go
- pkg/server/internal/testserverclient/BUILD.bazel
- pkg/server/internal/testserverclient/server_client.go
- pkg/server/tests/commontest/tidb_test.go
- pkg/server/tests/servertestkit/BUILD.bazel
- pkg/server/tests/servertestkit/testkit.go
Issue Number: close https://github.com/pingcap/tidb/issues/53634
Init SQLs：
```
CREATE TABLE stock ( a int NOT NULL, b char(30) NOT NULL,  c int, d char(64), PRIMARY KEY(a,b)) ;
insert into stock values(1, 'a', 11, 'x'), (2, 'b', 22, 'y');
alter table stock add column cct_1 int default 10;
alter table stock modify cct_1 json;
alter table stock add column adc_1 smallint;
```
* Step1. using conn1
prepare statements:
```
begin;
SELECT a, c, d from stock where (a, b) IN ((?, ?),(?, ?)) FOR UPDATE;
UPDATE stock SET c = ? WHERE a= ? AND b = 'a';
UPDATE stock SET c = ?, d = 'z' WHERE a= ? AND b = 'b';
commit;
```
run a statement:
`begin;`
* Step2. using conn2
do DDL:
```
alter table stock drop column cct_1;
```
* Step3. using conn1
When the DDL is in Write-Only state
exec …
> *: fix a bug that update statement uses point get and update plan with different tblInfo

- pkg/domain/domain.go
- pkg/planner/core/plan_cache_instance.go
- pkg/planner/core/plan_cache_instance_test.go
- pkg/session/session.go
- pkg/sessionctx/context.go
Problem Summary: planner: add InstacnePlanCache to Domain
planner: add InstacnePlanCache to Domain
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add InstacnePlanCache to Domain

- docs/design/2024-05-23-predicate-columns.md
- pkg/executor/set_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
We need to introduce a new global variable to control which columns we need to analyze during the auto-analyze and manual analyze.
Users can set this variable to ALL or PREDICATE to analyze all columns or only predicate columns. The default value will be PREDICATE after this feature is fully implemented.
- Added a new global variable called `tidb_analyze_column_options`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> sessionctx: add tidb_analyze_column_options global variable

- pkg/expression/constant_propagation.go
- pkg/expression/context/context.go
- pkg/expression/contextsession/sessionctx.go
- pkg/expression/contextstatic/exprctx.go
- pkg/expression/util.go
- pkg/planner/core/casetest/rule/BUILD.bazel
- pkg/planner/core/casetest/rule/main_test.go
- pkg/planner/core/casetest/rule/rule_predicate_pushdown_test.go
- pkg/planner/core/casetest/rule/testdata/predicate_pushdown_suite_in.json
- pkg/planner/core/casetest/rule/testdata/predicate_pushdown_suite_out.json
The constant propagated should consider the collation of mapped column.
For example, 
```
set collation = utf8_bin || set collation= utf8mb4_bin
where name='a' and length(name) = 1
```
The name = 'a' doesn't mean the all of column name data is 'a'. The 'a    ' also can match the name='a' condition.
The reason is that 'utf8_bin' and 'utf8mb4_bin' are 'PAD SPACE' collation which means that it will ignore the trailing spaces.
**This kind of constant couldn't be propagated to 'Length' function. **
So I changed the columnSubstitute function to special due with 'length' function case.
Issue Number: close #53730
Tests 
> 
Side effects
Documentation …
> planner: The length function could not be substitute when collation of mapped column is utfxxx_bin

- OWNERS_ALIASES
Issue Number: ref #46911
Reverts pingcap/tidb#54174
Although the code owners of a directory do not conflict with the community member mechanism of the repository, the exit mechanism of the code owners of the directory still needs to be determined(ref: https://internals.tidb.io/t/topic/877
).
Only the repository "/OWNERS" file will be synchronized with the member list in [pingcap/community](https://github.com/pingcap/community), in which members can participate in the review of the entire repository. However, for subdirectories configured with the "OWNERS" file, the code owners of the directory are needed to determine whether they can be merged.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes …
> *: update prow OWNERS_ALIASES file

- pkg/server/internal/testserverclient/server_client.go
- pkg/server/tests/commontest/tidb_test.go
Issue Number: close #54254 #48457
Problem Summary: add test for issue #54254 and it has been fixed by pr #54183
PR #54183 also fix the issue #54254, and I've verified and add a test `TestIssue54254`  for it.
Without the fix in PR #54183, the test `TestIssue54254` will failed and has the same panic stack, such as following:
```log
[2024/06/28 14:06:22.604 +08:00] [ERROR] [conn.go:1024] ["connection running loop panic"] [conn=2097158] [session_alias=] [lastSQL="UPDATE stock SET c = ? WHERE a= ? AND b = 'a' [arguments: (101, 1)]"] [err="runtime error: index out of range [4] with length 4"] [stack="github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1
/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:1027
runtime.gopanic
/usr/local/go/src/runtime/panic.go:914 …
```
> *: add test for issue #54254 and it has been fixed by pr #54183

- pkg/sessionctx/variable/session.go
- pkg/util/redact/BUILD.bazel
- pkg/util/redact/redact.go
Issue Number: close #54190 , close #52743 , close #53264
The internal session does not init `EnableRedactLog` which cause `redact.String` always returns empty string.
Init it as an default value in this PR.
Tests 
```
set @@tidb_slow_log_threshold=0;
```
And check the output slow logs. No empty strings again.
> 
Side effects
Documentation
```release-note
fix empty SQL in slow log for internal statement
```
> *: fix empty SQL in slow log for internal statement

- pkg/executor/test/analyzetest/analyze_test.go
- pkg/planner/core/planbuilder.go
- pkg/statistics/handle/autoanalyze/BUILD.bazel
- pkg/statistics/handle/autoanalyze/autoanalyze_test.go
- pkg/statistics/handle/updatetest/update_test.go
- pkg/statistics/handle/usage/BUILD.bazel
- pkg/statistics/handle/usage/predicate_column_test.go
This PR is based on https://github.com/pingcap/tidb/pull/54200.
When `tidb_analyze_column_options` is set to `PREDICATE`, we should only analyze predicate columns.
- Checked `tidb_analyze_default_column_choice` when building the analyze plan.
- Only analyze indexes and the columns composing the indexes if there are no predicate columns.
- Added some tests to cover the analyze plan building code.
- Removed all use of `tidb_enable_column_tracking`.
Tests 
> 
Side effects
Documentation …
> planner: respect `tidb_analyze_column_options ` when build analyze plan

- pkg/table/context/table.go
Issue Number: ref #53837
`Value` method in `table.MutateContext` is useless after #53832. Just remove it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: remove useless method `MutateContext.Value`

- planner/core/logical_plan_builder.go
- planner/core/plan_cache_test.go
- types/parser_driver/value_expr.go
Issue Number: close #53872
Problem Summary: planner: fix the issue that cannot find column if using question marker in group-by-clause
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue that cannot find column if using question marker in group-by-clause

- executor/distsql.go
- executor/join.go
- util/chunk/list.go
- util/chunk/row_container.go
- util/memory/tracker.go
close pingcap/tidb#54005
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: support memTracker.detach for HashJoin, Apply and IndexLookUp in Close func (#54095)

- statistics/handle/handle_hist.go
- statistics/handle/handle_hist_test.go
close pingcap/tidb#52657
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add upper bound of retry for sync load

- pkg/executor/sortexec/BUILD.bazel
- pkg/executor/sortexec/topn.go
- pkg/executor/sortexec/topn_spill_test.go
Issue Number: close #54206
Tests 
> 
Side effects
Documentation
```release-note
fix panic in TopN when system variable tidb_enable_tmp_storage_on_oom is disabled
```
> executor: fix panic in `TopN` when system variable `tidb_enable_tmp_storage_on_oom` is disabled

- statistics/handle/bootstrap.go
- statistics/handle/handle_test.go
Issue Number: ref https://github.com/pingcap/tidb/pull/53710
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix wrong behavior for primary key' non-lite init stats 

- pkg/executor/slow_query.go
- pkg/executor/slow_query_test.go
Issue Number: close #54324
The old code does not handle all the cases well.
`if i >= len(lines)-1` should be a typo, it should be something like `if i >= len(chars)-1`
And the simplified logic is just the same as this PR.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix query panic on INFORMATION_SCHEMA.CLUSTER_SLOW_QUERY with some slow query files

- pkg/expression/column.go
- pkg/expression/column_test.go
- pkg/expression/constant.go
- pkg/expression/expression.go
- pkg/expression/expression_test.go
- pkg/expression/scalar_function_test.go
- pkg/planner/core/scalar_subq_expression.go
Issue Number: close https://github.com/pingcap/tidb/issues/53840
The `MarshalJSON` function of `Expression` interface is not used in TiDB. This PR tried to remove it.
1. Remove the `MarshalJSON` method for `Expression` and its implementations.
I've checked through some static analyze + manually analyze in https://github.com/pingcap/tidb/pull/53841. The `MarshalJSON` method is not used in tidb. Blaming the code shows that it's originally introduced in https://github.com/pingcap/tidb/pull/1632, and it's not used anymore.
(The linter in #53841 cannot be used, because it'll report every use-case of `json.Marshal` on an interface which didn't implement `json.Marshal`. It's not possible to actually statically analyze this case.)
We cannot give a proper implementation for …
> expression: remove unused MarshalJSON function in Expression

- br/pkg/storage/s3.go
Issue Number: close https://github.com/pingcap/tidb/issues/45551
Fix the problem that BR only accept credentials from ISM service.
Now, if the BR can't get the ISM credentials, it will try to retrieve credentials from other sources.
And even if it got, it will still try to apply env provider and then shared provider first.
Tests 
> 
Protocol:
1. Set access-key and secret-access-key as my local machine environmental variable.
2. Try `br backup full` from a public address (my local machine) without ISM access-key.
3. Check if the full backup task finished and if the Aliyun OSS server received the backup files.
Result:
1. On my local machine:
```
./bin/br backup full     --pd "localhost:45129"     --storage …
```
> br: fix backup to aliyum OSS not support ak/sk as env

- DEPS.bzl
- go.mod
- go.sum
- pkg/server/internal/testserverclient/BUILD.bazel
- pkg/server/internal/testserverclient/server_client.go
- pkg/server/tests/cursor/BUILD.bazel
- pkg/server/tests/cursor/cursor_test.go
Issue Number: close #54286
I've extended the go mysql driver to support `fetchSize` argument (See the [commit](https://github.com/YangKeao/go-mysql-driver/commit/dd5589458cfa93737bab4038c769c3435053aa12)). Though it's not suitable to use it directly with `sql` standard library, we can use the function exposed by it directly to test TiDB now.
1. Fork a go mysql driver and support cursor fetch.
2. Add a test for cursor fetch function in TiDB with it.
Tests 
> 
```release-note
None
```
> test: use a mysql driver supporting cursor fetch to test the cursor fetch function

- docs/design/2023-09-12-grouping-sets.md
Issue Number: ref https://github.com/pingcap/tidb/issues/42631
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix grouping sets document typo

- pkg/testkit/testkit.go
Issue Number: close #54376
`rand.Rand` is not thread-safe.
Initialize the random number generator inside `RefreshSession()` is enough for reproducing.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix data race in RefreshSession

- pkg/executor/adapter.go
- pkg/sessionctx/variable/BUILD.bazel
- pkg/sessionctx/variable/session.go
- pkg/util/stmtsummary/BUILD.bazel
- pkg/util/stmtsummary/statement_summary.go
- pkg/util/stmtsummary/statement_summary_test.go
- pkg/util/stmtsummary/v2/BUILD.bazel
- pkg/util/stmtsummary/v2/record.go
- pkg/util/stmtsummary/v2/record_test.go
Issue Number: ref #54047
Problem Summary: Many memory allocations caused by `GetTextToLog` are unnecessary. Typically, we only need the sql text when: 1. record stmt summary for commit (which needs sql text of prev stmt) 2. new stmt record (when the LRU cache miss).
Evaluate sql text lazily. Refer to the following benchmark results of sysbench oltp point select.
https://clinic.pingcap.com.cn/portal/#/orgs/541/clusters/7381654358775158872?from=1718790105&to=1718790705
  | avg lat | p95 lat | throughput | througput diff
-- | -- | -- | -- | --
baseline | 1.52 | 3.02 | 65740.95 | -
this PR | 1.49 | 2.91 | 67045.73 | 1.98%
baseline
this PR
Tests 
> 
Side effects
Documentation …
> *: reduce mem allocs caused by GetTextToLog

- pkg/executor/analyze.go
- pkg/executor/analyze_col.go
- pkg/executor/show_stats_test.go
- pkg/executor/test/analyzetest/analyze_test.go
- pkg/statistics/handle/autoanalyze/autoanalyze_test.go
- pkg/statistics/handle/usage/predicate_column_test.go
- tests/integrationtest/r/executor/analyze.result
We display `job_info` in the `mysql.analyze_jobs` table. But we didn't include the indexes information in this column. We need to make it clearer after introducing the predicate columns feature because, by default, we only analyze the index if there are no predicate columns. 
- Removed the unused parameter and added more comments
- Distinguished between singular and plural.
- Included the indexes info.
Tests 
> 
Side effects
Documentation
```release-note
在 analyze_job 中显示分析了的 …
```
> planner: include both indexes and columns in job info

- pkg/table/context/BUILD.bazel
- pkg/table/context/buffers.go
- pkg/table/context/buffers_test.go
- pkg/table/context/table.go
- pkg/table/contextimpl/table.go
- pkg/table/tables/tables.go
Issue Number: ref #54392, ref #54397
This PR introduces a better way to manage buffers  in `AddRecord/UpdateRecord/DeleteRecord`. It renamed `TablesBuffer` to `MutateBuffers` and returns buffers by methods instead of accessing the inner object directly. `MutateBuffers` is defined as:
```go
type MutateBuffers struct {
addRecord    *AddRecordBuffer
update       *UpdateRecordBuffer
colSizeDelta *ColSizeDeltaBuffer
}
func NewMutateBuffers(stmtBufs *variable.WriteStmtBufs) *MutateBuffers {
return &MutateBuffers{
addRecord: &AddRecordBuffer{
encodeRowBuffer: encodeRowBuffer{
writeStmtBufs: stmtBufs,
},
},
updateRecord: &UpdateRecordBuffer{
encodeRowBuffer: encodeRowBuffer{
writeStmtBufs: stmtBufs,
},
},
colSizeDelta: &ColSizeDeltaBuffer{},
}
}
func (b *MutateBuffers) …
```
> table: Use `MutateBuffers` to manage buffers

- pkg/executor/builder.go
- pkg/executor/join/BUILD.bazel
- pkg/executor/join/base_join_probe.go
- pkg/executor/join/bench_test.go
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/hash_table_v2.go
- pkg/executor/join/hash_table_v2_test.go
- pkg/executor/join/inner_join_probe.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/join_row_table_test.go
- pkg/executor/join/left_outer_join_probe.go
- pkg/executor/join/row_table_builder_test.go
- pkg/executor/test/issuetest/executor_issue_test.go
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
- pkg/executor/test/seqtest/seq_executor_test.go
In #53208, it creates a lots of long-lived `unsafe.Pointer` during hash join's build, a simple performance test shows lots of `unsafe.Pointer` will significantly increases gc time:
gc with a lots of unsafe.Pointer
```
[gc_test]# cat pointer_gc.go 
package main
import "runtime"
import "time"
import "fmt"
import "unsafe"
func main() {
a := make([]byte, 1e9*8)
b := make([]unsafe.Pointer, 1e9)
for i := 0; i < 1e9; i++ {
b[i] = unsafe.Pointer(&a[i*8])
}
for i := 0; i < 1e9; i++ {
*(*int64)(b[i]) = int64(i)
}
for i := 0; i < 10; i++ {
start := time.Now()
runtime.GC()
fmt.Printf("GC took %s\n", time.Since(start))
}
for i := 0; i < 1e9; i++ {
if *(*int64)(b[i]) != int64(i) {
panic("test failed")
}
}
runtime.KeepAlive(a)
runtime.KeepAlive(b)
}
[gc_test]# …
```
> executor: Do not save long-lived unsafe.Pointer in hash join v2

- DEPS.bzl
- br/pkg/restore/split/client.go
- br/pkg/streamhelper/advancer_env.go
- br/tests/br_key_locked/codec.go
- go.mod
- go.sum
- pkg/store/mockstore/unistore/tikv/mock_region.go
Issue Number: close #54313 #54341
We have deprecated the `ScanRegion` and introduce `BatchScanRegions` as a replacement in v8.2. However, to keep compatibility(v8.2 br/lightning should work with previous TiDB clusters), the tools should keep using the old supported `ScanRegion`.
Tests 
> 
The integration test case which import into 8.1 tidb with this PR's lightning is passed.
Side effects
Documentation
```release-note
None
```
> br: revert new introduced `BatchScanRegions` to keep compatibility

- tools/check/ut.go
Issue Number: Ref #30822
We can list pkg concurrently to accelerate build
check result
```bash
go clean -testcache
make gotest_in_verify_ci
```
before
```
building task finish, parallelism=144, count=5297, takes=2m5.029385545s
```
after
```bash
building task finish, parallelism=144, count=5297, takes=1m16.911219387s
```
Tests 
```release-note
None
```
> tools/ut.go: add concurrent when listing pkgs

- lightning/pkg/importer/import.go
- lightning/pkg/server/lightning.go
- pkg/lightning/common/util.go
Issue Number: close #54232
Problem Summary: When the keyspace-name is empty (default), and the user connecting to downstream TiDB is not a superuser, there will be a confusing "access denied" warning requesting CONFIG privilege. This confuses users to think that this privilege is actually required.
Just reduce the log level to DEBUG.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: reduce the "unable to get keyspace name" log level to DEBUG

- pkg/ddl/callback.go
- pkg/ddl/column.go
- pkg/ddl/ddl_running_jobs.go
- pkg/ddl/ddl_worker_test.go
- pkg/ddl/job_table.go
- pkg/ddl/job_table_test.go
- pkg/ddl/tests/adminpause/BUILD.bazel
- pkg/ddl/tests/adminpause/pause_resume_test.go
- pkg/ddl/util/callback/callback.go
Issue Number: close #54383, ref #53246
|    | session 1                   | session 2                                       | session 3                    |
|----|-----------------------------|-------------------------------------------------|------------------------------|
| t1 | create table t (a int);  OK |                                                 |                              |
| t2 |                             | alter table t modify column a tinyint; -- job 1 |                              |
| t3 | admin pause ddl jobs 1;  OK | Paused                                          |                              |
| t4 |                             | Paused                                          | alter table t add column c int; |
|    | …
> ddl: consider paused job when check runnable

- pkg/domain/domain.go
- pkg/domain/resourcegroup/runaway.go
- pkg/domain/runaway.go
- pkg/executor/adapter.go
Fix some typos and refine the runaway-related code.
Tests 
```release-note
None
```
> domain: refine the runaway code and fix typos

- pkg/executor/builder.go
- pkg/executor/index_merge_reader.go
- pkg/executor/table_reader.go
Issue Number: close #54446
There is a hidden session context inside `kvRangeBuilder`. I didn't found it when I was doing refactoring on the `TableReaderExecutor` :facepalm: . Now, it's removed.
1. Remove the session context inside the `kvRangeBuilder` implementation.
2. Add the `DistSQLContext` argument to all methods of `kvRangeBuilder`.
Tests 
> No logic change. It should be tested by existing tests.
> 
Side effects
Documentation
```release-note
None
```
> executor: remove the session context inside kvRangeBuilder

- pkg/ddl/tests/partition/db_partition_test.go
Issue Number: close #53725 
If infoschema v1->v2 switch happen, the infoschema full reload is triggered.
sleep(10ms) is not enough for the latest infoschema to be loaded.
So the test use the old schema and fail.
Tests 
(cd pkg/ddl/tests/partition/ ; go test -v -run TestTruncatePartitionWithGlobalIndex -tags=intest -count 1000 -failfast)
> 
Side effects
Documentation
```release-note
None
```
> ddl/tests/partition: fix an unstable test TestTruncatePartitionWithGlobalIndex

- pkg/infoschema/infoschema_v2.go
Issue Number: close #54423
Infoschema V2 *Data is a shared object, use sync.Map to replace builtin map to avoid data race.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: fix a data race on infoschema v2 addSpecialDB()

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref https://github.com/pingcap/tidb/issues/47421 ref https://github.com/tikv/pd/issues/8349
Tests 
> 
```release-note
None
```
> [cherry-pick] mod: update the pd client

- pkg/planner/core/base/plan_base.go
- pkg/planner/core/operator/baseimpl/plan.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_cache_test.go
- pkg/planner/core/plan_cache_utils.go
- pkg/planner/core/point_get_plan.go
- pkg/sessionctx/variable/session.go
Problem Summary: planner: consider using instance level plan cache 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: consider using instance level plan cache 

- br/pkg/errors/errors.go
- br/pkg/task/BUILD.bazel
- br/pkg/task/restore.go
- br/pkg/task/restore_test.go
- br/pkg/utils/backoff.go
Issue Number: close https://github.com/pingcap/tidb/issues/54316
Add a pre-check before the restore work, now the br will estimate the disk usage and check if each TiKV has enough disk space. User could disable this function by setting  `--check-requirements=false`
Tests 
> 
Side effects
Documentation
```release-note
Add a pre-check before the restore work, now the br will estimate the disk usage and check if each TiKV has enough disk space. User could disable this function by setting  `--check-requirements=false`
```
> br: pre-check TiKV disk space before restore task

- br/pkg/task/restore.go
- br/tests/br_incremental/run.sh
Issue Number: close https://github.com/pingcap/tidb/issues/54426
see https://github.com/pingcap/tidb/issues/54426#issuecomment-2208088735
make sure the rewritten data cover the backfilled data.
Tests 
> 
Side effects
Documentation
```release-note
fix the issue that backfill ddls(add index/modify column) may not restored correctly during incremental restore.
```
> Incremental restore: fix the issue that backfill data is not covered by newTS

- pkg/domain/resourcegroup/runaway.go
- pkg/executor/adapter.go
- pkg/sessionctx/variable/session.go
Use the `StartTime` in `SessionVars` to calculate the runaway deadline.
Tests 
```release-note
None
```
> session, executor, domain: use the SQL start time to calculate the runaway deadline

- pkg/ddl/callback.go
- pkg/ddl/cancel_test.go
- pkg/ddl/db_test.go
- pkg/ddl/ddl_api_test.go
- pkg/ddl/ddl_worker_test.go
- pkg/ddl/ddl_workerpool.go
- pkg/ddl/ddl_workerpool_test.go
- pkg/ddl/job_table.go
- pkg/ddl/job_table_test.go
- pkg/ddl/logutil/logutil.go
- pkg/ddl/table_test.go
- pkg/ddl/tests/adminpause/pause_resume_test.go
- pkg/ddl/util/callback/callback.go
- pkg/session/bootstraptest/bootstrap_upgrade_test.go
- pkg/statistics/handle/initstats/BUILD.bazel
- pkg/statistics/handle/initstats/load_stats_page.go
- pkg/statistics/handle/logutil/BUILD.bazel
- pkg/statistics/handle/logutil/logutil.go
- pkg/util/logutil/log.go
- pkg/util/logutil/log_test.go
- schedule as many jobs as possible in one round, simplify sql to query jobs
- replace 2 ddl test hook with failpoint
- rename methods
Tests 
before this pr: create 100K tables under same database on owner on 1pd/3tidb/3tikv using 10 threads, run 2 time, takes 31m16/29m5. avg cpu about [335, 400]
after: run 3 times, takes 32m8/22m56/25m29, avg cpu about [200, 280]. the test result is not stable as expected, seems there are other components interfering DDL process, will check it later. but overall it it's better, both in time and resource usage
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-no …
> ddl: schedule as many jobs as possible in one round, simplify sql to query jobs

- pkg/expression/builtin_cast.go
- pkg/expression/builtin_cast_vec.go
- tests/integrationtest/r/expression/json.result
- tests/integrationtest/t/expression/json.test
Issue Number: ref #54027, close #54494
When casting YEAR as JSON, the YEAR argument is not regarded as an unsigned value.
Regard the `YEAR` argument as an unsigned value, and give `unsigned integer` json type.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that the `json_type` of a json value converted from `YEAR` is not correct.
```
> expression: fix the type of casting YEAR as json

- pkg/executor/insert_common.go
- pkg/table/tables/tables.go
We move the TTL added row metric outside the `table` package to ensure the table mutation operation is simple.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: move add TTL insert rows metrics code out of table package

- pkg/executor/sortexec/sort.go
Issue Number: close #54006 
Tests 
> 
Side effects
Documentation
```release-note
fix unstable unit test `TestMergeJoinInDisk`
```
> executor: fix unstable unit test `TestMergeJoinInDisk`

- errors.toml
- pkg/errno/errcode.go
- pkg/errno/errname.go
- pkg/executor/simple.go
- pkg/infoschema/error.go
- tests/integrationtest/r/executor/simple.result
- tests/integrationtest/t/executor/simple.test
Issue Number: close #54417, ref #54434.
Check if a user is a role before assigning a resource group to it.
Tests 
```release-note
None
```
> executor/simple: prohibit setting a resource group to a role

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_cte.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_limit.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/rule_topn_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical cte logic into a separate file for later pkg move

- pkg/lightning/backend/kv/session.go
- pkg/session/bootstrap_test.go
- pkg/session/session.go
- pkg/table/context/buffers.go
- pkg/table/context/buffers_test.go
- pkg/table/context/table.go
- pkg/table/contextimpl/BUILD.bazel
- pkg/table/contextimpl/table.go
- pkg/table/contextimpl/table_test.go
- pkg/table/tables/BUILD.bazel
- pkg/table/tables/tables.go
- pkg/util/mock/context.go
Issue Number: ref #54392, ref #54397
- Add a new method `EncodeBinlogRowData` to `EncodeRowBuffer` to encode row data for binlog. And remove method `GetColDataBuffer` to ensure the inner slices are private. 
- Add `BinlogEnabled` and `GetBinlogMutation` to remove some references of `SessionVars` in `MutateContext`.
- Add some unit tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: provide some binlog related methods for binlog in `MutateContext`

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/logical_sequence.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
- pkg/planner/core/stats.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical sequence logic into a separate file for later pkg move.

- pkg/ddl/job_table.go
Issue Number: ref https://github.com/pingcap/tidb/issues/49752
- add retry for retryable error
- add id allocator to reduce write conflict
Tests 
> 
Side effects
Documentation
```release-note
None
```
> fast_create_table: add retry for local worker

- br/pkg/task/BUILD.bazel
- br/pkg/task/restore.go
- br/pkg/task/restore_test.go
- br/pkg/task/stream.go
- br/tests/br_incremental/run.sh
- br/tests/br_incremental_index/run.sh
- br/tests/br_mv_index/run.sh
- br/tests/br_pitr/run.sh
- pkg/ddl/backfilling.go
Issue Number: ref https://github.com/pingcap/tidb/issues/54474
1. current incremental backup is not compatible with log backup in one restore command. this pr try to make them compatible.
1. skip cluster empty check when restore incremental + log backup.
2. provide an option for restore command to skip rewrite timestamp with a limitation ddl support.(NOTICE: this option will make incremental restore do a strict check for ddls by default)
Tests 
> 
Side effects
In order to protect data not loss for later log restore, the new add option during incremental restore will perform a strict check for ddls by default. which means the restore could fail due to unsupported backfill ddl types appeared. such as Add Index/Modify …
> restore: make incremental restore and log restore compatible

- pkg/executor/importer/import.go
- pkg/executor/internal/exec/executor.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/session_test.go
- pkg/table/context/buffers.go
- pkg/table/context/buffers_test.go
- pkg/table/tables/tables.go
Issue Number: close #54392
The inner slices in `ColSizeDeltaBuffer` should not be accessed directly for safe. This PR makes inner slices in `ColSizeDeltaBuffer` private and exposes another method `UpdateColSizeMap` to update col size.
This PR also removes `UpdateDeltaForTableFromColSlice` and use a unique function `UpdateDeltaForTable` to update the table delta.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: make slices in `ColSizeDeltaBuffer` private

- pkg/ddl/callback.go
- pkg/ddl/ddl.go
- pkg/ddl/ddl_worker.go
- pkg/ddl/job_table.go
- pkg/ddl/schema_version.go
- pkg/ddl/tests/indexmerge/BUILD.bazel
- pkg/ddl/tests/indexmerge/merge_test.go
- pkg/domain/domain.go
- pkg/infoschema/builder.go
- pkg/infoschema/builder_misc.go
- pkg/infoschema/context/infoschema.go
- pkg/infoschema/infoschema.go
- in https://go-review.googlesource.com/c/go/+/471400, maps.Clone is optimized to clone underlying buckets, not iterating each item as before. our info schema load part is the perfect place for this
- remove the Reload inside OnChangedof DefaultCallback which is used in normal code path, we have already waited each instance to reload, no need to call it again, will remove it in later refactor. reload inside OnSchemaStateChanged is for test, but i don't see the need to do so, as we have waited schema change before this call, so remove it too. And as fast-create depends on reload after DDL execution, we add a reload for it separately
https://github.com/pingcap/tidb/blob/a4908820a38f6e893c1882fdcf2c3a6d56141dba/pkg/ddl/job_table.go#L625-L636
Tests …
> infoschema: use maps.Clone to replace iterating

- pkg/ddl/ingest/engine.go
Issue Number: close #54568
we should close writers first, otherwise it will send to closed channel
Tests 
> pass existing test
Side effects
Documentation
```release-note
None
```
> ddl/ingest: close writer before engine

- pkg/meta/meta.go
Start tidb with 1M tables, I found some unexpected memory usage.
That could be a leak.
When TiDB start up using infoschema v2, it builds the name-> id mapping by loading the meta data, and store the mapping in memory.
The map key (name) is a []byte slice taken from the original kvpair, and we use hack.String for optimization.
So the key references the original  kvrpcpb.Response causing the Go GC can't release it, result in a memory leak.
Tests 
Get the heap profile and compare them.
After this commit, the occpuation of kvrpcpb.XXX is gone:
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes …
> meta: fix memory leak when loading infoschema v2

- pkg/executor/slow_query.go
- pkg/executor/slow_query_test.go
- pkg/sessionctx/variable/session.go
Issue Number: close #54538
Replace regexp matching with simple string comparison operations. Besides, previously, ":=" inside "{}" are not handled correctly, fix it in this PR also.
In local mannual test, performance will improve about 10x, from 24s to 2.2s for the following sql:
```SELECT   Digest,   Query,   Conn_ID,   (UNIX_TIMESTAMP(Time) + 0E0) AS timestamp,   Query_time,   Mem_max,   Process_keys FROM   `INFORMATION_SCHEMA`.`CLUSTER_SLOW_QUERY` WHERE   Time BETWEEN FROM_UNIXTIME(1720471890)   AND FROM_UNIXTIME(1720515091) ORDER BY   Query_time DESC LIMIT   100;```
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/r …
> executor: Optimize slow log parsing's splitByColon function

- pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
- pkg/planner/core/explain.go
- tests/integrationtest/r/executor/jointest/join.result
- tests/integrationtest/r/executor/merge_join.result
…
Issue Number: close #54656
When to explain, The left condition uses [], while other conditions do not. From the code, it's evident that the left condition is handled with special code. This can be standardized.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: explanation of the left condition remains consistent with the others

- pkg/statistics/analyze.go
- pkg/statistics/handle/autoanalyze/BUILD.bazel
- pkg/statistics/handle/autoanalyze/autoanalyze_test.go
- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/cache/statscache.go
- pkg/statistics/table.go
It only occurs in the following situations:
1. The table has already been analyzed, but because the predicate columns feature is turned on, and it doesn't have any columns or indexes analyzed, it only analyzes _row_id and refreshes stats_meta, in which case the snapshot is not zero.
2. LastAnalyzeVersion is 0 because this are no histogram(buckets) records for this table at all.
So in this case, the auto-analyze will try to analyze it again and again.
If you find an actual case and attempt to compare the snapshot from stats_meta with the version from the histogram, you will always find that this equation is true.
```sql
+------------------+--------+------------+-----+------------------+
|version …
```
> statistics: init LastAnalyzeVersion with snapshot timestamp

- pkg/table/context/BUILD.bazel
- pkg/table/context/buffers.go
- pkg/table/context/buffers_test.go
- pkg/table/tables/tables.go
Issue Number: close #54392
The previous implementation of `CheckRowBuffer.GetRowToCheck` returns the inner slice which is not safe to use if the outside code keeps the code somewhere. This PR returns `chunk.Row` instead to make the inner slice not accessed by the out code, so it is safe to use.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: `CheckRowBuffer.GetRowToCheck` returns `chunk.Row` to protect inner slices

- pkg/ddl/tests/metadatalock/mdl_test.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_test.go
- pkg/planner/core/plan_cache_utils.go
- pkg/planner/core/tests/prepare/prepare_test.go
Issue Number: close #54652
Problem Summary: planner: fix the issue of reusing wrong point-plan for "select ... for update"
Encode more txn state into the plan cache key, and check whether the key has changed before reusing point-get plans.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the issue of reusing wrong point-plan for "select ... for update"

- pkg/executor/benchmark_test.go
- pkg/executor/builder.go
- pkg/executor/executor_required_rows_test.go
- pkg/executor/projection.go
Issue Number: close #54613
Similar to https://github.com/pingcap/tidb/pull/51397. This PR uses the `BaseExecutorV2` and removed the session context in the `ProjectionExec`.
1. Remove the `BaseExecutor` internal and replace it with `BaseExecutorV2`.
2. Add a new `projectionExecutorContext`, which includes all information needed by the projection executor.
Tests 
> No logic change. It shouldn't break existing tests.
> 
Side effects
Documentation
```release-note
None
```
> executor: refactor the `BaseExecutor` and remove session context in `ProjectionExec`

- pkg/executor/simple.go
- pkg/executor/test/simpletest/simple_test.go
- tests/integrationtest/r/privilege/privileges.result
Fixes the wrong user and host info when `SET PASSWORD FOR` fails with insufficient privilege to be consistent with MySQL behavior.
Issue Number: close #54039
When populating the error message when the current user lacks sufficient privileges for executing `SET PASSWORD FOR` for another user, the current code used the wrong user/host info in the error message.
Use the current session's user name/host in the error message.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue where incorrect user is populated in SET PASSWORD's error …
```
> executor: populate correct user in set pwd for error msg

- pkg/executor/join/BUILD.bazel
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/hash_table_v2_test.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/row_table_builder_test.go
1. During hash join v2 build, it will pre-allocate maxRowTableSegmentSize(which is 1024) rows for a new rowTableSegment
https://github.com/pingcap/tidb/blob/634ac69d272f117a0abea52f32a860e0078c0611/pkg/executor/join/join_row_table.go#L87-L95
For small queries, it is a waste to pre allocate so many memories and may hurt the performance in high concurrency scenarios.
In this pr, when constructing a new rowTableSegment, it will use `chunk_row_number/partition_number * 1.2` as the row size hint for the first rowTableSegment, but still use maxRowTableSegmentSize as the row size hint for the following rowTableSegment.
2. Add `maxRowTableSegmentByteSize` to control the max memory size of a rowTableSegment.
3. Since rowTableSegment saves `rowStartOffset` …
> executor: some minor refine for hash join v2 build

- pkg/table/tables/tables.go
Issue Number: close #54698
see descriptions in issue
Reuse `indexVals` in `addIndices`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tables: fix invalid reuse of `indexVals` in `addIndices`

- br/pkg/aws/BUILD.bazel
- br/pkg/aws/ebs.go
- br/pkg/aws/ebs_test.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/pointer.go
Issue Number: close #54511
EC2 DescribeSnapshots API doesn't always return StateMessage in response for errored snapshot. Example response:
```
{
"Snapshots": [
{
"Description": "",
"Encrypted": true,
"KmsKeyId": "...",
"OwnerId": "...",
"Progress": "99%",
"SnapshotId": "snap-04c5f87d0a2b069b0",
"StartTime": "2024-07-08T15:07:01.437000+00:00",
"State": "error",
"VolumeId": "vol-0377214577dd710de",
"VolumeSize": 50,
"Tags": [
...
],
"StorageTier": "standard"
}
]
}
```
In these cases, snapshot backup process panics due to nil pointer dereference. End result is the same (failed backup), but we still want to correctly process these errors
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 …
```
> br: fix get snapshot response pointer deref panic

- pkg/ddl/schema.go
- pkg/ddl/schema_version.go
- pkg/domain/domain.go
- pkg/executor/BUILD.bazel
- pkg/executor/recover_test.go
- pkg/infoschema/builder.go
- pkg/infoschema/infoschema_v2.go
- pkg/parser/model/ddl.go
Issue Number: close #54415
as title. Follow up of https://github.com/pingcap/tidb/pull/54439
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: don't save table IDs in schema diff of FLASHBACK DATABASE

- pkg/executor/batch_point_get_test.go
Issue Number: close #54702
The test tests temporary table does not visit network. But when infoschema v2 is used, table by name also visit network. 
So the test is not appliabl to infoschema v2, just skip it in that case.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix unstable test TestPointGetForTemporaryTable

- pkg/executor/adapter.go
- pkg/executor/staticrecordset/BUILD.bazel
- pkg/executor/staticrecordset/integration_test.go
- pkg/server/conn.go
- pkg/server/conn_stmt.go
- pkg/server/conn_stmt_test.go
- pkg/server/driver_tidb.go
- pkg/server/internal/resultset/cursor.go
- pkg/server/internal/resultset/resultset.go
- pkg/server/tests/commontest/BUILD.bazel
- pkg/server/tests/commontest/cursor_test.go
- pkg/server/tests/cursor/BUILD.bazel
- pkg/server/tests/cursor/cursor_test.go
- pkg/session/session.go
- pkg/session/tidb.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #54526
Previously, all cursor fetch requests will load the data to the TiDB. Now, we can support lazily fetch results in a limited scope.
1. Add a new system variable `tidb_enable_lazy_cursor_fetch`.
2. Add a new implementation of `ResultSet` to give similar interface like the one for eager cursor fetch.
Tests 
> 
```release-note
Add a new system variable `tidb_enable_lazy_cursor_fetch` to indicate whether to try to fetch data lazily for cursor fetch requests.
```
> server: add protocol support for lazy cursor fetch

- pkg/planner/core/find_best_task.go
- pkg/planner/core/point_get_plan.go
- tests/integrationtest/r/planner/core/integration_partition.result
- tests/integrationtest/t/planner/core/integration_partition.test
Issue Number: close #54583
Problem Summary: For partitioned tables, it is not possible to determine which partition the row belongs to through `_tidb_rowid`, so the PointGet plan cannot obtain correct results. We should ban it.
Tests 
> 
Side effects
Documentation
```release-note
Forbid generate `PointGet` plan with partition table + `_tidb_rowid`.
```
> planner: forbid generate `PointGet` plan with partition table + `_tidb_rowid`

- DEPS.bzl
- go.mod
- go.sum
This is a reopened PR of https://github.com/pingcap/tidb/pull/54574 which cherry-picks https://github.com/pingcap/tidb/pull/53698
Issue Number: close #53540
Update client-go to fix the problem that when query OOM kill happens in a transaction, the next query in the transaction may encounter panic when starting fair locking.
Also includes https://github.com/tikv/client-go/pull/1381 (ref: https://github.com/pingcap/tidb/issues/54375)
Tests 
> 
Side effects
Documentation
```release-note
Fix the problem that when query OOM kill happens in a …
```
> *: Update client-go to fix fair locking panic when executing a query after OOM kill in a transaction

- pkg/executor/builder.go
- pkg/executor/executor.go
- pkg/executor/executor_required_rows_test.go
Issue Number: close #54616
Similar to https://github.com/pingcap/tidb/pull/51397. This PR uses the `BaseExecutorV2` and removed the session context in the `SelectionExec`.
1. Remove the `BaseExecutor` internal and replace it with `BaseExecutorV2`.
2. Add a new `selectionExecutorContext`, which includes all information needed by the selection executor.
Tests 
> No logic change. It shouldn't break existing tests.
> 
Side effects
Documentation
```release-note
None
```
> executor: Use the `BaseExecutorV2` to refactor the `SelectionExec` and remove the session context inside

- pkg/executor/analyze_col_v2.go
More comments were added to collect stats on the generated column index.
We collect the stats for the generated column index. But we ignore the generated columns themselves because we don't store them on TiKV and we can't calculate the NDV from TiKV.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Add more comments for collecting stats on generated column index

- pkg/executor/benchmark_test.go
- pkg/executor/builder.go
- pkg/executor/join/BUILD.bazel
- pkg/executor/join/base_join_probe.go
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/hash_table_v2.go
- pkg/executor/join/hash_table_v2_test.go
- pkg/executor/join/inner_join_probe_test.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/left_outer_join_probe_test.go
- pkg/executor/join/row_table_builder_test.go
Current, we dispatch row to each partition by the LSB bits in hash value
https://github.com/pingcap/tidb/blob/31c1de0b4f30d708de8228aa72c1a0dbff547504/pkg/executor/join/join_row_table.go#L540
And in each partition, we build hash table also based on the LSB bits in hash value
https://github.com/pingcap/tidb/blob/31c1de0b4f30d708de8228aa72c1a0dbff547504/pkg/executor/join/hash_table_v2.go#L86
This may increase the hash table conflicts especially if partition number is power of 2
1. make the partition number to be a number that is pow of 2
2. dispatch row to each partition by the n MSB bits in hash value 
Tests 
> 
Side effects
Documentation …
> executor: Refine partition number in hash join v2

- pkg/table/context/buffers.go
- pkg/table/context/buffers_test.go
- pkg/table/context/table.go
- pkg/table/contextimpl/BUILD.bazel
- pkg/table/contextimpl/table.go
- pkg/table/contextimpl/table_test.go
- pkg/table/tables/index.go
- pkg/table/tables/tables.go
expose some fields from `SessionVars` to `MutateContext`. This PR added:
- `WriteStmtBufs` for `MutateBuffers`
- `ConnectionID` for `MutateContext`
- `TxnAssertionLevel` for `MutateContext`
- `EnableMutationChecker` for `MutateContext`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: expose some fields to `MutateContext` from `GetSessionVars()`

- pkg/infoschema/infoschema_v2.go
- pkg/infoschema/test/infoschemav2test/v2_test.go
I find some performance issue of the TableByName API.
As the flamegraph shows, all the calling of `TableByName` goes to `mallocgc`
It's cause by the old style of writting like:
```
var end tableItem
var schemaVersion
var ok bool
var itm tableItem
is.byName.Descend(end, func() {             //   <-  this closure is allocated every time!
if item.dbName != h.end.dbName || item.tableName != end.tableName {
ok = false
return false
}
if item.schemaVersion <= schemaVersion {
if !item.tomb { // If the item is a tomb record, the database is dropped.
ok = true
itm = item
}
return false
}
return true
}
```
This closure function is a large burden for GC, it need to be allocated every time.
In this PR, we use and the closure allocation is avoid.
``` …
```
> infoschema: optimize the performance of TableByName for infoschemav2

- pkg/planner/core/casetest/index/BUILD.bazel
- pkg/planner/core/casetest/index/index_test.go
- pkg/util/ranger/detacher.go
- tests/integrationtest/r/planner/core/casetest/integration.result
- tests/integrationtest/r/util/ranger.result
- tests/integrationtest/t/planner/core/casetest/integration.test
Issue Number: close #54188 
Problem Summary: Properly classify columns with null predicates (e.g. `WHERE a IS NULL`) as constant so index selection can take advantage of that to satisfy a sort in https://github.com/pingcap/tidb/blob/432bb79f9732cb89a0be220ca93415df37a4849e/pkg/planner/core/find_best_task.go#L791.
Added checks for is null predicate during planning and fill corresponding data structures marking that column as a constant.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use ordered index with is null predicate | tidb-test=pr/2368

- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/hash_table_v2.go
- pkg/executor/test/jointest/hashjoin/BUILD.bazel
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
Issue Number: close #54755
In `HashJoinV2Exec`, there is a method `needUsedFlag`, which means if the row entry need to reserve a piece of memory to hold used flag, if yes, then during probe stage, if a build row is matched, its used flag will be set to true. This used flag is only used for join probe that need to scan the row table after probe is done.
In BaseJoinProbe, there is an interface `NeedScanRowTable`, which will return true if current join probe need to scan the row table after probe is done. So basically, `needUsedFlag` and `NeedScanRowTable` is the same thing. The pr remove `needUsedFlag`
Tests 
> 
Side effects
Documentation …
> executor: remove `HashJoinV2Exec.needUsedFlag()`

- pkg/executor/infoschema_reader.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/memtable_predicate_extractor.go
- pkg/planner/core/memtable_predicate_extractor_test.go
- tests/integrationtest/r/executor/explainfor.result
Issue Number: ref #50305 
Push down some filters for：
1. infoschema.TableStatistics
2. infoschema.TablePartitions
3. infoschema.TableSequences
4. infoschema.TableCheckConstraints
5. infoschema.TableTiDBCheckConstraints
6. infoschema.TableTiDBIndexUsage
7. infoschema.TableTiDBIndexes
8. infoschema.TableViews
9. infoschema.TableConstraints
10. infoschema.TableSchemata
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: speed up reader for some tables

- pkg/executor/batch_point_get.go
- pkg/executor/builder.go
- pkg/executor/distsql.go
- pkg/executor/executor.go
- pkg/executor/index_merge_reader.go
- pkg/executor/internal/exec/executor.go
- pkg/executor/point_get.go
- pkg/executor/table_readers_required_rows_test.go
- pkg/util/admin/admin.go
- pkg/util/logutil/consistency/BUILD.bazel
- pkg/util/logutil/consistency/reporter.go
Issue Number: close #54625
Similar to https://github.com/pingcap/tidb/pull/51397. This PR uses the `BaseExecutorV2` and removed the session context in the `IndexLookUpExecutor` and `IndexReaderExecutor`.
As these two executors have a very close connection. I refactored them in a single PR.
1. Remove the `BaseExecutor` internal and replace it with `BaseExecutorV2`.
2. Add a new `indexLookUpExecutorContext` and `indexReaderExecutorContext`, which include all information needed by the selection executor.
3. Remove the needed session context inside the redact log helper.
4. Remove the session context arguments for a function in `table` pkg.
Tests 
> 
> No logic change. It should be protected by existing tests.
Side effects
Documentation …
> executor: refactor the `BaseExecutor` and remove session context in `IndexLookUpExecutor` and `IndexReaderExecutor`.

- br/pkg/restore/snap_client/systable_restore_test.go
- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
Issue Number: close #54241
- Add summary field to tidb_background_subtask_history.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: add summary field to tidb_background_subtask_history

- br/tests/br_shuffle_leader/run.sh
- br/tests/br_shuffle_region/run.sh
Issue Number: close #54820
Pd-ctl now disabled the prefix matching, we may need to adapt the modification.
ref: https://github.com/tikv/pd/pull/8414
Use full command instead of prefix matching in pd-ctl command.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: Use full name instead of prefix in integration test

- pkg/infoschema/tables.go
- pkg/infoschema/test/clustertablestest/cluster_tables_test.go
- pkg/infoschema/test/clustertablestest/tables_test.go
- pkg/util/processinfo.go
Issue Number: close #54486
We need a straightforward way to know the progress of long-running statements.
Add a column `affected_rows` to `information_schema.processlist`
Tests 
> 
Side effects
Documentation
```release-note
Add a column `affected_rows` to `information_schema.processlist`.
```
> infoschema: add affected_rows to the processlist table

- br/pkg/errors/errors.go
- br/pkg/task/BUILD.bazel
- br/pkg/task/restore.go
- br/pkg/task/restore_test.go
- br/pkg/utils/backoff.go
- errors.toml
Issue Number: ref https://github.com/pingcap/tidb/issues/54316, https://github.com/pingcap/tidb/issues/54470
Now, the preserve rate of tiflash is set 1.3
Add more log and normalized errors
Fix the error that `TiFlashReplicas` is not set
Tests 
> 
Side effects
Documentation
```release-note
Now, the preserve rate of tiflash is set 1.3
Add more log and normalized errors
Fix the error that `TiFlashReplicas` is not se
```
> br:  disk space check follow up

- pkg/ddl/db_integration_test.go
- pkg/ddl/ddl.go
- pkg/ddl/ddl_worker.go
- pkg/ddl/job_table.go
- pkg/parser/model/ddl.go
as title
- currently, SeqNum is used to identify the order of moving the job into DDL history, it's not the order of the job execution. for jobs with dependency, or if they are run in the same session, their SeqNum will be in increasing order. when using fast create table, there might duplicate seq_num as any TiDB can execute the DDL in this case.
- after this PR, the SeqNum will always start from 1 when DDL owner not changed, and `for jobs with dependency, or if they are run in the same session, their SeqNum will be in increasing order` is still maintained. on owner change, new owner will reset and start it from 1 again. as previous semantic forces 'moving jobs into DDL history' part to be serial, it's more complex and has very limited usage …
> ddl: decouple job seq number from job history & reset its allocator on owner change

- pkg/domain/resourcegroup/runaway.go
- pkg/executor/infoschema_reader.go
- pkg/executor/internal/querywatch/query_watch_test.go
Issue Number: Close #54770, Ref #54434
Problem Summary: runaway: change `tidb_runaway_watch` to UTC
Currently `tidb_runaway_watch` relies on struct `QuarantineRecord` to store time as UTC, while `runaway_watch` directly selects `tidb_runaway_watch` to convert to local time. Let's change `tidb_runaway_watch` to UTC as well.
> **why not change `tidb_runaway_watch` to local time?**
because `tidb_runaway_watch` is `datetime`, which is different from `timestamp`, and can not convert UTC to local time automatically.
https://github.com/pingcap/tidb/blob/e5a8a23e836a99b95db201f412cb7fdd9c811c5f/pkg/session/bootstrap.go#L635-L646
This means the timezone information will be lost, and the user will not know which timezone to switch to when in crossing time zones (the user needs to confirm the local …
> runaway: change `tidb_runaway_watch` time type to UTC

- pkg/util/gctuner/BUILD.bazel
- pkg/util/gctuner/finalizer_test.go
- pkg/util/gctuner/memory_limit_tuner_test.go
- pkg/util/gctuner/tuner_test.go
Issue Number: close #54836
Problem Summary: sometime when we run test manually, we may forget to add `intest` flag
check intest flag is set in tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
> gctuner: check intest flag in tests

- pkg/executor/executor.go
- pkg/executor/infoschema_reader.go
- pkg/executor/show.go
- pkg/planner/core/logical_plan_builder.go
- pkg/table/tables/tables_test.go
Issue Number: close #54343
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: isolate more variables for `runWithSystemSession`

- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_utils.go
Problem Summary: planner: simplify the plan cache code for fast point get
planner: simplify the plan cache code for fast point get
A small performance regression around 1%, but it's acceptable:
```
BenchmarkPreparedPointGet
Before:
183510              6434 ns/op
After:
155811              6518 ns/op
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify the plan cache code for fast point get

- pkg/executor/detach.go
- pkg/executor/detach_integration_test.go
- pkg/executor/distsql.go
Issue Number: close #54799
Previously, the `IndexReader` and `IndexLookUp` didn't support lazy cursor fetch.
Now, the lazy cursor fetch function should also support `IndexReader` and `IndexLookUp` executors. It's implemented by adding `Detach` function on these executors.
Tests 
> 
```release-note
None
```
> executor: support detaching the `IndexReader` and `IndexLookUp`

- pkg/expression/evaluator.go
- pkg/expression/evaluator_test.go
Issue Number: close #54797
Expose the optional property on the `EvaluatorSuit`. It can help us to implement the `Detach` function for `ProjectionExec` and `SelectionExec`.
It recursively reads the optional property of all expressions and their arguments.
Tests 
> 
```release-note
None
```
> expression: expose the optional property on EvaluatorSuit

- pkg/executor/insert_test.go
- pkg/table/context/table.go
- pkg/table/contextimpl/BUILD.bazel
- pkg/table/contextimpl/table.go
- pkg/table/contextimpl/table_test.go
- pkg/table/tables/tables.go
Some fields/operations provided by `MutateContext` are optional. For example, binlog is not used in lighting import and all binlog operations should be skipped in this scene.
To make the `MutateContext` easy to construct and better decouple with `sessionctx.Context`. We can add some "optional" design for some fields or methods.
We name some operational information with "XXXSupport" and provide methods "GetXXXSupport" to return them. These methods return two values, the first value is the optional object implements `XXXSupport` and the second value is a boolean that indicates whether it is supported.
In this PR, two optional objects are defined to support binlog and statistics update:
```go
// BinlogSupport is used for binlog operations
type BinlogSupport interface …
```
> table: Add `GetStatisticsSupport` and `GetBinlogSupport` for `MutateContext`

- pkg/executor/write.go
- pkg/infoschema/tables.go
- pkg/table/table.go
- pkg/table/tables/partition.go
- pkg/table/tables/tables.go
Issue Number: close #54824
An implicit interface `CheckConstraintTable` should be implemented for all table objects to check constraints somewhere. For example: 
https://github.com/pingcap/tidb/blob/f774ef6fb5bd140c4db67a1ab5fc3dea53253bec/pkg/table/tables/partition.go#L1582-L1593
However, it is not a good way to achieve it. The coders unfamiliar with those codes may rename or remove the method 'CheckRowConstraint` by mistake, but it will not produce any error in the build phase.
To make the code strong, it's better not to use implicit interface implementation and all methods a table should implement should be declared in `table.Table`
1. Add `WritableConstraint` to `table.Table` and its derived type should implement it.
2. Add static functions `CheckRowConstraint` and …
> table: add `WritableConstraint` to interface `table.Table` to avoid implicit interface implementation

- pkg/config/config.go
- pkg/executor/set_test.go
- pkg/session/bootstrap.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: ref #51876 #53831
In #53831, we change tidb_opt_projection_push_down session variable's default value to 'on'. After discussion with PM, we need to keep consistency with older versions and avoid any unknown potential problems, we decide to keep the 'off' value for tidb cluster upgradation. Thus we change the variable to both session and global scope. Besides, this PR deprecates the previous config item "projection-push-down", we can do this because this config would have never been used by customers due to #34993 issue. 
Tests 
> 
Side effects
Documentation …
> session, config, sessionctx, executor: Set tidb_opt_projection_push_down to false when tidb upgrades from versions older than 8.3.0 to 8.3.0 and later

- pkg/ddl/executor.go
- pkg/executor/internal/querywatch/query_watch.go
- pkg/parser/ast/ddl.go
- pkg/parser/ast/ddl_test.go
- pkg/parser/ast/misc.go
- pkg/parser/ast/misc_test.go
- pkg/parser/parser.y
Before this PR, many `RESOURCE GROUP` and `QUERY WATCH` ASTs used ambiguous union struct fields to parse different options. This PR makes them use clearer structures to improve readability and extensibility.
Tests 
```release-note
None
```
> pkg/parser: use clearer structures for RESOURCE GROUP ASTs

- pkg/executor/join/BUILD.bazel
- pkg/executor/join/index_lookup_merge_join.go
- pkg/executor/join/index_lookup_merge_join_test.go
- pkg/executor/partition_table_test.go
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
- pkg/executor/test/jointest/join_test.go
- pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- pkg/util/hint/hint.go
- tests/integrationtest/r/executor/index_lookup_join.result
- tests/integrationtest/r/executor/index_lookup_merge_join.result
- tests/integrationtest/r/executor/jointest/hash_join.result
- tests/integrationtest/r/executor/write.result
- tests/integrationtest/r/expression/charset_and_collation.result
- tests/integrationtest/r/expression/issues.result
- tests/integrationtest/r/planner/core/casetest/hint/hint.result
- tests/integrationtest/r/planner/core/casetest/index/index.result
- tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result
- tests/integrationtest/r/planner/core/casetest/rule/rule_join_reorder.result
- tests/integrationtest/r/planner/core/integration.result
- tests/integrationtest/r/planner/core/physical_plan.result
- tests/integrationtest/t/planner/core/physical_plan.test
Issue Number: close #54064
Tests 
> 
Side effects
Documentation
```release-note
废弃 index lookup merge join hint.
deprecate index lookup merge join.
```
> planner: deprecate index lookup merge join.

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_expand.go
- pkg/planner/core/logical_initialize.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_predicate_push_down.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: classify logical expand logic into a separate file for later pkg move.

- pkg/planner/core/collect_column_stats_usage.go
- pkg/session/session.go
- pkg/statistics/histogram.go
Issue Number: ref https://github.com/pingcap/tidb/issues/54883
- The "if" statement is never going to be true, so we are making an assertion here.
- Removed an unused function of the histogram.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove useless check

- pkg/ddl/ddl_worker.go
Issue Number: close #54703
Timeline:
1. Create a TiDB v6.1.7 cluster.
2. Add a TiDB nightly instance. It will trigger the upgrade procedure.
3. Submit upgrade DDLs at TiDB nightly, and TiDB v6.1.7 will run it as DDL owner.
Because concurrent DDL is not implemented in TiDB v6.1, these upgrade DDLs will be submited to the queue. However, #54669 does not consider those jobs who are submited to queue, new TiDB does not assign table IDs for create tables/views/sequences jobs.
```
[2024/07/24 15:45:21.524 +08:00] [INFO] [ddl_worker.go:264] ["add DDL jobs"] [category=ddl] ["batch count"=1] [jobs="ID:72, Type:create table, State:queueing, SchemaState:none, SchemaID:3, TableID:0, RowCount:0, ArgLen:2, start time: 2024-07-24 15:45:21.484 +0800 CST, Err:<nil>, ErrCount:0, …
```
> ddl: assign table IDs for jobs submitted to queue

- pkg/session/bench_test.go
- pkg/table/tables/bench_test.go
Issue Number: ref #50215
Refine some benchmarks to make them more realistic and stable.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: refine pipelined dml benchmarks

- pkg/executor/test/analyzetest/BUILD.bazel
- pkg/executor/test/analyzetest/analyze_test.go
- pkg/executor/test/analyzetest/memorycontrol/BUILD.bazel
- pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go
- pkg/statistics/BUILD.bazel
- pkg/statistics/handle/autoanalyze/BUILD.bazel
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/autoanalyze_test.go
- pkg/statistics/handle/autoanalyze/exec/exec.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
- pkg/statistics/handle/cache/statscache.go
- pkg/statistics/handle/metrics/metrics.go
- pkg/statistics/handle/updatetest/BUILD.bazel
- pkg/statistics/handle/updatetest/update_test.go
- pkg/statistics/integration_test.go
- pkg/statistics/table.go
- pkg/ttl/ttlworker/BUILD.bazel
- pkg/ttl/ttlworker/job_manager_integration_test.go
Issue Number: close #54823
The primary changes in ```pkg/statistics/handle/cache/statscache.go``` file.
the rest are code migrations to avoid cyclic imports.
Tests 
I test in the 1m tables cluster. we can see this metrics in the grafana.
> 
Side effects
Documentation
```release-note
None
```
> statistics: add metrics for unneeded analyze table

- pkg/executor/join/BUILD.bazel
- pkg/executor/join/index_lookup_hash_join.go
- pkg/executor/join/index_lookup_join_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/54688
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that index_hash_join could not exit properly when SQL was interrupted abnormally.
```
> executor: fix index_hash_join hang when context canceled

- lightning/pkg/importer/meta_manager.go
Issue Number: close #49826
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: fix SET SESSION on connection pool

- pkg/ddl/backfilling.go
Issue Number: close https://github.com/pingcap/tidb/issues/54373
`localRowCntListener` can create tasks by `HandleTask()`, which can be read/write `curPhysicalRowCnt`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix a data race on localRowCntListener Written()

- pkg/ddl/tests/fail/fail_db_test.go
Issue Number: close #48758
if after schema validator restart, there is no `reload` within 200ms which is the ddllease before this pr, `schemaValidator.latestSchemaExpire` will expire, so later insert will fail with `schema changed`
https://github.com/pingcap/tidb/blob/e0e8f89336e442e9cf6aa002469d291d075ace47/pkg/domain/domain.go#L1076
```
Error Trace:	/Users/xiedong/repos/tidb/pkg/testkit/testkit.go:157
/Users/xiedong/repos/tidb/pkg/testkit/testkit.go:150
/Users/xiedong/repos/tidb/pkg/ddl/tests/partition/db_partition_test.go:2674
Error:      	Received unexpected error:
[domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing …
```
> test: fix flaky test TestFailSchemaSyncer

- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_clone_generator.go
Problem Summary: planner: use code-gen to generate CloneForPlanCache method for some operators
planner: use code-gen to generate CloneForPlanCache method for some operators
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use code-gen to generate CloneForPlanCache method for some operators

- tests/integrationtest/r/executor/expand.result
- tests/integrationtest/t/executor/expand.test
Issue Number: close https://github.com/pingcap/tidb/issues/42631
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: import more expand test.

- pkg/expression/constant_propagation.go
- pkg/util/disjointset/BUILD.bazel
- pkg/util/disjointset/int_set.go
- pkg/util/disjointset/set.go
- pkg/util/disjointset/set_test.go
Add the generic implementation for disjoint set.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> disjoinset: add generic impl

- pkg/planner/core/integration_test.go
- pkg/planner/core/logical_union_scan.go
Issue Number: close #54870
Problem Summary: planner: push necessary predicates without virtual column down through UnionScan
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: push necessary predicates without virtual column down through UnionScan

- pkg/planner/core/logical_expand.go
- tests/integrationtest/r/executor/expand.result
- tests/integrationtest/t/executor/expand.test
Issue Number: close #54983
expand is an operator that will generate additional columns based on what the child outputs, so in the building phase, construct expand's proj exprs is too much earlier until the column pruning logic is done in the logical optimizing phase.
that's means `expand.exprs` will be nil in the plan building phase if we use it in the time, it will cause panic. For extracting correlated columns logic, we could simply return nil(what the correlated columns it may generate later must exist its child) because expand itself doesn't produce any correlated columns inside.
Tests 
> 
Side effects
Documentation …
> planner: fix extract correlated column for expand in building phase will panic.

- pkg/domain/domain.go
- pkg/domain/domain_test.go
- pkg/expression/context/context.go
- pkg/session/bootstrap_test.go
- pkg/session/bootstraptest/bootstrap_upgrade_test.go
- pkg/session/session.go
- pkg/session/tidb.go
Issue Number: close #54868, close #54860
as title, see this for root cause https://github.com/pingcap/tidb/issues/54868#issuecomment-2249663873
Tests 
bootstrap with TiKV, test some ddl/dml, they should work and check no error logs.
bootstrap with unistore, same test as above.
> 
Side effects
Documentation
```release-note
None
```
> ddl: init global vars from system tables before start domain

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/core_init.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/operator/logicalop/BUILD.bazel
- pkg/planner/core/operator/logicalop/logical_show_ddl_jobs.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/stats.go
- pkg/planner/core/stringer.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move logical show ddl jobs to logicalop pkg.

- pkg/infoschema/cache.go
- pkg/infoschema/test/infoschemav2test/BUILD.bazel
- pkg/infoschema/test/infoschemav2test/v2_test.go
Issue Number: close #54926
In infoschema cache.go, we maintain the infoschema snapsht history.
As the comment says:
```
// `GetByVersion` is allowed to load the latest schema that is less than argument
// `version` when the argument `version` <= the latest schema version.
// if `version` > the latest schema version, always return nil, loadInfoSchema
// will use this behavior to decide whether to load schema diffs or full reload.
// Consider cache has values [10, 9, _, _, 6, 5, 4, 3, 2, 1], version 8 and 7 is empty because of the diff is empty.
// If we want to get version 8, we can return version 6 because v7 and v8 do not change anything, they are totally the same,
// in this case the `i` will not be 0.
```
However, when v1 & v2 infoschema switch, we reset the history …
> infoschema: fix a snapshot infoschema cache bug after v1 v2 switch

- pkg/metrics/grafana/performance_overview.json
Issue Number: close #54981
Enhance the performance overview
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: add memory info and traffic flow into performance overview

- br/pkg/gluetidb/BUILD.bazel
- br/pkg/gluetidb/glue.go
- br/pkg/gluetidb/glue_test.go
Issue Number: close #55039
after https://github.com/pingcap/tidb/pull/54913, we separate domain Init and Start. BR also depends on domain and should start it to do DDLs
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix br domain start

- pkg/executor/test/executor/executor_test.go
- pkg/executor/update.go
Issue Number: close #50308
Problem Summary: As title said, see more detail in issue #50308
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix issue that update ignore stmt return error when meet incorrect timestamp value error

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/exhaust_physical_plans_test.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache_rebuild.go
- pkg/planner/core/task.go
Problem Summary: planner: simplify the indexJoinBuildHelper structure
ONLY REFACTORYING, NO LOGICAL CHANGE.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: simplify the indexJoinBuildHelper structure

- pkg/executor/analyze.go
- pkg/executor/analyze_worker.go
Just reuse the concurrent code to handle the single-threaded case.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: do not copy and paste the code for saving statistics

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #54848
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: update tikv/client-go for fix rpc client panic cause by concurrent close

- pkg/ddl/backfilling.go
- pkg/ddl/ddl.go
- pkg/ddl/job_scheduler.go
- pkg/ddl/reorg.go
Issue Number: close #54897 
Timeline:
1. tidb-0 run ingest backfill workers as the DDL owner.
2. Inject network latency to tidb-0.
3. tidb-1 get DDL owner, and switch to merge temp index step.
4. Inject network latency to tidb-1. tidb-1's merge temp index backfill workers failed with "DDL is not owner"
5. tidb-0 get DDL owner AGAIN, but `reorgCtx` is the one added in step(1).
6. Merge temp index step is skipped because the `reorgCtx` is done.
Record get owner TS and compare it before runReorgJob quit.
Tests 
Here is the log from HA test:
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write …
> ddl: record get owner TS and compare it before runReorgJob quit

- pkg/ttl/ttlworker/job_manager.go
- pkg/ttl/ttlworker/job_manager_integration_test.go
Issue Number: close #55098
Tests 
After this PR, if the job cancel because for out of time window, the message is: 
```
[2024/07/31 16:39:16.585 +08:00] [INFO] [job_manager.go:589] ["cancel job because out of TTL job schedule window"] [ttl-worker=job-manager] [jobID=904b49393e3d4b0ea4d24fbe502b2b83]
```
> 
Side effects
Documentation
```release-note
None
```
> ttl: fix cancel job message for TTL

- pkg/kv/key.go
- pkg/planner/core/operator/baseimpl/plan.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_clone_generator.go
- pkg/planner/core/point_get_plan.go
- pkg/planner/core/util.go
- pkg/planner/util/misc.go
Problem Summary: planner: use code-gen to generate CloneForPlanCache method for some operators
planner: use code-gen to generate CloneForPlanCache method for some operators
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use code-gen to generate CloneForPlanCache method for Point/BatchPoint/Limit

- pkg/statistics/handle/autoanalyze/internal/heap/BUILD.bazel
- pkg/statistics/handle/autoanalyze/internal/heap/heap.go
- pkg/statistics/handle/autoanalyze/internal/heap/heap_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/55063
This PR added a thread-safe heap for the priority queue.
Because it doesn't involve any business logic to the priority queue, it is a pure data structure, so I think we can add it in advance.
Maybe you will ask why we don't use Fibonacci heap here. The constants for Fibonacci heaps are actually quite large, and their complexity is amortized. Therefore, it is very likely that their performance will be similar to that of regular binary heaps in this scenario.
The original implementation:
https://github.com/kubernetes/client-go/blob/master/tools/cache/heap.go
Tests 
> 
Side effects
Documentation …
> statistics: add a thread-safe heap

- pkg/ddl/partition.go
- tests/integrationtest/r/ddl/partition.result
- tests/integrationtest/t/ddl/partition.test
Issue Number: close #55093
Tests 
> 
Side effects
Documentation
```release-note
Fix create interval partition not report error when partition numbers exceed limit number.
```
> ddl, partition: report error when interval partition create partition numbers exceed limit number

- pkg/executor/test/fktest/BUILD.bazel
- pkg/executor/test/fktest/foreign_key_test.go
- pkg/infoschema/builder_misc.go
Issue Number: close #54909
use correct v2 infoschema to build FK
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: fix foreign key building using schema cache V2

- pkg/executor/detach.go
- pkg/executor/detach_integration_test.go
- pkg/executor/projection.go
- pkg/expression/evaluator.go
- pkg/expression/evaluator_test.go
- pkg/server/tests/cursor/BUILD.bazel
- pkg/server/tests/cursor/cursor_test.go
Issue Number: close #54863
The lazy cursor fetch didn't support `Projection` and `Selection`. This PR enables it to handle most of the `Projection` and `Selection` operator.
Implement the `Detach` function for these operators.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor, expression: detach projection and selection operator

- pkg/util/execdetails/execdetails.go
Issue Number: close #55042
Tests 
> Just a mutex lock changes, using defer to protect it.
Side effects
Documentation
```release-note
Fix the issue that queries may get stuck when they are being killed due to exceeding tidb_mem_quota_query.
```
> util: Resolve RuntimeStatsColl potential unlock mutex

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/issuetest/BUILD.bazel
- pkg/planner/core/issuetest/planner_issue_test.go
Issue Number: close #54535
When set system variable `tidb_enable_inl_join_inner_multi_pattern` to `ON`, the following SQL will get an error.
```SQL
set GLOBAL tidb_enable_inl_join_inner_multi_pattern='ON';
create table ta(a1 int, a2 int, a3 int, index idx_a(a1));
create table tb(b1 int, b2 int, b3 int, index idx_b(b1));
explain SELECT /*+ inl_join(tmp) */ * FROM ta, (SELECT b1, COUNT(b3) AS cnt FROM tb GROUP BY b1, b2) as tmp where ta.a1 = tmp.b1;
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```
Tests 
> 
Side effects
Documentation …
> planner: fix index out of range in constructIndexJoinInnerSideTask

- pkg/store/copr/coprocessor.go
Issue Number: ref #54969
In the past, https://github.com/pingcap/tidb/pull/35975 reduce coprocessor concurrency to 2 for the keep order query.
But recently we meet an oncall case that the change cause performance regression.
Balance the memory usage and concurrency is a difficult job, ~~we need more tests and expirements to reach the conclusion.~~
~~Currently we can simply set TiFlash to not reduce concurrency, when a user using TiFlash, the tidb memory usage would not be a top concern (their hardware must be better).~~
Tests 
See comments below
> 
One line change, just revert part of the previous optimization.
Side effects
Documentation …
> store/copr: revert pr/35975, do not reduce concurrency for keep order coprocessor request

- pkg/executor/join/join_row_table.go
- pkg/executor/join/join_row_table_test.go
- pkg/executor/test/jointest/hashjoin/BUILD.bazel
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
- pkg/util/codec/codec.go
Issue Number: close #55016
HashJoinV2, it will first pack all the join keys into a byte array named `serializedKey`, and during the probe stage, it will compare `serializedKey` directly, if the `serializedKey` matches, the join think its original key matches. `codec.SerializeKeys` is used to generate `serializedKey`, for var-length column, if `SerializeMode` is not `keepStringLength`, it will not record string length in `serializedKey`.
Currently, only a string key is inlined, it need to record string length.
The problem is if the join key is 2 strings like `a = a and b = b`, if string length is not kept in `serializedKey`, then the following two pair of keys will generate same `serializedKey`
{a: `aa`, b: `a`}
{a: `a`, b: `aa`}
which is not expected.
In this pr, it …
> executor: fix correctness of hash join v2 when there are multiple var-length keys

- pkg/planner/core/preprocess.go
Issue Number: close #54779
Before checking table change by comparing `TableInfo`, we can just examine `Revision` first to skip unnecessary checks. Besides, I also found that column comparation is done by double loop, which can use `map`.
https://github.com/pingcap/tidb/blob/da7d83f54a8673016dd32415d5997f24f78c05ea/pkg/planner/core/preprocess.go#L1874-L1875
Using a table containing more than 1000 columns to test.
Before:
After:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: Add Revision check in tryLockMDLAndUpdateSchemaIfNecessary

- pkg/expression/evaluator.go
- pkg/expression/evaluator_test.go
- pkg/util/chunk/column.go
- pkg/util/disjointset/int_set.go
- pkg/util/disjointset/set.go
Issue Number: close https://github.com/pingcap/tidb/issues/53713
Tests 
use the valid SQL and error SQL inside issue to produce result
and compare it with MySQL output, both them output like below:
```
mysql> source /Users/arenatlx/Downloads/error.txt
+------+------+------+------+
| c1   | c3   | c4   | c5   |
+------+------+------+------+
| NULL | NULL | 4    | NULL |
+------+------+------+------+
1 row in set (0.04 sec)
```
> 
Side effects
Documentation
```release-note
Fixed an issue where the column evaluator could not detect column …
```
> planner: fix column evaluator can not detect input's column-ref and thus swapping and destroying later column ref projection logic

- store/copr/coprocessor.go
Issue Number: close #54969
Cherry-pick https://github.com/pingcap/tidb/pull/55141 to provide a hotfix on v7.1 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> store/copr: revert pr/35975, do not reduce concurrency for keep order coprocessor request (#55141)

- pkg/executor/join/base_join_probe.go
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/inner_join_probe.go
- pkg/executor/join/outer_join_probe.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Avoid too many concurrent atomic update in probe collision

- pkg/executor/infoschema_reader.go
- tests/integrationtest/r/infoschema/infoschema.result
- tests/integrationtest/t/infoschema/infoschema.test
Issue Number: close #55156
Previously, the condition `table_schema = ...` has no effect on table `INFORMATION_SCHEMA.KEY_COLUMN_USAGE`. This PR fixed it.
Also filter on `table_schema` condition.
Maybe I can add more automatically generated tests for `InfoSchemaTablesExtractor` :thinking: later. We should verify that all these extracted columns work on all the information schema tables.
Tests 
> 
```release-note
None
```
> executor: filter on `table_schema` for `INFORMATION_SCHEMA.KEY_COLUMN_USAGE` table

- server/BUILD.bazel
- server/conn.go
- server/conn_test.go
- server/packetio_test.go
Issue Number: close #53689
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server: fix connection double close

- pkg/ddl/column_change_test.go
- pkg/ddl/index_change_test.go
- pkg/executor/write.go
- pkg/infoschema/tables.go
- pkg/table/BUILD.bazel
- pkg/table/index.go
- pkg/table/table.go
- pkg/table/table_test.go
- pkg/table/tables/BUILD.bazel
- pkg/table/tables/bench_test.go
- pkg/table/tables/cache.go
- pkg/table/tables/index.go
- pkg/table/tables/partition.go
- pkg/table/tables/tables.go
- pkg/table/tables/tables_test.go
Issue Number: close #55121
This PR does some code refactors of the input options for methods `Table.AddRecord/UpdateRecord` and `Index.Create` including:
1. Introduce `UpdateRecordOption` to give some optional args for `Table.UpdateRecord`:
We moved argument `ctx` to `UpdateRecordOption` for method `UpdateRecord`
```go
// UpdateRecordOption is defined for the UpdateRecord() method of the Table interface.
type UpdateRecordOption interface {
ApplyUpdateRecordOpt(*UpdateRecordOpt)
}
type Table interface {
// ...
UpdateRecord(ctx MutateContext, h kv.Handle, currData, newData []types.Datum, touched []bool, opts ...UpdateRecordOption) error
// ...
}
```
Now, the method `UpdateRecord` is more like `AddRecord` and we can extend it in the future.
2. Use `CreateIdxOption` to replace …
> table: refactor options for `Table.AddRecord/Table.UpdateRecord/IndexCreate

- pkg/metrics/metrics.go
- pkg/metrics/server.go
- pkg/server/conn.go
Issue Number: close https://github.com/pingcap/tidb/issues/54887
Per-query-statement RPC count and processed key count are useful metrics to understand the TiKV request fan-out when debugging expensive queries.
Added two new server metrics(query_statement_rpc_count and query_statment_processed_keys) to keep track of the per query statement TiKV RPC count and scan processed key count information.
Tests 
Tested the metrics by adding the p99, p80 prometheus queries to the two metrics in the local grafana dashboard.
Side effects
Documentation
```release-note
None
```
> metrics: add per-query-statement RPC count and scan processed key count metrics

- pkg/executor/join/BUILD.bazel
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/join_row_table_test.go
HashJoinV2 assumes that heap object can not be moved, this pr add runtime check to make sure of this.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: add heap object can move check for hash join v2

- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/issuetest/planner_issue_test.go
Issue Number: close #55169
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: avoid nil PhysicalProperty when to build agg

- distsql/request_builder.go
- session/sessiontest/session_test.go
- store/copr/coprocessor.go
Issue Number: close #54969
Hotfix for release-7.1-20240802-v7.1.5, cherry-pick https://github.com/pingcap/tidb/pull/55196
Tests 
See the original PR
> 
Side effects
Documentation
```release-note
None
```
> store/copr: partly revert pr/35975, do it correctly this time #55196

- pkg/planner/core/memtable_infoschema_extractor.go
- tests/integrationtest/r/infoschema/infoschema.result
- tests/integrationtest/t/infoschema/infoschema.test
Issue Number: close #55166
The result from `TableByName` contains temporary tables. We should filter temporary tables for all memory tables from `information_schema`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner/core: filter temp tables for information_schema

- pkg/executor/infoschema_reader.go
- pkg/executor/infoschema_reader_test.go
Issue Number: close #55235
Some conditions are just not used in the retriever of information schema tables. This PR adds a test for them, and fixes these issues. These issues are introduced in https://github.com/pingcap/tidb/pull/54333.
No matter whether an extracted condition is used in the real implementation, the parent executor will not use it to run a `SELECTION` again, and that's why these issues appear. It's hard to ensure all the conditions are used correctly, so I added a test to automatically test these lines.
1. Add a test to automatically generate tables and selecting rows in the information schema to see whether the condition behaves well.
2. Fix the case when the condition has no effect.
Tests 
> …
> executor: fix the issue that some extracted conditions are not used in information_schema

- pkg/planner/core/casetest/plan_test.go
- pkg/planner/core/casetest/testdata/plan_normalized_suite_out.json
- pkg/planner/core/issuetest/BUILD.bazel
- pkg/planner/core/issuetest/planner_issue_test.go
- pkg/util/ranger/detacher.go
Issue Number: close #54803
```points2EqOrInCond``` will generate the ```Equal```/```IN``` expression according the column info and const value. but we cannot regard ```isnull()``` and ```= null``` as equivalent. so ```isnull``` should skip the ```points2EqOrInCond```.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: incorrect query result using ISNULL

- pkg/executor/analyze.go
- pkg/executor/analyze_col.go
- pkg/executor/analyze_col_v2.go
- pkg/executor/analyze_global_stats.go
- pkg/executor/analyze_idx.go
- pkg/executor/analyze_worker.go
- pkg/executor/test/analyzetest/analyze_test.go
- pkg/statistics/analyze_jobs.go
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/types/interfaces.go
Issue Number: ref https://github.com/pingcap/tidb/issues/55043#issuecomment-2264674742
In the above issue comment, we decided to remove the dedicated analyze sessions. But after we removed them we need to find a better way to write the analysis job history. Theoretically we can call `_, _, err := exec.ExecRestrictedSQL(ctx, []sqlexec.OptionFuncAlias{sqlexec.ExecOptionUseSessionPool}, sql, args...)` concurrently to do it. But it is counterintuitive because we need to use the same session to get the executor and then use it to exec SQL with the session pool.
Because we already moved `InsertAnalyzeJob` into the stats handle, so I decided to move other job history-related functions into it as well.
- Moved startAnalyzeJob into the stats handle.
- Moved UpdateAnalyzeJob into …
> statistics: move history-related functions into the stats handle

- pkg/planner/core/rule_eliminate_projection.go
- tests/integrationtest/r/planner/core/issuetest/planner_issue.result
- tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #52985 
The AvoidColumnEvaluator attribute in the Projection operator is used to avoid the incorrect reuse of chunks with different metadata. During the projection elimination optimization process, the setting of the AvoidColumnEvaluator attribute must be preserved if any of the consecutive projections have it set to true.
Tests 
> 
Side effects
Documentation
```release-note
Fixed an issue where certain queries were producing incorrect results. This was caused by a bug in the query processing logic related to the handling …
```
> pkg/planner, tests: set the AvoidColumnEvaluator correctly in ProjectionElimination

- pkg/sessionctx/variable/tidb_vars.go
- Updated the comments for some stats-related variables.
- See more at https://tidb-analyze.vercel.app/32?clicks=1
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: update comments for statistics related variables

- br/pkg/checkpoint/checkpoint.go
Issue Number: close #55265
`WalkDir` the path `{bucket}/{prefix}//{sub-dir}` get the object `{bucket}/{prefix}//{sub-dir}/object`, but `ReadFile` the object `{bucket}/{prefix}//{sub-dir}/object` cannot find it.
`/checkpoints` -> `checkpoints`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix checkpoint path

- pkg/infoschema/test/clustertablestest/cluster_tables_test.go
- pkg/planner/core/casetest/physicalplantest/BUILD.bazel
- pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
- pkg/planner/core/hint_utils.go
- pkg/planner/core/physical_plans.go
Issue Number: ref #55280 
There's no actual logic change. It's in preparation for the next PR, which contains the real logic changes.
- Add a `PhysicalJoin` interface.
- Reorder functions in `hint_utils.go`.
- Split `getJoinHints()` and extract a new function `extractHintTableForJoinNode()` from it.
- Change the return value type of `getJoinHints()` from `[]*ast.TableOptimizerHint` to `*ast.TableOptimizerHint` because it returns one element at most.
-  Rename `getJoinHints()` to `genJoinMethodHintForSinglePhysicalJoin()` in `hint_utils.go`.
Tests 
> 
Side effects
Documentation …
> planner: add `PhysicalJoin` interface and move and split methods in `hint_utils.go`

- tools/check/ut.go
- tools/check/xprog.go
`filepath.Join` is platform dependent and joins paths based on the operating system's path separator (e.g., `/` on Windows and `/` on Unix).
`path.Join` is platform-independent and always uses `/` as the path separator.
Issue Number: Ref #30822
Tests 
```release-note
None
```
> tools/ut.go: replace path with filepath

- pkg/executor/builder.go
- pkg/executor/insert.go
- pkg/executor/insert_common.go
- pkg/executor/load_data.go
- pkg/executor/replace.go
- pkg/executor/update.go
- pkg/executor/write.go
- pkg/planner/core/common_plans.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/point_get_plan.go
- pkg/sessionctx/variable/BUILD.bazel
- pkg/sessionctx/variable/session.go
- pkg/table/table.go
- pkg/table/tables/index.go
- pkg/table/tables/tables.go
- pkg/table/tables/tables_test.go
- Added a new option `DupKeyCheckLazy` for `table.DupKeyMode` to check duplicated keys lazily in table operations. After this, the key check mode is determined by outside code and the logic is easier to understand.
- Remove `DupKeyCheckDefault` and add `DupKeyCheckInPlace` to replace it.
- Adding `IgnoreError` to `UpdateExec` and `InsertExec` to indicate `INSERT IGNORE ...` or `UPDATE IGNORE ...`. The condition `e.IgnoreError` will replace `ec.ErrGroupLevel(errctx.ErrGroupDupKey) != errctx.LevelError` which makes code more readable.
- Remove `LazyCheckKeyNotExists` because the lazy check mode is determined by each scene now, this method is useless now. This PR also removed `PresumeKeyNotExists` in `SessionVars`.
Tests 
> - [ ] I checked and no code files have been …
> table: Add option `DupKeyCheckLazy` to check duplicated key lazily

- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/plan_clone_generator.go
- pkg/planner/util/misc.go
Problem Summary: planner: use code-gen to generate CloneForPlanCache method for SelectLock
planner: use code-gen to generate CloneForPlanCache method for SelectLock
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use code-gen to generate CloneForPlanCache method for SelectLock

- pkg/executor/executor.go
- pkg/parser/ast/util.go
- pkg/planner/core/operator/logicalop/logical_lock.go
- pkg/planner/core/plan_cache_utils.go
- pkg/planner/core/point_get_plan.go
- pkg/planner/core/preprocess.go
- pkg/sessionctx/stmtctx/stmtctx.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
- tests/realtikvtest/pessimistictest/pessimistic_test.go
Issue Number: close #55022
1. Support `tidb_enable_shared_lock_promotion` to achive that the `for share` statements could be executed like `for update` statements which acquire pessimistic locks.
2. Fix serveral issues when `tidb_enable_noop_functions` is enabled, the behaviours of `select for share` are unexpected, including:
- When `nowait` is used, the execution is not `no-op` actually.
- When `tidb_enable_noop_functions` is set to `off`, the `select for share` **DOES** acquire locks, so is `on`.
3. Refactor the behaviours of `tidb_enable_noop_functions`, `tidb_enabled_shared_lock_promotion` and `for share` statements for executions with `PointGet` and `Coprocessor` pathes. 
Tests 
> 
Side effects
Documentation …
> server: add tidb_enable_shared_lock_promotion to support for share lock upgrade

- pkg/table/tables/BUILD.bazel
- pkg/table/tables/index.go
- pkg/table/tables/index_test.go
Issue Number: close #55313
`opt.IgnoreAssertion` is corrupted if `AddRecord` has multiple indexes and one index is not in public state.
https://github.com/pingcap/tidb/blob/0cfa66fcf031e1261b3c24e4ac93b5b2c5b7599e/pkg/table/tables/index.go#L249
We should not change the value `opt.IgnoreAssertion`.
TODO: we should make all options immutable to avoid similar bugs.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: fix some txn assertion error when executing DDL and DML

- pkg/executor/set_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/varsutil.go
Problem Summary: planner: support using "KiB/MiB/GiB" to set isntance_plan_cache_target/max_mem_size
planner: support using "KiB/MiB/GiB" to set isntance_plan_cache_target/max_mem_size to improve user experience
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: support using "KiB/MiB/GiB" to set isntance_plan_cache_target/max_mem_size

- pkg/domain/BUILD.bazel
- pkg/domain/domain.go
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/exec/BUILD.bazel
- pkg/statistics/handle/autoanalyze/exec/exec.go
- pkg/statistics/handle/autoanalyze/exec/exec_test.go
Issue Number: close #55283
TiDB forget to kill the anto analyze which is out of the time windows
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: kill auto analyze out of the auto analyze time windows

- pkg/executor/show.go
Issue Number: close #55301 
- clone table before fill column types
Tests 
see #52688 
```
Running tool: /usr/local/go/bin/go test -timeout 10m -coverprofile=/tmp/vscode-gomVYcKs/go-code-cover -run ^TestShowViewPriv$ github.com/pingcap/tidb/pkg/privilege/privileges -race --tags=intest
ok  	github.com/pingcap/tidb/pkg/privilege/privileges	12.034s	coverage: 27.4% of statements
```
> 
Side effects
Documentation
```release-note
None
```
> ddl: clone table for show columns

- docs/tidb_http_api.md
- pkg/domain/BUILD.bazel
- pkg/domain/domain.go
- pkg/server/BUILD.bazel
- pkg/server/http_status.go
- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/initstats/BUILD.bazel
- pkg/statistics/handle/initstats/load_stats_page.go
Issue Number: close #53564
Add progress information in the status.
Tests 
```
➜  opensource curl http://127.0.0.1:9081/status
{"connections":0,"version":"8.0.11-TiDB-v8.3.0-alpha-129-g158199c87d","git_hash":"158199c87d9bb83e045e4e113d38d323006ea41d","status":{"init_stats_percentage":100}}
```
> 
Side effects
Documentation
```release-note
None
```
> *: support to query init stats percentage from http api

- pkg/table/index.go
- pkg/table/table.go
- pkg/table/table_test.go
- pkg/table/tables/index.go
- pkg/table/tables/tables.go
We should to make `XXXOpt` in table immutable to avoid some potential bugs introduced by modifying its inner state and then shared with other operations. See issue: #55313
- Make the fields in the opt objects private to avoid modification directly in other package.
- Make the method in the interfaces `AddRecordOption` / `UpdateRecordOption` / `CreateIdxOption` private to forbid outside package to use them.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: make `AddRecordOpt`/`UpdateRecordOpt`/`CreateIdxOpt` immutable

- pkg/executor/staticrecordset/BUILD.bazel
- pkg/executor/staticrecordset/integration_test.go
- pkg/session/session.go
Issue Number: close #55227
There was a data conflict in the test, because the `MemTracker` is pre-allocated in the cache of `StatementContext`. If the `StatementContext` is re-used, the mem tracker will be cleaned..
Add a `ServerStatusCursorExists` flag. It makes sure the `StatementContext` will not be re-used.
Tests 
> 
```release-note
None
```
> test: fix data conflict in `TestCursorWillBlockMinStartTS`

- pkg/statistics/handle/storage/save.go
- pkg/statistics/handle/storage/stats_read_writer.go
- pkg/statistics/handle/storage/update.go
Issue Number: close #55126
Problem Summary: planner: add protection to avoid setting `tot_col_size` to negative numbers
See more details and analysis in the issue.
When updating `tot_col_size`, use `GREATEST` to protect it from becoming a negative number.
Hard to use UT to test it, so I tested it manually locally:
First I hacked the code below to simulate all positive updates on `tot_col_size` are lost:
Then execute those SQLs:
```
mysql> create table t (a varchar(100), key(a));
Query OK, 0 rows affected (0.01 sec)
mysql> analyze table t;
Query OK, 0 rows affected, 2 warnings (0.03 sec)
mysql> insert into t values (space(100));
Query OK, 1 row affected (0.01 sec)
mysql> update t set a="";
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```
Then we can see the …
> planner: add protection to avoid setting `tot_col_size` to negative numbers

- pkg/sessionctx/variable/session.go
Issue Number: close #55337
fix data race for `TxnCtx.GetTemporaryTable`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> variable: fix data race in `GetTemporaryTable`

- WORKSPACE
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade bazel rules

- docs/design/2023-08-24-background-tasks-control.md
- pkg/ddl/tests/resourcegroup/BUILD.bazel
- pkg/ddl/tests/resourcegroup/resource_group_test.go
- pkg/domain/resourcegroup/runaway.go
- pkg/executor/simple.go
- pkg/server/server.go
- pkg/session/session.go
- pkg/store/driver/error/error.go
- pkg/testkit/mocksessionmanager.go
- pkg/ttl/cache/table.go
- pkg/util/BUILD.bazel
- pkg/util/expensivequery/expensivequery.go
- pkg/util/processinfo.go
- pkg/util/sqlkiller/sqlkiller.go
mark runaway query when processing time on tidb side exceed executed time
Issue Number: close #51325
```bash
mysql> ALTER RESOURCE GROUP default QUERY_LIMIT=(EXEC_ELAPSED='2s', ACTION=KILL,  WATCH=EXACT DURATION='10m');
Query OK, 0 rows affected (0.07 sec)
mysql> select sleep(3) from t;
ERROR 8253 (HY000): Query execution was interrupted, identified as runaway query
```
can find log 
```bash
[2024/08/07 16:54:49.501 +08:00] [WARN] [expensivequery.go:109] ["runaway query timeout"] [costTime=2.06010825s] [groupName=default] [rule=execElapsedTimeMs:2s] [processInfo="{id:295698438, user:root, host:127.0.0.1:52409, db:test, command:Query, time:2, state:autocommit, info:select sleep(3) from t}"]
[2024/08/07 16:54:49.502 +08:00] [INFO] [server.go:896] [kill] [conn=295698438] …
```
> runaway: add runaway tidb-side time checker

- pkg/planner/cascades/implementation_rules.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_union_all.go
- pkg/planner/core/operator/logicalop/logical_projection.go
- pkg/planner/core/optimizer.go
- pkg/planner/core/physical_plan_test.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/rule_inject_extra_projection.go
- pkg/planner/core/task.go
Issue Number: close #52985 
Tests 
> 
Side effects
Documentation
```release-note
Fixed an issue where certain queries were producing incorrect results. This was caused by a bug in the query processing logic related to the handling of the projection operator which is a child of Union operator.
```
> pkg/planner: set proj.AvoidColumnEvaluator in postOptimize

- pkg/executor/infoschema_reader.go
- pkg/executor/infoschema_reader_test.go
Issue Number: close #55253
The previous patch https://github.com/pingcap/tidb/pull/55236/files#diff-cd85979e0fe90c288bf582cb1b181f51cbb7b874423cc4e1163617e2dbf95c98R2140-R2142 forgot to filter the `PRIMARY` index and the foreign keys. This PR fixes this issue.
Add two filters condition on PRIMARY index and foreign keys.
It'd be better to have a function to automatically check all `record`s according to the extracted column and defined columns in the table, and replace all manual `append(rows, record)`. However, @tangenta told me he's working on rewriting the extractor and making every table has its own retriever, so I only submit some temporary fixes.
Tests 
> 
```release-note
Fix the issue that the `PRIMARY` index …
```
> executor, infoschema: filter out the PRIMARY index and foreign keys in table_constraints

- pkg/executor/aggfuncs/aggfuncs.go
- pkg/executor/aggfuncs/func_count.go
- pkg/executor/aggfuncs/func_max_min.go
- pkg/executor/aggregate/agg_hash_executor.go
- pkg/executor/aggregate/agg_spill.go
- pkg/executor/aggregate/agg_spill_test.go
Issue Number: close #55290
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that getting incorrect result when hash agg spill is triggered
```
> executor: fix incorrect result when hash agg spill is triggered

- pkg/executor/historical_stats_test.go
- pkg/statistics/handle/util/util.go
Issue Number: close #55364
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestRecordHistoryStatsAfterAnalyze

- pkg/types/vector.go
- pkg/types/vector_test.go
- pkg/util/codec/codec.go
Issue Number: ref #54245 
When CSV data is loaded via LOAD DATA statement, it turns out that row is encoded using Format v1:
```
LOAD DATA LOCAL INFILE '/Users/breezewish/Downloads/backup_llama_index_rag_test/test.llama_index_rag_test.0000000010000.csv' INTO TABLE `llama_index_rag_test` FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
```
And it causes problems:
```mysql
mysql> select * from llama_index_rag_test limit 10;
ERROR 1105 (HY000): invalid data type: unsupported data type `20`
```
This PR make it work.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide …
> copr: Support VECTOR for RowFormatv1

- pkg/ddl/BUILD.bazel
- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_dist_executor.go
- pkg/ddl/backfilling_operators.go
- pkg/ddl/backfilling_scheduler.go
- pkg/ddl/cancel_test.go
- pkg/ddl/executor.go
- pkg/ddl/export_test.go
- pkg/ddl/index.go
- pkg/ddl/index_cop.go
- pkg/ddl/index_modify_test.go
- pkg/ddl/ingest/backend_mgr.go
- pkg/ddl/ingest/config.go
- pkg/ddl/ingest/integration_test.go
- pkg/ddl/ingest/mock.go
- pkg/ddl/tests/adminpause/global.go
- pkg/executor/test/admintest/admin_test.go
- pkg/executor/test/ddl/ddl_test.go
- pkg/parser/model/reorg.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/varsutil_test.go
- tests/realtikvtest/addindextest1/disttask_test.go
- tests/realtikvtest/addindextest3/functional_test.go
- tests/realtikvtest/addindextest3/ingest_test.go
- tests/realtikvtest/addindextest3/operator_test.go
Issue Number: close #55335
Problem Summary: see https://github.com/pingcap/tidb/issues/55335
- Add session scope support for system variables `tidb_ddl_reorg_worker_cnt` and `tidb_ddl_reorg_batch_size`.
- For session scope variables, the value cannot be changed during DDL job execution.
- For global scope variables, the they only provide the default values of session variables.
Tests 
Execute following SQLs on root user:
```
create user 'aa'@'%' identified by '';
create database aa;
grant create, alter, insert on aa.* to 'aa'@'%';
```
Switch to user 'aa'@'%':
```
mysql> use aa;
mysql> show tables;
Empty set (0.00 sec)
mysql> create table t (a int, b int);
Query OK, 0 rows affected (0.07 sec)
mysql> insert into t values (1, 1);
Query OK, 1 row affected (0.03 sec)
mysql> …
```
> ddl: support session level tidb_ddl_reorg_worker_cnt and batch_size

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/optimizer.go
- pkg/planner/core/rule/BUILD.bazel
- pkg/planner/core/rule/rule_constant_propagation.go
Issue Number: ref #55231
move rule_constant_propagation from core to rule pkg
Tests 
> - [x] I ran locally, and executed a sql with pagination.
> 
Side effects
Documentation
```release-note
None
```
> planner: move `rule_constant_propagation` to rule pkg. (#55231)

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #55206
Problem Summary: it's an enhancement, ref #55206 .
Make batch policy configurable and improve batch efficiency for high throughput workloads.
Tests 
> 
Side effects
Documentation
```release-note
Make batch policy configurable and improve batch efficiency for high throughput workloads.
```
> *: bump client-go to adopt new batch policy

- pkg/domain/domain.go
- pkg/planner/core/metrics/metrics.go
- pkg/planner/core/plan_cache_instance.go
- pkg/planner/core/plan_cache_instance_test.go
- pkg/sessionctx/context.go
Problem Summary: planner: add more log and metrics for instance plan cache eviction
1. add more log and metrics for instance plan cache eviction
2. prevent updating instance plan cache items during eviction
3. update the default eviction interval from 15s to 30s
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more log and metrics for instance plan cache eviction

- pkg/executor/aggregate/agg_spill_test.go
Issue Number: close #55376
Tests 
> 
Side effects
Documentation
```release-note
fix data race in hash agg spill test
```
> executor: fix data race in hash agg spill test

- pkg/executor/insert.go
- pkg/executor/insert_common.go
- pkg/executor/write.go
- pkg/table/context/table.go
- pkg/table/table.go
- pkg/table/tables/index.go
- pkg/table/tables/tables.go
- pkg/table/tables/tables_test.go
Issue Number: close #54397
This PR introduced a new table option `PessimisticLazyDupKeyCheckMode` to determine the lazy check mode in pessimistic mode. It has two values:
```go
type PessimisticLazyDupKeyCheckMode uint8
const (
// PessimisticKeyCheckInLock indicates to check the duplicated key when acquiring the pessimistic lock.
PessimisticKeyCheckInLock PessimisticLazyDupKeyCheckMode = iota
// PessimisticKeyCheckInPrewrite indicates to check the duplicated key in the prewrite step when committing.
// Please notice that if it is used, the duplicated key error may not be returned immediately after each statement,
// because the duplicated key is not checked when acquiring the pessimistic lock.
PessimisticKeyCheckInPrewrite
)
```
If `PessimisticLazyDupKeyCheckMode` is not specified, it is …
> table: Add `PessimisticLazyDupKeyCheckMode` to determine lazy mode in pessimistic txn

- pkg/planner/cascades/implementation_rules.go
- pkg/planner/cascades/transformation_rules.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/casetest/stats_test.go
- pkg/planner/core/collect_column_stats_usage.go
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/operator/logicalop/BUILD.bazel
- pkg/planner/core/operator/logicalop/logical_apply.go
- pkg/planner/core/plan.go
- pkg/planner/core/rule_decorrelate.go
- pkg/planner/core/rule_eliminate_projection.go
- pkg/planner/core/stringer.go
- pkg/planner/pattern/pattern.go
- pkg/planner/pattern/pattern_test.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move logical apply to logicalop pkg.

- pkg/domain/resourcegroup/runaway.go
- pkg/executor/infoschema_reader.go
- pkg/util/expensivequery/expensivequery.go
- Delete some unnecessary code.
- Add more comments.
- Organize and enhance some functions.
Tests 
```release-note
None
```
> domain/rg: organize and enhance the code of RunawayChecker

- pkg/executor/infoschema_reader.go
- pkg/infoschema/cluster.go
- pkg/infoschema/tables.go
- pkg/planner/core/explain.go
- pkg/planner/core/pb_to_plan.go
Issue Number: ref #50305
`InfoSchemaIndexUsageExtractor` is added for cluster_tidb_index usage memtable.
Besides, the explain output of cluster memory table is changed to make it consistent with other memtable.
```
mysql> explain select * from information_schema.CLUSTER_TIDB_INDEX_USAGE where table_schema = "test";    
+------------------------+----------+-----------+--------------------------------+----------------------------------------------------------------------+
| id                     | estRows  | task      | access object                  | operator info                                                        |
+------------------------+----------+-----------+--------------------------------+----------------------------------------------------------------------+
| TableReader_7 …
```
> *: add extractor for cluster_tidb_index_usage

- pkg/executor/ddl.go
Issue Number: close #55442
Make a clone for table meta since the return value will be modified here:
https://github.com/pingcap/tidb/blob/c74a2330c03faceb14b0ba081a4a93716964c9af/pkg/ddl/executor.go#L1429-L1444
This can fix `TestRecoverTableByJobID` failure.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: clone table meta for recover table

- pkg/metrics/grafana/tidb_runtime.json
This commit improves the TiDB-Runtime->Memory Usage panel to make it more readable.
Before:
After:
According to https://pkg.go.dev/runtime/metrics, we have reorganized the data in the Memory Usage panel into the following categories:
- RSS Memory
- Heap In-Use
- Stack In-Use
- Heap Unused
-  Go Runtime Metadata
-  Other Memory
-  Free Memory Reserved by Go
-  Memory Returned to OS
In this structure, `rss` is approximately equal to `heap_inuse + stack_inuse + heap_unused + go_runtime_metadata + other_memory + free_mem_reserved_by_go`.
The data sources corresponding to each category are listed in the table below:
Tests 
> 
Side effects
Documentation …
> pkg/metrics: improve the TiDB-Runtime->Memory Usage panel

- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
Issue Number: close #53460
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: support concurrent auto analyze

- pkg/expression/builtin_other.go
- pkg/expression/builtin_other_test.go
- pkg/expression/builtin_other_vec.go
- pkg/expression/builtin_other_vec_test.go
- pkg/expression/context/param.go
Issue Number: close #55471
After EvalContext implemented `ParamValues` in https://github.com/pingcap/tidb/pull/53534, builtinGetParamStringSig do not need to read SessionVarsPropReader to get param values. So it' time to delete SessionVarsPropReader in it.
remove `SessionVarsPropReader` in `builtinGetParamStringSig`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: remove `SessionVarsPropReader` in `builtinGetParamStringSig`

- pkg/planner/core/issuetest/planner_issue_test.go
- pkg/util/ranger/ranger.go
- pkg/util/ranger/ranger_test.go
Issue Number: close #55475
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ranger: should replace ast.Or with ast.LogicalOr 

- pkg/planner/core/collect_column_stats_usage.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_cte.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/recheck_cte.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: export elements in cteClass for late pkg move.

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/logical_plans.go
- pkg/planner/core/operator/logicalop/BUILD.bazel
- pkg/planner/core/operator/logicalop/logical_expand.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/rule_resolve_grouping_expand.go
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move logical expand into logicalop pkg.

- pkg/executor/test/analyzetest/BUILD.bazel
- pkg/executor/test/analyzetest/analyze_test.go
- pkg/planner/core/expression_rewriter.go
Issue Number: close #55438
When we deal with analyze statement, it cannot contain the ```planCtx```. so we have to get column meta from the infoschema.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix cannot get column info from generate column

- pkg/expression/contextstatic/exprctx.go
- pkg/expression/util.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/expression_test.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/point_get_plan.go
Issue Number: close #55492
After #53534 , we have removed inner `SessionVars` in `ParamMarker`. We can make `expression.BuildSimpleExpr`  to support `ParamMarker` now
`expression.BuildSimpleExpr` supports to build `ParamMarker`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: `expression.BuildSimpleExpr` supports to build `ParamMarker`

- pkg/executor/insert_common.go
- pkg/executor/write.go
- pkg/table/context/table.go
- pkg/table/contextimpl/BUILD.bazel
- pkg/table/contextimpl/table.go
- pkg/table/contextimpl/table_test.go
- pkg/table/tables/partition.go
Issue Number: ref #53388
`MutateContext.GetDomainInfoSchema()` is only used by DML when a DDL exchanging partition is in progress. It is not required in other cases, such as lighting or DDL reorg (adding index). We can make `GetDomainInfoSchema` "optional" so  to make easier to construct `MutateContext` for the scenes who does not need it.
- Remove `GetDomainInfoSchema` in `MutateContext`
- Add a new interface `ExchangePartitionDMLSupport` to provide information schema optionally:
```go
// ExchangePartitionDMLSupport is used for DML operations when the table exchanging a partition.
type ExchangePartitionDMLSupport interface {
// GetInfoSchemaToCheckExchangeConstraint is used by DML to get the exchanged table to check
// constraints when exchanging partition. …
```
> table: Add `GetExchangePartitionDMLSupport` and remove `GetDomainInfoSchema` in `MutateContext`

- pkg/ddl/index_cop.go
- pkg/ddl/reorg.go
- pkg/executor/admin.go
- pkg/executor/builder.go
- pkg/planner/core/find_best_task.go
- pkg/planner/core/plan_to_pb.go
- pkg/planner/core/plan_to_pb_test.go
- pkg/table/tables/tables.go
- pkg/util/misc.go
- pkg/util/misc_test.go
Issue Number: close #55462
As described in https://github.com/pingcap/tidb/issues/55462, the infoschema checker has found inconsistent with v1 and v2 in `TestDisaggregatedTiFlashGeneratedColumn`, thus throw a panic.
This is because the column info returned from `getOriginalPhysicalTableScan` is modifed here:
https://github.com/pingcap/tidb/blob/f73e3e34c5b39dcc7c7908cb7fdabd920fb5bf44/pkg/planner/core/find_best_task.go#L2461-L2467
As described in the comments, we should do this check in `ColumnToProto` to avoid `ColumnInfo` changes.
Tests 
> 
Side effects
Documentation …
> planner/core: pushdown TiFlash store type check to ColumnToProto

- pkg/config/config.go
- pkg/domain/domain.go
- pkg/executor/analyze.go
- pkg/executor/analyze_worker.go
- pkg/session/session.go
- pkg/sessionctx/variable/sysvar.go
See my article at https://github.com/pingcap/tidb/issues/55043#issuecomment-2264674742
- Marked analyze-partition-concurrency-quota as deprecated.
- Removed useless dedicated sessions for analysis.
- Set the correct type for the `AnalyzePartitionConcurrency` variable.
Tests 
> 
Side effects
Documentation
```release-note
将 analyze-partition-concurrency-quota 配置标记为弃用
mark analyze-partition-concurrency-quota as deprecated
```
> variable: mark analyze-partition-concurrency-quota as deprecated

- pkg/executor/sortexec/BUILD.bazel
- pkg/executor/sortexec/parallel_sort_spill_test.go
- pkg/executor/sortexec/parallel_sort_test.go
- pkg/executor/sortexec/sort.go
- pkg/executor/sortexec/topn.go
Issue Number: close #55344
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that parallel sort may be stuck when sorted column is constant
```
> executor: fix query hang when sorted column is constant

- pkg/server/conn.go
- pkg/server/conn_test.go
- pkg/server/server.go
Issue Number: close #55464
Previously, TiDB will not wait for auto-commit queries. These queries are directly killed. It'd be better to wait for them to finish.
Also checking the connection status when filtering the connection to wait.
Tests 
> 
Run a workload with heavy auto-commit traffic, and you'll see the connections are closed with little leaked lock.
```release-note
None
```
> server: wait for auto commit queries before shutdown

- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_operators.go
- pkg/ddl/ingest/checkpoint.go
- tests/realtikvtest/addindextest3/ingest_test.go
Issue Number: close #55488
See https://github.com/pingcap/tidb/issues/55488#issuecomment-2296771408.
The end key in checkpoint should be "next unprocessed key" instead of "last processed key".
- Remove `.Next()` for checkpoint end key when resuming.
- Add an integration test.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix resuming to wrong checkpoint when failed during adding index

- pkg/domain/BUILD.bazel
- pkg/domain/domain.go
Change splitted group count to 8 instead of group size when using infoschema V2.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: change groupSize in splitForConcurrentFetch

- pkg/ddl/foreign_key.go
- pkg/domain/plan_replayer_dump.go
- pkg/infoschema/BUILD.bazel
- pkg/infoschema/infoschema_nokit_test.go
- pkg/infoschema/infoschema_test.go
- pkg/infoschema/infoschema_v2.go
- pkg/planner/core/memtable_infoschema_extractor.go
Use context to pass the refill option for TableByName/TableByID
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: add WithRefillOption for TableByName and TableByID

- lightning/pkg/importer/BUILD.bazel
- lightning/pkg/importer/get_pre_info.go
- pkg/distsql/BUILD.bazel
- pkg/distsql/select_result.go
- pkg/domain/sysvar_cache.go
- pkg/sessionctx/variable/session.go
- pkg/statistics/table.go
- pkg/util/intset/BUILD.bazel
- pkg/util/intset/fast_int_set_test.go
- pkg/util/stmtsummary/BUILD.bazel
- pkg/util/stmtsummary/statement_summary.go
- pkg/util/stmtsummary/v2/stmtsummary.go
Issue Number: close #55527
as title, some maps.Copy which are used to override old item are kept
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: replace maps.Copy which is for map clone with std maps.Clone

- pkg/parser/parser.y
- pkg/parser/parser_test.go
Issue Number: close #55441
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser:  call `SetText` correctly for `CreateViewStmt`

- pkg/executor/infoschema_reader.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/memtable_infoschema_extractor.go
- pkg/planner/core/operator/logicalop/logicalop_test/logical_mem_table_predicate_extractor_test.go
- pkg/planner/core/pb_to_plan.go
Issue Number: ref #50305
Previously, we have a few usages like `ex.Filter("partition_name", pi.Name.L)` which is easy to misuse.
- Add `HasXXX` method for each extractors, remove `Filter`s.
- Extract similar code `ListSchemasAndTables` to `InfoSchemaBaseExtractor`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: refactor infoschema predicate extractors

- pkg/expression/BUILD.bazel
- pkg/expression/simple_rewriter.go
- pkg/expression/simple_rewriter_test.go
- pkg/planner/core/logical_plan_builder.go
Issue Number: close https://github.com/pingcap/tidb/issues/52112
This function becomes sluggish with numerous columns. So, I tried to improve it in this pull request.
1. Early continue: We check NotExplicitUsable and ColName first, as these are likely to eliminate many candidates quickly.
2. Avoid repeated access: We precompute dbName.L, tblName.L, and colName.L at the beginning.
Benchmark result:
```console
Running tool: /opt/homebrew/bin/go test -benchmem -run=^$ -tags intest -bench ^BenchmarkFindFieldName$ github.com/pingcap/tidb/pkg/expression
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/expression
BenchmarkFindFieldName/Original-10-8         	10015628	       120.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkFindFieldName/Optimized-10-8 …
```
> planner: improve the performance of FindFieldName

- pkg/planner/core/optimizer.go
- pkg/planner/core/optimizer_test.go
Issue Number: close #55543
As the issue described.
Use logical cores as default fine grained stream count
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: use logical cores as default fine grained stream count

- pkg/ttl/ttlworker/job.go
Issue Number: close #55545
The function `updateJobCurrentStatusSQL` is not used (though I'm not sure whether it's useless by day one or it's useless after some refactor).
It's removed. No logic change.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: remove useless function in TTL

- pkg/domain/domain_sysvars.go
- pkg/infoschema/builder.go
- pkg/infoschema/sieve.go
Issue Number: close #55490
In the previous implementation, if the setting value is 0, we would not call `SetCapacity` for sieve, nor `onUpdateLimit`.
always call `onUpdateLimit` for setting any capacity value
Tests 
> 
Now `set @@tidb_schema_cache_size = 0` can update the metric
Side effects
Documentation
```release-note
None
```
> infoschema: set the capacity of sieve to 0 for disabling infoschema v2

- pkg/expression/builtin.go
- tests/integrationtest/r/expression/builtin.result
- tests/integrationtest/t/expression/builtin.test
Issue Number: close #52420 
Based on https://github.com/pingcap/tidb/issues/52420#issuecomment-2268270133
Tests 
> 
Side effects
Documentation
```release-note
The two argument version of `MID()` is now supported to improve MySQL compatibility.
```
> expression: Support 2 argument version of MID()

- pkg/executor/join/BUILD.bazel
- pkg/executor/join/base_join_probe.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/join_row_table_test.go
Issue Number: close #55465
Add `TableMeta.isColumnNullThreadSafe` and use `TableMeta.isColumnNullThreadSafe` when there is potential data race during join probe.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix data race in hash join v2

- pkg/ddl/db_table_test.go
- pkg/ddl/ddl.go
- pkg/ddl/executor.go
- pkg/ddl/executor_test.go
- pkg/ddl/job_submitter.go
- pkg/ddl/job_submitter_test.go
- in https://github.com/pingcap/tidb/pull/54669 we have combine table/db id together with job id, in this pr we unify all global id allocation with job id, after that we don't need globalIDLock to reduce potential write conflict.
- move table lock handling in TruncateTable into DoDDLWrapper
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: alloc global id together with job id

- pkg/planner/core/rule_decorrelate.go
- tests/integrationtest/r/cte.result
- tests/integrationtest/t/cte.test
Issue Number: close #55551
`ExtractOuterApplyCorrelatedCols` is used to find all correlated columns which is inside CTE definition and its corresponding Apply is outside of CTE definition. Check the following diagram, `ExtractOuterApplyCorrelatedCols` should **NOT** return `cor_col_3`, because `cor_col_3`'s corresponding Apply is `Apply_3`, which is inside CTE definition.
Why need `ExtractOuterApplyCorrelatedCols`: For those CTE whose result of `ExtractOuterApplyCorrelatedCols(CTE_definition)` is not empty, we need to re-compute the definition of CTE.
```
// For Plan-2, the result of ExtractOuterApplyCorrelatedCols(CTE-2) will not return cor_col_3.
// Because Apply_3 is inside CTE-2.
// Plan-2:
//
//	Apply_2
//	 |_ outerSide
//	 |_ Selection(cor_col_2)
// …
```
> planner: fix CTE hang or wrong result when multiple Apply is used

- pkg/executor/executor.go
- pkg/executor/sortexec/sortexec_pkg_test.go
- pkg/util/chunk/row_container_test.go
- pkg/util/sqlkiller/sqlkiller.go
Issue Number: close #55467
fix data race in sqlkiller
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util: fix data race in sqlkiller

- pkg/parser/mysql/const.go
- pkg/parser/mysql/util.go
These changes makes it so that tidb can also compile for ARM, with for instance:
GOOS=linux GOARCH=arm GOARM=7 go build
Issue Number: close #54247 
Changing `int` to `int64` a couple of places in `parser/mysql/const.go` and `parser/mysql/util.go`.
The length of int is shorter on ARM7 than on x86_64.
Tests 
> 
I am using `tidb` in [Algernon](https://github.com/xyproto/algernon), and the proposed changes made it compile.
How I tested it:
```sh
git clone https://github.com/xyproto/algernon
cd algernon
go get -v github.com/pingcap/tidb@master
go mod tidy
go mod vendor
cd vendor/github.com/pingcap/tidb
curl -o arm.patch 'https://github.com/pingcap/tidb/commit/cc5f0b180c4f9609af02c3f628412f0a75bd73fa.diff'
patch -p1 -i …
```
> pkg/parser/mysql: Also compile for ARM 7

- pkg/planner/core/indexmerge_path.go
- pkg/planner/core/indexmerge_unfinished_path.go
- pkg/planner/core/logical_datasource.go
- pkg/server/testdata/optimizer_suite_out.json
- pkg/testkit/testdata/testdata.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove unnecessary pointer receiver function of datasource.

- cmd/mirror/mirror.go
- go.mod
Issue Number: close #37091
Problem Summary: The rely of `jwt-go` already removed by #48057, so we could remove the replace stmt.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> go.mod: remove replace `jwt-go`

- pkg/executor/analyze.go
- pkg/executor/test/analyzetest/BUILD.bazel
- pkg/executor/test/analyzetest/memorycontrol/BUILD.bazel
Issue Number: close #55469
```EnableAnalyzeSnapshot``` should not be used with different goroutines. 
Tests 
enable race for analyze test.
> 
Side effects
Documentation
```release-note
None
```
> *: fix data race in the EnableAnalyzeSnapshot

- pkg/ttl/ttlworker/del.go
- pkg/ttl/ttlworker/del_test.go
- pkg/ttl/ttlworker/scan.go
- pkg/ttl/ttlworker/task_manager.go
- pkg/ttl/ttlworker/task_manager_test.go
Issue Number: close #55561
- fix some missed count for `ErrorRows`
- if a scan task is finished, it will wait for all rows to be processed. If it is not finished in a certain time, the task will go one to mark itself as finished.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: fix the issue that TTL job may hang some time when shrink the delete worker count

- Makefile
``` --subcommands``` is for debug. remove it in the production.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> bazel: remove --subcommands for build

- DEPS.bzl
- go.mod
- go.sum
- pkg/session/test/txn/BUILD.bazel
- pkg/session/test/txn/txn_test.go
Issue Number: close #54929
Fix the issue that mem buffer don't bypass the staging data when doing snapshot read and add a regression test.
Tests 
> 
Side effects
Documentation
```release-note
Fix a bug that mem buffer's snapshot can read staging data.
```
> *: bump client-go to fix correctness issue of membuffer snapshot read

- br/pkg/restore/log_client/BUILD.bazel
- br/pkg/restore/log_client/client_test.go
- br/pkg/restore/log_client/export_test.go
- br/tests/br_pitr/run.sh
Issue Number: ref #54418
add test
add test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: add test for #54421

- tests/realtikvtest/testkit.go
Issue Number: ref #55529
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: turn on `-with-real-tikv` inside realtikvtest.RunTestMain

- pkg/ddl/foreign_key.go
- tests/integrationtest/r/ddl/foreign_key.result
- tests/integrationtest/t/ddl/foreign_key.test
Issue Number: close #55623 
In this func, we only use the table's `Name`, we don't need the whole `TableInfo`, so replace `SchemaTableInfos()` by `SchemaSimpleTableInfos()` 
Tests 
> 
Side effects
Documentation
```release-note
Replace `SchemaTableInfos` by `SchemaSimpleTableInfos()` , avoid unnecessary load of all table infos
```
> infoschema_v2: remove schemaTableInfos for foreign key

- pkg/planner/core/optimizer.go
- pkg/session/bootstraptest/BUILD.bazel
- pkg/session/bootstraptest/bootstrap_upgrade_test.go
Issue Number: close #55250 
as title. I'll create another PR for master after this PR is merged
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: skip check AllowCartesianProduct for internal SQL

- pkg/parser/model/model.go
- pkg/planner/cardinality/selectivity_test.go
- pkg/statistics/handle/bootstrap.go
- pkg/statistics/handle/storage/read.go
- pkg/statistics/handle/syncload/BUILD.bazel
- pkg/statistics/handle/syncload/stats_syncload.go
- pkg/statistics/table.go
- tests/integrationtest/r/executor/show.result
- tests/integrationtest/t/executor/show.test
Issue Number: close #54532
after https://github.com/pingcap/tidb/pull/53399,  we don't load the common column's stats into the cache. so it also cannot init the infoschema in the stats structure. so it will lead the problem, which cannot sync load 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix sync load fails after disabling lite init stats

- br/pkg/streamhelper/BUILD.bazel
- br/pkg/streamhelper/advancer.go
- br/pkg/streamhelper/advancer_cliext.go
- br/pkg/streamhelper/advancer_test.go
- pkg/util/redact/BUILD.bazel
- pkg/util/redact/redact.go
Issue Number: close #55273 
log-backup: secrets may be directly logging to log when --send-credentials-to-tikv=false not set during starting log backup
Added a wrap of the storage info and redact ak/sk, now the logging woud not print them directly.
Tests 
> 
Side effects
Documentation
```release-note
Added a wrap of the storage info and redact ak/sk, now the logging woud not print them directly.
```
> br: redact ak/sk in logging

- pkg/executor/infoschema_reader_test.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/memtable_infoschema_extractor.go
- pkg/planner/core/memtable_infoschema_extractor_test.go
- pkg/planner/core/operator/logicalop/logicalop_test/logical_mem_table_predicate_extractor_test.go
Issue Number: ref #50305
In `pkg/planner/core/memtable_infoschema_extractor_test.go` we cover testing all combinations of predicates for each infoschema table. It takes tens of seconds to run `TestMemtableInfoschemaExtractor`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: add more tests for infoschema predicate

- pkg/ddl/executor.go
- pkg/server/handler/tikvhandler/tikv_handler.go
Issue Number: ref #55394
Tests 
> 
1. create a cluster with 3 tiflash nodes by `tiup playground --db.binpath bin/tidb-server --db 1 --pd 1 --kv 1 --tiflash 3`
2. create two tables with tiflash replica 1 and 3
```sql
TiDB root@127.0.0.1:(none)> use test;
You are now connected to database "test" as user "root"
Time: 0.000s
TiDB root@127.0.0.1:test> create table t1 (c int);
Query OK, 0 rows affected
Time: 0.021s
TiDB root@127.0.0.1:test> create table t2 (c int);
Query OK, 0 rows affected
Time: 0.026s
TiDB root@127.0.0.1:test> alter table t1 set tiflash replica 1;
Query OK, 0 rows affected
Time: 0.023s
TiDB root@127.0.0.1:test> alter table t2 set tiflash replica 3;
Query OK, 0 rows affected
Time: 0.028s
```
3. `curl …
> infoschema: use `ListTablesWithSpecialAttribute` instead of `SchemaTableInfos`

- executor/mem_reader.go
- table/tables/tables.go
Issue Number: close https://github.com/pingcap/tidb/issues/43118
Problem Summary: Use `GetColOriginDefaultValueWithoutStrictSQLMode` instead of `GetColOriginDefaultValue` to fix potienal data race.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor, table: fix potienal data race

- pkg/expression/BUILD.bazel
- pkg/planner/cascades/base/hash_equaler.go
- pkg/types/BUILD.bazel
- pkg/types/datum.go
- pkg/util/codec/BUILD.bazel
- pkg/util/codec/codec.go
- pkg/util/codec/codec_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: introduce hashEqual interface for datum.

- executor/executor_pkg_test.go
- executor/sort.go
Issue Number: close https://github.com/pingcap/tidb/issues/55061
Add the final partition to the list when sort executor exit unexpected.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: clear the disk files after sort spilling when exit unexpected

- lightning/tests/lightning_checkpoint_chunks/run.sh
Issue Number: ref #55713
The CI failure is slow to fix, we will temporary disable it to allow other PR merging
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: temporary disable the stats check in lightning CI

- pkg/ddl/placement_policy.go
- pkg/infoschema/infoschema_v2.go
- pkg/meta/meta.go
Issue Number: ref #55394
Replace`SchemaTableInfos` with `ListTablesWithSpecialAttribute` to get table infos.
Currently, `CheckPlacementPolicyNotInUseFromInfoSchema` will fetch table infos from meta, which makes it no different from `CheckPlacementPolicyNotInUseFromMeta`.
https://github.com/pingcap/tidb/blob/87244edabf0ebae9870411cb83d91a9add4a797e/pkg/ddl/placement_policy.go#L347-L362
Additionally, a new function `GetTableInfoWithAttributes` is added to meta module to retrieve tables with special attributes under certain db.
Tests 
> 
Test using the following SQLs:
```mysql
mysql> use test
mysql> CREATE PLACEMENT POLICY p1 PRIMARY_REGION="us-east-1" REGIONS="us-east-1,us-west-1" FOLLOWERS=4;
Query OK, …
```
> *: remove call of SchemaTableInfos for CheckPlacementPolicy

- pkg/executor/show_placement.go
- pkg/executor/show_placement_test.go
Issue Number: close #55538
- list table id instead of table info
- only get table info if it's still scheduled
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: remove call of SchemaTableInfos for show placement

- OWNERS_ALIASES
Issue Number: ref https://github.com/pingcap/tidb/issues/46911
Following the retire mechanism from EE team, we should keep owner list as fresh as our team currently status.
Tests 
> 
```release-note
None
```
> * : Edit owner_aliases file to make approvers updated to newest team status.

- pkg/infoschema/infoschema_v2.go
- pkg/infoschema/test/infoschemav2test/BUILD.bazel
- pkg/infoschema/test/infoschemav2test/v2_test.go
Issue Number: close #55827
Fix a bug introduced by https://github.com/pingcap/tidb/pull/55574
That PR does not consider the snapshot read, its `IterateAllTableItems` funcation is always reading the latest infoschema.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: fix snapshot read bug for information_schema.tables

- br/pkg/streamhelper/advancer_daemon.go
Issue Number: close #42419
When the owner get evicted but not restarted, its checkpoint metric may consist. 
```commit-message
This PR make the owner remove the last checkpoint when it loses its ownership.
```
Tests 
(I think this could be covered by the existing tests in AdvancerDaemon.)
(TBD)
```release-note
Fixed a bug that may cause PITR lag in the metrics grows too high when TiDB stop.
```
> streamhelper/advancer: Fix owner transfer metric

- lightning/tests/README.md
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: update README to help newcomer run lightning integration tests

- pkg/planner/core/integration_test.go
- pkg/planner/core/logical_plan_builder.go
Issue Number: close #53967
IF:
Virtual generated column B depends on A
Virtual generated column C depends on B
Index idx on C.
Update A should update index idx too.
but the dependence C on B is not built correctly.
Build dependence correctly.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> core: fix missing update on nested generated column

- pkg/statistics/table.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: remove useless function

- pkg/expression/contextstatic/BUILD.bazel
- pkg/expression/contextstatic/evalctx.go
- pkg/expression/contextstatic/evalctx_test.go
- pkg/expression/contextstatic/exprctx.go
- pkg/expression/contextstatic/exprctx_test.go
- pkg/util/deeptest/statictesthelper.go
- pkg/util/deeptest/statictesthelper_test.go
Issue Number: close #55799
Sometimes we need to load state of `StaticExprContext/EvalContext` from system variables, just like in lightning:
https://github.com/pingcap/tidb/blob/df02db014ac68614909de4c728593d843a8c4d0f/pkg/lightning/backend/kv/session.go#L327-L357
- This PR introduces a new method `LoadSystemVars` to `StaticExprContext` and `StaticEvalContext` to load state from system variables.
- Also do some modifies in `deeptest` to make it easier to use.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: `StaticExprContext/EvalContext` support to load state from system variables

- tests/integrationtest/run-tests.sh
Problem Summary: check remained lines after all test cases finished. See https://github.com/pingcap/mysql-tester/pull/132 get detail.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> integration_test: update mysql-tester

- pkg/ttl/cache/split_test.go
Issue Number: close #55862
Add case to test `varbinary` to split TTL task.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: add `varbinary` case for `TestSplitTTLScanRangesWithBytes`

- pkg/executor/infoschema_reader.go
Issue Number: close #55867
Privilege checker should keep the same behavior as normal path.
https://github.com/pingcap/tidb/blob/487ef06b7a49c70b77fe4ede8ab6756fdceaaa3e/pkg/executor/infoschema_reader.go#L588-L590
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix unstable TestShowViewPriv

- pkg/executor/batch_point_get.go
- pkg/executor/builder.go
- pkg/executor/index_merge_reader.go
- pkg/executor/internal/exec/BUILD.bazel
- pkg/executor/internal/exec/indexusage.go
- pkg/executor/internal/exec/indexusage_test.go
- pkg/executor/point_get.go
- pkg/executor/table_reader.go
- pkg/planner/core/physical_plans.go
Issue Number: close #55601
Record the index usage for primary keys.
Also record the scanned rows for clustered primary key in the following executors:
1. `TableReaderExecutor`.
2. `IndexMergeExecutor`.
Tests 
> 
Side effects
Documentation
```release-note
Record the index usage statistics for the clustered primary keys
```
> executor: record index usage for the clustered primary keys

- pkg/executor/join/base_join_probe.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/join_row_table_test.go
Fix a bug introduced by #55525
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix index out of range bug in hash join v2

- pkg/executor/join/base_join_probe.go
- pkg/executor/join/inner_join_probe.go
- pkg/executor/join/outer_join_probe.go
- pkg/executor/join/row_table_builder_test.go
In previous implementation, probe will new a lots of small objects, this pr avoid this by reuse them.
Test Dataset: tpch-50
Test Query: `select /*+ hash_join(orders) */ count(*) from orders join lineitem on l_orderkey = o_orderkey`
Before this pr
After this pr
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: avoid new small objects in probe stage of hash join v2

- pkg/ddl/partition.go
- pkg/ddl/util/schema_change_notifier.go
- pkg/statistics/handle/ddl/BUILD.bazel
- pkg/statistics/handle/ddl/ddl.go
- pkg/statistics/handle/ddl/drop_partition.go
- pkg/statistics/handle/ddl/truncate_partition.go
- pkg/statistics/handle/util/ddl_event.go
Issue Number: ref #55723
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl, stat: switch to new struct for add/truncate/drop partition

- br/pkg/aws/BUILD.bazel
- br/pkg/aws/ebs.go
…Snapshot
Issue Number: close #55672
In the past, we use the default retry strategy to back off when create snapshot failed. But the quota for `CreateSnapshots` is pretty low. Hence sometimes we exceeded the retry limit.
Also there isn't any log when encountered issues, we need log them.
Tests 
(TBD)
> 
Side effects
Documentation
```release-note
None
```
> br/ebs: added log for EBS snapshot creation, increase backoff time for creating snapshot

- pkg/executor/show_placement.go
Issue Number: ref #55945
Tests 
- tcms case [placement-in-sql-common-cases](https://tcms.pingcap.net/dashboard/executions/case/12104510)
> 
Side effects
Documentation
```release-note
None
```
> placement: return state instead of schedule

- pkg/ddl/BUILD.bazel
- pkg/ddl/backfilling.go
- pkg/ddl/backfilling_scheduler.go
- pkg/ddl/backfilling_test.go
- pkg/ddl/column.go
- pkg/ddl/index.go
- pkg/ddl/partition.go
- pkg/ddl/reorg.go
- pkg/table/context/BUILD.bazel
- pkg/table/context/buffers.go
Issue Number: ref #53388
This PR:
- Introduces `reorgTableMutateContext` as the `table.MutateContext` to provide context for DDL reorg
- remove `newReorgSessCtx` from production code.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: remove `mock.Context` from DDL reorg

- pkg/executor/detach_integration_test.go
- pkg/expression/builtin_other.go
- pkg/expression/builtin_other_vec.go
- pkg/expression/context/context.go
- pkg/expression/contextsession/sessionctx.go
- pkg/expression/contextsession/sessionctx_test.go
- pkg/expression/contextstatic/evalctx.go
- pkg/expression/contextstatic/evalctx_test.go
- pkg/planner/core/expression_rewriter.go
- pkg/planner/core/expression_test.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/session_test.go
- pkg/testkit/BUILD.bazel
- pkg/testkit/testkit.go
Issue Number: close #55865
This PR adds new method `GetUserVarsReader` to `EvalContext` so that the user vars can be read directly from the context. It has some benefits:
1. `BuildSimpleExpr` can now build expressions like `@a+1` without adding optional property `SessionVars` to the inner context.
2. We can evaluate an expression like `@a+1` or `get_var("a")` without requiring an additional property `SessionVars` in `EvalContext`.
3. Lazy cursor fetch can now support SQL with user vars.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: Add `GetUserVarsReader` to `EvalContext`

- pkg/expression/column.go
- pkg/expression/column_test.go
- pkg/expression/constant.go
- pkg/expression/constant_test.go
- pkg/expression/expression.go
- pkg/expression/scalar_function.go
- pkg/expression/scalar_function_test.go
- pkg/expression/util_test.go
- pkg/parser/types/field_type.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/scalar_subq_expression.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: introduce hashEquals interface for expression.Expression

- pkg/statistics/handle/cache/statscache.go
Issue Number: ref #54552
Let's first increase the synchronization offset size to reduce the likelihood of resynchronization.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statstics: increase the synchronization offset size when to sync stats

- pkg/executor/adapter.go
- pkg/metrics/executor.go
- pkg/metrics/grafana/tidb.json
- pkg/metrics/server.go
- pkg/server/conn.go
- pkg/server/metrics/metrics.go
Issue Number: close #55875
Set it in executor.
Tests 
2. use multi-queries to insert data, e.g. insert; insert; insert;
3. compare QPS(insert) and Affected Rows(insert)
This PR:
Master:
> 
Side effects
Documentation
```release-note
None
```
> *: fix affected rows metrics to make it compatiable with multi-queries

- br/pkg/restore/ingestrec/ingest_recorder_test.go
- br/pkg/stream/rewrite_meta_rawkv_test.go
- pkg/ddl/delete_range.go
- pkg/ddl/executor.go
- pkg/ddl/foreign_key.go
- pkg/ddl/index_test.go
- pkg/ddl/job_scheduler.go
- pkg/ddl/job_submitter.go
- pkg/ddl/job_submitter_test.go
- pkg/ddl/restart_test.go
- pkg/ddl/sanity_check.go
- pkg/ddl/schema.go
- pkg/ddl/schema_test.go
- pkg/ddl/schema_version.go
- pkg/ddl/stat_test.go
- pkg/ddl/table.go
- pkg/ddl/table_test.go
- pkg/ddl/tests/partition/db_partition_test.go
- pkg/meta/model/BUILD.bazel
- pkg/meta/model/job.go
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
- pkg/meta/model/job_test.go
- pkg/store/gcworker/gc_worker.go
Issue Number: ref https://github.com/pingcap/tidb/issues/53930
- args v2 for `create-schema`/`drop-schema`/`modify schema charset or collate` / `modify schema placement`
- remove ArgsV2/RawArgsV2, we can reuse Args/RawArgs actually
- add `FinishedJobArgs` interface for jobs that need to save some info after job finish
- add some senity check
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: args v2 for create/drop/modify schema

- expression/builtin_compare.go
- expression/builtin_compare_test.go
- expression/builtin_control.go
- expression/expr_to_pb_test.go
- expression/typeinfer_test.go
cherry-pick of https://github.com/pingcap/tidb/pull/48032
Issue Number: close #46475
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: fix the return type of coalesce when arg type is DATE | tidb-test=pr/2386

- pkg/statistics/handle/autoanalyze/internal/heap/BUILD.bazel
- pkg/statistics/handle/autoanalyze/internal/heap/heap.go
- pkg/statistics/handle/autoanalyze/internal/heap/main_test.go
Just reorder the generic parameters of the heap. <V,K> -> <K,V>.
When I wrote this code, I thought it didn't matter, but it was kind of annoying when I tried to use it. So it's better to keep it like any other normal heap.
Also, I added `main_test` to check the goroutine leak.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: reorder key and value generic parameters of the heap

- pkg/executor/BUILD.bazel
- pkg/executor/import_into.go
- pkg/executor/import_into_test.go
- pkg/executor/importer/import.go
- pkg/lightning/backend/kv/session.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/planbuilder_test.go
- tests/realtikvtest/importintotest/import_into_test.go
Issue Number: close #55497
This PR does a complete check for column assignments in `IMPORT INTO ...`, it:
- Disallow subquery, column reference, system vars access... in planner pahse.
- Because import into is running across node, it uses a ctx that provides restricted fields. So we also check the `RequiredOptionalEvalProps`  of the expressions to match the context.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> importinto: check column assignment expressions in `import into ...`

- pkg/session/session.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar_test.go
Issue Number: close #55981
Some internal sessions may not set `EnableWindowFunction` correctly.
As a result, the binding containing window functions might fail at <=v6.5.10 and <=v7.5.3 and <=v7.1.5
Tests 
> 
Side effects
Documentation
```release-note
None
```
> session: set EnableWindowFunction for all SessionVars

- expression/builtin_compare.go
- expression/builtin_compare_test.go
- expression/builtin_control.go
- expression/expr_to_pb_test.go
- expression/typeinfer_test.go
cherry-pick of https://github.com/pingcap/tidb/pull/48032
Issue Number: close https://github.com/pingcap/tidb/issues/46475
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: fix the return type of coalesce when arg type is DATE | tidb-test=pr/2387

- pkg/metrics/grafana/tidb_runtime.json
Add a panel for sync mutex wait seconds.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> pkg/metrics: add a panel for sync mutex wait

- pkg/tablecodec/tablecodec.go
Issue Number: ref #43249
CutIndexKeyNew decode the value, but discard the value. It cause unnecessary allocations.
```
_, b, err := CutIndexKeyNew(key, colsLen)
```
Before vs After:
Tests 
```
func BenchmarkUnionScanRead(b *testing.B) {
store := testkit.CreateMockStore(b)
tk := testkit.NewTestKit(b, store)
tk.MustExec("use test")
tk.MustExec(`create table t_us (
a int,
c1 varchar(10),
c2 varchar(30),
c3 varchar(1),
c4 varchar(12),
c5 varchar(10),
c6 datetime,
index k(a));`)
tk.MustExec(`begin;`)
for i := 0; i < 8000; i++ {
tk.MustExec(fmt.Sprintf("insert into t_us values (%d, '54321', '1234', '1', '000000', '7518', '2014-05-08')", i))
}
b.ReportAllocs()
b.ResetTimer()
for i := 0; i < b.N; i++ {
// tk.MustQuery("select * from t_us where c1 = '12345'").Check(testkit.Rows()) …
```
> tablecodec: optimize DecodeIndexHandle to avoid unnecessary allocation

- pkg/statistics/handle/bootstrap.go
…
Issue Number: close #55684 
The old init stats doesn't handle the collation string.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: fix the error that init stats might got failure when decoding column bucket

- pkg/executor/internal/querywatch/query_watch.go
When using `QUERY WATCH ADD RESOURCE GROUP default SQL TEXT EXACT TO 'select * from sbtest.sbtest1';` will add local time
```
mysql> SELECT * FROM INFORMATION_SCHEMA.RUNAWAY_WATCHES ORDER BY id\G
*************************** 1. row ***************************
ID: 1
RESOURCE_GROUP_NAME: default
START_TIME: 2024-09-11 07:38:09
END_TIME: 2024-09-11 07:48:09
WATCH: Exact
WATCH_TEXT: select sleep(2) from t
SOURCE: 127.0.0.1:4000
ACTION: Kill
*************************** 2. row ***************************
ID: 2
RESOURCE_GROUP_NAME: default
START_TIME: 2024-09-11 15:38:20
END_TIME: UNLIMITED
WATCH: Exact
WATCH_TEXT: select * from sbtest.sbtest1
SOURCE: manual
ACTION: Kill
2 rows in set (0.00 sec)
```
```bash
mysql> SELECT * FROM INFORMATION_SCHEMA.RUNAWAY_WATCHES ORDER BY id\G …
```
> runaway: change `QUERY WATCH` time type to UTC

- pkg/lightning/common/retry.go
updating this PR: https://github.com/pingcap/tidb/pull/53043
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Lightning: add retry if transaction failed while fetching task metas

- pkg/ddl/create_table.go
- pkg/ddl/ddl.go
- pkg/ddl/executor.go
- pkg/ddl/schematracker/checker.go
- pkg/executor/test/ddl/BUILD.bazel
- pkg/executor/test/ddl/ddl_test.go
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #55716
Tests 
> 
Side effects
Documentation
```release-note
Introduced variables `tidb_shard_row_id_bits` and `tidb_pre_split_regions`, to change the default values of `shard_row_id_bits` and `pre_split_regions`, avoiding setting them individually for each table.
```
> *: set default shard_row_id_bits and pre_split_regions for all tables 

- pkg/executor/test/seqtest/seq_executor_test.go
Issue Number: close #55828 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix unstable TestAdminShowNextID

- pkg/executor/detach_integration_test.go
- pkg/expression/BUILD.bazel
- pkg/expression/builtin_time.go
- pkg/expression/helper.go
- tests/integrationtest/r/ddl/db_change.result
- tests/integrationtest/t/ddl/db_change.test
Issue Number: close #56051, close #56054
Fix all strong assumptions of the location of the return value of `getStmtTimestamp`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: fix expression return wrong current time when using `StaticEvalContext`

- pkg/planner/core/planbuilder.go
- tests/integrationtest/r/executor/import_into.result
- tests/integrationtest/t/executor/import_into.test
Issue Number: close #55970
add a check in plan build
Tests 
> 
Side effects
Documentation
```release-note
None
```
> importinto: fix panic when import to a temporary table, disallow import to cached table

- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
- pkg/statistics/table.go
In this pull request, I attempted to utilize table statistics to obtain the column number instead of relying on the table information schema. This approach would eliminate the need to retrieve the table information schema when updating the analysis job based on the new table row count.
See: https://github.com/pingcap/tidb/pull/55889/files#r1756288302
We only need ColNum here because every time we create a table or a new column, we will also create a histogram record for it. After that, we will load it into memory(If it has udpate). So, usually, it is the same as the column number from the table information schema.
Tests 
> 
Side effects
Documentation …
> statistics: do not depend on table information when calculating the table size

- pkg/executor/slow_query_test.go
- pkg/infoschema/internal/testkit.go
- pkg/infoschema/tables.go
- pkg/infoschema/test/clustertablestest/tables_test.go
- pkg/sessionctx/variable/session.go
- pkg/util/processinfo.go
Issue Number: ref #55542
In #55455, we added tidb/tikv cpu usages into several system table. During document review process, we discussed the display details, and want to do some display changes: https://github.com/pingcap/docs-cn/pull/18527. Mainly two points:
1. Use nanoseconds instead of seconds to display processlist's tidb/tikv cpu time
2. Change the slow log field names from **tidb_cpu_usage** to **tidb_cpu_time**, **tikv_cpu_usage** to **tikv_cpu_time**
The display will look like this:
Tests 
> 
Side effects
Documentation …
> *: Change cpu usages related representation format

- pkg/executor/partition_table_test.go
Problem Summary: add more test cases for `select for update` with `global index`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: add more tests for `select for update` with `global index`

- br/pkg/restore/import.go
Issue Number: ref #54426
For incremental restore, we need add new timestamp to rewrite rule used for download SST.
Add new timestamp to rewrite rule used for download SST.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: add new timestamp for download sst rewrite rule

- pkg/distsql/BUILD.bazel
- pkg/distsql/distsql_test.go
- pkg/distsql/request_builder.go
- pkg/executor/analyze_col.go
- pkg/executor/distsql.go
- pkg/executor/index_merge_reader.go
- pkg/executor/table_reader.go
- pkg/executor/test/executor/executor_test.go
- pkg/executor/test/splittest/split_table_test.go
- pkg/kv/BUILD.bazel
- pkg/kv/kv.go
- pkg/store/copr/BUILD.bazel
- pkg/store/copr/coprocessor.go
- pkg/store/copr/region_cache.go
Issue Number: close #55957 
In 8.1 and earlier versions, during building cop tasks, tidb needs to split key ranges. Tidb may use rpc to connect pd to get latest region info one by one, and this will cost too much time if tidb needs to load many regions' info. Even worse, tidb won't check the sqlkiller signal during this process, so the query won't be killed until the spliting key ranges work is done.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that query won't be killed during building coprocessor tasks process.
```
> *: Check sqlkiller status during split region process

- pkg/ddl/db_change_test.go
- pkg/executor/show.go
- pkg/executor/show_test.go
- pkg/executor/test/seqtest/seq_executor_test.go
- pkg/planner/core/planbuilder.go
- tests/integrationtest/r/ddl/multi_schema_change.result
- tests/integrationtest/r/ddl/primary_key_handle.result
- tests/integrationtest/r/executor/executor.result
- tests/integrationtest/r/executor/show.result
- tests/integrationtest/r/session/clustered_index.result
No info about index if its global or not , added in show index in this pr
Issue Number: ref #55452
added Global index from index info
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Add Global to SHOW INDEX output | tidb-test=pr/2391

- pkg/executor/importer/BUILD.bazel
- pkg/executor/importer/chunk_process.go
Issue Number: ref #55970 
use wrapped error group
Tests 
manually revert https://github.com/pingcap/tidb/pull/55983 , and import into a global temp table, now we can capture panic
```
mysql> create global temporary table temp (a varchar(100), b varchar(100), c varchar(100)) on commit delete rows;
Query OK, 0 rows affected (0.06 sec)
mysql> import into temp from '/Users/jujiajia/playground/lightning/single-file/test.t.1.csv';
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```
> 
Side effects
Documentation …
> importinto: protect panic from encode loop

- pkg/meta/model/job.go
in https://github.com/pingcap/tidb/pull/55754, some deprecated JobActionType is renamed to be unexported, but CDC actually depends on it, so rename it back
Tests 
> 
Side effects
Documentation
```release-note
None
```
> meta: export some deprecated action types for cdc

- pkg/expression/expr_to_pb_test.go
- pkg/expression/infer_pushdown.go
Issue Number: close #56173
The root cause is TiFlash does not support json compare, it just use string compare instead. So currently, we need disable pushing down such functions to TiFlash
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: disable some json function from pushdown to TiFlash

- pkg/expression/builtin_arithmetic.go
- pkg/expression/typeinfer_test.go
- tests/integrationtest/r/executor/issues.result
- tests/integrationtest/t/executor/issues.test
Issue Number: close #55837
In MySQL, it support minimum display length when creating a integer type, for example, you can create table with type `col1 bigint(4)`, it means the display length of col1 should be at least 4.
However, TiDB just treated `4` as the flen of the current type, which will cause wrong result in some cases, since `4` here does not mean the max length of `col1` is 4: for example, in #55837 a column is declared as `ts bigint(4)`, so tidb think the result type of `ts/1000` is `Decimal(9,4)`, which is obviousely wrong, and caused the wrong result.
Since the root cause of #55837 is when user declare an interger type with minimun display length, TiDB actually treated the minimum display length as the `max length` of the given type, a complete fix should be …
> expresssion: fix div result type infer bug if a integer type has minimum display length

- pkg/planner/core/rule_partition_processor.go
Issue Number: close #55630
Prepared statements would always fail partition pruning due to being a prepared statement and parameters not being considered to be constant.
Tests 
> 
Manual test, see #55630, i.e. using sysbench.
Side effects
Documentation
```release-note
None
```
> planner: Removed check for prepared stmt during partition pruning

- pkg/ddl/index_merge_tmp.go
- pkg/ddl/tests/indexmerge/BUILD.bazel
- pkg/ddl/tests/indexmerge/merge_test.go
Issue Number: close #56161
Problem Summary: when merge-temp-index workers check duplicate index keys, they use `BatchGet()` to get index KV from the origin index and record them as a map. However, this map is not updated while handling temp index records, there may be a false-positive detection.
For example, we have `{key_1 -> handle_1, key_2 -> handle_2}`. If there is a temp index record like `key_1 -> handle_3`, then there is a duplicate key. 
In this issue, we have two temp index records:
```
key_1 -> handle_1(deleted)
key_1 -> handle_2
```
The first record passes the check because a delete operation cannot cause a duplicate key. The second record fails the check because `handle_2 != handle_1`, even if `handle_1` is deleted in the previous operation.
Maintain the map while handling, …
> ddl: fix unexpected duplicate entry error when adding unique index

- pkg/executor/adapter.go
Before switching, verify the existence of the resource group. If the specified resource group does not exist, take no action.
Tests 
Before:
After:
```release-note
None
```
> executor: verify the existence of the resource group before switching

- pkg/session/bootstrap.go
Issue Number: close #56106.
Extend the length of `VARCHAR` for the `action` column to fix the truncation.
Tests 
Before:
After:
```release-note
None
```
> session: extend the length of action column to fix the truncation

- pkg/metrics/grafana/performance_overview.json
Issue Number: close #56213
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: adjust the position of duration panel in performance overview.

- dumpling/export/writer_util.go
Issue Number: close #54624
Fix the inaccurate calculation of file size in CSV format writer
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dumpling: fix the inaccurate calculation of file size in csv format writer

- pkg/ddl/tests/tiflash/ddl_tiflash_test.go
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
Issue Number: ref #53930 
introduced in https://github.com/pingcap/tidb/pull/56163, we need to make sure that PartInfo is not nil for DropPartition and roll-backing AddPartition, for v1 we have make sure it already, but forget v2
Tests 
run TestAddPartitionReplicaBiggerThanTiFlashStores with v1/v2, make sure it pass
run TestTiFlashReorgPartition with v2, pass
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix panic in TablePartitionArgs v2

- pkg/ddl/create_table.go
- pkg/ddl/db_cache_test.go
Issue Number: close #56134
Use 'create table like'  to copy a cached table, the new table should be a normal table.
This behavior is just like using migrate tools, treat cached tables as normal tables in those scenarios.
https://docs.pingcap.com/tidb/v8.3/cached-tables#compatibility-with-tidb-migration-tools 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix 'create table like' for cached table

- pkg/executor/builder.go
- pkg/executor/join/BUILD.bazel
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/joinversion/BUILD.bazel
- pkg/executor/join/joinversion/join_version.go
- pkg/executor/test/issuetest/executor_issue_test.go
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
- pkg/executor/test/seqtest/seq_executor_test.go
- pkg/sessionctx/variable/BUILD.bazel
- pkg/sessionctx/variable/session.go
- pkg/sessionctx/variable/setvar_affect.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/sysvar_test.go
- pkg/sessionctx/variable/tidb_vars.go
- tests/integrationtest/r/sessionctx/setvar.result
- tests/integrationtest/t/sessionctx/setvar.test
This pr add a session variable for hash join v2, and set the to false by default.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Add session variable for hash join v2

- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #53460
Reset the default value of auto analyze to 1, thereby maintaining consistency with previous behavior.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> variable: set default tidb_auto_analyze_concurrency as 1

- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/calculatoranalysis/calculator_analysis_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/refresher/worker_test.go
1. Added the SetIndicators API to update the indicators of jobs.
2. Added a util function `IsDynamicPartitionedTableAnalysisJob` to check if the job is a dynamic partitioned table analysis job.
Check https://github.com/pingcap/tidb/pull/55889/files#r1772550852 to see how we use it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add the SetIndicators API

- pkg/planner/core/find_best_task.go
- pkg/planner/core/logical_plans_test.go
- pkg/planner/core/mock.go
Issue Number: ref #52061
Problem Summary: Because we didn't consider `mergeSort` cost for many executors and it's not easy to fix it right now, see [comments](https://github.com/pingcap/tidb/issues/52061#issuecomment-2362859572). So we decided to consider a path is global index or not in `skylinePruning` function.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: consider path is global index path or not in `skylinePruning` function

- pkg/executor/executor.go
- pkg/planner/core/planbuilder.go
- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/options.go
- pkg/planner/indexadvisor/options_test.go
Problem Summary: planner: support `recommend index show` to show all options
planner: support `recommend index show` to show all options
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: support `recommend index show` to show all options

- pkg/executor/join/base_join_probe.go
- pkg/executor/join/hash_join_v2.go
- pkg/executor/join/outer_join_probe.go
Clear some probe state after probe is done
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: clear probe state after probe is done

- pkg/store/driver/tikv_driver.go
Issue Number: close #55872.
The original pd client uses the default `MaxCallRecvMsgSize` which is 4MB.
Tests 
> 
1. `tiup playground nightly --kv 3 --pd 1 --db 1 --tiflash 0 --host 10.2.8.101`
2. `mysql -h 10.2.8.101 -P 43099 -u root -D test --comments -e "create table t(id bigint primary key)"`
3. execute the following command and wait for it to finish
```
for i in {1..100}
do
mysql -h 10.2.8.101 -P 43099 -u root -D test --comments -e "SPLIT TABLE t BETWEEN ($(($i))000000) AND ($(( $i + 1 ))000000) REGIONS 1000" > /dev/null &
done
```
4. call the API
```
curl http://10.2.8.101:33613/tables/test/t/regions
{
"name": "t",
"id": 110,
"record_regions": [
{
"region_id": 1358901,
"leader": {
"id": 1358902,
"store_id": 1
}, …
```
> store/driver: set `MaxCallRecvMsgSize` to `MaxInt32` for pd client

- pkg/executor/show_placement.go
- pkg/executor/show_placement_test.go
Issue Number: ref #55394 
Tests 
original show placement test
> 
Side effects
Documentation
```release-note
None
```
> infoschema_v2: remove schemaTableInfos call of fetchAllTablePlacements

- pkg/infoschema/infoschema.go
- pkg/infoschema/infoschema_test.go
- pkg/infoschema/infoschema_v2.go
- pkg/infoschema/infoschema_v2_test.go
- pkg/infoschema/interface.go
This PR introduced a new API to query the database name using the table ID. This API will be used in the new priority queue implementation. 
Because we want to avoid fetching table information as much as possible. So we need to add this new API to achieve it.
Check https://github.com/pingcap/tidb/pull/55889/files#r1766302195 out to see how we use it in the new priority queue.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: add the SchemaNameByTableID API

- pkg/executor/BUILD.bazel
- pkg/executor/simple.go
- pkg/session/BUILD.bazel
Issue Number: close #56271
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix forget to release session

- pkg/executor/builder.go
- pkg/executor/executor.go
- pkg/parser/ast/misc.go
- pkg/parser/misc.go
- pkg/parser/parser.y
- pkg/parser/parser_test.go
- pkg/planner/core/common_plans.go
- pkg/planner/core/planbuilder.go
- pkg/planner/indexadvisor/BUILD.bazel
- pkg/planner/indexadvisor/indexadvisor.go
- pkg/planner/indexadvisor/indexadvisor_test.go
- pkg/planner/indexadvisor/indexadvisor_tpch_test.go
- pkg/planner/indexadvisor/options.go
- pkg/planner/indexadvisor/options_test.go
Problem Summary: planner: support using `with <opt>=<val>` to set options when running index advisor
planner: support using `with <opt>=<val>` to set options when running index advisor.
For example: `recommend index with max_num_index=5`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: support using `with <opt>=<val>` to set options when running index advisor

- pkg/metrics/grafana/tidb_resource_control.json
Issue Number: ref #56019
New panel:
Alter adjust the order of background tasks panels:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> resource_control: add new grafana panel for background task utilization

- pkg/ddl/schema_test.go
Issue Number: ref #55446 #56128
Move session outside to avoid infoschema v1/v2 switch. This is just a workaround.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix flaky TestRenameTableAutoIDs

- pkg/ddl/add_column.go
- pkg/expression/integration_test/BUILD.bazel
- pkg/expression/integration_test/integration_test.go
- pkg/table/column.go
Issue Number: ref https://github.com/pingcap/tidb/issues/54245
In non-strict mode, 0-sized vector may be wrongly inserted into a Non-Zero-Sized vector column:
```sql
set @session.sql_mode='';
create table x(e vector(3) not null comment 'hnsw(distance=l2)');
insert into x values();
```
Forbid such values in any SQL modes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: Fix possibly invalid vector default values

- pkg/lightning/backend/local/local.go
- pkg/lightning/backend/local/local_test.go
- pkg/lightning/backend/local/region_job.go
- tests/realtikvtest/addindextest3/ingest_test.go
Issue Number: close #55808
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: fix forget to set lastRetryableErr when ingest RPC fail 

- br/pkg/lightning/backend/local/BUILD.bazel
- br/pkg/lightning/backend/local/local.go
- br/pkg/lightning/backend/local/local_test.go
- br/pkg/lightning/backend/local/region_job.go
- tests/realtikvtest/addindextest4/ingest_test.go
Issue Number: close #55808
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: fix forget to set lastRetryableErr when ingest RPC fail (#56345)

- pkg/executor/BUILD.bazel
- pkg/executor/test/txn/BUILD.bazel
- pkg/executor/test/txn/main_test.go
- pkg/executor/test/txn/txn_test.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/casetest/enforcempp/enforce_mpp_test.go
- pkg/planner/core/tests/extractor/BUILD.bazel
- pkg/planner/core/tests/extractor/main_test.go
- pkg/planner/core/tests/extractor/memtable_infoschema_extractor_test.go
Issue Number: close #56352
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: move some test into tests package

- pkg/planner/cardinality/row_count_index.go
- pkg/planner/core/casetest/index/index_test.go
- pkg/util/ranger/types.go
…(#56117)
Issue Number: close https://github.com/pingcap/tidb/issues/56116
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix unique key get wrong row count when to query the NULL value | tidb-test=2eb0d03843bfec7539602dada4f96ea2ee982c0e

- pkg/owner/BUILD.bazel
- pkg/owner/manager.go
- pkg/owner/manager_test.go
Issue Number: close #56053
Problem Summary: **`m.campaignCancel`** is currently set in `campaignLoop` goroutine, which might happen after calling `campaignCancel()` that access **`m.campaignCancel`**, even though it is called after `CampaignOwner()`.
Set **`m.campaignCancel`** in `CampaignOwner()` rather than in `campaignLoop` goroutine, to ensure a `campaignCancel()` called after `CampaignOwner()` can always access **`m.campaignCancel`** instead of nil.
Tests 
Side effects
Documentation
```release-note
None
```
> owner: fix data race on ownerManager.campaignCancel

- pkg/parser/mysql/charset.go
- pkg/planner/core/memtable_infoschema_extractor.go
- tests/integrationtest/r/infoschema/infoschema.result
- tests/integrationtest/t/infoschema/infoschema.test
Issue Number: close #56377
There are two problems with #55844:
- When pattern match is pushed down to memory table reader, it is case sensitive. For example, `LIKE '%T'` cannot match `"tt"`.
- Pattern match does not work for the fast path introduced by #55574.
- Make memory table reader pattern match case-insensitive.
- Consider pattern match when filtering schema object.
- Sort the result returned from `ListSchemasAndTables` to make test stable.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: make pattern match case-insensitive for some infoschema tables

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/domain/domain.go
- pkg/domain/domain_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
- pkg/sessionctx/variable/varsutil.go
Issue Number: close #55989
Tests 
if disable this variable, you cannot find the auto-analyze stack in the profiler.
> 
Side effects
Documentation
```release-note
config: make tidb_enable_ddl controlling the stats owner
```
> config: make tidb_enable_stats_owner controlling the stats owner

- pkg/metrics/grafana/tidb_resource_control.json
- pkg/metrics/grafana/tidb_resource_control.jsonnet
Issue Number: close #56368
NOTE: some new metrics depends on the change of https://github.com/tikv/tikv/pull/17590
Tests 
> 
Side effects
Documentation
```release-note
None
```
> metrics: add metrics for priority resource control

- pkg/session/bootstrap.go
Issue Number: close #56375
Used the wrong mutex key. 
Tests 
Start a v8.3.0 tidb cluster and upgrade.
> 
Side effects
Documentation
```release-note
None
```
> session: fix wrong etcd mutex key

- pkg/ddl/add_column.go
- pkg/ddl/cluster.go
- pkg/ddl/column.go
- pkg/ddl/constraint.go
- pkg/ddl/create_table.go
- pkg/ddl/delete_range.go
- pkg/ddl/foreign_key.go
- pkg/ddl/index.go
- pkg/ddl/job_scheduler.go
- pkg/ddl/job_worker.go
- pkg/ddl/modify_column.go
- pkg/ddl/multi_schema_change.go
- pkg/ddl/partition.go
- pkg/ddl/placement_policy.go
- pkg/ddl/resource_group.go
- pkg/ddl/rollingback.go
- pkg/ddl/schema.go
- pkg/ddl/schema_version.go
- pkg/ddl/sequence.go
- pkg/ddl/table.go
- pkg/ddl/table_lock.go
- pkg/ddl/ttl.go
- make meta mutator part of jobContext to avoid passing everywhere
- move job logger from worker to jobContext
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: make meta mutator part of jobContext

- pkg/ddl/ddl_test.go
- pkg/ddl/executor.go
- pkg/ddl/job_submitter.go
- pkg/ddl/job_submitter_test.go
- pkg/ddl/job_worker_test.go
- pkg/ddl/restart_test.go
- pkg/ddl/schema_test.go
Issue Number: ref #53930 
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: use JobArgs in job wrapper and use doDDLJob2 for some job type

- br/pkg/task/restore_raw.go
when tikv region has empty endKey, the br split region will failed due to empty key
Issue Number: close https://github.com/pingcap/tidb/issues/56228
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix region split failure due to empty split key

- pkg/ddl/testargsv1/BUILD.bazel
Issue Number: ref #53930 
if we don't add it, bazel complains that
```
pkg/ddl/ddl.go:42:2: "github.com/pingcap/tidb/pkg/ddl/testargsv1" imported as empty and not used
pkg/ddl/ddl.go:803:6: undefined: testargsv1
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> bazel: add files for build tags

- pkg/kv/option.go
- pkg/server/conn_test.go
- pkg/server/server.go
- pkg/session/session.go
- pkg/sessionctx/context.go
- pkg/sessiontxn/isolation/BUILD.bazel
- pkg/sessiontxn/isolation/base.go
- pkg/store/driver/txn/txn_driver.go
- pkg/util/mock/context.go
Issue Number: close #55607
TiDB will leak some lock if the transaction is not committed/rollbacked successfully. The graceful shutdown routine didn't wait for the background async-commit (and secondary key lock cleanup) goroutines to finish, so it'd be better to also wait for them to avoid leaking the locks.
Use the hooks of the async-commit / secondary lock cleanup goroutines to track the lifecycle of them.
Tests 
> 
TODO
Side effects
Documentation
```release-note
Fix the issue that stopping TiDB may leak the transaction lock.
```
> server: add hooks to wait for background commit goroutines

- pkg/distsql/request_builder.go
- pkg/executor/distsql.go
- pkg/executor/executor_pkg_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56440
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: track the memory usage for building range in IndexLookUpExecutor | tidb-test=2eb0d03843bfec7539602dada4f96ea2ee982c0e

- pkg/parser/parser.y
- pkg/parser/parser_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56428
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: make HNSW as vector index default type

- pkg/executor/insert_common.go
- pkg/executor/test/loaddatatest/BUILD.bazel
- pkg/executor/test/loaddatatest/load_data_test.go
Issue Number: close #56408
The reason is the bool flag returned by `removeRow` was not rightly handled  in `handleDuplicateKey`. 
```
// removeRow removes the duplicate row and cleanup its keys in the key-value map.
// But if the to-be-removed row equals to the to-be-added row, no remove or add
// things to do and return (true, nil).
```
If we load a existed row, `removeRow` will return (true, nil), `handleDuplicateKey` should also return (true, nil) 
Tests 
> 
Side effects
Documentation
```release-note
Fix data inconsistency after load data …
```
> executor: fix data inconsistency after `load data ... replace into ...`

- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/calculatoranalysis/calculator_analysis_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_v2.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_v2_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/worker_test.go
- pkg/statistics/handle/cache/statscache.go
- pkg/statistics/handle/types/interfaces.go
This PR split from https://github.com/pingcap/tidb/pull/55889.
This pull request addresses the processing of DML changes from the stats cache. It is a continuation of the work started in [PR #55889](https://github.com/pingcap/tidb/pull/55889).
- Added functionality to process DML changes, including fetching and updating timestamps, and handling table stats.
- Added tests for processing DML changes.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: process DML changes in the new PQ

- pkg/util/execdetails/execdetails.go
- pkg/util/execdetails/execdetails_test.go
Issue Number: close #56445
Print the correct `Commit_primary_rpc_detail`, which is different from `Slowest_prewrite_rpc_detail`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> slowlog: print correct `Commit_primary_rpc_detail`

- pkg/util/execdetails/execdetails.go
- pkg/util/execdetails/execdetails_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/54245
Cherry-pick: https://github.com/tidbcloud/tidb-cse/pull/913 https://github.com/tidbcloud/tidb-cse/pull/925
Add a couple of metrics for benchmarking with vector scan.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> execdetails: Display vector search info in EXPLAIN ANALYZE

- pkg/ddl/tests/partition/db_partition_test.go
Issue Number: close #54759
Unstable test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: Stabilized TestRemovePartitioningAutoIDs test.

- br/pkg/checkpoint/checkpoint.go
- br/pkg/checkpoint/checkpoint_test.go
- br/pkg/checkpoint/external_storage.go
- br/pkg/checkpoint/log_restore.go
- br/pkg/checkpoint/restore.go
- br/pkg/checkpoint/storage.go
- br/pkg/restore/log_client/client.go
- br/pkg/restore/snap_client/client.go
- br/pkg/task/restore.go
- br/pkg/task/stream.go
Issue Number: close #56488 #56308 #56410 #56450
the session cannot be used concurrently.
use a unique session for checkpoint runner.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: use a unique session for checkpoint runner

- pkg/distsql/request_builder.go
- pkg/executor/distsql.go
- pkg/executor/executor_pkg_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56440
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: track the memory usage for building range in IndexLookUpExecutor

- pkg/expression/util.go
- pkg/planner/core/expression_rewriter.go
- tests/integrationtest/r/executor/expand.result
- tests/integrationtest/t/executor/expand.test
Issue Number: close https://github.com/pingcap/tidb/issues/56218
the details is commented here: https://github.com/pingcap/tidb/issues/56218#issuecomment-2382278367
mainly about two points
* in plan building process, outer's scope's expand should be pushed into stack, while at the same time it should be cleaned from current plan builder as well.
Tests 
> 
Side effects
Documentation
```release-note
planner: fix inner subq build process will ref-use outer's expand meta
优化器：修复了内层子查询构建时候会引用外层 scope 中的 expand 元信息
```
> planner: fix inner subq build process will ref-use outer's expand meta 

- pkg/statistics/handle/cache/statscache.go
- pkg/statistics/handle/metrics/metrics.go
Issue Number: close #56498
Currently, the stats health feature provides a high-level overview of system health metrics. While this is useful for identifying general trends and issues, it lacks the detailed granularity needed for in-depth analysis and troubleshooting. This enhancement aims to improve the granularity of the stats health metrics, allowing for more precise monitoring and diagnostics.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics,metrics: allow stats health to have finer granularity

- pkg/domain/extract.go
- pkg/domain/plan_replayer_dump.go
- pkg/server/handler/optimizor/BUILD.bazel
- pkg/server/handler/optimizor/plan_replayer_test.go
Issue Number: close #56458 
Now, we use extractWorker to traverse the SQL to get the table name. then we use those table names to dump the stats. but we forgot to check the table meta, so we cannot dump the table that is referred to those tables in the SQL.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: fix play replay dump cannot save the table in the foreign key's reference

- pkg/planner/core/BUILD.bazel
- pkg/planner/core/core_init.go
- pkg/planner/core/exhaust_physical_plans.go
- pkg/planner/core/operator/logicalop/base_logical_plan.go
- pkg/planner/core/operator/logicalop/logical_aggregation.go
- pkg/planner/core/operator/logicalop/logical_plans_misc.go
- pkg/planner/core/operator/logicalop/logical_sort.go
- pkg/planner/core/operator/logicalop/logical_top_n.go
- pkg/planner/core/rule_column_pruning.go
- pkg/planner/core/rule_topn_push_down.go
- pkg/planner/util/utilfuncp/BUILD.bazel
- pkg/planner/util/utilfuncp/func_pointer_misc.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: some code clean after all logical op are migrated

- pkg/statistics/handle/ddl/subscriber.go
port the handling logic of ActionAddColumn ActionModifyColumn ActionAddTablePartition ActionReorganizePartition ActionAlterTablePartitioning ActionRemovePartitioning ActionFlashbackCluster to DDL notifier subscriber.
Tests 
> will test it after the publisher is ready
Side effects
Documentation
```release-note
None
```
> stats: implement stats handler for DDL notifier part 2

- pkg/planner/core/expression_rewriter.go
- tests/integrationtest/r/planner/core/issuetest/planner_issue.result
- tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #53766 
Merge FullSchema and FullNames of subplans when rewring "in (subquery)" to inner join, which will be used to rewrite fields when using natural join.
https://github.com/pingcap/tidb/blob/438169989e2d6ab5f778238d02eb50c8eb408a76/pkg/planner/core/expression_rewriter.go#L2469-L2485
The merging code I referenced was from the code in buildJoin as follows:
https://github.com/pingcap/tidb/blob/438169989e2d6ab5f778238d02eb50c8eb408a76/pkg/planner/core/logical_plan_builder.go#L985-L1026
Tests 
> 
Side effects
Documentation …
> planner: merge FullSchema and FullNames of subplans when rewriting "in (subquery)" to inner join

- executor/insert_common.go
- executor/write_test.go
This is an cherry-pick of #56415
Issue Number: close #56408
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix data inconsistency after `load data ... replace into ...` | tidb-test=e5f82b826aeb7e912c2d4dc36389960daac36d96

- build/BUILD.bazel
- build/nogo_config.json
in go1.22, 
The vet tool now reports a non-deferred call to [time.Since(t)](https://tip.golang.org/pkg/time/#Since) within a defer statement. This is equivalent to calling time.Now().Sub(t) before the defer statement, not when the deferred function is called. In nearly all cases, the correct code requires deferring the time.Since call. For example:
```
t := time.Now()
defer log.Println(time.Since(t)) // non-deferred call to time.Since
tmp := time.Since(t); defer log.Println(tmp) // equivalent to the previous defer
defer func() {
log.Println(time.Since(t)) // a correctly deferred call to time.Since
}()
```
Tests 
> 
Side effects
Documentation …
> linter: enable defers linter in the govet

- pkg/lightning/backend/local/duplicate.go
- pkg/lightning/backend/local/duplicate_test.go
Issue Number: close #53669
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: skip non-unique index when detect duplicate KV

- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/ddl/ddl.go
- pkg/statistics/handle/ddl/drop_partition.go
- pkg/statistics/handle/ddl/exchange_partition.go
- pkg/statistics/handle/ddl/subscriber.go
- pkg/statistics/handle/ddl/truncate_partition.go
- pkg/statistics/handle/lockstats/lock_stats.go
- pkg/statistics/handle/lockstats/query_lock.go
- pkg/statistics/handle/lockstats/query_lock_test.go
- pkg/statistics/handle/lockstats/unlock_stats.go
port the handling logic of ActionTruncateTablePartition ActionDropTablePartition ActionExchangeTablePartition to DDL notifier subscriber. Should finish the porting now.
Tests 
> will test it after the publisher is ready
Side effects
Documentation
```release-note
None
```
> stats: implement stats handler for DDL notifier part 3

- pkg/ttl/ttlworker/BUILD.bazel
- pkg/ttl/ttlworker/job.go
- pkg/ttl/ttlworker/job_manager.go
- pkg/ttl/ttlworker/job_manager_integration_test.go
- pkg/ttl/ttlworker/job_manager_test.go
- pkg/ttl/ttlworker/task_manager_test.go
Issue Number: close #56422
When the job is finished, and at the same time the task is assigned to some TiDB node, it may fail to finish the job.
Use the pessimistic transaction to finish job. Then the `DELETE ... FROM tidb_ttl_tasks` will block `UPDATE mysql.tidb_ttl_task SET owner_id = ?...` (or in another direction).
If the ttl task is removed, it'll finally be removed by `(m *taskManager) checkInvalidTask` in the memory.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that a TTL job cannot be finished in some situation. …
```
> ttl: use a pessimistic transaction to finish the job

- br/pkg/rtree/BUILD.bazel
- br/pkg/rtree/rtree.go
- br/pkg/task/restore_txn.go
- br/tests/br_txn/client.go
Issue Number: close #54979
Feels like the way of generating load might have a race condition with the test setup. We noticed a mismatch of number of items before and after restore causing checksum mismatch. 
This PR changes the code to generate a fixed number of items and run locally several times and cannot reproduce the issue anymore. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix flaky test br_txn

- pkg/domain/domain.go
Issue Number: close #56525
The log is misleading ... v1/v2 switch does not really happen.
The `oldIsV2` value is not accurate before this fix.
When old infoschema nil, `oldIsV2` is always false (default value).
Tests 
Check after this fix, start a new tidb would not get the "infoschema v1/v2 switch" log. 
> 
Side effects
Documentation
```release-note
None
```
> domain: fix unexpected "infoschema v1/v2 switch" log

- pkg/statistics/handle/usage/session_stats_collect.go
Issue Number: ref #56537
Previously, dumpStatsMaxDuration was set to 1 hour, which is excessively long for large tables. Additionally, achieving the 1/10000 threshold for large tables is quite challenging. Therefore, we have decided to reduce the maximum interval.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: reduce dumpStatsMaxDuration as 5min

- pkg/executor/show.go
- pkg/meta/model/BUILD.bazel
- pkg/meta/model/table.go
- pkg/meta/model/table_test.go
- pkg/ttl/ttlworker/timer_sync.go
- pkg/ttl/ttlworker/timer_test.go
Issue Number: close #56539
In 6.5, the TTL table is created without meta `ttl_job_interval`, so after upgraded, the `SCHED_POLICY_EXPR` in `mysql.tidb_timers` is also empty that causing the frequent scheduling of TTL job.
When syncing the timer, insert a default value if `ttl_job_interval` is empty
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: fix a wrong ttl's job schedule for TTL table upgraded from 6.5

- pkg/executor/infoschema_reader_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56554
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix flaky test TestIndexUsageTable

- br/pkg/utils/safe_point.go
Issue Number: close #55902
the wrong warning log is print after backup done.
don't print the wrong warning log.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: avoid wrong warning

- pkg/planner/core/collect_column_stats_usage.go
Issue Number: ref #53567 
Clean up for some future improvements.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: remove the unused collectPredicateColumns flag

- pkg/disttask/framework/taskexecutor/execute/interface.go
in go.122
The new function [TypeFor](https://tip.golang.org/pkg/reflect/#TypeFor) returns the [Type](https://tip.golang.org/pkg/reflect/#Type) that represents the type argument T. Previously, to get the reflect.Type value for a type, one had to use reflect.TypeOf((*T)(nil)).Elem(). This may now be written as reflect.TypeFor[T]().
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: replace reflect.TypeOf((*T)(nil)).Elem() with reflect.TypeFor[T]()

- pkg/lightning/backend/local/local_test.go
Issue Number: close #56413
Problem Summary: The result of TestDoImport (the last subtest) is flaky.
Delete the "check if empty" for `job.injected` in the last subtest.
In the last subtest of TestDoImport, we check if `job.injected` is empty after running all jobs. However, a fatal error job will break the flow in advance, and it is possible that this happens before other jobs are executed, which may lead to test failure when checking their `job.injected`.
It is hard to controll the execution order of the jobs, since in `storeBalancer.pickJob()` sync.Map iterate items in a uncertain order. In addition, the first subtest already tested the length of `job.injected`, and the last test is intended for retryable error, so it is reasonable to delete the check in the last subtask.
Tests 
> - [ ] …
> lightning: delete job.injected length check in TestDoImport

- pkg/executor/test/txn/BUILD.bazel
- pkg/executor/test/txn/txn_test.go
Issue Number: close #56562
Add test about using both `foreign key` and `savepoint`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> txn: test the `SAVEPOINT` statement with `foreign key`

- pkg/ddl/ddl_history.go
CDC depends on GetLastNHistoryDDLJobs where a meta reader should be used
Tests 
> - [x] only change param type to reduce the scope of APIs can be called
> 
Side effects
Documentation
```release-note
None
```
> ddl: change some param for cdc

- cmd/importer/rand.go
- dumpling/export/dump.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix wrong log because of wrongly rename

- pkg/planner/core/rule_collect_plan_stats.go
- pkg/statistics/handle/syncload/stats_syncload.go
- tests/integrationtest/r/planner/core/issuetest/planner_issue.result
- tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #56472
Tests 
e2e team has verified it by their e2e test cases/
> 
Side effects
Documentation
```release-note
None
```
> statstics: avoid unnecessary try when to sync load

- tests/realtikvtest/importintotest/import_into_test.go
Issue Number: close #56563
Add tests for using both `IMPORT INTO` statement and the foreign key. It's expected that `IMPORT INTO` will always ignore the foreign key checks.
TODO: confirm that the behavior is as expected, and modify the document.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: add tests for `IMPORT INTO` statement with Foreign Key

- tools/check/check-bazel-prepare-rbe.sh
- tools/check/check-bazel-prepare.sh
Tests 
> 
Side effects
Documentation
```release-note
None
```
> script: update guide to use `git apply -` to resolve bazel change

- DEPS.bzl
- go.mod
- go.sum
Issue Number: ref #56635
just check if the problem will gone, because I don't know the root cause 😢 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dep: upgrade github.com/dgryski/go-farm

- pkg/sessionctx/variable/sysvar.go
- pkg/table/tables/test/partition/partition_test.go
- tests/integrationtest/r/executor/partition/table.result
Issue Number: ref #56490
Problem Summary: As #56490 mentioned, we will deprecate `static prune mode` at v8.5. And plan to remove it after v9.1 released.
ref doc link https://github.com/pingcap/docs-cn/pull/18857
Tests 
> 
Side effects
Documentation
```release-note
None
```
> sessionctx: Deprecate static prune mode

- pkg/ddl/backfilling_dist_executor.go
- pkg/ddl/index.go
- pkg/ddl/job_worker.go
- pkg/owner/manager.go
- pkg/util/dbterror/ddl_terror.go
- tests/realtikvtest/addindextest1/disttask_test.go
- tests/realtikvtest/addindextest3/ingest_test.go
Issue Number: close #56550
```
[2024/10/02 17:46:51.687 +08:00] [INFO] [info.go:1001] ["get key failed"] [key=/tidb/server/info] [error="context deadline exceeded"]
[2024/10/02 17:46:52.841 +08:00] [WARN] [manager.go:536] ["close session error"] [error="etcdserver: requested lease not found"]
[2024/10/02 17:46:52.841 +08:00] [ERROR] [backfilling_operators.go:962] ["import error"] [task-id=120028] [subtask-id=120055] [category=ddl] [error="etcdserver: requested lease not found"]
[2024/10/02 17:46:52.841 +08:00] [INFO] [backend.go:352] ["engine close start"] [category=ddl-ingest] [engineTag=sbtest1:35] [engineUUID=dd035f55-b760-5f2e-b67a-4e79ffec0f3d]
[2024/10/02 17:46:52.842 +08:00] [INFO] [backend.go:354] ["engine close completed"] [category=ddl-ingest] …
```
> ddl: add `lease not found` and `deadline exceed` to retryable errors

- pkg/domain/plan_replayer_dump.go
- pkg/executor/plan_replayer.go
- pkg/server/handler/optimizor/plan_replayer_test.go
Issue Number: close #56456
when restoring the table schema, some tables have these dependencies between each other. so we need to disable the ForeignKeyChecks to create table.
Tests 
> 
Side effects
Documentation
```release-note
planner: play replay load restore the table with foreign key with right order
```
> planner: play replay load restore the table with foreign key with right order.

- Makefile
- cmd/pluginpkg/pluginpkg.go
- pkg/ddl/BUILD.bazel
- pkg/ddl/reorg.go
- pkg/ddl/util/BUILD.bazel
- pkg/ddl/util/util.go
- pkg/executor/benchmark_test.go
- pkg/executor/internal/testutil/BUILD.bazel
- pkg/executor/internal/testutil/agg.go
- pkg/executor/internal/testutil/limit.go
- pkg/executor/internal/testutil/sort.go
- pkg/executor/internal/testutil/window.go
- pkg/executor/sortexec/benchmark_test.go
- pkg/planner/core/mock.go
- pkg/statistics/handle/autoanalyze/BUILD.bazel
- pkg/statistics/handle/autoanalyze/autoanalyze_test.go
- pkg/store/mockstore/mockcopr/cop_handler_dag.go
- pkg/store/mockstore/unistore/cophandler/cop_handler.go
- pkg/util/mock/BUILD.bazel
- pkg/util/mock/context.go
- pkg/util/mock/fortest.go
- pkg/util/sqlexec/mock/BUILD.bazel
Issue Number: close #53388
Add checks to avoid to use `mock.NewContext` in production code.
1. Move the function `mock.NewContext` to a standalone file which has a `//go:build !codes` header to avoid to build this function in production code. So if some one uses `mock.NewContext` in some production code, `make server` will fail.
2. Introduce a function `mock.NewContextDeprecated` and add a `// Deprecated` comment for it. This method should only be used in some legacy code.
3. Remove `mock.NewContext` usage in other production codes. 
Tests 
> 
Side effects
Documentation …
> *: force forbiding to use `mock.NewContext` in production code

- pkg/planner/core/casetest/vectorsearch/BUILD.bazel
- pkg/planner/core/casetest/vectorsearch/vector_index_test.go
- pkg/planner/core/planbuilder.go
Issue Number: close https://github.com/pingcap/tidb/issues/56551
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: update access pathes when using the vector index

- br/pkg/task/BUILD.bazel
- br/pkg/task/common.go
- br/pkg/task/common_test.go
Issue Number: close #56388
```
1. checks the error of decoding hex format on crypto key and return a customized error indicating the hex format is not valid
2. added tests to verify that
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: have better crypter key error msg

- pkg/ddl/executor.go
- pkg/ddl/partition.go
- pkg/parser/ast/ast.go
- pkg/parser/parser.y
- tests/integrationtest/r/ddl/db_partition.result
- tests/integrationtest/t/ddl/db_partition.test
Issue Number: close #54283
Problem Summary: We use `OriginTextPosition` to split prepared ddl stmts. But it is wrong when query has prefixed blank, like '\ncreate ...'. So we should call `strings.index` to regenerate it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix prepare stmt with partition related ddl stmts

- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_v2.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_v2_ddl_handler.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_v2_test.go
- pkg/statistics/handle/handletest/lockstats/lock_partition_stats_test.go
- pkg/statistics/handle/lockstats/BUILD.bazel
- pkg/statistics/handle/lockstats/lock_stats.go
- pkg/statistics/handle/lockstats/lock_stats_test.go
- pkg/statistics/handle/lockstats/unlock_stats.go
- pkg/statistics/handle/lockstats/unlock_stats_test.go
- pkg/statistics/handle/updatetest/update_test.go
Handle the lock and unlock operations correctly.
1. When we unlock the tables, we need to update the version in order to trigger an update, allowing the priority queue to check the latest count and the modify_count.
2. When we lock the tables, we need to update the version as well. This lets the priority queue know that the table has been changed, and we need to evaluate it again.
3. In the priority queue, when we enqueue the table, we will check if this table has been locked or unlocked.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-g …
> statistics: handle lock and unlock operations correctly

- br/pkg/restore/snap_client/systable_restore_test.go
- pkg/session/bootstrap.go
Issue Number: close #56544
Upgrade from old version tidb, infoschema v2 should not be used.
Tests 
See the steps described in the issue.
> 
Side effects
Documentation
```release-note
None
```
> session: upgrade from old cluster infoschema v2 should not be used

- pkg/timer/runtime/BUILD.bazel
- pkg/timer/runtime/runtime.go
- pkg/timer/runtime/runtime_test.go
- pkg/ttl/client/BUILD.bazel
- pkg/ttl/client/command.go
- pkg/ttl/ttlworker/config.go
- pkg/ttl/ttlworker/job_manager.go
- pkg/ttl/ttlworker/job_manager_integration_test.go
- pkg/ttl/ttlworker/job_manager_test.go
- pkg/ttl/ttlworker/timer.go
Issue Number: close #56718
1. Provides `boostJobScheduleForTest` to make some intervals smaller to boost test.
2. Modify some cases to make it more reasonable and faster
In master, run tests in `pkg/ttl/ttlworker` takes 34.5s:
```
> X="run pkg/ttl/ttlworker" make ut
cd tools/check; \
GO111MODULE=on go build -o ../bin/ut ut.go
cd tools/check; \
GO111MODULE=on go build -o ../bin/xprog xprog.go
GOBIN=/Users/wangchao/Code/pingcap/tidb/tools/bin GO111MODULE=on go install github.com/pingcap/failpoint/failpoint-ctl@9b3b6e3
tools/bin/ut run pkg/ttl/ttlworker || { find $PWD/ -type d | grep -vE "(\.git|tools)" | xargs tools/bin/failpoint-ctl disable; exit 1; }
2024/10/18 12:09:12 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
building task finish, parallelism=20, count=55, …
```
> ttl: make some integration test faster

- pkg/util/execdetails/execdetails.go
Issue Number: close #56743
BasicRuntimeStats is a general structure used for all executors including tidb ones, it is a waste of resource to record the info here.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> util: Move tiflashScanContext outof basic stats

- pkg/ddl/constant.go
- pkg/ddl/notifier/store.go
- pkg/ddl/notifier/testkit_test.go
- pkg/ddl/session/session.go
- pkg/executor/infoschema_cluster_table_test.go
- pkg/executor/infoschema_reader_test.go
- pkg/session/bootstrap_test.go
- pkg/session/session.go
- create system table when bootstrap
- fix a bug that can't insert schema change events containing `'`
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl_notifier: create system table in test and escape the string literal

- pkg/server/handler/optimizor/plan_replayer_test.go
Issue Number: close #56735
Tests 
> 
Side effects
Documentation
```release-note
None
```
> server: fix flaky test by using t.TempDir

- pkg/ttl/ttlworker/job_manager_integration_test.go
- pkg/ttl/ttlworker/session.go
Issue Number: close #56402
If a TiDB node doesn't enable `TiKV` read engine, running TTL task may fail if the table doesn't have tiflash replica.
This PR always enables all read engines for TTL sessions.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that if the `isolation-read.engines` config is set without `tikv`, the TTL task may fail.
```
> ttl: always enable all read engines for TTL sessions

- pkg/ddl/create_table.go
- pkg/ddl/ddl.go
- pkg/ddl/ddl_error_test.go
- pkg/ddl/executor.go
- pkg/ddl/job_submitter.go
- pkg/ddl/job_worker.go
- pkg/ddl/multi_schema_change.go
- pkg/meta/model/job.go
- pkg/meta/model/job_args.go
- pkg/meta/model/job_args_test.go
- pkg/meta/model/job_test.go
- make args in job/subjob and DecodeArgs unexported, now caller should use GetXXXArgs function instead
- remove change fields inside job.decodeArgs
- remove tests related to `MockModifyJobArg` failpoint, it only test how we handle corrupted args, and the job is cancelled in this case.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: make args/DecodeArgs un-exported

- pkg/expression/builtin_compare.go
- pkg/expression/integration_test/integration_test.go
Issue Number: close #56744
Tests 
> 
Side effects
Documentation
```release-note
fix issue that fail to evaluate the expression that duration type null equal with const null
```
> expression: fix expression that duration type null equal with const null

- pkg/executor/plan_replayer.go
- pkg/server/handler/optimizor/plan_replayer_test.go
Issue Number: close #54961
when we restore the table with plan replay. we will ignore the placement rules to success to create table.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix plan replay cannot deal with placement mode

- pkg/meta/model/column.go
- pkg/meta/model/column_test.go
Issue Number: close #32881
Add not null flag for ExtraPhysTblIDColInfo and ExtraPartitionIDColInfo
Tests 
Side effects
Documentation
```release-note
None
```
> parser: Add not null flag for ExtraPhysTblIDColInfo and ExtraPartitionIDColInfo

- pkg/sessionctx/variable/tidb_vars.go
- tests/integrationtest/r/sessionctx/setvar.result
This pr enable hash join v2 for tests
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: enable hash join v2 by default for tests

- pkg/resourcegroup/runaway/manager.go
- pkg/resourcegroup/runaway/record.go
- pkg/resourcegroup/runaway/record_test.go
Issue Number: close #56797
We may have multiple domains in unit test. It is better not to use global variables as soon as possible.
Change global variable `recordMap` to local one.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: stabilize TestAnalyzeColumnsWithVirtualColumnIndex

- pkg/infoschema/infoschema.go
- pkg/infoschema/infoschema_test.go
Issue Number: ref https://github.com/pingcap/tidb/issues/50959
In development, we store the TableInfo in a system table. After unmarshal, we use `SchemaByTable` to find its database. However `SchemaByTable` can only be used with TableInfo that are not go through de(serialization).
So change `SchemaByTable` to support all `TableInfo` 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> infoschema: improve usability of SchemaByTable

- pkg/server/handler/optimizor/BUILD.bazel
- pkg/server/handler/optimizor/statistics_handler.go
Issue Number: close #56782
A simple tidy PR, it removes an use of `session` and replace it with a `types.Context`.
Instead of creating a fully functional session, it creates a `types.Context` instead.
Tests 
> It has been covered by `TestDumpStatsAPI` test.
Side effects
Documentation
```release-note
None
```
> server: replace session in statsHistoryHandler with `types.Context`

- pkg/infoschema/test/clustertablestest/tables_test.go
- pkg/util/stmtsummary/evicted.go
- pkg/util/stmtsummary/evicted_test.go
Issue Number: close #56629
Problem Summary: reduce the memory consumption by information_schema.statements_summary_evicted
Remove the digest map of `statements_summary_evicted`, use a counter to count evicted digest.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> stmtsummary: reduce the memory consumption by information_schema.statements_summary_evicted

- pkg/planner/core/casetest/partition/testdata/integration_partition_suite_in.json
- pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json
- pkg/planner/core/logical_plan_trace_test.go
- pkg/planner/core/rule_partition_processor.go
- pkg/table/tables/partition.go
- tests/integrationtest/r/planner/core/casetest/partition/integration_partition.result
- tests/integrationtest/r/planner/core/integration_partition.result
- tests/integrationtest/t/planner/core/integration_partition.test
Issue Number: close #56673
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner, table: list partition support prune non point range

- tests/integrationtest2/r/br_integration.result
- tests/integrationtest2/r/dumpling_import_integration.result
- tests/integrationtest2/run-tests.sh
Issue Number: ref #56556
Fix some bugs introduced in #56486
Tests 
> 
Side effects
- NA
Documentation
- NA
```release-note
None
```
> tests/integrationtest2: fix bugs in the tests

- pkg/executor/builder.go
Issue Number: close #56825
The root cause is in HashJoinV2, it use `hCtx.OtherCondition != nil` to check if it has other condition. However, sometimes, `hCtx.OtherCondition` can be an empty slice.
This pr makes sure that `OtherCondition/BuildFilter/ProbeFilter` must be either nil or a non-empty slice.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix hash join v2 bug that mistakenly think the join has other condition

- pkg/ddl/create_table.go
- pkg/ddl/executor.go
- tests/integrationtest/r/globalindex/ddl.result
- tests/integrationtest/r/globalindex/misc.result
- tests/integrationtest/t/globalindex/ddl.test
- tests/integrationtest/t/globalindex/misc.test
Issue Number: close #56804 
Problem Summary: If the primary index mentioned is a global index, then it should be a non-clustered index.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: fix some limitation of primary key + global index

- br/pkg/storage/azblob.go
- br/pkg/storage/azblob_test.go
Issue Number: ref #56606
replace `open reader on every read` by `open reader once and read`
Tests 
read one 250M file, before 17s, after 395ms
> 
Side effects
Documentation
```release-note
None
```
> obj storage: optimize azure reader

- pkg/executor/join/inner_join_probe_test.go
- pkg/executor/join/left_outer_join_probe_test.go
- pkg/executor/join/outer_join_probe.go
- pkg/executor/join/right_outer_join_probe_test.go
- pkg/executor/test/jointest/hashjoin/BUILD.bazel
- pkg/executor/test/jointest/hashjoin/hash_join_test.go
Issue Number: close #56856
Fix a bug in outer join v2
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix outer join bug in hash join v2

- tests/integrationtest2/r/ticdc/cdc_integration.result
Issue Number: ref #56556
Fix missing test result
Tests 
> 
Side effects
- NA
Documentation
- NA
```release-note
None
```
> tests/integrationtest2: go on fixing the tests

- br/tests/br_pitr/run.sh
Issue Number: close #53835
The log file may not be restored so sometimes corrupting one log file does not make restore fail.
lost/corrupt all the files.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix br integration test file corruption

- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/casetest/instanceplancache/concurrency_test.go
Problem Summary: planner: add more test cases for plan cache
planner: add more test cases for plan cache
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add more test cases for plan cache

- pkg/executor/builder.go
- pkg/executor/delete.go
- pkg/executor/delete_test.go
- pkg/executor/foreign_key.go
- pkg/executor/insert.go
- pkg/executor/insert_common.go
- pkg/executor/update.go
- pkg/executor/write.go
- pkg/planner/core/common_plans.go
- pkg/planner/core/logical_plan_builder.go
- pkg/planner/core/point_get_plan.go
- tests/integrationtest/r/executor/delete.result
- tests/integrationtest/r/executor/insert.result
- tests/integrationtest/r/executor/update.result
- tests/integrationtest/t/executor/delete.test
- tests/integrationtest/t/executor/insert.test
- tests/integrationtest/t/executor/update.test
Issue Number: close #56678, close #56681, close #39712
In the following cases, the foreign key error should be omitted and placed in the warning:
1. `INSERT IGNORE ... ON DUPLICATE UPDATE ...`
2. `DELETE IGNORE ...`
3. `UPDATE IGNORE ...`
Introduce a function `checkFKIgnoreErr` to check rows explicitly, and use this function to check each rows in these three cases.
Tests 
> 
```release-note
None
```
> executor: ignore foreign key error in `UPDATE/INSERT/DELETE ignore`

- DEPS.bzl
- go.mod
- go.sum
This is a cherry-pick of https://github.com/pingcap/tidb/pull/56860.
Issue Number: ref #56757
Update the client-go dependency to add retry logic when returned region from PD has no leaders.
Tests 
> 
Side effects
Documentation
```release-note
Add retry logic when returned region from PD has no leaders.
```
> kv-client: update client-go to fix the retry issue(#56860)

- pkg/ddl/ddl.go
- pkg/domain/domain.go
- pkg/meta/meta.go
- pkg/session/bootstrap_test.go
- pkg/session/session.go
Issue Number: ref https://github.com/pingcap/tidb/issues/55722
Enable the DDL notifier by default.
I added the `DDLNotifierTableVersion` to init the DDL notifier table.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: enable the ddl notifier by default

- pkg/ddl/executor.go
- pkg/ddl/multi_schema_change.go
- tests/integrationtest/r/ddl/multi_schema_change.result
- tests/integrationtest/t/ddl/multi_schema_change.test
Issue Number: close #28421 
Previously, TiDB doesn't support dropping multiple foreign keys.
Add support for dropping multiple foreign keys.
Tests 
> 
```release-note
None
```
> ddl: support dropping multiple foreign keys

- pkg/executor/executor_failpoint_test.go
- pkg/store/copr/coprocessor.go
Issue Number: close https://github.com/pingcap/tidb/issues/56916
The query may be blocking after identifying a runaway query with a cooldown action.
Tests 
> 
```release-note
None
```
> copr: fix the issue about runaway index lookup query blocking

- pkg/infoschema/metrics_schema.go
Issue Number: close #56775 
Sort tables before assign ids
Tests 
Run two tidb nodes in a cluster and run below SQL in each node:
```
select tidb_table_id, table_name from information_schema.tables where table_schema='metrics_schema' and table_name='tidb_ddl_total_time' limit 1;
```
The return results are all the same.
> 
Side effects
Documentation
```release-note
None
```
> *: make table id in `metrics_schema` stable

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close #56757 
Update the client-go dependency to add retry logic when returned region from PD has no leaders.
Tests 
> 
Side effects
Documentation
```release-note
Add retry logic when returned region from PD has no leaders.
```
> kv-client: update client-go to fix the retry issue

- pkg/executor/prepared_test.go
- pkg/session/nontransactionaltest/BUILD.bazel
- pkg/session/nontransactionaltest/nontransactional_test.go
Issue Number: close #56365
We didn't have tests for the cooperation between foreign key and `PREPARE` or Non-Transactional DML. This PR adds these tests.
Add two tests about the cooperation between foreign key and `PREPARE` or Non-Transactional DML.
Tests 
> 
```release-note
None
```
> tests: add test for foreign key related to prepare and Non-Transactional DML

- pkg/planner/indexadvisor/indexadvisor.go
- pkg/util/stmtsummary/v2/tests/BUILD.bazel
- pkg/util/stmtsummary/v2/tests/table_test.go
Problem Summary: planner: convert schema_name from NULL to "" for index advisor
planner: convert schema_name from NULL to "" for index advisor
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: convert schema_name from NULL to "" for index advisor

- pkg/ddl/notifier/BUILD.bazel
- pkg/ddl/notifier/testkit_test.go
as title
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: pin the behaviour when cluster has two owners for a short time

- pkg/ttl/ttlworker/del.go
- pkg/ttl/ttlworker/del_test.go
- pkg/ttl/ttlworker/job_manager.go
- pkg/ttl/ttlworker/job_manager_integration_test.go
- pkg/ttl/ttlworker/job_manager_test.go
- pkg/ttl/ttlworker/scan_test.go
- pkg/ttl/ttlworker/session_test.go
- pkg/ttl/ttlworker/timer_sync_test.go
Issue Number: close #56934
This is cherry-pick of #56935
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ttl: fix some memory leak in TTL (#56935)

- tests/integrationtest/r/executor/delete.result
- tests/integrationtest/t/executor/delete.test
Issue Number: close #56978 
The query `delete parent, parent2 from parent join parent2 on parent.a = parent2.a;` is possible to give two errors:
1. Delete from parent2 will break the foreign key constraint in `child2`.
2. Delete from parent will break the foreign key constraint in `child`.
It caused the flaky.
A `replace` is added to make these two errors appear the same.
Tests 
> 
```release-note
None
```
> test: fix the flaky integration test for foreign key.

- pkg/metrics/grafana/tidb.json
Issue Number: close #56980
The current sync load monitoring primarily focuses on P95 latency, which is insufficient for capturing extreme timeout issues. While P95 latency may not indicate a timeout, P9999 latency could be significantly high, leading to potential misjudgments and overlooked performance issues.
Tests 
> 
Side effects
Documentation
```release-note
Enhanced sync load monitoring to include P9999 latency metrics for better detection and analysis of extreme performance issues
对 sync load 监控改为P9999，更好的观察性能问题
```
> metrics: set sync load latency as P9999

- pkg/executor/test/fktest/BUILD.bazel
- pkg/executor/test/fktest/foreign_key_test.go
- pkg/store/mockstore/unistore/tikv/mvcc.go
- tests/realtikvtest/txntest/txn_test.go
Issue Number: close #56663 
When there is an update for the same row in other transactions, it's necessary to update the `for_update_ts` to use the latest data to verify the constraint. Meanwhile, TiDB/TiKV has a mechanism called fair locking to lock the key with conflict. 
Therefore, when a key is locked, the storage layer (unistore or TiKV) should verify whether other transactions have written this key. If so, it should return the conflict info to TiDB, and TiDB can retry and update the `for_update_ts`.
However, the implementation of unistore has a little bug:
For TiKV, it returns the latest TS of both WRITE and LOCK, because they share the similar key (but with different value):
```rust
pub fn commit<S: Snapshot>(
txn: &mut MvccTxn,
reader: &mut SnapshotReader<S>,
key: …
```
> unistore: fix the fair locking mechanism in unistore and make foreign key work

- pkg/planner/core/operator/logicalop/logical_apply.go
- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add apply's hash64 and equals interface implementation

- pkg/ddl/executor.go
- tests/integrationtest/r/globalindex/aggregate.result
- tests/integrationtest/r/globalindex/ddl.result
- tests/integrationtest/r/globalindex/insert.result
- tests/integrationtest/r/globalindex/mem_index_lookup.result
- tests/integrationtest/r/globalindex/mem_index_merge.result
- tests/integrationtest/r/globalindex/mem_index_reader.result
- tests/integrationtest/r/globalindex/point_get.result
- tests/integrationtest/r/globalindex/update.result
- tests/integrationtest/t/globalindex/aggregate.test
- tests/integrationtest/t/globalindex/ddl.test
- tests/integrationtest/t/globalindex/insert.test
- tests/integrationtest/t/globalindex/mem_index_lookup.test
- tests/integrationtest/t/globalindex/mem_index_merge.test
- tests/integrationtest/t/globalindex/mem_index_reader.test
- tests/integrationtest/t/globalindex/point_get.test
- tests/integrationtest/t/globalindex/update.test
Issue Number: close #56230
Tests 
> 
Side effects
Documentation
```release-note
Allow global Index including all columns in the partitioning expression.
```
> ddl: Allow global Index including all columns in the partitioning expression

- br/pkg/backup/BUILD.bazel
- br/pkg/backup/store.go
- br/pkg/backup/store_test.go
Issue Number: ref #53480
the context will leak because it is not cancelled.
cancel the context
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: cancel context when timer stop

- br/pkg/restore/snap_client/client.go
Issue Number: close #56866
Currently, BR only has 16 db pools to create databases, and it takes about more than one hour to create 200K databases. 
Use 100 db pools to create databases, and it only takes about half an hour to finish create 200K databases.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: more db pools to create databases

- br/pkg/conn/conn.go
Issue Number: close #56999 ref #55870
annotate the wrong error
annotate the correct error
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: fix wrong error

- pkg/executor/foreign_key.go
- pkg/executor/test/fktest/BUILD.bazel
- pkg/executor/test/fktest/foreign_key_test.go
Issue Number: close #56655 
`INSERT IGNORE` cannot lock the rows in parent, so the constraint may be broken.
Try to lock the rows even when the `toBeCheckedKeys` and `toBeCheckedPrefixKeys` are empty.
Tests 
> 
```release-note
None
```
> executor: fix the issue that `INSERT IGNORE` doesn't lock the parent table

- pkg/domain/domain.go
- pkg/owner/BUILD.bazel
- pkg/owner/manager.go
- pkg/owner/manager_test.go
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/types/BUILD.bazel
- pkg/statistics/handle/types/interfaces.go
In this PR, I added the refresher as a listener for the stats owner, to ensure that after a stats owner changes, the background process can stop correctly.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: add the refresher as a stats owner listener

- pkg/statistics/handle/cache/internal/lfu/lfu_cache_test.go
if runing test cases in the high load scenario， it is not enough to wait 1 second. so we have to check many times in a 5 second.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: avoid flaky test with high load scenario

- br/pkg/gluetidb/glue.go
- pkg/ddl/ddl.go
- pkg/ddl/restart_test.go
- pkg/ddl/schema_test.go
- pkg/ddl/schematracker/checker.go
- pkg/domain/BUILD.bazel
- pkg/domain/domain.go
- pkg/domain/domain_test.go
- pkg/owner/manager.go
- pkg/owner/mock.go
- pkg/session/BUILD.bazel
- pkg/session/bootstrap.go
- pkg/session/bootstrap_test.go
- pkg/session/session.go
- pkg/session/session_test.go
- pkg/session/tidb.go
Issue Number: close #56924, #56713
older versions which don't have the fix of https://github.com/pingcap/tidb/issues/54689, when upgrade and forcing newer version node to be owner, multiple owner might exist at the same time, this pr tries to mitigate the issue, see code comments for more detail
also mitigate https://github.com/pingcap/tidb/issues/57003 by sleep after force to be owner
Tests 
- start a v7.5.0 cluster with 3 TiDBs, rolling upgrade to this pr, success
- start a v8.1.1 cluster with 3 TiDBs, rolling upgrade to this pr, success
- start a v7.5.0 cluster with 3 TiDBs, stop all TiDBs, then start them with this pr, success
- **Note: after this PR, we will aquire distributed lock before start domain, so in this case, the 2 non-owner node will not involve in schema …
> ddl: mitigate the issue that multiple owner might exist during force to be owner

- pkg/ddl/executor.go
- tests/integrationtest/r/session/common.result
- tests/integrationtest/t/session/common.test
Issue Number: close #56930
Miss the check of index length.
Check the index length when convert to new charset.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> ddl: check index key length when convert charset

- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_join.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add equals function generation logic for logical operator.

- pkg/ddl/index_merge_tmp.go
- pkg/ddl/ingest/BUILD.bazel
- pkg/ddl/ingest/integration_test.go
- pkg/kv/key.go
- pkg/table/tables/index.go
- pkg/tablecodec/tablecodec.go
Issue Number: close #56535
Problem Summary: TempIndex didn't process partition handle before. So let it supports encode/decode partition handle.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: let TempIndex support encode/decode partitionID flag

- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_aggregation.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: generate the hash64 and equals for logical aggregation.

- tests/_utils/run_services
`mkdir` on mac doesn't support put options after the directory param, it takes as directory names to create
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: fix integration test create empty "-m"/"700" dir on mac

- pkg/executor/delete_test.go
Issue Number: close #57094
The test `TestDeleteIgnoreWithFK` is flaky because of the order of warnings.
Sort the warnings before the assertion.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix the flaky test `TestDeleteIgnoreWithFK`

- pkg/tablecodec/tablecodec.go
- tests/integrationtest/r/globalindex/misc.result
- tests/integrationtest/t/globalindex/misc.test
Issue Number: close #57087
Problem Summary: In `reEncodeHandleConsiderNewCollation`, we assume all columns in `columns[colLen:]` related with Common Handle. But it contains `model.ExtraPhysTblID` when use global index.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tablecodec: fix global index + commonHandle + restoredValues panic

- pkg/executor/join/joinversion/join_version.go
- pkg/planner/core/BUILD.bazel
- pkg/planner/core/physical_plans.go
Add an internal variable so we can control which kind of join can use hash join v2 when `tidb_hash_join_version` is set to `optimized`, in this way we can GA hash join v2 step by step for all kinds of join types
Tests 
> 
Side effects
Documentation
```release-note
None
```
> exeuctor: add a helper variable to help ga hash join v2 step by step for all kinds of join types

- pkg/executor/internal/mpp/local_mpp_coordinator.go
- pkg/executor/internal/mpp/local_mpp_coordinator_test.go
- pkg/planner/core/physical_plans.go
Issue Number: close #50455 
Currently, if limit operator is not pushed down to tiflash side, then execution summary in tiflash side will be lost. This is because we only check if limit operator exists under TableReader. Refine the logic so that it checks if limit operator exists in the path from TableReader to Root.
Tests 
Manually verified explain analyze insert/update/delete statements' execution summary.
> 
Side effects
Documentation
```release-note
None
```
> executor,planner: Fix tiflash plan with limit operator may lose execution summary problem

- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
- pkg/statistics/handle/updatetest/update_test.go
When checking the prune mode, we need to ensure that we have loaded the latest variable value. However, directly using the system session pool does not work, as it requires manual updates to obtain the latest global variable value.
In this PR, I utilized the session context from the caller that has already updated the session, allowing us to correctly retrieve the prune mode.
For earlier versions of TiDB, this issue did not occur because we did not use this session to retrieve the global variable in those versions.
Additionally, I added a test case for the queue to verify the handling of DML changes for partitioned tables.
Tests 
> 
Side effects …
> statistics: handle the prune mode correctly in the refresher

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close https://github.com/pingcap/tidb/issues/57135
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: upgrade golang-jwt/jwt to fix secruity alerms

- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/util/misc.go
Problem Summary: planner: update the plan_clone_gen file
planner: update the plan_clone_gen file
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: update the plan_clone_gen file

- lightning/pkg/importer/get_pre_info.go
- lightning/pkg/importer/mock/mock.go
- lightning/pkg/importer/mock/mock_test.go
- pkg/lightning/backend/backend.go
- pkg/lightning/backend/local/local.go
- pkg/lightning/backend/tidb/BUILD.bazel
- pkg/lightning/backend/tidb/tidb.go
- pkg/lightning/backend/tidb/tidb_test.go
Issue Number: close #57115
add `table_name IN (...)` to that query, split the table name list into batches with maximum size of 32, and execute them with maximum concurrency 8.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: optimize a query to I_S.columns

- pkg/planner/cardinality/selectivity_test.go
- pkg/planner/core/casetest/binaryplan/testdata/binary_plan_suite_out.json
- pkg/planner/core/casetest/dag/testdata/plan_suite_out.json
- pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
- pkg/planner/core/plan_cost_ver2.go
- pkg/planner/core/plan_cost_ver2_test.go
- tests/integrationtest/r/executor/chunk_reuse.result
- tests/integrationtest/r/executor/explain.result
- tests/integrationtest/r/planner/core/casetest/integration.result
- tests/integrationtest/r/planner/core/cbo.result
- tests/integrationtest/r/planner/core/integration.result
- tests/integrationtest/r/planner/core/plan_cache.result
- tests/integrationtest/r/planner/core/plan_cost_ver2.result
Issue Number: close #57085 
Code to provide a minimum cost to table scan - should use "max" rather than "min" to ensure that the minimum is actually applied. Current code will produce a lower cost for tablescans greater than 1000 rows that fit the other criteria for requiring a minimum cost to table scans.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix cost adjustment for high risk tablescan

- pkg/timer/runtime/BUILD.bazel
- pkg/timer/runtime/runtime.go
- pkg/timer/runtime/runtime_test.go
Issue Number: close #57137
This issue is because a trigger action will be sent to the timer worker via the chan:
https://github.com/pingcap/tidb/blob/6004c3e109a7f70b05287563b0b192e61be87fb9/pkg/timer/runtime/runtime.go#L285-L300
If the chan is full, it will fail and retry after a while. However, some tables always have lower priorities even if they are not triggered for a long time.
reorder timers by `nextEventTime` before sending them to workers to make sure the timer which has a max delay will be handled first to avoid starvation
Tests 
> 
Side effects
Documentation …
> timer: make sure timer which has a max delay will be scheduled first

- pkg/executor/internal/mpp/local_mpp_coordinator.go
- pkg/executor/test/tiflashtest/BUILD.bazel
- pkg/executor/test/tiflashtest/tiflash_test.go
Issue Number: close #57149 
Introduced in https://github.com/pingcap/tidb/pull/57101. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: add nil check protection for non-related subquery which base plan will be nil

- pkg/executor/analyze.go
- pkg/statistics/handle/autoanalyze/autoanalyze.go
- pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
We need to continue tracking the retryable table while the table analysis is in progress. This will prevent a situation where, after the new index is added, there’s no way to analyze it.
I changed the failed jobs to retryable jobs so we can track them. Each time we attempt to push a currently running job, we will mark it as retryable, as we may need to analyze the table again after it has been processed.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: Handle the adding index event properly while the job is running

- pkg/expression/builtin_op.go
- pkg/expression/builtin_other.go
- pkg/expression/builtin_threadsafe_generated.go
- pkg/expression/builtin_threadunsafe_generated.go
- pkg/expression/generator/builtin_threadsafe.go
- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/casetest/instanceplancache/builtin_func_test.go
Problem Summary: expression: label more expressions as thread-safe and add more test cases
expression: label more expressions as thread-safe and add more test cases
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: label more expressions as thread-safe and add more test cases

- pkg/executor/adapter.go
Issue Number: close #55468
The cause of that DATA RACE is a resource leak.
After executing "select * from low_resolution_tso for update" when `tidb_low_resolution_tso` is on,
error is return but the executor is not closed, so the background goroutine leak.
The leaked goroutine still referencing session ctx.
So when the next SQL is executed, it races visiting the session ctx.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> *: fix resource leak in select for update when 'tidb_low_resolution_tso' is set

- tests/realtikvtest/testkit.go
Issue Number: close #57191
Ignore the function `github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).resolveFlushedLocks.func1` which runs in background. This function is responsible for commit/rollback locks and transaction status broadcast, which is running in background by designed, and it should not break goleak verification.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> tests: ignore goroutines created by resolveFlushedLocks

- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/casetest/instanceplancache/concurrency_test.go
- pkg/planner/core/common_plans.go
- pkg/planner/core/generator/plan_cache/plan_clone_generator.go
- pkg/planner/core/index_join_path.go
- pkg/planner/core/physical_plans.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_clone_generated.go
- pkg/planner/core/point_get_plan.go
- pkg/planner/core/util.go
Problem Summary: planner: shallow copy more field for Instance Plan Cache to improve performance
planner: shallow copy more field for Instance Plan Cache to improve performance
These unnecessary clone operations could cause more than 10% regression in some benchmarks:
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: shallow copy more field for Instance Plan Cache to improve performance

- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
In the following scenario:
1. In a three-node cluster, node1 initially becomes the stats owner and starts and initializes the PQ.
2. Due to network or etcd issues, an owner re-election occurs.
3. Node2 becomes the stats owner, starting and initializing the PQ, while node1 shuts down the PQ.
4. Another issue triggers a re-election.
5. Node1 is re-elected as the owner. However, because we forgot to reset `pq.syncFields.initialized`, it can no longer properly start or reinitialize the PQ.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guid …
> statistics: make sure the PQ can be re-initialized

- pkg/domain/domain.go
Issue Number: close #57199 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> domain: set right order to compaign stats owner

- dumpling/export/dump.go
Issue Number: ref #53082 
Related to: https://github.com/pingcap/tidb/issues/53082#issuecomment-2103937423
I think failure to collect metadata should be at least a warning instead of an info message.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> dumpling: make metadata collection failure a warning

- .github/workflows/integration-test-dumpling.yml
- dumpling/export/config.go
- dumpling/export/dump.go
- dumpling/export/metadata.go
- dumpling/export/metadata_test.go
- dumpling/export/sql.go
- dumpling/tests/consistency/run.sh
Issue Number: close #53082 
Tests 
> 
Side effects
Documentation
```release-note
Dumpling now supports dumpling databases from MySQL 8.4 and newer
```
> dumpling: New terminology for MySQL

- pkg/ddl/job_worker.go
- pkg/ddl/notifier/BUILD.bazel
- pkg/ddl/notifier/events.go
- pkg/ddl/notifier/testkit_test.go
- pkg/ddl/schema.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler_test.go
- pkg/statistics/handle/ddl/ddl.go
Issue Number: ref https://github.com/pingcap/tidb/issues/57227
We forget to handle the drop schema event in the PQ. So in this PR, we used the DDL notifier to deliver the drop schema event to the PQ. In the PQ, we try to delete the table jobs for the tables that come from this schema.
To avoid a transition that is too large, I created some mini-structs to include only the essential information for the schema event.
I also split the job into smaller jobs so that the subscriber can avoid performing a bulk update.
Tests 
> 
Side effects
Documentation …
> ddl,statistics: handle the drop database event in the PQ

- tests/realtikvtest/sessiontest/session_fail_test.go
Issue Number: close #57221
- Why there is a DATA RACE?
Because there are some goroutine resource leak.
And the leaked background goroutine conflict with the main goroutine when executing the next SQL statement.
- Why the test code cause resource leak?
As you can see, for unistore and real tikv, the behaviour differs.
The failpoint cause error on unistore, but it success on tikv.
Then, on the real tikv case, the code is not rubost, it forget to close the result when the SQL actually success.
https://github.com/pingcap/tidb/blob/1770006c2e8f40bcc79068e8d8210de0768a8b83/tests/realtikvtest/sessiontest/session_fail_test.go#L68-L73
- So why the behaviour differs on real tikv and unistore?
Here, when we use the failpoint mock, we return error on unistore.
But for real tikv, we …
> realtikvtest/sessiontest: fix data race for test TestGetTSFailDirtyState

- br/pkg/restore/snap_client/systable_restore_test.go
- pkg/ddl/tests/fastcreatetable/fastcreatetable_test.go
- pkg/session/bootstrap.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #57214
Tests 
bootstrap new cluster, it should be enabled
upgrade from 8.1.1, it's keep old value after upgrade
> 
Side effects
Documentation
```release-note
None
```
> ddl: enable fast create table on default

- pkg/planner/core/casetest/instanceplancache/BUILD.bazel
- pkg/planner/core/casetest/instanceplancache/concurrency_test.go
- pkg/planner/core/plan_cache.go
- pkg/planner/core/plan_cache_rebuild_test.go
- pkg/planner/core/plan_cache_utils.go
- pkg/planner/core/plan_clone_utils.go
- pkg/planner/core/point_get_plan.go
Problem Summary: planner: optimizer the performance of PointPlan for Instance Plan Cache
planner: optimizer the performance of PointPlan for Instance Plan Cache
9X faster:
```
Original Clone:
6381717               160.8 ns/op           801 B/op          5 allocs/op
Fast Clone:
69654463                17.13 ns/op            0 B/op          0 allocs/op
```
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: optimize the performance of PointPlan for Instance Plan Cache

- statistics/handle/handle.go
- statistics/handle/handle_hist_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/57264
when we read stats for merge global stats, we forget to force to load fm skretch. so it will lead wrong NDV.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: wrong NDV when to merge global stats with index

- pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go
Issue Number: close https://github.com/pingcap/tidb/issues/57257
After switching to the new PQ, we only have one chance to analyze newly added indexes. For example, if two indexes are created in a very short period and the analyze version 1 is used, we need to analyze these indexes separately.
However, with the current implementation, we only analyze one index at a time, which means the second index will be missed.
In this PR, I’ve checked the analyze version to ensure proper handling. The lower versions don’t have this issue because we can analyze the second index after rebuilding the entire priority queue.
Tests 
> 
Side effects
Documentation …
> statistics: make sure PQ can analyze all indexes with stats version 1

- pkg/expression/aggregation/descriptor.go
- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add hash64 and equal for maxOneRow and fix some bugs.

- pkg/executor/builder.go
- pkg/planner/core/common_plans.go
- pkg/planner/core/issuetest/planner_issue_test.go
- pkg/planner/core/planbuilder.go
- pkg/planner/core/tests/analyze/BUILD.bazel
- pkg/planner/core/tests/analyze/analyze_test.go
- pkg/planner/core/tests/analyze/main_test.go
Issue Number: close #57079
the problem happen at the ```executorBuilder.buildAnalyze```.
```ColumnInfos2ColumnsAndNames``` will find the virtual reference column by the ```column Infos```. but when we enable ```analyze_skip_column_types```, ```column Infos``` will lost some columns. so it cannot find its needed column.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix the problem of not finding the referenced column in the virtual column

- br/pkg/streamhelper/basic_lib_for_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/57298
As title.
add mutex for race functions.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix data race in scan locks

- pkg/parser/ast/misc.go
- pkg/parser/parser.y
- pkg/parser/parser_test.go
Issue Number: ref #57229
ref #57229, we need a new grammer to dynamically adjust related parameters during the ddl operation, Similar to the existed `admin cancel ...` and `admin pause ...`, we use `admin alter ...` as an syntax entrance to implement the adjust logic.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> parser: support `admin alter ddl jobs` grammar

- statistics/handle/handle.go
- statistics/handle/handle_hist_test.go
close pingcap/tidb#57264
Issue Number: close #57264
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: wrong NDV when to merge global stats with index (#57269)

- br/pkg/streamhelper/advancer.go
- br/pkg/utils/key.go
- br/pkg/utils/key_test.go
Issue Number: Close #57316
See the issue.
Replaced all `CloneSlice` with `slices.Clone`.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> chore: use `slices.Clone` to replace CloneSlice

- pkg/ddl/add_column.go
- pkg/executor/test/writetest/write_test.go
- pkg/types/datum.go
- pkg/types/datum_test.go
- tests/integrationtest/r/ddl/column.result
- tests/integrationtest/r/table/tables.result
- tests/integrationtest/t/ddl/column.test
- tests/integrationtest/t/table/tables.test
Issue Number: close #57301, close https://github.com/pingcap/tidb/issues/57312
1. The `CREATE TABLE` statement didn't assert whether the default value for `BIT` is valid.
2. The default value for `BIT` column is casted multiple times and may cause unexpected behavior.
1. Revert part of #21310
2. Validate the length of `BIT` default value.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> table: fix the issue that the default value for `BIT` column is wrong | tidb-test=pr/2424

- pkg/statistics/handle/autoanalyze/priorityqueue/analysis_job_factory.go
- pkg/statistics/handle/autoanalyze/priorityqueue/analysis_job_factory_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/calculator_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/calculatoranalysis/calculator_analysis_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/heap_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/job_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/non_partitioned_table_analysis_job_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
- pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job.go
- pkg/statistics/handle/autoanalyze/priorityqueue/static_partitioned_table_analysis_job_test.go
- pkg/statistics/handle/autoanalyze/refresher/BUILD.bazel
- pkg/statistics/handle/autoanalyze/refresher/refresher.go
- pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
- pkg/statistics/handle/autoanalyze/refresher/worker_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/57227
After https://github.com/pingcap/tidb/pull/57222, we can handle most cases where tables have been dropped. However, there is still a chance that we might attempt to analyze a non-existent table or use incorrect information to perform the analysis.
In this PR, I check the schema and table information before performing the actual analysis. This helps minimize unnecessary analysis work.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> statistics: do not analyze non exist table anymore

- br/cmd/br/debug.go
- br/pkg/metautil/BUILD.bazel
- br/pkg/metautil/debug.go
- br/pkg/metautil/debug_test.go
- br/pkg/metautil/metafile.go
- br/pkg/utils/BUILD.bazel
- br/pkg/utils/json.go
- br/pkg/utils/json_test.go
- br/tests/br_debug_meta/run.sh
Issue Number: close #56296
We can only see the main `backupmeta.json`.
decode the meta file and stats file.
Tests 
```
$ ls -aF1 /tmp/testbr
./
../
1/
backup.lock
backupmeta
backupmeta.datafile.000000001
backupmeta.schema.000000002
backupmeta.schema.stats.000000110
jsons/
$ ls -aF1 /tmp/testbr/jsons
./
../
backupmeta.datafile.000000001.json
backupmeta.json
backupmeta.schema.000000002.json
backupmeta.schema.stats.000000110.json
```
```
backupmeta.datafile.000000001.json
{
"data_files": [
{
"name":"..",
"sha256":"lu4KiCseT0M6dG2gghZXDwD5WOUOqDMhYKcLHMuDYGA=",
"start_key":"..",
"end_key":"..",
"end_version":452625823236882437,
"crc64xor":17088955387164552884,
"total_kvs":1,
"total_bytes":47,
"cf":"write",
"size":1673,
"cipher_iv":..,
},
...
],
}
```
``` …
```
> br: fix debug decode backupmeta

- pkg/executor/cte.go
- pkg/executor/test/issuetest/BUILD.bazel
- pkg/executor/test/issuetest/executor_issue_test.go
Issue Number: close #55881
The root cause is described in https://github.com/pingcap/tidb/issues/55881#issuecomment-2348366506
This pr fix it by 
1. when close the cte producer, check if `e.producer.resTbl.Done()` is false, which means the producer is opened without produce, in this case, close will reset the cte producer
2. before produce the cte producer, double check if it is already opened, if not, then open the cte producer before actually produce it.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix random cte error under apply

- DEPS.bzl
- go.mod
- go.sum
Issue Number: close https://github.com/pingcap/tidb/issues/57310
Tests 
before:
after:
> 
```release-note
None
```
> mod: update client-go to use new RC interface

- br/pkg/rtree/rtree.go
Issue Number: close #53529
it preallocates too much items and uses too much memory.
reduce the number of preallocated items
Tests 
> 
Side effects
Documentation
```release-note
None
```
> br: reduce memory usage when get incomplete ranges

- pkg/meta/model/BUILD.bazel
- pkg/meta/model/table.go
- pkg/planner/core/generator/hash64_equals/BUILD.bazel
- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_aggregation.go
- pkg/planner/core/operator/logicalop/logical_datasource.go
- pkg/planner/core/operator/logicalop/logical_expand.go
- pkg/planner/core/operator/logicalop/logical_join.go
- pkg/planner/core/operator/logicalop/logical_schema_producer.go
- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: take logical schema producer into logical operator's hash generation

- pkg/domain/domain.go
- pkg/planner/core/plan_cache_instance.go
- pkg/planner/core/plan_cache_instance_test.go
- pkg/sessionctx/context.go
Problem Summary: planner: evict all cached plans after disabling instance plan cache
All cached plans are automatically cleaned.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: evict all cached plans after disabling instance plan cache

- pkg/server/handler/optimizor/plan_replayer_test.go
- pkg/statistics/handle/storage/json.go
- pkg/statistics/histogram.go
Issue Number: close #56083
We will reuse the memory when to create stats. so we need to copy memory into ```JsonTbl```. but we forget to copy.so it lead to break lower bound and upper bound.
pkg/statistics/handle/storage/json.go:91 (it will try to reuse the memory)-> GenJSONTableFromStats -> dumpJSONCol -> HistogramToProto (it forget to copy it)
Tests 
> 
Side effects
Documentation
```release-note
fix bad lower bound and upper bound when to dump stats into json
修复在dump stats转json过程中，导致 hist 上下界数据受损的问题 
```
> statistics: fix bad lower bound and upper bound when to dump stats into json

- pkg/executor/infoschema_reader.go
- tests/integrationtest/r/executor/infoschema_reader.result
- tests/integrationtest/t/executor/infoschema_reader.test
Issue Number: close #57345
The issue was introduced by #31463 and accidentally fixed by #55263. Since #55263 involves a lot of refactoring code, it is not easy to cherry-pick, so I filed this PR for cherry-picking.
- Improve retrieval logic. If `extractor.SkipRequest` is true, we should return the empty result directly.
- Add integration tests.
This PR doesn't fix the issue, it is only used to cherry-pick 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: improve retrieval logic in hugeMemTableRetriever and add tests

- pkg/executor/infoschema_reader_test.go
Issue Number: close #57306
Problem Summary: `TestColumnTable` and `TestIndexUsageTable` assert that the number of rows in the `information_schema.columns` and `information_schema.tidb_index_usage` tables match certain hardcoded values. The number of rows reflect *all* columns and indexes in the database, not just those added by the test cases. Whenever any (unrelated) new column, table, or index is added to the information schema, these hardcoded values no longer match, causing the tests to fail spuriously.
Add a `where` clause that constrains `select count(*) from information_schema.{columns,tidb_index_usage}` to the tables/views that the test case added.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language …
> executor: constrain test cases that check for a hardcoded row count

- pkg/ddl/ddl.go
- pkg/ddl/ingest/config.go
- pkg/ddl/job_submitter.go
- pkg/ddl/util/util.go
- pkg/executor/test/ddl/BUILD.bazel
- pkg/executor/test/ddl/ddl_test.go
- pkg/sessionctx/variable/sysvar.go
- pkg/sessionctx/variable/tidb_vars.go
Issue Number: close #57156
See the issue description
Introduce a new system variable to control the `store-write-bwlimit` when ingesting
Tests 
> 
Manual test:
1. bootstrap a cluster
2. Turn on `tidb_ddl_enable_fast_reorg`, and with `tidb_enable_dist_task` on or off, do the following test:
1. set the `tidb_ddl_reorg_max_write_speed` to `1mb`
2. add index for a table, the speed is slow
3. after setting the `tidb_ddl_reorg_max_write_speed` to `0`(no limitation), the speed of adding index increases
For a table containing 200,000 rows:
```sql
TiDB root@127.0.0.1:test> select count(*) from t1;
+----------+
| count(*) |
+----------+
| 200000   |
+----------+
1 row in set
Time: 0.272s
TiDB root@127.0.0.1:test> select * from …
```
> ddl: introduce a new system variable to control the `store-write-bwlimit` when ingesting

- pkg/planner/core/rule_predicate_simplification.go
- tests/integrationtest/r/planner/core/issuetest/planner_issue.result
- tests/integrationtest/t/planner/core/issuetest/planner_issue.test
Issue Number: close #56270
When checking predicate type in predicate simplification, it will use arg[0] to judge if the arg is *expression.Column, however, "rand()" has 0 argument, which will lead a panic.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: Fix predicate simplification panic caused by zero-argument expressions like rand()

- pkg/planner/core/partition_pruning_test.go
- pkg/planner/core/rule_partition_processor.go
- pkg/util/ranger/detacher.go
Issue Number: close #57261
Problem Summary: Don't use `sortKey` to do partition prune.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: fix RANGE COLUMNS partition prune gives wrong result with special collation

- pkg/parser/ast/dml.go
- pkg/planner/core/preprocess.go
- pkg/planner/core/preprocess_test.go
Issue Number: close #56726 
```delete tt1 from t1 tt1,(select max(id) id from t2)tt2 where tt1.id<=tt2.id```
```delete tt1``` will be transfer to ```delete current_database.t1``` in default when to deal with the statsment in the ```create binding```.
because ```tt1``` cannot be used as alias in delete statement.
so we have to set ```tt1``` as alias by aliasChecker.
Tests 
> 
Side effects
Documentation
```release-note
fix cannot binding for deleting multi table with alias
修复无法为带别名的多表删除进行 binding 的问题
```
> planner: fix cannot binding for deleting multi table with alias 

- pkg/expression/builtin_math.go
- tests/integrationtest/r/expression/constant_fold.result
- tests/integrationtest/t/expression/constant_fold.test
Issue Number: close #53546 
When `truncate([const], NULL)` is NULL, `truncate([const], NULL) is not NULL` evaluates to 1 unexpectedly.
In master, all the flags of `arg0` are copied to a truncate function.
If `arg0` is a constant, `NotNullFlag` is copied, leading to an unexpected constant fold.
Only `UnsignedFlag` is copied, which is similar behavior to the round function.
`round([const], NULL)` is also NULL, but `round([const], NULL) is not NULL` returns 0 as expected, so it is used as the reference.
The root cause of this problem refers to https://github.com/pingcap/tidb/issues/53546#issuecomment-2478340107
Tests 
> 
Side effects
Documentation …
> expression: fix incorrect copy of flag in truncate function

- pkg/meta/model/index.go
- pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
- pkg/planner/core/operator/logicalop/hash64_equals_generated.go
- pkg/planner/core/operator/logicalop/logical_table_dual.go
- pkg/planner/core/operator/logicalop/logical_top_n.go
- pkg/planner/core/operator/logicalop/logical_union_scan.go
- pkg/planner/core/operator/logicalop/logical_window.go
- pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
- pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go
- pkg/planner/util/handle_cols.go
Tests 
> 
Side effects
Documentation
```release-note
None
```
> planner: add hash64 equals for tableDual/topN/unionScan/Window.

- lightning/pkg/importer/import.go
- pkg/lightning/mydump/loader.go
- pkg/lightning/mydump/loader_test.go
Issue Number: close #56104
From test, before this pr, lightning importing ten files in parquet format needs to takes 4m40s in the preparation stage. After this pr, lightning importing ten files in parquet format needs to takes 1m10s.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> lightning: sample once parquet file

- pkg/domain/db_test.go
Issue Number: close https://github.com/pingcap/tidb/issues/56851
- Fix unstable case.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> test: fix unstable case

- pkg/executor/join/join_table_meta.go
- pkg/executor/join/join_table_meta_test.go
Issue Number: close #57450, ref #53127
In hash join v2, if the join need to set usedFlag during probe stage, there is potantial data race, this pr fix it by make nullmap length 4 byte alignment if join need usedFlag.
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: fix data race in nullmap in hash join v2

- pkg/ttl/ttlworker/job_manager.go
- pkg/ttl/ttlworker/job_manager_integration_test.go
Issue Number: close #57404
If a job's hearbeat timeout, it cannot be cancelled after disabling the TTL job.
Move the logic of locking the heartbeat timeout job above the logic of cancelling jobs.
Tests 
> 
```release-note
None
```
> ttl: cancel the hearbeat timeout job after disable the TTL

- pkg/bindinfo/session_handle_test.go
- pkg/distsql/distsql_test.go
- pkg/executor/internal/exec/executor.go
- pkg/expression/integration_test/integration_test.go
- pkg/util/execdetails/execdetails.go
- pkg/util/execdetails/execdetails_test.go
Issue Number: close #56233 ref #56232 
Some executors' open or close operation may take too much time, thus we'd probably record these time in execution summary. 
#55957 provides an example that table reader operator's open takes much time while not included.
#50377 provides an example that limit operator's close takes much time while not included. 
**TPCH Q3 TiFlash**
```
+--------------------------------------------------------------------+------------+---------+--------------+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
> distsql,util: Add executor open close time into its total consume time

- pkg/sessionctx/variable/noop.go
Issue Number: close #57459 
Problem Summary: Some applications are complaining that the innodb_buffer_pool_size is too small. Since it doesn't affect any logic in TiDB, we can safely increase the default value so it will work out of box in this situation
Tests 
> 
Side effects
Documentation
```release-note
The noop global variable innodb_buffer_pool_size is increased to 4GiB 
```
> variables: Increase default innodb_buffer_pool_size to 4GiB

- pkg/sessionctx/variable/tidb_vars.go
- tests/integrationtest/r/sessionctx/setvar.result
Issue Number: close #57444 , ref #53127
Hash join v2 is enabled in release-8.5 branch for test purpose, this pr disable it by default. 
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: disable hash join v2 in release-8.5 by default

- pkg/ddl/index.go
- pkg/ddl/index_modify_test.go
- pkg/kv/key.go
- pkg/kv/key_test.go
- pkg/table/tables/index.go
Issue Number: close #57414
Unlike other indices, global index encodes the value of its key-value pairs with a partition ID:
https://github.com/pingcap/tidb/blob/2ca497e23e1488a1675dfe5793296b8b367c261b/pkg/tablecodec/tablecodec.go#L1630-L1649
So during the double write process, we may do comparison between partition handles and non-partition handles.
https://github.com/pingcap/tidb/blob/2ca497e23e1488a1675dfe5793296b8b367c261b/pkg/table/tables/index.go#L419-L432
For example, in #57414, `h` is the handle of global index `i1` whose type is `PartitionHandle` while `oh` is `IntHandle` of the current index. Thus, `!h.Equal(oh)` will return false.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language …
> table: fix wrong handle comparation in index double write

- errors.toml
- pkg/planner/core/planbuilder.go
- pkg/util/dbterror/ddl_terror.go
- tests/integrationtest/r/ddl/ddl_error.result
- tests/integrationtest/r/executor/ddl.result
- tests/integrationtest/t/ddl/ddl_error.test
- tests/integrationtest/t/executor/ddl.test
Issue Number: close #53176
No check if there were variables in the CREATE VIEW statement.
Added a visitor to check for `VariableExpr` and give an error for such CREATE VIEW
Tests 
> 
Side effects
Documentation
```release-note
Do not allow Variables or Parameters in CREATE VIEW, just like MySQL.
```
> planner: Do not allow variables in create view

- pkg/lightning/mydump/reader.go
Issue Number: close #57413
When importing from cloud storage, high concurrency can lead to bottlenecks in mydump.PooledReader.Seek(0, io.SeekCurrent) due to the application of ioWorkers. Seek(0, io.SeekCurrent) does not cause disk IO operations, applying ioWorkers is unnecessary.
Skip apply ioworkers when seek(0, io.SeekCurrent)
Tests 
> 
Side effects
Documentation
```release-note
None
```
> Lightning: Skip apply ioworkers when seek(0, io.SeekCurrent)

- pkg/executor/join/base_join_probe.go
- pkg/executor/join/join_row_table.go
- pkg/executor/join/join_row_table_test.go
- pkg/executor/join/join_table_meta.go
- pkg/executor/join/left_outer_semi_join_probe_test.go
- pkg/executor/join/row_table_builder.go
- pkg/util/chunk/chunk.go
- pkg/util/chunk/column.go
- pkg/util/codec/codec.go
In TiDB the max row size is 128MB, so for a specific element in any table, it's size should not exceed `math.MaxUint32`, so this pr use `uint32` as the element size in hash join v2
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: Use uint32 as element length in hash join v2

- docs/tidb_http_api.md
related this topic: https://asktug.com/t/topic/1033423/4
@zimulala could you help take a look?
Tests 
> 
Side effects
Documentation
```release-note
None
```
> docs: fix parameter format in tidb_http_api.md

- pkg/expression/aggregation/descriptor.go
- pkg/expression/expression.go
- pkg/expression/expression_test.go
- pkg/expression/integration_test/BUILD.bazel
- pkg/expression/integration_test/integration_test.go
- pkg/planner/core/casetest/rule/BUILD.bazel
- pkg/planner/core/casetest/rule/rule_outer2inner_test.go
- pkg/planner/core/casetest/rule/testdata/outer2inner_in.json
- pkg/planner/core/casetest/rule/testdata/outer2inner_out.json
- pkg/planner/core/operator/logicalop/logical_aggregation.go
- pkg/planner/core/rule_aggregation_push_down.go
- pkg/planner/util/null_misc.go
Issue Number: close #55886
1. Both `evaluateExprWithNull` and `evaluateExprWithNullInNullRejectCheck` use `NewFunction` instead of `NewFunctionInternal` to create a scalar function
2. let `EvaluateExprWithNull` return error if some error happens inside `EvaluateExprWithNull`
2. The caller of `EvaluateExprWithNull` need to decide how to handle this error, currently, all the callers of `EvaluateExprWithNull` are optimizer, and will ignore the error
Tests 
> 
Side effects
Documentation
```release-note
None
```
> expression: Fix optimizer panic in evaluate expr with null

- pkg/executor/test/oomtest/oom_test.go
Issue Number: close #57509
update log filter to avoid flaky test
Tests 
> 
Side effects
Documentation
```release-note
None
```
> executor: update log filter to avoid flaky test
