pingcap/tidb

pkg/executor/adapter.go
pkg/session/session.go
pkg/session/test/variable/BUILD.bazel
pkg/session/test/variable/variable_test.go

Issue Number: close #57396
When a query statement is not in utf-8, e.g. `_binary 'some_binary_data'`, `GENERAL_LOG` logs the utf-8 text, not the original text. This is because `ExecStmt.OriginText` simply returns `Text`, not `StmtNode.OriginalText`.
This PR fixes `ExecStmt.OriginText` to return `StmtNode.OriginalText`, and includes the quoted query in `GENERAL_LOG`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor, session: fix ExecStmt.OriginText to use the actual original text

---

pkg/executor/join/hash_join_v2.go

Issue Number: ref #57450
Init rowTableBulider in BuildWorkerV2 before start worker.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix data race in hash join v2 spill

---

pkg/executor/infoschema_reader_test.go
pkg/planner/core/memtable_infoschema_extractor.go
pkg/planner/core/memtable_predicate_extractor.go

Issue Number: close #56987
`InfoSchemaBaseExtractor` wrongly filter table names for the fast path introduced by https://github.com/pingcap/tidb/pull/55574 
Introduce a new variable `extractLowerString` to dertermine whether to do case-insensitive comparisons for specific columns.
Test case is not added in integration test because we don't want to write some hardcoded value. (ref #57306)
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix `count(*)` return wrong value for `information_schema.tables`

---

pkg/expression/builtin_cast.go
pkg/expression/builtin_convert_charset.go
pkg/expression/expr_to_pb_test.go
pkg/planner/core/integration_test.go
tests/integrationtest/r/expression/cast.result
tests/integrationtest/t/expression/cast.test
tests/realtikvtest/pushdowntest/BUILD.bazel
tests/realtikvtest/pushdowntest/expr_test.go
tests/realtikvtest/pushdowntest/main_test.go

Issue Number: close #56494
When casting the bit type to a non binary string, this PR first convert bits to binary string first. This can ensure `HandleBinaryLiteral` can be used in the following code and convert binary to the specified collation with right behavior.
Tests 
> 
Side effects
Documentation
```release-note
fix tikv crash when `bool like cast(bit as char)`
```

expression: fix tikv crash when `bool like cast(bit as char)`

---

pkg/disttask/framework/scheduler/scheduler.go
pkg/disttask/framework/scheduler/scheduler_manager.go
pkg/disttask/framework/taskexecutor/manager.go
pkg/disttask/framework/taskexecutor/task_executor.go

- reduce indent of scheduleTask, will refactor it further after add `modifying` state
- some log refactor
Tests 
> 
Side effects
Documentation
```release-note
None
```

dxf: reduce indent of scheduleTask and some log refactor

---

pkg/statistics/handle/cache/statscache.go
pkg/statistics/handle/metrics/metrics.go

Issue Number: close #57176
we use the wrong index of total table count metrics. 
Tests 
> 
Side effects
Documentation
```release-note
None
```

statstics: fix wrong stats health metrics 

---

br/pkg/storage/gcs.go

Issue Number: close #56127
Always retry with GCS requests.
Tests 
> 
Side effects
Documentation
```release-note
None
```

Dumpling: GCS always retry.

---

DEPS.bzl
errors.toml
go.mod
go.sum
pkg/errno/errcode.go
pkg/errno/errname.go
pkg/executor/adapter.go
pkg/executor/executor_pkg_test.go
pkg/executor/mem_reader.go
pkg/executor/union_scan.go
pkg/executor/union_scan_test.go
pkg/kv/error.go
pkg/kv/key.go
pkg/kv/key_test.go
pkg/session/test/txn/BUILD.bazel
pkg/session/test/txn/txn_test.go
pkg/store/driver/error/error.go
pkg/store/driver/error/error_test.go
pkg/store/driver/txn/BUILD.bazel
pkg/store/driver/txn/driver_test.go
tests/integrationtest/r/executor/ddl.result
tests/integrationtest/r/globalindex/insert.result
tests/integrationtest/t/executor/ddl.test
tests/integrationtest/t/globalindex/insert.test

Issue Number: ref #55287, close #56837, ref #57338, close #57425
Introduce the chunk comparison of common prefix (`amd64` and `arm64` only), which can accelerate a lot for indexes with very wide columns.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: bump client-go with some regression tests

---

pkg/expression/builtin_json.go
pkg/parser/mysql/errcode.go
pkg/parser/mysql/errname.go
pkg/parser/mysql/state.go
pkg/types/field_type.go
tests/integrationtest/r/expression/json.result
tests/integrationtest/t/expression/json.test

Issue Number: close #54029, close #54044
For some json functions, the arg verification is not implemented correctly:
1. For `json_type`, it didn't verify the type of args.
2. For many other json functions, they didn't verify the charset of the args.
For `PREPARE`, the param marker is set to binary string type, which is not expected. This PR will give it a default collation. It will not affect the `EXECUTE`, because when it's executing a statement, it'll infer the collation according to the datum (whose collation is set according to the collation settings of the connection).
1. Add a unified function to verify the args of json functions.
2. Modify the collation of param marker from binary to default collation.
Tests 
> …

expression: fix the arg verification for json functions.

---

pkg/owner/manager.go

Issue Number: close #57533
I'm not sure how the error is triggered.
But reading the code, I can see that line 405, if condition `terror.ErrorEqual(err, rpctypes.ErrLeaseNotFound)` hold, the error is not reset. So this loop will happen again and again, cause the log print.
Tests 
> 
Don't know how to reproduce but it's easy to fix by reading the code 
Side effects
Documentation
```release-note
None
```

owner: fix unlimited log print "meet lease not found error, refresh session"

---

pkg/distsql/BUILD.bazel
pkg/distsql/context/context.go
pkg/distsql/context/context_test.go
pkg/distsql/request_builder.go
pkg/distsql/request_builder_test.go
pkg/executor/batch_point_get.go
pkg/executor/point_get.go
pkg/kv/kv.go
pkg/session/session.go
pkg/store/copr/batch_coprocessor.go
pkg/store/copr/coprocessor.go

This change plumbs the TiDB query max execution time to the executor point_get(bath_point_get) and coprocessor(batch_coprocessor) tasks to timebox the GetRegion PD grpc calls (and other task operations). 
Issue Number: ref #56753
1. Plumbed query execution time to kv request and distsql context
2. Set context deadline based on query max execution time for point get snapshot read (point_get and batch_point_get)
3. Set context deadline based on query max execution time for coprocessor tasks (coprocessor and batch_coprocessor)
Tests 
> 
Side effects
Documentation …

executor, store: Plumb the query max execution time to timebox the PD GetRegion grpc calls

---

pkg/planner/core/point_get_plan.go
pkg/planner/core/point_get_plan_test.go

Issue Number: close #56832
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: set enumsetasint if original value is int in point get

---

pkg/executor/check_table_index.go
pkg/executor/test/admintest/BUILD.bazel
pkg/executor/test/admintest/admin_test.go

Issue Number: close #57153
When generating index SQL under fast admin check mode, use the correct names for virtual columns.
More specifically, only use `GeneratedExprString` when column is hidden.
https://github.com/pingcap/tidb/blob/7fe6cfec152ce6e102cb672f6de559f954005644/pkg/executor/check_table_index.go#L377-L380
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix admin check return wrong result for index containing generated columns

---

pkg/lightning/errormanager/errormanager.go
pkg/lightning/errormanager/errormanager_test.go
pkg/lightning/errormanager/resolveconflict_test.go

Issue Number: close #57578
https://github.com/pingcap/tidb/pull/55477 change the behavior of null value insert. To adapt to this change, some `NOT NULL` constraints have to be removed.
Previous PR just wrongly change `INSERT INTO` to `INSERT IGNORE INTO`, which may case data correctness.
Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning: remove some `NOT NULL` constraints on lightning table

---

pkg/executor/executor_failpoint_test.go

Issue Number: close #57348
After #57050 , the safety check on stale read ts is made strict, making sure that the stale read ts never exceeds that PD has allocated.
However there seems still exists some test code that have some unsafe usage of stale read (such as reading at `now`). For these usages, the read ts has chance to exceed PD's max allocated ts, causing the ts validation failed.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: Fix unstable test TestTiKVClientReadTimeout

---

pkg/statistics/handle/syncload/BUILD.bazel
pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/handle/syncload/stats_syncload_test.go

Issue Number: close #57138
Sometimes, we disable the analysis of certain columns using analyze_skip_column. However, these columns may still retain outdated statistics, especially after being modified. Since their statistics are larger, syncing them via sync load can be very slow and prone to timeouts. To address this, we filter out these columns.
Tests 
> 
Side effects
Documentation
```release-note
statsitstics: avoid sync load column which is skiped to analyze
避免将 skip analyze 的列通过 sync load 加载
```

statsitstics: avoid sync load column which is skiped type to analyze

---

br/pkg/task/common.go
br/pkg/task/common_test.go

Issue Number: close #57585
Problem Summary: Some values from the command line are not properly redacted.
In additional to the existing handling for `--storage`, we also apply redaction to the following parameters:
* `--full-backup-storage`
* `--crypter.key`
* `--log.crypter.key`
* `--azblob.encryption-key`
* `--master-key` (the current implementation of this may be too conservative)
Tests 
> 
Side effects
Documentation
```release-note
When invoking BR in command line with secret keys passed directly from arguments, they are no longer printed as plaintext in …
```

br: redact secret strings when logging arguments

---

pkg/statistics/handle/util/BUILD.bazel
pkg/statistics/handle/util/table_info.go

Issue Number: close #57573
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: use infoschema api to get table info

---

pkg/ddl/partition_test.go
pkg/table/table.go
pkg/table/table_test.go

Issue Number: close #57588
Didn't set `isUpdate = true` before, so it will use the last value in datum as `_tidb_rowid` which caused primary key duplicate.
If we don't do this during add columns, `len(r) == len(cols)` always equal to true, so it's safe.
Tests 
> 
Side effects
Documentation
```release-note
None
```

partition: set `AddRecordOpt.isUpdate = true` when update partition records

---

pkg/planner/core/logical_plan_builder.go
pkg/planner/core/planbuilder.go
tests/integrationtest/r/privilege/privileges.result
tests/integrationtest/t/privilege/privileges.test

Issue Number: close #53490
See https://github.com/pingcap/tidb/issues/53490#issuecomment-2128700572, for statement like:
```
with t_f as (
select id,pid,name,'AAA' fullname from test.tt1 )
update test.tt1 inner join t_f
set tt1.fullname=t_f.fullname
where tt1.id=t_f.id;
```
The privilege check for CTE in the update statement should be avoided.
Tests 
> 
Side effects
Therocially it consumes more CPU to remove the privilege check, but I believe the real world performance will not be impacted.
Documentation
- NA
```release-note
Fix a wrong …
```

planner/core: fix a wrong privilege check for CTE & UPDATE statement

---

pkg/executor/adapter.go
pkg/executor/compiler.go
pkg/executor/test/executor/executor_test.go
pkg/session/session.go
pkg/util/sqlexec/restricted_sql_executor.go

executor, session: store utf8 string in `sessionctx`

---

pkg/statistics/handle/autoanalyze/priorityqueue/analysis_job_factory.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
pkg/statistics/handle/autoanalyze/refresher/refresher.go

Issue Number: close https://github.com/pingcap/tidb/issues/57648
1. Correctly skip the deleted table. Sorry for overlooking this.
2. Make sure we don't write to nil runningJobs and mustRetryJobs because the worker might access them again after the queue is closed (we don't stop the worker at the same time because we don't want to block the etcd election process). Accessing it is ok because we will reinitialize the queue next time. So we will take care of the failed jobs next time.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: handle deleted tables correctly in the PQ

---

pkg/executor/aggregate/agg_hash_partial_worker.go

Issue Number: close #57546
Partial worker gets input by calling `getChildInput` function. In this function, we call `Consume` function to track memory occupied by input chunk. When sql's memory usage is high, there will be possible to lead to panic in `Consume` function. According to the synchronization rule, each time we get a chunk from `getChildInput` we need to call `Done` function for variable `inflightChunkSync`. However, when panic happens `Done` function is not called and the counter in `inflightChunkSync` will never be minused to 0 which leads to hang.
**Solution**: Each time waked up in channel in `getChildInput` function, we will set a variable named `needDone`. When panic happens in `getChildInput` function, we will catch the panic in this function and check …

executor: fix hang in hash agg when exceeding memory limit leads to panic

---

pkg/ttl/ttlworker/config.go
pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_test.go
pkg/ttl/ttlworker/session_test.go

Issue Number: close #57700
The actual splits  = `min(tableRegionCount, max(64, tikvStoreCount))`
Tests 
> 
Side effects
Documentation
```release-note
ttl: enlarge the max split of TTL job for large clusters
```

ttl: enlarge the max split of TTL job

---

.bazelrc

ref https://github.com/bazelbuild/bazel/issues/21626
ref https://github.com/bazel-contrib/rules_go/issues/4116
Tests 
> 
Side effects
Documentation
```release-note
None
```

bazel: remove experimental_remote_merkle_tree_cache

---

br/pkg/backup/prepare_snap/env.go
br/pkg/backup/prepare_snap/prepare_test.go
br/pkg/backup/store.go
br/pkg/checkpoint/external_storage.go
br/pkg/checksum/executor.go
br/pkg/conn/conn.go
br/pkg/encryption/master_key/kms_backend.go
br/pkg/restore/data/data.go
br/pkg/restore/log_client/import.go
br/pkg/restore/log_client/import_retry.go
br/pkg/restore/log_client/import_retry_test.go
br/pkg/restore/misc.go
br/pkg/restore/snap_client/client.go
br/pkg/restore/snap_client/import.go
br/pkg/restore/split/client.go
br/pkg/restore/split/split.go
br/pkg/restore/split/split_test.go
br/pkg/task/backup_ebs.go
br/pkg/task/operator/prepare_snap.go
br/pkg/task/restore.go
br/pkg/task/restore_data.go
br/pkg/utils/backoff.go
br/pkg/utils/backoff_test.go
br/pkg/utils/error_handling.go
br/pkg/utils/retry.go
br/pkg/utils/retry_test.go
br/tests/br_file_corruption/run.sh
br/tests/br_pitr/run.sh
dumpling/export/retry.go

Issue Number: close #54643 
Refactor the BR CLI backoff retry logic to make is more simplified and extendable in future.
Tests 
> 
Side effects
Documentation
```release-note
NA
```

br: refactor br cli backoff logic

---

br/tests/br_encryption/run.sh
br/tests/br_pitr/run.sh
br/tests/br_pitr_failpoint/run.sh
br/tests/br_pitr_gc_safepoint/run.sh
br/tests/br_restore_checkpoint/run.sh
br/tests/br_test_utils.sh
br/tests/br_tiflash_conflict/run.sh

Issue Number: close #57609
Extract the wait for checkpoint to advance logic in integration test to a method
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: refactor test to use wait checkpoint method

---

pkg/statistics/handle/syncload/BUILD.bazel
pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/handle/syncload/stats_syncload_test.go

Issue Number: close #57710 
in the origin code, we can not check the timeout after sending the sync load. so it will block the sending sync load and take too much time.
Tests 
> 
Side effects
Documentation
```release-note
rightly deal with timout when to send sync load
正确处理发送 sync load 的超时
```

statistics: rightly deal with timout when to send sync load 

---

br/pkg/restore/restorer_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/57760
As issue describe.
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix the data race in restore test

---

pkg/ddl/tests/serial/serial_test.go
pkg/ddl/ttl.go
pkg/ddl/ttl_test.go
pkg/executor/show.go
pkg/meta/model/table.go
pkg/meta/model/table_test.go
pkg/ttl/ttlworker/timer_sync.go
pkg/ttl/ttlworker/timer_test.go
tests/integrationtest/r/executor/ddl.result
tests/integrationtest/r/executor/show.result

Issue Number: close #57757
The default value of `ttl_job_interval` changed from `1h` to `24h`
Tests 
> 
Side effects
Documentation
```release-note
ttl: The default value of `ttl_job_interval` changed from `1h` to `24h`
```

ttl: make the default value of `ttl_job_interval` to `24h`

---

pkg/executor/builder.go
pkg/executor/infoschema_reader.go
pkg/infoschema/cluster.go
pkg/infoschema/tables.go
pkg/infoschema/test/clustertablestest/cluster_tables_test.go

Problem Summary: planner: provide a system view `cluster_tidb_plan_cache` to allow users to see the cluster's Plan Cache Info
```
mysql> select * from information_schema.cluster_tidb_plan_cache\G
*************************** 1. row ***************************
INSTANCE: 127.0.0.1:10080
SQL_DIGEST: e5796985ccafe2f71126ed6c0ac939ffa015a8c0744a24b7aee6d587103fd2f7
SQL_TEXT: select * from t
STMT_TYPE: Select
PARSE_USER: root
PLAN_DIGEST: ccb0d7dbb386cbf97a7007105f4b9f48d79db972766c84bfba32e55df7ffede8
BINARY_PLAN: wAFYCr0BCg1UYWJsZVJlYWRlcl81EmoKD1QBEVBGdWxsU2Nhbl80IQEAAAA4DU9BKQABAdiIw0A4AkACSgsKCQoEVEVTVBIBdFIea2VlcCBvcmRlcjpmYWxzZSwgc3RhdHM6cHNldWRvcP//DQIEAXgNCSj//wEhVVVVVZUjEx1ZKAFAAVIUZGF0YTpUNoUAAHAZNyh4////////////AQ==
BINDING: 
OPT_ENV: …
```

planner: provide a system view `cluster_tidb_plan_cache` to allow users to see the cluster's Plan Cache Info

---

pkg/distsql/distsql_test.go
pkg/executor/adapter.go
pkg/executor/builder.go
pkg/executor/distsql.go
pkg/executor/explain_test.go
pkg/executor/index_merge_reader.go
pkg/executor/internal/exec/executor.go
pkg/executor/internal/exec/indexusage.go
pkg/executor/internal/exec/indexusage_test.go
pkg/executor/point_get.go
pkg/planner/core/explain.go
pkg/util/execdetails/execdetails.go
pkg/util/execdetails/execdetails_test.go

Issue Number: close #56746 
Thanks to Keao's [PR ](https://github.com/pingcap/tidb/pull/56485), all executors must be created by either NewBaseExecutorV2 or BuildNewBaseExecutorV2. Thus, we can identify the "parallel time" case by checking if any existing executors have the same ID. Then use a different name, like "total_parallel_time" to display it.
Some special cases:
1. IndexLookUp & IndexMergeReader 's index plan doesn't mapping to an Executor, just mapping to several distsql calls. So need to handle them case by case.
2. PointGet's Init function not only initializes some fields but also re-constructs its BaseExecutor, which is not reasonable, split it to two functions now.
**ParallelApply & IndexLookUp Query**
``` …
```

executor,distsql,util: distinguish walltime from sum of walltime in execution info

---

pkg/ttl/ttlworker/BUILD.bazel
pkg/ttl/ttlworker/scan.go
pkg/ttl/ttlworker/task_manager.go
pkg/ttl/ttlworker/task_manager_integration_test.go
pkg/ttl/ttlworker/task_manager_test.go
pkg/ttl/ttlworker/timer_test.go
pkg/ttl/ttlworker/worker_test.go

Issue Number: close #57708 
The result is not set for the scan task when TiDB is shrinking the scan worker and timeout.
Set a result for the scan task.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: set a result for timeout scan task during shrinking scan worker

---

pkg/ddl/placement_policy.go
pkg/ddl/placement_policy_test.go
pkg/ddl/schema.go
pkg/ddl/table.go
pkg/domain/domain.go
pkg/executor/infoschema_reader.go
pkg/infoschema/infoschema_v2.go
pkg/meta/meta.go
pkg/meta/meta_test.go
pkg/meta/reader.go
pkg/planner/core/memtable_infoschema_extractor.go

Issue Number: close #57749
Check ctx cancel in the loop.
`ListTables`  might be slow when there are too many tables, add a ctx to it to support cancel.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: support cancel query like 'select * from information_schema.tables'

---

pkg/ddl/index.go
pkg/ddl/reorg.go
pkg/ddl/tests/indexmerge/BUILD.bazel
pkg/ddl/tests/indexmerge/merge_test.go

Issue Number: close #57769
> The cause is the PR(https://github.com/pingcap/tidb/pull/56406/files#diff-45ad039a8b87835b475a52615355c444538d3a1f31a84d7b3ac94e15b1ce8721R1159), which uses the user specified timestamp math.MaxInt64 to read directly with DAG interfaces.
Use the transaction key-value interface instead to check if a table is empty.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: fix ExistsTableRow and add tests for skip reorg checks

---

pkg/ddl/partition.go
pkg/ddl/placement_policy_test.go
pkg/ddl/reorg.go
pkg/ddl/rollingback.go
pkg/ddl/tests/partition/BUILD.bazel
pkg/ddl/tests/partition/db_partition_test.go
pkg/ddl/tests/partition/error_injection_test.go
pkg/ddl/tests/partition/multi_domain_test.go
pkg/ddl/tests/partition/reorg_partition_test.go
pkg/ddl/tests/tiflash/ddl_tiflash_test.go
pkg/executor/test/admintest/admin_test.go
pkg/meta/model/job.go
pkg/meta/model/table.go
pkg/planner/core/find_best_task.go
pkg/planner/core/point_get_plan.go
pkg/table/tables/index.go
pkg/table/tables/mutation_checker.go
pkg/table/tables/partition.go
pkg/table/tables/tables.go
pkg/tablecodec/tablecodec.go

Issue Number: close #57721
There were issues with TRUNCATE PARTITION and Global indexes, no rollback and blocked writes during some stages.
Cherry pick of #55831 and #56029
Tests 
> 
Side effects
Documentation
```release-note
No more partition wide write block during "delete only" and "delete reorganization" for TRUNCATE PARTITION
```

*: Fix for TRUNCATE PARTITION and Global Index

---

pkg/planner/core/plan_to_pb.go

Issue Number: ref #54245
When `p.AnnIndexExtra.PushDownQueryInfo.TopK == math.MaxUint32`, there is no need to set `AnnQuery` in `TableScan`/`PartitionTableScan`, since it means do not use vector index.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: do not set AnnQuery when TopK = MaxUint32

---

pkg/planner/core/generator/hash64_equals/hash64_equals_generator.go
pkg/planner/core/operator/logicalop/base_logical_plan.go
pkg/planner/core/operator/logicalop/hash64_equals_generated.go
pkg/planner/core/operator/logicalop/logical_max_one_row.go
pkg/planner/core/operator/logicalop/logical_sequence.go
pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix max-one-row will hash equals to each other because of no elements inside.

---

pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add test for hash64 and equals for logical show and sort operator.

---

pkg/ttl/ttlworker/task_manager_integration_test.go

Issue Number: close #57876 
The worker has started before it sets the context. It may cause data race.
Set the context before start the worker.
Tests 
> It only modified tests.
> 
Side effects
Documentation
```release-note
None
```

ttl,test: fix the datarace in `TestShrinkScanWorkerTimeout`

---

pkg/timer/tablestore/store.go
pkg/ttl/ttlworker/task_manager.go
pkg/ttl/ttlworker/task_manager_integration_test.go
pkg/ttl/ttlworker/task_manager_test.go

Issue Number: close #57784
The TTL task is not cancelled after the owner transfers to other TiDB nodes.
1. Don't report status when the owner is not myself.
2. Don't update heartbeat when the owenr is not myself.
3. Check the affected rows to see whether task manager `UPDATE` successfully.
4. Cancel the task after finding that the owner is not myself.
Tests 
> 
```release-note
None
```

ttl: fix the issue that the task is not cancelled after transfering owners

---

go.mod

Issue Number: close #57896
Tests 
> 
Side effects
Documentation
```release-note
None
```

gomod: specify go patch-level version

---

pkg/statistics/handle/handletest/lockstats/BUILD.bazel
pkg/statistics/handle/handletest/lockstats/lock_table_stats_test.go
pkg/statistics/handle/usage/BUILD.bazel
pkg/statistics/handle/usage/session_stats_collect.go

Issue Number: close https://github.com/pingcap/tidb/issues/57628
We don't need to record the historical stats meta if the table is locked because all the information is stored in the locked tables.
So in this PR, we skip the record when the tables are locked.
Tests 
> 
Side effects
Documentation
```release-note
修复在 tidb_enable_historical_stats 开启并且锁定表统计信息的时候会出现的无效错误日志的问题
Fix the issue of invalid error logs that occur when `tidb_enable_historical_stats` is enabled and table statistics are locked
```

statistics: do not record historical stats meta if the table is locked

---

br/pkg/task/stream.go
br/pkg/utils/BUILD.bazel
br/pkg/utils/encryption.go
br/pkg/utils/wait.go
br/tests/br_pitr_long_running_schema_loading/run.sh
br/tests/run_group_br_tests.sh
pkg/domain/domain.go
pkg/domain/schema_validator.go

Issue Number: close #57743
Wait until schema info finished reloading before proceeding to the rest of the restore process,
Added test to first to reproduce the issue and then add the fix to verify the issue has been fixed (TDD)
Tests 
> 
Side effects
Documentation
```release-note
Fixed loading schema taking long time during restore causing insertGc row and other operations to fail  
```

br: fix insert gc failed due to slow schema reload

---

pkg/planner/core/operator/logicalop/logicalop_test/BUILD.bazel
pkg/planner/core/operator/logicalop/logicalop_test/hash64_equals_test.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add test for logical topN and logical tableDual's hash64 and equals

---

pkg/statistics/handle/ddl/BUILD.bazel
pkg/statistics/handle/ddl/ddl.go
pkg/statistics/handle/ddl/ddl_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/57230
We overlooked handling the drop schema event in the stats DDL handler. In this PR, we'll address this by cleaning up the dropped tables one by one.
Tests 
> 
Side effects
Documentation
```release-note
修复统计信息在整个数据库被删除后无法清理的问题
Fix the issue where statistics cannot be cleaned up after the entire database is deleted.
```

statistics: gc the statistics correctly after drop the database

---

br/pkg/storage/azblob.go
br/pkg/storage/gcs.go
br/pkg/storage/local.go
br/pkg/storage/locking.go
br/pkg/storage/locking_test.go
br/pkg/storage/s3.go
br/pkg/storage/storage.go

Issue Number: ref https://github.com/pingcap/tidb/issues/56523
close https://github.com/pingcap/tidb/issues/57755
The test case `TestConcurrentLock` isn't stable enough.
Make it more stable by stronger syncing.
```console
ok      github.com/pingcap/tidb/br/pkg/storage  9.397s
```
Tests 
> It is a test.
Side effects
Documentation
```release-note
None
```

br: fix flaky test `TestConcurrentLock`

---

dumpling/export/dump.go
dumpling/export/prepare_test.go
dumpling/export/sql.go
dumpling/export/sql_test.go

Issue Number: close #57902
by copilot
dumpling/export/dump.go: The logic for preparing the table list to dump has been updated to optimize the performance of reading INFORMATION_SCHEMA.TABLES for TiDB. It includes conditional checks and refactored code.
dumpling/export/sql.go: The function ListAllDatabasesTables has been refactored for improved readability and efficiency, particularly when querying INFORMATION_SCHEMA.TABLES. The function CheckIfSeqExists has been renamed to checkIfSeqExists.
dumpling/export/sql_test.go: Corresponding test cases have been updated to reflect the renaming of the function CheckIfSeqExists to checkIfSeqExists.
Tests 
> 
```
/dumpling-patch -u root -P 4000 -h xxx --filetype csv -t 16 -r …
```

dumpling: use I_S to get table list for TiDB and add database to WHERE

---

pkg/executor/infoschema_reader.go
pkg/executor/memtable_reader.go

Issue Number: close #57874
The GC should be blocked by query.
There are two places that the transaction should blcok GC:
- The query "SELECT COUNT(1) as c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='SEQUENCE'" itself
- The internal transaction `meta.ListTables` invoked by `SchemaTableInfos()` API
This commit just fix the first one. It should be enough to fix issue 57874.
The root cause is that whe we query on infoschema tables, the transaction is not activated.
So the session process info would not be collected to block GC.
The second issue is caused by the fact that the meta API call does not block GC.
I don't take investigation on it further more, meta API is limited used.
Tests 
Modify the code and build tidb, check no more "GC life time is shorter than …

*: activate txn for query on infoschema tables

---

pkg/executor/infoschema_reader.go

Issue Number: close https://github.com/pingcap/tidb/issues/57816
The timeout is only 1 second for fetching the system table from tiflash instance. When there are thousand of table  with tiflash replica under the disaggregated compute and storage arch, fetching the metadata require accessing files stored on S3. Under that situation, the 1 second is too short for timeout.
https://github.com/pingcap/tidb/blob/9812d85d0d259547cf1dae88abbc7c406c56f935/pkg/executor/infoschema_reader.go#L3484-L3489
Fetching the info with about 5000 tables and 10 TiB data under disaggregated arch take about 3 seconds. Enlarge the timeout for fetching data from each tiflash instance to be 5 minutes is long enough.
And I've tested that the query respect `max_execution_time`.
Tests 
Inject an …

executor: Enlarge the timeout for fetching TiFlash system tables

---

pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go
pkg/ttl/ttlworker/job_manager_test.go
pkg/ttl/ttlworker/task_manager.go
pkg/ttl/ttlworker/task_manager_integration_test.go
pkg/ttl/ttlworker/task_manager_test.go

Issue Number: close #57915
If one task failed to update heartbeat, the other tasks will not be tried. It's not expected.
Print an error and continue to try other tasks.
This PR also adapts the same change for job.
Tests 
> 
```release-note
None
```

ttl: fix the issue that one task losing heartbeat will block other tasks

---

pkg/meta/autoid/autoid.go

Issue Number: close #57877
Some test change the value of `step`, when the tests run parallelly, data race!
Tests 
> 
Side effects
Documentation
```release-note
None
```

meta/autoid: make step variable atomic to fix data race tests

---

pkg/statistics/BUILD.bazel
pkg/statistics/column.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/integration_test.go
pkg/statistics/table.go

close #57722, close #57735
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: fix some problem related to stats async load (#57723) (#57774) | tidb-test=2076e2fac85c636e0f3e0f287efc82465f62476a

---

pkg/statistics/handle/ddl/subscriber.go

Issue Number: ref https://github.com/pingcap/tidb/issues/57871
Split from https://github.com/pingcap/tidb/pull/57872
1. Renamed the handler to "subscriber" to avoid conflict with an existing handler in this package.
2. Correctly handled the schema drop event.
This will be integrated into my next PR, so additional tests will be added. We plan to update the tests in subsequent PRs.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: rename subscriber and handle drop schema event

---

pkg/bindinfo/BUILD.bazel
pkg/bindinfo/binding.go
pkg/planner/core/optimizer.go

Issue Number: close #58016
Problem Summary: planner: handle panic when loading bindings at startup
planner: handle panic when loading bindings at startup
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: handle panic when loading bindings at startup

---

pkg/ddl/ingest/backend.go
pkg/lightning/backend/backend.go
pkg/lightning/backend/local/engine_test.go
pkg/lightning/backend/local/local.go
pkg/lightning/backend/local/local_test.go
pkg/lightning/backend/local/region_job.go
tests/realtikvtest/addindextest2/BUILD.bazel
tests/realtikvtest/addindextest2/global_sort_test.go
tests/realtikvtest/addindextest3/ingest_test.go

Issue Number: close #57980
Previously, after reset engine we set the TS to `EngineConfig`. But `engineMeta` is the place that really take effect. The conversion from `EngineConfig` to `engineMeta` happens when 1) engine is opened, or 2) external engine is closed normally. In disk-quota triggered import, above conversion does not happen
Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning, ddl: set TS to engineMeta after ResetEngineSkipAllocTS 

---

pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/handletest/handle_test.go

Issue Number: close #58020
Wrong stats version is set for *statistics.Table when we're under lite init.
It was introduced by https://github.com/pingcap/tidb/pull/57943
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: lite init used wrong value to build table stats ver

---

pkg/statistics/handle/handletest/BUILD.bazel
pkg/statistics/handle/handletest/handle_test.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/util/BUILD.bazel
pkg/statistics/handle/util/util.go

Issue Number: ref #57901 
if query meets the problem, it will return null error, then it lead to delete stats. it is a bug. so we can first fix this problem first.
Tests 
> 
Side effects
Documentation
```release-note
right deal with error for reading stats from storage to avoid deleting stats
正确处理取统计信息的异常，来防止 stats 被误删除
```

statistics: right deal with error for reading stats from storage 

---

pkg/distsql/distsql_test.go
pkg/executor/batch_point_get.go
pkg/executor/internal/exec/indexusage.go
pkg/executor/internal/exec/indexusage_test.go
pkg/executor/point_get.go
pkg/util/execdetails/execdetails.go

Problem Summary: Optimize executor runtime stats by avoid unnecessary clone.
- Optimize executor runtime stats by avoid unnecessary clone.
- Tiny optimize index usage reporter for point_get.
version | workload | thread | QPS | QPS Increase
-- | -- | -- | -- | --
master | oltp_point_select | 10 | 17156 |  
This PR | oltp_point_select | 10 | 17365 | 1.2 %
master | oltp_point_select | 100 | 85664 |  
This PR | oltp_point_select | 100 | 86774 | 1.2%
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: optimize executor runtime stats by avoid unnecessary clone

---

pkg/disttask/framework/integrationtests/BUILD.bazel
pkg/disttask/framework/integrationtests/framework_test.go
pkg/disttask/framework/mock/execute/execute_mock.go
pkg/disttask/framework/mock/task_executor_mock.go
pkg/disttask/framework/proto/step.go
pkg/disttask/framework/proto/type.go
pkg/disttask/framework/storage/table_test.go
pkg/disttask/framework/storage/task_table.go
pkg/disttask/framework/taskexecutor/BUILD.bazel
pkg/disttask/framework/taskexecutor/execute/interface.go
pkg/disttask/framework/taskexecutor/interface.go
pkg/disttask/framework/taskexecutor/manager_test.go
pkg/disttask/framework/taskexecutor/task_executor.go
pkg/disttask/framework/taskexecutor/task_executor_test.go
pkg/disttask/framework/testutil/BUILD.bazel
pkg/disttask/framework/testutil/disttest_util.go
pkg/disttask/framework/testutil/executor_util.go

- when detecting whether params are modified, we need to make sure new subtask started after we finished `modify` can use the latest param, especially task concurrency which need to alloc slots from slot manager, and it might require recreating the task executor, if we want avoid create/init step executor when we need recreate the task executor, we have to handle param modify detection on both loop, so we merge them to avoid handle them twice.
- remove `HasSubtasksInStates` which is not needed now, add `GetStep` to step executor
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-styl …

dxf: merge loops in Run and RunStep of task executor

---

pkg/ddl/attributes_sql_test.go
pkg/ddl/main_test.go
pkg/ddl/tests/serial/main_test.go
pkg/domain/db_test.go
pkg/domain/domain.go
pkg/domain/infosync/info.go
pkg/domain/infosync/info_test.go
pkg/infoschema/cache.go
pkg/infoschema/infoschema_v2.go
pkg/infoschema/test/infoschemav2test/BUILD.bazel
pkg/infoschema/test/infoschemav2test/v2_test.go
pkg/server/stat_test.go

Issue Number: close #57952
Currently, when we get a infoschema v2 instance, it's lifetime is in range [ts, ts + 10min)
If the caller hold a infoschema, and use it some time later, it might get error "GC lifetime is shorter than transaction duration" error. That's because infoschema v2 internally use meta package API, while the meta API does not block the GC safepoint advancing.
In this commit, I add a `keepAlive()`  call to the infoschema API,
that `keepAlive()` function will keep the minimal start ts of active infoschema API calls.
The infosync.Syncer call `ReportMinStartTS()` periodically, amd now it will take the active infoschema ts into consideration, which is updated by the `keepAlive()` function.
Tests 
> 
Side …

domain,infoschema: make infoschema activity block GC safepoint advancing

---

pkg/planner/core/casetest/vectorsearch/testdata/ann_index_suite_out.json
pkg/planner/core/casetest/vectorsearch/vector_index_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/57871
Split from https://github.com/pingcap/tidb/pull/57872
We need to handle the DDL events here to ensure that the stats are loaded into memory. Otherwise, the stats cache entry will be deleted due to this issue: https://github.com/pingcap/tidb/issues/57901.
Moreover, there are no indexes or predicate columns on this table, so analyzing this table doesn't provide any help.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: correct the vector index tests

---

br/pkg/lightning/errormanager/errormanager.go
br/pkg/lightning/errormanager/errormanager_test.go

Issue Number: close #58085
Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning: fix data error summary table format

---

br/pkg/checkpoint/checkpoint_test.go
br/pkg/checkpoint/restore.go
br/pkg/restore/log_client/client.go
br/pkg/restore/restorer.go
br/pkg/restore/snap_client/BUILD.bazel
br/pkg/restore/snap_client/import.go
br/pkg/restore/snap_client/import_test.go
br/tests/br_pitr/run.sh

Issue Number:  ref https://github.com/pingcap/tidb/issues/56522
1. the initial config concurrencyPerStore of snapclient is not right. which make the compacted restore blocked. This PR try to fix it.
2. the initial checkpoint for compacted restore is not complete. this PR fix it.
set the correct config. and add a config check when initialize 
Tests 
> 
Side effects
Documentation
```release-note
None
```

compacted restore: fix the wrong initial configrations

---

pkg/statistics/handle/storage/read.go

Issue Number: close #58074 
close https://github.com/pingcap/tidb/issues/57958
I find this data race. we forget to copy stats when to update it.
```
==================
WARNING: DATA RACE
Write at 0x00c0114072c0 by goroutine 830:
runtime.mapassign_fast64()
/usr/local/go/src/runtime/map_fast64.go:113 +0x0
github.com/pingcap/tidb/pkg/statistics.(*HistColl).SetCol()
/tidb/pkg/statistics/table.go:294 +0x372
github.com/pingcap/tidb/pkg/statistics/handle/storage.loadNeededColumnHistograms()
/tidb/pkg/statistics/handle/storage/read.go:663 +0x32d
github.com/pingcap/tidb/pkg/statistics/handle/storage.LoadNeededHistograms()
/tidb/pkg/statistics/handle/storage/read.go:598 +0x15d
github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).LoadNeededHistograms.func1() …
```

statistics: copy stats when to update it for avoiding data race

---

pkg/domain/domain.go

Issue Number: close #58079
See the code comments
Tests 
```
git diff pkg/sessionctx/variable/session.go
diff --git a/pkg/sessionctx/variable/session.go b/pkg/sessionctx/variable/session.go
index 0551e77718..67bc82199e 100644
--- a/pkg/sessionctx/variable/session.go
+++ b/pkg/sessionctx/variable/session.go
@@ -732,10 +732,16 @@ func (s *UserVars) Clone() UserVarsReader {
return cloned
}
+var LALALA bool
+
// SetUserVarVal set user defined variables' value
func (s *UserVars) SetUserVarVal(name string, dt types.Datum) {
s.lock.Lock()
defer s.lock.Unlock()
+       if name == "lalala" {
+               fmt.Println("set lalala = true ===========")
+               LALALA = true
+       }
s.values[name] = dt
}
@@ -746,6 +752,10 @@ func (s *UserVars) UnsetUserVar(varName string) { …
```

domain: reduce the chance of "Information schema is out of date" error

---

pkg/statistics/handle/ddl/drop_partition.go
pkg/statistics/handle/ddl/exchange_partition.go
pkg/statistics/handle/ddl/subscriber.go
pkg/statistics/handle/ddl/truncate_partition.go

Issue Number: ref https://github.com/pingcap/tidb/issues/57871
Split from https://github.com/pingcap/tidb/pull/57872
This PR simply moved the common functions into `subscriber.go` because we will drop these files in upcoming PRs. I am doing this now to reduce the changes needed in the next PR.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: refactor common functions into subscriber

---

pkg/planner/core/casetest/index/index_test.go
pkg/planner/core/casetest/index/testdata/index_range_in.json
pkg/planner/core/casetest/index/testdata/index_range_out.json
pkg/util/ranger/detacher.go

Issue Number: close #57694
This is a limitation for optimal multi-column index range derivation. It is similar to  https://github.com/pingcap/tidb/pull/54166 but different where point ranges are derived from IN list on the prefix column. A simple example is below where the range is based on "t1.a1 IN ( 44, 70, 76)" and not the full predicate  "t1.a1 IN ( 44, 70, 76) AND (t1.a1 > 70 OR (t1.a1 = 70 AND t1.b1 > 41))"
```
CREATE TABLE t1 (
a1 int,
b1 int,
c1 varbinary(767) DEFAULT NULL,
KEY twoColIndex (a1,b1)
)
EXPLAIN  format = brief
SELECT 1
FROM t1 FORCE INDEX (twoColIndex)
WHERE
t1.a1 IN ( 44, 70, 76)
AND (t1.a1 > 70 OR (t1.a1 = 70 AND t1.b1 > 41))
--------------
id      estRows task    access object   operator info
Projection      10.07   root            1->Column#5
└─IndexReader …
```

planner: fix index range intersection for in-list and other predicates 

---

pkg/domain/domain.go
pkg/statistics/handle/cache/internal/inner.go
pkg/statistics/handle/cache/internal/lfu/lfu_cache.go
pkg/statistics/handle/cache/internal/mapcache/map_cache.go
pkg/statistics/handle/cache/statscache.go
pkg/statistics/handle/cache/statscacheinner.go
pkg/statistics/handle/types/interfaces.go

Issue Number: close #58052
Tests 
after it. we can create a cluster with many table. stop the workload and waiting for no update/insert the stats cache. then you change the stats cache capacity. you will see the stats cache and evict more quick.
before:
after:
> 
Side effects
Documentation
```release-note
None
```

statstics: trigger evict by the timer

---

pkg/statistics/handle/syncload/stats_syncload_test.go

Issue Number: close #58162
sync load is running on the background. so we need to create the checkpoint which wait for the sync load's completing working. then we can check the result.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: fix flaky test TestSyncLoadOnObjectWhichCanNotFoundInStorage

---

pkg/metrics/grafana/tidb.json

Issue Number: close #58142  ref #50959 
Before:
After:
Tests 
Import the json to check it works.
> 
Side effects
Documentation
```release-note
None
```

metrics/grafana: display instance for information v2 cache size grafana panel

---

pkg/executor/test/tiflashtest/tiflash_test.go
pkg/store/mockstore/unistore/cophandler/mpp.go
pkg/store/mockstore/unistore/cophandler/mpp_exec.go

Issue Number: close #58188
* disable later materialize in some tiflash tests
* fix some bug in unistore execution framework
Tests 
> 
Side effects
Documentation
```release-note
None
```

tests: disable later materialize in some tiflash tests

---

pkg/executor/infoschema_reader.go
pkg/executor/infoschema_reader_test.go
pkg/planner/core/logical_plan_builder.go

Issue Number: close #58184
use `PlanBuilderOptNoExecution` to skip unnecessary execution. This should be the same behaviour with `SHOW COLUMNS`
Tests 
> 
I tested the new `PlanBuilderOptNoExecution` based on release-6.5 with the reproduce steps in issue. Before this PR (which is v6.5.11)
```
mysql> select count(1) from INFORMATION_SCHEMA.columns;
+----------+
| count(1) |
+----------+
|     4635 |
+----------+
1 row in set (0.66 sec)
mysql> trace select count(1) from INFORMATION_SCHEMA.columns;
+-----------------------------------------------------------------------------+-----------------+-------------+
| operation                                                                   | startTS         | duration    | …
```

executor: skip execution when build query for VIEW in I_S

---

DEPS.bzl
go.mod
go.sum
pkg/disttask/framework/scheduler/BUILD.bazel
pkg/disttask/framework/scheduler/balancer.go
pkg/disttask/framework/scheduler/nodes.go
pkg/disttask/framework/scheduler/scheduler.go
pkg/disttask/framework/scheduler/scheduler_manager.go
pkg/disttask/framework/taskexecutor/BUILD.bazel
pkg/disttask/framework/taskexecutor/manager.go
pkg/disttask/framework/taskexecutor/task_executor.go
pkg/util/logutil/log.go

see https://github.com/pingcap/tidb/issues/56014 too
```
// error verbose is disabled on default, but without stack it's harder to investigate
// some issues, such as in DXF the error mostly happen in business logic, the
// error stack is very deep, we want to log the stack to help us investigate.
// Note: if stack is not that needed to investigate, use normal logger instead.
```
Tests 
apply this patch
```diff
diff --git a/pkg/disttask/framework/taskexecutor/manager.go b/pkg/disttask/framework/taskexecutor/manager.go
index 43179a6ba0..bca8e50fd2 100644
--- a/pkg/disttask/framework/taskexecutor/manager.go
+++ b/pkg/disttask/framework/taskexecutor/manager.go
@@ -84,6 +84,8 @@ func NewManager(ctx context.Context, id string, taskTable TaskTable) …
```

logutil/dxf: add a error verbose logger, and use it in DXF

---

executor/infoschema_reader.go
executor/infoschema_reader_test.go
planner/core/logical_plan_builder.go
tools/check/check-bazel-prepare.sh

Issue Number: close #58184
use `PlanBuilderOptNoExecution` to skip unnecessary execution. This should be the same behaviour with `SHOW COLUMNS`
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: skip execution when build query for VIEW in I_S (#58203)

---

pkg/executor/prepared_test.go
pkg/expression/builtin_other.go

Issue Number: close #58053
As mentioned in https://github.com/pingcap/tidb/issues/58053#issuecomment-2522362546, sometimes we can generate and cache some incorrect execution plans, such as those involving invalid type conversions. These erroneous plans may be pushed down to TiKV, and TiKV side can't handle them properly.
This PR serves as a workaround to mitigate this problem by preventing the generation of potentially wrong plans on the TiDB side.
- For `prepare` statement, the input args are `ConstStrict`, so this PR won't affect `prepare`.
- For `execute` statement whose args are `ConstOnlyInContext`, we try to evaluate it in advance to make sure we can get a correct plan. So the behavior is consistent with the result of directly executing these queries.
﻿
Tests 
> - [ …

expression: prevent building plan for `execute` statement with wrong type

---

br/pkg/task/restore.go
br/tests/br_300_small_tables/run.sh
br/tests/br_check_dup_table/run.sh
br/tests/br_incompatible_tidb_config/run.sh
br/tests/run_group_br_tests.sh

Issue Number: close #58168 
Remove the client check of `tableExistenceCheck`, now it works on both sql and cli client.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: make table existence check unified on different br client

---

br/pkg/streamhelper/BUILD.bazel
br/pkg/streamhelper/advancer.go
br/pkg/streamhelper/advancer_daemon.go
br/pkg/streamhelper/advancer_test.go
br/pkg/streamhelper/basic_lib_for_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/58031
The previous lag calculation relied on c.lastCheckpoint.TS to compute the lag. However, this approach is unreliable, especially when ownership changes, as c.lastCheckpoint.TS is not guaranteed to increase steadily. This PR addresses the issue by introducing a global checkpoint timestamp that maintains a strictly non-decreasing state.
The lag calculation now utilizes a global checkpoint timestamp instead of c.lastCheckpoint.TS. This global timestamp ensures consistency and stability, as it always increases or stays the same, even during ownership transitions. This change guarantees a more robust and accurate lag measurement.
Tests 
> 
Side effects …

log backup: use global checkpoint ts as source of truth

---

pkg/autoid_service/BUILD.bazel
pkg/autoid_service/autoid_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/58210
In the TestAPI, when it is necessary to send an autoid.AutoIDRequest:
1. Non-keyspace scenario: KeyspaceID: uint32(tikv.NullspaceID)
2. Keyspace scenario: Construct the store through keyspaceMeta, and pass keyspaceMeta.Id in the AutoIDRequest. The service side will check whether the keyspace ID in the store is consistent with the one in the request.
Tests 
> 
Side effects
Documentation
```release-note
keyspace: Add UT for the auto ID in the keyspace scenario
```

keyspace: Add UT for the auto ID in the keyspace scenario

---

pkg/executor/slow_query.go
pkg/executor/slow_query_test.go

Issue Number: close #58147 
Handle uncommon empty value string case in slow log, still not sure why empty copr addr appeared.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that queries for slow log may fail when some item's value is empty. 
```

executor: Fix the parse problematic slow log panic issue due to empty value string

---

pkg/infoschema/sieve.go
pkg/infoschema/sieve_test.go

Issue Number: close #58227
Change Mutex to RWMutex
Tests 
If there is not lock contention, 
```
go test -bench BenchmarkSieveGet -run XX -benchmem
goos: linux
goarch: amd64
pkg: github.com/pingcap/tidb/pkg/infoschema
cpu: AMD Ryzen 7 PRO 4750G with Radeon Graphics
BenchmarkSieveGet-16            52371621                21.79 ns/op            0 B/op          0 allocs/op
--- BENCH: BenchmarkSieveGet-16
sieve_test.go:178: 1: hit 1, miss 0, ratio 1.00
sieve_test.go:178: 100: hit 100, miss 0, ratio 1.00
sieve_test.go:178: 10000: hit 353, miss 9647, ratio 0.04
sieve_test.go:178: 1000000: hit 9820, miss 990180, ratio 0.01
sieve_test.go:178: 52371621: hit 474198, miss 51897423, ratio 0.01
PASS
ok      github.com/pingcap/tidb/pkg/infoschema  25.550s
```
With a goroutine calling …

infoschema: change sieve Get() function Mutex to RWMutex

---

pkg/ttl/ttlworker/del.go
pkg/ttl/ttlworker/del_test.go

Issue Number: close #58205
When `globalDelRateLimiter` returns an error, put the waiting rows to `retryRows`
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: retry the rows when del rate limiter returns error in delWorker

---

pkg/planner/cascades/base/BUILD.bazel
pkg/planner/cascades/base/cascadesctx/BUILD.bazel
pkg/planner/cascades/base/cascadesctx/cascades_ctx.go
pkg/planner/cascades/base/task_scheduler_base.go
pkg/planner/cascades/base/task_stack_base.go
pkg/planner/cascades/memo/BUILD.bazel
pkg/planner/cascades/memo/group.go
pkg/planner/cascades/memo/group_expr.go
pkg/planner/cascades/memo/memo.go
pkg/planner/cascades/rule/binder_test.go
pkg/planner/cascades/task/BUILD.bazel
pkg/planner/cascades/task/base.go
pkg/planner/cascades/task/task.go
pkg/planner/cascades/task/task_apply_rule.go
pkg/planner/cascades/task/task_opt_group.go
pkg/planner/cascades/task/task_opt_group_expression.go
pkg/planner/cascades/task/task_scheduler.go
pkg/planner/cascades/task/task_scheduler_test.go
pkg/planner/cascades/task/task_test.go
pkg/planner/core/casetest/cascades/memo_test.go

Tests 
> 
when the scheduler part is on, it will be more easier to test the memo workflow, currently single task couldn't run itself
Side effects
Documentation
```release-note
None
```

planner: add cascade basic interface definition and basic task type.

---

br/pkg/restore/snap_client/systable_restore_test.go
pkg/session/bootstrap.go
pkg/session/bootstrap_test.go
pkg/session/bootstraptest/bootstrap_upgrade_test.go
pkg/statistics/handle/autoanalyze/priorityqueue/dynamic_partitioned_table_analysis_job_test.go
pkg/statistics/handle/autoanalyze/priorityqueue/interval.go

Issue Number: close https://github.com/pingcap/tidb/issues/57996
This PR added two indexes for the `mysql.analyze_jobs` to speed up queries.
I also bumped the bootstrap version from 239 to 140.
Tests 
> 
Side effects
Documentation
```release-note
为 `mysql.analyze_jobs` 添加索引加速查询
Add some indexes to `mysql.analyze_jobs` to speed up queries
```

session: add indexes for `mysql.analyze_jobs`

---

pkg/util/stmtsummary/statement_summary.go
pkg/util/workloadrepo/BUILD.bazel
pkg/util/workloadrepo/worker.go

Issue Number: ref #57147 
Problem Summary: When the workload repository is enabled, we only care about collecting cumulative metrics for SQL statements from the new `tidb_statements_stats` memory table, rather than from the interval-based statement summary tables. Since statement summary records are large, maintaining statement summary history adds unnecessary memory burden while the workload repository is active.
* Add an option to enable/disable statement summary history that the repository worker controls by calling `SetHistoryEnabled()`.
* When statement summary history is disabled, any existing history is cleared.
* When we add statement execution info to a statement summary while history is disabled, pin the history size to 0.
Tests 
```
1. Started tidb-server.
2. Ran `set global …
```

workloadrepo: disable statement summary history when repository is enabled

---

pkg/store/copr/BUILD.bazel
pkg/store/copr/coprocessor.go
pkg/store/copr/coprocessor_test.go
pkg/store/copr/region_cache.go

Issue Number: close #58001
When the coprocessor tasks are batched by store, the busy threshold may redirect them to follower peer of the main task. The main tasks' follower peer can easily be the wrong store for batched tasks and cause unexpected error and retries.
Tests 
> 
Side effects
Documentation
```release-note
None
```

copr: fix the issue that busy threshold may redirect batch copr to followers

---

pkg/util/execdetails/execdetails.go

Problem Summary: `RecordOneCopTask` constructs a new `basicCopRuntimeStats` and merge it, which is inefficient (introduce extra mem allocs).
Let it merge `ExecutorExecutionSummary` directly.
baseline:
this PR:
Tests 
> 
Side effects
Documentation
```release-note
None
```

execdetails: reduce mem allocs on RecordOneCopTask

---

pkg/domain/domain.go

Issue Number: ref https://github.com/pingcap/tidb/issues/58315
want to know the reason why this function will be failed.
Tests 
> 
Side effects
Documentation
```release-note
None
```

domain: change some stats log level as WARN

---

pkg/bindinfo/capture_test.go
pkg/bindinfo/global_handle.go
pkg/bindinfo/global_handle_test.go
pkg/bindinfo/internal/testutil.go
pkg/executor/bind.go
pkg/planner/core/common_plans.go
pkg/planner/core/planbuilder.go

Problem Summary:  planner: remove unnecessary methods in global binding handler
just refactor, no logical change
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: remove unnecessary methods in global binding handler

---

pkg/ddl/backfilling_dist_scheduler.go
pkg/disttask/importinto/BUILD.bazel
pkg/disttask/importinto/planner.go
pkg/disttask/importinto/planner_test.go
pkg/lightning/backend/external/split.go
pkg/lightning/backend/local/local.go
pkg/lightning/common/engine.go

Issue Number: close #58267 
The data flow of region split keys are long. The requirement of later usage is it must contain the region start/end keys, to correctly pause the PD scheduling of given ranges.
Tests 
> 
this test failed in the past
Side effects
Documentation
```release-note
None
```

global sort: add boundaries to split keys when generating plan

---

pkg/ddl/backfilling_dist_scheduler.go
pkg/disttask/importinto/BUILD.bazel
pkg/disttask/importinto/planner.go
pkg/disttask/importinto/planner_test.go
pkg/lightning/backend/external/split.go
pkg/lightning/backend/local/local.go
pkg/lightning/common/engine.go

This is a manual cherry-pick of https://github.com/pingcap/tidb/pull/58323
---
Issue Number: close #58267 
The data flow of region split keys are long. The requirement of later usage is it must contain the region start/end keys, to correctly pause the PD scheduling of given ranges.
Tests 
> 
Side effects
Documentation
```release-note
None
```

global sort: add boundaries to split keys when generating plan (#58323)

---

DEPS.bzl
go.mod
go.sum
pkg/planner/cascades/memo/BUILD.bazel
pkg/planner/cascades/memo/group.go
pkg/planner/cascades/memo/group_and_expr_test.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: introduce hash collision consideration on group expression de-duplication

---

pkg/domain/domain.go

Issue Number: close https://github.com/pingcap/tidb/issues/58303
Now async load and sync stats are put together, so if sync stats takes too long, it will affect async load. Although there should be no async load after sync load is turned on, from current observations, there may be unknown bugs. So in order to avoid affecting the online, it is recommended to take it out separately
Tests 
> 
Side effects
Documentation
```release-note
None
```

domain: move async load stats into single goroutine

---

pkg/executor/builder.go
pkg/executor/traffic.go
pkg/executor/traffic_test.go
pkg/planner/core/planbuilder.go
pkg/planner/core/planbuilder_test.go

Issue Number: close #58319 
Support `show traffic jobs`, which fetches traffic jobs from TiProxy and outputs them.
- `Open()` fetches all traffic jobs
- `Next()` outputs the traffic jobs
The privileges will be checked in another PR.
Tests 
> 
```sql
mysql> traffic capture to "/tmp/traffic" duration="1m";
Query OK, 0 rows affected (0.01 sec)
mysql> traffic replay from "/tmp/traffic" user="root";
Query OK, 0 rows affected (1.60 sec)
mysql> show traffic jobs;
+----------------------------+----------------------------+----------------+---------+----------+--------+-------------+
| START_TIME                 | END_TIME                   | INSTANCE       | TYPE    | PROGRESS | STATUS | FAIL_REASON | …
```

planner, executor: support `show traffic jobs`

---

pkg/planner/core/indexmerge_path.go
pkg/planner/core/indexmerge_unfinished_path.go

Issue Number: ref #58361
- The argument of the two slice parameter of `generateNormalIndexPartialPath()` always has 1 length, so I directly changed the parameter type.
- Try to make it more clear and easier to understand by renaming some variable/function names and cleaning up some comments.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: improve comments and clean up function for OR type IndexMerge logic

---

pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/handletest/initstats/BUILD.bazel
pkg/statistics/handle/handletest/initstats/load_stats_test.go

Issue Number: close #58378
a table is dropped. but it's stats will still be in the system table. but when to init stats, we should skip this non-exicted table to avoid the nill point from the ```tableByID```. it will happen to panic.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: skip non-exicted table when to init stats

---

br/pkg/backup/BUILD.bazel
br/pkg/backup/client.go
br/pkg/backup/client_test.go

Issue Number: close #58340
We gave up too early when there is a `StoreErr` returns because the `errors` package cannot properly get the inner error and soonly give up retry then.
Make the `StoreErr` can be rightly unwraped by `pingcap/errors`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br/backup: make the error rightly checked

---

pkg/planner/cardinality/ndv.go

Issue Number: close https://github.com/pingcap/tidb/issues/58366
Recently, I found that the map iter time here has become significantly longer. 
Compared with the older code, you will find that the current code will traverse the column statistics after traversing the index, which makes the time here longer.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: quickly get total count from index/column

---

pkg/sessionctx/variable/noop.go

Issue Number: close #9155 
Tests 
> 
Side effects
Documentation
```release-note
The `date_format`, `datetime_format` and `max_tmp_tables` variables have been removed.
```

sessionctx: Remove date_format, datetime_format,max_tmp_tables variables

---

pkg/planner/core/casetest/partition/partition_pruner_test.go
pkg/planner/core/casetest/partition/testdata/partition_pruner_in.json
pkg/planner/core/casetest/partition/testdata/partition_pruner_out.json
pkg/planner/core/rule_partition_processor.go

Issue Number: close #58374
Problem Summary: Let codes in `getUsedHashPartitions` same as `getUsedKeyPartitions`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix hash partition prune with `is null` condition

---

pkg/ddl/ddl.go

Issue Number: close https://github.com/pingcap/tidb/issues/58344 close https://github.com/pingcap/tidb/issues/58421
Enhance the asyncNotifyEvent function to include a backoff mechanism when sending events to the channel during unit tests. This prevents indefinite blocking on a full channel by attempting to send the event multiple times before giving up, while also logging a warning if the notification fails.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: implement backoff strategy for async event notification in tests

---

pkg/planner/core/casetest/instanceplancache/BUILD.bazel
pkg/planner/core/casetest/instanceplancache/concurrency_test.go
pkg/planner/core/casetest/instanceplancache/others_test.go
pkg/planner/core/plan_clone_utils.go

Issue Number: close #58395
Problem Summary: planner: fix "invalid memory address or nil pointer dereference" when using Instance Plan Cache in some cases
planner: fix "invalid memory address or nil pointer dereference" when using Instance Plan Cache in some cases
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix "invalid memory address or nil pointer dereference" when using Instance Plan Cache in some cases

---

lightning/tests/lightning_error_summary/run.sh
pkg/lightning/log/log.go

Issue Number: close https://github.com/pingcap/tidb/issues/58337
Tests 
> 
```release-note
None
```

lightning: enable pd grpc client log

---

pkg/bindinfo/binding_cache.go
pkg/bindinfo/binding_cache_test.go

Problem Summary: planner: refactor some code of cross-db binding
planner: refactor some code of cross-db binding
NO logical change, just refactor.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: refactor some code of cross-db binding

---

pkg/util/replayer/replayer.go

Issue Number: close #55513
@Tema 
Tests 
> 
Verified in a test cluster that the PLAN REPLAYER worked:
```
use test;
mysql> create table replayer_test(a int, b int);
mysql> insert into replayer_test values(1,1), (2, 2), (3, 3);
mysql> analyze table replayer_test;
mysql> plan replayer dump explain select * from replayer_test;
+-----------------------------------------------------------+
| File_token                                                |
+-----------------------------------------------------------+
| replayer_3kAIFhAJ2gJPs9qLL__K4Q==_1734048775715226847.zip |
+-----------------------------------------------------------+
1 row in set (0.17 sec)
```
Side effects
Documentation
Please refer to [Release Notes …

util: Change the output dir of the PLAN REPLAYER to be temp_dir

---

pkg/meta/model/BUILD.bazel
pkg/meta/model/table.go
pkg/ttl/ttlworker/config.go
pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go
pkg/ttl/ttlworker/job_manager_test.go
pkg/ttl/ttlworker/session_integration_test.go
pkg/ttl/ttlworker/task_manager.go

Issue Number: close #58411
1. Add two tests related to TTL. One of them is the test with randomly faulty session, which cannot execute the SQL.
2. Fix the bug that the result of `getSession` is unexpected in some situation.
3. Fix the bug that the `last_job_finish_time` is not in correct TZ when the job is cancelled.
Tests 
> 
```release-note
None
```

ttl: add integration test with random fault session for TTL

---

pkg/statistics/handle/bootstrap.go

Signed-off-by: Rustin170506 <techregister@pm.me>
Issue Number: ref https://github.com/pingcap/tidb/issues/57804
In this PR, I removed the dead code. The stats loading for the PK, as shown, has never been executed, so it is safe to remove.
Some background:
1. https://github.com/pingcap/tidb/pull/37552 This PR tried to load it correctly.
2. https://github.com/pingcap/tidb/pull/53298 This PR decided to remove it at all.
3. Another fix based on the previous PR: https://github.com/pingcap/tidb/pull/53399
4. Another full rewrite: https://github.com/pingcap/tidb/pull/57803
So we just forgot to delete it.
Tests 
> 
Side effects
Documentation …

statistics: remove dead code

---

pkg/meta/model/job.go
pkg/metrics/grafana/overview.json
pkg/metrics/grafana/performance_overview.json
pkg/metrics/grafana/tidb.json
pkg/metrics/grafana/tidb_resource_control.json
pkg/metrics/grafana/tidb_resource_control.jsonnet
pkg/metrics/grafana/tidb_runtime.json
pkg/metrics/grafana/tidb_summary.json
pkg/metrics/grafana/tidb_summary.jsonnet
tools/dashboard-linter/main.go

Issue Number: close #58435
see issue
Tests 
> 
Side effects
Documentation
```release-note
None
```

metric: add more lint rules for metric panels

---

pkg/bindinfo/binding_cache.go
pkg/bindinfo/binding_cache_test.go
pkg/bindinfo/global_handle.go
pkg/bindinfo/session_handle.go

Problem Summary: planner: refactor code of Global Binding
Merge CrossDBBindingCache into BindingCache to simplify the code, no logical change, only refactor.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: refactor code of Global Binding

---

pkg/executor/aggregate/agg_hash_executor.go
pkg/executor/aggregate/agg_hash_partial_worker.go
pkg/executor/aggregate/agg_spill_test.go

Issue Number: close #58004
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix goroutine leak when exceed quota in hash agg

---

pkg/planner/cascades/memo/BUILD.bazel
pkg/planner/cascades/memo/group.go
pkg/planner/cascades/memo/group_and_expr_test.go
pkg/planner/cascades/memo/group_expr.go
pkg/planner/cascades/memo/memo.go
pkg/planner/cascades/memo/memo_test.go
pkg/planner/core/optimizer.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add parent GE refs of group and prepare the global GE map for detecting group merge case.

---

pkg/executor/BUILD.bazel
pkg/executor/infoschema_reader.go
pkg/executor/infoschema_reader_test.go
pkg/executor/internal/exec/indexusage.go
pkg/planner/core/memtable_infoschema_extractor.go
tests/integrationtest/r/infoschema/infoschema.result

Issue Number: close #58256
If the table only has an integer primary key, add a fake index entry to the index usage extractor to get it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix the issue that the int primary key doesn't show in the index usage

---

pkg/ddl/backfilling.go
pkg/ddl/backfilling_operators.go
pkg/ddl/backfilling_read_index.go
pkg/ddl/backfilling_scheduler.go
pkg/ddl/column.go
pkg/ddl/index.go
pkg/ddl/modify_column.go
pkg/ddl/partition.go
pkg/ddl/reorg.go
pkg/metrics/ddl.go

Issue Number: close #58114
For BackfillProgressGauge and BackfillTotalCounter, tidb only shows the database name and table name in the metrics. If we add multiple indexes on a single table, it would be difficult to know the rate and progress of each index.
* Add column names and index names for metrics.
Tests 
> 
Test script:
```bash
mysql -h 127.0.0.1 -P4000 -uroot -e'create database test1; create database test2;'
sysbench oltp_read_write prepare --db-driver=mysql --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-db=test1 --threads=16 --tables=2 --table-size=1000000
sysbench oltp_read_write prepare --db-driver=mysql --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-db=test2 …
```

metrics: add col/idx name(s) for BackfillProgressGauge and BackfillTotalCounter

---

pkg/ttl/ttlworker/del.go
pkg/ttl/ttlworker/del_test.go

Issue Number: close #58484
Copied from PR, the below comments describe how this bug happens.
```
//  1. The `tidb_ttl_delete_rate_limit` set to some non-zero value such as 128.
//  2. Some delWorker delete rows concurrency and try to wait for the inner `rate.Limiter`.
//  3. Before internal `l.limiter.Wait` is called, the `tidb_ttl_delete_rate_limit` is set to 0.
//     It resets the internal `rate.Limiter` (in the bug codes, its rate is set to 0).
//  4. The delWorkers in step 2 continue to call l.limiter.Wait.
//     In the bug codes, some of them are blocked forever because the rate is set to 0.
```
Set the inner limiter rate to `rate.Inf` when `tidb_ttl_delete_rate_limit` is set to 0
Tests 
> 
Side effects …

ttl: fix the infinite waiting for delRateLimiter when `tidb_ttl_delete_rate_limit` changes

---

pkg/executor/slow_query.go
pkg/executor/slow_query_sql_test.go

Issue Number: close #58452 
fix time zone issue when querying slow log
Tests 
> 
Side effects
Documentation
```release-note
fix time zone issue when querying slow log
```

executor: fix time zone issue when querying slow log

---

br/tests/br_file_corruption/run.sh
br/tests/run_br

Issue Number: close #57472
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: enable checksum in test

---

pkg/bindinfo/binding.go
pkg/bindinfo/binding_cache.go
pkg/bindinfo/binding_cache_test.go
pkg/bindinfo/binding_match.go
pkg/bindinfo/global_handle.go
pkg/bindinfo/session_handle.go
pkg/domain/plan_replayer.go
pkg/domain/plan_replayer_dump.go
pkg/executor/adapter.go
pkg/executor/show.go
pkg/planner/optimize.go
pkg/server/BUILD.bazel
pkg/server/server_test.go

Problem Summary: planner: refactor some code of binding cache
planner: refactor some code of binding cache
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: refactor some code of binding cache 

---

pkg/domain/domain.go
pkg/executor/ddl.go

Issue Number: ref #58418
The ctx passed to owner manager is background context, and the owner manager does not respond to domain cancel.
Another thing is that when tikv is gone, `TableByName` returns error, but `getLocalTemporaryTable` ignores the error.
The returned is nil, some code get nil pointer runtime panic.
Tests 
When tikv OOM, and Ctrl+C can't make tidb exit 
dlv attach the tidb process to check where it's blocking ...
After this fix, there are still some other places, fixing all the problems once seems too difficult.
> 
Side effects
Documentation …

domain,executor: handle some cases tidb cannot exit

---

pkg/ddl/BUILD.bazel
pkg/ddl/cancel_test.go
pkg/ddl/executor_test.go
pkg/ddl/job_scheduler.go
pkg/ddl/job_worker.go
pkg/ddl/mock/BUILD.bazel
pkg/ddl/mock/systable_manager_mock.go
pkg/ddl/systable/manager.go
pkg/meta/model/job.go
pkg/session/bootstraptest/bootstrap_upgrade_test.go

Issue Number: close #52747
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: fix job state overridden when concurrent updates don't overlap in time range

---

br/pkg/task/restore.go

Issue Number: ref #54316
precheck disk space does not distinguish checkpoint recorded data.
skip prechecking disk space when br is not first run.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: precheck disk space only when checkpoint first run

---

pkg/ddl/schemaver/syncer.go

Issue Number: close #58480
Tests 
`tiup playground`; add sleep(5 seconds) on domain reload, and then start a tidb with this PR. run `create table`
before
```
[2024/12/24 18:28:04.889 +08:00] [INFO] [syncer.go:403] ["syncer check all versions, all nodes are not synced"] [category=ddl] ["ddl job id"=111] [ver=55]
[2024/12/24 18:28:05.891 +08:00] [INFO] [syncer.go:403] ["syncer check all versions, all nodes are not synced"] [category=ddl] ["ddl job id"=111] [ver=55]
```
after
```
[2024/12/24 18:45:50.058 +08:00] [INFO] [syncer.go:398] ["syncer check all versions, someone is not synced"] [category=ddl] [info="instance ip 192.168.206.89, port 5000, id 8d02f9b2-bfe1-4292-a1ef-5c1ef86eebf8"] ["ddl job id"=117] [ver=58]
```
> …

ddl: fix version syncer doesn't print who hasn't synced on partial sync

---

pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go
pkg/ttl/ttlworker/job_manager_test.go

Issue Number: close #58510
The job history is not updated after removing the table status. Therefore, the timer adapter will still believe there is a job running for it.
Update the status to `cancelled` after removing the table status.
Tests 
> 
```release-note
None
```

ttl: set the job history status to `cancelled` if it's removed in GC and it's still running

---

br/cmd/br/backup.go
br/cmd/br/cmd.go
br/cmd/br/main.go
br/cmd/br/restore.go
br/pkg/backup/schema.go
br/pkg/metautil/metafile.go
br/pkg/restore/client.go
br/pkg/task/backup.go
br/pkg/task/common.go
br/pkg/task/common_test.go
br/pkg/task/restore.go
br/pkg/task/restore_raw.go
br/pkg/task/restore_txn.go
br/tests/br_full_ddl/run.sh
br/tests/br_full_index/run.sh
pkg/executor/brie.go

close pingcap/tidb#56373
(cherry picked from commit 4f047be191be48d151c025703fc1c83ed015e453)
Tests 
> 
Side effects
Documentation
```release-note
The default behavior of doing checksum during full backup has changed from enabled to disabled. 
The meaning of checksum flag is kind of ambiguous here, it doesn't mean we don't do the checksum of files when doing backup, instead we don't do checksum to compare from coprocessor side to the br side to improve the performance
```

cherry-pick-8.1: br: restore checksum shouldn't rely on backup checksum (#56712)

---

cmd/tidb-server/main.go
pkg/domain/domain.go
pkg/util/signal/signal_posix.go
pkg/util/wait_group_wrapper.go

Issue Number: close #58418
Continue to fix some place to make Ctrl+C work as expected and improve the user experience.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: improve the user experience for using Ctrl+C to make tidb exit

---

pkg/util/stmtsummary/BUILD.bazel
pkg/util/stmtsummary/evicted.go
pkg/util/stmtsummary/evicted_test.go
pkg/util/stmtsummary/statement_summary.go
pkg/util/stmtsummary/statement_summary_test.go
pkg/util/stmtsummary/v2/BUILD.bazel
pkg/util/stmtsummary/v2/stmtsummary.go

Problem Summary: Optimize statements summary by using buffer pool
Before:
This PR:
version | workload | thread | QPS | 
-- | -- | -- | -- 
master | oltp_point_select | 100 | 83498 |  
This PR | oltp_point_select | 100 | 83800 | 
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: Optimize statements summary by using buffer pool

---

pkg/planner/core/casetest/partition/BUILD.bazel
pkg/planner/core/casetest/partition/integration_partition_test.go
pkg/planner/core/integration_test.go
pkg/planner/core/physical_plans.go

Issue Number: close #58475, close https://github.com/pingcap/tidb/issues/56013
As title. Previously we only move column with id `ExtraHandleID` to the end, but we forgot some other extra columns.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner/core: move all extra columns to the end in ExpandVirtualColumn

---

pkg/ddl/index.go
pkg/ddl/job_worker.go
tests/realtikvtest/addindextest1/BUILD.bazel
tests/realtikvtest/addindextest1/disttask_test.go

Issue Number: close #58573
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: fix addindex wrong rowcount on dxf when the job txn failed

---

pkg/executor/BUILD.bazel
pkg/executor/builder.go
pkg/executor/join/hash_join_v2.go
pkg/executor/join/joinversion/join_version.go
pkg/planner/core/BUILD.bazel
pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
pkg/planner/core/casetest/join/join_test.go
pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/physical_plans.go

Issue Number: close #58325
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: support hash v2 variable to control the join order

---

pkg/executor/select.go
pkg/sessionctx/stmtctx/stmtctx.go
pkg/sessionctx/variable/session.go
tests/integrationtest/r/session/session.result
tests/integrationtest/t/session/session.test

Issue Number: close #58201
Tests 
> 
Side effects
Documentation
```release-note
Handling of `last_insert_id(0)` was changed to be compatible with MySQL
```

executor,sessionctx: handle last_insert_id(0) like MySQL

---

pkg/infoschema/cache.go
pkg/infoschema/test/infoschemav2test/v2_test.go

Issue Number: close #58453
If infoschema cache v2 is not enabled, the TS is never updated:
https://github.com/pingcap/tidb/blob/b11cce72848142c279842061285ed457846340c0/pkg/domain/domain.go#L322-L329
As a result, `infocache.GetAndResetRecentInfoSchemaTS` is always MaxInt64 and we cannot get the changed TS.
Enable infoschema cache v2.
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: stabilize TestGetAndResetRecentInfoSchemaTS

---

br/pkg/rtree/rtree.go

Issue Number: close https://github.com/pingcap/tidb/issues/58587
When performing a full backup on millions of tables, the default incomplete range buffer grows significantly due to the large number of ranges. Since most ranges are complete, a lower buffer value should be used to optimize memory usage.
Set default incomplete to a lower value.
Tests 
Manually Backup millions of tables
Before this PR, the inuse memory consume 4GB with GetIncompleteRanges
After the memory usage reduced.
> 
Side effects
Documentation
```release-note
None
```

Backup: remove improper memory usage during full backup

---

pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/optimizer.go
tests/integrationtest/r/cte.result
tests/integrationtest/r/naaj.result
tests/integrationtest/r/planner/core/casetest/integration.result
tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result
tests/integrationtest/r/tpch.result

Issue Number: close #58325
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: use right hint to build join order | tidb-test=pr/2463

---

pkg/lightning/backend/local/region_job.go

Issue Number: close #58449
Timestamp assertion was flaky due to minor clock drift between TiDB and PD.
Expanded the range to tolerate minor differences, allowing timestamps up to 1 hour in the future and 24 hours in the past.
Tests 
> 
I’d greatly appreciate it if you could suggest a good place to add tests, if needed!
Side effects
Documentation
```release-note
Fix flaky assert by adjusting the TS range
```

lightning: adjust TS assertion range between TiDB and PD

---

pkg/statistics/handle/ddl/BUILD.bazel
pkg/statistics/handle/ddl/ddl.go
pkg/statistics/handle/ddl/ddl_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/58545
In this PR, I just temporarily ignore this error and make sure the ddl notfier can proceed. I will spend more time figuring out how to avoid this kind of bug altogether.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: temporarily skip handling errors for DDL events

---

pkg/distsql/context/BUILD.bazel
pkg/distsql/context/context.go
pkg/distsql/context/context_test.go
pkg/kv/kv.go
pkg/store/copr/BUILD.bazel
pkg/store/copr/coprocessor.go

Try to reuse [lite-cop-worker](https://github.com/pingcap/tidb/pull/57522).
Before this PR
This PR, the `tableWorker` of `IndexLookUpExecutor` can use lite-cop-worker to reduce consumption.
version | workload | thread | QPS | QPS Increase
-- | -- | -- | -- | --
master | oltp_index_lookup | 100 | 26522 |  
This PR | oltp_index_lookup | 100 | 27158 | 2.4%
master | oltp_index_lookup | 150 | 26985 |  
This PR | oltp_index_lookup | 150 | 28290 | 4.8%
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: tiny optimize index-lookup query performance by reuse lite-cop-worker.

---

pkg/lightning/mydump/csv_parser.go
pkg/lightning/mydump/csv_parser_test.go
pkg/lightning/mydump/parser.go

Issue Number: close #58590
Tests 
import a file with 20 fields, each field is about 10+M, total row size is about 266M
```mysql
mysql> import into t from '/playground/lightning/single-file/long-row.csv';
ERROR 1105 (HY000): size of row cannot exceed the max value of txn-entry-size-limit
mysql>
```
> 
Side effects
Documentation
```release-note
None
```

importinto/lightning: check max row size when parsing csv to avoid OOM

---

br/pkg/streamhelper/advancer.go
br/pkg/streamhelper/advancer_test.go
br/pkg/streamhelper/config/advancer_conf.go
br/pkg/streamhelper/daemon/owner_daemon.go
br/pkg/streamhelper/daemon/owner_daemon_test.go
br/pkg/task/stream.go
pkg/config/BUILD.bazel
pkg/config/config.go
pkg/domain/domain.go

Issue Number: close #50458
Add a cycle to force to be owner and retire when using `log advancer` cmd. In the test we can start this debugging command and it will do this cycle repeatedly until exits. It creates a chaos scenario for advancer testing. 
Also all the parameters in the advancer are exposed to the cmd already which is convenient. The advancer daemon running on TiDB domain will not be affected by any of these configs since they use default and cannot be configured.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: add chaos testing for advancer owner

---

pkg/planner/cascades/memo/memo.go
pkg/planner/core/casetest/cascades/memo_test.go
pkg/planner/core/casetest/cascades/testdata/cascades_suite_out.json
pkg/planner/core/collect_column_stats_usage.go
pkg/planner/core/collect_column_stats_usage_test.go
pkg/planner/core/rule_collect_plan_stats.go
pkg/sessionctx/stmtctx/stmtctx.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: leverage stats collection rule to get operator num

---

lightning/cmd/tidb-lightning-ctl/main.go
lightning/tests/lightning_local_backend/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/57402
Problem Summary: `checkpointDump()` use incorrect file name.
`checkpointDump()` use correct file name.
Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning: fix lightning-ctl dump checkpoint file name

---

pkg/executor/BUILD.bazel
pkg/executor/builder.go
pkg/executor/workloadrepo.go
pkg/parser/ast/misc.go
pkg/parser/parser.y
pkg/parser/parser_test.go
pkg/planner/core/common_plans.go
pkg/planner/core/planbuilder.go
pkg/util/workloadrepo/BUILD.bazel
pkg/util/workloadrepo/const.go
pkg/util/workloadrepo/sampling.go
pkg/util/workloadrepo/snapshot.go
pkg/util/workloadrepo/table.go
pkg/util/workloadrepo/worker.go
pkg/util/workloadrepo/worker_test.go

Issue Number: close #58248
Problem Summary: as title, a new syntax to trigger snapshot manually.
1. Minimal changes to parser/planner/executor
2. Due to cyclic imports, I must export some "internal" interfaces in workloadrepo
Tests 
> 
Side effects
Documentation
```release-note
None
```

workloadrepo: add admin create workload snapshot stmt

---

pkg/executor/cte.go
pkg/executor/index_merge_reader.go
pkg/executor/internal/mpp/executor_with_retry.go
pkg/executor/traffic.go
pkg/resourcemanager/pool/workerpool/workpool_test.go
pkg/store/copr/batch_coprocessor.go
pkg/store/copr/batch_coprocessor_test.go
pkg/util/memoryusagealarm/memoryusagealarm.go
pkg/util/tiflashcompute/topo_fetcher.go
tests/globalkilltest/util.go

Issue Number: ref #31716.
Tests 
> 
```release-note
None
```

*: replace any with specific type in log

---

pkg/executor/benchmark_test.go
pkg/store/copr/batch_coprocessor.go

Issue Number: ref #31716.
Tests 
```release-note
None
```

copr, executor: remove some unused function parameters

---

pkg/planner/cardinality/selectivity_test.go
pkg/statistics/handle/autoanalyze/autoanalyze_test.go
pkg/statistics/handle/autoanalyze/priorityqueue/analysis_job_factory_test.go
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/cache/internal/testutil/testutil.go
pkg/statistics/handle/storage/json.go
pkg/statistics/handle/storage/read.go
pkg/statistics/statistics_test.go
pkg/statistics/table.go

Just removed an unused field. As you can see, it is always true. So we can remove it safely.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: remove unused HavePhysicalID field from HistColl struct

---

lightning/tests/lightning_character_sets/run.sh
lightning/tests/lightning_no_schema/data/noschema.invalid-schema.sql
lightning/tests/lightning_no_schema/data/noschema.invalid.sql
lightning/tests/lightning_no_schema/run.sh
pkg/lightning/mydump/BUILD.bazel
pkg/lightning/mydump/schema_import.go
pkg/lightning/mydump/schema_import_test.go

Issue Number: ref #58141
info schema V2 only store one copy of schema object in memory, so read/write need to lock, if we read too much and takes too long, it affects write, i.e. schema reloading during DDL execution, we can mitigate this by using finer-grained lock, but we cannot avoid it completely with current strategy. so in lightning, we remove related queries, and avoid create table twice by `IF NOT EXIST`, and check table existence on error by `SHOW CREATE TABLE`, to make schema import part faster
we also found that the query to `information_schema.tables` is getting slower over time, and cause lightning dispatch jobs slower, we can fix it too by replace the query.
Tests 
import 100K DB and total 200K tables, time reduced from 55m27 -> 19m20
before
after
> - [ ] I …

lightning: replace information_schema query when importing table schema with separate show create table

---

pkg/lightning/backend/kv/BUILD.bazel
pkg/lightning/backend/kv/context.go
pkg/lightning/backend/kv/context_test.go
pkg/util/misc.go
tests/realtikvtest/importintotest2/from_select_test.go

Issue Number: close #58613
Tests 
> 
Side effects
Documentation
```release-note
None
```

importinto/lightning: fix negative value cast to upper bound in non strict sql mode

---

pkg/distsql/select_result.go
pkg/distsql/select_result_test.go

Issue Number: close #58703 
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that cop tasks' backoff info is inaccurate in execution summary.
```

distsql: Fix backoff execution info inaccurate issue

---

pkg/domain/domain.go
pkg/executor/grant.go
pkg/executor/simple.go
pkg/executor/utils.go
pkg/executor/utils_test.go
pkg/parser/ast/BUILD.bazel
pkg/parser/ast/misc.go
pkg/parser/ast/misc_test.go
pkg/privilege/privilege.go
pkg/privilege/privileges/cache.go
pkg/privilege/privileges/privileges.go
pkg/privilege/privileges/privileges_test.go
pkg/server/conn.go
pkg/sessionctx/variable/sysvar.go
tests/integrationtest/r/executor/simple.result
tests/integrationtest/t/executor/simple.test

Issue Number: ref #54138
In [`func (n *UserSpec) EncodedPassword()`](https://github.com/pingcap/tidb/blob/e79d22f156ca8305de126297d1a85ff900cba586/pkg/parser/ast/misc.go#L1528), if the [`opt.AuthPlugin`](https://github.com/pingcap/tidb/blob/e79d22f156ca8305de126297d1a85ff900cba586/pkg/parser/ast/misc.go#L1535) is empty, it will always encode the password by the `mysql_native_password` way. However, after introducing `default_authentication_plugin` in https://github.com/pingcap/tidb/pull/56660, here should instead consider the 'default' way.
1. In `encodedPassword`, if the `opt.AuthPlugin` is empty, use the default auth plugin to encode the password. 
2. Remove some unreachable code.
3. Add more tests
Tests 
> 
Side …

*: fix a bug for default_authentication_plugin

---

pkg/lightning/backend/local/duplicate.go

Issue Number: close #58523
gRPC "canceled" error may be caused by network problems, for example the server thinks the client is gone so it cancels the RPC, and then the client receives canceled error, because streaming RPC has 2 connections independently for C->S and S->C. In lightning use case, we only want to break the retry when the user cancels it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

dupdetect: gRPC cancel should trigger retry

---

pkg/disttask/framework/scheduler/balancer.go
pkg/disttask/framework/taskexecutor/task_executor.go
pkg/disttask/framework/taskexecutor/task_executor_test.go
tests/realtikvtest/addindextest1/disttask_test.go

Issue Number: close #58450
Problem Summary: See https://github.com/pingcap/tidb/issues/58450#issuecomment-2565218662
Cancel subtask context if scheduled away.
Tests 
> 
Side effects
Documentation
```release-note
None
```

disttask: cancel subtask context if scheduled away

---

pkg/executor/cluster_table_test.go
pkg/executor/slow_query.go
pkg/executor/slow_query_test.go
pkg/infoschema/test/clustertablestest/cluster_tables_test.go
pkg/planner/core/memtable_predicate_extractor.go

This is an hotfix of #56356
Issue Number: close #56100
Problem Summary: fix issue that query slow_query table return wrong result
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix issue that query slow_query table return wrong result  | tidb-test=345b2782950dafda7b4a938c84bffb7f46834add 

---

pkg/statistics/handle/ddl/subscriber.go
pkg/statistics/handle/storage/update.go
pkg/statistics/handle/usage/session_stats_collect.go

Issue Number: ref https://github.com/pingcap/tidb/issues/57869
If you want to understand how it works, read more at https://github.com/pingcap/tidb/issues/57869#issuecomment-2568720215.
This PR split from https://github.com/pingcap/tidb/pull/58331.
Just updated the `UpdateStatsMeta` can handle multiple detla table updates by taking a slice of DeltaUpdate as an argument.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: refactor stats meta handling to use DeltaUpdate for multi-table support

---

pkg/ddl/executor.go
pkg/ddl/index_modify_test.go
pkg/ddl/ingest/integration_test.go
pkg/ddl/partition.go
tests/integrationtest/r/globalindex/ddl.result
tests/integrationtest/r/globalindex/expression_index.result
tests/integrationtest/r/globalindex/insert.result
tests/integrationtest/r/globalindex/update.result
tests/integrationtest/t/globalindex/ddl.test
tests/integrationtest/t/globalindex/expression_index.test
tests/integrationtest/t/globalindex/insert.test
tests/integrationtest/t/globalindex/update.test

Issue Number: close #58650
Problem Summary: Supports non-unqiue global index. Not found bugs right now, we will add more test cases later.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: supports non-unique global index

---

pkg/planner/util/path.go

Issue Number: close #58784
As the flame graph shows, this runtime.growslice should be avoided.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: prealloc the slices in the SplitCorColAccessCondFromFilters

---

pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
pkg/planner/core/casetest/join/join_test.go
pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
pkg/planner/core/exhaust_physical_plans.go
tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result

Issue Number: close https://github.com/pingcap/tidb/issues/58647
1. Improved warning message for conflicting HASH_JOIN_BUILD and HASH_JOIN_PROBE hints. 
2. Improved warning about unsupported hints for SemiJoin and AntiSemiJoin with hash join versions 1. 
3. Improved warning about unsupported hints for LeftOuterSemiJoin and AntiLeftOuterSemiJoin.
Tests 
> 
Side effects
Documentation
```release-note
改进 HASH_JOIN_BUILD 和 HASH_JOIN_PROBE 不生效的警告消息
Improved warning messages for HASH_JOIN_BUILD and HASH_JOIN_PROBE not taking effect
```

planner: improve warning messages for unsupported HASH_JOIN hints

---

pkg/ttl/ttlworker/job_manager_integration_test.go

Issue Number: close #58745
Modify the test to also scale workers during fault tests.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl, test: scale TTL workers during the fault tests

---

DEPS.bzl
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/55248, close https://github.com/pingcap/tidb/issues/58239
ref https://github.com/tikv/pd/issues/8962
Problem Summary: tso client may initiate failed
retry it, and if it always fails after retry, it will report an error.
Tests 
> 
Side effects
Documentation
```release-note
Fix the problem of importing data or adding indexes may fail when PD encounter network problems.
```

*: upgrade pd client to make sure tso client initiate successfully

---

pkg/util/workloadrepo/BUILD.bazel
pkg/util/workloadrepo/housekeeper.go
pkg/util/workloadrepo/sampling.go
pkg/util/workloadrepo/snapshot.go
pkg/util/workloadrepo/table.go
pkg/util/workloadrepo/utils.go
pkg/util/workloadrepo/worker.go
pkg/util/workloadrepo/worker_test.go

This pull request adds unit testing for the Workload Repository code.  It also fixes a few issues and refactors some code. Specific changes include:
* Create the etcd snap id key the first actual value instead of zero.
* Enable snapshot collection for the TIDB_INDEX_USAGE.
* Add checks for nil to a few places in the partition handling code.
* Partition validation code will only check that partitions cover today and tomorrow.
* It will only generate new partitions if no partition covers the current day and the next day.
* Validate that the value assigned to tidb_workload_repository_dest is either an empty string or 'table.'
* Fix a couple of bugs in the housing keeping process.
* Factor out fillInTableNames(), createPartition() and …

workloadrepo: Add unit testing for the Workload Repository.

---

pkg/ttl/ttlworker/scan.go
pkg/ttl/ttlworker/session.go
pkg/ttl/ttlworker/session_integration_test.go

Issue Number: close #58342
disable paging in TTL
See the metrics above. Left is `@@tidb_enable_paging=1` and right is `@@tidb_enable_paging=0`. The cop operations decreases a little (~7%)
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: disable paging in TTL

---

pkg/statistics/handle/cache/internal/lfu/lfu_cache.go

Issue Number: close https://github.com/pingcap/tidb/issues/58014
stats cache set default quota as 20%
Tests 
> 
Side effects
Documentation
```release-note 
stats cache set default quota as 20%
state cache 的默认阈值为 20%
```

statistics: stats cache set default quota as 20% 

---

pkg/ddl/placement/bundle.go
pkg/ddl/placement/bundle_test.go
pkg/ddl/placement/constraint.go
pkg/ddl/placement/constraint_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/58633
When creating a placement policy through tidb, tidb will create a placement-rule with `"engine" notIn "tiflash"` https://github.com/pingcap/tidb/pull/22065
However, under tiflash disaggregated compute and storage arch, the compute node will register store with label `{"engine": "tiflash_compute"}`.
The logic in PD of choosing store for rule: [pkg/schedule/placement/label_constraint.go @ pd](https://github.com/tikv/pd/blob/7d33065019f78d9150a8c89ddb4593f81e6ff9b3/pkg/schedule/placement/label_constraint.go#L81-L95)
1. If the store's label.key is equal to "engine" (or "exclusive," or starts with '$'), and the rule's constraint does not contain a rule with the same label.key, then do not schedule the peer to …

ddl: Remove explicit exclude for "engine" notIn "tiflash"

---

pkg/util/stmtsummary/reader.go
pkg/util/stmtsummary/statement_summary_test.go

Issue Number: close #58403
`isAuthed` was factored out of `getStmtByDigestElementRow` so it could be shared with `getStmtByDigestCumulativeRow`, but the logic was hardcoded to use the cumulative statement stats, breaking the auth checks for the original interval-based statement summary tables.
* In `isAuthed`, check `ssStats.authUsers` rather than checking `ssbd.cumulative.authUsers`.
* Extend `TestAccessPrivilege` to test the same query digests as before, but run as a different user in a new statement summary interval (which should not be able to access rows generated for the old user).
Tests 
```Reverted the fix and confirmed that the modified TestAccessPrivilege test fails.```
> 
Side effects
Documentation
Please …

stmtsummary: check authUsers using the polymorphic stmtSummaryStats

---

pkg/planner/core/find_best_task.go
pkg/planner/core/task.go
tests/integrationtest/r/infoschema/cluster_tables.result
tests/integrationtest/t/infoschema/cluster_tables.test

Issue Number: close #51723
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: correct plan when scan tidb related cluster table with KeepOrder

---

pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
pkg/planner/core/expression_rewriter.go
pkg/planner/core/integration_test.go
pkg/planner/core/logical_plan_builder.go
pkg/util/hint/hint.go

Issue Number: close #58829
Problem Summary: planner: allow semi_join_rewrite hint to work for in-subquery
planner: allow semi_join_rewrite hint to work for in-subquery
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: allow semi_join_rewrite hint to work for in-subquery

---

pkg/expression/integration_test/integration_test.go
pkg/types/vector.go
pkg/types/vector_test.go

Issue Number: ref #58379
Tests 
> 
Side effects
Documentation
```release-note
None
```

types: throw error when input exceeds the range of float32 in vector

---

pkg/ddl/notifier/BUILD.bazel
pkg/ddl/notifier/subscribe.go
pkg/ddl/notifier/testkit_test.go

Issue Number: close #58824
create another session for DeleteAndCommit
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl notifier: fix shared session by List and DeleteAndCommit

---

pkg/lightning/backend/external/writer.go

Issue Number: close #58826
just a log improvement
Tests 
> 
Side effects
Documentation
```release-note
None
```

globalsort: skip retry when context has error

---

pkg/executor/distsql.go
pkg/executor/utils.go
pkg/executor/utils_test.go

also refine the worker pool
Problem Summary: copystack in index lookup workers consume a lot of cpu resources.
Growing the stack at the beginning of the worker goroutine. Also refine the implementation of the worker pool.
And here are some benchmark results.
| Workload  | Threads | TPS (this PR) | TPS (baseline) | Diff |
| --------- | ------: | ------------: | -------------: | ---: |
| idxlookup |      32 |       2797.99 |        2708.88 | 3.3% |
| idxlookup |      64 |       3292.84 |        3123.35 | 5.4% |
Tests 
> 
Side effects
Documentation …

executor: reduce overhead of copystack in idxlookup workers

---

pkg/statistics/column.go
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/handletest/statstest/stats_test.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/storage/save.go
pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/index.go

This field will never be read. So we can safely remove it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: remove unused LastAnalyzePos field

---

pkg/statistics/handle/handletest/statstest/BUILD.bazel
pkg/statistics/handle/handletest/statstest/stats_test.go
pkg/statistics/handle/storage/update.go
pkg/statistics/handle/usage/BUILD.bazel
pkg/statistics/handle/usage/session_stats_collect.go

Issue Number: close https://github.com/pingcap/tidb/issues/57869
close https://github.com/pingcap/tidb/pull/58331
In this PR I changed `DumpStatsDeltaToKV` to dump the stats in batch instead of one by one. This will significantly improve the performance of the dump process. From my tests, the duration dropped from 40 minutes to 20 seconds under 100m table workload.
See more: https://github.com/pingcap/tidb/issues/57869#issuecomment-2568720215
Tests 
> 
Side effects
Documentation
```release-note
提升 TiDB 在大量表和高负载下 dump stats delta 更新比较慢的问题 …
```

statistics: optimize stats delta dumping with batch processing

---

br/tests/br_pitr/run.sh

Issue Number: ref https://github.com/pingcap/tidb/issues/58430
The previous cherry-pick PR(https://github.com/pingcap/tidb/pull/58527) has merge conflict on `br_pitr` test case. This PR fixed it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

integration test: fix test case "br_pitr"

---

pkg/executor/test/tiflashtest/tiflash_test.go
pkg/expression/integration_test/integration_test.go
pkg/kv/mpp.go
pkg/kv/version_test.go
pkg/planner/core/casetest/cbotest/testdata/analyze_suite_out.json
pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json
pkg/planner/core/casetest/hint/testdata/integration_suite_out.json
pkg/planner/core/casetest/mpp/testdata/integration_suite_out.json
pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
pkg/planner/core/casetest/pushdown/testdata/integration_suite_out.json
pkg/planner/core/casetest/rule/testdata/derive_topn_from_window_out.json
pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json
pkg/planner/core/casetest/testdata/integration_suite_out.json
pkg/planner/core/casetest/vectorsearch/testdata/ann_index_suite_out.json
pkg/planner/core/casetest/windows/testdata/window_push_down_suite_out.json
pkg/planner/core/integration_test.go
pkg/planner/core/testdata/runtime_filter_generator_suite_out.json
pkg/planner/core/tests/redact/redact_test.go
pkg/sessionctx/sessionstates/session_states_test.go
tests/integrationtest/r/executor/set.result
tests/integrationtest/r/planner/core/plan.result
tests/integrationtest/t/executor/set.test

Issue Number: ref #58654
Tests 
- Rolling upgrade tiflash servers and executing queries which exchanging string data.
- In a mixed cluster of old and new tiflash versions, queries can be executed normally.
- Upgrade tidb servers after tiflash servers has been upgraded.
- Check the value of `mpp_version` is changed to `3`, and tiflash servers are using new string data format.
> 
Side effects
Documentation
```release-note
None
```

copr: add MppVersionV3

---

pkg/statistics/handle/cache/statscache.go

Issue Number: close https://github.com/pingcap/tidb/issues/58797
if it failed, tidb cannot collect the timeout for it.
Tests 
> 
Side effects
Documentation
```release-note
collect duration of failed stats cache sync
收集失败的统计信息同步的耗时
```

statistics: collect duration of failed stats cache sync

---

pkg/executor/sortexec/topn.go

Issue Number: ref #58891
The chunk is created by topN's schema when spill happens, so it will miss some rows and throw an error. This pr is consistent with #58500 , using `children(0)` instead.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: modify the spill chunk size of topn

---

DEPS.bzl
br/pkg/restore/log_client/BUILD.bazel
br/pkg/restore/log_client/export_test.go
br/pkg/restore/log_client/migration.go
br/pkg/restore/log_client/migration_test.go
br/pkg/stream/stream_metas.go
br/pkg/stream/stream_metas_test.go
br/pkg/streamhelper/basic_lib_for_test.go
go.mod
go.sum

Issue Number: close #58733
We use `compaction_from|until_ts` as filter, which may mistakenly filter out something we actually needing.
Use `input_min|max_ts` instead.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br/restore/log_client: use input ts as filter

---

pkg/executor/prepared.go
pkg/executor/prepared_test.go

Issue Number: close #58870
When it is text-prepare, SQL will be parsed twice. The first time, it is already transformed to utf8 due to `charset_client`. Thus when it comes to executor, only the other two parameters need to set.
But if it is coming from prepare protocol, SQL have not been parsed before. We also need to set `charset_client` to transform it to utf8.
Tests 
> 
Side effects
Documentation
```release-note
Fix broken prepare protocol when charset_client is not UTF8
```

executor: fix prepared protocol charset

---

pkg/planner/core/operator/logicalop/logical_aggregation.go
pkg/planner/core/rule_join_reorder.go
pkg/planner/core/rule_join_reorder_dp.go

remove the ```//nolint: prealloc``` 
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: remove skip prealloc tag

---

pkg/executor/traffic.go
pkg/executor/traffic_test.go

Issue Number: close #58861 
Support writing traffic files to shared storage so that users don't need to copy files from the production cluster to the testing cluster.
- For capturing, TiDB assigns each TiProxy a sub-directory under the output path, in the form of `tiproxy-0`, `tiproxy-1`, ...
- For replaying, TiDB reads the sub-directories under the input path and assigns them to TiProxy instances.
- TiProxy is unaware of the assignment.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: support capturing to and replaying from shared storage

---

pkg/types/BUILD.bazel
pkg/types/json_binary.go
pkg/types/json_binary_functions.go
pkg/types/json_binary_test.go
pkg/types/json_path_expr.go
pkg/types/json_path_expr_test.go
tests/integrationtest/r/executor/executor.result
tests/integrationtest/r/expression/builtin.result
tests/integrationtest/r/expression/issues.result
tests/integrationtest/r/expression/json.result
tests/integrationtest/t/expression/issues.test
tests/integrationtest/t/expression/json.test

Issue Number: close #58897, close #58896, close #58895, close #58894, close #58888, close #37806
This PR adds a fuzz test for `json_extract` function and fix several bugs found by it.
1. Add a fuzz test for `json_extract`.
2. Modify the behavior of `jsonMarshalStringTo` to specially handle the `\b` and `\f`.
3. Fix the json path parser by using `[]rune` to make sure we have correct unicode behavior.
4. Fix the scientific notation of float value.
Tests 
> 
Side effects
Documentation
```release-note
None
```

json: add json fuzz test for `json_extract` function and fix several bugs found by it | tidb-test=pr/2467

---

pkg/parser/ast/misc.go
pkg/parser/parser.y
pkg/parser/parser_test.go
pkg/planner/core/planbuilder.go
pkg/planner/indexadvisor/options_test.go

Problem Summary: planner: update index advisor commends
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: update index advisor commends

---

pkg/ttl/session/session.go
pkg/ttl/ttlworker/BUILD.bazel
pkg/ttl/ttlworker/scan_integration_test.go
pkg/ttl/ttlworker/scan_test.go

Issue Number: close #58900
Previously, the `RunInTxn` will only rollback the transaction after the `BEGIN` runs successfully. However, if the `BEGIN` is killed after setting the transaction status, it can still leave a valid transaction. We'll need to also `ROLLBACK` it.
The effect is that when we are cancelling a TTL task (scaling the workers, stepping out of the TTL window, stopping the TTL function...), a session with valid transaction may pollute the session pool.
Move the `defer ... ROLLBACK` logic to the top of the `RunInTxn` function.
Tests 
> 
```release-note
Fix the issue that canceling a TTL task may return a polluted session to global session pool.
```

ttl: rollback the scan trasnaction even if the `BEGIN` failed.

---

pkg/statistics/handle/storage/read.go

Issue Number: close #58865
when drop index happen during the async load. it will happen the panic.
Tests 
with 1m tables's DDL and DML, this problem will not happen again.
> 
Side effects
Documentation
```release-note
None
```

statistics: fix the panic when to async load stats with dropped index

---

pkg/statistics/handle/usage/session_stats_collect.go

Issue Number: ref https://github.com/pingcap/tidb/issues/57869
1. Remove useless map update. 
2. Make sure we use the right slice to update the delta map and record the historical stats meta.
~~3. I also updated it to use `SELECT FOR UPDATE NOWAIT` to avoid the deadlock in the first place.~~
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: enhance dumpStatsDeltaToKV to return updated batch updates and ensure proper sorting

---

Makefile.common

Issue Number: ref #57275
I'm using goland and have some templates which is not avoid go file, need to ignore them when enable failpoints
Tests 
> 
Side effects
Documentation
```release-note
None
```

makefile: ignore go template files in .idea dir when enable failpoints

---

pkg/ddl/schemaver/syncer.go

Issue Number: ref https://github.com/pingcap/tidb/issues/58992
If enable MDL, doesn't put DDLAllSchemaVersionsByJob key when job id = 0.
The etcd key DDLAllSchemaVersionsByJob with job id = 0 not be used anywhere.
Tests 
1. start tidb
2. check there is no `/keyspaces/tidb/1/tidb/ddl/all_schema_by_job_versions/0/xxx` in etcd 
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 get / --prefix
```
> 
Side effects
Documentation
```release-note
If enable MDL, doesn't put DDLAllSchemaVersionsByJob key when job id = 0
```

ddl: filter zero job IDs when puting `DDLAllSchemaVersionsByJob` key

---

pkg/planner/core/point_get_plan.go
tests/integrationtest/r/planner/core/casetest/partition/integration_partition.result
tests/integrationtest/t/planner/core/casetest/partition/integration_partition.test

Issue Number: close #54746
`newBatchPointGetPlan()` did not use the converted `datum` resulting in no found row for partitioned tables that used ` IN ()` with non-matching types.
Using the converted `datum`, like it was done for some other item types.
Tests 
> 
Side effects
Documentation
```release-note
Fixed matching rows for partitioned tables using IN function which also needed type conversion.
```

planner: Using converted value in newBatchPointGetPlan, fix for partitioned table and IN

---

br/tests/br_table_partition/prepare.sh
br/tests/br_table_partition/run.sh
dumpling/tests/partition_table/data/pt_case_0.sql
dumpling/tests/partition_table/data/pt_case_1.sql
dumpling/tests/partition_table/data/pt_case_2.sql
dumpling/tests/partition_table/result/pt_case_0-schema.sql
dumpling/tests/partition_table/result/pt_case_1-schema.sql
dumpling/tests/partition_table/result/pt_case_2-schema.sql
lightning/tests/lightning_partitioned-table/data/partitioned.a-schema.sql
lightning/tests/lightning_partitioned-table/data/partitioned.defaultlist-schema.sql
lightning/tests/lightning_partitioned-table/data/partitioned.list-schema.sql
lightning/tests/lightning_partitioned-table/data/partitioned.range-schema.sql
lightning/tests/lightning_partitioned-table/run.sh
tests/realtikvtest/importintotest/import_into_test.go

Issue Number: ref #58650 
Problem Summary: add more test cases for non-unique global index
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: add test cases for non-unique global index

---

pkg/ddl/BUILD.bazel
pkg/ddl/backfilling.go
pkg/ddl/backfilling_dist_scheduler.go
pkg/ddl/backfilling_dist_scheduler_test.go
pkg/ddl/backfilling_txn_executor.go
pkg/disttask/importinto/scheduler.go
pkg/disttask/importinto/scheduler_test.go
pkg/disttask/importinto/scheduler_testkit_test.go

- previous `backfillScheduler` doesn't schedule anything, it only send tasks to its worker and run them, so rename it to `backfillExecutor` to avoid confusion with other schedulers like job scheduler, and dxf scheduler.
- merge explicit impl of `scheduler.Extension` into impl of `scheduler.Scheduler`
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl/dxf: some rename and merge explicit impl of scheduler.Extension with scheduler

---

pkg/util/workloadrepo/BUILD.bazel
tools/tazel/util.go

Issue Number: ref #58247 
In https://github.com/pingcap/tidb/pull/58266, the timeout was set to long. From https://bazel.build/reference/test-encyclopedia, we can see that the `long` is 900s, which is too long for a whole dir. 
If it really has some tests exceeding the default short threshold, please verify the test first, then consider putting slow ones into a separate dir.
And enable the sharding
Tests 
> 
Side effects
Documentation
```release-note
None
```

util: split the tests of workloadrepo into multiple shard

---

util/expensivequery/expensivequerey_test.go
util/expensivequery/memory_usage_alarm.go

Issue Number: close #58942
Tests 
> 
Side effects
Documentation
```release-note
fix tidb panic in (*memoryUsageAlarm).recordSQL
```

*: fix tidb panic in (*memoryUsageAlarm).recordSQL

---

br/cmd/br/stream.go

Issue Number: ref #52088
The log task will start a domain, which spends much time to load statistic.
disable loading stats for log task
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: disable stats for log task

---

br/pkg/storage/s3.go

Issue Number: close #59043
We used the wrong client to copy object.
Used the rightly configured client to copy object.
Tests 
With the new client, now it returns no more `BucketRegionError`.
> 
Side effects
Documentation
```release-note
None
```

backup/pitr_coll: use target client of S3

---

br/cmd/br/backup.go
br/cmd/br/cmd.go
br/cmd/br/main.go
br/cmd/br/restore.go
br/pkg/backup/schema.go
br/pkg/metautil/metafile.go
br/pkg/restore/client.go
br/pkg/task/backup.go
br/pkg/task/common.go
br/pkg/task/common_test.go
br/pkg/task/restore.go
br/pkg/task/restore_raw.go
br/pkg/task/restore_txn.go
br/tests/br_file_corruption/run.sh
br/tests/br_full_ddl/run.sh
br/tests/br_full_index/run.sh
build/BUILD.bazel
pkg/executor/brie.go

close pingcap/tidb#56373
(cherry picked from commit 4f047be191be48d151c025703fc1c83ed015e453)
The default behavior of doing checksum during full backup has changed from enabled to disabled. 
The meaning of checksum flag is kind of ambiguous here, it doesn't mean we don't do the checksum of files when doing backup, instead we don't do checksum to compare from coprocessor side to the br side to improve the performance
Tests 
> 
Side effects
Documentation
```release-note
The default behavior of doing checksum during full …
```

cherry-pick-7.5: br: restore checksum shouldn't rely on backup checksum (#56712)

---

DEPS.bzl
go.mod
go.sum
pkg/executor/adapter.go
pkg/executor/internal/mpp/BUILD.bazel
pkg/executor/internal/mpp/local_mpp_coordinator.go
pkg/executor/internal/mpp/local_mpp_coordinator_test.go
pkg/planner/core/plan_to_pb.go
pkg/util/execdetails/execdetails.go
pkg/util/execdetails/execdetails_test.go

Issue Number: close #58682 
1. Refine the execution summary merging code for tiflash to reduce heap allocation
2. Encode sameZoneFlags for mpp exchange senders/receivers
3. Parse new added network traffic info in tiflash execution summary, and finally set to tikv exec details
Slow Log Test will be done in https://github.com/pingcap/tidb/pull/59041 
Execution Summary Test: 3 TiFlash Nodes, zone labels: [east, east, west]
TPCH-10, Q1
```
For ExchangeSender_51, all data are sent to one east tiflash node
+--------------------------------------------+-------------+----------+--------------+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

executor,util: Stat inner/inter zone network traffic for MPP tasks

---

br/pkg/storage/s3.go

Issue Number: close #59043
We used the wrong client to copy object.
Used the rightly configured client to copy object.
Tests 
With the new client, now it returns no more `BucketRegionError`.
> 
Side effects
Documentation
```release-note
None
```

backup/pitr_coll: use target client of S3 (#59044)

---

pkg/executor/builder.go
pkg/executor/internal/exec/indexusage.go
pkg/executor/internal/exec/indexusage_test.go
pkg/executor/point_get.go

Issue Number: close #58477
As described in the issue, maybe load stats is too slow for point get requests.
1. Don't load stats for point get requests.
Tests 
> 
It has been covered by existing tests.
Side effects
Documentation
```release-note
None
```

executor, indexusage: don't load stats for point get index usage reporter

---

ddl/db_partition_test.go
table/column.go

Issue Number: close #59047 
During the executor build phase getColDefaultValue is called for the date column and fails, due to trying to cast the default value '0000-00-00' which fails due to default sql_mode.
The underlying issue seems to be that CREATE TABLE does not set column.OriginDefaultValue, while ALTER TABLE ADD COLUMN does, which is ignored in this PR.
Do as DATETIME and TIMESTAMP, skip cast.
Tests 
> 
Side effects
Documentation
```release-note
Fix UPDATE after ALTER ADD date column giving error for incorrect value '0000-00-00'.
```

table: Don't cast date default values (same as timestamp/datetime) | tidb-test=pr/2472

---

pkg/domain/domain.go

Issue Number: ref https://github.com/pingcap/tidb/issues/58821 
- we have check schema version in domain reload after https://github.com/pingcap/tidb/issues/58095, so no need to reload twice when domain init
Tests 
restart tidb with millions of tables
> 
Side effects
Documentation
```release-note
None
```

infoschema: remove domain init reload when reload time greater than half of schemaLease

---

pkg/expression/builtin.go

Issue Number: close #59084
it set the wrong size. so it will happen the slicegrow. it should be avoided.
Tests 
run the ```BenchmarkScalarFunctionClone```
before:
```
BenchmarkScalarFunctionClone
BenchmarkScalarFunctionClone-8   	 1867233	       642.6 ns/op	    2384 B/op	      27 allocs/op
```
after:
```
BenchmarkScalarFunctionClone
BenchmarkScalarFunctionClone-8   	 1864874	       633.1 ns/op	    2352 B/op	      25 allocs/op
```
> 
Side effects
Documentation
```release-note
None
```

expression: fix wrong size in the baseBuiltinFunc.cloneFrom

---

pkg/planner/core/logical_plan_builder.go

Issue Number: close #58842 
https://github.com/pingcap/tidb/blob/cd9d3c03dbd863e4a9ebde08b35017fed93686db/pkg/planner/core/logical_plan_builder.go#L4648-L4658
here is the root causion of the slices grow. so we should add 1 to the capacity of column
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: avoid slicesgrow in the buildDataSource

---

pkg/util/execdetails/execdetails.go

Issue Number: ref #36058
BCE (Bound Check Elimination)
Go is a memory safe language. In array/slice/string element indexing and subslice operations, Go runtime will check whether or not the involved indexes are out of range. If an index is out of range, a panic will be produced to prevent the invalid index from doing harm. This is called bounds checking.
Bounds checks make our code run safely, on the other hand, they also make our code run a little slower. This is a trade-off a safe language must made.
Tests 
run ```go build -gcflags="-d=ssa/check_bce" ./pkg/util/execdetails/...```
before
```
pkg/util/execdetails/execdetails.go:706:20: Found IsInBounds
pkg/util/execdetails/execdetails.go:706:47: Found IsInBounds
pkg/util/execdetails/execdetails.go:709:18: Found IsInBounds …
```

execdetails: use slices.SortFunc to eliminate bound checker 

---

Makefile
br/pkg/stream/stream_metas_test.go
br/pkg/streamhelper/integration_test.go
br/pkg/task/stream_test.go
br/pkg/utils/backoff_test.go
pkg/ddl/tests/tiflash/ddl_tiflash_test.go
pkg/executor/sortexec/topn_chunk_heap.go
pkg/executor/test/admintest/admin_test.go
pkg/expression/helper_test.go
pkg/expression/integration_test/integration_test.go
pkg/owner/manager_test.go
pkg/planner/core/plan_cache_lru_test.go
pkg/table/column_test.go
pkg/table/temptable/interceptor_test.go

Issue Number: ref #57275
- `require.Error` only checks that the error is not nil, if you want to check the error is some specific error, you need to use API like `require.ErrorIs` or `ErrorContains`
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix error checking

---

pkg/server/http_status.go

If a C-based gRPC client connects to the TiDB status server, it might fail because of https://github.com/grpc/grpc/issues/23172
Issue Number: close #59093
The status server should support ALPN, otherwise C-based gRPC client might fail to connect to the status server. 
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: support ALPN for the status server

---

pkg/executor/traffic.go
pkg/executor/traffic_test.go
pkg/planner/core/planbuilder.go
pkg/planner/core/planbuilder_test.go
pkg/privilege/privileges/privileges.go
tests/integrationtest/r/executor/executor.result
tests/integrationtest/r/privilege/privileges.result
tests/integrationtest/t/privilege/privileges.test

Issue Number: close #59053 
- traffic capture: need `TRAFFIC_CAPTURE_ADMIN`
- traffic replay: need `TRAFFIC_REPLAY_ADMIN`
- show traffic: `TRAFFIC_CAPTURE_ADMIN` shows capture jobs, `TRAFFIC_REPLAY_ADMIN` shows replay jobs
- cancel traffic: `TRAFFIC_CAPTURE_ADMIN` cancels capture jobs, `TRAFFIC_REPLAY_ADMIN` cancels replay jobs
- Add privilege check in the planner
- Filter the results for show traffic jobs
- Add HTTP parameters for cancel traffic
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner, executor: add privilege check for traffic replay

---

pkg/executor/utils_test.go

Issue Number: close #59097
Problem Summary: `TestWorkerPool/TwoWorkers` is unstable because both workers are runnable after yield (`runtime.Gosched`), the execution order is not guaranteed by runtime scheduler.
Use sleep instead of yield.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: make TestWorkerPool stable

---

pkg/domain/schema_validator.go

Issue Number: ref #57743 #59094
there is a data race in the function `IsLeaseExpired`
lock before get the variable.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix data race for the function IsLeaseExpired

---

pkg/disttask/framework/integrationtests/framework_test.go
pkg/disttask/framework/scheduler/balancer.go
pkg/disttask/framework/taskexecutor/task_executor.go
pkg/disttask/framework/taskexecutor/task_executor_test.go
tests/realtikvtest/addindextest1/disttask_test.go

Issue Number: close #58827
See https://github.com/pingcap/tidb/issues/58827#issuecomment-2582290429
1. check `subtaskCtx` instead of `stepCtx` in `markSubTaskCanceledOrFailed`
2. ~~remove `checkCtx` since we introduced `subtaskCtx`~~
Tests 
> 
Side effects
Documentation
```release-note
None
```

DXF: check the cause of `subtaskCtx` to decide the subtask state

---

pkg/statistics/handle/history/history_stats.go
pkg/statistics/handle/types/interfaces.go

Issue Number: close https://github.com/pingcap/tidb/issues/57869
Partially revert https://github.com/pingcap/tidb/pull/59037
It turned out that we couldn't hold the lock that long, it would affect the auto-analysis and cause it to timeout.
```log
2025-01-22 17:32:19 (UTC+08:00)
TiDB [tc-tidb-5.tc](http://tc-tidb-5.tc/)-tidb-peer.forge4-tps-7687608-1-783.svc:4000
[exec.go:63] ["auto analyze failed"] [category=stats] [sql="analyze table `sbtest50476`.`sbtest1`"] [cost_time=50.740453383s] [error="[tikv:1205]Lock wait timeout exceeded; try restarting transaction"]
```
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release …

statistics: refactor RecordHistoricalStatsMeta to handle single table

---

pkg/types/field_name.go

Issue Number: close #59135
we observe the slicegrow in the FieldName.String()
Tests 
> 
Side effects
Documentation
```release-note
None
```

types: avoid slicegrow in the FieldName.String()

---

pkg/planner/core/casetest/planstats/testdata/plan_stats_suite_out.json
pkg/planner/core/collect_column_stats_usage.go
pkg/planner/core/collect_column_stats_usage_test.go
pkg/planner/core/rule_collect_plan_stats.go
pkg/planner/core/stats.go

Issue Number: close https://github.com/pingcap/tidb/issues/59107
As the issue said, the async load is loading more item than we expected.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: stats async load only load real predicate columns

---

ddl/db_partition_test.go
table/column.go

This PR is a cherry-pick for #59049 on hotfix branch
Issue Number: close #59047 
During the executor build phase getColDefaultValue is called for the date column and fails, due to trying to cast the default value '0000-00-00' which fails due to default sql_mode.
The underlying issue seems to be that CREATE TABLE does not set column.OriginDefaultValue, while ALTER TABLE ADD COLUMN does, which is ignored in this PR.
Do as DATETIME and TIMESTAMP, skip cast.
Tests 
> 
Side effects
Documentation
```release-note
Fix UPDATE after ALTER ADD date …
```

table: Don't cast date default values (same as timestamp/datetime) | tidb-test=920d9bf1b1137cda1272bdd59ae527aee8067944

---

pkg/executor/builder.go
pkg/planner/core/logical_plan_builder.go
pkg/planner/core/operator/logicalop/logical_lock.go
pkg/planner/core/operator/logicalop/logical_table_scan.go
pkg/planner/util/handle_cols.go

1、 The more important is to write the less code
2、```GetCol ``` has bound check. now we use iter and avoid to use this ```GetCol```
```
pkg/planner/util/handle_cols.go:227:19: Found IsInBounds
```
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add iter for HandleCols

---

pkg/statistics/handle/globalstats/BUILD.bazel
pkg/statistics/handle/globalstats/global_stats_async.go
pkg/statistics/handle/globalstats/global_stats_test.go

Issue Number: close #59194 
the same cmsketch is merge twice, which affects row estimation.
remove the unnecessary part.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: fix async merge global stats use cmsketch twice

---

pkg/planner/cardinality/selectivity_test.go
pkg/planner/core/find_best_task.go

Extend support for skyline pruning recognition of index without statistics to existing rules. 
By passing the "pseudo" result of the index from the CompareCandidates function for the "successful" index - it allows the later checking in SkyLinePruning to keep that index to prioritize above a table scan if tidb_opt_prefer_range_scan global variable is set.
This change is a minor addition to address prior customer concerns that a newly created index that does NOT yet have statistics may be selected by the existing CompareCandidates code - and the index WITH statistics is pruned. But the cost of the index that used defaults (since no statistics) may have a higher cost than tablescan.
Issue Number: close #57948
Tests 
> …

planner: notify skyline pruning of index statistics availability

---

br/pkg/stream/BUILD.bazel
br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/stream/rewrite_meta_rawkv_test.go
br/pkg/stream/table_mapping.go
br/pkg/stream/table_mapping_test.go
br/tests/br_pitr/check/check_key_types.sh
br/tests/br_pitr/incremental_data/key_types.sql
br/tests/br_pitr/prepare_data/key_types.sql
br/tests/br_pitr/run.sh

Issue Number: close #59108
Add tests to cover sequence id, auto increment id and auto random id cases are correctly handled in PiTR life cycle 
Revert the change in rewrite meta kv to return error instead of nil when items not found in db replace map to make sure it's absolutely safe. Will find another way to handle filtered items in next PR
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: add tests to cover sequence id, auto increment id and auto random id, revert meta kv capture logic

---

br/cmd/br/operator.go
br/pkg/restore/utils/rewrite_rule.go
br/pkg/restore/utils/rewrite_rule_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/58238
use a safe method to set rule rewrite ts.
1. hidden unsafe command
2. use a safe method to filter default data
Tests 
> 
Side effects
Documentation
```release-note
None
```

Compacted log: tiny fix or enhancement

---

pkg/planner/core/plan_cost_ver2.go
tests/integrationtest/r/planner/core/casetest/integration.result

Issue Number: close #59134 
The table access cost of PhysicalIndexLookUpReader should use TableRows for the table portion of the cost.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: typo in index costing

---

DEPS.bzl
WORKSPACE
go.mod
go.sum

Issue Number: close #59247
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: upgrade golang/glog to fix insecure temporary file usage

---

pkg/planner/core/casetest/index/testdata/index_range_out.json
pkg/planner/core/casetest/testdata/plan_normalized_suite_out.json
pkg/planner/core/cost/factors_thresholds.go
pkg/planner/core/find_best_task.go
pkg/planner/core/stats.go
tests/integrationtest/r/clustered_index.result

Issue Number: close #59133
Due to precision errors in floating point, a small tolerance is needed to ensure that an unnecessary adjustments are not made for cardinality estimation. An arbitrary value of 0.00001 is used as the tolerance.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add tolerance for row count floating point comparison

---

br/tests/br_check_dup_table/run.sh

Issue Number: close #59269 59269
The error `ErrTableAlreadyExisted` has not been applied on 8.1, we choose to check the log instead.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix intergration test check unapplied error type

---

pkg/util/generatedexpr/generated_expr.go

Issue Number: close #59303 
as shown, creating parser spend too much time. so we need to reuse this parser.
Tests 
> 
Side effects
Documentation
```release-note
None
```

generatedexpr: reuse parser to improve performance

---

pkg/ddl/table.go
pkg/ddl/table_test.go
pkg/meta/model/table.go

Issue Number: close #59238
Problem Summary: Follow MySQL, don't update UpdateTS for truncate partition and exchange partition.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl, meta: don't update `tblInfo.UpdateTS` for exchangePartition and truncatePartition

---

pkg/types/datum.go

Issue Number: close https://github.com/pingcap/tidb/issues/59332
1、reuse strings.Builder, but it cannot reuse buffer in the builder. so it is unnecessary to reuse builder
2、prealloc the buffer in the builder.
Tests 
> 
Side effects
Documentation
```release-note
None
```

datum: remove wrong usage of pool and prealloc the buffer

---

br/pkg/storage/ks3.go
br/pkg/storage/s3.go
br/pkg/storage/s3_test.go

Issue Number: close #59326
simply use `%s` instead of `%v` when printf
Tests 
> 
Side effects
Documentation
```release-note
None
```

external: improve S3 error message

---

pkg/ttl/client/notification.go
pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go

Issue Number: close #59347 
Some of the TTL jobs are skipped for handled multiple times in one iteration. It caused the following effect:
1. It'll take more time for `CheckNotOwnedJob`, `checkFinishedJob`, `rescheduleJobs` to handle all existing jobs.
2. The last job may be handled for multiple times, like finished multiple times.
I think it's a minor issue as both of them don't block the TTL.
Iterate the jobs in the reverse order.
Tests 
> 
```release-note
None
```

ttl: fix the issue that the TTL jobs are skipped or handled multiple times in one iteration

---

pkg/executor/show.go
pkg/executor/show_test.go

Issue Number: close #59336
Some users only want TiProxy to replay traffic, which needs session states but not session tokens.
However, `show session_states` reports errors when the signing cert is unavailable. Installing signing certs requires TiDB to restart, but users don't want that.
Return NULL in the token column if the signing cert is unavailable.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: support showing session_states when signing cert is unavailable

---

pkg/executor/slow_query.go
pkg/executor/slow_query_test.go

Issue Number: close #39940 
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix parse slow_query when db or index name contains `: `

---

pkg/parser/ast/expressions.go
pkg/parser/format/format.go
pkg/parser/parser.y
pkg/parser/parser_test.go

Issue Number: close #59000
Tests 
> 
Side effects
Documentation
```release-note
None
```

parser: fix compile error with mod function

---

pkg/disttask/framework/storage/table_test.go
pkg/disttask/framework/storage/task_table.go

Issue Number: close #59344
see issue
Tests 
before vs after
**Note:**: for the `after`, out of the remaining 1.9% CPU, only 0.5 is taken by DXF, others are taken by bindinfo/metric collect/cpu observer/runaway watcher, etc, see the third graph
how DXF query frequency affects CPU usage
> 
Side effects
Documentation
```release-note
None
```

dxf: optimize querying eligible tasks in task executor manager

---

pkg/ddl/notifier/subscribe.go
pkg/statistics/handle/ddl/BUILD.bazel
pkg/statistics/handle/ddl/ddl.go
pkg/statistics/handle/ddl/ddl_test.go
pkg/statistics/handle/storage/save.go

Issue Number: close https://github.com/pingcap/tidb/issues/58545
I checked all the ddl event handlers, the only one that can meet duplicate key error is insert the stats meta. So in this PR I used `insert ignore into` to avoid the error.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: do not ignore DDL event handing errors

---

pkg/executor/join/BUILD.bazel
pkg/executor/join/hash_join_base.go
pkg/executor/join/hash_join_v2.go
pkg/executor/join/outer_join_spill_test.go

Issue Number: close #59377
Tests 
> 
Side effects
Documentation
```release-note
Fix the incorrect return when hash join encounters error
```

executor: fix the incorrect return when hash join encounters error

---

pkg/metrics/grafana/tidb.json
pkg/ttl/metrics/metrics.go
pkg/ttl/ttlworker/BUILD.bazel
pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go
pkg/ttl/ttlworker/job_manager_test.go

Issue Number: close #59357
Only run ttl `DoGC` and `GetDelayMetricRecords` in leader node
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: only gc in leader to save performance

---

pkg/ttl/ttlworker/job.go
pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go
pkg/ttl/ttlworker/job_manager_test.go

Issue Number: close #58642
As mentioned in https://github.com/pingcap/tidb/pull/58539, a better solution to #58510 is to not remove running TTL jobs in GC, but let the owner to finish the job.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: don't GC running TTL jobs

---

pkg/planner/core/casetest/integration_test.go
pkg/planner/core/integration_test.go
pkg/planner/core/rule_partition_processor.go
tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result

…ant of different types
Issue Number: close #59123
SQL is a weak type language, and users always ignore constant types when comparing partition key.
When try to prune partitions, try more types of constant. For now, we should consider real and decimal, which are regularly used.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: enhance partition prune when comparing partition key with constant of different types

---

pkg/kv/interface_mock_test.go
pkg/kv/kv.go
pkg/session/session.go
pkg/session/test/txn/BUILD.bazel
pkg/session/test/txn/txn_test.go
pkg/session/txn.go
pkg/sessionctx/variable/session.go
pkg/sessiontxn/isolation/BUILD.bazel
pkg/sessiontxn/isolation/base.go

Issue Number: close #57165
This PR checks the invariant that timestamps of transactions in a session should increase monotonically.
It saves the timestamp of the last transaction in `SessionVars`, after the transaction is committed. The saved timestamp is compared with the `start_ts` and the `commit_ts` of the next transaction.
This PR depends on the TiKV client-go PR, https://github.com/tikv/client-go/pull/1489, which exports `commit_ts` of the transaction.
Tests 
> 
Side effects
Documentation
```release-note
None
```

session: track LastCommitTS in SessionVars and check timestamps of later txns are larger

---

pkg/expression/aggregation/descriptor.go
pkg/expression/expression.go
pkg/expression/expression_test.go
pkg/planner/core/operator/logicalop/logical_aggregation.go
pkg/planner/core/operator/logicalop/logical_join.go
pkg/planner/core/operator/logicalop/logical_projection.go
pkg/planner/util/funcdep_misc.go
pkg/planner/util/null_misc.go

…
Issue Number: ref #38610
when we need to extract the functional dependencies duration the physical optimization, it will skip the plan cache. but it is wrong. so we need to avoid skipPlanCache when to extract FD.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: avoid skipping plan cache when extracting funcdep

---

pkg/ddl/notifier/subscribe.go
pkg/statistics/handle/ddl/ddl.go

Issue Number: close #59501
seems when domain is closing, DDL notifier may not exit in time. So we tolerate some error
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl notifier: allow another error in CI assert

---

pkg/expression/builtin_json.go
pkg/expression/builtin_json_test.go
pkg/expression/builtin_json_vec.go
tests/integrationtest/r/expression/json.result
tests/integrationtest/t/expression/json.test

Issue Number: close https://github.com/pingcap/tidb/issues/56788
Fix the issue where the json_keys function returns incorrect results when called with two arguments and the first argument is of type JSONTypeCodeArray.
* Make `builtinJSONKeys2ArgsSig.vecEvalJSON` has the same behavior as `builtinJSONKeys2ArgsSig.evalJSON` and add tests.
* Add some tests for `evalJSON`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

expression: fix incorrect results of `json_keys(json, path)` with JSONTypeCodeArray as the first argument | tidb-test=pr/2480

---

br/pkg/restore/snap_client/systable_restore_test.go
pkg/ddl/schematracker/checker.go
pkg/session/bootstrap.go
pkg/session/bootstrap_test.go

Issue Number: close #59476
We need a mechanism to detect whether two TiDB servers are in the same tidb cluster. Adding the `cluster_id` to the `mysql.tidb` table is the most sutiable way. I've also considered other options in #59476 .
Add the `cluster_id` row to the `mysql.tidb` table.
Tests 
> 
Side effects
Documentation
```release-note
Insert the `cluster_id` to the `mysql.tidb` table.
```

bootstrap: add `cluster_id` to the `mysql.tidb` table

---

pkg/util/prefetch/reader.go
pkg/util/prefetch/reader_test.go

Issue Number: close #59495
use `io.ReadFull` to fully fill the buffer
Tests 
> 
performance increased in a AWS manual test
Side effects
Documentation
```release-note
None
```

prefetch: the prefetch buffer should be fully filled

---

pkg/ddl/split_region.go
pkg/ddl/tests/partition/db_partition_test.go
pkg/executor/test/splittest/split_table_test.go

Issue Number: close #59530
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: let partition table pre split index regions

---

br/pkg/storage/BUILD.bazel
br/pkg/storage/gcs.go

Issue Number: close #56127
Tests 
> 
Side effects
Documentation
```release-note
None
```

Dumpling: GCS client always retry and also retry for 401 error. (#58198)

---

br/pkg/lightning/backend/kv/sql2kv.go

Issue Number: close #56705
Cached the result of columnAPI.Cols() in Encoder so that it could be repeatably used in encoding.
Tests 
> - [x] The original test cases were able to cover the change.
Side effects
Documentation
```release-note
None
```

Lightning: fix performance regression introduced by behavior change of columnAPI.Cols()

---

pkg/expression/expr_to_pb_test.go
pkg/expression/infer_pushdown.go

Issue Number: ref  https://github.com/pingcap/tidb/issues/59566
TiKV can't get the sql_mode and get wrong result.
So now we disable str_to_date pushdown to tikv.
Tests 
> 
Side effects
Documentation
```release-note
None
```

Revert "expr: support str_to_date pushdown to tikv #59362"

---

pkg/infoschema/infoschema.go
pkg/infoschema/infoschema_test.go
pkg/infoschema/infoschema_v2.go
pkg/infoschema/infoschema_v2_test.go
pkg/infoschema/interface.go
pkg/statistics/handle/handle.go
pkg/statistics/handle/types/interfaces.go
pkg/statistics/handle/usage/session_stats_collect.go
pkg/statistics/handle/util/BUILD.bazel
pkg/statistics/handle/util/table_info.go

Issue Number: ref https://github.com/pingcap/tidb/issues/59104, ref #57869 
Add some new APIs to `InfoSchema`. All of them only contain memory operations.
Tests 
> 
Side effects
Documentation
```release-note
None
```

stats, infoschema: avoid some network cost of reading table meta kv

---

pkg/expression/infer_pushdown.go
pkg/planner/core/find_best_task.go

Issue Number: ref #59307
avoid slicesgrow in the ```PushDownExprsWithExtraInfo```
Tests 
> 
Side effects
Documentation
```release-note
None
```

expression: avoid slicesgrow in the PushDownExprsWithExtraInfo

---

br/pkg/storage/gcs.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

external storage: retry on a new http2 error | tidb-test=release-8.1.2

---

DEPS.bzl
go.mod
go.sum
pkg/metrics/grafana/tidb.json

Issue Number: ref #58780 
Tests 
```release-note
None
```

metrics: add circuit breaker metrics

---

br/pkg/task/operator/config.go
br/pkg/task/operator/prepare_snap.go
tests/realtikvtest/brietest/BUILD.bazel
tests/realtikvtest/brietest/operator_test.go

Issue Number: close #59604 
The CI test idc-jenkins-ci-tidb/check_dev_2  may fail when checking safepoint.
This is because there is gc safepoint registered by other concurrent test.
Only check the gc safepoint registered by current test.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix ci fail due to unexpected gc safepoint

---

pkg/lightning/backend/local/localhelper.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning: use 2 level split & scatter | tidb-test=release-8.1.2

---

pkg/bindinfo/global_handle.go
pkg/bindinfo/global_handle_test.go
pkg/bindinfo/tests/cross_db_binding_test.go
pkg/ddl/notifier/testkit_test.go
pkg/domain/domain.go
pkg/domain/infosync/info.go
pkg/planner/core/rule_collect_plan_stats.go
pkg/server/server.go
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/handle.go
pkg/statistics/handle/lockstats/lock_stats.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/handle/util/BUILD.bazel
pkg/statistics/handle/util/pool.go
pkg/statistics/handle/util/util.go
pkg/statistics/handle/util/util_test.go
pkg/testkit/mocksessionmanager.go
pkg/timer/tablestore/sql_test.go
pkg/util/processinfo.go
pkg/util/session_pool.go
pkg/util/session_pool_test.go

Issue Number: close #59524 close https://github.com/pingcap/tidb/issues/59560
ref https://github.com/pingcap/tidb/pull/59522
This is an alternative API design to solve the problem. I believe explicitly using destroy instead of exposing implementation details is a better approach to fix it.
I also added more logs to help us inspect error cases.
Note: This PR doesn’t address the root cause of the issues; it only ensures that we don’t encounter OOM problems. We still need to figure out why we’re running into this kind of stats loading.
Tests 
> 
Side effects
Documentation …

statistics: add Destroy method and handle session recycling

---

pkg/session/session.go
pkg/sessionctx/variable/session.go
tests/integrationtest/r/privilege/privileges.result
tests/integrationtest/t/privilege/privileges.test

Issue Number: close #59600
`set session_states` sets the current resource group but doesn't check the dynamic privilege.
If the resource group changes and `tidb_resource_control_strict_mode` is ON, check the privilege.
Tests 
> 
Side effects
Documentation
```release-note
- Fix missing dynamic privilege check to `SET SESSION_STATES`.
```

session, variable: add privilege check to `set session_states`

---

pkg/disttask/framework/mock/scheduler_mock.go
pkg/disttask/framework/proto/task.go
pkg/disttask/framework/scheduler/interface.go
pkg/disttask/framework/scheduler/scheduler.go
pkg/disttask/framework/storage/task_state.go
pkg/disttask/importinto/scheduler.go
pkg/disttask/importinto/scheduler_testkit_test.go
tests/integrationtest/r/ddl/db.result
tests/integrationtest/r/ddl/db_integration.result
tests/integrationtest/r/ddl/multi_schema_change.result
tests/integrationtest/r/executor/partition/write.result
tests/integrationtest/r/executor/write.result
tests/integrationtest/r/generated_columns.result
tests/integrationtest/r/session/clustered_index.result
tests/integrationtest/t/ddl/db.test
tests/integrationtest/t/ddl/db_integration.test
tests/integrationtest/t/ddl/multi_schema_change.test
tests/integrationtest/t/executor/partition/write.test
tests/integrationtest/t/executor/write.test
tests/integrationtest/t/generated_columns.test
tests/integrationtest/t/session/clustered_index.test
tests/realtikvtest/importintotest/BUILD.bazel
tests/realtikvtest/importintotest/import_into_test.go

sometimes, our internal test takes a long time before it meet some bug that's not handled before, we want the task enter a `awaiting-resolution` state to avoid the intermediate state or files be cleaned up, and after we fix the bug, we can continue to verify that it works.
Tests 
file content on import
```csv
aaa,bbb
```
then
```sql
mysql> import into t from '/Users/xxxxxxxx/playground/lightning/single-file/test.t1.1.csv' with detached;
+--------+----------------------------------------------------------------+--------------+----------+-------+---------+------------------+---------------+----------------+----------------------------+------------+----------+------------+
| Job_ID | Data_Source                                                    | …
```

dxf: make task enter `awaiting-resolution` state on error | tidb-test=release-8.1.2

---

br/pkg/storage/BUILD.bazel
br/pkg/storage/azblob.go
br/pkg/storage/azblob_test.go
br/pkg/storage/gcs.go

Issue Number: close #59339
When log backup enabled, restoring from azure blob storage and GCS is still impossible because they didn't implement `Copier`.
This Added support to `CopyFrom` for `AzureBlobStorage` and `GCSStorage`.
Tests 
Tested Azure by `azurite`. 
Start PiTR by:
```fish
#! /usr/bin/env fish
set pfx $fish_pid
set -q container || set container "tc-tidb-0"
set -q strg_prefix || set strg_prefix "test"
function strg
echo "gs://br-datasets/$argv[1]"
end
function br
kubectl exec '-it' $container '--' /br-for-restore $argv
end
br backup full -s (strg "juncen/tpcc-test/$pfx/$strg_prefix-full") $argv
gcloud storage cp (strg "juncen/tpcc-test/$pfx/$strg_prefix-full/backupmeta") ./.backupmeta.tmp
set backupts (cat ./.backupmeta.tmp | _get_brpb BackupMeta | rg -r '$1' …
```

br/storage: adapt copier for azure and gcs

---

pkg/infoschema/cluster.go
pkg/infoschema/tables.go
pkg/planner/core/explain.go

Issue Number: close #59606 
in fact, They have been upper.
```memTableToAllTiDBClusterTables``` and ```memTableToDDLOwnerClusterTables``` have been upper. the parameters of IsClusterTableByName have been upper, too.
Tests 
```
func BenchmarkIsClusterTableByName(b *testing.B) {
b.ResetTimer()
for i := 0; i < b.N; i++ {
infoschema.IsClusterTableByName("test", "t1")
}
}
```
before
```
BenchmarkIsClusterTableByName
BenchmarkIsClusterTableByName-8   	55993436	        20.92 ns/op
```
after
```
BenchmarkIsClusterTableByName
BenchmarkIsClusterTableByName-8   	895389862	         1.412 ns/op
```
> 
Side effects
Documentation …

infoschema: avoid strings.toUpper in the IsClusterTableByName

---

DEPS.bzl
go.mod
go.sum
tests/realtikvtest/txntest/BUILD.bazel
tests/realtikvtest/txntest/txn_test.go

Do not set txn scope in snapshot to fix the problem.
Tests 
> 
Side effects
Documentation
```release-note
Fix TSO retrieval failure during read TS validation when `zone` label is set.
```

*: (7.1) fix TSO retrieval failure during read TS validation

---

pkg/ddl/backfilling.go
pkg/ddl/backfilling_dist_executor.go
pkg/ddl/backfilling_dist_scheduler.go
pkg/ddl/backfilling_operators.go
pkg/ddl/backfilling_read_index.go
pkg/ddl/db_test.go
pkg/ddl/index.go
pkg/ddl/ingest/integration_test.go
pkg/disttask/framework/taskexecutor/execute/interface.go
pkg/disttask/framework/taskexecutor/interface.go
pkg/disttask/framework/taskexecutor/task_executor.go
pkg/disttask/framework/testutil/context.go
pkg/disttask/operator/operator.go
pkg/disttask/operator/pipeline.go
pkg/executor/operate_ddl_jobs.go
pkg/meta/model/job.go
pkg/resourcemanager/pool/workerpool/BUILD.bazel
pkg/resourcemanager/pool/workerpool/workerpool.go
pkg/resourcemanager/pool/workerpool/workpool_test.go
tests/realtikvtest/addindextest1/BUILD.bazel
tests/realtikvtest/addindextest1/disttask_test.go
tests/realtikvtest/addindextest2/BUILD.bazel
tests/realtikvtest/addindextest2/alter_job_test.go
tests/realtikvtest/addindextest3/operator_test.go

Issue Number: ref #57497, ref #57229
Tests 
- ENV: 1pd/1tidb/1tikv
- `create table t(id bigint primary key auto_increment, b varchar(1024), c varchar(1024));` and insert 16M rows
- run `alter table t add index(b(128));`, the total index KV is about 5G
- case 1: with initial thread=2/batch_size=32, after `admin alter ddl jobs 131 thread = 8, batch_size = 256;`, time of encoding part changes from `34s` -> `18s`
- case 2: with initial thread=4/batch_size=256, after `admin alter ddl jobs 133 thread = 1, batch_size = 32;`, time of encoding part changes from `16s` -> `28s`
- case 3: with initial thread=4/batch_size=256/max_write_speed=100M, after `admin alter ddl jobs 135 max_write_speed = 0;`, time of importing part changes from `53s` -> `23s`
- case 4: with initial …

ddl: modify param at runtime for add-index on DXF local sort

---

pkg/planner/core/task.go
pkg/planner/property/physical_property.go

This reverts commit 41c60da715d96a3a708ad0824dd5b544e8c25d0b.
Issue Number: ref #38610
it is some problem in this PR
```
if len(p.MPPPartitionCols) > len(keys) {
```
it is wrong. we must add an exchanger here.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: revert support sub-merge needEnforceExchanger

---

pkg/executor/workloadrepo.go
pkg/util/workloadrepo/const.go
pkg/util/workloadrepo/snapshot.go
pkg/util/workloadrepo/worker.go
pkg/util/workloadrepo/worker_test.go

This pull request simplifies the workload repository code.
This pull request removes the snapshot command key (/tidb/workloadrepo/snap_command) and changes the snapshot command (admin create workload snapshot) to update the snapshot id key directly.
Tests 
> 
Side effects
Documentation
```release-note
None
```

workloadrepo: Simplify the snapshot code.

---

sessionctx/variable/session.go

Issue Number: close #57798 
cherry-pick https://github.com/pingcap/tidb/pull/57799
hotfix for 6.5.11
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: avoid unlock of unlocked mutex panic on TableDeltaMap | tidb-test=920d9bf1b1137cda1272bdd59ae527aee8067944  (#57799)

---

br/pkg/storage/parse.go
br/pkg/storage/parse_test.go

Issue Number: close #59548
The external storage backend becomes dirty after parse any external storage URL.
Clone the backend options when parse it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: clone backend options

---

pkg/executor/analyze_global_stats.go
pkg/statistics/histogram.go

Issue Number: close #59274 
the `mergeBuffer` is in reverse order. we need to call `slices.Reverse` before join it with others.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: correct the bucket order when merging global hist

---

pkg/util/workloadrepo/worker.go
pkg/util/workloadrepo/worker_test.go

Issue Number: ref #59243, ref #58247 
Problem Summary: Reading from these memory tables sends requests to the PD. For sampled tables especially, this adds unwanted load to the PD. Additionally, frequently sampling `INFORMATION_SCHEMA.TIDB_HOT_REGIONS` introduces a throughput regression (#59243).
The following tables are no longer snapshotted by the workload repository:
* `INFORMATION_SCHEMA.TIKV_REGION_STATUS`
The following tables are no longer sampled by the workload repository:
* `INFORMATION_SCHEMA.CLUSTER_LOAD`
* `INFORMATION_SCHEMA.TIDB_HOT_REGIONS`
* `INFORMATION_SCHEMA.TIKV_STORE_STATUS`
The partition unit tests (`TestCreatePartition` and `TestDropOldPartitions`) have also been modified to remove the excluded tables. In a couple of cases, they have been replaced with snapshotted …

workloadrepo: exclude tables that contact the PD server on read

---

pkg/bindinfo/BUILD.bazel
pkg/bindinfo/binding.go
pkg/bindinfo/global_handle.go
pkg/bindinfo/global_handle_test.go
pkg/bindinfo/tests/BUILD.bazel
pkg/bindinfo/tests/bind_test.go
pkg/planner/core/planbuilder.go
pkg/planner/core/preprocess.go

Problem Summary: planner: refactor some code related to binding
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: refactor some code related to binding

---

Makefile.common

Problem Summary: `make failpoint-enable` will reports warn in ubuntu env, just fix it.
Tests 
before this commit
after this commit
> 
Side effects
Documentation
```release-note
None
```

makefile: fix `make failpoint-enable` reports warn

---

br/pkg/storage/ks3.go
br/pkg/storage/s3.go
br/pkg/storage/s3_test.go

Issue Number: close #50451
when reading a file range using s3, the `pos` must be set, as we will use it as the start position when retry
Tests 
> 
Side effects
Documentation
```release-note
None
```

objstore: fix read position on retry when reading a file range using s3

---

pkg/types/json_binary_functions.go
tests/integrationtest/r/expression/json.result
tests/integrationtest/t/expression/json.test

Issue Number: close #59619
`json_extract('{"a":"b"}', '$[last]')` should also return `{"a":"b"}`. It also affects the `json_set` and any other json functions using the path.
TiDB already handled the case for `$[0]`, but we didn't handle this case for `$[last]`.
Also return the object itself when the path is `$[last]`, just like `$[0]`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

json: extract the `$[last]` entry from json object should also return itself

---

pkg/executor/insert_test.go
pkg/store/mockstore/unistore/lockstore/lockstore.go
pkg/store/mockstore/unistore/tikv/write.go

Issue Number: close #59651
The Unistore cannot handle a row is larger than the lockstore arena blocksize.
Added an error when trying to lock a row that is too big.
Tests 
> 
Side effects
Documentation
```release-note
Return error if a row is larger than the unistore lock blocksize instead of panic: runtime error: index out of range [-1]
```

unistore: Added error if row is too long to be locked

---

pkg/executor/BUILD.bazel
pkg/executor/traffic.go
pkg/executor/traffic_test.go

Issue Number: close #59712
`Show traffic jobs` and `cancel traffic jobs` show or cancel replay jobs when the user has `TRAFFIC_CAPTURE_ADMIN` privilege but not the `TRAFFIC_REPLAY_ADMIN` privilege.
- Fix the typo on privilege
- Add more info to the error message
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix traffic replay jobs are shown when the user doesn't have the TRAFFIC_REPLAY_ADMIN privilege

---

br/pkg/restore/internal/prealloc_table_id/BUILD.bazel
br/pkg/restore/internal/prealloc_table_id/alloc.go
br/pkg/restore/internal/prealloc_table_id/alloc_test.go

Issue Number: close #59718
BR snapshot restore reuses the last global ID when pre-allocates table IDs
pre-allocate from `last global ID + 1`
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix pre allocate id exceeds bound

---

pkg/expression/builtin_json.go
tests/integrationtest/r/expression/json.result
tests/integrationtest/t/expression/json.test

Issue Number: close #59465
Previously, `JSON_ARRAY_APPEND('[1]', '$', '[2,3]')` will give `[1,2,3]`, which is not expected. It's because in TiDB the `JSON_ARRAY_APPEND` shared the same implementation with `JSON_MERGE`. To fix this issue, we should wrap the new item with an array when passing it to the merge logic.
Wrap the new item with array before re-using the merge logic.
Tests 
> 
Side effects
Documentation
```release-note
None
```

json: fix the issue that two arrays are merged but not append in `JSON_ARRAY_APPEND`.

---

pkg/lightning/backend/external/BUILD.bazel
pkg/lightning/backend/external/engine.go
pkg/lightning/backend/external/engine_test.go

Issue Number: ref #59725
See https://github.com/pingcap/tidb/pull/59613
Tests 
> 
Side effects
Documentation
```release-note
None
```

external: fix decoding the last key in split keys  | tidb-test=release-8.1.2

---

DEPS.bzl
executor/BUILD.bazel
executor/set.go
go.mod
go.sum

Do not return errors in the ts validator. Only logs.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: (release-6.5) Validate ts only for stale read

---

pkg/planner/core/stats.go
tests/integrationtest/r/planner/core/issuetest/planner_issue.result
tests/integrationtest/t/planner/core/issuetest/planner_issue.test

Issue Number: close #59762 
when we fixed the `IdxCols` for the path, we didn't update the full one for it.
So the full one may be smaller than the prefix one.
Tests 
> 
Side effects
Documentation
```release-note
fix the issue that the TiDB may panic when fixcontrol#44855 is enabled
修复当 fixcontrol#44855 开启时，TiDB 的会话可能执行崩溃的问题
```

planner: fix the possible panic when fixcontrol#44855 enabled

---

pkg/privilege/privileges/cache.go
pkg/privilege/privileges/cache_test.go
pkg/privilege/privileges/tidb_auth_token_test.go
tests/integrationtest/r/privilege/privileges.result
tests/integrationtest/t/privilege/privileges.test

Issue Number: close #59552
The old code use key = username + "@" + host, and also split by "@" to get back the username.
This is not stable enough when the username itself contains "@"
Change key from username + "@" + host to {username, host} struct makes the code more robust.
Tests 
> 
Side effects
Documentation
```release-note
None
```

privilege: handle username with "@" correctly for role(RBAC) related code

---

ddl/ddl_api.go
ddl/integration_test.go
executor/write_test.go
types/datum.go
types/datum_test.go

Reverts pingcap/tidb#57354 because of https://github.com/pingcap/tidb/issues/59759
close #59769
We'll need to reconsider the solution / bugfix for both issues before the next release of 6.5.

table: Revert "table: fix the issue that the default value for `BIT` column is wrong (#57303)"

---

DEPS.bzl
go.mod
go.sum
pkg/executor/BUILD.bazel
pkg/executor/set.go

Issue Number: ref #59402 
Only enable the ts check for stale reads
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: (release-7.5) validate ts only for stale read

---

pkg/executor/BUILD.bazel
pkg/executor/traffic.go
pkg/executor/traffic_test.go

Issue Number: close #59811
- Traffic replay from S3 always reports `tiproxy instances number is less than input paths number`
- The URL paths passed to TiProxy miss parameters like access key and endpoint
- Extract the right subdirectory from the URL path and then assign it to TiProxy
- Create another *url.URL object because the previous one is updated in parsing
Tests 
> 
Manual test: manually execute traffic replay from S3 and check the result.
Side effects
Documentation
```release-note
None
```

executor: fix that traffic replay from S3 always report an error

---

br/pkg/restore/log_client/batch_meta_processor.go
br/pkg/stream/table_history.go
br/pkg/task/restore.go
br/pkg/task/stream.go
br/tests/br_pitr_table_filter/run.sh

Issue Number: close #59723
we detect partition changes during log restore, if we found a partition is moved in/out of the filter range during log restore, we throw an error since we cannot support on partition level right now. If the partition exchange happens totally in or out of the filter range without moving across the filter boundary, we can support that and no error will be thrown. 
also added a few more tests to piggyback on this PR
1. filter restore one table at a time and don't clean up cluster
2. filter restore with log compaction
3. filter restore with truncation 
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-t …

br: error out if pitr with table filter has exchange partition in/out filter range

---

br/pkg/storage/gcs.go
br/pkg/storage/gcs_test.go

Issue Number: close #59754
see https://github.com/googleapis/google-cloud-go/issues/7090 and https://github.com/golang/go/issues/53472, it seems a bug of golang net/http. we workaround it
Tests 
> 
Side effects
Documentation
```release-note
None
```

objstore: retry on GCS EOF error

---

pkg/executor/infoschema_reader.go
pkg/statistics/handle/cache/stats_table_row_cache.go
pkg/statistics/handle/history/BUILD.bazel
pkg/statistics/handle/history/history_stats.go
pkg/statistics/handle/lockstats/BUILD.bazel
pkg/statistics/handle/lockstats/unlock_stats.go
pkg/statistics/handle/storage/BUILD.bazel
pkg/statistics/handle/storage/gc.go
pkg/statistics/handle/storage/save.go
pkg/statistics/handle/storage/update.go
tests/integrationtest/r/globalindex/information_schema.result

Issue Number: close https://github.com/pingcap/tidb/issues/55803
As I mentioned in the issue https://github.com/pingcap/tidb/issues/55803#issuecomment-2357772381, the main problem is that `UpdateByID` anciently updates the modify_time even when the dirty tables have not been updated.
But as @time-and-fate mentioned, the maintenance of the dirty table follows a best-effort approach, so it would be better to delete it entirely.
Tests 
> 
Side effects
Documentation
```release-note
修复 information_schema.tables 内存表信息不准确的问题
Fix the issue of …
```

statistics: Remove the ineffective dirty IDs from the row count cache

---

br/pkg/restore/snap_client/client.go
br/pkg/restore/snap_client/systable_restore.go
br/pkg/utils/schema.go
br/tests/br_systables/run.sh
pkg/ddl/executor.go
pkg/parser/mysql/const.go
pkg/util/filter/BUILD.bazel
pkg/util/filter/schema.go
pkg/util/misc.go
pkg/util/workloadrepo/BUILD.bazel
pkg/util/workloadrepo/const.go
pkg/util/workloadrepo/housekeeper.go
pkg/util/workloadrepo/snapshot.go
pkg/util/workloadrepo/table.go
pkg/util/workloadrepo/worker.go
pkg/util/workloadrepo/worker_test.go

Issue Number: close #58768 
Add `WORKLOAD_SCHEMA` schema to the ignore list of BR when performing the restore.
BTW, For the 'full backup' process, BR tries to backup everything so there's no mechanism to skip a specific table/schema.
Tests 
> 
Side effects
- NA
Documentation
- NA
```release-note
None
```

workloadrepo: make sure WORKLOAD_SCHEMA is ignored by BR

---

pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/handle/types/interfaces.go

I moved the lock to the correct position because placing it near the two channels was too confusing.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: replace StatsLoad mutex with a dedicated mutex for statsCache protection

---

pkg/domain/domain.go
pkg/privilege/privileges/cache.go
pkg/session/session.go

Issue Number: ref #55563
On 8.5 branch, the feature to [support 2M users](https://github.com/pingcap/tidb/issues/55563) is not completed,  but some code sneak in.
That cause subtle bug,  the `loadSomeUser` function should load user and also the roles of the user,  on the bug-free version, it is:
```
// Load the full role edge table first.
p.roleGraph = make(map[string]roleGraphEdgesTable)
err := p.loadTable(ctx, sqlLoadRoleGraph, p.decodeRoleEdgesTable)
if err != nil {
return nil, errors.Trace(err)
}
// Including the user list and also their roles
extendedUserList := make(map[string]struct{}, len(userList))
for _, user := range userList {
extendedUserList[user] = struct{}{}
}
findUserAndAllRoles(extendedUserList, p.roleGraph)
// Re-generate the user list.
userList = …
```

*: revert to load full privilege data on v8.5

---

pkg/executor/traffic.go
pkg/executor/traffic_test.go
pkg/planner/core/planbuilder.go
pkg/planner/core/planbuilder_test.go

Issue Number: close #59871
The only way to see the parameters is to check tiproxy logs, which is unfriendly.
Add an extra column `PARAMS` to the output of `show traffic jobs`
Tests 
> 
```sql
mysql> show traffic jobs;
+----------------------------+----------------------------+----------------+---------+----------+--------+-------------+----------------------------------------------------------------------------+
| START_TIME                 | END_TIME                   | INSTANCE       | TYPE    | PROGRESS | STATUS | FAIL_REASON | PARAMS                                                                     |
+----------------------------+----------------------------+----------------+---------+----------+--------+-------- …
```

planner, executor: add PARAMS column to the output of `show traffic jobs`

---

pkg/ddl/backfilling_operators.go
tests/realtikvtest/addindextest2/global_sort_test.go
tests/realtikvtest/addindextest3/operator_test.go

Issue Number: close #59897
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: fix job's row count for global sort

---

pkg/disttask/framework/storage/task_table.go

[Double](https://github.com/pingcap/tidb/pull/59750) the memory quota is not enough, let's quadruple it
Tests 
> 
Side effects
Documentation
```release-note
None
```

dxf: increase memory quota for session of generating subtasks (part 2) | tidb-test=release-8.1.2

---

WORKSPACE
build/image/base
build/image/parser_test
dumpling/README.md
go.mod

Tests 
> 
Side effects
Documentation
```release-note
None
```

*: upgrade go1.23.7

---

pkg/planner/core/operator/logicalop/logical_apply.go
pkg/planner/core/operator/logicalop/logical_join.go
pkg/planner/funcdep/extract_fd_test.go

since `col.CorrelatedColUniqueID` is only filled when projection projects a correlated column, so for apply's case, when inner schema column's CorrelatedColUniqueID is not equal to 0, it means correlated column is projected again inside, we can directly add equivalence between this schema column == CorrelatedColUniqueID. 
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: simplify the apply's extract FD logic facilitating the memo case.

---

pkg/executor/test/tiflashtest/BUILD.bazel
pkg/executor/test/tiflashtest/tiflash_test.go
pkg/planner/core/optimizer.go

Issue Number: close #59877 
Problem described [here](https://github.com/pingcap/tidb/issues/59877#issuecomment-2696140665)
This PR limit the fined grained shuffle usage to situations that shuffle keys are the same with actual join keys. In this way the pre-calculated hash codes will always be valid.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that the query result might be wrong when mpp hash join's equal condition keys have different data type.
```

planner: Limit fine grained shuffle usage for mpp join operators to ensure shuffle keys are the same with actual join keys

---

br/pkg/restore/log_client/client_test.go
br/pkg/restore/log_client/log_split_strategy.go

Issue Number: close https://github.com/pingcap/tidb/issues/59900
The current log restore process accumulates small files, which can negatively impact performance. During performance testing, log restore took twice as long as before due to the excessive number of small files. To optimize performance, we should skip accumulating small files, as was done previously.
Tests 
before this PR
after this PR
> 
Side effects
Documentation
```release-note
None
```

log restore: fix the bottleneck of btree map

---

pkg/executor/traffic.go
pkg/executor/traffic_test.go

Issue Number: close #59906
Currently, when any error occurs on TiProxy, TiDB just shows `Internal Server Error` to the user because TiDB writes the unwrapped error to the client. This error message is useless and users need to check the logs.
- Replace `errors.Wrapf` with `errors.Errorf` to create only one error
- Remove some `errors.Wrapf` and `errors.Trace`
Tests 
> 
```sql
mysql> traffic capture to '/tmp/traffic' duration="10s";
ERROR 1105 (HY000): request to tiproxy '127.0.0.1:3080' failed: start capture failed: file meta already exists, please remove it before capture
mysql> traffic capture to '/tmp/traffic' duration="10s";
ERROR 1105 (HY000): request to tiproxy '127.0.0.1:3080' failed: Post …
```

executor: show the error message from TiProxy when replay traffic fails

---

pkg/planner/core/planbuilder.go
pkg/statistics/handle/storage/stats_read_writer.go
pkg/statistics/handle/types/interfaces.go

1.	Ensure that all code uses the constant `statistics.NonPartitionTableID`. 
2.	Remove the unnecessary interface.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: update AnalyzeTableStmt to use NonPartitionTableID for non-partitioned tables

---

pkg/ddl/column.go
pkg/ddl/create_table.go
pkg/ddl/executor.go
pkg/ddl/index.go
pkg/ddl/index_modify_test.go
pkg/ddl/job_worker.go
pkg/ddl/modify_column.go
pkg/ddl/sanity_check.go
pkg/executor/builder.go
pkg/executor/check_table_index.go
pkg/meta/model/job_args.go
pkg/meta/model/job_args_test.go
pkg/planner/core/casetest/index/index_test.go
pkg/planner/core/indexmerge_path_test.go
pkg/planner/core/planbuilder.go
pkg/statistics/handle/autoanalyze/autoanalyze.go
pkg/statistics/handle/autoanalyze/priorityqueue/analysis_job_factory.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler.go
pkg/util/dbterror/ddl_terror.go

Issue Number: ref #59880
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: generalize some vector index logic to columnar index

---

pkg/domain/domain_sysvars.go

Issue Number: close #59949
Change schema cache size take effect immediately, but switch from v2 to v1 take effect after a schema reload.
This cause a bug that during the period when @@tidb_schema_cache_size is set to 0, but the implement have not change to v1, the schame cache hit rate become 0.
When set @@tidb_schema_cache_size to 0, do not change the schema cache capacity.
Tests 
Now the result is expected, there is no data after changing from v2 to v1:
> 
Side effects
Documentation
```release-note
None
```

domain: change @@tidb_schema_cache_size to 0 should not set the capacity to 0

---

pkg/ddl/tests/partition/db_partition_test.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

tests: fix unstable test `TestTruncatePartitionWithGlobalIndex`

---

pkg/privilege/privileges/cache.go

Issue Number: ref #55563
`chunk.Renew` cause more allocations and wastes memory, change the code from `chunk.Renew` to `req.GrowAndReset(1024)`
`strings.Clone` is required in decodeTableRow functions.
Tests 
Modify the code to call `LoadSomeUsers` manually, the database have 2M users and load 1/10 of them.
```
func (e *ShowExec) fetchShowEngines(ctx context.Context) error {
+       fmt.Println("!!!!!!!")
ctx = kv.WithInternalSourceType(ctx, kv.InternalTxnMeta)
-       exec := e.Ctx().GetRestrictedSQLExecutor()
+       // exec := e.Ctx().GetRestrictedSQLExecutor()
+
+       // rows, _, err := exec.ExecRestrictedSQL(ctx, nil, `SELECT * FROM information_schema.engines`)
+       // if err != nil {
+       //      return errors.Trace(err)
+       // }
+       // …
```

privilege: reuse chunk in loadTable function

---

pkg/bindinfo/BUILD.bazel
pkg/bindinfo/binding_operator.go
pkg/bindinfo/binding_operator_test.go

[Problem Summary: planner: refactor some code related to binding
](planner: return error if binding sql is too long)
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: return error if binding sql is too long

---

pkg/expression/aggregation/BUILD.bazel
pkg/expression/aggregation/base_func.go
pkg/expression/aggregation/base_func_test.go
pkg/planner/core/task.go

Issue Number: close #59708
the type infer of `avg(col_decimal_15_2)`:
1. In `plan builder`, call [typeInfer4Avg](https://github.com/pingcap/tidb/blob/62165a41faa800def93a0582dad918ad669ca435/pkg/expression/aggregation/base_func.go#L138), the return type of avg becomes `decimal(19, 6)`
2. In `task.go`, trying to convert normal `avg` to mpp `avg`, which will be spilit to `count() and sum(col_decimal_15_2)`(1 phase) and `sum/count`(2 phase). And the return type of 1 phase `sum(col_decimal_15_2)` is `decimal(41, 6)` because of calling [TypeInfer4AvgSum](https://github.com/pingcap/tidb/blob/62165a41faa800def93a0582dad918ad669ca435/pkg/expression/aggregation/base_func.go#L249)
`decimal(41, 6)` will use Int256 to compute, which is slow. So we need to optimize type infer.
1. …

planner: optimize return type of partial sum for tiflash

---

br/pkg/mock/backend.go
pkg/ddl/BUILD.bazel
pkg/ddl/backfilling_import_cloud.go
pkg/ddl/backfilling_merge_sort.go
pkg/ddl/index.go
pkg/ddl/ingest/engine.go
pkg/ddl/ingest/engine_mgr.go
pkg/lightning/backend/backend.go
pkg/lightning/backend/local/local.go
pkg/lightning/backend/tidb/tidb.go
tests/realtikvtest/addindextest2/global_sort_test.go

Issue Number: ref #57670
See the description of https://github.com/pingcap/tidb/pull/57770
* remove some useless code (`ResetEngine`)
* add a test case to cover the global sort scenario that it can recover from retryable error
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl/ingest: add test for ADD INDEX with global sort recovery from retryable error

---

br/pkg/streamhelper/BUILD.bazel
br/pkg/streamhelper/flush_subscriber.go
br/pkg/streamhelper/subscription_test.go

Issue Number: close #58691
After a subcription connection cut down by `context canceled` or `EOF`, it won't be re-established.
In fact we can reconnect.
Always report the error to upper level and let them decide whether to retry.
Tests 
> 
Side effects
Documentation
```release-note
None
```

streamhelper: don't cut down connection when subscription stream closed

---

pkg/statistics/handle/syncload/stats_syncload.go

Issue Number: ref #60017 
There is no point in retrying the sync load, because there will be other tasks requesting this task at the same time. As long as the subsequent tasks are normal, it will be fine. Too many retries will only cause congestion and delays
but we first reduce it as 1 to observer the changement.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: reduce the max retry count as 1 for sync load

---

DEPS.bzl
go.mod
go.sum
pkg/executor/BUILD.bazel
pkg/executor/set.go

Only enable the ts check for stale reads
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: (release-8.5) validate ts only for stale read

---

DEPS.bzl
executor/BUILD.bazel
executor/set.go
go.mod
go.sum

Only enable the ts check for stale reads
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: (release-7.1) Validate ts only for stale read

---

DEPS.bzl
go.mod
go.sum
pkg/executor/BUILD.bazel
pkg/executor/set.go

Only enable the ts check for stale reads
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: (release-8.1) Validate ts only for stale read

---

br/pkg/backup/client.go

Issue Number:  ref https://github.com/pingcap/tidb/issues/53835
Find region peer will retry 5 minutes which break the integration test 30s exits.
if context is cancelled, find region logic should return immediately.
Tests 
> 
Side effects
Documentation
```release-note
None
```

Backup: Fix excessive retry delays caused by context errors

---

pkg/metrics/distsql.go
pkg/metrics/grafana/tidb.json
pkg/store/copr/coprocessor.go

Issue Number: ref #59990
In TiDB clusters with numerous nodes and high request loads, tidb_distsql_copr_resp_size is monitoring a large amount of data, consider reducing the number of buckets to reduce its data size.
Change the minimum unit from B to KiB
Tests 
After this PR:
> 
Side effects
Documentation
```release-note
None
```

metrics: update distsql_copr_resp_size unit

---

br/pkg/stream/table_mapping.go

Issue Number: close #60024, close #57613
The pitr restore meta kv parsing phase has some issue regarding to writeCF value, and the pitr restore could fail
this PR made it exact same as the rewrite_meta_kv logic to avoid the parsing failure found in e2e test.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix pitr meta kv fail to parse in during table filter code refactor 

---

pkg/ddl/db_test.go
pkg/meta/meta.go

Issue Number: close #59912
We used number order to split subtasks, which is wrong.
Use string order to split subtasks.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: fix incorrect handling IterAllTables

---

pkg/ddl/partition.go
pkg/ddl/tests/partition/multi_domain_test.go
pkg/meta/model/table.go

Issue Number: close #60021 
The dropped partition was not filtered out when reading from the global index during StateWriteOnly, resulting in a rows from the dropped partition could be seen if the Global Index was used, but not if other access paths was used during that DDL State.
Filtering out the dropped partition also for StateWriteOnly
Tests 
> 
Side effects
Documentation
```release-note
During DROP PARTITION StateWriteOnly one could still access rows from the dropped partition through the Global Index.
```

ddl: DROP PARTITION sees a row from a dropped partition in StateDeleteOnly with Global Index

---

pkg/parser/ast/util.go
pkg/parser/ast/util_test.go
pkg/planner/optimize.go
tests/integrationtest/r/session/user_variables.result
tests/integrationtest/t/session/user_variables.test

Issue Number: close #55281
In read-only mode user-defined variables cannot be set with select statements.  You can reproduce this by running:
`set global tidb_super_read_only=1; select @i:=@i+1;`
This is allowed on MySQL.
After reviewing the various code paths that can reach ast.IsReadOnly, I could find no reason this function would need to return false for read-only queries that set user-defined variables. This patch removes the part of ast.IsReadOnly that checks for writes to user-defined variables, which fixes the bug.
Tests 
> 
Side effects
Documentation …

ast: Allow SELECT statements to set user-defined variables in read-only mode.

---

pkg/executor/join/hash_join_spill_helper.go
pkg/executor/join/hash_join_v2.go

Issue Number: close #60052
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix data race in the join.(*hashJoinSpillHelper).generateSpilledValidJoinKey()

---

br/pkg/restore/snap_client/pitr_collector_test.go

Issue Number: close #60051
It is possible to trigger race after closing the fence. 
Added lock to the callbacks. 
Tests 
> It is a test.
Side effects
Documentation
```release-note
None
```

test: fix concurrency issue in pitr_collector_test

---

pkg/disttask/framework/scheduler/scheduler_manager.go
tests/realtikvtest/addindextest1/BUILD.bazel
tests/realtikvtest/addindextest1/disttask_test.go

Issue Number: close #59944
The channel receiver may not receive, then send a signal to the channel, which may get blocked.
Use select-default to discard the signal.
Tests 
> 
Side effects
Documentation
```release-note
fix potential block on DXF scheduler
```

disttask: fix potential block on DXF scheduler

---

br/pkg/gluetidb/glue.go
pkg/domain/domain.go
pkg/meta/meta.go
pkg/planner/core/logical_plans_test.go
pkg/planner/core/mock.go
pkg/session/session.go
pkg/statistics/handle/autoanalyze/autoanalyze.go
pkg/statistics/handle/autoanalyze/priorityqueue/BUILD.bazel
pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler_test.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue_test.go
pkg/statistics/handle/autoanalyze/refresher/refresher.go
pkg/statistics/handle/autoanalyze/refresher/refresher_test.go
pkg/statistics/handle/handle.go
pkg/statistics/handle/handletest/handle_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/57960
In this PR, we used the new API to speed up table iteration during PQ initialization. The duration was reduced from 23 minutes to 1 minute for 3 million tables.
It will use more goroutines to get the table info from TiKV. The concurrency is half of the CPU cores.
Tests 
> 
Side effects
Documentation
```release-note
Accelerating TiDB's initialization of the auto-analyze queue
加速 TiDB 初始化自动分析队列的过程
```

statistics: speed up table iteration during PQ initialization

---

br/tests/lightning_write_limit/config.toml

Issue Number: close #60059
See also:
https://github.com/pingcap/tidb/commit/e92a92f7f4c842af350338080c52a85e30eb41f8#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
https://pkg.go.dev/github.com/docker/go-units?utm_source=godoc
Tests 
> 
Side effects
Documentation
```release-note
None
```

Lightning: testcase avoid using go units.

---

pkg/executor/grant.go
pkg/executor/simple.go
pkg/privilege/privileges/cache.go

Issue Number: close #33174
Previously, `user@''` consider equals to `user@'%'` when performing operations related to set default role.
Tests 
Test link https://github.com/PingCAP-QE/tidb-test/pull/2498
> 
Side effects
Documentation
```release-note
Fix `set default role` failed with empty hostname user.
```

privileges: `user@''` is different with `user@'%'` | tidb-test=pr/2498

---

pkg/domain/domain.go
pkg/workloadlearning/BUILD.bazel
pkg/workloadlearning/cache.go
pkg/workloadlearning/cache_test.go
pkg/workloadlearning/handle.go
pkg/workloadlearning/metrics.go

Issue Number:ref #58131
1. Add a new workload-learning cache worker
2. Implement the read table cost cache logic from workload_values table to memory
The tablecost cache will be called after WorkloadLearningHandle saving the metrics in workload_values table. 
```
wbLearningHandle.HandleReadTableCost(do.InfoSchema())
wbCacheWorker.UpdateTableCostCache()
``` 
This ensures that the cacheworker can update the latest data in memory neither too early nor too late.
Tests 
> 
Side effects
Documentation
```release-note
None
```

workload-learning: Add a workload-learning cache worker

---

pkg/planner/core/exhaust_physical_plans.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: make index join's code about build tableScan and indexScan more clean.

---

pkg/executor/analyze.go
pkg/executor/analyze_worker.go
pkg/executor/test/analyzetest/analyze_test.go
pkg/statistics/handle/cache/statscache.go
pkg/statistics/handle/ddl/subscriber.go
pkg/statistics/handle/globalstats/global_stats.go
pkg/statistics/handle/storage/BUILD.bazel
pkg/statistics/handle/storage/dump_test.go
pkg/statistics/handle/storage/save.go
pkg/statistics/handle/storage/stats_read_writer.go
pkg/statistics/handle/storage/stats_read_writer_test.go
pkg/statistics/handle/storage/update.go
pkg/statistics/handle/types/interfaces.go

Issue Number: close https://github.com/pingcap/tidb/issues/54552
In most cases, this would prevent the stats from being lost on other nodes.
The reason this could happen is that the stats update might be too slow and blocked for more than 3 * lease duration. Once this happens, there is no way to load the stats correctly on other nodes, as we push forward the maximum version from the stats cache.
In this PR, we aim to minimize the chances of the table failing to load after ANALYZE. If such a situation occurs, we will attempt to update the stats version again to ensure that other nodes can read it. This will be done through a very small transaction to ensure the version refresh, which triggers the normal loading process.
If even this recovery mechanism fails, the ANALYZE …

statistics: improve handling for slow stats updates and logging

---

br/pkg/conn/BUILD.bazel
br/pkg/conn/conn.go
br/pkg/task/restore.go
br/tests/br_full_ddl/run.sh
br/tests/br_incremental_ddl/run.sh

Issue Number:  close https://github.com/pingcap/tidb/issues/60105
ref https://github.com/pingcap/tidb/issues/60085
A scan region issue was identified in [pingcap/tidb#60085](https://github.com/pingcap/tidb/issues/60085)
- Temporarily disabled the PD follower handle to ensure that region scanning functions correctly when restoring from a checkpoint.
- Fixed a panic issue caused by a missing nil check during checkpoint removal.
Tests 
> 
Side effects
Documentation
```release-note
None
```

restore: disable pd follower handle

---

pkg/ddl/ddl_test.go
pkg/ddl/schemaver/syncer_nokit_test.go
pkg/disttask/importinto/planner_test.go
pkg/disttask/importinto/scheduler_testkit_test.go
pkg/domain/domain_test.go
pkg/domain/infosync/BUILD.bazel
pkg/domain/infosync/info.go
pkg/domain/infosync/info_test.go
pkg/domain/infosync/mock_info.go
pkg/server/handler/tests/BUILD.bazel
pkg/server/handler/tests/http_handler_test.go
pkg/statistics/handle/autoanalyze/autoanalyze_test.go
pkg/util/disttask/idservice_test.go
tests/realtikvtest/txntest/stale_read_test.go

Issue Number: close #58405
The labels of TiDB are stored within a static structure, meanwhile TiDB have update-label API. Before this PR, the way TiDB handles the mutations of labels have data-race risk.
Refactor the `ServerInfo` into static and dynamic sections and fix the data race by atomic operations.
Tests 
> 
Side effects
Documentation
```release-note
None
```

infosync: refactor server config into dynamic and static sections

---

br/pkg/storage/gcs.go
br/pkg/storage/gcs_test.go

Add "server sent GOAWAY" to retry error list.
See https://stackoverflow.com/questions/45209168/http2-server-sent-goaway-and-closed-the-connection-laststreamid-1999 for details.
Tests 
> 
Side effects
Documentation
```release-note
None
```

objstore: retry on "server sent GOAWAY" http2 error | tidb-test=release-8.1.2

---

br/pkg/storage/gcs.go
br/pkg/storage/gcs_test.go

Issue Number: close #60143
Add "server sent GOAWAY" to retry error list, since gcp support recommends to retry on this error.
And see https://stackoverflow.com/questions/45209168/http2-server-sent-goaway-and-closed-the-connection-laststreamid-1999 for details.
Tests 
> 
Side effects
Documentation
```release-note
None
```

objstore: retry on "server sent GOAWAY" http2 error

---

pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/initstats/load_stats.go
pkg/statistics/handle/initstats/load_stats_page.go

We shouldn’t simply duplicate the same code for both concurrent and non-concurrent init stats.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: enhance concurrency handling in stats initialization to reduce duplication

---

cmd/tidb-server/BUILD.bazel
cmd/tidb-server/main.go
pkg/util/intest/BUILD.bazel
pkg/util/intest/assert.go
pkg/util/intest/assert_common.go
pkg/util/intest/in_unittest.go
pkg/util/intest/no_assert.go
pkg/util/intest/not_in_unittest.go

Issue Number: close #60142
1. Introduca a global variable: EnableInternalCheck
2. Add init() in Intest to inject a failpoint.
3. Enable EnableAssert if EnableInternalCheck is enabled by failpoint.
Tests 
```
export GO_FAILPOINTS="github.com/pingcap/tidb/server/enableTestAPI=return;github.com/pingcap/tidb/pkg/server/enableTestAPI=return;/enableInternalCheck=return(true)"
start tidb
Verify that EnableInternalCheck and InTest are true.
```
> 
Side effects
Documentation
```release-note
None
```

util/intest: support enable internal check by failpoint

---

pkg/executor/test/issuetest/executor_issue_test.go
pkg/executor/test/tiflashtest/tiflash_test.go
pkg/planner/core/physical_plan_test.go
pkg/planner/core/preprocess.go
tests/integrationtest/r/executor/executor.result
tests/integrationtest/r/planner/core/issuetest/planner_issue.result
tests/integrationtest/t/executor/executor.test
tests/integrationtest/t/planner/core/issuetest/planner_issue.test

Issue Number: close #60112
Tests 
> 
Side effects
Documentation
```release-note
Report error when subquery with union/expect/intersect doesn't has an alias, it's compatible with MySQL.
```

planner: report error when subquery doesn't has an alias | tidb-test=pr/2499

---

pkg/disttask/importinto/BUILD.bazel
pkg/disttask/importinto/encode_and_sort_operator.go
pkg/disttask/importinto/encode_and_sort_operator_test.go
pkg/disttask/importinto/task_executor.go
pkg/lightning/backend/external/onefile_writer.go

- previously, our data mem buf block size is aligned to 32MiB, so each row cannot exceed this size, this is the designed behavior. But we meet a case that will have 40MiB+ per row, so we align with current max_entry_size_limit, i.e. 120MiB.
- also set the block size of membuf of writers of merge-sort step to 128MiB which is also the mem limit size
Tests 
> 
Side effects
Documentation
```release-note
None
```

import: adjust data mem buf block size based on max_entry_size_limit | tidb-test=release-8.1.2

---

pkg/util/workloadrepo/BUILD.bazel
pkg/util/workloadrepo/const.go
pkg/util/workloadrepo/snapshot.go
pkg/util/workloadrepo/worker.go
pkg/util/workloadrepo/worker_test.go

Issue Number:  ref #58247
Problem Summary: Serverless TiDB wants a specialized auto-scalable etcd cluster for etcd usages in TiDB, rather than relying on PD. However, moving from PD to the new etcd cluster will also remove all persistent data on PD. We can workaround this by recovering snapID from table.
Also check tidbcloud/tidb-cse#1522
As title.
Tests 
> 
Side effects
Documentation
```release-note
None
```

workloadrepo: try to recover etcd snapID from table

---

pkg/expression/builtin_string.go
pkg/expression/builtin_string_test.go
pkg/expression/builtin_string_vec.go
tests/integrationtest/r/expression/builtin.result
tests/integrationtest/t/expression/builtin.test

Issue Number: close #59447
Problem Summary: In MySQL 8, [as of 8.0.13](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-13.html#mysqld-8-0-13-bug), the `LPAD` and `RPAD` functions now return an empty string if the specified padding string is empty, and the given length is greater than the length of the string to pad. However, TiDB currently returns NULL instead.
* Modify the implementations of `LPAD` and `RPAD` to return an empty string if the specified padding string is empty, and the given length is greater than the length of the string to pad.
* Update the `TestLpad` and `TestRpad` unit tests accordingly.
* Update the `expression/builtin` integration test.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes …

expression: make `LPAD`/`RPAD` return an empty string for an empty padstr | tidb-test=pr/2488

---

lightning/pkg/importer/table_import.go
pkg/lightning/backend/local/engine.go
pkg/lightning/backend/local/engine_test.go
pkg/lightning/config/config.go

Issue Number: close #59947
Make we are using a sufficient default block size. Ref https://github.com/pingcap/tidb/pull/49514
Tests 
> To test the specific issue addressed in this PR, I used a ~1.4TB dataset consisting mostly of duplicate data. Before the fix, memory usage spiked during the ingest phase due to the large index metadata loaded by Pebble, causing OOM kills on a 16c64g VM. With the fix, memory consumption remained stable, staying below 17GB and leading to no disastrous memory spikes.
> 
Side effects
Documentation
```release-note …
```

Lightning: Make sure we are using default block size of 16KB if user does not specify one.

---

pkg/statistics/BUILD.bazel
pkg/statistics/table.go
pkg/statistics/table_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/60104
We should also clone the checked field. Otherwise, the sync load will mistakenly attempt to load the stats of a non-existent index.
Note: This bug only occurs when there are no further writes to the table. Otherwise, the stats item is correctly updated as checked, preventing this issue from happening.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: fix Clone method to include checked field in ColAndIdxExistenceMap

---

br/pkg/stream/rewrite_meta_rawkv.go
br/pkg/stream/table_mapping.go
br/pkg/task/stream.go
br/pkg/utils/schema.go
br/tests/br_pitr_table_filter/run.sh

Issue Number: close #60201
Prevent pitr to restore system table change during log backup,
only restore full snapshot to be consistent with previous version
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix pitr system table inconsistency issue

---

pkg/planner/optimize.go
tests/realtikvtest/pipelineddmltest/pipelineddml_test.go

Issue Number: close #60231 close #60229
https://github.com/pingcap/tidb/pull/34702 says AdviceWarmUp in only an optimization, won't affect the correctness. 
Because 
1. AdviceWarmUp will use pipeline DML flag when creating TS future
2. binding is processed after AdviceWarmUp
3. binding may change the pipeline DML flag
in order to let pipeline DML flag in binding really take effect, I postpone AdviceWarmUp.
Tests 
> 
Side effects
Documentation
```release-note
None
```

optimizer: postpone AdviseWarmup after processing binding

---

pkg/planner/core/plan_cache_param.go
pkg/session/session.go
pkg/util/generatedexpr/BUILD.bazel
pkg/util/generatedexpr/generated_expr.go
pkg/util/parser/BUILD.bazel
pkg/util/parser/parser.go

merge parser's Pool into a global pool
Tests 
> 
Side effects
Documentation
```release-note
None
```

util: unite the parser's Pool

---

pkg/planner/core/casetest/physicalplantest/testdata/plan_suite_out.json
pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/issuetest/BUILD.bazel
pkg/planner/core/issuetest/planner_issue_test.go
tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result
tests/integrationtest/r/planner/core/indexjoin.result

Issue Number: close #59902
in the ```constructIndexJoinInnerSideTaskWithAggCheck```, we forget to transfer the parents stats by the child stats.
Tests 
> 
Side effects
Documentation
```release-note
fix wrong HashAgg estrows for inner operator of index join
修复 index join 的 inner operator 中 HashAgg 估算行数错误的问题
```

planner: fix wrong HashAgg estrows for inner operator of index join

---

pkg/executor/insert_common.go
pkg/executor/insert_test.go
pkg/sessionctx/stmtctx/stmtctx.go
pkg/util/execdetails/execdetails.go

Issue Number: close #59356 
In #54004, some stats' clone operations are removed. However, the removal of clone operation in RegisterStats function introduced new issue:
https://github.com/pingcap/tidb/blob/d13e52ed6e22cc5789bed7c64c861578cd2ed55b/pkg/util/execdetails/execdetails.go#L1462 
Because, for insert operator's stats, it keeps a pointer to the BasicRuntimeStats which is unique for all executors with the same executor_id. For issue 59356, tidb first tries the insert executor, but fails with write conflicts,registering the executor stats in close function. Then it retries, using a new insert executor, while still has a pointer to the registered BasicRuntimeStats. Finally, when the new insert executor closes, it register the stats also, triggering the …

util,executor: Fix incorrect execution info issue of pessimistic lock error

---

pkg/ddl/db_test.go
pkg/table/tables/partition.go

Issue Number: close #60047
When execute `evalBuffer.SetDatums(r...) ` in `locateRangeColumnPartition`，a non-public column may overlap with handle column, which causes locating to a wrong partition.
* How to judge?
1）On the Update Path: partitionedTableUpdateRecord -> locatePartition -> locateRangeColumnPartition, currData and newData both contain writable Columns。
That is to say，if `add column` DDL reach StateWriteOnly phase, updated currData and newData both contain the new added column。
2）While in `locateRangeColumnPartition` method，we get MutRow from t.evalBufferPool, whose Columns are all public, and actually extraHandle column is added at the end(see `initEvalBufferType`)。
* Give an example?
A table like the following:
```
CREATE TABLE t (
a INT, b INT, c …
```

table: use writable columns to avoid columns not match when add column DDL exec parallel with update DML

---

pkg/planner/cardinality/selectivity_test.go
pkg/planner/cardinality/testdata/cardinality_suite_in.json
pkg/planner/cardinality/testdata/cardinality_suite_out.json
pkg/planner/core/find_best_task.go

Issue Number: close #60242
As said in #42060 and the [doc](https://docs.pingcap.com/tidb/stable/system-variables/#tidb_opt_ordering_index_selectivity_threshold-new-in-v700), this variable was originally introduced to control the choice between a "filter index" that satisfies the filter conditions and an "ordering index" that satisfies the `ORDER BY` clause. The allowed range for this variable is `[0,1]`.
Obviously, it's meaningless to choose a "filter index" when the selectivity is 1, which basically means there are no filters. So we made the semantic of this variable "less than". This provides a benefit: when setting it to 0, the behavior is not changed, so we can safely use 0 as the default value.
However, in a recent ticket, we met another case where there were no …

planner: change the semantic of `tidb_opt_ordering_index_selectivity_threshold` from `<` to `<=`

---

pkg/domain/domain.go
pkg/statistics/handle/storage/read.go

Issue Number: ref https://github.com/pingcap/tidb/issues/59939
- Updated logging calls (using StatsSampleLogger and StatsErrVerboseSampleLogger) across histogram loading functions to provide clearer diagnostic messages.
- Added and clarified inline comments to explain when items (table, column, index) are missing due to being dropped after async load is triggered.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: add warnings for missing table, column, and histogram information during async loading

---

planner/core/find_best_task.go
statistics/integration_test.go
statistics/testdata/integration_suite_in.json
statistics/testdata/integration_suite_out.json

Manual cherry-pick of #60255
---
Issue Number: close #60242
As said in #42060 and the [doc](https://docs.pingcap.com/tidb/stable/system-variables/#tidb_opt_ordering_index_selectivity_threshold-new-in-v700), this variable was originally introduced to control the choice between a "filter index" that satisfies the filter conditions and an "ordering index" that satisfies the `ORDER BY` clause. The allowed range for this variable is `[0,1]`.
Obviously, it's meaningless to choose a "filter index" when the selectivity is 1, which basically means there are no filters. So we made the semantic of this variable "less than". This provides a benefit: when setting it to 0, the behavior is not changed, so we can safely use 0 as the default value.
However, in a recent ticket, we met …

planner: change the semantic of `tidb_opt_ordering_index_selectivity_threshold` from `<` to `<=` (#60255)

---

pkg/executor/infoschema_reader.go
pkg/infoschema/test/clustertablestest/tables_test.go

Issue Number: close #25475
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix `NUMERIC_PRECISION` field value in `information_schema.columns` table | tidb-test=pr/2502

---

pkg/disttask/importinto/BUILD.bazel
pkg/disttask/importinto/scheduler.go
pkg/disttask/importinto/scheduler_test.go

Issue Number: ref #59754
previously, we don't retry for scheduler error, but we might meet them,  like the one in the issue
Tests 
> 
Side effects
Documentation
```release-note
None
```

importinto: check retryable schedule error

---

pkg/executor/BUILD.bazel
pkg/executor/adapter.go
pkg/executor/builder.go
pkg/executor/point_get.go
pkg/executor/prepared_test.go

Issue Number: close #57528 
In #57528, point get sysbench started to run with execution info set on, and point get executors with execution info will be stored in plan cache. Then we turned off the execution info system variable. However, we can get the cached executors with execution info in a session which execution info is set off. This is caused due to incomplete re-initialization of point get executor: the stats field should be reset to nil when a cached point get executor is reused in an "execution-info-off" session. 
Tests 
Do manually test as #57528 described, ensure no errors happen
> 
Side effects
Documentation …

executor: Refact pointGetExecutor init function to ensure member fields are correctly reset

---

br/pkg/storage/ks3.go
br/pkg/storage/s3.go
br/pkg/storage/s3_test.go
pkg/ddl/backfilling.go
pkg/ddl/backfilling_test.go
pkg/ddl/ingest/BUILD.bazel
pkg/ddl/ingest/integration_test.go
pkg/lightning/backend/external/engine.go
pkg/lightning/common/retry.go
pkg/util/dbterror/ddl_terror.go
tests/realtikvtest/addindextest4/failure_test.go
tests/realtikvtest/importintotest4/global_sort_test.go

This is an manual cherry-pick of #59694 #59659 #59767
Issue Number: ref https://github.com/pingcap/tidb/issues/50451 https://github.com/pingcap/tidb/issues/59650 https://github.com/pingcap/tidb/issues/59701
This is a merged PR for 3 PR to be cherry-picked to hotfix branch
See corresponding PR for detail of what fixed and how it is fixed.
```
commit c5ea2e79b25e5f35bb8efd2da9c23621dfb330f8 (HEAD -> release-8.5-20250401-v8.5.1, origin/test-import, test-import)
Author: D3Hunter <jujj603@gmail.com>
Date:   Mon Feb 24 10:17:48 2025 +0800
objstore: fix read position on retry when reading a file range using s3 (#59694)
close pingcap/tidb#50451
commit d74a0aff7b1e873cd484fd08664def3619fda69d
Author: tangenta <tangenta@126.com>
Date:   Fri Feb 28 00:58:21 2025 +0800
ddl: refine …
```

*: cherry-pick #59694 #59659 #59767 to release 8.5.1 hotfix

---

pkg/sessionctx/variable/BUILD.bazel
pkg/sessionctx/variable/session.go
pkg/sessionctx/variable/sysvar_test.go

Currently, `NewSessionVars` does not set default value for `UseHashJoinV2`, so for internal sqls, it will always use hash join v1, which is not expected.
Tests 
> 
Side effects
Documentation
```release-note
None
```

session: set default value for hash join v2 in NewSessionVars

---

pkg/executor/importer/import.go
pkg/executor/importer/import_test.go
tests/realtikvtest/importintotest3/from_server_test.go
tests/realtikvtest/importintotest4/global_sort_test.go

Issue Number: close #60361
disable switch to `import mode` when using global sort, no change for local sort
Tests 
> 
Side effects
Documentation
```release-note
None
```

importinto: disable switching to 'import mode' when global sort

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/index_join_path.go

this is a split pull request from the complete one: https://github.com/pingcap/tidb/pull/60204
in this pull request, we add 3 functions:
* `getBestIndexJoinPathResultByProp` which is changed from `getBestIndexJoinPathResult`, which we don't give them the operator join and related info, because all elements should be passed down with indexJoinProp in our refactor, so I change the parameter to receive indexJoinProp, besides that, the basic detect whether the index path can be valid by this kind of indexJoinProp is still the same by call indexJoinPathBuild with a wrapped structure as indexJoinPathInfo as before.
* `buildDataSource2TableScanByIndexJoinProp` which is changed from `buildIndexJoinInner2TableScan`, …

planner: add tableScan and indexScan build portal by feeling indexJoinProp.

---

pkg/statistics/asyncload/BUILD.bazel
pkg/statistics/asyncload/async_load_test.go
pkg/statistics/handle/storage/read.go

Issue Number: close https://github.com/pingcap/tidb/issues/60247
If the stats item or table information cannot be found, we should not attempt to load the statistics again, as this could lead to an infinite loop. Therefore, in this PR, I have removed the invalid items from loadNeededColumnHistograms and loadNeededIndexHistograms.
Additionally, if the index has been dropped, we shouldn't return an error; we can simply delete it from the load list.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: remove invalid histogram items in loadNeededColumnHistograms and loadNeededIndexHistograms

---

Makefile
pkg/config/store.go

Issue Number: ref #60418
- see the issue, and comment in the code, we use a compile variable to determine current binary type
Tests 
change the code to print the value of `IsCloudStore`
use `make ng_server`, and run, check it's true
use `make sever`, run and check it's false
> 
Side effects
Documentation
```release-note
None
```

*: add method to distinguish storage and build separate binary for NG tidb

---

pkg/disttask/framework/mock/plan_mock.go
pkg/disttask/framework/planner/BUILD.bazel
pkg/disttask/framework/planner/plan.go
pkg/disttask/framework/planner/planner.go
pkg/disttask/framework/planner/planner_test.go
pkg/disttask/importinto/job.go
pkg/disttask/importinto/job_testkit_test.go
pkg/disttask/importinto/planner.go
pkg/disttask/importinto/scheduler.go
pkg/executor/import_into.go
pkg/executor/importer/import.go
pkg/executor/show.go
pkg/executor/show_test.go
tests/realtikvtest/importintotest4/BUILD.bazel
tests/realtikvtest/importintotest4/manual_recovery_test.go

Issue Number: ref #59640 
after https://github.com/pingcap/tidb/pull/59641, import into can integrate it.
for the step to do `manual recovery`, see the example in https://github.com/pingcap/tidb/pull/59599
Tests 
> 
Side effects
Documentation
```release-note
None
```

import: add a hidden option to enable manual recover for debug purpose

---

pkg/executor/check_table_index.go
pkg/util/wait_group_wrapper.go

Using `wg.RunWithRecover` instead of `wg.Run` and `util.WithRecovery`
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: tiny cleanup for `WithRecovery`

---

pkg/util/workloadrepo/worker_test.go

There are other issues related to #60200 in the Workload Repository tests.
This patch fixes concurrency issues in setupWorker(), TestRecoverSnapID, and TestOwnerRandomDown.
Tests 
> 
Side effects
Documentation
```release-note
None
```

workloadrepo: Fix other data race issues in the tests.

---

pkg/statistics/handle/storage/BUILD.bazel
pkg/statistics/handle/storage/save.go
tests/integrationtest/r/statistics/handle.result
tests/integrationtest/t/statistics/handle.test

Issue Number: close #60194
Fix the issue that the `HandleDDLEvent` cannot handle timezone issues properly.
Tests 
> 
Documentation
```release-note
None
```

stats: use `GetColOriginDefaultValue` to get default value of a column

---

pkg/planner/core/preprocess.go
pkg/planner/core/preprocess_test.go

Issue Number: close #45674
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add `inCreateOrDropTable` flag for `alter table stmt` when it's in prepare stmt

---

pkg/session/syssession/BUILD.bazel
pkg/session/syssession/pool_test.go
pkg/session/syssession/session.go
pkg/session/syssession/session_test.go

Issue Number: ref #60115
Consider the below case:
```go 
var pool *AdvancedSessionPool
se, err := pool.Get()
go func() {
se.ExecuteInternal(...)
}()
go func() {
se.Close()
}()
```
If the above two operations are executed in parallel, a data race may occur in the current implementation.
Though it is unexpected, we still want to reduce unnecessary data race here.
Postphone the close of the session when `inUse` decreased to `0` if `se.Close()` is called but found it is still in use.
Tests 
> 
Side effects
Documentation
```release-note
None
```

session: A safer way to close session from the pool

---

br/pkg/streamhelper/advancer.go
br/pkg/streamhelper/basic_lib_for_test.go

Issue Number: close #58627
test will fail if when try to advance the new TS is less than hardcoded 5, make it 0
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix flaky test TestGCServiceSafePoint

---

pkg/planner/core/base/task_base.go
pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/find_best_task.go

this is a split pull request from the complete one: https://github.com/pingcap/tidb/pull/60204
* `enumerateIndexJoinByOuterIdx` is quite similar to `getIndexJoinByOuterIdx`, while inside we do not assert the inner plan's pattern and build their physical out, but pushing down the indexJoinProp instead and return a static(temporary) physical index join out directly.
* `tryToEnumerateIndexJoin` logic is quite similar to `tryToGetIndexJoin`, while inside we do not build the inner physical plan out, but pushing down the indexJoinProp instead and return a static(temporary) physical index join out directly.
* `suitLogicalJoinHint` logic is quite similar to `handleForceIndexJoinHints`; the later one will prune other …

planner: add enumeration of index join with indexJoinProp pushed down to inner plan.

---

pkg/executor/join/hash_join_base.go
pkg/executor/join/hash_join_v2.go

Issue Number: close #60466
Described in #60466
The root cause is when build meet error, the hash table is not build, and in `scanRowTableAfterProbeDone` it will try to access hash table, which will cause the panic
This fix avoid scanRowTable if build meet error
Tests 
after this pr, there is no panic log in tidb.log
> 
Side effects
Documentation
```release-note
None
```

executor: don't scanRowTable if build stage meet error

---

pkg/config/config.go
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/handletest/initstats/load_stats_test.go
pkg/statistics/handle/handletest/statstest/stats_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/60206, close https://github.com/pingcap/tidb/issues/60138
The current default value is true, as we believe it makes sense to initialize stats concurrently by default. The reasons are as follows:
1. It only runs once when the TiDB node starts.
2. For clusters with a large number of tables, single-threaded stats initialization is too slow. See https://github.com/pingcap/tidb/issues/60138
4. There is no need to expose this implementation detail to users anymore.
So this PR is to deprecate this configuration and initialize stats concurrently by default.
Tests 
> 
Side effects
Documentation …

config: deprecate ConcurrentlyInitStats and make it always enabled by default

---

pkg/lightning/backend/external/engine.go
pkg/lightning/backend/external/engine_test.go
pkg/lightning/backend/external/file.go
pkg/lightning/backend/external/file_test.go
pkg/lightning/backend/external/iter_test.go
pkg/lightning/backend/external/merge_v2.go
pkg/lightning/backend/external/onefile_writer.go
pkg/lightning/backend/external/onefile_writer_test.go
pkg/lightning/backend/external/reader.go
pkg/lightning/backend/external/reader_test.go
pkg/lightning/backend/external/testutil.go
pkg/lightning/backend/external/writer.go
pkg/lightning/backend/external/writer_test.go

Issue Number: ref #48779
replace key and value slice with kvPair, refactor KV store
Tests 
> 
Side effects
Documentation
```release-note
None
```

globalsort: replace key and value slice with kvPair 

---

pkg/bindinfo/utils.go
pkg/planner/core/plan_cache_param.go
pkg/session/session.go
pkg/util/generatedexpr/generated_expr.go
pkg/util/parser/parser.go

Simple fix to rename `DestoryParser` to `DestroyParser` in the util package.
Issue Number: close #60493
Problem Summary: fix typo
Tests 
> 
Side effects
Documentation
```release-note
None
```

util: fix typo in `DestroyParser` function name

---

br/cmd/br/backup.go
br/pkg/task/common.go
br/pkg/task/common_test.go
pkg/executor/brie.go
pkg/executor/brie_test.go

Issue Number: close #60329
Turn off both backup and restore checksum by default 
Default turned on by int test
Tests 
> 
Side effects
Documentation
```release-note
We previously turned off backup checksum by default and this PR turns off restore checksum by default as well as we think it's resource intensive in production. User can still turn it on by enabling the flag explicitly. 
```

br: set default restore checksum to false

---

pkg/session/syssession/BUILD.bazel
pkg/session/syssession/pool_test.go
pkg/session/syssession/session.go
pkg/session/syssession/session_test.go

Issue Number: ref #60115
Consider below case:
```go
pool := NewAdvancedSessionPool(256, factory);
s, err := pool.Get()
// handle error ...
go func() {
rs, err := s.ExecuteInternal(ctx, "select * from t");
// handle result
}()
go func() {
rs, err := s.ExecuteInternal(ctx, "select * from t");
// handle result
}()
```
The above two statements are executed concurrently which is not expected and may cause data race. It's better to deny the second execution and return an error instead.
This PR adds some checks of the concurrency of thread-unsafe calls. When one thread-unsafe operation is ongoing and another operation (also thread-unsafe) begins, the latter one will return an error.
Tests 
> 
Side effects
Documentation …

session: syssession checks the concurrency of thread-unsafe calls

---

pkg/ddl/backfilling_operators.go
pkg/ddl/backfilling_read_index.go
pkg/disttask/importinto/encode_and_sort_operator.go
pkg/lightning/backend/external/BUILD.bazel
pkg/lightning/backend/external/engine.go
pkg/lightning/backend/external/writer.go

Issue Number: ref https://github.com/pingcap/tidb/issues/60418
encode keyspace when writing to external storage
Tests 
```
tiup playground:nightly nightly --mode=tidb-cse \
--db.binpath /DATA/disk1/gmhdbjd/code/tidb/bin/tidb-server --db.config /DATA/disk1/gmhdbjd/environment/cse/tidb.toml \
--kv.binpath /DATA/disk1/gmhdbjd/code/cloud-storage-engine/target/debug/tikv-server \
--tiflash 0
mysql> use test;
mysql> create table t(id int);
Query OK, 0 rows affected (0.07 sec)
mysql> SET GLOBAL tidb_cloud_storage_uri = 's3://sort?access-key=minioadmin&secret-access-ke
y=minioadmin&endpoint=http://10.2.4.3:9000';
mysql> IMPORT INTO t FROM 's3://data/test.csv?access-key=minioadmin&secret-access-key=minioa …
```

globalsort: encode keyspace when writing to external storage

---

Makefile
Makefile.common
pkg/util/printer/printer.go

Tests 
```shell
➜  tidb git:(build-option) ✗ NEXT_GEN=1 make server
➜  tidb git:(build-option) ✗ bin/tidb-server -V
Release Version: v9.0.0-alpha-506-gc7d7a967f4-dirty
Edition: Community
Git Commit Hash: c7d7a967f4833a3989d5c98d37d26c6c6dda7b93
Git Branch: build-option
UTC Build Time: 2025-04-11 09:19:10
GoVersion: go1.23.8
Next Generation
➜  tidb git:(build-option) ✗ make server
➜  tidb git:(build-option) ✗ bin/tidb-server -V
Release Version: v9.0.0-alpha-506-gc7d7a967f4-dirty
Edition: Community
Git Commit Hash: c7d7a967f4833a3989d5c98d37d26c6c6dda7b93
Git Branch: build-option
UTC Build Time: 2025-04-11 09:21:46
GoVersion: go1.23.8
Check Table Before Drop: …
```

build: use makefile flag to control next gen build

---

pkg/planner/core/point_get_plan.go
pkg/server/tests/commontest/tidb_test.go

Issue Number: close #60523 
Some branches of `BatchGet` don't convert the type of parameters, and make it fail to select correct rows. Some branches are good. Ref https://github.com/pingcap/tidb/pull/32534
1. Remove unused `pairs`.
2. Set the `values` to be the result of `getPointGetValue`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix the issue that the type of `BatchGet` with multiple columns is incorrect

---

pkg/planner/core/physical_plan_test.go
pkg/planner/core/resolve_indices.go
pkg/planner/property/physical_property.go

Issue Number: close #60517
Described in #60517
Use deep copy instead of shallow copy in `PhysicalExchangeSender::ResolveIndicesItself`
Tests 
> 
Side effects
Documentation
```release-note
Fix a bug that will cause TiFlash crash or return wrong query result
```

planner: fix bug in `PhysicalExchangeSender::ResolveIndicesItself`

---

pkg/planner/core/point_get_plan.go
pkg/server/tests/tidb_test.go

Issue Number: close #60523 
Some branches of `BatchGet` don't convert the type of parameters, and make it fail to select correct rows. Some branches are good. Ref https://github.com/pingcap/tidb/pull/32534
1. Remove unused `pairs`.
2. Set the `values` to be the result of `getPointGetValue`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix the issue that the type of BatchGet with multiple columns is incorrect (hotfix branch)

---

pkg/executor/adapter.go
pkg/resourcegroup/runaway/checker.go

Issue Number: close #60404
Run the corresponding actions in `BeforeCopRequest` once it's marked by `IdentifyInRunawaySettings`.
Tests 
```release-note
None
```

runaway: fix the issue where COOLDOWN/SWITCH_GROUP can't be triggered

---

pkg/statistics/handle/handletest/BUILD.bazel
pkg/statistics/handle/handletest/handle_test.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/storage/save.go
pkg/types/datum.go

Issue Number: close #59759 
The stats logic relies on the behavior that type conversion from A to Blob to A is still equal to the original value. However, it's not true for `BIT` after https://github.com/pingcap/tidb/pull/57303.
Add an extra function to handle the load of `BLOB` bound specially. It'll not affect the behavior of any expression, but only modify the stats part.
BTW, I add some test assertion, because I don't know in which case the `BIT` cannot be formatted into an integer. Maybe never.
Tests 
> 
```release-note
Fix the issue that …
```

stats: use an alternative function to read the bound from `BLOB` stored in `mysql.stats_buckets`. | tidb-test=pr/2503

---

br/pkg/restore/snap_client/import.go
br/pkg/restore/utils/BUILD.bazel
br/pkg/restore/utils/rewrite_rule.go
br/pkg/restore/utils/rewrite_rule_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/60577
- As issue described.
1. The RewriteRules (specifically tableRules) are now handled after the data copy process.
2. This ensures that different goroutines apply the correct start_ts when restoring entries, avoiding inconsistencies caused by early binding of rewrite rules.
Tests 
> 
Side effects
Documentation
```release-note
None
```

compacted log restore: solve the race of rule.

---

pkg/ddl/backfilling_operators.go
pkg/executor/insert.go
pkg/executor/insert_common.go
pkg/executor/replace.go
pkg/table/tables/index.go
tests/realtikvtest/addindextest3/ingest_test.go

Issue Number: close #60339
Problem Summary: See https://github.com/pingcap/tidb/issues/60339#issuecomment-2765273746
Always append temp index values during DML execution for unique indexes.
Tests 
> 
Side effects
Documentation
```release-note
None
```

tables: always append temp index values for unique index

---

pkg/executor/adapter.go

Issue Number: close #60604
Problem Summary: see #60604
The fast plan check is now performed at the very beginning of observeStmtBeginForTopSQL. This change skips the expensive GetPlanDigest call when TopSQL is disabled and the execution plan is a fast path, since point gets return early and the plan digest is only cached without further use.
For this optimization to take effect, TopSQL, slow log, and statement summary must be disabled.
Tests 
> 
before:
after (no `GetPlanDigest` found in flame graph):
in our special edition of TiDB, sysbench point select QPS can have 2~3% increment
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-st …

topsql: move fast plan check to beginning of observeStmtBeginForTopSQL when disable top sql

---

pkg/planner/core/casetest/tpch/BUILD.bazel
pkg/planner/core/casetest/tpch/testdata/tpch_suite_in.json
pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json
pkg/planner/core/casetest/tpch/tpch_test.go
pkg/planner/core/physical_plans.go
pkg/planner/core/task.go

Issue Number: close #60407
caused by https://github.com/pingcap/tidb/pull/57417
because `NeedMPPExchangeByEquivalence` will change the hash partitioning information. Having different numbers of MPP partitions in the child nodes of a join can lead to invalid tasks, which ultimately result in incorrect plan.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix doesn't push down hash join to tiflash

---

pkg/metrics/grafana/overview.json
pkg/metrics/grafana/performance_overview.json
pkg/metrics/grafana/tidb.json

Issue Number: close #60535
Previously, the connection count panel doesn't have resource group name:
After this PR, it should have a resource group name:
Apply a similar change to https://github.com/pingcap/tidb/pull/51996. In https://github.com/pingcap/tidb/pull/51996 I forgot to modify the "tidb" page :facepalm: .
Tests 
> 
Modify the grafana configuration, and you'll see the result.
Side effects
Documentation
```release-note
None
```

grafana: fix the connection count panel in "tidb" page

---

pkg/statistics/asyncload/BUILD.bazel
pkg/statistics/asyncload/async_load_test.go
pkg/statistics/handle/storage/read.go

Issue Number: close https://github.com/pingcap/tidb/issues/60598
1. Use defer statement to remove the redundant calls to AsyncLoadHistogramNeededItems.Delete(col)
throughout the loadNeededColumnHistograms function. 
2. Use defer statement to remove the redundant calls to AsyncLoadHistogramNeededItems.Delete(idx)
throughout the loadNeededIndexHistograms function. 
This change ensures cleanup happens
exactly once regardless of which path the function takes, making the code more maintainable
and less error-prone when adding new exit paths in the future.
I discussed this behavior with @terry1purcell and @time-and-fate. We all agreed that we should stop retrying to load the statistics after a failure, because the sync load process already has a retry mechanism. There’s no need …

statistics: Simplify histogram async load with defer cleanup

---

pkg/planner/core/memtable_infoschema_extractor.go
tests/integrationtest/r/executor/infoschema_reader.result
tests/integrationtest/t/executor/infoschema_reader.test

Issue Number: close #60593
Previous sorting impl is problematic.
The original code mistakenly swapped the elements of `tableSlice` manually during sorting, causing it to be out of sync with `schemaSlice`. By merging the data and sorting them uniformly, the order consistency of the two is ensured, eliminating the data misalignment problem caused by manual swapping.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix schema-table inconsistent issue in `IS.tables`

---

pkg/ddl/job_scheduler.go
pkg/ddl/util/util.go

Issue Number: ref #60611 
This PR uses a new context with deadline to query etcd delete API. Thus, it prevents system stuck when the etcd request meets a timeout.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue of cleanMDLInfo getting stuck due to etcd delete API timeout.
```

ddl: add deadline for cleanMDLInfo etcd operation

---

pkg/planner/core/planbuilder.go
pkg/util/workloadrepo/BUILD.bazel
pkg/util/workloadrepo/worker_test.go

The "ADMIN CREATE WORKLOAD SNAPSHOT" command does not currently require that the user have any privileges.
This patch will make "SUPER" required for users to initiate a manual workload repository snapshots.
Tests 
> 
Side effects
Documentation
```release-note
None
```

workloadrepo: Add permission checks to workload repo's ADMIN command.

---

errors.toml
pkg/lightning/backend/local/region_job.go
pkg/lightning/backend/local/region_job_test.go
pkg/lightning/common/errors.go
pkg/lightning/common/retry_test.go
tests/realtikvtest/importintotest2/from_select_test.go

Issue Number: close #60678
add a named `ErrKVDiskFull` and avoid retry on it
Tests 
> 
Side effects
Documentation
```release-note
None
```

localbackend: fix retry on ingest err 'disk full'

---

pkg/planner/core/casetest/index/index_test.go
pkg/planner/core/casetest/index/testdata/index_range_in.json
pkg/planner/core/casetest/index/testdata/index_range_out.json
pkg/util/ranger/types.go
pkg/util/ranger/types_test.go

Issue Number: close #60556
Current logic of range intersection is broken for a corner case like [5,5] and (5,+inf) where the intersection should be empty.
The logic of considering lower/upper bounds with open/cloxsed intervals is bot working for this case. 
An example is shown below. 
```
create table t (a int, b int, key ab(a, b));
insert into t values (100, 500);
mysql> set @@tidb_opt_fix_control = "54337:OFF";
mysql> select 1 from t where ((a>100) or (a=100 and b>0)) and ((a<100) or (a=100 and b<10));
Empty set (0.00 sec)
mysql> set @@tidb_opt_fix_control = "54337:ON";
Query OK, 0 rows affected (0.00 sec)
mysql> select 1 from t where ((a>100) or (a=100 and b>0)) and ((a<100) or (a=100 and b<10));
+---+
| 1 |
+---+
| 1 |
| 1 |
+---+
```
The fix is to simplify the code that:
- extend …

planner: Fix issue #60556: Simplify Range Intersection Logic

---

pkg/planner/core/expression_rewriter.go
pkg/planner/core/optimizer.go
pkg/planner/core/tests/subquery/BUILD.bazel
pkg/planner/core/tests/subquery/main_test.go
pkg/planner/core/tests/subquery/subquery_test.go
pkg/util/collate/collate.go

Issue Number: close #60701
1、 latin1_bin, utf8mb4_bin, utf8_bin should be the same collate which has the same comparison method. 
2、 merge the same code in the expressionRewriter.
Tests 
> 
Side effects
Documentation
```release-note
collate: latin1_bin has the same collate with utf8mb4_bin,utf8_bin
collate: latin1_bin   与 utf8mb4_bin, utf8_bin 的比较方式相同
```

collate: latin1_bin has the same collate with utf8mb4_bin,utf8_bin

---

errors.toml
pkg/lightning/backend/local/job_worker.go
pkg/lightning/backend/local/job_worker_test.go
pkg/lightning/backend/local/local_test.go
pkg/lightning/backend/local/region_job.go
pkg/lightning/backend/local/region_job_test.go
pkg/lightning/common/errors.go

- split previous `convertStageOnIngestError` into `convertPBError2Error` and `getNextStageOnIngestError`
- unify job stage transition during ingest in `regionJobBaseWorker.runJob`
Tests 
> 
Side effects
Documentation
```release-note
None
```

localbackend: unify job stage transition during ingest | tidb-test=ccf9f5de6817ed2e54c18f2c1757056d2c8b4e4c

---

br/metrics/grafana/br.json

Issue Number: close #60212 
fix a promql syntax issue in backup&restore panel. As a workaround, please goto tikv panel to check br related metrics.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix a PromQL syntax error

---

pkg/statistics/handle/globalstats/global_stats_async.go
pkg/statistics/histogram.go

Issue Number: ref https://github.com/pingcap/tidb/issues/60570
See https://github.com/pingcap/tidb/pull/56676#pullrequestreview-2778865430
So, in this PR, I did a post-merge update.
Clarified the conditions under which empty histograms and TopN records occur, emphasizing the impact of unprocessed DDL events and the absence of indexes or keys.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: improve comments for empty histogram handling

---

pkg/meta/model/index.go
pkg/parser/ast/model.go

Issue Number: ref https://github.com/pingcap/tidb/issues/54245
In https://github.com/pingcap/tidb/pull/60663 we wrongly changed the Tp value of a vector index from HNSW=5 to HNSW=7. This is wrong, because tp is persisted in schema and also used in TiFlash.
This mistake is discovered by TiFlash integration test.
This PR reverts back Tp from 7 to 5. Only the code name changes (HNSW=5 -> Vector=5), and this is compatible.
Tests 
> 
Side effects
Documentation
```release-note
None
```

meta: Fix vector incompatibility with old version and TiFlash

---

pkg/planner/core/operator/logicalop/logical_join.go
tests/integrationtest/r/planner/core/issuetest/planner_issue.result
tests/integrationtest/t/planner/core/issuetest/planner_issue.test

Issue Number: close #60692
As said in the issue, sometimes the `FullSchema` may contain outdated `Column`s after the projection elimination. 
We should have fixed the `FullSchema`, but considering the long-standing problems in schema maintenance and column pruning in tidb, we can't make sure we won't introduce any new risk.
This PR is likely to be cherry-picked to the LTS version quickly. So it's better to just restore the previous checking logic, i.e., use the `Schema()` to do the check.
Add back what's been removed in #51057 in `(*LogicalJoin).ExtractUsedCols()`.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/releas …

planner: add back children's `Schema` when checking `LogicalJoin`'s used columns in column pruning

---

pkg/util/topsql/reporter/pubsub.go

Issue Number: close #60646 
Problem Summary: as title, use `WithCancelCause` to return error.
Tests 
> 
Side effects
Documentation
```release-note
None
```

topsql: fix a possible race

---

pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler.go
pkg/statistics/handle/ddl/BUILD.bazel
pkg/statistics/handle/ddl/ddl.go
pkg/statistics/handle/ddl/ddl_test.go
pkg/statistics/handle/ddl/subscriber.go

Issue Number: close https://github.com/pingcap/tidb/issues/60729
We shouldn't require this schema name since it's only used for logging purposes.
In this PR, I’ve made it optional and added a log message in case it’s not found.
Tests 
> 
Side effects
Documentation
```release-note
消除 TiDB 在处理 exchange partition 和 truncate partition 事件时可能遇到的无效日志
Eliminate invalid logs that TiDB may encounter when processing exchange partition and truncate partition DDL events
```

statistics: log schema not found for table in updateGlobalTableStats functions

---

pkg/planner/core/logical_plan_builder.go
tests/integrationtest/r/executor/executor.result
tests/integrationtest/t/executor/executor.test

Issue Number: close #60798
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix panic when execute `select 1 for update`

---

Makefile

Issue Number: close #60814
We want to support getting coverage information on our integration tests.
To do it in GoLang, we just need to add a build flag -cover.
Our internal building platform uses make server to build the image.
So we must let make server build the coverage image if we want.
Tests 
``` 
➜  tidb git:(build_cover) make server
CGO_ENABLED=1  GO111MODULE=on go build -tags codes   -ldflags '-X "github.com/pingcap/tidb/pkg/parser/mysql.TiDBReleaseVersion=v9.0.0-alpha-619-g18f3b949e8" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBBuildTS=2025-04-24 12:25:44" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitHash=18f3b949e8d89b62dd376decaac87ea8e1adcee7" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitBranch=build_cover" -X …
```

*: support building coverage image

---

DEPS.bzl
dumpling/log/BUILD.bazel
dumpling/log/log_test.go
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/60689
ref https://github.com/pingcap/log/pull/42 
- upgrade log dependency, so InitAppLogger will return error if no permission
Tests 
> 
Side effects
Documentation
```release-note
None
```

dumpling: return error if init log file failed

---

pkg/planner/core/expression_rewriter.go
pkg/planner/core/logical_plan_builder.go
tests/integrationtest/r/planner/core/casetest/predicate_simplification.result
tests/integrationtest/r/planner/core/casetest/rule/rule_join_reorder.result

Issue Number: close https://github.com/pingcap/tidb/issues/60608
* resolve group by should use the full schema if any
* rewrite group by item should use the full schema if any
* build selection converted to table dual should use full schema if any
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: use full schema to resolve and rewrite group by item and to build table dual's schema in building where clause | tidb-test=pr/2508

---

pkg/ddl/BUILD.bazel
pkg/ddl/backfilling_operators.go
pkg/disttask/importinto/BUILD.bazel
pkg/disttask/importinto/encode_and_sort_operator.go
pkg/disttask/importinto/encode_and_sort_operator_test.go
pkg/disttask/importinto/task_executor.go
pkg/lightning/backend/external/writer.go
pkg/lightning/backend/external/writer_test.go

Issue Number: ref #59508
Same as #59518, avoid alignment when the aligned size >= 1.1 * calculated-buf-size.
Tests 
Adding 64 indexes:
> 
Side effects
Documentation
```release-note
None
```

ddl: fix OOM issue when adding many indexes

---

br/pkg/restore/split/BUILD.bazel
br/pkg/restore/split/client.go
br/pkg/restore/split/client_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/60077
Tests 
> 
Side effects
Documentation
```release-note
None
```

lightning: added retry times and two new retry reasons | tidb-test=release-8.1.2

---

pkg/executor/BUILD.bazel
pkg/executor/adapter.go
pkg/util/metricsutil/BUILD.bazel
pkg/util/metricsutil/common.go

Issue Number: ref #60864 Doesn't close this issue, keep it to track possible keyspace_id/keyspace_name logic changes, since it is not settle down now.
Currently, we assume global unique keyspace_id is passed as keyspace_name config for next gen tidb. Thus, for next gen, we can use the keyspace_name directly as keyspace_id now. 
Tests 
There is already slow_log test covering keyspace_name/keyspace_id.
Hack code to set keyspace_name to "987654321", hack code because just setting tidb config's keyspace_name value doesn't work(pd can't find responding keyspace_id). Then check slow log and grafana：
> 
Side effects
Documentation …

*: Support metrics and slowlog with keyspace info for next gen

---

pkg/ingestor/engineapi/engine.go
pkg/lightning/backend/external/file.go
pkg/lightning/backend/external/kv_reader.go
pkg/lightning/backend/external/onefile_writer.go
pkg/lightning/backend/external/writer.go
pkg/lightning/backend/external/writer_test.go
pkg/lightning/membuf/buffer.go
pkg/lightning/membuf/buffer_test.go

Issue Number: ref #60621 
implement `record` and `remove` for writer
Tests 
> 
Side effects
Documentation
```release-note
None
```

globalsort: support onDup param for writer

---

pkg/ddl/backfilling.go
pkg/ddl/index.go
pkg/ddl/index_change_test.go
pkg/ddl/job_worker.go
pkg/ddl/modify_column.go
pkg/ddl/multi_schema_change.go
pkg/ddl/multi_schema_change_test.go
pkg/ddl/partition.go
pkg/ddl/reorg.go

Issue Number: close https://github.com/pingcap/tidb/issues/60145
https://github.com/pingcap/tidb/pull/56404 introduced the step context for each step of a DDL job. `runReorgJob` is changed to a blocking implementation, resulting in the inability to update job's row count.
This PR returns `dbterror.ErrWaitReorgTimeout` periodically to let the routine of `runJobOneStep` update job's row count. It also manages `stepCtx` carefully to avoid premature cancelling.
Tests 
The previous behavior was to run one job step and then get stuck inside.
Now the behavior is that it exits periodically, so there are many run one job steps, and the job row count is updated.
```
[2025/04/25 11:14:56.185 +08:00] [INFO] [job_worker.go:816] ["run one job step"] [category=ddl] [jobID=129] …
```

ddl: update row count periodically when running reorg job

---

pkg/sessionctx/variable/BUILD.bazel
pkg/sessionctx/variable/error.go
pkg/sessionctx/variable/nextgen_test.go
pkg/sessionctx/variable/sysvar.go
pkg/store/driver/txn/BUILD.bazel
pkg/store/driver/txn/txn_driver.go

Issue Number: ref #60697
Problem Summary: fair locking is incompatible with tikv next‑gen.
disable it in next-gen build
Tests 
> 
Side effects
Documentation
```release-note
None
```

sessionctx: disable fair locking in next-gen

---

pkg/metrics/grafana/tidb_resource_control.json
pkg/metrics/grafana/tidb_resource_control.jsonnet

Issue Number: close #60640
- Change the y-axis format from 'short' to 's'.
- Also remove the redundant group by condition of 'Total KV Request Count'
Tests 
> 
Side effects
Documentation
```release-note
None
```

metrics: fix the y-axis of Kv Request Duration in Resource Control page

---

br/pkg/storage/memstore.go
pkg/disttask/importinto/planner_test.go
pkg/lightning/backend/external/bench_test.go
pkg/lightning/backend/external/byte_reader.go
pkg/lightning/backend/external/byte_reader_test.go
pkg/lightning/backend/external/iter_test.go
pkg/lightning/backend/external/kv_reader.go
pkg/lightning/backend/external/onefile_writer.go
pkg/lightning/backend/external/onefile_writer_test.go
pkg/lightning/backend/external/reader_test.go
pkg/lightning/backend/external/sort_test.go
pkg/lightning/backend/external/split_test.go
pkg/lightning/backend/external/util.go
pkg/lightning/backend/external/util_test.go
pkg/lightning/backend/external/writer.go
pkg/lightning/backend/external/writer_test.go
tests/realtikvtest/addindextest2/global_sort_test.go

on default, S3 have only one partition per bucket, and each partition have it's own request limit, if user want to have larger  upper bound of the limit, they have to ask AWS support to partition manually before accessing, and BTW, from the feedback of S3, the partition is not durable forever, if you don't use the partition too frequently, the partition might be merged automatically, as partition takes additionally resource.
when importing large mount of data with import-into using large number of nodes, during global sort steps, we might many intermediate files to S3, and might meet request throttle, and slows import down.
currently, we are using `cloud_storage_uri/<task-id>/<subtask-id>/<uuid><type-suffix>/<seq>` to store intemediate KV and stat …

globalsort: use partitioned prefix to store intermediate files | tidb-test=release-8.1.2

---

Makefile
Makefile.common

use the same `NEXT_GEN=1` to control next gen real-tikv test
Tests 
see the `define gotags=` part
```
➜  tidb git:(one-writer-ondup) ✗ make --dry-run bazel_importintotest3
GOBIN=/Users/jujiajia/code/pingcap/tidb/tools/bin GO111MODULE=on go install github.com/pingcap/failpoint/failpoint-ctl@9b3b6e3
find $PWD/ -mindepth 1 -type d | grep -vE "(\.git|\.idea|tools)" | xargs tools/bin/failpoint-ctl enable
bazel  run  //:gazelle
bazel  run   \
--run_under="cd /Users/jujiajia/code/pingcap/tidb && " \
//tools/tazel:tazel
bazel  test  --test_output=all --test_arg=-with-real-tikv --define gotags=deadlock,intest \
-- //tests/realtikvtest/importintotest3/...
➜  tidb git:(one-writer-ondup) ✗ NEXT_GEN=1 make --dry-run bazel_importintotest3 …
```

*: prepare for real-tikv-test on next gen

---

pkg/ddl/ingest/disk_root.go

Issue Number: close #60893 
darwin‘s disk is too expensive and we only use it in the development environment. so we ignore the error.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: ignore ingest's disk check in the darwin

---

pkg/lightning/backend/external/bench_test.go
pkg/lightning/backend/external/byte_reader_test.go
pkg/lightning/backend/external/file.go
pkg/lightning/backend/external/merge.go
pkg/lightning/backend/external/merge_v2.go
pkg/lightning/backend/external/onefile_writer.go
pkg/lightning/backend/external/onefile_writer_test.go
pkg/lightning/backend/external/reader_test.go
pkg/lightning/backend/external/split_test.go
pkg/lightning/backend/external/writer_test.go

Issue Number: ref #60621 
impl onDup for onefile writer.
Tests 
> 
Side effects
Documentation
```release-note
None
```

globalsort: impl onDup for onefile writer

---

pkg/planner/core/tests/redact/redact_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/60940
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: make redact log test result ignore plan ID with explain format as brief.

---

pkg/parser/ast/functions.go
pkg/parser/ast/functions_test.go
tests/integrationtest/r/expression/json.result
tests/integrationtest/t/expression/json.test

Issue Number: close #60906 
Tests 
> 
Side effects
Documentation
```release-note
None
```

parser: fix panic when call `json_memberof` without parameters

---

pkg/domain/domain.go
pkg/statistics/handle/autoanalyze/autoanalyze.go
pkg/statistics/handle/autoanalyze/exec/exec.go
pkg/statistics/handle/autoanalyze/priorityqueue/job.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue.go
pkg/statistics/handle/autoanalyze/priorityqueue/queue_ddl_handler.go
pkg/statistics/handle/autoanalyze/refresher/refresher.go
pkg/statistics/handle/autoanalyze/refresher/worker.go
pkg/statistics/handle/logutil/logutil.go

Issue Number: ref https://github.com/pingcap/tidb/issues/59939
We should use the error verbose logger to print the stack of the error. Since every 3 seconds it will try to fetch available tables to analyze, we use the sample logger here to reduce the number of logs.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: update logging in auto-analyze components to use the error verbose logger

---

pkg/planner/core/task.go

As said in the title, union scan should convert the child to be the root task type first, then we can do the pattern assert, such as pull the project above the union-scan itself.
But once the task is cop type here, it may be converted as proj + tablePlan here, then when it's attached with union-scan here, we may get as: union-scan + proj + tablePlan, and miss the proj pullup action in the code change, while proj is not allowed to be built under union-scan in the execution layer currently.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-g …

planner: fix union scan should convert child to be root task type first then we can do the pattern assert 

---

pkg/domain/plan_replayer_dump.go
pkg/server/handler/optimizor/plan_replayer_test.go

Issue Number: close #60985
Foreign keys cannot form a cycle during the table definition phase. However, it is possible to disable FK checks to force a cycle. When traversing the definitions, we need to skip parts that have already been traversed to avoid an infinite loop
Tests 
> 
Side effects
Documentation
```release-note
domain: fix the issue where defining FKs in a circular manner causes an infinite loop
修复外键定义成环时的死循坏问题
```

domain: fix the issue where defining FKs in a circular manner causes an infinite loop

---

pkg/planner/core/plan_cache_test.go
pkg/planner/core/plan_cacheable_checker.go
pkg/planner/core/plan_cacheable_checker_test.go
pkg/planner/optimize.go
tests/integrationtest/r/planner/core/plan_cache.result

Issue Number: ref #60920
The non-prepared plan cache does not presently support queries with hints.
This pull request:
* enables the non-prepared plan cache for queries with all hint types except for RESOURCE_GROUP and SET_VAR,
* disables prepared plan cache for queries with the RESOURCE_GROUP hints,
* disables the caching of queries with bindings that use SET_VAR hints.
* makes minor improvements to TestPlanCacheRandomCases in pkg/planner/core/plan_cache_test.go
* adds a test (TestNonPreparedPlanSupportsHints) to validate that SELECT queries with hints are cached.
* and patches the tests in plan_cacheable_checker_test.go for the changes.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language …

planner: Enable non-prepared plan cache for queries with hints.

---

pkg/planner/core/plan_cache_test.go
pkg/planner/optimize.go
tests/integrationtest/r/planner/core/plan_cache.result
tests/integrationtest/t/planner/core/plan_cache.test

Issue Number: close #61047
The non-prepared plan cache does not support queries with SQL bindings.
This patch:
* adds support for SQL bindings in the non-prepared plan cache,
* adds some comments in Optimize(),
* adds a test for the SQL bindings in the non-prepared plan cache.
Tests 
> 
Side effects
Documentation
```release-note
The non-prepared cache now supports queries with SQL binding.
```

planner: Enable the non-prepared plan cache for queries with bindings.

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/find_best_task.go
pkg/planner/core/index_join_path.go
pkg/planner/core/physical_plans.go
pkg/planner/property/physical_property.go
tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result

* previously the tidb will enumerate and build index join‘s inner task as tableRangeScan and indexRangeScan separately, which means two kinds of this index join will compare their total cost from indexJoin itself. 
* obviously, one indexJoinProp couldn't output two kinds of underlying cop tasks, so we just add one more field in the indexJoinProp to guide the underlying datasource to build separate copTask(tableRangeScan or indexRangeScan) out, then leverage the attack2Task to wrap them as TableReader or IndexReader or IndexLookUpReader just like old logic does, consequently, leading to different physical index join and the cost comparing just between them.
* some small fix: 
* clone function should check …

planner: distinguish the index join probe as indexScan or tableScan from indexJoinProp side.

---

pkg/executor/distsql.go

Issue Number: close #61072 
Problem described in #61072
In this PR, when index/table work failed, we first check if context is cancelled. And only log errors when context is not cancelled. Doesn't use WithCancelCause function to pass cancel cause here, since the actual root cause is limit executor quit quitely, by returning empty data.
Tests 
Use tpch, sf=1 benchmark, add index for orders table: 
```alter table orders add index(o_orderdate);```
Then execute the following sql and check tidb.log to see if "table reader fetch next chunk failed" log doesn't exists any more:
```
+----------------------------------+---------+---------+-----------+-----------------------------------------+-------------------------------------------------------------------------------------------- …
```

executor: Remove useless error logs for indexLoopUp executor when context canceled

---

pkg/planner/core/point_get_plan.go
pkg/planner/core/tests/redact/redact_test.go

Issue Number: close #61060 
when to implement the redact, forget to add the redact into ```BatchPointGetPlan```. 
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix BatchPointGetPlan cannot redact the explain data

---

pkg/ddl/placement/BUILD.bazel
pkg/ddl/placement/bundle.go
pkg/ddl/placement/bundle_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/60888
Tests 
> 
```release-note
None
```

placement: fix alter meta range cannot work

---

br/pkg/restore/snap_client/pipeline_items.go
br/pkg/task/common_test.go
br/pkg/task/restore.go
br/tests/br_stats/run.sh

Issue Number: ref #60374
If the count of stats_meta is larger than 1000 and the table has not been analyzed yet, the priority_queue also analyze the table in the background.
1. remove `--auto-analyze`
2. BR won't update `stats_meta` if `--load-stats=true`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: adjust auto analyze

---

pkg/executor/mem_reader.go
pkg/tablecodec/tablecodec.go
tests/integrationtest/r/globalindex/mem_index_merge_non_unique.result
tests/integrationtest/r/globalindex/mem_index_non_unique.result
tests/integrationtest/t/globalindex/mem_index_merge_non_unique.test
tests/integrationtest/t/globalindex/mem_index_non_unique.test

Issue Number: close #61083
Tests 
> 
Side effects
Documentation
```release-note
None
```

tablecodec, executor: fix non unqiue global index work with union scan

---

pkg/executor/adapter.go
pkg/executor/test/executor/executor_test.go
pkg/session/BUILD.bazel
pkg/session/session.go

Issue Number: close #61056
also update the `@@tidb_last_txn_info` for readyonly or rollback transactions
Tests 
> 
Side effects
Documentation
```release-note
@@tidb_last_txn_info will also be updated when readonly transaction ends or transaction rollback
```

txn: also update the `@@tidb_last_txn_info` for readyonly or rollback txns

---

DEPS.bzl
dumpling/log/log_test.go
go.mod
go.sum

Issue Number: close https://github.com/pingcap/tidb/issues/61100
ref https://github.com/pingcap/log/pull/43
Tests 
> 
Side effects
Documentation
```release-note
None
```

dumpling: precheck log file permisssion

---

pkg/executor/infoschema_cluster_table_test.go
pkg/executor/infoschema_reader.go

Issue Number: close #59698
Add a check to exclude INFORMATION_SCHEMA, METRICS_SCHEMA and PERFORMANCE_SCHEMA when TIKV_REGION_STATUS is queried.
Tests 
> 
Side effects
Documentation
```release-note
Previously, when you query TIKV_REGION_STATUS, results will show tables from INFORMATION_SCHEMA, METRICS_SCHEMA and PERFORMANCE_SCHEMA. From now on, it will not be shown as a part of this TIKV_REGION_STATUS results as they are not a part of TiKV data store.
```

executor/infoschema_reader: exclude virtual schema in TIKV_REGION_STATUS

---

pkg/metrics/grafana/tidb.json

Issue Number: close #61051
After this PR:
Move the panel to DDL
Tests 
> 
Side effects
Documentation
```release-note
None
```

metrics: fix panel "retryable error"

---

pkg/types/json_binary_functions.go
pkg/types/json_binary_functions_test.go
tests/integrationtest/r/types/json_binary_functions.result
tests/integrationtest/t/types/json_binary_functions.test

Issue Number: close #61091
Problem Summary: For some special charactesrs, such like some emoji, it uses two `\\uxxxx` to present. The `decodeEscapedUnicode` func didn't deal with it correctly before. This PR fix it.
Tests 
> 
Side effects
Documentation
```release-note
None
```

types: fix `decodeEscapedUnicode` func work with `surrogate pair`

---

pkg/ddl/index.go
tests/integrationtest/r/ddl/db_integration.result
tests/integrationtest/t/ddl/db_integration.test

Issue Number: close https://github.com/pingcap/tidb/issues/61133
TiDB accept this kind of invalid expression index. If tiflash replica is created and new rows inserted, it cause TiFlash crashes becuase unexpectedly need to create a "Nothing" data type in  the storage layer. https://github.com/pingcap/tiflash/issues/9891
```
TiDB root@10.2.12.81:test> CREATE TABLE `t2` (
->   `id` int,
->   KEY `idx_name` ((null))
-> );
TiDB root@10.2.12.81:test> show create table t2 \G
***************************[ 1. row ]***************************
Table        | t2
Create Table | CREATE TABLE `t2` (
`id` int DEFAULT NULL,
KEY `idx_name` ((null))
```
For a valid expression, the return value type stored in generated column should never be `TypeNull`. Add a check whether …

ddl: Fix invalid expression index

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/task.go
pkg/planner/core/task_base.go
pkg/util/context/warn.go

It inherits some stats from the index join inside underlying datasource, which is the problem we have been talking about --- some index join's inner side operator's est row count may be greater the underlying ds and this is because this operator didn't adjust it estimation according to the avgInnerCount as the ds does. So this pr is essentially to directly inherit and keep the alignment with the undelrying rowcount, as long as it is found to be the index join inside end. Also there are some tasks warnings collection work. Generally speaking, the tasks copy() and convertToRoot() basically cover most of the situations, but for some task new mannually, we need to manually inherit warnings. Here is a supplement. …

planner: inherit the index join info and stats  bottom-up for index join inner side

---

pkg/server/internal/column/result_encoder.go
tests/integrationtest/r/new_character_set.result
tests/integrationtest/t/new_character_set.test

Issue Number: close #61085
Problem Summary: Change behavior when convert result.
Tests 
> 
Side effects
Documentation
```release-note
Fix bug that character_set_results will truncate instead of replace on error char
```

server: replace instead of truncate encoded result

---

DEPS.bzl
go.mod
go.sum
pkg/ddl/job_worker.go
pkg/distsql/request_builder_test.go
pkg/executor/select.go
pkg/infoschema/test/clustertablestest/cluster_tables_test.go
pkg/keyspace/BUILD.bazel
pkg/keyspace/keyspace.go
pkg/keyspace/keyspace_test.go
pkg/kv/BUILD.bazel
pkg/kv/kv.go
pkg/kv/kv_test.go
pkg/server/BUILD.bazel
pkg/server/conn.go
pkg/sessionctx/stmtctx/BUILD.bazel
pkg/sessionctx/stmtctx/stmtctx.go

Issue Number: close https://github.com/pingcap/tidb/issues/61095
Related PR: https://github.com/pingcap/tipb/pull/363
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: update tipb and support `ResourceGroupTag` with keyspace info

---

pkg/planner/core/casetest/tpch/BUILD.bazel
pkg/planner/core/casetest/tpch/tpch_test.go
pkg/planner/core/common_plans.go
pkg/planner/core/planbuilder.go

Issue Number: close #61155
When we use the cost trace's explain, it will calculate the cost twice. Unfortunately, when calculating secondly, the row count has been polluted by the first.
the first calculation:
```
1500000000*math.log2(46.17)*11.6+10000*math.log2(46.17)*11.6 = 96203219945.10272
```
```1500000000``` will become the ```5.645217633333338e+07```, because ```postOptimize```‘s 
```tryEnableLateMaterialization``` can change the ```row count``` in the first plan generate.
https://github.com/pingcap/tidb/blob/7419112ef7bcd6fb0f0acb2e98222487e6616297/pkg/planner/core/tiflash_selection_late_materialization.go#L283-L290
the second calculation:
```
5.645217633333338e+07*math.log2(46.17)*11.6+10000*math.log2(46.17)*11.6 = 3621204637.5523133
```
So two formats have …

planner: fix get wrong cost with cost tracer 

---

pkg/distsql/distsql_test.go
pkg/distsql/select_result.go

Issue Number: close #61125 
Described in #61125 
Output fetch response duration in tableReader's execution summary after cop_task item.
```
explain analyze select l_orderkey, max(l_suppkey) from lineitem group by l_orderkey;
+------------------------------+------------+---------+-----------+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

distsql: Add fetch_resp_duration in table reader's execution info

---

pkg/bindinfo/binding_auto.go
pkg/bindinfo/binding_auto_test.go
pkg/bindinfo/binding_plan_generation.go
pkg/bindinfo/testdata/binding_auto_suite_out.json
pkg/planner/core/common_plans.go
pkg/planner/core/flat_plan.go
pkg/planner/optimize.go

Issue Number: ref #60148
Problem Summary: planner: merge the some code of helper func `genPlanWithSCtx` with `Explain` to reduce redundant code
Refactor some of of `Explain`, and remove the prior `ExplainFlatPlan` (merged with `ExplainFlatPlanInRowFormat`).
Now `ExplainFlatPlanInRowFormat` is the only function to get a formatted plan in row format:
```
func ExplainFlatPlanInRowFormat(flat *FlatPhysicalPlan, format string, analyze bool,
runtimeStatsColl *execdetails.RuntimeStatsColl, explainRows [][]string) (rows [][]string) {...}
```
Tests 
> 
Side effects
Documentation …

planner: merge the some code of helper func `genPlanWithSCtx` with `Explain` to reduce redundant code

---

pkg/domain/domain.go
pkg/privilege/privileges/cache.go

Issue Number: close #61206
The root case is:
Two SQL statements are executed consecutively:  
1. `CREATE USER tcd1, tcd2;`  
2. `GRANT ALL ON *.* to tcd2 WITH GRANT OPTION;`  
**Normal sequence:**  
`notifyUpdatePrivilege()` → priv 0  
`etcd` → `LoadPrivilegeLoop()` → priv 0  
`notifyUpdatePrivilege()` → priv all  
`etcd` → `LoadPrivilegeLoop()` → priv all  
**After adding a sleep between `LoadAll` and `h.priv.Store` in `UpdateAll` for the etcd case, it becomes:**  
`notifyUpdatePrivilege()` → priv 0  
`notifyUpdatePrivilege()` → priv all  
`etcd` → `LoadPrivilegeLoop()` → priv 0  
*(At this point, executing some SQL on tcd2 will result in permission denied errors.)*  
`etcd` → `LoadPrivilegeLoop()` → priv all  
Tests 
Add logs in `func privReloadEvent(h …

privilege: avoid processing the same privilege event twice

---

pkg/planner/core/casetest/partition/BUILD.bazel
pkg/planner/core/casetest/partition/partition_pruner_test.go
pkg/planner/core/rule_partition_processor.go
pkg/testkit/result.go

Issue Number: close #61176
Partition pruning for NullEQ `<=>` of range columns could return more than one partition, resulting in PointGet failed.
Added handling to first check if constant is NULL, then just use first partition, else treat as EQ `=`.
Tests 
> 
Side effects
Documentation
```release-note
Fixed an issue where PointGet could fail when using NullEQ (<=>) for a table partitioned by range column
```

planner: Handle NullEQ <=> in range columns partition pruning

---

pkg/executor/aggregate/agg_hash_executor.go
pkg/executor/aggregate/agg_hash_partial_worker.go

Issue Number: close #58822
We delete the memory tracking for received chunk in partial worker. Received chunk in partial worker has been tracked in fetcher, if we receive a smaller chunk compared to the current chunk both held by fetcher and partial worker, memory tracker will double minus the memory usage it tracked. However, duplicate operation will decrease more memory usage and will lead to negative counter in the end.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that getting wrong statistic from memory tracker in …
```

executor: fix wrong statistic from memory tracker in hash agg

---

pkg/executor/BUILD.bazel
pkg/executor/analyze.go
pkg/planner/core/BUILD.bazel
pkg/planner/core/planbuilder.go
pkg/statistics/handle/cache/statscache.go
pkg/statistics/handle/logutil/logutil.go

Issue Number: close https://github.com/pingcap/tidb/issues/59939
Replace `logutil` with `statslogutil` to include the module field in the logs, and use the verbose logger to print the stack trace.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: replace logutil with statslogutil for improved logging in the analyze process

---

br/pkg/restore/log_client/batch_meta_processor.go
br/pkg/task/stream.go
br/tests/br_pitr_table_filter/run.sh

Issue Number: close #61226
Need to take into account of multiple segments of PiTR.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix table filter nil pointer issue

---

pkg/server/driver_tidb_test.go
pkg/server/internal/column/convert.go

Issue Number: close #60503 , close #34901
Problem Summary:  MySQL will always output a usable column-type-info length in the returned packet, so do we. While we cannot output the same flen as mysql, we can return a non-zero length, at least.
Tests 
> 
Side effects
Documentation
```release-note
Fix that tidb will return zero in the column type info of mysql protocol when flen unspecified
```

server: return a default flen when unspecified

---

pkg/domain/domain.go

Issue Number: close #60665 
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue of NotifyUpdateSysVarCache getting stuck due to etcd put API timeout.
```

domain: use PutKVToEtcd in NotifyUpdateSysVarCache to avoid stuck by etcd operation

---

pkg/executor/internal/mpp/local_mpp_coordinator.go

Issue Number: close #61233 
Tests 
Check 
```
explain analyze select o_orderkey, o_custkey from orders where o_comment like "%%" limit 5;
+--------------------------------+---------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

executor: update internal mpp tasks waitReport time from 3s to 100ms

---

lightning/pkg/importer/BUILD.bazel
lightning/pkg/importer/chunk_process.go
lightning/pkg/importer/chunk_process_test.go
lightning/pkg/importer/get_pre_info.go
pkg/executor/importer/chunk_process_testkit_test.go
pkg/executor/importer/import.go
pkg/executor/importer/import_test.go
pkg/executor/importer/precheck.go
pkg/executor/importer/table_import.go
pkg/executor/load_data.go
pkg/lightning/mydump/csv_parser.go
pkg/lightning/mydump/csv_parser_test.go
pkg/lightning/mydump/region.go
pkg/lightning/mydump/region_test.go
tests/integrationtest/r/executor/import_into.result
tests/integrationtest/t/executor/import_into.test
tests/realtikvtest/importintotest/BUILD.bazel
tests/realtikvtest/importintotest/import_into_test.go

Issue Number: ref #61166
Add new option `remove_csv_header` for `IMPORT INTO` with CSV format.
For now, this option coexists with `skip_rows`, although users can't set both of them.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: add new option for auto detecting CSV header | tidb-test=b256656b231ebd8f752e8738e89fc64f5263721a

---

br/pkg/restore/snap_client/pipeline_items.go

Issue Number: close #61140
After BR starts, the region cache may not be updated in time. Therefore, the pessimistic prewrite batches are sent to follower peer.
However, BR heartbeat for pessimistic lock exceeds 20 seconds, so that the lock is rollbacked by select SQL from other TiDB nodes.
add retry for updating stats meta
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: add retry for updating stats meta

---

pkg/executor/BUILD.bazel
pkg/executor/adapter.go
pkg/util/metricsutil/common.go

Issue Number: ref #60864 
Confirmed that we should expose keyspace_name from kernerl instead of keyspace_id for metrics. Set real keyspace_id instead of keyspace_name for slow log.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: Update metrics and slow log keyspace info for next gen

---

br/pkg/streamhelper/advancer.go
br/pkg/streamhelper/advancer_cliext.go

Issue Number: close #61031
The last checkpoint from tidb advancer owner that metrics shows is not updated in PD.
update the last checkpoint from tidb advancer owner that metrics shows after it is updated in PD.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix the last checkpoint from tidb advancer owner is not updated in PD

---

br/cmd/br/backup.go
br/cmd/br/restore.go
pkg/util/metricsutil/BUILD.bazel
pkg/util/metricsutil/common.go

Issue Number: close https://github.com/pingcap/tidb/issues/61121
TLS is currently not supported for restore operations with keyspace.
Use TLS configuration to initialize the PD client.
Tests 
> 
Side effects
Documentation
```release-note
None
```

metrics: fix connect issue when tls enabled

---

pkg/session/syssession/session_test_util.go
pkg/timer/tablestore/sql_test.go
pkg/timer/tablestore/store.go
pkg/ttl/ttlworker/job_manager_integration_test.go
pkg/ttl/ttlworker/task_manager_integration_test.go

Issue Number: close #61175
1. Timeout error for session in long tests.
2. Fail in `ResetSctxForTest` because the owner is nil.
Both of them are not likely to occur in production environment. For the second issue, it'll occur only when the `SET @@time_zone = ...` failed.
1. Don't call `.Close()` in `withSession`.
4. Extend the timeout of a session for test.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ttl: fix ut failure after using advanced session

---

pkg/executor/join/row_table_builder_test.go

Hash join v2 use unalignment load during join probe, this pr add an unalignment load test.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: add an unalignment load test for hash join v2

---

cmd/tidb-server/BUILD.bazel
cmd/tidb-server/main.go
pkg/util/printer/printer.go

Issue Number: ref #60418
as title, also add log
Tests 
without keyspace name
```
invalid config: keyspace name is required for nextgen TiDB
```
on success start
```
[.....] ["Welcome to TiDB."] [keyspaceName=a] .... ["Kernel Type"="Next Generation"]
```
> 
Side effects
Documentation
```release-note
None
```

*: ensure keyspace name is set for nextgen

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/operator/logicalop/logical_union_scan.go
tests/integrationtest/r/explain_union_scan.result
tests/integrationtest/r/planner/core/indexjoin.result
tests/integrationtest/t/planner/core/indexjoin.test

Issue Number: close https://github.com/pingcap/tidb/issues/61323
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: index join banned the enforced sort from stream agg, which is not supported in executor layer now.

---

br/pkg/task/backup.go

Issue Number: close #60149
backup schemas progress's total value is only 1 if skip checksum
the backup schemas progress's total is number of schemas.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix backup schemas progress if skip checksum

---

pkg/executor/aggfuncs/BUILD.bazel
pkg/executor/aggfuncs/aggfunc_test.go
pkg/expression/aggregation/aggregation.go
pkg/expression/expr_to_pb_test.go
pkg/expression/infer_pushdown.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61375
In current implementation, `IsPushDownEnabled` explicitly check `AggFuncApproxCountDistinct`:
https://github.com/pingcap/tidb/blob/eeccd2e94c23df353ba70919691d65d38ad31805/pkg/expression/infer_pushdown.go#L452-L1455
Actually, this check can be moved to `CheckAggPushDown`
Tests 
> 
Side effects
Documentation
```release-note
None
```

expression: refine code in `IsPushDownEnabled`

---

pkg/planner/core/optimizer.go
pkg/planner/core/rule_collect_plan_stats.go

Previously, the checkpoint for avoiding the sync load of internal SQL was too late, and the logic was scattered. Now, it is centralized in ```adjustOptimizationFlags```.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: improve OptimizationFlags to avoid internal sql's syncload

---

pkg/planner/core/BUILD.bazel
pkg/planner/core/hint_test.go
pkg/sessionctx/stmtctx/stmtctx.go
tests/realtikvtest/pipelineddmltest/pipelineddml_test.go

The SET_VAR SQL hint does not properly restore the previous session values.
Issue Number: ref #60905, close #59822
When a session variable is set by the SET_VAR hint, it overwrites any value previously saved for restoration.  If there is a SET_VAR hint in a SQL query and a SET_VAR hint (for the same variable) in a matching binding, the binding code will set the value to be restored to the value from the query's hint.  See my comment on issue [#60905](https://github.com/pingcap/tidb/issues/60905#issuecomment-2836026943).  This is also the issue with issue #59822.
With this pull request, only the first value to be restored for a session variable will be retained.
Tests 
> 
Side effects
Documentation
Please refer to …

planner: Make SET_VAR query hints restore the original session variable values.

---

pkg/expression/builtin_other.go
pkg/util/ranger/ranger_test.go
tests/integrationtest/r/expression/issues.result
tests/integrationtest/r/planner/core/integration.result
tests/integrationtest/r/planner/core/issuetest/planner_issue.result
tests/integrationtest/t/expression/issues.test

Issue Number: close #61246 
deduplicate args of the IN when building the hashmap.
Tests 
> 
Side effects
Documentation
```release-note
对 IN 的参数列表进行去重，避免给 tikv 发送过大的 grpc 请求
Do deduplication for IN function's arguments, to avoid sending a big GRPC request to TiKV
```

expression: deduplicate the args of IN function | tidb-test=pr/2518

---

pkg/executor/simple.go
pkg/util/sqlexec/BUILD.bazel
pkg/util/sqlexec/restricted_sql_executor.go

This PR addresses the enhancement suggestion regarding repetitive patterns when using DrainRecordSet. Previously, callers needed to manually defer the closing of the RecordSet after execution, which introduced boilerplate and risked forgetting to close the resource.
Issue Number: close #61408 
This change introduces a new utility function DrainRecordSetAndClose, which automatically drains and closes the RecordSet, simplifying the common usage pattern and improving code readability and safety. Existing code that follows the defer Close() pattern can now be replaced with a single call to this new function.
Tests 
Side effects
Documentation
```release-note
Add DrainRecordSetAndClose to simplify draining and closing RecordSet, reducing boilerplate and preventing resource …
```

executor, sqlexec: add a function to let DrainRecordSet also close the RecordSet

---

Makefile
Makefile.common
pkg/util/printer/printer.go

Issue Number: ref #60418
- add `GOBUILD_NO_TAGS`, as some make target explicitly specify `-tags` param which will override the `-tags` in `GOBUILD`
- always print kernel type in output of `-V`
Tests 
community build
```
➜  tidb git:(close-idle-conn) ✗ make server; bin/tidb-server -V
CGO_ENABLED=1  GO111MODULE=on go build -tags codes   -ldflags '-X "github.com/pingcap/tidb/pkg/parser/mysql.TiDBReleaseVersion=v9.0.0-alpha-857-gca89c94ed0-dirty" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBBuildTS=2025-06-04 02:59:37" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitHash=ca89c94ed07a7eaec7ce71113fbbfc40245e0275" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitBranch=close-idle-conn" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBEdition=Community" …
```

build: fix build tags for some make target

---

pkg/util/ranger/points.go

Issue Number: close #61458
Using `slices.SortFunc` has many advantages
- avoid the boundary check
- simple the code
it can make sort quicker.
Tests 
```
before
BenchmarkDetachCondAndBuildRangeForIndex-8   	    6349	    216681 ns/op
after 
BenchmarkDetachCondAndBuildRangeForIndex-8   	    6542	    205847 ns/op
```
improve the performance 4.99%
> 
Side effects
Documentation
```release-note
None
```

planner,range: simple the code for sorting the pointers

---

pkg/metrics/metrics.go
pkg/metrics/wrapper.go
pkg/util/metricsutil/common.go

Issue Number: ref #60864 
In this PR, init tikv_client and pd_client metrics with keyspace_name const labels. Note, pd client uses init-only-once mechanism to init metrics, thus create a temporary pd client for this usage.
Tests 
Hack code to set const labels manually, and verify the metrics got from http API.
> 
Side effects
Documentation
```release-note
None
```

*: Set keyspace_name const labels for client-go related metrics

---

pkg/planner/core/logical_plan_builder.go
pkg/planner/core/rule_partition_processor.go

use slices.Sort to simple code
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: use slices.Sort to simple code

---

pkg/ttl/cache/BUILD.bazel
pkg/ttl/cache/split_test.go
pkg/ttl/cache/table.go
tools/check/longtests.go

Issue Number: close #61512 
When the regions are merged frequently, the TTL will fail to start.
1. Use `regionCache.LocateKeyRange` to get the region info. Instead of fetching the `regionIds` and then get the region info.
Most of the changes are from unit test.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that merging regions frequently will block TTL job from starting
```

ttl: fix the issue that TTL cannot start if regions are merged frequently

---

pkg/ttl/ttlworker/job_manager.go
pkg/ttl/ttlworker/job_manager_integration_test.go

Issue Number: close #61509 
1. Create a new function `summarizeTaskResultWithError` to submit summary with error.
2. Find all existing tasks and summary them when the ttl job timeout.
Tests 
> 
Side effects
Documentation
```release-note
Fix the issue that the summary for timeout TTL job is empty
```

ttl: fix the issue that the TTL execution summary for timeout job is empty

---

docs/design/2025-05-26-refresh-stats-command.md
pkg/executor/simple.go
pkg/planner/core/pb_to_plan.go
pkg/planner/core/planbuilder.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61273
In this PR, I added a basic framework for distributing SQL queries to different TiDB nodes. I also used a simple log to simulate the real refresh stats. I will add the actual code in my subsequent updates.
I tested it locally, and it can distribute the correct SQL to different TiDB nodes. The core idea is that we need to use the coprocessor to send tasks to each TiDB cluster and execute them correctly.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner, executor: implement support for broadcasting queries

---

pkg/planner/core/casetest/plan_test.go
pkg/planner/core/rule/util/misc.go
pkg/planner/core/rule_join_elimination.go
tests/integrationtest/r/planner/core/rule_constant_propagation.result

Issue Number: ref #61305
Issue 61305 exposed limitations in the outer join pruning if constants are in the select list. If a constant is in the select list, then we don't recognize that this column is irrelvant - and thus if you ONLY otherwise have columns from the left side, we don't prune right side tables due to the constant.
Enhanced outer join pruning to cover these cases.
An example is - before:
``` 
EXPLAIN SELECT DISTINCT 1, t3.parent_id as w1
-> FROM t3
->          LEFT OUTER JOIN t1 ON t1.parent_id = t3.parent_id
->       WHERE t3.search_field = 'Find me'
-> LIMIT 101;
+---------------------------------+------------+-----------+--------------------------------------------+-------------------------------------------------------------------------------------------- …
```

planner: outer join pruning for constants

---

br/pkg/storage/s3.go

Issue Number: close https://github.com/pingcap/tidb/issues/61547
We’re encountering the same issue when using a regular S3 endpoint together with assumeWebIdentity for authorization.
As mentioned in [aws/aws-sdk-go#3972](https://github.com/aws/aws-sdk-go/issues/3972), if the endpoint is not explicitly set when calling s3.New(...), it can unintentionally override the endpoint globally — including for STS — which breaks the WebIdentity auth flow.
A workaround is to explicitly set the S3 endpoint only within the s3.New() call, rather than modifying the shared config.
Alternatively, migrating to AWS SDK for Go v2 would avoid this issue entirely, as endpoint resolution is better isolated in v2.
Tests 
prepare a eks environment and use eks pod identity to grant s3 permission (a …

s3: fix compatibility issue when using AssumeWebIdentity with custom S3 endpoint

---

br/pkg/streamhelper/advancer.go

Issue Number: close #61550
As the issue content.
`listen task meet error, would reopen.` is retryable but an error level log, which is confusing.
Make it an `Warn`. 
Tests 
> It is trivial.
Side effects
Documentation
```release-note
Now, log backup advancer's `listen task meet error, would reopen.` is an WARN level log.
```

br/advancer: move retryable error logs to warn

---

pkg/ddl/backfilling_operators.go
pkg/ddl/ingest/BUILD.bazel
pkg/ddl/ingest/integration_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/61087
The `getChunk()` stuck issue has been solved by #57468, which changed the chunk pool implementation from channel to a `sync.Pool`.
This PR only adds the test to make sure that there will be no regression in the future.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: fix cancelling stuck issue during adding index

---

pkg/executor/join/joinversion/join_version.go

Issue Number: ref https://github.com/pingcap/tidb/issues/60299
TiFlash hash join v2 is enabled in master for test purpose. 
Now disable tiflash hash join v2 in the coming release version.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: disable tiflash hash join v2 by default

---

pkg/planner/core/plan_cost_ver1.go
pkg/sessionctx/variable/session.go
pkg/util/mock/context.go

Issue Number: close #61565
We don't set the default of the tidb_cost_model_version in the right place. so it led many problems in the internal SQL. The internal SQL will not use the cost model v2.
Tests 
> 
Side effects
Documentation
```release-note
planner: rightly set the default of the tidb_cost_model_version
正确设置 tidb_cost_model_version 的默认值
```

planner: set the default of the tidb_cost_model_version correctly

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/integration_test.go

Issue Number: close #61669
Problem Summary: planner: fix the issue that invalid column error when building IndexJoin for sub-query with multiple Agg
planner: fix the issue that invalid column error when building IndexJoin for sub-query with multiple Agg
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix the issue that invalid column error when building IndexJoin for sub-query with multiple Agg

---

pkg/planner/core/stats.go
tests/integrationtest/r/executor/index_lookup_merge_join.result
tests/integrationtest/r/explain_complex.result
tests/integrationtest/r/planner/core/casetest/physicalplantest/physical_plan.result
tests/integrationtest/r/planner/core/indexjoin.result

Issue Number: close #61602
Problem Summary: planner: fix the wrong join estimation depending on missing or uninitialized stats
planner: fix the wrong join estimation depending on missing or uninitialized stats
It's hard to construct test cases for this issue since it depends on stats cache's status. So I tested it locally, and this PR can work for this scenario:
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix the wrong join estimation depending on missing or uninitialized stats

---

pkg/planner/core/common_plans.go
pkg/util/memoryusagealarm/memoryusagealarm.go
pkg/util/plancodec/binary_plan_decode.go

Issue Number: close #61693
TOP SQL sometimes retrieves a plan without runtime information, which may cause an index out of range error.
Tests 
> 
Side effects
Documentation
```release-note
None
```

Planner: fix panic when getting Top SQL without runtime stats

---

pkg/util/printer/BUILD.bazel
pkg/util/printer/printer.go
pkg/util/printer/printer_test.go

introduced by https://github.com/pingcap/tidb/pull/61697 , forget add new line
Tests 
```
~/code/pingcap/tidb git:[fix-printer] make server; bin/tidb-server -V; NEXT_GEN=1 make server; bin/tidb-server -V
CGO_ENABLED=1  GO111MODULE=on go build -tags codes   -ldflags '-X "github.com/pingcap/tidb/pkg/parser/mysql.TiDBReleaseVersion=v9.0.0-alpha-924-gc893db633f-dirty" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBBuildTS=2025-06-12 11:46:28" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitHash=c893db633f56e7d9c2ca532f9c50074c831d4950" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitBranch=fix-printer" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBEdition=Community" ' -o 'bin/tidb-server' ./cmd/tidb-server
Release …
```

printer: fix printed kernel type

---

pkg/ddl/ddl_test.go
pkg/ddl/ingest/BUILD.bazel
pkg/ddl/ingest/integration_test.go
pkg/ddl/modify_column.go
pkg/metrics/ddl.go

Issue Number: close #61668
There are two roles for DDL execution:
- DDL submitter: the node that accepts DDL SQL submitted from users.
- DDL owner: the node that runs real DDL workers.
It is a TOCTOU issue. The problem is that DDL submitter checks the collation of MODIFY COLUMN job and make sure there is no index defined on the target column. However, an ADD INDEX job is finished, before DDL owner runs the MODIFY COLUMN job.
Add double check at DDL owner side (in `onModifyColumn`).
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: double check collation compatibility before modifying column

---

pkg/store/gcworker/gc_worker.go

Issue Number: ref #58720
Now we have NextGen and classic tidb share the same code by using build flag.
NextGen introduce keyspace level GC, and classic still use unifed GC. Those two GC types should not co-exist in theory (not talking about tidbcloud).
I change the label to distinguish them, not quite useful, but just in case some bad thing really happen, we can diagnose that.
Tests 
> 
Side effects
Documentation
```release-note
None
```

store/gcworker: use label to distinguish keylevel GC and unified GC

---

br/pkg/restore/misc.go
br/pkg/restore/misc_test.go
br/pkg/stream/table_mapping.go
br/pkg/stream/table_mapping_test.go
br/pkg/task/restore.go
br/pkg/task/stream.go

Issue Number: close #61728 close #61731
the incomplete metakv cannot be restored
skip the incomplete metakv
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: skip incomplete metakv

---

pkg/infoschema/tables.go

Issue Number: close #61483
The SELECT * FROM INFORMATION_SCHEMA.CLUSTER_INFO query internally uses GetClusterServerInfo, which collects node information from various TiDB components. Each node address is resolved using ResolveLoopBackAddr(), but this was previously done sequentially, resulting in slow performance on large clusters.
- Inside the loop over cluster retrievers, each node's ResolveLoopBackAddr() is now executed in a separate goroutine.
- A sync.WaitGroup ensures that all address resolutions complete before appending nodes to the final servers list.
- Care is taken to avoid pointer capture issues inside the goroutine by copying the loop variable.
- This significantly reduces overall resolution time for clusters with many nodes.
This results in a noticeable …

infoschema: optimize cluster info retrieval using concurrency

---

pkg/bindinfo/BUILD.bazel
pkg/bindinfo/binding_auto.go
pkg/bindinfo/binding_auto_test.go
pkg/bindinfo/binding_plan_generation.go
pkg/executor/adapter.go
pkg/executor/show.go
pkg/executor/test/executor/executor_test.go
pkg/parser/parser.y
pkg/planner/BUILD.bazel
pkg/planner/core/common_plans.go
pkg/planner/optimize.go
pkg/sessionctx/stmtctx/stmtctx.go

Issue Number: ref #60148
Problem Summary: planner: support "explain explore analyze" when exploring new plans offline
Support "analyze" mode in "explain explore", which will run all generated plans to get their execution info to help users make the plan choice decision.
The main idea is to execute all generated plans when running `explain explore`, and get their execution info from `sctx`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: support "explain explore analyze" when exploring new plans offline

---

pkg/privilege/privileges/privileges.go
pkg/privilege/privileges/privileges_test.go

Issue Number: close #61790
When `max_user_connections` was introduced in https://github.com/pingcap/tidb/pull/59197, the privilege system didn't consider `skip-grant-table`, which skips loading the privilege system.
If `skip-grant-table` is true, do not query `max_user_connections` and directly return.
I've checked other functions in `UserPrivileges`, no other similar problems.
It's introduced in v9.0.0-beta.1 so it doesn't need a release note.
Tests 
> 
Steps:
1. Start a TiDB instance with configuration `security.skip-grant-table` and OS root privilege.
2. Connect to TiDB with `mysql -h127.1 -uroot -P4000`
Side effects
Documentation …

privileges: fix TiDB panic when `security.skip-grant-table` is true

---

pkg/executor/analyze_col_v2.go

Issue Number: close #61785 
The issue is that customers have observed higher I/O consumption when the   analyze   operation reaches the index, compared to when it analyzes regular tables. (The   analyze   status contains sensitive information, so it will not be included here.)
The root cause of the issue lies in improper coding practices. When we perform the   analyze   operation, we create multiple concurrent tasks to execute it. However, within these concurrently spawned goroutines, we further create additional concurrency. This nested concurrency results in an actual level of parallelism that is significantly higher than we anticipated.
```
CREATE TABLE `test` (
`c1` binary(16) NOT NULL,
`c2` tinyint(1) NOT NULL DEFAULT '0',
`c3` int NOT NULL,
`c4` varchar(48) COLLATE …
```

planner: avoid exceeding the configured concurrency limit

---

pkg/executor/adapter.go
pkg/executor/executor.go
pkg/executor/executor_test.go

Issue Number: ref #61612
This is a manual cherry-pick for https://github.com/pingcap/tidb/pull/55537, which add panic handle logic for `WorkerPool`.
This PR only pick codes related to fast admin check back to release7.5, i.e. handle panic for `checkIndexTask`, to avoid check pass when underlying SQLs meet panic.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: handle panic for fast admin check

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/property/physical_property.go

Issue Number: close https://github.com/pingcap/tidb/issues/28812
rejectSort was previously introduced ignore meaningless sort operator when planning mpp plans (because tiflash node can not support sort operator, once there is one sort operator across mpp plan, like in the middle, the whole plan tree can not be pushed to tiflash at all), currently, tidb itself can eliminate most meaningless sort operator in logical phase, so the former hack way which introduced in https://github.com/pingcap/tidb/pull/28924 can be removed. But previously introduced test is kept which is used to show that tidb currently has the ability to eliminate redundant logic sort which can get access to the same effect as before.
Tests 
> 
Side …

planner: remove rejectSort field of physical property

---

pkg/ddl/BUILD.bazel
pkg/ddl/ddl_tiflash_api.go
pkg/domain/infosync/info.go
pkg/domain/infosync/tiflash_manager.go

Issue Number: Close #61864
See the issue.
Added a `syncer` to placement rules.
Tests 
1. Create a test table.
```sql
create table test(pk varchar(200) PRIMARY KEY CLUSTERED, note text, id int);
```
2. Add TiFlash replica for it.
```sql
alter table test set tiflash replica 1;
```
3. Restore to another keyspace with the backup.
```
/cse-ctl restore keyspace --name 20250620/074700.meta --target-keyspace-name celestial --keyspace-name aqua --pd cse-ks3-pd:2379 --config /etc/tikv/tikv.toml
```
4. Start TiDB in the new keyspace. (path = `.spec`)
```yaml
tidb:
baseImage: hub-new.pingcap.net/br/tidb/tispace/pick-refresh-tiflash
config: |
enable-telemetry = false
keyspace-name = "celestial"
[log]
[log.file]
max-backups = 3
version: "250620173342"
```
5. After TiDB started, check …

ddl: refresh TiFlash PlacementRules periodically

---

pkg/infoschema/tables.go

Issue Number: close #56057
Problem Summary: The `plan_hint` column type is currently a `VARCHAR(64)`, but plan hints are not limited to 64 characters and may exceed this size. Normally this would raise a "Data Too Long" warning and truncate the column value, but due to #60330, internal memtable column values are not type checked.
Change the `plan_hint` column type to `text` instead.
Tests 
> 
Side effects
Documentation
```release-note
None
```

stmtsummary: change `plan_hint` column type to `text`

---

pkg/statistics/handle/globalstats/global_stats_internal_test.go

Issue Number: close #61901 
Disabled auto_analyze in test because it can accidentally break the test if auto analyze executes before the manual analyze. The test first requires plans to be chosen without statistics, and then later executes ANALYZE to test plans with statistics. Auto analyze can therefore disrupt this test and make it unpredictable.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: Fix flaky TestGlobalStatsAndSQLBindingWithConcurrency

---

pkg/session/bootstrap.go
pkg/session/bootstrap_test.go

Issue Number: close #61884
Tests 
```
Modified v7.5.6 and let it create a mysql.global_variables table with clustered index.
Run v8.5.2 to upgrade the cluster, before this PR, it will failed. After this PR, cluster start up success.
```
> 
Side effects
Documentation
```release-note
None
```

session: fix `initGlobalVariableIfNotExists` function forget call rs.close

---

pkg/ddl/db_test.go
pkg/executor/test/admintest/admin_test.go
pkg/executor/test/executor/executor_test.go
pkg/planner/core/planbuilder.go
tests/integrationtest/r/ddl/foreign_key.result
tests/integrationtest/t/ddl/foreign_key.test

Issue Number: close #61827
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: report error when admin check on multiple tables | tidb-test=pr/2534

---

pkg/session/session.go

Issue Number: close #61899.
Update `GetDistSQLCtx` to check and align the `RunawayChecker` in the cached DistSQL context with the session's current value.
Tests 
Prepare:
```sql
create table t1(a int, b int);
insert into t1 value(rand()*1000, rand()*1000); x 44600
mysql> select count(*) from t1;
+----------+
| count(*) |
+----------+
|    44600 |
+----------+
1 row in set (0.01 sec)
mysql> CREATE RESOURCE GROUP IF NOT EXISTS rg1 RU_PER_SEC = 100 QUERY_LIMIT=(RU=10, ACTION=KILL);
Query OK, 0 rows affected (0.06 sec)
mysql> SET RESOURCE GROUP rg1;
Query OK, 0 rows affected (0.00 sec)
```
Before:
```sql
mysql> explain analyze select * from t1 where b > 36;
ERROR 8253 (HY000): Query execution was interrupted, identified as runaway query [RequestUnit = RRU:13.419626, WRU:0.000000, …
```

fix(runaway): ensure DistSQLContext's checker is synchronized with session variables

---

executor/aggregate.go
executor/hash_table.go
executor/join.go
executor/test/issue_test/BUILD.bazel
executor/test/issue_test/executor_issue_test.go
parser/terror/terror.go

Issue Number: ref #60926
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix goroutine leak when exceeding quota in `Close`

---

pkg/bindinfo/BUILD.bazel
pkg/bindinfo/binding_auto_test.go
pkg/parser/ast/misc.go
pkg/parser/parser.y
pkg/parser/parser_test.go
pkg/planner/core/BUILD.bazel
pkg/planner/core/common_plans.go
pkg/planner/core/planbuilder.go

Issue Number: ref #60148
Problem Summary: planner: support `explain [analyze] <plan_digest>` for `explain explore`
Support `explain [analyze] <plan_digest>` for `explain explore` to make it easier to use.
An example is shown blow:
Changes:
1. support the new syntax `explain [analyze] <sql_digest>`
2. add 2 new columns in the output of `explain explore`
3. fill necessary statement information for explain in `getHintedStmtThroughPlanDigest`
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: support `explain [analyze] <plan_digest>` for `explain explore`

---

CONTRIBUTORS.md

As diff fix a dead link and the same as https://github.com/pingcap/docs/blob/885805fa1a37a375a47d5370f4c57d5c908dac3d/credits.md?plain=1#L14
Tests 
> 
Side effects
Documentation
```release-note
None
```

docs: fix a dead link in CONTRIBUTORS.md

---

pkg/ddl/foreign_key.go
pkg/sessionctx/variable/session.go

Issue Number: ref https://github.com/pingcap/tidb/issues/40111
Old bugfix has problem. The root cause is the uninit system variable.
Tests 
in the origin Bugfix [PR](https://github.com/pingcap/tidb/pull/40112)，```TestAddForeignKeyInBigTable``` is for testing this problem.
> 
Side effects
Documentation
```release-note
None
```

planner,ddl: rightly fix issue of add foreign key too slow in big table

---

Makefile

This patch fix the 61966 that use the same version from go.mod for the same version
make the `make  check-static` work again(but not happy for now)
also this patch get the `version` from go.mod file aim to avoid this kind of issue again
another work is add it to `make help` that can show in `make help`
but for now when run `make check-static` will got bunch of unhappy errror which is I do
not sure need to fix, so just fix the `Make`
cc @zimulala 
Issue Number: close #61966
Tests 
> 
Side effects
Documentation
```release-note
None
```

fix: fix golint version in make file to make check-static happy

---

pkg/planner/core/point_get_plan.go
pkg/util/ranger/detacher.go
tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result
tests/integrationtest/t/planner/core/casetest/partition/partition_pruner.test

Issue Number: close #61965, close https://github.com/pingcap/tidb/issues/59827
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix `PointGetPlan.PrunePartitions` function works with non-binary collate

---

cmd/tidb-server/main.go

Issue Number: close #62096
Problem Summary: I did not notice messages in back quotes will be placed right after the flag
```
-redact ./tidb-server --redact=xxx collect-log <input> <output>
remove sensitive words from marked tidb logs, if ./tidb-server --redact=xxx collect-log <input> <output> subcommand is used (default false)
```
to 
```
-redact
remove sensitive words from marked tidb logs when using collect-log subcommand, e.g. ./tidb-server --redact=xxx collect-log <input> <output> (default false)
```
Tests 
> 
Side effects
Documentation
```release-note …
```

tidb-server: reword command message

---

pkg/disttask/importinto/job_testkit_test.go
pkg/domain/crossks/cross_ks_test.go
pkg/testkit/mockstore.go

```
// in nextgen, SYSTEM ks must be bootstrapped first, to make UT easier, we
// always run them inside SYSTEM keyspace, if your test requires bootstrapping
// multiple keyspace, you should use CreateMockStoreAndDomainForKS instead.
```
Tests 
choose random test that uses `CreateMockStoreAndDomain` and `CreateMockStoreWithSchemaLease`, and run with `nextgen` tags, all success
> 
Side effects
Documentation
```release-note
None
```

testkit: make ut works in nextgen after introduce SYSTEM ks

---

pkg/ddl/executor.go
pkg/privilege/BUILD.bazel
pkg/privilege/privilege.go
pkg/privilege/privileges/BUILD.bazel
pkg/privilege/privileges/cache.go
pkg/privilege/privileges/cache_test.go
pkg/privilege/privileges/privileges.go
pkg/privilege/privileges/tidb_auth_token_test.go

Issue Number: ref #61706
* Pick #58945, replace array and map in `MySQLPrivilege` with btree
* Refactor `FetchColumnPrivileges`, `FetchTablePrivileges` and `FetchSchemaPrivileges` to reuse `fetchPrivilege`
Related mysql test: https://github.com/PingCAP-QE/tidb-test/pull/2543
Tests 
> 
Side effects
Documentation
```release-note
None
```

privilege/privileges: refactor the data struct for user privilege data | tidb-test=pr/2543

---

pkg/parser/charset/encoding_base.go
pkg/parser/digester.go
pkg/util/chunk/codec.go
pkg/util/chunk/column.go
pkg/util/context/warn_test.go
pkg/util/rowcodec/common.go

follow #61952 another part
fix: reflect.SliceHeader is deprecated: Use unsafe.Slice or unsafe.SliceData instead.
Issue Number: close #62129
Tests 
> 
Side effects
Documentation
```release-note
None
```

fix: reflect.SliceHeader is deprecated: Use slice instead.

---

lightning/pkg/importer/import.go
lightning/pkg/importer/meta_manager_test.go
pkg/disttask/importinto/subtask_executor.go
pkg/lightning/backend/local/checksum.go
pkg/lightning/backend/local/checksum_test.go

Issue Number: ref #61702, close #62142
send a request with TTL=0 to remove it, see https://github.com/tikv/pd/blob/29ead019cd0982a3120bc79d4a4d19199dab2279/server/grpc_service.go#L2280-L2284 too
Tests 
with master, we can see the service safe point still exist after lightning exist, it will expire after 10m
```
➜  lightning /Users/user/code/pingcap/tidb/bin/tidb-lightning-master --config test.toml
Verbose debug logs will be written to lightning.log
tidb lightning exit successfully
➜  lightning etcdctl --endpoints localhost:2379 get --prefix ""|grep -a lightning
/pd/7522392937985088901/gc/safe_point/service/lightning-c8a20fff-07bd-4744-bfa5-a12e529847c5
{"service_id":"lightning-c8a20fff-07bd-4744-bfa5-a12e529847c5","expired_at":1751444458,"safe_point":459130498717057084} …
```

localbackend: release the service safe point on finish checksum

---

pkg/parser/digester.go
pkg/parser/digester_test.go

Issue Number: close #58447
Problem Summary:  `_charset ?, _charset ?`, i.e. list of literal with charset will be converted to `...`
Tests 
> 
Side effects
Documentation
```release-note
None
```

parser: also reduce literal list with charset

---

pkg/util/codec/codec.go
pkg/util/codec/codec_test.go
tests/integrationtest/r/executor/aggregate.result
tests/integrationtest/t/executor/aggregate.test

Issue Number: close #61735 
The `HashGroupKey` didn't return a valid `buf` with the error. Therefore, if the error is ignored (or regarded as a warning), the `buf` cannot be accessed. Ref https://github.com/pingcap/tidb/pull/48613/files#diff-6215f2010e82b5ba1c5dd0158b1026512071abe70470ba50eb3055d37b8f5eeeL1262-L1271. Previously, `HashGroupKey` handle the error inside the function, so it'll not have this issue. PR #48613 refactored it to handling the error outside, which cause this issue.
Return a valid buf with the error in `HashGroupKey`.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) …

codec: should also return the value even with error because the error may be ignored in the future

---

pkg/ddl/notifier/subscribe.go
pkg/executor/test/distsqltest/BUILD.bazel

Issue Number: ref #60842 
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: cannot panic with failpoint panic in the DDLNotifier

---

pkg/domain/domain.go

Issue Number: close #62197
See https://github.com/pingcap/tidb/issues/62197#issue-3199721449
Wait for statistics owner to close on exit.
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: wait for statistics owner to close on exit

---

pkg/domain/domain.go
pkg/domain/runaway.go
pkg/executor/internal/querywatch/query_watch_test.go
pkg/resourcegroup/runaway/manager.go
pkg/resourcegroup/runaway/syncer.go
pkg/resourcegroup/tests/resource_group_test.go

Issue Number: close #61782.
Revert #52283 and implement a simpler method to prevent error logs.
Tests 
Mannually modify `maxWatchRecordChannelSize` to 10 to ensure easier triggering.
Before:
After:
```release-note
Resolve the issue causing system table read/write operations related to runaways to hang after restarting TiDB instance.
```

fix(runaway): resolve the dead channel in UpdateNewAndDoneWatch

---

pkg/planner/core/base/plan_base.go
pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/find_best_task.go
pkg/planner/core/operator/logicalop/base_logical_plan.go
pkg/planner/core/operator/logicalop/logical_plans_misc.go

Issue Number: ref https://github.com/pingcap/tidb/issues/62006
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: deprecate the logical interface CanPushToCop and its implementation canPushToCopImpl.

---

pkg/planner/core/exhaust_physical_plans.go
pkg/planner/core/operator/logicalop/logical_aggregation.go
pkg/planner/property/physical_property.go

Issue Number: ref https://github.com/pingcap/tidb/issues/62006
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: use prop based noCopPushDown mechanism to replace aggregation field.

---

br/pkg/storage/gcs.go
br/pkg/storage/gcs_test.go
pkg/util/prefetch/reader.go
pkg/util/prefetch/reader_test.go

This PR manually cherry-picks two PRs to `release-8.5` to resolve a dependency.
---
cherry-pick #59496
cherry-pick #59851
Issue Number: close #59495, close #59754
This PR addresses two separate but related issues:
1. The prefetch buffer was not always being fully filled, potentially leading to inefficient reads.
2. A bug in Go's `net/http` library can cause `io.EOF` errors when using GCS, which were not being retried, causing operations to fail.
1.  **Prefetch Buffer Fix:** Switched to using `io.ReadFull` to ensure the prefetch buffer is always filled completely.
2.  **GCS EOF Retry:** Added a workaround in the GCS storage layer to specifically retry on `io.EOF` errors, making the connection more resilient to the underlying library bug.
Tests 
```release-note
None
```

release-8.5: Fix prefetch buffer and GCS EOF retry (#59496, #59851)

---

pkg/expression/util.go
tests/integrationtest/r/expression/issues.result
tests/integrationtest/t/expression/issues.test

Issue Number: close #56772
In the `expression rewriting` process, when constructing the condition `t1.col1 + 10 > ? + 10`, the argument `? + 10` will go through `argument refinement`, and the final result is set to` NULL`. The type of NULL is determined as `int.` 
Then, the method signature for` t1.col1 + 10 > ? + 10` is set to `builtinArithmeticPlusIntSig`. But the `DeferredExpr` for the expression `plus(NULL, 10)` is not removed, which results in a conflict method signature of `builtinArithmeticPlusRealSig`, 
which cannot handle int types. This leads to an error during execution.
`RemoveMutableConst():` will not traverse all the expressions.
https://github.com/pingcap/tidb/blob/8ecdb54c51a156a40ad1c84215af424dc55add41/pkg/expression/util.go#L1583-L1602
I modified the …

planner: Fix expression rewriting and method signature mismatch in plan cache

---

br/pkg/storage/s3.go
br/pkg/storage/s3_test.go

Issue Number: close #55568
For buckets created after January 1, 2024, the use of path-style domain is not supported, only virtual-hosted-style domain is permitted.
https://www.tencentcloud.com/document/product/436/57456
disable ForcePathStyle and use virtual-hosted-style for Tencent Cloud
Tests 
> 
Side effects
Documentation
```release-note
br: always set ForcePathStyle=false for s3 compatible Tencent Cloud provider
```

br: always set ForcePathStyle=false for s3 compatible Tencent Cloud provider

---

pkg/domain/crossks/BUILD.bazel
pkg/domain/crossks/cross_ks.go
pkg/domain/crossks/cross_ks_test.go
pkg/infoschema/issyncer/BUILD.bazel
pkg/infoschema/issyncer/loader.go
pkg/planner/core/planbuilder.go
pkg/planner/planctx/context.go
pkg/session/session.go
pkg/sessionctx/context.go
pkg/util/mock/context.go

cross ks sessions are only allowed to read/write system tables of target ks, we enforce this rule in this pr
Tests 
> 
Side effects
Documentation
```release-note
None
```

crossks: forbid cross ks session to access user tables and run DDL

---

pkg/planner/core/casetest/physicalplantest/BUILD.bazel
pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
pkg/planner/core/casetest/physicalplantest/testdata/cascades_template_in.json
pkg/planner/core/casetest/physicalplantest/testdata/cascades_template_out.json
pkg/planner/core/casetest/physicalplantest/testdata/cascades_template_xut.json
pkg/planner/core/rule_partition_processor.go

Issue Number: close #62331 
Since PR [#61571](https://github.com/pingcap/tidb/pull/61571), `applyPredicateSimplification` invokes `PropagateConstant`. Then`ds.AllConds` and `ds.PushedDownConds` may not kept in sync after `rule.PartitionProcessor`, it will cause a nil pointer panic.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: fix sql with static partition pruning mode got nil pointer error

---

pkg/planner/core/logical_plan_builder.go
pkg/table/tables/tables_test.go
tests/integrationtest/r/planner/core/integration.result
tests/integrationtest/t/planner/core/integration.test

Issue Number: close #62350
The following sql will fail to execute
```
create table t (col timestamp);
select cast(col as char) from t group by cast(col as char);
```
1. Split the function `resolveGbyExpr` into two parts, the first one to do the resolve and the second one to rewrite the expression
Previously, the order of check and resolve is like this:
```
┌───────────────────────────────────────────────────────────┐     
│SELECT CAST(col as char) FROM t GROUP BY CAST(col as char);│     
└──┬────────────────────────────────────────────────────────┘     
│                                                              
│RESOLVE                                                       
│                                                              
▼ …
```

planner: fix the issue that the group by check not allow `cast` expr in both projection and group by | tidb-test=pr/2555

---

pkg/executor/join/hash_join_v1.go
pkg/executor/join/hash_table_v1.go
pkg/executor/test/issuetest/executor_issue_test.go

Issue Number: close #62351
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: log error in the Close of joinv1 instead of returning it

---

pkg/ddl/backfilling_operators.go
tests/realtikvtest/addindextest2/global_sort_test.go

This is the cherry-pick PR for #59898,
Issue Number: close #59897
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: fix job's row count for global sort (#59898)

---

pkg/lightning/backend/external/engine.go
pkg/lightning/backend/external/split.go

Issue Number: close #62388
consider the memory taken by slice header when splitting range
Tests 
same case in the issue, before this pr, 2 out of 3 runs stuck. after this pr, we run 10 times, all success.
> 
Side effects
Documentation
```release-note
None
```

globalsort: fix stuck when ingesting small kv

---

br/pkg/storage/gcs.go
br/pkg/storage/gcs_test.go
pkg/util/prefetch/reader.go
pkg/util/prefetch/reader_test.go

This PR manually cherry-picks two PRs to `release-8.1` to resolve a dependency.
---
cherry-pick #59496
cherry-pick #59851
Issue Number: close #59495, close #59754
This PR addresses two separate but related issues:
1. The prefetch buffer was not always being fully filled, potentially leading to inefficient reads.
2. A bug in Go's `net/http` library can cause `io.EOF` errors when using GCS, which were not being retried, causing operations to fail.
1.  **Prefetch Buffer Fix:** Switched to using `io.ReadFull` to ensure the prefetch buffer is always filled completely.
2.  **GCS EOF Retry:** Added a workaround in the GCS storage layer to specifically retry on `io.EOF` errors, making the connection more resilient to the underlying library bug.
Tests 
```release-note
None
```

release-8.1: Fix prefetch buffer and GCS EOF retry (#59496, #59851)

---

pkg/statistics/histogram.go

Issue Number: ref #62093
Previous usage of tidb_opt_risk_range_skew_ratio for skew within a bucket didn't filter out scenarios where the predicate bounds were out of range. Added check so this skew ratio only applies when at least part of the range predicate is within the histogram range. 
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: add check for skew risk ratio within a bucket | tidb-test=pr/2564

---

br/cmd/br/abort.go
br/pkg/task/restore.go
br/tests/br_parallel_restore/run.sh
br/tests/config/pd.toml

Issue Number: close #62357
Update keyspace when user passes in
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: add keyspace support for br abort command

---

pkg/disttask/framework/integrationtests/resource_control_test.go

Issue Number: close #61354
after we continue all running subtasks, they finish, and scheduler will try to schedule left subtasks immediately, so the active running subtask count might be in range `[0, 4]`, `c.waitTotalSubtaskCount(0)` night not hold, so change to another way to check
Tests 
> 
Side effects
Documentation
```release-note
None
```

dxf: fix flaky test TestResourceControl/scale-in

---

pkg/disttask/framework/handle/BUILD.bazel
pkg/disttask/framework/handle/handle.go
pkg/executor/test/fktest/foreign_key_test.go
pkg/planner/core/BUILD.bazel
pkg/planner/core/plan_cost_ver2_test.go
pkg/sessiontxn/BUILD.bazel
pkg/sessiontxn/txn_manager_test.go
pkg/statistics/asyncload/BUILD.bazel
pkg/statistics/asyncload/async_load_test.go
tests/realtikvtest/BUILD.bazel
tests/realtikvtest/addindextest1/BUILD.bazel
tests/realtikvtest/addindextest1/cross_ks_test.go
tests/realtikvtest/addindextest4/failure_test.go
tests/realtikvtest/importintotest3/cross_ks_test.go
tests/realtikvtest/pessimistictest/pessimistic_test.go
tests/realtikvtest/testkit.go

Tests 
> 
Side effects
Documentation
```release-note
None
```

tests: add create index realtikv test for next_gen

---

.gitignore
pkg/planner/optimize.go
pkg/session/resourcegrouptest/resource_group_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/62361
Tests 
> 
```release-note
None
```

*: fix the issue about the case-insensitive in resource group hint

---

Makefile

if make ut fails it only run FAILPOINT_DISABLE but not run CLEAN_UT_BINARY
then exit 1
this patch fix it, and also fix some other issues like this
cc @lance6716 
Issue Number: close #62088
Tests 
> 
Side effects
Documentation
```release-note
None
```

fix: close issue #62088 do not generate trash files when ut fails

---

pkg/domain/BUILD.bazel
pkg/domain/domain.go

in https://github.com/pingcap/tidb/pull/51575, we add the memory adjust for cgroups v2, as we think the memory got from `MemTotal` is not accurate on it, but now i found the memory we got from `MemTotal` is controlled by the `resource limit` of the pod.
so we can remove the adjustment, and use pod spec control it. the max limit memory can be set for a pod need also consider the reserved space by k8s, see https://learnk8s.io/allocatable-resources
Tests 
below is the result tested on a 8c16g node, before this PR, we can see we set the pod limit to `13208 MiB/1024 = 12.9 GiB`
```
resources:
limits:
cpu: "7"
memory: 13208Mi
requests:
cpu: "7"
memory: 13208Mi
```
and from the log of tidb, we can see, the memory we got is also `12.9GiB`, and we adjusted …

dxf: remove memory adjust for cgoups v2

---

pkg/planner/core/rule/BUILD.bazel
pkg/planner/core/rule/rule_build_key_info.go

Issue Number: close #62526
1、reuse slices and refrain from allocating the memory frequantly
2、this slices will not use in the logical ops's buildKeyInfo
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: reuse slices with buildKeyInfo

---

pkg/bindinfo/binding_auto.go
pkg/bindinfo/binding_auto_test.go

Issue Number: ref #60148 
Problem Summary: Empty plans are currently considered simple point plans, which is incorrect. (Passing empty plans to this function indicates other issues, but those are out of scope for this PR.)
Modify `bindinfo.IsSimplePointPlan` to check for empty plans (or plans that only consist of whitespace), and modify `TestIsSimplePointPlan` to exercise this case.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: don't consider an empty plan a simple point plan

---

pkg/meta/autoid/autoid_service.go

Issue Number: close #61987
reducing backoff from 250 ms to 5 ms and adding retry if leader is not assigned in etcd.
Tests 
> 
Side effects
Documentation
```release-note
None
```
test results

meta/autoid:  reduce get autoID's backoff

---

pkg/ddl/create_table.go
pkg/ddl/db_table_test.go
pkg/ddl/executor.go
pkg/ddl/table.go
pkg/ddl/tests/fastcreatetable/fastcreatetable_test.go

Issue Number: close #60804
Previously, the procedure of (batch) creating table is as follow:
- submitter submit the job and wait it finished
- ddl owner execute the job and mark table as public
- submitter pre-scatter the table and update the auto id.
But if the submitter quit before waiting job finished, the post process will be skipped. So the creation itself is **not atomic**.
Now ddl owner takes the responsibility to update auto id and submitter only needs to pre-scatter the table.
https://github.com/pingcap/tidb/blob/1f24032d4e641c38fbd0e72b036bf5f679b809b0/pkg/ddl/job_submitter.go#L224-L227
Because merged ddl job only holds the session variables from the first job for now, which means all jobs share the same variables, we don't apply pre-scatter in ddl owner.
Tests …

ddl: move auto id handling from submitter to executor

---

pkg/planner/core/plan_cache.go
pkg/planner/core/plan_cache_rebuild.go
pkg/planner/optimize.go
pkg/session/session.go
pkg/sessionctx/stmtctx/stmtctx.go
pkg/util/mock/context.go

Issue Number: ref #61876
The InPreparedPlanBuilding member from StatementContext is no longer needed.  There used to be indirect recursive calls to the planner.Optimize function and the InPreparedPlanBuilding member was set to prevent infinite recursion, but this indirect recursion has been removed.
This pull request removes InPreparedPlanBuilding member from StatementContext.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: Remove InPreparedPlanBuilding member from StatementContext.

---

pkg/domain/domain.go
pkg/domain/runaway.go

Issue Number: close #62577
Use atomic point for the `resourceGroupsController` in Domain to avoid data race.
Tests 
> 
Side effects
Documentation
```release-note
None
```

domain: fix data race in ResourceGroupsController unit test

---

pkg/config/BUILD.bazel
pkg/config/config.go

Issue Number: close #62502
```
config: pessimistic-auto-commit defaults to true for next-gen TiDB
```
Tests 
> 
Side effects
Documentation
```release-note
config: pessimistic-auto-commit defaults to true for next-gen TiDB
```

config: pessimistic-auto-commit defaults to true for next-gen TiDB

---

pkg/util/ranger/context/context.go
pkg/util/ranger/context/context_test.go
pkg/util/ranger/ranger.go

Issue Number: ref #61876
The InPreparedPlanBuilding member was removed from StatementContext in a previous patch, so the InPreparedPlanBuilding member in RangerContext will no longer be set correctly.  As a result, the code in ranger.convertPoint will not call SetSkipPlanCache as needed when there is an error, which could result in caching ineligible plans.  Since it is safe to call SetSkipPlanCache even if the code was not reached via the plan cache code, we can fix this by just removing the enclosing if statement.
This pull request removes the InPreparedPlanBuilding member from RangerContext, and changes ranger.convertPoint to call sctx.SetSkipPlanCache without checking whether the plan could potentially be cached.
Tests 
> - [ ] I checked and no code files have been …

planner: Remove InPreparedPlanBuilding member from RangerContext

---

br/tests/br_z_gc_safepoint/run.sh

Issue Number: close https://github.com/pingcap/tidb/issues/62610
Now, pd server won't have 0 value safepoint any more.
remove unnecessary gc operation in test
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: remove unnecessary gc setting after update pd client

---

pkg/bindinfo/binding_auto.go
pkg/executor/builder.go
pkg/executor/show.go
pkg/parser/ast/dml.go
pkg/parser/parser.y
pkg/parser/parser_test.go
pkg/planner/core/operator/logicalop/logical_show.go
pkg/planner/core/planbuilder.go

Issue Number: ref #60148 
Problem Summary: `SHOW PLAN FOR <SQL>` was an early iteration of the SQL syntax for SPM, but has now been supplanted by the `EXPLAIN EXPLORE <SQL>` syntax. 
Delete `ShowPlanForSQL` and related `SQLOrDigest` fields from the parser and the implementation of the `SHOW` SQL statement, and update tests accordingly.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: remove "SHOW PLAN FOR <SQL>" syntax

---

pkg/distsql/distsql.go
pkg/executor/test/executor/BUILD.bazel
pkg/executor/test/executor/executor_test.go

Issue Number: ref #56311
The test TestIssue48756 was reported as failing rarely. Since pull request #57522 was merged, it now fails every time. Originally issue #56311 was prioritized low because the problem was hard to reproduce. Now it's easy to reproduce, but the existing test fails to exercise the "lite" coprocessor path added in that pull request.
This commit adds a failpoint that sets the TryCopLiteWorker option in distsql.Select(), and runs test case "TestIssue48756" twice: once with, and once without, the "lite" coprocessor option. One of the two paths consistently fails, as described in issue #56311, so this change reproduces the failure.
Tests 
> 
Side effects
Documentation
```release-note
Add a unit test …
```

pkg/distsql: Add failpoint so TestIssue48756 can run with and without CopLiteWorker

---

dumpling/export/config.go
dumpling/export/util.go
pkg/planner/core/partition_pruning_test.go
pkg/store/mockstore/unistore/cophandler/cop_handler_test.go

In the Go 1.21 standard library, a new function has been introduced that enhances code conciseness and readability. It can be find  [here](https://pkg.go.dev/slices@go1.21.1#Equal).
Tests 
> 
Side effects
Documentation
```release-note
None
```

refactor: use slices.Equal to simplify code

---

pkg/util/sem/sem.go
pkg/util/sem/sem_test.go

Issue Number: close #62583
The variable `tidb_service_scope` is not controlled by SEM.
Add `tidb_service_scope` to the list of SEM.
Tests 
> 
```
mysql> set global tidb_service_scope = 'background';
ERROR 1227 (42000): Access denied; you need (at least one of) the RESTRICTED_VARIABLES_ADMIN privilege(s) for this operation
mysql> select @@tidb_service_scope;
ERROR 1227 (42000): Access denied; you need (at least one of) the RESTRICTED_VARIABLES_ADMIN privilege(s) for this operation
```
Side effects
Documentation
```release-note
None
```

sem: add `tidb_service_scope` to SEM hidden variable list

---

pkg/planner/core/plan_cacheable_checker.go
pkg/util/filter/BUILD.bazel
pkg/util/filter/schema.go
pkg/util/filter/schema_test.go

Issue Number: close #62658
no need to always convert dbname to lowercase in IsSystemSchema. Each input is lowercase
Tests 
> 
Side effects
Documentation
```release-note
None
```

filter: no need to always convert dbname to lowercase in IsSystemSchema

---

pkg/bindinfo/binding.go
pkg/planner/core/plan_cache_test.go
pkg/planner/core/plan_cache_utils.go
pkg/planner/core/plan_cacheable_checker.go
pkg/planner/core/plan_cacheable_checker_test.go
pkg/planner/optimize.go
pkg/util/hint/hint.go
pkg/util/stmtsummary/v2/tests/table_test.go
tests/integrationtest/r/planner/core/plan_cache.result
tests/integrationtest/r/planner/core/tests/prepare/prepare.result
tests/integrationtest/t/planner/core/tests/prepare/prepare.test

Issue Number: close #62634
The 'ignore_plan_cache' hint does not work for non-prepared queries.
This pull request:
* removes the binding specific 'ignore_plan_cache' hint check,
* removes the prepared statement specific 'ignore_plan_cache' hint check,
* adds code to check for the 'ignore_plan_cache' hint to optimizeNoCache,
* and adds a test for non-prepared statements.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: Implement ignore_plan_cache hint for non-prepared statements.

---

pkg/domain/domain.go
pkg/statistics/handle/autoanalyze/autoanalyze.go

Issue Number: ref https://github.com/pingcap/tidb/issues/59939
We should provide more information before we conduct the process of killing. Otherwise, it is very difficult to know if it is an active kill or if it was caused by other reasons.
Tests 
> 
Side effects
Documentation
```release-note
在 auto-analyze 被 kill 的时候打印日志
Print logs when auto-analyze is killed
```

domain: log warning when killing auto analyze processes that exceed the time window

---

pkg/planner/core/collect_column_stats_usage.go
pkg/planner/core/optimizer.go
pkg/planner/core/rule_collect_plan_stats.go
pkg/sessionctx/variable/session.go
pkg/ttl/ttlworker/session.go
pkg/ttl/ttlworker/session_integration_test.go

Issue Number: close #61822
The TTL scan is different from our other internal SQL, as it reads user tables. So, our previous approach of determining whether to perform sync load based on whether it is internal SQL has issues.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: TTL scan can trigger sync/async load/generateRuntimeFilter

---

pkg/ddl/db_rename_test.go
pkg/executor/show_ddl_jobs.go

Issue Number: close #46897
For `RENAME TABLE`, we store new schema name and old table name in the job, and old schema and new table name are stored in job args. 
And for running jobs, the table/schema name displayed in `ADMIN SHOW DDL JOBS` is get from job. So we will get inconsistent names for running `RENAME TABLE`
I don't want to change the way we store job arguments, since it may arise compatibility issues, so just apply a patch for the outputs.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: show consistent table and schema name for `RENAME TABLE`

---

br/pkg/restore/log_client/client.go
br/pkg/storage/local.go
br/pkg/storage/locking.go
br/pkg/storage/storage.go
br/pkg/stream/stream_metas.go
br/pkg/task/stream.go
br/tests/br_parallel_restore/run.sh

Issue Number: close #62546
change append migration op to acquire read lock instead of write lock so it can works with restore at the same time.
create a new append_lock that append will acquire after acquiring read lock (two phase locking), to prevent multiple append threads to race.
Append migration should work fine with restore as new ssts added will have larger TS that any restore should filter out, effectively invisible to the ongoing restore.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: allow append migration to work with restore

---

pkg/ddl/backfilling_txn_executor.go
pkg/ddl/column_test.go
pkg/ddl/index.go

Issue Number: close #55755
See the issue description.
In `newAddIndexTxnWorker`, if the adding index is triggered by modifying column, only index of `currElement` will be recreated.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: let modify column with multiple indexes recreates index one by one

---

pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
pkg/planner/core/operator/logicalop/logical_partition_union_all.go

Issue Number: close #62764 , ref #62328  #62472
When a partitioned table generates a parent plan using *logicalop.LogicalPartitionUnionAll, it inherits the methods of LogicalUnionAll. 
Tests 
> 
Side effects
Documentation
```release-note
None
```

Cascades Planner: correct plan generation logic for PartitionUnionAll for limit in cascades mode

---

pkg/expression/constant_propagation.go
pkg/planner/cascades/old/transformation_rules.go
pkg/planner/core/operator/logicalop/logical_join.go
tests/integrationtest/r/planner/core/casetest/integration.result
tests/integrationtest/r/planner/core/rule_constant_propagation.result
tests/integrationtest/t/planner/core/rule_constant_propagation.test

Issue Number: close #62536 
close #38662
In an anti join, if the condition column is in the left schema, then this condition can be subject to constant propagation. PgSQL has this kind of optimization.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: constant propagation can deal with anti semi join

---

pkg/planner/cardinality/BUILD.bazel
pkg/planner/cardinality/row_count_column.go
pkg/planner/cardinality/row_count_index.go
pkg/planner/cardinality/selectivity.go
pkg/planner/cardinality/selectivity_test.go
pkg/statistics/histogram.go

Issue Number: close #62665
Like what the linked issue describes, the end value in the last histogram bucket could be underrepresented due to stale stats. This PR tries to detect such case precisely by looking at two conditions:
1.  The value should be in last histogram bucket and it should be the upper bound
2. The last bucket end count is much less than the average count of other NDV, indicating this might be a tail write traffic
After detecting the underrepresented value, instead of passing it back using stale stats from histogram, we reuse the current logic of handling other value by taking the average histogram value count.
Tests 
> 
Side effects
Documentation …

planner: handle histogram last bucket end value underrepresented

---

pkg/server/internal/packetio.go

Issue Number: close #62795
Buffer the zlib writer and zstd encoder because the small object allocations are unacceptable overhead.
Tests 
> 
Run sysbench read-only in fixed rate, the CPU usage of TiDB is optimized from 1300% to 1000%.
```bash
sysbench]$ sysbench --config-file="config" oltp_read_only --tables=1 --table-size=100000000 --rate=1000 --mysql-compression=on run
```
Side effects
Documentation
```release-note
Optimize the performance of connection's traffic compressing.
```

conn: add buffer for zlib & zstd compressor

---

Makefile
Makefile.common
ci.md
tests/integrationtest/README.md
tests/integrationtest/run-tests-next-gen.sh
tests/integrationtest/run-tests.sh
tests/realtikvtest/configs/next-gen/tikv.toml
tests/realtikvtest/scripts/classic/README.md
tests/realtikvtest/scripts/classic/bootstrap-test-with-cluster.sh
tests/realtikvtest/scripts/classic/run-tests-with-gotest.sh
tests/realtikvtest/scripts/classic/run-tests.sh
tests/realtikvtest/scripts/next-gen/README.md
tests/realtikvtest/scripts/next-gen/bootstrap-test-with-cluster.sh
tests/realtikvtest/scripts/next-gen/run-tests-with-gotest.sh
tests/realtikvtest/scripts/next-gen/run-tests.sh

Issue Number: ref #62803
Tests 
> in `pull_integration_realcluster_test_next_gen` job: <img width="1086" height="186" alt="image" src="https://github.com/user-attachments/assets/e8f0edec-d054-4392-844a-dcdca9b5ddf6" /><img width="1080" height="201" alt="image" src="https://github.com/user-attachments/assets/ce10c66f-9aa6-4562-b3ef-8300a58fd5ec" /><img width="1073" height="194" alt="image" src="https://github.com/user-attachments/assets/6b02d6ac-6528-47a3-a292-f4a9fd4b40f6" />
> 
Side effects
Documentation
```release-note
None
```

tests: adjust test scripts for next-gen

---

tests/realtikvtest/scripts/classic/bootstrap-test-with-cluster.sh
tests/realtikvtest/scripts/next-gen/bootstrap-test-with-cluster.sh

Issue Number: ref #62803
- kill `minio` process after tests to avoid process leaking.
- recover for fail-point after testing.
Tests 
> 
Side effects
Documentation
```release-note
None
```

tests: kill minio after tests to avoid process leak

---

pkg/domain/BUILD.bazel
pkg/domain/domain.go

This PR makes DXF use a separate session pool, to avoid other components put bad sessions to the pool and make DXF report errors.
Tests 
> 
Side effects
Documentation
```release-note
None
```

domain: separate session pool for DXF service

---

pkg/util/cgroup/cgroup_memory_unsupport.go

There no such function like `getCgroupMemLimit` on cgroup_memory_unsupport for now
so go test on mac will always fail
This patch mock this function and fix it.
Issue Number: ref #62782
Tests 
> 
Side effects
Documentation
```release-note
None
```

fix: make cgroup run happy on mac

---

pkg/config/BUILD.bazel
pkg/config/config.go
pkg/config/config.toml.nextgen.example
pkg/config/config_test.go
pkg/kv/kv_test.go

Issue Number: close #62702
The default config with/without nextgen is different. The nextgen sets `pessimistic-auto-commit = true` by default. I think we should also provide an example for the default config of nextgen, so I added a `config.toml.nextgen.example` in the same folder. Ref:
Add a `config.toml.nextgen.example`, and use this file if the test is running with nextgen.
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: fix `TestConfig`,`TestResourceGroupTagEncoding` UT for nextgen

---

br/pkg/storage/memstore.go
pkg/disttask/importinto/planner_test.go
pkg/executor/test/indexmergereadtest/BUILD.bazel
pkg/lightning/backend/external/bench_test.go
pkg/lightning/backend/external/byte_reader_test.go
pkg/lightning/backend/external/iter_test.go
pkg/lightning/backend/external/onefile_writer.go
pkg/lightning/backend/external/onefile_writer_test.go
pkg/lightning/backend/external/reader_test.go
pkg/lightning/backend/external/sort_test.go
pkg/lightning/backend/external/split_test.go
pkg/lightning/backend/external/util.go
pkg/lightning/backend/external/util_test.go
pkg/lightning/backend/external/writer.go
pkg/lightning/backend/external/writer_test.go
pkg/statistics/handle/handletest/BUILD.bazel
tests/realtikvtest/addindextest2/global_sort_test.go

Issue Number: close #62904
- this is a manually pick of https://github.com/pingcap/tidb/pull/60816
- we also change the partition prefix schema from hex to binary string, so the partition can response faster as it's binary.
Tests 
intermediate files of importing using global sort, and they are successfully cleanup after it.
```
➜  minio bin/mc ls -r minio/mybucket/gsort
[2025-08-11 12:34:35 CST]   467B STANDARD 2/4/meta.json
[2025-08-11 12:34:34 CST]   194B STANDARD 2/plan/encode/1/meta.json
[2025-08-11 12:34:36 CST]   521B STANDARD 2/plan/ingest/1/meta.json
[2025-08-11 12:34:35 CST]    82B STANDARD p01001100/2/4/data/f3af2ec6-b252-4221-af32-42c5bf12c8cb_stat/0
[2025-08-11 12:34:35 CST]   294B STANDARD p11010101/2/4/data/f3af2ec6-b252-4221-af32-42c5bf12c8cb/0
```
> - [ ] …

globalsort: use partitioned prefix to store intermediate files

---

br/pkg/streamhelper/advancer.go

Issue Number: close #62939
When dropping the advancer, the subscription manager may not get initialized. Then dropping it causes a panic.
Added a guard to prevent dropping a `nil` subscription manager.
Tests 
> The modification is trivial.
> 
Side effects
Documentation
```release-note
None
```

br/streamhelper: added a guard for dropping subscriber

---

pkg/statistics/handle/handle.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/types/interfaces.go
pkg/statistics/handle/usage/session_stats_collect.go

Issue Number: close #62590
based on issue reproduction and memory analysis , the majority of memory waste comes from creating pseudo stats table when doing needDumpStatsDelta check, we can simply use a lightweight approach to solve it without changing too much of the code.
This is happening during millions table workload while dumping stats happens frequently, in the issue mentioned smaller table size should also have same effect but I was unable to reproduce, maybe query creates only limited number of pseudo stats and quickly got GC, whereas dump stats happened for all tables in a burst, causing memory pressure.   
Tests 
> 
Side effects
Documentation …

stats: avoid creating pseudo stats table when dumping stats delta 

---

pkg/executor/adapter.go
pkg/sessionctx/variable/session_test.go
pkg/sessionctx/variable/slow_log.go
pkg/util/execdetails/util.go

Issue Number: close https://github.com/pingcap/tidb/issues/62988
* Remove several `SlowQueryLogItems` fields that get their values directly from `sessVars`
* Remove `GetEncodedPlan`
Tests 
> 
Side effects
Documentation
```release-note
None
```

*: tiny cleanup LogSlowQuery

---

pkg/executor/show_stats.go
pkg/executor/show_stats_test.go
pkg/planner/core/planbuilder.go

Issue Number: ref https://github.com/pingcap/tidb/issues/62685
based on https://github.com/pingcap/tidb/pull/62790
In this PR, we utilize SchemaSimpleTableInfos for the commands `show stats_meta` and `show stats_healthy`, which helps to accelerate the process of retrieving table information.
Additionally, I utilized `ListTablesWithSpecialAttribute` to retrieve information about the partitioned tables, as we still need the relationship between the global table and its partitions. 
After this change, the duration reduced from `5 min 44.55 sec` to `2.3 sec`.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-st …

statistics: use GetNonPseudoPhysicalTableStats to get stats in the show commands

---

cmd/tidb-server/main.go
pkg/autoid_service/BUILD.bazel
pkg/autoid_service/autoid_test.go
pkg/executor/BUILD.bazel
pkg/executor/sample_test.go
pkg/executor/test/infoschema/BUILD.bazel
pkg/executor/test/infoschema/infoschema_test.go
pkg/kv/BUILD.bazel
pkg/kv/unistore.go
pkg/session/BUILD.bazel
pkg/session/bootstrap_test.go
pkg/store/mockstore/mockstore.go
pkg/util/rowcodec/BUILD.bazel
pkg/util/rowcodec/common.go
pkg/util/rowcodec/common_test.go

https://github.com/pingcap/tidb/pull/57865 add the `RemoveKeyspacePrefix` for uni-store, but all integration tests in standalone mode are not using keyspace, it means there are **NO** tests covers the logic in the caller `DecodeRowKey`'s check about keys, i.e at that time there is no key with keyspace.
after https://github.com/pingcap/tidb/pull/62742, we are creating the uni-store with SYSTEM keyspace, so keys will have keyspace prefix, but not removed by `RemoveKeyspacePrefix`, we fix it by introducing a variable `kv.StandAloneTiDB` which is `true` only when run in standalone TiDB, and will remove the keyspace prefix.
we also make the keyspace-meta related test only run in NextGen, Classic kernel doesn't support keyspace.
Tests 
before this PR, …

test: fix standalone TiDB of next-gen report 'invalid key'

---

errors.toml
pkg/ddl/ddl_running_jobs_test.go
pkg/ddl/executor.go
pkg/ddl/executor_test.go
pkg/ddl/job_worker.go
pkg/ddl/schema.go
pkg/ddl/schema_test.go
pkg/errno/errcode.go
pkg/errno/errname.go
pkg/executor/infoschema_reader.go
pkg/executor/show.go
pkg/infoschema/builder.go
pkg/infoschema/infoschema_v2.go
pkg/meta/model/bdr.go
pkg/meta/model/db.go
pkg/meta/model/job.go
pkg/meta/model/job_args.go
pkg/meta/model/job_args_test.go
pkg/planner/core/preprocess.go
pkg/util/dbterror/ddl_terror.go

Issue Number: ref #62122
Support setting databases to a read-only state by DDL. The main points:
* Block the read-only DDL by checking uncommitted transactions, this is achieved by checking the information_schema.cluster_tidb_trx sys table.
* In transactions, check the latest DBInfo if changed before access it.
* Make read-only DDL as Non-replicable DDLs in BDR mode.
* show create database displays the read only status.
Tests 
> 
Side effects
Documentation
```release-note
None
```

ddl: support read only ddl | tidb-test=release-8.5.2

---

pkg/executor/builder.go
pkg/executor/infoschema_reader.go
pkg/executor/infoschema_reader_test.go
pkg/infoschema/tables.go
pkg/planner/core/logical_plan_builder.go
tests/integrationtest/r/ddl/db_read_only.result
tests/integrationtest/t/ddl/db_read_only.test

Issue Number: ref #62122
Add `INFORMATION_SCHEMA.SCHEMATA_EXTENSIONS` system table to check read only state. If the database is at read-only status, query this table will see the `OPTIONS` column has ` READ ONLY=1 ` content, read-write database shows nothing. The structure and content of this system table are consistent with MySQL.
```
mysql> select * from information_schema.schemata_extensions;
+--------------+--------------------+-------------+
| CATALOG_NAME | SCHEMA_NAME        | OPTIONS     |
+--------------+--------------------+-------------+
| def          | db_read_only       |             |
| def          | INFORMATION_SCHEMA |             |
| def          | METRICS_SCHEMA     |             |
| def          | mysql              |             |
| def          | …
```

ddl: add system table INFORMATION_SCHEMA.SCHEMATA_EXTENSIONS to check read only status | tidb-test=release-8.5.2

---

pkg/ddl/partition.go
pkg/lightning/mydump/BUILD.bazel
pkg/lightning/mydump/router.go
pkg/planner/core/casetest/cbotest/BUILD.bazel
pkg/planner/core/casetest/physicalplantest/BUILD.bazel
pkg/planner/core/issuetest/BUILD.bazel
pkg/util/slice/slice.go
pkg/util/slice/slice_test.go
pkg/util/workloadrepo/table.go
pkg/util/workloadrepo/worker_test.go

as diff I run some bench mark local seems it can have a better performance, 
and I am still learning it, not sure it is 100% right
benchmark:
```cli
BenchmarkAnyOf_New_Small-10             144057651                8.305 ns/op           0 B/op          0 allocs/op
BenchmarkAnyOf_Old_Small-10             121768545                9.815 ns/op           0 B/op          0 allocs/op
BenchmarkAnyOf_New_Medium-10            30066207                39.44 ns/op            0 B/op          0 allocs/op
BenchmarkAnyOf_Old_Medium-10            29319988                40.62 ns/op            0 B/op          0 allocs/op
BenchmarkAnyOf_New_Large-10             30374875                39.85 ns/op            0 B/op          0 allocs/op
BenchmarkAnyOf_Old_Large-10             29228607                40.93 ns/op …
```

perf: using generics instead of reflect for better performance

---

pkg/lightning/backend/local/rate_limiter_param.go
pkg/server/handler/tests/BUILD.bazel
pkg/server/handler/tests/http_handler_serial_test.go
pkg/server/http_status.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61553
When I cherry-pick #61622 to master(https://github.com/pingcap/tidb/pull/61555), the http handler registering part is missed. We can't modify the ingest parameters through http API.
Register missing http handlers related to ingest param.
Tests 
```
❯ curl http://127.0.0.1:10080/ingest/max-batch-split-ranges
{
"is_null": false,
"value": 2048
}% 
❯ curl http://127.0.0.1:10080/ingest/max-batch-split-ranges -X POST -d '{"value": 1}'
{
"message": "success"
}%                                                                              
❯ curl http://127.0.0.1:10080/ingest/max-batch-split-ranges
{
"is_null": false,
"value": 1
}%                                                                         
❯ curl …
```

server/handler: register missing http handlers related to ingest param

---

pkg/planner/core/plan_test.go
pkg/planner/core/planbuilder.go
tests/realtikvtest/importintotest/import_into_test.go

Issue Number: close #63147
As title, I forgot to check nilness of the map passed in 😢, introduced in #58401 
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner/core: fix missing nilness check for passed `onDup` map

---

br/pkg/checksum/BUILD.bazel
br/pkg/checksum/executor.go
br/pkg/checksum/executor_nokit_test.go
br/pkg/checksum/main_test.go
pkg/distsql/request_builder.go
pkg/lightning/backend/local/checksum.go
pkg/store/copr/coprocessor.go

Tests 
apply below diff
<details><summary>code diff</summary>
```diff
diff --git a/pkg/store/copr/coprocessor.go b/pkg/store/copr/coprocessor.go
index 28eaaeef54..2dcbe28f19 100644
--- a/pkg/store/copr/coprocessor.go
+++ b/pkg/store/copr/coprocessor.go
@@ -1421,6 +1421,10 @@ func (worker *copIteratorWorker) handleTaskOnce(bo *Backoffer, task *copTask) (*
req.ReplicaReadType = options.GetTiKVReplicaReadType(kv.ReplicaReadFollower)
ops = append(ops, tikv.WithMatchStores([]uint64{*task.redirect2Replica}))
}
+	if req.InputRequestSource != "internal_DistTask" && req.InputRequestSource != "internal_others" &&
+		req.InputRequestSource != "internal_ddl" && req.InputRequestSource != "internal_stats" && req.InputRequestSource != "internal_DDLNotifier" {
+ …
```

importinto: set request resource during checksum for nextgen

---

pkg/bindinfo/binding_plan_generation.go
pkg/bindinfo/testdata/binding_auto_suite_out.json
pkg/planner/cardinality/pseudo.go
pkg/planner/cardinality/selectivity.go
pkg/sessionctx/vardef/tidb_vars.go
pkg/sessionctx/variable/session.go
pkg/sessionctx/variable/setvar_affect.go
pkg/sessionctx/variable/sysvar.go
pkg/sessionctx/variable/sysvar_test.go

Issue Number: close #55366
For the complex predicate, we cannot directly derive the selectivity from the stats. It better to use the SPM background job to record, retry and learning the selectivity.
The PR record the selectivity factor and make it as a session variable instead of internal const
1. Add a new session variable named "tidb_opt_selectivity_factor" instead of internal const "selectionFactor"
2. Record the selectivity factor in following cases: 
> The number of exprs is more than 63
> col without col stats and index stats
> Complex predicate such as string match, DNF etc
Tests 
> 
Side effects
Documentation …

planner,selectivity: record the default selectivity

---

pkg/planner/core/planbuilder.go
pkg/planner/optimize.go

Issue Number: ref #61876
The function planner.Optimize is recursively called from core.buildExplain.
Optimize will no longer by called by buildExplain.  Instead this function will call optimizeCache if the plan is to be cached and optimizeNoCache if it is not.   This removes a recursive loop involving Optimize.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: Make explain code call non-recursive functions to build plans instead of planner.Optimize.

---

pkg/lightning/backend/local/job_worker.go
pkg/lightning/backend/local/local.go
tests/realtikvtest/importintotest3/BUILD.bazel
tests/realtikvtest/importintotest3/cross_ks_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61088
Next-gen and classic kernel have different code path for ingest, but we only add metric collector for classic kernel.
Tests 
> 
You can also start a next-gen cluster with tiup and run `TestOnUserKeyspace` locally. Note, you should disable the remote coprocessor for tikv (ref https://github.com/pingcap/tidb/pull/62701/files#diff-6f6451c097e1954613b68d673de4a921e43820e8e46d842c946cfad2ad84c0cdR14-R17) to make post-process succeed.
Side effects
Documentation
```release-note
None
```

backend/local: add missing collector for next-gen ingest

---

pkg/util/stmtsummary/v2/stmtsummary.go
pkg/util/stmtsummary/v2/stmtsummary_test.go

Issue Number: close #63197 
Tests 
Manually check the dumped tidb_statements.log to see the evicted entry, and tidb.log to check no Marshall warning message.
> 
Side effects
Documentation
```release-note
Fix the issue that the persist of evicted statements will fail when tidb_stmt_summary_enable_persistent is turned on.
```

stmtsummary: Fix statement summary persist evicted entry failure issue

---

pkg/planner/core/logical_plan_builder.go
pkg/statistics/BUILD.bazel
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/cache/internal/lfu/lfu_cache.go
pkg/statistics/handle/cache/statscache.go
pkg/statistics/handle/storage/read.go
pkg/statistics/handle/storage/stats_read_writer.go
pkg/statistics/handle/storage/update.go
pkg/statistics/handle/syncload/stats_syncload.go
pkg/statistics/table.go
pkg/statistics/table_test.go

Issue Number: close #63076
1. remove copy in InitStatsLite as it's single thread update, so can update in place
2. postpone deep copy in TableStatsFromStorage and use shallow copy if applicable
3. add copyForCol and copyForIndex method to only copy relevant components instead of everything and apply to updateCachedItem and TableStatsFromStorage
Tests 
> 
Side effects
Documentation
```release-note
None
```

stats: optimize stats table copy to save memory

---

pkg/sessionctx/vardef/tidb_vars.go
pkg/sessionctx/variable/BUILD.bazel
pkg/sessionctx/variable/sysvar.go
pkg/sessionctx/variable/sysvar_test.go

Issue Number: close #63172
The default transaction assertion level for next-gen TiDB should be set to STRICT to prevent correctness risks, while classic TiDB should maintain compatibility with existing behavior.
This PR implements kernel-type-aware defaults for the transaction assertion level during TiDB bootstrap:
1. **Modified `GlobalSystemVariableInitialValue()`** in `pkg/sessionctx/variable/sysvar.go`:
- Added kernel-type detection using `kerneltype.IsNextGen()`
- Next-gen kernels use `STRICT` assertion level during bootstrap
- Classic kernels use `FAST` assertion level (improved from previous `OFF`)
2. **Added helper function `GetDefaultTxnAssertionLevel()`** in `pkg/sessionctx/vardef/tidb_vars.go`:
- Provides kernel-aware defaults following existing patterns like …

sessionctx: set strict assertion level as default for next-gen

---

pkg/parser/ast/ddl.go
pkg/parser/ast/ddl_test.go
pkg/parser/format/format.go

Issue Number: close #63252
In TiDB-specific DDLs like `ADD COLUMN IF NOT EXISTS`, put the `IF NOT EXISTS` inside `/*T! … */` when calling `Restore()` of the AST node.
Tests 
> 
Side effects
Documentation
```release-note
TiCDC: Replication of some TiDB-specific statements such as ADD COLUMN IF NOT EXISTS to MySQL no longer causes the changefeed to stop with error.
```

parser: format ADD COLUMN IF NOT EXISTS and similar DDLs in special comments

---

pkg/store/copr/tici_shard_cache.go
pkg/store/copr/tici_shard_cache_test.go

Different indexes use the same range domain, this will cause queries on different indexes to return incorrect shard information
So we need each index to have its own independent range domain.
Tests 
```
ALTER TABLE test.hdfs ADD FULLTEXT INDEX ft_index (body) WITH PARSER standard;
ALTER TABLE test.hdfs ADD FULLTEXT INDEX ft_index2 (severity_text) WITH PARSER standard;
select * from hdfs where fts_match_word("Receiving", body);
-- The second query returns the correct result
select * from hdfs where fts_match_word("info", severity_text);
```
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes- …

tici: add index id into shard cache | tidb-test=3b2adda7436d5e712bffaa859f679c5ca370811b

---

pkg/config/config.go
pkg/config/config_test.go
pkg/util/naming/OWNERS
pkg/util/naming/naming.go

as keyspace name might be stored inside system table, we limit the length to help us design related column and avoid potential `truncated value`
```
// mostly we use an uint64 as the keyspace name, the max value is 20 characters.
// And there are at most 16,777,215 keyspace ID in a single physical cluster,
// as keyspace ID is encoded into KV, it's very hard to extend its length, so
// current keyspace name limit is more than enough for current usage and later
// extension.
```
related PD pr https://github.com/tikv/pd/pull/9708
Tests 
```
~/code/pingcap/tidb git:[limit-ks-mame] bin/tidb-server --keyspace-name 18446744073709551615a
load config file: /Users/jujiajia/code/pingcap/tidb
invalid config invalid keyspace name: the value …
```

config: limit keyspace name to at most 20 chars

---

pkg/ddl/modify_column.go

Issue Number: close #63304
The `processModifyColumnOptions` function, which encapsulates the logic for processing column options, was previously an unexported (private) function within the `ddl` package. This limited its direct reusability by other internal components or DDL sub-systems that might need to apply or validate column options independently. By exporting this function, we enable its direct use across different parts of the codebase, improving modularity and reducing potential code duplication for column option handling.
This PR refactors the DDL column modification logic by exporting the `processModifyColumnOptions` function.
The changes include:
* Renamed the unexported function `processModifyColumnOptions` to `ProcessModifyColumnOptions`. This makes the …

ddl: export `processModifyColumnOptions` for broader utility

---

pkg/domain/crossks/cross_ks_test.go
pkg/store/mockstore/mockcopr/executor.go
pkg/store/mockstore/mockstorage/BUILD.bazel
pkg/store/mockstore/mockstorage/storage.go

`crossks_test.TestManager` and `"test_test.TestDoDDLJobQuit" ` panic previously, we fix them in this pr
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix panic in TestManager and TestDoDDLJobQuit in nextgen

---

pkg/server/handler/tests/http_handler_test.go
pkg/session/bootstrap_test.go
pkg/session/test/bootstraptest/BUILD.bazel
pkg/session/test/bootstraptest/bootstrap_upgrade_test.go

Since in next-gen cluster all tables that are created by bootstrap can not have non-clustered primary key, we can skip the test cases containing `upgradeToVer248`
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: skip some upgrade tests for next-gen

---

pkg/sessiontxn/isolation/BUILD.bazel
pkg/sessiontxn/isolation/readcommitted_test.go
pkg/telemetry/data_feature_usage_test.go

Issue Number: close #63343
Fix failing tests in next-gen mode by adding appropriate kernel type checks and skipping incompatible tests.
1. **readcommitted_test.go**: Added next-gen kernel checks to skip `TestFailedDMLConsistency1` and `TestFailedDMLConsistency2` because next-gen hangs when acquiring pessimistic locks after failed DML with fair locking disabled
2. **data_feature_usage_test.go**: 
- Added kernel type check in `TestTxnUsageInfo` to only test fair locking settings in classic mode
- Added skip for `TestFairLockingUsage` in next-gen mode since fair locking is not yet supported
These changes prevent test failures and hangs in next-gen environment while maintaining full test coverage in classic mode.
Tests 
> …

test: fix some tests for next-gen

---

pkg/ddl/index_modify_test.go
pkg/ddl/primary_key_handle_test.go
pkg/ddl/reorg_util.go
pkg/executor/test/ddl/BUILD.bazel
pkg/executor/test/ddl/ddl_test.go
pkg/meta/model/reorg.go

Fix:
* TestSetDDLReorgMaxWriteSpeed
* TestAddIndexUniqueFailOnDuplicate
* TestMultiRegionGetTableEndHandle
* TestMultiRegionGetTableEndCommonHandle
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix next-gen CI failure cases

---

pkg/disttask/framework/scheduler/scheduler.go
pkg/disttask/importinto/planner.go
pkg/disttask/importinto/proto.go
pkg/disttask/importinto/scheduler.go
pkg/disttask/importinto/subtask_executor.go
pkg/disttask/importinto/task_executor.go
pkg/executor/importer/import.go
pkg/executor/show.go
pkg/executor/show_test.go

we add update time in #62283, the value is from update time of subtask summary, but during validation phase, we don't have subtask level summary. this pr change to use the update time of the job itself in this case
refine logs to print related task/subtask id and other info
Tests 
before, at validating step, `Last_Update_Time` is zero
```
+--------+-----------+-------------+--------------+----------+------------+---------+------------------+---------------+----------------+----------------------------+----------------------------+----------+------------+---------------------+--------------+-------------------------+---------------------+-----------------------+----------------+--------------+
| Job_ID | Group_Key | Data_Source | Target_Table | …
```

importinto: fix zero update time during validation phase and refine logs

---

pkg/statistics/handle/BUILD.bazel
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/bootstrap_test.go
pkg/statistics/handle/handletest/initstats/BUILD.bazel
pkg/statistics/handle/handletest/initstats/init_stats_test.go
pkg/util/slice/slice.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61273
In this PR, I added support for lite init stats to allow specifying table IDs. This enables us to implement the refresh stats command when specific tables are provided.
I introduced a general option to allow passing the table ID to the init stats functions.
Tests 
> 
Side effects
Documentation
```release-note
None
```

statistics: support specify table IDs

---

br/pkg/restore/snap_client/client_test.go

Issue Number: ref #62803
The table ID of `mysql.user` in next gen is very large.
Fix the unit test
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix alloc test for next gen

---

pkg/planner/core/casetest/physicalplantest/BUILD.bazel
pkg/planner/core/casetest/physicalplantest/physical_plan_test.go
pkg/planner/core/operator/logicalop/logical_join.go
pkg/planner/core/rule_semi_join_rewrite.go

Issue Number: close #58958
When we perform predicate pushdown, we simplify the predicates. After simplification, the join may have the opportunity to undergo semi join rewrite. Therefore, we attempt semi join rewrite on the join that has undergone predicate pushdown.
Additionally, there is another issue here. When we process LogicalApply and call predicate pushdown, the object being operated on is actually a LogicalJoin. If we return the LogicalJoin at this point, it will cause problems. Therefore, the correct approach here is to return p.Self().
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide …

planner: rewrite semi join when to predicate push down

---

pkg/executor/aggfuncs/func_count_distinct.go
pkg/executor/aggfuncs/func_group_concat.go
pkg/util/codec/codec.go
pkg/util/collate/bin.go
pkg/util/collate/collate.go
pkg/util/collate/collate_bench_test.go
pkg/util/collate/collate_test.go
pkg/util/collate/gb18030_bin.go
pkg/util/collate/gb18030_chinese_ci.go
pkg/util/collate/gbk_bin.go
pkg/util/collate/gbk_chinese_ci.go
pkg/util/collate/general_ci.go
pkg/util/collate/pinyin_tidb_as_cs.go
pkg/util/collate/ucaimpl/unicode_ci.go.tpl
pkg/util/collate/unicode_0400_ci_generated.go
pkg/util/collate/unicode_0900_ai_ci_generated.go

Issue Number: close #63507
1. add `ImmutableKey` to `Collator`, so the caller can use this instead of `Key` if the return value will not be modified.
2. optimize `SerializeKeys` and `HashChunkSelected` for string type by getting collator each chunk instead of each row.
Benchmark
```
BenchmarkUtf8mb4Bin_KeyShort-16                   	34731619	        35.26 ns/op	      48 B/op	       1 allocs/op
BenchmarkUtf8mb4Bin_ImmutableKeyShort-16          	476855181	         2.538 ns/op	       0 B/op	       0 allocs/op
BenchmarkUtf8mb4GeneralCI_KeyShort-16             	 4594576	       258.4 ns/op	     128 B/op	       2 allocs/op
BenchmarkUtf8mb4GeneralCI_ImmutableKeyShort-16    	 4685094	       261.7 ns/op	     144 B/op	       2 allocs/op
BenchmarkUtf8mb4UnicodeCI_KeyShort-16 …
```

executor: Optimize hash join/agg for `__bin` collator

---

pkg/executor/adapter.go
pkg/parser/ast/misc.go
pkg/plugin/BUILD.bazel
pkg/plugin/audit.go
pkg/plugin/helper.go
pkg/plugin/integration_test.go
pkg/server/conn.go
pkg/server/conn_stmt.go
pkg/server/tests/commontest/BUILD.bazel
pkg/server/tests/commontest/tidb_test.go
pkg/session/session.go
tests/realtikvtest/configs/next-gen/tikv-worker.toml
tests/realtikvtest/configs/next-gen/tikv.toml

Issue Number: close #63525
Now, the plugin doesn't know the statement id of `PREPARE/CLOSE` statement.
1. For `PREPARE/CLOSE`, simply add the stmtID in the context.
2. For `EXECUTE`, Add `StmtID` field to the `ast.ExecStmt`, and then use it to record the `COMPLETED` event.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor, plugin: add statement id info to the plugin

---

tests/realtikvtest/configs/next-gen/tikv-worker.toml
tests/realtikvtest/configs/next-gen/tikv.toml

Signed-off-by: Juncen Yu <yujuncen@pingcap.com>
Issue Number: ref #62803 
After a PR, the default protocol become `https` instead of `http`. which breaks `real-tikv-test`, because the latter didn't specify the protocol in endpoint.
Use explicit `http` protocol in test configuration.
Tests 
Who test tests?
> 
Side effects
Documentation
```release-note
None
```

tests: update s3-endpoint to include protocol in configuration files

---

pkg/executor/test/issuetest/executor_issue_test.go

Issue Number: close #57515
When exceeding memory limit in index join, context's cancel function will be called and set context error with information "context canceled".  After cancelled, fetchInnerResults may get error fron ctx.Err() which returns "context canceled" caused by a exceeding memory panic or get exceeding memory limit error directly from `exec.Next`
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix flaky test TestIndexJoin31494

---

pkg/ddl/reorg_util.go
pkg/session/BUILD.bazel
pkg/session/bootstrap_test.go

after https://github.com/pingcap/tidb/pull/63524, nextgen will have the need to upgrade, and at that time we have merged the pr to cal resource params for reorg related ddl. for modify column, we actually don't need to cal the param, but we will get the table size as the first step, so will fail
during init for reorg params, we auto calculate resource related params for nextgen, but during upgrade, DXF service hasn't initialized, and we shouldn't use DXF service to run boot related DDL
Tests 
bootstrap nextgen cluster before hash 365cc2544478a814144ba7e811474877eb525a46, then upgrade to master, it will fail with 
```
[2025/09/17 17:16:11.404 +08:00] [FATAL] [upgrade.go:733] ["doReentrantDDL error"] [keyspaceName=SYSTEM] [error="task manager is not …
```

upgrade: fix upgrade failed on nextgen

---

pkg/executor/sample.go
pkg/session/bootstrap_test.go
pkg/store/mockstore/mockstore.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61702
- Skip null keyspace test in next-gen.
- Set tablesample end key to table end key if the length is zero.
Tests 
> 
Side effects
Documentation
```release-note
None
```

next-gen: fix tablesample test and null keyspace test

---

br/pkg/metautil/metafile.go
br/pkg/restore/snap_client/pipeline_items.go

Issue Number: close #60978
the count of stats_meta is zero if backup has no checksum
get the count of stats_meta by collecting the files instead of total kvs of table.
Tests 
> 
Side effects
Documentation
```release-note
None
```

br: fix stats meta count is zero if no checksum 8.5

---

pkg/session/test/variable/variable_test.go
pkg/sessionctx/variable/BUILD.bazel
pkg/sessionctx/variable/session.go
pkg/sessionctx/variable/varsutil_test.go
pkg/sessiontxn/isolation/base.go
pkg/sessiontxn/isolation/main_test.go
tests/realtikvtest/txntest/BUILD.bazel
tests/realtikvtest/txntest/replica_read_test.go

Issue Number: close #62856
For the follower read function, DML is neither an optimization target nor a benefit one. Letting the reading phase of DML be affected by follower read only increases risk. This PR makes follower read no longer apply to DML, thereby reducing the risk of functionality overlap.
Tests 
> 
Run range update with `tidb_replica_read="closest-replicas"`.
Side effects
Documentation
```release-note
Replica read only works for read-only statements.
```

txn: follower read only affect read-only statements

---

pkg/planner/core/casetest/cbotest/BUILD.bazel
pkg/planner/core/casetest/cbotest/cbo_test.go
pkg/planner/core/casetest/cbotest/testdata/analyze_suite_in.json
pkg/planner/core/casetest/cbotest/testdata/analyze_suite_out.json
pkg/planner/core/casetest/cbotest/testdata/analyze_suite_xut.json
pkg/store/mockstore/unistore/cophandler/analyze.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61702
Unistore's analyze index processor cannot handle encoded index keys.
- Strip the prefixed keyspace before decoding index key.
- Fix `TestAnalyzeColumnsWithVirtualColumnIndex`, `TestAnalyzeMVIndex` and `TestNormalAnalyzeOnCommonHandle`.
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: fix analyze tests for next-gen

---

pkg/ddl/reorg_util.go
pkg/store/copr/coprocessor.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61702
> tikv-server may return paging range even if paging is not enabled. Then if the range is not handled, the result would be wrong.
Cherry-pick https://github.com/tidbcloud/tidb-cse/pull/1194.
> handle paging result if `copResp` has Range, even if paging is not enabled.
Tests 
Before this PR(the log is from TiDB built by https://github.com/pingcap/tidb/pull/63495:
```
[ERROR] [reporter.go:274] ["admin check found data inconsistency"] [keyspaceName=10708255509240425689] [conn=2936078708] [session_alias=] [table_name=t] [index_name=k] [row_id=28802665] [index=] [row="handle: 28802665, values: [KindInt64 83349]"] [row_mvcc="{\"decoded\":{\"460711990272720897\":{\"bigint_0\":\"63763\",\"bigint_1\":\"98976\",\"bigint …
```

coprocessor: handle paging result even if not enabled

---

pkg/executor/join/base_join_probe.go
pkg/executor/join/hash_join_v2.go
pkg/executor/join/row_table_builder.go

In most of the cases, `chunk` does not have `sel` field, in this case hash join v2 need to allocate a `sel` explicitly for each chunk, in this pr, it use a pre-defined `fakeSel` to avoid this allocation.
Tests 
The existing ut already covered this case.
> 
Side effects
Documentation
```release-note
None
```

executor: Use fakeSel to avoid memory allocate when chunk has no `sel` field in hash join v2

---

pkg/executor/test/executor/executor_test.go
pkg/server/tests/commontest/tidb_test.go

Issue Number: ref #62803
Set `pessimistic-auto-commit` to false for some tests that rely on the value.
Tests 
> 
Side effects
Documentation
```release-note
None
```

test: adjust some tests for pessimistic-auto-commit change

---

pkg/ddl/executor.go
pkg/ddl/job_submitter.go
pkg/ddl/modify_column.go
pkg/session/test/bootstraptest/BUILD.bazel
pkg/session/test/bootstraptest/bootstrap_upgrade_test.go

Issue Number: close #60042
During the upgrade, TiDB needs to do some DDL on the system table.
Some of them are non-replicable, such as 
```
ALTER TABLE mysql.bind_info MODIFY COLUMN original_sql LONGTEXT NOT NULL
```
In upgradeToVer245(),
```
ALTER TABLE mysql.tidb_pitr_id_map ADD PRIMARY KEY(restore_id, restored_ts, upstream_cluster_id, segment_id)
```
In upgradeToVer248().
If BDR mode is enabled, TiDB would fail to upgrade. 
If the DDL is on a system table, we should not report an error.
Since the CDC would not sync the system table, it's ok to execute in BDR mode.
Tests 
Start an upstream cluster and a downstream cluster. (v8.1.0)
Upstream:
```
ADMIN SET BDR ROLE PRIMARY;
```  
Downstream:
```
ADMIN SET BDR ROLE SECONDARY;
```
Upgrade the upstream cluster to master. …

ddl: allow DDL on the system table in BDR mode

---

pkg/executor/importer/chunk_process.go
pkg/executor/importer/chunk_process_testkit_test.go

Issue Number: close #63763
Tests 
```
mysql> import into t from '/data/t.00000028.csv' with skip_rows=1;
ERROR 1105 (HY000): when encoding 210-th row in this chunk: encode kv error in file test.t.1.csv:0 at offset 313609: DECIMAL value is out of range in '(38, 18)'
```
> 
Side effects
Documentation
```release-note
None
```

importinto: enhance encode error msg

---

pkg/domain/domain.go
pkg/statistics/handle/usage/BUILD.bazel
pkg/statistics/handle/usage/session_stats_collect.go
pkg/statistics/handle/usage/session_stats_collect_test.go

Issue Number: close #63426 
We noticed updating to cols usage query has been taking 10s seconds when scale TIDB nodes to 100. It was mainly due to lock contention that every node trying to update the same set of cols. 
By doing some experiments locally, it is noticed that the batch size might contribute a lot to the lock contention. By tuning down the batch size, it should mitigate the problem.
This PR also tries to not update the cols if it's only timestamp change, we decide to update the col timestamp every 12 hours, that should also reduce the update time and lock contention.
Perf with different batch size:
```
// batch size 1024
DumpColStatsUsage concurrent: goroutines=10 tables=100 cols/table=1000 per-g: avg=7.486120933s min=7.300108708s max=7.718235625s; …
```

stats: reduce updating col predicate usage table

---

pkg/distsql/BUILD.bazel
pkg/distsql/request_builder.go
pkg/executor/distsql.go
pkg/executor/index_merge_reader.go
pkg/executor/test/distsqltest/distsql_test.go

Cherry pick #61376 into release-8.5-20250114-v8.5.0
---
close pingcap/tidb#60175
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: fix data race because of using shared KV requests (#61376)  | tidb-test=pr/2617

---

DEPS.bzl
go.mod
go.sum
pkg/config/BUILD.bazel
pkg/config/config.go
pkg/config/config_test.go
pkg/sessionctx/variable/sysvar.go

This is the cherry-pick PR of #63651 for release-8.5
--------------------------
See #63650
-->
Issue Number: close #63650
This PR introduces new configuration options to control the buffering behavior of the audit log plugin:
- `instance.plugin_audit_log_flush_interval` — Defines the interval at which buffered audit logs are flushed to the plugin.
- `instance. plugin_audit_log_buffer_size ` — Sets the maximum number of audit log entries that can be buffered before a flush is triggered.
So that:
- Audit log entries are collected in memory until either the flush interval elapses or the buffer reaches its maximum size.
- Once triggered, all buffered logs are flushed to the audit log plugin in batch.
- The configuration options can be adjusted in the TiDB config file under …

pkg/config: add buffer config for plugin audit log (#63651)

---

br/pkg/restore/snap_client/systable_restore_test.go
pkg/bindinfo/binding.go
pkg/bindinfo/binding_cache.go
pkg/bindinfo/binding_operator.go
pkg/bindinfo/binding_operator_test.go
pkg/bindinfo/tests/BUILD.bazel
pkg/bindinfo/tests/bind_test.go
pkg/bindinfo/tests/bind_usage_info_test.go
pkg/bindinfo/utils.go
pkg/domain/domain.go
pkg/infoschema/test/clustertablestest/BUILD.bazel
pkg/infoschema/test/clustertablestest/cluster_tables_test.go
pkg/session/BUILD.bazel
pkg/session/bootstrap.go
pkg/session/bootstrap_test.go
pkg/session/test/bootstraptest/BUILD.bazel
pkg/session/test/bootstraptest/bootstrap_upgrade_test.go
pkg/session/upgrade.go

Issue Number: close #63407 
Currently, some customers have created a large number of bindings. However, it is difficult to determine whether these bindings are still in use. The sheer volume of bindings also puts pressure on TiDB. Therefore, we need a way to identify and mark the bindings that are not in use.
Tests 
start a tidb with master which is started by script. ```Tikv``` and ```PD``` is started by ```tiup playground nightly --mode tikv-slim```.
```
+----------------------------------+----------------------------------+------------+---------+-------------------------+-------------------------+---------+-----------+---------+------------+-------------+
| original_sql                     | bind_sql                         | default_db | status  | create_time …
```

bindinfo: add last_used_date to track bindinfo usage frequency

---

pkg/domain/BUILD.bazel
pkg/domain/domain.go
pkg/executor/BUILD.bazel
pkg/executor/simple.go
pkg/executor/simple_test.go
pkg/parser/ast/stats.go
pkg/parser/ast/stats_test.go
pkg/planner/core/planbuilder.go
pkg/statistics/handle/bootstrap.go
pkg/statistics/handle/initstats/load_stats_page.go

Issue Number: ref https://github.com/pingcap/tidb/issues/61273
This PR implements REFRESH STATS all the way through: the planner now fills in default schemas and dedupes targets, the executor asserts everything is qualified, refreshes locally, and—when requested—broadcasts the normalized SQL so other TiDB nodes can execute without relying on their own CurrentDB; missing databases/tables just raise warnings instead of kicking off a full reload, the stats-handle progress counter lives where it belongs, and a batch of executor/parser tests nails the behaviour down.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-n …

statistics: implement refresh stats command

---

pkg/executor/simple_test.go
pkg/planner/core/planbuilder.go
pkg/planner/core/planbuilder_test.go

Issue Number: close https://github.com/pingcap/tidb/issues/61273
Do privilege checks for the refresh cmd. We require the select privilege for all tables.
So we require the select privilege for this command, and because this command is mainly for BR, we also add the restore admin permission as a special case.
Tests 
> 
Side effects
Documentation
```release-note
None
```

planner: check select or restore-admin privilege for the refresh cmd

---

docs/design/2022-03-03-rc-read-tso-optimization.md
docs/design/2024-01-09-pipelined-DML.md
tools/check/ut.go

This PR corrects several minor typos in comments and documentation across the codebase. The changes are non-functional and purely textual to improve clarity and maintain a clean, professional codebase.
- Corrected misspellings:
- `becoms` → `becomes`
- `unncessary` → `unnecessary`
- `concurreny` → `concurrency`
These fixes help enhance readability and eliminate minor distractions during development and code reviews.
No logic or functionality has been modified. All changes are restricted to comments or non-executable doc annotations.
Tests 
> 
Side effects
Documentation
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes- …

docs: fix typos

---

pkg/executor/inspection_result.go

Issue Number: close #63840 
The advertise address is expected to be different for each instance, so it should be ignore from the checks which checks for inconsistencies in the configuration.
Tests 
> 
Side effects
Documentation
```release-note
None
```

executor: exclude tiproxy advertise addr from inspection result
