pingcap/tidb

Makefile

golint is broken.
https://github.com/golang/lint/issues/396

Makefile: disable golint

---

Makefile

fix fetch issue of golint (#6363)

---

executor/builder.go
executor/executor.go
plan/physical_plan_builder.go
plan/physical_plans.go
util/ranger/points.go
util/ranger/types.go
util/ranger/types_test.go

Some clean up.
PTAL @zz-jason @XuHuaiyu @lamxTyler

*: remove `IntColumnRange`.

---

executor/executor_test.go
plan/eliminate_projection.go

executor, plan: eliminate projection if the schema len is 0 (#6318)

---

Makefile

Makefile: use go get golint again (#6371)

---

store/tikv/txn.go

Cherry-pick to release 2.0
@coocood @zz-jason

store/tikv: make LockKeys() function thread safe (#6340)

---

ddl/column.go
ddl/ddl.go
ddl/ddl_api.go
ddl/ddl_worker.go
ddl/schema_test.go

- remove some useless functions
- add some comments
- remove DDL.GetInformationSchema interface

ddl: remove some useless functions

---

expression/aggregation/agg_to_pb_test.go
expression/expr_to_pb_test.go
util/mock/client.go

cherry pick #6299 to release 2.0

[release 2.0] expression: remove mockKVClient (#6299)

---

executor/adapter.go
executor/builder.go
sessionctx/stmtctx/stmtctx.go

cherry pick #6343 to release 2.0

[release-2.0] executor: refine log information about slow queries (#6343)

---

plan/preprocess.go
plan/preprocess_test.go

plan: check empty table name in RenameTableStmt (#6383)

---

plan/physical_plan_builder.go
plan/physical_plan_test.go

Cherry pick to release-2.0
PTAL @zz-jason @winoros

plan: fix a bug in `tryToGetMemTask` function (#6390)

---

parser/parser.y
parser/parser_test.go

for #6401 , Support  syntax:
```sql 
ALTER TABLE t AUTO_INCREMENT number
```

parser: support 'ALTER TABLE t AUTO_INCREMENT number' syntax

---

ddl/index.go

 ddl: Add reorg log to make trouble-shooting easier. (#6428)

---

ddl/column.go
ddl/index.go
ddl/reorg.go
ddl/reorg_test.go

ddl: update ddl add index progress timely (#6453)

---

ddl/ddl.go
metrics/ddl.go

This PR improves readability. 
PTAL @shenli @zimulala

metric: rename CreateDDL to CreateDDLInstance

---

executor/set.go
executor/set_test.go
parser/parser.y
sessionctx/variable/sysvar.go

executor, parser: treat tx_isolation, transaction_isolation or tx_read_only, transaction_read_only as synonyms variable

---

ddl/index.go
executor/ddl_test.go

ddl: fix bug when add index meet math.MaxInt64 handle. (#6481)

---

docs/tidb_http_api.md
server/http_handler.go
server/http_handler_test.go

Support log level and general log.
Makes it easier to address issue.

sever: add HTTP API to change log level dynamically.

---

ddl/util/util.go
store/tikv/gcworker/gc_worker.go

set GC worker and loadDeleteRangeSQL high priority (#6450)

---

docs/tidb_http_api.md
server/http_handler.go
server/http_handler_test.go

sever: add HTTP API to change log level dynamically. (#6513)

---

docs/tidb_http_api.md
server/http_handler.go
server/http_handler_test.go

log level is not accessed atomically in this version, cause race issue.

http: revert log_level change

---

executor/executor_test.go
plan/errors.go
plan/preprocess.go

plan :fix the compatibility problem of  UNION statement (#6370)

---

docs/tidb_http_api.md
server/http_handler.go
server/http_handler_test.go

log level is not accessed atomically in this version, cause race issue.
cherry-pick #6525

http: revert log_level change (#6525)

---

store/tikv/coprocessor.go

Cherry pick from master.
@coocood  @zz-jason @zimulala

store/tikv: copIteratorTaskSender is not initialized properly (#6514)

---

ddl/ddl_db_test.go
ddl/index.go
ddl/reorg.go
ddl/reorg_test.go

ddl: fix bug that update handle failed before adding table indics (#6523)

---

ddl/ddl_db_change_test.go
ddl/table.go

* ddl: handle parallel rename table

ddl: handle parallel rename table (#6462)

---

executor/write_test.go
plan/resolve_indices.go

plan: resolve indices for apply schema (#6540)

---

plan/physical_plan_test.go
plan/property_cols_prune.go

 plan: prepare possible property for logical Sort/TopN/Projection (#6485)

---

store/tikv/coprocessor.go

cherry pick #6553 to release 2.0

store/tikv: log slow processing and waiting cop tasks separately with different labels (#6553)

---

config/config.go
config/config.toml.example
config/config_test.go
server/http_handler.go
server/http_status.go
sessionctx/binloginfo/binloginfo.go
sessionctx/binloginfo/binloginfo_test.go
tidb-server/main.go

Cherry pick from https://github.com/pingcap/tidb/pull/6503
@jackysp  @winkyao @coocood

*: Add an option to stop writting binlog when TiDB meets binlog error  (#6503)

---

ddl/ddl.go
ddl/ddl_api.go
executor/ddl_test.go

Cherry-pick https://github.com/pingcap/tidb/pull/6572

ddl: check `auto_increment` for `shard_row_id_bits` statements

---

expression/builtin_arithmetic.go

cherry pick #6583 to release 2.0

expression: set pb code for builtinArithmeticDivideDecimalSig (#6583)

---

config/config.go
config/config.toml.example
sessionctx/binloginfo/binloginfo.go
tidb-server/main.go

Cherry pick https://github.com/pingcap/tidb/pull/6587 for release 2.0

sessionctx/binloginfo: add a timeout for writing binlog

---

expression/builtin_math.go
expression/integration_test.go

expression: fix wrong result of CEIL

---

executor/executor_test.go
util/chunk/chunk.go

chunk: fix delete index in year type; (#6611)

---

executor/write.go
executor/write_test.go

executor: fix a bug of duplicate key update (#6589)

---

statistics/histogram.go
statistics/selectivity_test.go

stats: fix estimation for between row count (#6596)

---

expression/builtin_math.go
expression/integration_test.go

cherry pick #6598 to release 2.0

expression: fix wrong result of CEIL (#6598)

---

domain/domain.go
statistics/handle.go
statistics/table.go

As the title says.
PTAL @shenli @coocood @zz-jason @winoros

stats: refine stats log level

---

expression/builtin_compare.go
expression/integration_test.go

expression: refine compare timestamp col with string constant (#6621)

---

domain/domain.go
statistics/handle.go
statistics/table.go

stats: refine stats log level (#6627)

---

server/conn.go
server/util.go
server/util_test.go

server: support ComChangeUser

---

server/conn.go
server/util.go
server/util_test.go

cherry-pick #6623 from release-2.0 to master

server: support ComChangeUser 

---

ddl/column.go
ddl/ddl_api.go
ddl/index.go
executor/admin_test.go
model/model.go
tablecodec/tablecodec.go
util/admin/admin.go

*: unflatten datum in checkIndexAndRecord, to fix admin check table false alarm (#6625)

---

executor/aggregate_test.go
expression/aggregation/descriptor.go
plan/aggregation_push_down.go
plan/decorrelate.go
plan/expression_rewriter.go
plan/logical_plan_builder.go

cherry pick #6632 to release 2.0

executor, expression: fix a panic of MAX/MIN (#6632)

---

executor/simple.go
store/tikv/txn.go

*: set rollback log to debug level (#6653)

---

expression/builtin_math.go
expression/integration_test.go

cherry pick #6620 to release 2.0

expression: fix wrong result of floor (#6620)

---

executor/adapter.go
executor/compiler.go
executor/set.go
executor/simple.go
server/conn.go
server/server.go
session/session.go
store/tikv/2pc.go
table/column.go
x-server/conn.go
x-server/server.go

Makes tracing the events of a session easier.

*: unify the connection ID format in log

---

executor/join_test.go
plan/predicate_push_down.go

cherry pick #6669 to release 2.0

plan: Fix the empty result of join (#6669)

---

executor/show.go
executor/show_test.go

executor: don't output foreign keys in show create table statement. (#6693)

---

server/conn_stmt.go
server/conn_stmt_test.go
server/server_test.go
server/tidb_test.go

Cherry pick #6516 to release 2.0.
PTAL @shenli @coocood

server: support binary time type (#6516)

---

executor/prepared_test.go
plan/common_plans.go
plan/prepare_test.go

plan: fix a bug in `rebuildRange` when enabling prepare-plan-cache. (#6637)

---

ddl/ddl.go
ddl/mock.go
ddl/syncer.go
domain/domain.go
metrics/ddl.go
metrics/owner.go
owner/manager.go

*: add check when watching (#6671)

---

plan/errors.go
plan/optimizer.go

To avoid the panic caused by "nil pointer dereference"

plan: check invalid task after physical optimization

---

expression/builtin_compare.go
expression/integration_test.go

This PR cherry-pick changes from #6690 to release 2.0 branch. @shenli @coocood PTAL

cherry-pick : revert pr 6621 (#6690)

---

ddl/ddl_worker.go

ddl: unify ddl log prefix

---

ast/dml.go
executor/prepared.go
parser/parser.y
parser/parser_test.go
plan/logical_plan_builder.go
plan/physical_plan_test.go

Cherry-picked from #6592 and #6626 
The first commit is included to avoid conflict.

Support JOIN hint for UPDATE/DELETE statements

---

domain/domain.go

domain: change default delta update duration to 1 minute (#6700)

---

CHANGELOG.md

changelog: update wording, format and links

---

executor/builder.go
executor/join_test.go
plan/explain.go
plan/gen_physical_plans.go
plan/physical_plan_test.go
plan/physical_plans.go
plan/resolve_indices.go
plan/stringer.go

cherry pick https://github.com/pingcap/tidb/pull/6753 to release 2.0
- unit test
- explain test
https://github.com/pingcap/tidb/pull/6753

plan, executor: fix the wrong result of merge join (#6753)

---

plan/cbo_test.go
statistics/selectivity.go
statistics/table.go

Cherry pick PR #6746 
unit test

stats: refine row count estimation (#6746)

---

executor/show_stats_test.go
executor/write.go
server/http_handler_test.go
statistics/histogram.go
types/datum.go

Cherry-pick one commit.
Cherry-pick
There's test in original commit.

types: handle `NULL datum` if we need convert it to string. (#6761)

---

store/tikv/client.go

Cherry pick from this PR: https://github.com/pingcap/tidb/pull/6770

store: add max backoff settings for tikv-client

---

expression/builtin_cast.go
expression/builtin_cast_test.go
expression/evaluator_test.go
mysql/type.go

cherry pick #6678 to release 2.0
- unit test
- explain test
No
#6678

expression: Do not wrap a 'CAST As JSON' when input is already a JSON (#6678)

---

ast/dml.go
executor/executor_test.go
parser/parser.y
plan/errors.go
plan/logical_plan_builder.go
plan/logical_plan_test.go

Cherry pick #6752 to release 2.0
- Breaking change (fix or feature that would cause existing functionality if user depends on bug)
- explain test
- unit test
No.
#6752

plan, parser: fix the wrong result of the `UNION` statement (#6752)

---

executor/compiler.go

Cherry pick https://github.com/pingcap/tidb/pull/6419 to release 2.0

executor: fix confusing statement label (#6419)

---

executor/executor_test.go
parser/parser.y

Cherry pick #6579 to release 2.0 to make other cherry pick easier.
- Breaking change (fix or feature that would cause existing functionality if user depends on bug)
- unit test
No
#6579

*: Fix select lock option for union statement (#6579)

---

cmd/importer/README.md

@queenypingcap @hanfei1991  PTAL

importer: fix typo and a broken link

---

ast/dml.go
executor/show.go
executor/show_test.go
parser/parser.y
parser/parser_test.go
plan/planbuilder.go

support 'show privileges'
```
mysql> show privileges;
+-------------------------+---------------------------------------+-------------------------------------------------------+
| Privilege               | Context                               | Comment                                               |
+-------------------------+---------------------------------------+-------------------------------------------------------+
| Alter                   | Tables                                | To alter the table                                    |
| Alter                   | Tables                                | To alter the table                                    |
| Alter routine           | Functions,Procedures                  | To alter or drop stored functions/procedures          |
| …
```

*: support 'show privileges'

---

executor/join_test.go
plan/predicate_push_down.go

cherry-pick
cherry-pick
tested in original pr.
#6809

plan: fix a bug in `predicate push down` phase. (#6809)

---

executor/executor_test.go
privilege/privileges/cache_test.go
privilege/privileges/privileges_test.go
server/http_handler_test.go
server/statistics_handler_test.go
server/tidb_test.go
sessionctx/binloginfo/binloginfo_test.go
util/codec/codec.go
util/ranger/ranger_test.go

make sure close dom/store in all test.
fix test leak in test case.
- test fix
modification is test.

test: fix leak test

---

executor/executor_test.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go
store/tikv/oracle/oracle.go

cherry-picking PR #6749 into our release-2.0. For more detail, please refer to that PR.

stroe: allow session variable tidb_snapeshot accepting tso. 

---

config/config.go
config/config.toml.example
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil_test.go

cherry pick #6788 to release 2.0
- unit test
- explain test

config, variable: add memory quota config for a query (#6788)

---

CHANGELOG.md

CHANGELOG.md
Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Summarize your change
Add changelog for release 2.0.4
Please **NOTE** that:
- Do not assume the code is self-evident
- Do not assume reviewers understand the original issue
- Improvement: Keep the changelog up to date.
Please describe the tests that you ran to verify your changes. Have you finished unit tests, integration tests, or manual tests?
Nothing to test.
Will update the release notes.

CHANGELOG: Add changelog for 2.0.4

---

session/session.go
session/session_test.go
session/tidb.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go

cherry-pick https://github.com/pingcap/tidb/pull/6872

session: add a global/session variable 'tidb_disable_txn_auto_retry'

---

config/config.go
config/config.toml.example

This PR enables TxnLocalLatches  as default value.
The stability test has been run one week with no error
no
@coocood @tiancaiamao PTAL

config: enable TxnLocalLatches in default

---

store/tikv/gcworker/gc_worker.go

cherry-pick "export gc concurrency (#6325)" (commit 2e18696) to branch release-2.0
This supports invoking concurrent GC on TiKV with ticlient.
- New feature (non-breaking change which adds functionality)
None
None
#6325

tikv/gc_worker: cherry-pick "export gc concurrency (#6325)" to release-2.0

---

distsql/request_builder.go
tidb-server/main.go

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Fix some typos in code.
Yes, I have passed the unit tests by `make dev`.

Typo fix: fix some typos.

---

executor/revoke.go

Improve documentation.
Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Summarize your change (mandatory)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)
Please **NOTE** that:
- Do not assume the code is self-evident
- Do not assume reviewers understand the original issue
- New feature (non-breaking change which adds …

executor: polish comment

---

parser/parser.y
parser/parser_test.go

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
Just for compatibly the mysql server's behaviour
A improvement for the issue:
https://github.com/pingcap/tidb/issues/6782
Passed make dev test.
nope

parser:support order by in select from dual

---

config/config.go
config/config.toml.example

This PR disables TxnLocalLatches  as default value.
The stability test has been run one week with no error
no
@coocood @tiancaiamao PTAL
The related PR:https://github.com/pingcap/tidb/pull/6874

config: disable local latches for transaction as default

---

docs/design/README.md
docs/design/TEMPLATE.md

- created the "docs/design" directory to store all the design documents or proposals 
- added an proposal template.
Yes, maybe we can add a link to the design document?
No
No

docs: add proposal template

---

docs/tidb_http_api.md

curl -X option is for the request, -x is for the proxy.
manual tests
Yes.
No.
No.
PTAL @coocood @zhexuany

docs: fix the wrong option in tidb_http_api.md

---

executor/admin_test.go
executor/executor.go

support 'admin check table' statement for table partition
unit test
PTAL @winkyao @coocood @zz-jason

executor: support 'admin check table' statement for table partition

---

expression/aggregation/concat.go
expression/aggregation/count.go

- GetValue call is very slow. We should avoid that call if possible.
- Performance improvement
- Manually, it saves 1 seconds of cpu runtime when counting 100m records.

expression/aggregation: less type covert call

---

expression/aggregation/agg_to_pb.go
expression/aggregation/agg_to_pb_test.go
expression/expr_to_pb.go
plan/plan_to_pb.go
plan/plan_to_pb_test.go

1. Set the Aggregation expression field type in PB.
2. Set the type for ExtraHandle Column.
Those are required to implement the chunk execution in the faketikv and mocktikv.

expression/aggregation, plan: set PB field type and ExtraHandle column  type

---

meta/autoid/autoid_test.go

reduce autoid test concurrency from 100 to 10.
Makes test more stable.
unit test
NO
NO
NO

meta/autoid: reduce concurrency in test

---

executor/aggfuncs/func_count.go

- Exist tests
##Does this PR affect documentation (docs/docs-cn) update? (mandatory)
- No
##Does this PR affect tidb-ansible update? (mandatory)
- No
##Does this PR need to be added to the release notes? (mandatory)
- No
go test -bench .
goos: linux
goarch: amd64
BenchmarkRowPointer-12        2000000000             0.65 ns/op
BenchmarkRow-12               50000000            33.4 ns/op
PASS

avoid very slow structure to interface type converation

---

table/tables/index_test.go
table/tables/memory_tables_test.go

Close the domain and store in test suite `TearDown` method.
- Improve the stability of the test.
unit test
No
No
No

table/tables: fix goroutine leak

---

executor/aggfuncs/func_avg.go
executor/aggfuncs/func_bitfuncs.go
executor/aggfuncs/func_count.go
executor/aggfuncs/func_first_row.go
executor/aggfuncs/func_group_concat.go
executor/aggfuncs/func_max_min.go
executor/aggregate.go

- Improvement
Exist tests
no
no
no
#7121 
flame graph to be uploaded

executor: pass row pointer rather than row to avoid convertT2I

---

statistics/table.go
statistics/update.go

When updating the stats cache, we will check if the histogram version is changed. If changed, we will also load the buckets from storage. So even if the version is caused by column size change, we will also read the buckets. This PR does not change histogram version when updating column size, thus avoiding unnecessary reads.
Existing test.
No.
No.
No.
PTAL @coocood @zz-jason @winoros

stats: do not change histogram version when updating column size

---

server/conn_stmt.go
server/conn_stmt_test.go

Cherry pick #6922 to release 2.0.
Unit tests and manual tests.
No.
No.
release note:
Fix binary numeric type overflow.
PTAL @coocood @lysu

server: fix binary numeric type overflow (#6922)

---

config/config.go
config/config.toml.example
executor/simple.go

When compatible-kill-query option is turned on, "kill xxx" command will not be
ignored, it works like "kill tidb xxx".
- New feature (non-breaking change which adds functionality)
manually
Yes
No
Yes
https://github.com/pingcap/tidb/issues/7183
@shenli @coocood

config,executor: provide a compatible-kill-query option in the config file

---

util/chunk/chunk.go
util/chunk/chunk_test.go

Fix the wrong nullBitmap index after truncate. 
Cherry-pick https://github.com/pingcap/tidb/pull/7216
Fix the wrong nullBitmap index after truncate.
Unit test
NO
NO
NO

util/chunk: fix chunk truncate (#7216)

---

statistics/update.go
statistics/update_test.go

After updating the histograms in local feedback, we should also calculate the scalar info, or it will cause panic in queries.
Fix #7213 
Unit test.
No.
No.
No.
PTAL @coocood @zz-jason @winoros

stats: calculate the scalar info for histogram after local update

---

expression/column.go
expression/column_test.go
expression/constant_test.go
expression/expression.go
expression/expression_test.go
expression/scalar_function_test.go
expression/schema.go
expression/schema_test.go
expression/simple_rewriter.go
plan/expression_rewriter.go
plan/find_best_task.go
plan/logical_plan_builder.go
plan/planbuilder.go
plan/point_get_plan.go
plan/rule_aggregation_push_down.go
plan/rule_build_key_info.go
plan/rule_join_reorder.go
plan/rule_predicate_push_down.go
plan/task.go

Variable renaming.
- refactor
Don't need.

expression, plan: rename `Column.Position` to `Column.UniqueID`

---

executor/analyze.go
metrics/metrics.go

Recover from panic if analyze worker goes into trouble.
@winkyao @lamxTyler

executor: panic recover for analyze worker

---

util/chunk/chunk.go
util/chunk/chunk_test.go

When we append null, we simply increment the nullCount,
so we need to clear the unused bits in the last bitmap byte.
Clear the unused bits in the last bitmap byte in `chunk.TruncateTo` 
Unit test
NO
NO
NO

util/chunk: fix TruncateTo again

---

executor/prepared_test.go
executor/write_test.go
plan/logical_plan_builder.go
types/datum.go
types/etc.go

plan, executor: check b.err when building logical plan(#7114)(#7204)

---

CHANGELOG.md

update change-log add 2.0.6
update change-log add 2.0.6
NO CODE
NO
NO
NO

docs: update change-log add 2.0.6

---

Makefile

Sometimes the current CI server needs more than 600 seconds to run `make race` for ddl or executor packages. This pr,
1. add a  to 20 minutes timeout for `make race`.
1. rollback gofail modified files when `make race` failed.
Unit tests.
No.
No.
No.
PTAL @tiancaiamao @coocood

Makefile: add a timeout for make race

---

executor/write.go
table/tables/partition.go
table/tables/tables.go
table/tables/tables_test.go

1. Rewrite `CheckHandleExists` though we do not need to expose `Partition` for executor.
1. Rename struct `Partition` to `partition` and `PartitionedTable` to `partitionedTable`, then we can easily explicit the interface PartitionedTable to struct partitionTable, like interface `Table` to struct `table`, interface `Index` to struct `index`.
Unit test.
No.
No.
No.
PTAL @tiancaiamao @coocood

table: tiny refactor partition by rewriting CheckHandleExists and changing the name

---

Makefile

makefile go get use etcd-io instead of coreos
- unit tests
- integration tests
no
no
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/7341)

Makefile: fix gofail go get repo path

---

.github/pull_request_template.md

This PR refines the pull request template, guide the PR author to write better the pull request description.
1. put `What problem does this PR solve` on the first section.
This is the section the reviewers most care about.
2. add `how it works` in the end of `What is changed`.
The auther tend to answer the title question and ignore the long description in the comments, include `how it works` reminds the author to explain the `How`.
3. Make a checklist to fill out.
Makes the YES/NO questions easier to answer, simplify the templates and added more questions.
Tests 
- No code

docs: refine the pull request template

---

Makefile

cherry pick  #7341 
- unit tests
- integration tests
no
no
no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/7342)

Makefile: fix gofail go get repo path (#7341)

---

ddl/db_test.go
executor/insert.go
executor/replace.go
executor/write_test.go
store/mockstore/mocktikv/cop_handler_dag.go
types/datum.go

Add logs for `replace` and `insert on dup` statements when some critical errors occur.
Add more info in log files.
Tests 
- Unit test
Code changes
Side effects
PTAL @coocood

* add logs for replace and insert on dup statements

---

docs/design/2018-07-01-refactor-aggregate-framework.md
docs/design/README.md

1. Add description for MergePartialResult in proposal refactor-aggregate-framework.
2. Add links for proposals in README.md
Tests 
- No code
Code changes
Side effects

docs: add MergePartialResult for refactor-aggregate-framework doc

---

executor/executor_test.go
expression/helper.go

cherry-pick #7355
Tests 
- Unit test
Code changes
- Impl change
Side effects
- no
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/7467)

expression: fix fraction part handle of current_timestamp (#7355)

---

ddl/ddl.go
ddl/ddl_api.go
ddl/partition.go

Some functions are not allowed in partition expression when creating a partitioned table.
Tiny fix
Tests 
Tests depend on https://github.com/pingcap/tidb-test/pull/610
@ciscoxll @crazycs520 @winkyao

ddl: fix partition function check for partitioned table

---

domain/domain.go
server/tidb_test.go
statistics/update.go
table/tables/tables.go
x-server/conn.go

pass tests under Go 1.11
Cherry-Pick https://github.com/pingcap/tidb/pull/7178
Tests 
- Unit test

*: fix format placeholders and TLS test.

---

docs/design/README.md

add a link in docs/design/readme

docs/design: add restore-dropped-table link in readme

---

ddl/delete_range.go
session/bootstrap.go

This PR cherry picks a bug fix in master to release. Please refer to #7610 for details
cherry-pick a commit to release-2.0 branch.
Tests 
- Already tested in #7610

cherry-pick a bug fix to release-2.0: Use TSO instead of seconds in gc_delete_range table (#7610)

---

CHANGELOG.md

Add the change logs for 2.0.7 release.
Update CHANGELOG.md
Tests 
- No code

CHANGELOG: Add 2.0.7 change logs

---

mysql/type.go
server/conn_stmt.go
server/http_handler.go
server/http_status.go
server/server_test.go

This pr is referred to Issue #3120. And i just fix comments mistakes in package mysql and package server.

*: correct comments mistake.

---

Gopkg.lock
Gopkg.toml
vendor/github.com/pingcap/tidb-tools/pkg/utils/urls.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/client.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/pump.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/selector.go

update vendor for pump client
remove tidb-tools's info in Gopkg.toml, and then 
dep ensure -add github.com/pingcap/tidb-tools/tidb-binlog/pump_client@ff0ddbf51b5744cca6d426b892a5dac5aa97a014
sh hack/clean_vendor.sh

binlog: update vendor for pump client

---

expression/aggregation/aggregation.go
expression/aggregation/concat.go
expression/aggregation/descriptor.go
expression/builtin_arithmetic.go
expression/builtin_control.go
expression/builtin_info.go
expression/builtin_info_test.go
expression/builtin_json.go
expression/builtin_math.go
expression/builtin_other.go
expression/builtin_time.go
expression/column.go
expression/simple_rewriter.go

As i mentioned [here](https://github.com/pingcap/tidb/issues/3120#issuecomment-421571317) for #3120 .

expression: fix comments mistake

---

CONTRIBUTING.md

doc: remove duplicate space

---

tidb-server/main.go

tidb-server: set TiDBMemQuotaQuery to the value in configuration file(#7729)

---

docs/QUICKSTART.md

The documentation of the binary deployment has already not existed.
This PR fixes the dead link.
Tests 
- No code

*: fix a dead link

---

util/chunk/chunk.go
util/chunk/chunk_test.go

util: refine chunk.SwapColumn to rebuild the column reference (#7841)

---

ddl/index.go
executor/admin_test.go

cherry-pick from https://github.com/pingcap/tidb/pull/7724

ddl: fix add index on timestamp column bug

---

executor/aggfuncs/func_avg.go
executor/builder.go
expression/aggregation/descriptor.go
expression/typeinfer_test.go

executor: refine the precision for avg (#7860)

---

statistics/histogram.go
statistics/selectivity_test.go

cherry pick #7814 to 2.1
(cherry picked from commit d5d8ba09a3c4c2a0f30d98edacafe7030755728f)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/7856)

stats: fix combined index low-bound check (#7814)

---

Gopkg.lock
Gopkg.toml
vendor/google.golang.org/grpc/rpc_util.go
vendor/google.golang.org/grpc/transport/http2_server.go
vendor/google.golang.org/grpc/transport/http_util.go
vendor/google.golang.org/grpc/transport/transport.go

Fix data race in grpc 1.12.0. The detailed information can be found in pingcap/pd#1264.
This PR bumps grpc to 1.12.2.
Tests 
- No code

*: bump grpc to 1.12.2

---

expression/function_traits.go
expression/function_traits_test.go

cherry pick #7838 to release 2.0
Tests 
- Unit test
Code changes

expression: make sysdate unfoldable (#7838)

---

expression/builtin_string.go
expression/integration_test.go

cherry pick #7806 to release 2.1
Tests 
- Unit test

expression: fix painc on substring_index (#7806)

---

CHANGELOG.md

Add release note for v2.0.8
@shenli @lilin90 @zz-jason PTAL

CHANGELOG: Add 2.0.8 change logs

---

executor/executor_test.go
plan/column_pruning.go

planner, executor: refine ColumnPrune for LogicalUnionAll (#7930)

---

executor/adapter.go
session/session.go

Cherry pick #7951 to release 2.1.

executor: add the slow log for commit (#7951)

---

ddl/ddl_worker.go
ddl/ddl_worker_test.go

cherry-pick from https://github.com/pingcap/tidb/pull/7940
Tests 
- Unit testCode changes

ddl: fix invailid ddl job panic (#7940)

---

executor/executor_test.go
planner/core/logical_plan_builder.go

executor, planner: clone proj schema for different children in buildProj4Union (#7999)

---

CHANGELOG.md

add changelog for v2.1.0-rc.4
Tests 
- No code

add changelog for v2.1.0-rc.4

---

executor/builder.go
executor/insert.go
executor/insert_common.go
executor/load_data.go
executor/replace.go
executor/update.go

cherry pick from #7935
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8024)

executor: improve wide table insert & update performance (#7935)

---

expression/integration_test.go
util/charset/encoding_table.go

Cherry pick from #7339, Fix #8042

util/charset: Add utf8mb4 as alias for utf8 (#7339)

---

planner/core/exhaust_physical_plans.go
planner/core/expression_rewriter.go
planner/core/find_best_task.go
planner/core/initialize.go
planner/core/logical_plan_builder.go
planner/core/logical_plan_test.go
planner/core/plan.go
planner/core/planbuilder.go
planner/core/rule_aggregation_elimination.go
planner/core/rule_aggregation_push_down.go
planner/core/rule_decorrelate.go
planner/core/rule_join_reorder.go
planner/core/rule_max_min_eliminate.go
planner/core/rule_partition_processor.go
planner/core/rule_predicate_push_down.go
planner/core/rule_topn_push_down.go
planner/core/task.go

export the "init()" function. makes other packages be able to use it.
Tests 
- Unit test
Code changes

planner: export init() to Init()

---

config/config.go
config/config.toml.example
config/config_test.go
ddl/ddl.go
session/session.go
session/session_test.go
session/tidb.go
session/tidb_test.go
sessionctx/binloginfo/binloginfo.go
sessionctx/binloginfo/binloginfo_test.go
sessionctx/variable/session.go
table/tables/tables_test.go
tidb-server/main.go

cherry pick commit in binlog-dev
pr: https://github.com/pingcap/tidb/pull/7659
git cherry-pick 71d13534aabe07d42b42681531a83b5fb5b6a407

binlog: use pumps client to write binlog (#7659)

---

infoschema/tables.go
infoschema/tables_test.go

infoschema: fix pseudo data for profiling table (#8092)

---

executor/executor_test.go
planner/core/resolve_indices.go

cherry-pick #8073 
PTAL @winoros @zz-jason @eurekaka @lamxTyler

planner: refine PhysicalProjection.ResolveIndices during neighbouringProj(#8073)

---

statistics/boostrap.go
statistics/dump.go
statistics/handle.go
statistics/histogram.go
statistics/selectivity.go
statistics/selectivity_test.go
statistics/table.go

stats: fix selectivity estimation for primary key (#8134)

---

executor/executor_test.go
plan/resolve_indices.go

planner: refine PhysicalProjection.ResolveIndices during neighbouringProj (#8073)

---

executor/executor_test.go
planner/core/exhaust_physical_plans.go
planner/core/find_best_task.go

 planner: fix issue#8135 (#8143)

---

statistics/gc.go
statistics/handle_test.go

stats: fix converting duration to timestamp (#8174)

---

CONTRIBUTING.md

update CONTRIBUTING.md  dependency management descrption and go version should be 1.11 or above.
update CONTRIBUTING.md  dependency management descrption and go version should be 1.11 or above.
Tests 
- No code

CONTRIBUTING.md: update the description of dependency management

---

session/session.go
store/tikv/2pc.go
store/tikv/backoff.go
store/tikv/coprocessor.go
store/tikv/scan.go
store/tikv/snapshot.go

cherry-pick #8207
(cherry picked from commit 81d2fff83c5ffc845862b6a48adc9c886e38a2e9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8239)

store/tikv: refine backoff log (#8207)

---

cmd/explaintest/r/explain_easy.result
planner/core/logical_plan_builder.go
planner/core/logical_plan_test.go

planner: fix union statements order (#8214)

---

Gopkg.lock
Gopkg.toml
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/client.go

fix a bug in pump client, need update vendor for it.
dep ensure -add github.com/pingcap/tidb-tools/tidb-binlog/pump_client@8dd71127bcf09130ae032ab6877dd22f32b53e14
sh hack/clean_vendor.sh

update vendor for pump client

---

CHANGELOG.md

add changelog for v2.1.0-rc.5 (#8272)

---

kv/txn.go
store/tikv/2pc_fail_test.go

kv, store: remove `Rollback` in `RunInNewTxn` (#8250)

---

executor/index_lookup_join_test.go
executor/join_test.go
planner/core/exhaust_physical_plans.go
planner/core/logical_plan_builder.go
planner/core/logical_plans.go
planner/core/physical_plan_test.go

cherry-pick #8243 to release-2.1

planner/core: make TIDB_INLJ to specify the inner table (#8243)

---

executor/executor_test.go
planner/core/logical_plan_builder.go
planner/core/logical_plan_test.go

planner, executor: eliminate extra columns introduced by OrderBy upon Union (#8290)

---

executor/adapter.go
executor/builder.go
executor/errors.go
executor/executor.go
executor/executor_test.go
executor/index_lookup_join.go
executor/simple.go
planner/core/logical_plan_builder.go
session/session.go
session/session_test.go
session/tidb.go
session/txn.go
sessionctx/context.go
table/tables/tables.go
util/mock/context.go

Cherry pick from https://github.com/pingcap/tidb/pull/8260
@jackysp @zz-jason @winkyao @zimulala

session,executor: run statement without transaction (#8260)

---

domain/schema_validator_test.go
executor/set_test.go
sessionctx/variable/session.go
sessionctx/variable/varsutil.go

variable: validate setting tx_isolation variable value (#8299)

---

executor/explain.go

util/execdetail: fix race 2.1

---

session/session.go

Cherry-pick #8281 to release 2.1

session: add sql types for commit and retry logs (#8281)

---

executor/adapter.go
executor/builder.go
executor/executor.go
executor/executor_test.go
executor/index_lookup_join.go
executor/simple.go
plan/logical_plan_builder.go
session/session.go
session/session_test.go
session/tidb.go
session/txn.go
sessionctx/context.go
util/mock/context.go

Cherry pick from https://github.com/pingcap/tidb/pull/8260 to release-2.0 branch
Tiny modify to address conflict.
PTAL @jackysp @zz-jason @zimulala @winkyao

session,executor: run statement without transaction

---

README.md

Related comment: https://github.com/pingcap/docs/pull/677#issuecomment-430252483
Update the ETL description. Related comment: https://github.com/pingcap/docs/pull/677#issuecomment-430252483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8369)

readme: update ETL description

---

session/bootstrap_test.go
session/session.go

Cherry pick from https://github.com/pingcap/tidb/pull/8353
@winkyao @jackysp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8367)

session: fix bootstrap error in ANSI sql_mode (#8353)

---

executor/join.go

fixes CI failure introduced by  #8338
- don't use waitGroup
- listen closeChan close
- listen innerResultChan close
Tests 
- Unit test
Code changes
- impl change
Side effects
- N/A
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8374)

executor: fix hash join sqllogic test block

---

executor/insert_test.go
server/util.go
server/util_test.go
types/datum.go
types/time.go
types/time_test.go

cherry-pick https://github.com/pingcap/tidb/pull/8292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8397)

server,types: convert zero input correctly for column type `year`

---

executor/join.go

chery-pick #8374 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8392)

executor: fix hash join sqllogic test block, data race.

---

docs/tidb_http_api.md
server/http_handler.go

cherry-pick https://github.com/pingcap/tidb/pull/8424
Tests 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8425)

server/http: fix scatter table API and add document (#8424)

---

domain/schema_validator_test.go

Cherry-pick #8334
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8409)

domain: make TestSchemaValidator stable (#8334)

---

executor/aggfuncs/func_count_test.go
executor/aggfuncs/func_max_min_test.go
executor/aggfuncs/func_sum_test.go

cherry-pick #7993
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8445)

executor/aggfuncs: split unit tests to corresponding file (#7993)

---

ddl/ddl.go
ddl/fail_db_test.go

Add a simple test to cover more code, improve test coverage.
Mock getGlobalID fail
Tests 
- Unit test
PTAL @crazycs520 @ciscoxll @winkyao
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8440)

ddl: add some test code to mock genGlobalID fail

---

session/session.go
session/txn.go
sessionctx/variable/session.go

cherry-pick #8458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8466)

session: release datum memory after transaction finished (#8458)

---

statistics/dump_test.go
statistics/histogram.go
statistics/table.go

Cherry-pick #8448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8462)

stats: fix panic when dumping stats (#8448)

---

executor/prepared_test.go
planner/core/planbuilder.go

cherry-pick #8437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8489)

planner, executor: fix `PREPARE FROM @var_name` (#8437) 

---

executor/write_test.go
table/column.go
table/column_test.go
types/datum.go

Cherry pick #8469 to release 2.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8476)

table, executor: set a real enum as the default enum value (#8469)

---

ddl/ddl.go
ddl/fail_db_test.go
ddl/mock.go
domain/domain.go
domain/schema_validator.go
domain/schema_validator_test.go

Cherry-pick from #8441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8492)

domain: stop schema validator to prohibit DML executing when tidb lost session of etcd (#8441)

---

server/server.go
tidb-server/main.go

cherry-pick #8446 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8475)

server: close connection when tidb server closed. (#8446)

---

executor/prepared_test.go
plan/planbuilder.go

cherry-pick #8437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8488)

planner, executor: fix `PREPARE FROM @var_name` (#8437)

---

session/session.go
session/session_test.go
session/txn.go

Cherry-pick from https://github.com/pingcap/tidb/pull/8434 to release-2.1
PTAL @jackysp @winkyao
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8502)

session: add GoString() for TxnState and make the log more use friendly (#8434)

---

executor/index_lookup_join.go
executor/join_test.go

cherry-pick #8505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8508)

executor: do not build range for NullOuterVal in IndexLookUpJoin (#8505)

---

domain/domain.go
session/session.go
session/tidb_test.go

Cherry-pick from https://github.com/pingcap/tidb/pull/8456 to release-2.0 branch
@lysu @winkyao
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8501)

domain,session: simplify the session pool of domain (#8456)

---

kv/union_store.go
session/txn.go
store/tikv/txn.go

cherry-pick #8527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8528)

tidb/kv: remove useless errors.Trace (8527)

---

executor/executor_test.go
store/mockstore/mocktikv/pd.go

Make our code more robust
Add test
Tests 
- Unit tes
- No code
release-2.0 and release 2.1 may fail on this test
@winkyao  @crazycs520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8566)

executor,store/mockstore: add a test to mock get tso fail

---

planner/cascades/enforcer_rules.go
planner/cascades/enforcer_rules_test.go
planner/cascades/group.go
planner/cascades/group_test.go
planner/cascades/implementation.go
planner/cascades/implementation_rules.go
planner/cascades/implementation_test.go
planner/cascades/optimize.go
planner/cascades/optimize_test.go
planner/core/find_best_task.go
planner/core/plan.go
planner/core/point_get_plan.go
planner/core/task.go
planner/property/logical_property.go

Not a problem. This patch is for implementation phase framework of cascades planner, detailed implementation rules are not in the scope of this PR.
- Add implementation rule interface
- Add enforcer interface
- Add implementation interface which wraps up cost logic for physical plan nodes, detailed cost model integration is split into next PR
- Add search algorithm for implementations
- Introduce logical property, which would be derived in exploration phase (in another PR)
Tests 
- Unit test
Code changes
Side effects
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8449)

plan: implementation phase framework of cascades planner

---

executor/insert.go
table/column.go

Some minor changes to make the code more readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8627)

executor,table: remove redundant if condition and fix comment typos

---

expression/builtin_compare.go
expression/builtin_json.go
expression/util.go

cherry-pick #8564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8660)

expression: do not set ParseToJSONFlag to a JSON column (#8564)

---

CHANGELOG.md

Add the change log for release 2.1.1
Tests 
- No code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8666)

docs: add the change log for release 2.1.1

---

server/conn_stmt.go

Cherry-pick #8645 to release 2.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8677)

server: reset bound arguments when it is executed by execute command (#8645)

---

session/session.go
session/session_fail_test.go
session/tidb.go
session/txn.go
table/tables/tables_test.go

Make the code more robust and easier to debug bug.
Add an error log if the transaction state is unexpected when calling `Commit` 
Tests 
- No code
@winkyao @crazycs520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8687)

session: add error log to catch bug stack in Commit

---

server/conn.go
server/server.go

cherry-pick #8692.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8708)

server: close all connection directly when terminate tidb (#8692)

---

executor/executor.go

admin: check transaction valid before execute. Because of the transaction maybe nil.
Tests 
Code changes
Side effects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8714)

admin: check transaction valid before execute

---

ddl/ddl_test.go
ddl/index.go
domain/domain.go
expression/constraint_propagation.go
planner/cascades/optimize.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8722)

*: fix misspelled words

---

executor/merge_join_test.go
planner/core/exhaust_physical_plans.go
planner/property/physical_property.go

cherry-pick https://github.com/pingcap/tidb/pull/8635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8729)

plan: build separate required physical property for children

---

session/session.go
session/session_fail_test.go
session/txn.go

Add gofail test for https://github.com/pingcap/tidb/pull/8743
Add a gofail test.
Tests 
- Unit test
Code changes
Side effects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8771)

session: add gofail test for (#8743)

---

Gopkg.lock
Gopkg.toml
vendor/github.com/pingcap/tidb-tools/pkg/utils/cpu.go
vendor/github.com/pingcap/tidb-tools/pkg/utils/errors.go
vendor/github.com/pingcap/tidb-tools/pkg/utils/printer.go
vendor/github.com/pingcap/tidb-tools/pkg/utils/security.go
vendor/github.com/pingcap/tidb-tools/pkg/utils/tso.go
vendor/github.com/pingcap/tidb-tools/pkg/utils/urls.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/node/node.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/node/registry.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/client.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/pump.go
vendor/github.com/pingcap/tidb-tools/tidb-binlog/pump_client/selector.go

add vendor for pump client
dep ensure -add
Tests 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8815)

add vendor for pump client

---

executor/show.go
executor/show_test.go

Add `SHOW FULL TABLES` to show view status
ref proposal [Proposal: Implement View](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-24-view-support.md)
Tests
- Unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8860)

executor: show full tables support view

---

util/ranger/ranger.go
util/ranger/ranger_test.go

cherry-pick #8851 to release-2.0 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8877)

util/ranger: fix incorrect behavior about index who has prefix column(#8851)

---

ddl/ddl_db_test.go
ddl/ddl_test.go
ddl/ddl_worker_test.go
ddl/rollingback.go
util/admin/admin.go

Cherry pick #8545
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8464)

ddl: fix cancel drop column ddl error

---

planner/core/logical_plan_builder.go

Explain why the update statement using the writable columns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8913)

docs: add comments about why update statement using writable columns.

---

executor/show.go
session/session_fail_test.go
session/txn.go

Cherry-pick from https://github.com/pingcap/tidb/pull/8918
@winkyao @lysu @crazycs520
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8923)

session: add a `doNotCommit` flag to transaction when `StmtCommit` fail (#8918)

---

CHANGELOG.md

Add changelog for v2.0.11
@zz-jason @jackysp PTAL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8925)

CHANGELOG: add changelog for v2.0.11

---

ddl/db_test.go
ddl/ddl_api.go

fix #8959
make rename table error code compatible with mysql
* Unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8960)

ddl: fix rename table compatibility

---

executor/join_test.go
types/mydecimal.go
types/mydecimal_test.go
util/codec/codec.go

util/codec, types: add new method to get comparable hash key from MyDecimal

---

executor/distsql.go
executor/executor_test.go
executor/prepared.go
executor/write_test.go
expression/builtin_cast.go
expression/errors.go
sessionctx/stmtctx/stmtctx.go
sessionctx/variable/session.go
types/convert.go
types/datum.go

Cherry pick #8544 to release 2.0.

*: fix the lower bound when converting numbers less than 0 to unsigned integers

---

Makefile
tools/check/go.mod
tools/check/go.sum

Update `errcheck` to [v1.2.0](https://github.com/kisielk/errcheck/releases/tag/v1.2.0) which support Go Modules.
Tests 
- No code

*: update errcheck

---

cmd/explaintest/r/explain_easy.result
cmd/explaintest/t/explain_easy.test
planner/core/logical_plans.go

cherry pick #8047 to release 2.1
fix https://github.com/pingcap/tidb/issues/9034

support _tidb_rowid for table scan range (#8047)

---

executor/update_test.go
plan/logical_plan_builder.go

cherry pick #8909 to release 2.0

planner: update generated column inside a transaction should return error (#8909)

---

executor/merge_join.go
executor/merge_join_test.go

executor: reset hasMatch flag for each outer row in merge join (#9046)

---

CHANGELOG.md

Add release note 3.0.0-beta to CHANGLOG.md.

*: add release note 3.0.0-beta to CHANGLOG.md

---

store/tikv/2pc.go

Cancel the context all the time to avoid memory leaks
Tests 
Has been tested manually。
Code changes
No broken changes
Side effects
None
Nothing

Cancel the context to avoid memory leaks

---

ddl/db_integration_test.go
ddl/db_test.go
ddl/ddl_api.go

Cherry pick #9107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/8464)

ddl: restricting altering the utf8 charset to utf8mb4 

---

statistics/update.go
statistics/update_test.go

statistics: log the reason when triggering auto analyze (#9176)

---

CHANGELOG.md

Pick 2.1.3 release notes into master, from #9174

CHANGELOG: add release notes for v2.1.3 (#9174)

---

ddl/ddl_worker_test.go

Fix ddl test fail by paralle test.
add check.
Tests 
- No code
Code changes
Side effects

ddl: fix ddl test fail by paralle test

---

expression/builtin_other.go
expression/integration_test.go

cherry pick #9215 to release-2.0

expression: handle Float32 for builtin function Values() (#9215)

---

domain/domain.go

fix #9236
change the log level from INFO to DEBUG
Tests 

domain: change "reload privilege success" to DEBUG level

---

util/chunk/row.go

A typo in the comment
Correct a typo
Tests 
- No code
Code changes
- None
Side effects
- None
- None

util/chunk: correct a typo in the comment

---

expression/builtin_time.go

Some typos in the comments.
Fix some typos by change "Add" to "Sub".
Tests 
- No code
Code changes
- None
Side effects
- None
- None

expression: fix some typos in the comments

---

executor/write_test.go
session/txn.go

Cherry-pick #9199 to release 2.1.

*: add some tests for writing-data corner cases (#9199)

---

executor/builder.go
executor/show_test.go
planner/core/planbuilder.go
planner/core/planbuilder_test.go

fix 'show master status' output
git cherry-pick df55d3815d98bdd90f8f86b97fe71a76ac0f85cb
Tests 
- Manual test (execute `show master status` in tidb)

executor,planner: fix 'show master status' output (#8737)

---

domain/domain.go

cherry pick #9237 to release 2.0

domain: change "reload privilege success" to DEBUG level (#9237)

---

distsql/distsql_test.go
distsql/request_builder_test.go
distsql/select_result.go
distsql/stream.go
util/chunk/chunk.go
util/chunk/chunk_test.go

Control the number of rows in chunks returned by SelectResult

---

cmd/explaintest/r/explain_complex.result
cmd/explaintest/r/explain_complex_stats.result
cmd/explaintest/r/explain_easy.result
cmd/explaintest/r/tpch.result
executor/builder.go
planner/core/cbo_test.go
planner/core/optimizer.go
planner/core/physical_plan_test.go
planner/core/rule_build_proj_below_agg.go

planner, executor: add post-process after physical plan optimization and move buildProjBelowAgg from executor to planner (#8828)

---

planner/core/optimizer.go
planner/core/rule_inject_extra_projection.go

executor: introduce projInjector for postOptimize (#9097)

---

expression/builtin_cast.go
expression/builtin_cast_test.go
types/datum.go

cherry-pick https://github.com/pingcap/tidb/pull/8768

expression: return null when cast to huge binary type (#8768)

---

tidb-server/main.go

Fix misspell.
"seperated" is a misspelling of "separated" (misspell)
Just change only a word.

tidb-server:Fix misspell

---

go.mod
go.sum

go.mod: update parser

---

ddl/table.go

fix the errcheck
Signed-off-by: Keyi Xie <xiekeyi98@gmail.com>
Catch and check the error.
Add `if` to check error

ddl: add err check in table.go

---

plan/expression_rewriter.go
plan/expression_rewriter_test.go

cherry-pick https://github.com/pingcap/tidb/pull/9106

plan: check null and empty for `!= any(subq)` and `= all(subq)` (#9106)

---

domain/schema_validator_test.go

Handle #9369
Make sure newItem's version is bigger than currVer, and add some log to trace this test.

domain: make tests stable

---

session/txn.go

Fix data race.
Tests 
- Unit test

test: fix gofail test race

---

ddl/index.go
executor/admin.go
executor/write.go
executor/write_test.go
kv/fault_injection.go
kv/kv.go
kv/mock.go
kv/txn.go
session/txn.go
store/tikv/txn.go

Cherry-pick #9374 to release 2.0.

*: merge statement buffer when BatchGetValues (#9374)

---

session/txn.go

Cherry-pick #9412 to release 2.1.

test: fix gofail race (#9412)

---

ddl/db_test.go
ddl/ddl_algorithm_test.go
ddl/ddl_api.go

Fix ineffassign and mis-spell.

ddl:fix ineffassign and mis-spell

---

expression/builtin_math.go
expression/integration_test.go

expression: refactor builtin function RAND to be compatible with MySQL (#9387)

---

statistics/feedback.go
statistics/update_test.go

stats: restrict the adjust factor for index feedback (#9445)

---

executor/admin_test.go
util/admin/admin.go

cherry-pick #9108 
Tests 
- Unit test
Code changes

admin: fix admin check table err when add column not null, then add index on the column (#9108)

---

ddl/db_test.go
ddl/rollingback.go
util/admin/admin.go

Cherry pick #8977
Tests 
- Unit test

ddl: fix cancel truncate table ddl error

---

ddl/ddl_worker.go

ddl: write binlog when ddl job state is done. (#9207)

---

expression/expr_to_pb.go
expression/integration_test.go

Cherry pick from https://github.com/pingcap/tidb/pull/9473
PTAL @zz-jason @XuHuaiyu

expression: fix timezone for timestamp constant when converting expression to pb (#9473)

---

ddl/db_test.go
ddl/ddl_api.go

ddl: fix check column field length when add column (#9143)

---

session/session.go

It should be upgraded to 27 in 45f9d6a00f4e08ae97d60a3348ce9a6fbe710987, but it was lost when merging conflicts.
Bump version.
Tests 
- Manual test: before applying this patch, there are many error message in log saying "cannot find column correlation"; after applying this patch, those error messages disappear.
Code changes
N/A
Side effects
N/A
N/A

session: upgrade currentBootstrapVersion to 27

---

executor/show_stats.go
executor/show_stats_test.go
statistics/table.go

cherry-pick https://github.com/pingcap/tidb/pull/9487

executor: only show valid columns in `stats_histogram` (#9487)

---

CHANGELOG.md

NOTE: I labeled this PR as "2.1 cherry-pick", but actually this is the original PR. I will cherry pick it to master branch as it merged.
as the title said
Tests 
- No code

CHANGELOG: add changelog for v2.1.5

---

ddl/ddl_api.go
ddl/ddl_db_test.go
ddl/ddl_worker.go
ddl/ddl_worker_test.go
ddl/index.go
ddl/rollingback.go
plan/planbuilder.go
util/admin/admin.go
util/schemautil/schemautil.go

ddl: fix cancel drop index error (#8504)

---

ddl/db_test.go
ddl/ddl_worker_test.go
ddl/rollingback.go
ddl/schema.go
ddl/table.go
util/admin/admin.go

ddl: fix cancel drop table/database ddl job bug. (#8537)

---

executor/executor_test.go

The error has not checked in test.
Check it!
Check the error.
Tests 
- Unit test
Side effects
-  None
- None

executor: add error check

---

go.mod
go.sum

cherry-pick #9583 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9584)

*: update go-proxyprotocol version

---

ddl/ddl_worker_test.go
go.sum

Fix the test cases in TestCancelJob, which set the job type mistakenly.

ddl_test: fix the wrong test

---

ddl/ddl_worker_test.go
go.sum

ddl_test: fix the wrong test #9610

---

.codecov.yml
Makefile

Add codecov.yml.
Tests 
- No code

build:add codecov.yml

---

ddl/ddl_worker_test.go
ddl/rollingback.go
util/admin/admin.go

cherry-pick https://github.com/pingcap/tidb/pull/9419
Tests 
- Unit test

ddl: refine cancel modify column, add/drop foreign key rollback (#9419)

---

plan/gen_physical_plans.go
plan/stats.go

cherry-pick https://github.com/pingcap/tidb/pull/9497

planner: correct `ExpectedCnt` for children plans of join (#9497)

---

ddl/ddl_api.go
ddl/ddl_db_test.go

ddl: fix create table with like bug when refer table has non-public column/index (#9580)

---

executor/executor.go
util/memory/tracker.go

Tiny refactor, use more go idiom

*: tiny refactor, more go idiom

---

executor/executor_test.go
planner/core/find_best_task.go
planner/core/logical_plan_builder.go

planner, executor: check col.OrigColName instead of col.ColName in isCoveringIndex (#9637)

---

statistics/histogram.go
store/tikv/backoff.go

tidy local variable.
Make the code style more GO.
Drop the init.
Because all the variables in Golang will be auto-init.
Tests 
- Unit test

statistics,store: tidy local variable

---

planner/core/find_best_task.go
planner/core/logical_plans.go
util/ranger/detacher.go

Not a problem, just to make the code clearer, and remove obsolete fields of `DataSource`.
No code logic change.
Tests 
- No code: no code logic change
Code changes
N/A
Side effects
N/A
N/A

planner: tiny refactor for building table scan

---

cmd/explaintest/r/topn_push_down.result
cmd/explaintest/r/topn_pushdown.result
cmd/explaintest/t/topn_pushdown.test
executor/join_test.go
planner/core/physical_plan_test.go
planner/core/rule_inject_extra_projection.go
planner/core/rule_topn_push_down.go

cherry-pick #9684 to release 2.1

planner, executor: set new child after injecting Project operator (#9684)

---

CONTRIBUTING.md

The old CONTRIBUTING.md guild hasn't pointed out the PR title style
use https://github.com/pingcap/community/blob/master/commit-message-pr-style.md
Tests 
- No code

CONTRIBUTING.md: update commit message and pull request style

---

session/session.go

cherry pick #9654 to release 2.1

session: skip loading previlige when "skip-grant-table" is enabled (#9654)

---

ddl/ddl_worker_test.go
ddl/rollingback.go
ddl/table_test.go
util/admin/admin.go

ddl: add rolling back for rename table, modify table charset, truncate table partition (#9602)

---

executor/chunk_size_control_test.go

Fix goroutine leak in unit tests `chunk_size_control_test.go`.
Close `tikv.Client` after test.
Tests 
- Unit test

executor: fix goroutine leak in unit tests

---

executor/write_concurrent_test.go
util/testkit/ctestkit.go

we need to add test some concurrent case but need rework for every time to setup goroutine and so on...
reduce duplicate work and make write tidb concurrent test easier.
and use `TestBatchInsertWithOnDuplicate` to reproduce a old bug in 2.0.
Tests 
- Unit test
Code changes
- New methods
Side effects
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9645)

util/testkit: add concurrent test toolkit

---

ddl/column_test.go
ddl/ddl_api.go
ddl/ddl_worker_test.go
ddl/integration_test.go
ddl/mock.go
util/charset/charset.go

ddl: resolve the charset by the order: table->database->server (#9105)

---

statistics/bootstrap.go
statistics/feedback.go
statistics/handle.go
statistics/histogram.go
statistics/table.go
statistics/update.go
statistics/update_test.go

Unify log format in package statistics
Unify log format in package statistics.
Tests 
- No code
Code changes
- None
Side effects
- None

statistics: unify log format in package statistics

---

go.mod
go.sum

ref #https://github.com/pingcap/errors/pull/12, https://github.com/pingcap/errors/pull/12 need review first
Tests 
- Unit test
Code changes
- N/A
Side effects
- N/A
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9761)

*: update pingcap/errors version

---

infoschema/slow_log.go
sessionctx/variable/session.go

replace logger with zap logger and refine slow log.
Tests 
- No code
Code changes

infoschema: replace logger with zap logger and refine slow log

---

ddl/ddl_worker_test.go
ddl/rollingback.go
ddl/table_test.go
util/admin/admin.go

cherry-pick #9602, cherry-pick some part of the code because 2.0 not support some function.

ddl: add rolling back for rename table (#9602)

---

expression/builtin_time_test.go
types/time.go

types: fix incompatible issue for builtin function `str_to_date` (#9693)

---

planner/core/logical_plan_test.go
planner/core/planbuilder.go

Cherry pick from https://github.com/pingcap/tidb/pull/9828

planner/core: fix privilege check for grant on table (#9828)

---

planner/core/logical_plan_test.go
planner/core/planbuilder.go

privilege: add drop_priv check when truncate table (#9870)

---

cmd/importer/main.go
cmd/importer/rand.go
privilege/privileges/privileges.go
server/http_handler.go
server/http_handler_test.go
server/http_status.go
server/server.go
server/server_test.go
sessionctx/binloginfo/binloginfo.go

Use the unified log format for the package of `server` and the remaining packages.
Tests 
- Unit test

*: unify and normalize the format of the log in the pkg of server

---

cmd/pluginpkg/pluginpkg.go
go.mod
go.sum
plugin/conn_ip_example/conn_ip_example.go
plugin/conn_ip_example/conn_ip_example_test.go
plugin/conn_ip_example/manifest.toml
plugin/const.go
plugin/errors.go
plugin/helper.go
plugin/plugin.go
plugin/spi.go
plugin/spi_test.go

cherry-pick #8788 to 2.1
```
#	cmd/pluginpkg/pluginpkg.go
#	go.mod
#	go.sum
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9880)

plugin: introduce plugin framework (#8788)

---

README.md

Update README with latest and most accurate feature descriptions and formatting changes to facilitate more community engagement and support.
Tests 
- No code

Update README.md with up-to-date feature descriptions and better formatting

---

CHANGELOG.md

release notes for v2.1.7
@jackysp @zz-jason @shenli PTAL

CHANGELOG: add release notes for v2.1.7

---

domain/domain.go
executor/simple.go
go.mod
go.sum
plugin/conn_ip_example/conn_ip_example_test.go
plugin/plugin.go
plugin/spi.go
session/session.go
tidb-server/main.go

cherry-pick #9320 to 2.1
please review and merge https://github.com/pingcap/parser/pull/262 first thx~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9911)

 plugin: support `flush tidb plugin {name}` in tidb-server (#9320)

---

executor/show.go
executor/show_test.go

cherry-pick #9810 to v2.1
Related PR: pingcap/tidb-test#768

ddl:`show full columns` for date, datetime, timestamp compatibility (#9810)

---

metrics/session.go

Cherry-pick https://github.com/pingcap/tidb/pull/9925
PTAL @jackysp @lysu

metrics: adjust the parse & compile duration metrics (#9925)

---

config/config.go
config/config.toml.example
config/config_test.go
kv/kv.go
kv/memdb_buffer.go
store/tikv/2pc.go
tidb-server/main.go

Cherry pick #9035 to release 2.1.
Tests 
- Unit test
Code changes

config, kv: make TxnEntryCountLimit and TxnTotalSizeLimit configurable (#9035)

---

go.mod
go.sum
server/conn.go
server/conn_test.go
server/server.go
util/logutil/log.go

cherry-pick #9548 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9980)

log,server: add contextual log util & test it in conn.go (#9548)

---

session/bench_test.go
session/bootstrap.go
session/session.go
session/session_test.go
session/tidb.go
session/txn.go

Cherry-pick #9517 to release 2.1.

session: use the uniform log format for session (#9517)

---

expression/builtin_json.go
expression/builtin_json_test.go

Fix json_contains_path not compatible with MySQL. [#9984](https://github.com/pingcap/tidb/issues/9984)
Tests 
- Unit test

expression: fix json_contains_path not compatible with MySQL

---

domain/domain.go

Signed-off-by: Keyi Xie <xiekeyi98@gmail.com>
Some logs output wrong by my fault.
Fix it.
This error is introduced in https://github.com/pingcap/tidb/pull/9646
Make the log correct.
Tests 
- Unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10012)

domain: fix log typos.

---

util/admin/admin.go
util/kvencoder/kv_encoder.go
util/memory/action.go
util/misc.go
util/printer/printer.go
util/signal/signal_posix.go
util/signal/signal_windows.go
util/systimemon/systime_mon.go
util/timeutil/time.go

Cherry-pick #9668 to release 2.1

 util: use uniform log format for util package (#9668)

---

cmd/benchkv/main.go
cmd/explaintest/main.go

Go imports should be grouped by third-party lib and go lib.
Sort some libs order.
Tests 
- Unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10021)

cmd: tidy goimports

---

cmd/pluginpkg/pluginpkg.go
executor/adapter.go
executor/set.go
planner/core/optimizer.go
planner/core/planbuilder.go
plugin/audit.go
plugin/conn_ip_example/conn_ip_example.go
plugin/conn_ip_example/conn_ip_example_test.go
plugin/conn_ip_example/manifest.toml
plugin/plugin.go
plugin/spi.go
plugin/spi_test.go
server/conn.go
server/driver.go
server/driver_tidb.go
server/server.go
session/session.go
sessionctx/stmtctx/stmtctx.go
sessionctx/variable/session.go
util/sys/linux/sys_linux.go
util/sys/linux/sys_other.go
util/sys/linux/sys_test.go

cherry-pick #9136 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/9954)

plugin: add audit plugin extension point (#9136)

---

table/column.go
table/tables/partition.go
table/tables/tables.go

table: replace logger with zap logger (#9514)

---

go.mod
go.sum
server/driver_tidb.go
server/driver_tidb_test.go
server/tidb_test.go

driver_tidb.go: Optimize convertColumnInfo
fix https://github.com/pingcap/tidb/issues/9784
see https://github.com/pingcap/parser/pull/248
Tests 
- Unit test
Code changes
Side effects

driver_tidb.go: Optimize convertColumnInfo

---

util/set/float64_set_test.go
util/set/int_set_test.go
util/set/string_set_test.go

add ut for package `util/set`, improve ut coverage from 0% to 100%
add ut
Tests 
- Unit test

set: improve ut coverage to 100%

---

plan/logical_plan_builder.go
plan/logical_plan_test.go
plan/logical_plans.go
plan/predicate_push_down.go

plan: push down constant filters over join properly (#9848)

---

config/config.toml.example
docs/design/2018-07-22-enhance-propagations.md
docs/design/2018-09-10-adding-tz-env.md

Fix misspell.
Make words correct.
Tests 
- No code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10067)

docs,config: fix misspell

---

planner/core/logical_plans.go
planner/core/logical_plans_test.go
planner/core/stats.go

planner: unify the log format(#9630)

---

expression/builtin_string.go
expression/builtin_time.go
expression/constant.go
expression/constant_fold.go
expression/constant_propagation.go
expression/distsql_builtin_test.go
expression/expr_to_pb.go

expression: using pingcap/log and unify the log format (#9507)

---

cmd/benchdb/main.go
cmd/benchfilesort/main.go
cmd/benchkv/main.go
cmd/benchraw/main.go
cmd/explaintest/main.go
cmd/importer/db.go
cmd/importer/job.go
cmd/importer/stats.go
kv/txn.go
kv/union_iter.go
meta/autoid/autoid.go
meta/meta.go
plugin/plugin.go
types/datum.go
types/time.go

*: use the unified log format for the remaining packages (#9743)

---

statistics/bootstrap.go
statistics/feedback.go
statistics/handle.go
statistics/histogram.go
statistics/table.go
statistics/update.go
statistics/update_test.go

statistics: unify log format in package statistics 

---

config/config.go
config/config_test.go
tidb-server/main.go

Cherry pick from #9855.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10096)

config: Stop server startup if an unrecognized option is found in a config file (#9855)

---

ddl/ddl.go

The previous logs are all "start DDL job", keeping the log content uniform helps to analyze the logs.
Tests 
- No code

ddl: update a log

---

executor/executor_required_rows_test.go
executor/sort.go

executor: control Chunk size for TopN&Sort

---

ddl/ddl.go

ddl: update a log (#10095)

---

expression/builtin_time.go
expression/builtin_time_test.go

expression: handle maketime unsigned hour overflow(#10074)

---

CHANGELOG.md

CHANGELOG: add release notes for v2.1.8

---

server/http_handler.go
server/http_handler_test.go

server: change db-table/{table_partition_id} http api (#10026)

---

cmd/pluginpkg/pluginpkg.go

A  typo in pluginpkg.go
Tests 
- No code
Side effects
- command usage message

fix pluginpkg.go typo

---

kv/kv.go
kv/mock.go
store/tikv/kv.go
util/mock/store.go

Signed-off-by: c4pt0r <i@huangdx.net>
Currently, in TiDB, there are still some implementations that rely heavily on the storage engine for specific features, for example:
https://github.com/pingcap/tidb/blob/master/domain/domain.go#L585
`if ebd, ok := do.store.(tikv.EtcdBackend); ok { ... }`
Like the code above, the domain should not determine the storage type by typecasting.
In addition, for InfoSyncer (domain/info.go), Information should not rely on specific etcd storage, which should be part of the API abstraction, and the information should be provided by the engine itself.
And here is a example, from MySQL's code:
```
typedef struct {
const char *name;
SHOW_COMP_OPTION state;
const char *comment;
enum db_type db_type;
bool (*init)();
uint slot;
uint savepoint_offset;
int …
```

storage: add some new interfaces for Storage

---

circle.yml

The jenkins CI already run this check, it's redundant for circle CI to check again
Remove the check in circle.yml
Tests 
- No code

*: remove parser replace check in circle CI

---

server/conn.go
session/session.go

split PRs of #10158
prometheus's WithLabelValues will require heavy mutex/hash operation in pprof
make easy to review this PR just handle conn/session package.
pre with label for metrics
Tests 
- Unit test
Code changes
- pre with labels for frequence label
Side effects
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10232)

plan, executor: pre with labels for metrics in conn/session

---

executor/builder.go
executor/compiler.go
executor/seqtest/prepared_test.go
metrics/server.go
planner/core/common_plans.go
planner/core/point_get_plan_test.go
planner/core/prepare_test.go

split PRs of #10158
prometheus's WithLabelValues will require heavy mutex/hash operation in pprof
make easy to review this PR just handle executor/plan package.
pre with label for metrics
Tests 
- Unit test
Code changes
- pre with labels
Side effects
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10231)

plan, executor: pre with labels for metrics in plan/executor package

---

store/tikv/2pc.go
store/tikv/backoff.go
store/tikv/coprocessor.go
store/tikv/lock_resolver.go
store/tikv/rawkv.go
store/tikv/region_cache.go
store/tikv/snapshot.go
store/tikv/txn.go

split PRs of #10158
prometheus's WithLabelValues will require heavy mutex/hash operation in pprof
make easy to review this PR just handle store package.
pre with label for metrics
Tests 
- Unit test
Code changes
- pre with label
Side effects
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10229)

store: pre with labels for metrics in store package

---

go.mod
store/tikv/client.go

https://github.com/pingcap/tidb/pull/10216 miss the most needed interceptor in tikv/client package - - sorry
remove interceptor
Tests 
- Unit test
Code changes
- N/A
Side effects
- N/A
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10233)

tikv/client: remove unused grpc metric in tikv-client

---

executor/index_lookup_join.go
executor/index_lookup_join_test.go

executor: ignore overflow error when construct inner key (#10244)

---

domain/domain.go
domain/domain_test.go

doamin: fix GetSnapshotInfoSchema using current TS (#10309)

---

expression/builtin_json.go
expression/builtin_json_test.go
go.mod
go.sum

This PR aims to close #9957
Added more args check
Tests 
- Unit test
Code changes
Side effects

expression: fix a compatibility issue in JSON_CONTAINS

---

util/chunk/chunk.go
util/chunk/chunk_test.go
util/chunk/chunk_util.go
util/chunk/codec.go
util/chunk/column.go
util/chunk/column_test.go
util/chunk/mutrow.go

cherry pick #10348 to release 2.1

chunk: change offset type to int64 (#10348)

---

CHANGELOG.md

Release notes for v2.1.9
@zz-jason @shenli @jackysp PTAL

CHANGELOG: release notes for v2.1.9

---

structure/structure_test.go

Improve test coverage
Add test code
Tests 
- Unit test

structure: improve package unit test code coverage to 86%

---

README.md

Simply fix TiDB Slack link in README.md.

Fixed TiDB Slack link

---

store/tikv/gcworker/gc_worker.go

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
This PR adds a exported function `RunDistributedGCJob` to file gc_worker. It is similar to `RunGCJob`, which is exported to be used without TiDB.
A function `RunDistributedGCJob` is added.
Tests 
- None
Code changes
Side effects
- None
- None

store/tikv/gc_worker: Add RunDistributedGCJob function

---

cmd/explaintest/r/explain_easy.result
cmd/explaintest/t/explain_easy.test
expression/util.go
expression/util_test.go
planner/core/logical_plan_test.go

expression: let `PushDownNot` does not change the argument (#10363)

---

session/bootstrap.go

 server: only owner do bootstrap (#10029)

---

executor/sort_test.go
expression/column.go
expression/column_test.go
planner/core/rule_column_pruning.go

cherry-pick #10064
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10442)

planner: keep unfoldable exprs when pruning for ORDER BY items (#10064)

---

ddl/column_test.go
ddl/ddl_api.go
executor/admin_test.go

ddl: prohibit modification decimal precision to avoid inconsistency problem (#10433)

---

expression/integration_test.go
types/time.go

types: fix `time_format` is not compatible with MySQL (#9841)

---

executor/insert_test.go
types/convert_test.go
types/datum.go

fix invalid `YEAR` string is not compatible with Mysql 

---

infoschema/slow_log.go
infoschema/slow_log_test.go

infoschema: fix error in ParseSlowLog (#10526)

---

ddl/db_change_test.go
ddl/ddl_api.go
ddl/ddl_worker_test.go
ddl/schema.go
ddl/schema_test.go

This PR fixes 2 potential bugs in AlterSchema DDL job
The change is simple enough, please check the codes.
Tests 

ddl: fix a bug in AlterSchema job and add more tests

---

ddl/db_change_test.go
ddl/ddl_api.go
ddl/ddl_worker_test.go
ddl/schema.go
ddl/schema_test.go

Cherry-pick https://github.com/pingcap/tidb/pull/10529

ddl: fix a bug in AlterSchema job and add more tests (#10529)

---

ddl/column.go
ddl/db_test.go
ddl/ddl_api.go
ddl/index.go
ddl/table.go

ddl: validate table info before doing ddl job to avoid load infoschema error (#10464)

---

executor/analyze.go
executor/analyze_test.go

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: send on closed channel
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x19f2993]
goroutine 18097050 [running]:
github.com/pingcap/tidb/executor.(*AnalyzeExec).analyzeWorker.func1(0xc02031e000, 0x19ebe01, 0xc02c18e180)
/home/jenkins/workspace/build_tidb_release-3.0/go/src/github.com/pingcap/tidb/executor/analyze.go:179 +0x367
panic(0x1d35fc0, 0x31169e0)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/tidb/executor.analyzeIndexPushdown(0xc0215368c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/jenkins/workspace/build_tidb_release-3.0/go/src/github.com/pingcap/tidb/executor/analyze.go:234 +0x2e3
github.com/pingcap/tidb/executor.(*AnalyzeExec).analyzeWorker( …
```

executor: fix analyze worker panic

---

executor/analyze.go
executor/analyze_test.go

Cherry pick #10603 to release 3.0

executor: fix analyze worker panic (#10603)

---

planner/core/planbuilder.go

Cherry-pick #10623 for release-2.1

planner: ignore the virtual column when collect statistics (#10623)

---

expression/builtin_cast.go
expression/builtin_info_test.go
expression/constant_test.go
expression/distsql_builtin_test.go
expression/integration_test.go
expression/util.go
expression/util_test.go

Improve UT coverage of `expression` package to 80%.
Add more UTs.
Tests 
- Unit test

expression: improve UT coverage of `expression` package to 80%

---

ddl/ddl.go
ddl/ddl_worker.go
domain/domain.go
owner/manager.go
session/bootstrap.go

ddl, session: update logs (#10546)

---

store/mockstore/mocktikv/rpc.go

Fix mocktikv  `handleKvScan` bug. 
Tests 
Code changes
Side effects

mocktikv: fix mocktikv kv scan bug

---

executor/executor_test.go
go.mod
go.sum

parser: Support SQL_BIG_RESULT, SQL_SMALL_RESULT, SQL_BUFFER_RESULT
Update parser for https://github.com/pingcap/parser/pull/304. 
Tests 
- No code
Code changes
Side effects

parser: Support SQL_BIG_RESULT, SQL_SMALL_RESULT, SQL_BUFFER_RESULT

---

store/mockstore/mocktikv/rpc.go

cherry-pick https://github.com/pingcap/tidb/pull/10652

mocktikv: fix mocktikv kv scan bug (#10652)

---

executor/builder.go
executor/show_test.go
executor/simple.go
privilege/privileges/privileges_test.go

Cherry pick from https://github.com/pingcap/tidb/pull/10571

executor,privilege: fix "show grants" result for RBAC (#10571)

---

ddl/db_test.go
go.mod
go.sum

go.mod: update parser to fix case expression format bug (#10600)

---

ddl/db_integration_test.go
ddl/table.go

ddl: fix alter table charset bug that change blob column type to text(#10477)

---

store/tikv/client.go

cherry-pick #10706 to 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10709)

ticlient: set max send/recv msg size match tikv's config (#10706)

---

go.mod
go.sum
session/pessimistic_test.go
store/mockstore/mocktikv/mvcc_leveldb.go
util/deadlock/deadlock.go
util/deadlock/deadlock_test.go

Cherry pick #10669 
Tests 
- Unit test

pessimistic-txn: support deadlock detector in mocktikv (#10669)

---

executor/adapter.go
executor/errors.go
executor/executor.go
session/pessimistic_test.go
session/tidb.go
store/mockstore/mocktikv/cluster.go
store/mockstore/mocktikv/errors.go
store/mockstore/mocktikv/mvcc.go
store/mockstore/mocktikv/mvcc_leveldb.go
store/mockstore/mocktikv/rpc.go
store/tikv/2pc.go
store/tikv/backoff.go
store/tikv/error.go
store/tikv/tikvrpc/tikvrpc.go
store/tikv/txn.go
util/deadlock/deadlock.go
util/testkit/testkit.go

Cherry pick #10654 
Tests 
- Unit test

store/tikv: support single statement rollback for pessimistic txn (#10654)

---

infoschema/slow_log.go
infoschema/slow_log_test.go
infoschema/tables_test.go
sessionctx/variable/session.go

infoschema/slow_query: add host column in slow_query table. (#10693)

---

infoschema/slow_log.go

infoschema/slow_query: fix shallow copy problem (#10696)

---

expression/integration_test.go
go.mod
go.sum

Cherry pick [#10700](https://github.com/pingcap/tidb/pull/10700)
Tests 
- No code

parser: add MySQL extension assignment support for VariableAssignment (#10700)

---

executor/grant.go
executor/revoke.go
executor/simple.go
executor/simple_test.go

Cherry-pick from https://github.com/pingcap/tidb/pull/10707 to release-2.1

executor: execute some statement (`create user` `grant` etc) would commit current transaction automically

---

ddl/db_integration_test.go
ddl/table.go

ddl: fix alter table charset bug that change blob column type to text (#10477)

---

statistics/feedback.go
statistics/feedback_test.go
statistics/handle/update.go
statistics/handle/update_test.go

Cherry pick #10614 to release 3.0

stats: adjust datum type when using the index query feedback (#10614)

---

executor/builder.go
executor/executor.go
executor/executor_test.go
executor/split.go
executor/split_test.go
go.mod
go.sum
planner/core/common_plans.go
planner/core/planbuilder.go

*: split index region with lower upper syntax (#10409)

---

executor/builder.go
executor/executor_test.go
executor/split.go
executor/split_test.go
planner/core/planbuilder.go

 *: add split table syntax to split table region (#10553)

---

executor/builder.go
executor/executor_test.go

executor: fix split table bug (#10761)

---

executor/executor_test.go

speed up unit tests in executor package
change TestRecoverTable from TestSuite1 to testRecoverTable
Tests 
- Unit test

executor: speed up unit tests in executor package

---

ddl/syncer.go

ddl: make the SyncerSessionTTL smaller (#10371)

---

store/mockstore/mocktikv/mvcc.go
store/mockstore/mocktikv/mvcc_leveldb.go
store/tikv/2pc.go
store/tikv/lock_resolver.go

Cherry-pick https://github.com/pingcap/tidb/pull/10292

[release 3.0] store/tikv: support resolve specified lock keys (#10292)

---

session/txn.go
store/tikv/2pc_test.go
store/tikv/txn.go

Cherry-pick #10800 
Cherry-pick #10800 
Tests 
- Unit test

store/tikv: exclude keys that are already locked in `LockKeys`

---

table/tables/tables.go

Remove Chinese Character from tables.go 
No Code is changed in this PR. 
closes https://github.com/pingcap/tidb/issues/10818

table: remove Chinese character from tables.go

---

session/pessimistic_test.go
session/tidb.go

Cherry-pick #10823 
Tests 
- Unit test

session: do not add history for pessimistic transaction

---

store/tikv/backoff.go
store/tikv/backoff_test.go

cherry-pick #10809 to 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/10821)

tikv: fix backoff stop early (#10809)

---

server/http_handler_test.go
store/helper/helper_test.go
store/mockoracle/oracle.go
store/mockstore/mocktikv/errors.go
store/mockstore/mocktikv/mock_tikv_test.go
store/mockstore/mocktikv/mvcc.go
store/mockstore/mocktikv/mvcc_leveldb.go
store/mockstore/mocktikv/pd.go
store/mockstore/tikv_test.go
store/store_test.go
store/tikv/gcworker/gc_worker.go
store/tikv/gcworker/gc_worker_test.go
store/tikv/store_test.go

Improve the ut coverage for store package.
Tests 
- Unit test
Code changes

store: improve ut coverage for store

---

domain/domain.go
executor/adapter.go
executor/compiler.go
executor/executor_pkg_test.go
executor/explainfor_test.go
executor/prepared.go
executor/set_test.go
executor/show_test.go
infoschema/tables_test.go
planner/core/util.go
server/driver.go
server/driver_tidb.go
server/server.go
session/session.go
sessionctx/stmtctx/stmtctx.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go
tidb-server/main.go
util/execdetails/execdetails.go
util/expensivequery/expensivequery.go
util/memory/action.go
util/memory/tracker.go
util/processinfo.go

 *: print an expensive log when a query exceeds time threshold (#10350)

---

session/bootstrap_test.go
session/session.go

session: init expensiveQueryHandle immediately after domain be initiated (#10845)

---

ddl/db_integration_test.go

Cherry-pick #10855 
Tests 
- No code

ddl: skip race test for Tests that change global config

---

planner/core/cbo_test.go
planner/core/find_best_task.go
sessionctx/variable/session.go
sessionctx/variable/tidb_vars.go

cherry-pick https://github.com/pingcap/tidb/pull/10537

planner: use max correlation in heuristic row count estimation (#10537)

---

executor/distsql.go

executor: log inconsistent handles when inconsistent-check fail in `IndexLookupReader` (#10838)

---

ddl/db_partition_test.go
ddl/ddl.go
ddl/partition.go

Cherry-pick https://github.com/pingcap/tidb/pull/10902

ddl: fix 'alter table drop partition' check on hash partitioned table

---

CHANGELOG.md

add release notes for v2.1.13
@GregoryIan @zz-jason @jackysp @coocood PTAL

CHANGELOG: add release notes for v2.1.13

---

executor/analyze.go
executor/analyze_test.go

executor: fix wrong row count in fast analyze (#10859)

---

expression/builtin_time.go
expression/builtin_time_test.go
sessionctx/variable/tidb_vars.go

expression: fix the behavior of `DATE_SUB` (#10607)

---

ddl/db_test.go
ddl/ddl_api.go

type/compatibility: fix show create table output of generated column (#9608)

---

executor/analyze.go
executor/analyze_test.go
statistics/cmsketch.go
statistics/cmsketch_test.go
statistics/sample.go

Cherry pick #10839 
Conflicts: analyze.go

stats: fix the index cm sketch for fast analyze (#10839)

---

session/session.go
session/tidb.go

session: don't change the DDL lease when doing bootstrap (#10908)

---

cmd/explaintest/r/explain_easy.result
executor/aggfuncs/aggfunc_test.go
executor/aggfuncs/window_func_test.go
executor/aggregate_test.go
executor/benchmark_test.go
executor/builder.go
executor/executor_required_rows_test.go
expression/aggregation/agg_to_pb_test.go
expression/aggregation/aggregation_test.go
expression/aggregation/base_func.go
expression/aggregation/base_func_test.go
expression/aggregation/bench_test.go
expression/aggregation/descriptor.go
expression/aggregation/window_func.go
planner/core/expression_rewriter.go
planner/core/logical_plan_builder.go
planner/core/rule_aggregation_push_down.go
planner/core/rule_decorrelate.go
planner/core/rule_inject_extra_projection_test.go

cherry-pick #10910 
no conflicts

*: let baseFuncDesc.typeInfer return error instead of panic (#10910)

---

executor/adapter.go
kv/kv.go
kv/union_store.go
session/pessimistic_test.go
store/tikv/txn.go

Cherry-pick #10905 
No conflict

store/tikv: fix insert on dup update for pessimistic transaction

---

executor/analyze.go
executor/analyze_test.go
statistics/cmsketch.go
statistics/cmsketch_test.go

stats: correct fast analyze stats caclulation (#10766)

---

ddl/db_partition_test.go
ddl/db_test.go

cherry-pick #10387 #10827 
make DDL test more stable.

 ddl: make add index test stable by change ddl reorg batch size (#10387) (#10827)

---

session/pessimistic_test.go
store/mockstore/mocktikv/mvcc_leveldb.go

Cherry-pick #10919 
No conflict

mocktikv: fix key exists check for pessimistic transaction (#10919)

---

store/tikv/gcworker/gc_worker_test.go

Add unit test for #10927  
Tests 
- No code
Code changes
Side effects

gc_worker: add test for check save gc safe point

---

store/mockstore/mocktikv/pd.go
store/tikv/gcworker/gc_worker_test.go

cherry-pick #10964.
Tests 
- No code

gc_worker: add test for check save gc safe point (#10964)

---

CHANGELOG.md

add release notes for v3.0.0,v3.0.0-rc.3
@shenli @GregoryIan @zz-jason @jackysp

CHANGELOG: add release notes for v3.0.0,v3.0.0-rc.3

---

ddl/db_change_test.go
executor/executor_test.go
executor/seqtest/seq_executor_test.go
planner/core/prepare_test.go

Fix malformed SQL statements in test. This PR blocks [parser PR 367](https://github.com/pingcap/parser/pull/367).
Remove invalid characters at the end of the SQL statements.
Tests 
- Unit test

*: fix malformed SQL statements in test

---

executor/executor_test.go
store/tikv/coprocessor.go

*: fix oom action cancel bug (#10993)

---

ddl/ddl_worker.go
ddl/failtest/fail_db_test.go
ddl/table.go
infoschema/infoschema.go

cherry pick #10981.
No conflict.

ddl: add recover for run ddl job (#10981)

---

executor/point_get.go
session/pessimistic_test.go

Cherry-pick #11012
No conflict

executor: fix point get snapshot TS for pessimistic transaction. 

---

cmd/explaintest/r/explain_easy.result
cmd/explaintest/t/explain_easy.test
planner/core/logical_plan_test.go
planner/core/rule_column_pruning.go

Cherry-pick https://github.com/pingcap/tidb/pull/10974

planner: fix a corner case in column pruning rule (#10974)

---

infoschema/tables.go
infoschema/tables_test.go
session/session.go
util/expensivequery/expensivequery.go
util/processinfo.go

cherry-pick #10985 
conflict:
infoschema/tables_test.go
session/session.go
util/processinfo.go

*: fix 'db' and 'Info' column of 'show processlist' (#10985)

---

expression/builtin_other.go
expression/builtin_other_test.go

cherry-pick #11041 to release-2.1

expression: deep copy the string when setting user variable from Chunk (#11041)

---

config/config.go
config/config.toml.example
store/tikv/2pc.go

store/tikv: Make maxTxnTimeUse a configurable value 

---

ddl/db_integration_test.go
ddl/ddl_api.go

Cherry-pick https://github.com/pingcap/tidb/pull/10958

ddl: allow more charset/collation modifications for database/table (#10958)

---

planner/core/logical_plan_builder.go
planner/core/logical_plan_test.go

Cherry pick #11095
No conflicts

planner/core: stabilize the execution order of window functions (#11095)

---

domain/schema_checker.go

As there are retries here, the previous metric doesn't reflect that the
error really happens, this commit makes the metric more accurate.
Move the metric code to the right place
Tests 
- No code

domain: update the schema check outdate metric

---

metrics/ddl.go
metrics/distsql.go
metrics/domain.go
metrics/gc_worker.go
metrics/meta.go
metrics/metrics.go
metrics/oracles.go
metrics/owner.go
metrics/server.go
metrics/session.go
metrics/stats.go
metrics/tikvclient.go

Conflicts:
metrics/tikvclient.go
Cherry-pick #10279 to release 2.1.

metrics: add comments for metrics ranges (#10279)

---

planner/core/planbuilder.go

Tiny cleanup...
This code is really ugly:
```
switch xxx {
case aaa:
case bbb:
...
default:
switch {
case zzz:
....
}
}
```
Remove one unnecessary `switch ... case`
Tests 
- No code

planner/core: tiny cleanup the buildShow function

---

expression/builtin_math.go
expression/integration_test.go

Cherry pick #11168 
No conflicts.

expression: fix data race of rand function (#11168)

---

go.mod
go.sum

update vendor to build on ARM64 (#10805)

---

go.mod
go.sum
store/mockstore/mocktikv/pd.go
store/tikv/store_test.go

Update the tso wait duration metric
Update pd client in go.mod to include https://github.com/pingcap/pd/pull/1626
Tests 
- No code

go.mod: update tidb to use the latest release-3.0 pd client

---

executor/point_get.go
executor/point_get_test.go

Cherry pick #11219 
No conflicts.

executor: fix bug of point get when meet null values (#11219)

---

executor/builder.go
executor/executor_test.go
executor/show.go
executor/split.go
go.mod
go.sum
kv/kv.go
planner/core/common_plans.go
planner/core/planbuilder.go
store/tikv/region_cache.go
store/tikv/region_cache_test.go
store/tikv/split_region.go

cherry-pick #10612 
related parser: https://github.com/pingcap/parser/pull/384
Please merge parser first.

 *: add show table regions syntax (#10612)

---

util/chunk/chunk.go

chunk: use native go style to do initialization

---

executor/executor_test.go
executor/insert_common.go
executor/load_data.go
executor/write_test.go
infoschema/tables.go
server/conn.go
table/table.go
table/tables/tables.go
table/tables/tables_test.go

Cherry-pick https://github.com/pingcap/tidb/pull/11158

*: add trace support for the `AllocAutoIncrementValue` function (#11158)

---

ddl/split_region.go

Conflicts:
ddl/split_region.go
Cherry-pick #11183 to release 3.0.

ddl: do not split index when creating table (#11183)

---

ddl/db_integration_test.go
ddl/index.go

ddl: fix the issue that the length of the index is 0. (#11045)

---

executor/analyze.go
server/http_handler.go
store/helper/helper.go
store/mockstore/mocktikv/rpc.go
store/tikv/2pc.go
store/tikv/2pc_test.go
store/tikv/client.go
store/tikv/coprocessor.go
store/tikv/delete_range.go
store/tikv/gcworker/gc_worker.go
store/tikv/gcworker/gc_worker_test.go
store/tikv/lock_resolver.go
store/tikv/lock_test.go
store/tikv/rawkv.go
store/tikv/region_request.go
store/tikv/region_request_test.go
store/tikv/scan.go
store/tikv/snapshot.go
store/tikv/split_region.go
store/tikv/store_test.go
store/tikv/tikvrpc/tikvrpc.go

ref #9641, try to reduce tikvrpc response struct size
pair with https://github.com/pingcap/tidb/pull/11055
same to https://github.com/pingcap/tidb/pull/11055
Tests 
- Unit test
Code changes
- N/A
Side effects
- N/A
- Need to cherry-pick to the release 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/11056)

*: reduce tikvrpc resp struct size

---

expression/builtin_time.go
expression/integration_test.go

expression: fix getIntervalFromDecimal in DATE_ADD() (#11297)

---

CHANGELOG.md

Add release notes for v2.1.15
@GregoryIan @bb7133 @zz-jason @jackysp PTAL

CHANGELOG: add release notes for v2.1.15

---

executor/executor_test.go
planner/core/logical_plan_builder.go

cherry-pick #11324 to release-2.1

planner: correct the generation of the field name (#11324)

---

util/chunk/chunk.go
util/chunk/column.go
util/chunk/column_test.go

Add  `CopyConstruct()` and `CopyReconstruct()` to `Column`, which is prepared for vectorized evaluation.
1. Expose `CopyConstruct()` method;
2. Add a new method `CopyReconstruct()` method;
**Most of these changes are for unit tests, so it's easy to review.**
Tests 
- Unit test

executor: add `CopyReconstruct()` and `CopyConstruct()` methods to `Column`

---

executor/adapter.go
infoschema/slow_log.go
infoschema/slow_log_test.go
infoschema/tables_test.go
sessionctx/variable/session.go
sessionctx/variable/session_test.go

 *: add succ filed to slow log and fix shallow copy problem when parse slow log file. (#11417)

---

server/http_handler.go

Cherry-pick #9104 to 2.1, no conflict

server: adjust the result of curl * (#9104)

---

ddl/column.go
ddl/db_change_test.go

cherry-pick #11341 to release-2.1

ddl: fix the parallel problem of "set default value" and other DDL (#11341)

---

expression/integration_test.go
types/convert.go
types/convert_test.go
types/datum_test.go

cherry-pick #11355 to release-2.1

types: fix uint64 overflow bug in `ConvertJSONToFloat` (#11355)

---

expression/constant_fold.go
expression/integration_test.go

cherry-pick ##11105 to release-2.1

expression, session: handle `CASE WHEN` specially when folding constant during outerJoin Simplification(#11105)

---

server/http_handler_test.go

This PR https://github.com/pingcap/tidb/pull/11463 added a table name pt in `test` database which was shared and concurrent running with other cases. Some expect will be changed.
Fix the expect string to a number.
Tests 
- Unit test

server: fix unit test in http_handler_test.go

---

expression/builtin_time_test.go

manual cherry-pick #11412 from master/release-3.0 branch
make current_timestamp tests stable
Tests 
- Unit test
Code changes
Side effects

expression: make current_timestamp tests stable

---

executor/load_data.go

Reduce a memory allocation
By comparing byte slice directly
Tests 
- Unit test
- No code
Side effects
- No
- No

load data: avoid an unnecessary converting from byte slice to string

---

store/helper/helper_test.go

Fix the CI of parser repo.
See:https://circleci.com/gh/pingcap/parser/2612?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
the cause of the failed CI is the entries of maps is out-of-order
Tests 
- Unit test

Test: Improve asserts oftest cases in `helper_test.go` and fix ci

---

executor/seqtest/seq_executor_test.go
executor/write_test.go

Cherry-pick #11525 to release 3.0.

executor: move failpoint test case to seq test suite (#11525)

---

ddl/db_integration_test.go
ddl/index.go
planner/core/logical_plan_builder.go
util/admin/admin.go
util/rowDecoder/decoder.go

ddl: fix invalid index on multi-layer virtual columns (#11260)

---

infoschema/builder.go
infoschema/tables_test.go
server/http_handler.go

infoschema: fix load drop database schema bug and refine db-table api error. (#11573)

---

executor/load_data.go

Tow field type in `fieldWriter` is wrong and break the code style.
Chang field type in `fieldWriter`.
Tests 
- No code
Code changes
- None
Side effects
- None

executor: fix field type error in `LOAD DATA`

---

CHANGELOG.md

CHANGELOG: add release notes for v2.1.16

---

server/http_handler_test.go

Improve unit test coverage of `server` module.
Add test case for `/debug/zip` api in `server` module
Tests 
- Unit test
Code changes
- None
Side effects
- None
- None
This PR will continue unfinished jobs in #11025

server: improving test coverage for `/debug/zip` api

---

CHANGELOG.md

CHANGELOG: add release notes for v3.0.2

---

store/tikv/gcworker/gc_worker.go
store/tikv/kv.go
store/tikv/safepoint.go
store/tikv/safepoint_test.go

Fixed a typo in loadSafePoint
changed a single variable name.
Side effects
NO

fix an obvious typo in loadSafePoint

---

planner/core/planbuilder.go

This PR refactor the function `tableNames2HintTableInfo` to improve performance.
Use the index to assign value instead of append value to slice.
Tests 
- Unit test
Benchmark
```go
type hintTbl struct {
n string
a bool
}
const num = 100
func test1() {
x := hintTbl{n: "a", a: true}
a := make([]hintTbl, 0, num)
for i := 0; i < num; i++ {
a = append(a, x)
}
}
func test2() {
x := hintTbl{n: "a", a: true}
a := make([]hintTbl, num)
for i := 0; i < num; i++ {
a[i] = x
}
}
func BenchmarkT1(b *testing.B) {
for i := 0; i < b.N; i++ {
test2()
}
}
func BenchmarkT2(b *testing.B) {
for i := 0; i < b.N; i++ {
test2()
}
}
```
Result
```
BenchmarkT1-8   	10000000	       185 ns/op
BenchmarkT2-8   	50000000	        34.7 ns/op
```

planner: tiny optimization for `tableNames2HintTableInfo`

---

ddl/db_test.go

```go
----------------------------------------------------------------------
FAIL: db_test.go:4335: testDBSuite.TestDropSchemaWithPartitionTable
db_test.go:4378:
c.Assert(recordsNum, Equals, 0)
... obtained int = 2
... expected int = 0
```
cherry pick some part from #8612  https://github.com/pingcap/tidb/pull/8612/files#diff-e259172e2953a3597b096f11d3c8d3daR1223
Tests 
- No code

ddl: make ddl test more stable

---

executor/show_test.go
executor/simple.go
planner/core/planbuilder.go

cherry-pick #11201 
conflict has been fixed.

executor, privileges: fix privileges check fail for `SET DEFAULT ROLE`(#11201)

---

executor/executor.go

Cherry-pick #11802 to release 2.1.

executor: fix error check in EvalSubquery #11802

---

util/hack/hack.go

Improve Slice function
See the same PR in this link https://github.com/valyala/fasthttp/pull/637
Tests 
- Unit test
- No code
Code changes
- Has persistent data change
Side effects
No

util: Faster-Slice-Function

---

.github/pull_request_template.md

Update pull request template to add release note
Tests 
- No code

.github: update pull request template to add release note

---

session/tidb.go

Cherry pick (#11851) to release 2.1.

server: fix start ts in slow log when transaction retrying (#11851)

---

sessionctx/variable/tidb_vars.go

cherry pick https://github.com/pingcap/tidb/pull/11786

sessionctx/variable: change add index variable default value (#11786)

---

planner/core/task.go

Remove unnecessary conversion and parenthesis
N/A

planner: remove unnecessary conversion and parenthesis

---

executor/executor_test.go
executor/split.go
planner/core/planbuilder.go

executor: split a separate region for index when split table region (#11721)

---

go.mod
go.sum

update btree version in master and 3.0
using @nolouch 's pr https://github.com/google/btree/pull/25
update go.mod
Tests 
- No code
Code changes
- go.mod
Side effects
- N/A
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/11988)

gomod: update region cache btree version

---

CHANGELOG.md

*: add release notes for v3.0.3

---

store/tikv/2pc.go

fix adding rate limiter for txn resolving conflicts missing one line "putback token"
thx lysu for reminding
Tests 
- Unit test
Code changes
Side effects
Release note

store: fix missing line resolving conflicts

---

expression/bench_test.go

1. Introduce `defaultGener`.
2. Check warnings generated by expressions.
Tests 
- Unit test

expression: tiny refactor around the vectorized testing framework

---

ddl/db_integration_test.go
ddl/db_partition_test.go
ddl/db_test.go
ddl/serial_test.go
planner/core/integration_test.go
types/errors.go
util/testkit/testkit.go

Add test for PR #11942.
Blocked by pingcap/parser#530.
- Add `MustGetErrCode` for testkit.
- Replace all `assertErrCode` with `MustGetErrCode`
- Add `TestBitColErrorMessage` test.
Tests 
- Unit test
Code changes
Side effects

planner/core: add bit column test about display width range

---

planner/core/logical_plan_test.go
planner/core/optimizer.go
planner/core/physical_plan_test.go
planner/core/rule_eliminate_projection.go

*: fix typo of `eliminator`

---

domain/topn_slow_query.go
executor/adapter.go
executor/builder.go
executor/executor.go
infoschema/slow_log.go
sessionctx/stmtctx/stmtctx.go
sessionctx/variable/session.go
sessionctx/variable/session_test.go

*: record index name in the slow log instead of index id (#11795)

---

go.mod
go.sum

Update parser to add where for show table region syntax.
Related parser PR: pingcap/parser#553

parser: update parser for add where for show table region syntax (#12015)

---

README.md

Advertise https://asktug.com
Tests 
- Unit test
- No code
Code changes
- Has persistent data change
Side effects
Release note
- Write release note for bug-fix or new feature.

Advertise https://asktug.com

---

statistics/feedback.go
statistics/feedback_test.go
statistics/handle/update.go
statistics/handle/update_test.go
statistics/histogram.go
statistics/histogram_test.go

stats: do not split excluded lower value ranges (#12009)

---

expression/bench_test.go
expression/builtin_cast_vec_test.go
expression/builtin_compare_vec_test.go
expression/builtin_control_vec_generated_test.go
expression/builtin_math_vec_test.go
expression/builtin_miscellaneous_vec_test.go
expression/builtin_string_vec_test.go
expression/builtin_time_vec_test.go
expression/generator/control_vec.go
go.mod
tools/check/go.mod
types/datum.go
types/datum_test.go

support customizing FieldTypes of arguments for benchmark framework.
previous PR of #12224
Tests 
- Unit test
Code changes
Side effects
- None
Release note
- None

expression: support customizing FieldTypes of arguments for benchmark framework

---

planner/core/point_get_plan.go
privilege/privileges/privileges_test.go

cherry-pick #12268 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/12341)

planner/core: fix point-get db privilege check (#12268)

---

executor/batch_checker.go
executor/insert.go
executor/insert_common.go

Cherry-pick https://github.com/pingcap/tidb/pull/12122

executor: do not use batchChecker in 'insert ignore into ...' (#12122)

---

server/conn.go

The #12454 inadvertently deleted a line: 
See: https://github.com/pingcap/tidb/pull/12454/files#diff-dc417f5322100e2e83a8818c70a25878L178
Revert this change.
Tests 
- Unit test
Release note
- No need to add to release note.

server: fix wrong deletion introduced by #12454

---

domain/schema_validator.go
domain/schema_validator_test.go
executor/seqtest/seq_executor_test.go
metrics/domain.go
metrics/metrics.go
session/session.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go

*: adjust delta schema count and add metrics (#11625)

---

CHANGELOG.md

CHANGELOG: add release notes for v3.0.4

CHANGELOG: add release notes for v3.0.4

---

planner/core/physical_plan_test.go
planner/core/testdata/plan_suite_in.json
planner/core/testdata/plan_suite_out.json
util/testutil/testutil.go

Make it eaiser to cherry pick planner cases into 2.1.
Cherry pick PRs related to test data.
Tests 
- No code
Code changes
- None
Side effects
- None
- None
Release note
- None

util, planner: split test data from test cases

---

cmd/explaintest/r/explain_complex.result
cmd/explaintest/r/explain_complex_stats.result
cmd/explaintest/r/explain_easy.result
cmd/explaintest/r/explain_easy_stats.result
cmd/explaintest/r/generated_columns.result
cmd/explaintest/r/index_join.result
cmd/explaintest/r/topn_push_down.result
cmd/explaintest/r/tpch.result
planner/core/exhaust_physical_plans.go

As the title says.
Add the `extraHandleCol` to cop task.
Tests 
- Unit test
Code changes
Side effects

planner: fix bug the inner child can't keep order in index join

---

Makefile

There is lengthy filesystem path with the binary built by  `go build` ,which made traceback seems messy,like:
```
[session:8002][16524] can not retry select for update statement
github.com/pingcap/errors.AddStack
/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20181122084134-815d2f65fd25/terror/terror.go:231
github.com/pingcap/tidb/session.(*session).retry
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:463
```
In golang 1.13 see `go help build`:
```
-trimpath
remove all file system paths from the resulting executable.
Instead of absolute file …
```

Makefile: add `-trim-path` flag to build command

---

executor/set.go
server/conn.go

cherry-pick #12310
with conflict at https://github.com/pingcap/tidb/blob/release-3.1/executor/set.go#L190

log: move autocommit varable value into connection info (#12310)

---

expression/builtin_miscellaneous_vec.go
expression/builtin_miscellaneous_vec_test.go

Implement vectorized evaluation for builtinRealAnyValueSig, for #12105
```
BenchmarkVectorizedBuiltinMiscellaneousCasesFunc/builtinRealAnyValueSig-VecBuiltinFunc-8         	10000000	       119 ns/op	       0 B/op	       0 allocs/op
BenchmarkVectorizedBuiltinMiscellaneousCasesFunc/builtinRealAnyValueSig-NonVecBuiltinFunc-8      	  100000	     20881 ns/op	       0 B/op	       0 allocs/op
```
Tests 
- Unit test

expression: implement vectorized evaluation for 'builtinRealAnyValueSig'

---

bindinfo/bind_test.go
planner/optimize.go
session/session.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go
util/testkit/testkit.go

Add a system variable to control the usage of baselines, so we can disable them if needed.
Add a system variable.
Tests 
Code changes
Side effects
- None
- None
Release note
- None

*: add a system variable to control the usage of baselines

---

executor/adapter.go
infoschema/slow_log.go
infoschema/slow_log_test.go
infoschema/tables_test.go
session/tidb.go
sessionctx/variable/session.go

Cherry-pick #11908 to release 2.1

*: record previous statement when commit is slow (#11908)

---

executor/index_lookup_join_test.go
planner/core/exhaust_physical_plans.go

cherry-pick https://github.com/pingcap/tidb/pull/12581
Conflicts:
planner/core/exhaust_physical_plans.go

planner: handle single partition in IndexJoin correctly (#12581)

---

cmd/explaintest/r/tpch.result
planner/core/integration_test.go
planner/core/logical_plan_builder.go
planner/core/testdata/plan_suite_out.json
planner/core/util.go

cherry-pick https://github.com/pingcap/tidb/pull/12419
Conflict Files:
cmd/explaintest/r/tpch.result
planner/core/testdata/plan_suite_out.json

planner: reset NotNull flag for schema of Apply and MaxOneRow properly (#12419)

---

ddl/column.go
ddl/db_partition_test.go
ddl/partition.go

Cherry-pick https://github.com/pingcap/tidb/pull/12622
PTAL @crazycs520 @jackysp @winkyao

ddl: fix create table check for range columns partition #12622

---

store/tikv/client_batch.go

store/tikv: fix data race on idle (#12164)

---

Makefile

Just for ci test
Tests 
- Unit test
- No code
Code changes
- Has persistent data change
Side effects
Release note
- Write release note for bug-fix or new feature.

Makefile: change test parallel to 8

---

planner/core/logical_plan_builder.go
planner/core/logical_plan_test.go

cherry-pick #12347
conflict file: logical_plan_test.go

planner/core: do not change window ast when building plan (#12347)

---

go.sum
store/tikv/2pc.go

Cherry-pick https://github.com/pingcap/tidb/pull/12845

store/tikv: tiny refactoring, change `twoPhaseCommitAction` to interface (#12845)

---

Makefile
go.mod
go.sum

Fix current CI
Update parser
Tests 
- No code

go.mod: update parser version in go.mod

---

CHANGELOG.md

*: add release notes for v3.0.5

---

store/tikv/client_batch.go

fix #12819's cherry-pick to 3.0
remove code need be removed
Tests 
- Unit test
Code changes
-  remove useless wait
Side effects
- N/A
- N/A
Release note
- N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/13101)

tikv: fix init batch client cherry-pick 3.0(#12819)

---

expression/builtin_info_vec.go
expression/builtin_info_vec_test.go

PCP #12106
#12106
vectorize `builtinTiDBVersionSig`
Tests 
- Unit test
Code changes
Side effects
Release note
vectorize `builtinTiDBVersionSig`

 expression: implement vectorized evaluation for `builtinTiDBVersionSig`

---

infoschema/slow_log.go
infoschema/slow_log_test.go
infoschema/tables_test.go
util/execdetails/execdetails.go

cherry-pick https://github.com/pingcap/tidb/pull/13007

infoschema/slow_query: add more field in slow_query table (#13007)

---

expression/builtin_json.go
expression/builtin_json_test.go
expression/distsql_builtin.go
expression/integration_test.go
go.mod
go.sum

cherry-pick #12596 to release-3.1
Add ```json_valid``` builtin function described [#7546](https://github.com/pingcap/tidb/issues/7546).
See [here](https://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html#function_json-valid) for details.

expression: add builtin function json_valid

---

bindinfo/bind_test.go
bindinfo/handle.go
expression/builtin_string.go

Cherry pick #13115 
Conflicts: bindinfo/handle.go, bindinfo/bind_test.go

bindinfo: correctly handle quotes for bindings sql (#13115)

---

executor/admin_test.go
executor/builder.go
executor/executor.go
executor/statement_context_test.go
planner/core/common_plans.go
planner/core/exhaust_physical_plans.go
planner/core/find_best_task.go
planner/core/planbuilder.go
util/admin/admin.go

cherry pick cherry-pick https://github.com/pingcap/tidb/pull/12796
```
both modified:   admin_test.go
both modified:   ../planner/core/exhaust_physical_plans.go
both modified:   ../planner/core/find_best_task.go
both modified:   ../planner/core/planbuilder.go
```

util/admin: support admin check table on partition table (#12796)

---

tools/check/check-gogenerate.sh

GNU version xargs will return error in this case.
`set +e` temporarily.
Tests 
- No code

build: fix check-gogenerate.sh

---

server/conn.go
server/conn_test.go

cherry-pick #13051 
---
Fix #13050
Tests 
- Unit test (covered by TestShutDown)
Code changes
- None
Side effects
- None
- None
Release note
- None

server: fix potential goroutine leak when kill connection (#13051)

---

expression/bench_test.go

Fix the vectorization test framework to produce negative decimal types to improve test coverage.
Increased the possibility of decimal types generating negative numbers.
Tests 
- Unit test

expression: fix the vectorization test framework to produce negative decimal types

---

executor/executor.go
executor/hash_table.go
executor/index_lookup_join.go
executor/index_lookup_merge_join.go
executor/join.go
executor/pkg_test.go
executor/sort.go
util/chunk/disk.go
util/chunk/iterator.go
util/chunk/iterator_test.go
util/chunk/list.go
util/chunk/list_test.go

Revert "executor, util: rename original List to ListInMemory and add a new interface List"

---

executor/executor_test.go
executor/update_test.go
planner/core/logical_plan_builder.go

planner: refactor the code of buildUpdate to solve some bugs (#13208)

---

executor/adapter.go
store/tikv/lock_resolver.go

*: refine transaction related log

---

statistics/handle/update.go
statistics/histogram.go
statistics/histogram_test.go
statistics/selectivity_test.go
statistics/table.go

stats: specially handle unqiue key when estimate (#13354)

---

session/bootstrap.go

session: fix upgrade logic when bootstrap (#12827)

---

ddl/util/syncer_test.go
domain/domain_test.go

stabilize some tests for CI, Fix #12685, Fix #12942
Enlarge timeout
- Tests 
N/A

*: stabilize some tests for CI

---

ddl/util/syncer_test.go

cherry-pick #13413 without conflict.
stabilize some tests for CI, Fix #12942
Enlarge timeout
- Tests 
N/A

*: stabilize some tests for CI (#13381)

---

go.mod
go.sum
planner/core/integration_test.go
planner/core/preprocess.go
types/errors.go

planner/core: add a range check against display width of BIT column type (#11942)

---

executor/executor_test.go
table/tables/partition.go

table, executor: fix the data race of the partition table's hashcode #13421

---

expression/bench_test.go
expression/builtin_cast_vec.go
expression/builtin_cast_vec_test.go

This PR reverts https://github.com/pingcap/tidb/pull/13445 for now in order to pass copr-test.

expression: Revert vectorized builtinCastStringAsRealSig (#13445)

---

cmd/ddltest/random.go
server/server_test.go
types/time.go
util/stringutil/string_util.go

Remove unused code.
Remove the code who is unused.
Tests 
- Unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/13547)

*: remove unused code 

---

go.mod
go.sum
planner/core/integration_test.go

fix cherry-pick #13512

---

go.mod
go.sum
planner/core/integration_test.go

fix cherry-pick #13511

---

expression/constant_fold.go
expression/expression.go

Directly change the arg of expression is dangerous and may cause data race.
Fix the CI problem.
Don't modify it directly.
Tests 
- Passing existing tests.

expression: foldConstant don't modify the arg of function directly

---

docs/design/2019-11-05-index-advisor.md
docs/design/README.md

add design doc for a new DBA tool -- index advisor
a detailed proposal for index advisor

docs/design: add proposal for index advisor

---

ddl/db_test.go
ddl/index.go

Cherry-pick #13616 to v3.0
Conflicts:
- db_test.go

ddl: fix the result of executing "desc table" after altering "primary key" (#13616 )

---

util/signal/signal_windows.go

Building on Windows failed.
Add the imports which needed.
Tests 
`make` on Windows, it will success.

*: fix build on Windows

---

config/config.go
config/config.toml.example
config/config_test.go
kv/kv.go
kv/memdb_buffer.go
store/tikv/2pc.go
tidb-server/main.go

Conflicts:
config/config.go
config/config.toml.example
config/config_test.go
kv/kv.go
store/tikv/2pc.go
Cherry-pick #9035 to release 3.0.

config, kv: make TxnEntryCountLimit and TxnTotalSizeLimit configurable (#9035) (#9952)

---

distsql/distsql.go
distsql/select_result.go
distsql/stream.go
executor/analyze_test.go
store/mockstore/mocktikv/cop_handler_dag.go
store/mockstore/mocktikv/rpc.go
store/tikv/client.go
store/tikv/coprocessor.go
store/tikv/sql_fail_test.go
store/tikv/tikvrpc/tikvrpc.go
util/sqlexec/restricted_sql_executor.go

Cherry pick from https://github.com/pingcap/tidb/pull/11311
Conflict: 
- store/tikv/coprocessor.go
Close #11317 
Tests 
- Unit test
Code changes
- None
Side effects

distsql: make CopStream available (#11311)

---

executor/compiler.go
executor/executor.go
executor/prepared.go
executor/seqtest/seq_executor_test.go

Conflicts:
executor/compiler.go
Cherry-pick #13633 to release 3.0.

executor: do not set priority when tidb_force_priority is set (#13633)

---

config/config.go
config/config.toml.example
executor/delete.go
executor/errors.go
executor/insert_common.go
executor/seqtest/seq_executor_test.go
executor/update.go
executor/write.go
executor/write_test.go
session/session.go
sessionctx/variable/session.go

Conflicts:
executor/delete.go
executor/errors.go
executor/insert_common.go
executor/simple.go
executor/update.go
executor/write_test.go
session/session.go
Cherry-pick #9882 to release 3.0. Be careful, many conflicts...

executor: support batch commit the DMLs (#9882)

---

statistics/bootstrap.go
statistics/dump_test.go
statistics/feedback.go
statistics/handle.go
statistics/table.go
statistics/update.go

Cherry pick #13647 
Conflicts: all files.

stats: fix data race when updating stats cache (#13647)

---

session/session.go
store/tikv/snapshot.go

cherry-pick #13525 
with conflict at store/tikv/snapshot.go
conflict was fixed

session: add more information for retry error (#13525)

---

CONTRIBUTORS.md

Updated the url of CONTRIBUTORS 
Changed outdated url
Tests 
- No code
Code changes
Side effects
Release note

doc: fixed invalid url in CONTRIBUTORS.md

---

go.mod
go.sum

Signed-off-by: 5kbpers <tangminghua@pingcap.com>
tidb3.1 depends on tipb3.0 currently.
switch tipb dependency to release-3.1.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
Release note
N/A

*: switch tipb dependency to release-3.1

---

ddl/callback_test.go
ddl/db_integration_test.go
ddl/db_test.go
ddl/ddl.go
ddl/ddl_api.go

Fix a part of `ddl` package warning in static check.
See: #13736, #13456.
- remove duplicate imports.
- remove unused test result.
Tests 
- Unit test
Code changes
N/A
Side effects
N/A
N/A
Release note
N/A

ddl: remove duplicate import and unused test result

---

util/stmtsummary/statement_summary.go
util/stmtsummary/statement_summary_test.go

remove unnecessary guard around and simplify string comparison.
#13736
Tests 
None
Code changes
None
Side effects
None
None
Release note
None

util: refactor the code

---

store/tikv/region_cache_test.go
store/tikv/region_request.go

cherry-pick #13472 to 3.1
resolve conflict due 3.1 hasn't tiflash read logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/13746)

tikv: make follower-read request retry other peers when meet EpochNotMatchError (#13472)

---

statistics/feedback.go
statistics/histogram.go

#13456 
Tests 
- No code
Code changes
Side effects
Release note

*: fix staticcheck errors in folder statistics

---

table/tables/tables.go

#13736 
Tests 
None
Code changes
None
Side effects
None
None
Release note
None

table: refactor the code to check the err

---

go.mod
go.sum
store/tikv/2pc.go
store/tikv/2pc_test.go
store/tikv/txn.go

merge parallel commit to 4.0-perf

merge parallel commit

---

executor/analyze_test.go
executor/chunk_size_control_test.go

Fix leak test in executor because of the unclosed domain.
Close every domain that has been created.
Tests 
- No code
Code changes
- None
Side effects
- None
- None
Release note
- None

executor: fix leak test

---

planner/cascades/implementation_rules.go
planner/cascades/testdata/integration_suite_in.json
planner/cascades/testdata/integration_suite_out.json
planner/implementation/simple_plans.go

part of https://github.com/pingcap/tidb/issues/13709.
Add ImplementationRule for UnionAll.
Tests 
- Unit test

planner/cascades: add ImplementationRule for UnionAll

---

ddl/column_test.go
ddl/db_change_test.go
ddl/db_integration_test.go
ddl/ddl_api.go
executor/admin_test.go
store/tikv/2pc.go
store/tikv/2pc_test.go

Merge release-3.0 into release-3.1

Merge release-3.0 into release-3.1

---

go.mod
go.sum

```
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-alpha-1064-g64333abae" -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=2019-12-04 02:42:06" -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=64333abaee420788d3e0a21506326ae09b083e86" -X "github.com/pingcap/tidb/util/printer.TiDBGitBranch=master" ' -o bin/tidb-server tidb-server/main.go
go: github.com/pingcap/tipb@v0.0.0-20191129094129-04ea15eb054e: invalid version: unknown revision 04ea15eb054e
make: *** [Makefile:195: server] Error 1
```
After https://github.com/pingcap/tidb/pull/13823, the tipb is not updated to latest master though the tipb pr has already merged and branch is deleted, so go mod cannot find the revision.
Tests 
- No code
Code changes
- …

build: fix build fail

---

ddl/db_integration_test.go
domain/schema_validator_test.go
store/tikv/oracle/oracles/pd.go
util/expensivequery/expensivequery.go

Fix https://github.com/pingcap/tidb/issues/13897
Close tickers and prefer use defer to close tickers.
Tests 
- Unit test

*: close tickers properly

---

go.mod
go.sum
kv/kv.go
session/session.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go
store/tikv/2pc.go
store/tikv/txn.go

Add `tidb_enable_parallel_commit` global variable. Default is false.

[4.0-perf] *: add tidb_enable_parallel_commit global variable 

---

executor/simple.go

cherry-pick #13820 with conflict resolved.

privilege: using system session to execute internal sql of RBAC (#13820)

---

executor/builder.go
executor/executor_test.go
executor/split.go
executor/split_test.go
go.mod
go.sum
planner/core/common_plans.go
planner/core/planbuilder.go

cherry-pick https://github.com/pingcap/tidb/pull/12213
Parser PR: https://github.com/pingcap/parser/pull/663.
conflict file:
```go
go.sum
go.mod
```

*: support split partition table region (#12213)

---

expression/builtin_compare.go

Redirect to the correct location of the  mysql document
Fix document URL in the comment
Tests 
- No code
Code changes
-No change
Side effects
- No
- No
Release note
- fix typo in the URL of mysql documentation

fix document url

---

expression/builtin_math.go
expression/distsql_builtin.go
go.mod
go.sum

Signed-off-by: andylokandy <andylokandy@hotmail.com>
Rename `RandWithSeed` to `RandWithSeedFirstGen`. This reflexes the change in tipb (https://github.com/pingcap/tipb/pull/162)
Tests 
- Unit test
Code changes

expression: rename RandWithSeed to RandWithSeedFirstGen

---

planner/core/common_plans.go

`IsAutoCommitNotValidTxn` is a bit complex.
Use `InTxn()` instead of `Valid()` to check the transaction is auto-commit or not.
Tests 
- Unit test
Code changes

planner: simplify IsAutoCommitNotValidTxn

---

bindinfo/cache.go
bindinfo/handle.go
executor/load_data.go
util/chunk/column.go

#[14025](https://github.com/pingcap/tidb/issues/14025)
fix some problems according to issues except "warning: should not use basic type string as key in context.WithValue (golint)"
Tests 
- Manual test 
: According to golint test there is no error message

*: make golint happy #14025

---

expression/expr_to_pb.go

Remove useless true statement.
Tests 
None
Code changes
None
Side effects
None
None
Release note
None

expression: remove useless true statement

---

meta/meta.go
session/bootstrap.go
session/session.go

*: fix typo boostrap

---

metrics/metrics.go

Missing register new metric
Tests 
- Unit test
Code changes
Side effects
Release note

server: add missing register

---

ddl/db_change_test.go
executor/adapter.go
expression/explain.go
expression/expression.go
expression/util_test.go
planner/core/encode.go
planner/core/explain.go
planner/core/plan.go
planner/core/plan_test.go
planner/core/point_get_plan.go
planner/core/testdata/plan_normalized_suite_in.json
planner/core/testdata/plan_normalized_suite_out.json
util/plancodec/codec.go

planner: support plan digest (#13124)

---

go.mod
go.sum
store/mockstore/mocktikv/pd.go
store/tikv/store_test.go

Cherry-pick #14008 to release-3.1 to fit with the latest code of PD 3.1

mockstore: update pd (#14008)

---

executor/builder.go
executor/index_merge_reader.go

Fix issue #14339 
- Remove the attribute `IndexMergeReader.keepOrder`
- Remove the attribute `indexMergeProcessWorker.maps`
Tests 
- Unit test
Code changes
Side effects
Release note

executor: polish the code of IndexMergeReaderExecutor

---

ddl/db_partition_test.go
domain/domain.go
domain/schema_validator.go
domain/schema_validator_test.go
go.sum
infoschema/builder.go
session/session.go
session/session_test.go
sessionctx/variable/session.go

Cherry-pick https://github.com/pingcap/tidb/pull/14235
Conflict resolved.

*: fix schema change validation for partitioned table when transaction commit (#14235)

---

config/config.go
executor/set_test.go
server/conn.go
sessionctx/variable/session.go
sessionctx/variable/sysvar.go
sessionctx/variable/tidb_vars.go
sessionctx/variable/varsutil.go
tidb-server/main.go
util/misc.go

cherry-pick #14385 to 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/14416)

*: replace conf item `pprof_sql_cpu` with srv var `tidb_pprof_sql_cpu` (#14385)

---

executor/merge_join_test.go

Mainly for https://github.com/pingcap/tidb/pull/14458.
Add a test for vectorized merge join to cover some corner cases.
Tests 
- Unit test

executor: add vectorized merge join test

---

store/tikv/gcworker/gc_worker.go

cherry-pick #14403 
conflict:
store/tikv/gcworker/gc_worker.go
store/tikv/gcworker/gc_worker_test.go

store: fix potential panic in GC worker (#14403)

---

session/session.go

session: fix incorrect OPS on unretryable session error

---

types/time_test.go

Rename local variable.
Tests 
None
Code changes
None
Side effects
None
None
Release note
None

types: rename local variable

---

server/conn.go
server/conn_stmt.go

prepare stmt is no need to re normalize and no need append args
add a new method to generate pprof label
Tests 
- Unit test
Code changes
- impl
Side effects
- n/a
Release note
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/14425)

server: refine pprof sql in prepare stmt

---

infoschema/tables.go
infoschema/tables_test.go

`TIDB_ROW_ID_SHARDING_INFO` column of `tables` table shows if the
table is sharded. Since a new sharding feature `AUTO_RANDOM` is added,
this column should be updated accordingly.
NA
Tests 
NA
NA

infoschema: update `information_schema`.`tables` to support AUTO_RANDOM.

---

plugin/audit.go
plugin/conn_ip_example/conn_ip_example.go
plugin/conn_ip_example/manifest.toml
server/server.go

cherry-pick #14594 to 2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/14622)

plugin: support logging rejected connection attempts in audit log (#14594)

---

types/convert_test.go

This is for Issue https://github.com/pingcap/tidb/issues/14612. 
Just print more info when the test failed. 
Tests 
- No code

types: add more info in test to investigate the fail cause

---

expression/builtin_cast.go
expression/expr_to_pb.go
expression/expr_to_pb_test.go
expression/integration_test.go
planner/cascades/testdata/transformation_rules_suite_out.json
store/mockstore/mocktikv/cop_handler_dag.go
types/time.go

This PR open CAST function push-down switcher fully. After this PR merged, we can enable CAST push-down integration test https://github.com/tikv/copr-test/pull/122.
**Note**: This PR should be merged with https://github.com/tikv/tikv/pull/5817 and https://github.com/tikv/copr-test/pull/122
Add CAST to push-down whitelist.
Tests 
- Unit test
Release note
- No need.

expression: fully open CAST push-down switcher

---

executor/point_get.go
kv/kv.go
sessionctx/variable/session.go
store/mockstore/mocktikv/mvcc.go
store/mockstore/mocktikv/mvcc_leveldb.go
store/mockstore/mocktikv/rpc.go
store/tikv/2pc.go
store/tikv/txn.go

Tests 
- Unit test
- No code
Code changes
- Has persistent data change
Side effects
Release note
- Write release note for bug-fix or new feature.

executor: pessimistic lock return value

---

go.mod
go.sum

fix unit test deadlock by update newest failpoint 
the newest failpoint fix a bug that lead to unit test deadlock. see https://github.com/pingcap/failpoint/pull/49.
Tests 
- Unit test
- No code

test: bump failpoint

---

store/tikv/2pc.go
store/tikv/backoff.go
store/tikv/lock_resolver.go

Make transaction-related logs more detailed debugging problems  
Tests 
- Unit test
Code changes
Side effects
Release note

server: make txn related logs more detailed

---

executor/adapter.go
executor/compiler.go

As the title says, remove some dead code about `Cacheable`, since the function call consumes CPU while the result is not used actually.
Ditto.
Tests 
- No code: successful build can guarantee the correctness.
Code changes
Side effects
N/A
N/A
Release note
N/A

executor: remove dead code about Cacheable function call

---

config/config.go
config/config_test.go
tidb-server/main.go

Reverts pingcap/tidb#14641
Some mysql_test in pingcap/tidb-test will failed.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/9513/pipeline/118/

Revert "config: check the validity of the DDL lease"

---

session/pessimistic_test.go

Cherry-pick https://github.com/pingcap/tidb/pull/14746
Release-3.0 doesn't contain large txn related code, so only the fix part is included.

session: make unit test TestOptimisticConflicts more stable #14746

---

session/pessimistic_test.go

Cherry-pick #14805 
Tests 
- No code

session: make unit test TestDeadlock more stable

---

planner/core/find_best_task.go
planner/core/point_get_plan_test.go
table/column.go

Signed-off-by: Liu Cong <liucong@pingcap.com>
Reduce the memory allocating in function FindCols
Simply switch to pre-allocating
Tests 
- Unit test
Code changes
- Simple change in the function FindCols and some gofmt result
Side effects

Reduce memory alloc in FindCols

---

executor/slow_query_test.go

Close #14866 
`TestParseSlowLogFile` changes a global variable `variable.MaxOfMaxAllowedPacket`, so it should be stayed in `SerialSuite`.
Tests 
- Unit test

executor: fix DATA RACE in TestParseSlowLogFile

---

tidb-server/main.go

Fix this error:
```
TASK [check_config_tidb : Check TiDB config] *************************************************************************
fatal: [172.16.4.224]: FAILED! => {"changed": true, "cmd": "cd /tmp/tidb_check_config && ./tidb-server -config ./tidb.toml -config-check", "delta": "0:00:00.670082", "end": "2020-02-25 12:01:23.252087", "msg": "non-zero return code", "rc": 1, "start": "2020-02-25 12:01:22.582005", "stderr": "time=\"2020-02-25T12:01:23+08:00\" level=fatal msg=\"config file ./tidb.toml contained unknown configuration options: log.file.log-rotate, pessimistic-txn.ttl\"", "stderr_lines": ["time=\"2020-02-25T12:01:23+08:00\" level=fatal msg=\"config file ./tidb.toml contained unknown configuration options: log.file.log-rotate, pessimistic-txn.ttl\""], "stdout": "", …
```

tidb-server: fix a typo

---

ddl/ddl_api.go
ddl/partition.go
table/tables/partition_test.go

cherry-pick #14295 
with conflict fixed.

ddl: avoid panic when creating partition table with unsupported expression(#14295)

---

planner/core/integration_test.go
planner/core/rule_topn_push_down.go

cherry-pick https://github.com/pingcap/tidb/pull/14927

planner: fold constant in TopN push down

---

ddl/db_test.go
ddl/partition.go
ddl/table.go

ddl: truncate table/partition should clear the table tiflash replica available status (#14872)

---

.github/ISSUE_TEMPLATE/challenge-program.md

add a issue template for challenge program
No code changes
Tests 
- No code

.github: add issue template for challenge program

---

session/bootstrap.go

`CreateGloablVariablesTable` -> `CreateGlobalVariablesTable`

session: fix mis-spell

---

executor/seqtest/prepared_test.go
expression/integration_test.go
planner/core/cache.go
planner/core/point_get_plan_test.go
planner/core/prepare_test.go
session/session.go

Fix #14723 
Tests 
- Unit test
Code changes

*: fix data race for plan cache

---

ddl/db_test.go
ddl/ddl_api.go

ddl: fix create table with like bug when refer table has tiflash replica (#14918)

---

expression/expr_to_pb.go
expression/expression.go

release 3.1: cherry pick TiFlash related PRs

---

session/pessimistic_test.go
store/mockstore/mocktikv/mvcc_leveldb.go

Force reading value doing point get a pessimistic lock, the `op_lock` record should be skipped, or the wrong value is returned, there may be error like
```
ERROR 8021 (HY000): inconsistent extra index unq_j, handle 1 not found in table
```
Add get value after `checkConflict`  operation
Tests 
- Unit test
Code changes
Side effects
Release note

mocktikv: change pessimistic lock return value skip op_lock in mocktikv

---

config/config.go
config/config.toml.example

Since TiDB and PD have already enabled dynamic config by default. TiDB also should change it.
This PR enables dynamic config by default.
Tests 
- No code
Code changes
N/A
Side effects
N/A
Release note
- enable dynamic config by default

config: enable dynamic config by default

---

.github/labeler.yml

The labeler doesn't work.
There should be a `/*` to indicate all the files inside a package.
Tests 
- Manual test (add detailed scripts or steps below): manually tested on my personal repo.
- No code

.github: correct labeler rules

---

.github/workflows/assign_project.yml

Also, assign Planner/Runtime's PRs to Kanban
Tests 
- No code

workflow: assign Planner/Runtime's PRs to Kanban

---

config/config_handler_test.go
config/config_test.go

Fix https://github.com/pingcap/tidb/issues/15330
Tests 
- Unit test

config: fix the unstable test `TestPDConfHandler`

---

util/rowcodec/encoder.go
util/rowcodec/rowcodec_test.go

fix decode panic for `Test65535Bug` test case
remove wrong became large logic 
How it Works:
remove wrong became large logic 
- Need to cherry-pick to the release branch 4.0
Tests 
- Unit test
Side effects
- n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/15404)

rowcodec: fix panic when encode MaxUint16 len data

---

infoschema/perfschema/tables.go

Format imports in tables.go
How it Works:
N/A
Tests 
N/A
Side effects
N/A
N/A

infoschema: format imports in tables

---

executor/infoschema_reader_test.go

Issue Number: close #15432 
Problem Summary: the unit test of AnalyzeStatus is not robust.
What's Changed: make the unit test of AnalyzeStatus robust
Tests 
- Unit test

infoschema: make the unit test of AnalyzeStatus robust.

---

config/config.toml.example

Update config comments.
How it Works: Replace `pkIsHandle` with a sentence that the user can understand in config.
For `alter-primary-key` configuration item description, replace` pkIsHandle` with a sentence that the user can understand.

config: update the comments of `alter-primary-key` configuration

---

ddl/serial_test.go
executor/ddl.go

cherry-pickhttps://github.com/pingcap/tidb/pull/15398/files
- support recover truncate table.

ddl: support recover truncate table (#15398)

---

executor/infoschema_reader_test.go
statistics/analyze_jobs.go

Issue Number: close #15477 
How it Works:

executor: fix AnalyzeStatus unit test data race

---

executor/builder.go
executor/infoschema_reader.go
executor/infoschema_reader_test.go
go.mod
infoschema/tables.go

implement feature #15388 
implement `sequences` view in `information_schema`;
Tests 
- Unit test
Code changes

executor: implement sequence view

---

infoschema/metric_table_def.go

Add 2 `TiKV` config metric definition.
Tests 
- No code

infoschema/perschema: add tikv config metric def

---

config/config_handler.go

Check the dynamical config and if it is not changed, don't write it back to the disk.
Tests 
- Unit test

config: don't write dynamical config to disk if there is no change

---

.github/workflows/assign_project.yml

Add the auto-assignment for project UT Coverage.
Tests 
- No code
Side effects

.github: add the auto-assignment for project UT Coverage

---

executor/memtable_reader.go
expression/expression.go

Problem Summary: As the title says.
What's Changed: ban collation expression push down to TiFlash.
Tests 
- Unit test
Side effects

expression: ban collation expression push down to TiFlash

---

executor/builder.go
executor/show_test.go

privilege: fix user with `%` hostname can not show grants. (#15825)

---

store/tikv/2pc.go
store/tikv/oracle/oracle.go
store/tikv/store_test.go

Cherry-pick #15648  to 4.0 release branch
Tests 
- Unit test
Side effects

server: failpoint for some integration tests (#15648)

---

expression/builtin_op.go
expression/builtin_op_test.go
expression/distsql_builtin.go
go.mod
go.sum

cherry-pick #10498
TiPB change: https://github.com/pingcap/tipb/pull/148
TiKV change: https://github.com/tikv/tikv/pull/7326
They should be merged at the same time.

expression: fix wrong result of `Not`/`IsTrue`/`IsFalse` functions (#10498)

---

executor/aggregate_test.go
planner/core/logical_plan_builder.go

cherry-pick #14955
fix #14947
Tests 
- Unit test
Side effects

planner: fix redundant brackets cause full group by check failed  (#14955)

---

statistics/selectivity.go
statistics/selectivity_test.go

cherry-pick https://github.com/pingcap/tidb/pull/15536

statistics: fix repetitive selectivity accounting and stabilify the result (#15536)

---

session/pessimistic_test.go
store/mockstore/mocktikv/rpc.go

Add kill lock holding session test case 
How it Works:
Tests 
- Unit test
Side effects

test: add one kill query test

---

sessionctx/variable/tidb_vars.go

Disable batch cop request by default, since this feature has not been fully tested.
Disable batch cop request by default

session: disable batch cop request by default

---

executor/inspection_result.go

Remove redundant `println`, sorry for my mistake.
Tests 
- No code
- No.

executor/inspect: remove redundant code

---

metrics/grafana/overview.json

Problem Summary: add tiflash to grafana dashboard
Tests 
- No code

monitor: add tiflash to grafana dashboard

---

store/mockstore/mocktikv/mvcc_leveldb.go
store/tikv/2pc_test.go

Check #15899 to release-4.0 manually since auto pick #15912 has conflicts 
Tests 
- Unit test
Side effects

mocktikv: fix conflict check

---

bindinfo/bind_test.go
bindinfo/cache.go
util/hint/hint_processor.go

Issue Number: close #16057  
Check if the parsed hint string is empty and parser reports warning, if yes, escalate the warning to error.
How it Works:
Tests 
- Unit test
Side effects
N/A

bindinfo: report error for completely invalid hint of bind_sql

---

util/expensivequery/expensivequerey_test.go
util/expensivequery/expensivequery.go

cherry-pick for https://github.com/pingcap/tidb/pull/12809

executor: update the memory usage format in expensive logs (#12809)

---

metrics/session.go

Cherry pick #16196 to release 3.0.

metrics: enlarge statement retry count upper limit (#16196)

---

distsql/select_result.go
distsql/stream.go
metrics/ddl.go
metrics/distsql.go
metrics/domain.go
metrics/gc_worker.go
metrics/meta.go
metrics/metrics.go
metrics/oracles.go
metrics/owner.go
metrics/server.go
metrics/session.go
metrics/stats.go
metrics/tikvclient.go

`ExponentialBuckets` uses the last bucket lower limit as the upper bound for the whole range.
Adjust some ranges and comments.
How it Works:
Tests 
- No code

metrics: adjust metrics and its comments

---

expression/integration_test.go

Try to drop the table before creating it.
Tests 
- No code
Side effects

test: fix tests which may fail because of concurrency 

---

ddl/util/syncer_test.go

Issue Number: close #14777  
enlarge timeout for test
Tests 
- No code
Side effects

test: enlarge timeout for test

---

expression/integration_test.go
go.mod
go.sum

fix parser related integration test pingcap/parser#810

go.mod: update parser for revamped special comment parser (#14389)

---

kv/key.go
kv/key_test.go

Makes handle able to be implemented in  non-int64 type in the future.
Added a `Handle` interface in the `kv` pacakge.
How it Works:
The interface abstracts the implementation, so it would be much easier to change the implementation after refactor.
- PR to update `pingcap/tidb-ansible`:
Tests 
- Unit test

kv: add Handle interface

---

domain/global_vars_cache_test.go

Issue Number: close #16598, close #16636 
The results may not be stable if the input function executes very fast
Add some sleep in the input function, so the key may not be deleted too soon and other goroutines could be scheduled
How it Works:
Tests 
- Unit test
Side effects

test: stable global var test

---

go.mod
go.sum

Issue Number: close #16700 
`parser` version in `go.mod` and `go.sum` is changed.
How it Works:
Tests 
- Unit test
Side effects

Update the version of parser

---

executor/point_get.go
session/pessimistic_test.go

The read consistency isolation level will lock only exist keys, the keys check logic is incorrect if the key is already is the pessimistic lock cache, which will cause `data inconsistency` error report
Make the `get` function work like `snapshot`.`get`, it will return `NotExist` error if the key is not found, the caller should check all the errors and decide if it should ignore the `NotExist` error 
like
```
ERROR 8021 (HY000): inconsistent extra index PRIMARY, handle 1 not found in table
```
How it Works:
Tests 
- Unit test
Side effects

txn: fix read val from lock cache from RC

---

kv/memdb/memdb.go
kv/memdb/memdb_test.go

Update https://github.com/pingcap/tidb/issues/15656.
Add more test cases.
Tests 
- Unit test

memdb: improve test coverage of memdb

---

executor/builder.go
executor/executor.go
meta/meta.go
meta/meta_test.go
structure/hash.go
util/admin/admin.go

cherry pick https://github.com/pingcap/tidb/pull/12472
No conflict file.
-- No need.

*: use iterator in show ddl jobs to avoid oom when ... (#12472)

---

ddl/serial_test.go
executor/ddl.go
server/http_handler.go
server/http_handler_test.go
util/admin/admin.go
util/admin/admin_test.go

cherry-pick https://github.com/pingcap/tidb/pull/15699
- No need.

server: add drop/truncate table tiflash replica info in /tiflash/replica http api (#15699)

---

executor/set_config.go
go.mod
go.sum
planner/core/planbuilder.go
privilege/privileges/cache_test.go
privilege/privileges/privileges_test.go
session/bootstrap.go
session/bootstrap_test.go
session/session.go

Cherry pick for https://github.com/pingcap/tidb/pull/16847.

executor, privilege: introduce a new privilege for t...(#16847)

---

executor/show.go
executor/show_test.go

Problem Summary: fix auto random base comment in `show.go`
How it Works: refine the show result iin show.go
Tests 
- Unit test
executor: fix auto random base comment in show.go

executor: fix auto random base comment in show.go

---

server/conn.go

many users complain handshake info log
let them be DEBUG level, and we can turn log level to debug when RD want to see problem dynamic.
- Need to cherry-pick to the release branch 
Tests 
- No code
Side effects
- n/a
let handshake packet read/write error log as debug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/tidb/16877)

server: make handshake packet read/write error log as debug

---

distsql/request_builder.go
distsql/request_builder_test.go
executor/admin.go
executor/batch_point_get.go
executor/builder.go
executor/delete.go
executor/distsql.go
executor/distsql_test.go
executor/executor.go
executor/index_merge_reader.go
executor/mem_reader.go
executor/point_get.go
executor/union_scan.go
executor/update.go
kv/key.go
kv/key_test.go
planner/core/common_plans.go
planner/core/find_best_task.go
planner/core/point_get_plan.go
session/txn.go
sessionctx/context.go
table/tables/tables.go
util/mock/context.go

refacor Handle in executor package for cluster index.
- add HandleMap.
- refacor Handle in executor package for cluster index.
Tests 
- Unit test

*: refactor Handle in executor package

---

session/pessimistic_test.go
store/tikv/isolation_test.go

Issue Number: close #16345 
- close #16345 
- stable this fail
```
FAIL: pessimistic_test.go:757: testPessimisticSuite.TestInnodbLockWaitTimeoutWaitStart
pessimistic_test.go:794:
c.Check(duration, LessEqual, 1100*time.Millisecond)
... compare_one time.Duration = 1116419618 ("1.116419618s")
... compare_two time.Duration = 1100000000 ("1.1s")
```
How it Works:
Tests 
- Unit test
Side effects

test: stable test cases

---

session/pessimistic_test.go
store/tikv/isolation_test.go

cherry-pick #16913 to release-4.0
Tests 
- Unit test
Side effects

test: stable test cases (#16913)

---

store/tikv/gcworker/gc_worker.go
store/tikv/gcworker/gc_worker_test.go

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
Enable green gc by default
Tests 
- No code
Side effects
Enable green GC by default.

gc_worker: enable green gc by default

---

executor/write_test.go
planner/core/cbo_test.go
planner/core/logical_plan_builder.go
planner/core/planbuilder.go

Problem Summary: return err when INSERT/UPDATE/ANALYZE/DELETE a sequence
judge table whether is a sequence when INSERT/UPDATE/ANALYSE/DELETE and return error.
Tests 
- Unit test
planner, executor: return err when INSERT/UPDATE/ANALYZE/DELETE a sequence

planner, executor: return err when INSERT/UPDATE/ANALYZE/DELETE a sequence

---

store/tikv/2pc.go
store/tikv/2pc_slow_test.go

Issue Number: close #17006 
Process pessimistic locks for 2pc pre-split logic
Check values length before access in case of pessimistic lock keys
How it Works:
Tests 
- Unit test
automated test insert into select large size
Side effects
* Fix execution fail using pessimistic mode for large transaction

txn: check values length during pre split execution

---

config/config.toml.example

The NOTE of transaction limit in config.tom.example is out of date.
Fix it.
How it Works:
Tests 
- No code

config: update NOTE of transaction limit in config.toml.example

---

domain/domain_test.go

Print stack info to investigate TestInfo leak, it will be removed later.
Print stack info in beforeTest and afterTest
Tests 
- No code
Side effects
- No Release note

domain: print stack info to investigate TestInfo leak

---

executor/builder.go
expression/builtin.go
expression/builtin_compare.go
expression/collation.go
expression/collation_test.go
expression/constant_propagation.go
expression/distsql_builtin.go
expression/expr_to_pb.go
expression/expr_to_pb_test.go
expression/integration_test.go
expression/scalar_function.go
expression/util.go
expression/util_test.go
planner/util/path.go
util/ranger/checker.go
util/ranger/detacher.go
util/ranger/points.go

Issue Number: close #17098  
Flen has not thing to do with collation. However, it may cover the previous correct Flen.
Remove flen when derives or sets the collation.
Tests 
Side effects
- Fix a bug caused by collation derivation that may cause a truncated result.

*: fix a bug which causes function return truncated result

---

store/mockstore/mocktikv/executor.go
store/mockstore/mocktikv/executor_test.go

executor: fix mocktikv panic (#15662)

---

util/profile/trackerrecorder_test.go

Fix the error  in `trackRecorderSuite.TestHeapProfileRecorder` test which would fail in CI Test with a high probability
For 7b2a48c ,I run unit-test for 5 times. 4 pass ,1 failed for unrelational test.
For more details:
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36468/pipeline
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36465/pipeline
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36463/pipeline
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36461/pipeline …

test: fix profile recorder test

---

config/config.go
config/config.toml.example
store/tikv/coprocessor_cache.go
store/tikv/coprocessor_cache_test.go

Signed-off-by: Breezewish <me@breeswish.org>
This change is to make it unified with other config items, as well as the [new documentation](https://github.com/pingcap/docs-cn/pull/2857)
What's Changed: Config files and code.
- PR to update `pingcap/docs`/`pingcap/docs-cn`: No need, already using `enable`.
Tests 
- Unit test
(Release note not needed for the hidden feature)

copr: Rename copr-cache config enabled to enable
